// Periodic work declared by state: runtime (code/__defines/sys_periodic.dm, doc/rewrite/systems.md
// section 5).
//
// Declarations are static /datum/sys_periodic_def subtypes (one per DECLARE_* line, generated by
// the macros), read once. Each also adds `add_sys_periodic()` to its type's lifecycle declaration
// table, so only declared types pay anything at materialize: finish() resolves the type's
// /datum/sys_periodic_table (its nearest while-declaration and its repeats) into
// `decls.sys_periodic`.
//
// Watching: each entity type's OM type table carries sys_periodic_mask, the union of its declared
// fields' change channels (sys_periodic_mask_for()). om_dispatch_change() re-evaluates the entity's
// declarations synchronously when one is raised: start what now holds, stop what no longer does.
// Starting only schedules (a pipeline wake, a timer), so evaluating inside a setter is safe.
// Materialize ensures the entity has an OM record (its listen mask then carries those channels)
// and evaluates once.
//
// Gate: while a type's while-declaration doesn't hold, om_task_periodic() on its cadence and
// MACHINE_WAKE() refuse to start the work, and the machine stages don't run machine_step(), so the
// body never needs to guard on the declared fields.

/// One DECLARE_PERIODIC_WHILE(_ALL) / DECLARE_REPEAT line. Instantiated once (sys_periodic_defs()).
/datum/sys_periodic_def
	/// The declaring type.
	var/of
	/// While-declaration: the periodic pipeline type, or MACHINE_PIPELINE. Null for a repeat.
	var/cadence
	/// While-declaration: the field specs as written ("name" or "!name").
	var/list/fields
	/// Repeat: the one field spec, or null (always while materialized).
	var/field
	/// Repeat: a time, or the name of a var or proc of the holder.
	var/delay
	/// Repeat: the proc name (nameof) run every `delay`.
	var/repeat_proc
	/// Resolved at build: field names, parallel negation flags, whether each is derived (a proc).
	var/list/names
	var/list/negated
	var/list/derived
	/// The union of the declared fields' change channels (what the service watches on `of`).
	var/mask = 0

/// Every declaration, instantiated and resolved once (at global init; the registry's service build reads it).
GLOBAL_LIST_INIT(sys_periodic_defs, build_sys_periodic_defs())

/proc/sys_periodic_defs()
	RETURN_TYPE(/list)
	return GLOB.sys_periodic_defs || (GLOB.sys_periodic_defs = build_sys_periodic_defs())

/proc/build_sys_periodic_defs()
	var/list/defs = list()
	for(var/path in subtypesof(/datum/sys_periodic_def))
		var/datum/sys_periodic_def/proto = path
		if(!initial(proto.of))
			continue // an intermediate path node (/datum/sys_periodic_def/obj/...)
		var/datum/sys_periodic_def/D = new path
		D.resolve()
		defs += D
	return defs

/datum/sys_periodic_def/proc/resolve()
	var/list/specs = cadence ? fields : (field ? list(field) : null)
	names = list()
	negated = list()
	derived = list()
	for(var/spec in specs)
		var/name = spec
		var/neg = FALSE
		if(copytext(spec, 1, 2) == "!")
			neg = TRUE
			name = copytext(spec, 2)
		var/list/info = sys_periodic_field_info(of, name)
		if(!info[1])
			stack_trace("sys_periodic: [of] declares periodic work on '[name]', which is not a declared field of it (OM_FIELD / OM_FLAG_FIELD / OM_FIELD_SETTER / OM_DERIVE_FIELD)")
		names += name
		negated += neg
		derived += info[2]
		mask |= info[1]

/// list(channel, derived) for field `name` of `path`: the OR of every field_def registered on
/// `path` or an ancestor (the same merge as om_registry().fields_of(), which is not available
/// yet while the registry builds its services).
/proc/sys_periodic_field_info(path, name)
	var/static/list/derived_defs
	if(!derived_defs)
		derived_defs = list()
		for(var/def_path in subtypesof(/datum/om/field_def))
			var/datum/om/field_def/F = def_path
			if(initial(F.derived))
				derived_defs += def_path
	var/is_derived = FALSE
	for(var/datum/om/field_def/F as anything in derived_defs)
		if(initial(F.field) == name && ispath(path, initial(F.of)))
			is_derived = TRUE
			break
	var/list/table = om_field_table(path)
	return list(table[name] || 0, is_derived)

/// TRUE when every field of D holds on E.
/proc/sys_periodic_def_holds(datum/E, datum/sys_periodic_def/D)
	var/list/names = D.names
	for(var/i in 1 to length(names))
		var/value = D.derived[i] ? call(E, names[i])() : E.vars[names[i]]
		if(!value != D.negated[i])
			return FALSE
	return TRUE

/// A type's resolved declarations: its nearest while-declaration and its repeats by proc name.
/datum/sys_periodic_table
	var/datum/sys_periodic_def/while_def
	/// proc name -> /datum/sys_periodic_def (the nearest declaring type wins).
	var/list/repeats

/// The declarations are boot-time singletons (sys_periodic_defs()): shared, never owned.
REGISTRY_TYPE(/datum/sys_periodic_def, GLOBAL_PROC_REF(registry_sys_periodic_def))

/proc/registry_sys_periodic_def(datum/D)
	return (D in sys_periodic_defs()) ? D : null

/// The table for `path`, or null when nothing applies (built once per type by finish()).
/proc/sys_periodic_table_for(path)
	var/datum/sys_periodic_table/T = new
	var/while_depth = -1
	var/list/repeat_depth
	for(var/datum/sys_periodic_def/D as anything in sys_periodic_defs())
		if(!ispath(path, D.of))
			continue
		var/depth = length(splittext("[D.of]", "/"))
		if(D.cadence)
			if(depth > while_depth)
				while_depth = depth
				shared_set(T, nameof(T.while_def), D)
			continue
		if(!repeat_depth)
			repeat_depth = list()
			T.repeats = list()
		if(depth > (repeat_depth[D.repeat_proc] || -1))
			repeat_depth[D.repeat_proc] = depth
			T.repeats[D.repeat_proc] = D
	if(!T.while_def && !length(T.repeats))
		return null
	return T

// ---------------------------------------------------------------- lifecycle

/// Materialize (atoms), or lifecycle_decls_init() from New() (non-atom datums): watch and evaluate.
/proc/sys_periodic_start(datum/E, datum/sys_periodic_table/T)
	if(QDELETED(E))
		return
	om_rec_of(E) // the record carries the service's listen mask for E's type
	sys_periodic_apply(E, T)

/// Dematerialize: stop the while-work; repeats are cancelled (the core also drops timers).
/proc/sys_periodic_stop(datum/E, datum/sys_periodic_table/T)
	var/datum/sys_periodic_def/W = T.while_def
	if(W)
		if(W.cadence == MACHINE_PIPELINE)
			machine_sleep(E)
		else if(E.periodic_pipe == W.cadence)
			om_task_periodic_stop(E)
	for(var/proc_name in T.repeats)
		cancel_after(E, "sys_repeat:[proc_name]")

/// Re-evaluates every declaration of E (the service's on_changes()).
/proc/sys_periodic_evaluate(datum/E)
	if(QDELETED(E))
		return
	var/datum/lifecycle_decls/decls = lifecycle_decls_of(E)
	var/datum/sys_periodic_table/T = decls?.sys_periodic
	if(T)
		sys_periodic_apply(E, T)

/proc/sys_periodic_apply(datum/E, datum/sys_periodic_table/T)
	var/datum/sys_periodic_def/W = T.while_def
	if(W)
		var/want = sys_periodic_def_holds(E, W)
		if(W.cadence == MACHINE_PIPELINE)
			var/obj/machinery/M = E
			if(M.speed_process)
				// Fast mode runs machine_step() on the fast periodic lane instead.
				if(want)
					om_task_periodic(M, PERIODIC_FAST)
				else if(M.periodic_pipe == PERIODIC_FAST)
					om_task_periodic_stop(M)
			else if(want)
				if(!M.step_active)
					machine_wake(M)
			else if(M.step_active || M.step_waiting_power)
				machine_sleep(M)
		else if(want)
			om_task_periodic(E, W.cadence)
		else if(E.periodic_pipe == W.cadence)
			om_task_periodic_stop(E)
	for(var/proc_name in T.repeats)
		var/datum/sys_periodic_def/R = T.repeats[proc_name]
		var/slot = "sys_repeat:[proc_name]"
		if(sys_periodic_def_holds(E, R))
			if(!after_pending(E, slot))
				sys_repeat_arm(E, R)
		else
			cancel_after(E, slot)

/// The gate: FALSE while E's type declares while-work on `cadence` whose fields don't hold.
/// om_task_periodic() and MACHINE_WAKE() ask it; so do the machine stages before machine_step().
/proc/sys_periodic_allows(datum/E, cadence)
	var/datum/lifecycle_decls/decls = lifecycle_decls_of(E)
	var/datum/sys_periodic_table/T = decls?.sys_periodic
	var/datum/sys_periodic_def/W = T?.while_def
	if(!W || W.cadence != cadence)
		return TRUE
	return sys_periodic_def_holds(E, W)

/// The every() gate for a manual periodic start: FALSE when `E`'s type declares type-level every(..., when = ...)
/// work (code/engine/actions/every.dm) and none of those gates holds now. The PERIODIC_WHILE -> every() codemod
/// moved the "runs only while X" rule from DECLARE_PERIODIC_WHILE into every()'s `when =`; om_task_periodic()
/// asks this so a switched-off item still can't be started by hand. Ungated every() work and capability
/// every() (an activation's) don't gate.
/proc/sys_every_allows(datum/E)
	var/datum/type_table/T = table_of(E)
	if(!T)
		return TRUE
	var/gated = FALSE
	for(var/datum/centry/C as anything in compiled_entries(T, ENTRY_EVERY))
		if(!isnull(C.owner))
			continue
		var/datum/entry/entry = C.item
		if(isnull(entry.args["when"]) && !length(C.whens))
			continue
		gated = TRUE
		if(type_every_gate(E, C))
			return TRUE
	return !gated

// ---------------------------------------------------------------- repeats

/proc/sys_repeat_arm(datum/E, datum/sys_periodic_def/R)
	var/delay = R.delay
	if(istext(delay))
		delay = (delay in E.vars) ? E.vars[delay] : call(E, delay)()
	after(E, max(delay, 0), GLOBAL_PROC_REF(sys_repeat_fire), key = "sys_repeat:[R.repeat_proc]", with = list(E, R.repeat_proc))

/proc/sys_repeat_fire(datum/E, proc_name)
	if(QDELETED(E))
		return
	var/datum/lifecycle_decls/decls = lifecycle_decls_of(E)
	var/datum/sys_periodic_table/T = decls?.sys_periodic
	var/datum/sys_periodic_def/R = T?.repeats?[proc_name]
	if(!R || !sys_periodic_def_holds(E, R))
		return
	if(call(E, proc_name)() == REPEAT_STOP)
		return
	if(QDELETED(E) || !sys_periodic_def_holds(E, R))
		return
	if(!after_pending(E, "sys_repeat:[proc_name]"))
		sys_repeat_arm(E, R)

// ---------------------------------------------------------------- the watch

/// The union of the declared fields' channels on `path` (its own and its ancestors' declarations).
/// The type table keeps it (sys_periodic_mask): om_dispatch_change() re-evaluates the entity's
/// declarations synchronously when one of them is raised, and the listen mask carries it.
/proc/sys_periodic_mask_for(path)
	. = 0
	for(var/datum/sys_periodic_def/D as anything in sys_periodic_defs())
		if(ispath(path, D.of))
			. |= D.mask

/// finish()'s check against the first instance: every field is a var (or a derived field's proc)
/// of it, every repeat proc exists. A bad declaration is reported once and dropped.
/proc/sys_periodic_validated(datum/D, datum/sys_periodic_table/T)
	if(!T)
		return null
	if(T.while_def && !sys_periodic_def_valid(D, T.while_def))
		shared_set(T, nameof(T.while_def), null)
	for(var/proc_name in T.repeats?.Copy())
		var/datum/sys_periodic_def/R = T.repeats[proc_name]
		if(!hascall(D, proc_name))
			stack_trace("DECLARE_REPEAT([R.of]): no proc [proc_name]; dropped")
			T.repeats -= proc_name
		else if(!sys_periodic_def_valid(D, R))
			T.repeats -= proc_name
	if(!length(T.repeats))
		T.repeats = null
	if(!T.while_def && !T.repeats)
		return null
	return T

/proc/sys_periodic_def_valid(datum/D, datum/sys_periodic_def/R)
	for(var/i in 1 to length(R.names))
		var/name = R.names[i]
		if(R.derived[i] ? !hascall(D, name) : !(name in D.vars))
			stack_trace("sys_periodic: [R.of] declares periodic work on '[name]', which [D.type] has no var or derived proc for; dropped")
			return FALSE
	return TRUE
