// Auto-generated stubs for orphaned types after removing map includes.
// Each is an empty type definition just so code that references it compiles.
// No actual content; the original definitions lived in removed map files.

/area/ai_core_foyer
/area/groundbase/level1/centsquare
/area/groundbase/level1/eastspur
/area/groundbase/level1/northspur
/area/groundbase/level1/southeastspur
/area/groundbase/level1/southwestspur
/area/groundbase/level1/westspur
/area/groundbase/level2/eastspur
/area/groundbase/level2/ne
/area/groundbase/level2/northspur
/area/groundbase/level2/nw
/area/groundbase/level2/se
/area/groundbase/level2/southeastspur
/area/groundbase/level2/southwestspur
/area/groundbase/level2/sw
/area/groundbase/level2/westspur
/area/groundbase/level3/escapepad
/area/groundbase/level3/ne
/area/groundbase/level3/ne/open
/area/groundbase/level3/nw
/area/groundbase/level3/nw/open
/area/groundbase/level3/se
/area/groundbase/level3/se/open
/area/groundbase/level3/sw
/area/groundbase/level3/sw/open
/area/hallway/station/upper
/area/maintenance/groundbase/level1/netunnel
/area/maintenance/groundbase/level1/nwtunnel
/area/maintenance/groundbase/level1/setunnel
/area/maintenance/groundbase/level1/stunnel
/area/maintenance/groundbase/level1/swtunnel
/area/shuttle/sdboat
/area/submap/event
/obj/item/bluespace_harpoon/wand
/obj/item/clothing/accessory/storage/webbing/pilot1
/obj/item/clothing/accessory/storage/webbing/pilot2
/obj/item/clothing/gloves/bluespace/magic
/obj/item/clothing/suit/storage/toggle/bomber/pilot
/obj/item/clothing/under/rank/pilot1
/obj/item/clothing/under/rank/pilot1/no_webbing
/obj/item/clothing/under/rank/pilot2
/obj/item/gun/energy/taser/magic
/obj/item/healthanalyzer/scroll
/obj/item/perfect_tele/magic
/obj/item/slow_sizegun/magic
/obj/item/surgical/bone_clamp/alien/magic
/obj/item/tool/crowbar/alien/magic
/obj/item/tool/screwdriver/alien/magic
/obj/item/tool/wirecutters/alien/magic
/obj/item/tool/wrench/alien/magic
/obj/item/weldingtool/alien/magic
