// Counted volleys (random, quad random, gattling, cutoff): the entry procs below keep their old
// signatures (callers after() them) and start the volley; the declared repeat fires the rest
// every volley_fire_delay while shots remain, then moves on to the volley's next attack cycle.
#define ECLIPSE_VOLLEY_RANDOM 1
#define ECLIPSE_VOLLEY_QUAD_RANDOM 2
#define ECLIPSE_VOLLEY_GATTLING 3
#define ECLIPSE_VOLLEY_CUTOFF 4
#define ECLIPSE_VOLLEY_CUTOFF_ULTI 5

/// Shots left in the current counted volley. A field: the volley repeats while it is non-zero.
OM_FIELD(/mob/living/simple_mob/mechanical/mecha/eclipse, volley_shots_left, 0, CHANGE_MOB_CONDITIONS)
/mob/living/simple_mob/mechanical/mecha/eclipse/var/volley_kind
/// What the current volley is fired at (a relation view).
/mob/living/simple_mob/mechanical/mecha/eclipse/var/atom/volley_target
/mob/living/simple_mob/mechanical/mecha/eclipse/var/volley_next_cycle
/mob/living/simple_mob/mechanical/mecha/eclipse/var/volley_fire_delay = 0
DECLARE_REPEAT(/mob/living/simple_mob/mechanical/mecha/eclipse, "volley_fire_delay", volley_step, "volley_shots_left")

/// Starts a counted volley: the first shot now, the rest on the declared repeat.
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/start_volley(kind, atom/target, amount, next_cycle, fire_delay)
	volley_kind = kind
	rel_set(src, nameof(volley_target), target)
	volley_next_cycle = next_cycle
	volley_fire_delay = fire_delay
	set_volley_shots_left(amount)
	volley_step()

/// DECLARE_REPEAT while shots remain: one shot of the current volley.
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/volley_step()
	var/atom/target = volley_target
	if(!target)
		set_volley_shots_left(0)
		return REPEAT_STOP
	switch(volley_kind)
		if(ECLIPSE_VOLLEY_RANDOM)
			bullet_heck(target, rand(-7,7), rand(-7,7))
		if(ECLIPSE_VOLLEY_QUAD_RANDOM)
			var/rngx = rand(-7,7)
			var/rngy = rand(-7,7)
			var/rngxx = rand(-7,7)
			var/rngyy = rand(-7,7)
			bullet_heck(target, rngx, rngy)
			bullet_heck(target, rngxx, rngyy)
			bullet_heck(target, rngxx, rngy)
			bullet_heck(target, rngx, rngyy)
		if(ECLIPSE_VOLLEY_GATTLING)
			var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
			P.launch_projectile(target, BP_TORSO, src)
		if(ECLIPSE_VOLLEY_CUTOFF)
			bullet_heck(target, 7, 0)
			bullet_heck(target, -7, 0)
			bullet_heck(target, 0, 7)
			bullet_heck(target, 0, -7)
		if(ECLIPSE_VOLLEY_CUTOFF_ULTI)
			bullet_heck(target, 7, 0)
			bullet_heck(target, -7, 0)
			bullet_heck(target, 0, 7)
			bullet_heck(target, 0, -7)
			bullet_heck(target, 7, 7)
			bullet_heck(target, -7, -7)
			bullet_heck(target, -7, 7)
			bullet_heck(target, 7, -7)
	set_volley_shots_left(volley_shots_left - 1)
	if(volley_shots_left <= 0)
		attackcycle = volley_next_cycle
		return REPEAT_STOP


/mob/living/simple_mob/mechanical/mecha/eclipse/proc/singleproj(atom/target, next_cycle)
	if(!target)
		return
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	P.launch_projectile(target, BP_TORSO, src)
	attackcycle = next_cycle


/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bullet_heck(atom/target, horix, vertiy) //horix is the X vaule, vertix is the Y vaule
	var/obj/item/projectile/P = new specialattackprojectile(get_turf(src))
	var/turf = locate(src.x+horix, src.y+vertiy, src.z)
	target = turf
	P.launch_projectile(target, BP_TORSO, src)

//spinny dual blades
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spin(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 0, 7)
	bullet_heck(target, -7, 0)
	bullet_heck(target, 7, 0)
	after(src, fire_delay, PROC_REF(dual_spinA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -1, -7)
	bullet_heck(target, 1, 7)
	bullet_heck(target, -7, 1)
	bullet_heck(target, 7, -1)
	after(src, fire_delay, PROC_REF(dual_spinB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -2, -7)
	bullet_heck(target, 2, 7)
	bullet_heck(target, -7, 2)
	bullet_heck(target, 7, -2)
	after(src, fire_delay, PROC_REF(dual_spinC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinC(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -3, -7)
	bullet_heck(target, 3, 7)
	bullet_heck(target, -7, 3)
	bullet_heck(target, 7, -3)
	after(src, fire_delay, PROC_REF(dual_spinD), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinD(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -4, -7)
	bullet_heck(target, 4, 7)
	bullet_heck(target, -7, 4)
	bullet_heck(target, 7, -4)
	after(src, fire_delay, PROC_REF(dual_spinE), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinE(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -5, -7)
	bullet_heck(target, 5, 7)
	bullet_heck(target, -7, 5)
	bullet_heck(target, 7, -5)
	after(src, fire_delay, PROC_REF(dual_spinF), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinF(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -6, -7)
	bullet_heck(target, 6, 7)
	bullet_heck(target, -7, 6)
	bullet_heck(target, 7, -6)
	after(src, fire_delay, PROC_REF(dual_spinG), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinG(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -7)
	bullet_heck(target, 7, 7)
	bullet_heck(target, -7, 7)
	bullet_heck(target, 7, -7)
	after(src, fire_delay, PROC_REF(dual_spinH), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinH(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -6)
	bullet_heck(target, 7, 6)
	bullet_heck(target, -6, 7)
	bullet_heck(target, 6, -7)
	after(src, fire_delay, PROC_REF(dual_spinI), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinI(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -5)
	bullet_heck(target, 7, 5)
	bullet_heck(target, -5, 7)
	bullet_heck(target, 5, -7)
	after(src, fire_delay, PROC_REF(dual_spinJ), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinJ(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -4)
	bullet_heck(target, 7, 4)
	bullet_heck(target, -4, 7)
	bullet_heck(target, 4, -7)
	after(src, fire_delay, PROC_REF(dual_spinK), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinK(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -3)
	bullet_heck(target, 7, 3)
	bullet_heck(target, -3, 7)
	bullet_heck(target, 3, -7)
	after(src, fire_delay, PROC_REF(dual_spinL), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinL(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -2)
	bullet_heck(target, 7, 2)
	bullet_heck(target, -2, 7)
	bullet_heck(target, 2, -7)
	after(src, fire_delay, PROC_REF(dual_spinM), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinM(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -1)
	bullet_heck(target, 7, 1)
	bullet_heck(target, -1, 7)
	bullet_heck(target, 1, -7)
	after(src, fire_delay, PROC_REF(dual_spinN), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_spinN(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 0)
	bullet_heck(target, 7, 0)
	bullet_heck(target, 0, 7)
	bullet_heck(target, 0, -7)
	if(prob(50)) //coin flip to reverse
		after(src, fire_delay, PROC_REF(fdual_spin), with = list(target, next_cycle, fire_delay))
	else
		after(src, fire_delay, PROC_REF(rdual_spin), with = list(target, next_cycle, fire_delay))

//the four spin finish
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spin(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 1)
	bullet_heck(target, 7, -1)
	bullet_heck(target, 1, 7)
	bullet_heck(target, -1, -7)
	after(src, fire_delay, PROC_REF(fdual_spinA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 2)
	bullet_heck(target, 7, -2)
	bullet_heck(target, 2, 7)
	bullet_heck(target, -2, -7)
	after(src, fire_delay, PROC_REF(fdual_spinB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 3)
	bullet_heck(target, 7, -3)
	bullet_heck(target, 3, 7)
	bullet_heck(target, -3, -7)
	after(src, fire_delay, PROC_REF(fdual_spinC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinC(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 4)
	bullet_heck(target, 7, -4)
	bullet_heck(target, 4, 7)
	bullet_heck(target, -4, -7)
	after(src, fire_delay, PROC_REF(fdual_spinD), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinD(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 5)
	bullet_heck(target, 7, -5)
	bullet_heck(target, 5, 7)
	bullet_heck(target, -5, -7)
	after(src, fire_delay, PROC_REF(fdual_spinE), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinE(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 6)
	bullet_heck(target, 7, -6)
	bullet_heck(target, 6, 7)
	bullet_heck(target, -6, -7)
	after(src, fire_delay, PROC_REF(fdual_spinF), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinF(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 7)
	bullet_heck(target, 7, -7)
	bullet_heck(target, 7, 7)
	bullet_heck(target, -7, -7)
	after(src, fire_delay, PROC_REF(fdual_spinG), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinG(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -6, 7)
	bullet_heck(target, 6, -7)
	bullet_heck(target, 7, 6)
	bullet_heck(target, -7, -6)
	after(src, fire_delay, PROC_REF(fdual_spinH), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinH(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -5, 7)
	bullet_heck(target, 5, -7)
	bullet_heck(target, 7, 5)
	bullet_heck(target, -7, -5)
	after(src, fire_delay, PROC_REF(fdual_spinI), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinI(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -4, 7)
	bullet_heck(target, 4, -7)
	bullet_heck(target, 7, 4)
	bullet_heck(target, -7, -4)
	after(src, fire_delay, PROC_REF(fdual_spinJ), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinJ(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -3, 7)
	bullet_heck(target, 3, -7)
	bullet_heck(target, 7, 3)
	bullet_heck(target, -7, -3)
	after(src, fire_delay, PROC_REF(fdual_spinK), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinK(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -2, 7)
	bullet_heck(target, 2, -7)
	bullet_heck(target, 7, 2)
	bullet_heck(target, -7, -2)
	after(src, fire_delay, PROC_REF(fdual_spinL), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinL(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -1, 7)
	bullet_heck(target, 1, -7)
	bullet_heck(target, 7, 1)
	bullet_heck(target, -7, -1)
	after(src, fire_delay, PROC_REF(fdual_spinM), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fdual_spinM(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 0, 7)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 7, 0)
	bullet_heck(target, -7, -0)
	attackcycle = next_cycle

//the reverse
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinM(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 0, 7)
	bullet_heck(target, 7, 0)
	bullet_heck(target, -7, 0)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinL(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -1, -7)
	bullet_heck(target, 1, 7)
	bullet_heck(target, 7, -1)
	bullet_heck(target, -7, 1)
	after(src, fire_delay, PROC_REF(rdual_spinM), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinK(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -2, -7)
	bullet_heck(target, 2, 7)
	bullet_heck(target, 7, -2)
	bullet_heck(target, -7, 2)
	after(src, fire_delay, PROC_REF(rdual_spinL), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinJ(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -3, -7)
	bullet_heck(target, 3, 7)
	bullet_heck(target, 7, -3)
	bullet_heck(target, -7, 3)
	after(src, fire_delay, PROC_REF(rdual_spinK), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinI(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -4, -7)
	bullet_heck(target, 4, 7)
	bullet_heck(target, 7, -4)
	bullet_heck(target, -7, 4)
	after(src, fire_delay, PROC_REF(rdual_spinJ), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinH(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -5, -7)
	bullet_heck(target, 5, 7)
	bullet_heck(target, 7, -5)
	bullet_heck(target, -7, 5)
	after(src, fire_delay, PROC_REF(rdual_spinI), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinG(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -6, -7)
	bullet_heck(target, 6, 7)
	bullet_heck(target, 7, -6)
	bullet_heck(target, -7, 6)
	after(src, fire_delay, PROC_REF(rdual_spinH), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinF(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -7)
	bullet_heck(target, 7, 7)
	bullet_heck(target, 7, -7)
	bullet_heck(target, -7, 7)
	after(src, fire_delay, PROC_REF(rdual_spinG), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinE(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -6)
	bullet_heck(target, 7, 6)
	bullet_heck(target, 6, -7)
	bullet_heck(target, -6, 7)
	after(src, fire_delay, PROC_REF(rdual_spinF), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinD(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -5)
	bullet_heck(target, 7, 5)
	bullet_heck(target, 5, -7)
	bullet_heck(target, -5, 7)
	after(src, fire_delay, PROC_REF(rdual_spinE), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinC(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -4)
	bullet_heck(target, 7, 4)
	bullet_heck(target, 4, -7)
	bullet_heck(target, -4, 7)
	after(src, fire_delay, PROC_REF(rdual_spinD), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -3)
	bullet_heck(target, 7, 3)
	bullet_heck(target, 3, -7)
	bullet_heck(target, -3, 7)
	after(src, fire_delay, PROC_REF(rdual_spinC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spinA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -2)
	bullet_heck(target, 7, 2)
	bullet_heck(target, 2, -7)
	bullet_heck(target, -2, 7)
	after(src, fire_delay, PROC_REF(rdual_spinB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rdual_spin(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -1)
	bullet_heck(target, 7, 1)
	bullet_heck(target, 1, -7)
	bullet_heck(target, -1, 7)
	after(src, fire_delay, PROC_REF(rdual_spinA), with = list(target, next_cycle, fire_delay))

//two spinning blade
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spin(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 0, 7)
	after(src, fire_delay, PROC_REF(cross_spinA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -1, -7)
	bullet_heck(target, 1, 7)
	after(src, fire_delay, PROC_REF(cross_spinB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -2, -7)
	bullet_heck(target, 2, 7)
	after(src, fire_delay, PROC_REF(cross_spinC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinC(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -3, -7)
	bullet_heck(target, 3, 7)
	after(src, fire_delay, PROC_REF(cross_spinD), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinD(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -4, -7)
	bullet_heck(target, 4, 7)
	after(src, fire_delay, PROC_REF(cross_spinE), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinE(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -5, -7)
	bullet_heck(target, 5, 7)
	after(src, fire_delay, PROC_REF(cross_spinF), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinF(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -6, -7)
	bullet_heck(target, 6, 7)
	after(src, fire_delay, PROC_REF(cross_spinG), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinG(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -7)
	bullet_heck(target, 7, 7)
	after(src, fire_delay, PROC_REF(cross_spinH), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinH(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -6)
	bullet_heck(target, 7, 6)
	after(src, fire_delay, PROC_REF(cross_spinI), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinI(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -5)
	bullet_heck(target, 7, 5)
	after(src, fire_delay, PROC_REF(cross_spinJ), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinJ(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -4)
	bullet_heck(target, 7, 4)
	after(src, fire_delay, PROC_REF(cross_spinK), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinK(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -3)
	bullet_heck(target, 7, 3)
	after(src, fire_delay, PROC_REF(cross_spinL), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinL(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -2)
	bullet_heck(target, 7, 2)
	after(src, fire_delay, PROC_REF(cross_spinM), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinM(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -1)
	bullet_heck(target, 7, 1)
	after(src, fire_delay, PROC_REF(cross_spinN), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cross_spinN(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 0)
	bullet_heck(target, 7, 0)
	if(prob(50)) //coin flip to reverse
		after(src, fire_delay, PROC_REF(fcross_spin), with = list(target, next_cycle, fire_delay))
	else
		after(src, fire_delay, PROC_REF(rcross_spin), with = list(target, next_cycle, fire_delay))

//the dual spin finish
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spin(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 1)
	bullet_heck(target, 7, -1)
	after(src, fire_delay, PROC_REF(fcross_spinA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 2)
	bullet_heck(target, 7, -2)
	after(src, fire_delay, PROC_REF(fcross_spinB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 3)
	bullet_heck(target, 7, -3)
	after(src, fire_delay, PROC_REF(fcross_spinC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinC(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 4)
	bullet_heck(target, 7, -4)
	after(src, fire_delay, PROC_REF(fcross_spinD), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinD(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 5)
	bullet_heck(target, 7, -5)
	after(src, fire_delay, PROC_REF(fcross_spinE), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinE(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 6)
	bullet_heck(target, 7, -6)
	after(src, fire_delay, PROC_REF(fcross_spinF), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinF(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 7)
	bullet_heck(target, 7, -7)
	after(src, fire_delay, PROC_REF(fcross_spinG), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinG(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -6, 7)
	bullet_heck(target, 6, -7)
	after(src, fire_delay, PROC_REF(fcross_spinH), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinH(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -5, 7)
	bullet_heck(target, 5, -7)
	after(src, fire_delay, PROC_REF(fcross_spinI), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinI(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -4, 7)
	bullet_heck(target, 4, -7)
	after(src, fire_delay, PROC_REF(fcross_spinJ), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinJ(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -3, 7)
	bullet_heck(target, 3, -7)
	after(src, fire_delay, PROC_REF(fcross_spinK), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinK(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -2, 7)
	bullet_heck(target, 2, -7)
	after(src, fire_delay, PROC_REF(fcross_spinL), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinL(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -1, 7)
	bullet_heck(target, 1, -7)
	after(src, fire_delay, PROC_REF(fcross_spinM), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/fcross_spinM(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 0, 7)
	bullet_heck(target, 0, -7)
	attackcycle = next_cycle

//the dual spin reverse
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinM(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 0, 7)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinL(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -1, -7)
	bullet_heck(target, 1, 7)
	after(src, fire_delay, PROC_REF(rcross_spinM), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinK(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -2, -7)
	bullet_heck(target, 2, 7)
	after(src, fire_delay, PROC_REF(rcross_spinL), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinJ(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -3, -7)
	bullet_heck(target, 3, 7)
	after(src, fire_delay, PROC_REF(rcross_spinK), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinI(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -4, -7)
	bullet_heck(target, 4, 7)
	after(src, fire_delay, PROC_REF(rcross_spinJ), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinH(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -5, -7)
	bullet_heck(target, 5, 7)
	after(src, fire_delay, PROC_REF(rcross_spinI), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinG(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -6, -7)
	bullet_heck(target, 6, 7)
	after(src, fire_delay, PROC_REF(rcross_spinH), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinF(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -7)
	bullet_heck(target, 7, 7)
	after(src, fire_delay, PROC_REF(rcross_spinG), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinE(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -6)
	bullet_heck(target, 7, 6)
	after(src, fire_delay, PROC_REF(rcross_spinF), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinD(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -5)
	bullet_heck(target, 7, 5)
	after(src, fire_delay, PROC_REF(rcross_spinE), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinC(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -4)
	bullet_heck(target, 7, 4)
	after(src, fire_delay, PROC_REF(rcross_spinD), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -3)
	bullet_heck(target, 7, 3)
	after(src, fire_delay, PROC_REF(rcross_spinC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spinA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -2)
	bullet_heck(target, 7, 2)
	after(src, fire_delay, PROC_REF(rcross_spinB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rcross_spin(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -1)
	bullet_heck(target, 7, 1)
	after(src, fire_delay, PROC_REF(rcross_spinA), with = list(target, next_cycle, fire_delay))
//bursts attack
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/burst_one(atom/target)
	bullet_heck(target, 0, -1)
	bullet_heck(target, 0, 1)
	bullet_heck(target, 1, 0)
	bullet_heck(target, -1, 0)
	bullet_heck(target, 1, -1)
	bullet_heck(target, -1, -1)
	bullet_heck(target, 1, 1)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/burst_two(atom/target)
	bullet_heck(target, 0, -2)
	bullet_heck(target, 1, -2)
	bullet_heck(target, 2, -2)
	bullet_heck(target, -1, -2)
	bullet_heck(target, -2, -2)
	bullet_heck(target, 0, 2)
	bullet_heck(target, 1, 2)
	bullet_heck(target, 2, 2)
	bullet_heck(target, 2, 1)
	bullet_heck(target, 2, 0)
	bullet_heck(target, 2, -1)
	bullet_heck(target, 2, -2)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/burst_three(atom/target)
	bullet_heck(target, 0, -3)
	bullet_heck(target, 1, -3)
	bullet_heck(target, 2, -3)
	bullet_heck(target, 3, -3)
	bullet_heck(target, -1, -3)
	bullet_heck(target, -2, -3)
	bullet_heck(target, -3, -3)
	bullet_heck(target, 3, 0)
	bullet_heck(target, 3, 1)
	bullet_heck(target, 3, 2)
	bullet_heck(target, 3, 3)
	bullet_heck(target, 3, -1)
	bullet_heck(target, 3, -2)
	bullet_heck(target, 3, -3)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/burst_four(atom/target)
	bullet_heck(target, 0, -4)
	bullet_heck(target, 1, -4)
	bullet_heck(target, 2, -4)
	bullet_heck(target, 3, -4)
	bullet_heck(target, 4, -4)
	bullet_heck(target, 4, -3)
	bullet_heck(target, 4, -2)
	bullet_heck(target, 4, -1)
	bullet_heck(target, 4, 0)
	bullet_heck(target, 4, 1)
	bullet_heck(target, 4, 2)
	bullet_heck(target, 4, 3)
	bullet_heck(target, 4, 4)
	bullet_heck(target, 3, 4)
	bullet_heck(target, 2, 4)
	bullet_heck(target, 1, 4)
	bullet_heck(target, 0, 4)
	bullet_heck(target, -1, 4)
	bullet_heck(target, -2, 4)
	bullet_heck(target, -3, 4)
	bullet_heck(target, -4, 4)
	bullet_heck(target, -4, 3)
	bullet_heck(target, -4, 2)
	bullet_heck(target, -4, 1)
	bullet_heck(target, -4, 0)
	bullet_heck(target, -4, -1)
	bullet_heck(target, -4, -2)
	bullet_heck(target, -4, -3)
	bullet_heck(target, -4, -4)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/checker_board(atom/target, next_cycle)
	bullet_heck(target, -1, 1)
	bullet_heck(target, 1, 1)
	bullet_heck(target, 1, -1)
	bullet_heck(target, -1, -1)
	bullet_heck(target, 0, 2)
	bullet_heck(target, 0, -2)
	bullet_heck(target, 2, 0)
	bullet_heck(target, -2, 0)
	bullet_heck(target, -2, 2)
	bullet_heck(target, 2, 2)
	bullet_heck(target, 2, -2)
	bullet_heck(target, -2, -2)
	bullet_heck(target, -3, 1)
	bullet_heck(target, -3, -1)
	bullet_heck(target, 3, 1)
	bullet_heck(target, 3, -1)
	bullet_heck(target, 1, 3)
	bullet_heck(target, -1, 3)
	bullet_heck(target, 1, -3)
	bullet_heck(target, -1, -3)
	bullet_heck(target, -3, 3)
	bullet_heck(target, 3, 3)
	bullet_heck(target, 3, -3)
	bullet_heck(target, -3, -3)
	attackcycle = next_cycle


/mob/living/simple_mob/mechanical/mecha/eclipse/proc/chain_burst(atom/target, next_cycle, fire_delay)
	burst_one(target)
	after(src, fire_delay, PROC_REF(chain_burstA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/chain_burstA(atom/target, next_cycle, fire_delay)
	burst_two(target)
	after(src, fire_delay, PROC_REF(chain_burstB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/chain_burstB(atom/target, next_cycle, fire_delay)
	burst_three(target)
	after(src, fire_delay, PROC_REF(chain_burstC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/chain_burstC(atom/target, next_cycle, fire_delay)
	burst_four(target)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/dual_burst(atom/target, next_cycle)
	burst_two(target)
	burst_four(target)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/giant_burst(atom/target, next_cycle)
	burst_four(target)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/star_burst(atom/target, next_cycle)
	bullet_heck(target, 0, 7)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 7, 7)
	bullet_heck(target, -7, 7)
	bullet_heck(target, -7, -7)
	bullet_heck(target, 7, -7)
	bullet_heck(target, -7, 0)
	bullet_heck(target, 7, 0)
	attackcycle = next_cycle

//random
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/random_firing(atom/target, amount, next_cycle, fire_delay)
	start_volley(ECLIPSE_VOLLEY_RANDOM, target, amount, next_cycle, fire_delay)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/quad_random_firing(atom/target, amount, next_cycle, fire_delay)
	start_volley(ECLIPSE_VOLLEY_QUAD_RANDOM, target, amount, next_cycle, fire_delay)

//perscion
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/hole_in_wall(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -7)
	bullet_heck(target, -7, -6)
	bullet_heck(target, -7, -5)
	bullet_heck(target, -7, -4)
	bullet_heck(target, -6, -7)
	bullet_heck(target, -5, -7)
	bullet_heck(target, -4, -7)
	bullet_heck(target, 7, -7)
	bullet_heck(target, 6, -7)
	bullet_heck(target, 5, -7)
	bullet_heck(target, 4, -7)
	bullet_heck(target, 7, -6)
	bullet_heck(target, 7, -5)
	bullet_heck(target, 7, -4)
	bullet_heck(target, 7, 7)
	bullet_heck(target, 7, 6)
	bullet_heck(target, 7, 5)
	bullet_heck(target, 7, 4)
	bullet_heck(target, 6, 7)
	bullet_heck(target, 5, 7)
	bullet_heck(target, 4, 7)
	bullet_heck(target, -7, 7)
	bullet_heck(target, -7, 6)
	bullet_heck(target, -7, 5)
	bullet_heck(target, -7, 4)
	bullet_heck(target, -6, 7)
	bullet_heck(target, -5, 7)
	bullet_heck(target, -4, 7)
	after(src, fire_delay, PROC_REF(hole_in_wallA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/hole_in_wallA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -4)
	bullet_heck(target, -7, -3)
	bullet_heck(target, -7, -2)
	bullet_heck(target, -7, -1)
	bullet_heck(target, -7, 0)
	bullet_heck(target, -7, 1)
	bullet_heck(target, -7, 2)
	bullet_heck(target, -7, 3)
	bullet_heck(target, -7, 4)
	bullet_heck(target, -4, -7)
	bullet_heck(target, -3, -7)
	bullet_heck(target, -2, -7)
	bullet_heck(target, -1, -7)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 1, -7)
	bullet_heck(target, 2, -7)
	bullet_heck(target, 3, -7)
	bullet_heck(target, 4, -7)
	bullet_heck(target, 4, 7)
	bullet_heck(target, 3, 7)
	bullet_heck(target, 2, 7)
	bullet_heck(target, 1, 7)
	bullet_heck(target, 0, 7)
	bullet_heck(target, -1, 7)
	bullet_heck(target, -2, 7)
	bullet_heck(target, -3, 7)
	bullet_heck(target, -4, 7)
	bullet_heck(target, 7, -4)
	bullet_heck(target, 7, -3)
	bullet_heck(target, 7, -2)
	bullet_heck(target, 7, -1)
	bullet_heck(target, 7, 0)
	bullet_heck(target, 7, 1)
	bullet_heck(target, 7, 2)
	bullet_heck(target, 7, 3)
	bullet_heck(target, 7, 4)
	after(src, fire_delay, PROC_REF(hole_in_wallB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/hole_in_wallB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, -7)
	bullet_heck(target, -7, -6)
	bullet_heck(target, -7, -5)
	bullet_heck(target, -7, -4)
	bullet_heck(target, -6, -7)
	bullet_heck(target, -5, -7)
	bullet_heck(target, -4, -7)
	bullet_heck(target, 7, -7)
	bullet_heck(target, 6, -7)
	bullet_heck(target, 5, -7)
	bullet_heck(target, 4, -7)
	bullet_heck(target, 7, -6)
	bullet_heck(target, 7, -5)
	bullet_heck(target, 7, -4)
	bullet_heck(target, 7, 7)
	bullet_heck(target, 7, 6)
	bullet_heck(target, 7, 5)
	bullet_heck(target, 7, 4)
	bullet_heck(target, 6, 7)
	bullet_heck(target, 5, 7)
	bullet_heck(target, 4, 7)
	bullet_heck(target, -7, 7)
	bullet_heck(target, -7, 6)
	bullet_heck(target, -7, 5)
	bullet_heck(target, -7, 4)
	bullet_heck(target, -6, 7)
	bullet_heck(target, -5, 7)
	bullet_heck(target, -4, 7)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bomb_lines(atom/A, next_cycle)
	if(!A)
		return
	var/list/potential_targets = ai_brain.list_targets()
	for(var/atom/entry in potential_targets)
		if(istype(entry, /mob/living/simple_mob/mechanical/mecha/eclipse))
			potential_targets -= entry
	if(potential_targets.len)
		var/iteration = clamp(potential_targets.len, 1, 3)
		for(var/i = 0, i < iteration, i++)
			if(!(potential_targets.len))
				break
			var/mob/target = pick(potential_targets)
			potential_targets -= target
			spawn_lines(target, next_cycle)


/mob/living/simple_mob/mechanical/mecha/eclipse/proc/spawn_lines(atom/target, next_cycle)
	var/alignment = rand(1,2)	// 1 for vertical, 2 for horizontal
	var/list/line_range = list()
	var/turf/T = get_turf(target)
	line_range += T
	for(var/i = 1, i <= 7, i++)
		switch(alignment)
			if(1)
				if(T.x-i > 0)
					line_range += locate(T.x-i, T.y-i, T.z)
				if(T.x+i <= world.maxx)
					line_range += locate(T.x+i, T.y+i, T.z)
				if(T.y-i > 0)
					line_range += locate(T.x+i, T.y-i, T.z)
				if(T.y+i <= world.maxy)
					line_range += locate(T.x-i, T.y+i, T.z)
			if(2)
				if(T.x-i > 0)
					line_range += locate(T.x-i, T.y, T.z)
				if(T.x+i <= world.maxx)
					line_range += locate(T.x+i, T.y, T.z)
				if(T.y-i > 0)
					line_range += locate(T.x, T.y-i, T.z)
				if(T.y+i <= world.maxy)
					line_range += locate(T.x, T.y+i, T.z)
	for(var/turf/dropspot in line_range)
		new artidrop(dropspot)
	attackcycle = next_cycle



/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bomb_chaos(atom/A, next_cycle)
	if(!A)
		return
	var/list/potential_targets = ai_brain.list_targets()
	for(var/atom/entry in potential_targets)
		if(istype(entry, /mob/living/simple_mob/mechanical/mecha/eclipse))
			potential_targets -= entry
	if(potential_targets.len)
		var/iteration = clamp(potential_targets.len, 1, 3)
		for(var/i = 0, i < iteration, i++)
			if(!(potential_targets.len))
				break
			var/mob/target = pick(potential_targets)
			potential_targets -= target
			chaos_lines(target, next_cycle)


/mob/living/simple_mob/mechanical/mecha/eclipse/proc/chaos_lines(atom/target, next_cycle)
	var/alignment = rand(1,2)
	var/list/line_range = list()
	var/turf/T = get_turf(target)
	line_range += T
	for(var/i = 1, i <= 7, i++)
		switch(alignment)
			if(1)
				if(T.x-i > 0)
					var/zed = rand(1,3)
					line_range += locate(T.x+zed, T.y-i, T.z)
				if(T.x+i <= world.maxx)
					var/zed = rand(1,3)
					line_range += locate(T.x+zed, T.y+i, T.z)
				if(T.y-i > 0)
					var/zed = rand(1,3)
					line_range += locate(T.x+i, T.y+zed, T.z)
				if(T.y+i <= world.maxy)
					var/zed = rand(1,3)
					line_range += locate(T.x-i, T.y+zed, T.z)
			if(2)
				if(T.x-i > 0)
					var/zed = rand(1,3)
					line_range += locate(T.x-i, T.y-zed, T.z)
				if(T.x+i <= world.maxx)
					var/zed = rand(1,3)
					line_range += locate(T.x+i, T.y-zed, T.z)
				if(T.y-i > 0)
					var/zed = rand(1,3)
					line_range += locate(T.x-zed, T.y-i, T.z)
				if(T.y+i <= world.maxy)
					var/zed = rand(1,3)
					line_range += locate(T.x-zed, T.y+i, T.z)
	for(var/turf/dropspot in line_range)
		new artidrop(dropspot)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rising_star(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 0)
	bullet_heck(target, -7, 0)
	bullet_heck(target, 0, 7)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 7, 7)
	bullet_heck(target, 7, -7)
	bullet_heck(target, -7, 7)
	bullet_heck(target, -7, -7)
	after(src, fire_delay, PROC_REF(rising_starA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rising_starA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, -4)
	bullet_heck(target, -7, 4)
	bullet_heck(target, 4, 7)
	bullet_heck(target, -4, -7)
	bullet_heck(target, 7, -4)
	bullet_heck(target, -7, 4)
	bullet_heck(target, 4, 7)
	bullet_heck(target, -4, -7)
	after(src, fire_delay, PROC_REF(rising_starB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/rising_starB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, -1)
	bullet_heck(target, -7, 1)
	bullet_heck(target, 1, 7)
	bullet_heck(target, -1, -7)
	bullet_heck(target, 5, 7)
	bullet_heck(target, 7, -5)
	bullet_heck(target, -5, 7)
	bullet_heck(target, -7, -5)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/gattlingfire(atom/target, next_cycle, amount, fire_delay)
	start_volley(ECLIPSE_VOLLEY_GATTLING, target, amount, next_cycle, fire_delay)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/death_wall(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 0)
	bullet_heck(target, 7, 1)
	bullet_heck(target, 7, 2)
	bullet_heck(target, 7, 3)
	bullet_heck(target, 7, 4)
	bullet_heck(target, 7, 5)
	bullet_heck(target, 7, 6)
	bullet_heck(target, 7, 7)
	bullet_heck(target, 7, -1)
	bullet_heck(target, 7, -2)
	bullet_heck(target, 7, -3)
	bullet_heck(target, 7, -4)
	bullet_heck(target, 7, -5)
	bullet_heck(target, 7, -6)
	bullet_heck(target, 7, -7)
	after(src, fire_delay, PROC_REF(death_wallA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/death_wallA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 0)
	bullet_heck(target, -7, 1)
	bullet_heck(target, -7, 2)
	bullet_heck(target, -7, 3)
	bullet_heck(target, -7, 4)
	bullet_heck(target, -7, 5)
	bullet_heck(target, -7, 6)
	bullet_heck(target, -7, 7)
	bullet_heck(target, -7, -1)
	bullet_heck(target, -7, -2)
	bullet_heck(target, -7, -3)
	bullet_heck(target, -7, -4)
	bullet_heck(target, -7, -5)
	bullet_heck(target, -7, -6)
	bullet_heck(target, -7, -7)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/death_wallR(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 0)
	bullet_heck(target, -7, 1)
	bullet_heck(target, -7, 2)
	bullet_heck(target, -7, 3)
	bullet_heck(target, -7, 4)
	bullet_heck(target, -7, 5)
	bullet_heck(target, -7, 6)
	bullet_heck(target, -7, 7)
	bullet_heck(target, -7, -1)
	bullet_heck(target, -7, -2)
	bullet_heck(target, -7, -3)
	bullet_heck(target, -7, -4)
	bullet_heck(target, -7, -5)
	bullet_heck(target, -7, -6)
	bullet_heck(target, -7, -7)
	after(src, fire_delay, PROC_REF(death_wallRA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/death_wallRA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 0)
	bullet_heck(target, 7, 1)
	bullet_heck(target, 7, 2)
	bullet_heck(target, 7, 3)
	bullet_heck(target, 7, 4)
	bullet_heck(target, 7, 5)
	bullet_heck(target, 7, 6)
	bullet_heck(target, 7, 7)
	bullet_heck(target, 7, -1)
	bullet_heck(target, 7, -2)
	bullet_heck(target, 7, -3)
	bullet_heck(target, 7, -4)
	bullet_heck(target, 7, -5)
	bullet_heck(target, 7, -6)
	bullet_heck(target, 7, -7)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cutoff(atom/target, next_cycle, fire_delay, amount)
	start_volley(ECLIPSE_VOLLEY_CUTOFF, target, amount, next_cycle, fire_delay)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/cutoff_ulti(atom/target, next_cycle, fire_delay, amount)
	start_volley(ECLIPSE_VOLLEY_CUTOFF_ULTI, target, amount, next_cycle, fire_delay)

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bullet_blossom(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 7)
	bullet_heck(target, -7, -7)
	bullet_heck(target, -7, 7)
	bullet_heck(target, 7, -7)
	after(src, fire_delay, PROC_REF(bullet_blossomA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bullet_blossomA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 6, 7)
	bullet_heck(target, 7, 6)
	bullet_heck(target, -6, -7)
	bullet_heck(target, -7, -6)
	bullet_heck(target, -6, 7)
	bullet_heck(target, -7, 6)
	bullet_heck(target, 6, -7)
	bullet_heck(target, 7, -6)
	after(src, fire_delay, PROC_REF(bullet_blossomB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bullet_blossomB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 5, 7)
	bullet_heck(target, 7, 5)
	bullet_heck(target, -5, -7)
	bullet_heck(target, -7, -5)
	bullet_heck(target, -5, 7)
	bullet_heck(target, -7, 5)
	bullet_heck(target, 5, -7)
	bullet_heck(target, 7, -5)
	after(src, fire_delay, PROC_REF(bullet_blossomC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bullet_blossomC(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 4, 7)
	bullet_heck(target, 7, 4)
	bullet_heck(target, -4, -7)
	bullet_heck(target, -7, -4)
	bullet_heck(target, -4, 7)
	bullet_heck(target, -7, 4)
	bullet_heck(target, 4, -7)
	bullet_heck(target, 7, -4)
	after(src, fire_delay, PROC_REF(bullet_blossomD), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bullet_blossomD(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 3, 7)
	bullet_heck(target, 7, 3)
	bullet_heck(target, -3, -7)
	bullet_heck(target, -7, -3)
	bullet_heck(target, -3, 7)
	bullet_heck(target, -7, 3)
	bullet_heck(target, 3, -7)
	bullet_heck(target, 7, -3)
	after(src, fire_delay, PROC_REF(bullet_blossomE), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bullet_blossomE(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 2, 7)
	bullet_heck(target, 7, 2)
	bullet_heck(target, -2, -7)
	bullet_heck(target, -7, -2)
	bullet_heck(target, -2, 7)
	bullet_heck(target, -7, 2)
	bullet_heck(target, 2, -7)
	bullet_heck(target, 7, -2)
	after(src, fire_delay, PROC_REF(bullet_blossomF), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bullet_blossomF(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 1, 7)
	bullet_heck(target, 7, 1)
	bullet_heck(target, -1, -7)
	bullet_heck(target, -7, -1)
	bullet_heck(target, -1, 7)
	bullet_heck(target, -7, 1)
	bullet_heck(target, 1, -7)
	bullet_heck(target, 7, -1)
	after(src, fire_delay, PROC_REF(bullet_blossomG), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/bullet_blossomG(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 0, 7)
	bullet_heck(target, -7, 0)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 7, 0)
	attackcycle = next_cycle

//Three spinning lines with occassional projectiles thrown in the middle
/mob/living/simple_mob/mechanical/mecha/eclipse/proc/triple_lines(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -7, 7)
	bullet_heck(target, 7, 7)
	bullet_heck(target, 0, -7)
	bullet_heck(target, 7, -7)
	bullet_heck(target, -7, -7)
	bullet_heck(target, 0, 7)
	after(src, fire_delay, PROC_REF(triple_linesA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/triple_linesA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -6, 7)
	bullet_heck(target, 7, 6)
	bullet_heck(target, -1, -7)
	after(src, fire_delay, PROC_REF(triple_linesB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/triple_linesB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -5, 7)
	bullet_heck(target, 7, 5)
	bullet_heck(target, -2, -7)
	bullet_heck(target, 5, -7)
	bullet_heck(target, -7, -5)
	bullet_heck(target, 2, 7)
	after(src, fire_delay, PROC_REF(triple_linesC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/triple_linesC(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -4, 7)
	bullet_heck(target, 7, 4)
	bullet_heck(target, -3, -7)
	after(src, fire_delay, PROC_REF(triple_linesD), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/triple_linesD(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -3, 7)
	bullet_heck(target, 7, 3)
	bullet_heck(target, -4, -7)
	bullet_heck(target, 3, -7)
	bullet_heck(target, -7, -3)
	bullet_heck(target, 4, 7)
	after(src, fire_delay, PROC_REF(triple_linesE), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/triple_linesE(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -2, 7)
	bullet_heck(target, 7, 2)
	bullet_heck(target, -5, -7)
	after(src, fire_delay, PROC_REF(triple_linesF), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/triple_linesF(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -1, 7)
	bullet_heck(target, 7, 1)
	bullet_heck(target, -6, -7)
	bullet_heck(target, 1, -7)
	bullet_heck(target, -7, -1)
	bullet_heck(target, 6, 7)
	after(src, fire_delay, PROC_REF(triple_linesG), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/triple_linesG(atom/target, next_cycle, fire_delay)
	bullet_heck(target, -0, 7)
	bullet_heck(target, 7, 0)
	bullet_heck(target, -7, -7)
	attackcycle = next_cycle

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laser(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 7)
	bullet_heck(target, 6, 7)
	bullet_heck(target, 5, 7)
	bullet_heck(target, 4, 7)
	bullet_heck(target, 3, 7)
	bullet_heck(target, 2, 7)
	bullet_heck(target, 1, 7)
	bullet_heck(target, 0, 7)
	bullet_heck(target, -7, -7)
	bullet_heck(target, -6, -7)
	bullet_heck(target, -5, -7)
	bullet_heck(target, -4, -7)
	bullet_heck(target, -3, -7)
	bullet_heck(target, -2, -7)
	bullet_heck(target, -1, -7)
	bullet_heck(target, 0, -7)
	after(src, fire_delay, PROC_REF(vertical_double_laserA), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserA(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 6)
	bullet_heck(target, 6, 6)
	bullet_heck(target, 5, 6)
	bullet_heck(target, 4, 6)
	bullet_heck(target, 3, 6)
	bullet_heck(target, 2, 6)
	bullet_heck(target, 1, 6)
	bullet_heck(target, 0, 6)
	bullet_heck(target, -7, -6)
	bullet_heck(target, -6, -6)
	bullet_heck(target, -5, -6)
	bullet_heck(target, -4, -6)
	bullet_heck(target, -3, -6)
	bullet_heck(target, -2, -6)
	bullet_heck(target, -1, -6)
	bullet_heck(target, 0, -6)
	after(src, fire_delay, PROC_REF(vertical_double_laserB), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserB(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 5)
	bullet_heck(target, 6, 5)
	bullet_heck(target, 5, 5)
	bullet_heck(target, 4, 5)
	bullet_heck(target, 3, 5)
	bullet_heck(target, 2, 5)
	bullet_heck(target, 1, 5)
	bullet_heck(target, 0, 5)
	bullet_heck(target, -7, -5)
	bullet_heck(target, -6, -5)
	bullet_heck(target, -5, -5)
	bullet_heck(target, -4, -5)
	bullet_heck(target, -3, -5)
	bullet_heck(target, -2, -5)
	bullet_heck(target, -1, -5)
	bullet_heck(target, 0, -5)
	after(src, fire_delay, PROC_REF(vertical_double_laserC), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserC(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 4)
	bullet_heck(target, 6, 4)
	bullet_heck(target, 5, 4)
	bullet_heck(target, 4, 4)
	bullet_heck(target, 3, 4)
	bullet_heck(target, 2, 4)
	bullet_heck(target, 1, 4)
	bullet_heck(target, 0, 4)
	bullet_heck(target, -7, -4)
	bullet_heck(target, -6, -4)
	bullet_heck(target, -5, -4)
	bullet_heck(target, -4, -4)
	bullet_heck(target, -3, -4)
	bullet_heck(target, -2, -4)
	bullet_heck(target, -1, -4)
	bullet_heck(target, 0, -4)
	after(src, fire_delay, PROC_REF(vertical_double_laserD), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserD(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 3)
	bullet_heck(target, 6, 3)
	bullet_heck(target, 5, 3)
	bullet_heck(target, 4, 3)
	bullet_heck(target, 3, 3)
	bullet_heck(target, 2, 3)
	bullet_heck(target, 1, 3)
	bullet_heck(target, 0, 3)
	bullet_heck(target, -7, -3)
	bullet_heck(target, -6, -3)
	bullet_heck(target, -5, -3)
	bullet_heck(target, -4, -3)
	bullet_heck(target, -3, -3)
	bullet_heck(target, -2, -3)
	bullet_heck(target, -1, -3)
	bullet_heck(target, 0, -3)
	after(src, fire_delay, PROC_REF(vertical_double_laserE), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserE(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 2)
	bullet_heck(target, 6, 2)
	bullet_heck(target, 5, 2)
	bullet_heck(target, 4, 2)
	bullet_heck(target, 3, 2)
	bullet_heck(target, 2, 2)
	bullet_heck(target, 1, 2)
	bullet_heck(target, 0, 2)
	bullet_heck(target, -7, -2)
	bullet_heck(target, -6, -2)
	bullet_heck(target, -5, -2)
	bullet_heck(target, -4, -2)
	bullet_heck(target, -3, -2)
	bullet_heck(target, -2, -2)
	bullet_heck(target, -1, -2)
	bullet_heck(target, 0, -2)
	after(src, fire_delay, PROC_REF(vertical_double_laserF), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserF(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 1)
	bullet_heck(target, 6, 1)
	bullet_heck(target, 5, 1)
	bullet_heck(target, 4, 1)
	bullet_heck(target, 3, 1)
	bullet_heck(target, 2, 1)
	bullet_heck(target, 1, 1)
	bullet_heck(target, 0, 1)
	bullet_heck(target, -7, -1)
	bullet_heck(target, -6, -1)
	bullet_heck(target, -5, -1)
	bullet_heck(target, -4, -1)
	bullet_heck(target, -3, -1)
	bullet_heck(target, -2, -1)
	bullet_heck(target, -1, -1)
	bullet_heck(target, 0, -1)
	after(src, fire_delay, PROC_REF(vertical_double_laserG), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserG(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, 0)
	bullet_heck(target, 6, 0)
	bullet_heck(target, 5, 0)
	bullet_heck(target, 4, 0)
	bullet_heck(target, 3, 0)
	bullet_heck(target, 2, 0)
	bullet_heck(target, 1, 0)
	bullet_heck(target, -7, 0)
	bullet_heck(target, -6, 0)
	bullet_heck(target, -5, 0)
	bullet_heck(target, -4, 0)
	bullet_heck(target, -3, 0)
	bullet_heck(target, -2, 0)
	bullet_heck(target, -1, 0)
	after(src, fire_delay, PROC_REF(vertical_double_laserH), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserH(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, -1)
	bullet_heck(target, 6, -1)
	bullet_heck(target, 5, -1)
	bullet_heck(target, 4, -1)
	bullet_heck(target, 3, -1)
	bullet_heck(target, 2, -1)
	bullet_heck(target, 1, -1)
	bullet_heck(target, 0, -1)
	bullet_heck(target, -7, 1)
	bullet_heck(target, -6, 1)
	bullet_heck(target, -5, 1)
	bullet_heck(target, -4, 1)
	bullet_heck(target, -3, 1)
	bullet_heck(target, -2, 1)
	bullet_heck(target, -1, 1)
	bullet_heck(target, 0, 1)
	after(src, fire_delay, PROC_REF(vertical_double_laserI), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserI(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, -2)
	bullet_heck(target, 6, -2)
	bullet_heck(target, 5, -2)
	bullet_heck(target, 4, -2)
	bullet_heck(target, 3, -2)
	bullet_heck(target, 2, -2)
	bullet_heck(target, 1, -2)
	bullet_heck(target, 0, -2)
	bullet_heck(target, -7, 2)
	bullet_heck(target, -6, 2)
	bullet_heck(target, -5, 2)
	bullet_heck(target, -4, 2)
	bullet_heck(target, -3, 2)
	bullet_heck(target, -2, 2)
	bullet_heck(target, -1, 2)
	bullet_heck(target, 0, 2)
	after(src, fire_delay, PROC_REF(vertical_double_laserJ), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserJ(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, -3)
	bullet_heck(target, 6, -3)
	bullet_heck(target, 5, -3)
	bullet_heck(target, 4, -3)
	bullet_heck(target, 3, -3)
	bullet_heck(target, 2, -3)
	bullet_heck(target, 1, -3)
	bullet_heck(target, 0, -3)
	bullet_heck(target, -7, 3)
	bullet_heck(target, -6, 3)
	bullet_heck(target, -5, 3)
	bullet_heck(target, -4, 3)
	bullet_heck(target, -3, 3)
	bullet_heck(target, -2, 3)
	bullet_heck(target, -1, 3)
	bullet_heck(target, 0, 3)
	after(src, fire_delay, PROC_REF(vertical_double_laserK), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserK(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, -4)
	bullet_heck(target, 6, -4)
	bullet_heck(target, 5, -4)
	bullet_heck(target, 4, -4)
	bullet_heck(target, 3, -4)
	bullet_heck(target, 2, -4)
	bullet_heck(target, 1, -4)
	bullet_heck(target, 0, -4)
	bullet_heck(target, -7, 4)
	bullet_heck(target, -6, 4)
	bullet_heck(target, -5, 4)
	bullet_heck(target, -4, 4)
	bullet_heck(target, -3, 4)
	bullet_heck(target, -2, 4)
	bullet_heck(target, -1, 4)
	bullet_heck(target, 0, 4)
	after(src, fire_delay, PROC_REF(vertical_double_laserL), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserL(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, -5)
	bullet_heck(target, 6, -5)
	bullet_heck(target, 5, -5)
	bullet_heck(target, 4, -5)
	bullet_heck(target, 3, -5)
	bullet_heck(target, 2, -5)
	bullet_heck(target, 1, -5)
	bullet_heck(target, 0, -5)
	bullet_heck(target, -7, 5)
	bullet_heck(target, -6, 5)
	bullet_heck(target, -5, 5)
	bullet_heck(target, -4, 5)
	bullet_heck(target, -3, 5)
	bullet_heck(target, -2, 5)
	bullet_heck(target, -1, 5)
	bullet_heck(target, 0, 5)
	after(src, fire_delay, PROC_REF(vertical_double_laserM), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserM(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, -6)
	bullet_heck(target, 6, -6)
	bullet_heck(target, 5, -6)
	bullet_heck(target, 4, -6)
	bullet_heck(target, 3, -6)
	bullet_heck(target, 2, -6)
	bullet_heck(target, 1, -6)
	bullet_heck(target, 0, -6)
	bullet_heck(target, -7, 6)
	bullet_heck(target, -6, 6)
	bullet_heck(target, -5, 6)
	bullet_heck(target, -4, 6)
	bullet_heck(target, -3, 6)
	bullet_heck(target, -2, 6)
	bullet_heck(target, -1, 6)
	bullet_heck(target, 0, 6)
	after(src, fire_delay, PROC_REF(vertical_double_laserN), with = list(target, next_cycle, fire_delay))

/mob/living/simple_mob/mechanical/mecha/eclipse/proc/vertical_double_laserN(atom/target, next_cycle, fire_delay)
	bullet_heck(target, 7, -7)
	bullet_heck(target, 6, -7)
	bullet_heck(target, 5, -7)
	bullet_heck(target, 4, -7)
	bullet_heck(target, 3, -7)
	bullet_heck(target, 2, -7)
	bullet_heck(target, 1, -7)
	bullet_heck(target, 0, -7)
	bullet_heck(target, -7, 7)
	bullet_heck(target, -6, 7)
	bullet_heck(target, -5, 7)
	bullet_heck(target, -4, 7)
	bullet_heck(target, -3, 7)
	bullet_heck(target, -2, 7)
	bullet_heck(target, -1, 7)
	bullet_heck(target, 0, 7)
	attackcycle = next_cycle

#undef ECLIPSE_VOLLEY_RANDOM
#undef ECLIPSE_VOLLEY_QUAD_RANDOM
#undef ECLIPSE_VOLLEY_GATTLING
#undef ECLIPSE_VOLLEY_CUTOFF
#undef ECLIPSE_VOLLEY_CUTOFF_ULTI
