// THIS FILE IS GENERATED by tools/build/lib/verdigris_bindings.ts from the
// #[auxmacros::bind] functions in verdigris/. Do not edit it by hand: run
// `tools/build/build.sh verdigris-bindings`. CI fails when it is stale.
//
// This is the only file allowed to use call_ext for verdigris.

/* This comment bypasses grep checks */ /var/__verdigris

/proc/__detect_verdigris()
	if (world.system_type == UNIX)
		return __verdigris = (fexists("./libverdigris.so") ? "./libverdigris.so" : "libverdigris")
	else
		return __verdigris = "verdigris"

#define VERDIGRIS (__verdigris || __detect_verdigris())

#if defined(BENCHMARK) || defined(UNIT_TESTS)
/// FFI calls made through the vg_* procs. Benchmark and unit-test builds
/// only: the benchmarks report it per window (code/modules/benchmarks/_benchmark.dm)
/// and tests assert that DM-only paths make none.
/* This comment bypasses grep checks */ /var/__verdigris_ffi_calls = 0
#define VG_COUNT_FFI_CALL __verdigris_ffi_calls++
#else
#define VG_COUNT_FFI_CALL
#endif

/// Bind-set hash shared with verdigris/ffi/src/abi.rs; checked by verdigris_init().
#define VERDIGRIS_ABI "a429627f5b1dbf38"

// Numeric registry (@dm-define constants in the Rust sources).

/// Every face a mask can block (`NORTH|SOUTH|EAST|WEST|UP|DOWN`).
// verdigris/domains/gas/src/turf.rs
#define AIR_BLOCK_ALL 63

/// Mask argument meaning "keep the mask Rust already has for this turf".
// verdigris/domains/gas/src/turf.rs
#define AIR_BLOCK_KEEP -1

/// Normal human core body temperature, 37 °C in K. The one body temperature:
/// species, mobs, reagents and machines all read this define.
// verdigris/domains/heat/src/consts.rs
#define BODYTEMP_NORMAL 310.15

/// Lowest temperature a fire exists at, and phoron's ignition point, K
/// (100 °C). The gas crate's `FIRE_MINIMUM_TEMPERATURE_TO_EXIST` and
/// `PLASMA_MINIMUM_BURN_TEMPERATURE` must equal it (tested there).
// verdigris/domains/heat/src/consts.rs
#define FIRE_MINIMUM_TEMPERATURE_TO_EXIST 373.15

// verdigris/domains/gas/src/gas.rs
#define GAS_DEPENDENCY_COMPOSITION 4

/// Floats per record returned by `drain_dirty_gas_observations`.
// verdigris/domains/gas/src/lib.rs
#define GAS_DEPENDENCY_OBSERVATION_STRIDE 15

// verdigris/domains/gas/src/gas.rs
#define GAS_DEPENDENCY_PRESSURE 1

// verdigris/domains/gas/src/gas.rs
#define GAS_DEPENDENCY_TEMPERATURE 2

/// Spacewind: `turf.consider_pressure_difference(other, value)`.
// verdigris/domains/gas/src/turf.rs
#define GAS_EVENT_PRESSURE 1

/// A turf's gas may react (`air.react(turf)`).
// verdigris/domains/gas/src/turf.rs
#define GAS_EVENT_REACT 2

/// Numbers per event returned by `gas_tick`: kind, turf, value, other turf.
// verdigris/domains/gas/src/turf.rs
#define GAS_EVENT_STRIDE 4

/// A turf's visible gas changed (`set_visuals()`).
// verdigris/domains/gas/src/turf.rs
#define GAS_EVENT_VISUAL 3

/// Main-owned mixtures use handles `0..PIPE_BASE`.
// verdigris/domains/gas/src/world.rs
#define GAS_HANDLE_PIPE_BASE 2097152

/// Turf cells use `TURF_BASE + cell`.
// verdigris/domains/gas/src/world.rs
#define GAS_HANDLE_TURF_BASE 4194304

/// `/datum/gas/antinoblium`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_ANTINOBLIUM 19

/// `/datum/gas/bz`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_BZ 9

/// `/datum/gas/carbon_dioxide`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_CARBON_DIOXIDE 2

/// Number of registered gases.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_COUNT 22

/// `/datum/gas/freon`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_FREON 12

/// `/datum/gas/halon`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_HALON 17

/// `/datum/gas/healium`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_HEALIUM 14

/// `/datum/gas/helium`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_HELIUM 18

/// `/datum/gas/hydrogen`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_HYDROGEN 13

/// `/datum/gas/hypernoblium`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_HYPERNOBLIUM 5

/// `/datum/gas/methane`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_METHANE 20

/// `/datum/gas/miasma`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_MIASMA 11

/// `/datum/gas/nitrium`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_NITRIUM 7

/// `/datum/gas/nitrogen`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_NITROGEN 1

/// `/datum/gas/nitrous_oxide`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_NITROUS_OXIDE 6

/// `/datum/gas/oxygen`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_OXYGEN 0

/// `/datum/gas/plasma`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_PLASMA 3

/// `/datum/gas/pluoxium`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_PLUOXIUM 10

/// `/datum/gas/proto_nitrate`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_PROTO_NITRATE 15

/// `/datum/gas/tritium`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_TRITIUM 8

/// `/datum/gas/volatile_fuel`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_VOLATILE_FUEL 21

/// `/datum/gas/water_vapor`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_WATER_VAPOR 4

/// `/datum/gas/zauker`.
// verdigris/domains/gas/src/gas/ids.rs
#define GAS_ID_ZAUKER 16

/// Floats per mixture in `read_mixtures`: pressure, temperature, volume,
/// total moles, heat capacity, then the moles of every gas by ID.
// verdigris/domains/gas/src/lib.rs
#define GAS_READ_HEADER 5

/// Heat capacity DM gives vacuum (`HEAT_CAPACITY_VACUUM`), J/K: the capacity
/// of a space or planet reservoir cell.
// verdigris/domains/heat/src/consts.rs
#define HEAT_CAPACITY_VACUUM 7000.0

// verdigris/ffi/src/heat.rs
#define HEAT_CELL_PLANET 2

/// `HEAT_CELL_*` kinds DM sends for a turf.
// verdigris/ffi/src/heat.rs
#define HEAT_CELL_SOLID 0

// verdigris/ffi/src/heat.rs
#define HEAT_CELL_SPACE 1

// verdigris/ffi/src/heat.rs
#define HEAT_TARGET_BODY 4

// verdigris/ffi/src/heat.rs
#define HEAT_TARGET_MIXTURE 3

/// Coupling-slot kinds DM sends, matching the pre-existing `HEAT_TARGET_*`
/// defines exactly (unchanged DM proc surface).
// verdigris/ffi/src/heat.rs
#define HEAT_TARGET_NONE 0

// verdigris/ffi/src/heat.rs
#define HEAT_TARGET_SOLID 1

// verdigris/ffi/src/heat.rs
#define HEAT_TARGET_TURF_AIR 2

/// Watch kinds, matching the pre-existing `HEAT_WATCH_*` defines.
// verdigris/ffi/src/heat.rs
#define HEAT_WATCH_ABOVE 0

// verdigris/ffi/src/heat.rs
#define HEAT_WATCH_BAND 2

// verdigris/ffi/src/heat.rs
#define HEAT_WATCH_BELOW 1

// verdigris/ffi/src/heat.rs
#define HEAT_WATCH_SET 3

/// Heat capacity of an 80 kg human body, J/K (about 3.5 kJ/(kg·K)).
// verdigris/domains/heat/src/consts.rs
#define HUMAN_HEAT_CAPACITY 280000.0

/// Node kinds in the graph (an opaque tag `NetworkHost` stores per node;
/// power does not read it back, only DM's own bookkeeping might).
// verdigris/ffi/src/power.rs
#define POWER_NODE_CABLE 0

// verdigris/ffi/src/power.rs
#define POWER_NODE_MACHINE 1

/// Gas: turf gas and main-owned mixtures, by gas handle (vg-gas).
// verdigris/ffi/src/reactor.rs
#define REACT_DOMAIN_GAS 2

/// The probe domain: DM-written test cells (see the module docs).
// verdigris/ffi/src/reactor.rs
#define REACT_DOMAIN_PROBE 1

/// Cells in the probe domain.
// verdigris/ffi/src/reactor.rs
#define REACT_PROBE_CELLS 256

/// Reason class: a condition watch (Threshold, Band, Difference, ...).
// verdigris/ffi/src/reactor.rs
#define REACT_REASON_CONDITION 0x100000

/// The bits below the reason classes: channel bits, or a key's mask.
// verdigris/ffi/src/reactor.rs
#define REACT_REASON_DETAIL 0x0FFFFF

/// Reason class: a DM-owned key was published.
// verdigris/ffi/src/reactor.rs
#define REACT_REASON_KEY 0x400000

/// Reason class: a rate model crossed a watched level.
// verdigris/ffi/src/reactor.rs
#define REACT_REASON_RATE 0x800000

/// Reason class: a `REACT_AT` timer fired.
// verdigris/ffi/src/reactor.rs
#define REACT_REASON_TIMER 0x200000

/// Numbers per wake returned by `vg_react_step`:
/// `subscriber, lane, reason, source, source_kind`.
// verdigris/ffi/src/reactor.rs
#define REACT_WAKE_STRIDE 5

// verdigris/ffi/src/heat_regulator.rs
#define REGULATOR_MODE_BOTH 2

// verdigris/ffi/src/heat_regulator.rs
#define REGULATOR_MODE_COOL 1

/// `RegulatorMode` as DM sends it.
// verdigris/ffi/src/heat_regulator.rs
#define REGULATOR_MODE_HEAT 0

/// Registration flag DM passes for a simulated turf.
// verdigris/domains/gas/src/turf.rs
#define SIMULATION_ANY 3

/// Stefan-Boltzmann constant, W/(m^2*K^4). Written out in decimal
/// because the define scanner reads plain literals only.
// verdigris/core/src/units.rs
#define STEFAN_BOLTZMANN_CONSTANT 0.00000005670374419

/// 0 degrees Celsius, K.
// verdigris/core/src/units.rs
#define T0C 273.15

/// 20 degrees Celsius, K ("room temperature").
// verdigris/core/src/units.rs
#define T20C 293.15

/// Cosmic microwave background temperature, K. The floor every body and
/// gas cools toward.
// verdigris/core/src/units.rs
#define TCMB 2.7

/// Default heat capacity of an atom that declares no thermal properties, J/K.
// verdigris/domains/heat/src/consts.rs
#define THERMAL_CAPACITY_DEFAULT 2000.0

/// An item's heat capacity per `w_class` step, J/K.
// verdigris/domains/heat/src/consts.rs
#define THERMAL_CAPACITY_PER_W_CLASS 400.0

/// Default conductance of an atom to its surroundings, W/K.
// verdigris/domains/heat/src/consts.rs
#define THERMAL_CONDUCTANCE_DEFAULT 2.0

/// An item's conductance per `w_class` step, W/K.
// verdigris/domains/heat/src/consts.rs
#define THERMAL_CONDUCTANCE_PER_W_CLASS 0.5

/// Emissivity used when DM declares none.
// verdigris/domains/heat/src/consts.rs
#define THERMAL_EMISSIVITY_DEFAULT 0.9

// verdigris/core/src/component.rs
#define VG_DOMAIN_GAS 0

/// The bits of a `vg_entity` value (after subtracting the raw-plus-one
/// offset) that carry the slot index, matching `vg_core::entity::INDEX_BITS`
/// (checked in this module's tests). DM computes an entity's table index
/// with it to look up the bound atom for event dispatch, without needing to
/// know anything else about id packing.
// verdigris/ffi/src/entity.rs
#define VG_ENTITY_INDEX_MASK 524287

/// Registry ids at and above this are world component kinds:
/// `WORLD_KIND_BASE | kind_code` ([`crate::world::kind_code`]).
// verdigris/core/src/registry.rs
#define VG_WORLD_KIND_BASE 0x10000

// Binds.

/// Args: (amount). Adds the given amount to each gas.
// /datum/gas_mixture/proc/add (verdigris/domains/gas/src/lib.rs)
/proc/vg_add_hook(src_ref, num_val)
	var/static/__f = load_ext(VERDIGRIS, "byond:add_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, num_val)

/// Args: (heat). Adds a given amount of heat to the mixture, i.e. in joules taking into account capacity.
// /datum/gas_mixture/proc/adjust_heat (verdigris/domains/gas/src/lib.rs)
/proc/vg_adjust_heat_hook(src_ref, temp)
	var/static/__f = load_ext(VERDIGRIS, "byond:adjust_heat_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, temp)

/// Args: (gas_id, moles). Adjusts the given gas's amount by the given amount, e.g. (GAS_O2, -0.1) will remove 0.1 moles of oxygen from the mixture.
// /datum/gas_mixture/proc/adjust_moles (verdigris/domains/gas/src/lib.rs)
/proc/vg_adjust_moles_hook(src_ref, id_val, num_val)
	var/static/__f = load_ext(VERDIGRIS, "byond:adjust_moles_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, id_val, num_val)

/// Args: (gas_id, moles, temp). Adjusts the given gas's amount by the given amount, with that gas being treated as if it is at the given temperature.
// /datum/gas_mixture/proc/adjust_moles_temp (verdigris/domains/gas/src/lib.rs)
/proc/vg_adjust_moles_temp_hook(src_ref, id_val, num_val, temp_val)
	var/static/__f = load_ext(VERDIGRIS, "byond:adjust_moles_temp_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, id_val, num_val, temp_val)

/// Args: (gas_id_1, amount_1, gas_id_2, amount_2, ...). As adjust_moles, but with variadic arguments.
// /datum/gas_mixture/proc/adjust_multi (verdigris/domains/gas/src/lib.rs)
/proc/vg_adjust_multi_hook(...)
	var/static/__f = load_ext(VERDIGRIS, "byond:adjust_multi_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(arglist(args))

/// Returns: the turfs this turf shares air with (face neighbours only).
// /proc/atmos_adjacent_turfs (verdigris/domains/gas/src/turf.rs)
/proc/vg_atmos_adjacent_turfs(turf)
	var/static/__f = load_ext(VERDIGRIS, "byond:atmos_adjacent_turfs_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turf)

/// Batched form of `atmos_adjacent_turfs`: a list of lists, one per turf.
// /proc/atmos_adjacent_turfs_bulk (verdigris/domains/gas/src/turf.rs)
/proc/vg_atmos_adjacent_turfs_bulk(turfs)
	var/static/__f = load_ext(VERDIGRIS, "byond:atmos_adjacent_turfs_bulk_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turfs)

/// Args: (ms). Runs callbacks until time limit is reached. If time limit is omitted, runs all callbacks.
// /proc/process_atmos_callbacks (verdigris/domains/gas/src/lib.rs)
/proc/vg_atmos_callback_handle(remaining)
	var/static/__f = load_ext(VERDIGRIS, "byond:atmos_callback_handle_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(remaining)

/// Diagnostic: list(registered, mask, z-level links, zero-based z).
// /proc/atmos_cell_info (verdigris/domains/gas/src/turf.rs)
/proc/vg_atmos_cell_info(turf)
	var/static/__f = load_ext(VERDIGRIS, "byond:atmos_cell_info_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turf)

/// Returns: the direction bits (NORTH..DOWN) across which this turf shares air.
// /proc/atmos_open_dirs (verdigris/domains/gas/src/turf.rs)
/proc/vg_atmos_open_dirs(turf)
	var/static/__f = load_ext(VERDIGRIS, "byond:atmos_open_dirs_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turf)

/// Returns: whether two turfs are face neighbours that share air.
// /proc/atmos_turfs_share (verdigris/domains/gas/src/turf.rs)
/proc/vg_atmos_turfs_share(first, second)
	var/static/__f = load_ext(VERDIGRIS, "byond:atmos_turfs_share_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(first, second)

/// `list(main mixtures live, main slots, pipe regions, pipe ports,
/// registered turf cells, gas frames, pending callbacks, heat frames, heat
/// bodies, heat frame us)` for SSair's stat panel.
// /datum/controller/subsystem/air/proc/auxmos_diagnostics (verdigris/domains/gas/src/lib.rs)
/proc/vg_auxmos_diagnostics()
	var/static/__f = load_ext(VERDIGRIS, "byond:auxmos_diagnostics_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Flat operation list: pipe mixture, environment mixture, exposed pipe
/// volume. Returns one boolean residual per exposed face.
// /proc/auxmos_batch_mingle (verdigris/domains/gas/src/lib.rs)
/proc/vg_batch_mingle_hook(operations)
	var/static/__f = load_ext(VERDIGRIS, "byond:batch_mingle_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(operations)

/// Flat operation list: source handle, sink handle, requested moles. Returns
/// one actual mole count per operation after shared-source clamping.
// /proc/auxmos_batch_transfer (verdigris/domains/gas/src/lib.rs)
/proc/vg_batch_transfer_hook(operations)
	var/static/__f = load_ext(VERDIGRIS, "byond:batch_transfer_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(operations)

/// Binds a gas mixture datum to a pipe region's gas (the handle from
/// `vg_pipe_upsert`/`vg_pipe_commit`, `verdigris/ffi/src/pipes.rs`). The
/// datum's own slot is freed.
// /datum/gas_mixture/proc/__bind_handle (verdigris/domains/gas/src/lib.rs)
/proc/vg_bind_handle(src_ref, handle)
	var/static/__f = load_ext(VERDIGRIS, "byond:bind_handle_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, handle)

/// Clears the gas mixture my removing all of its gases.
// /datum/gas_mixture/proc/clear (verdigris/domains/gas/src/lib.rs)
/proc/vg_clear_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:clear_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Returns: true if the two mixtures are different enough for processing, false otherwise.
// /datum/gas_mixture/proc/compare (verdigris/domains/gas/src/lib.rs)
/proc/vg_compare_hook(src_ref, other)
	var/static/__f = load_ext(VERDIGRIS, "byond:compare_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, other)

/// Take reconciliation on a conserved field: adds `delta` to the owner's
/// current value. Returns the shortfall of a removal.
// /proc/vg_component_adjust (verdigris/ffi/src/world.rs)
/proc/vg_component_adjust(entity, code, field_id, index, delta)
	var/static/__f = load_ext(VERDIGRIS, "byond:component_adjust_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, code, field_id, index, delta)

/// Attaches component `code` to `entity` (0: a new entity), seeded from its
/// defaults with `init` (`[field, value, ...]`) applied as validated
/// writes. Returns the entity handle.
// /proc/vg_component_bind (verdigris/ffi/src/world.rs)
/proc/vg_component_bind(entity, code, init)
	var/static/__f = load_ext(VERDIGRIS, "byond:component_bind_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, code, init)

/// Detaches one component.
// /proc/vg_component_detach (verdigris/ffi/src/world.rs)
/proc/vg_component_detach(entity, code)
	var/static/__f = load_ext(VERDIGRIS, "byond:component_detach_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, code)

/// One field (element `index` of an array field; 0 otherwise).
// /proc/vg_component_get (verdigris/ffi/src/world.rs)
/proc/vg_component_get(entity, code, field_id, index)
	var/static/__f = load_ext(VERDIGRIS, "byond:component_get_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, code, field_id, index)

/// Several fields in one call (a query group): one number per field id.
// /proc/vg_component_get_many (verdigris/ffi/src/world.rs)
/proc/vg_component_get_many(entity, code, fields)
	var/static/__f = load_ext(VERDIGRIS, "byond:component_get_many_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, code, fields)

/// Whether `entity` has component `code` (never a runtime).
// /proc/vg_component_has (verdigris/ffi/src/world.rs)
/proc/vg_component_has(entity, code)
	var/static/__f = load_ext(VERDIGRIS, "byond:component_has_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, code)

/// A validated write (`index` < 0 or null: the whole field). Returns the
/// value DM now reads back.
// /proc/vg_component_set (verdigris/ffi/src/world.rs)
/proc/vg_component_set(entity, code, field_id, index, value)
	var/static/__f = load_ext(VERDIGRIS, "byond:component_set_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, code, field_id, index, value)

/// Args: (maxx, maxy, maxz). Sizes the gas field (and the heat field) for
/// the map. Called at world start and when the map grows.
// /proc/auxmos_configure_world (verdigris/domains/gas/src/turf.rs)
/proc/vg_configure_world(max_x, max_y, max_z)
	var/static/__f = load_ext(VERDIGRIS, "byond:configure_world_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(max_x, max_y, max_z)

/// Arg: (mixture). Makes src into a copy of the argument mixture.
// /datum/gas_mixture/proc/copy_from (verdigris/domains/gas/src/lib.rs)
/proc/vg_copy_from_hook(src_ref, giver)
	var/static/__f = load_ext(VERDIGRIS, "byond:copy_from_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, giver)

/// Args: (coefficient). Divides all gases by this amount.
// /datum/gas_mixture/proc/divide (verdigris/domains/gas/src/lib.rs)
/proc/vg_divide_hook(src_ref, num_val)
	var/static/__f = load_ext(VERDIGRIS, "byond:divide_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, num_val)

// /proc/drain_dirty_gas_mixtures (verdigris/domains/gas/src/lib.rs)
/proc/vg_drain_dirty_gas_mixtures()
	var/static/__f = load_ext(VERDIGRIS, "byond:drain_dirty_gas_mixtures_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Drains dirty notifications and captures the control-relevant gas state in
/// one call, so sleeping air alarms evaluate thresholds without crossing the
/// FFI once per value. Flat stride: id, mask, revision, pressure,
/// temperature, volume, o2, co2, plasma, methane, n2o, volatile_fuel,
/// miasma, zauker, total_moles.
// /proc/drain_dirty_gas_observations (verdigris/domains/gas/src/lib.rs)
/proc/vg_drain_dirty_gas_observations()
	var/static/__f = load_ext(VERDIGRIS, "byond:drain_dirty_gas_observations_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

// /proc/drop_material_power_graph (verdigris/verdigris/src/material_power.rs)
/proc/vg_drop_material_power_graph(handle)
	var/static/__f = load_ext(VERDIGRIS, "byond:drop_material_power_graph_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(handle)

/// EMP severity around (`x`, `y`, `z`) with the four band radii in `ranges`
/// (non-decreasing). Returns `list(min_x, min_y, max_x, max_y, severity...)`
/// with severities in `block()` order over that square, clipped to the map:
/// 1 heavy .. 4 harmless, `n.5` a coin flip between `n` and `n + 1`.
// /proc/emp_falloff (verdigris/ffi/src/propagate.rs)
/proc/vg_emp_falloff(x, y, z, max_x, max_y, max_z, ranges)
	var/static/__f = load_ext(VERDIGRIS, "byond:emp_falloff_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(x, y, z, max_x, max_y, max_z, ranges)

/// Live entities (a reconciler/test metric).
// /proc/entity_count (verdigris/ffi/src/entity.rs)
/proc/vg_entity_count()
	var/static/__f = load_ext(VERDIGRIS, "byond:entity_count_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Test/reconciler hook: every live entity and the domains it has a
/// component in, as `[entity, domain, kind, cell, ...]` flat groups of 4.
// /proc/entity_debug_list (verdigris/ffi/src/entity.rs)
/proc/vg_entity_debug_list()
	var/static/__f = load_ext(VERDIGRIS, "byond:entity_debug_list_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// `vg_describe(atom)`: every attached component's fields, as one
/// semicolon-joined line (`domain field=value, field=value; domain ...`).
// /proc/entity_describe (verdigris/ffi/src/entity.rs)
/proc/vg_entity_describe(entity)
	var/static/__f = load_ext(VERDIGRIS, "byond:entity_describe_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity)

/// A safe probe for whether `entity_v` currently resolves to a live
/// component of `domain`/`kind`: `FALSE` for stale, out-of-range, unbound
/// (0), wrong-component or wrong-kind, never a runtime. `resolve()` (used
/// by every generated `get_*`/`set_*`) is deliberately not this: those must
/// error loudly (§5, §9). This exists for callers — admin tools, and tests
/// that check a handle is correctly rejected — that want the answer without
/// risking one (this codebase's test harness fails a "clean" run on any
/// runtime at all, caught or not).
// /proc/entity_is_valid (verdigris/ffi/src/entity.rs)
/proc/vg_entity_is_valid(entity, domain, kind)
	var/static/__f = load_ext(VERDIGRIS, "byond:entity_is_valid_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, domain, kind)

/// `SSvg`'s per-sweep maintenance for hosts not yet on the world's pacer
/// (the world itself is paced by `vg_world_tick`).
// /proc/entity_tick_all (verdigris/ffi/src/entity.rs)
/proc/vg_entity_tick_all()
	var/static/__f = load_ext(VERDIGRIS, "byond:entity_tick_all_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Generic unbind (J1's `pre_destroy()`, or today's earliest guaranteed
/// point — see `on_dematerialize()` in `atom_materialize.dm`): detaches
/// every domain's component from the entity through its registered handler,
/// then frees the entity itself. A zero/null handle (never bound, or
/// already unbound) is a silent no-op.
// /proc/entity_unbind (verdigris/ffi/src/entity.rs)
/proc/vg_entity_unbind(entity)
	var/static/__f = load_ext(VERDIGRIS, "byond:entity_unbind_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity)

/// Args: (list). Takes every gas in the list and makes them all identical, scaled to their respective volumes. The total heat and amount of substance in all of the combined gases is conserved.
// /proc/equalize_all_gases_in_list (verdigris/domains/gas/src/lib.rs)
/proc/vg_equalize_all_hook(gas_list)
	var/static/__f = load_ext(VERDIGRIS, "byond:equalize_all_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(gas_list)

/// Args: (mixture). Makes `src` a copy of `mixture`, with volumes taken into account.
// /datum/gas_mixture/proc/equalize_with (verdigris/domains/gas/src/lib.rs)
/proc/vg_equalize_with_hook(src_ref, total)
	var/static/__f = load_ext(VERDIGRIS, "byond:equalize_with_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, total)

/// For updating reagent gas fire products, do not use for now.
// /proc/finalize_gas_refs (verdigris/domains/gas/src/lib.rs)
/proc/vg_finalize_gas_refs()
	var/static/__f = load_ext(VERDIGRIS, "byond:finalize_gas_refs_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Args: (temperature). Returns: how much fuel for fire is in the mixture at the given temperature. If temperature is omitted, just uses current temperature instead.
// /datum/gas_mixture/proc/get_fuel_amount (verdigris/domains/gas/src/lib.rs)
/proc/vg_fuel_amount_hook(src_ref, temp)
	var/static/__f = load_ext(VERDIGRIS, "byond:fuel_amount_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, temp)

/// Test hook: runs `frames` gas frames to completion, one after another,
/// deterministically (no wall clock), and returns their events like
/// `gas_tick`.
// /proc/gas_run_frames (verdigris/domains/gas/src/turf.rs)
/proc/vg_gas_run_frames(frames)
	var/static/__f = load_ext(VERDIGRIS, "byond:gas_run_frames_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(frames)

/// `list(frames, commands, events, reactions, visuals, pressure, takes
/// reconciled, last tick µs, last frame µs, command backlog, overlay entries,
/// view age, frames skipped, removal shortfall (mol), fallback pieces applied,
/// fallback pieces rejected, mode, idle frames skipped, active chunks last
/// step)`.
// /proc/gas_stats (verdigris/domains/gas/src/turf.rs)
/proc/vg_gas_stats()
	var/static/__f = load_ext(VERDIGRIS, "byond:gas_stats_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// One SSair tick: pin the newest turf gas, collect its events and watch
/// wakes, apply heat, start the next frame. Never waits. Returns the events
/// as `GAS_EVENT_STRIDE` values each: `GAS_EVENT_*`, turf, value, other turf.
// /proc/gas_tick (verdigris/domains/gas/src/turf.rs)
/proc/vg_gas_tick()
	var/static/__f = load_ext(VERDIGRIS, "byond:gas_tick_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Conservation totals for tests: `list(moles, energy)` summed over every
/// main-owned mixture, pipe region and turf cell (pinned), plus what flowed
/// into reservoirs.
// /proc/gas_totals (verdigris/domains/gas/src/turf.rs)
/proc/vg_gas_totals()
	var/static/__f = load_ext(VERDIGRIS, "byond:gas_totals_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Args: (limit_x, limit_y, iterations, initial_wall_cell). Returns a flat
/// row-major DM list of 1/0 (wall/floor) of length limit_x * limit_y.
// /proc/generate_automata (verdigris/ffi/src/layout.rs)
/proc/vg_generate_automata(limit_x, limit_y, iterations, initial_wall_cell)
	var/static/__f = load_ext(VERDIGRIS, "byond:generate_automata_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(limit_x, limit_y, iterations, initial_wall_cell)

/// Args: (flag). As get_gases(), but only returns gases with the given flag.
// /datum/gas_mixture/proc/get_by_flag (verdigris/domains/gas/src/lib.rs)
/proc/vg_get_by_flag_hook(src_ref, flag_val)
	var/static/__f = load_ext(VERDIGRIS, "byond:get_by_flag_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, flag_val)

/// Returns: a flat list `id, moles, id, moles, ...` of every gas present in the
/// mixture, with numeric `GAS_ID_*` IDs. One call replaces a get_gases() plus a
/// get_moles() per gas.
// /datum/gas_mixture/proc/get_gases (verdigris/domains/gas/src/lib.rs)
/proc/vg_get_gases_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:get_gases_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Args: (gas_id). Returns: the amount of substance of the given gas, in moles.
// /datum/gas_mixture/proc/get_moles (verdigris/domains/gas/src/lib.rs)
/proc/vg_get_moles_hook(src_ref, gas_id)
	var/static/__f = load_ext(VERDIGRIS, "byond:get_moles_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, gas_id)

// /turf/proc/heat_add_turf (verdigris/ffi/src/heat.rs)
/proc/vg_heat_add_turf(turf, joules)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_add_turf_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turf, joules)

// /proc/heat_body_add (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_add(h, joules)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_add_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h, joules)

// /proc/heat_body_capacity (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_capacity(h, capacity)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_capacity_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h, capacity)

// /proc/heat_body_couple (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_couple(h, slot, target_kind, target_ref, conductance)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_couple_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h, slot, target_kind, target_ref, conductance)

/// Creates a heat body: capacity (J/K), temperature (K), coupling slot 0
/// (`HEAT_TARGET_*`, target, conductance), and whether DM keeps it. Returns
/// the entity handle, or null on failure.
// /proc/heat_body_create (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_create(capacity, temperature, target_kind, target_ref, conductance, keep)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_create_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(capacity, temperature, target_kind, target_ref, conductance, keep)

// /proc/heat_body_flow (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_flow(h)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_flow_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h)

// /proc/heat_body_keep (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_keep(h, keep)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_keep_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h, keep)

// /proc/heat_body_phase (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_phase(h, temperature, latent)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_phase_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h, temperature, latent)

// /proc/heat_body_power (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_power(h, watts)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_power_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h, watts)

/// Releases a body: settles it (if relaxing) into its environment,
/// deposits its excess over slot 0's environment there too, drops its
/// coupling entities and despawns it at once.
// /proc/heat_body_release (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_release(h)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_release_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h)

// /proc/heat_body_set_temperature (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_set_temperature(h, temperature)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_set_temperature_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h, temperature)

// /proc/heat_body_temperature (verdigris/ffi/src/heat.rs)
/proc/vg_heat_body_temperature(h)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_body_temperature_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(h)

/// Returns: Heat capacity, in J/K (probably).
// /datum/gas_mixture/proc/heat_capacity (verdigris/domains/gas/src/lib.rs)
/proc/vg_heat_cap_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_cap_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

// /turf/proc/heat_clear_turf (verdigris/ffi/src/heat.rs)
/proc/vg_heat_clear_turf(turf)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_clear_turf_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turf)

/// Sizes the world's grid for the map (`maxx`, `maxy`, `maxz`), the same
/// call site as `vg_configure_world` -- gas's own field is separate and
/// sized by that call already. Rebuilds the whole world only on the first
/// call (or if the current grid is already too small); once built, a
/// within-headroom call is a no-op, exactly as the pre-port `HeatWorld`
/// behaved.
// /proc/vg_heat_configure_world (verdigris/ffi/src/heat.rs)
/proc/vg_heat_configure_world(max_x, max_y, max_z)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_configure_world_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(max_x, max_y, max_z)

/// `list(TCMB, T0C, T20C, space sky temperature, Stefan-Boltzmann constant,
/// default emissivity, seconds per heat frame, normal body temperature,
/// human heat capacity, ignition temperature, vacuum heat capacity)`.
// /proc/heat_constants (verdigris/ffi/src/heat.rs)
/proc/vg_heat_constants()
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_constants_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Runs `frames` heat frames to completion, blocking. Unit tests only.
// /proc/heat_debug_run_frames (verdigris/ffi/src/heat.rs)
/proc/vg_heat_debug_run_frames(frames)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_debug_run_frames_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(frames)

/// Just the cooling-side Carnot-bounded COP (`cold`/`hot` in K), for a
/// caller that owns its own power-budget accounting (grid `draw_power()`)
/// and only wants the COP formula itself off DM -- a smaller surface than
/// [`heat_regulator_step`] for a machine that can't hand its whole budget
/// to the generic step without also rewriting how it draws from the power
/// grid.
///
/// # Errors
/// A non-numeric argument.
// /proc/heat_regulator_cooling_cop (verdigris/ffi/src/heat_regulator.rs)
/proc/vg_heat_regulator_cooling_cop(cold, hot, carnot_fraction, max_cop)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_regulator_cooling_cop_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(cold, hot, carnot_fraction, max_cop)

/// One regulator step. `other_capacity < 0` means an infinite (reservoir)
/// other side (space, a planet's atmosphere, an unlimited external loop).
/// Returns `list(work, moved, other)` (`RegulatorStep`'s three flows, W or
/// J per `dt`, matching whichever unit the caller passed capacities in).
///
/// # Errors
/// A non-numeric argument.
// /proc/heat_regulator_step (verdigris/ffi/src/heat_regulator.rs)
/proc/vg_heat_regulator_step(target, max_power, mode, carnot_fraction, max_cop, resistive_heating, deadband, controlled_capacity, controlled_temp, other_capacity, other_temp, dt)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_regulator_step_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(target, max_power, mode, carnot_fraction, max_cop, resistive_heating, deadband, controlled_capacity, controlled_temp, other_capacity, other_temp, dt)

/// Drops heat's coupling side table (`verdigris_cleanup`, a fresh round):
/// the world itself is rebuilt generically (`crate::entity::reset_all`).
// /proc/heat_reset (verdigris/ffi/src/heat.rs)
/proc/vg_heat_reset()
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_reset_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

// /turf/proc/heat_set_turf (verdigris/ffi/src/heat.rs)
/proc/vg_heat_set_turf(turf, kind, capacity, conductivity, emissivity, temperature, air)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_set_turf_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turf, kind, capacity, conductivity, emissivity, temperature, air)

// /turf/proc/heat_set_turf_temperature (verdigris/ffi/src/heat.rs)
/proc/vg_heat_set_turf_temperature(turf, temperature)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_set_turf_temperature_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turf, temperature)

// /proc/heat_set_turfs_bulk (verdigris/ffi/src/heat.rs)
/proc/vg_heat_set_turfs_bulk(records)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_set_turfs_bulk_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(records)

/// Takes every wake and `ThresholdSet` crossing collected since the last
/// call, as one flat list matching the pre-port wire format exactly:
/// `[wake count]`, then `[subscriber, watch, reason, source]` per wake,
/// then `[watch, payload, entered, generation]` per `ThresholdSet`
/// crossing. The world itself is driven by `SSvg`'s `vg_world_tick()`
/// (`code/controllers/subsystems/vg.dm`), not a heat-specific pacer, so
/// this bind only drains -- it never steps a frame.
// /proc/heat_take_wakes (verdigris/ffi/src/heat.rs)
/proc/vg_heat_take_wakes()
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_take_wakes_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Kept for DM ABI stability (SSair's `process_turf_heat()` still calls
/// it): returns whether any wakes/crossings are waiting. Never steps a
/// frame itself -- see [`heat_take_wakes`]'s doc.
// /datum/controller/subsystem/air/proc/heat_tick (verdigris/ffi/src/heat.rs)
/proc/vg_heat_tick(seconds)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_tick_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(seconds)

// /turf/proc/heat_turf_properties (verdigris/ffi/src/heat.rs)
/proc/vg_heat_turf_properties(turf)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_turf_properties_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turf)

// /turf/proc/heat_turf_temperature (verdigris/ffi/src/heat.rs)
/proc/vg_heat_turf_temperature(turf)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_turf_temperature_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(turf)

// /proc/heat_unwatch (verdigris/ffi/src/heat.rs)
/proc/vg_heat_unwatch(on_body, index, watch_generation)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_unwatch_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(on_body, index, watch_generation)

// /proc/heat_watch (verdigris/ffi/src/heat.rs)
/proc/vg_heat_watch(on_body, target_ref, subscriber, lane, kind, level, both)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_watch_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(on_body, target_ref, subscriber, lane, kind, level, both)

// /proc/heat_watch_set_add (verdigris/ffi/src/heat.rs)
/proc/vg_heat_watch_set_add(on_body, index, watch_generation, payload, generation, cmp, limit, both)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_watch_set_add_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(on_body, index, watch_generation, payload, generation, cmp, limit, both)

// /proc/heat_watch_set_remove (verdigris/ffi/src/heat.rs)
/proc/vg_heat_watch_set_remove(on_body, index, watch_generation, payload)
	var/static/__f = load_ext(VERDIGRIS, "byond:heat_watch_set_remove_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(on_body, index, watch_generation, payload)

/// This turf's gas revision (bumped whenever its gas changes).
// /turf/proc/air_revision (verdigris/domains/gas/src/turf.rs)
/proc/vg_hook_air_revision(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:hook_air_revision_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Returns: the amount of gas mixtures that are attached to a byond gas mixture.
// /datum/controller/subsystem/air/proc/get_amt_gas_mixes (verdigris/domains/gas/src/lib.rs)
/proc/vg_hook_amt_gas_mixes()
	var/static/__f = load_ext(VERDIGRIS, "byond:hook_amt_gas_mixes_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Registers gases, and get reaction infos for auxmos, only call when ssair is initing.
// /proc/auxtools_atmos_init (verdigris/domains/gas/src/lib.rs)
/proc/vg_hook_init(gas_data)
	var/static/__f = load_ext(VERDIGRIS, "byond:hook_init_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(gas_data)

/// Returns: the total amount of gas mixtures in the arena, including "free" ones.
// /datum/controller/subsystem/air/proc/get_max_gas_mixes (verdigris/domains/gas/src/lib.rs)
/proc/vg_hook_max_gas_mixes()
	var/static/__f = load_ext(VERDIGRIS, "byond:hook_max_gas_mixes_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// The mixture's gas revision (bumped whenever its gas changes).
// /datum/gas_mixture/proc/revision (verdigris/domains/gas/src/lib.rs)
/proc/vg_hook_mix_revision(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:hook_mix_revision_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Args: (flag, mask). Registers (flag >= 0) or removes (flag < 0) this
/// turf's gas and publishes its air-block mask (`AIR_BLOCK_KEEP` keeps the
/// current one). Reads blocks_air, air, immutable_atmos, planetary_atmos and
/// initial_gas_mix.
// /turf/proc/update_air_ref (verdigris/domains/gas/src/turf.rs)
/proc/vg_hook_register_turf(src_ref, flag, mask)
	var/static/__f = load_ext(VERDIGRIS, "byond:hook_register_turf_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, flag, mask)

/// Bulk registration for round start and map loads. Args: (turfs, flag),
/// where `turfs` is an assoc list of turf -> air-block mask.
// /proc/_auxmos_register_turfs_bulk (verdigris/domains/gas/src/turf.rs)
/proc/vg_hook_register_turfs_bulk(list, flag)
	var/static/__f = load_ext(VERDIGRIS, "byond:hook_register_turfs_bulk_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(list, flag)

/// Marks the mix as immutable, meaning it will never change. This cannot be undone.
// /datum/gas_mixture/proc/mark_immutable (verdigris/domains/gas/src/lib.rs)
/proc/vg_mark_immutable_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:mark_immutable_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Args: (mixture). Merges the gas from the giver into src, without modifying the giver mix.
// /datum/gas_mixture/proc/merge (verdigris/domains/gas/src/lib.rs)
/proc/vg_merge_hook(src_ref, giver)
	var/static/__f = load_ext(VERDIGRIS, "byond:merge_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, giver)

/// Args: (min_heat_cap). Sets the mix's minimum heat capacity.
// /datum/gas_mixture/proc/set_min_heat_capacity (verdigris/domains/gas/src/lib.rs)
/proc/vg_min_heat_cap_hook(src_ref, arg_min)
	var/static/__f = load_ext(VERDIGRIS, "byond:min_heat_cap_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, arg_min)

/// Args: (coefficient). Multiplies all gases by this amount.
// /datum/gas_mixture/proc/multiply (verdigris/domains/gas/src/lib.rs)
/proc/vg_multiply_hook(src_ref, num_val)
	var/static/__f = load_ext(VERDIGRIS, "byond:multiply_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, num_val)

/// Args: (temperature). Returns: how much oxidizer for fire is in the mixture at the given temperature. If temperature is omitted, just uses current temperature instead.
// /datum/gas_mixture/proc/get_oxidation_power (verdigris/domains/gas/src/lib.rs)
/proc/vg_oxidation_power_hook(src_ref, temp)
	var/static/__f = load_ext(VERDIGRIS, "byond:oxidation_power_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, temp)

/// Returns: true. Parses gas strings like "o2=2500;plasma=5000;TEMP=370" and turns src mixes into the parsed gas mixture, invalid patterns will be ignored
// /datum/gas_mixture/proc/__auxtools_parse_gas_string (verdigris/domains/gas/src/lib.rs)
/proc/vg_parse_gas_string(src_ref, string)
	var/static/__f = load_ext(VERDIGRIS, "byond:parse_gas_string_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, string)

/// Args: (gas_id). Returns the heat capacity from the given gas, in J/K (probably).
// /datum/gas_mixture/proc/partial_heat_capacity (verdigris/domains/gas/src/lib.rs)
/proc/vg_partial_heat_capacity(src_ref, gas_id)
	var/static/__f = load_ext(VERDIGRIS, "byond:partial_heat_capacity_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, gas_id)

/// Drops every port (a map reload).
// /proc/vg_pipe_clear (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_clear()
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_clear_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Commits pending topology and returns the regions DM must rebuild, one
/// header per changed or retired region: `region_slot, port_count,
/// prior_count, volume, ports..., prior_region_slots...` (`volume < 0`:
/// the region is gone) -- the exact wire shape `rust_apply_pipe_topology`
/// already parses.
// /proc/vg_pipe_commit (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_commit()
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_commit_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Connects two ports' nodes directly (`NetworkHost::connect_entities`,
/// bypassing any geometric connection rule -- pipes manage topology
/// explicitly).
// /proc/vg_pipe_connect (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_connect(port_a, port_b)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_connect_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(port_a, port_b)

// /proc/vg_pipe_device_remove (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_device_remove(id)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_device_remove_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(id)

/// Registers (or replaces) a region<->region device edge between two
/// ports. Carries no flow law of its own (`rust_architecture.md` §8.5 step
/// 6's pipe-device redesign): DM attaches that afterward by creating a
/// `/obj/effect/device_flow_row`/`device_valve_row` instance, binding it
/// (`vg_bind_gas`, generated), and setting its `device` field to this
/// device's `vg_entity` handle -- no bespoke bind here, just the generic
/// `vg_component_*` accessors every component gets.
// /proc/vg_pipe_device_set (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_device_set(id, port_a, port_b)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_device_set_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(id, port_a, port_b)

/// Registers (or replaces) a device edge between a port and a turf (a vent
/// pump or scrubber): `turf_mixture_handle` is the turf's gas-mixture
/// handle, not a port id. See [`pipe_device_set`]'s own docs on flows.
// /proc/vg_pipe_device_set_turf (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_device_set_turf(id, port_a, turf_mixture_handle)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_device_set_turf_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(id, port_a, turf_mixture_handle)

// /proc/vg_pipe_disconnect (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_disconnect(port_a, port_b)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_disconnect_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(port_a, port_b)

/// Removes a `DeviceFlow` row created by [`pipe_flow_set`]. `entity` is the
/// handle that call returned; a no-op for `0`.
// /proc/vg_pipe_flow_remove (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_flow_remove(entity)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_flow_remove_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity)

/// Creates (when `entity` is 0) or replaces (otherwise) one `DeviceFlow` row
/// on device `id` and returns its entity handle for DM to hold and pass back
/// next call. The row is a bare entity with no backing DM object at all --
/// `DeviceFlow`/`DeviceValve` rows are Rust-internal bookkeeping, never
/// placed as a `/obj/effect` map atom (`rust_architecture.md` §8.5 step 6's
/// pipe-device redesign) -- so every field, including the owning device's
/// link, is set in this one call instead of through the generated
/// per-type `vg_component_*` accessors a bound atom would otherwise use.
// /proc/vg_pipe_flow_set (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_flow_set(entity, id, gases, rate_kind, rate, direction, stop_side, stop_cmp, stop_kpa)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_flow_set_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, id, gases, rate_kind, rate, direction, stop_side, stop_cmp, stop_kpa)

/// Removes a port; its gas share is released, to `mixture_handle` if given
/// (else discarded -- `RUST_PIPE_OP_REMOVE`/`REMOVE_TO_MIXTURE`).
// /proc/vg_pipe_remove (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_remove(port_id, mixture_handle)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_remove_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(port_id, mixture_handle)

/// Runs every device edge's flow(s)/valve once for `dt` seconds -- region
/// <-> region edges directly, region<->turf edges (a vent pump/scrubber)
/// through `vg_gas::world`'s turf accessors (this module's own docs) --
/// and returns a flat `id, moles, power_w, target_reached` list per device
/// that moved something or drew power.
// /proc/vg_pipe_step_devices (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_step_devices(dt)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_step_devices_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(dt)

/// Adds a port holding the gas from `mixture_handle` (a `datum/gas_mixture`
/// handle; `0`/invalid: empty), or changes its volume if it already exists.
/// Mints a fresh entity for a new port. Returns whether it succeeded.
// /proc/vg_pipe_upsert (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_upsert(port_id, mixture_handle, volume)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_upsert_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(port_id, mixture_handle, volume)

/// See [`pipe_flow_remove`]'s own docs; the same for a `DeviceValve` row.
// /proc/vg_pipe_valve_remove (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_valve_remove(entity)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_valve_remove_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity)

/// See [`pipe_flow_set`]'s own docs; the same for a `DeviceValve` row.
// /proc/vg_pipe_valve_set (verdigris/ffi/src/pipes.rs)
/proc/vg_pipe_valve_set(entity, id, open)
	var/static/__f = load_ext(VERDIGRIS, "byond:pipe_valve_set_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, id, open)

// /proc/poll_material_power_graph (verdigris/verdigris/src/material_power.rs)
/proc/vg_poll_material_power_graph(handle)
	var/static/__f = load_ext(VERDIGRIS, "byond:poll_material_power_graph_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(handle)

/// Binds (or rebinds) `entity`'s node as a cable piece: `shape` is
/// `[x, y, z, d1, d2, up, down, link]`. `entity` `0`: mints a new one (a
/// cable has no component of its own). Returns the entity handle.
// /proc/vg_power_bind_cable (verdigris/ffi/src/power.rs)
/proc/vg_power_bind_cable(entity, shape)
	var/static/__f = load_ext(VERDIGRIS, "byond:power_bind_cable_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, shape)

/// Binds (or rebinds) `entity`'s node as a plain machine terminal at
/// `(x, y, z)`: a producer, an APC's own area terminal, or one of a SMES's
/// two terminals. `entity` must already exist (a `vg_component_bind` on
/// the matching component) -- unlike a cable, a machine terminal is never
/// topology-only.
// /proc/vg_power_bind_machine (verdigris/ffi/src/power.rs)
/proc/vg_power_bind_machine(entity, x, y, z)
	var/static/__f = load_ext(VERDIGRIS, "byond:power_bind_machine_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity, x, y, z)

/// Commits pending topology now, instead of at the next `vg_world_tick`
/// (an explosion or a construction burst wants its region split/merge
/// reflected before the next machinery tick reads it).
// /proc/vg_power_commit (verdigris/ffi/src/power.rs)
/proc/vg_power_commit()
	var/static/__f = load_ext(VERDIGRIS, "byond:power_commit_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// A mid-tick draw against `region`'s ledger, outside the normal
/// `ApcTick`/`PowerBalance` pass (the material power overlay paying its
/// resistive loss from the grid, `powernet.dm`'s `draw_power()`). Returns
/// what was delivered (never more than the region's remaining surplus).
// /proc/vg_power_region_draw (verdigris/ffi/src/power.rs)
/proc/vg_power_region_draw(region, watts)
	var/static/__f = load_ext(VERDIGRIS, "byond:power_region_draw_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(region, watts)

/// Every entity with a node on `region` (the material power overlay's cable
/// enumeration, `powernet.dm`'s `rebuild_material_cache()`).
// /proc/vg_power_region_members (verdigris/ffi/src/power.rs)
/proc/vg_power_region_members(region)
	var/static/__f = load_ext(VERDIGRIS, "byond:power_region_members_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(region)

/// `entity`'s region, `0` if it has none (never a runtime): a raw handle
/// plus one (`0` is DM's null), stable until the node's region changes.
// /proc/vg_power_region_of (verdigris/ffi/src/power.rs)
/proc/vg_power_region_of(entity)
	var/static/__f = load_ext(VERDIGRIS, "byond:power_region_of_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity)

/// A region's ledger: `avail, load, brown` (W, W, 0/1). Everything else
/// (a region's producers, consumers, SMES terminals) DM already knows --
/// it bound them.
// /proc/vg_power_region_read (verdigris/ffi/src/power.rs)
/proc/vg_power_region_read(region)
	var/static/__f = load_ext(VERDIGRIS, "byond:power_region_read_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(region)

/// Drops `entity`'s cable/machine node (the entity and any component it
/// holds are untouched; `entity_unbind`/`vg_component_detach` handle
/// those).
// /proc/vg_power_unbind_node (verdigris/ffi/src/power.rs)
/proc/vg_power_unbind_node(entity)
	var/static/__f = load_ext(VERDIGRIS, "byond:power_unbind_node_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(entity)

/// One radiation pulse from (`x`, `y`, `z`): returns the path transmission
/// to each target in `targets` (a flat list of `x, y, z`), or -1 for targets
/// out of `range`, on another z-level or off the grid. Rays stop early once
/// the transmission drops below `threshold`.
// /proc/radiation_pulse (verdigris/ffi/src/propagate.rs)
/proc/vg_radiation_pulse(x, y, z, range, threshold, targets)
	var/static/__f = load_ext(VERDIGRIS, "byond:radiation_pulse_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(x, y, z, range, threshold, targets)

/// Writes radiation transmission for changed turfs. `cells` is a flat list of
/// `x, y, z, transmission`. The field is sized to the plane `max_x` by
/// `max_y` (z-levels are added as written) and reset if the plane changes.
// /proc/radiation_set_cells (verdigris/ffi/src/propagate.rs)
/proc/vg_radiation_set_cells(max_x, max_y, cells)
	var/static/__f = load_ext(VERDIGRIS, "byond:radiation_set_cells_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(max_x, max_y, cells)

/// A linear model starting at `v0` now, changing by `rate` per tick,
/// clamped to [`min`, `max`] (null for unbounded). Returns the model id.
// /proc/rate_linear (verdigris/ffi/src/reactor.rs)
/proc/vg_rate_linear(v0, rate, min, max)
	var/static/__f = load_ext(VERDIGRIS, "byond:rate_linear_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(v0, rate, min, max)

/// The model's value now.
// /proc/rate_read (verdigris/ffi/src/reactor.rs)
/proc/vg_rate_read(model)
	var/static/__f = load_ext(VERDIGRIS, "byond:rate_read_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(model)

/// A model relaxing from `v0` toward `target` at `k` per tick
/// (`target + (v0 - target) e^(-k t)`). Returns the model id.
// /proc/rate_relax (verdigris/ffi/src/reactor.rs)
/proc/vg_rate_relax(v0, target, k)
	var/static/__f = load_ext(VERDIGRIS, "byond:rate_relax_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(v0, target, k)

/// Removes a model and its watches. Returns 1 if it was live.
// /proc/rate_remove (verdigris/ffi/src/reactor.rs)
/proc/vg_rate_remove(model)
	var/static/__f = load_ext(VERDIGRIS, "byond:rate_remove_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(model)

/// Sets a linear or sum model's value now (the rate continues from it).
// /proc/rate_set (verdigris/ffi/src/reactor.rs)
/proc/vg_rate_set(model, value)
	var/static/__f = load_ext(VERDIGRIS, "byond:rate_set_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(model, value)

/// Sets a linear model's rate per tick (or a relax model's target).
// /proc/rate_set_rate (verdigris/ffi/src/reactor.rs)
/proc/vg_rate_set_rate(model, rate)
	var/static/__f = load_ext(VERDIGRIS, "byond:rate_set_rate_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(model, rate)

/// Sets (or, with rate 0, removes) term `term` of a sum model.
// /proc/rate_set_term (verdigris/ffi/src/reactor.rs)
/proc/vg_rate_set_term(model, term, rate)
	var/static/__f = load_ext(VERDIGRIS, "byond:rate_set_term_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(model, term, rate)

/// A store with named inflow/outflow terms (`vg_rate_set_term`), clamped.
// /proc/rate_sum (verdigris/ffi/src/reactor.rs)
/proc/vg_rate_sum(v0, min, max)
	var/static/__f = load_ext(VERDIGRIS, "byond:rate_sum_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(v0, min, max)

/// Wakes `subscriber` whenever the model enters `cmp level` (0 above: `v >=
/// level`, 1 below), at the exact predicted crossing tick; at once if it
/// already holds. Returns the token.
// /proc/rate_watch (verdigris/ffi/src/reactor.rs)
/proc/vg_rate_watch(model, sub, lane_v, cmp_v, level)
	var/static/__f = load_ext(VERDIGRIS, "byond:rate_watch_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(model, sub, lane_v, cmp_v, level)

/// `REACT_AT`: wakes `subscriber` on `lane` at tick `tick` (a past tick fires
/// at the next step). Returns the token.
// /proc/react_at (verdigris/ffi/src/reactor.rs)
/proc/vg_react_at(sub, lane_v, tick)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_at_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(sub, lane_v, tick)

/// `REACT_CANCEL`: drops one subscription. Returns 1 if the token was live.
// /proc/react_cancel (verdigris/ffi/src/reactor.rs)
/proc/vg_react_cancel(token)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_cancel_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(token)

/// `REACT_CLEAR`: drops every subscription and pending wake of `subscriber`.
/// Returns how many subscriptions it had.
// /proc/react_clear (verdigris/ffi/src/reactor.rs)
/proc/vg_react_clear(sub)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_clear_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(sub)

/// Args: (holder). Runs all reactions on this gas mixture. Holder is used by the reactions, and can be any arbitrary datum or null.
// /datum/gas_mixture/proc/react (verdigris/domains/gas/src/lib.rs)
/proc/vg_react_hook(src_ref, holder)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, holder)

/// `REACT_ON_KEY`: wakes `subscriber` when key (`kind`, `id`) is published
/// with any bit of `mask`. Returns the token.
// /proc/react_on_key (verdigris/ffi/src/reactor.rs)
/proc/vg_react_on_key(sub, kind, id, mask, lane_v)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_on_key_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(sub, kind, id, mask, lane_v)

/// Writes one probe cell (the probe domain is DM-written; see module docs).
// /proc/react_probe_set (verdigris/ffi/src/reactor.rs)
/proc/vg_react_probe_set(cell, kpa, kelvin)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_probe_set_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(cell, kpa, kelvin)

/// `REACT_PUBLISH`: DM-owned state under key (`kind`, `id`) changed. Merged
/// per tick; a key nobody subscribes to costs a lookup and is not stored.
// /proc/react_publish (verdigris/ffi/src/reactor.rs)
/proc/vg_react_publish(kind, id, mask)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_publish_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(kind, id, mask)

/// Reactor counters as a flat list: timers pending, timers fired, rate
/// crossings fired, key publications, rate models, keys with subscribers,
/// live subscriptions, wakes received, merged, delivered, deferred, watch
/// wakes, backlog urgent/normal/background, last step microseconds.
// /proc/react_stats (verdigris/ffi/src/reactor.rs)
/proc/vg_react_stats()
	var/static/__f = load_ext(VERDIGRIS, "byond:react_stats_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// SSreactor's one call per tick. Advances to tick `now` (firing timers and
/// rate crossings, dispatching key publications), evaluates the domain
/// watches, and returns up to `budget` normal/background wakes (urgent ones
/// always) as a flat list, `REACT_WAKE_STRIDE` numbers per wake:
/// `subscriber, lane, reason, source, source_kind`. `source` is the cell of a
/// watch wake, the key id of a key wake (with `source_kind` its key kind), or
/// the model of a rate wake.
// /proc/react_step (verdigris/ffi/src/reactor.rs)
/proc/vg_react_step(now, budget)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_step_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(now, budget)

/// Live subscriptions of `subscriber` (tests and the audit).
// /proc/react_subscriptions (verdigris/ffi/src/reactor.rs)
/proc/vg_react_subscriptions(sub)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_subscriptions_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(sub)

/// `REACT_WHEN` band: wakes when `cell`'s channel `ch` moves into a
/// different band of the increasing `levels` list (and once at registration).
// /proc/react_watch_band (verdigris/ffi/src/reactor.rs)
/proc/vg_react_watch_band(domain, sub, lane, cell, ch, levels, hysteresis)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_watch_band_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(domain, sub, lane, cell, ch, levels, hysteresis)

/// `REACT_ON`: wakes when any channel in `mask` of `cell` moves past its
/// hysteresis. Returns the token.
// /proc/react_watch_changed (verdigris/ffi/src/reactor.rs)
/proc/vg_react_watch_changed(domain, sub, lane, cell, mask)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_watch_changed_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(domain, sub, lane, cell, mask)

/// `REACT_WHEN` difference: `a - b` (or `|a - b|` with `abs`) on channel
/// `ch` crosses `value` like a threshold.
// /proc/react_watch_difference (verdigris/ffi/src/reactor.rs)
/proc/vg_react_watch_difference(domain, sub, lane, a, b, ch, cmp, value, hysteresis, abs)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_watch_difference_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(domain, sub, lane, a, b, ch, cmp, value, hysteresis, abs)

/// `REACT_WHEN` threshold: `cmp` 0 above / 1 below `value` on channel `ch`;
/// `hysteresis` < 0 takes the channel's; `both_edges` also wakes on leaving.
// /proc/react_watch_threshold (verdigris/ffi/src/reactor.rs)
/proc/vg_react_watch_threshold(domain, sub, lane, cell, ch, cmp, value, hysteresis, both_edges)
	var/static/__f = load_ext(VERDIGRIS, "byond:react_watch_threshold_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(domain, sub, lane, cell, ch, cmp, value, hysteresis, both_edges)

/// Batched read. Args: (list of gas mixtures). Returns one flat list with, for
/// each mixture in order, `GAS_READ_HEADER` floats (pressure, temperature,
/// volume, total moles, heat capacity) followed by `GAS_ID_COUNT` mole counts.
/// A null or unregistered entry reads as all zeroes. Used by DM loops that used
/// to call several getters per mixture.
// /proc/read_mixtures (verdigris/domains/gas/src/lib.rs)
/proc/vg_read_mixtures(mixtures)
	var/static/__f = load_ext(VERDIGRIS, "byond:read_mixtures_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(mixtures)

/// Gives a new `/datum/gas_mixture` a main-owned slot sized from its
/// `initial_volume`, and writes the handle into it.
// /datum/gas_mixture/proc/__gasmixture_register (verdigris/domains/gas/src/lib.rs)
/proc/vg_register_gasmixture_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:register_gasmixture_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Args: (mixture, flag, amount). Takes `amount` from src that have the given `flag` and puts them into the given `mixture`. Returns: 0 if gas didn't have any with that flag, 1 if it did.
// /datum/gas_mixture/proc/__remove_by_flag (verdigris/domains/gas/src/lib.rs)
/proc/vg_remove_by_flag_hook(src_ref, into, flag_val, amount_val)
	var/static/__f = load_ext(VERDIGRIS, "byond:remove_by_flag_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, into, flag_val, amount_val)

/// Args: (mixture, amount). Takes the given amount of gas from src and puts it into the argument mixture. Amount is amount of substance in moles.
// /datum/gas_mixture/proc/__remove (verdigris/domains/gas/src/lib.rs)
/proc/vg_remove_hook(src_ref, into, amount_arg)
	var/static/__f = load_ext(VERDIGRIS, "byond:remove_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, into, amount_arg)

/// Args: (mixture, ratio). Takes the given ratio of gas from src and puts it into the argument mixture. Ratio is a number between 0 and 1.
// /datum/gas_mixture/proc/__remove_ratio (verdigris/domains/gas/src/lib.rs)
/proc/vg_remove_ratio_hook(src_ref, into, ratio_arg)
	var/static/__f = load_ext(VERDIGRIS, "byond:remove_ratio_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, into, ratio_arg)

/// Returns: the mix's pressure, in kilopascals.
// /datum/gas_mixture/proc/return_pressure (verdigris/domains/gas/src/lib.rs)
/proc/vg_return_pressure_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:return_pressure_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Returns: the mix's temperature, in kelvins.
// /datum/gas_mixture/proc/return_temperature (verdigris/domains/gas/src/lib.rs)
/proc/vg_return_temperature_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:return_temperature_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Returns: the mix's volume, in liters.
// /datum/gas_mixture/proc/return_volume (verdigris/domains/gas/src/lib.rs)
/proc/vg_return_volume_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:return_volume_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Args: (mixture, ratio, gas_list). Takes gases given by `gas_list` and moves `ratio` amount of those gases from `src` into `mixture`.
// /datum/gas_mixture/proc/scrub_into (verdigris/domains/gas/src/lib.rs)
/proc/vg_scrub_into_hook(src_ref, into, ratio_v, gas_list)
	var/static/__f = load_ext(VERDIGRIS, "byond:scrub_into_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, into, ratio_v, gas_list)

/// Args: (gas_id, moles). Sets the amount of substance of the given gas, in moles.
// /datum/gas_mixture/proc/set_moles (verdigris/domains/gas/src/lib.rs)
/proc/vg_set_moles_hook(src_ref, gas_id, amt_val)
	var/static/__f = load_ext(VERDIGRIS, "byond:set_moles_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, gas_id, amt_val)

/// Args: (temperature). Sets the temperature of the mixture. Will be set to 2.7 if it's too low.
// /datum/gas_mixture/proc/set_temperature (verdigris/domains/gas/src/lib.rs)
/proc/vg_set_temperature_hook(src_ref, arg_temp)
	var/static/__f = load_ext(VERDIGRIS, "byond:set_temperature_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, arg_temp)

/// Args: (volume). Sets the volume of the gas.
// /datum/gas_mixture/proc/set_volume (verdigris/domains/gas/src/lib.rs)
/proc/vg_set_volume_hook(src_ref, vol_arg)
	var/static/__f = load_ext(VERDIGRIS, "byond:set_volume_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, vol_arg)

/// Args: (links). One entry per z-level: the `UP`/`DOWN` bits of the levels
/// air may cross into. Vertical faces open only between linked levels.
// /datum/controller/subsystem/air/proc/auxmos_set_z_links (verdigris/domains/gas/src/turf.rs)
/proc/vg_set_z_links(links)
	var/static/__f = load_ext(VERDIGRIS, "byond:set_z_links_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(links)

// /proc/solve_material_power_graph (verdigris/verdigris/src/material_power.rs)
/proc/vg_solve_material_power_graph(topology, loads, warm)
	var/static/__f = load_ext(VERDIGRIS, "byond:solve_material_power_graph_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(topology, loads, warm)

// /proc/submit_material_power_graph (verdigris/verdigris/src/material_power.rs)
/proc/vg_submit_material_power_graph(handle, topology, loads, warm, generation)
	var/static/__f = load_ext(VERDIGRIS, "byond:submit_material_power_graph_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(handle, topology, loads, warm, generation)

/// Args: (amount). Subtracts the given amount from each gas.
// /datum/gas_mixture/proc/subtract (verdigris/domains/gas/src/lib.rs)
/proc/vg_subtract_hook(src_ref, num_val)
	var/static/__f = load_ext(VERDIGRIS, "byond:subtract_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, num_val)

/// Returns: the mix's thermal energy, the product of the mixture's heat capacity and its temperature.
// /datum/gas_mixture/proc/thermal_energy (verdigris/domains/gas/src/lib.rs)
/proc/vg_thermal_energy_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:thermal_energy_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Diagnostic invariant for shuttle and atmos tests: the turf's air datum
/// names its field cell (or the shared vacuum), and the cell's geometry is
/// what the turf's mask says.
// /proc/_auxmos_topology_matches (verdigris/domains/gas/src/turf.rs)
/proc/vg_topology_matches(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:topology_matches_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Returns: Amount of substance, in moles.
// /datum/gas_mixture/proc/total_moles (verdigris/domains/gas/src/lib.rs)
/proc/vg_total_moles_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:total_moles_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Args: (mixture, amount). Takes the `amount` given and transfers it from `src` to `mixture`.
// /datum/gas_mixture/proc/transfer_to (verdigris/domains/gas/src/lib.rs)
/proc/vg_transfer_hook(src_ref, other, moles)
	var/static/__f = load_ext(VERDIGRIS, "byond:transfer_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, other, moles)

/// Args: (mixture, ratio). Transfers `ratio` of `src` to `mixture`.
// /datum/gas_mixture/proc/transfer_ratio_to (verdigris/domains/gas/src/lib.rs)
/proc/vg_transfer_ratio_hook(src_ref, other, ratio)
	var/static/__f = load_ext(VERDIGRIS, "byond:transfer_ratio_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref, other, ratio)

/// Diagnostic: whether the turf's gas is still moving (some open edge is
/// not settled).
// /turf/proc/auxmos_is_atmos_active (verdigris/domains/gas/src/turf.rs)
/proc/vg_turf_active_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:turf_active_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

/// Frees a mixture's main-owned slot. Turf and pipe gas outlive their datums
/// (the cell and the region own it).
// /datum/gas_mixture/proc/__gasmixture_unregister (verdigris/domains/gas/src/lib.rs)
/proc/vg_unregister_gasmixture_hook(src_ref)
	var/static/__f = load_ext(VERDIGRIS, "byond:unregister_gasmixture_hook_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(src_ref)

// /proc/unwatch_dirty_gas_mixture (verdigris/domains/gas/src/lib.rs)
/proc/vg_unwatch_dirty_gas_mixture(id)
	var/static/__f = load_ext(VERDIGRIS, "byond:unwatch_dirty_gas_mixture_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(id)

/// For updating reaction informations for auxmos, only call this when it is changed.
// /datum/controller/subsystem/air/proc/auxtools_update_reactions (verdigris/domains/gas/src/lib.rs)
/proc/vg_update_reactions()
	var/static/__f = load_ext(VERDIGRIS, "byond:update_reactions_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

// /proc/verdigris_allocator_diagnostics (verdigris/ffi/src/lifecycle.rs)
/proc/vg_verdigris_allocator_diagnostics()
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_allocator_diagnostics_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Drop transient Rust-side state for a clean `/world/New()`
/// (`rust_bindings.md` §4: "world start ... resets every Rust store"). Every
/// registered entity domain (§1) drops its components and the entity table
/// itself is rebuilt, so no `vg_entity` handle survives into a new round.
// /proc/verdigris_cleanup (verdigris/ffi/src/lifecycle.rs)
/proc/vg_verdigris_cleanup()
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_cleanup_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

// /proc/verdigris_features (verdigris/ffi/src/lifecycle.rs)
/proc/vg_verdigris_features()
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_features_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

// /proc/verdigris_generate_station_layout (verdigris/ffi/src/layout.rs)
/proc/vg_verdigris_generate_station_layout(payload)
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_generate_station_layout_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(payload)

/// One-time global state init and the version handshake. DM calls this in
/// `/world/New()` before any other verdigris call, passing its generated
/// `VERDIGRIS_ABI`. Returns the library's ABI string; DM stops the boot when it
/// differs (a DLL and a DM build from different bind sets).
// /proc/verdigris_init (verdigris/ffi/src/lifecycle.rs)
/proc/vg_verdigris_init(dm_abi)
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_init_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(dm_abi)

/// Asks a job to stop; its result is dropped. Returns 1 if it was pending.
// /proc/verdigris_job_cancel (verdigris/ffi/src/jobs.rs)
/proc/vg_verdigris_job_cancel(job_id)
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_job_cancel_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(job_id)

/// Forgets a job and drops its result (cancelling it if still pending).
/// Returns 1 if the job existed.
// /proc/verdigris_job_finish (verdigris/ffi/src/jobs.rs)
/proc/vg_verdigris_job_finish(job_id)
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_job_finish_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(job_id)

/// A job's status: `PENDING`, `READY`, `CANCELLED` or `ERROR:<reason>`
/// (`ERROR:unknown job` once finished).
// /proc/verdigris_job_poll (verdigris/ffi/src/jobs.rs)
/proc/vg_verdigris_job_poll(job_id)
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_job_poll_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(job_id)

/// A job's progress in 0..1 (1 once it has finished; 0 if unknown).
// /proc/verdigris_job_progress (verdigris/ffi/src/jobs.rs)
/proc/vg_verdigris_job_progress(job_id)
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_job_progress_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(job_id)

/// Ids (decimal strings) of jobs that finished since the last call, for DM
/// code that prefers one completion sweep per tick over polling each job.
// /proc/verdigris_jobs_completed (verdigris/ffi/src/jobs.rs)
/proc/vg_verdigris_jobs_completed()
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_jobs_completed_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Every Rust metric in one call: a JSON object mapping each name to a
/// number (counters, gauges) or `{count,sum,max,bounds,buckets}`
/// (histograms). Includes `alloc.<tag>.current_bytes` / `peak_bytes` per
/// allocator tag and `alloc.heap.*` for the whole Rust heap.
// /proc/verdigris_metrics (verdigris/ffi/src/metrics.rs)
/proc/vg_verdigris_metrics()
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_metrics_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// One section of a finished plan (JSON): `header`, or rows
/// `[offset, offset + limit)` of an array section.
// /proc/verdigris_station_layout_section (verdigris/ffi/src/layout.rs)
/proc/vg_verdigris_station_layout_section(job_id, section, offset, limit)
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_station_layout_section_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(job_id, section, offset, limit)

/// Starts a station-layout planning job and returns its id. Plans for
/// different sites may run at once, so there is no supersede key. Poll with
/// `vg_verdigris_job_poll`, read with `vg_verdigris_station_layout_section`,
/// release with `vg_verdigris_job_finish`.
// /proc/verdigris_submit_station_layout (verdigris/ffi/src/layout.rs)
/proc/vg_verdigris_submit_station_layout(payload)
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_submit_station_layout_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(payload)

// /proc/verdigris_version (verdigris/ffi/src/lifecycle.rs)
/proc/vg_verdigris_version()
	var/static/__f = load_ext(VERDIGRIS, "byond:verdigris_version_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

// /proc/watch_dirty_gas_mixture (verdigris/domains/gas/src/lib.rs)
/proc/vg_watch_dirty_gas_mixture(id, interest_mask)
	var/static/__f = load_ext(VERDIGRIS, "byond:watch_dirty_gas_mixture_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(id, interest_mask)

/// Every typed event since the last call, as `vg_core::event`'s wire form
/// (`header, entity, len, payload...` per record). The generated DM
/// `vg_drain_events()` decodes it and dispatches each record.
// /proc/vg_world_events (verdigris/ffi/src/world.rs)
/proc/vg_world_events()
	var/static/__f = load_ext(VERDIGRIS, "byond:world_events_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Per-law statistics, as `name phase stepped awake` lines.
// /proc/vg_world_laws (verdigris/ffi/src/world.rs)
/proc/vg_world_laws()
	var/static/__f = load_ext(VERDIGRIS, "byond:world_laws_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()

/// Pacing: feeds `seconds` of game time to the world's pacer and runs a
/// step when one is owed. Returns whether a step ran.
// /proc/vg_world_tick (verdigris/ffi/src/world.rs)
/proc/vg_world_tick(seconds)
	var/static/__f = load_ext(VERDIGRIS, "byond:world_tick_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)(seconds)

/// Conservation violations since the last call, as text (empty: none).
// /proc/vg_world_violations (verdigris/ffi/src/world.rs)
/proc/vg_world_violations()
	var/static/__f = load_ext(VERDIGRIS, "byond:world_violations_ffi")
	VG_COUNT_FFI_CALL
	return call_ext(__f)()
