// THIS FILE IS GENERATED by tools/build/lib/verdigris_bindings.ts from the
// #[vg::component]/#[vg::query]/#[vg::events] declarations in verdigris/.
// Do not edit it by hand: run `tools/build/build.sh verdigris-bindings`.
// CI fails when it is stale. See doc/rewrite/rust_bindings.md.

/atom/movable
	/// The entity handle (rust_bindings.md §1). 0: unbound.
	var/tmp/vg_entity = 0
	/// Which gas component kind (a VG_GAS_* define), or 0.
	var/tmp/vg_gas = 0

/// Binds this atom's gas component (if the type declares one) and
/// returns the (possibly newly created) entity handle. Overridden per
/// bound type below.
/atom/movable/proc/vg_bind_gas(entity)
	return entity

/// Reconciler (§7): mismatches between this atom's declared inputs and
/// what Rust has stored for its gas component, repairing as it goes.
/// Overridden per bound type below.
/atom/movable/proc/vg_reconcile_gas()
	return list()

// ---- Pump (gas kind 1; verdigris/domains/gas/src/kind/pump.rs) ----

#define VG_GAS_PUMP 1

/obj/machinery/atmospherics/binary/pump
	vg_gas = VG_GAS_PUMP

/obj/machinery/atmospherics/binary/pump/var/tmp/init_target_pressure = 101.325
/obj/machinery/atmospherics/binary/pump/var/tmp/init_power_rating = 7500.0
/obj/machinery/atmospherics/binary/pump/var/tmp/init_on = FALSE

#define VG_PUMP_TARGET_PRESSURE_MIN 0
#define VG_PUMP_TARGET_PRESSURE_MAX 15000
#define VG_PUMP_POWER_RATING_MIN 0
#define VG_PUMP_POWER_RATING_MAX 60000

/// kPa; clamped to VG_PUMP_TARGET_PRESSURE_MIN..MAX.
/obj/machinery/atmospherics/binary/pump/proc/get_target_pressure()
	return vg_pump_get_target_pressure(vg_entity) // kPa

/// Returns the stored value.
/obj/machinery/atmospherics/binary/pump/proc/set_target_pressure(value)
	return vg_pump_set_target_pressure(vg_entity, value)

/// W; clamped to VG_PUMP_POWER_RATING_MIN..MAX.
/obj/machinery/atmospherics/binary/pump/proc/get_power_rating()
	return vg_pump_get_power_rating(vg_entity) // W

/// Returns the stored value.
/obj/machinery/atmospherics/binary/pump/proc/set_power_rating(value)
	return vg_pump_set_power_rating(vg_entity, value)

/// unitless;.
/obj/machinery/atmospherics/binary/pump/proc/get_on()
	return vg_pump_get_on(vg_entity)

/// Returns the stored value.
/obj/machinery/atmospherics/binary/pump/proc/set_on(value)
	return vg_pump_set_on(vg_entity, value)

/// mol/s, read-only (state).
/obj/machinery/atmospherics/binary/pump/proc/get_flow_rate()
	return vg_pump_get_flow_rate(vg_entity) // mol/s

/// Pure proc over Pump's declared input sources (construction, integrity).
/// Override per subtype if the default doesn't apply.
/obj/machinery/atmospherics/binary/pump/proc/pump_input_operable()
	return FALSE

/// What Rust currently has stored, for the reconciler (§7). Compare
/// against pump_input_operable(); never used for game logic.
/obj/machinery/atmospherics/binary/pump/proc/get_operable()
	return vg_pump_get_operable(vg_entity)

/// target_pressure, power_rating, on, flow_rate in one call.
/obj/machinery/atmospherics/binary/pump/proc/pump_query_ui()
	return vg_pump_query_ui(vg_entity)

/obj/machinery/atmospherics/binary/pump/vg_bind_gas(entity)
	return vg_pump_bind(entity, init_target_pressure, init_power_rating, init_on, pump_input_operable())

/// Compares every declared input against what Rust has stored (§7);
/// repairs any mismatch and returns "field: expected=.. actual=.." for
/// each one (empty: no divergence).
/obj/machinery/atmospherics/binary/pump/proc/pump_reconcile()
	var/list/mismatches = list()
	var/expected_operable = pump_input_operable()
	var/actual_operable = get_operable()
	if(!expected_operable != !actual_operable)
		mismatches += "operable: expected=[expected_operable] actual=[actual_operable]"
		vg_pump_push_operable(vg_entity, expected_operable)
	return mismatches

/obj/machinery/atmospherics/binary/pump/vg_reconcile_gas()
	return pump_reconcile()

// integrity (class 3): pushes Pump's operable when it changes.
/obj/machinery/atmospherics/binary/pump/atom_break(damage_flag)
	. = ..()
	if(vg_entity)
		vg_pump_push_operable(vg_entity, pump_input_operable())

/obj/machinery/atmospherics/binary/pump/atom_fix()
	. = ..()
	if(vg_entity)
		vg_pump_push_operable(vg_entity, pump_input_operable())

#define VG_PUMP_EVENT_TARGET_REACHED 0
#define VG_PUMP_EVENT_STARVED 1

/// Generated no-op default. Override to react to the event.
/obj/machinery/atmospherics/binary/pump/proc/on_pump_target_reached()
	return

/// Generated no-op default. Override to react to the event.
/obj/machinery/atmospherics/binary/pump/proc/on_pump_starved()
	return

// ---- One entry point per bound atom -------------------------------------

/// Binds every component this atom's type declares (base on_materialize(), L2).
/atom/movable/proc/vg_bind()
	var/entity = 0
	if(vg_gas)
		entity = vg_bind_gas(entity)
	vg_entity = entity

/// Every declared-input mismatch across every bound domain (§7). SSvg's
/// sweep and the test sandbox teardown call this per atom.
/atom/movable/proc/vg_reconcile()
	if(!vg_entity)
		return list()
	var/list/mismatches = list()
	if(vg_gas)
		mismatches += vg_reconcile_gas()
	return mismatches
