// THIS FILE IS GENERATED by tools/build/lib/verdigris_bindings.ts.
// Do not edit it by hand: run `tools/build/build.sh verdigris-bindings`.

/datum/object_model/rust_component/pump
	domain = "gas"
	domain_id = VG_DOMAIN_GAS
	kind = 1
	dm_type = /obj/machinery/atmospherics/binary/pump
	fields = list(
		"target_pressure" = list("role" = "config", "value_type" = "f32", "array" = FALSE, "unit" = "kPa", "min" = 0, "max" = 15000, "default" = 101.325, "on_invalid" = "clamp"),
		"power_rating" = list("role" = "config", "value_type" = "f32", "array" = FALSE, "unit" = "W", "min" = 0, "max" = 60000, "default" = 7500.0, "on_invalid" = "clamp"),
		"on" = list("role" = "config", "value_type" = "bool", "array" = FALSE, "unit" = null, "min" = null, "max" = null, "default" = FALSE, "on_invalid" = "clamp"),
		"operable" = list("role" = "input", "value_type" = "bool", "array" = FALSE, "unit" = null, "min" = null, "max" = null, "default" = null, "on_invalid" = "clamp"),
		"flow_rate" = list("role" = "state", "value_type" = "f32", "array" = FALSE, "unit" = "mol/s", "min" = null, "max" = null, "default" = null, "on_invalid" = "clamp"),
	)

/datum/object_model/rust_component/pump/bind(atom/movable/entity, handle, list/config)
	if(!istype(entity, /obj/machinery/atmospherics/binary/pump))
		return 0
	var/obj/machinery/atmospherics/binary/pump/target = entity
	return vg_pump_bind(handle, config["target_pressure"], config["power_rating"], config["on"], target.pump_input_operable())

/datum/object_model/rust_component/pump/dispatch_event(atom/movable/entity, event_id)
	switch(event_id)
		if(0)
			om_emit(entity, /datum/object_model/event/rust/pump_target_reached)
		if(1)
			om_emit(entity, /datum/object_model/event/rust/pump_starved)

/datum/object_model/event/rust/pump_target_reached

/datum/object_model/event/rust/pump_starved

/datum/object_model/rust_component/gas_mix
	domain = "gas"
	domain_id = VG_DOMAIN_GAS
	kind = 2
	dm_type = /obj/item/gas_mix_holder
	fields = list(
		"moles" = list("role" = "config", "value_type" = "array", "array" = TRUE, "unit" = "mol", "min" = 0, "max" = 1000000, "default" = null, "on_invalid" = "clamp"),
		"temperature" = list("role" = "config", "value_type" = "f32", "array" = FALSE, "unit" = "K", "min" = 2.7, "max" = 10000, "default" = T20C, "on_invalid" = "clamp"),
		"volume" = list("role" = "config", "value_type" = "f32", "array" = FALSE, "unit" = "L", "min" = 0, "max" = 100000, "default" = 70.0, "on_invalid" = "clamp"),
	)

/datum/object_model/rust_component/gas_mix/bind(atom/movable/entity, handle, list/config)
	if(!istype(entity, /obj/item/gas_mix_holder))
		return 0
	return vg_gas_mix_bind(handle, config["temperature"], config["volume"])

/datum/object_model/rust_component/gas_mix/dispatch_event(atom/movable/entity, event_id)
	switch(event_id)
		if(0)
			om_emit(entity, /datum/object_model/event/rust/gas_mix_overpressure)
		if(1)
			om_emit(entity, /datum/object_model/event/rust/gas_mix_depleted)

/datum/object_model/event/rust/gas_mix_overpressure

/datum/object_model/event/rust/gas_mix_depleted

