[package]
name = "dm-analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
dm-ir = { path = "../dm-ir" }
dm-semantics = { path = "../dm-semantics" }
dm-syntax = { path = "../dm-syntax" }
dm-preprocess = { path = "../dm-preprocess" }
dm-store = { path = "../dm-store" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
