// after_init(delay, handler): a one-shot timer armed when the holder initializes (doc/rewrite/reactions.md section 4).
// The foundation form of DECLARE_START_TIMER (code/__defines/lifecycle_decl.dm, which stays until its sites move).
//
//	/obj/item/broken_gun/reactions()
//		. = ..()
//		. += after_init(30 SECONDS, PROC_REF(validate_gun_type))
//
// `delay` is a time, or nameof() a holder var read per instance when it is armed (`after_init(nameof(fuse_time),
// PROC_REF(detonate))`). The timer is armed by rx_enrol(): in caps_init() for an atom (the end of /atom/Initialize(),
// so a subtype's Initialize() has run its `. = ..()` part), in /datum/New() for another datum on the boot list. It is
// an ordinary after() on the holder (rx_after(), CLOCK_OWN): dropped with it, paused with its clock. A subtype that
// declares after_init() with the same handler replaces the inherited one (the last declaration of a handler wins).
//
// The boot list (rx_boot_types(), generated by tools/ci/derived_reads_lint.py --fix-generated) marks a type whose
// reactions() declare after_init() with RXB_INIT, so a type without one builds nothing at init.
//
// Self-contained on purpose: the reaction table (reactions.dm) ignores this kind; the per-type list is built here
// from the same reactions() list.

/// A one-shot handler() call `delay` after the holder initializes. delay: a time, or nameof() a holder var.
/proc/after_init(delay, handler)
	var/datum/reaction/R = rx_make(RXN_AFTER_INIT, null, null, handler)
	R.interval = delay
	R.sig = "[R.sig]|[delay]"
	return R

/// type -> the after_init() reactions its reactions() declare (last declaration of a handler wins), or 0 for none.
GLOBAL_LIST_EMPTY(rx_after_inits)

/// D's type's after_init() reactions (a shared list), or null.
/proc/rx_after_inits_of(datum/D)
	RETURN_TYPE(/list)
	var/list/cache = GLOB?.rx_after_inits
	var/known = cache?[D.type]
	if(!isnull(known))
		return known || null
	var/list/by_handler = list()
	for(var/datum/reaction/R in type_list(D, TYPE_PROC_REF(/datum, reactions)))
		if(R.kind == RXN_AFTER_INIT)
			by_handler["[R.handler]"] = R
	var/list/found
	for(var/handler in by_handler)
		LAZYADD(found, by_handler[handler])
	if(cache)
		cache[D.type] = found || 0
	return found

/// Arms D's after_init() timers. rx_enrol() calls it once per holder, at init.
/proc/rx_arm_after_init(datum/D)
	for(var/datum/reaction/R as anything in rx_after_inits_of(D))
		var/delay = istext(R.interval) ? D.vars[R.interval] : R.interval
		rx_after(D, isnum(delay) ? max(delay, 0) : 0, R.handler)
