// the underfloor wiring terminal for the APC
// autogenerated when an APC is placed
// all conduit connects go to this object instead of the APC
// using this solves the problem of having the APC in a wall yet also inside an area

/obj/machinery/power/terminal
	name = "terminal"
	icon_state = "term"
	desc = "It's an underfloor wiring terminal for power equipment."
	level = 1
	var/master_handle
	anchored = TRUE
	plane = PLATING_PLANE
	layer = WIRES_LAYER+0.01

/obj/machinery/power/terminal/Initialize(mapload)
	. = ..()
	var/turf/T = src.loc
	if(level==1) hide(!T.is_plating())

// LIFECYCLE: its master disconnects the terminal.
/obj/machinery/power/terminal/Destroy()
	if(master())
		master().disconnect_terminal(src)
		master_handle = null
	return ..()

/obj/machinery/power/terminal/hide(i)
	invisibility = i ? INVISIBILITY_ABSTRACT : INVISIBILITY_NONE
	icon_state = i ? "term-f" : "term"

/obj/machinery/power/terminal/hides_under_flooring()
	return 1

/obj/machinery/power/terminal/overload(obj/machinery/power/source)
	if(master())
		master().overload(source)

/// LC-refs: the master this refers to -- an OM handle (om_handle()), so it reads null once that is deleted.
/obj/machinery/power/terminal/proc/master() as /obj/machinery/power
	return om_resolve(master_handle)
