/atom/proc/stumble_into(mob/living/M)
	play_sfx(src, SFX_PUNCH, 0.5, extrarange = -1)
	visible_message(span_warning("[M] [pick("ran", "slammed")] into \the [src]!"))
	to_chat(M, span_warning("You just [pick("ran", "slammed")] into \the [src]!"))
	M.injure(INJURY_BLUNT, 5, null, src)
	M.status_at_least(STAT_WEAKENED, 2)
	M.stop_flying()

/obj/structure/table/stumble_into(mob/living/M)
	var/obj/occupied = can_climb_turf(src)
	if(occupied)
		return ..()
	if(material())
		playsound(src, material().tableslam_noise, 25, 1, -1)
	else
		play_sfx(src, SFX_WEAPONS_TABLEHIT1)
	visible_message(span_warning("[M] flopped onto \the [src]!"))
	M.injure(INJURY_BLUNT, 5, null, src)
	M.status_at_least(STAT_WEAKENED, 2)
	M.forceMove(get_turf(src))
	M.stop_flying()

/obj/machinery/disposal/stumble_into(mob/living/M)
	play_sfx(src, SFX_EFFECTS_CLANG)
	visible_message(span_warning("[M] [pick("tripped", "stumbled")] into \the [src]!"))
	log_and_message_admins("stumbled into \the [src]", M)
	M.injure(INJURY_BLUNT, 5, null, src)
	M.status_at_least(STAT_WEAKENED, 2)
	M.forceMove(src)
	M.stop_flying()
	update_icon()

/obj/structure/inflatable/stumble_into(mob/living/M)
	playsound(src, "sound/effects/Glasshit.ogg", 25, 1, -1)
	visible_message(span_warning("[M] [pick("ran", "slammed")] into \the [src]!"))
	M.status_at_least(STAT_WEAKENED, 1)
	M.stop_flying()

/obj/structure/kitchenspike/stumble_into(mob/living/M)
	playsound(src, "sound/weapons/pierce.ogg", 25, 1, -1)
	visible_message(span_warning("[M] [pick("ran", "slammed")] into the spikes on \the [src]!"))
	M.injure(INJURY_PIERCE, 15, null, src)
	M.status_at_least(STAT_WEAKENED, 5)
	M.stop_flying()

/obj/structure/m_tray/stumble_into(mob/living/M)
	play_sfx(src, SFX_WEAPONS_TABLEHIT1)
	visible_message(span_warning("[M] flopped onto \the [src]!"))
	M.injure(INJURY_BLUNT, 5, null, src)
	M.status_at_least(STAT_WEAKENED, 2)
	M.forceMove(get_turf(src))
	M.stop_flying()

/obj/structure/c_tray/stumble_into(mob/living/M)
	play_sfx(src, SFX_WEAPONS_TABLEHIT1)
	visible_message(span_warning("[M] flopped onto \the [src]!"))
	M.injure(INJURY_BLUNT, 5, null, src)
	M.status_at_least(STAT_WEAKENED, 2)
	M.forceMove(get_turf(src))
	M.stop_flying()

/obj/structure/window/stumble_into(mob/living/M)
	visible_message(span_warning("[M] [pick("ran", "slammed")] into \the [src]!"))
	M.injure(INJURY_BLUNT, 5, null, src)
	M.status_at_least(STAT_WEAKENED, 2)
	hitby(M)
	M.stop_flying()

/obj/structure/railing/stumble_into(mob/living/M)
	var/obj/occupied = can_climb_turf(src)
	if(occupied)
		return ..()
	play_sfx(src, SFX_MISC_SLIP)
	visible_message(span_warning("[M] [pick("tripped", "stumbled")] over \the [src]!"))
	M.status_at_least(STAT_WEAKENED, 2)
	M.stop_flying()
	if(get_turf(M) == get_turf(src))
		var/turf/T = get_step(src, src.dir)
		if(T?.Enter(M, get_turf(src)))
			M.forceMove(T)
	else
		M.forceMove(get_turf(src))

/obj/machinery/door/window/stumble_into(mob/living/M)
	..()
	bumpopen(M)

/obj/machinery/door/airlock/stumble_into(mob/living/M)
	..()
	if(!shocks_bumper(M))
		bumpopen(M)

/obj/machinery/appliance/cooker/fryer/stumble_into(mob/living/M)
	visible_message(span_warning("[M] [pick("ran", "slammed")] into \the [src]!"))
	M.injure(INJURY_BURN, 15, null, src)
	M.status_at_least(STAT_WEAKENED, 5)
	M.emote("scream")
	M.stop_flying()

// cryo_cell deleted with ZAS unary atmos machinery; stumble override removed.

/obj/machinery/porta_turret/stumble_into(mob/living/M)
	..()
	if(!attacked && !emag_emagged(src))
		set_attacked(TRUE)
		after(src, 6 SECONDS, PROC_REF(calm_down), key = "grudge")

// space_heater (spaceheater.dm) deleted with ZAS atmos machinery;
// stumble override removed.

/obj/machinery/suit_storage_unit/stumble_into(mob/living/M)
	if(!ishuman(M) || !isopen || !ispowered || isbroken || src?.slot_item(OCCUPANT_SLOT_SUIT_STORAGE) || HELMET || SUIT)
		return ..()
	play_sfx(src, SFX_EFFECTS_CLANG)
	visible_message(span_warning("[M] [pick("tripped", "stumbled")] into \the [src]!"))
	if(!move_into(src, OCCUPANT_SLOT_SUIT_STORAGE, M))
		return ..()
	set_isopen(0)
	changed(src)
	add_fingerprint(M)
	M.stop_flying()

/obj/machinery/vending/stumble_into(mob/living/M)
	..()
	if(prob(2))
		throw_item()
