#!/usr/bin/env python3
"""Generates tools/dx/capability_varmap.json (the table convert_map_capabilities.py reads) from the capability
declarations in code/, so the converter covers every converted type, now and as waves convert more.

    python tools/dx/gen_capability_varmap.py             # rewrite the json
    python tools/dx/gen_capability_varmap.py --check     # CI: exit 1 when the committed json is stale
    python tools/dx/gen_capability_varmap.py --selftest
    python tools/dx/gen_capability_varmap.py --list      # per type: bits it can carry, and the rules emitted

What it reads
  * every `/T/capabilities()` proc body and every `CAPABILITY(T, entry)` line under code/ (unit-test and
    benchmark fixtures are skipped);
  * the global bundle procs of code/datums/capabilities/ (`machine_basics`, `wall_machine`, `maintenance_hatch`,
    `door`, `console`, ...), resolved recursively down to library constructors (`cap_panel`, `cap_bolts`, ...);
  * `cap_state = CAP_A|CAP_B` type defaults;
  * code/__defines/cap_bits.dm for the bit names.

How a type's carried bits are found
  * `. = ..()` inherits the nearest ancestor (by type path prefix) that declares capabilities; a body without it
    starts empty.
  * `. += name(...)` adds a library constructor's bits (CONSTRUCTOR_BITS) or, for a bundle, the union of everything
    its body calls (a bundle's `if(x)` branches count: a bit it can carry is a bit a map may set).
  * `. = without(., X)` / `replace(., X, ...)` drop what X contributed, where X is a `/datum/capability/x` type or a
    CAP_* op key (`emag_op` is CAP_EMAG); the replacement's own calls are then added.
  * `refine(...)` and `cap_require(...)` edit an operation in place: they carry no state bit.
  * STATE_HOLDERS lists types whose bits come from base code, not a capabilities() (the door base).

Each carried bit is mapped back to the legacy var(s) maps used (BIT_VARS, then FAMILY_VARS per type family), only
when the type carries that bit: a var whose bit the type cannot carry is not mapped (left alone, rule H1).
"""
import argparse
import collections
import json
import os
import re
import sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "tools", "dx", "capability_varmap.json")
BITS_FILE = os.path.join(ROOT, "code", "__defines", "cap_bits.dm")
LIB_DIR = os.path.join("code", "datums", "capabilities")
SKIP_DIRS = ("code/modules/unit_tests/", "code/modules/benchmarks/")

DOC = (
    "Type path prefix -> rules. Longest prefix (on a path-segment boundary) wins. Var spec: \"CAP_X\" (truthy value "
    "sets the bit, falsy clears it), {\"<value>\": \"CAP_X\" | null, ...} (value-mapped; null = no bit), \"drop\" "
    "(delete the varedit), \"keep\" (leave untouched). _default_bits: the cap_state bits the TYPE sets by default "
    "(so a falsy varedit such as locked = 0 can clear them, and a result equal to the default emits no varedit). "
    "Per-instance config vars (req_access, req_one_access, id_tag, frequency...) are never listed: H1 keeps them as "
    "instance vars. GENERATED by tools/dx/gen_capability_varmap.py from the capability declarations: edit the "
    "generator's tables, not this file."
)

# ---- what each library constructor carries -------------------------------------------------------------------
# constructor proc -> (the /datum/capability type it builds, the cap_state bits it owns). A bundle is NOT listed: it
# is resolved from its body. Verified against code/datums/capabilities/library/*.dm (the "State:" header of each).
CONSTRUCTOR_BITS = {
    "cap_panel": ("/datum/capability/panel", ["CAP_PANEL_OPEN"]),
    "cap_cover": ("/datum/capability/cover", ["CAP_COVER_OPEN"]),  # + CAP_COVER_REMOVED with removable = TRUE
    "cap_lock": ("/datum/capability/lock", ["CAP_LOCKED"]),
    "cap_emag": ("/datum/capability/emag", ["CAP_EMAGGED"]),
    "emag_op": (None, ["CAP_EMAGGED"]),  # the emag's state lives with the op when the hatch declares it
    "cap_breakable": ("/datum/capability/breakable", ["CAP_BROKEN"]),
    "cap_wires": ("/datum/capability/wires", []),  # exposed = every `behind` open; CAP_WIRES_EXPOSED only by explicit set
    "cap_bolts": ("/datum/capability/bolts", ["CAP_BOLTED"]),
    "cap_weld_shut": ("/datum/capability/weld_shut", ["CAP_WELDED"]),
    "cap_emergency_access": ("/datum/capability/emergency_access", ["CAP_EMERGENCY_ACCESS"]),
    "cap_reagent_container": ("/datum/capability/reagent_container", []),  # CAP_LID_OPEN with lid = TRUE
    "cap_smokable": ("/datum/capability/smokable", ["CAP_LIT"]),
    "cap_two_handed": ("/datum/capability/two_handed", ["CAP_WIELDED"]),
}
# CAP_* op keys that `without()` / `refine()` may name, -> the constructor whose entry they are.
OP_KEYS = {"CAP_EMAG": "emag_op", "CAP_LOCK": "lock_op"}
# Constructors with an extra bit under a named argument that must be literally TRUE at the call.
ARG_BITS = {("cap_cover", "removable"): ["CAP_COVER_REMOVED"], ("cap_reagent_container", "lid"): ["CAP_LID_OPEN"]}
# Bundle args that forward to such a constructor argument: (bundle, bundle arg) -> (constructor, constructor arg).
ARG_FORWARD = {("maintenance_hatch", "removable_cover"): ("cap_cover", "removable")}

# Types whose bits come from base code, not a capabilities() proc. The door base reads panel_is_open()/is_welded()
# for every door (shutters, blast doors), but only the airlock declares the capabilities that own them.
STATE_HOLDERS = {
    "/obj/machinery/door": ["CAP_PANEL_OPEN", "CAP_WELDED"],
}

# ---- bit -> the legacy var(s) maps used ------------------------------------------------------------------------
# Legacy var -> candidate bits, in priority order; the first bit the type carries wins (so `locked` is the bolts on
# a door, which has cap_bolts and no cap_lock, and the ID lock on an APC). A var maps only to a carried bit.
#   locked  : /obj/machinery `locked` (machinery_fields.dm); airlock `locked` was the bolts (old airlock.dm: `locked`
#             drew door_locked and refused open) -> CAP_BOLTED; APC `locked` was the ID lock -> CAP_LOCKED.
#   welded  : old door/airlock `var/welded`.   panel_open: machinery/vending panel.   emagged: machinery field.
#   emergency: carried over from the hand-written table (no old var found in history: harmless, kept).
BIT_VARS = {
    "locked": ["CAP_BOLTED", "CAP_LOCKED"],
    "welded": ["CAP_WELDED"],
    "panel_open": ["CAP_PANEL_OPEN"],
    "emagged": ["CAP_EMAGGED"],
    "emergency": ["CAP_EMERGENCY_ACCESS"],
}
# Per type family (path prefix; every type under it, longest wins): extra var aliases, vars that a family
# spells differently, value-mapped vars, transient vars to drop and per-instance config to keep.
#   "alias":  var -> [candidate bits]; "no_alias": vars of BIT_VARS this family does not use
#   "values": var -> {"<v>": [bits]|None}    a value-mapped var; every bit named must be carried
#   "drop" / "keep": var lists
FAMILY_VARS = {
    # old door.dm `var/p_open` (the maintenance panel); airlock keeps panel_open too (the hand-written table did).
    "/obj/machinery/door": {"alias": {"p_open": ["CAP_PANEL_OPEN"]}, "no_alias": ["panel_open"]},
    "/obj/machinery/door/airlock": {
        "alias": {"panel_open": ["CAP_PANEL_OPEN"]},
        "drop": ["operating"],
        "keep": ["icon_state", "req_access", "req_one_access", "id_tag"],
    },
    # old apc.dm: `var/opened` 0 closed / 1 open / 2 cover removed; `var/wiresexposed` was the wire panel;
    # `var/failure_timer` is transient.
    "/obj/machinery/power/apc": {
        "alias": {"wiresexposed": ["CAP_PANEL_OPEN"]},
        "no_alias": ["panel_open"],
        "values": {"opened": {"0": None, "1": ["CAP_COVER_OPEN"], "2": ["CAP_COVER_OPEN", "CAP_COVER_REMOVED"]}},
        "drop": ["failure_timer"],
        "keep": ["req_access"],
    },
    "/obj/machinery/vending": {"keep": ["req_access"]},
}


# ---- DM scanning --------------------------------------------------------------------------------------------------
def dm_files(root):
    for top, _, files in os.walk(os.path.join(root, "code")):
        for f in sorted(files):
            if f.endswith(".dm"):
                path = os.path.join(top, f)
                yield path, os.path.relpath(path, root).replace(os.sep, "/")


def parse_bits(text):
    return set(re.findall(r"^\s*#define\s+(CAP_[A-Z0-9_]+)\s+\(?\s*1\s*<<", text, re.M))


def strip_comment(line):
    out, q, i = [], None, 0
    while i < len(line):
        c = line[i]
        if q:
            out.append(c)
            if c == "\\" and i + 1 < len(line):
                out.append(line[i + 1]); i += 2; continue
            if c == q:
                q = None
        elif c == '"':
            q = c; out.append(c)
        elif c == "/" and line[i:i + 2] == "//":
            break
        else:
            out.append(c)
        i += 1
    return "".join(out)


def split_args(s):
    out, depth, cur, q, i = [], 0, [], None, 0
    while i < len(s):
        c = s[i]
        if q:
            cur.append(c)
            if c == "\\" and i + 1 < len(s):
                cur.append(s[i + 1]); i += 2; continue
            if c == q:
                q = None
        elif c == '"':
            q = c; cur.append(c)
        elif c in "([{":
            depth += 1; cur.append(c)
        elif c in ")]}":
            depth -= 1; cur.append(c)
        elif c == "," and depth == 0:
            out.append("".join(cur).strip()); cur = []
        else:
            cur.append(c)
        i += 1
    last = "".join(cur).strip()
    if last:
        out.append(last)
    return out


CALL = re.compile(r"\b([a-z_][a-z0-9_]*)\(")


def calls(expr):
    """[(name, {argname: text}, [positional])] for every call in expr (nested ones too, outermost first)."""
    out = []
    for m in CALL.finditer(expr):
        depth, i, q = 1, m.end(), None
        while i < len(expr) and depth:
            c = expr[i]
            if q:
                if c == "\\":
                    i += 2; continue
                if c == q:
                    q = None
            elif c == '"':
                q = c
            elif c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
            i += 1
        args = split_args(expr[m.end():i - 1])
        named, pos = {}, []
        for a in args:
            mm = re.match(r"^([a-z_][a-z0-9_]*)\s*=\s*(.*)$", a, re.S)
            if mm and not a.startswith("=="):
                named[mm.group(1)] = mm.group(2).strip()
            else:
                pos.append(a)
        out.append((m.group(1), named, pos))
    return out


class Scan:
    def __init__(self):
        self.bits = set()
        self.bundles = {}  # proc name -> [(line text)] body lines (comments stripped), plus its arg names
        self.bundle_args = {}
        self.cap_procs = {}  # type path -> [body lines]
        self.cap_lines = collections.defaultdict(list)  # type path -> [CAPABILITY entry text]
        self.defaults = {}  # type path -> [bits]


def proc_blocks(lines):
    """Yield (header_line_text, [body lines]) for every top-level (no indent) proc/var-less definition line."""
    i = 0
    n = len(lines)
    while i < n:
        raw = lines[i]
        if raw and not raw[0].isspace() and raw.startswith("/"):
            body = []
            j = i + 1
            while j < n and (not lines[j].strip() or lines[j][0].isspace()):
                body.append(lines[j])
                j += 1
            yield i, raw, body
            i = j
        else:
            i += 1


def scan_text(scan, rel, text):
    lines = text.splitlines()
    in_lib = rel.startswith(LIB_DIR.replace(os.sep, "/"))
    skip = rel.startswith(SKIP_DIRS)
    # CAPABILITY(T, entry) lines (a macro on one logical line; entries may continue, but the bits sit on the first)
    if not skip:
        for raw in lines:
            m = re.match(r"^CAPABILITY\(\s*(/[A-Za-z0-9_/]+)\s*,\s*(.*)\)\s*(//.*)?$", raw)
            if m:
                scan.cap_lines[m.group(1)].append(strip_comment(m.group(2)))
    for _, header, body in proc_blocks(lines):
        header = strip_comment(header).rstrip()
        m = re.match(r"^(/[A-Za-z0-9_/]+)/capabilities\(\)\s*$", header)
        if m and not skip and not m.group(1).endswith("/proc"):
            scan.cap_procs[m.group(1)] = [strip_comment(b).strip() for b in body if strip_comment(b).strip()]
            continue
        m = re.match(r"^/proc/([a-z_][a-z0-9_]*)\((.*)\)\s*$", header)
        if m and in_lib:
            name = m.group(1)
            scan.bundles[name] = [strip_comment(b) for b in body]
            scan.bundle_args[name] = [re.split(r"\s*=\s*", a, 1)[0].strip() for a in split_args(m.group(2))]
            continue
        # a type block: `/path` then `\tcap_state = ...`
        m = re.match(r"^(/[A-Za-z0-9_/]+)\s*$", header)
        if m and not skip:
            for b in body:
                mm = re.match(r"^\s*cap_state\s*=\s*([A-Z0-9_|\s]+?)\s*(//.*)?$", b)
                if mm:
                    scan.defaults[m.group(1)] = sorted(x for x in re.split(r"\s*\|\s*", mm.group(1)) if x and x != "0")


# ---- resolving a capability expression to bits --------------------------------------------------------------------
class Item:
    """One contributed capability: a library constructor with the bits it carries."""
    def __init__(self, ctor, bits):
        self.ctor = ctor
        self.bits = set(bits)


def truthy(text):
    return text is not None and text.strip() in ("TRUE", "1")


def expand(scan, name, named, pos, depth=0):
    """Items a call to `name` contributes (constructor or bundle), or None if it is neither."""
    if depth > 12:
        return []
    if name in CONSTRUCTOR_BITS:
        bits = list(CONSTRUCTOR_BITS[name][1])
        for (ctor, arg), extra in ARG_BITS.items():
            if ctor == name and truthy(named.get(arg)):
                bits += extra
        return [Item(name, bits)]
    if name in scan.bundles:
        params = scan.bundle_args[name]
        args = dict(named)
        for i, p in enumerate(pos):
            if i < len(params):
                args[params[i]] = p
        # defaults of the bundle's own params that are literal TRUE feed forwarded args (removable_cover = FALSE)
        items = []
        for line in scan.bundles[name]:
            for cname, cnamed, cpos in calls(line):
                if cname == name:
                    continue
                if cname in CONSTRUCTOR_BITS or cname in scan.bundles:
                    cnamed = dict(cnamed)
                    for (b, barg), (ctor, carg) in ARG_FORWARD.items():
                        if b == name and ctor == cname and barg in args:
                            cnamed[carg] = args[barg]
                    sub = expand(scan, cname, cnamed, cpos, depth + 1)
                    # only the outermost call on the line: nested calls are its arguments
                    items += sub
                    break
        return items
    return None


def drop_target(arg):
    arg = arg.strip()
    if arg in OP_KEYS:
        return ("ctor", OP_KEYS[arg])
    m = re.match(r"^/datum/capability/([a-z_0-9]+)$", arg)
    if m:
        for ctor, (path, _) in CONSTRUCTOR_BITS.items():
            if path == arg:
                return ("ctor", ctor)
        return ("ctor", "?" + arg)
    return None


def apply_line(scan, items, line):
    """Applies one body line (`. += x`, `. = without(., X)`, `. = replace(., X, y)`, `. = ..()`) to items."""
    line = line.strip()
    m = re.match(r"^\.\s*(\+=|=)\s*(.*)$", line)
    if not m:
        return items
    op, expr = m.groups()
    if expr == "..()":
        return items
    cs = calls(expr)
    if not cs:
        return items
    head, named, pos = cs[0]
    if op == "=" and head in ("without", "replace") and len(pos) >= 2:
        tgt = drop_target(pos[1])
        if tgt:
            items = [it for it in items if it.ctor != tgt[1]]
        if head == "without":
            return items
        rep = calls(pos[2]) if len(pos) > 2 else []
        if rep:
            sub = expand(scan, rep[0][0], rep[0][1], rep[0][2])
            if sub:
                items = items + sub
        return items
    if head in ("refine", "cap_require"):
        return items
    sub = expand(scan, head, named, pos)
    if sub:
        items = items + sub
    return items


def parent_of(path, declared):
    """Nearest strict path-prefix ancestor in `declared`."""
    parts = path.split("/")
    for n in range(len(parts) - 1, 1, -1):
        cand = "/".join(parts[:n])
        if cand in declared:
            return cand
    return None


def carried(scan):
    """type path -> sorted list of bits it can carry (declarers and STATE_HOLDERS)."""
    result = {}
    memo = {}

    def items_of(path):
        if path in memo:
            return memo[path]
        body = scan.cap_procs.get(path)
        items = []
        if body is not None:
            if any(re.match(r"^\.\s*=\s*\.\.\(\)", b) or re.match(r"^\.\s*=\s*\.\.\(\)", b) for b in body):
                par = parent_of(path, scan.cap_procs)
                if par:
                    items = list(items_of(par))
            for b in body:
                items = apply_line(scan, items, b)
        for entry in scan.cap_lines.get(path, []):
            items = apply_line(scan, items, ". += " + entry)
        memo[path] = items
        return items

    for path in set(scan.cap_procs) | set(scan.cap_lines):
        bits = set()
        for it in items_of(path):
            bits |= it.bits
        # a CAPABILITY()-only type extends its capabilities() ancestor
        if path not in scan.cap_procs:
            par = parent_of(path, scan.cap_procs)
            if par:
                for it in items_of(par):
                    bits |= it.bits
        result[path] = sorted(bits)
    for path, bits in STATE_HOLDERS.items():
        result[path] = sorted(set(result.get(path, [])) | set(bits))
    return result


def default_bits(scan, path, declared_types):
    p = path
    while p:
        if p in scan.defaults:
            return scan.defaults[p]
        parts = p.split("/")
        p = "/".join(parts[:-1]) if len(parts) > 2 else None
    return []


def family_rules(path):
    """Merged FAMILY_VARS of every prefix of path (longer prefixes override)."""
    merged = {"alias": {}, "no_alias": [], "values": {}, "drop": [], "keep": []}
    parts = path.split("/")
    for n in range(2, len(parts) + 1):
        fam = FAMILY_VARS.get("/".join(parts[:n]))
        if not fam:
            continue
        merged["alias"].update(fam.get("alias", {}))
        merged["no_alias"] += fam.get("no_alias", [])
        merged["values"].update(fam.get("values", {}))
        for k in ("drop", "keep"):
            merged[k] += [v for v in fam.get(k, []) if v not in merged[k]]
    return merged


def rules_for(path, bits, defaults):
    fam = family_rules(path)
    have = set(bits)
    rules = {"_default_bits": sorted(defaults, key=lambda b: b)}
    cand = {k: list(v) for k, v in BIT_VARS.items()}
    for v in fam["no_alias"]:
        cand.pop(v, None)
    for v, c in fam["alias"].items():
        cand[v] = c
    for var, c in cand.items():
        if var in fam["values"]:
            continue
        pick = next((b for b in c if b in have), None)
        if pick:
            rules[var] = pick
    for var, vmap in fam["values"].items():
        out = {}
        for val, bs in vmap.items():
            if bs is None:
                out[val] = None
                continue
            missing = [b for b in bs if b not in have and b != "CAP_COVER_REMOVED"]
            if missing:
                raise SystemExit("%s: value map of %s needs %s, which the type does not carry" % (path, var, missing))
            out[val] = "|".join(bs)
        rules[var] = out
    for var in fam["drop"]:
        rules[var] = "drop"
    for var in fam["keep"]:
        rules[var] = "keep"
    return rules


def build(root=ROOT, scan=None):
    if scan is None:
        scan = Scan()
        for path, rel in dm_files(root):
            if rel.startswith(SKIP_DIRS):
                continue
            with open(path, encoding="utf-8", errors="replace") as f:
                scan_text(scan, rel, f.read())
        with open(os.path.join(root, "code", "__defines", "cap_bits.dm"), encoding="utf-8") as f:
            scan.bits = parse_bits(f.read())
    return generate(scan), scan


def generate(scan):
    carry = carried(scan)
    for path, bits in carry.items():
        unknown = [b for b in bits if scan.bits and b not in scan.bits]
        if unknown:
            raise SystemExit("%s carries %s, not defined in cap_bits.dm" % (path, unknown))
    # Types that need an entry: those carrying a mappable bit, plus any type whose default bits differ from its
    # nearest emitted ancestor (an airlock subtype that starts bolted).
    out = {}
    emitted_rules = {}
    paths = set(carry)
    for p in scan.defaults:
        anc = p
        while anc:
            if anc in carry:
                paths.add(p)
                break
            parts = anc.split("/")
            anc = "/".join(parts[:-1]) if len(parts) > 2 else None
    for path in sorted(paths, key=lambda p: (p.count("/"), p)):
        anc = path
        bits = carry.get(path)
        if bits is None:
            # a pure default-override subtype: carries what its nearest declaring ancestor carries
            parts = path.split("/")
            for n in range(len(parts) - 1, 1, -1):
                if "/".join(parts[:n]) in carry:
                    bits = carry["/".join(parts[:n])]
                    break
        rules = rules_for(path, bits or [], default_bits(scan, path, carry))
        if len([k for k in rules if k != "_default_bits"]) == 0 and not rules["_default_bits"]:
            continue
        par = parent_of(path, emitted_rules)
        if par and emitted_rules[par] == rules:
            continue
        emitted_rules[path] = rules
        out[path] = rules
    return out


def render(table):
    data = {"_doc": DOC}
    for path in sorted(table, key=lambda p: (p.count("/"), p)):
        rules = table[path]
        entry = {"_default_bits": rules["_default_bits"]}
        for k in sorted(rules, key=lambda k: (rules[k] in ("keep",), rules[k] == "drop", k)):
            if k != "_default_bits":
                entry[k] = rules[k]
        data[path] = entry
    return json.dumps(data, indent=2) + "\n"


# ---- CLI ----------------------------------------------------------------------------------------------------------
def selftest():
    fx = {
        "code/datums/capabilities/library/presets.dm": """
/proc/machine_basics(board, powered = TRUE)
	. = list(
		cap_panel(),
		cap_breakable(repair_tool = repair),
	)
	if(powered)
		. += cap_power()

/proc/maintenance_hatch(cover_holds, removable_cover = FALSE)
	. = list(hatch)
	. += cap_cover(open_tool = cover_tool, removable = removable_cover)
	. += cap_panel(needs = null)
	. += cap_lock(needs = req_clear(COVER | PANEL), entries = FALSE)
	. += emag_op(mode = emag_mode)

/proc/door(wires)
	. = list(cap_panel(tool = panel_tool))
	. += cap_emag(effect = emag_effect)
	. += cap_bolts()
	. += cap_weld_shut(applies = x)
""",
        "code/x/a.dm": """
/obj/machinery/thing/capabilities()
	. = ..()
	. += machine_basics()
	. += maintenance_hatch(removable_cover = TRUE)

/obj/machinery/thing/sub/capabilities()
	. = ..()
	. = without(., CAP_EMAG)
	. += refine(CAP_LOCK, delay = 1)

/obj/machinery/gate/capabilities()
	. = ..()
	. += door(wires = /datum/wires/x)
	. = replace(., /datum/capability/emag, cap_emag(say = "hi"))

/obj/machinery/gate/closed
	cap_state = CAP_BOLTED

CAPABILITY(/obj/item/gizmo, emp_disable(5 SECONDS))
""",
        "code/modules/unit_tests/skip.dm": """
/obj/cap_fixture/x/capabilities()
	. += cap_bolts()
""",
    }
    scan = Scan()
    scan.bits = {"CAP_PANEL_OPEN", "CAP_COVER_OPEN", "CAP_COVER_REMOVED", "CAP_LOCKED", "CAP_EMAGGED", "CAP_BROKEN",
                 "CAP_BOLTED", "CAP_WELDED"}
    for rel, text in fx.items():
        scan_text(scan, rel, text)
    carry = carried(scan)
    fails = []

    def eq(what, got, want):
        if got != want:
            fails.append("%s: got %r want %r" % (what, got, want))

    eq("skip fixtures", "/obj/cap_fixture/x" in carry, False)
    eq("thing bits", carry["/obj/machinery/thing"],
       ["CAP_BROKEN", "CAP_COVER_OPEN", "CAP_COVER_REMOVED", "CAP_EMAGGED", "CAP_LOCKED", "CAP_PANEL_OPEN"])
    eq("without op key drops emag_op bits", "CAP_EMAGGED" in carry["/obj/machinery/thing/sub"], False)
    eq("sub inherits lock", "CAP_LOCKED" in carry["/obj/machinery/thing/sub"], True)
    eq("gate bits", carry["/obj/machinery/gate"], ["CAP_BOLTED", "CAP_EMAGGED", "CAP_PANEL_OPEN", "CAP_WELDED"])
    eq("CAPABILITY-only type carries none", carry["/obj/item/gizmo"], [])
    eq("defaults", scan.defaults, {"/obj/machinery/gate/closed": ["CAP_BOLTED"]})
    # no removable_cover passed -> the removed bit is not carried
    scan2 = Scan()
    scan_text(scan2, "code/datums/capabilities/library/presets.dm", fx["code/datums/capabilities/library/presets.dm"])
    scan_text(scan2, "code/x/b.dm", "/obj/machinery/plain/capabilities()\n\t. = ..()\n\t. += maintenance_hatch()\n")
    eq("removable default FALSE", "CAP_COVER_REMOVED" in carried(scan2)["/obj/machinery/plain"], False)
    table = generate(scan)
    eq("gate locked -> bolts", table["/obj/machinery/gate"]["locked"], "CAP_BOLTED")
    eq("gate welded", table["/obj/machinery/gate"]["welded"], "CAP_WELDED")
    eq("gate no lock bit", "CAP_LOCKED" in str(table["/obj/machinery/gate"]), False)
    eq("subtype default emitted", table["/obj/machinery/gate/closed"]["_default_bits"], ["CAP_BOLTED"])
    eq("thing locked -> lock", table["/obj/machinery/thing"]["locked"], "CAP_LOCKED")
    eq("sub differs (no emag)", "emagged" in table["/obj/machinery/thing/sub"], False)
    eq("deterministic", render(table), render(generate(scan)))
    eq("dropped nothing for unconverted", "/obj/item/gizmo" in table, False)
    if fails:
        print("selftest: FAIL")
        for f in fails:
            print("  " + f)
        return 1
    print("selftest: PASS")
    return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--list", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    table, scan = build()
    text = render(table)
    if a.list:
        carry = carried(scan)
        for p in sorted(carry):
            print("%-62s %s" % (p, " ".join(b[4:] for b in carry[p]) or "-"))
        print("%d capability holder(s), %d emitted rule set(s)" % (len(carry), len(table)))
        return 0
    if a.check:
        cur = open(OUT, encoding="utf-8", newline="").read() if os.path.exists(OUT) else ""
        if cur != text:
            print("tools/dx/capability_varmap.json is stale: run python tools/dx/gen_capability_varmap.py")
            return 1
        print("capability_varmap.json is up to date (%d type rule set(s))" % len(table))
        return 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s (%d type rule set(s))" % (os.path.relpath(OUT, ROOT), len(table)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
