
/obj/machinery/account_database
	name = "Accounts uplink terminal"
	desc = "Access transaction logs, account data and all kinds of other financial records."
	icon = 'icons/obj/computer.dmi'
	icon_state = "account_computer"
	density = TRUE
	req_one_access = list(ACCESS_HOP, ACCESS_CAPTAIN, ACCESS_CENT_CAPTAIN)
	anchored = TRUE
	var/receipt_num
	var/machine_id = ""
	var/obj/item/card/id/held_card
	var/tmp/datum/money_account/detailed_account_view
	var/creating_new_account = 0
	var/const/fund_cap = 1000000
	circuit = /obj/item/circuitboard/account_console

/obj/machinery/account_database/proc/get_access_level()
	if(!held_card)
		return 0
	if(ACCESS_CENT_CAPTAIN in held_card.access)
		return 2
	else if((ACCESS_HOP in held_card.access) || (ACCESS_CAPTAIN in held_card.access))
		return 1

/obj/machinery/account_database/proc/create_transation(target, reason, amount)
	var/datum/transaction/T = new()
	T.target_name = target
	T.purpose = reason
	T.amount = amount
	T.date = GLOB.current_date_string
	T.time = stationtime2text()
	T.source_terminal = machine_id
	return T

/obj/machinery/account_database/proc/accounting_letterhead(report_name)
	return {"
		<center><h1><b>[report_name]</b></h1></center>
		<center><small><i>[station_name()] Accounting Report</i></small></center>
		<hr>
		<u>Generated By:</u> [held_card.registered_name], [held_card.assignment]<br>
	"}

CAPABILITIES(/obj/machinery/account_database)
	climb()
	op("insert_card", ui_act(), then(PROC_REF(ui_act_insert_card)))
	interface("AccountsTerminal")
	without("ui_open")
	op("create_account", ui_act("create_account"), then(PROC_REF(ui_act_create_account)))
	op("add_funds", ui_act("add_funds"), asks(/datum/prompt/number/account_ui_funds/add, step = "amount", when = PROC_REF(central_access)), then(PROC_REF(ui_act_add_funds)))
	op("remove_funds", ui_act("remove_funds"), asks(/datum/prompt/number/account_ui_funds/remove, step = "amount", when = PROC_REF(central_access)), then(PROC_REF(ui_act_remove_funds)))
	op("toggle_suspension", ui_act("toggle_suspension"), then(PROC_REF(ui_act_toggle_suspension)))
	op("finalise_create_account", ui_act("finalise_create_account", arg("holder_name", schema_text(4096)), arg("starting_funds", num())), then(PROC_REF(ui_act_finalise_create_account)))
	op("view_account_detail", ui_act("view_account_detail", arg("account_index", num())), then(PROC_REF(ui_act_view_account_detail)))
	op("view_accounts_list", ui_act("view_accounts_list"), then(PROC_REF(ui_act_view_accounts_list)))
	op("revoke_payroll", ui_act("revoke_payroll"), then(PROC_REF(ui_act_revoke_payroll)))
	op("print", ui_act("print"), then(PROC_REF(ui_act_print)))

/obj/machinery/account_database/Initialize(mapload)
	machine_id = "[station_name()] Acc. DB #[GLOB.num_financial_terminals++]"
	. = ..()

/obj/machinery/account_database/declare_interactions(list/into)
	into += list(
		/datum/interaction/machine_item/account_database_insert_card,
		/datum/interaction/machine_hand/ungated/account_database_open_ui,
	)
	..()

/// Old attackby: insert an ID card, then reopen the UI.
/datum/interaction/machine_item/account_database_insert_card
	id = "account_database_insert_card"
	name = "Insert ID"
	held_type = /obj/item/card/id
	effect = /obj/machinery/account_database/proc/interaction_insert_card

/obj/machinery/account_database/proc/interaction_insert_card(mob/user, obj/item/O, datum/interaction/interaction)
	if(!held_card)
		if(!move_into(src, nameof(src.held_card), O, user))
			return TRUE

		SStgui.update_uis(src)

	attack_hand(user)
	return TRUE

/obj/machinery/account_database/screwdriver_act(mob/user, obj/item/tool)
	return deconstruct_display(user, tool)

/// Old attack_hand: never called ..(); silently did nothing when unpowered or broken.
/datum/interaction/machine_hand/ungated/account_database_open_ui
	id = "account_database_open_ui"
	name = "Use"
	category = INTERACTION_CAT_CONFIGURE
	effect = /obj/machinery/account_database/proc/interaction_open_ui_impl

/obj/machinery/account_database/proc/interaction_open_ui_impl(mob/user, obj/item/held, datum/interaction/interaction)
	if(!operable())
		return TRUE
	tgui_interact(user)
	return TRUE


/obj/machinery/account_database/ui_data(datum/act/eval/A)
	var/list/data = list()
	data["machine_id"] = machine_id
	data["creating_new_account"] = creating_new_account
	var/list/merged_1 = ui_data_obj_machinery_account_database(A.actor, null, null)
	if(islist(merged_1))
		for(var/merged_key_1 in merged_1)
			data[merged_key_1] = merged_1[merged_key_1]
	return data

/// /obj/machinery/account_database's window data.
/obj/machinery/account_database/proc/ui_data_obj_machinery_account_database(mob/user, datum/tgui/ui, datum/tgui_state/state)
	var/list/data = list()

	data["id_inserted"] = !!held_card
	data["id_card"] = held_card ? text("[held_card.registered_name], [held_card.assignment]") : "-----"
	data["access_level"] = get_access_level()
	data["detailed_account_view"] = !!detailed_account_view()
	data["station_account_number"] = GLOB.station_account.account_number

	data["account_number"] = null
	data["owner_name"] = null
	data["money"] = null
	data["suspended"] = null
	data["transactions"] = list()

	if(detailed_account_view())
		data["account_number"] = detailed_account_view().account_number
		data["owner_name"] = detailed_account_view().owner_name
		data["money"] = detailed_account_view().money
		data["suspended"] = detailed_account_view().suspended

		var/list/trx[0]
		for (var/datum/transaction/T in detailed_account_view().transaction_log)
			trx.Add(list(list(\
				"date" = T.date, \
				"time" = T.time, \
				"target_name" = T.target_name, \
				"purpose" = T.purpose, \
				"amount" = T.amount, \
				"source_terminal" = T.source_terminal)))

		data["transactions"] = trx

	var/list/accounts = list()
	for(var/i in 1 to REGISTRY_COUNT(REGISTRY_MONEY_ACCOUNTS))
		var/datum/money_account/D = REGISTRY_MEMBERS(REGISTRY_MONEY_ACCOUNTS)[i]
		if(D.offmap)
			continue
		accounts.Add(list(list(\
			"account_number"=D.account_number,\
			"owner_name"=D.owner_name,\
			"suspended"=D.suspended ? "SUSPENDED" : "",\
			"account_index"=i)))

	data["accounts"] = accounts

	return data

/obj/machinery/account_database/proc/ui_gate(datum/act/op/A)
	var/action = A.window_action()
	var/access_level = get_access_level()
	if(action != "insert_card" && !access_level)
		return FALSE
	return TRUE

/obj/machinery/account_database/proc/ui_act_create_account(datum/act/op/A)
	if(!ui_gate(A))
		return FALSE
	creating_new_account = 1
	return TRUE

/obj/machinery/account_database/proc/ui_act_add_funds(datum/act/op/A)
	if(!ui_gate(A))
		return FALSE
	if(get_access_level() < 2)
		return FALSE
	return apply_ui_add_funds(A.actor, A.step_value("amount"))

/// The silent fund buttons ask their amount only of a central command card.
/obj/machinery/account_database/proc/central_access(datum/act/op/A)
	return held_card && (ACCESS_CENT_CAPTAIN in held_card.access) // ALLOW(reads): asked once, when the button is pressed, to decide whether its question opens (get_access_level() 2)

/obj/machinery/account_database/proc/apply_ui_add_funds(mob/user, amount)
	if(detailed_account_view() && isnum(amount) && amount > 0)
		var/allowed_amount = min(amount, fund_cap - detailed_account_view().money)
		detailed_account_view().credit(allowed_amount, user.real_name, "Authorized account adjustment", machine_id)
	return TRUE

/obj/machinery/account_database/proc/ui_act_remove_funds(datum/act/op/A)
	if(!ui_gate(A))
		return FALSE
	if(get_access_level() < 2)
		return FALSE
	return apply_ui_remove_funds(A.actor, A.step_value("amount"))

/obj/machinery/account_database/proc/apply_ui_remove_funds(mob/user, amount)
	if(detailed_account_view() && isnum(amount) && amount > 0)
		detailed_account_view().debit(min(amount, detailed_account_view().money), user.real_name, "Authorized account adjustment", machine_id)
	return TRUE

/obj/machinery/account_database/proc/ui_act_toggle_suspension(datum/act/op/A)
	if(!ui_gate(A))
		return FALSE
	var/access_level = get_access_level()
	if(access_level < 2)
		return FALSE
	if(detailed_account_view())
		detailed_account_view().suspended = !detailed_account_view().suspended
		OM_EMIT_WORLD(/datum/om/event/world_payment_account_status, detailed_account_view())
	return TRUE

/obj/machinery/account_database/proc/ui_act_finalise_create_account(datum/act/op/A, holder_name, starting_funds_arg)
	if(!ui_gate(A))
		return FALSE
	var/account_name = holder_name
	var/starting_funds = max(starting_funds_arg, 0)

	starting_funds = CLAMP(starting_funds, 0, GLOB.station_account.money)	// Not authorized to put the station in debt.
	starting_funds = min(starting_funds, fund_cap)						// Not authorized to give more than the fund cap.

	if(!account_name)
		return FALSE
	if(!create_station_funded_account(account_name, starting_funds, src))
		return FALSE
	creating_new_account = 0
	return TRUE

/obj/machinery/account_database/proc/ui_act_insert_card(datum/act/op/A)
	var/mob/user = A.actor
	if(held_card)
		held_card.forceMove(src.loc)

		if(ishuman(user) && !user.get_active_hand())
			user.put_in_hands(held_card)
		own_take(src, nameof(/obj/machinery/account_database::held_card))

	else
		var/obj/item/I = user.get_active_hand()
		if(istype(I, /obj/item/card/id))
			var/obj/item/card/id/C = I
			move_into(src, nameof(src.held_card), C, user)
	return OP_OK

/obj/machinery/account_database/proc/ui_act_view_account_detail(datum/act/op/A, account_index)
	if(!ui_gate(A))
		return FALSE
	var/index = account_index
	if(index && index <= REGISTRY_COUNT(REGISTRY_MONEY_ACCOUNTS))
		rel_set(src, nameof(/obj/machinery/account_database::detailed_account_view), REGISTRY_MEMBERS(REGISTRY_MONEY_ACCOUNTS)[index])
	return TRUE

/obj/machinery/account_database/proc/ui_act_view_accounts_list(datum/act/op/A)
	if(!ui_gate(A))
		return FALSE
	rel_clear(src, nameof(/obj/machinery/account_database::detailed_account_view))
	creating_new_account = 0
	return TRUE

/obj/machinery/account_database/proc/ui_act_revoke_payroll(datum/act/op/A)
	if(!ui_gate(A))
		return FALSE
	var/access_level = get_access_level()
	if(access_level < 2 || !detailed_account_view() || detailed_account_view().is_budget_account)
		return FALSE
	var/funds = detailed_account_view().money
	if(funds > 0)
		transfer_account_funds(detailed_account_view(), GLOB.station_account, funds, "Revoke payroll", machine_id)
	return TRUE

/obj/machinery/account_database/proc/ui_act_print(datum/act/op/A)
	if(!ui_gate(A))
		return FALSE
	print()
	return TRUE

/obj/machinery/account_database/proc/print()
	var/text
	var/obj/item/paper/P = new(loc)
	if(detailed_account_view())
		P.name = "account #[detailed_account_view().account_number] details"
		var/title = "Account #[detailed_account_view().account_number] Details"
		text = {"
			[accounting_letterhead(title)]
			<u>Holder:</u> [detailed_account_view().owner_name]<br>
			<u>Balance:</u> $[detailed_account_view().money]<br>
			<u>Status:</u> [detailed_account_view().suspended ? "Suspended" : "Active"]<br>
			<u>Transactions:</u> ([length(detailed_account_view().transaction_log)])<br>
			<table>
				<thead>
					<tr>
						<td>Timestamp</td>
						<td>Target</td>
						<td>Reason</td>
						<td>Value</td>
						<td>Terminal</td>
					</tr>
				</thead>
				<tbody>
			"}

		for (var/datum/transaction/T in detailed_account_view().transaction_log)
			text += {"
						<tr>
							<td>[T.date] [T.time]</td>
							<td>[T.target_name]</td>
							<td>[T.purpose]</td>
							<td>[T.amount]</td>
							<td>[T.source_terminal]</td>
						</tr>
				"}

		text += {"
				</tbody>
			</table>
			"}

	else
		P.name = "financial account list"
		text = {"
			[accounting_letterhead("Financial Account List")]

			<table>
				<thead>
					<tr>
						<td>Account Number</td>
						<td>Holder</td>
						<td>Balance</td>
						<td>Status</td>
					</tr>
				</thead>
				<tbody>
		"}

		for(var/i=1, i <= REGISTRY_COUNT(REGISTRY_MONEY_ACCOUNTS), i++)
			var/datum/money_account/D = REGISTRY_MEMBERS(REGISTRY_MONEY_ACCOUNTS)[i]
			text += {"
					<tr>
						<td>#[D.account_number]</td>
						<td>[D.owner_name]</td>
						<td>$[D.money]</td>
						<td>[D.suspended ? "Suspended" : "Active"]</td>
					</tr>
			"}

		text += {"
				</tbody>
			</table>
		"}

	P.info = text
	state("The terminal prints out a report.")

/obj/machinery/account_database/ownership()
	. = ..()
	. += owns(nameof(held_card), policy = OWN_CONTAINED)

/// the detailed_account_view this refers to (a relation view: null once it is deleted).
/obj/machinery/account_database/proc/detailed_account_view() as /datum/money_account
	return detailed_account_view

// Original account-terminal windows own these scalar continuations.
/datum/prompt/number/account_ui_funds
	timeout = 0

/datum/prompt/number/account_ui_funds/add
	title = "Silently add funds"
	question = "Enter the amount you wish to add"

/datum/prompt/number/account_ui_funds/remove
	title = "Silently remove funds"
	question = "Enter the amount you wish to remove"
