/datum/malf_research
	var/stored_cpu = 0								// Currently stored amount of CPU time.
	EXPIRY_DECLARE(last_tick) // Last process() tick.
	var/max_cpu = 0									// Maximal amount of CPU time stored.
	var/cpu_increase_per_tick = 0					// Amount of CPU time generated by tick
	var/list/available_abilities = null				// List of available abilities that may be researched.
	var/list/unlocked_abilities = null				// List of already unlocked abilities.
	var/mob/living/silicon/ai/owner			// AI which owns this research datum.
	var/datum/malf_research_ability/focus_static	// Currently researched item (a relation view into available_abilities)

CAPABILITIES(/datum/malf_research)
	owns_many(nameof(available_abilities))
	owns_many(nameof(unlocked_abilities))

/datum/malf_research/New()
	setup_abilities()
	EXPIRY_STAMP(src, last_tick, CLOCK_WORLD)


// Proc:		setup_abilities()
// Parameters: 	None
// Description: Sets up basic abilities for AI Malfunction gamemode.
/datum/malf_research/proc/setup_abilities()
	rel_clear(src, nameof(available_abilities))
	rel_clear(src, nameof(unlocked_abilities))

	rel_add(src, nameof(available_abilities), new/datum/malf_research_ability/networking/basic_hack())
	rel_add(src, nameof(available_abilities), new/datum/malf_research_ability/interdiction/recall_shuttle())
	rel_add(src, nameof(available_abilities), new/datum/malf_research_ability/manipulation/electrical_pulse())


// Proc:		finish_research()
// Parameters: 	None
// Description: Finishes currently focused research.
/datum/malf_research/proc/finish_research()
	if(!get_focus())
		return
	to_chat(owner_ref(), span_bold("Research Completed") + ": [get_focus().name]")
	grant(owner_ref(), granted_verb(get_focus().ability), get_focus())
	var/datum/malf_research_ability/done = get_focus()
	rel_move(src, nameof(available_abilities), src, nameof(unlocked_abilities), done)
	if(done.next)
		own_move(done.next, src, nameof(available_abilities))
	rel_clear(src, nameof(focus_static))


// Proc:		process()
// Parameters: 	None
// Description: Processes CPU gain and research progress based on "realtime" calculation.
/datum/malf_research/proc/research_tick(idle = 0)
	if(idle)		// No power or running on APU. Do nothing.
		EXPIRY_STAMP(src, last_tick, CLOCK_WORLD)
		return
	var/time_diff = (world.time - last_tick)
	EXPIRY_STAMP(src, last_tick, CLOCK_WORLD)
	var/cpu_gained = time_diff * cpu_increase_per_tick
	if(cpu_gained < 0)
		return // This shouldn't happen, but just in case..
	if(max_cpu > stored_cpu)
		var/given = min((max_cpu - stored_cpu), cpu_gained)
		stored_cpu += given
		cpu_gained -= given

	cpu_gained = max(0, cpu_gained)
	if(get_focus() && (cpu_gained > 0))
		get_focus().research_tick(cpu_gained)
		if(get_focus().unlocked)
			finish_research()

/// Owner (a relation view).
/datum/malf_research/proc/owner_ref() as /mob/living/silicon/ai
	return owner

/// A shared definition/flyweight (implicitly shared), never cleared.
/datum/malf_research/proc/get_focus() as /datum/malf_research_ability
	return focus_static

