#define CARGO_MARKET_REFRESH_INTERVAL (8 MINUTES)
#define CARGO_MARKET_LISTINGS_PER_PARTY 3
#define CARGO_MARKET_BIDS_PER_PARTY 3
#define CARGO_MARKET_TRANSACTION_LIMIT 100

#define CARGO_MARKET_BUY "station_purchase"
#define CARGO_MARKET_SELL "station_export"
#define CARGO_MARKET_FUNDING_DEPARTMENT "department"
#define CARGO_MARKET_FUNDING_PERSONAL "personal"
#define CARGO_MARKET_FUNDING_CONTRACT "contract"

#define CARGO_MARKET_AGENT_REPUTATION REPUTATION_ALLIED
#define CARGO_MARKET_AGENT_EARNED_REPUTATION 50
#define CARGO_MARKET_SYNDICATE_REPUTATION REPUTATION_UNFRIENDLY
#define CARGO_MARKET_SYNDICATE_EARNED_REPUTATION 20
#define CARGO_MARKET_AGENT_OFFERS 2
#define CARGO_MARKET_AGENT_OFFER_DELAY (2 MINUTES)

#define FACTION_AGENT_TIER_CANDIDATE 1
#define FACTION_AGENT_TIER_ACCREDITED 2
#define FACTION_AGENT_TIER_TRUSTED 3
#define FACTION_AGENT_TIER_OPERATIVE 4
#define FACTION_AGENT_TRUSTED_COMPLETIONS 3
#define FACTION_AGENT_TRUSTED_REPUTATION REPUTATION_ALLIED
#define FACTION_AGENT_MAX_EXPOSURE 100
#define FACTION_AGENT_INVESTIGATION_THRESHOLD 40
#define FACTION_AGENT_COUNTER_OFFER_THRESHOLD 30

#define CARGO_MARKET_LEGAL_PUBLIC "public"
#define CARGO_MARKET_LEGAL_RESTRICTED "restricted"
#define CARGO_MARKET_LEGAL_COVERT "covert"
#define CARGO_MARKET_TRACE_LIMIT 160
#define CARGO_MARKET_VETTING_VALUE 500

#define AGENT_CONTACT_STANDARD "standard"
#define AGENT_CONTACT_CONFIDENTIAL "confidential"
#define AGENT_CONTACT_DENIABLE "deniable"
#define AGENT_CONTACT_STANDARD_SHARE 35
#define AGENT_CONTACT_CONFIDENTIAL_SHARE 50
#define AGENT_CONTACT_DENIABLE_SHARE 65
#define AGENT_CONTACT_STANDARD_COMMISSION 0.05
#define AGENT_CONTACT_CONFIDENTIAL_COMMISSION 0.1
#define AGENT_CONTACT_DENIABLE_COMMISSION 0.15
#define AGENT_CONTACT_STANDARD_EXPOSURE 3
#define AGENT_CONTACT_CONFIDENTIAL_EXPOSURE 8
#define AGENT_CONTACT_DENIABLE_EXPOSURE 15
#define AGENT_INVESTIGATION_REPUTATION_PENALTY 20

#define CONTRACT_OPERATIVE_ANTAG_ID "contract_operative"
