#define CONTRACT_SCOPE_STATION "station"
#define CONTRACT_SCOPE_DEPARTMENT "department"
#define CONTRACT_SCOPE_PERSONAL "personal"

#define CONTRACT_OFFERED "offered"
#define CONTRACT_ACTIVE "active"
#define CONTRACT_GRACE "grace"
#define CONTRACT_COMPLETED "completed"
#define CONTRACT_FAILED "failed"
#define CONTRACT_CANCELLED "cancelled"

#define CONTRACT_OUTCOME_UNRATED "unrated"
#define CONTRACT_OUTCOME_MINIMUM "minimum"
#define CONTRACT_OUTCOME_SUCCESSFUL "successful"
#define CONTRACT_OUTCOME_EXCEPTIONAL "exceptional"

#define CONTRACT_GRADE_MINIMUM_RATIO 0.5
#define CONTRACT_GRADE_SUCCESS_RATIO 0.75
#define CONTRACT_GRADE_EXCEPTIONAL_RATIO 1
#define CONTRACT_GRADE_MINIMUM_REWARD 0.6
#define CONTRACT_GRADE_SUCCESS_REWARD 0.8
#define CONTRACT_GRADE_EXCEPTIONAL_REWARD 1

#define CONTRACT_STAKEHOLDER_PENDING "pending"
#define CONTRACT_STAKEHOLDER_COUNTERED "countered"
#define CONTRACT_STAKEHOLDER_APPROVED "approved"
#define CONTRACT_STAKEHOLDER_REJECTED "rejected"
#define CONTRACT_STAKEHOLDER_WITHDRAWN "withdrawn"
#define CONTRACT_STAKEHOLDER_REVOKED "revoked"

#define CONTRACT_OFFER_STANDING "standing"
#define CONTRACT_OFFER_OPPORTUNITY "opportunity"

#define CONTRACT_CLOSE_COMPLETED "completed"
#define CONTRACT_CLOSE_FAILED "failed"
#define CONTRACT_CLOSE_CANCELLED "cancelled"
#define CONTRACT_CLOSE_DECLINED "declined"
#define CONTRACT_CLOSE_EXPIRED "expired"
#define CONTRACT_CLOSE_INELIGIBLE "ineligible"

#define CONTRACT_BOARD_STATION_LIMIT 2
#define CONTRACT_BOARD_DEPARTMENT_LIMIT 2
#define CONTRACT_BOARD_PERSONAL_LIMIT 4
#define CONTRACT_BOARD_FACTION_LIMIT 1
#define CONTRACT_TERM_SHORT "short"
#define CONTRACT_TERM_LONG "long"
#define CONTRACT_SHORT_TERM_CUTOFF 30 MINUTES
#define CONTRACT_LIFECYCLE_HISTORY_LIMIT 200
#define CONTRACT_DEFAULT_GRACE_DURATION 2 MINUTES
#define CONTRACT_DEFAULT_OFFER_COOLDOWN 2 MINUTES
#define CONTRACT_DEFAULT_REPEAT_COOLDOWN 20 MINUTES
#define CONTRACT_ROTATION_MIN_DELAY 3 MINUTES
#define CONTRACT_ROTATION_MAX_DELAY 8 MINUTES
#define CONTRACT_DEFAULT_FAILURE_REPUTATION_FACTOR 0.5

#define CONTRACT_REQUIREMENT_PENDING "pending"
#define CONTRACT_REQUIREMENT_COMPLETE "complete"
#define CONTRACT_REQUIREMENT_FAILED "failed"

#define CONTRACT_FUNDING_EXTERNAL "external"
#define CONTRACT_FUNDING_INTERNAL "internal"

#define CONTRACT_AUDIT_CREATED "created"
#define CONTRACT_AUDIT_ACCEPTED "accepted"
#define CONTRACT_AUDIT_PROGRESS "progress"
#define CONTRACT_AUDIT_COMPLETED "completed"
#define CONTRACT_AUDIT_FAILED "failed"
#define CONTRACT_AUDIT_CANCELLED "cancelled"
#define CONTRACT_AUDIT_PAYMENT "payment"
#define CONTRACT_AUDIT_EVIDENCE "evidence"
#define CONTRACT_AUDIT_RECOVERY "recovery"
#define CONTRACT_AUDIT_NEGOTIATION "negotiation"
#define CONTRACT_AUDIT_OFFER "offer"
#define CONTRACT_AUDIT_GRACE "grace"
#define CONTRACT_EVIDENCE_DOCUMENT "document"
#define CONTRACT_EVIDENCE_ENGINEERING "engineering_measurement"
#define CONTRACT_FAX_ENGINEERING "NanoTrasen Engineering Assurance"
#define CONTRACT_EVIDENCE_MEDICAL_SCAN "medical_scan"
#define CONTRACT_EVIDENCE_RETENTION 30 MINUTES

// Generic, event-driven contract evidence. Producers report facts once; active
// requirements subscribe to only the event families they need.
#define CONTRACT_EVENT_EVIDENCE_REGISTERED "evidence_registered"
#define CONTRACT_EVENT_EVIDENCE_CONSUMED "evidence_consumed"
#define CONTRACT_EVENT_DOCUMENT_CREATED "document_created"
#define CONTRACT_EVENT_DOCUMENT_SIGNED "document_signed"
#define CONTRACT_EVENT_FAX_ACCEPTED "fax_accepted"
#define CONTRACT_EVENT_MEDICAL_SCAN_CREATED "medical_scan_created"
#define CONTRACT_EVENT_MEDICAL_OBSERVATION_ACCEPTED "medical_observation_accepted"
#define CONTRACT_EVENT_MEDICAL_ANALYSIS_ACCEPTED "medical_analysis_accepted"
#define CONTRACT_EVENT_RARE_CASE_ACCEPTED "rare_case_accepted"
#define CONTRACT_EVENT_CONTRACT_ACTION_ACCEPTED "contract_action_accepted"
#define CONTRACT_EVENT_SHIPMENT_DEPARTED "shipment_departed"
#define CONTRACT_EVENT_ITEM_EXPORTED "item_exported"
#define CONTRACT_EVENT_SERVICE_INVOICE_CHANGED "service_invoice_changed"
#define CONTRACT_EVENT_EQUIPMENT_ADOPTED "equipment_adopted"
#define CONTRACT_EVENT_SERVICE_PERIOD_SETTLED "service_period_settled"
#define CONTRACT_EVENT_MONEY_TRANSFERRED "money_transferred"
#define CONTRACT_EVENT_BUDGET_ALLOCATION_CHANGED "budget_allocation_changed"
#define CONTRACT_EVENT_BUDGET_CYCLE_SETTLED "budget_cycle_settled"
#define CONTRACT_EVENT_MACHINE_RESULT "machine_result"
#define CONTRACT_EVENT_SECURITY_DISPOSITION_CHANGED "security_disposition_changed"
#define CONTRACT_EVENT_CUSTODY_CHANGED "custody_changed"
#define CONTRACT_EVENT_ITEM_PRODUCED "item_produced"
#define CONTRACT_EVENT_SUPPLY_ORDER_FULFILLED "supply_order_fulfilled"
#define CONTRACT_EVENT_INFRASTRUCTURE_DAMAGED "infrastructure_damaged"
#define CONTRACT_EVENT_INFRASTRUCTURE_REPAIRED "infrastructure_repaired"
#define CONTRACT_EVENT_MEDICAL_TREATMENT_OUTCOME "medical_treatment_outcome"
#define CONTRACT_EVENT_SUPPLY_SHORTAGE_DECLARED "supply_shortage_declared"
#define CONTRACT_EVENT_SUPPLY_SHORTAGE_DELIVERY "supply_shortage_delivery"
#define CONTRACT_EVENT_STAKEHOLDER_APPROVED "stakeholder_approved"
#define CONTRACT_EVENT_POWER_SERVICE_CHANGED "power_service_changed"
#define CONTRACT_EVENT_ATMOS_SERVICE_CHANGED "atmos_service_changed"
#define CONTRACT_EVENT_BLOOD_DONATED "blood_donated"
#define CONTRACT_EVENT_RESEARCH_MILESTONE "research_milestone"
#define CONTRACT_EVENT_CHEMISTRY_RESULT "chemistry_result"
#define CONTRACT_EVENT_FOOD_CONSUMED "food_consumed"
#define CONTRACT_EVENT_CROP_HARVESTED "crop_harvested"
#define CONTRACT_EVENT_SANITATION_COMPLETED "sanitation_completed"
#define CONTRACT_EVENT_AUTOMATION_TASK_COMPLETED "automation_task_completed"
#define CONTRACT_EVENT_CARGO_MARKET_PURCHASE "cargo_market_purchase"
#define CONTRACT_EVENT_CARGO_MARKET_EXPORT "cargo_market_export"
#define CONTRACT_EVENT_COVERT_MARKET_ACTIVITY "covert_market_activity"
#define CONTRACT_EVENT_COVERT_MARKET_AUDIT "covert_market_audit"
#define CONTRACT_EVENT_AGENT_CONTACT_SIGNED "agent_contact_signed"
#define CONTRACT_EVENT_AGENT_ENDORSEMENT_SIGNED "agent_endorsement_signed"
#define CONTRACT_EVENT_AGENT_PHYSICAL_EVIDENCE "agent_physical_evidence"
#define CONTRACT_EVENT_AGENT_APPROACH_SIGNED "agent_approach_signed"
#define CONTRACT_EVENT_AGENT_CONTACT_COOPERATED "agent_contact_cooperated"

#define CONTRACT_EVENT_HISTORY_LIMIT 100
#define CONTRACT_EVENT_DEDUP_LIMIT 4096

#define CONTRACT_OPPORTUNITY_HISTORY_LIMIT 100
#define CONTRACT_OPPORTUNITY_FACT_LIMIT 128
#define CONTRACT_OPPORTUNITY_DEFAULT_WINDOW 10 MINUTES
#define CONTRACT_OPPORTUNITY_DEFAULT_COOLDOWN 20 MINUTES
#define CONTRACT_OPPORTUNITY_RESET_RATIO 0.5
#define CONTRACT_OPPORTUNITY_AGGREGATE_SUM "sum"
#define CONTRACT_OPPORTUNITY_AGGREGATE_MAX "maximum"

#define CONTRACT_EVIDENCE_SCOPE_ANY "any"
#define CONTRACT_EVIDENCE_SCOPE_CONTRACT "contract"
#define CONTRACT_EVIDENCE_SCOPE_DEPARTMENT "department"
#define CONTRACT_EVIDENCE_SCOPE_OWNER "owner"

#define CONTRACT_EVIDENCE_COMPARE_EQUAL "equal"
#define CONTRACT_EVIDENCE_COMPARE_NOT_EQUAL "not_equal"
#define CONTRACT_EVIDENCE_COMPARE_AT_LEAST "at_least"
#define CONTRACT_EVIDENCE_COMPARE_AT_MOST "at_most"
#define CONTRACT_EVIDENCE_COMPARE_GREATER "greater"
#define CONTRACT_EVIDENCE_COMPARE_LESS "less"
#define CONTRACT_DOCUMENT_CLINICAL_CASE "clinical_case"
#define CONTRACT_DOCUMENT_FINAL_REPORT "final_report"
#define CONTRACT_DOCUMENT_MANIFEST "manifest"
#define CONTRACT_DOCUMENT_RARE_CASE_CONSENT "rare_case_consent"
#define CONTRACT_DOCUMENT_RARE_CASE_REPORT "rare_case_report"
#define CONTRACT_DOCUMENT_CONSENT_REVOCATION "consent_revocation"
#define CONTRACT_DOCUMENT_AGENT_CONTACT "agent_contact"
#define CONTRACT_DOCUMENT_AGENT_ENDORSEMENT "agent_endorsement"
#define CONTRACT_DOCUMENT_AGENT_CHARTER "agent_charter"

#define AGENT_APPROACH_REGISTERED "registered"
#define AGENT_APPROACH_DISCREET "discreet"
#define AGENT_APPROACH_HOSTILE "hostile"

#define AGENT_DISCOVERY_CLEAN 0
#define AGENT_DISCOVERY_SUSPECTED 1
#define AGENT_DISCOVERY_TRACED 2
#define AGENT_DISCOVERY_IDENTIFIED 3
#define AGENT_DISCOVERY_PROVEN 4

#define AGENT_OPERATION_SOURCING "sourcing"
#define AGENT_OPERATION_DEMONSTRATION "demonstration"
#define AGENT_OPERATION_SERVICE "service"
#define AGENT_OPERATION_CUSTODY "custody"
#define AGENT_OPERATION_INFLUENCE "influence"

#define CONTRACT_FAX_VEYMED "VeyMed Clinical Development"
#define CONTRACT_FAX_RISK "VeyMed Clinical Risk"
#define CONTRACT_FAX_ADVOCACY "Worker's Union Advocacy"
#define CONTRACT_FAX_CASE_REGISTRY "VeyMed Clinical Case Registry"

#define MEDICAL_TRIAL_OBSERVATION_TIME 1 MINUTE
#define MEDICAL_TRIAL_MINIMUM_BASELINE 15
#define MEDICAL_TRIAL_MINIMUM_DOSE 3
#define MEDICAL_TRIAL_REAGENT_ID "dq_experimental_medication"
#define MEDICAL_TRIAL_MARKER_REAGENT_ID "dq_trial_marker"
#define MEDICAL_TRIAL_CHALLENGE_REAGENT_ID "dq_experimental_challenge"
#define MEDICAL_TRIAL_COHORT_THERAPEUTIC "affected-patient therapeutic"
#define MEDICAL_TRIAL_COHORT_HEALTHY "healthy-volunteer safety"
#define MEDICAL_TRIAL_COHORT_MIXED "mixed controlled"
#define MEDICAL_TRIAL_COHORT_PREVENTATIVE "preventative challenge"
#define MEDICAL_TRIAL_OFFER_DURATION 15 MINUTES
#define MEDICAL_TRIAL_RESUPPLY_COST 150
#define MEDICAL_TRIAL_MAX_RESUPPLIES 2
#define MEDICAL_RARE_CASE_MINIMUM_SEVERITY 25
#define MEDICAL_RARE_CASE_IMPROVEMENT 0.5
