#define MATERIAL_PHASE_SOLID "solid"
#define MATERIAL_PHASE_MOLTEN "molten"
#define MATERIAL_PHASE_POWDER "powder"
#define MATERIAL_PHASE_SOLUTION "solution"

#define MATERIAL_PROCESS_MELT "melt"
#define MATERIAL_PROCESS_CAST "cast"
#define MATERIAL_PROCESS_ANNEAL "anneal"
#define MATERIAL_PROCESS_QUENCH "quench"
#define MATERIAL_PROCESS_TEMPER "temper"
#define MATERIAL_PROCESS_SINTER "sinter"
#define MATERIAL_PROCESS_ROLL "roll"
#define MATERIAL_PROCESS_FORGE "forge"
#define MATERIAL_PROCESS_DRAW "wire draw"
#define MATERIAL_PROCESS_PURIFY "purify"
#define MATERIAL_PROCESS_ELECTROLYZE "electrolyze"
#define MATERIAL_PROCESS_CRYSTALLIZE "crystallize"
#define MATERIAL_PROCESS_HEAT "heat"
#define MATERIAL_PROCESS_COOL "controlled cool"
#define MATERIAL_PROCESS_HOMOGENIZE "homogenize"
#define MATERIAL_PROCESS_SOLUTION_TREAT "solution treat"
#define MATERIAL_PROCESS_DISSOLVE "dissolve"
#define MATERIAL_PROCESS_PULVERIZE "pulverize"
#define MATERIAL_PROCESS_PLATE "electroplate"

#define MATERIAL_STRUCTURE_SOFT "soft matrix"
#define MATERIAL_STRUCTURE_HARDENED "hardened matrix"
#define MATERIAL_STRUCTURE_PRECIPITATE "precipitate"
#define MATERIAL_STRUCTURE_REINFORCEMENT "reinforcement"
#define MATERIAL_STRUCTURE_AMORPHOUS "amorphous"
#define MATERIAL_STRUCTURE_DEFECT "defect"

#define MATERIAL_TEST_SPECTROMETRY "spectrometry"
#define MATERIAL_TEST_MICROSCOPY "microscopy"
#define MATERIAL_TEST_HARDNESS "hardness indentation"
#define MATERIAL_TEST_CONDUCTIVITY "conductivity probe"
#define MATERIAL_TEST_TENSILE "tensile test"
#define MATERIAL_TEST_CORROSION "corrosion exposure"
#define MATERIAL_TEST_FIELD "fabricated article field test"

#define MATERIAL_ATMOSPHERE_AIR "air"
#define MATERIAL_ATMOSPHERE_INERT "nitrogen"
#define MATERIAL_ATMOSPHERE_VACUUM "vacuum"
#define MATERIAL_ATMOSPHERE_REDUCING "hydrogen"

#define CONTRACT_EVENT_MATERIAL_PROCESSED "material_processed"
#define CONTRACT_EVENT_MATERIAL_CERTIFIED "material_certified"

#define MATERIAL_SCIENCE_MAX_BATCH 50
#define MATERIAL_SCIENCE_REAGENT_SAMPLE 10
