#define MATERIAL_PHASE_SOLID "solid"
#define MATERIAL_PHASE_MOLTEN "molten"
#define MATERIAL_PHASE_POWDER "powder"
#define MATERIAL_PHASE_SOLUTION "solution"

#define MATERIAL_SURFACE_CARBON "carbon case"
#define MATERIAL_SURFACE_SLIME_METAL "metal slime skin"
#define MATERIAL_SURFACE_SLIME_CRYO "cryogenic slime skin"
#define MATERIAL_SURFACE_SLIME_THERMAL "thermal slime skin"
#define MATERIAL_SURFACE_SLIME_CONDUCTIVE "conductive slime skin"
#define MATERIAL_SURFACE_SLIME_CORROSION "corrosion-resistant slime skin"
#define MATERIAL_SURFACE_SLIME_CATALYTIC "catalytic slime skin"
#define MATERIAL_SURFACE_SLIME_BLUESPACE "bluespace slime skin"
#define MATERIAL_SURFACE_PLATING "chemical plating"
#define MATERIAL_SURFACE_OXIDE "oxide scale"

#define MATERIAL_FIELD_PARTICLE "particle-conditioned lattice"
#define MATERIAL_FIELD_MAGNETIC "magnetically aligned lattice"

// Rare feedstocks are concrete phases, not spell-like effect payloads. They
// enter the same batch/composite model as ordinary metals and ceramics.
#define MAT_VOLTAIC_CRYSTAL "voltaic crystal"
#define MAT_THERMIC_CERAMIC "thermic ceramic"
#define MAT_KINETIC_CRYSTAL "kinetic crystal"
#define MAT_WARD_METAL "ward metal"
#define MAT_SPORE_BIOMASS "spore biomass"
#define MAT_ETCHING_CERAMIC "etching ceramic"
#define MAT_LUMEN_CRYSTAL "lumen crystal"
#define MAT_RIFT_GLASS "rift glass"

#define MATERIAL_PROCESS_MELT "melt"
#define MATERIAL_PROCESS_CAST "cast"
#define MATERIAL_PROCESS_ANNEAL "anneal"
#define MATERIAL_PROCESS_QUENCH "quench"
#define MATERIAL_PROCESS_TEMPER "temper"
#define MATERIAL_PROCESS_SINTER "sinter"
#define MATERIAL_PROCESS_FORGE "forge"
#define MATERIAL_PROCESS_PURIFY "purify"
#define MATERIAL_PROCESS_ELECTROLYZE "electrolyze"
#define MATERIAL_PROCESS_CRYSTALLIZE "crystallize"
#define MATERIAL_PROCESS_HEAT "heat"
#define MATERIAL_PROCESS_COOL "controlled cool"
#define MATERIAL_PROCESS_HOMOGENIZE "homogenize"
#define MATERIAL_PROCESS_SOLUTION_TREAT "solution treat"
#define MATERIAL_PROCESS_DISSOLVE "dissolve"
#define MATERIAL_PROCESS_PULVERIZE "pulverize"
#define MATERIAL_PROCESS_PLATE "electroplate"

#define MATERIAL_STRUCTURE_SOFT "soft matrix"
#define MATERIAL_STRUCTURE_HARDENED "hardened matrix"
#define MATERIAL_STRUCTURE_PRECIPITATE "precipitate"
#define MATERIAL_STRUCTURE_REINFORCEMENT "reinforcement"
#define MATERIAL_STRUCTURE_AMORPHOUS "amorphous"
#define MATERIAL_STRUCTURE_DEFECT "defect"

#define MATERIAL_TEST_SPECTROMETRY "spectrometry"
#define MATERIAL_TEST_MICROSCOPY "microscopy"
#define MATERIAL_TEST_HARDNESS "hardness indentation"
#define MATERIAL_TEST_CONDUCTIVITY "conductivity probe"
#define MATERIAL_TEST_TENSILE "tensile test"
#define MATERIAL_TEST_CORROSION "corrosion exposure"
#define MATERIAL_TEST_FIELD "fabricated article field test"

#define MATERIAL_ATMOSPHERE_AIR "air"
#define MATERIAL_ATMOSPHERE_INERT "nitrogen"
#define MATERIAL_ATMOSPHERE_VACUUM "vacuum"
#define MATERIAL_ATMOSPHERE_REDUCING "hydrogen"

#define MATERIAL_APPLICATION_TOOL "engineering tool"
#define MATERIAL_APPLICATION_SURGICAL "surgical instrument"
#define MATERIAL_APPLICATION_CELL "power cell"
#define MATERIAL_APPLICATION_ARMOR "armor"
#define MATERIAL_APPLICATION_PRESSURE "pressure service"
#define MATERIAL_APPLICATION_MACHINE_PART "machine component"
#define MATERIAL_APPLICATION_PROJECTILE "projectile"
#define MATERIAL_APPLICATION_ELECTRONICS "electronic assembly"
#define MATERIAL_APPLICATION_FIREARM "firearm"
#define MATERIAL_APPLICATION_CONTAINER "container"
#define MATERIAL_APPLICATION_CAPACITOR "capacitor"
#define MATERIAL_APPLICATION_MANIPULATOR "servo manipulator"
#define MATERIAL_APPLICATION_MATTER_BIN "matter containment bin"
#define MATERIAL_APPLICATION_SCANNER "sensor module"
#define MATERIAL_APPLICATION_LASER "emitter module"
#define MATERIAL_APPLICATION_MAGAZINE "ammunition magazine"
#define MATERIAL_APPLICATION_CIRCUIT_BOARD "circuit board"
#define MATERIAL_APPLICATION_SOFT_GOODS "soft goods"
#define MATERIAL_APPLICATION_MECHANICAL "mechanical assembly"
#define MATERIAL_APPLICATION_ENERGY_DEVICE "powered device"
#define MATERIAL_APPLICATION_CABLE "electrical cable"
#define MATERIAL_APPLICATION_LIGHT "light source"
#define MATERIAL_APPLICATION_MONOLITHIC "single-material object"

// Universal manufactured-object roles. A design chooses a small meaningful
// subset; the finished object stores the material used for every role.
#define MATERIAL_ROLE_BODY "body"
#define MATERIAL_ROLE_STRUCTURE "structure"
#define MATERIAL_ROLE_WORKING "working surface"
#define MATERIAL_ROLE_GRIP "grip"
#define MATERIAL_ROLE_CONDUCTOR "conductor"
#define MATERIAL_ROLE_ELECTRODE "electrodes"
#define MATERIAL_ROLE_THERMAL "thermal buffer"
#define MATERIAL_ROLE_INSULATION "insulation"
#define MATERIAL_ROLE_LINER "liner"
#define MATERIAL_ROLE_JACKET "jacket"
#define MATERIAL_ROLE_OPTICAL "optical element"
#define MATERIAL_ROLE_CATALYST "catalyst"
#define MATERIAL_ROLE_SUBSTRATE "substrate"
#define MATERIAL_ROLE_CONTACTS "contacts"
#define MATERIAL_ROLE_BARREL "barrel"
#define MATERIAL_ROLE_DIELECTRIC "dielectric"
#define MATERIAL_ROLE_ACTUATOR "actuator"
#define MATERIAL_ROLE_BEARINGS "bearings"
#define MATERIAL_ROLE_SENSOR "sensor element"
#define MATERIAL_ROLE_EMITTER "emitter element"
#define MATERIAL_ROLE_FEED "feed mechanism"
#define MATERIAL_ROLE_SPRING "spring"
#define MATERIAL_ROLE_FRAME "frame"
#define MATERIAL_ROLE_FASTENERS "fasteners"
#define MATERIAL_ROLE_FABRIC "fabric"
#define MATERIAL_ROLE_CASING "cartridge case"
#define MATERIAL_ROLE_PRIMER "primer"

#define MATERIAL_LAYER_CORE "conductive/load-bearing core"
#define MATERIAL_LAYER_FUNCTIONAL "functional buffer"
#define MATERIAL_LAYER_LINER "internal liner"
#define MATERIAL_LAYER_JACKET "external jacket"

#define MATERIAL_COMPONENT_CABLE "power cable"
#define MATERIAL_COMPONENT_PIPE "pressure pipe"
#define MATERIAL_COMPONENT_VESSEL "chemical vessel"
#define MATERIAL_COMPONENT_STRUCTURE "structural panel"

#define MATERIAL_CABLE_REFERENCE_AREA 12
#define MATERIAL_PIPE_REFERENCE_RADIUS 40
#define MATERIAL_PIPE_REFERENCE_THICKNESS 4

#define COMSIG_MATERIAL_SURGERY "material_surgery"

#define CONTRACT_EVENT_MATERIAL_PROCESSED "material_processed"
#define CONTRACT_EVENT_MATERIAL_CERTIFIED "material_certified"

#define MATERIAL_SCIENCE_MAX_BATCH 50
#define MATERIAL_SCIENCE_REAGENT_SAMPLE 10

#define MATERIAL_COST_FEEDSTOCK "feedstock"
#define MATERIAL_COST_CHEMICALS "chemical additives"
#define MATERIAL_COST_CATALYSTS "catalysts"
#define MATERIAL_COST_ELECTRICITY "electricity"
#define MATERIAL_COST_MEDIA "process media"
#define MATERIAL_COST_LABOR "process time"
#define MATERIAL_COST_EQUIPMENT "equipment wear"
#define MATERIAL_COST_WASTE_HANDLING "waste handling"
#define MATERIAL_COST_RECOVERY "byproduct recovery"
#define MATERIAL_COST_WASTE "waste value"
#define MATERIAL_POWER_UNITS_PER_THALER 1000
#define MATERIAL_LABOR_COST_PER_SECOND 0.25
#define MATERIAL_EQUIPMENT_COST_PER_SECOND 0.1
