#define REPUTATION_MINIMUM -1000
#define REPUTATION_MAXIMUM 1000
#define REPUTATION_AFFILIATION_NET_CAP 0

#define REPUTATION_HATED -750
#define REPUTATION_HOSTILE -500
#define REPUTATION_UNFRIENDLY -250
#define REPUTATION_NEUTRAL 0
#define REPUTATION_FRIENDLY 250
#define REPUTATION_ALLIED 500
#define REPUTATION_REVERED 750

#define AFFILIATION_HOSTILE "Hostile"
#define AFFILIATION_OPPOSED "Opposed"
#define AFFILIATION_NEUTRAL "Neutral"
#define AFFILIATION_FRIENDLY "Friendly"
#define AFFILIATION_MEMBER "Member"

#define REPUTATION_FACTION_NANOTRASEN "nanotrasen"
#define REPUTATION_FACTION_SOLGOV "solgov"
#define REPUTATION_FACTION_CHIMERA "chimera_genetics"
#define REPUTATION_FACTION_ECLIPSE "eclipse_corporation"
#define REPUTATION_FACTION_SYNDICATE "syndicate"
#define REPUTATION_FACTION_TRADERS_GUILD "interstellar_traders_guild"
#define REPUTATION_FACTION_TALON "talon"
#define REPUTATION_FACTION_WORKERS_UNION "workers_union"
#define REPUTATION_FACTION_VEYMED "veymed"
