// Verb categories (plan 2.12). The dotted string is written once, here; every `set category`
// and every ADMIN_VERB/DEBUG_VERB category uses a VERB_CAT_* define. tools/ci/verb_category_lint.py
// rejects a raw string (shrink-only baseline). ADMIN_CATEGORY_* (admin_verb.dm) alias the Admin/
// Debug/... entries below.

#define VERB_CAT_ABILITIES "Abilities"
#define VERB_CAT_ABILITIES_AI "Abilities.AI"
#define VERB_CAT_ABILITIES_ALIEN "Abilities.Alien"
#define VERB_CAT_ABILITIES_ALRAUNE "Abilities.Alraune"
#define VERB_CAT_ABILITIES_ANTAG "Abilities.Antag"
#define VERB_CAT_ABILITIES_BEAR "Abilities.Bear"
#define VERB_CAT_ABILITIES_BORER "Abilities.Borer"
#define VERB_CAT_ABILITIES_BRAINSLUG "Abilities.Brainslug"
#define VERB_CAT_ABILITIES_CATSLUG "Abilities.Catslug"
#define VERB_CAT_ABILITIES_CLOWN "Abilities.Clown"
#define VERB_CAT_ABILITIES_DEMON "Abilities.Demon"
#define VERB_CAT_ABILITIES_DIONA "Abilities.Diona"
#define VERB_CAT_ABILITIES_DURAND "Abilities.Durand"
#define VERB_CAT_ABILITIES_GARGOYLE "Abilities.Gargoyle"
#define VERB_CAT_ABILITIES_GENERAL "Abilities.General"
#define VERB_CAT_ABILITIES_GOOSE "Abilities.Goose"
#define VERB_CAT_ABILITIES_HYENA "Abilities.Hyena"
#define VERB_CAT_ABILITIES_KURURAK "Abilities.Kururak"
#define VERB_CAT_ABILITIES_LEECH "Abilities.Leech"
#define VERB_CAT_ABILITIES_LEOPARDMANDER "Abilities.Leopardmander"
#define VERB_CAT_ABILITIES_LLEILL "Abilities.Lleill"
#define VERB_CAT_ABILITIES_MOB "Abilities.Mob"
#define VERB_CAT_ABILITIES_MORPH "Abilities.Morph"
#define VERB_CAT_ABILITIES_MOUSE "Abilities.Mouse"
#define VERB_CAT_ABILITIES_PAI "Abilities.pAI"
#define VERB_CAT_ABILITIES_PAI_COMMANDS "Abilities.pAI Commands"
#define VERB_CAT_ABILITIES_PROMETHEAN "Abilities.Promethean"
#define VERB_CAT_ABILITIES_PROTEAN "Abilities.Protean"
#define VERB_CAT_ABILITIES_RADIATION "Abilities.Radiation"
#define VERB_CAT_ABILITIES_SAKIMM "Abilities.Sakimm"
#define VERB_CAT_ABILITIES_SAVIK "Abilities.Savik"
#define VERB_CAT_ABILITIES_SECT_DRONE "Abilities.Sect Drone"
#define VERB_CAT_ABILITIES_SECT_QUEEN "Abilities.Sect Queen"
#define VERB_CAT_ABILITIES_SETTINGS "Abilities.Settings"
#define VERB_CAT_ABILITIES_SHADEKIN "Abilities.Shadekin"
#define VERB_CAT_ABILITIES_SHANTAK "Abilities.Shantak"
#define VERB_CAT_ABILITIES_SHAPESHIFT "Abilities.Shapeshift"
#define VERB_CAT_ABILITIES_SILICON "Abilities.Silicon"
#define VERB_CAT_ABILITIES_SPARKLEDOG "Abilities.Sparkledog"
#define VERB_CAT_ABILITIES_STARDOG "Abilities.Stardog"
#define VERB_CAT_ABILITIES_SUCCUBUS "Abilities.Succubus"
#define VERB_CAT_ABILITIES_SUPERPOWER "Abilities.Superpower"
#define VERB_CAT_ABILITIES_SYNX "Abilities.Synx"
#define VERB_CAT_ABILITIES_TEPPI "Abilities.Teppi"
#define VERB_CAT_ABILITIES_VORE "Abilities.Vore"
#define VERB_CAT_ABILITIES_VR "Abilities.VR"
#define VERB_CAT_ABILITIES_WEAVER "Abilities.Weaver"
#define VERB_CAT_ABILITIES_WORM "Abilities.Worm"
#define VERB_CAT_ABILITIES_XENO "Abilities.Xeno"
#define VERB_CAT_ABILITIES_XENOCHIMERA "Abilities.Xenochimera"
#define VERB_CAT_ADMIN "Admin"
#define VERB_CAT_ADMIN_CHAT "Admin.Chat"
#define VERB_CAT_ADMIN_EVENTS "Admin.Events"
#define VERB_CAT_ADMIN_FUN "Admin.Fun"
#define VERB_CAT_ADMIN_GAME "Admin.Game"
#define VERB_CAT_ADMIN_INVESTIGATE "Admin.Investigate"
#define VERB_CAT_ADMIN_IPINTEL "Admin.IPIntel"
#define VERB_CAT_ADMIN_LOGS "Admin.Logs"
#define VERB_CAT_ADMIN_MISC "Admin.Misc"
#define VERB_CAT_ADMIN_MODERATION "Admin.Moderation"
#define VERB_CAT_ADMIN_SECRETS "Admin.Secrets"
#define VERB_CAT_ADMIN_SHUTTLE "Admin.Shuttle"
#define VERB_CAT_ADMIN_SILICON "Admin.Silicon"
#define VERB_CAT_AI_CAMERA_CONTROL "AI.Camera Control"
#define VERB_CAT_AI_COMMANDS "AI.Commands"
#define VERB_CAT_AI_SETTINGS "AI.Settings"
#define VERB_CAT_AI_STATION_COMMANDS "AI.Station Commands"
#define VERB_CAT_AI_VORE "AI.Vore"
#define VERB_CAT_ALIEN "Alien"
#define VERB_CAT_AUGMENTS "Augments"
#define VERB_CAT_BLOB "Blob"
#define VERB_CAT_BOT_COMMANDS "Bot Commands"
#define VERB_CAT_CHANGELING "Changeling"
#define VERB_CAT_COMBAT "Combat"
#define VERB_CAT_COMMUNICATOR "Communicator"
#define VERB_CAT_DEBUG "Debug"
#define VERB_CAT_DEBUG_ASSETS "Debug.Assets"
#define VERB_CAT_DEBUG_DANGEROUS "Debug.Dangerous"
#define VERB_CAT_DEBUG_EVENTS "Debug.Events"
#define VERB_CAT_DEBUG_GAME "Debug.Game"
#define VERB_CAT_DEBUG_INVESTIGATE "Debug.Investigate"
#define VERB_CAT_DEBUG_MISC "Debug.Misc"
#define VERB_CAT_DEBUG_SERVER "Debug.Server"
#define VERB_CAT_DEBUG_SPRITES "Debug.Sprites"
#define VERB_CAT_EXOSUIT_INTERFACE "Exosuit Interface"
#define VERB_CAT_FUN_ADD_NIF "Fun.Add Nif"
#define VERB_CAT_FUN_DO_NOT "Fun.Do Not"
#define VERB_CAT_FUN_DROP_POD "Fun.Drop Pod"
#define VERB_CAT_FUN_EVENT_KIT "Fun.Event Kit"
#define VERB_CAT_FUN_NARRATE "Fun.Narrate"
#define VERB_CAT_FUN_SILICON "Fun.Silicon"
#define VERB_CAT_FUN_SOUNDS "Fun.Sounds"
#define VERB_CAT_GHOST_GAME "Ghost.Game"
#define VERB_CAT_GHOST_JOIN "Ghost.Join"
#define VERB_CAT_GHOST_MESSAGE "Ghost.Message"
#define VERB_CAT_GHOST_SETTINGS "Ghost.Settings"
#define VERB_CAT_HARDSUIT "Hardsuit"
#define VERB_CAT_HARDWARE "Hardware"
#define VERB_CAT_IC "IC"
#define VERB_CAT_IC_ANTAG "IC.Antag"
#define VERB_CAT_IC_CHAT "IC.Chat"
#define VERB_CAT_IC_EVENT "IC.Event"
#define VERB_CAT_IC_GAME "IC.Game"
#define VERB_CAT_IC_MOB "IC.Mob"
#define VERB_CAT_IC_NIF "IC.NIF"
#define VERB_CAT_IC_NOTES "IC.Notes"
#define VERB_CAT_IC_SETTINGS "IC.Settings"
#define VERB_CAT_IC_SUBTLE "IC.Subtle"
#define VERB_CAT_IC_TGUI_SAY "IC.TGUI Say"
#define VERB_CAT_IC_VORE "IC.Vore"
#define VERB_CAT_MAPPING "Mapping"
#define VERB_CAT_MAPPING_ATMOS "Mapping.Atmos"
#define VERB_CAT_MAPPING_TESTSERVER_ONLY "Mapping.Testserver Only"
#define VERB_CAT_OBJECT "Object"
#define VERB_CAT_OOC_CHAT "OOC.Chat"
#define VERB_CAT_OOC_CHAT_SETTINGS "OOC.Chat Settings"
#define VERB_CAT_OOC_CLIENT_SETTINGS "OOC.Client Settings"
#define VERB_CAT_OOC_DEBUG "OOC.Debug"
#define VERB_CAT_OOC_GAME "OOC.Game"
#define VERB_CAT_OOC_GAME_SETTINGS "OOC.Game Settings"
#define VERB_CAT_OOC_MOB_SETTINGS "OOC.Mob Settings"
#define VERB_CAT_OOC_RESOURCES "OOC.Resources"
#define VERB_CAT_OOC_SETTINGS "OOC.Settings"
#define VERB_CAT_OOC_VORE "OOC.Vore"
#define VERB_CAT_PREFERENCES_CHARACTER "Preferences.Character"
#define VERB_CAT_PREFERENCES_GAME "Preferences.Game"
#define VERB_CAT_PREFERENCES_SOUNDS "Preferences.Sounds"
#define VERB_CAT_PREFERENCES_VORE "Preferences.Vore"
#define VERB_CAT_PROFILE "Profile"
#define VERB_CAT_SERVER "Server"
#define VERB_CAT_SERVER_ADMIN "Server.Admin"
#define VERB_CAT_SERVER_CHAT "Server.Chat"
#define VERB_CAT_SERVER_CONFIG "Server.Config"
#define VERB_CAT_SERVER_GAME "Server.Game"
#define VERB_CAT_SLIME "Slime"
#define VERB_CAT_SOFTWARE "Software"
#define VERB_CAT_SOULCATCHER "Soulcatcher"
#define VERB_CAT_SPECIAL_VERBS "Special Verbs"
#define VERB_CAT_SUPERPOWER "Superpower"
