/datum/construction_graph/mecha/micro/polecat
	id = "mecha_micro_polecat"
	result = /obj/mecha/micro/sec/polecat
	icon_finished = 'icons/mecha/mech_construction_vr.dmi'
	icon_prefix = "polecat"
	feedback_key = "mecha_polecat_created"
	mecha_parts = list(/obj/item/mecha_parts/micro/part/polecat_torso, /obj/item/mecha_parts/micro/part/polecat_left_arm, /obj/item/mecha_parts/micro/part/polecat_right_arm, /obj/item/mecha_parts/micro/part/polecat_left_leg, /obj/item/mecha_parts/micro/part/polecat_right_leg)
	ladder = list(
		list("key" = TOOL_WELDER, "backkey" = TOOL_WRENCH, "desc" = "External armor is wrenched.", "fwd_self" = "You weld external armor layer to {HOLDER}.", "fwd_others" = "{USER} welds external armor layer to {HOLDER}.", "fwd_icon" = null, "fwd_span" = TRUE, "back_self" = "You unfasten the external armor layer.", "back_others" = "{USER} unfastens the external armor layer.", "back_icon" = "polecat19", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WRENCH, "backkey" = TOOL_CROWBAR, "desc" = "External armor is installed.", "fwd_self" = "You secure external reinforced armor layer.", "fwd_others" = "{USER} secures external armor layer.", "fwd_icon" = "polecat19", "fwd_span" = TRUE, "back_self" = "You pry the external armor layer from {HOLDER}.", "back_others" = "{USER} pries external armor layer from {HOLDER}.", "back_icon" = "polecat18", "back_span" = TRUE, "refund_type" = /obj/item/mecha_parts/micro/part/polecat_armour, "refund_amt" = 1),
		list("key" = /obj/item/mecha_parts/micro/part/polecat_armour, "backkey" = TOOL_WELDER, "desc" = "Internal armor is welded.", "fwd_self" = "You install external reinforced armor layer to {HOLDER}.", "fwd_others" = "{USER} installs external reinforced armor layer to {HOLDER}.", "fwd_icon" = "polecat18", "fwd_span" = TRUE, "back_self" = "You cut the internal armor layer from {HOLDER}.", "back_others" = "{USER} cuts internal armor layer from {HOLDER}.", "back_icon" = "polecat17", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WELDER, "backkey" = TOOL_WRENCH, "desc" = "Internal armor is wrenched", "fwd_self" = "You weld the internal armor layer to {HOLDER}.", "fwd_others" = "{USER} welds internal armor layer to {HOLDER}.", "fwd_icon" = "polecat17", "fwd_span" = TRUE, "back_self" = "You unfasten the internal armor layer.", "back_others" = "{USER} unfastens the internal armor layer.", "back_icon" = "polecat16", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WRENCH, "backkey" = TOOL_CROWBAR, "desc" = "Internal armor is installed", "fwd_self" = "You secure internal armor layer.", "fwd_others" = "{USER} secures internal armor layer.", "fwd_icon" = "polecat16", "fwd_span" = TRUE, "back_self" = "You prie internal armor layer from {HOLDER}.", "back_others" = "{USER} pries internal armor layer from {HOLDER}.", "back_icon" = "polecat15", "back_span" = TRUE, "refund_type" = /obj/item/stack/material/steel, "refund_amt" = 3),
		list("key" = /obj/item/stack/material/steel, "backkey" = TOOL_SCREWDRIVER, "desc" = "Advanced capacitor is secured", "fwd_self" = "You install internal armor layer to {HOLDER}.", "fwd_others" = "{USER} installs internal armor layer to {HOLDER}.", "fwd_icon" = "polecat15", "fwd_span" = TRUE, "back_self" = "You unfasten the advanced capacitor.", "back_others" = "{USER} unfastens the advanced capacitor.", "back_icon" = "polecat14", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Advanced capacitor is installed", "fwd_self" = "You secure the advanced capacitor.", "fwd_others" = "{USER} secures the advanced capacitor.", "fwd_icon" = "polecat14", "fwd_span" = TRUE, "back_self" = "You remove the advanced capacitor from {HOLDER}.", "back_others" = "{USER} removes the advanced capacitor from {HOLDER}.", "back_icon" = "polecat13", "back_span" = TRUE, "refund_type" = /obj/item/stock_parts/capacitor, "refund_amt" = 1),
		list("key" = /obj/item/stock_parts/capacitor, "backkey" = TOOL_SCREWDRIVER, "desc" = "Advanced scanner module is secured", "fwd_self" = "You install advanced capacitor to {HOLDER}.", "fwd_others" = "{USER} installs advanced capacitor to {HOLDER}.", "fwd_icon" = "polecat13", "fwd_span" = TRUE, "back_self" = "You unfasten the advanced scanner module.", "back_others" = "{USER} unfastens the advanced scanner module.", "back_icon" = "polecat12", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Advanced scanner module is installed", "fwd_self" = "You secure the advanced scanner module.", "fwd_others" = "{USER} secures the advanced scanner module.", "fwd_icon" = "polecat12", "fwd_span" = TRUE, "back_self" = "You remove the advanced scanner module from {HOLDER}.", "back_others" = "{USER} removes the advanced scanner module from {HOLDER}.", "back_icon" = "polecat11", "back_span" = TRUE, "refund_type" = /obj/item/stock_parts/scanning_module, "refund_amt" = 1),
		list("key" = /obj/item/stock_parts/scanning_module, "backkey" = TOOL_SCREWDRIVER, "desc" = "Targeting module is secured", "fwd_self" = "You install advanced scanner module to {HOLDER}.", "fwd_others" = "{USER} installs advanced scanner module to {HOLDER}.", "fwd_icon" = "polecat11", "fwd_span" = TRUE, "back_self" = "You unfasten the weapon control module.", "back_others" = "{USER} unfastens the weapon control module.", "back_icon" = "polecat10", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Targeting module is installed", "fwd_self" = "You secure the weapon control module.", "fwd_others" = "{USER} secures the weapon control module.", "fwd_icon" = "polecat10", "fwd_span" = TRUE, "back_self" = "You remove the weapon control module from {HOLDER}.", "back_others" = "{USER} removes the weapon control module from {HOLDER}.", "back_icon" = "polecat9", "back_span" = TRUE, "refund_type" = /obj/item/circuitboard/mecha/polecat/targeting, "refund_amt" = 1),
		list("key" = /obj/item/circuitboard/mecha/polecat/targeting, "backkey" = TOOL_SCREWDRIVER, "desc" = "Peripherals control module is secured", "fwd_self" = "You install the weapon control module into {HOLDER}.", "fwd_others" = "{USER} installs the weapon control module into {HOLDER}.", "fwd_icon" = "polecat9", "fwd_span" = TRUE, "back_self" = "You unfasten the peripherals control module.", "back_others" = "{USER} unfastens the peripherals control module.", "back_icon" = "polecat8", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Peripherals control module is installed", "fwd_self" = "You secure the peripherals control module.", "fwd_others" = "{USER} secures the peripherals control module.", "fwd_icon" = "polecat8", "fwd_span" = TRUE, "back_self" = "You remove the peripherals control module from {HOLDER}.", "back_others" = "{USER} removes the peripherals control module from {HOLDER}.", "back_icon" = "polecat7", "back_span" = TRUE, "refund_type" = /obj/item/circuitboard/mecha/polecat/peripherals, "refund_amt" = 1),
		list("key" = /obj/item/circuitboard/mecha/polecat/peripherals, "backkey" = TOOL_SCREWDRIVER, "desc" = "Central control module is secured", "fwd_self" = "You install the peripherals control module into {HOLDER}.", "fwd_others" = "{USER} installs the peripherals control module into {HOLDER}.", "fwd_icon" = "polecat7", "fwd_span" = TRUE, "back_self" = "You unfasten the mainboard.", "back_others" = "{USER} unfastens the mainboard.", "back_icon" = "polecat6", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Central control module is installed", "fwd_self" = "You secure the mainboard.", "fwd_others" = "{USER} secures the mainboard.", "fwd_icon" = "polecat6", "fwd_span" = TRUE, "back_self" = "You remove the central computer mainboard from {HOLDER}.", "back_others" = "{USER} removes the central control module from {HOLDER}.", "back_icon" = "polecat5", "back_span" = TRUE, "refund_type" = /obj/item/circuitboard/mecha/polecat/main, "refund_amt" = 1),
		list("key" = /obj/item/circuitboard/mecha/polecat/main, "backkey" = TOOL_SCREWDRIVER, "desc" = "The wiring is adjusted", "fwd_self" = "You install the central computer mainboard into {HOLDER}.", "fwd_others" = "{USER} installs the central control module into {HOLDER}.", "fwd_icon" = "polecat5", "fwd_span" = TRUE, "back_self" = "You disconnect the wiring of {HOLDER}.", "back_others" = "{USER} disconnects the wiring of {HOLDER}.", "back_icon" = "polecat4", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WIRECUTTER, "backkey" = TOOL_SCREWDRIVER, "desc" = "The wiring is added", "fwd_self" = "You adjust the wiring of {HOLDER}.", "fwd_others" = "{USER} adjusts the wiring of {HOLDER}.", "fwd_icon" = "polecat4", "fwd_span" = TRUE, "back_self" = "You remove the wiring from {HOLDER}.", "back_others" = "{USER} removes the wiring from {HOLDER}.", "back_icon" = "polecat3", "back_span" = TRUE, "refund_type" = /obj/item/stack/cable_coil, "refund_amt" = 4),
		list("key" = /obj/item/stack/cable_coil, "backkey" = TOOL_SCREWDRIVER, "desc" = "The hydraulic systems are active.", "fwd_self" = "You add the wiring to {HOLDER}.", "fwd_others" = "{USER} adds the wiring to {HOLDER}.", "fwd_icon" = "polecat3", "fwd_span" = TRUE, "back_self" = "You deactivate {HOLDER} hydraulic systems.", "back_others" = "{USER} deactivates {HOLDER} hydraulic systems.", "back_icon" = "polecat2", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_WRENCH, "desc" = "The hydraulic systems are connected.", "fwd_self" = "You activate {HOLDER} hydraulic systems.", "fwd_others" = "{USER} activates {HOLDER} hydraulic systems.", "fwd_icon" = "polecat2", "fwd_span" = TRUE, "back_self" = "You disconnect {HOLDER} hydraulic systems.", "back_others" = "{USER} disconnects {HOLDER} hydraulic systems", "back_icon" = "polecat1", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WRENCH, "backkey" = TOOL_CROWBAR, "desc" = "The hydraulic systems are disconnected.", "fwd_self" = "You connect {HOLDER} hydraulic systems.", "fwd_others" = "{USER} connects {HOLDER} hydraulic systems", "fwd_icon" = "polecat1", "fwd_span" = TRUE, "back_self" = "You disconnect {HOLDER} hydraulic systems.", "back_others" = "{USER} disconnects {HOLDER} hydraulic systems.", "back_icon" = "polecat0", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null)
		)

/datum/construction_graph/mecha/micro/gopher
	id = "mecha_micro_gopher"
	result = /obj/mecha/micro/utility/gopher
	icon_finished = 'icons/mecha/mech_construction_vr.dmi'
	icon_prefix = "gopher"
	feedback_key = "mecha_gopher_created"
	mecha_parts = list(/obj/item/mecha_parts/micro/part/gopher_torso, /obj/item/mecha_parts/micro/part/gopher_left_arm, /obj/item/mecha_parts/micro/part/gopher_right_arm, /obj/item/mecha_parts/micro/part/gopher_left_leg, /obj/item/mecha_parts/micro/part/gopher_right_leg)
	ladder = list(
		list("key" = TOOL_WELDER, "backkey" = TOOL_WRENCH, "desc" = "External armor is wrenched.", "fwd_self" = "You weld external armor layer to {HOLDER}.", "fwd_others" = "{USER} welds external armor layer to {HOLDER}.", "fwd_icon" = null, "fwd_span" = TRUE, "back_self" = "You unfasten the external armor layer.", "back_others" = "{USER} unfastens the external armor layer.", "back_icon" = "gopher13", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WRENCH, "backkey" = TOOL_CROWBAR, "desc" = "External armor is installed.", "fwd_self" = "You secure external reinforced armor layer.", "fwd_others" = "{USER} secures external armor layer.", "fwd_icon" = "gopher13", "fwd_span" = TRUE, "back_self" = "You prie external armor layer from {HOLDER}.", "back_others" = "{USER} pries external armor layer from {HOLDER}.", "back_icon" = "gopher12", "back_span" = TRUE, "refund_type" = /obj/item/stack/material/plasteel, "refund_amt" = 2),
		list("key" = /obj/item/stack/material/plasteel, "backkey" = TOOL_WELDER, "desc" = "Internal armor is welded.", "fwd_self" = "You install external reinforced armor layer to {HOLDER}.", "fwd_others" = "{USER} installs external reinforced armor layer to {HOLDER}.", "fwd_icon" = "gopher12", "fwd_span" = TRUE, "back_self" = "You cut the internal armor layer from {HOLDER}.", "back_others" = "{USER} cuts internal armor layer from {HOLDER}.", "back_icon" = "gopher11", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WELDER, "backkey" = TOOL_WRENCH, "desc" = "Internal armor is wrenched", "fwd_self" = "You weld the internal armor layer to {HOLDER}.", "fwd_others" = "{USER} welds internal armor layer to {HOLDER}.", "fwd_icon" = "gopher11", "fwd_span" = TRUE, "back_self" = "You unfasten the internal armor layer.", "back_others" = "{USER} unfastens the internal armor layer.", "back_icon" = "gopher10", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WRENCH, "backkey" = TOOL_CROWBAR, "desc" = "Internal armor is installed", "fwd_self" = "You secure internal armor layer.", "fwd_others" = "{USER} secures internal armor layer.", "fwd_icon" = "gopher10", "fwd_span" = TRUE, "back_self" = "You prie internal armor layer from {HOLDER}.", "back_others" = "{USER} pries internal armor layer from {HOLDER}.", "back_icon" = "gopher9", "back_span" = TRUE, "refund_type" = /obj/item/stack/material/steel, "refund_amt" = 3),
		list("key" = /obj/item/stack/material/steel, "backkey" = TOOL_SCREWDRIVER, "desc" = "Peripherals control module is secured", "fwd_self" = "You install internal armor layer to {HOLDER}.", "fwd_others" = "{USER} installs internal armor layer to {HOLDER}.", "fwd_icon" = "gopher9", "fwd_span" = TRUE, "back_self" = "You unfasten the peripherals control module.", "back_others" = "{USER} unfastens the peripherals control module.", "back_icon" = "gopher8", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Peripherals control module is installed", "fwd_self" = "You secure the peripherals control module.", "fwd_others" = "{USER} secures the peripherals control module.", "fwd_icon" = "gopher8", "fwd_span" = TRUE, "back_self" = "You remove the peripherals control module from {HOLDER}.", "back_others" = "{USER} removes the peripherals control module from {HOLDER}.", "back_icon" = "gopher7", "back_span" = TRUE, "refund_type" = /obj/item/circuitboard/mecha/gopher/peripherals, "refund_amt" = 1),
		list("key" = /obj/item/circuitboard/mecha/gopher/peripherals, "backkey" = TOOL_SCREWDRIVER, "desc" = "Central control module is secured", "fwd_self" = "You install the peripherals control module into {HOLDER}.", "fwd_others" = "{USER} installs the peripherals control module into {HOLDER}.", "fwd_icon" = "gopher7", "fwd_span" = TRUE, "back_self" = "You unfasten the mainboard.", "back_others" = "{USER} unfastens the mainboard.", "back_icon" = "gopher6", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Central control module is installed", "fwd_self" = "You secure the mainboard.", "fwd_others" = "{USER} secures the mainboard.", "fwd_icon" = "gopher6", "fwd_span" = TRUE, "back_self" = "You remove the central computer mainboard from {HOLDER}.", "back_others" = "{USER} removes the central control module from {HOLDER}.", "back_icon" = "gopher5", "back_span" = TRUE, "refund_type" = /obj/item/circuitboard/mecha/gopher/main, "refund_amt" = 1),
		list("key" = /obj/item/circuitboard/mecha/gopher/main, "backkey" = TOOL_SCREWDRIVER, "desc" = "The wiring is adjusted", "fwd_self" = "You install the central computer mainboard into {HOLDER}.", "fwd_others" = "{USER} installs the central control module into {HOLDER}.", "fwd_icon" = "gopher5", "fwd_span" = TRUE, "back_self" = "You disconnect the wiring of {HOLDER}.", "back_others" = "{USER} disconnects the wiring of {HOLDER}.", "back_icon" = "gopher4", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WIRECUTTER, "backkey" = TOOL_SCREWDRIVER, "desc" = "The wiring is added", "fwd_self" = "You adjust the wiring of {HOLDER}.", "fwd_others" = "{USER} adjusts the wiring of {HOLDER}.", "fwd_icon" = "gopher4", "fwd_span" = TRUE, "back_self" = "You remove the wiring from {HOLDER}.", "back_others" = "{USER} removes the wiring from {HOLDER}.", "back_icon" = "gopher3", "back_span" = TRUE, "refund_type" = /obj/item/stack/cable_coil, "refund_amt" = 4),
		list("key" = /obj/item/stack/cable_coil, "backkey" = TOOL_SCREWDRIVER, "desc" = "The hydraulic systems are active.", "fwd_self" = "You add the wiring to {HOLDER}.", "fwd_others" = "{USER} adds the wiring to {HOLDER}.", "fwd_icon" = "gopher3", "fwd_span" = TRUE, "back_self" = "You deactivate {HOLDER} hydraulic systems.", "back_others" = "{USER} deactivates {HOLDER} hydraulic systems.", "back_icon" = "gopher2", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_WRENCH, "desc" = "The hydraulic systems are connected.", "fwd_self" = "You activate {HOLDER} hydraulic systems.", "fwd_others" = "{USER} activates {HOLDER} hydraulic systems.", "fwd_icon" = "gopher2", "fwd_span" = TRUE, "back_self" = "You disconnect {HOLDER} hydraulic systems.", "back_others" = "{USER} disconnects {HOLDER} hydraulic systems", "back_icon" = "gopher1", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WRENCH, "backkey" = TOOL_CROWBAR, "desc" = "The hydraulic systems are disconnected.", "fwd_self" = "You connect {HOLDER} hydraulic systems.", "fwd_others" = "{USER} connects {HOLDER} hydraulic systems", "fwd_icon" = "gopher1", "fwd_span" = TRUE, "back_self" = "You disconnect {HOLDER} hydraulic systems.", "back_others" = "{USER} disconnects {HOLDER} hydraulic systems.", "back_icon" = "gopher0", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null)
		)

/datum/construction_graph/mecha/micro/weasel
	id = "mecha_micro_weasel"
	result = /obj/mecha/micro/sec/weasel
	icon_finished = 'icons/mecha/mech_construction_vr.dmi'
	icon_prefix = "weasel"
	feedback_key = "mecha_weasel_created"
	mecha_parts = list(/obj/item/mecha_parts/micro/part/weasel_torso, /obj/item/mecha_parts/micro/part/weasel_head, /obj/item/mecha_parts/micro/part/weasel_left_arm, /obj/item/mecha_parts/micro/part/weasel_right_arm, /obj/item/mecha_parts/micro/part/weasel_tri_leg)
	ladder = list(
		list("key" = TOOL_WELDER, "backkey" = TOOL_WRENCH, "desc" = "External armor is wrenched.", "fwd_self" = "You weld external armor layer to {HOLDER}.", "fwd_others" = "{USER} welds external armor layer to {HOLDER}.", "fwd_icon" = null, "fwd_span" = TRUE, "back_self" = "You unfasten the external armor layer.", "back_others" = "{USER} unfastens the external armor layer.", "back_icon" = "weasel19", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WRENCH, "backkey" = TOOL_CROWBAR, "desc" = "External armor is installed.", "fwd_self" = "You secure external reinforced armor layer.", "fwd_others" = "{USER} secures external armor layer.", "fwd_icon" = "weasel19", "fwd_span" = TRUE, "back_self" = "You prie external armor layer from {HOLDER}.", "back_others" = "{USER} pries external armor layer from {HOLDER}.", "back_icon" = "weasel18", "back_span" = TRUE, "refund_type" = /obj/item/stack/material/plasteel, "refund_amt" = 3),
		list("key" = /obj/item/stack/material/plasteel, "backkey" = TOOL_WELDER, "desc" = "Internal armor is welded.", "fwd_self" = "You install external reinforced armor layer to {HOLDER}.", "fwd_others" = "{USER} installs external reinforced armor layer to {HOLDER}.", "fwd_icon" = "weasel18", "fwd_span" = TRUE, "back_self" = "You cut the internal armor layer from {HOLDER}.", "back_others" = "{USER} cuts internal armor layer from {HOLDER}.", "back_icon" = "weasel17", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WELDER, "backkey" = TOOL_WRENCH, "desc" = "Internal armor is wrenched", "fwd_self" = "You weld the internal armor layer to {HOLDER}.", "fwd_others" = "{USER} welds internal armor layer to {HOLDER}.", "fwd_icon" = "weasel17", "fwd_span" = TRUE, "back_self" = "You unfasten the internal armor layer.", "back_others" = "{USER} unfastens the internal armor layer.", "back_icon" = "weasel16", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WRENCH, "backkey" = TOOL_CROWBAR, "desc" = "Internal armor is installed", "fwd_self" = "You secure internal armor layer.", "fwd_others" = "{USER} secures internal armor layer.", "fwd_icon" = "weasel16", "fwd_span" = TRUE, "back_self" = "You prie internal armor layer from {HOLDER}.", "back_others" = "{USER} pries internal armor layer from {HOLDER}.", "back_icon" = "weasel15", "back_span" = TRUE, "refund_type" = /obj/item/stack/material/steel, "refund_amt" = 3),
		list("key" = /obj/item/stack/material/steel, "backkey" = TOOL_SCREWDRIVER, "desc" = "Advanced capacitor is secured", "fwd_self" = "You install internal armor layer to {HOLDER}.", "fwd_others" = "{USER} installs internal armor layer to {HOLDER}.", "fwd_icon" = "weasel15", "fwd_span" = TRUE, "back_self" = "You unfasten the advanced capacitor.", "back_others" = "{USER} unfastens the advanced capacitor.", "back_icon" = "weasel14", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Advanced capacitor is installed", "fwd_self" = "You secure the advanced capacitor.", "fwd_others" = "{USER} secures the advanced capacitor.", "fwd_icon" = "weasel14", "fwd_span" = TRUE, "back_self" = "You remove the advanced capacitor from {HOLDER}.", "back_others" = "{USER} removes the advanced capacitor from {HOLDER}.", "back_icon" = "weasel13", "back_span" = TRUE, "refund_type" = /obj/item/stock_parts/capacitor, "refund_amt" = 1),
		list("key" = /obj/item/stock_parts/capacitor, "backkey" = TOOL_SCREWDRIVER, "desc" = "Advanced scanner module is secured", "fwd_self" = "You install advanced capacitor to {HOLDER}.", "fwd_others" = "{USER} installs advanced capacitor to {HOLDER}.", "fwd_icon" = "weasel13", "fwd_span" = TRUE, "back_self" = "You unfasten the advanced scanner module.", "back_others" = "{USER} unfastens the advanced scanner module.", "back_icon" = "weasel12", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Advanced scanner module is installed", "fwd_self" = "You secure the advanced scanner module.", "fwd_others" = "{USER} secures the advanced scanner module.", "fwd_icon" = "weasel12", "fwd_span" = TRUE, "back_self" = "You remove the advanced scanner module from {HOLDER}.", "back_others" = "{USER} removes the advanced scanner module from {HOLDER}.", "back_icon" = "weasel11", "back_span" = TRUE, "refund_type" = /obj/item/stock_parts/scanning_module, "refund_amt" = 1),
		list("key" = /obj/item/stock_parts/scanning_module, "backkey" = TOOL_SCREWDRIVER, "desc" = "Targeting module is secured", "fwd_self" = "You install advanced scanner module to {HOLDER}.", "fwd_others" = "{USER} installs advanced scanner module to {HOLDER}.", "fwd_icon" = "weasel11", "fwd_span" = TRUE, "back_self" = "You unfasten the weapon control module.", "back_others" = "{USER} unfastens the weapon control module.", "back_icon" = "weasel10", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Targeting module is installed", "fwd_self" = "You secure the weapon control module.", "fwd_others" = "{USER} secures the weapon control module.", "fwd_icon" = "weasel10", "fwd_span" = TRUE, "back_self" = "You remove the weapon control module from {HOLDER}.", "back_others" = "{USER} removes the weapon control module from {HOLDER}.", "back_icon" = "weasel9", "back_span" = TRUE, "refund_type" = /obj/item/circuitboard/mecha/weasel/targeting, "refund_amt" = 1),
		list("key" = /obj/item/circuitboard/mecha/weasel/targeting, "backkey" = TOOL_SCREWDRIVER, "desc" = "Peripherals control module is secured", "fwd_self" = "You install the weapon control module into {HOLDER}.", "fwd_others" = "{USER} installs the weapon control module into {HOLDER}.", "fwd_icon" = "weasel9", "fwd_span" = TRUE, "back_self" = "You unfasten the peripherals control module.", "back_others" = "{USER} unfastens the peripherals control module.", "back_icon" = "weasel8", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Peripherals control module is installed", "fwd_self" = "You secure the peripherals control module.", "fwd_others" = "{USER} secures the peripherals control module.", "fwd_icon" = "weasel8", "fwd_span" = TRUE, "back_self" = "You remove the peripherals control module from {HOLDER}.", "back_others" = "{USER} removes the peripherals control module from {HOLDER}.", "back_icon" = "weasel7", "back_span" = TRUE, "refund_type" = /obj/item/circuitboard/mecha/weasel/peripherals, "refund_amt" = 1),
		list("key" = /obj/item/circuitboard/mecha/weasel/peripherals, "backkey" = TOOL_SCREWDRIVER, "desc" = "Central control module is secured", "fwd_self" = "You install the peripherals control module into {HOLDER}.", "fwd_others" = "{USER} installs the peripherals control module into {HOLDER}.", "fwd_icon" = "weasel7", "fwd_span" = TRUE, "back_self" = "You unfasten the mainboard.", "back_others" = "{USER} unfastens the mainboard.", "back_icon" = "weasel6", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_CROWBAR, "desc" = "Central control module is installed", "fwd_self" = "You secure the mainboard.", "fwd_others" = "{USER} secures the mainboard.", "fwd_icon" = "weasel6", "fwd_span" = TRUE, "back_self" = "You remove the central computer mainboard from {HOLDER}.", "back_others" = "{USER} removes the central control module from {HOLDER}.", "back_icon" = "weasel5", "back_span" = TRUE, "refund_type" = /obj/item/circuitboard/mecha/weasel/main, "refund_amt" = 1),
		list("key" = /obj/item/circuitboard/mecha/weasel/main, "backkey" = TOOL_SCREWDRIVER, "desc" = "The wiring is adjusted", "fwd_self" = "You install the central computer mainboard into {HOLDER}.", "fwd_others" = "{USER} installs the central control module into {HOLDER}.", "fwd_icon" = "weasel5", "fwd_span" = TRUE, "back_self" = "You disconnect the wiring of {HOLDER}.", "back_others" = "{USER} disconnects the wiring of {HOLDER}.", "back_icon" = "weasel4", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WIRECUTTER, "backkey" = TOOL_SCREWDRIVER, "desc" = "The wiring is added", "fwd_self" = "You adjust the wiring of {HOLDER}.", "fwd_others" = "{USER} adjusts the wiring of {HOLDER}.", "fwd_icon" = "weasel4", "fwd_span" = TRUE, "back_self" = "You remove the wiring from {HOLDER}.", "back_others" = "{USER} removes the wiring from {HOLDER}.", "back_icon" = "weasel3", "back_span" = TRUE, "refund_type" = /obj/item/stack/cable_coil, "refund_amt" = 4),
		list("key" = /obj/item/stack/cable_coil, "backkey" = TOOL_SCREWDRIVER, "desc" = "The hydraulic systems are active.", "fwd_self" = "You add the wiring to {HOLDER}.", "fwd_others" = "{USER} adds the wiring to {HOLDER}.", "fwd_icon" = "weasel3", "fwd_span" = TRUE, "back_self" = "You deactivate {HOLDER} hydraulic systems.", "back_others" = "{USER} deactivates {HOLDER} hydraulic systems.", "back_icon" = "weasel2", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_SCREWDRIVER, "backkey" = TOOL_WRENCH, "desc" = "The hydraulic systems are connected.", "fwd_self" = "You activate {HOLDER} hydraulic systems.", "fwd_others" = "{USER} activates {HOLDER} hydraulic systems.", "fwd_icon" = "weasel2", "fwd_span" = TRUE, "back_self" = "You disconnect {HOLDER} hydraulic systems.", "back_others" = "{USER} disconnects {HOLDER} hydraulic systems", "back_icon" = "weasel1", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null),
		list("key" = TOOL_WRENCH, "backkey" = TOOL_CROWBAR, "desc" = "The hydraulic systems are disconnected.", "fwd_self" = "You connect {HOLDER} hydraulic systems.", "fwd_others" = "{USER} connects {HOLDER} hydraulic systems", "fwd_icon" = "weasel1", "fwd_span" = TRUE, "back_self" = "You disconnect {HOLDER} hydraulic systems.", "back_others" = "{USER} disconnects {HOLDER} hydraulic systems.", "back_icon" = "weasel0", "back_span" = TRUE, "refund_type" = null, "refund_amt" = null)
		)
