#define GENERATED_STATION_ISSUE_ERROR 1
#define GENERATED_STATION_ISSUE_WARNING 2

#define GENERATED_STATION_NODE_DEPARTMENT 1
#define GENERATED_STATION_NODE_TRANSIT 2
#define GENERATED_STATION_NODE_UTILITY 3

#define GENERATED_STATION_EDGE_ADJACENT 1
#define GENERATED_STATION_EDGE_TRANSIT 2
#define GENERATED_STATION_EDGE_UTILITY 3

#define GENERATED_DEPARTMENT_OFFLINE 1
#define GENERATED_DEPARTMENT_DEGRADED 2
#define GENERATED_DEPARTMENT_OPERATIONAL 3

#define GENERATED_STATION_ALERT_GREEN 1
#define GENERATED_STATION_ALERT_BLUE 2
#define GENERATED_STATION_ALERT_RED 3
#define GENERATED_STATION_ALERT_DELTA 4

#define GENERATED_STATION_ORDER_PENDING 1
#define GENERATED_STATION_ORDER_ACTIVE 2
#define GENERATED_STATION_ORDER_COMPLETE 3
#define GENERATED_STATION_ORDER_CANCELLED 4

#define GENERATED_STATION_MAX_SQUADS 12
#define GENERATED_STATION_MAX_SQUAD_MEMBERS 8
#define GENERATED_STATION_MAX_ORDERS 32

#define GENERATED_STATION_ORDER_INTERCEPT "intercept"
#define GENERATED_STATION_ORDER_DEFEND "defend"
#define GENERATED_STATION_ORDER_RETREAT "retreat"
#define GENERATED_STATION_ORDER_SEARCH "search"
#define GENERATED_STATION_ORDER_PATROL "patrol"
#define GENERATED_STATION_DEFENDER_FACTION "generated-station-defender"
#define GENERATED_STATION_DEFENDER_RETREAT_HEALTH 0.35
#define GENERATED_STATION_DEFENDER_DAMAGE_SIGNAL "dqai_damage_taken"
#define GENERATED_STATION_CONTACT_LIFETIME (2 MINUTES)
#define GENERATED_STATION_IRREGULAR_ROOM_MINIMUM_AREA_RATIO 0.4
#define GENERATED_STATION_SEARCH_DURATION (30 SECONDS)
#define GENERATED_STATION_PATROL_DURATION (20 SECONDS)
