// GENERATED by tools/analyze: `analyze gen declare`. Do not edit by hand; edit the declarations it reads.
// Written to code/engine/_generated/declare.dm; CI fails when this file is stale (`analyze gen --check`).

/// CAPABILITY_TYPE(bay_cell, CAP_CELL_BAY) at code/engine/library/bays.dm:106
/datum/capability/bay_cell
	var/slot_var = null
	var/bay = null
	var/accepts = /obj/item/cell
	var/starts = null
/proc/bay_cell(slot_var, bay, accepts, starts)
	RETURN_TYPE(/datum/capability/bay_cell)
	return cap_construct(CAP_CELL_BAY, /datum/capability/bay_cell, list(slot_var, bay, accepts, starts), "slot_var, bay, accepts, starts")
/datum/capdef_decl/c_bay_cell/spec()
	return list(CAP_CELL_BAY, /datum/capability/bay_cell, "slot_var", STACK, "cell_bay", "slot_var, bay, accepts, starts")

/// CAPABILITY_TYPE(bay_compartment, CAP_COMPARTMENT) at code/engine/library/bays.dm:74
/datum/capability/bay_compartment
	var/bay = null
	var/door = null
	var/applies_to = AUTH_PHYSICAL
/proc/bay_compartment(bay, door, applies_to)
	RETURN_TYPE(/datum/capability/bay_compartment)
	return cap_construct(CAP_COMPARTMENT, /datum/capability/bay_compartment, list(bay, door, applies_to), "bay, door, applies_to")
/datum/capdef_decl/c_bay_compartment/spec()
	return list(CAP_COMPARTMENT, /datum/capability/bay_compartment, "bay", STACK, "compartment", "bay, door, applies_to")

/// CAPABILITY_TYPE(construction_graph, CAP_CONSTRUCTION) at code/engine/declare/graph.dm:224
/datum/capability/construction
/proc/construction_graph(start, via)
	RETURN_TYPE(/datum/capability/construction)
	return cap_construct(CAP_CONSTRUCTION, /datum/capability/construction, list(start, via), "start, via")
/datum/capdef_decl/c_construction_graph/spec()
	return list(CAP_CONSTRUCTION, /datum/capability/construction, NONE, STACK, "construction", "start, via")

/// CAPABILITY_TYPE(cover, CAP_COVER) at code/engine/library/bays.dm:34
/datum/capability/bay_cover
	var/name = "cover"
	var/tool = BY_HAND
	var/removable = FALSE
	var/starts_open = FALSE
/proc/cover(name, tool, removable, starts_open)
	RETURN_TYPE(/datum/capability/bay_cover)
	return cap_construct(CAP_COVER, /datum/capability/bay_cover, list(name, tool, removable, starts_open), "name, tool, removable, starts_open")
/datum/capdef_decl/c_cover/spec()
	return list(CAP_COVER, /datum/capability/bay_cover, "name", STACK, "cover", "name, tool, removable, starts_open")

/// CAPABILITY_TYPE(deployment_graph, CAP_DEPLOYMENT) at code/engine/declare/graph.dm:225
/datum/capability/construction/deployment
/proc/deployment_graph(start, via)
	RETURN_TYPE(/datum/capability/construction/deployment)
	return cap_construct(CAP_DEPLOYMENT, /datum/capability/construction/deployment, list(start, via), "start, via")
/datum/capdef_decl/c_deployment_graph/spec()
	return list(CAP_DEPLOYMENT, /datum/capability/construction/deployment, NONE, STACK, "deployment", "start, via")

/// CAPABILITY_DEF(telekinesis, CAP_TELEKINESIS) at code/engine/library/bays.dm:179
/proc/telekinesis()
	RETURN_TYPE(/datum/capability/def/telekinesis)
	return cap_construct(CAP_TELEKINESIS, /datum/capability/def/telekinesis, list(), "")
/datum/capdef_decl/c_telekinesis/spec()
	return list(CAP_TELEKINESIS, /datum/capability/def/telekinesis, NONE, STACK, "telekinesis", "")

/// cap_keys(CAP_COVER) at code/engine/library/bays.dm:35
/datum/cap_keys_decl/k_cover/spec()
	return list(CAP_COVER, list(OPEN = MSG(cover/closed), REMOVED = MSG(cover/still_on)))
/// The state key OPEN of cover, read on a holder (a granted capability with several selectors names the selector).
/proc/cover_open(datum/holder, selector)
	return cap_key_get(holder, COVER_OPEN, selector)
/// The state key REMOVED of cover, read on a holder (a granted capability with several selectors names the selector).
/proc/cover_removed(datum/holder, selector)
	return cap_key_get(holder, COVER_REMOVED, selector)

/datum/stage_def/door_frame/spec()
	return list(STAGE_DOOR_FRAME, "door", "frame")
/datum/stage_def/door_wired/spec()
	return list(STAGE_DOOR_WIRED, "door", "wired")
/datum/stage_def/door_boarded/spec()
	return list(STAGE_DOOR_BOARDED, "door", "boarded")
/datum/stage_def/door_finished/spec()
	return list(STAGE_DOOR_FINISHED, "door", "finished")
/datum/source_def/status/spec()
	return list(SRC_STATUS, "status")
/datum/source_def/vv/spec()
	return list(SRC_VV, "vv")
/datum/source_def/ai_control/spec()
	return list(SRC_AI_CONTROL, "ai_control")
/datum/source_def/held_item/spec()
	return list(SRC_HELD_ITEM, "held_item")
/datum/source_def/all/spec()
	return list(SRC_ALL, "all")

/// CAPABILITIES(/datum/pending_op) at code/engine/parts/run.dm:306
/datum/pending_op/declared_entries(list/into)
	..(into)
	into += entry_block("code/engine/parts/run.dm", 306, /datum/pending_op)
	into += entry_line(307)
	into += list(global.ref_one(nameof(holder), /datum, on_other_deleted = OTHER_DELETE_ME))
	into += entry_line(308)
	into += list(global.ref_one(nameof(target), /datum, on_other_deleted = OTHER_DELETE_ME))
	into += entry_line(309)
	into += list(global.ref_one(nameof(actor), /mob, on_other_deleted = OTHER_DELETE_ME))
	into += entry_line(310)
	into += list(global.ref_one(nameof(held), /obj/item, on_other_deleted = OTHER_DELETE_ME))

#if defined(UNIT_TESTS) || defined(SPACEMAN_DMM)

/// CAPABILITY_TYPE(e0_door, CAP_E0_DOOR) at code/tests/engine/fixtures.dm:144
/proc/e0_door()
	RETURN_TYPE(/datum/capability/e0_door)
	return cap_construct(CAP_E0_DOOR, /datum/capability/e0_door, list(), "")
/datum/capdef_decl/c_e0_door/spec()
	return list(CAP_E0_DOOR, /datum/capability/e0_door, NONE, STACK, "e0_door", "")

/// CAPABILITY_TYPE(e0_mirror_plating, CAP_E0_MIRROR) at code/tests/engine/fixtures.dm:34
/datum/e0_cap/mirror
	var/reflect_chance = 30
/proc/e0_mirror_plating(reflect_chance)
	RETURN_TYPE(/datum/e0_cap/mirror)
	return cap_construct(CAP_E0_MIRROR, /datum/e0_cap/mirror, list(reflect_chance), "reflect_chance")
/datum/capdef_decl/c_e0_mirror_plating/spec()
	return list(CAP_E0_MIRROR, /datum/e0_cap/mirror, NONE, BEST(reflect_chance), "e0_mirror_plating", "reflect_chance")

/// CAPABILITY_TYPE(e0_phase_shift, CAP_PHASE_SHIFT) at code/tests/engine/fixtures.dm:51
/datum/e0_cap/phase_shift
	var/cost = 50
/proc/e0_phase_shift(cost)
	RETURN_TYPE(/datum/e0_cap/phase_shift)
	return cap_construct(CAP_PHASE_SHIFT, /datum/e0_cap/phase_shift, list(cost), "cost")
/datum/capdef_decl/c_e0_phase_shift/spec()
	return list(CAP_PHASE_SHIFT, /datum/e0_cap/phase_shift, NONE, STACK, "phase_shift", "cost")

/// CAPABILITY_TYPE(e0_phased, CAP_PHASED) at code/tests/engine/fixtures.dm:66
/datum/e0_cap/phased
	var/drain = 1
/proc/e0_phased(drain)
	RETURN_TYPE(/datum/e0_cap/phased)
	return cap_construct(CAP_PHASED, /datum/e0_cap/phased, list(drain), "drain")
/datum/capdef_decl/c_e0_phased/spec()
	return list(CAP_PHASED, /datum/e0_cap/phased, NONE, STACK, "phased", "drain")

/// CAPABILITY_TYPE(e1_beacon, CAP_E1_BEACON) at code/tests/engine/e1_fixtures.dm:49
/proc/e1_beacon()
	RETURN_TYPE(/datum/capability/e1_beacon)
	return cap_construct(CAP_E1_BEACON, /datum/capability/e1_beacon, list(), "")
/datum/capdef_decl/c_e1_beacon/spec()
	return list(CAP_E1_BEACON, /datum/capability/e1_beacon, NONE, STACK, "e1_beacon", "")

/// CAPABILITY_TYPE(e1_nested, CAP_E1_NESTED) at code/tests/engine/e1_fixtures.dm:44
/proc/e1_nested()
	RETURN_TYPE(/datum/capability/e1_nested)
	return cap_construct(CAP_E1_NESTED, /datum/capability/e1_nested, list(), "")
/datum/capdef_decl/c_e1_nested/spec()
	return list(CAP_E1_NESTED, /datum/capability/e1_nested, NONE, STACK, "e1_nested", "")

/// CAPABILITY_TYPE(e1_solo, CAP_E1_SOLO) at code/tests/engine/e1_fixtures.dm:22
/datum/capability/e1_solo
	var/note = "plain"
/proc/e1_solo(note)
	RETURN_TYPE(/datum/capability/e1_solo)
	return cap_construct(CAP_E1_SOLO, /datum/capability/e1_solo, list(note), "note")
/datum/capdef_decl/c_e1_solo/spec()
	return list(CAP_E1_SOLO, /datum/capability/e1_solo, NONE, STACK, "e1_solo", "note")

/// CAPABILITY_TYPE(e1_widget, CAP_E1_WIDGET) at code/tests/engine/e1_fixtures.dm:9
/datum/capability/e1_widget
	var/label = "main"
	var/power = 1
/proc/e1_widget(label, power)
	RETURN_TYPE(/datum/capability/e1_widget)
	return cap_construct(CAP_E1_WIDGET, /datum/capability/e1_widget, list(label, power), "label, power")
/datum/capdef_decl/c_e1_widget/spec()
	return list(CAP_E1_WIDGET, /datum/capability/e1_widget, "label", BEST(power), "e1_widget", "label, power")

/// CAPABILITY_TYPE(p1_ticker, CAP_P1_TICKER) at code/tests/engine/p1_fixtures.dm:13
/datum/capability/p1_ticker
	var/power = 1
/proc/p1_ticker(power)
	RETURN_TYPE(/datum/capability/p1_ticker)
	return cap_construct(CAP_P1_TICKER, /datum/capability/p1_ticker, list(power), "power")
/datum/capdef_decl/c_p1_ticker/spec()
	return list(CAP_P1_TICKER, /datum/capability/p1_ticker, NONE, BEST(power), "p1_ticker", "power")

/// cap_keys(CAP_E1_SOLO) at code/tests/engine/e1_fixtures.dm:41
/datum/cap_keys_decl/k_e1_solo/spec()
	return list(CAP_E1_SOLO, list(ARMED = null, LIT = null))
/// The state key ARMED of e1_solo, read on a holder (a granted capability with several selectors names the selector).
/proc/e1_solo_armed(datum/holder, selector)
	return cap_key_get(holder, E1_SOLO_ARMED, selector)
/// The state key LIT of e1_solo, read on a holder (a granted capability with several selectors names the selector).
/proc/e1_solo_lit(datum/holder, selector)
	return cap_key_get(holder, E1_SOLO_LIT, selector)

/// cap_keys(CAP_E0_DOOR) at code/tests/engine/fixtures.dm:145
/datum/cap_keys_decl/k_e0_door/spec()
	return list(CAP_E0_DOOR, list(OPEN = null))
/// The state key OPEN of e0_door, read on a holder (a granted capability with several selectors names the selector).
/proc/e0_door_open(datum/holder, selector)
	return cap_key_get(holder, E0_DOOR_OPEN, selector)

/// STATE_GRAPH(GRAPH_DOOR_ASSEMBLY) at code/tests/engine/e1_fixtures.dm:179
/datum/graph_decl/g_graph_door_assembly/spec()
	return list(GRAPH_DOOR_ASSEMBLY, global.start(STAGE_DOOR_FRAME), global.stage(STAGE_DOOR_WIRED, global.stack(/obj/item/stack/cable_coil, 5)), global.stage(STAGE_DOOR_BOARDED, global.item(/obj/item/e0_fixture/board), global.put_in(SLOT_CONSTRUCTION)), global.stage(STAGE_DOOR_FINISHED, global.tool(TOOL_SCREWDRIVER), global.wait(0), from = STAGE_DOOR_BOARDED), global.stage(STAGE_DOOR_FINISHED, global.item(/obj/item/e0_fixture/door_kit), global.consumes(), from = STAGE_DOOR_WIRED, key = "kit", undo = list(global.tool(TOOL_CROWBAR), global.wait(0))), global.dismantle(global.tool(TOOL_WELDER)))

/// CAPABILITIES(/datum/e0_chain_node) at code/tests/engine/fixtures.dm:319
/datum/e0_chain_node/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 319, /datum/e0_chain_node)
	into += entry_line(319)
	into += list(global.on_notice(/datum/notice/e0_chain, global.then(PROC_REF(hear))))

/// CAPABILITIES(/datum/e0_species/shifter) at code/tests/engine/fixtures.dm:92
/datum/e0_species/shifter/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 92, /datum/e0_species/shifter)
	into += entry_line(92)
	into += list(global.e0_phase_shift())

/// CAPABILITIES(/datum/e1_species/alpha) at code/tests/engine/e1_fixtures.dm:61
/datum/e1_species/alpha/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 61, /datum/e1_species/alpha)
	into += entry_line(61)
	into += list(global.e1_widget("species", power = 5))
	into += entry_line(61)
	into += list(global.e1_beacon())

/// CAPABILITIES(/datum/e1_species/beta) at code/tests/engine/e1_fixtures.dm:66
/datum/e1_species/beta/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 66, /datum/e1_species/beta)
	into += entry_line(66)
	into += list(global.e1_solo())

/// CAPABILITIES(/datum/om_test_entity/e4_twin) at code/tests/engine/e4_fixtures.dm:151
/datum/om_test_entity/e4_twin/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 151, /datum/om_test_entity/e4_twin)
	into += entry_line(152)
	into += list(global.on_notice(/datum/notice/atom_bumped, global.then(PROC_REF(notice_heard))))

/// CAPABILITIES(/mob/living/simple_mob/e0_fixture) at code/tests/engine/fixtures.dm:112
/mob/living/simple_mob/e0_fixture/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 112, /mob/living/simple_mob/e0_fixture)
	into += entry_line(113)
	into += list(global.ref_one(nameof(species), /datum/e0_species))
	into += entry_line(114)
	into += list(global.rel_grants(nameof(species)))
	into += entry_line(115)
	into += list(global.hands())

/// CAPABILITIES(/obj/e0_fixture/cabinet) at code/tests/engine/fixtures.dm:257
/obj/e0_fixture/cabinet/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 257, /obj/e0_fixture/cabinet)
	into += entry_line(258)
	into += list(global.cover(starts_open = TRUE))
	into += entry_line(259)
	into += list(global.bay_compartment(BAY_CABINET, door = CAP_COVER))
	into += entry_line(260)
	into += list(global.bay_cell(nameof(cell), bay = BAY_CABINET, accepts = /obj/item/e0_fixture/cell, starts = /obj/item/e0_fixture/cell))
	into += entry_line(261)
	into += list(global.op("pry_panel", global.tool(TOOL_CROWBAR), global.priority(global.above("cell_bay.cell.take")), global.wait(5 SECONDS), global.toggles(nameof(panel_open))))

/// CAPABILITIES(/obj/e0_fixture/door) at code/tests/engine/fixtures.dm:160
/obj/e0_fixture/door/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 160, /obj/e0_fixture/door)
	into += entry_line(161)
	into += list(global.e0_door())
	into += entry_line(162)
	into += list(global.when(E0_DOOR_OPEN, global.contributes(STAT_DENSITY, FALSE, priority = PRIORITY_FORCE)))

/// CAPABILITIES(/obj/e0_fixture/door_assembly) at code/tests/engine/fixtures.dm:348
/obj/e0_fixture/door_assembly/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 348, /obj/e0_fixture/door_assembly)
	into += entry_line(349)
	into += list(global.construction(GRAPH_DOOR_ASSEMBLY))

/// CAPABILITIES(/obj/e0_fixture/door_assembly/finished) at code/tests/engine/fixtures.dm:365
/obj/e0_fixture/door_assembly/finished/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 365, /obj/e0_fixture/door_assembly/finished)
	into += entry_line(366)
	into += list(global.configure(global.construction_graph(start = STAGE_DOOR_FINISHED, via = list(STAGE_DOOR_WIRED, STAGE_DOOR_BOARDED))))

/// CAPABILITIES(/obj/e0_fixture/hopper) at code/tests/engine/fixtures.dm:216
/obj/e0_fixture/hopper/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 216, /obj/e0_fixture/hopper)
	into += entry_line(217)
	into += list(global.slot(SLOT_HOPPER, accepts = list(/obj/item/e0_fixture/sheets), capacity = E0_HOPPER_CAPACITY))
	into += entry_line(218)
	into += list(global.op("load", global.stack(/obj/item/e0_fixture/sheets, E0_SHEETS_PER_LOAD), global.wait(2 SECONDS), global.put_in(SLOT_HOPPER), global.says(MSG(fab/loaded)), global.logs(LOG_GAME)))

/// CAPABILITIES(/obj/e0_fixture/lamp) at code/tests/engine/fixtures.dm:289
/obj/e0_fixture/lamp/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 289, /obj/e0_fixture/lamp)
	into += entry_line(290)
	into += list(global.contributes(STAT_E0_LAMP_RANGE, PROC_REF(lit_range)))

/// CAPABILITIES(/obj/e0_fixture/library) at code/tests/engine/fixtures.dm:177
/obj/e0_fixture/library/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 177, /obj/e0_fixture/library)
	into += entry_line(178)
	into += list(global.op("select", global.ui_act(global.arg("id", global.int(1))), global.then(PROC_REF(select_row))))
	into += entry_line(179)
	into += list(global.op("print", global.ui_act(), global.needs(global.req_is(nameof(selected_id), because = MSG(library/nothing_selected))), global.confirms("Print the selected book?"), global.captures(nameof(selected_id)), global.then(PROC_REF(print_book)), global.logs(LOG_GAME)))

/// CAPABILITIES(/obj/e0_fixture/library/strict) at code/tests/engine/fixtures.dm:198
/obj/e0_fixture/library/strict/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 198, /obj/e0_fixture/library/strict)
	into += entry_line(199)
	into += list(global.extend("print", global.captures(nameof(selected_id), resume = CANCEL_IF_CHANGED)))

/// CAPABILITIES(/obj/e0_fixture/p1_impure) at code/tests/engine/p1_fixtures.dm:45
/obj/e0_fixture/p1_impure/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/p1_fixtures.dm", 45, /obj/e0_fixture/p1_impure)
	into += entry_line(46)
	into += list(global.op("writes", global.hand(), global.when(PROC_REF(writes_in_condition)), global.then(PROC_REF(ran))))
	into += entry_line(47)
	into += list(global.op("touches", global.menu(), global.needs(global.req(PROC_REF(writes_in_requirement), because = MSG(p1/not_ready))), global.then(PROC_REF(ran))))
	into += entry_line(48)
	into += list(global.op("clean", global.item(/obj/item/e2_key), global.when(PROC_REF(reads_only)), global.then(PROC_REF(ran))))

/// CAPABILITIES(/obj/e0_fixture/p1_waiter) at code/tests/engine/p1_fixtures.dm:75
/obj/e0_fixture/p1_waiter/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/p1_fixtures.dm", 75, /obj/e0_fixture/p1_waiter)
	into += entry_line(76)
	into += list(global.op("press", global.hand(), global.needs(global.req_is(nameof(ready), because = MSG(p1/not_ready))), global.wait(5 SECONDS), global.then(PROC_REF(done))))

/// CAPABILITIES(/obj/e0_fixture/pump) at code/tests/engine/fixtures.dm:384
/obj/e0_fixture/pump/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 384, /obj/e0_fixture/pump)
	into += entry_line(385)
	into += list(global.interface("E0Pump", title = "Gas Pump"))
	into += entry_line(386)
	into += list(global.ui_shape(target_pressure))
	into += entry_line(387)
	into += list(global.op("set_pressure", global.ui_act(global.arg("pressure", from = nameof(target_pressure))), global.then(PROC_REF(set_pressure))))

/// CAPABILITIES(/obj/e1_assembly) at code/tests/engine/e1_fixtures.dm:190
/obj/e1_assembly/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 190, /obj/e1_assembly)
	into += entry_line(190)
	into += list(global.construction(GRAPH_DOOR_ASSEMBLY))

/// CAPABILITIES(/obj/e1_assembly/finished) at code/tests/engine/e1_fixtures.dm:196
/obj/e1_assembly/finished/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 196, /obj/e1_assembly/finished)
	into += entry_line(196)
	into += list(global.configure(global.construction_graph(start = STAGE_DOOR_FINISHED, via = list(STAGE_DOOR_WIRED, STAGE_DOOR_BOARDED))))

/// CAPABILITIES(/obj/e1_fixture) at code/tests/engine/e1_fixtures.dm:93
/obj/e1_fixture/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 93, /obj/e1_fixture)
	into += entry_line(94)
	into += list(global.e1_solo())
	into += entry_line(95)
	into += list(global.e1_widget("a", power = 2))
	into += entry_line(96)
	into += list(global.ref_one(nameof(species), /datum/e1_species))
	into += entry_line(97)
	into += list(global.rel_grants(nameof(species)))
	into += entry_line(98)
	into += list(global.owns_one(nameof(gizmo), /obj/item/e1_part, starts = /obj/item/e1_part))
	into += entry_line(99)
	into += list(global.owns_many(nameof(gizmos), /obj/item/e1_part))
	into += entry_line(100)
	into += list(global.ref_many(nameof(watchers), /mob))
	into += entry_line(101)
	into += list(global.entry_link("/obj/e1_fixture::partner", "/obj/e1_fixture::partner"))
	into += entry_line(102)
	into += list(global.slot("e1_slot", accepts = list(/obj/item/e1_part), capacity = 1))
	into += entry_line(103)
	into += list(global.while_slotted("e1_slot", global.e1_beacon(), on = ON_HOLDER))
	into += entry_line(104)
	into += list(global.when(nameof(e1_armed), global.entry_of("contributes", "armed_glow", stat = STAT_LIGHT_RANGE, value = 4)))
	into += entry_line(105)
	into += list(global.entry_of("op", "toggle"))

/// CAPABILITIES(/obj/e1_fixture/changed) at code/tests/engine/e1_fixtures.dm:114
/obj/e1_fixture/changed/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 114, /obj/e1_fixture/changed)
	into += entry_line(115)
	into += list(global.extend("toggle", global.entry_of("part", "needs")))
	into += entry_line(116)
	into += list(global.configure(global.e1_widget("a", power = 9)))
	into += entry_line(117)
	into += list(global.without(CAP_E1_SOLO))

/// CAPABILITIES(/obj/e1_starts) at code/tests/engine/e1_fixtures.dm:143
/obj/e1_starts/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 143, /obj/e1_starts)
	into += entry_line(144)
	into += list(global.owns_one(nameof(picked), /obj/item/e1_part, starts = global.pick_one(list(/obj/item/e1_part/tarnished = 1))))
	into += entry_line(145)
	into += list(global.owns_one(nameof(conditional), /obj/item/e1_part, starts = global.when(nameof(flag), /obj/item/e1_part/tarnished)))
	into += entry_line(146)
	into += list(global.owns_one(nameof(skipped), /obj/item/e1_part, starts = global.when(nameof(off_flag), /obj/item/e1_part/tarnished)))
	into += entry_line(147)
	into += list(global.owns_many(nameof(counted), /obj/item/e1_part, starts = list(/obj/item/e1_part = 2)))
	into += entry_line(148)
	into += list(global.owns_one(nameof(argy), /datum/e1_argy, starts = /datum/e1_argy, starts_args = list("hello")))
	into += entry_line(149)
	into += list(global.owns_one(nameof(computed), /obj/item/e1_part, starts = PROC_REF(make_computed)))

/// CAPABILITIES(/obj/e2_bench_stack) at code/tests/engine/e2_bench_fixtures.dm:41
/obj/e2_bench_stack/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_bench_fixtures.dm", 41, /obj/e2_bench_stack)
	into += entry_line(42)
	into += list(global.op("hand_use", global.hand(), global.then(PROC_REF(note_use))))
	into += entry_line(43)
	into += list(global.op("key1", global.item(/obj/item/e2_bench_key1), global.then(PROC_REF(note_use))))
	into += entry_line(44)
	into += list(global.op("key2", global.item(/obj/item/e2_bench_key2), global.then(PROC_REF(note_use))))
	into += entry_line(45)
	into += list(global.op("key3", global.item(/obj/item/e2_bench_key3), global.then(PROC_REF(note_use))))
	into += entry_line(46)
	into += list(global.op("key4", global.item(/obj/item/e2_bench_key4), global.then(PROC_REF(note_use))))
	into += entry_line(47)
	into += list(global.op("key5", global.item(/obj/item/e2_bench_key5), global.then(PROC_REF(note_use))))
	into += entry_line(48)
	into += list(global.op("key6", global.item(/obj/item/e2_bench_key6), global.then(PROC_REF(note_use))))
	into += entry_line(49)
	into += list(global.op("key7", global.item(/obj/item/e2_bench_key7), global.then(PROC_REF(note_use))))
	into += entry_line(50)
	into += list(global.op("key8", global.item(/obj/item/e2_bench_key8), global.then(PROC_REF(note_use))))
	into += entry_line(51)
	into += list(global.op("key9", global.item(/obj/item/e2_bench_key9), global.then(PROC_REF(note_use))))
	into += entry_line(52)
	into += list(global.op("key10", global.item(/obj/item/e2_bench_key10), global.then(PROC_REF(note_use))))
	into += entry_line(53)
	into += list(global.op("key11", global.item(/obj/item/e2_bench_key11), global.then(PROC_REF(note_use))))
	into += entry_line(54)
	into += list(global.op("key12", global.item(/obj/item/e2_bench_key12), global.then(PROC_REF(note_use))))
	into += entry_line(55)
	into += list(global.op("key13", global.item(/obj/item/e2_bench_key13), global.then(PROC_REF(note_use))))
	into += entry_line(56)
	into += list(global.op("key14", global.item(/obj/item/e2_bench_key14), global.then(PROC_REF(note_use))))
	into += entry_line(57)
	into += list(global.op("key15", global.item(/obj/item/e2_bench_key15), global.then(PROC_REF(note_use))))
	into += entry_line(58)
	into += list(global.op("key16", global.item(/obj/item/e2_bench_key16), global.then(PROC_REF(note_use))))
	into += entry_line(59)
	into += list(global.op("key17", global.item(/obj/item/e2_bench_key17), global.then(PROC_REF(note_use))))
	into += entry_line(60)
	into += list(global.op("key18", global.item(/obj/item/e2_bench_key18), global.then(PROC_REF(note_use))))
	into += entry_line(61)
	into += list(global.op("key19", global.item(/obj/item/e2_bench_key19), global.then(PROC_REF(note_use))))
	into += entry_line(62)
	into += list(global.op("key20", global.item(/obj/item/e2_bench_key20), global.then(PROC_REF(note_use))))
	into += entry_line(63)
	into += list(global.op("key21", global.item(/obj/item/e2_bench_key21), global.then(PROC_REF(note_use))))
	into += entry_line(64)
	into += list(global.op("key22", global.item(/obj/item/e2_bench_key22), global.then(PROC_REF(note_use))))
	into += entry_line(65)
	into += list(global.op("key23", global.item(/obj/item/e2_bench_key23), global.then(PROC_REF(note_use))))
	into += entry_line(66)
	into += list(global.op("key24", global.item(/obj/item/e2_bench_key24), global.then(PROC_REF(note_use))))
	into += entry_line(67)
	into += list(global.op("key25", global.item(/obj/item/e2_bench_key25), global.then(PROC_REF(note_use))))
	into += entry_line(68)
	into += list(global.op("key26", global.item(/obj/item/e2_bench_key26), global.then(PROC_REF(note_use))))
	into += entry_line(69)
	into += list(global.op("key27", global.item(/obj/item/e2_bench_key27), global.then(PROC_REF(note_use))))
	into += entry_line(70)
	into += list(global.op("key28", global.item(/obj/item/e2_bench_key28), global.then(PROC_REF(note_use))))
	into += entry_line(71)
	into += list(global.op("key29", global.item(/obj/item/e2_bench_key29), global.then(PROC_REF(note_use))))
	into += entry_line(72)
	into += list(global.op("key30", global.item(/obj/item/e2_bench_key30), global.then(PROC_REF(note_use))))

/// CAPABILITIES(/obj/e2_box) at code/tests/engine/e2_fixtures.dm:45
/obj/e2_box/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 45, /obj/e2_box)
	into += entry_line(46)
	into += list(global.op("open", global.hand(), global.toggles(nameof(opened)), global.logs(LOG_GAME)))
	into += entry_line(47)
	into += list(global.op("pry", global.tool(TOOL_CROWBAR), global.then(PROC_REF(note_pry))))
	into += entry_line(48)
	into += list(global.op("insert_key", global.item(/obj/item/e2_key), global.consumes(), global.then(PROC_REF(note_key))))
	into += entry_line(49)
	into += list(global.op("slide_in", global.item(/obj/item/e2_cloth), global.answers(INTENT_DROP_ONTO), global.then(PROC_REF(note_slide))))
	into += entry_line(50)
	into += list(global.op("peek", global.menu(), global.then(PROC_REF(note_peek))))
	into += entry_line(51)
	into += list(global.op("set_label", global.ui_act("set_label", global.arg("text", global.schema_text(8))), global.then(PROC_REF(apply_label))))
	into += entry_line(52)
	into += list(global.op("ping", global.topic("ping", global.arg("n", global.int(0, 9))), global.then(PROC_REF(note_ping))))
	into += entry_line(53)
	into += list(global.op("escape", global.inside(), global.priority(global.above("open")), global.then(PROC_REF(note_escape))))

/// CAPABILITIES(/obj/e2_lever) at code/tests/engine/e2_fixtures.dm:115
/obj/e2_lever/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 115, /obj/e2_lever)
	into += entry_line(116)
	into += list(global.op("pull_slow", global.hand(), global.wait(2 SECONDS), global.toggles(nameof(pulled)), global.logs(LOG_GAME)))

/// CAPABILITIES(/obj/e2_machine) at code/tests/engine/e2_fixtures.dm:100
/obj/e2_machine/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 100, /obj/e2_machine)
	into += entry_line(101)
	into += list(global.op("rename", global.ui_act("rename"), global.costs(RES_DARK_ENERGY, 5), global.asks(/datum/prompt/text, fields = list("question" = "What is it called?")), global.then(PROC_REF(apply_name)), global.logs(LOG_GAME)))

/// CAPABILITIES(/obj/e2_mixed) at code/tests/engine/e2_fixtures.dm:125
/obj/e2_mixed/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 125, /obj/e2_mixed)
	into += entry_line(126)
	into += list(global.op("wave", global.hand(), global.then(PROC_REF(note_wave))))

/// CAPABILITIES(/obj/e2_vault) at code/tests/engine/e2_fixtures.dm:92
/obj/e2_vault/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 92, /obj/e2_vault)
	into += entry_line(93)
	into += list(global.op("open", global.hand(), global.needs(global.req_is(nameof(locked), FALSE, because = MSG(e2/locked))), global.toggles(nameof(opened))))

/// CAPABILITIES(/obj/e3_apc) at code/tests/engine/e3_fixtures.dm:69
/obj/e3_apc/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 69, /obj/e3_apc)
	into += entry_line(70)
	into += list(global.ref_many(nameof(loads), /obj/e3_load))

/// CAPABILITIES(/obj/e3_load) at code/tests/engine/e3_fixtures.dm:78
/obj/e3_load/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 78, /obj/e3_load)
	into += entry_line(79)
	into += list(global.ref_one(nameof(apc), /obj/e3_apc))
	into += entry_line(80)
	into += list(global.contributes(STAT_E3_POWERED, PROC_REF(apc_channel), reads = list("apc.channel_on")))

/// CAPABILITIES(/obj/e3_machine) at code/tests/engine/e3_fixtures.dm:43
/obj/e3_machine/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 43, /obj/e3_machine)
	into += entry_line(44)
	into += list(global.contributes(STAT_E3_OPERABLE, global.cond_not(nameof(broken))))
	into += entry_line(45)
	into += list(global.contributes(STAT_E3_DRAW, 2))
	into += entry_line(46)
	into += list(global.when(nameof(e3_on), global.contributes(STAT_E3_DRAW, 10)))
	into += entry_line(47)
	into += list(global.contributes(STAT_E3_CAN_RUN, STAT_E3_OPERABLE))
	into += entry_line(48)
	into += list(global.immune_to(STATUS_E3_STUN, when = nameof(broken)))

/// CAPABILITIES(/obj/e3_machine/stoic) at code/tests/engine/e3_fixtures.dm:54
/obj/e3_machine/stoic/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 54, /obj/e3_machine/stoic)
	into += entry_line(55)
	into += list(global.immune_to(STATUS_E3_STUN))

/// CAPABILITIES(/obj/e3_wire) at code/tests/engine/e3_fixtures.dm:93
/obj/e3_wire/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 93, /obj/e3_wire)
	into += entry_line(94)
	into += list(global.ref_one(nameof(plugged), /obj/e3_machine))
	into += entry_line(95)
	into += list(global.when(nameof(live), global.contributes_to(nameof(plugged), STAT_E3_DRAW, 7)))

/// CAPABILITIES(/obj/e4_fixture/bed) at code/tests/engine/e4_fixtures.dm:101
/obj/e4_fixture/bed/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 101, /obj/e4_fixture/bed)
	into += entry_line(102)
	into += list(global.while_slotted("e4_bed", global.extend(/datum/act/e4_strike, global.adjusts("amount", by = 2)), on = ON_CONTENTS))

/// CAPABILITIES(/obj/e4_fixture/nester) at code/tests/engine/e4_fixtures.dm:75
/obj/e4_fixture/nester/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 75, /obj/e4_fixture/nester)
	into += entry_line(76)
	into += list(global.extend(/datum/act/e4_nest, global.instead(global.then(PROC_REF(again)))))

/// CAPABILITIES(/obj/e4_fixture/quiet) at code/tests/engine/e4_fixtures.dm:64
/obj/e4_fixture/quiet/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 64, /obj/e4_fixture/quiet)
	into += entry_line(65)
	into += list(global.on_notice(/datum/notice/e4_hushed, global.then(PROC_REF(heard))))

/// CAPABILITIES(/obj/e4_fixture/switch) at code/tests/engine/e4_fixtures.dm:132
/obj/e4_fixture/switch/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 132, /obj/e4_fixture/switch)
	into += entry_line(132)
	into += list(global.on_change(nameof(powered), ENTER, global.then(PROC_REF(power_on))))
	into += entry_line(132)
	into += list(global.on_change(nameof(powered), EXIT, global.then(PROC_REF(power_off))))
	into += entry_line(132)
	into += list(global.on_change(nameof(charge_level), ANY, global.then(PROC_REF(charge_level_changed))))
	into += entry_line(132)
	into += list(global.on_op("e4.toggle", global.then(PROC_REF(op_heard))))

/// CAPABILITIES(/obj/e4_fixture/target) at code/tests/engine/e4_fixtures.dm:34
/obj/e4_fixture/target/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 34, /obj/e4_fixture/target)
	into += entry_line(35)
	into += list(global.extend(/datum/act/e4_strike, global.adjusts("amount", scale = 0.5)))
	into += entry_line(36)
	into += list(global.extend(/datum/act/e4_strike, global.instead(global.when(nameof(shield)), global.then(PROC_REF(absorb)))))
	into += entry_line(37)
	into += list(global.on_notice(/datum/notice/e4_struck, global.then(PROC_REF(heard))))
	into += entry_line(38)
	into += list(global.on_notice(/datum/notice/e4_struck, global.then(PROC_REF(heard_when_replaced)), outcome = ACT_REPLACED))
	into += entry_line(39)
	into += list(global.on_notice(/datum/notice/e4_struck, global.then(PROC_REF(heard_whatever)), outcome = ACT_ANY))

/// CAPABILITIES(/obj/item/e2_cloth) at code/tests/engine/e2_fixtures.dm:28
/obj/item/e2_cloth/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 28, /obj/item/e2_cloth)
	into += entry_line(29)
	into += list(global.op("polish", global.in_hand(), global.then(PROC_REF(note_polish))))

/// CAPABILITIES(/obj/item/e4_fixture/amulet) at code/tests/engine/e4_fixtures.dm:95
/obj/item/e4_fixture/amulet/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 95, /obj/item/e4_fixture/amulet)
	into += entry_line(96)
	into += list(global.while_slotted("e4_slot", global.extend(/datum/act/e4_strike, global.adjusts("amount", by = 1)), on = ON_HOLDER))

/// CAPABILITIES(/obj/item/p1_telecube) at code/tests/engine/p1_fixtures.dm:89
/obj/item/p1_telecube/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/p1_fixtures.dm", 89, /obj/item/p1_telecube)
	into += entry_line(90)
	into += list(global.op("zap", global.hand(), global.cooldown(5 SECONDS), global.flash("p1"), global.says(MSG(p1/not_ready)), global.label("Zap")))
	into += entry_line(91)
	into += list(global.op("stash", global.item(/obj/item/e2_key), global.put_in("p1_slot"), global.menu()))

/// CAPABILITIES(/obj/p2_frame) at code/tests/engine/p2_fixtures.dm:91
/obj/p2_frame/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/p2_fixtures.dm", 91, /obj/p2_frame)
	into += entry_line(92)
	into += list(global.construction(global.start(STAGE_DOOR_FRAME), global.stage(STAGE_DOOR_WIRED, global.stack(/obj/item/stack/cable_coil, 5), undo = null), global.dismantle(global.tool(TOOL_CROWBAR), global.wait(0), global.becomes(/obj/item/p2_frame_item), global.ruined(TYPE_PROC_REF(/obj/p2_frame, frame_ruined), global.becomes(/obj/item/p2_scrap)))))

/// CAPABILITIES(/obj/p2_hit/both) at code/tests/engine/p2_fixtures.dm:66
/obj/p2_hit/both/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/p2_fixtures.dm", 66, /obj/p2_hit/both)
	into += entry_line(67)
	into += list(global.extend(/datum/act/hit/emp, global.adjusts("packet.amounts", scale = 0.5)))

/// CAPABILITIES(/obj/p2_hit/halver) at code/tests/engine/p2_fixtures.dm:35
/obj/p2_hit/halver/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/p2_fixtures.dm", 35, /obj/p2_hit/halver)
	into += entry_line(36)
	into += list(global.extend(/datum/act/hit, global.adjusts("packet.amounts", scale = 0.5)))
	into += entry_line(37)
	into += list(global.extend(/datum/act/hit/fire, global.needs(global.req(PROC_REF(never), because = MSG(p1/not_ready)))))

/// CAPABILITIES(/obj/p2_hit/listener) at code/tests/engine/p2_fixtures.dm:45
/obj/p2_hit/listener/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/p2_fixtures.dm", 45, /obj/p2_hit/listener)
	into += entry_line(46)
	into += list(global.on_notice(/datum/notice/hit/blob, global.then(PROC_REF(hear))))

/// CAPABILITIES(/obj/p2_hit/taker) at code/tests/engine/p2_fixtures.dm:26
/obj/p2_hit/taker/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/p2_fixtures.dm", 26, /obj/p2_hit/taker)
	into += entry_line(27)
	into += list(global.extend(/datum/act/hit/emp, global.instead(global.then(PROC_REF(take_over)))))

#endif
