// GENERATED by tools/analyze: `analyze gen declare`. Do not edit by hand; edit the declarations it reads.
// Written to code/engine/_generated/declare.dm; CI fails when this file is stale (`analyze gen --check`).

/// CAPABILITY_TYPE(construction_graph, CAP_CONSTRUCTION) at code/engine/declare/graph.dm:217
/datum/capability/construction
/proc/construction_graph(start, via)
	RETURN_TYPE(/datum/capability/construction)
	return cap_construct(CAP_CONSTRUCTION, /datum/capability/construction, list(start, via), "start, via")
/datum/capdef_decl/c_construction_graph/spec()
	return list(CAP_CONSTRUCTION, /datum/capability/construction, NONE, STACK, "construction_graph", "start, via")

/// CAPABILITY_TYPE(deployment_graph, CAP_DEPLOYMENT) at code/engine/declare/graph.dm:218
/datum/capability/construction/deployment
/proc/deployment_graph(start, via)
	RETURN_TYPE(/datum/capability/construction/deployment)
	return cap_construct(CAP_DEPLOYMENT, /datum/capability/construction/deployment, list(start, via), "start, via")
/datum/capdef_decl/c_deployment_graph/spec()
	return list(CAP_DEPLOYMENT, /datum/capability/construction/deployment, NONE, STACK, "deployment_graph", "start, via")

/datum/stage_def/door_frame/spec()
	return list(STAGE_DOOR_FRAME, "door", "frame")
/datum/stage_def/door_wired/spec()
	return list(STAGE_DOOR_WIRED, "door", "wired")
/datum/stage_def/door_boarded/spec()
	return list(STAGE_DOOR_BOARDED, "door", "boarded")
/datum/stage_def/door_finished/spec()
	return list(STAGE_DOOR_FINISHED, "door", "finished")
/datum/source_def/status/spec()
	return list(SRC_STATUS, "status")
/datum/source_def/vv/spec()
	return list(SRC_VV, "vv")
/datum/source_def/ai_control/spec()
	return list(SRC_AI_CONTROL, "ai_control")
/datum/source_def/held_item/spec()
	return list(SRC_HELD_ITEM, "held_item")
/datum/source_def/all/spec()
	return list(SRC_ALL, "all")

/// CAPABILITIES(/datum/pending_op) at code/engine/parts/run.dm:309
/datum/pending_op/declared_entries(list/into)
	..(into)
	into += entry_block("code/engine/parts/run.dm", 309, /datum/pending_op)
	into += entry_line(310)
	into += list(ref_one(nameof(holder), /datum, on_other_deleted = OTHER_DELETE_ME))
	into += entry_line(311)
	into += list(ref_one(nameof(target), /datum, on_other_deleted = OTHER_DELETE_ME))
	into += entry_line(312)
	into += list(ref_one(nameof(actor), /mob, on_other_deleted = OTHER_DELETE_ME))
	into += entry_line(313)
	into += list(ref_one(nameof(held), /obj/item, on_other_deleted = OTHER_DELETE_ME))

#if defined(UNIT_TESTS) || defined(SPACEMAN_DMM)

/// CAPABILITY_TYPE(e0_door, CAP_E0_DOOR) at code/tests/engine/fixtures.dm:119
/proc/e0_door()
	RETURN_TYPE(/datum/capability/e0_door)
	return cap_construct(CAP_E0_DOOR, /datum/capability/e0_door, list(), "")
/datum/capdef_decl/c_e0_door/spec()
	return list(CAP_E0_DOOR, /datum/capability/e0_door, NONE, STACK, "e0_door", "")

/// CAPABILITY_TYPE(e0_mirror_plating, CAP_E0_MIRROR) at code/tests/engine/fixtures.dm:34
/datum/e0_cap/mirror
	var/reflect_chance = 30
/proc/e0_mirror_plating(reflect_chance)
	RETURN_TYPE(/datum/e0_cap/mirror)
	return cap_construct(CAP_E0_MIRROR, /datum/e0_cap/mirror, list(reflect_chance), "reflect_chance")
/datum/capdef_decl/c_e0_mirror_plating/spec()
	return list(CAP_E0_MIRROR, /datum/e0_cap/mirror, NONE, BEST(reflect_chance), "e0_mirror_plating", "reflect_chance")

/// CAPABILITY_TYPE(e0_phase_shift, CAP_PHASE_SHIFT) at code/tests/engine/fixtures.dm:52
/proc/e0_phase_shift()
	RETURN_TYPE(/datum/e0_cap/phase_shift)
	return cap_construct(CAP_PHASE_SHIFT, /datum/e0_cap/phase_shift, list(), "")
/datum/capdef_decl/c_e0_phase_shift/spec()
	return list(CAP_PHASE_SHIFT, /datum/e0_cap/phase_shift, NONE, STACK, "e0_phase_shift", "")

/// CAPABILITY_TYPE(e0_phased, CAP_PHASED) at code/tests/engine/fixtures.dm:56
/datum/e0_cap/phased
	var/drain = 1
/proc/e0_phased(drain)
	RETURN_TYPE(/datum/e0_cap/phased)
	return cap_construct(CAP_PHASED, /datum/e0_cap/phased, list(drain), "drain")
/datum/capdef_decl/c_e0_phased/spec()
	return list(CAP_PHASED, /datum/e0_cap/phased, NONE, STACK, "e0_phased", "drain")

/// CAPABILITY_TYPE(e0_tk, CAP_E0_TK) at code/tests/engine/fixtures.dm:47
/proc/e0_tk()
	RETURN_TYPE(/datum/e0_cap/tk)
	return cap_construct(CAP_E0_TK, /datum/e0_cap/tk, list(), "")
/datum/capdef_decl/c_e0_tk/spec()
	return list(CAP_E0_TK, /datum/e0_cap/tk, NONE, STACK, "e0_tk", "")

/// CAPABILITY_TYPE(e1_beacon, CAP_E1_BEACON) at code/tests/engine/e1_fixtures.dm:49
/proc/e1_beacon()
	RETURN_TYPE(/datum/capability/e1_beacon)
	return cap_construct(CAP_E1_BEACON, /datum/capability/e1_beacon, list(), "")
/datum/capdef_decl/c_e1_beacon/spec()
	return list(CAP_E1_BEACON, /datum/capability/e1_beacon, NONE, STACK, "e1_beacon", "")

/// CAPABILITY_TYPE(e1_nested, CAP_E1_NESTED) at code/tests/engine/e1_fixtures.dm:44
/proc/e1_nested()
	RETURN_TYPE(/datum/capability/e1_nested)
	return cap_construct(CAP_E1_NESTED, /datum/capability/e1_nested, list(), "")
/datum/capdef_decl/c_e1_nested/spec()
	return list(CAP_E1_NESTED, /datum/capability/e1_nested, NONE, STACK, "e1_nested", "")

/// CAPABILITY_TYPE(e1_solo, CAP_E1_SOLO) at code/tests/engine/e1_fixtures.dm:22
/datum/capability/e1_solo
	var/note = "plain"
/proc/e1_solo(note)
	RETURN_TYPE(/datum/capability/e1_solo)
	return cap_construct(CAP_E1_SOLO, /datum/capability/e1_solo, list(note), "note")
/datum/capdef_decl/c_e1_solo/spec()
	return list(CAP_E1_SOLO, /datum/capability/e1_solo, NONE, STACK, "e1_solo", "note")

/// CAPABILITY_TYPE(e1_widget, CAP_E1_WIDGET) at code/tests/engine/e1_fixtures.dm:9
/datum/capability/e1_widget
	var/label = "main"
	var/power = 1
/proc/e1_widget(label, power)
	RETURN_TYPE(/datum/capability/e1_widget)
	return cap_construct(CAP_E1_WIDGET, /datum/capability/e1_widget, list(label, power), "label, power")
/datum/capdef_decl/c_e1_widget/spec()
	return list(CAP_E1_WIDGET, /datum/capability/e1_widget, "label", BEST(power), "e1_widget", "label, power")

/// cap_keys(CAP_E1_SOLO) at code/tests/engine/e1_fixtures.dm:41
/datum/cap_keys_decl/k_e1_solo/spec()
	return list(CAP_E1_SOLO, list(ARMED = null, LIT = null))
/// The state key ARMED of e1_solo, read on a holder (a granted capability with several selectors names the selector).
/proc/e1_solo_armed(datum/holder, selector)
	return cap_key_get(holder, E1_SOLO_ARMED, selector)
/// The state key LIT of e1_solo, read on a holder (a granted capability with several selectors names the selector).
/proc/e1_solo_lit(datum/holder, selector)
	return cap_key_get(holder, E1_SOLO_LIT, selector)

/// cap_keys(CAP_E0_DOOR) at code/tests/engine/fixtures.dm:120
/datum/cap_keys_decl/k_e0_door/spec()
	return list(CAP_E0_DOOR, list(OPEN = null))
/// The state key OPEN of e0_door, read on a holder (a granted capability with several selectors names the selector).
/proc/e0_door_open(datum/holder, selector)
	return cap_key_get(holder, E0_DOOR_OPEN, selector)

/// STATE_GRAPH(GRAPH_DOOR_ASSEMBLY) at code/tests/engine/e1_fixtures.dm:179
/datum/graph_decl/g_graph_door_assembly/spec()
	return list(GRAPH_DOOR_ASSEMBLY, start(STAGE_DOOR_FRAME), stage(STAGE_DOOR_WIRED, entry_of("part", "wire")), stage(STAGE_DOOR_BOARDED, entry_of("part", "board")), stage(STAGE_DOOR_FINISHED, entry_of("part", "screwdriver"), from = STAGE_DOOR_BOARDED), stage(STAGE_DOOR_FINISHED, entry_of("part", "kit"), from = STAGE_DOOR_WIRED, key = "kit", undo = list(entry_of("part", "crowbar"))), dismantle(entry_of("part", "welder")))

/// CAPABILITIES(/datum/e0_chain_node) at code/tests/engine/fixtures.dm:289
/datum/e0_chain_node/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 289, /datum/e0_chain_node)
	into += entry_line(289)
	into += list(on_notice(/datum/notice/e0_chain, then(PROC_REF(hear))))

/// CAPABILITIES(/datum/e0_species/shifter) at code/tests/engine/fixtures.dm:67
/datum/e0_species/shifter/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 67, /datum/e0_species/shifter)
	into += entry_line(67)
	into += list(e0_phase_shift())

/// CAPABILITIES(/datum/e1_species/alpha) at code/tests/engine/e1_fixtures.dm:61
/datum/e1_species/alpha/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 61, /datum/e1_species/alpha)
	into += entry_line(61)
	into += list(e1_widget("species", power = 5))
	into += entry_line(61)
	into += list(e1_beacon())

/// CAPABILITIES(/datum/e1_species/beta) at code/tests/engine/e1_fixtures.dm:66
/datum/e1_species/beta/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 66, /datum/e1_species/beta)
	into += entry_line(66)
	into += list(e1_solo())

/// CAPABILITIES(/datum/om_test_entity/e4_twin) at code/tests/engine/e4_fixtures.dm:151
/datum/om_test_entity/e4_twin/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 151, /datum/om_test_entity/e4_twin)
	into += entry_line(152)
	into += list(on_notice(/datum/notice/atom_bumped, then(PROC_REF(notice_heard))))

/// CAPABILITIES(/mob/living/simple_mob/e0_fixture) at code/tests/engine/fixtures.dm:87
/mob/living/simple_mob/e0_fixture/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 87, /mob/living/simple_mob/e0_fixture)
	into += entry_line(88)
	into += list(ref_one(nameof(species), /datum/e0_species))
	into += entry_line(89)
	into += list(rel_grants(nameof(species)))
	into += entry_line(90)
	into += list(hands())

/// CAPABILITIES(/obj/e0_fixture/door) at code/tests/engine/fixtures.dm:135
/obj/e0_fixture/door/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 135, /obj/e0_fixture/door)
	into += entry_line(136)
	into += list(e0_door())
	into += entry_line(137)
	into += list(when(E0_DOOR_OPEN, contributes(STAT_DENSITY, FALSE, priority = PRIORITY_FORCE)))

/// CAPABILITIES(/obj/e0_fixture/hopper) at code/tests/engine/fixtures.dm:191
/obj/e0_fixture/hopper/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 191, /obj/e0_fixture/hopper)
	into += entry_line(192)
	into += list(slot(SLOT_HOPPER, accepts = list(/obj/item/e0_fixture/sheets), capacity = E0_HOPPER_CAPACITY))
	into += entry_line(193)
	into += list(op("load", stack(/obj/item/e0_fixture/sheets, E0_SHEETS_PER_LOAD), wait(2 SECONDS), put_in(SLOT_HOPPER), says(MSG(fab/loaded)), logs(LOG_GAME)))

/// CAPABILITIES(/obj/e0_fixture/lamp) at code/tests/engine/fixtures.dm:259
/obj/e0_fixture/lamp/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 259, /obj/e0_fixture/lamp)
	into += entry_line(260)
	into += list(contributes(STAT_E0_LAMP_RANGE, PROC_REF(lit_range)))

/// CAPABILITIES(/obj/e0_fixture/library) at code/tests/engine/fixtures.dm:152
/obj/e0_fixture/library/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 152, /obj/e0_fixture/library)
	into += entry_line(153)
	into += list(op("select", ui_act(arg("id", int(1))), then(PROC_REF(select_row))))
	into += entry_line(154)
	into += list(op("print", ui_act(), needs(req_is(nameof(selected_id), because = MSG(library/nothing_selected))), confirms("Print the selected book?"), captures(nameof(selected_id)), then(PROC_REF(print_book)), logs(LOG_GAME)))

/// CAPABILITIES(/obj/e0_fixture/library/strict) at code/tests/engine/fixtures.dm:173
/obj/e0_fixture/library/strict/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 173, /obj/e0_fixture/library/strict)
	into += entry_line(174)
	into += list(extend("print", captures(nameof(selected_id), resume = CANCEL_IF_CHANGED)))

/// CAPABILITIES(/obj/e0_fixture/pump) at code/tests/engine/fixtures.dm:341
/obj/e0_fixture/pump/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/fixtures.dm", 341, /obj/e0_fixture/pump)
	into += entry_line(342)
	into += list(interface("E0Pump", title = "Gas Pump"))
	into += entry_line(343)
	into += list(ui_shape(target_pressure))
	into += entry_line(344)
	into += list(op("set_pressure", ui_act(arg("pressure", from = nameof(target_pressure))), then(PROC_REF(set_pressure))))

/// CAPABILITIES(/obj/e1_assembly) at code/tests/engine/e1_fixtures.dm:190
/obj/e1_assembly/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 190, /obj/e1_assembly)
	into += entry_line(190)
	into += list(construction(GRAPH_DOOR_ASSEMBLY))

/// CAPABILITIES(/obj/e1_assembly/finished) at code/tests/engine/e1_fixtures.dm:196
/obj/e1_assembly/finished/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 196, /obj/e1_assembly/finished)
	into += entry_line(196)
	into += list(configure(construction_graph(start = STAGE_DOOR_FINISHED, via = list(STAGE_DOOR_WIRED, STAGE_DOOR_BOARDED))))

/// CAPABILITIES(/obj/e1_fixture) at code/tests/engine/e1_fixtures.dm:93
/obj/e1_fixture/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 93, /obj/e1_fixture)
	into += entry_line(94)
	into += list(e1_solo())
	into += entry_line(95)
	into += list(e1_widget("a", power = 2))
	into += entry_line(96)
	into += list(ref_one(nameof(species), /datum/e1_species))
	into += entry_line(97)
	into += list(rel_grants(nameof(species)))
	into += entry_line(98)
	into += list(owns_one(nameof(gizmo), /obj/item/e1_part, starts = /obj/item/e1_part))
	into += entry_line(99)
	into += list(owns_many(nameof(gizmos), /obj/item/e1_part))
	into += entry_line(100)
	into += list(ref_many(nameof(watchers), /mob))
	into += entry_line(101)
	into += list(entry_link("/obj/e1_fixture::partner", "/obj/e1_fixture::partner"))
	into += entry_line(102)
	into += list(slot("e1_slot", accepts = list(/obj/item/e1_part), capacity = 1))
	into += entry_line(103)
	into += list(while_slotted("e1_slot", e1_beacon(), on = ON_HOLDER))
	into += entry_line(104)
	into += list(when(nameof(e1_armed), entry_of("contributes", "armed_glow", stat = STAT_LIGHT_RANGE, value = 4)))
	into += entry_line(105)
	into += list(entry_of("op", "toggle"))

/// CAPABILITIES(/obj/e1_fixture/changed) at code/tests/engine/e1_fixtures.dm:114
/obj/e1_fixture/changed/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 114, /obj/e1_fixture/changed)
	into += entry_line(115)
	into += list(extend("toggle", entry_of("part", "needs")))
	into += entry_line(116)
	into += list(configure(e1_widget("a", power = 9)))
	into += entry_line(117)
	into += list(without(CAP_E1_SOLO))

/// CAPABILITIES(/obj/e1_starts) at code/tests/engine/e1_fixtures.dm:143
/obj/e1_starts/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e1_fixtures.dm", 143, /obj/e1_starts)
	into += entry_line(144)
	into += list(owns_one(nameof(picked), /obj/item/e1_part, starts = pick_one(list(/obj/item/e1_part/tarnished = 1))))
	into += entry_line(145)
	into += list(owns_one(nameof(conditional), /obj/item/e1_part, starts = when(nameof(flag), /obj/item/e1_part/tarnished)))
	into += entry_line(146)
	into += list(owns_one(nameof(skipped), /obj/item/e1_part, starts = when(nameof(off_flag), /obj/item/e1_part/tarnished)))
	into += entry_line(147)
	into += list(owns_many(nameof(counted), /obj/item/e1_part, starts = list(/obj/item/e1_part = 2)))
	into += entry_line(148)
	into += list(owns_one(nameof(argy), /datum/e1_argy, starts = /datum/e1_argy, starts_args = list("hello")))
	into += entry_line(149)
	into += list(owns_one(nameof(computed), /obj/item/e1_part, starts = PROC_REF(make_computed)))

/// CAPABILITIES(/obj/e2_bench_stack) at code/tests/engine/e2_bench_fixtures.dm:41
/obj/e2_bench_stack/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_bench_fixtures.dm", 41, /obj/e2_bench_stack)
	into += entry_line(42)
	into += list(op("hand_use", hand(), then(PROC_REF(note_use))))
	into += entry_line(43)
	into += list(op("key1", item(/obj/item/e2_bench_key1), then(PROC_REF(note_use))))
	into += entry_line(44)
	into += list(op("key2", item(/obj/item/e2_bench_key2), then(PROC_REF(note_use))))
	into += entry_line(45)
	into += list(op("key3", item(/obj/item/e2_bench_key3), then(PROC_REF(note_use))))
	into += entry_line(46)
	into += list(op("key4", item(/obj/item/e2_bench_key4), then(PROC_REF(note_use))))
	into += entry_line(47)
	into += list(op("key5", item(/obj/item/e2_bench_key5), then(PROC_REF(note_use))))
	into += entry_line(48)
	into += list(op("key6", item(/obj/item/e2_bench_key6), then(PROC_REF(note_use))))
	into += entry_line(49)
	into += list(op("key7", item(/obj/item/e2_bench_key7), then(PROC_REF(note_use))))
	into += entry_line(50)
	into += list(op("key8", item(/obj/item/e2_bench_key8), then(PROC_REF(note_use))))
	into += entry_line(51)
	into += list(op("key9", item(/obj/item/e2_bench_key9), then(PROC_REF(note_use))))
	into += entry_line(52)
	into += list(op("key10", item(/obj/item/e2_bench_key10), then(PROC_REF(note_use))))
	into += entry_line(53)
	into += list(op("key11", item(/obj/item/e2_bench_key11), then(PROC_REF(note_use))))
	into += entry_line(54)
	into += list(op("key12", item(/obj/item/e2_bench_key12), then(PROC_REF(note_use))))
	into += entry_line(55)
	into += list(op("key13", item(/obj/item/e2_bench_key13), then(PROC_REF(note_use))))
	into += entry_line(56)
	into += list(op("key14", item(/obj/item/e2_bench_key14), then(PROC_REF(note_use))))
	into += entry_line(57)
	into += list(op("key15", item(/obj/item/e2_bench_key15), then(PROC_REF(note_use))))
	into += entry_line(58)
	into += list(op("key16", item(/obj/item/e2_bench_key16), then(PROC_REF(note_use))))
	into += entry_line(59)
	into += list(op("key17", item(/obj/item/e2_bench_key17), then(PROC_REF(note_use))))
	into += entry_line(60)
	into += list(op("key18", item(/obj/item/e2_bench_key18), then(PROC_REF(note_use))))
	into += entry_line(61)
	into += list(op("key19", item(/obj/item/e2_bench_key19), then(PROC_REF(note_use))))
	into += entry_line(62)
	into += list(op("key20", item(/obj/item/e2_bench_key20), then(PROC_REF(note_use))))
	into += entry_line(63)
	into += list(op("key21", item(/obj/item/e2_bench_key21), then(PROC_REF(note_use))))
	into += entry_line(64)
	into += list(op("key22", item(/obj/item/e2_bench_key22), then(PROC_REF(note_use))))
	into += entry_line(65)
	into += list(op("key23", item(/obj/item/e2_bench_key23), then(PROC_REF(note_use))))
	into += entry_line(66)
	into += list(op("key24", item(/obj/item/e2_bench_key24), then(PROC_REF(note_use))))
	into += entry_line(67)
	into += list(op("key25", item(/obj/item/e2_bench_key25), then(PROC_REF(note_use))))
	into += entry_line(68)
	into += list(op("key26", item(/obj/item/e2_bench_key26), then(PROC_REF(note_use))))
	into += entry_line(69)
	into += list(op("key27", item(/obj/item/e2_bench_key27), then(PROC_REF(note_use))))
	into += entry_line(70)
	into += list(op("key28", item(/obj/item/e2_bench_key28), then(PROC_REF(note_use))))
	into += entry_line(71)
	into += list(op("key29", item(/obj/item/e2_bench_key29), then(PROC_REF(note_use))))
	into += entry_line(72)
	into += list(op("key30", item(/obj/item/e2_bench_key30), then(PROC_REF(note_use))))

/// CAPABILITIES(/obj/e2_box) at code/tests/engine/e2_fixtures.dm:45
/obj/e2_box/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 45, /obj/e2_box)
	into += entry_line(46)
	into += list(op("open", hand(), toggles(nameof(opened)), logs(LOG_GAME)))
	into += entry_line(47)
	into += list(op("pry", tool(TOOL_CROWBAR), then(PROC_REF(note_pry))))
	into += entry_line(48)
	into += list(op("insert_key", item(/obj/item/e2_key), consumes(), then(PROC_REF(note_key))))
	into += entry_line(49)
	into += list(op("slide_in", item(/obj/item/e2_cloth), answers(INTENT_DROP_ONTO), then(PROC_REF(note_slide))))
	into += entry_line(50)
	into += list(op("peek", menu(), then(PROC_REF(note_peek))))
	into += entry_line(51)
	into += list(op("set_label", ui_act("set_label", arg("text", schema_text(8))), then(PROC_REF(apply_label))))
	into += entry_line(52)
	into += list(op("ping", topic("ping", arg("n", int(0, 9))), then(PROC_REF(note_ping))))
	into += entry_line(53)
	into += list(op("escape", inside(), priority(above("open")), then(PROC_REF(note_escape))))

/// CAPABILITIES(/obj/e2_lever) at code/tests/engine/e2_fixtures.dm:115
/obj/e2_lever/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 115, /obj/e2_lever)
	into += entry_line(116)
	into += list(op("pull_slow", hand(), wait(2 SECONDS), toggles(nameof(pulled)), logs(LOG_GAME)))

/// CAPABILITIES(/obj/e2_machine) at code/tests/engine/e2_fixtures.dm:100
/obj/e2_machine/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 100, /obj/e2_machine)
	into += entry_line(101)
	into += list(op("rename", ui_act("rename"), costs(RES_DARK_ENERGY, 5), asks(/datum/prompt/text, fields = list("question" = "What is it called?")), then(PROC_REF(apply_name)), logs(LOG_GAME)))

/// CAPABILITIES(/obj/e2_mixed) at code/tests/engine/e2_fixtures.dm:125
/obj/e2_mixed/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 125, /obj/e2_mixed)
	into += entry_line(126)
	into += list(op("wave", hand(), then(PROC_REF(note_wave))))

/// CAPABILITIES(/obj/e2_vault) at code/tests/engine/e2_fixtures.dm:92
/obj/e2_vault/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 92, /obj/e2_vault)
	into += entry_line(93)
	into += list(op("open", hand(), needs(req_is(nameof(locked), FALSE, because = MSG(e2/locked))), toggles(nameof(opened))))

/// CAPABILITIES(/obj/e3_apc) at code/tests/engine/e3_fixtures.dm:69
/obj/e3_apc/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 69, /obj/e3_apc)
	into += entry_line(70)
	into += list(ref_many(nameof(loads), /obj/e3_load))

/// CAPABILITIES(/obj/e3_load) at code/tests/engine/e3_fixtures.dm:78
/obj/e3_load/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 78, /obj/e3_load)
	into += entry_line(79)
	into += list(ref_one(nameof(apc), /obj/e3_apc))
	into += entry_line(80)
	into += list(contributes(STAT_E3_POWERED, PROC_REF(apc_channel), reads = list("apc.channel_on")))

/// CAPABILITIES(/obj/e3_machine) at code/tests/engine/e3_fixtures.dm:43
/obj/e3_machine/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 43, /obj/e3_machine)
	into += entry_line(44)
	into += list(contributes(STAT_E3_OPERABLE, cond_not(nameof(broken))))
	into += entry_line(45)
	into += list(contributes(STAT_E3_DRAW, 2))
	into += entry_line(46)
	into += list(when(nameof(e3_on), contributes(STAT_E3_DRAW, 10)))
	into += entry_line(47)
	into += list(contributes(STAT_E3_CAN_RUN, STAT_E3_OPERABLE))
	into += entry_line(48)
	into += list(immune_to(STATUS_E3_STUN, when = nameof(broken)))

/// CAPABILITIES(/obj/e3_machine/stoic) at code/tests/engine/e3_fixtures.dm:54
/obj/e3_machine/stoic/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 54, /obj/e3_machine/stoic)
	into += entry_line(55)
	into += list(immune_to(STATUS_E3_STUN))

/// CAPABILITIES(/obj/e3_wire) at code/tests/engine/e3_fixtures.dm:93
/obj/e3_wire/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e3_fixtures.dm", 93, /obj/e3_wire)
	into += entry_line(94)
	into += list(ref_one(nameof(plugged), /obj/e3_machine))
	into += entry_line(95)
	into += list(when(nameof(live), contributes_to(nameof(plugged), STAT_E3_DRAW, 7)))

/// CAPABILITIES(/obj/e4_fixture/bed) at code/tests/engine/e4_fixtures.dm:101
/obj/e4_fixture/bed/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 101, /obj/e4_fixture/bed)
	into += entry_line(102)
	into += list(while_slotted("e4_bed", extend(/datum/act/e4_strike, adjusts("amount", by = 2)), on = ON_CONTENTS))

/// CAPABILITIES(/obj/e4_fixture/nester) at code/tests/engine/e4_fixtures.dm:75
/obj/e4_fixture/nester/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 75, /obj/e4_fixture/nester)
	into += entry_line(76)
	into += list(extend(/datum/act/e4_nest, instead(then(PROC_REF(again)))))

/// CAPABILITIES(/obj/e4_fixture/quiet) at code/tests/engine/e4_fixtures.dm:64
/obj/e4_fixture/quiet/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 64, /obj/e4_fixture/quiet)
	into += entry_line(65)
	into += list(on_notice(/datum/notice/e4_hushed, then(PROC_REF(heard))))

/// CAPABILITIES(/obj/e4_fixture/switch) at code/tests/engine/e4_fixtures.dm:132
/obj/e4_fixture/switch/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 132, /obj/e4_fixture/switch)
	into += entry_line(132)
	into += list(on_change(nameof(powered), ENTER, then(PROC_REF(power_on))))
	into += entry_line(132)
	into += list(on_change(nameof(powered), EXIT, then(PROC_REF(power_off))))
	into += entry_line(132)
	into += list(on_change(nameof(charge_level), ANY, then(PROC_REF(charge_level_changed))))
	into += entry_line(132)
	into += list(on_op("e4.toggle", then(PROC_REF(op_heard))))

/// CAPABILITIES(/obj/e4_fixture/target) at code/tests/engine/e4_fixtures.dm:34
/obj/e4_fixture/target/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 34, /obj/e4_fixture/target)
	into += entry_line(35)
	into += list(extend(/datum/act/e4_strike, adjusts("amount", scale = 0.5)))
	into += entry_line(36)
	into += list(extend(/datum/act/e4_strike, instead(when(nameof(shield)), then(PROC_REF(absorb)))))
	into += entry_line(37)
	into += list(on_notice(/datum/notice/e4_struck, then(PROC_REF(heard))))
	into += entry_line(38)
	into += list(on_notice(/datum/notice/e4_struck, then(PROC_REF(heard_when_replaced)), outcome = ACT_REPLACED))
	into += entry_line(39)
	into += list(on_notice(/datum/notice/e4_struck, then(PROC_REF(heard_whatever)), outcome = ACT_ANY))

/// CAPABILITIES(/obj/item/e2_cloth) at code/tests/engine/e2_fixtures.dm:28
/obj/item/e2_cloth/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e2_fixtures.dm", 28, /obj/item/e2_cloth)
	into += entry_line(29)
	into += list(op("polish", in_hand(), then(PROC_REF(note_polish))))

/// CAPABILITIES(/obj/item/e4_fixture/amulet) at code/tests/engine/e4_fixtures.dm:95
/obj/item/e4_fixture/amulet/declared_entries(list/into)
	..(into)
	into += entry_block("code/tests/engine/e4_fixtures.dm", 95, /obj/item/e4_fixture/amulet)
	into += entry_line(96)
	into += list(while_slotted("e4_slot", extend(/datum/act/e4_strike, adjusts("amount", by = 1)), on = ON_HOLDER))

#endif
