// GENERATED by tools/analyze: `analyze gen declare_ids`. Do not edit by hand; edit the declarations it reads.
// Written to code/engine/_generated/ids.dm; CI fails when this file is stale (`analyze gen --check`).

/// Stat ids: STAT_<NAME> for each STAT(T, name, ...), from 100001. A status (units =) also has STATUS_<NAME> and STAT_<NAME>_IMMUNE.
#define STAT_ACTS_VIA 100001
#define STAT_CAN_ACT 100002
#define STAT_CAN_MOVE 100003
#define STAT_CLOCK_RATE 100004
#define STAT_CLOCK_RATE_BIO 100005
#define STAT_DENSITY 100006
#define STAT_INVISIBILITY 100007
#define STAT_LIGHTS_NIGHTSHIFT 100008
#define STAT_LIGHT_RANGE 100009
#define STAT_OPACITY 100010
#define STAT_OPERABLE 100011
#define STAT_POWER_DRAW 100012
#define STAT_SUSPENDED 100013

/// Capability ids: the CAP_X of each CAPABILITY_TYPE/DEF whose id no hand-written define gives, from 300.
#define CAP_E1_BEACON 300
#define CAP_E1_NESTED 301
#define CAP_E1_SOLO 302
#define CAP_E1_WIDGET 303

/// Source ids: SRC_<NAME> for each SOURCE_DEF(name).
#define SRC_AI_CONTROL 1
#define SRC_ALL 2
#define SRC_HELD_ITEM 3
#define SRC_STATUS 4
#define SRC_VV 5

/// Build stage ids: STAGE_<GROUP>_<NAME> for each STAGE_DEF(group, name).
#define STAGE_DOOR_BOARDED 1
#define STAGE_DOOR_FINISHED 2
#define STAGE_DOOR_FRAME 3
#define STAGE_DOOR_WIRED 4

/// State graph ids: the GRAPH_X of each STATE_GRAPH(GRAPH_X, ...).
#define GRAPH_DOOR_ASSEMBLY 1

/// Capability state ids: <CAPNAME>_<KEY> for each key of a cap_keys(CAP_X, KEY = ..., ...), bit 1 first.
#define E1_SOLO_ARMED CAPKEY_ID(CAP_E1_SOLO, 1)
#define E1_SOLO_LIT CAPKEY_ID(CAP_E1_SOLO, 2)
