// GENERATED by tools/analyze: `analyze gen reads`. Do not edit by hand; edit the declarations it reads.
// Written to code/engine/_generated/reads.dm; CI fails when this file is stale (`analyze gen --check`).

#define READ_ROOT_HOLDER 1
#define READ_ROOT_ACTOR 2
#define READ_ROOT_HELD 3
#define READ_ROOT_TARGET 4
#define READ_KIND_VAR 0
#define READ_KIND_ACCESSOR 1
#define READ_KIND_NATIVE 2
#define READ_KIND_SYSTEM 3

/// Every interned name a read uses (a var, a relation hop, an accessor key). Id = index in this list.
GLOBAL_LIST_INIT(generated_read_names, list(
	"night",
	"steady",
	"touched",
	"locked",
	"apc",
	"channel_on",
	"w_class",
	"coverlocked",
	"stat",
	"cell",
	"connected_ai",
	"lying",
	"aidisabled",
	"hacker",
	"loc"
))

/// The roots a read starts from (READ_ROOT_*): the holder, or a context hop. Id = index in this list.
GLOBAL_LIST_INIT(generated_read_roots, list(
	"holder",
	"actor",
	"held",
	"target",
	"system:e0_night"
))

/// "<type>::<proc>" = list(rank, list(root id, kind, name id, hop name ids...), ...). Never edited by hand.
GLOBAL_LIST_INIT(generated_reads_table, list(
	"/obj/e0_fixture/lamp::lit_range" = list(0,
		list(5, 3, 1)),
	"/obj/e0_fixture/p1_impure::reads_only" = list(0,
		list(1, 0, 2)),
	"/obj/e0_fixture/p1_impure::writes_in_condition" = list(0,
		list(1, 0, 3)),
	"/obj/e0_fixture/p1_impure::writes_in_requirement" = list(0,
		list(1, 0, 4)),
	"/obj/e3_load::apc_channel" = list(0,
		list(1, 0, 5),
		list(1, 0, 6, 5)),
	"/obj/machinery/power/apc::actor_works_locked" = list(0),
	"/obj/machinery/power/apc::cell_fits" = list(0,
		list(3, 0, 7)),
	"/obj/machinery/power/apc::cover_free" = list(0,
		list(1, 0, 8),
		list(1, 0, 9)),
	"/obj/machinery/power/apc::cover_replaceable" = list(0,
		list(1, 0, 10),
		list(1, 0, 9)),
	"/obj/machinery/power/apc::ui_usable" = list(0,
		list(2, 0, 11),
		list(2, 0, 12),
		list(2, 0, 9),
		list(1, 0, 13),
		list(1, 0, 14),
		list(1, 0, 15))
))
