// GENERATED by tools/analyze: `analyze gen stats`. Do not edit by hand; edit the declarations it reads.
// Written to code/engine/_generated/stats.dm; CI fails when this file is stale (`analyze gen --check`).

/// STAT(/area, lights_emergency_off, ANY) at code/contracts/ids/stats.dm:18
/area/proc/__stat_lights_emergency_off()
	return list("lights_emergency_off", "ANY", list(id = STAT_LIGHTS_EMERGENCY_OFF))
/datum/stat_decl/area/__lights_emergency_off/spec()
	return list(/area, /area/proc/__stat_lights_emergency_off)

/// STAT(/area, lights_nightshift, ANY) at code/contracts/ids/stats.dm:17
/area/proc/__stat_lights_nightshift()
	return list("lights_nightshift", "ANY", list(id = STAT_LIGHTS_NIGHTSHIFT))
/datum/stat_decl/area/__lights_nightshift/spec()
	return list(/area, /area/proc/__stat_lights_nightshift)

/// STAT(/atom, clock_rate, MIN) at code/contracts/ids/stats.dm:15
/atom/proc/__stat_clock_rate()
	return list("clock_rate", "MIN", list(id = STAT_CLOCK_RATE, base = 1))
/datum/stat_decl/atom/__clock_rate/spec()
	return list(/atom, /atom/proc/__stat_clock_rate)

/// STAT(/atom, density, TOP) at code/contracts/ids/stats.dm:10
/atom/proc/__stat_density()
	return list("density", "TOP", list(id = STAT_DENSITY))
/datum/stat_decl/atom/__density/spec()
	return list(/atom, /atom/proc/__stat_density)

/// STAT(/atom, invisibility, MAX) at code/contracts/ids/stats.dm:12
/atom/proc/__stat_invisibility()
	return list("invisibility", "MAX", list(id = STAT_INVISIBILITY))
/datum/stat_decl/atom/__invisibility/spec()
	return list(/atom, /atom/proc/__stat_invisibility)

/// STAT(/atom, light_range, MAX) at code/contracts/ids/stats.dm:13
/atom/proc/__stat_light_range()
	return list("light_range", "MAX", list(id = STAT_LIGHT_RANGE))
/datum/stat_decl/atom/__light_range/spec()
	return list(/atom, /atom/proc/__stat_light_range)

/// STAT(/atom, opacity, ANY) at code/contracts/ids/stats.dm:11
/atom/proc/__stat_opacity()
	return list("opacity", "ANY", list(id = STAT_OPACITY))
/datum/stat_decl/atom/__opacity/spec()
	return list(/atom, /atom/proc/__stat_opacity)

/// STAT(/atom/movable, suspended, ANY) at code/contracts/ids/stats.dm:14
/atom/movable/proc/__stat_suspended()
	return list("suspended", "ANY", list(id = STAT_SUSPENDED))
/datum/stat_decl/atom/movable/__suspended/spec()
	return list(/atom/movable, /atom/movable/proc/__stat_suspended)

/// STAT(/mob/living, acts_via, MASK_AND) at code/contracts/ids/stats.dm:9
/mob/living/var/acts_via = ORIGIN_ALL // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/mob/living/proc/__stat_acts_via()
	return list("acts_via", "MASK_AND", list(id = STAT_ACTS_VIA, base = ORIGIN_ALL))
/datum/stat_decl/mob/living/__acts_via/spec()
	return list(/mob/living, /mob/living/proc/__stat_acts_via)

/// STAT(/mob/living, can_act, ALL) at code/contracts/ids/stats.dm:7
/mob/living/var/can_act = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/mob/living/proc/__stat_can_act()
	return list("can_act", "ALL", list(id = STAT_CAN_ACT))
/datum/stat_decl/mob/living/__can_act/spec()
	return list(/mob/living, /mob/living/proc/__stat_can_act)

/// STAT(/mob/living, can_move, ALL) at code/contracts/ids/stats.dm:8
/mob/living/var/can_move = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/mob/living/proc/__stat_can_move()
	return list("can_move", "ALL", list(id = STAT_CAN_MOVE))
/datum/stat_decl/mob/living/__can_move/spec()
	return list(/mob/living, /mob/living/proc/__stat_can_move)

/// STAT(/mob/living, clock_rate_bio, MIN) at code/contracts/ids/stats.dm:16
/mob/living/var/clock_rate_bio = 1 // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/mob/living/proc/__stat_clock_rate_bio()
	return list("clock_rate_bio", "MIN", list(id = STAT_CLOCK_RATE_BIO, base = 1))
/datum/stat_decl/mob/living/__clock_rate_bio/spec()
	return list(/mob/living, /mob/living/proc/__stat_clock_rate_bio)

/// STAT(/obj/item/gps, operable, ALL) at code/game/objects/items/devices/gps.dm:88
/obj/item/gps/proc/__stat_operable()
	return list("operable", "ALL", list(id = STAT_OPERABLE))
/datum/stat_decl/obj/item/gps/__operable/spec()
	return list(/obj/item/gps, /obj/item/gps/proc/__stat_operable)

/// STAT(/obj/machinery, operable, ALL) at code/contracts/ids/stats.dm:5
/obj/machinery/proc/__stat_operable()
	return list("operable", "ALL", list(id = STAT_OPERABLE))
/datum/stat_decl/obj/machinery/__operable/spec()
	return list(/obj/machinery, /obj/machinery/proc/__stat_operable)

/// STAT(/obj/machinery, power_draw, SUM) at code/contracts/ids/stats.dm:6
/obj/machinery/proc/__stat_power_draw()
	return list("power_draw", "SUM", list(id = STAT_POWER_DRAW))
/datum/stat_decl/obj/machinery/__power_draw/spec()
	return list(/obj/machinery, /obj/machinery/proc/__stat_power_draw)

/// STAT(/obj/machinery/alarm, aidisabled, ANY) at code/game/machinery/air_alarm.dm:128
/obj/machinery/alarm/var/aidisabled = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/alarm/proc/__stat_aidisabled()
	return list("aidisabled", "ANY", list(id = STAT_AIDISABLED))
/datum/stat_decl/obj/machinery/alarm/__aidisabled/spec()
	return list(/obj/machinery/alarm, /obj/machinery/alarm/proc/__stat_aidisabled)

/// STAT(/obj/machinery/alarm, shorted, ANY) at code/game/machinery/air_alarm.dm:130
/obj/machinery/alarm/var/shorted = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/alarm/proc/__stat_shorted()
	return list("shorted", "ANY", list(id = STAT_SHORTED))
/datum/stat_decl/obj/machinery/alarm/__shorted/spec()
	return list(/obj/machinery/alarm, /obj/machinery/alarm/proc/__stat_shorted)

/// STAT(/obj/machinery/autolathe, disabled, ANY) at code/game/machinery/autolathe.dm:43
/obj/machinery/autolathe/var/disabled = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/autolathe/proc/__stat_disabled()
	return list("disabled", "ANY", list(id = STAT_DISABLED))
/datum/stat_decl/obj/machinery/autolathe/__disabled/spec()
	return list(/obj/machinery/autolathe, /obj/machinery/autolathe/proc/__stat_disabled)

/// STAT(/obj/machinery/autolathe, hacked, ANY) at code/game/machinery/autolathe.dm:41
/obj/machinery/autolathe/var/hacked = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/autolathe/proc/__stat_hacked()
	return list("hacked", "ANY", list(id = STAT_HACKED))
/datum/stat_decl/obj/machinery/autolathe/__hacked/spec()
	return list(/obj/machinery/autolathe, /obj/machinery/autolathe/proc/__stat_hacked)

/// STAT(/obj/machinery/autolathe, shocked, ANY) at code/game/machinery/autolathe.dm:45
/obj/machinery/autolathe/var/shocked = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/autolathe/proc/__stat_shocked()
	return list("shocked", "ANY", list(id = STAT_SHOCKED))
/datum/stat_decl/obj/machinery/autolathe/__shocked/spec()
	return list(/obj/machinery/autolathe, /obj/machinery/autolathe/proc/__stat_shocked)

/// STAT(/obj/machinery/door/airlock, aiControlDisabled, ANY) at code/game/machinery/doors/airlock.dm:430
/obj/machinery/door/airlock/var/aiControlDisabled = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/door/airlock/proc/__stat_aiControlDisabled()
	return list("aiControlDisabled", "ANY", list(id = STAT_AICONTROLDISABLED))
/datum/stat_decl/obj/machinery/door/airlock/__aiControlDisabled/spec()
	return list(/obj/machinery/door/airlock, /obj/machinery/door/airlock/proc/__stat_aiControlDisabled)

/// STAT(/obj/machinery/door/airlock, aiDisabledIdScanner, ANY) at code/game/machinery/doors/airlock.dm:432
/obj/machinery/door/airlock/var/aiDisabledIdScanner = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/door/airlock/proc/__stat_aiDisabledIdScanner()
	return list("aiDisabledIdScanner", "ANY", list(id = STAT_AIDISABLEDIDSCANNER))
/datum/stat_decl/obj/machinery/door/airlock/__aiDisabledIdScanner/spec()
	return list(/obj/machinery/door/airlock, /obj/machinery/door/airlock/proc/__stat_aiDisabledIdScanner)

/// STAT(/obj/machinery/door/airlock, safe, ALL) at code/game/machinery/doors/airlock.dm:434
/obj/machinery/door/airlock/var/safe = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/door/airlock/proc/__stat_safe()
	return list("safe", "ALL", list(id = STAT_SAFE))
/datum/stat_decl/obj/machinery/door/airlock/__safe/spec()
	return list(/obj/machinery/door/airlock, /obj/machinery/door/airlock/proc/__stat_safe)

/// STAT(/obj/machinery/light, area_emergency_off, ANY) at code/modules/power/lighting.dm:30
/obj/machinery/light/var/area_emergency_off = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/light/proc/__stat_area_emergency_off()
	return list("area_emergency_off", "ANY", list(id = STAT_AREA_EMERGENCY_OFF))
/datum/stat_decl/obj/machinery/light/__area_emergency_off/spec()
	return list(/obj/machinery/light, /obj/machinery/light/proc/__stat_area_emergency_off)

/// STAT(/obj/machinery/light, nightshift_enabled, ANY) at code/modules/power/lighting.dm:29
/obj/machinery/light/var/nightshift_enabled = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/light/proc/__stat_nightshift_enabled()
	return list("nightshift_enabled", "ANY", list(id = STAT_NIGHTSHIFT_ENABLED))
/datum/stat_decl/obj/machinery/light/__nightshift_enabled/spec()
	return list(/obj/machinery/light, /obj/machinery/light/proc/__stat_nightshift_enabled)

/// STAT(/obj/machinery/power/apc, aidisabled, ANY) at code/modules/power/apc.dm:135
/obj/machinery/power/apc/var/aidisabled = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/power/apc/proc/__stat_aidisabled()
	return list("aidisabled", "ANY", list(id = STAT_AIDISABLED))
/datum/stat_decl/obj/machinery/power/apc/__aidisabled/spec()
	return list(/obj/machinery/power/apc, /obj/machinery/power/apc/proc/__stat_aidisabled)

/// STAT(/obj/machinery/power/apc, shorted, ANY) at code/modules/power/apc.dm:133
/obj/machinery/power/apc/var/shorted = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/power/apc/proc/__stat_shorted()
	return list("shorted", "ANY", list(id = STAT_SHORTED))
/datum/stat_decl/obj/machinery/power/apc/__shorted/spec()
	return list(/obj/machinery/power/apc, /obj/machinery/power/apc/proc/__stat_shorted)

/// STAT(/obj/machinery/power/apc, supplying, ALL) at code/modules/power/apc.dm:131
/obj/machinery/power/apc/var/supplying = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/power/apc/proc/__stat_supplying()
	return list("supplying", "ALL", list(id = STAT_SUPPLYING))
/datum/stat_decl/obj/machinery/power/apc/__supplying/spec()
	return list(/obj/machinery/power/apc, /obj/machinery/power/apc/proc/__stat_supplying)

/// STAT(/obj/machinery/power/shield_generator, ai_control_disabled, ANY) at code/modules/shieldgen/shield_generator.dm:46
/obj/machinery/power/shield_generator/var/ai_control_disabled = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/power/shield_generator/proc/__stat_ai_control_disabled()
	return list("ai_control_disabled", "ANY", list(id = STAT_AI_CONTROL_DISABLED))
/datum/stat_decl/obj/machinery/power/shield_generator/__ai_control_disabled/spec()
	return list(/obj/machinery/power/shield_generator, /obj/machinery/power/shield_generator/proc/__stat_ai_control_disabled)

/// STAT(/obj/machinery/power/shield_generator, input_cut, ANY) at code/modules/shieldgen/shield_generator.dm:44
/obj/machinery/power/shield_generator/var/input_cut = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/power/shield_generator/proc/__stat_input_cut()
	return list("input_cut", "ANY", list(id = STAT_INPUT_CUT))
/datum/stat_decl/obj/machinery/power/shield_generator/__input_cut/spec()
	return list(/obj/machinery/power/shield_generator, /obj/machinery/power/shield_generator/proc/__stat_input_cut)

/// STAT(/obj/machinery/rnd, disabled, ANY) at code/modules/research/tg/rdmachines.dm:101
/obj/machinery/rnd/var/disabled = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/rnd/proc/__stat_disabled()
	return list("disabled", "ANY", list(id = STAT_DISABLED))
/datum/stat_decl/obj/machinery/rnd/__disabled/spec()
	return list(/obj/machinery/rnd, /obj/machinery/rnd/proc/__stat_disabled)

/// STAT(/obj/machinery/rnd, hacked, ANY) at code/modules/research/tg/rdmachines.dm:99
/obj/machinery/rnd/var/hacked = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/rnd/proc/__stat_hacked()
	return list("hacked", "ANY", list(id = STAT_HACKED))
/datum/stat_decl/obj/machinery/rnd/__hacked/spec()
	return list(/obj/machinery/rnd, /obj/machinery/rnd/proc/__stat_hacked)

/// STAT(/obj/machinery/smartfridge, scan_id, TOP) at code/modules/food/kitchen/smartfridge/smartfridge.dm:36
/obj/machinery/smartfridge/var/scan_id = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/smartfridge/proc/__stat_scan_id()
	return list("scan_id", "TOP", list(id = STAT_SCAN_ID, base = TRUE))
/datum/stat_decl/obj/machinery/smartfridge/__scan_id/spec()
	return list(/obj/machinery/smartfridge, /obj/machinery/smartfridge/proc/__stat_scan_id)

/// STAT(/obj/machinery/smartfridge, shoot_inventory, ANY) at code/modules/food/kitchen/smartfridge/smartfridge.dm:34
/obj/machinery/smartfridge/var/shoot_inventory = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/smartfridge/proc/__stat_shoot_inventory()
	return list("shoot_inventory", "ANY", list(id = STAT_SHOOT_INVENTORY))
/datum/stat_decl/obj/machinery/smartfridge/__shoot_inventory/spec()
	return list(/obj/machinery/smartfridge, /obj/machinery/smartfridge/proc/__stat_shoot_inventory)

/// STAT(/obj/machinery/suit_cycler, safeties, ALL) at code/game/machinery/suit_storage/suit_cycler.dm:331
/obj/machinery/suit_cycler/var/safeties = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/suit_cycler/proc/__stat_safeties()
	return list("safeties", "ALL", list(id = STAT_SAFETIES))
/datum/stat_decl/obj/machinery/suit_cycler/__safeties/spec()
	return list(/obj/machinery/suit_cycler, /obj/machinery/suit_cycler/proc/__stat_safeties)

/// STAT(/obj/machinery/vending, scan_id, TOP) at code/modules/economy/vending.dm:114
/obj/machinery/vending/var/scan_id = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/vending/proc/__stat_scan_id()
	return list("scan_id", "TOP", list(id = STAT_SCAN_ID, base = TRUE))
/datum/stat_decl/obj/machinery/vending/__scan_id/spec()
	return list(/obj/machinery/vending, /obj/machinery/vending/proc/__stat_scan_id)

/// STAT(/obj/machinery/vending, shoot_inventory, ANY) at code/modules/economy/vending.dm:116
/obj/machinery/vending/var/shoot_inventory = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/machinery/vending/proc/__stat_shoot_inventory()
	return list("shoot_inventory", "ANY", list(id = STAT_SHOOT_INVENTORY))
/datum/stat_decl/obj/machinery/vending/__shoot_inventory/spec()
	return list(/obj/machinery/vending, /obj/machinery/vending/proc/__stat_shoot_inventory)

/// STAT(/obj/vehicle, operable, ALL) at code/modules/vehicles/vehicle.dm:51
/obj/vehicle/proc/__stat_operable()
	return list("operable", "ALL", list(id = STAT_OPERABLE))
/datum/stat_decl/obj/vehicle/__operable/spec()
	return list(/obj/vehicle, /obj/vehicle/proc/__stat_operable)

#if defined(UNIT_TESTS) || defined(SPACEMAN_DMM)

/// STAT(/obj/e0_fixture/lamp, e0_lamp_range, MAX) at code/tests/engine/fixtures.dm:288
/obj/e0_fixture/lamp/var/e0_lamp_range = null // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e0_fixture/lamp/proc/__stat_e0_lamp_range()
	return list("e0_lamp_range", "MAX", list(id = STAT_E0_LAMP_RANGE))
/datum/stat_decl/obj/e0_fixture/lamp/__e0_lamp_range/spec()
	return list(/obj/e0_fixture/lamp, /obj/e0_fixture/lamp/proc/__stat_e0_lamp_range)

/// STAT(/obj/e3_load, e3_powered, ALL) at code/tests/engine/e3_fixtures.dm:76
/obj/e3_load/var/e3_powered = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_load/proc/__stat_e3_powered()
	return list("e3_powered", "ALL", list(id = STAT_E3_POWERED))
/datum/stat_decl/obj/e3_load/__e3_powered/spec()
	return list(/obj/e3_load, /obj/e3_load/proc/__stat_e3_powered)

/// STAT(/obj/e3_machine, e3_can_run, ALL) at code/tests/engine/e3_fixtures.dm:37
/obj/e3_machine/var/e3_can_run = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_machine/proc/__stat_e3_can_run()
	return list("e3_can_run", "ALL", list(id = STAT_E3_CAN_RUN))
/datum/stat_decl/obj/e3_machine/__e3_can_run/spec()
	return list(/obj/e3_machine, /obj/e3_machine/proc/__stat_e3_can_run)

/// STAT(/obj/e3_machine, e3_draw, SUM) at code/tests/engine/e3_fixtures.dm:36
/obj/e3_machine/var/e3_draw = 0 // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_machine/proc/__stat_e3_draw()
	return list("e3_draw", "SUM", list(id = STAT_E3_DRAW))
/datum/stat_decl/obj/e3_machine/__e3_draw/spec()
	return list(/obj/e3_machine, /obj/e3_machine/proc/__stat_e3_draw)

/// STAT(/obj/e3_machine, e3_operable, ALL) at code/tests/engine/e3_fixtures.dm:35
/obj/e3_machine/var/e3_operable = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_machine/proc/__stat_e3_operable()
	return list("e3_operable", "ALL", list(id = STAT_E3_OPERABLE))
/datum/stat_decl/obj/e3_machine/__e3_operable/spec()
	return list(/obj/e3_machine, /obj/e3_machine/proc/__stat_e3_operable)

/// STAT(/obj/e3_machine, e3_stun, MAX) at code/tests/engine/e3_fixtures.dm:38
/obj/e3_machine/var/e3_stun = 0 // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_machine/proc/__stat_e3_stun()
	return list("e3_stun", "MAX", list(id = STAT_E3_STUN, base = 0, units = LIFE_CYCLE, reapply = REAPPLY_MAX))
/datum/stat_decl/obj/e3_machine/__e3_stun/spec()
	return list(/obj/e3_machine, /obj/e3_machine/proc/__stat_e3_stun)

/// STAT(/obj/e3_rules, e3_all, ALL) at code/tests/engine/e3_fixtures.dm:12
/obj/e3_rules/var/e3_all = TRUE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_all()
	return list("e3_all", "ALL", list(id = STAT_E3_ALL))
/datum/stat_decl/obj/e3_rules/__e3_all/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_all)

/// STAT(/obj/e3_rules, e3_any, ANY) at code/tests/engine/e3_fixtures.dm:13
/obj/e3_rules/var/e3_any = FALSE // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_any()
	return list("e3_any", "ANY", list(id = STAT_E3_ANY))
/datum/stat_decl/obj/e3_rules/__e3_any/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_any)

/// STAT(/obj/e3_rules, e3_formula, FORMULA) at code/tests/engine/e3_fixtures.dm:22
/obj/e3_rules/var/e3_formula = null // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_formula()
	return list("e3_formula", "FORMULA", list(id = STAT_E3_FORMULA, formula = PROC_REF(compute_formula), reads = list("e3_seed", "e3_sum")))
/datum/stat_decl/obj/e3_rules/__e3_formula/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_formula)

/// STAT(/obj/e3_rules, e3_mask_and, MASK_AND) at code/tests/engine/e3_fixtures.dm:20
/obj/e3_rules/var/e3_mask_and = 15 // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_mask_and()
	return list("e3_mask_and", "MASK_AND", list(id = STAT_E3_MASK_AND, base = 15))
/datum/stat_decl/obj/e3_rules/__e3_mask_and/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_mask_and)

/// STAT(/obj/e3_rules, e3_mask_or, MASK_OR) at code/tests/engine/e3_fixtures.dm:21
/obj/e3_rules/var/e3_mask_or = 0 // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_mask_or()
	return list("e3_mask_or", "MASK_OR", list(id = STAT_E3_MASK_OR))
/datum/stat_decl/obj/e3_rules/__e3_mask_or/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_mask_or)

/// STAT(/obj/e3_rules, e3_max, MAX) at code/tests/engine/e3_fixtures.dm:16
/obj/e3_rules/var/e3_max = null // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_max()
	return list("e3_max", "MAX", list(id = STAT_E3_MAX))
/datum/stat_decl/obj/e3_rules/__e3_max/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_max)

/// STAT(/obj/e3_rules, e3_min, MIN) at code/tests/engine/e3_fixtures.dm:17
/obj/e3_rules/var/e3_min = null // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_min()
	return list("e3_min", "MIN", list(id = STAT_E3_MIN))
/datum/stat_decl/obj/e3_rules/__e3_min/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_min)

/// STAT(/obj/e3_rules, e3_product, PRODUCT) at code/tests/engine/e3_fixtures.dm:15
/obj/e3_rules/var/e3_product = 1 // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_product()
	return list("e3_product", "PRODUCT", list(id = STAT_E3_PRODUCT))
/datum/stat_decl/obj/e3_rules/__e3_product/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_product)

/// STAT(/obj/e3_rules, e3_set, SET) at code/tests/engine/e3_fixtures.dm:19
/obj/e3_rules/var/e3_set = null // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_set()
	return list("e3_set", "SET", list(id = STAT_E3_SET))
/datum/stat_decl/obj/e3_rules/__e3_set/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_set)

/// STAT(/obj/e3_rules, e3_sum, SUM) at code/tests/engine/e3_fixtures.dm:14
/obj/e3_rules/var/e3_sum = 0 // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_sum()
	return list("e3_sum", "SUM", list(id = STAT_E3_SUM))
/datum/stat_decl/obj/e3_rules/__e3_sum/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_sum)

/// STAT(/obj/e3_rules, e3_top, TOP) at code/tests/engine/e3_fixtures.dm:18
/obj/e3_rules/var/e3_top = null // ALLOW(base_vars): a stat's var is its settled value (STAT, code/engine/stats)
/obj/e3_rules/proc/__stat_e3_top()
	return list("e3_top", "TOP", list(id = STAT_E3_TOP))
/datum/stat_decl/obj/e3_rules/__e3_top/spec()
	return list(/obj/e3_rules, /obj/e3_rules/proc/__stat_e3_top)

#endif
