// Generated by tools/object_model/ui_bindings.py. Do not edit.

/datum/object_model/ui/schema_fixture
	interface = "ObjectModelSchemaFixture"
	data_schema = list("description" = list("type" = "text", "optional" = TRUE), "value" = list("type" = "number"))
	actions = list("set" = list("value" = list("type" = "number", "min" = 0, "max" = 10)))
