"""Generate compact, named DM stat APIs from stat_definitions.json.

Usage: python tools/object_model/stat_definitions.py [--check]
"""

import argparse
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "tools/object_model/stat_definitions.json"
OUTPUT = ROOT / "code/datums/object_model/generated_stats.dm"
NAME = re.compile(r"^[a-z][a-z0-9_]*$")
RULES = {
    "add": "OM_STAT_ADD",
    "multiply": "OM_STAT_MULTIPLY",
    "max": "OM_STAT_MAX",
    "min": "OM_STAT_MIN",
    "flags": "OM_STAT_FLAGS",
}


def number(value):
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not math.isfinite(value):
        raise ValueError(f"expected finite number, got {value!r}")
    return json.dumps(value)


def validate(doc):
    if doc.get("version") != 1 or not isinstance(doc.get("domains"), list):
        raise ValueError("expected version 1 and domains array")
    domains = set()
    for domain in doc["domains"]:
        name = domain.get("name")
        if not isinstance(name, str) or not NAME.fullmatch(name) or name in domains:
            raise ValueError(f"invalid or duplicate domain {name!r}")
        domains.add(name)
        if not isinstance(domain.get("change_mask"), int) or domain["change_mask"] <= 0:
            raise ValueError(f"{name}: change_mask must be a positive integer")
        stats = domain.get("stats")
        if not isinstance(stats, list) or not stats:
            raise ValueError(f"{name}: expected nonempty stats array")
        names = set()
        for stat in stats:
            sname = stat.get("name")
            if not isinstance(sname, str) or not NAME.fullmatch(sname) or sname in names:
                raise ValueError(f"{name}: invalid or duplicate stat {sname!r}")
            names.add(sname)
            rule = stat.get("rule")
            if rule not in RULES:
                raise ValueError(f"{name}.{sname}: unsupported rule {rule!r}")
            baseline, low, high = (stat.get(k) for k in ("baseline", "min", "max"))
            for value in (baseline, low, high):
                number(value)
            if not low <= baseline <= high:
                raise ValueError(f"{name}.{sname}: baseline outside bounds")
            if rule == "flags" and any(not isinstance(v, int) or v < 0 for v in (baseline, low, high)):
                raise ValueError(f"{name}.{sname}: flags require nonnegative integer bounds")


def generate(doc):
    validate(doc)
    out = ["// Generated by tools/object_model/stat_definitions.py. Do not edit.", ""]
    for domain in doc["domains"]:
        dname = domain["name"]
        upper = dname.upper()
        stats = domain["stats"]
        block = f"/datum/object_model/stat_block/{dname}"
        draft = f"/datum/object_model/stat_draft/{dname}"
        for index, stat in enumerate(stats, 1):
            out.append(f"#define OM_{upper}_{stat['name'].upper()} {index}")
        out.append(f"#define OM_{upper}_COUNT {len(stats)}")
        out.extend(["", block, f"\tchange_mask = {domain['change_mask']}", "", f"{block}/definitions()", "\tvar/static/list/defs = list("])
        for index, stat in enumerate(stats):
            values = ", ".join((number(stat["baseline"]), RULES[stat["rule"]], number(stat["min"]), number(stat["max"])))
            comma = "," if index < len(stats) - 1 else ""
            out.append(f"\t\tlist({values}){comma}")
        out.extend(["\t)", "\treturn defs", ""])
        out.extend([f"{draft}/New()", f"\t. = ..({block}, OM_{upper}_COUNT)", ""])
        for stat in stats:
            sname = stat["name"]
            sid = f"OM_{upper}_{sname.upper()}"
            out.extend([f"{block}/proc/get_{sname}()", f"\treturn get_stat({sid})", "", f"{block}/proc/set_base_{sname}(value)", f"\treturn set_base_stat({sid}, value)", ""])
            method = {"add": "add", "multiply": "multiply", "max": "at_least", "min": "at_most", "flags": "grant"}[stat["rule"]]
            out.extend([f"{draft}/proc/{method}_{sname}(value)", f"\tcontribute({sid}, value, {RULES[stat['rule']]})", ""])
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate(json.loads(SOURCE.read_text(encoding="utf-8")))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"stale generated file: {OUTPUT}")
    else:
        OUTPUT.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
