"""Generate object-model UI contracts for DM and TGUI from one JSON schema.

Usage: python tools/object_model/ui_bindings.py [--check]
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHEMA = ROOT / "tools/object_model/ui_schemas.json"
DM = ROOT / "code/datums/object_model/generated_ui_schema.dm"
TS = ROOT / "tgui/packages/tgui/interfaces/ObjectModel/generatedSchemas.ts"
LEAVES = {"number": "number", "text": "string", "boolean": "boolean"}


def quoted(value):
    return json.dumps(value, ensure_ascii=False)


def dm_value(value):
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    return quoted(value)


def dm_leaf(spec):
    fields = [f'"type" = {quoted(spec["type"])}']
    for key in ("min", "max", "values"):
        if key in spec:
            value = spec[key]
            if key == "values":
                value = "list(" + ", ".join(dm_value(item) for item in value) + ")"
            else:
                value = dm_value(value)
            fields.append(f'"{key}" = {value}')
    return "list(" + ", ".join(fields) + ")"


def ts_leaf(spec):
    values = spec.get("values")
    if values:
        return " | ".join(quoted(value) for value in values)
    return LEAVES[spec["type"]]


def validate(document):
    if document.get("version") != 1 or not isinstance(document.get("interfaces"), list):
        raise ValueError("expected version 1 and interfaces array")
    seen = set()
    paths = set()
    for interface in document["interfaces"]:
        name, path = interface["name"], interface["dm_type"]
        if not name.isidentifier() or name in seen:
            raise ValueError(f"invalid or duplicate interface name: {name}")
        if not path.startswith("/datum/object_model/ui/") or path in paths:
            raise ValueError(f"invalid or duplicate DM UI type: {path}")
        seen.add(name)
        paths.add(path)
        for group in ("data", "actions"):
            if not isinstance(interface.get(group), dict):
                raise ValueError(f"{name}.{group} must be an object")
        if "can" in interface["data"] or "revision" in interface["data"]:
            raise ValueError(f"{name}: can and revision are reserved data fields")
        for action, params in interface["actions"].items():
            if not action.isidentifier() or not isinstance(params, dict) or "revision" in params:
                raise ValueError(f"{name}.{action}: invalid action parameters")
        for field, spec in list(interface["data"].items()) + [
            (f"{action}.{param}", spec)
            for action, params in interface["actions"].items()
            for param, spec in params.items()
        ]:
            if not all(part.isidentifier() for part in field.split(".")) or not isinstance(spec, dict) or spec.get("type") not in LEAVES:
                raise ValueError(f"{name}.{field}: invalid leaf")
            if spec.get("optional") not in (None, True, False):
                raise ValueError(f"{name}.{field}: optional must be boolean")
            if "min" in spec and "max" in spec and spec["min"] > spec["max"]:
                raise ValueError(f"{name}.{field}: min exceeds max")
            if "values" in spec and (not isinstance(spec["values"], list) or not spec["values"]):
                raise ValueError(f"{name}.{field}: values must be nonempty")
            if "values" in spec and any(
                (type(value) is not int and type(value) is not float) if spec["type"] == "number"
                else type(value) is not (str if spec["type"] == "text" else bool)
                for value in spec["values"]
            ):
                raise ValueError(f"{name}.{field}: values have the wrong type")
            if spec["type"] != "number" and "min" in spec:
                raise ValueError(f"{name}.{field}: min requires number")
            if spec["type"] == "boolean" and "max" in spec:
                raise ValueError(f"{name}.{field}: max is not valid for boolean")


def generate(document):
    validate(document)
    dm = ["// Generated by tools/object_model/ui_bindings.py. Do not edit.", ""]
    ts = ["// Generated by tools/object_model/ui_bindings.py. Do not edit.",
          "// Data includes the common revision and action availability fields.", ""]
    for interface in sorted(document["interfaces"], key=lambda item: item["name"]):
        name, path = interface["name"], interface["dm_type"]
        dm.append(path)
        dm.append(f'\tinterface = {quoted(name)}')
        for group, var in (("data", "data_schema"), ("actions", "actions")):
            entries = []
            for key, value in sorted(interface[group].items()):
                if group == "actions":
                    params = ", ".join(f'{quoted(k)} = {dm_leaf(v)}' for k, v in sorted(value.items()))
                    expr = f"list({params})"
                else:
                    expr = dm_leaf(value)
                    if value.get("optional"):
                        expr = expr[:-1] + ', "optional" = TRUE)'
                entries.append(f'{quoted(key)} = {expr}')
            dm.append(f'\t{var} = list({", ".join(entries)})')
        dm.append("")
        ts.append(f"export interface {name}Data {{")
        ts.append("  revision: number;")
        ts.append(f"  can: Partial<Record<keyof {name}Actions, string | null>>;")
        for field, spec in sorted(interface["data"].items()):
            ts.append(f'  {field}{"?" if spec.get("optional") else ""}: {ts_leaf(spec)};')
        ts.append("}")
        ts.append(f"export interface {name}Actions {{")
        for action, params in sorted(interface["actions"].items()):
            props = "; ".join(f'{k}{"?" if v.get("optional") else ""}: {ts_leaf(v)}' for k, v in sorted(params.items()))
            ts.append(f'  {action}: {{ {props} }};')
        ts.append("}")
        ts.append("")
    ts.append("export interface ObjectModelUiContracts {")
    for interface in sorted(document["interfaces"], key=lambda item: item["name"]):
        name = interface["name"]
        ts.append(f'  {name}: {{')
        ts.append(f'    data: {name}Data;')
        ts.append(f'    actions: {name}Actions;')
        ts.append('  };')
    ts.append("}")
    ts.append("")
    ts.append("export type ObjectModelAction<K extends keyof ObjectModelUiContracts> = <")
    ts.append("  A extends keyof ObjectModelUiContracts[K]['actions'],")
    ts.append(">(")
    ts.append("  action: A,")
    ts.append("  params: ObjectModelUiContracts[K]['actions'][A] & { revision: number },")
    ts.append(") => void;")
    return "\n".join(dm), "\n".join(ts) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate(json.loads(SCHEMA.read_text(encoding="utf-8")))
    stale = []
    for path, content in zip((DM, TS), expected):
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Stale object-model UI bindings: " + ", ".join(stale))


if __name__ == "__main__":
    main()
