// Declared fields (doc/rewrite/object_model_core.md §5.1).
//
// A var that a stage, behaviour or watch reads to decide whether it has work is a declared
// field. It is declared once, with its default and the channel its change raises:
//
//	OM_FIELD(/obj/machinery/portable_atmospherics/powered/pump, on, FALSE, CHANGE_MACHINE_SETTINGS)
//
// which declares the var, generates the typed setter E.set_on(value) (raises the channel, only
// when the value changed) and registers the field (a /datum/om/field_def subtype). Every write
// goes through the setter, or om_set(E, "on", TRUE) where the name is data. A stage names what it
// reads (`reads = list("on")`) and the registry ORs the read fields' channels into its wake_on at
// boot, so the two can't drift; wake_on keeps only the channels that aren't field reads. The boot
// check fails on a read of an undeclared field, and tools/ci/field_write_lint.py (api_lints.py
// `field_write`) bans every other write, in any proc of any type, unit tests included.

/// One declared field, generated by OM_FIELD(): /datum/om/field_def<declaring type>/<name>.
/datum/om/field_def
	/// The declaring type.
	var/of
	/// The var name.
	var/field
	/// The channel its setter raises.
	var/channel = 0
	/// OM_DERIVE_FIELD(): computed by the proc named `field`; no var, no setter.
	var/derived = FALSE
	/// OM_DERIVE_FIELD(): its inputs, field names and raw channels (its channel is their union).
	var/list/inputs

/datum/om/registry
	/// type path -> field name -> channel (every field_def whose `of` is an ancestor, merged).
	var/list/fields_by_type = list() // ALLOW(instance_list): d: registry singleton, filled per entity type on first use
	/// Every /datum/om/field_def type (read with initial(); never instantiated).
	var/list/field_defs

/// Declared fields of `path` (and its ancestors): field name -> channel.
/datum/om/registry/proc/fields_of(path)
	RETURN_TYPE(/list)
	var/list/F = fields_by_type[path]
	if(F)
		return F
	if(!field_defs)
		field_defs = list()
		for(var/def_path in subtypesof(/datum/om/field_def))
			var/datum/om/field_def/D = def_path
			if(initial(D.field))
				field_defs += def_path
	F = om_field_table(path)
	fields_by_type[path] = F
	return F

/// The union of the channels of the declared fields `reads` of type `path` (undeclared names add
/// nothing; check_field_reads() reports them).
/datum/om/registry/proc/field_reads_mask(path, list/reads)
	. = 0
	if(!path || !length(reads))
		return
	var/list/F = fields_of(path)
	for(var/name in reads)
		. |= F[name]

/// Boot check: every field a stage (or behaviour) `reads` is declared, and its channel wakes it
/// (build_stages()/build_behaviours() derive that; this catches a later override).
/// Returns the problems (also recorded as registry errors).
/datum/om/registry/proc/check_field_reads()
	. = list()
	for(var/path in stage_by_type)
		var/datum/om/stage/T = stage_by_type[path]
		if(!length(T.reads))
			continue
		var/mask = T.wake_mask || T.wake_on
		var/list/F = fields_of(T.of)
		for(var/name in T.reads)
			var/channel = F[name]
			if(!channel)
				. += "[T.type] reads [name], which [T.of] does not declare as a field"
			else if(!(mask & channel))
				. += "[T.type] reads [name] (channel [channel]) but its wake_on [mask] does not cover it"
	for(var/datum/om/behaviour/B as anything in behaviours)
		if(!length(B.reads))
			continue
		if(!B.reads_of)
			. += "[B.type] reads fields but names no reads_of type"
			continue
		var/list/F = fields_of(B.reads_of)
		for(var/name in B.reads)
			var/channel = F[name]
			if(!channel)
				. += "[B.type] reads [name], which [B.reads_of] does not declare as a field"
			else if(!(B.wake_on & channel))
				. += "[B.type] reads [name] (channel [channel]) but its wake_on [B.wake_on] does not cover it"
	for(var/problem in .)
		error(problem)

/// The channel declared for `E`'s field `name`, or 0.
/proc/om_field_channel(datum/E, name)
	var/list/F = om_registry().fields_of(E.type)
	return F[name] || 0

/// The one write path for a declared field: sets `E.name` to `value` and raises the field's
/// declared channel. Nothing is raised when the value is unchanged. Returns TRUE on a change.
/proc/om_set(datum/E, name, value)
	if(!(name in E.vars))
		CRASH("om_set: [E.type].[name] is not a writable field (derived fields have no var)")
	if(E.vars[name] == value)
		return FALSE
	var/channel = om_field_channel(E, name)
	if(!channel)
		CRASH("om_set: [E.type].[name] is not a declared field")
	E.vars[name] = value
	om_changed(E, channel)
	return TRUE

/// Raises the declared channel of `E`'s field `name` after an in-place change the setter can't
/// see (a list or datum field edited in place). Setters call it for you.
/proc/om_field_changed(datum/E, name)
	var/channel = om_field_channel(E, name)
	if(!channel)
		CRASH("om_field_changed: [E.type].[name] is not a declared field")
	om_changed(E, channel)

/// OM_FLAG_FIELD_BITS() helper: the union of the channels of the `changed` bits in `table`
/// ("[bit]" = channel); a changed bit with no row adds `fallback`.
/proc/om_flag_channels(list/table, changed, fallback)
	. = 0
	var/bit = 1
	while(changed && bit <= 0x800000)
		if(changed & bit)
			changed &= ~bit
			var/channel = table["[bit]"]
			. |= channel ? channel : fallback
		bit <<= 1

/// Declared fields of `path` (and its ancestors), field name -> channel, with derived fields
/// resolved to the union of their inputs' channels. Usable before the registry exists (the
/// declared-periodic service build reads it); the registry caches it per type in fields_of().
/proc/om_field_table(path)
	RETURN_TYPE(/list)
	var/static/list/plain_defs
	var/static/list/derived_defs
	if(!plain_defs)
		plain_defs = list()
		derived_defs = list()
		for(var/def_path in subtypesof(/datum/om/field_def))
			var/datum/om/field_def/D = def_path
			if(!initial(D.field))
				continue
			if(initial(D.derived))
				derived_defs += new def_path // inputs is a list: read from an instance
			else
				plain_defs += def_path
	var/list/F = list()
	for(var/datum/om/field_def/D as anything in plain_defs)
		if(ispath(path, initial(D.of)))
			F[initial(D.field)] |= initial(D.channel)
	var/list/mine = list()
	for(var/datum/om/field_def/D as anything in derived_defs)
		if(ispath(path, D.of))
			mine += D
	// Derived fields may read other derived fields: resolve until nothing changes.
	for(var/pass in 1 to max(1, length(mine)))
		var/changed = FALSE
		for(var/datum/om/field_def/D as anything in mine)
			var/channel = F[D.field]
			for(var/input in D.inputs)
				channel |= isnum(input) ? input : F[input]
			if(channel != F[D.field])
				F[D.field] = channel
				changed = TRUE
		if(!changed)
			break
	return F

/// Boot check: every derived field's inputs are declared fields of its type (or raw channels).
/proc/om_check_derived_inputs()
	. = list()
	for(var/def_path in subtypesof(/datum/om/field_def))
		var/datum/om/field_def/proto = def_path
		if(!initial(proto.field) || !initial(proto.derived))
			continue
		var/datum/om/field_def/D = new def_path
		var/list/F = om_field_table(D.of)
		if(!length(D.inputs))
			. += "OM_DERIVE_FIELD([D.of], [D.field]) declares no inputs"
		for(var/input in D.inputs)
			if(!isnum(input) && !F[input])
				. += "OM_DERIVE_FIELD([D.of], [D.field]) reads [input], which [D.of] does not declare as a field"
		qdel(D)
