// Generated by tools/object_model/ui_bindings.py. Do not edit.
// Data includes the common revision and action availability fields.

export interface ObjectModelSchemaFixtureData {
  revision: number;
  can: Partial<Record<keyof ObjectModelSchemaFixtureActions, string | null>>;
  description?: string;
  value: number;
}
export interface ObjectModelSchemaFixtureActions {
  set: { value: number };
}

export interface ObjectModelUiContracts {
  ObjectModelSchemaFixture: {
    data: ObjectModelSchemaFixtureData;
    actions: ObjectModelSchemaFixtureActions;
  };
}

export type ObjectModelAction<K extends keyof ObjectModelUiContracts> = <
  A extends keyof ObjectModelUiContracts[K]['actions'],
>(
  action: A,
  params: ObjectModelUiContracts[K]['actions'][A] & { revision: number },
) => void;
