// Sound and effect sets (doc/rewrite/systems.md section 16).
// A sound set is a named group of files with a default volume, vary, extrarange and falloff.
// play_sfx() picks a file and calls the playsound() core; get_sfx() resolves a set id to a file.
// Ids are defined in code/__defines/sfx.dm. One row per set, below.

/datum/sound_set
	var/id
	var/list/files
	var/volume = 50
	var/vary = FALSE
	var/extrarange = 0
	var/falloff = null

/datum/sound_set/New(id, list/files, volume = 50, vary = FALSE, extrarange = 0, falloff = null)
	src.id = id
	src.files = files
	src.volume = volume
	src.vary = vary
	src.extrarange = extrarange
	src.falloff = falloff

/// The id -> /datum/sound_set table. Built once, on first use.
/proc/sound_set(id)
	var/static/list/table
	if(!table)
		table = build_sound_sets()
	return table[id]

/// Resolves a sound set id to one of its files; anything else (a file, a /sound) passes through.
/proc/get_sfx(soundin)
	if(istext(soundin))
		var/datum/sound_set/set_row = sound_set(soundin)
		if(set_row)
			return pick(set_row.files)
	return soundin

/**
 * Plays a sound set at source. volume_mult scales the set volume; volume overrides it outright.
 * vary / extrarange / falloff default to the set's values when left null.
 * The remaining arguments pass straight to playsound().
 */
/proc/play_sfx(atom/source, id, volume_mult = 1, volume = null, vary = null, extrarange = null, falloff = null, is_global = FALSE, frequency = null, channel = 0, pressure_affected = TRUE, ignore_walls = TRUE, preference = null, volume_channel = null)
	var/datum/sound_set/set_row = sound_set(id)
	if(!set_row)
		CRASH("play_sfx: unknown sound set '[id]'")
	playsound(source, pick(set_row.files), isnull(volume) ? set_row.volume * volume_mult : volume, \
		isnull(vary) ? set_row.vary : vary, isnull(extrarange) ? set_row.extrarange : extrarange, \
		isnull(falloff) ? set_row.falloff : falloff, is_global, frequency, channel, pressure_affected, \
		ignore_walls, preference, volume_channel)

/proc/build_sound_sets()
	. = list()
	SOUND_SET(SFX_SHATTER, list('sound/effects/Glassbr1.ogg', 'sound/effects/Glassbr2.ogg', 'sound/effects/Glassbr3.ogg'), 70, TRUE)
	SOUND_SET(SFX_EXPLOSION, list('sound/effects/Explosion1.ogg', 'sound/effects/Explosion2.ogg', 'sound/effects/Explosion3.ogg', 'sound/effects/Explosion4.ogg', 'sound/effects/Explosion5.ogg', 'sound/effects/Explosion6.ogg'), 75, TRUE)
	SOUND_SET(SFX_SPARKS, list('sound/effects/sparks1.ogg', 'sound/effects/sparks2.ogg', 'sound/effects/sparks3.ogg', 'sound/effects/sparks5.ogg', 'sound/effects/sparks6.ogg', 'sound/effects/sparks7.ogg'), 50, TRUE)
	SOUND_SET(SFX_RUSTLE, list('sound/effects/rustle1.ogg', 'sound/effects/rustle2.ogg', 'sound/effects/rustle3.ogg', 'sound/effects/rustle4.ogg', 'sound/effects/rustle5.ogg'), 25, TRUE, -5, null)
	SOUND_SET(SFX_PUNCH, list('sound/weapons/punch1.ogg', 'sound/weapons/punch2.ogg', 'sound/weapons/punch3.ogg', 'sound/weapons/punch4.ogg'), 50, TRUE)
	SOUND_SET(SFX_CLOWNSTEP, list('sound/effects/clownstep1.ogg', 'sound/effects/clownstep2.ogg'), 50, FALSE)
	SOUND_SET(SFX_SWING_HIT, list('sound/weapons/genhit1.ogg', 'sound/weapons/genhit2.ogg', 'sound/weapons/genhit3.ogg'), 25, TRUE, -1, null)
	SOUND_SET(SFX_HISS, list('sound/voice/hiss1.ogg', 'sound/voice/hiss2.ogg', 'sound/voice/hiss3.ogg', 'sound/voice/hiss4.ogg'), 50, FALSE)
	SOUND_SET(SFX_PAGETURN, list('sound/effects/pageturn1.ogg', 'sound/effects/pageturn2.ogg', 'sound/effects/pageturn3.ogg'), 50, TRUE)
	SOUND_SET(SFX_FRACTURE, list('sound/effects/bonebreak1.ogg', 'sound/effects/bonebreak2.ogg', 'sound/effects/bonebreak3.ogg', 'sound/effects/bonebreak4.ogg'), 90, TRUE, -2, null)
	SOUND_SET(SFX_CANOPEN, list('sound/effects/can_open1.ogg', 'sound/effects/can_open2.ogg', 'sound/effects/can_open3.ogg', 'sound/effects/can_open4.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHSTEP, list('sound/mecha/mechstep1.ogg', 'sound/mecha/mechstep2.ogg'), 50, FALSE)
	SOUND_SET(SFX_THUNDER, list('sound/effects/thunder/thunder1.ogg', 'sound/effects/thunder/thunder2.ogg', 'sound/effects/thunder/thunder3.ogg', 'sound/effects/thunder/thunder4.ogg', 'sound/effects/thunder/thunder5.ogg', 'sound/effects/thunder/thunder6.ogg', 'sound/effects/thunder/thunder7.ogg', 'sound/effects/thunder/thunder8.ogg', 'sound/effects/thunder/thunder9.ogg', 'sound/effects/thunder/thunder10.ogg'), 50, FALSE)
	SOUND_SET(SFX_KEYBOARD, list('sound/effects/keyboard/keyboard1.ogg', 'sound/effects/keyboard/keyboard2.ogg', 'sound/effects/keyboard/keyboard3.ogg', 'sound/effects/keyboard/keyboard4.ogg'), 40, FALSE)
	SOUND_SET(SFX_BUTTON, list('sound/machines/button1.ogg', 'sound/machines/button2.ogg', 'sound/machines/button3.ogg', 'sound/machines/button4.ogg'), 10, FALSE)
	SOUND_SET(SFX_SWITCH, list('sound/machines/switch1.ogg', 'sound/machines/switch2.ogg', 'sound/machines/switch3.ogg', 'sound/machines/switch4.ogg'), 50, FALSE)
	SOUND_SET(SFX_CASING_SOUND, list('sound/weapons/casingfall1.ogg', 'sound/weapons/casingfall2.ogg', 'sound/weapons/casingfall3.ogg'), 50, TRUE)
	SOUND_SET(SFX_PICKAXE, list('sound/weapons/mine/pickaxe1.ogg', 'sound/weapons/mine/pickaxe2.ogg', 'sound/weapons/mine/pickaxe3.ogg', 'sound/weapons/mine/pickaxe4.ogg'), 50, FALSE)
	SOUND_SET(SFX_RICOCHET, list('sound/weapons/effects/ric1.ogg', 'sound/weapons/effects/ric2.ogg', 'sound/weapons/effects/ric3.ogg', 'sound/weapons/effects/ric4.ogg', 'sound/weapons/effects/ric5.ogg'), 50, FALSE)
	SOUND_SET(SFX_BULLET_MISS, list('sound/weapons/bulletflyby.ogg', 'sound/weapons/bulletflyby2.ogg', 'sound/weapons/bulletflyby3.ogg'), 75, TRUE)
	SOUND_SET(SFX_HUNGER_SOUNDS, list('sound/vore/growl1.ogg', 'sound/vore/growl2.ogg', 'sound/vore/growl3.ogg', 'sound/vore/growl4.ogg', 'sound/vore/growl5.ogg'), 50, FALSE)
	SOUND_SET(SFX_CLASSIC_DIGESTION_SOUNDS, list('sound/vore/digest1.ogg', 'sound/vore/digest2.ogg', 'sound/vore/digest3.ogg', 'sound/vore/digest4.ogg', 'sound/vore/digest5.ogg', 'sound/vore/digest6.ogg', 'sound/vore/digest7.ogg', 'sound/vore/digest8.ogg', 'sound/vore/digest9.ogg', 'sound/vore/digest10.ogg', 'sound/vore/digest11.ogg', 'sound/vore/digest12.ogg'), 50, FALSE)
	SOUND_SET(SFX_CLASSIC_DEATH_SOUNDS, list('sound/vore/death1.ogg', 'sound/vore/death2.ogg', 'sound/vore/death3.ogg', 'sound/vore/death4.ogg', 'sound/vore/death5.ogg', 'sound/vore/death6.ogg', 'sound/vore/death7.ogg', 'sound/vore/death8.ogg', 'sound/vore/death9.ogg', 'sound/vore/death10.ogg'), 50, FALSE)
	SOUND_SET(SFX_CLASSIC_STRUGGLE_SOUNDS, list('sound/vore/squish1.ogg', 'sound/vore/squish2.ogg', 'sound/vore/squish3.ogg', 'sound/vore/squish4.ogg'), 50, FALSE)
	SOUND_SET(SFX_FANCY_PREY_STRUGGLE, list('sound/vore/sunesound/prey/struggle_01.ogg', 'sound/vore/sunesound/prey/struggle_02.ogg', 'sound/vore/sunesound/prey/struggle_03.ogg', 'sound/vore/sunesound/prey/struggle_04.ogg', 'sound/vore/sunesound/prey/struggle_05.ogg'), 50, FALSE)
	SOUND_SET(SFX_FANCY_DIGEST_PRED, list('sound/vore/sunesound/pred/digest_01.ogg', 'sound/vore/sunesound/pred/digest_02.ogg', 'sound/vore/sunesound/pred/digest_03.ogg', 'sound/vore/sunesound/pred/digest_04.ogg', 'sound/vore/sunesound/pred/digest_05.ogg', 'sound/vore/sunesound/pred/digest_06.ogg', 'sound/vore/sunesound/pred/digest_07.ogg', 'sound/vore/sunesound/pred/digest_08.ogg', 'sound/vore/sunesound/pred/digest_09.ogg', 'sound/vore/sunesound/pred/digest_10.ogg', 'sound/vore/sunesound/pred/digest_11.ogg', 'sound/vore/sunesound/pred/digest_12.ogg', 'sound/vore/sunesound/pred/digest_13.ogg', 'sound/vore/sunesound/pred/digest_14.ogg', 'sound/vore/sunesound/pred/digest_15.ogg', 'sound/vore/sunesound/pred/digest_16.ogg', 'sound/vore/sunesound/pred/digest_17.ogg', 'sound/vore/sunesound/pred/digest_18.ogg'), 50, FALSE)
	SOUND_SET(SFX_FANCY_DEATH_PRED, list('sound/vore/sunesound/pred/death_01.ogg', 'sound/vore/sunesound/pred/death_02.ogg', 'sound/vore/sunesound/pred/death_03.ogg', 'sound/vore/sunesound/pred/death_04.ogg', 'sound/vore/sunesound/pred/death_05.ogg', 'sound/vore/sunesound/pred/death_06.ogg', 'sound/vore/sunesound/pred/death_07.ogg', 'sound/vore/sunesound/pred/death_08.ogg', 'sound/vore/sunesound/pred/death_09.ogg', 'sound/vore/sunesound/pred/death_10.ogg'), 50, FALSE)
	SOUND_SET(SFX_FANCY_DIGEST_PREY, list('sound/vore/sunesound/prey/digest_01.ogg', 'sound/vore/sunesound/prey/digest_02.ogg', 'sound/vore/sunesound/prey/digest_03.ogg', 'sound/vore/sunesound/prey/digest_04.ogg', 'sound/vore/sunesound/prey/digest_05.ogg', 'sound/vore/sunesound/prey/digest_06.ogg', 'sound/vore/sunesound/prey/digest_07.ogg', 'sound/vore/sunesound/prey/digest_08.ogg', 'sound/vore/sunesound/prey/digest_09.ogg', 'sound/vore/sunesound/prey/digest_10.ogg', 'sound/vore/sunesound/prey/digest_11.ogg', 'sound/vore/sunesound/prey/digest_12.ogg', 'sound/vore/sunesound/prey/digest_13.ogg', 'sound/vore/sunesound/prey/digest_14.ogg', 'sound/vore/sunesound/prey/digest_15.ogg', 'sound/vore/sunesound/prey/digest_16.ogg', 'sound/vore/sunesound/prey/digest_17.ogg', 'sound/vore/sunesound/prey/digest_18.ogg'), 50, FALSE)
	SOUND_SET(SFX_FANCY_DEATH_PREY, list('sound/vore/sunesound/prey/death_01.ogg', 'sound/vore/sunesound/prey/death_02.ogg', 'sound/vore/sunesound/prey/death_03.ogg', 'sound/vore/sunesound/prey/death_04.ogg', 'sound/vore/sunesound/prey/death_05.ogg', 'sound/vore/sunesound/prey/death_06.ogg', 'sound/vore/sunesound/prey/death_07.ogg', 'sound/vore/sunesound/prey/death_08.ogg', 'sound/vore/sunesound/prey/death_09.ogg', 'sound/vore/sunesound/prey/death_10.ogg'), 50, FALSE)
	SOUND_SET(SFX_BELCHES, list('sound/vore/belches/belch1.ogg', 'sound/vore/belches/belch2.ogg', 'sound/vore/belches/belch3.ogg', 'sound/vore/belches/belch4.ogg', 'sound/vore/belches/belch5.ogg', 'sound/vore/belches/belch6.ogg', 'sound/vore/belches/belch7.ogg', 'sound/vore/belches/belch8.ogg', 'sound/vore/belches/belch9.ogg', 'sound/vore/belches/belch10.ogg', 'sound/vore/belches/belch11.ogg', 'sound/vore/belches/belch12.ogg', 'sound/vore/belches/belch13.ogg', 'sound/vore/belches/belch14.ogg', 'sound/vore/belches/belch15.ogg'), 50, FALSE)
	SOUND_SET(SFX_TERMINAL_TYPE, list('sound/machines/terminal_button01.ogg', 'sound/machines/terminal_button02.ogg', 'sound/machines/terminal_button03.ogg', 'sound/machines/terminal_button04.ogg', 'sound/machines/terminal_button05.ogg', 'sound/machines/terminal_button06.ogg', 'sound/machines/terminal_button07.ogg', 'sound/machines/terminal_button08.ogg'), 50, TRUE)
	SOUND_SET(SFX_SMCALM, list('sound/machines/sm/accent/normal/1.ogg', 'sound/machines/sm/accent/normal/2.ogg', 'sound/machines/sm/accent/normal/3.ogg', 'sound/machines/sm/accent/normal/4.ogg', 'sound/machines/sm/accent/normal/5.ogg', 'sound/machines/sm/accent/normal/6.ogg', 'sound/machines/sm/accent/normal/7.ogg', 'sound/machines/sm/accent/normal/8.ogg', 'sound/machines/sm/accent/normal/9.ogg', 'sound/machines/sm/accent/normal/10.ogg', 'sound/machines/sm/accent/normal/11.ogg', 'sound/machines/sm/accent/normal/12.ogg', 'sound/machines/sm/accent/normal/13.ogg', 'sound/machines/sm/accent/normal/14.ogg', 'sound/machines/sm/accent/normal/15.ogg', 'sound/machines/sm/accent/normal/16.ogg', 'sound/machines/sm/accent/normal/17.ogg', 'sound/machines/sm/accent/normal/18.ogg', 'sound/machines/sm/accent/normal/19.ogg', 'sound/machines/sm/accent/normal/20.ogg', 'sound/machines/sm/accent/normal/21.ogg', 'sound/machines/sm/accent/normal/22.ogg', 'sound/machines/sm/accent/normal/23.ogg', 'sound/machines/sm/accent/normal/24.ogg', 'sound/machines/sm/accent/normal/25.ogg', 'sound/machines/sm/accent/normal/26.ogg', 'sound/machines/sm/accent/normal/27.ogg', 'sound/machines/sm/accent/normal/28.ogg', 'sound/machines/sm/accent/normal/29.ogg', 'sound/machines/sm/accent/normal/30.ogg', 'sound/machines/sm/accent/normal/31.ogg', 'sound/machines/sm/accent/normal/32.ogg', 'sound/machines/sm/accent/normal/33.ogg', 'sound/machines/sm/supermatter1.ogg', 'sound/machines/sm/supermatter2.ogg', 'sound/machines/sm/supermatter3.ogg'), 50, FALSE, 10, null)
	SOUND_SET(SFX_SMDELAM, list('sound/machines/sm/accent/delam/1.ogg', 'sound/machines/sm/accent/normal/2.ogg', 'sound/machines/sm/accent/normal/3.ogg', 'sound/machines/sm/accent/normal/4.ogg', 'sound/machines/sm/accent/normal/5.ogg', 'sound/machines/sm/accent/normal/6.ogg', 'sound/machines/sm/accent/normal/7.ogg', 'sound/machines/sm/accent/normal/8.ogg', 'sound/machines/sm/accent/normal/9.ogg', 'sound/machines/sm/accent/normal/10.ogg', 'sound/machines/sm/accent/normal/11.ogg', 'sound/machines/sm/accent/normal/12.ogg', 'sound/machines/sm/accent/normal/13.ogg', 'sound/machines/sm/accent/normal/14.ogg', 'sound/machines/sm/accent/normal/15.ogg', 'sound/machines/sm/accent/normal/16.ogg', 'sound/machines/sm/accent/normal/17.ogg', 'sound/machines/sm/accent/normal/18.ogg', 'sound/machines/sm/accent/normal/19.ogg', 'sound/machines/sm/accent/normal/20.ogg', 'sound/machines/sm/accent/normal/21.ogg', 'sound/machines/sm/accent/normal/22.ogg', 'sound/machines/sm/accent/normal/23.ogg', 'sound/machines/sm/accent/normal/24.ogg', 'sound/machines/sm/accent/normal/25.ogg', 'sound/machines/sm/accent/normal/26.ogg', 'sound/machines/sm/accent/normal/27.ogg', 'sound/machines/sm/accent/normal/28.ogg', 'sound/machines/sm/accent/normal/29.ogg', 'sound/machines/sm/accent/normal/30.ogg', 'sound/machines/sm/accent/normal/31.ogg', 'sound/machines/sm/accent/normal/32.ogg', 'sound/machines/sm/accent/normal/33.ogg', 'sound/machines/sm/supermatter1.ogg', 'sound/machines/sm/supermatter2.ogg', 'sound/machines/sm/supermatter3.ogg'), 50, FALSE, 10, null)
	SOUND_SET(SFX_GENERIC_DROP, list('sound/items/drop/generic1.ogg', 'sound/items/drop/generic2.ogg'), 50, FALSE)
	SOUND_SET(SFX_GENERIC_PICKUP, list('sound/items/pickup/generic1.ogg', 'sound/items/pickup/generic2.ogg', 'sound/items/pickup/generic3.ogg'), 50, FALSE)
	SOUND_SET(SFX_POWERLOADERSTEP, list('sound/effects/mech/powerloader_step.ogg', 'sound/effects/mech/powerloader_step2.ogg'), 50, FALSE)
	SOUND_SET(SFX_SIZZLE, list('sound/effects/wounds/sizzle1.ogg', 'sound/effects/wounds/sizzle2.ogg'), 50, FALSE)

	SOUND_SET(SFX_ARCADE_BOOM, list('sound/arcade/boom.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_EXPLO, list('sound/arcade/explo.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_GET_FUEL, list('sound/arcade/get_fuel.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_HEAL, list('sound/arcade/heal.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_HIT, list('sound/arcade/hit.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_KILL_CREW, list('sound/arcade/kill_crew.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_LOSE, list('sound/arcade/lose.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_LOSE_FUEL, list('sound/arcade/lose_fuel.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_MANA, list('sound/arcade/mana.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_ORI_BEGIN, list('sound/arcade/ori_begin.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_ORI_FAIL, list('sound/arcade/ori_fail.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_ORI_WIN, list('sound/arcade/ori_win.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_RAID, list('sound/arcade/raid.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_STEAL, list('sound/arcade/steal.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_ARCADE_WIN, list('sound/arcade/win.ogg'), 50, TRUE, -3, 0.1)
	SOUND_SET(SFX_BODYFALL, list('sound/effects/bodyfall1.ogg', 'sound/effects/bodyfall2.ogg', 'sound/effects/bodyfall3.ogg', 'sound/effects/bodyfall4.ogg'), 50, TRUE)
	SOUND_SET(SFX_BUREAUCRACY_BOOKCLOSE, list('sound/bureaucracy/bookclose.ogg'), 50, TRUE)
	SOUND_SET(SFX_BUREAUCRACY_BOOKOPEN, list('sound/bureaucracy/bookopen.ogg'), 50, TRUE)
	SOUND_SET(SFX_BUREAUCRACY_FILINGCABINET, list('sound/bureaucracy/filingcabinet.ogg'), 50, TRUE)
	SOUND_SET(SFX_BUREAUCRACY_PAPERBURN, list('sound/bureaucracy/paperburn.ogg'), 50, TRUE)
	SOUND_SET(SFX_BUREAUCRACY_PAPERCRUMPLE, list('sound/bureaucracy/papercrumple.ogg'), 50, TRUE)
	SOUND_SET(SFX_BUREAUCRACY_PEN, list('sound/bureaucracy/pen1.ogg', 'sound/bureaucracy/pen2.ogg'), 20, FALSE)
	SOUND_SET(SFX_BUREAUCRACY_STAMP, list('sound/bureaucracy/stamp.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_3, list('sound/effects/3.wav'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_ADMINHELP, list('sound/effects/adminhelp.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_ALERT, list('sound/effects/alert.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_ATTACKBLOB, list('sound/effects/attackblob.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_BAMF, list('sound/effects/bamf.ogg'), 75, TRUE)
	SOUND_SET(SFX_EFFECTS_BANG, list('sound/effects/bang.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_BASSCANNON, list('sound/effects/basscannon.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_BLIND, list('sound/effects/blind.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_BLOBATTACK, list('sound/effects/blobattack.ogg'), 30, TRUE)
	SOUND_SET(SFX_EFFECTS_BODYFALL1, list('sound/effects/bodyfall1.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_BODYFALL4, list('sound/effects/bodyfall4.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_BREAK_STONE, list('sound/effects/break_stone.ogg'), 75, TRUE)
	SOUND_SET(SFX_EFFECTS_BUBBLES, list('sound/effects/bubbles.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_BUBBLES2, list('sound/effects/bubbles2.ogg'), 80, TRUE, -3, null)
	SOUND_SET(SFX_EFFECTS_CAPTURE_CRYSTAL_IN, list('sound/effects/capture-crystal-in.ogg'), 75, TRUE, -1, null)
	SOUND_SET(SFX_EFFECTS_CAPTURE_CRYSTAL_NEGATIVE, list('sound/effects/capture-crystal-negative.ogg'), 75, TRUE, -1, null)
	SOUND_SET(SFX_EFFECTS_CAPTURE_CRYSTAL_OUT, list('sound/effects/capture-crystal-out.ogg'), 75, TRUE, -1, null)
	SOUND_SET(SFX_EFFECTS_CAPTURE_CRYSTAL_PROBLEM, list('sound/effects/capture-crystal-problem.ogg'), 75, TRUE, -1, null)
	SOUND_SET(SFX_EFFECTS_CARREV, list('sound/effects/carrev.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_CHOP, list('sound/effects/chop.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_CLANG, list('sound/effects/clang.ogg'), 25, TRUE, -1, null)
	SOUND_SET(SFX_EFFECTS_CLANG2, list('sound/effects/clang2.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_CLOSET_CLOSE, list('sound/effects/closet_close.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_CLOSET_OPEN, list('sound/effects/closet_open.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_CLOWNSTEP2, list('sound/effects/clownstep2.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_COMP_ALERT_CLEAR, list('sound/effects/comp_alert_clear.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_COMP_ALERT_MAJOR, list('sound/effects/comp_alert_major.ogg'), 70, TRUE)
	SOUND_SET(SFX_EFFECTS_COMP_ALERT_MINOR, list('sound/effects/comp_alert_minor.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_CONTACTOR_OFF, list('sound/effects/contactor_off.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_CONTACTOR_ON, list('sound/effects/contactor_on.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_COSMIC_ENERGY, list('sound/effects/cosmic_energy.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_CRATE_CLOSE, list('sound/effects/crate_close.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_CRATE_OPEN, list('sound/effects/crate_open.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_DESKBELL, list('sound/effects/deskbell.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_DESKBELL_RUDE, list('sound/effects/deskbell_rude.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_DICEROLL_ROBOTIC, list('sound/effects/diceroll_robotic.ogg'), 75, FALSE)
	SOUND_SET(SFX_EFFECTS_DOORCREAKY, list('sound/effects/doorcreaky.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_DROPPOD, list('sound/effects/droppod.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_EAR_RING_EAR_DEAF_IN, list('sound/effects/ear_ring/ear_deaf_in.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_EMPULSE, list('sound/effects/EMPulse.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_EXPLOSION, list('sound/effects/Explosion1.ogg', 'sound/effects/Explosion2.ogg', 'sound/effects/Explosion3.ogg', 'sound/effects/Explosion4.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_EXPLOSION1, list('sound/effects/Explosion1.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_EXPLOSIONFAR, list('sound/effects/explosionfar.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_EXPLOSIONS_VEHICLEEXPLOSION, list('sound/effects/explosions/vehicleexplosion.ogg'), 100, TRUE, 3, null)
	SOUND_SET(SFX_EFFECTS_EXTINGUISH, list('sound/effects/extinguish.ogg'), 75, TRUE, -3, null)
	SOUND_SET(SFX_EFFECTS_FINGERSNAP, list('sound/effects/fingersnap.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_FOOTSTEP_CATWALK, list('sound/effects/footstep/catwalk1.ogg', 'sound/effects/footstep/catwalk2.ogg', 'sound/effects/footstep/catwalk3.ogg', 'sound/effects/footstep/catwalk4.ogg', 'sound/effects/footstep/catwalk5.ogg'), 25, TRUE)
	SOUND_SET(SFX_EFFECTS_FOOTSTEP_CRAWL1, list('sound/effects/footstep/crawl1.ogg'), 50, FALSE, 0, 1)
	SOUND_SET(SFX_EFFECTS_FOOTSTEP_FLOOR1, list('sound/effects/footstep/floor1.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_GHOST, list('sound/effects/ghost.ogg'), 50, TRUE, -3, null)
	SOUND_SET(SFX_EFFECTS_GHOST2, list('sound/effects/ghost2.ogg'), 20, TRUE)
	SOUND_SET(SFX_EFFECTS_GHOST_MIX, list('sound/effects/ghost.ogg', 'sound/effects/ghost2.ogg', 'sound/effects/Heart Beat.ogg', 'sound/effects/screech.ogg', 'sound/hallucinations/behind_you1.ogg', 'sound/hallucinations/behind_you2.ogg', 'sound/hallucinations/far_noise.ogg', 'sound/hallucinations/growl1.ogg', 'sound/hallucinations/growl2.ogg', 'sound/hallucinations/growl3.ogg', 'sound/hallucinations/im_here1.ogg', 'sound/hallucinations/im_here2.ogg', 'sound/hallucinations/i_see_you1.ogg', 'sound/hallucinations/i_see_you2.ogg', 'sound/hallucinations/look_up1.ogg', 'sound/hallucinations/look_up2.ogg', 'sound/hallucinations/over_here1.ogg', 'sound/hallucinations/over_here2.ogg', 'sound/hallucinations/over_here3.ogg', 'sound/hallucinations/wail.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_GLASSBR2, list('sound/effects/Glassbr2.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_GLASSBR3, list('sound/effects/Glassbr3.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_GLASSHIT, list('sound/effects/Glasshit.ogg'), 75, TRUE)
	SOUND_SET(SFX_EFFECTS_GLASSKNOCK, list('sound/effects/glassknock.ogg'), 80, TRUE)
	SOUND_SET(SFX_EFFECTS_GLASS_STEP, list('sound/effects/glass_step.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_GRILLEHIT, list('sound/effects/grillehit.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_HIT_ON_SHATTERED_GLASS, list('sound/effects/hit_on_shattered_glass.ogg'), 70, TRUE)
	SOUND_SET(SFX_EFFECTS_HOUNDSTEP, list('sound/effects/houndstep.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_HYPOSPRAY, list('sound/effects/hypospray.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_INSERT_ID_CARD, list('sound/effects/insert_id_card.ogg'), 75, FALSE)
	SOUND_SET(SFX_EFFECTS_LIGHTNINGBOLT, list('sound/effects/lightningbolt.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_LIGHTNINGSHOCK, list('sound/effects/lightningshock.ogg'), 100, TRUE, 5, null)
	SOUND_SET(SFX_EFFECTS_LIGHTNING_CHARGEUP, list('sound/effects/lightning_chargeup.ogg'), 100, TRUE, 30, null)
	SOUND_SET(SFX_EFFECTS_LIGHTON, list('sound/effects/lighton.ogg'), 65, TRUE)
	SOUND_SET(SFX_EFFECTS_LIGHT_FLICKER, list('sound/effects/light_flicker.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_LOCKER_CLOSE, list('sound/effects/locker_close.ogg'), 25, FALSE, -3, null)
	SOUND_SET(SFX_EFFECTS_LOCKER_OPEN, list('sound/effects/locker_open.ogg'), 15, TRUE, -3, null)
	SOUND_SET(SFX_EFFECTS_MAGNETCLAMP, list('sound/effects/magnetclamp.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_METALSCRAPE, list('sound/effects/metalscrape1.ogg', 'sound/effects/metalscrape2.ogg', 'sound/effects/metalscrape3.ogg'), 70, TRUE)
	SOUND_SET(SFX_EFFECTS_METALSCRAPE2, list('sound/effects/metalscrape2.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_METAL_CLOSE, list('sound/effects/metal_close.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_METEORIMPACT, list('sound/effects/meteorimpact.ogg'), 40, TRUE)
	SOUND_SET(SFX_EFFECTS_MOB_EFFECTS_SUIT_BREATHE_IN, list('sound/effects/mob_effects/suit_breathe_in.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_MOB_EFFECTS_SUIT_BREATHE_OUT, list('sound/effects/mob_effects/suit_breathe_out.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_MOB_EFFECTS_XENOCHIMERA_HATCH, list('sound/effects/mob_effects/xenochimera/hatch.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_MOB_EFFECTS_XENOCHIMERA_REGEN_MIX, list('sound/effects/mob_effects/xenochimera/regen_1.ogg', 'sound/effects/mob_effects/xenochimera/regen_2.ogg', 'sound/effects/mob_effects/xenochimera/regen_4.ogg', 'sound/effects/mob_effects/xenochimera/regen_3.ogg', 'sound/effects/mob_effects/xenochimera/regen_5.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_MONOLITH_DEATH, list('sound/effects/monolith_death.ogg'), 100, FALSE)
	SOUND_SET(SFX_EFFECTS_MOUSE_SQUEAK, list('sound/effects/mouse_squeak.ogg'), 35, TRUE)
	SOUND_SET(SFX_EFFECTS_MOUSE_SQUEAK_LOUD, list('sound/effects/mouse_squeak_loud.ogg'), 35, TRUE)
	SOUND_SET(SFX_EFFECTS_OINTMENT, list('sound/effects/ointment.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_OMINOUS_HUM_2, list('sound/effects/ominous-hum-2.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_PACKAGEDFOODOPEN, list('sound/effects/packagedfoodopen.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_PAI_RESTORE, list('sound/effects/pai-restore.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_PHASEIN, list('sound/effects/phasein.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_PLOP, list('sound/effects/plop.ogg'), 45, FALSE)
	SOUND_SET(SFX_EFFECTS_POP, list('sound/effects/pop.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_PORTAL_EFFECT, list('sound/effects/portal_effect.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_RADIO_COMMON, list('sound/effects/radio_common.ogg'), 20, TRUE, 1, null)
	SOUND_SET(SFX_EFFECTS_REFILL, list('sound/effects/refill.ogg'), 50, TRUE, -6, null)
	SOUND_SET(SFX_EFFECTS_REMOVE_ID_CARD, list('sound/effects/remove_id_card.ogg'), 75, FALSE)
	SOUND_SET(SFX_EFFECTS_REPULSE, list('sound/effects/repulse.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_RIP_MIX, list('sound/effects/rip1.ogg', 'sound/effects/rip2.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_RIP_MIX_2, list('sound/effects/rip1.ogg', 'sound/effects/rip2.ogg', 'sound/effects/tape.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_ROLL, list('sound/effects/roll.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_RUSTLE1, list('sound/effects/rustle1.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_RUSTLE2, list('sound/effects/rustle2.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_RUSTLE3, list('sound/effects/rustle3.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_RUSTLE4, list('sound/effects/rustle4.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SCREECH, list('sound/effects/screech.ogg'), 100, TRUE, 1, null)
	SOUND_SET(SFX_EFFECTS_SEATBELT, list('sound/effects/seatbelt.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SERVOSTEP, list('sound/effects/servostep.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SHIELDBASH, list('sound/effects/shieldbash.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SHUTTLES_HYPERSPACE_BEGIN, list('sound/effects/shuttles/hyperspace_begin.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SHUTTLES_HYPERSPACE_END, list('sound/effects/shuttles/hyperspace_end.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SHUTTLES_HYPERSPACE_PROGRESS, list('sound/effects/shuttles/hyperspace_progress.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SINGLEBEAT, list('sound/effects/singlebeat.ogg'), 50, FALSE)
	SOUND_SET(SFX_EFFECTS_SINK, list('sound/effects/sink.ogg'), 75, TRUE)
	SOUND_SET(SFX_EFFECTS_SINK_LONG, list('sound/effects/sink_long.ogg'), 75, TRUE)
	SOUND_SET(SFX_EFFECTS_SKELETON_WALK, list('sound/effects/skeleton_walk.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SLIME_SQUISH, list('sound/effects/slime_squish.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SLOSH, list('sound/effects/slosh.ogg'), 25, TRUE)
	SOUND_SET(SFX_EFFECTS_SMOKE, list('sound/effects/smoke.ogg'), 50, TRUE, -3, null)
	SOUND_SET(SFX_EFFECTS_SMOKE_MIX, list('sound/effects/smoke.ogg', 'sound/effects/bubbles.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SNAP, list('sound/effects/snap.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SNORT, list('sound/effects/snort.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SPARKS1, list('sound/effects/sparks1.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_SPARKS2, list('sound/effects/sparks2.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SPARKS3, list('sound/effects/sparks3.ogg'), 10, TRUE, -3, null)
	SOUND_SET(SFX_EFFECTS_SPARKS4, list('sound/effects/sparks4.ogg'), 75, TRUE)
	SOUND_SET(SFX_EFFECTS_SPARKS6, list('sound/effects/sparks6.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_SPARKS7, list('sound/effects/sparks7.ogg'), 40, TRUE)
	SOUND_SET(SFX_EFFECTS_SPIDER_LOOP, list('sound/effects/spider_loop.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SPLAT, list('sound/effects/splat.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SPRAY, list('sound/effects/spray.ogg'), 10, TRUE, -3, null)
	SOUND_SET(SFX_EFFECTS_SPRAY2, list('sound/effects/spray2.ogg'), 100, TRUE, -6, null)
	SOUND_SET(SFX_EFFECTS_SPRAY3, list('sound/effects/spray3.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SPRAY_MIX, list('sound/effects/spray.ogg', 'sound/effects/spray2.ogg', 'sound/effects/spray3.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_STEALTHOFF, list('sound/effects/stealthoff.ogg'), 50, TRUE, 1, null)
	SOUND_SET(SFX_EFFECTS_STONEDOOR_OPENCLOSE, list('sound/effects/stonedoor_openclose.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_SUPERMATTER, list('sound/effects/supermatter.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_TABLEHEADSMASH, list('sound/effects/tableheadsmash.ogg'), 90, TRUE)
	SOUND_SET(SFX_EFFECTS_TAPE, list('sound/effects/tape.ogg'), 25, FALSE)
	SOUND_SET(SFX_EFFECTS_TELEPORT, list('sound/effects/teleport.ogg'), 40, FALSE)
	SOUND_SET(SFX_EFFECTS_TINCANOPEN, list('sound/effects/tincanopen.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_TURRET_MOVE1, list('sound/effects/turret/move1.wav'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_TURRET_MOVE2, list('sound/effects/turret/move2.wav'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_UNCLOAK, list('sound/effects/uncloak.ogg'), 35, TRUE, -1, null)
	SOUND_SET(SFX_EFFECTS_VEHICLE_ENGINE_OFF, list('sound/effects/vehicle/engine_off.ogg'), 60, TRUE, -2, null)
	SOUND_SET(SFX_EFFECTS_VEHICLE_IGNITION_CAR, list('sound/effects/vehicle/ignition_car.ogg'), 60, TRUE, -2, null)
	SOUND_SET(SFX_EFFECTS_WARBLE, list('sound/effects/warble.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_WEATHER_RAIN_START_RAIN, list('sound/effects/weather/rain/start_rain.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_WEATHER_SNOWSTORM_SNOWSTORM_START, list('sound/effects/weather/snowstorm/snowstorm_start.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_WEATHER_STORM_STORM_START_MIX, list('sound/effects/weather/storm/storm_start1.ogg', 'sound/effects/weather/storm/storm_start2.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_WEATHER_WIND_WIND_START, list('sound/effects/weather/wind/wind_start.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_WEIGHTDROP, list('sound/effects/weightdrop.ogg'), 25, TRUE)
	SOUND_SET(SFX_EFFECTS_WEIGHTLIFTER, list('sound/effects/weightlifter.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_WHIPCRACK, list('sound/effects/Whipcrack.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_WHISTLE, list('sound/effects/whistle.ogg'), 50, TRUE, 0, 5)
	SOUND_SET(SFX_EFFECTS_WOODCUTTING, list('sound/effects/woodcutting.ogg'), 100, TRUE)
	SOUND_SET(SFX_EFFECTS_WOODEN_CLOSET_CLOSE, list('sound/effects/wooden_closet_close.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_WOODEN_CLOSET_OPEN, list('sound/effects/wooden_closet_open.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_WOODHIT, list('sound/effects/woodhit.ogg'), 25, TRUE, -1, null)
	SOUND_SET(SFX_EFFECTS_XYLOPHONE_MIX, list('sound/effects/xylophone1.ogg', 'sound/effects/xylophone2.ogg', 'sound/effects/xylophone3.ogg'), 50, TRUE)
	SOUND_SET(SFX_EFFECTS_ZZZT, list('sound/effects/zzzt.ogg'), 50, TRUE)
	SOUND_SET(SFX_GOONSTATION_SPOOKY_CREEPYSHRIEK, list('sound/goonstation/spooky/creepyshriek.ogg'), 100, TRUE, 75, null)
	SOUND_SET(SFX_HALLUCINATIONS_GROWL, list('sound/hallucinations/growl1.ogg', 'sound/hallucinations/growl2.ogg', 'sound/hallucinations/growl3.ogg'), 50, TRUE, -3, null)
	SOUND_SET(SFX_HALLUCINATIONS_GROWL1, list('sound/hallucinations/growl1.ogg'), 50, TRUE)
	SOUND_SET(SFX_HALLUCINATIONS_GROWL_MIX, list('sound/hallucinations/growl1.ogg', 'sound/hallucinations/growl2.ogg', 'sound/hallucinations/growl3.ogg', 'sound/hallucinations/wail.ogg'), 50, TRUE)
	SOUND_SET(SFX_HALLUCINATIONS_VOICES, list('sound/hallucinations/behind_you1.ogg', 'sound/hallucinations/behind_you2.ogg', 'sound/hallucinations/i_see_you1.ogg', 'sound/hallucinations/i_see_you2.ogg', 'sound/hallucinations/im_here1.ogg', 'sound/hallucinations/im_here2.ogg', 'sound/hallucinations/look_up1.ogg', 'sound/hallucinations/look_up2.ogg', 'sound/hallucinations/over_here1.ogg', 'sound/hallucinations/over_here2.ogg', 'sound/hallucinations/over_here3.ogg', 'sound/hallucinations/turn_around1.ogg', 'sound/hallucinations/turn_around2.ogg'), 50, TRUE, -3, null)
	SOUND_SET(SFX_HALLUCINATIONS_WAIL, list('sound/hallucinations/wail.ogg', 'sound/hallucinations/veryfar_noise.ogg', 'sound/hallucinations/far_noise.ogg'), 50, TRUE, -3, null)
	SOUND_SET(SFX_H_SOUNDS_BREATHING, list('sound/h_sounds/breathing.ogg'), 60, TRUE)
	SOUND_SET(SFX_H_SOUNDS_HEADCRAB, list('sound/h_sounds/headcrab.ogg'), 50, TRUE)
	SOUND_SET(SFX_H_SOUNDS_HEADCRAB_2, list('sound/h_sounds/headcrab.ogg', 'sound/h_sounds/holla.ogg', 'sound/h_sounds/lynx.ogg', 'sound/h_sounds/mumble.ogg', 'sound/h_sounds/yell.ogg'), 50, TRUE)
	SOUND_SET(SFX_H_SOUNDS_HOLLA, list('sound/h_sounds/holla.ogg'), 50, TRUE)
	SOUND_SET(SFX_H_SOUNDS_IMBECILES, list('sound/h_sounds/imbeciles.ogg'), 50, TRUE)
	SOUND_SET(SFX_H_SOUNDS_LYNX, list('sound/h_sounds/lynx.ogg'), 50, TRUE)
	SOUND_SET(SFX_H_SOUNDS_MUMBLE, list('sound/h_sounds/mumble.ogg'), 50, TRUE)
	SOUND_SET(SFX_H_SOUNDS_NEGATIVE, list('sound/h_sounds/negative.ogg'), 50, TRUE)
	SOUND_SET(SFX_H_SOUNDS_SAMPLER, list('sound/h_sounds/sampler.ogg'), 50, TRUE)
	SOUND_SET(SFX_H_SOUNDS_SHITTY_TIM, list('sound/h_sounds/shitty_tim.ogg'), 50, TRUE)
	SOUND_SET(SFX_H_SOUNDS_YOUKNOWWHOITIS, list('sound/h_sounds/youknowwhoitis.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_AIRHORN, list('sound/items/AirHorn.ogg'), 100, TRUE)
	SOUND_SET(SFX_ITEMS_BIKEHORN, list('sound/items/bikehorn.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_BUTTON_CLOSE, list('sound/items/button-close.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_BUTTON_OPEN, list('sound/items/button-open.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_CARDSHUFFLE, list('sound/items/cardshuffle.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_CHANGE_DRILL, list('sound/items/change_drill.ogg'), 25, TRUE)
	SOUND_SET(SFX_ITEMS_CHANGE_JAWS, list('sound/items/change_jaws.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_CIGS_LIGHTERS_CIG_LIGHT, list('sound/items/cigs_lighters/cig_light.ogg'), 75, TRUE, -1, null)
	SOUND_SET(SFX_ITEMS_CIGS_LIGHTERS_CIG_SNUFF, list('sound/items/cigs_lighters/cig_snuff.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_CIGS_LIGHTERS_INHALE, list('sound/items/cigs_lighters/inhale.ogg'), 50, FALSE, -1, null)
	SOUND_SET(SFX_ITEMS_CIGS_LIGHTERS_MATCHSTICK_HIT, list('sound/items/cigs_lighters/matchstick_hit.ogg'), 25, FALSE, -1, null)
	SOUND_SET(SFX_ITEMS_CIGS_LIGHTERS_MATCHSTICK_LIT, list('sound/items/cigs_lighters/matchstick_lit.ogg'), 25, FALSE, -1, null)
	SOUND_SET(SFX_ITEMS_CONFETTI, list('sound/items/confetti.ogg'), 50, FALSE)
	SOUND_SET(SFX_ITEMS_COUNTDOWN, list('sound/items/countdown.ogg'), 75, TRUE, -3, null)
	SOUND_SET(SFX_ITEMS_CROWBAR, list('sound/items/Crowbar.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DECONSTRUCT, list('sound/items/Deconstruct.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DRILL_HIT, list('sound/items/drill_hit.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DRILL_USE, list('sound/items/drill_use.ogg', 'sound/items/jaws_cut.ogg', 'sound/items/jaws_pry.ogg', 'sound/items/Welder.ogg', 'sound/items/Wirecutter.ogg', 'sound/items/Crowbar.ogg', 'sound/items/Ratchet.ogg'), 80, TRUE, -1, null)
	SOUND_SET(SFX_ITEMS_DRILL_USE_2, list('sound/items/drill_use.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DRINK, list('sound/items/drink.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_ACCESSORY, list('sound/items/drop/accessory.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_AMMOBOX, list('sound/items/drop/ammobox.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_AXE, list('sound/items/drop/axe.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_BACKPACK, list('sound/items/drop/backpack.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_BASKETBALL, list('sound/items/drop/basketball.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_BOOK, list('sound/items/drop/book.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_BOOTS, list('sound/items/drop/boots.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_BOTTLE, list('sound/items/drop/bottle.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_BOX, list('sound/items/drop/box.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_CARD, list('sound/items/drop/card.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_CARDBOARDBOX, list('sound/items/drop/cardboardbox.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_CLOTH, list('sound/items/drop/cloth.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_CLOTHING, list('sound/items/drop/clothing.ogg'), 100, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_COMPONENT, list('sound/items/drop/component.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_CROWBAR, list('sound/items/drop/crowbar.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_DEVICE, list('sound/items/drop/device.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_DISK, list('sound/items/drop/disk.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_DRINKGLASS, list('sound/items/drop/drinkglass.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_FLESH, list('sound/items/drop/flesh.ogg'), 100, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_FOOD, list('sound/items/drop/food.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_GASCAN, list('sound/items/drop/gascan.ogg'), 100, TRUE, 1, null)
	SOUND_SET(SFX_ITEMS_DROP_GLASS, list('sound/items/drop/glass.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_GLOVES, list('sound/items/drop/gloves.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_GUN, list('sound/items/drop/gun.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_HAT, list('sound/items/drop/hat.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_HELM, list('sound/items/drop/helm.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_HERB, list('sound/items/drop/herb.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_KNIFE, list('sound/items/drop/knife.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_LEATHER, list('sound/items/drop/leather.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_MATCHBOX, list('sound/items/drop/matchbox.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_METALBOOTS, list('sound/items/drop/metalboots.ogg'), 75, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_METALSHIELD, list('sound/items/drop/metalshield.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_METALWEAPON, list('sound/items/drop/metalweapon.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_MULTITOOL, list('sound/items/drop/multitool.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_PAPER, list('sound/items/drop/paper.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_PAPERCUP, list('sound/items/drop/papercup.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_PILLBOTTLE, list('sound/items/drop/pillbottle.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_PLUSHIE, list('sound/items/drop/plushie.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_RING, list('sound/items/drop/ring.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_RUBBER, list('sound/items/drop/rubber.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_SCRAP, list('sound/items/drop/scrap.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_SCREWDRIVER, list('sound/items/drop/screwdriver.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_SHOES, list('sound/items/drop/shoes.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_SHOVEL, list('sound/items/drop/shovel.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_SMOLEMATERIAL, list('sound/items/drop/smolematerial.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_SODA, list('sound/items/drop/soda.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_SWORD, list('sound/items/drop/sword.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_TOOLBELT, list('sound/items/drop/toolbelt.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_TOOLBOX, list('sound/items/drop/toolbox.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_WELDINGTOOL, list('sound/items/drop/weldingtool.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_WIRECUTTER, list('sound/items/drop/wirecutter.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_WOODEN, list('sound/items/drop/wooden.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_WRAPPER, list('sound/items/drop/wrapper.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_DROP_WRENCH, list('sound/items/drop/wrench.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_EATFOOD, list('sound/items/eatfood.ogg'), 75, TRUE)
	SOUND_SET(SFX_ITEMS_ELECTRONIC_ASSEMBLY_EMPTYING, list('sound/items/electronic_assembly_emptying.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_FULEXT_DEPLOY, list('sound/items/fulext_deploy.wav'), 50, TRUE, -3, null)
	SOUND_SET(SFX_ITEMS_FULTEXT_LAUNCH, list('sound/items/fultext_launch.wav'), 50, TRUE, -3, null)
	SOUND_SET(SFX_ITEMS_GEIGER_HIGH1, list('sound/items/geiger/high1.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_GOGGLES_CHARGE, list('sound/items/goggles_charge.ogg'), 50, TRUE, -6, null)
	SOUND_SET(SFX_ITEMS_HELMETDEPLOY, list('sound/items/helmetdeploy.ogg'), 40, TRUE)
	SOUND_SET(SFX_ITEMS_HOLSTERIN, list('sound/items/holsterin.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_HOLSTEROUT, list('sound/items/holsterout.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_HOOH, list('sound/items/hooh.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_JAWS_CUT, list('sound/items/jaws_cut.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_JAWS_PRY, list('sound/items/jaws_pry.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_JUMPSUIT_EQUIP, list('sound/items/jumpsuit_equip.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_LIGHTER_OFF, list('sound/items/lighter_off.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_LIGHTER_ON, list('sound/items/lighter_on.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_MAIL_MAILAPPROVED, list('sound/items/mail/mailapproved.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_MAIL_MAILDENIED, list('sound/items/mail/maildenied.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_MAIL_MAILSCANNED, list('sound/items/mail/mailscanned.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_NIF_CLICK, list('sound/items/nif_click.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_NIF_TONE_BAD, list('sound/items/nif_tone_bad.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_NIF_TONE_GOOD, list('sound/items/nif_tone_good.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PACKAGE_UNWRAP, list('sound/items/package_unwrap.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PACKAGE_WRAP, list('sound/items/package_wrap.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PENCLICK, list('sound/items/penclick.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_ACCESSORY, list('sound/items/pickup/accessory.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_AMMOBOX, list('sound/items/pickup/ammobox.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_AXE, list('sound/items/pickup/axe.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_BACKPACK, list('sound/items/pickup/backpack.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_BASKETBALL, list('sound/items/pickup/basketball.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_BOOK, list('sound/items/pickup/book.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_BOOTS, list('sound/items/pickup/boots.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_BOTTLE, list('sound/items/pickup/bottle.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_CARD, list('sound/items/pickup/card.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_CARDBOARDBOX, list('sound/items/pickup/cardboardbox.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_CLOTH, list('sound/items/pickup/cloth.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_CLOTHING, list('sound/items/pickup/clothing.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_COMPONENT, list('sound/items/pickup/component.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_CROWBAR, list('sound/items/pickup/crowbar.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_DEVICE, list('sound/items/pickup/device.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_DISK, list('sound/items/pickup/disk.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_DRINKGLASS, list('sound/items/pickup/drinkglass.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_FLESH, list('sound/items/pickup/flesh.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_FOOD, list('sound/items/pickup/food.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_GASCAN, list('sound/items/pickup/gascan.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_GLASS, list('sound/items/pickup/glass.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_GLOVES, list('sound/items/pickup/gloves.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_GUN, list('sound/items/pickup/gun.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_HAT, list('sound/items/pickup/hat.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_HELM, list('sound/items/pickup/helm.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_HERB, list('sound/items/pickup/herb.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_KNIFE, list('sound/items/pickup/knife.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_LEATHER, list('sound/items/pickup/leather.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_MATCHBOX, list('sound/items/pickup/matchbox.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_METALWEAPON, list('sound/items/pickup/metalweapon.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_MULTITOOL, list('sound/items/pickup/multitool.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_PAPER, list('sound/items/pickup/paper.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_PAPERCUP, list('sound/items/pickup/papercup.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_PILLBOTTLE, list('sound/items/pickup/pillbottle.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_RING, list('sound/items/pickup/ring.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_RUBBER, list('sound/items/pickup/rubber.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_SCREWDRIVER, list('sound/items/pickup/screwdriver.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_SHOES, list('sound/items/pickup/shoes.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_SHOVEL, list('sound/items/pickup/shovel.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_SODA, list('sound/items/pickup/soda.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_SWORD, list('sound/items/pickup/sword.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_TOOLBELT, list('sound/items/pickup/toolbelt.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_TOOLBOX, list('sound/items/pickup/toolbox.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_WELDINGTOOL, list('sound/items/pickup/weldingtool.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_WIRECUTTER, list('sound/items/pickup/wirecutter.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_WOODEN, list('sound/items/pickup/wooden.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_WOODWEAPON, list('sound/items/pickup/woodweapon.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_WRAPPER, list('sound/items/pickup/wrapper.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PICKUP_WRENCH, list('sound/items/pickup/wrench.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_POLAROID, list('sound/items/polaroid1.ogg', 'sound/items/polaroid2.ogg'), 75, TRUE, -3, null)
	SOUND_SET(SFX_ITEMS_POLAROID1, list('sound/items/polaroid1.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_POLAROID2, list('sound/items/polaroid2.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_POSTER_BEING_CREATED, list('sound/items/poster_being_created.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_POSTER_RIPPED, list('sound/items/poster_ripped.ogg'), 100, TRUE)
	SOUND_SET(SFX_ITEMS_PSHOOM, list('sound/items/pshoom.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_PSHRED, list('sound/items/pshred.ogg'), 75, TRUE)
	SOUND_SET(SFX_ITEMS_RATCHET, list('sound/items/Ratchet.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_RPED, list('sound/items/rped.ogg'), 25, TRUE)
	SOUND_SET(SFX_ITEMS_SALVAGE_SALVAGEDROP, list('sound/items/salvage/salvagedrop.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_SALVAGE_SALVAGEPICKUP, list('sound/items/salvage/salvagepickup.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_SCREWDRIVER, list('sound/items/Screwdriver.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_SCREWDRIVER2, list('sound/items/Screwdriver2.ogg'), 25, TRUE)
	SOUND_SET(SFX_ITEMS_SMALL_MOTOR_MOTOR_PULL_ATTEMPT, list('sound/items/small_motor/motor_pull_attempt.ogg'), 100, FALSE)
	SOUND_SET(SFX_ITEMS_SMALL_MOTOR_MOTOR_START_NOPULL, list('sound/items/small_motor/motor_start_nopull.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_SMOLEBUILDINGDESTORYED, list('sound/items/smolebuildingdestoryed.ogg'), 50, TRUE, -1, null)
	SOUND_SET(SFX_ITEMS_SMOLEBUILDINGDESTORYEDSHORT, list('sound/items/smolebuildingdestoryedshort.ogg'), 50, TRUE, -1, null)
	SOUND_SET(SFX_ITEMS_SMOLEBUILDINGHIT2, list('sound/items/smolebuildinghit2.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_SMOLELARGEUNBUILD, list('sound/items/smolelargeunbuild.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_SMOLESMALLBUILD, list('sound/items/smolesmallbuild.ogg'), 50, TRUE, -1, null)
	SOUND_SET(SFX_ITEMS_SONIC_DRIVER, list('sound/items/sonic_driver.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_STORAGE_BOX, list('sound/items/storage/box.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_STORAGE_BOXFOLD, list('sound/items/storage/boxfold.ogg'), 30, TRUE)
	SOUND_SET(SFX_ITEMS_STORAGE_BRIEFCASE, list('sound/items/storage/briefcase.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_STORAGE_PILLBOTTLE, list('sound/items/storage/pillbottle.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_STORAGE_SMOLECASE, list('sound/items/storage/smolecase.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_STORAGE_TOOLBOX, list('sound/items/storage/toolbox.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_SYRINGEPROJ, list('sound/items/syringeproj.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_TAPERECORDER_DROP, list('sound/items/taperecorder_drop.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_TAPERECORDER_PICKUP, list('sound/items/taperecorder_pickup.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_TICKET_PRINTER, list('sound/items/ticket_printer.ogg'), 75, TRUE)
	SOUND_SET(SFX_ITEMS_TIMER, list('sound/items/timer.ogg'), 50, FALSE)
	SOUND_SET(SFX_ITEMS_TINYTETHER, list('sound/items/tinytether.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_TOOLBELT_EQUIP, list('sound/items/toolbelt_equip.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_TOOLS_WELDER, list('sound/items/tools/welder.ogg'), 100, TRUE)
	SOUND_SET(SFX_ITEMS_TRAYHIT1, list('sound/items/trayhit1.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_TRAYHIT_MIX, list('sound/items/trayhit1.ogg', 'sound/items/trayhit2.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_WASHINGMACHINE, list('sound/items/washingmachine.ogg'), 50, TRUE, 1, null)
	SOUND_SET(SFX_ITEMS_WEAPONS_SEAR, list('sound/items/weapons/sear.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_WEAPONS_SMASH, list('sound/items/weapons/smash.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_WEAPONS_TAP, list('sound/items/weapons/tap.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_WELDER, list('sound/items/Welder.ogg'), 100, TRUE)
	SOUND_SET(SFX_ITEMS_WELDER2, list('sound/items/Welder2.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_WELDERACTIVATE, list('sound/items/welderactivate.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_WELDERDEACTIVATE, list('sound/items/welderdeactivate.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_WIRECUTTER, list('sound/items/Wirecutter.ogg'), 100, TRUE)
	SOUND_SET(SFX_ITEMS_ZIP, list('sound/items/zip.ogg'), 75, TRUE)
	SOUND_SET(SFX_ITEMS_ZIPPO_OFF, list('sound/items/zippo_off.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_ZIPPO_ON, list('sound/items/zippo_on.ogg'), 50, TRUE)
	SOUND_SET(SFX_ITEMS_ZIPPO_ON_ALT, list('sound/items/zippo_on_alt.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_2BEEPHIGH, list('sound/machines/2beephigh.ogg'), 75, FALSE)
	SOUND_SET(SFX_MACHINES_2BEEPLOW, list('sound/machines/2beeplow.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_AIRALARM, list('sound/machines/airalarm.ogg'), 25, FALSE, 4, null)
	SOUND_SET(SFX_MACHINES_AIRPUMPIDLE, list('sound/machines/airpumpidle.ogg'), 100, TRUE)
	SOUND_SET(SFX_MACHINES_AIR_PUMP_AIRPUMPSHUTDOWN, list('sound/machines/air_pump/airpumpshutdown.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_AIR_PUMP_AIRPUMPSTART, list('sound/machines/air_pump/airpumpstart.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_ALARM, list('sound/machines/Alarm.ogg'), 10, FALSE)
	SOUND_SET(SFX_MACHINES_APC_NOPOWER, list('sound/machines/apc_nopower.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_BEEP, list('sound/machines/beep.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_BIOGENERATOR_END, list('sound/machines/biogenerator_end.ogg'), 40, TRUE)
	SOUND_SET(SFX_MACHINES_BLENDER, list('sound/machines/blender.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_BOOBEEBEEP, list('sound/machines/boobeebeep.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_BUTTON, list('sound/machines/button.ogg'), 30, TRUE)
	SOUND_SET(SFX_MACHINES_BUTTONBEEP, list('sound/machines/buttonbeep.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_BUZZBEEP, list('sound/machines/buzzbeep.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_BUZZ_SIGH, list('sound/machines/buzz-sigh.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_BUZZ_TWO, list('sound/machines/buzz-two.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_CHIME, list('sound/machines/chime.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_CLICK, list('sound/machines/click.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_CLICK2, list('sound/machines/click2.ogg'), 75, TRUE)
	SOUND_SET(SFX_MACHINES_CLOCKCULT_STEAM_WHOOSH, list('sound/machines/clockcult/steam_whoosh.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_CONSOLE_POWER_ON, list('sound/machines/console_power_on.ogg'), 60, TRUE)
	SOUND_SET(SFX_MACHINES_COPIER, list('sound/machines/copier.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_DEFIB_CHARGE, list('sound/machines/defib_charge.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_DEFIB_FAILED, list('sound/machines/defib_failed.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_DEFIB_READY, list('sound/machines/defib_ready.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_DEFIB_SAFETYOFF, list('sound/machines/defib_safetyOff.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_DEFIB_SAFETYON, list('sound/machines/defib_SafetyOn.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_DEFIB_SUCCESS, list('sound/machines/defib_success.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_DEFIB_ZAP, list('sound/machines/defib_zap.ogg'), 50, TRUE, -1, null)
	SOUND_SET(SFX_MACHINES_DENIEDBEEP, list('sound/machines/deniedbeep.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_DESTRUCTIVE_ANALYZER, list('sound/machines/destructive_analyzer.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DING, list('sound/machines/ding.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DISPERSER_FIRE, list('sound/machines/disperser_fire.ogg'), 100, TRUE)
	SOUND_SET(SFX_MACHINES_DISPOSALFLUSH, list('sound/machines/disposalflush.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_DOORBELL, list('sound/machines/doorbell.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_AIRLOCK_CREAKING, list('sound/machines/door/airlock_creaking.ogg'), 100, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_AIRLOCK_TEAR_APART, list('sound/machines/door/airlock_tear_apart.ogg'), 100, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_BLASTDOORCLOSE, list('sound/machines/door/blastdoorclose.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_BLASTDOOROPEN, list('sound/machines/door/blastdooropen.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_BOLTSDOWN, list('sound/machines/door/boltsdown.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_BOLTSUP, list('sound/machines/door/boltsup.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_GARAGEDOORCLOSE, list('sound/machines/door/garagedoorclose.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_GARAGEDOOROPEN, list('sound/machines/door/garagedooropen.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_KNOCK_GLASS, list('sound/machines/door/knock_glass.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_KNOCK_WOOD, list('sound/machines/door/knock_wood.wav'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_LOCKED, list('sound/machines/door_locked.ogg'), 30, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_OLD_AIRLOCK, list('sound/machines/door/old_airlock.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_DOOR_WINDOWDOOR, list('sound/machines/door/windowdoor.ogg'), 100, TRUE)
	SOUND_SET(SFX_MACHINES_DWOOP, list('sound/machines/dwoop.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_FIRELOCKCLOSE, list('sound/machines/firelockclose.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_FIRELOCKOPEN, list('sound/machines/firelockopen.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_FIREWIDE1C, list('sound/machines/firewide1c.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_FIREWIDE1O, list('sound/machines/firewide1o.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_GENERATOR_GENERATOR_END, list('sound/machines/generator/generator_end.ogg'), 70, TRUE)
	SOUND_SET(SFX_MACHINES_GENERATOR_GENERATOR_START, list('sound/machines/generator/generator_start.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_HATCHCLOSE, list('sound/machines/hatchclose.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_HATCH_OPEN, list('sound/machines/hatch_open.ogg'), 75, TRUE)
	SOUND_SET(SFX_MACHINES_HISS, list('sound/machines/hiss.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_HONKBOT_EVIL_LAUGH, list('sound/machines/honkbot_evil_laugh.ogg'), 20, TRUE)
	SOUND_SET(SFX_MACHINES_HPLC_BINARY_PUMP, list('sound/machines/HPLC_binary_pump.ogg'), 15, TRUE)
	SOUND_SET(SFX_MACHINES_ID_SWIPE, list('sound/machines/id_swipe.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_JUICER, list('sound/machines/juicer.ogg'), 25, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_CANDYMAKER_CANDYMAKER_MID1, list('sound/machines/kitchen/candymaker/candymaker-mid1.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_CANDYMAKER_CANDYMAKER_START, list('sound/machines/kitchen/candymaker/candymaker-start.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_CEREALMAKER_CEREALMAKER_START, list('sound/machines/kitchen/cerealmaker/cerealmaker-start.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_FRIDGE_CLOSE_FRIDGE, list('sound/machines/kitchen/fridge/close_fridge.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_FRIDGE_OPEN_FRIDGE, list('sound/machines/kitchen/fridge/open_fridge.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_FRYER_DEEP_FRYER_IMMERSE, list('sound/machines/kitchen/fryer/deep_fryer_immerse.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_GRILL_GRILL_START, list('sound/machines/kitchen/grill/grill-start.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_MICROWAVE_MICROWAVE_END, list('sound/machines/kitchen/microwave/microwave-end.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_MICROWAVE_MICROWAVE_MID2, list('sound/machines/kitchen/microwave/microwave-mid2.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_MICROWAVE_MICROWAVE_START, list('sound/machines/kitchen/microwave/microwave-start.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_MIXER_MIXER_START, list('sound/machines/kitchen/mixer/mixer-start.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_KITCHEN_OVEN_OVEN_START, list('sound/machines/kitchen/oven/oven-start.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_LOCKENABLE, list('sound/machines/lockenable.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_LOCKRESET, list('sound/machines/lockreset.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_MACHINE_DIE_SHORT, list('sound/machines/machine_die_short.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_MEDBAYSCANNER1, list('sound/machines/medbayscanner1.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_PDA_CLICK, list('sound/machines/pda_click.ogg'), 20, FALSE)
	SOUND_SET(SFX_MACHINES_PING, list('sound/machines/ping.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_PRINTER, list('sound/machines/printer.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_QUIET_BEEP, list('sound/machines/quiet_beep.ogg'), 40, FALSE)
	SOUND_SET(SFX_MACHINES_REAGENT_DISPENSE, list('sound/machines/reagent_dispense.ogg'), 25, TRUE)
	SOUND_SET(SFX_MACHINES_RIG_RIGDOWN, list('sound/machines/rig/rigdown.ogg'), 60, FALSE)
	SOUND_SET(SFX_MACHINES_RIG_RIGERROR, list('sound/machines/rig/rigerror.ogg'), 20, FALSE)
	SOUND_SET(SFX_MACHINES_RIG_RIGSERVO, list('sound/machines/rig/rigservo.ogg'), 10, FALSE)
	SOUND_SET(SFX_MACHINES_RIG_RIGSTARTED, list('sound/machines/rig/rigstarted.ogg'), 10, FALSE)
	SOUND_SET(SFX_MACHINES_ROULETTE, list('sound/machines/roulette.ogg'), 40, TRUE)
	SOUND_SET(SFX_MACHINES_SHIELD_HUM_SHIELD_GENERATOR_WHIR, list('sound/machines/shield_hum/shield_generator_whir.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_SHOWER_SHOWER_START, list('sound/machines/shower/shower_start.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_SHUTDOWN, list('sound/machines/shutdown.ogg'), 60, TRUE)
	SOUND_SET(SFX_MACHINES_SLOTMACHINE, list('sound/machines/slotmachine.ogg'), 25, TRUE)
	SOUND_SET(SFX_MACHINES_SLOTMACHINE_PULL, list('sound/machines/slotmachine_pull.ogg'), 15, TRUE)
	SOUND_SET(SFX_MACHINES_SYNTH_ALERT, list('sound/machines/synth_alert.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_SYNTH_NO, list('sound/machines/synth_no.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_SYNTH_YES, list('sound/machines/synth_yes.ogg'), 50, FALSE)
	SOUND_SET(SFX_MACHINES_TCOMMS_TCOMMS_PULSE, list('sound/machines/tcomms/tcomms_pulse.ogg'), 70, TRUE, 30, null)
	SOUND_SET(SFX_MACHINES_TERMINAL_ALERT, list('sound/machines/terminal_alert.ogg'), 150, FALSE)
	SOUND_SET(SFX_MACHINES_TERMINAL_OFF, list('sound/machines/terminal_off.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_TERMINAL_ON, list('sound/machines/terminal_on.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_TERMINAL_PROMPT_CONFIRM, list('sound/machines/terminal_prompt_confirm.ogg'), 25, FALSE)
	SOUND_SET(SFX_MACHINES_THRUSTER, list('sound/machines/thruster.ogg'), 50, FALSE, 0, 0.1)
	SOUND_SET(SFX_MACHINES_TURRETS_TURRET_DEPLOY, list('sound/machines/turrets/turret_deploy.ogg'), 100, TRUE)
	SOUND_SET(SFX_MACHINES_TURRETS_TURRET_RETRACT, list('sound/machines/turrets/turret_retract.ogg'), 100, TRUE)
	SOUND_SET(SFX_MACHINES_TURRETS_TURRET_ROTATE, list('sound/machines/turrets/turret_rotate.ogg'), 100, TRUE)
	SOUND_SET(SFX_MACHINES_TWOBEEP, list('sound/machines/twobeep.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_VEHICLE_ENGINE_START, list('sound/machines/vehicle/engine_start.ogg'), 50, TRUE)
	SOUND_SET(SFX_MACHINES_VENDING_VENDING_DROP, list('sound/machines/vending/vending_drop.ogg'), 100, TRUE)
	SOUND_SET(SFX_MACHINES_VENTCRAWL, list('sound/machines/ventcrawl.ogg'), 50, TRUE, -3, null)
	SOUND_SET(SFX_MACHINES_WARNING_BUZZER, list('sound/machines/warning-buzzer.ogg'), 50, FALSE)
	SOUND_SET(SFX_MAGIC_FIREBALL, list('sound/magic/Fireball.ogg'), 100, TRUE)
	SOUND_SET(SFX_MECHA_BIGMECH_LSTEP, list('sound/mecha/bigmech_lstep.ogg'), 40, TRUE)
	SOUND_SET(SFX_MECHA_BIGMECH_LTURN, list('sound/mecha/bigmech_lturn.ogg'), 40, TRUE)
	SOUND_SET(SFX_MECHA_BIGMECH_RSTEP, list('sound/mecha/bigmech_rstep.ogg'), 40, TRUE)
	SOUND_SET(SFX_MECHA_BIGMECH_RTURN, list('sound/mecha/bigmech_rturn.ogg'), 40, TRUE)
	SOUND_SET(SFX_MECHA_DURANDDEFENCEMODE, list('sound/mecha/duranddefencemode.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_FIGHTER_ENGINE_MID_BOOST_01, list('sound/mecha/fighter/engine_mid_boost_01.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_FIGHTER_FIGHTER_COLLISION, list('sound/mecha/fighter/fighter_collision.ogg'), 50, FALSE)
	SOUND_SET(SFX_MECHA_GASCONNECTED, list('sound/mecha/gasconnected.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_GASDISCONNECTED, list('sound/mecha/gasdisconnected.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_HEAVYLIGHTSWITCH, list('sound/mecha/heavylightswitch.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_HYDRAULIC, list('sound/mecha/hydraulic.ogg'), 10, TRUE, -2, null)
	SOUND_SET(SFX_MECHA_MECHANICAL_TOGGLE, list('sound/mecha/mechanical_toggle.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_MECHDRILL, list('sound/mecha/mechdrill.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_MECHMOVE01, list('sound/mecha/mechmove01.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_MECHMOVE03, list('sound/mecha/mechmove03.ogg'), 40, TRUE)
	SOUND_SET(SFX_MECHA_MECHMOVE04, list('sound/mecha/mechmove04.ogg'), 40, TRUE)
	SOUND_SET(SFX_MECHA_MECHSTEP, list('sound/mecha/mechstep.ogg'), 20, TRUE)
	SOUND_SET(SFX_MECHA_MECHSTEP2, list('sound/mecha/mechstep2.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_MECHTURN, list('sound/mecha/mechturn.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_MECH_RELOAD_DEFAULT, list('sound/mecha/mech_reload_default.ogg'), 50, TRUE)
	SOUND_SET(SFX_MECHA_MECH_SHIELD_RAISE, list('sound/mecha/mech_shield_raise.ogg'), 20, TRUE)
	SOUND_SET(SFX_MECHA_NOMINALSYNDI, list('sound/mecha/nominalsyndi.ogg'), 75, FALSE)
	SOUND_SET(SFX_MECHA_POWERUP, list('sound/mecha/powerup.ogg'), 30, TRUE)
	SOUND_SET(SFX_METROID_METROIDATTACH, list('sound/metroid/metroidattach.ogg'), 50, TRUE)
	SOUND_SET(SFX_METROID_METROIDATTACK, list('sound/metroid/metroidattack.ogg'), 100, TRUE)
	SOUND_SET(SFX_METROID_METROIDDEATH, list('sound/metroid/metroiddeath.ogg'), 100, TRUE)
	SOUND_SET(SFX_METROID_METROIDDETACH, list('sound/metroid/metroiddetach.ogg'), 50, TRUE)
	SOUND_SET(SFX_METROID_METROIDGAMMA, list('sound/metroid/metroidgamma.ogg'), 100, TRUE)
	SOUND_SET(SFX_METROID_METROIDGROW, list('sound/metroid/metroidgrow.ogg'), 50, TRUE)
	SOUND_SET(SFX_METROID_METROIDOMEGA, list('sound/metroid/metroidomega.ogg'), 100, TRUE)
	SOUND_SET(SFX_METROID_METROIDOMEGADEATH, list('sound/metroid/metroidomegadeath.ogg'), 50, TRUE)
	SOUND_SET(SFX_METROID_METROIDQUEEN, list('sound/metroid/metroidqueen.ogg'), 100, TRUE)
	SOUND_SET(SFX_METROID_METROIDQUEENDEATH, list('sound/metroid/metroidqueendeath.ogg'), 50, TRUE)
	SOUND_SET(SFX_METROID_METROIDSEE, list('sound/metroid/metroidsee.ogg'), 100, TRUE)
	SOUND_SET(SFX_METROID_METROIDZETA, list('sound/metroid/metroidzeta.ogg'), 100, TRUE)
	SOUND_SET(SFX_MISC_BLOOP, list('sound/misc/bloop.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_BOATSWAIN, list('sound/misc/boatswain.ogg'), 20, TRUE)
	SOUND_SET(SFX_MISC_CLAP_MIX, list('sound/misc/clap1.ogg', 'sound/misc/clap2.ogg', 'sound/misc/clap3.ogg', 'sound/misc/clap4.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_DEMONATTACK, list('sound/misc/demonattack.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_DEMONDEATH, list('sound/misc/demondeath.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_DEMONLAUGH, list('sound/misc/demonlaugh.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_INTERFERENCE, list('sound/misc/interference.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_LEGODEATH, list('sound/misc/legodeath.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_NOTICE3, list('sound/misc/notice3.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_NULL, list('sound/misc/null.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_NYMPHCHIRP, list('sound/misc/nymphchirp.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_SADTROMBONE, list('sound/misc/sadtrombone.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_SADTROMBONE_MIX, list('sound/misc/sadtrombone.ogg', 'sound/items/bikehorn.ogg', 'sound/effects/clownstep1.ogg', 'sound/effects/clownstep2.ogg'), 50, TRUE)
	SOUND_SET(SFX_MISC_SERVER_READY, list('sound/misc/server-ready.ogg'), 100, FALSE)
	SOUND_SET(SFX_MISC_SLIP, list('sound/misc/slip.ogg'), 25, TRUE, -1, null)
	SOUND_SET(SFX_MOB_ROBOTS_CYBER_HORROR_CHANGELINGLEAP, list('sound/mob/robots/cyber_horror_changelingleap.ogg'), 50, TRUE)
	SOUND_SET(SFX_MOB_ROBOTS_CYBER_HORROR_CHANGELINGMELEE, list('sound/mob/robots/cyber_horror_changelingmelee.ogg'), 50, TRUE)
	SOUND_SET(SFX_MOB_SPOOKY_BREATH1, list('sound/mob/spooky/breath1.ogg'), 50, TRUE)
	SOUND_SET(SFX_MOB_SPOOKY_BREATH2, list('sound/mob/spooky/breath2.ogg'), 50, TRUE)
	SOUND_SET(SFX_MOB_SPOOKY_LAUGH, list('sound/mob/spooky/laugh.ogg'), 50, TRUE)
	SOUND_SET(SFX_MOB_SPOOKY_NO, list('sound/mob/spooky/no.ogg'), 50, TRUE)
	SOUND_SET(SFX_RAKSHASA_CORROSION3, list('sound/rakshasa/Corrosion3.ogg'), 50, TRUE, -1, null)
	SOUND_SET(SFX_RAKSHASA_DECAY1, list('sound/rakshasa/Decay1.ogg'), 75, TRUE)
	SOUND_SET(SFX_RAKSHASA_DECAY3, list('sound/rakshasa/Decay3.ogg'), 100, TRUE)
	SOUND_SET(SFX_RECYCLER_A_WONDERFUL_THROW, list('code/modules/maint_recycler/sfx/voice/a wonderful throw.ogg'), 75, FALSE)
	SOUND_SET(SFX_RECYCLER_DENIED, list('code/modules/maint_recycler/sfx/voice/mad/denied.ogg'), 75, FALSE)
	SOUND_SET(SFX_RECYCLER_DENIED_MIX, list('code/modules/maint_recycler/sfx/voice/mad/denied.ogg', 'code/modules/maint_recycler/sfx/voice/mad/die die die die.ogg', 'code/modules/maint_recycler/sfx/voice/mad/this will not stand.ogg'), 50, TRUE)
	SOUND_SET(SFX_RECYCLER_EJECTGOODIES, list('code/modules/maint_recycler/sfx/ejectgoodies.ogg'), 75, TRUE)
	SOUND_SET(SFX_RECYCLER_GENERALDENY, list('code/modules/maint_recycler/sfx/generaldeny.ogg'), 75, TRUE)
	SOUND_SET(SFX_RECYCLER_HATCHCLOSE, list('code/modules/maint_recycler/sfx/hatchclose.ogg'), 40, TRUE)
	SOUND_SET(SFX_RECYCLER_HATCHOPEN, list('code/modules/maint_recycler/sfx/hatchopen.ogg'), 40, TRUE)
	SOUND_SET(SFX_RECYCLER_INITIALBOOT, list('code/modules/maint_recycler/sfx/initialBoot.ogg'), 20, TRUE)
	SOUND_SET(SFX_RECYCLER_KACHING, list('code/modules/maint_recycler/sfx/goodies/kaching.ogg'), 50, TRUE)
	SOUND_SET(SFX_RECYCLER_RECYCLE_ACT, list('code/modules/maint_recycler/sfx/recycle_act.ogg'), 50, FALSE)
	SOUND_SET(SFX_RECYCLER_TYPING, list('code/modules/maint_recycler/sfx/typing.ogg'), 50, TRUE)
	SOUND_SET(SFX_RUNTIME_INSTRUMENTS_SAXOPHONE_EN4, list('sound/runtime/instruments/saxophone/En4.mid'), 100, TRUE, -1, null)
	SOUND_SET(SFX_RUNTIME_INSTRUMENTS_TROMBONE_CN4, list('sound/runtime/instruments/trombone/Cn4.mid'), 100, TRUE, -1, null)
	SOUND_SET(SFX_RUNTIME_INSTRUMENTS_TROMBONE_EN4, list('sound/runtime/instruments/trombone/En4.mid'), 100, TRUE, -1, null)
	SOUND_SET(SFX_TALKSOUNDS_EMOTE, list('sound/talksounds/me_a.ogg', 'sound/talksounds/me_b.ogg', 'sound/talksounds/me_c.ogg', 'sound/talksounds/me_d.ogg', 'sound/talksounds/me_e.ogg', 'sound/talksounds/me_f.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_AWOO, list('sound/voice/awoo.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BAA, list('sound/voice/baa.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BAA2, list('sound/voice/baa2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BARK2, list('sound/voice/bark2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BCREEP, list('sound/voice/bcreep.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BCRIMINAL, list('sound/voice/bcriminal.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BCRIMINAL_MIX, list('sound/voice/bcriminal.ogg', 'sound/voice/bjustice.ogg', 'sound/voice/bfreeze.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BFREEZE, list('sound/voice/bfreeze.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BGOD, list('sound/voice/bgod.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BGOD_MIX, list('sound/voice/bgod.ogg', 'sound/voice/biamthelaw.ogg', 'sound/voice/bsecureday.ogg', 'sound/voice/bradio.ogg', 'sound/voice/bcreep.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BIAMTHELAW, list('sound/voice/biamthelaw.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BIAMTHELAW_MIX, list('sound/voice/biamthelaw.ogg', 'sound/voice/bradio.ogg', 'sound/voice/bjustice.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BINSULT, list('sound/voice/binsult.ogg'), 100, FALSE)
	SOUND_SET(SFX_VOICE_BORG_DEATHSOUND, list('sound/voice/borg_deathsound.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BORK, list('sound/voice/bork.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BRADIO, list('sound/voice/bradio.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BSECUREDAY, list('sound/voice/bsecureday.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BUG, list('sound/voice/bug.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BUGBUZZ, list('sound/voice/bugbuzz.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_BUGHISS, list('sound/voice/bughiss.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_CAT_PURR, list('sound/voice/cat_purr.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_CAT_PURR_LONG, list('sound/voice/cat_purr_long.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_COYOTEAWOO, list('sound/voice/coyoteawoo.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_COYOTEAWOO2, list('sound/voice/coyoteawoo2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_COYOTEAWOO3, list('sound/voice/coyoteawoo3.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_COYOTEAWOO4, list('sound/voice/coyoteawoo4.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_COYOTEAWOO5, list('sound/voice/coyoteawoo5.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_CROAK_FROG, list('sound/voice/croak_frog.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_CROAK_SKRELL, list('sound/voice/croak_skrell.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_CROON_MIX, list('sound/voice/croon1.ogg', 'sound/voice/croon2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_CAW1, list('sound/voice/emotes/caw1.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_CAW2, list('sound/voice/emotes/caw2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_CAW_MULTIPLE, list('sound/voice/emotes/caw_multiple.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_GWAH, list('sound/voice/emotes/gwah.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_SQUEALEMOTE, list('sound/voice/emotes/squealemote.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_TAILTHUMPEMOTE, list('sound/voice/emotes/tailthumpemote.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_WAWA, list('sound/voice/emotes/wawa.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_XENOGROWL, list('sound/voice/emotes/xenogrowl.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_XENOHISS, list('sound/voice/emotes/xenohiss.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_XENOPURR, list('sound/voice/emotes/xenopurr.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_EMOTES_YIP_MIX, list('sound/voice/emotes/yip1.ogg', 'sound/voice/emotes/yip2.ogg', 'sound/voice/emotes/yip3.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_FERRETDOOK, list('sound/voice/ferretdook.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_GAO, list('sound/voice/gao.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_GECK, list('sound/voice/geck.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_GROWL, list('sound/voice/growl.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_HALT, list('sound/voice/halt.ogg'), 100, FALSE)
	SOUND_SET(SFX_VOICE_HISS, list('sound/voice/hiss.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_HISS1, list('sound/voice/hiss1.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_HISS5, list('sound/voice/hiss5.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_HISS6, list('sound/voice/hiss6.ogg'), 100, TRUE)
	SOUND_SET(SFX_VOICE_HOOT, list('sound/voice/hoot.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_HYPNO, list('sound/voice/hypno.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_KNUCKLES, list('sound/voice/knuckles.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_LIVEAGAIN, list('sound/voice/liveagain.ogg'), 75, TRUE)
	SOUND_SET(SFX_VOICE_LONGWHISTLE, list('sound/voice/longwhistle.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_LONG_AWOO, list('sound/voice/long_awoo.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_LWARBLE, list('sound/voice/lwarble.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MALESCREAM_2, list('sound/voice/malescream_2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MAR, list('sound/voice/mar.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_DONT_LIKE, list('sound/voice/medbot/dont_like.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_FORGIVE, list('sound/voice/medbot/forgive.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_FUCK_YOU, list('sound/voice/medbot/fuck_you.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_HEY_WAIT, list('sound/voice/medbot/hey_wait.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_IS_THIS_THE_END, list('sound/voice/medbot/is_this_the_end.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_I_REQUIRE_ASST, list('sound/voice/medbot/i_require_asst.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_I_TRUSTED_YOU, list('sound/voice/medbot/i_trusted_you.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MAPPLE, list('sound/voice/medbot/mapple.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MCATCH, list('sound/voice/medbot/mcatch.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MCOMING, list('sound/voice/medbot/mcoming.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MDELICIOUS, list('sound/voice/medbot/mdelicious.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MFEELBETTER, list('sound/voice/medbot/mfeelbetter.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MFLIES, list('sound/voice/medbot/mflies.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MHELP, list('sound/voice/medbot/mhelp.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MINJURED, list('sound/voice/medbot/minjured.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MINSULT, list('sound/voice/medbot/minsult.ogg'), 50, FALSE)
	SOUND_SET(SFX_VOICE_MEDBOT_MLIVE, list('sound/voice/medbot/mlive.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MLOST, list('sound/voice/medbot/mlost.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MNO, list('sound/voice/medbot/mno.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MPATCHEDUP, list('sound/voice/medbot/mpatchedup.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MRADAR, list('sound/voice/medbot/mradar.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_MSURGEON, list('sound/voice/medbot/msurgeon.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_NOOO, list('sound/voice/medbot/nooo.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_OH_FUCK, list('sound/voice/medbot/oh_fuck.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_PAIN_IS_REAL, list('sound/voice/medbot/pain_is_real.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_PLEASE_DONT, list('sound/voice/medbot/please_dont.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_PLEASE_IM_SCARED, list('sound/voice/medbot/please_im_scared.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_PLEASE_PUT_ME_BACK, list('sound/voice/medbot/please_put_me_back.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_REPORTED, list('sound/voice/medbot/reported.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_THANK_YOU, list('sound/voice/medbot/thank_you.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEDBOT_YOURE_GOOD, list('sound/voice/medbot/youre_good.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MEOW, list('sound/voice/meow.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MERP, list('sound/voice/merp.ogg'), 20, FALSE)
	SOUND_SET(SFX_VOICE_MGEOW, list('sound/voice/mgeow.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MOO, list('sound/voice/moo.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MOTH_MOTH_CHITTER, list('sound/voice/moth/moth_chitter.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MOTH_MOTH_LAUGH, list('sound/voice/moth/moth_laugh.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MOTH_SCREAM_MOTH, list('sound/voice/moth/scream_moth.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MROW, list('sound/voice/mrow.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MULTICHIRP, list('sound/voice/multichirp.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_MYARP, list('sound/voice/myarp.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_NYA, list('sound/voice/nya.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_PAIN_SCIENTIST_SCI_PAIN_MIX, list('sound/voice/pain/scientist/sci_pain1.ogg', 'sound/voice/pain/scientist/sci_pain4.ogg', 'sound/voice/pain/scientist/sci_pain5.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_PEEP, list('sound/voice/peep.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_PRBT, list('sound/voice/prbt.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_PRBT2, list('sound/voice/prbt2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_QUACK, list('sound/voice/quack.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_QUACK_REVERB, list('sound/voice/quack_reverb.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_RATTLE, list('sound/voice/rattle.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_ROARBARK, list('sound/voice/roarbark.ogg'), 20, FALSE)
	SOUND_SET(SFX_VOICE_ROBOBOOP, list('sound/voice/roboboop.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_ROBOCHIRP, list('sound/voice/robochirp.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SCAWWYSOWNDS, list('sound/voice/scawwysownds/a_scawey_sownd.ogg', 'sound/voice/scawwysownds/is_that_you.ogg', 'sound/voice/scawwysownds/lookit_this_darkness_wow.ogg', 'sound/voice/scawwysownds/maint_preds.ogg', 'sound/voice/scawwysownds/spooky_sounds.ogg', 'sound/voice/scawwysownds/sus.ogg', 'sound/voice/scawwysownds/this_is_scaewy.ogg', 'sound/voice/scawwysownds/what_is_that_behind_you.ogg', 'sound/voice/scawwysownds/what_you_doin_over_dere.ogg', 'sound/voice/scawwysownds/whats_up_with_all_the_trash.ogg', 'sound/voice/scawwysownds/youre_afraid_of_the_dark_arent_you.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SCREAM_JELLY_M1, list('sound/voice/scream_jelly_m1.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SCREAM_MOTH_MOTH_SCREAM, list('sound/voice/scream/moth/moth_scream.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SCREAM_SCIENTIST_SCREAM_MIX, list('sound/voice/scream/scientist/scream01.ogg', 'sound/voice/scream/scientist/scream02.ogg', 'sound/voice/scream/scientist/scream06.ogg', 'sound/voice/scream/scientist/scream08.ogg', 'sound/voice/scream/scientist/scream25.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SHORTWHISTLE, list('sound/voice/shortwhistle.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SHRIEK1, list('sound/voice/shriek1.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SNORT, list('sound/voice/snort.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SPIDERCHITTER, list('sound/voice/spiderchitter.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SPIDERPURR, list('sound/voice/spiderpurr.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_SUCCLET_SHRIEK, list('sound/voice/succlet_shriek.ogg'), 100, TRUE)
	SOUND_SET(SFX_VOICE_SUMMON_WHISTLE, list('sound/voice/summon_whistle.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_TEPPI, list('sound/voice/teppi/gyooh1.ogg', 'sound/voice/teppi/gyooh2.ogg', 'sound/voice/teppi/gyooh3.ogg', 'sound/voice/teppi/gyooh4.ogg', 'sound/voice/teppi/gyooh5.ogg', 'sound/voice/teppi/gyooh6.ogg', 'sound/voice/teppi/snoot1.ogg', 'sound/voice/teppi/snoot2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_TEPPI_CUTE_RUMBLE, list('sound/voice/teppi/cute_rumble.ogg'), 75, TRUE)
	SOUND_SET(SFX_VOICE_TEPPI_ROAR, list('sound/voice/teppi/roar.ogg'), 10, FALSE)
	SOUND_SET(SFX_VOICE_TEPPI_RUMBLE, list('sound/voice/teppi/rumble.ogg'), 75, TRUE)
	SOUND_SET(SFX_VOICE_TEPPI_WHINE1, list('sound/voice/teppi/whine1.ogg'), 75, TRUE)
	SOUND_SET(SFX_VOICE_TEPPI_WHINE2, list('sound/voice/teppi/whine2.ogg'), 75, TRUE)
	SOUND_SET(SFX_VOICE_TEPPI_WHINE_MIX, list('sound/voice/teppi/whine1.ogg', 'sound/voice/teppi/whine2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_TESHCHIRP, list('sound/voice/teshchirp.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_TESHSCREAM, list('sound/voice/teshscream.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_TESHSQUEAK, list('sound/voice/teshsqueak.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_TESHTRILL, list('sound/voice/teshtrill.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_TINYTIN_FUCKEDUP, list('sound/voice/tinytin_fuckedup.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_WEH, list('sound/voice/weh.ogg'), 20, FALSE)
	SOUND_SET(SFX_VOICE_WHEEZE, list('sound/voice/wheeze.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_WOLFWHISTLE, list('sound/voice/wolfwhistle.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_WOOF, list('sound/voice/woof.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_WOOF2, list('sound/voice/woof2.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_WURBLE, list('sound/voice/wurble.ogg'), 50, TRUE)
	SOUND_SET(SFX_VOICE_YEENCACKLE, list('sound/voice/yeencackle.ogg'), 50, TRUE)
	SOUND_SET(SFX_VORE_DEATH7, list('sound/vore/death7.ogg'), 50, TRUE)
	SOUND_SET(SFX_VORE_GULP, list('sound/vore/gulp.ogg'), 50, TRUE)
	SOUND_SET(SFX_VORE_INSERT, list('sound/vore/insert.ogg'), 50, TRUE)
	SOUND_SET(SFX_VORE_SCHLORP, list('sound/vore/schlorp.ogg'), 100, FALSE)
	SOUND_SET(SFX_VORE_SHORTGURGLES_GURGLE_L_MIX, list('sound/vore/shortgurgles/gurgle_l1.ogg', 'sound/vore/shortgurgles/gurgle_l2.ogg', 'sound/vore/shortgurgles/gurgle_l3.ogg'), 50, TRUE)
	SOUND_SET(SFX_VORE_SHORTGURGLES_GURGLE_M_MIX, list('sound/vore/shortgurgles/gurgle_m1.ogg', 'sound/vore/shortgurgles/gurgle_m2.ogg', 'sound/vore/shortgurgles/gurgle_m3.ogg'), 50, TRUE)
	SOUND_SET(SFX_VORE_SHORTGURGLES_GURGLE_S_MIX, list('sound/vore/shortgurgles/gurgle_s1.ogg', 'sound/vore/shortgurgles/gurgle_s2.ogg', 'sound/vore/shortgurgles/gurgle_s3.ogg'), 50, TRUE)
	SOUND_SET(SFX_VORE_SQUISH1, list('sound/vore/squish1.ogg'), 50, TRUE)
	SOUND_SET(SFX_VORE_SUNESOUND_PRED_INSERTION_01, list('sound/vore/sunesound/pred/insertion_01.ogg'), 50, TRUE)
	SOUND_SET(SFX_VORE_SUNESOUND_PRED_SCHLORP, list('sound/vore/sunesound/pred/schlorp.ogg'), 25, FALSE)
	SOUND_SET(SFX_WEAPONS_45PISTOL_VR, list('sound/weapons/45pistol_vr.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_ALIEN_CLAW_FLESH, list('sound/weapons/alien_claw_flesh.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_ALIEN_SPITACID, list('sound/weapons/alien_spitacid.ogg'), 25, FALSE)
	SOUND_SET(SFX_WEAPONS_ARMBOMB, list('sound/weapons/armbomb.ogg'), 75, TRUE, -3, null)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_A12G, list('sound/weapons/ballistics/a12g.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_A145, list('sound/weapons/ballistics/a145.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_A44RIFLE, list('sound/weapons/ballistics/a44rifle.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_A45, list('sound/weapons/ballistics/a45.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_A545, list('sound/weapons/ballistics/a545.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_A762, list('sound/weapons/ballistics/a762.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_A762X54, list('sound/weapons/ballistics/a762x54.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_A9MM, list('sound/weapons/ballistics/a9mm.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_BOLTACTIONCLOSE, list('sound/weapons/ballistics/boltactionclose.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_BOLTACTIONOPEN, list('sound/weapons/ballistics/boltactionopen.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_PISTOL_CHAMBER, list('sound/weapons/ballistics/pistol_chamber.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_PISTOL_EJECT, list('sound/weapons/ballistics/pistol_eject.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_PISTOL_EJECTCHAMBER, list('sound/weapons/ballistics/pistol_ejectchamber.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_RIFLE_CHAMBER, list('sound/weapons/ballistics/rifle_chamber.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_RIFLE_EJECT, list('sound/weapons/ballistics/rifle_eject.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_RIFLE_EJECTCHAMBER, list('sound/weapons/ballistics/rifle_ejectchamber.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BALLISTICS_SMG_HEAVY, list('sound/weapons/ballistics/smg_heavy.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BANJOSLAP, list('sound/weapons/banjoslap.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BATTLERIFLE, list('sound/weapons/battlerifle.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BITE, list('sound/weapons/bite.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BLADE1, list('sound/weapons/blade1.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_BLADESLICE, list('sound/weapons/bladeslice.ogg'), 50, TRUE, -1, null)
	SOUND_SET(SFX_WEAPONS_BLASTER, list('sound/weapons/blaster.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_CABLECUFF, list('sound/weapons/cablecuff.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_CHAINSAW_ATTACK, list('sound/weapons/chainsaw_attack.ogg'), 40, TRUE)
	SOUND_SET(SFX_WEAPONS_CHAINSAW_STARTUP, list('sound/weapons/chainsaw_startup.ogg'), 10, FALSE)
	SOUND_SET(SFX_WEAPONS_CHAINSAW_TURNOFF, list('sound/weapons/chainsaw_turnoff.ogg'), 40, TRUE)
	SOUND_SET(SFX_WEAPONS_CHARGEUP, list('sound/weapons/chargeup.ogg'), 100, TRUE)
	SOUND_SET(SFX_WEAPONS_CIRCSAWHIT, list('sound/weapons/circsawhit.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_CLOCKWORK_CLOCKWORK_COCK, list('sound/weapons/clockwork/clockwork_cock.ogg'), 25, TRUE)
	SOUND_SET(SFX_WEAPONS_CLOCKWORK_CWC_RIFLE_FABRICATE, list('sound/weapons/clockwork/cwc_rifle_fabricate.ogg'), 25, TRUE)
	SOUND_SET(SFX_WEAPONS_CLOCKWORK_CWC_RIFLE_FIRE, list('sound/weapons/clockwork/cwc_rifle_fire.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_CLOCKWORK_VOLTBEAMSEARWALL, list('sound/weapons/clockwork/voltbeamsearwall.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_CLOCKWORK_VOLTBEAM_FIRE, list('sound/weapons/clockwork/voltbeam_fire.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_DODGEBALL, list('sound/weapons/dodgeball.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_DOOMPISTOL, list('sound/weapons/doompistol.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_EFFECTS_ALIEN_SPIT_WALL, list('sound/weapons/effects/alien_spit_wall.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_EFFECTS_SEARWALL, list('sound/weapons/effects/searwall.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_EGLOVES, list('sound/weapons/egloves.ogg'), 50, TRUE, -1, null)
	SOUND_SET(SFX_WEAPONS_ELUGER, list('sound/weapons/eLuger.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_EMITTER, list('sound/weapons/emitter.ogg'), 25, TRUE)
	SOUND_SET(SFX_WEAPONS_EMITTER2, list('sound/weapons/emitter2.ogg'), 25, TRUE, 3, 5)
	SOUND_SET(SFX_WEAPONS_EMPTY, list('sound/weapons/empty.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_ENERGY_LASER_STRONG, list('sound/weapons/energy/laser_strong.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_FLAMER, list('sound/weapons/Flamer.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_FLASH, list('sound/weapons/flash.ogg'), 100, TRUE)
	SOUND_SET(SFX_WEAPONS_FLIPBLADE, list('sound/weapons/flipblade.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_FRIGATE_TURRET_FRIGATE_TURRET_FIRE_MIX, list('sound/weapons/frigate_turret/frigate_turret_fire1.ogg', 'sound/weapons/frigate_turret/frigate_turret_fire2.ogg', 'sound/weapons/frigate_turret/frigate_turret_fire3.ogg', 'sound/weapons/frigate_turret/frigate_turret_fire4.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GARAND_PING, list('sound/weapons/garand_ping.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GAUSS_SHOOT, list('sound/weapons/gauss_shoot.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GENHIT, list('sound/weapons/genhit.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GENHIT1, list('sound/weapons/genhit1.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GENHIT3, list('sound/weapons/genhit3.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GRENADE_LAUNCHER, list('sound/weapons/grenade_launcher.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT1, list('sound/weapons/gunshot1.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT2, list('sound/weapons/gunshot2.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT3, list('sound/weapons/gunshot3.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT4, list('sound/weapons/gunshot4.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_CANNON, list('sound/weapons/gunshot_cannon.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_DEAGLE, list('sound/weapons/gunshot_deagle.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_GENERIC_RIFLE, list('sound/weapons/gunshot_generic_rifle.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_HEAVY, list('sound/weapons/gunshot_heavy.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_LIGHT, list('sound/weapons/gunshot_light.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_MACHINEGUN, list('sound/weapons/gunshot_machinegun.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_OLD, list('sound/weapons/gunshot_old.ogg'), 100, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_PATHETIC, list('sound/weapons/gunshot_pathetic.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_SHOTGUN, list('sound/weapons/gunshot_shotgun.ogg'), 20, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_SNIPER, list('sound/weapons/gunshot_sniper.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_GUNSHOT_SVD, list('sound/weapons/gunshot_svd.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_HANDCUFFS, list('sound/weapons/handcuffs.ogg'), 30, TRUE, -3, null)
	SOUND_SET(SFX_WEAPONS_HEAVYSMASH, list('sound/weapons/heavysmash.ogg'), 75, TRUE)
	SOUND_SET(SFX_WEAPONS_HOLSTER_SHEATHIN, list('sound/weapons/holster/sheathin.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_HOLSTER_SHEATHOUT, list('sound/weapons/holster/sheathout.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_IONCANNON, list('sound/weapons/IonCannon.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_IONRIFLE, list('sound/weapons/ionrifle.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_KENETIC_ACCEL, list('sound/weapons/kenetic_accel.ogg'), 100, TRUE)
	SOUND_SET(SFX_WEAPONS_KENETIC_RELOAD, list('sound/weapons/kenetic_reload.ogg'), 60, TRUE)
	SOUND_SET(SFX_WEAPONS_LARGELASER, list('sound/weapons/LargeLaser.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_LASER, list('sound/weapons/Laser.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_LASER2, list('sound/weapons/laser2.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_LASER3, list('sound/weapons/laser3.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_LASER4, list('sound/weapons/laser4.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_LASER5, list('sound/weapons/laser5.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_LASERCANNONFIRE, list('sound/weapons/lasercannonfire.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_MANDALORIAN, list('sound/weapons/mandalorian.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_MARAUDER, list('sound/weapons/marauder.ogg'), 20, TRUE)
	SOUND_SET(SFX_WEAPONS_MARKSMANALT, list('sound/weapons/marksmanalt.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_MEDIUMLASER, list('sound/weapons/MediumLaser.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_MELEETEAR, list('sound/weapons/meleetear.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_MG42, list('sound/weapons/mg42.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PARRY, list('sound/weapons/parry.ogg'), 20, TRUE)
	SOUND_SET(SFX_WEAPONS_PHASE_NEW_PHASECANNON, list('sound/weapons/phase_new/phasecannon.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PHASE_NEW_PHASECARBINE, list('sound/weapons/phase_new/phasecarbine.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PHASE_NEW_PHASEPISTOL, list('sound/weapons/phase_new/phasepistol.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PHASE_NEW_PHASERIFLE, list('sound/weapons/phase_new/phaserifle.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PIERCE, list('sound/weapons/pierce.ogg'), 25, TRUE, -1, null)
	SOUND_SET(SFX_WEAPONS_PLASMANEW, list('sound/weapons/plasmaNEW.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PLASMA_CUTTER, list('sound/weapons/plasma_cutter.ogg'), 100, TRUE)
	SOUND_SET(SFX_WEAPONS_PULSE, list('sound/weapons/pulse.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PULSE3, list('sound/weapons/pulse3.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PUNCH1, list('sound/weapons/punch1.ogg'), 50, TRUE, -1, null)
	SOUND_SET(SFX_WEAPONS_PUNCH3, list('sound/weapons/punch3.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PUNCH4, list('sound/weapons/punch4.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_PUNCHMISS, list('sound/weapons/punchmiss.ogg'), 25, TRUE, -1, null)
	SOUND_SET(SFX_WEAPONS_RAILGUN, list('sound/weapons/railgun.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_RAPIDSLICE, list('sound/weapons/rapidslice.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_RESONATOR_BLAST, list('sound/weapons/resonator_blast.ogg'), 100, TRUE, -1, null)
	SOUND_SET(SFX_WEAPONS_RESONATOR_FIRE, list('sound/weapons/resonator_fire.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_REVOLVER_SPIN, list('sound/weapons/revolver_spin.ogg'), 100, TRUE)
	SOUND_SET(SFX_WEAPONS_RIFLEBOLT, list('sound/weapons/riflebolt.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_RING, list('sound/weapons/ring.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_RPG, list('sound/weapons/rpg.ogg'), 75, TRUE)
	SOUND_SET(SFX_WEAPONS_SABEROFF, list('sound/weapons/saberoff.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SABERON, list('sound/weapons/saberon.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SEAR, list('sound/weapons/sear.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SERDY_9MMPISTOL, list('sound/weapons/serdy/9mmpistol.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SERDY_AK74, list('sound/weapons/serdy/ak74.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SERDY_MOLNIYAB, list('sound/weapons/serdy/molniyab.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SERDY_SKS, list('sound/weapons/serdy/sks.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SERDY_STRELA, list('sound/weapons/serdy/strela.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SERDY_TYPE901, list('sound/weapons/serdy/type901.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SERDY_VEPR, list('sound/weapons/serdy/vepr.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SERDY_VITYAZ, list('sound/weapons/serdy/vityaz.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SHOTGUNPUMP, list('sound/weapons/shotgunpump.ogg'), 60, TRUE)
	SOUND_SET(SFX_WEAPONS_SLASH, list('sound/weapons/slash.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SLASHMISS, list('sound/weapons/slashmiss.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SLICE, list('sound/weapons/slice.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SMALLLASER, list('sound/weapons/smallLaser.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SMARTGUNCLOSE, list('sound/weapons/smartgunclose.ogg'), 75, FALSE)
	SOUND_SET(SFX_WEAPONS_SMARTGUNOPEN, list('sound/weapons/smartgunopen.ogg'), 75, FALSE)
	SOUND_SET(SFX_WEAPONS_SMASH, list('sound/weapons/smash.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SMG_EMPTY_ALARM, list('sound/weapons/smg_empty_alarm.ogg'), 40, FALSE)
	SOUND_SET(SFX_WEAPONS_SONIC_JACKHAMMER, list('sound/weapons/sonic_jackhammer.ogg'), 20, TRUE)
	SOUND_SET(SFX_WEAPONS_SPARKLE, list('sound/weapons/sparkle.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_SPIDERLUNGE, list('sound/weapons/spiderlunge.ogg'), 75, TRUE)
	SOUND_SET(SFX_WEAPONS_SRM, list('sound/weapons/SRM.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_STRINGSMASH, list('sound/weapons/stringsmash.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_TABLEHIT1, list('sound/weapons/tablehit1.ogg'), 25, TRUE, -1, null)
	SOUND_SET(SFX_WEAPONS_TAP, list('sound/weapons/tap.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_TARGETOFF, list('sound/weapons/targetoff.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_TARGETON, list('sound/weapons/targeton.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_TASER, list('sound/weapons/taser.ogg'), 30, TRUE)
	SOUND_SET(SFX_WEAPONS_TASER2, list('sound/weapons/taser2.ogg'), 75, TRUE)
	SOUND_SET(SFX_WEAPONS_THROWTAP, list('sound/weapons/throwtap.ogg'), 1, FALSE, -1, null)
	SOUND_SET(SFX_WEAPONS_THUDSWOOSH, list('sound/weapons/thudswoosh.ogg'), 50, TRUE, -1, null)
	SOUND_SET(SFX_WEAPONS_TOWELWHIP, list('sound/weapons/towelwhip.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_TOWELWIPE, list('sound/weapons/towelwipe.ogg'), 25, TRUE)
	SOUND_SET(SFX_WEAPONS_WAVE, list('sound/weapons/wave.ogg'), 60, FALSE)
	SOUND_SET(SFX_WEAPONS_WEAPONSOUNDS_HEAVYRIFLESHOT, list('sound/weapons/weaponsounds_heavyrifleshot.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_WEAPONSOUNDS_LASERMID, list('sound/weapons/weaponsounds_lasermid.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_WEAPONSOUNDS_LASERSTRONG, list('sound/weapons/weaponsounds_laserstrong.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_WEAPONSOUNDS_SHOTGUNSHOT, list('sound/weapons/weaponsounds_shotgunshot.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_WHIP, list('sound/weapons/whip.ogg'), 50, TRUE)
	SOUND_SET(SFX_WEAPONS_ZAPBANG, list('sound/weapons/zapbang.ogg'), 50, TRUE)
