
//---------- actual energy field

// Each field object has a strength var (mensured in "Renwicks").
// Melee weapons do 5% of their normal (force var) damage, so a harmbaton would do 0.75 Renwick.
// Projectiles do 5% of their structural damage, so a normal laser would do 2 Renwick damage.
// For meteors, one Renwick is about equal to one layer of r-wall.
// Meteors will be completely halted by the shield if the shield survives the impact.
// Explosions do 4 Renwick of damage per severity, at a max of 12.
//
// Strength is the field's integrity (damage.md §5), FIELD_INTEGRITY_PER_RENWICK
// integrity to the Renwick, so take_damage(x) costs the field x / 20 Renwicks.
// Below one Renwick the field drops (loses density); it is never destroyed,
// only regenerated by its generator.

#define FIELD_INTEGRITY_PER_RENWICK 20

/obj/effect/energy_field
	name = "energy shield field"
	desc = "Impenetrable field of energy, capable of blocking anything as long as it's active."
	icon = 'icons/obj/machines/shielding.dmi'
	icon_state = "shield"
	alpha = 100
	anchored = TRUE
	plane = MOB_PLANE
	layer = ABOVE_MOB_LAYER
	density = FALSE
	can_atmos_pass = ATMOS_PASS_DENSITY
	var/tmp/my_gen_handle
	var/ticks_recovering = 10
	uses_integrity = TRUE
	max_integrity = 10 * FIELD_INTEGRITY_PER_RENWICK
	resistance_flags = FIRE_PROOF | ACID_PROOF | LAVA_PROOF

/obj/effect/energy_field/Initialize(mapload, new_gen)
	. = ..()
	update_integrity(0) // Fields start down; the generator charges them.
	my_gen_handle = om_handle(new_gen)
	if(nearby_active_shield_diffuser(src))
		return INITIALIZE_HINT_QDEL
	update_nearby_tiles()

// Leaves its generator's field (a shield generator or a forcefield artifact).
DECLARE_REF(/obj/effect/energy_field, "my_gen_handle", BACKLIST_HANDLE, list(/obj/machinery/shield_gen = "field", /datum/artifact_effect/forcefield = "created_field"))

// Neighbouring fields redraw.
/obj/effect/energy_field/on_destroy(force)
	update_nearby_tiles()
	var/turf/current_loc = get_turf(src)
	..()
	for(var/direction in GLOB.cardinal)
		var/turf/T = get_step(current_loc, direction)
		if(T)
			for(var/obj/effect/energy_field/F in turf_contents_of_type(T, /obj/effect/energy_field))
				F.update_icon()

/obj/effect/energy_field/ex_act(severity)
	adjust_strength(-(4 - severity) * 4)

/obj/effect/energy_field/bullet_act(obj/item/projectile/Proj)
	adjust_strength(-Proj.get_structure_damage() / 10)

EXTEND_INTERACTIONS(/obj/effect/energy_field, \
	INTERACT_ITEM(null, PROC_REF(interaction_hit_energy_field)), \
	INTERACT_HAND_UNGATED(null, PROC_REF(interaction_touch_energy_field)), \
)

/// Old attackby: a forceful hit weakens the field; the item's normal handling carries on.
/obj/effect/energy_field/proc/interaction_hit_energy_field(mob/user, obj/item/held, datum/interaction/interaction)
	if(held.force)
		adjust_strength(-held.force / 20)
		user.do_attack_animation(src)
		user.setClickCooldown(user.get_attack_speed(held))
	return FALSE

/obj/effect/energy_field/attack_generic(mob/user, damage)
	if(damage)
		adjust_strength(-damage / 20)
		user.do_attack_animation(src)
		user.setClickCooldown(user.get_attack_speed())

/// Old attack_hand: harmless, but still produces the 'impact' effect; the touch carries on.
/obj/effect/energy_field/proc/interaction_touch_energy_field(mob/user, obj/item/held, datum/interaction/interaction)
	impact_effect(3)
	return FALSE

/obj/effect/energy_field/Bumped(atom/A)
	..(A)
	impact_effect(2)

/obj/effect/energy_field/handle_meteor_impact(obj/effect/meteor/meteor)
	var/penetrated = TRUE
	adjust_strength(-max((meteor.wall_power * meteor.hits) / 800, 0)) // One renwick (strength var) equals one r-wall for the purposes of meteor-stopping.
	if(density) // Check if we're still up.
		penetrated = FALSE
		explosion(meteor.loc, 0, 0, 0, 0, 0, 0, 0) // For the sound effect.

	// Returning FALSE will kill the meteor.
	return penetrated // If the shield's still around, the meteor was successfully stopped, otherwise keep going and plow into the station.

/// Field strength in Renwicks.
/obj/effect/energy_field/proc/get_strength()
	return get_integrity() / FIELD_INTEGRITY_PER_RENWICK

/obj/effect/energy_field/proc/set_strength(renwicks)
	update_integrity(clamp(renwicks * FIELD_INTEGRITY_PER_RENWICK, 0, max_integrity))

/obj/effect/energy_field/proc/set_max_strength(renwicks)
	max_integrity = renwicks * FIELD_INTEGRITY_PER_RENWICK
	if(get_integrity() > max_integrity)
		update_integrity(max_integrity)

/obj/effect/energy_field/proc/adjust_strength(amount, impact = 1)
	if(amount < 0) // Taking damage.
		if(impact)
			impact_effect(round(abs(amount * 2)))
		take_damage(-amount * FIELD_INTEGRITY_PER_RENWICK, BRUTE, null, FALSE)
	else if(amount > 0) // Healing damage.
		repair_damage(amount * FIELD_INTEGRITY_PER_RENWICK)

/obj/effect/energy_field/on_update_integrity(old_value, new_value)
	. = ..()
	var/old_density = density
	//if we take too much damage, drop out - the generator will bring us back up if we have enough power
	if(new_value < old_value)
		ticks_recovering = min(ticks_recovering + 2, 10)
		if(new_value < FIELD_INTEGRITY_PER_RENWICK) // We broke
			set_density(FALSE)
			ticks_recovering = 10
			if(new_value > 0)
				update_integrity(0)
	else if(new_value >= FIELD_INTEGRITY_PER_RENWICK)
		set_density(TRUE)

	if(density != old_density)
		update_icon()
		update_nearby_tiles()

/// A drained field stays up for its generator to recharge.
/obj/effect/energy_field/atom_destruction(damage_flag)
	SHOULD_CALL_PARENT(FALSE)
	return

DECLARE_APPEARANCE_PROC(/obj/effect/energy_field, PROC_REF(appearance_overlays), list(CHANGE_NEIGHBOURS))
/obj/effect/energy_field/appearance_overlays()
	. = list()
	var/list/adjacent_shields_dir = list()
	for(var/direction in GLOB.cardinal)
		var/turf/T = get_step(src, direction)
		if(T) // Incase we somehow stepped off the map.
			for(var/obj/effect/energy_field/F in turf_contents_of_type(T, /obj/effect/energy_field))
				adjacent_shields_dir |= direction
				break
	// Adjacent fields draw edges toward us: tell them when we appear, go down or come back.
	appearance_notify_neighbours("[density]|[x],[y],[z]", /obj/effect/energy_field)
	// Icon_state and Glow
	if(density)
		icon_state = "shield"
		set_light(3, 3, "#66FFFF")
	else
		icon_state = "shield_broken"
		set_light(3, 5, "#FF9900")

	// Edge overlays
	for(var/found_dir in adjacent_shields_dir)
		. += image(src.icon, src, icon_state = "shield_edge", dir = found_dir)

// Small visual effect, makes the shield tiles brighten up by becoming more opaque for a moment, and spreads to nearby shields.
/obj/effect/energy_field/proc/impact_effect(i, list/affected_shields = list())
	i = between(1, i, 10)
	alpha = 200
	animate(src, alpha = initial(alpha), time = 1 SECOND)
	affected_shields |= src
	i--
	if(i)
		om_after(src, 2, PROC_REF(spread_impact), i, affected_shields)

/obj/effect/energy_field/proc/spread_impact(i, list/affected_shields)
	for(var/direction in GLOB.cardinal)
		var/turf/T = get_step(src, direction)
		if(T) // Incase we somehow stepped off the map.
			for(var/obj/effect/energy_field/F in turf_contents_of_type(T, /obj/effect/energy_field))
				if(!(F in affected_shields))
					F.impact_effect(i, affected_shields) // Spread the effect to them.

#undef FIELD_INTEGRITY_PER_RENWICK

/// LC-refs: the my_gen this refers to -- an OM handle (om_handle()), so it reads null once that is deleted.
/obj/effect/energy_field/proc/my_gen() as /obj/machinery/shield_gen
	return om_resolve(my_gen_handle)
