// TGUI belly overlay.
//
// One datum per prey mob. Owns the `mapwindow.belly_overlay` BROWSER child
// element on that client and the React tree rendered inside it. The TGUI
// state schema is just: a list of layers, each with a single URL that
// points to a pre-built WebP/PNG generated by
// tools/build_belly_apngs/build.py. The browser plays animated WebPs
// natively, so we don't ship per-frame URLs or any animation timing.

/datum/belly_overlay_tgui
	var/mob/owner
	var/datum/tgui/active_ui
	var/list/state = list()

/datum/belly_overlay_tgui/New(mob/M)
	owner = M

/datum/belly_overlay_tgui/Destroy(force)
	if(owner?.client)
		winset(owner.client, "mapwindow.belly_overlay", "is-visible=false")
	owner = null
	active_ui = null
	return ..()

/datum/belly_overlay_tgui/tgui_state(mob/user)
	return GLOB.tgui_always_state

/datum/belly_overlay_tgui/ui_assets(mob/user)
	// Belly overlay files are registered + sent lazily via
	// dq_send_belly_overlay_urls() in show(), not as a static bundle.
	return list()

/datum/belly_overlay_tgui/tgui_data(mob/user)
	return state

/datum/belly_overlay_tgui/tgui_close(mob/user)
	hide()

/datum/belly_overlay_tgui/proc/open_window()
	if(!owner?.client)
		return
	var/client/C = owner.client
	winset(C, "mapwindow.belly_overlay", "is-visible=true;inner-background-color=#00000000")
	if(!active_ui)
		var/datum/tgui_window/win = new(C, "mapwindow.belly_overlay")
		active_ui = new /datum/tgui(owner, src, "BellyOverlay", "Belly Overlay", null, null, null, win)
		active_ui.open()

/datum/belly_overlay_tgui/proc/show(obj/belly/B, mob/prey)
	if(!owner?.client)
		return
	var/list/layers = list()
	if(B && B.belly_fullscreen)
		var/lookup_slug = lowertext(B.belly_fullscreen)
		var/datum/belly_overlays/lookup_path = text2path("/datum/belly_overlays/[lookup_slug]")
		var/icon/dmi = lookup_path ? initial(lookup_path.belly_icon) : null
		if(dmi)
			var/alpha = B.belly_fullscreen_alpha
			if(prey)
				alpha = min(alpha, prey.max_voreoverlay_alpha)
			var/list/states = list(
				list(B.belly_fullscreen,            B.belly_fullscreen_color),
				list("[B.belly_fullscreen]-2",      B.belly_fullscreen_color2),
				list("[B.belly_fullscreen]-3",      B.belly_fullscreen_color3),
				list("[B.belly_fullscreen]-4",      B.belly_fullscreen_color4),
			)
			for(var/list/pair in states)
				var/icon_state = pair[1]
				var/color = pair[2]
				var/url = dq_get_belly_overlay_url(dmi, icon_state)
				if(url)
					layers += list(list(
						"url"    = url,
						"color"  = color || "#ffffff",
						"alpha"  = alpha,
						"pixelY" = 0,
					))
			// Dynamic mush/liquid layers from bubbles.dmi. liquidbelly_visuals
			// is on /mob/living; pixel_y is driven by belly contents at
			// runtime — the React side applies the translate via CSS.
			var/mob/living/lp = prey
			if(istype(lp) && B.show_liquids && lp.liquidbelly_visuals)
				var/icon/bubbles = 'icons/mob/vore_fullscreens/bubbles.dmi'
				if(B.mush_overlay && (B.owner?.nutrition > 0 || B.max_mush == 0 || B.min_mush > 0 \
						|| (LAZYLEN(B.contents) * B.item_mush_val) > 0))
					var/mush_content = B.owner ? (B.owner.nutrition + LAZYLEN(B.contents) * B.item_mush_val) : 0
					var/mush_alpha = min(B.mush_alpha, prey.max_voreoverlay_alpha)
					var/pixel_y = -450 + (450 / max(B.max_mush, 1) * max(min(B.max_mush, mush_content), 1))
					if(pixel_y < -450 + (450 / 100 * B.min_mush))
						pixel_y = -450 + (450 / 100 * B.min_mush)
					var/mush_url = dq_get_belly_overlay_url(bubbles, "mush")
					if(mush_url)
						layers += list(list(
							"url"    = mush_url,
							"color"  = B.mush_color || "#ffffff",
							"alpha"  = mush_alpha,
							"pixelY" = pixel_y,
						))
				if(B.liquid_overlay && B.reagents?.total_volume)
					var/liquid_state = (B.digest_mode == DM_HOLD && B.item_digest_mode == IM_HOLD) ? "calm" : "bubbles"
					var/liquid_alpha = max(150, min(B.custom_max_volume, 255)) - (255 - alpha)
					if(B.custom_reagentalpha)
						liquid_alpha = B.custom_reagentalpha
					var/liquid_color = B.custom_reagentcolor || B.reagentcolor
					var/pixel_y = -450 + min((450 / max(B.custom_max_volume, 1) * B.reagents.total_volume), 450 / 100 * B.max_liquid_level)
					var/liquid_url = dq_get_belly_overlay_url(bubbles, liquid_state)
					if(liquid_url)
						layers += list(list(
							"url"    = liquid_url,
							"color"  = liquid_color || "#ffffff",
							"alpha"  = liquid_alpha,
							"pixelY" = pixel_y,
						))
			// Ship only the URLs we actually built into this layer set.
			// The transport's per-client dedupe makes repeated calls free.
			var/list/urls_to_send = list()
			for(var/list/L in layers)
				urls_to_send += L["url"]
			dq_send_belly_overlay_urls(owner.client, urls_to_send)
	state = list(
		"visible" = length(layers) > 0,
		"layers"  = layers,
	)
	open_window()
	if(active_ui)
		active_ui.send_update()

/datum/belly_overlay_tgui/proc/hide()
	// Don't tear down active_ui here — closing the tgui window means the
	// BROWSER reloads the entire bundle the next time we re-show, which
	// blanks for hundreds of ms. Just push an empty layer set so the React
	// side renders nothing, and hide the BROWSER widget. The window stays
	// alive in the background, ready to re-render the next belly instantly.
	state = list("visible" = FALSE, "layers" = list())
	if(active_ui)
		active_ui.send_update()
	if(owner?.client)
		winset(owner.client, "mapwindow.belly_overlay", "is-visible=false")

/proc/get_belly_overlay_tgui(mob/M)
	if(!M)
		return null
	if(!M.belly_overlay_tgui)
		M.belly_overlay_tgui = new /datum/belly_overlay_tgui(M)
	return M.belly_overlay_tgui

/mob
	var/datum/belly_overlay_tgui/belly_overlay_tgui

/mob/Destroy()
	if(belly_overlay_tgui)
		qdel(belly_overlay_tgui)
		belly_overlay_tgui = null
	return ..()
