// GENERATED by tools/ci/init_table_candidates.py --write. Do not edit by hand.
// Types whose whole Initialize() chain is table-expressible (doc/rewrite/init_and_turfs.md
// sec 3.1): SSatoms.InitAtom() runs table_initialize() instead of the proc chain.
// A type that gains an Initialize() override fails the init lint
// (`table_init_overrides`); rerun the tool to drop it from this list.

/obj/effect/abstract/light_spot
	init_from_table = TRUE

/obj/effect/ant_structure
	init_from_table = TRUE

/obj/effect/begin
	init_from_table = TRUE

/obj/effect/blocker
	init_from_table = TRUE

/obj/effect/bmode
	init_from_table = TRUE

/obj/effect/bump_teleporter
	init_from_table = TRUE

/obj/effect/ceiling
	init_from_table = TRUE

/obj/effect/dead_plant
	init_from_table = TRUE

/obj/effect/debugging/marker
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/allure
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/baron
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/gorilla
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/gunpod
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/hades
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/hoverpod
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/janus
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/marauder
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/mauler
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/micro
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/phazon
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/pinnace
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/scarab
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/scoralis
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/seraph
	init_from_table = TRUE

/obj/effect/decal/mecha_wreckage/shuttlecraft
	init_from_table = TRUE

/obj/effect/decal/remains
	init_from_table = TRUE

/obj/effect/decal/spraystill
	init_from_table = TRUE

/obj/effect/dog_nose
	init_from_table = TRUE

/obj/effect/dummy/chameleon
	init_from_table = TRUE

/obj/effect/ebeam/deadly
	init_from_table = TRUE

/obj/effect/ebeam/hose
	init_from_table = TRUE

/obj/effect/effect/ion_trails
	init_from_table = TRUE

/obj/effect/effect/snow
	init_from_table = TRUE

/obj/effect/effect/steam
	init_from_table = TRUE

/obj/effect/engine_setup
	init_from_table = TRUE

/obj/effect/extraction_holder
	init_from_table = TRUE

/obj/effect/floormimic
	init_from_table = TRUE

/obj/effect/forcefield
	init_from_table = TRUE

/obj/effect/fusion_particle_catcher
	init_from_table = TRUE

/obj/effect/hoist_hook
	init_from_table = TRUE

/obj/effect/immovablerod
	init_from_table = TRUE

/obj/effect/laser
	init_from_table = TRUE

/obj/effect/map_effect/perma_light
	init_from_table = TRUE

/obj/effect/map_effect/portal/line
	init_from_table = TRUE

/obj/effect/mark
	init_from_table = TRUE

/obj/effect/mist
	init_from_table = TRUE

/obj/effect/mobblocker
	init_from_table = TRUE

/obj/effect/overlay/aiholo
	init_from_table = TRUE

/obj/effect/overlay/atmos_excited
	init_from_table = TRUE

/obj/effect/overlay/bluespacify
	init_from_table = TRUE

/obj/effect/overlay/closet_door
	init_from_table = TRUE

/obj/effect/overlay/coconut
	init_from_table = TRUE

/obj/effect/overlay/energy_ball
	init_from_table = TRUE

/obj/effect/overlay/holographic
	init_from_table = TRUE

/obj/effect/overlay/light_visible
	init_from_table = TRUE

/obj/effect/overlay/palmtree_l
	init_from_table = TRUE

/obj/effect/overlay/palmtree_r
	init_from_table = TRUE

/obj/effect/overlay/recycler
	init_from_table = TRUE

/obj/effect/overlay/snow
	init_from_table = TRUE

/obj/effect/overlay/vis
	init_from_table = TRUE

/obj/effect/overlay/zone_sel
	init_from_table = TRUE

/obj/effect/projectile_shadow
	init_from_table = TRUE

/obj/effect/projection
	init_from_table = TRUE

/obj/effect/shield
	init_from_table = TRUE

/obj/effect/shut_controller
	init_from_table = TRUE

/obj/effect/simple_portal/coords
	init_from_table = TRUE

/obj/effect/space_dust
	init_from_table = TRUE

/obj/effect/speech_bubble
	init_from_table = TRUE

/obj/effect/spresent
	init_from_table = TRUE

/obj/effect/step_trigger/death
	init_from_table = TRUE

/obj/effect/step_trigger/stopper
	init_from_table = TRUE

/obj/effect/step_trigger/teleporter/offset
	init_from_table = TRUE

/obj/effect/step_trigger/teleporter/planetary_fall
	init_from_table = TRUE

/obj/effect/step_trigger/teleporter/random
	init_from_table = TRUE

/obj/effect/step_trigger/thrower
	init_from_table = TRUE

/obj/effect/step_trigger/warning
	init_from_table = TRUE

/obj/effect/suspension_field
	init_from_table = TRUE

/obj/effect/vac_visual
	init_from_table = TRUE

/obj/effect/weaversilk/trap
	init_from_table = TRUE

/obj/effect/zone_divider
	init_from_table = TRUE

/obj/structure/alien
	init_from_table = TRUE

/obj/structure/backup_implanter_ch
	init_from_table = TRUE

/obj/structure/balloon
	init_from_table = TRUE

/obj/structure/bedsheetbin
	init_from_table = TRUE

/obj/structure/bigDelivery
	init_from_table = TRUE

/obj/structure/boxingrope
	init_from_table = TRUE

/obj/structure/boxingropeenter
	init_from_table = TRUE

/obj/structure/c_tray
	init_from_table = TRUE

/obj/structure/chaoscake
	init_from_table = TRUE

/obj/structure/coatrack
	init_from_table = TRUE

/obj/structure/constructshell
	init_from_table = TRUE

/obj/structure/cryofeed
	init_from_table = TRUE

/obj/structure/cult/forge
	init_from_table = TRUE

/obj/structure/cult/talisman
	init_from_table = TRUE

/obj/structure/cult/tome
	init_from_table = TRUE

/obj/structure/curtain
	init_from_table = TRUE

/obj/structure/dancepole
	init_from_table = TRUE

/obj/structure/dark_portal/minion
	init_from_table = TRUE

/obj/structure/dirtybed
	init_from_table = TRUE

/obj/structure/displaycase
	init_from_table = TRUE

/obj/structure/disposalholder
	init_from_table = TRUE

/obj/structure/dogbed
	init_from_table = TRUE

/obj/structure/dummystairs
	init_from_table = TRUE

/obj/structure/event/santa_sack
	init_from_table = TRUE

/obj/structure/event/stage
	init_from_table = TRUE

/obj/structure/event_collector
	init_from_table = TRUE

/obj/structure/expedition_demo_target
	init_from_table = TRUE

/obj/structure/expedition_marker
	init_from_table = TRUE

/obj/structure/expedition_survey_beacon
	init_from_table = TRUE

/obj/structure/expedition_survivor_pod
	init_from_table = TRUE

/obj/structure/firedoor_assembly
	init_from_table = TRUE

/obj/structure/fireplace
	init_from_table = TRUE

/obj/structure/fitness/punchingbag
	init_from_table = TRUE

/obj/structure/fitness/weightlifter
	init_from_table = TRUE

/obj/structure/flag_base
	init_from_table = TRUE

/obj/structure/flag_decor
	init_from_table = TRUE

/obj/structure/flight_left
	init_from_table = TRUE

/obj/structure/flight_right
	init_from_table = TRUE

/obj/structure/generic_structure
	init_from_table = TRUE

/obj/structure/ghost_pod/manual/clegg
	init_from_table = TRUE

/obj/structure/ghost_pod/manual/corgi
	init_from_table = TRUE

/obj/structure/ghost_pod/manual/cursedblade
	init_from_table = TRUE

/obj/structure/ghost_pod/manual/lost_drone
	init_from_table = TRUE

/obj/structure/grille/cult
	init_from_table = TRUE

/obj/structure/grille/rustic
	init_from_table = TRUE

/obj/structure/handrail
	init_from_table = TRUE

/obj/structure/holohoop
	init_from_table = TRUE

/obj/structure/holostool
	init_from_table = TRUE

/obj/structure/hyperball_goal
	init_from_table = TRUE

/obj/structure/hyperball_pedestal
	init_from_table = TRUE

/obj/structure/kitchenspike
	init_from_table = TRUE

/obj/structure/ladder_assembly
	init_from_table = TRUE

/obj/structure/m_tray
	init_from_table = TRUE

/obj/structure/material_anvil
	init_from_table = TRUE

/obj/structure/morgue
	init_from_table = TRUE

/obj/structure/panic_button
	init_from_table = TRUE

/obj/structure/plasticflaps
	init_from_table = TRUE

/obj/structure/plushie
	init_from_table = TRUE

/obj/structure/portal_event
	init_from_table = TRUE

/obj/structure/portal_gateway
	init_from_table = TRUE

/obj/structure/portal_target
	init_from_table = TRUE

/obj/structure/prop/alien
	init_from_table = TRUE

/obj/structure/prop/altevian_generator_wrecked
	init_from_table = TRUE

/obj/structure/prop/big_skeleton
	init_from_table = TRUE

/obj/structure/prop/blackbox
	init_from_table = TRUE

/obj/structure/prop/cryopod
	init_from_table = TRUE

/obj/structure/prop/desert_planet160x160
	init_from_table = TRUE

/obj/structure/prop/desert_planet64x64
	init_from_table = TRUE

/obj/structure/prop/dna_vault
	init_from_table = TRUE

/obj/structure/prop/dominator
	init_from_table = TRUE

/obj/structure/prop/esoteric
	init_from_table = TRUE

/obj/structure/prop/fake_ai
	init_from_table = TRUE

/obj/structure/prop/fantasy
	init_from_table = TRUE

/obj/structure/prop/fence
	init_from_table = TRUE

/obj/structure/prop/grid_checker
	init_from_table = TRUE

/obj/structure/prop/lock
	init_from_table = TRUE

/obj/structure/prop/machine/alien_tank
	init_from_table = TRUE

/obj/structure/prop/machine/biosyphon
	init_from_table = TRUE

/obj/structure/prop/machine/bsb_off
	init_from_table = TRUE

/obj/structure/prop/machine/bsb_on
	init_from_table = TRUE

/obj/structure/prop/machine/centrifuge
	init_from_table = TRUE

/obj/structure/prop/machine/comm_tower
	init_from_table = TRUE

/obj/structure/prop/machine/complicator
	init_from_table = TRUE

/obj/structure/prop/machine/conduit
	init_from_table = TRUE

/obj/structure/prop/machine/core
	init_from_table = TRUE

/obj/structure/prop/machine/disease_analyser
	init_from_table = TRUE

/obj/structure/prop/machine/gravygen
	init_from_table = TRUE

/obj/structure/prop/machine/green_egg
	init_from_table = TRUE

/obj/structure/prop/machine/incubator
	init_from_table = TRUE

/obj/structure/prop/machine/isolator
	init_from_table = TRUE

/obj/structure/prop/machine/last_shelter
	init_from_table = TRUE

/obj/structure/prop/machine/nt_biocan
	init_from_table = TRUE

/obj/structure/prop/machine/nt_cruciforge
	init_from_table = TRUE

/obj/structure/prop/machine/nt_obelisk
	init_from_table = TRUE

/obj/structure/prop/machine/nt_optable
	init_from_table = TRUE

/obj/structure/prop/machine/random_radio
	init_from_table = TRUE

/obj/structure/prop/machine/smelter
	init_from_table = TRUE

/obj/structure/prop/machine/solifier
	init_from_table = TRUE

/obj/structure/prop/machine/sorter
	init_from_table = TRUE

/obj/structure/prop/machine/tgmc_console1
	init_from_table = TRUE

/obj/structure/prop/machine/tgmc_console2
	init_from_table = TRUE

/obj/structure/prop/machine/tgmc_console3
	init_from_table = TRUE

/obj/structure/prop/machine/tgmc_console4
	init_from_table = TRUE

/obj/structure/prop/machine/tgmc_console5
	init_from_table = TRUE

/obj/structure/prop/machine/tradebeacon
	init_from_table = TRUE

/obj/structure/prop/machine/tradebeacon2
	init_from_table = TRUE

/obj/structure/prop/machine/tube
	init_from_table = TRUE

/obj/structure/prop/machine/von_krabin
	init_from_table = TRUE

/obj/structure/prop/mainframe
	init_from_table = TRUE

/obj/structure/prop/memorial
	init_from_table = TRUE

/obj/structure/prop/poicanister
	init_from_table = TRUE

/obj/structure/prop/rock
	init_from_table = TRUE

/obj/structure/prop/statue/angel
	init_from_table = TRUE

/obj/structure/prop/statue/lion
	init_from_table = TRUE

/obj/structure/prop/statue/pillar
	init_from_table = TRUE

/obj/structure/prop/statue/statue1
	init_from_table = TRUE

/obj/structure/prop/statue/statue2
	init_from_table = TRUE

/obj/structure/prop/statue/statue3
	init_from_table = TRUE

/obj/structure/prop/statue/statue4
	init_from_table = TRUE

/obj/structure/prop/statue/statue5
	init_from_table = TRUE

/obj/structure/prop/statue/stump_plaque
	init_from_table = TRUE

/obj/structure/prop/statue/sunkensail
	init_from_table = TRUE

/obj/structure/prop/statue/venus
	init_from_table = TRUE

/obj/structure/prop/tyr_elevator
	init_from_table = TRUE

/obj/structure/prop/war
	init_from_table = TRUE

/obj/structure/prop/warmrocks
	init_from_table = TRUE

/obj/structure/salvageable/autolathe
	init_from_table = TRUE

/obj/structure/salvageable/computer_os
	init_from_table = TRUE

/obj/structure/salvageable/console_broken_os
	init_from_table = TRUE

/obj/structure/salvageable/console_os
	init_from_table = TRUE

/obj/structure/salvageable/data_os
	init_from_table = TRUE

/obj/structure/salvageable/implant_container_os
	init_from_table = TRUE

/obj/structure/salvageable/machine_os
	init_from_table = TRUE

/obj/structure/salvageable/server_os
	init_from_table = TRUE

/obj/structure/salvageable/shuttle_console
	init_from_table = TRUE

/obj/structure/salvageable/slotmachine1
	init_from_table = TRUE

/obj/structure/salvageable/slotmachine2
	init_from_table = TRUE

/obj/structure/ship_munition
	init_from_table = TRUE

/obj/structure/showcase
	init_from_table = TRUE

/obj/structure/shuttle/engine
	init_from_table = TRUE

/obj/structure/sign/atmos
	init_from_table = TRUE

/obj/structure/sign/atmos_air
	init_from_table = TRUE

/obj/structure/sign/atmos_ch4
	init_from_table = TRUE

/obj/structure/sign/atmos_co2
	init_from_table = TRUE

/obj/structure/sign/atmos_n2
	init_from_table = TRUE

/obj/structure/sign/atmos_n2o
	init_from_table = TRUE

/obj/structure/sign/atmos_o2
	init_from_table = TRUE

/obj/structure/sign/atmos_plasma
	init_from_table = TRUE

/obj/structure/sign/atmos_waste
	init_from_table = TRUE

/obj/structure/sign/atmosplaque
	init_from_table = TRUE

/obj/structure/sign/bigname
	init_from_table = TRUE

/obj/structure/sign/biohazard
	init_from_table = TRUE

/obj/structure/sign/botany
	init_from_table = TRUE

/obj/structure/sign/calendar
	init_from_table = TRUE

/obj/structure/sign/chemdiamond
	init_from_table = TRUE

/obj/structure/sign/chemistry
	init_from_table = TRUE

/obj/structure/sign/christmas
	init_from_table = TRUE

/obj/structure/sign/clock
	init_from_table = TRUE

/obj/structure/sign/coffee_shop_library
	init_from_table = TRUE

/obj/structure/sign/deathsposal
	init_from_table = TRUE

/obj/structure/sign/deck
	init_from_table = TRUE

/obj/structure/sign/deck1
	init_from_table = TRUE

/obj/structure/sign/deck2
	init_from_table = TRUE

/obj/structure/sign/deck3
	init_from_table = TRUE

/obj/structure/sign/deck4
	init_from_table = TRUE

/obj/structure/sign/department
	init_from_table = TRUE

/obj/structure/sign/double/maltesefalcon
	init_from_table = TRUE

/obj/structure/sign/electricshock
	init_from_table = TRUE

/obj/structure/sign/examroom
	init_from_table = TRUE

/obj/structure/sign/explosive
	init_from_table = TRUE

/obj/structure/sign/fire
	init_from_table = TRUE

/obj/structure/sign/flag
	init_from_table = TRUE

/obj/structure/sign/goldenplaque
	init_from_table = TRUE

/obj/structure/sign/graffiti
	init_from_table = TRUE

/obj/structure/sign/greencross
	init_from_table = TRUE

/obj/structure/sign/hangar
	init_from_table = TRUE

/obj/structure/sign/hostilefauna
	init_from_table = TRUE

/obj/structure/sign/hydro
	init_from_table = TRUE

/obj/structure/sign/hydrostorage
	init_from_table = TRUE

/obj/structure/sign/ironhammer
	init_from_table = TRUE

/obj/structure/sign/itg
	init_from_table = TRUE

/obj/structure/sign/kiddieplaque
	init_from_table = TRUE

/obj/structure/sign/level
	init_from_table = TRUE

/obj/structure/sign/levels
	init_from_table = TRUE

/obj/structure/sign/mining
	init_from_table = TRUE

/obj/structure/sign/nanotrasen
	init_from_table = TRUE

/obj/structure/sign/nosmoking_1
	init_from_table = TRUE

/obj/structure/sign/nosmoking_2
	init_from_table = TRUE

/obj/structure/sign/periodic
	init_from_table = TRUE

/obj/structure/sign/pods
	init_from_table = TRUE

/obj/structure/sign/redcross
	init_from_table = TRUE

/obj/structure/sign/scenery
	init_from_table = TRUE

/obj/structure/sign/science
	init_from_table = TRUE

/obj/structure/sign/sec1
	init_from_table = TRUE

/obj/structure/sign/sec2
	init_from_table = TRUE

/obj/structure/sign/sec3
	init_from_table = TRUE

/obj/structure/sign/sec4
	init_from_table = TRUE

/obj/structure/sign/securearea
	init_from_table = TRUE

/obj/structure/sign/signnew
	init_from_table = TRUE

/obj/structure/sign/small
	init_from_table = TRUE

/obj/structure/sign/vacuum
	init_from_table = TRUE

/obj/structure/sign/xenobio
	init_from_table = TRUE

/obj/structure/signevent
	init_from_table = TRUE

/obj/structure/signpost
	init_from_table = TRUE

/obj/structure/signpost_fake
	init_from_table = TRUE

/obj/structure/signpostwood
	init_from_table = TRUE

/obj/structure/smolebuilding
	init_from_table = TRUE

/obj/structure/smoleruins
	init_from_table = TRUE

/obj/structure/snowman
	init_from_table = TRUE

/obj/structure/stripper_pole
	init_from_table = TRUE

/obj/structure/target_stake
	init_from_table = TRUE

/obj/structure/thecake
	init_from_table = TRUE

/obj/structure/theonepizza
	init_from_table = TRUE

/obj/structure/tubes
	init_from_table = TRUE

/obj/structure/urinal
	init_from_table = TRUE
