// THIS FILE IS GENERATED by tools/build/lib/verdigris_bindings.ts. Do not edit.
//! The bind-set hash. DM passes its copy (VERDIGRIS_ABI) to `verdigris_init`.

pub const ABI: &str = "b86ff0d540bc801c";
