// THIS FILE IS GENERATED by tools/build/lib/verdigris_bindings.ts. Do not edit.
//! The bind-set hash. DM passes its copy (VERDIGRIS_ABI) to `verdigris_init`.

pub const ABI: &str = "92e87bfb0975be2b";
