// Life steps (doc/rewrite/life_sequences.md, doc/rewrite/om_retirement.md L1).
//
// Each mob type declares the Life steps it runs. A step is a proc on the mob type (life_<step>(F)), overridden by
// subtypes; `after =` edges reproduce the old stage order (derived by tools/dx/codemods/life_stage_steps.py; the
// solver breaks ties by key). `when =` names the frame conditions (/datum/sequence/life/conditions()), `reads =` the
// change channels that wake a sleeping step, `should_run =` says it has work, `rewake =` wakes it anyway after a
// delay. A later declaration of the same step on a subtype replaces the parent's. A step runs only for the Life set
// (life_set) it serves: preview dummies and delisted mobs keep none of the living steps.

/mob/living/life_steps()
	. = ..()
	if(life_set & LIFE_SET_DELIST)
		. += seq_step(PROC_REF(life_delist), after = LIFE_INPUT, reads = CHANGE_MOB_LOC | CHANGE_MOB_CONDITIONS)
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_upkeep), after = LIFE_INPUT, reads = CHANGE_MOB_LOC | CHANGE_MOB_CONDITIONS, should_run = PROC_REF(life_upkeep_due), woken_by = "Moved; ghosts following; spells learned")
		. += seq_step(PROC_REF(life_light), after = list(LIFE_INPUT, "life_instability"), when = "placed", reads = CHANGE_MOB_LOC | CHANGE_MOB_CONDITIONS, should_run = PROC_REF(life_light_due), woken_by = "refresh_glow(); instability")
		. += seq_step(PROC_REF(life_mutations), after = list(LIFE_INPUT, "life_breathing"), when = list("placed", "alive"), reads = CHANGE_MOB_STATUS, should_run = PROC_REF(life_mutations_due))
		if(life_radiation_applies())
			. += seq_step(PROC_REF(life_radiation), after = list(LIFE_INPUT, "life_mutations"), when = list("placed", "alive"), should_run = PROC_REF(life_radiation_due), rewake = PROC_REF(life_radiation_rewake))
		. += seq_step(PROC_REF(life_afk), after = list(LIFE_BODY, "life_random_events"), when = list("placed", "alive"), once = TRUE, rewake = PROC_REF(life_afk_rewake), woken_by = "Login, Logout; its own timer")
		. += seq_step(PROC_REF(life_environment), after = list(LIFE_BODY, "life_chemicals"), when = "placed", reads = CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT, should_run = PROC_REF(life_environment_due), rewake = PROC_REF(life_environment_rewake))
		. += seq_step(PROC_REF(life_ambience), after = list(LIFE_BODY, "life_environment"), when = "placed", once = TRUE, rewake = PROC_REF(life_ambience_rewake), woken_by = "Login; its own timer")
		. += seq_step(PROC_REF(life_movement), after = list(LIFE_BODY, "life_ambience"), when = "placed", reads = CHANGE_MOB_STATUS | CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT, should_run = PROC_REF(life_movement_due), rewake = PROC_REF(life_movement_rewake), woken_by = "Moved; start_pulling; equipping a grab; status setters")
		if(life_physiology_applies())
			. += seq_step(PROC_REF(life_physiology), after = list(LIFE_BODY, "life_movement"), when = list("placed", "!in_stasis", "alive"), reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_physiology_due), rewake = PROC_REF(life_physiology_rewake))
		. += seq_step(PROC_REF(life_status), after = LIFE_BODY, when = "placed", reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_status_due), rewake = PROC_REF(life_status_rewake), woken_by = "injure, mend, afflictions, factors and reagents (body invalidate); set_stat")
		. += seq_step(PROC_REF(life_disabilities), after = LIFE_MIND, when = list("placed", "status_ok"), reads = CHANGE_MOB_STATUS, should_run = PROC_REF(life_disabilities_due), woken_by = "status changes (blindness starting or ending); set_stat; body invalidate")
		. += seq_step(PROC_REF(life_tf_holder), after = LIFE_OUTPUT, when = "placed", reads = CHANGE_MOB_LOC | CHANGE_MOB_CONDITIONS, should_run = PROC_REF(life_tf_holder_due))
		. += seq_step(PROC_REF(life_vr_derez), after = LIFE_OUTPUT, when = "placed", reads = CHANGE_MOB_LOC | CHANGE_MOB_CONDITIONS, should_run = PROC_REF(life_vr_derez_due), woken_by = "Moved (a VR mob can only leave the VR area by moving)")
	if(life_set & (LIFE_SET_LIVING | LIFE_SET_ROBOT))
		. += seq_step(PROC_REF(life_instability), after = list(LIFE_INPUT, "life_type_pre", "life_robot_cycle", "life_trait_burninlight", "life_robot_senses", "life_trait_crowd_detection", "life_trait_diabetic", "life_trait_drippy", "life_trait_forms", "life_trait_gargoyle", "life_trait_nutrition_size_change", "life_trait_photosynth", "life_trait_promethean_biology", "life_trait_radiation_glow", "life_trait_schizophrenia", "life_trait_shadekin", "life_trait_using_machine_shim", "life_trait_weaver", "life_upkeep"), reads = CHANGE_MOB_LOC | CHANGE_MOB_CONDITIONS, should_run = PROC_REF(life_instability_due), woken_by = "adjust_instability()")

/mob/living/bot/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_bot_core), after = LIFE_TAIL)
		. += seq_step(PROC_REF(life_type_post), after = list(LIFE_TAIL, "life_voice", "life_weight", "life_visible_name"), should_run = PROC_REF(life_type_post_due), rewake = PROC_REF(life_type_post_rewake))

/mob/living/carbon/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_breathing), after = list(LIFE_INPUT, "life_light"), when = list("placed", "alive"), reads = CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT, should_run = PROC_REF(life_breathing_due), rewake = PROC_REF(life_breathing_rewake))
		. += seq_step(PROC_REF(life_addictions), after = list(LIFE_MIND, "life_disabilities"), when = list("placed", "status_ok"), reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_addictions_due), rewake = PROC_REF(life_addictions_rewake), woken_by = "reagent changes (body invalidate); its rewake")
		. += seq_step(PROC_REF(life_germs), after = LIFE_TAIL, reads = CHANGE_MOB_HEALTH, once = TRUE, rewake = PROC_REF(life_germs_rewake))
		. += seq_step(PROC_REF(life_type_post), after = list(LIFE_TAIL, "life_voice", "life_weight", "life_visible_name"), should_run = PROC_REF(life_type_post_due), rewake = PROC_REF(life_type_post_rewake))

/mob/living/dominated_brain/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_type_post), after = list(LIFE_TAIL, "life_voice", "life_weight", "life_visible_name"), should_run = PROC_REF(life_type_post_due), rewake = PROC_REF(life_type_post_rewake))

/mob/living/simple_mob/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_environment), after = list(LIFE_BODY, "life_chemicals"), when = list("placed", "!in_stasis"), reads = CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT, should_run = PROC_REF(life_environment_due), rewake = PROC_REF(life_environment_rewake), woken_by = "Moved; injure; its own timer for air changing in place")
		. += seq_step(PROC_REF(life_simple_vitals), after = LIFE_TAIL, reads = CHANGE_MOB_HEALTH, once = TRUE, woken_by = "injure, mend, body invalidate (health); set_stat")
		. += seq_step(PROC_REF(life_supernatural), after = LIFE_TAIL, when = "alive", reads = CHANGE_MOB_STATUS, should_run = PROC_REF(life_supernatural_due))
		. += seq_step(PROC_REF(life_guts), after = list(LIFE_TAIL, "life_special"), when = "alive", should_run = PROC_REF(life_guts_due))
		. += seq_step(PROC_REF(life_simple_healing), after = list(LIFE_TAIL, "life_guts"), when = "alive", reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_simple_healing_due), woken_by = "injure; feeding")
		. += seq_step(PROC_REF(life_type_post), after = list(LIFE_TAIL, "life_voice", "life_weight", "life_visible_name"), should_run = PROC_REF(life_type_post_due), rewake = PROC_REF(life_type_post_rewake))

/mob/living/voice/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_type_pre), after = LIFE_INPUT, should_run = PROC_REF(life_type_pre_due))

/mob/living/carbon/alien/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_type_pre), after = LIFE_INPUT, should_run = PROC_REF(life_type_pre_due))
		. += seq_step(PROC_REF(life_alien_growth), after = list(LIFE_TAIL, "life_germs"), reads = CHANGE_MOB_HEALTH)

/mob/living/carbon/brain/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_chemicals), after = list(LIFE_BODY, "life_afk"), when = "placed", reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_chemicals_due), rewake = PROC_REF(life_chemicals_rewake))
		. += seq_step(PROC_REF(life_status), after = LIFE_BODY, when = "placed", reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_status_due), rewake = PROC_REF(life_status_rewake), woken_by = "injure/mend (refresh_host_status), brain removal/insertion, MMI emp_act; slow rewake for tissue drift")

/mob/living/carbon/human/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_type_pre), after = LIFE_INPUT, should_run = PROC_REF(life_type_pre_due))
		. += seq_step(PROC_REF(life_breathing), after = list(LIFE_INPUT, "life_light"), when = list("placed", "!in_stasis", "alive"), reads = CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT, should_run = PROC_REF(life_breathing_due), rewake = PROC_REF(life_breathing_rewake))
		. += seq_step(PROC_REF(life_mutations), after = list(LIFE_INPUT, "life_breathing"), when = list("placed", "!in_stasis", "alive"), reads = CHANGE_MOB_STATUS, should_run = PROC_REF(life_mutations_due))
		if(life_radiation_applies())
			. += seq_step(PROC_REF(life_radiation), after = list(LIFE_INPUT, "life_mutations"), when = list("placed", "!in_stasis", "alive"), should_run = PROC_REF(life_radiation_due), rewake = PROC_REF(life_radiation_rewake), woken_by = "its rewake (radiation is written raw)")
		. += seq_step(PROC_REF(life_random_events), after = LIFE_BODY, when = list("placed", "!in_stasis", "alive"), reads = CHANGE_MOB_STATUS, should_run = PROC_REF(life_random_events_due))
		. += seq_step(PROC_REF(life_chemicals), after = list(LIFE_BODY, "life_afk"), when = list("placed", "!in_stasis"), reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_chemicals_due), rewake = PROC_REF(life_chemicals_rewake))
		. += seq_step(PROC_REF(life_status), after = LIFE_BODY, when = "placed", reads = CHANGE_MOB_HEALTH | CHANGE_MOB_STATUS | CHANGE_MOB_STAT | CHANGE_MOB_EQUIPMENT | CHANGE_MOB_CLIENT, should_run = PROC_REF(life_status_due), rewake = PROC_REF(life_status_rewake), woken_by = "injure/mend and body invalidate; status setters (sleep, blindness, drowsiness); set_stat; equipment (blindfolds, rig visors); Login/Logout (SSD); its rewake for raw fear/tiredness writes")
		. += seq_step(PROC_REF(life_voice), after = LIFE_TAIL, reads = CHANGE_MOB_HEALTH | CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT, once = TRUE, rewake = PROC_REF(life_voice_rewake), woken_by = "equipment; body invalidate; set_stat; Moved; its own timer")
		. += seq_step(PROC_REF(life_stasis_sleep), after = list(LIFE_TAIL, "life_voice"), reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_stasis_sleep_due))
		. += seq_step(PROC_REF(life_fall), after = list(LIFE_TAIL, "life_stasis_sleep"), reads = CHANGE_MOB_STATUS | CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT, once = TRUE, rewake = PROC_REF(life_fall_rewake))
		. += seq_step(PROC_REF(life_changeling), after = list(LIFE_TAIL, "life_fall"), when = list("!in_stasis", "alive"), reads = CHANGE_MOB_CLIENT, should_run = PROC_REF(life_changeling_due), rewake = PROC_REF(life_changeling_rewake), woken_by = "login (HUD); its rewake (becoming a changeling)")
		. += seq_step(PROC_REF(life_thermoregulation), after = list(LIFE_TAIL, "life_changeling"), when = list("!in_stasis", "alive"), reads = CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT | CHANGE_MOB_STAT, should_run = PROC_REF(life_thermoregulation_due), rewake = PROC_REF(life_thermoregulation_rewake), woken_by = "movement; equipment; set_stat; its rewake for raw body temperature writes")
		. += seq_step(PROC_REF(life_weight), after = LIFE_TAIL, when = list("!in_stasis", "alive"), should_run = PROC_REF(life_weight_due), rewake = PROC_REF(life_weight_rewake), woken_by = "its rewake (nutrition is written raw everywhere)")
		. += seq_step(PROC_REF(life_shock), after = list(LIFE_TAIL, "life_weight"), when = list("!in_stasis", "alive"), reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_shock_due), rewake = PROC_REF(life_shock_rewake), woken_by = "injure/mend and body invalidate (pain, analgesia); adjust_shock()/set_shock()")
		. += seq_step(PROC_REF(life_medical), after = list(LIFE_TAIL, "life_shock"), when = list("!in_stasis", "alive"), reads = CHANGE_MOB_HEALTH, should_run = PROC_REF(life_medical_due), rewake = PROC_REF(life_medical_rewake), woken_by = "body invalidate (conditions, chems, factors, oxygen debt via tissue hypoxia); its rewake for raw temperature/radiation writes")
		. += seq_step(PROC_REF(life_heartbeat), after = list(LIFE_TAIL, "life_medical"), when = list("!in_stasis", "alive"), reads = CHANGE_MOB_HEALTH | CHANGE_MOB_LOC | CHANGE_MOB_CLIENT, should_run = PROC_REF(life_heartbeat_due), rewake = PROC_REF(life_heartbeat_rewake), woken_by = "body invalidate; movement (space); login; its rewake for raw pulse writes")
		. += seq_step(PROC_REF(life_nif), after = list(LIFE_TAIL, "life_heartbeat"), when = list("!in_stasis", "alive"), should_run = PROC_REF(life_nif_due), rewake = PROC_REF(life_nif_rewake), woken_by = "its rewake (a NIF installed)")
		. += seq_step(PROC_REF(life_phobias), after = list(LIFE_TAIL, "life_nif"), when = list("!in_stasis", "alive"), should_run = PROC_REF(life_phobias_due), rewake = PROC_REF(life_phobias_rewake), woken_by = "its rewake (phobias gained)")
		. += seq_step(PROC_REF(life_npc), after = list(LIFE_TAIL, "life_phobias"), when = list("!in_stasis", "alive"), reads = CHANGE_MOB_CLIENT | CHANGE_MOB_STAT, should_run = PROC_REF(life_npc_due), rewake = PROC_REF(life_npc_rewake), woken_by = "login/logout; set_stat; its rewake")
		. += seq_step(PROC_REF(life_species_components), after = list(LIFE_TAIL, "life_npc"))
		. += seq_step(PROC_REF(life_visible_name), after = list(LIFE_TAIL, "life_species_components"), reads = CHANGE_MOB_HEALTH | CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT, once = TRUE, rewake = PROC_REF(life_visible_name_rewake), woken_by = "equipment; body invalidate (disfigurement); set_stat; its own timer")
		. += seq_step(PROC_REF(life_pulse), after = list(LIFE_TAIL, "life_visible_name"), reads = CHANGE_MOB_HEALTH, once = TRUE)

/mob/living/silicon/ai/life_steps()
	. = ..()
	if(life_set & LIFE_SET_AI)
		. += seq_step(PROC_REF(life_ai_power), after = LIFE_INPUT)
		. += seq_step(PROC_REF(life_ai_body), after = list(LIFE_INPUT, "life_ai_power"), reads = CHANGE_MOB_HEALTH)
		. += seq_step(PROC_REF(life_ai_upkeep), after = LIFE_BODY)

/mob/living/silicon/decoy/life_steps()
	. = ..()
	if(life_set & LIFE_SET_DECOY)
		. += seq_step(PROC_REF(life_decoy_body), after = LIFE_BODY, reads = CHANGE_MOB_HEALTH)

/mob/living/silicon/pai/life_steps()
	. = ..()
	if(life_set & LIFE_SET_PAI)
		. += seq_step(PROC_REF(life_pai_cable), after = LIFE_INPUT)
		. += seq_step(PROC_REF(life_pai_body), after = list(LIFE_INPUT, "life_pai_cable"), reads = CHANGE_MOB_HEALTH)
		. += seq_step(PROC_REF(life_pai_silence), after = LIFE_OUTPUT)
		. += seq_step(PROC_REF(life_pai_repair), after = list(LIFE_OUTPUT, "life_pai_silence"), reads = CHANGE_MOB_HEALTH)

/mob/living/silicon/robot/life_steps()
	. = ..()
	if(life_set & LIFE_SET_ROBOT)
		. += seq_step(PROC_REF(life_robot_cycle), after = LIFE_INPUT)
		. += seq_step(PROC_REF(life_robot_senses), after = LIFE_INPUT, reads = CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT | CHANGE_MOB_STATUS, should_run = PROC_REF(life_robot_senses_due))
		. += seq_step(PROC_REF(life_robot_power), after = LIFE_BODY)
		. += seq_step(PROC_REF(life_robot_body), after = list(LIFE_BODY, "life_robot_power"), reads = CHANGE_MOB_HEALTH)
		. += seq_step(PROC_REF(life_robot_alarms), after = LIFE_OUTPUT)

/mob/living/simple_mob/clockwork/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/slime/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/ysbryd/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_type_pre), after = LIFE_INPUT, should_run = PROC_REF(life_type_pre_due))

/mob/living/carbon/brain/caught_soul/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_type_pre), after = LIFE_INPUT, should_run = PROC_REF(life_type_pre_due))

/mob/living/simple_mob/animal/borer/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/blob/spore/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/homunculus/evil/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_type_pre), after = LIFE_INPUT, should_run = PROC_REF(life_type_pre_due))

/mob/living/simple_mob/mechanical/mecha/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/mechanical/mining_drone/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/metroid/juvenile/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/bigdragon/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/demonAI/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/fossiltank/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/giant_spider/lurker/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/giant_spider/nurse/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/passive/cat/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/passive/fish/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_breathing), after = list(LIFE_INPUT, "life_light"), when = list("placed", "alive"), reads = CHANGE_MOB_LOC | CHANGE_MOB_EQUIPMENT, should_run = PROC_REF(life_breathing_due), rewake = PROC_REF(life_breathing_rewake))

/mob/living/simple_mob/animal/sif/frostfly/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/sif/kururak/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/sif/leech/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/sif/savik/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/sif/tymisian/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/space/bear/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/space/goose/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/space/space_worm/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/tyr/rainbow_fly/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/mechanical/cyber_horror/tajaran/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/mechanical/ward/monitor/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/candy/bluecabold/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/candy/orangecabold/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/candy/purplecabold/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/candy/yellowcabold/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/spacecritter/livingice/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/spacecritter/radcrab/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/space/mouse_army/stealth/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/tyr/mineral_ants/builder/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/animal/tyr/mineral_ants/queen/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/humanoid/astral_collective/soul/shield_projector/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/mechanical/hivebot/support/commander/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/mechanical/hivebot/support/logistics/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))

/mob/living/simple_mob/vore/aggressive/panther/thor/life_steps()
	. = ..()
	if(life_set & LIFE_SET_LIVING)
		. += seq_step(PROC_REF(life_special), after = list(LIFE_TAIL, "life_supernatural"), when = "alive", should_run = PROC_REF(life_special_due))
