"""Generates doc/rewrite/signal_migration_map.md (completion_plan sec 3.2, step E1).

Counts every COMSIG_* signal's senders (SEND_SIGNAL/SEND_GLOBAL_SIGNAL sites) and
listeners (RegisterSignal(s) sites naming it), classifies its replacement, and
lists components/elements with their add sites. Grouped by code folder so the
LC-refs sweep can migrate folder by folder. Regenerate; don't hand-edit:

    python tools/ci/signal_migration_map.py
"""
import collections
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))
from state_schema_lint import code_only  # noqa: E402

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "doc", "rewrite", "signal_migration_map.md")

DEFINE = re.compile(r"^\s*#define\s+(COMSIG_\w+)\b")
FLAG_DEFINE = re.compile(r"^\s*#define\s+(?!COMSIG_)(\w+)")
SIG = re.compile(r"\bCOMSIG_\w+")
SEND = re.compile(r"SEND_(?:GLOBAL_)?SIGNAL\s*\(")
REG = re.compile(r"\bRegisterSignals?\s*\(")
STATEY = re.compile(r"(CHANGE|UPDATE|_SET_|_SET$|_MOVED|_Z_CHANGED|STAT$|_LOC)")
COMP_TYPE = re.compile(r"^/datum/(component|element)/([\w/]+)\s*$", re.M)
ADD = re.compile(r"\b(AddComponent|AddComponentFrom|LoadComponent|AddElement)\s*\(\s*(?:[^,()]+,\s*)?(/datum/(?:component|element)/[\w/]+)")


def folder(rel):
    parts = rel.split("/")
    return "/".join(parts[:3]) if len(parts) > 3 else "/".join(parts[:-1])


def main():
    files = sorted(glob.glob(os.path.join(ROOT, "code", "**", "*.dm"), recursive=True))
    defines, has_flags = {}, set()
    texts = {}
    for path in files:
        rel = os.path.relpath(path, ROOT).replace("\\", "/")
        raw = open(path, encoding="utf-8", errors="replace").read()
        lines = raw.split("\n")
        last = None
        for line in lines:
            m = DEFINE.match(line)
            if m:
                last = m.group(1)
                defines.setdefault(last, rel)
                continue
            if last and FLAG_DEFINE.match(line) and ("COMPONENT_" in line or "COMSIG_" not in line and line.startswith(("\t", " "))):
                has_flags.add(last)
                continue
            if line.strip() and not line.strip().startswith("/"):
                last = None
        texts[rel] = code_only(raw)

    sends = collections.defaultdict(collections.Counter)   # sig -> folder -> n
    listens = collections.defaultdict(collections.Counter)
    ret_used = set()
    comp_types = {}
    adds = collections.defaultdict(collections.Counter)
    for rel, text in texts.items():
        fold = folder(rel)
        for m in COMP_TYPE.finditer(text):
            kind, name = m.group(1), m.group(2)
            if name.split("/")[0] != "proc":
                comp_types.setdefault(f"/datum/{kind}/{name.split('/proc')[0]}", rel)
        for m in ADD.finditer(text):
            adds[m.group(2)][fold] += 1
        for line in text.split("\n"):
            if "#define" in line:
                continue
            if SEND.search(line):
                for s in SIG.findall(line):
                    sends[s][fold] += 1
                    pre = line[:line.find("SEND_")]
                    if re.search(r"(\bif\s*\(|=|&|\breturn\b|!|\|\|)\s*\(?\s*$", pre):
                        ret_used.add(s)
            elif REG.search(line):
                for s in SIG.findall(line):
                    listens[s][fold] += 1
    used = set(sends) | set(listens)
    used = {s for s in used if s in defines}

    def replacement(s):
        if s in has_flags or s in ret_used:
            return "before/ event (EVENT_VETO)"
        if STATEY.search(s):
            return "channel / watch"
        return "event"

    by_folder = collections.defaultdict(list)
    for s in used:
        for f in set(sends[s]) | set(listens[s]):
            by_folder[f].append(s)

    out = []
    w = out.append
    w("# Signal migration map")
    w("")
    w("Generated by `tools/ci/signal_migration_map.py`; regenerate, don't hand-edit.")
    w("Rule (object_model_core.md sec 16, completion_plan sec 3.2): synchronous reactions")
    w("that can refuse become `/datum/om/event/before/x` returning `EVENT_VETO`; synchronous")
    w("notifications become `/datum/om/event/x` via `om_emit()`; deferred or state-driven")
    w("reactions become a declared field's channel, a watch or `om_after()`.")
    w("")
    w("Classification: a signal whose sender reads the return value, or whose define is")
    w("followed by return flags, is a `before/` event; a name describing a state change")
    w("(`CHANGE`, `UPDATE`, `_SET`, `_MOVED`...) is a channel/watch; the rest are events.")
    w("Review each during its folder's sweep; the classification is a starting point.")
    w("")
    kinds = collections.Counter(replacement(s) for s in used)
    w(f"Signals in use: **{len(used)}** (defined: {len(defines)}; defined but unused: {len(set(defines) - used)}).")
    w(f"Send sites: {sum(sum(c.values()) for c in sends.values())}; listener sites: {sum(sum(c.values()) for c in listens.values())}.")
    w("")
    w("| Replacement | Signals |")
    w("|---|---|")
    for k, v in sorted(kinds.items()):
        w(f"| {k} | {v} |")
    w("")
    w("## All signals")
    w("")
    w("| Signal | Senders | Listeners | Replacement | Defined in |")
    w("|---|---|---|---|---|")
    for s in sorted(used):
        w(f"| `{s}` | {sum(sends[s].values())} | {sum(listens[s].values())} | {replacement(s)} | `{defines[s]}` |")
    w("")
    w("## By folder")
    w("")
    w("Counts are the sites in that folder only.")
    for f in sorted(by_folder, key=lambda f: -sum(sends[s][f] + listens[s][f] for s in by_folder[f])):
        total = sum(sends[s][f] + listens[s][f] for s in by_folder[f])
        w("")
        w(f"### `{f}` ({len(by_folder[f])} signals, {total} sites)")
        w("")
        w("| Signal | Senders | Listeners | Replacement |")
        w("|---|---|---|---|")
        for s in sorted(by_folder[f]):
            w(f"| `{s}` | {sends[s][f]} | {listens[s][f]} | {replacement(s)} |")
    w("")
    w("## Components and elements")
    w("")
    w("A component becomes a behaviour whose state lives on the entity (declared fields);")
    w("an element becomes a shared behaviour singleton (no per-instance state). Add sites")
    w("count `AddComponent`/`AddComponentFrom`/`LoadComponent`/`AddElement` calls naming the type.")
    w("")
    w("| Type | Kind | Add sites | Folders adding it | Equivalent | Defined in |")
    w("|---|---|---|---|---|---|")
    for t in sorted(comp_types):
        kind = "component" if t.startswith("/datum/component") else "element"
        eq = "behaviour (entity state)" if kind == "component" else "shared behaviour singleton"
        n = sum(adds[t].values())
        fl = ", ".join(f"`{f}` {c}" for f, c in adds[t].most_common(4))
        w(f"| `{t}` | {kind} | {n} | {fl} | {eq} | `{comp_types[t]}` |")
    open(OUT, "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
    print(f"{len(used)} signals, {len(comp_types)} components/elements -> {OUT}")


if __name__ == "__main__":
    main()
