// Notices: synchronous delivery, outcomes, the depth rule (doc/rewrite/final_api.html, section 8 "Outcomes and notices", "Lifetime"; section 10
// "After hooks", "Announcing and observing"; section 19 "E4").
//
// A notice is the action's name in the past tense (`/datum/notice/fell`), generated by ACTION(). It is pooled, and it is also the context its
// handlers get: a /datum/notice is a /datum/act/notice, so a handler x(datum/act/A) reads A.holder (the entity whose entry runs), A.target (the
// entity the action was done to, the publisher), A.source, A.outcome and the notice's own typed fields.
//
// Delivery is synchronous, at act_done() (or PUBLISH), in publish order: the publisher's next line sees the handlers' effects. A listener hears
// the outcomes it asked for (on_notice(..., outcome = ACT_COMMITTED | ACT_REFUSED | ACT_REPLACED | ACT_ROLL_FAILED | ACT_ANY, values combine
// with |); the default is committed only. An outcome nobody asked for builds no notice.
//
// Depth. Handlers nest (a handler publishes a notice, whose handler starts an action ...). A notice published while GLOB.act_depth is at
// ACT_MAX_DEPTH is queued to the next drain point (act_drain_point()), delivered late and out of publish order, logged with its chain, and a test
// build fails on it: delayed, never dropped. Except when its holder is deleted before the drain, which is the only way a late notice is not delivered.
//
// The late queue and deleted things (framework_gaps D3). A queued row names its holder by handle and holds its notice with the target cleared: nothing in the
// queue keeps a datum alive, so a queued notice never causes a hard delete.
//  - A holder deleted while its notice waits: the notice is delivered, at the moment the holder's destroy transaction begins (notice_late_subject_deleting()),
//    to every other receiver (the observers of the holder, the legacy reactions), with the holder in its deleting state (QDELETED, still whole); the
//    holder's own hooks do not run, as for any notice published by a dying holder. The row then goes.
//  - A receiver deleted while a notice waits for it (an observer, or a holder that was gone without a transaction): it gets nothing, and the row is
//    dropped at the drain (a handle that no longer names a datum), the same rule as a timer whose owner is gone.
//
// Legacy bridge. A notice delivered here also reaches the legacy on_notice() reactions (code/datums/reactions) of its holder, and a notice a
// legacy publish() delivers reaches the hooks here, so both sides run on one occurrence.

/datum/notice
	parent_type = /datum/act/notice
	/// op_done's op key, which the on_op() filter reads (null on every other notice).
	var/op_key

/// The notices waiting for the next drain point: list(holder handle, notice, outcome, chain) in the order they were queued. The holder is a handle
/// (entity_handle()), never a reference; the notice's target is cleared while it waits.
GLOBAL_LIST_EMPTY(notice_late_queue)
GLOBAL_VAR_INIT(notice_draining_late, FALSE)

/// A pooled notice of `type`. Give it to notice_publish(), which releases it once delivered.
/proc/notice_take(type)
	RETURN_TYPE(/datum/notice)
	var/datum/notice/N = take(type)
	GLOB.notice_taken++
	return N

/// The notice hooks of a compiled table for one notice type (static, in declaration order).
/proc/notice_hooks_static(datum/type_table/T, notice_type)
	var/list/for_table = GLOB.notice_plans[T]
	if(isnull(for_table))
		for_table = list()
		GLOB.notice_plans[T] = for_table
	var/list/known = for_table["[notice_type]"]
	if(!isnull(known))
		return known
	var/list/hooks = list()
	for(var/datum/hook/H as anything in hook_table_of(T))
		if(H.kind == HOOK_NOTICE && ispath(notice_type, H.target))
			hooks += H
	for_table["[notice_type]"] = hooks
	return hooks

/// TRUE when `E` is fully gone as far as notices go: deleted, and past being merely mid-deletion. An entity inside its own destroy transaction (qdel() has
/// started: its qdeleting notice, the contents it spills, the links it drops) still publishes, and its observers still hear it, until the transaction ends.
/proc/notice_entity_gone(datum/E)
	if(!E)
		return TRUE
	return E.gc_destroyed && E.gc_destroyed != GC_CURRENTLY_BEING_QDELETED

/// Does a hook asking for `asked` hear an outcome `outcome`? Asking about ACT_ANY (a WANTS) matches any hook that asked for something.
/proc/outcome_heard(asked, outcome)
	return !!(asked & outcome)

/// TRUE when something on E listens for `notice_type` for `outcome` (the committed outcome by default): a type-level or activation hook, or a
/// legacy on_notice() reaction (committed only).
/proc/notice_wanted(datum/E, notice_type, outcome = ACT_COMMITTED)
	return notice_wanted_native(E, notice_type, outcome)

/// notice_wanted()'s body.
/proc/notice_wanted_native(datum/E, notice_type, outcome = ACT_COMMITTED)
	if(notice_entity_gone(E) || !islist(GLOB?.notice_plans))
		return FALSE
	var/datum/type_table/T = table_of(E)
	for(var/datum/hook/H as anything in notice_hooks_static(T, notice_type))
		if(outcome_heard(H.outcomes, outcome) && !(H.cap_key && hook_cap_represented(E, H.cap_key)))
			return TRUE
	for(var/datum/hook/H as anything in E.rx?.hooks)
		if(H.kind == HOOK_NOTICE && ispath(notice_type, H.target) && outcome_heard(H.outcomes, outcome) && H.activation && !H.activation.dead && H.activation.runs)
			return TRUE
	return !!(outcome & ACT_COMMITTED) && rx_wants_notice(E, notice_type)

/// Publishes notice `N` from `holder` with `outcome`: delivered now, or queued when nesting is at the cap. N is released after delivery.
/proc/notice_publish(datum/holder, datum/notice/N, outcome = ACT_COMMITTED)
	OP_PURE_GUARD("notice [N.type] was published from [holder?.type]")
	N.target = holder
	var/at_cap = GLOB.act_depth >= ACT_MAX_DEPTH
	TEST_REC_NOTICE(N.type, outcome, at_cap)
	if(at_cap)
		var/chain = act_chain_text()
		GLOB.notice_late++
		N.target = null // the row holds the holder by handle only: a queued notice keeps nothing alive
		GLOB.notice_late_queue += list(list(entity_handle(holder) || entity_handle_of(holder), N, outcome, chain))
		log_world("ACT: notice [N.type] from [holder?.type] queued to the next drain point: nested deeper than [ACT_MAX_DEPTH] ([chain])")
		act_report(RULE_NOTICE_DEPTH, "notice [N.type] from [holder?.type] was queued to the next drain point (nested deeper than [ACT_MAX_DEPTH]; it is delivered late and out of publish order): [chain]")
		return
	notice_deliver(holder, N, outcome)
	N.release()

/// The hooks that hear notice N on holder now, in order: the table's, then the live activations'.
/proc/notice_plan_for(datum/holder, datum/notice/N, outcome)
	. = list()
	var/datum/type_table/T = table_of(holder)
	for(var/datum/hook/H as anything in notice_hooks_static(T, N.type))
		if(!outcome_heard(H.outcomes, outcome) || (H.cap_key && hook_cap_represented(holder, H.cap_key)))
			continue
		if(!hook_conditions_hold(H, holder))
			continue
		. += H
	for(var/datum/hook/H as anything in holder.rx?.hooks)
		if(H.kind != HOOK_NOTICE || !ispath(N.type, H.target) || !outcome_heard(H.outcomes, outcome))
			continue
		if(!H.activation || H.activation.dead || !H.activation.runs)
			continue
		. += H
	. = hooks_sorted(.)

/// Delivers N to every listener, synchronously: the hooks here and the legacy on_notice() reactions.
/proc/notice_deliver(datum/holder, datum/notice/N, outcome)
	notice_deliver_hooks(holder, N, outcome)
	if(outcome & ACT_COMMITTED)
		N.source = holder
		rx_deliver_notice_to(holder, N)

/// The hooks of this module that hear N (also called for a notice the legacy publish() delivers).
/proc/notice_deliver_hooks(datum/holder, datum/notice/N, outcome)
	if(notice_entity_gone(holder) || !islist(GLOB?.notice_plans))
		return
	N.target = holder
	N.outcome = (outcome == ACT_ROLL_FAILED) ? ACT_COMMITTED : outcome
	// A holder inside its destroy transaction is heard by the observers that are still alive (its qdeleting notice, what it spills while it goes), and
	// by its own hooks only for the qdeleting notice: nothing else runs on an entity that is being taken apart.
	var/holder_dying = QDELETED(holder)
	var/dying_notice = holder_dying && istype(N, /datum/notice/qdeleting)
	for(var/datum/hook/H as anything in notice_plan_for(holder, N, outcome))
		if(H.op_key && H.op_key != N.op_key)
			continue
		var/datum/run_on = H.on_listener ? H.activation?.source : holder
		if(!isdatum(run_on) || notice_entity_gone(run_on))
			continue
		if(QDELETED(run_on) && !(dying_notice && run_on == holder))
			continue // a listener mid-deletion hears nothing, except the notice that its own deletion has begun
		if(holder_dying && !H.on_listener && !dying_notice)
			continue
		N.holder = run_on
		hook_context(N, H)
		if(H.on_listener)
			N.source = holder
		var/depth = GLOB.act_depth
		GLOB.act_chain += "[N.type]:[run_on.type]"
		try
			hook_run_parts(H, N, H.entry.children)
		catch(var/exception/e)
			dq_report_caught(e, "notice [N.type] hook on [run_on.type]")
		GLOB.act_depth = depth
		GLOB.act_chain.len--

/// The next drain point (the kernel's D, P and R drains): the notices queued past the depth cap are delivered, in the order they were queued, at
/// depth zero; the on_change hooks that were marked run.
/proc/act_drain_point()
	if(length(GLOB.notice_late_queue) && !GLOB.notice_draining_late)
		notice_drain_late()
	if(length(GLOB.hook_change_pending))
		hooks_drain_changes()

/// The holder of a late-queue row: a handle resolves to a live datum (null once it was deleted); a datum put in a row by hand is itself.
/proc/notice_late_holder(list/row)
	var/holder = row[1]
	return istext(holder) ? resolve_handle(holder) : holder

/// Delivers one late row to every receiver and releases it. `holder` is the datum the row names (live, or in its deleting state).
/proc/notice_late_deliver(datum/holder, list/row)
	var/datum/notice/N = row[2]
	try
		if(holder)
			N.target = holder
			notice_deliver(holder, N, row[3])
	catch(var/exception/fault)
		// One throwing delivery must not strand the rest of the batch or leave the draining flag set (the late queue would never drain again).
		dq_report_caught(fault, "late notice [N?.type] on [holder?.type]")
		act_unwind(GLOB.act_depth, length(GLOB.act_chain), "late notice drain", fault)
	N?.release()

/// A holder's destroy transaction has begun (it is QDELETED and still whole): the notices queued for it are delivered now, to every receiver but its own
/// hooks, with the holder in its deleting state, and their rows go. After this nothing in the queue names it.
/proc/notice_late_subject_deleting(datum/holder)
	for(var/i in length(GLOB.notice_late_queue) to 1 step -1)
		var/list/row = GLOB.notice_late_queue[i]
		var/row_holder = row[1]
		if(row_holder != holder && (isnull(row_holder) || row_holder != entity_handle_of(holder)))
			continue
		GLOB.notice_late_queue.Cut(i, i + 1)
		var/datum/notice/queued = row[2]
		log_world("ACT: late notice [queued?.type] delivered to the observers of [holder.type] as it is deleted (\[[row[4]]\])")
		var/depth = GLOB.act_depth
		var/chain_len = length(GLOB.act_chain)
		notice_late_deliver(holder, row)
		GLOB.act_depth = depth
		if(length(GLOB.act_chain) > chain_len)
			GLOB.act_chain.len = chain_len

/proc/notice_drain_late()
	var/depth = GLOB.act_depth
	var/chain_len = length(GLOB.act_chain)
	GLOB.notice_draining_late = TRUE
	var/passes = 0
	while(length(GLOB.notice_late_queue) && passes < DRAIN_MAX_PASSES)
		passes++
		var/list/batch = GLOB.notice_late_queue
		GLOB.notice_late_queue = list()
		for(var/list/row as anything in batch)
			var/datum/holder = notice_late_holder(row)
			if(!holder || QDELETED(holder))
				// The receiver was deleted before the drain: it gets nothing and its row is dropped (a holder mid-deletion was delivered to when its
				// transaction began).
				var/datum/notice/dropped = row[2]
				log_world("ACT: late notice [dropped?.type] dropped: its holder was deleted before the drain (\[[row[4]]\])")
				dropped?.release()
				continue
			notice_late_deliver(holder, row)
	if(length(GLOB.notice_late_queue))
		log_world("ACT: the late notice drain stopped after [DRAIN_MAX_PASSES] passes with [length(GLOB.notice_late_queue)] notice(s) still queued (a handler keeps publishing past the depth cap); they wait for the next drain point")
	GLOB.notice_draining_late = FALSE
