//include unit test files in this module in this ifdef
//Keep this sorted alphabetically

#if defined(UNIT_TESTS) || defined(SPACEMAN_DMM)

/// For advanced cases, fail unconditionally but don't return (so a test can return multiple results)
#define TEST_FAIL(reason) (Fail(reason || "No reason", __FILE__, __LINE__))

/// Asserts that a condition is true
/// If the condition is not true, fails the test
#define TEST_ASSERT(assertion, reason) if (!(assertion)) { return Fail("Assertion failed: [reason || "No reason"]", __FILE__, __LINE__) }

/// Asserts that a parameter is not null
#define TEST_ASSERT_NOTNULL(a, reason) if (isnull(a)) { return Fail("Expected non-null value: [reason || "No reason"]", __FILE__, __LINE__) }

/// Asserts that a parameter is null
#define TEST_ASSERT_NULL(a, reason) if (!isnull(a)) { return Fail("Expected null value but received [a]: [reason || "No reason"]", __FILE__, __LINE__) }

/// Asserts that the two parameters passed are equal, fails otherwise
/// Optionally allows an additional message in the case of a failure
#define TEST_ASSERT_EQUAL(a, b, message) do { \
	var/lhs = ##a; \
	var/rhs = ##b; \
	if (lhs != rhs) { \
		return Fail("Expected [isnull(lhs) ? "null" : lhs] to be equal to [isnull(rhs) ? "null" : rhs].[message ? " [message]" : ""]", __FILE__, __LINE__); \
	} \
} while (FALSE)

/// Asserts that the two parameters passed are not equal, fails otherwise
/// Optionally allows an additional message in the case of a failure
#define TEST_ASSERT_NOTEQUAL(a, b, message) do { \
	var/lhs = ##a; \
	var/rhs = ##b; \
	if (lhs == rhs) { \
		return Fail("Expected [isnull(lhs) ? "null" : lhs] to not be equal to [isnull(rhs) ? "null" : rhs].[message ? " [message]" : ""]", __FILE__, __LINE__); \
	} \
} while (FALSE)

/// Waits, a tick at a time and for at most `max_ticks`, until `cond` holds. A positive assertion waits for the
/// condition itself (a loaded world skips kernel phases for several ticks); negative assertions keep a fixed wait.
#define OM_TEST_WAIT_UNTIL(cond, max_ticks) \
	for(var/om_wait_i in 1 to max_ticks) { \
		if(cond) { \
			break; \
		} \
		sleep(world.tick_lag); \
	}

/// *Only* run the test provided within the parentheses
/// This is useful for debugging when you want to reduce noise, but should never be pushed
/// Intended to be used in the manner of `TEST_FOCUS(/datum/unit_test/math)`
#define TEST_FOCUS(test_path) ##test_path { focus = TRUE; }

/// Logs a noticable message on GitHub, but will not mark as an error.
/// Use this when something shouldn't happen and is of note, but shouldn't block CI.
/// Does not mark the test as failed.
#define TEST_NOTICE(source, message) source.log_for_test((##message), "notice", __FILE__, __LINE__)

/// Constants indicating unit test completion status
#define UNIT_TEST_PASSED 0
#define UNIT_TEST_FAILED 1
#define UNIT_TEST_SKIPPED 2

/// Test tiers (the `tier` var on /datum/unit_test). The normal tier runs on every
/// integration merge (`dm-test`); exhaustive whole-type sweeps run in CI and
/// nightly (`dm-test --tier=all`), each with a small normal-tier representative.
/// A test named with --focus / dq_focused_test.sh runs whatever its tier.
#define TEST_TIER_NORMAL 0
#define TEST_TIER_EXHAUSTIVE 1
/// The E0 proofs (doc/rewrite/final_api.html section 19): fixtures that cannot pass until E1-E6 land. A plain run and --tier=all skip them,
/// so the normal suite stays green; `dm-test --tier=e0` or a focused run by name runs them (doc/testing.md "The E0 proofs").
#define TEST_TIER_E0 2

#define TEST_PRE 0
#define TEST_DEFAULT 1
/// After most test steps, used for tests that run long so shorter issues can be noticed faster
#define TEST_LONGER 10
/// This must be the one of last tests to run due to the inherent nature of the test iterating every single tangible atom in the game and qdeleting all of them (while taking long sleeps to make sure the garbage collector fires properly) taking a large amount of time.
#define TEST_CREATE_AND_DESTROY 9001
/**
 * For tests that rely on create and destroy having iterated through every (tangible) atom so they don't have to do something similar.
 * Keep in mind tho that create and destroy will absolutely break the test platform, anything that relies on its shape cannot come after it.
 */
#define TEST_AFTER_CREATE_AND_DESTROY INFINITY

/// Change color to red on ANSI terminal output, if enabled with -DANSICOLORS.
#ifdef ANSICOLORS
#define TEST_OUTPUT_RED(text) "\x1B\x5B1;31m[text]\x1B\x5B0m"
#else
#define TEST_OUTPUT_RED(text) (text)
#endif
/// Change color to green on ANSI terminal output, if enabled with -DANSICOLORS.
#ifdef ANSICOLORS
#define TEST_OUTPUT_GREEN(text) "\x1B\x5B1;32m[text]\x1B\x5B0m"
#else
#define TEST_OUTPUT_GREEN(text) (text)
#endif
/// Change color to yellow on ANSI terminal output, if enabled with -DANSICOLORS.
#ifdef ANSICOLORS
#define TEST_OUTPUT_YELLOW(text) "\x1B\x5B1;33m[text]\x1B\x5B0m"
#else
#define TEST_OUTPUT_YELLOW(text) (text)
#endif
/// A trait source when adding traits through unit tests
#define TRAIT_SOURCE_UNIT_TESTS "unit_tests"
/// Helper to allocate a new object with the implied type (the type of the variable it's assigned to) in the corner of the test room
#define EASY_ALLOCATE(arguments...) allocate(__IMPLIED_TYPE__, run_loc_floor_bottom_left, ##arguments)

// BEGIN_INCLUDE
#include "asset_smart_cache.dm"
#include "autowiki.dm"
#include "clothing_tests.dm"
#include "construction_tests.dm"
#include "cosmetic_tests.dm"
#include "type_list_tests.dm"
#include "dx_core_review_tests.dm"
#include "dx_core_tests.dm"
#include "dx_granted_verbs_tests.dm"
#include "dx_deps_tests.dm"
#include "dx_reactions_tests.dm"
#include "dq_a1_state_tests.dm"
#include "dx_reactions_work_tests.dm"
#include "dx_condition_tests.dm"
#include "decl_tests.dm"
#include "disease_tests.dm"
#include "dx_cap_breakable_tests.dm"
#include "dx_cap_cover_tests.dm"
#include "dx_cap_emag_tests.dm"
#include "dx_cap_lock_tests.dm"
#include "dx_cap_presets_tests.dm"
#include "dx_cap_panel_tests.dm"
#include "dx_cap_powered_tests.dm"
#include "dx_cap_wires_tests.dm"
#include "dx_cap_b2_library_tests.dm"
#include "dx_cap_checks_tests.dm"
#include "dx_cap_library_api_tests.dm"
#include "dq_test_overrides_tests.dm"
#include "dq_metrics_tests.dm"
#include "focus_only_tests.dm"
#include "font_awesome_icons.dm"
#include "genetics_tests.dm"
#include "interaction_tests.dm"
#include "language_tests.dm"
#include "loadout_tests.dm"
#include "map_tests.dm"
#include "mapping.dm"
#include "material_tests.dm"
#include "nuke_cinematic.dm"
#include "pai_tests.dm"
#include "preview_async_tests.dm"
#include "species_copy_ownership_tests.dm"
#include "mc_post_init_tests.dm"
#include "poster_tests.dm"
#include "special_roles.dm"
#include "preferences.dm"
#include "reagent_tests.dm"
#include "recipe_tests.dm"
#include "recycler_vendor_tests.dm"
#include "robot_tests.dm"
#include "slime_tests.dm"
#include "spritesheets.dm"
#include "sqlite_tests.dm"
#include "subsystem_init.dm"
#include "mc_boot_dependencies.dm"
#include "system_boot_dag.dm"
#include "system_membership.dm"
#include "kernel_cadence.dm"
#include "kernel_await.dm"
#include "kernel_latency.dm"
#include "kernel_loop.dm"
#include "kernel_periodic.dm"
#include "kernel_stages.dm"
#include "kernel_work.dm"
#include "kernel_test_clock.dm"
#include "kernel_inbox.dm"
#include "kernel_requests.dm"
#include "kernel_io.dm"
#include "kernel_sequence.dm"
#include "techwebs.dm"
#include "tgui_create_message.dm"
#include "trait_tests.dm"
#include "unit_test.dm"
#include "vbo_tests.dm"
#include "vore_tests.dm"
// DQ fork tests — need TEST_ASSERT* macros in scope, which are #undef'd at
// the bottom of this file.
#include "dq_c6_machine_parts_tests.dm"
#include "dq_atmos_tests.dm"
#include "dq_lifecycle_forms_tests.dm"
#include "dq_rust_integration_tests.dm"
#include "dq_native_tests.dm"
#include "dq_gas_arena_leak_tests.dm"
#include "dq_vg_binding_tests.dm"
#include "dq_heat_domain_tests.dm"
#include "dq_heat_api_tests.dm"
#include "dq_thermal_power_fixes_tests.dm"
#include "dq_performance_diagnostics_tests.dm"
#include "dq_audit_tests.dm"
#include "dq_bodyscanner_tests.dm"
#include "dq_diagnosis_tests.dm"
#include "dq_combat_ai_tests.dm"
#include "dq_ai_om_tests.dm"
#include "dq_economy_tests.dm"
#include "dq_contract_tests.dm"
#include "dq_debug_verb_gate_tests.dm"
#include "dq_expedition_tests.dm"
#include "dq_faction_reputation_tests.dm"
#include "dq_flight_operations_tests.dm"
#include "dq_generated_station_tests.dm"
#include "dq_generated_station_planner_tests.dm"
#include "dq_generated_station_room_definition_tests.dm"
#include "dq_generated_station_simulation_tests.dm"
#include "dq_generated_station_runtime_tests.dm"
#include "dq_generated_station_infrastructure_tests.dm"
#include "dq_generated_station_hardening_tests.dm"
#include "dq_generated_station_utility_tests.dm"
#include "dq_generated_station_director_tests.dm"
#include "dq_generated_station_defender_tests.dm"
#include "dq_generated_station_materializer_tests.dm"
#include "dq_generated_station_room_solver_tests.dm"
#include "dq_generated_station_architecture_tests.dm"
#include "dq_generated_station_rust_contract_tests.dm"
#include "dq_generated_station_objective_tests.dm"
#include "dq_focus.dm"
#include "dq_gc_tests.dm"
#include "dq_rust_memory_tests.dm"
#include "dq_medical_tests.dm"
#include "dq_mob_size_source_tests.dm"
#include "dq_mob_alpha_source_tests.dm"
#include "dq_robot_push_and_vtec_tests.dm"
#include "dq_denecrotizer_tests.dm"
#include "dq_event_headset_tests.dm"
#include "dq_pai_translator_tests.dm"
#include "dq_body_continuity_tests.dm"
#include "dq_body_effect_tests.dm"
#include "dq_mind_host_tests.dm"
#include "dq_mind_moves_tests.dm"
#include "dq_form_tests.dm"
#include "dq_protean_tests.dm"
#include "dq_body_factor_tests.dm"
#include "dq_body_slot_tests.dm"
#include "dq_armor_tests.dm"
#include "dq_harm_mitigation_tests.dm"
#include "dq_involuntary_emote_tests.dm"
#include "dq_propagation_tests.dm"
#include "dq_matter_snapshot.dm"
#include "dq_matter_tests.dm"
#include "dq_material_state_tests.dm"
#include "dq_property_tests.dm"
#include "dq_predicate_tests.dm"
#include "dq_constraint_tests.dm"
#include "dq_containment_tests.dm"
#include "dq_destroy_transaction_tests.dm"
#include "dq_decl_lifecycle_tests.dm"
#include "dq_lifecycle_diag_tests.dm"
#include "dq_inventory_tests.dm"
#include "dq_mob_memlist_tests.dm"
#include "dq_latent_tests.dm"
#include "dq_latency_policy_tests.dm"
#include "dq_rule_tests.dm"
#include "dq_h3_heat_tests.dm"
#include "dq_boot_bind_tests.dm"
#include "dq_h4_machine_heat_tests.dm"
#include "dq_containment_path_tests.dm"
#include "dq_pathfinder_tests.dm"
#include "dq_vore_slot_tests.dm"
#include "dq_c8a_occupant_slot_tests.dm"
#include "dq_mecha_dispatch_tests.dm"
#include "dq_storage_tests.dm"
#include "dq_stock_tests.dm"
#include "dq_breakpoint_tests.dm"
#include "dq_damage_packet_tests.dm"
#include "dq_explosion_batch_tests.dm"
#include "dq_materialize_batch_tests.dm"
#include "dq_map_load_job_tests.dm"
#include "dq_turf_damage_tests.dm"
#include "dq_integrity_pool_tests.dm"
#include "dq_mech_body_tests.dm"
#include "dq_ownership_tests.dm"
#include "dq_ownership_transfer_tests.dm"
#include "dq_destroy_guard_tests.dm"
#include "dq_pool_tests.dm"
#include "dq_foundation_look_tests.dm"
#include "dq_robot_machine_tests.dm"
#include "dq_b4_tracking_tests.dm"
#include "dq_phase0_tests.dm"
#include "dq_life_om_tests.dm"
#include "dq_medical_damage_model_tests.dm"
#include "dq_medical_p0_tests.dm"
#include "dq_medical_p1_tests.dm"
#include "dq_medical_med7_own_tests.dm"
#include "dq_medical_med7_expo_tests.dm"
#include "dq_medical_med8_tests.dm"
#include "dq_medical_k_c_tests.dm"
#include "dq_medical_k_a_tests.dm"
#include "dq_medical_k_b_tests.dm"
#include "dq_mutation_tests.dm"
#include "dq_dna_storage_tests.dm"
#include "dq_lesion_tests.dm"
#include "dq_stabilisation_tests.dm"
#include "dq_vital_systems_tests.dm"
#include "dq_contagion_tests.dm"
#include "dq_physiology_tests.dm"
#include "dq_melee_swing_tests.dm"
#include "dq_movement_tests.dm"
#include "dq_material_science_tests.dm"
#include "dq_preferences_tests.dm"
#include "dq_shuttle_tests.dm"
#include "dq_state_tests.dm"
#include "dq_sys_loot_tests.dm"
#include "dq_lifecycle_tests.dm"
#include "dq_lifecycle_declared_kinds_tests.dm"
#include "dq_lifecycle_verb_tests.dm"
#include "dq_verb_framework_tests.dm"
#include "dq_surgery_tests.dm"
#include "dq_sys_fields_tests.dm"
#include "dq_wires_tests.dm"
#include "dq_quick_fix_tests.dm"
#include "dq_om_world_watch_tests.dm"
#include "dq_live_sim_tests.dm"
#include "dq_om_fields_tests.dm"
#include "dx_ui_validators_tests.dm"
#include "dq_om_key_tests.dm"
#include "dq_om_periodic_tests.dm"
#include "dq_world_lanes_tests.dm"
#include "dq_world_lanes_f3_tests.dm"
#include "dq_power_tests.dm"
#include "dq_om_wake_tests.dm"
#include "dq_actor_adapter_tests.dm"
#include "dq_combat_mode_tests.dm"
#include "dq_interact_cleanup_tests.dm"
#include "dq_input_tests.dm"
#include "dq_i7_bulk_capture.dm"
#include "dq_i7_structures_bulk_capture.dm"
#include "dq_i7_items_bulk_capture.dm"
#include "dq_compact_interaction_tests.dm"
#include "dq_interaction_tests.dm"
#include "dq_interaction_entry_tests.dm"
#include "dx_cap_anchor_tests.dm"
#include "dx_cap_assembly_tests.dm"
#include "dx_cap_block_tests.dm"
#include "dx_cap_buckle_tests.dm"
#include "dx_cap_climb_tests.dm"
#include "dx_cap_drinkable_tests.dm"
#include "dx_cap_edible_tests.dm"
#include "dx_cap_embed_tests.dm"
#include "dx_cap_entries_tests.dm"
#include "dx_operations_tests.dm"
#include "dx_op_resolution_tests.dm"
#include "dx_cap_item_entries_tests.dm"
#include "dx_cap_label_tests.dm"
#include "dx_cap_reach_tests.dm"
#include "dx_cap_rotate_tests.dm"
#include "dx_cap_sharp_tests.dm"
#include "dx_cap_signaler_tests.dm"
#include "dx_cap_smokable_tests.dm"
#include "dx_cap_stamp_target_tests.dm"
#include "dx_cap_toggle_state_tests.dm"
#include "dx_cap_tool_tests.dm"
#include "dx_cap_two_handed_tests.dm"
#include "dx_cap_writable_tests.dm"
#include "dq_ability_tests.dm"
#include "dq_sys_sfx_tests.dm"
#include "dq_sys_grants_tests.dm"
#include "dq_tool_tests.dm"
#include "dq_construction_tests.dm"
#include "dq_capability_construction_tests.dm"
#include "dq_construction_mech_tests.dm"
#include "dq_construction_assembly_tests.dm"
#include "dq_memory_list_tests.dm"
#include "dq_automation_tests.dm"
#include "xgm_total_moles_test.dm"
#include "dq_w6_critical_tests.dm"
#include "dq_om_core_tests.dm"
#include "dq_tgui_client_tests.dm"
#include "dq_tgui_status_tests.dm"
#include "dq_shared_cache_tests.dm"
#include "dq_material_tree_tests.dm"
#include "dq_sys_hygiene_tests.dm"
#include "dq_sys_emag_tests.dm"
#include "dq_sys_requirements_tests.dm"
#include "dq_cap_slot_tests.dm"
#include "dq_sys_tables_tests.dm"
#include "dq_sys_ui_tests.dm"
#include "dq_sys_topic_tests.dm"
#include "dq_sys_messages_tests.dm"
#include "dq_om_core_fix_tests.dm"
#include "dq_om_pipeline_tests.dm"
#include "dq_om_relations_tests.dm"
#include "dq_om_scheduler_tests.dm"
#include "dq_om_lane_isolation_tests.dm"
#include "dq_om_io_tests.dm"
#include "dq_om_ask_tests.dm"
#include "dq_sys_damage_reactions_tests.dm"
#include "dq_sys_appearance_tests.dm"
#include "dq_sys_expiry_tests.dm"
#include "dq_periodic_autoclear_tests.dm"
#include "dq_sys_periodic_tests.dm"
#include "dq_flow_io_tests.dm"
#include "dq_refs_tests.dm"
#include "dq_om_timed_action_tests.dm"
#include "dq_base_proc_moves_tests.dm"
#include "dq_harm_time_invariance_tests.dm"
#include "dq_w5_loose_tests.dm"
#include "dq_vital_lifecycle_tests.dm"
#include "../balance/_balance_harness.dm"
#include "../balance/balance_scenarios.dm"
#include "dq_balance_harness_tests.dm"
#include "dq_part_lifecycle_tests.dm"
#include "dq_organ_slot_tests.dm"
#include "dx_cap_cell_holder_tests.dm"
#include "interim_actor_propagation.dm"
#include "interim_armor_lifecycle.dm"
#include "interim_autopsy_actor.dm"
#include "interim_beam_lifecycle.dm"
#include "interim_blueprint_actor.dm"
#include "interim_charger_feed.dm"
#include "interim_construction_doors.dm"
#include "interim_construction_interruptions.dm"
#include "interim_construct_spell_actor.dm"
#include "interim_device_lifecycle.dm"
#include "interim_economy_actor.dm"
#include "interim_ethanol_actor.dm"
#include "interim_experiment_actor.dm"
#include "interim_food_consumption.dm"
#include "interim_hud_actor.dm"
#include "interim_mindbinder_actor.dm"
#include "interim_mecha_extinguisher_actor.dm"
#include "interim_power_reagents.dm"
#include "interim_pull_actor.dm"
#include "interim_reagent_pour.dm"
#include "interim_resleever_actor.dm"
#include "interim_implantchair_actor.dm"
#include "interim_rig_wire_actor.dm"
#include "interim_spell_range_actor.dm"
#include "interim_candle_actor.dm"
#include "interim_glove_touch_actor.dm"
#include "interim_marker_beacon_lifecycle.dm"
#include "interim_pda_removal.dm"
#include "interim_energy_net_lifecycle.dm"
#include "interim_lathe_wire_actor.dm"
#include "interim_lego_lifecycle.dm"
#include "interim_wire_actor.dm"
#include "interim_frame_finalization.dm"
#include "interim_implant_actor.dm"
#include "interim_console_finalization.dm"
#include "interim_scope_actor.dm"
#include "interim_smokable_lifecycle.dm"
#include "interim_storage_lifecycle.dm"
#include "interim_wrapped_present_lifecycle.dm"
#include "dq_kernel_measure_tests.dm"
#include "dq_e0_proofs_tests.dm"
#include "dq_e1_declare_tests.dm"
#include "dq_e3_stats_tests.dm"
#include "dq_e4_actions_tests.dm"
#include "dq_e2_parts_tests.dm"
#include "dq_lib_tests.dm"
#include "dq_p1_close_tests.dm"
#include "dq_p2_library_tests.dm"
#include "dq_p2_engine_tests.dm"
#include "dq_p2_apc_behaviour.dm"
#include "dq_p2_chargers_behaviour.dm"
#include "dq_p2_smes_behaviour.dm"
#include "dq_p2_batteryrack_behaviour.dm"
#include "dq_p2_vending_behaviour.dm"
#include "dq_p2_door_behaviour.dm"
#include "dq_p2_door_base_tests.dm"
#include "dq_p2_table_behaviour.dm"
#include "dq_p2_reagent_behaviour.dm"
#include "dq_p2_reagent_spray_behaviour.dm"
#include "dq_p2_lights_behaviour.dm"
#include "dq_p2_reagent_needle_behaviour.dm"
#include "dq_p2_storage_behaviour.dm"
#include "dq_p2_storage_engine_tests.dm"
#include "dq_eg2_wait_tests.dm"
#include "dq_p2_reagent_pill_behaviour.dm"
#include "dq_p2_reagent_hypo_behaviour.dm"
#include "dq_p2_reagent_misc_behaviour.dm"
#include "dq_p2_reagent_rag_behaviour.dm"
#include "dq_eg2_gap_tests.dm"
#include "dq_p2_reagent_drink_behaviour.dm"
#include "dq_s1_slots_tests.dm"
#include "interim_fax_actor.dm"
#include "interim_crystal_consumption.dm"
#include "interim_prerelease_consequences.dm"
#include "interim_robobag_tag_spill.dm"
#include "interim_heavy_cable_replacement.dm"
#include "interim_id_cache.dm"
#include "interim_airlock_history.dm"
#include "interim_stasis_cage_deletion.dm"
#include "interim_gargoyle_deletion.dm"
#include "interim_aiming_relationships.dm"
#include "interim_clamp_deletion.dm"
#include "interim_hailer_mask_lifecycle.dm"
#include "interim_storage_hud_item_cleanup.dm"
#include "interim_selection_kit_lifecycle.dm"
#include "interim_pipe_meter_replacement.dm"
#include "interim_gunbox_lifecycle.dm"
#include "interim_bodybag_lifecycle.dm"
#include "interim_windoor_completion.dm"
#include "interim_windoor_dismantle.dm"
#include "interim_cryobag_injector.dm"
#include "interim_butterfly_assembly.dm"
#include "interim_turret_frame_completion.dm"
#include "interim_airlock_dismantle.dm"
#include "interim_locket_keepsake.dm"
#include "interim_tvassembly_devices.dm"
#include "interim_chem_grenade_beaker.dm"
#include "interim_firedoor_board_consumption.dm"
#include "interim_guest_access_alias.dm"
#include "interim_microscope_insertion.dm"
#include "interim_refill_vendor_matching.dm"
#include "interim_turret_sensor_consumption.dm"
#include "interim_shadekin_variant_grants.dm"
#include "interim_dnaforensics_insertion.dm"
#include "interim_circle_explicit_center.dm"
#include "interim_adminpaper_actor.dm"
#include "interim_pai_card_lifecycle.dm"
#include "interim_floor_light_lifecycle.dm"
#include "interim_pda_signal_actor.dm"
#include "interim_deadringer_deletion.dm"
#include "interim_bottle_smash_lifecycle.dm"
#include "interim_ic_signal_recipient.dm"
#include "interim_reagent_scaled_capacity.dm"
#include "interim_entopic_deletion.dm"
#include "interim_appearance_callback_actor.dm"
#include "interim_energy_arrow_lifecycle.dm"
#include "interim_clown_egg_actor.dm"
#include "interim_suspension_generator_deletion.dm"
#include "interim_cap_projectile_lifecycle.dm"
#include "interim_accessory_modifier_registry_deletion.dm"
#include "interim_ghost_pod_opening_actor.dm"
#include "interim_looking_glass_console_deletion.dm"
#include "interim_manual_passenger_actor.dm"
#include "interim_crossbow_rod_lifecycle.dm"
#include "interim_magic_staff_actor.dm"
#include "interim_frost_carrier_lifecycle.dm"
#include "interim_artifact_blade_deletion.dm"
#include "interim_iv_drip_dismantle.dm"
#include "interim_flight_assignment_deletion.dm"
#include "interim_fake_death_reagent_removal.dm"
#include "interim_one_pizza_lifecycle.dm"
#include "interim_bookcase_lifecycle.dm"
#include "interim_camera_wire_actor.dm"
#include "interim_machine_salvage_lifecycle.dm"
#include "interim_containment_field_deletion.dm"
#include "interim_air_alarm_wire_actor.dm"
#include "interim_range_explicit_center.dm"
#include "interim_snowman_lifecycle.dm"
#include "interim_bed_lifecycle.dm"
#include "interim_particle_wire_actor.dm"
#include "interim_email_actor.dm"
#include "interim_gravemarker_lifecycle.dm"
#include "interim_barricade_dismantle.dm"
#include "interim_floor_dismantle.dm"
#include "interim_telecrystal_release_validation.dm"
#include "interim_syringe_container_doses.dm"
#include "interim_cell_gradual_charge.dm"
#include "interim_picnic_blanket_actor.dm"
#include "interim_spell_explicit_caster.dm"
#include "interim_girder_windoor_recovery.dm"
#include "interim_emitter_emag_lock.dm"
#include "interim_crate_cage_recovery.dm"
#include "interim_vote_actor.dm"
#include "interim_storage_sticky_inventory.dm"
#include "interim_lowwall_egg_recovery.dm"
#include "interim_crate_opener_actor.dm"
#include "interim_apc_cell_inventory.dm"
#include "interim_flora_removal.dm"
#include "interim_computer_program_actor.dm"
#include "interim_frame_component_removal.dm"
#include "interim_stool_recovery.dm"
#include "interim_airlock_assembly_wiring.dm"
#include "interim_airlock_assembly_glass.dm"
#include "interim_adminpaper_write_actor.dm"
#include "interim_flag_removal.dm"
#include "interim_reagent_implant_transfer_actor.dm"
#include "interim_curtain_grave_removal.dm"
#include "interim_girder_reinforcement_dose.dm"
#include "interim_talisman_supply_actor.dm"
#include "interim_statue_endings.dm"
#include "interim_dropper_container_dose.dm"
#include "interim_event_queue_actor.dm"
#include "interim_projectile_endings.dm"
#include "interim_beaker_lid_transfer.dm"
#include "interim_remote_button_emag.dm"
#include "interim_type_picker_actor.dm"
#include "interim_cleanup_validation.dm"
#include "interim_sheet_sign_consumption.dm"
#include "interim_water_tank_refill.dm"
#include "interim_airlock_unpowered_motion.dm"
#include "interim_surplus_redemption.dm"
#include "interim_mine_endings.dm"
// END_INCLUDE
#if defined(BENCHMARK) || defined(SPACEMAN_DMM)
#include "../benchmarks/_benchmark.dm"
#include "../benchmarks/scenarios.dm"
#include "../benchmarks/boot_profile.dm"
#include "../benchmarks/om_dispatch.dm"
#include "../benchmarks/shared_cache.dm"
#include "../benchmarks/life_sweep.dm"
#include "../benchmarks/life_sweep_adapter.dm"
#include "../benchmarks/life_sequence.dm"
#include "../benchmarks/dx_refresh.dm"
#include "../benchmarks/dx_deps.dm"
#include "../benchmarks/op_resolve.dm"
#include "../benchmarks/apc_flip.dm"
#include "../benchmarks/kernel_metrics.dm"
#include "../balance/balance_benchmark.dm"
#endif
#ifdef REFERENCE_TRACKING_DEBUG //Don't try and parse this file if ref tracking isn't turned on. IE: don't parse ref tracking please mr linter
#include "find_reference_sanity.dm"
#endif

#undef TEST_ASSERT
#undef TEST_ASSERT_EQUAL
#undef TEST_ASSERT_NOTEQUAL
//#undef TEST_FOCUS - This define is used by vscode unit test extension to pick specific unit tests to run and appended later so needs to be used out of scope here
#endif
