/datum/unit_test/dq_generated_station_dependency_simulation

/datum/unit_test/dq_generated_station_dependency_simulation/Run()
	var/datum/generated_station_planner/planner = new
	var/datum/generated_station_spec/spec = planner.plan(42)
	var/datum/generated_station_simulation/simulation = new(spec)
	TEST_ASSERT_EQUAL(simulation.department_state("medical-1"), GENERATED_DEPARTMENT_OPERATIONAL, "Medical did not start operational")
	TEST_ASSERT_EQUAL(simulation.department_state("ai-1"), GENERATED_DEPARTMENT_OPERATIONAL, "AI did not start operational")
	TEST_ASSERT_EQUAL(simulation.department_state("security-1"), GENERATED_DEPARTMENT_OPERATIONAL, "Security did not start operational")
	simulation.set_integrity("engineering-1", 0)
	TEST_ASSERT(!simulation.capability_available("power"), "Destroyed Engineering still provided power")
	TEST_ASSERT_EQUAL(simulation.department_state("medical-1"), GENERATED_DEPARTMENT_OFFLINE, "Medical remained online without Engineering power")
	TEST_ASSERT_EQUAL(simulation.department_state("ai-1"), GENERATED_DEPARTMENT_OFFLINE, "AI remained online without Engineering power")
	TEST_ASSERT_EQUAL(simulation.department_state("security-1"), GENERATED_DEPARTMENT_OFFLINE, "Security remained online without Engineering power/data")
	simulation.set_integrity("engineering-1", 100)
	TEST_ASSERT_EQUAL(simulation.department_state("medical-1"), GENERATED_DEPARTMENT_OPERATIONAL, "Dependency restoration did not immediately wake Medical")
	simulation.set_integrity("medical-1", 25)
	TEST_ASSERT_EQUAL(simulation.department_state("medical-1"), GENERATED_DEPARTMENT_DEGRADED, "Damaged but supplied Medical did not enter its degraded state")
	simulation.set_integrity("medical-1", 100)
	qdel(simulation)
	qdel(spec)
	qdel(planner)

/datum/unit_test/dq_generated_station_stockpile_propagation

/datum/unit_test/dq_generated_station_stockpile_propagation/Run()
	var/datum/generated_station_planner/planner = new
	var/datum/generated_station_spec/spec = planner.plan(84)
	var/datum/generated_station_simulation/simulation = new(spec)
	simulation.set_stockpile("logistics-1", "supplies", 0)
	TEST_ASSERT_EQUAL(simulation.department_state("logistics-1"), GENERATED_DEPARTMENT_OFFLINE, "Empty Logistics stockpile did not take it offline")
	TEST_ASSERT_EQUAL(simulation.department_state("engineering-1"), GENERATED_DEPARTMENT_OFFLINE, "Logistics loss did not propagate to Engineering")
	TEST_ASSERT_EQUAL(simulation.department_state("medical-1"), GENERATED_DEPARTMENT_OFFLINE, "Logistics cascade did not reach Medical")
	simulation.add_stockpile("logistics-1", "supplies", 10)
	TEST_ASSERT_EQUAL(simulation.department_state("engineering-1"), GENERATED_DEPARTMENT_OPERATIONAL, "Restocking Logistics did not restore Engineering")
	simulation.set_stockpile("medical-1", "medicine", 0)
	TEST_ASSERT_EQUAL(simulation.department_state("medical-1"), GENERATED_DEPARTMENT_OFFLINE, "Medical ignored its finite medicine stockpile")
	TEST_ASSERT_EQUAL(simulation.department_state("engineering-1"), GENERATED_DEPARTMENT_OPERATIONAL, "Medical stock loss incorrectly disabled Engineering")
	simulation.set_stockpile("medical-1", "medicine", 1)
	TEST_ASSERT(simulation.consume_stockpile("medical-1", "medicine", 1), "Finite Medical stock could not be consumed by explicit work")
	TEST_ASSERT_EQUAL(simulation.department_state("medical-1"), GENERATED_DEPARTMENT_OFFLINE, "Consumed Medical stock did not immediately take the department offline")
	qdel(simulation)
	qdel(spec)
	qdel(planner)
