/datum/unit_test/dq_generated_station_ai_loss_preserves_local_response

/datum/unit_test/dq_generated_station_ai_loss_preserves_local_response/Run()
	var/datum/generated_station_planner/planner = new
	var/datum/generated_station_spec/spec = planner.plan(24680)
	var/datum/generated_station_simulation/simulation = new(spec)
	var/datum/generated_station_director/director = new(simulation)
	var/datum/generated_station_squad/security = director.create_squad("security-1")
	TEST_ASSERT_NOTNULL(security, "Security squad was not created")
	TEST_ASSERT(security.add_member("officer-1"), "Security squad rejected its first finite member")
	var/datum/generated_station_knowledge_report/initial = director.submit_report("medical-1", "patient-zero", "hazard", "Contagious patient", 90)
	TEST_ASSERT(director.globally_knows(initial.id), "Operational AI did not propagate knowledge globally")
	TEST_ASSERT(director.department_knows("security-1", initial.id), "Operational AI did not share knowledge with Security")
	var/datum/generated_station_order/global_order = director.issue_order(security.id, initial.id, "contain", TRUE)
	TEST_ASSERT_NOTNULL(global_order, "Operational AI could not coordinate a global response")
	director.complete_order(global_order.id)
	simulation.set_integrity("ai-1", 0)
	director.on_capabilities_changed()
	var/datum/generated_station_knowledge_report/local = director.submit_report("security-1", "intruder-2", "contact", "Intruder in Security", 75)
	TEST_ASSERT(director.department_knows("security-1", local.id), "AI loss erased Security's local observation")
	TEST_ASSERT(!director.globally_knows(local.id), "AI loss still allowed a new report into global knowledge")
	TEST_ASSERT(!director.department_knows("medical-1", local.id), "AI loss still propagated Security knowledge to Medical")
	TEST_ASSERT_NULL(director.issue_order(security.id, local.id, "intercept", TRUE), "AI loss still allowed global squad coordination")
	TEST_ASSERT_NOTNULL(director.issue_order(security.id, local.id, "intercept", FALSE), "AI loss prevented a department-local response")
	qdel(director)
	qdel(simulation)
	qdel(spec)
	qdel(planner)

/datum/unit_test/dq_generated_station_disconnection_isolates_knowledge

/datum/unit_test/dq_generated_station_disconnection_isolates_knowledge/Run()
	var/datum/generated_station_planner/planner = new
	var/datum/generated_station_spec/spec = planner.plan(13579)
	var/datum/generated_station_simulation/simulation = new(spec)
	var/datum/generated_station_director/director = new(simulation)
	director.set_department_connected("medical-1", FALSE)
	var/datum/generated_station_knowledge_report/report = director.submit_report("medical-1", "casualty-1", "medical", "Local casualty", 80)
	TEST_ASSERT(director.department_knows("medical-1", report.id), "Disconnected Medical lost its local report")
	TEST_ASSERT(!director.globally_knows(report.id), "Disconnected Medical published to strategic knowledge")
	director.set_department_connected("medical-1", TRUE)
	TEST_ASSERT(director.globally_knows(report.id), "Reconnected Medical did not publish its still-valid report")
	qdel(director)
	qdel(simulation)
	qdel(spec)
	qdel(planner)
