/**
 * I7: bulk domain snapshot for the items domain converted to interaction entries
 * (roadmap I7, doc/rewrite/interactions.md section 13). One snapshot covering every
 * converted item type, generated from the resolver's actual current output, the
 * same technique as dq_i7_bulk_capture.dm / dq_i7_structures_bulk_capture.dm for the
 * machinery and structures domains. Grows as more items subdomains are converted.
 */
/datum/unit_test/dq_interaction_domain_snapshot/i7_items_bulk
	snapshot_types = list(
		/obj/item/assembly,
		/obj/item/assembly/voice,
		/obj/item/assembly/igniter,
		/obj/item/assembly/shock_kit,
		/obj/item/assembly/mousetrap,
		/obj/item/assembly_holder,
		/obj/item/assembly/signaler,
		/obj/item/assembly/infra,
		/obj/item/nifrepairer,
		/obj/item/aicard,
		/obj/item/binoculars,
		/obj/item/bodysnatcher,
		/obj/item/chameleon,
		/obj/effect/dummy/chameleon,
		/obj/item/defib_kit,
		/obj/item/emergency_beacon,
		/obj/item/extrapolator,
		/obj/item/communicator,
	)
	expected = list(
		"/obj/item/assembly|human|none => gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly|robot|none => gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly|ai|none => |",
		"/obj/item/assembly|ghost|none => |",
		"/obj/item/assembly/voice|human|none => gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/voice|robot|none => gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/voice|ai|none => |",
		"/obj/item/assembly/voice|ghost|none => |",
		"/obj/item/assembly/igniter|human|none => gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/igniter|robot|none => gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/igniter|ai|none => |",
		"/obj/item/assembly/igniter|ghost|none => |",
		"/obj/item/assembly/shock_kit|human|none => gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/shock_kit|robot|none => gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/shock_kit|ai|none => |",
		"/obj/item/assembly/shock_kit|ghost|none => |",
		"/obj/item/assembly/mousetrap|human|none => mousetrap_hand,gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/mousetrap|robot|none => mousetrap_hand,gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/mousetrap|ai|none => |",
		"/obj/item/assembly/mousetrap|ghost|none => |",
		"/obj/item/assembly_holder|human|none => assembly_holder_hand|assembly_holder_self:must be held in hand",
		"/obj/item/assembly_holder|robot|none => assembly_holder_hand|assembly_holder_self:must be held in hand",
		"/obj/item/assembly_holder|ai|none => |",
		"/obj/item/assembly_holder|ghost|none => |",
		"/obj/item/assembly/signaler|human|none => gen_item_interaction_transfer,gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/signaler|robot|none => gen_item_interaction_transfer,gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/signaler|ai|none => |",
		"/obj/item/assembly/signaler|ghost|none => |",
		"/obj/item/assembly/infra|human|none => gen_hand_interaction_hand,gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/infra|robot|none => gen_hand_interaction_hand,gen_item_interaction_item|gen_use_interaction_self:must be held in hand",
		"/obj/item/assembly/infra|ai|none => |",
		"/obj/item/assembly/infra|ghost|none => |",
		"/obj/item/nifrepairer|human|none => gen_item_interaction_item_03f9d14fb3051a3f15d442ad85fd3ea2|",
		"/obj/item/nifrepairer|robot|none => gen_item_interaction_item_03f9d14fb3051a3f15d442ad85fd3ea2|",
		"/obj/item/nifrepairer|ai|none => |",
		"/obj/item/nifrepairer|ghost|none => |",
		"/obj/item/aicard|human|none => |gen_use_interaction_self_6e372e0966251f5fefd5a827a44cf31f:must be held in hand",
		"/obj/item/aicard|robot|none => |gen_use_interaction_self_6e372e0966251f5fefd5a827a44cf31f:must be held in hand",
		"/obj/item/aicard|ai|none => |",
		"/obj/item/aicard|ghost|none => |",
		"/obj/item/binoculars|human|none => |gen_use_zoom:must be held in hand",
		"/obj/item/binoculars|robot|none => |gen_use_zoom:must be held in hand",
		"/obj/item/binoculars|ai|none => |",
		"/obj/item/binoculars|ghost|none => |",
		"/obj/item/bodysnatcher|human|none => |gen_use_interaction_self_1a96b2de68aecdb078b977c2552b5ed8:must be held in hand",
		"/obj/item/bodysnatcher|robot|none => |gen_use_interaction_self_1a96b2de68aecdb078b977c2552b5ed8:must be held in hand",
		"/obj/item/bodysnatcher|ai|none => |",
		"/obj/item/bodysnatcher|ghost|none => |",
		"/obj/item/chameleon|human|none => |gen_use_toggle:must be held in hand",
		"/obj/item/chameleon|robot|none => |gen_use_toggle:must be held in hand",
		"/obj/item/chameleon|ai|none => |",
		"/obj/item/chameleon|ghost|none => |",
		"/obj/effect/dummy/chameleon|human|none => gen_item_interaction_disrupt,gen_hand_interaction_disrupt|",
		"/obj/effect/dummy/chameleon|robot|none => gen_item_interaction_disrupt,gen_hand_interaction_disrupt|",
		"/obj/effect/dummy/chameleon|ai|none => |",
		"/obj/effect/dummy/chameleon|ghost|none => |",
		"/obj/item/defib_kit|human|none => gen_hand_interaction_hand_39a0685b47ad3999892e03f7ccd142d4,gen_item_interaction_item_07321daa6ae96278c1f244c2e7aab928|",
		"/obj/item/defib_kit|robot|none => gen_hand_interaction_hand_39a0685b47ad3999892e03f7ccd142d4,gen_item_interaction_item_07321daa6ae96278c1f244c2e7aab928|",
		"/obj/item/defib_kit|ai|none => |",
		"/obj/item/defib_kit|ghost|none => |",
		"/obj/item/emergency_beacon|human|none => gen_hand_interaction_hand_282e7e4c9833c52dfd2b935325882034,gen_item_interaction_item_548cad8246f7619f68a79f09922b6ea2|gen_use_interaction_self_fd634edf8dd967a0cdb5e9fd826e2753:must be held in hand",
		"/obj/item/emergency_beacon|robot|none => gen_hand_interaction_hand_282e7e4c9833c52dfd2b935325882034,gen_item_interaction_item_548cad8246f7619f68a79f09922b6ea2|gen_use_interaction_self_fd634edf8dd967a0cdb5e9fd826e2753:must be held in hand",
		"/obj/item/emergency_beacon|ai|none => |",
		"/obj/item/emergency_beacon|ghost|none => |",
		"/obj/item/extrapolator|human|none => |gen_insert_interaction_item:needs a scanning module,gen_use_interaction_self_88f0a87a7957e99d05c16122f655af19:must be held in hand",
		"/obj/item/extrapolator|robot|none => |gen_insert_interaction_item:needs a scanning module,gen_use_interaction_self_88f0a87a7957e99d05c16122f655af19:must be held in hand",
		"/obj/item/extrapolator|ai|none => |",
		"/obj/item/extrapolator|ghost|none => |",
		"/obj/item/extrapolator|human|/obj/item/stock_parts/scanning_module => gen_insert_interaction_item|gen_use_interaction_self_88f0a87a7957e99d05c16122f655af19:must be held in hand",
		"/obj/item/communicator|human|none => gen_alt_interaction_alt,gen_item_interaction_item_bced019bd1e51b232b4daf0ac8685faf|gen_use_interaction_self_a48c9cd63143312e6b479fb34ecf8b51:must be held in hand",
		"/obj/item/communicator|robot|none => gen_alt_interaction_alt,gen_item_interaction_item_bced019bd1e51b232b4daf0ac8685faf|gen_use_interaction_self_a48c9cd63143312e6b479fb34ecf8b51:must be held in hand",
		"/obj/item/communicator|ai|none => |",
		"/obj/item/communicator|ghost|none => |",
	)
