/**
 * I7: bulk domain snapshot for the items domain converted to interaction entries
 * (roadmap I7, doc/rewrite/interactions.md section 13). One snapshot covering every
 * converted item type, generated from the resolver's actual current output, the
 * same technique as dq_i7_bulk_capture.dm / dq_i7_structures_bulk_capture.dm for the
 * machinery and structures domains. Grows as more items subdomains are converted.
 */
/datum/unit_test/dq_interaction_domain_snapshot/i7_items_bulk
	snapshot_types = list(
		/obj/item/assembly,
		/obj/item/assembly/voice,
		/obj/item/assembly/igniter,
		/obj/item/assembly/shock_kit,
		/obj/item/assembly/mousetrap,
		/obj/item/assembly_holder,
		/obj/item/assembly/signaler,
		/obj/item/assembly/infra,
		/obj/item/nifrepairer,
		/obj/item/aicard,
		/obj/item/binoculars,
		/obj/item/bodysnatcher,
		/obj/item/chameleon,
		/obj/effect/dummy/chameleon,
		/obj/item/defib_kit,
		/obj/item/emergency_beacon,
		/obj/item/extrapolator,
		/obj/item/communicator,
	)
	expected = list(
		"/obj/item/assembly|human|none => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly|robot|none => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/assembly|ghost|none => |",
		"/obj/item/assembly|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly|human|/obj/item/storage => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/assembly/voice|human|none => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/voice|robot|none => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/voice|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/assembly/voice|ghost|none => |",
		"/obj/item/assembly/voice|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/voice|human|/obj/item/storage => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/assembly/igniter|human|none => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/igniter|robot|none => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/igniter|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/assembly/igniter|ghost|none => |",
		"/obj/item/assembly/igniter|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/igniter|human|/obj/item/storage => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/assembly/shock_kit|human|none => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/shock_kit|robot|none => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/shock_kit|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/assembly/shock_kit|ghost|none => |",
		"/obj/item/assembly/shock_kit|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/shock_kit|human|/obj/item/storage => gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/assembly/mousetrap|human|none => mousetrap_hand,gen_verb_mousetrap_hide_under_effect,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/mousetrap|robot|none => mousetrap_hand,gen_verb_mousetrap_hide_under_effect,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/mousetrap|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/assembly/mousetrap|ghost|none => |",
		"/obj/item/assembly/mousetrap|human|/obj/item/kit => gen_insert_interaction_kit_customize,mousetrap_hand,gen_verb_mousetrap_hide_under_effect,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/mousetrap|human|/obj/item/storage => mousetrap_hand,gen_verb_mousetrap_hide_under_effect,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/assembly_holder|human|none => assembly_holder_hand,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,assembly_holder_self:must be held in hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly_holder|robot|none => assembly_holder_hand,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,assembly_holder_self:must be held in hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly_holder|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/assembly_holder|ghost|none => |",
		"/obj/item/assembly_holder|human|/obj/item/kit => gen_insert_interaction_kit_customize,assembly_holder_hand,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|assembly_holder_self:must be held in hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly_holder|human|/obj/item/storage => assembly_holder_hand,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,assembly_holder_self:must be held in hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/assembly/signaler|human|none => gen_item_interaction_transfer,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_verb_deadman_it_effect:you need to be carrying it,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/signaler|robot|none => gen_item_interaction_transfer,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_verb_deadman_it_effect:you need to be carrying it,gen_use_interaction_self:not in your hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/signaler|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/assembly/signaler|ghost|none => |",
		"/obj/item/assembly/signaler|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_item_interaction_transfer,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_verb_deadman_it_effect:you need to be carrying it,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/signaler|human|/obj/item/storage => gen_item_interaction_transfer,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_verb_deadman_it_effect:you need to be carrying it,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/assembly/infra|human|none => gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/infra|robot|none => gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/infra|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/assembly/infra|ghost|none => |",
		"/obj/item/assembly/infra|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/assembly/infra|human|/obj/item/storage => gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/nifrepairer|human|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/nifrepairer|robot|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/nifrepairer|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/nifrepairer|ghost|none => |",
		"/obj/item/nifrepairer|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/nifrepairer|human|/obj/item/storage => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/aicard|human|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/aicard|robot|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/aicard|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/aicard|ghost|none => |",
		"/obj/item/aicard|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/aicard|human|/obj/item/storage => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/binoculars|human|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/binoculars|robot|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/binoculars|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/binoculars|ghost|none => |",
		"/obj/item/binoculars|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/binoculars|human|/obj/item/storage => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/bodysnatcher|human|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/bodysnatcher|robot|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/bodysnatcher|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/bodysnatcher|ghost|none => |",
		"/obj/item/bodysnatcher|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/bodysnatcher|human|/obj/item/storage => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/chameleon|human|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/chameleon|robot|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/chameleon|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/chameleon|ghost|none => |",
		"/obj/item/chameleon|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/chameleon|human|/obj/item/storage => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/effect/dummy/chameleon|human|none => gen_item_interaction_disrupt,gen_hand_interaction_disrupt|gen_insert_interaction_pass:needs a mop,gen_insert_interaction_pass:needs a soap",
		"/obj/effect/dummy/chameleon|robot|none => gen_item_interaction_disrupt,gen_hand_interaction_disrupt|gen_insert_interaction_pass:needs a mop,gen_insert_interaction_pass:needs a soap",
		"/obj/effect/dummy/chameleon|ai|none => |",
		"/obj/effect/dummy/chameleon|ghost|none => |",
		"/obj/effect/dummy/chameleon|human|/obj/item/mop_deploy => gen_item_interaction_disrupt,gen_hand_interaction_disrupt,gen_insert_interaction_pass|gen_insert_interaction_pass:needs a soap",
		"/obj/effect/dummy/chameleon|human|/obj/item/soap => gen_item_interaction_disrupt,gen_hand_interaction_disrupt,gen_insert_interaction_pass|gen_insert_interaction_pass:needs a mop",
		"/obj/item/defib_kit|human|none => gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|emag:needs a cryptographic sequencer,gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/defib_kit|robot|none => gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|emag:needs a cryptographic sequencer,gen_insert_interaction_kit_customize:needs an item,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/defib_kit|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/defib_kit|ghost|none => |",
		"/obj/item/defib_kit|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|emag:needs a cryptographic sequencer,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/defib_kit|human|/obj/item/storage => gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|emag:needs a cryptographic sequencer,gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/defib_kit|human|/obj/item/card/emag => emag,gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/emergency_beacon|human|none => gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/emergency_beacon|robot|none => gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/emergency_beacon|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/emergency_beacon|ghost|none => |",
		"/obj/item/emergency_beacon|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/emergency_beacon|human|/obj/item/storage => gen_hand_interaction_hand,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/extrapolator|human|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/extrapolator|robot|none => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/extrapolator|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/extrapolator|ghost|none => |",
		"/obj/item/extrapolator|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/extrapolator|human|/obj/item/storage => gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_verb_toggle_digestable_effect:you need to be carrying it",
		"/obj/item/communicator|human|none => gen_alt_interaction_alt,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/communicator|robot|none => gen_alt_interaction_alt,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_silicon_item_silicon_equip_module:not possible right now,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/communicator|ai|none => |gen_silicon_item_silicon_equip_module:not possible right now",
		"/obj/item/communicator|ghost|none => gen_observer_communicator_observer_use|",
		"/obj/item/communicator|human|/obj/item/kit => gen_insert_interaction_kit_customize,gen_alt_interaction_alt,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up|gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it,gen_insert_interaction_collected:needs a storage",
		"/obj/item/communicator|human|/obj/item/storage => gen_alt_interaction_alt,gen_item_interaction_item,gen_verb_move_to_top_effect,gen_hand_interaction_pick_up,gen_insert_interaction_collected|gen_insert_interaction_kit_customize:needs an item,gen_use_interaction_self:not in your hand,gen_verb_toggle_digestable_effect:you need to be carrying it",
	)
