/**
 * I7: bulk domain snapshot for the structures domain converted to interaction entries
 * (roadmap I7, doc/rewrite/interactions.md section 13). One snapshot covering every
 * converted structure type, generated from the resolver's actual current output, the
 * same technique as dq_i7_bulk_capture.dm for machinery/ATMOSPHERICS/power.
 */
/datum/unit_test/dq_interaction_domain_snapshot/i7_structures_bulk
	snapshot_types = list(
		/obj/structure/alien,
		/obj/structure/barricade,
		/obj/structure/bed,
		/obj/structure/bed/chair/wheelchair,
		/obj/structure/bed/nest,
		/obj/structure/bed/pillowpile,
		/obj/structure/bed/pillowpilefront,
		/obj/structure/bedsheetbin,
		/obj/structure/biowaste_tank,
		/obj/structure/bonfire,
		/obj/structure/catwalk,
		/obj/structure/closet,
		/obj/structure/closet/crate/secure,
		/obj/structure/closet/grave,
		/obj/structure/closet/secure_closet,
		/obj/structure/coatrack,
		/obj/structure/curtain,
		/obj/structure/dirtybed,
		/obj/structure/dispenser,
		/obj/structure/displaycase,
		/obj/structure/door_assembly,
		/obj/structure/drop_pod,
		/obj/structure/easel,
		/obj/structure/extinguisher_cabinet,
		/obj/structure/fence,
		/obj/structure/fence/door,
		/obj/structure/fireaxecabinet,
		/obj/structure/fireplace,
		/obj/structure/fitness/punchingbag,
		/obj/structure/fitness/weightlifter,
		/obj/structure/flora,
		/obj/structure/flora/pottedplant,
		/obj/structure/flora/tree,
		/obj/structure/flora/tree/pine/xmas/presents,
		/obj/structure/foodcart,
		/obj/structure/gargoyle,
		/obj/structure/ghost_pod/automatic/xenomorph_egg,
		/obj/structure/ghost_pod/manual,
		/obj/structure/girder,
		/obj/structure/grille,
		/obj/structure/holosign,
		/obj/structure/inflatable,
		/obj/structure/inflatable/door,
		/obj/structure/janitorialcart,
		/obj/structure/kitchenspike,
		/obj/structure/largecrate,
		/obj/structure/lattice,
		/obj/structure/loot_pile,
		/obj/structure/low_wall,
		/obj/structure/m_tray,
		/obj/structure/mirror,
		/obj/structure/mopbucket,
		/obj/structure/morgue,
		/obj/structure/morgue/crematorium,
		/obj/structure/prop,
		/obj/structure/prop/desert_rock/rock,
		/obj/structure/prop/fake_ai,
		/obj/structure/prop/machine/centrifuge,
		/obj/structure/prop/machine/disease_analyser,
		/obj/structure/prop/machine/incubator,
		/obj/structure/prop/machine/isolator,
		/obj/structure/prop/nest,
		/obj/structure/prop/prism,
		/obj/structure/prop/prismcontrol,
		/obj/structure/prop/tyr_elevator,
		/obj/structure/railing,
		/obj/structure/reflector,
		/obj/structure/safe,
		/obj/structure/sign/double/barsign,
		/obj/structure/sign/flag,
		/obj/structure/sign/painting,
		/obj/structure/simple_door,
		/obj/structure/simple_door/resin,
		/obj/structure/sink,
		/obj/structure/snowman,
		/obj/structure/stasis_cage,
		/obj/structure/target_stake,
		/obj/structure/toilet,
		/obj/structure/transit_tube/station,
		/obj/structure/trash_pile,
		/obj/structure/undies_wardrobe,
		/obj/structure/urinal,
		/obj/structure/vehiclecage,
		/obj/structure/windoor_assembly,
		/obj/structure/window,
	)
	expected = list(
		"/obj/structure/alien|human|none => alien_item,alien_hand|",
		"/obj/structure/alien|robot|none => alien_item,alien_hand|",
		"/obj/structure/alien|ai|none => |",
		"/obj/structure/alien|ghost|none => |",
		"/obj/structure/barricade|human|none => barricade_item|",
		"/obj/structure/barricade|robot|none => barricade_item|",
		"/obj/structure/barricade|ai|none => |",
		"/obj/structure/barricade|ghost|none => |",
		"/obj/structure/bed|human|none => bed_item,gen_drag_interaction_drag_buckle|",
		"/obj/structure/bed|robot|none => bed_item,gen_drag_interaction_drag_buckle|",
		"/obj/structure/bed|ai|none => |",
		"/obj/structure/bed|ghost|none => |",
		"/obj/structure/bed/chair/wheelchair|human|none => wheelchair_hand,bed_item,gen_drag_interaction_drag_buckle|",
		"/obj/structure/bed/chair/wheelchair|robot|none => wheelchair_hand,bed_item,gen_drag_interaction_drag_buckle|",
		"/obj/structure/bed/chair/wheelchair|ai|none => |",
		"/obj/structure/bed/chair/wheelchair|ghost|none => |",
		"/obj/structure/bed/nest|human|none => nest_item,nest_hand|",
		"/obj/structure/bed/nest|robot|none => nest_item,nest_hand|",
		"/obj/structure/bed/nest|ai|none => |",
		"/obj/structure/bed/nest|ghost|none => |",
		"/obj/structure/bed/pillowpile|human|none => pillowpile_hand|",
		"/obj/structure/bed/pillowpile|robot|none => pillowpile_hand|",
		"/obj/structure/bed/pillowpile|ai|none => |",
		"/obj/structure/bed/pillowpile|ghost|none => |",
		"/obj/structure/bed/pillowpilefront|human|none => pillowpilefront_hand|",
		"/obj/structure/bed/pillowpilefront|robot|none => pillowpilefront_hand|",
		"/obj/structure/bed/pillowpilefront|ai|none => |",
		"/obj/structure/bed/pillowpilefront|ghost|none => |",
		"/obj/structure/bedsheetbin|human|none => bedsheetbin_item,bedsheetbin_hand|",
		"/obj/structure/bedsheetbin|robot|none => bedsheetbin_item,bedsheetbin_hand|",
		"/obj/structure/bedsheetbin|ai|none => |",
		"/obj/structure/bedsheetbin|ghost|none => |",
		"/obj/structure/biowaste_tank|human|none => biowaste_tank_hand|",
		"/obj/structure/biowaste_tank|robot|none => biowaste_tank_hand|",
		"/obj/structure/biowaste_tank|ai|none => |",
		"/obj/structure/biowaste_tank|ghost|none => |",
		"/obj/structure/bonfire|human|none => bonfire_item,bonfire_hand|",
		"/obj/structure/bonfire|robot|none => bonfire_item,bonfire_hand|",
		"/obj/structure/bonfire|ai|none => |",
		"/obj/structure/bonfire|ghost|none => |",
		"/obj/structure/catwalk|human|none => |catwalk_plate:needs a floor tile",
		"/obj/structure/catwalk|robot|none => |catwalk_plate:needs a floor tile",
		"/obj/structure/catwalk|ai|none => |",
		"/obj/structure/catwalk|ghost|none => |",
		"/obj/structure/catwalk|human|/obj/item/stack/tile/floor => catwalk_plate|",
		"/obj/structure/closet|human|none => closet_item,closet_hand,closet_drag,gen_verb_verb_toggleopen_effect,gen_verb_closet_hidden_vore_effect|",
		"/obj/structure/closet|robot|none => closet_item,closet_hand,closet_drag,gen_verb_verb_toggleopen_effect,gen_verb_closet_hidden_vore_effect|",
		"/obj/structure/closet|ai|none => |",
		"/obj/structure/closet|ghost|none => |",
		"/obj/structure/closet/crate/secure|human|none => secure_crate_hand,gen_verb_secure_verb_togglelock_effect,closet_item,closet_drag,gen_verb_verb_toggleopen_effect,gen_verb_closet_hidden_vore_effect,gen_drag_interaction_drag_buckle|",
		"/obj/structure/closet/crate/secure|robot|none => secure_crate_hand,gen_verb_secure_verb_togglelock_effect,closet_item,closet_drag,gen_verb_verb_toggleopen_effect,gen_verb_closet_hidden_vore_effect,gen_drag_interaction_drag_buckle|",
		"/obj/structure/closet/crate/secure|ai|none => |",
		"/obj/structure/closet/crate/secure|ghost|none => |",
		"/obj/structure/closet/grave|human|none => grave_hand,grave_item|",
		"/obj/structure/closet/grave|robot|none => grave_hand,grave_item|",
		"/obj/structure/closet/grave|ai|none => |",
		"/obj/structure/closet/grave|ghost|none => |",
		"/obj/structure/closet/secure_closet|human|none => secure_closet_hand,secure_closet_alt,gen_verb_secure_closet_verb_togglelock_effect,closet_item,closet_drag,gen_verb_verb_toggleopen_effect,gen_verb_closet_hidden_vore_effect|",
		"/obj/structure/closet/secure_closet|robot|none => secure_closet_hand,secure_closet_alt,gen_verb_secure_closet_verb_togglelock_effect,closet_item,closet_drag,gen_verb_verb_toggleopen_effect,gen_verb_closet_hidden_vore_effect|",
		"/obj/structure/closet/secure_closet|ai|none => |",
		"/obj/structure/closet/secure_closet|ghost|none => |",
		"/obj/structure/coatrack|human|none => coatrack_item|coatrack_hand:not possible right now",
		"/obj/structure/coatrack|robot|none => coatrack_item|coatrack_hand:not possible right now",
		"/obj/structure/coatrack|ai|none => |",
		"/obj/structure/coatrack|ghost|none => |",
		"/obj/structure/curtain|human|none => curtain_toggle,curtain_toggle_item|",
		"/obj/structure/curtain|robot|none => curtain_toggle,curtain_toggle_item,gen_silicon_curtain_silicon_toggle|",
		"/obj/structure/curtain|ai|none => gen_silicon_curtain_silicon_toggle|",
		"/obj/structure/curtain|ghost|none => |",
		"/obj/structure/dirtybed|human|none => gen_drag_interaction_drag_buckle|dirtybed_item:not possible right now",
		"/obj/structure/dirtybed|robot|none => gen_drag_interaction_drag_buckle|dirtybed_item:not possible right now",
		"/obj/structure/dirtybed|ai|none => |",
		"/obj/structure/dirtybed|ghost|none => |",
		"/obj/structure/dispenser|human|none => dispenser_open_ui,dispenser_item|",
		"/obj/structure/dispenser|robot|none => dispenser_open_ui,dispenser_item|",
		"/obj/structure/dispenser|ai|none => |",
		"/obj/structure/dispenser|ghost|none => |",
		"/obj/structure/displaycase|human|none => displaycase_item,displaycase_hand|",
		"/obj/structure/displaycase|robot|none => displaycase_item,displaycase_hand|",
		"/obj/structure/displaycase|ai|none => |",
		"/obj/structure/displaycase|ghost|none => |",
		"/obj/structure/door_assembly|human|none => door_assembly_item|",
		"/obj/structure/door_assembly|robot|none => gen_robot_door_assembly_robot_rename,door_assembly_item|",
		"/obj/structure/door_assembly|ai|none => |",
		"/obj/structure/door_assembly|ghost|none => |",
		"/obj/structure/drop_pod|human|none => drop_pod_open|",
		"/obj/structure/drop_pod|robot|none => drop_pod_open|",
		"/obj/structure/drop_pod|ai|none => |",
		"/obj/structure/drop_pod|ghost|none => |",
		"/obj/structure/easel|human|none => gen_drag_interaction_drag_buckle|easel_item:needs a canvas",
		"/obj/structure/easel|robot|none => gen_drag_interaction_drag_buckle|easel_item:needs a canvas",
		"/obj/structure/easel|ai|none => |",
		"/obj/structure/easel|ghost|none => |",
		"/obj/structure/easel|human|/obj/item/canvas => easel_item,gen_drag_interaction_drag_buckle|",
		"/obj/structure/extinguisher_cabinet|human|none => extinguisher_cabinet_item,extinguisher_cabinet_hand|",
		"/obj/structure/extinguisher_cabinet|robot|none => extinguisher_cabinet_item,extinguisher_cabinet_hand|",
		"/obj/structure/extinguisher_cabinet|ai|none => |",
		"/obj/structure/extinguisher_cabinet|ghost|none => |",
		"/obj/structure/fence|human|none => fence_hand,fence_item|",
		"/obj/structure/fence|robot|none => fence_hand,fence_item|",
		"/obj/structure/fence|ai|none => |",
		"/obj/structure/fence|ghost|none => |",
		"/obj/structure/fence/door|human|none => fence_door_hand,fence_door_item|",
		"/obj/structure/fence/door|robot|none => fence_door_hand,fence_door_item|",
		"/obj/structure/fence/door|ai|none => |",
		"/obj/structure/fence/door|ghost|none => |",
		"/obj/structure/fireaxecabinet|human|none => fireaxecabinet_item,fireaxecabinet_hand,gen_verb_toggle_openness_effect,gen_verb_remove_fire_axe_effect|",
		"/obj/structure/fireaxecabinet|robot|none => fireaxecabinet_item,fireaxecabinet_hand,gen_silicon_fireaxecabinet_silicon_lock,gen_verb_toggle_openness_effect,gen_verb_remove_fire_axe_effect|",
		"/obj/structure/fireaxecabinet|ai|none => gen_silicon_fireaxecabinet_silicon_lock|",
		"/obj/structure/fireaxecabinet|ghost|none => |",
		"/obj/structure/fireplace|human|none => fireplace_item,fireplace_hand|",
		"/obj/structure/fireplace|robot|none => fireplace_item,fireplace_hand|",
		"/obj/structure/fireplace|ai|none => |",
		"/obj/structure/fireplace|ghost|none => |",
		"/obj/structure/fitness/punchingbag|human|none => |punchingbag_hand:combat mode is off",
		"/obj/structure/fitness/punchingbag|robot|none => |punchingbag_hand:combat mode is off",
		"/obj/structure/fitness/punchingbag|ai|none => |",
		"/obj/structure/fitness/punchingbag|ghost|none => |",
		"/obj/structure/fitness/weightlifter|human|none => weightlifter_hand|",
		"/obj/structure/fitness/weightlifter|robot|none => weightlifter_hand|",
		"/obj/structure/fitness/weightlifter|ai|none => |",
		"/obj/structure/fitness/weightlifter|ghost|none => |",
		"/obj/structure/flora|human|none => flora_item|",
		"/obj/structure/flora|robot|none => flora_item|",
		"/obj/structure/flora|ai|none => |",
		"/obj/structure/flora|ghost|none => |",
		"/obj/structure/flora/pottedplant|human|none => pottedplant_item,pottedplant_hand|",
		"/obj/structure/flora/pottedplant|robot|none => pottedplant_item,pottedplant_hand|",
		"/obj/structure/flora/pottedplant|ai|none => |",
		"/obj/structure/flora/pottedplant|ghost|none => |",
		"/obj/structure/flora/tree|human|none => tree_item,tree_hand|",
		"/obj/structure/flora/tree|robot|none => tree_item,tree_hand|",
		"/obj/structure/flora/tree|ai|none => |",
		"/obj/structure/flora/tree|ghost|none => |",
		"/obj/structure/flora/tree/pine/xmas/presents|human|none => xmas_presents_hand,tree_item,tree_hand|",
		"/obj/structure/flora/tree/pine/xmas/presents|robot|none => xmas_presents_hand,tree_item,tree_hand|",
		"/obj/structure/flora/tree/pine/xmas/presents|ai|none => |",
		"/obj/structure/flora/tree/pine/xmas/presents|ghost|none => |",
		"/obj/structure/foodcart|human|none => foodcart_hand|foodcart_item:needs a Container",
		"/obj/structure/foodcart|robot|none => foodcart_hand|foodcart_item:needs a Container",
		"/obj/structure/foodcart|ai|none => |",
		"/obj/structure/foodcart|ghost|none => |",
		"/obj/structure/foodcart|human|/obj/item/reagent_containers/food => foodcart_item,foodcart_hand|",
		"/obj/structure/gargoyle|human|none => gargoyle_item|",
		"/obj/structure/gargoyle|robot|none => gargoyle_item|",
		"/obj/structure/gargoyle|ai|none => |",
		"/obj/structure/gargoyle|ghost|none => |",
		"/obj/structure/ghost_pod/automatic/xenomorph_egg|human|none => xenomorph_egg_item|",
		"/obj/structure/ghost_pod/automatic/xenomorph_egg|robot|none => xenomorph_egg_item|",
		"/obj/structure/ghost_pod/automatic/xenomorph_egg|ai|none => |",
		"/obj/structure/ghost_pod/automatic/xenomorph_egg|ghost|none => |",
		"/obj/structure/ghost_pod/manual|human|none => ghost_pod_open|",
		"/obj/structure/ghost_pod/manual|robot|none => ghost_pod_open|",
		"/obj/structure/ghost_pod/manual|ai|none => |",
		"/obj/structure/ghost_pod/manual|ghost|none => gen_observer_ghost_pod_manual_observer_use|",
		"/obj/structure/girder|human|none => girder_item|girder:anchored>displaced:crowbar:needs a crowbar,girder:anchored>done:wrench:needs a wrench,girder:anchored>anchored:screwdriver:needs a screwdriver,girder_hulk_smash:not possible right now",
		"/obj/structure/girder|robot|none => girder_item|girder:anchored>displaced:crowbar:needs a crowbar,girder:anchored>done:wrench:needs a wrench,girder:anchored>anchored:screwdriver:needs a screwdriver,girder_hulk_smash:not possible right now",
		"/obj/structure/girder|ai|none => |",
		"/obj/structure/girder|ghost|none => |",
		"/obj/structure/grille|human|none => grille_hand,grille_item|",
		"/obj/structure/grille|robot|none => grille_hand,grille_item|",
		"/obj/structure/grille|ai|none => |",
		"/obj/structure/grille|ghost|none => |",
		"/obj/structure/holosign|human|none => holosign_hand,holosign_item|",
		"/obj/structure/holosign|robot|none => holosign_hand,holosign_item|",
		"/obj/structure/holosign|ai|none => |",
		"/obj/structure/holosign|ghost|none => |",
		"/obj/structure/inflatable|human|none => inflatable_hand,inflatable_item,gen_verb_hand_deflate_effect|",
		"/obj/structure/inflatable|robot|none => inflatable_hand,inflatable_item,gen_verb_hand_deflate_effect|",
		"/obj/structure/inflatable|ai|none => |",
		"/obj/structure/inflatable|ghost|none => |",
		"/obj/structure/inflatable/door|human|none => inflatable_door_hand,gen_verb_hand_deflate_effect|",
		"/obj/structure/inflatable/door|robot|none => inflatable_door_hand,gen_silicon_inflatable_door_silicon_use,gen_verb_hand_deflate_effect|",
		"/obj/structure/inflatable/door|ai|none => gen_silicon_inflatable_door_silicon_use|",
		"/obj/structure/inflatable/door|ghost|none => |",
		"/obj/structure/janitorialcart|human|none => janitorialcart_item,janitorialcart_alt,janitorialcart_hand,janitorialcart_drag,gen_drag_interaction_drag_buckle|",
		"/obj/structure/janitorialcart|robot|none => janitorialcart_item,janitorialcart_alt,janitorialcart_hand,janitorialcart_drag,gen_drag_interaction_drag_buckle|",
		"/obj/structure/janitorialcart|ai|none => |",
		"/obj/structure/janitorialcart|ghost|none => |",
		"/obj/structure/kitchenspike|human|none => |kitchenspike_item:needs a grab,kitchenspike_hand:not possible right now",
		"/obj/structure/kitchenspike|robot|none => |kitchenspike_item:needs a grab,kitchenspike_hand:not possible right now",
		"/obj/structure/kitchenspike|ai|none => |",
		"/obj/structure/kitchenspike|ghost|none => |",
		"/obj/structure/largecrate|human|none => largecrate_hand|",
		"/obj/structure/largecrate|robot|none => largecrate_hand|",
		"/obj/structure/largecrate|ai|none => |",
		"/obj/structure/largecrate|ghost|none => |",
		"/obj/structure/lattice|human|none => |lattice_item:too far away",
		"/obj/structure/lattice|robot|none => |lattice_item:too far away",
		"/obj/structure/lattice|ai|none => |",
		"/obj/structure/lattice|ghost|none => |",
		"/obj/structure/loot_pile|human|none => loot_pile_search|",
		"/obj/structure/loot_pile|robot|none => loot_pile_search|",
		"/obj/structure/loot_pile|ai|none => |",
		"/obj/structure/loot_pile|ghost|none => |",
		"/obj/structure/low_wall|human|none => low_wall_item,low_wall_drag,gen_drag_interaction_drag_buckle|",
		"/obj/structure/low_wall|robot|none => low_wall_item,low_wall_drag,gen_drag_interaction_drag_buckle|",
		"/obj/structure/low_wall|ai|none => |",
		"/obj/structure/low_wall|ghost|none => |",
		"/obj/structure/m_tray|human|none => m_tray_hand,m_tray_drag|",
		"/obj/structure/m_tray|robot|none => m_tray_hand,m_tray_drag|",
		"/obj/structure/m_tray|ai|none => |",
		"/obj/structure/m_tray|ghost|none => |",
		"/obj/structure/mirror|human|none => mirror_open_ui,mirror_item|",
		"/obj/structure/mirror|robot|none => mirror_open_ui,mirror_item,gen_silicon_mirror_silicon_use|",
		"/obj/structure/mirror|ai|none => gen_silicon_mirror_silicon_use|",
		"/obj/structure/mirror|ghost|none => |",
		"/obj/structure/mopbucket|human|none => mopbucket_item,gen_drag_interaction_drag_buckle|",
		"/obj/structure/mopbucket|robot|none => mopbucket_item,gen_drag_interaction_drag_buckle|",
		"/obj/structure/mopbucket|ai|none => |",
		"/obj/structure/mopbucket|ghost|none => |",
		"/obj/structure/morgue|human|none => morgue_hand,morgue_item|",
		"/obj/structure/morgue|robot|none => morgue_hand,morgue_item|",
		"/obj/structure/morgue|ai|none => |",
		"/obj/structure/morgue|ghost|none => |",
		"/obj/structure/morgue/crematorium|human|none => crematorium_hand,crematorium_item|",
		"/obj/structure/morgue/crematorium|robot|none => crematorium_hand,crematorium_item|",
		"/obj/structure/morgue/crematorium|ai|none => |",
		"/obj/structure/morgue/crematorium|ghost|none => |",
		"/obj/structure/prop|human|none => |prop_hand:not possible right now",
		"/obj/structure/prop|robot|none => |prop_hand:not possible right now",
		"/obj/structure/prop|ai|none => |",
		"/obj/structure/prop|ghost|none => |",
		"/obj/structure/prop/desert_rock/rock|human|none => desert_rock_push|prop_hand:not possible right now",
		"/obj/structure/prop/desert_rock/rock|robot|none => desert_rock_push|prop_hand:not possible right now",
		"/obj/structure/prop/desert_rock/rock|ai|none => |",
		"/obj/structure/prop/desert_rock/rock|ghost|none => |",
		"/obj/structure/prop/fake_ai|human|none => |fake_ai_item:needs an intelliCore,prop_hand:not possible right now",
		"/obj/structure/prop/fake_ai|robot|none => |fake_ai_item:needs an intelliCore,prop_hand:not possible right now",
		"/obj/structure/prop/fake_ai|ai|none => |",
		"/obj/structure/prop/fake_ai|ghost|none => |",
		"/obj/structure/prop/fake_ai|human|/obj/item/aicard => fake_ai_item|prop_hand:not possible right now",
		"/obj/structure/prop/machine/centrifuge|human|none => centrifuge_toggle|prop_hand:not possible right now",
		"/obj/structure/prop/machine/centrifuge|robot|none => centrifuge_toggle|prop_hand:not possible right now",
		"/obj/structure/prop/machine/centrifuge|ai|none => |",
		"/obj/structure/prop/machine/centrifuge|ghost|none => |",
		"/obj/structure/prop/machine/disease_analyser|human|none => disease_analyser_toggle|prop_hand:not possible right now",
		"/obj/structure/prop/machine/disease_analyser|robot|none => disease_analyser_toggle|prop_hand:not possible right now",
		"/obj/structure/prop/machine/disease_analyser|ai|none => |",
		"/obj/structure/prop/machine/disease_analyser|ghost|none => |",
		"/obj/structure/prop/machine/incubator|human|none => incubator_toggle|prop_hand:not possible right now",
		"/obj/structure/prop/machine/incubator|robot|none => incubator_toggle|prop_hand:not possible right now",
		"/obj/structure/prop/machine/incubator|ai|none => |",
		"/obj/structure/prop/machine/incubator|ghost|none => |",
		"/obj/structure/prop/machine/isolator|human|none => isolator_toggle|prop_hand:not possible right now",
		"/obj/structure/prop/machine/isolator|robot|none => isolator_toggle|prop_hand:not possible right now",
		"/obj/structure/prop/machine/isolator|ai|none => |",
		"/obj/structure/prop/machine/isolator|ghost|none => |",
		"/obj/structure/prop/nest|human|none => nest_disturb|",
		"/obj/structure/prop/nest|robot|none => nest_disturb|",
		"/obj/structure/prop/nest|ai|none => |",
		"/obj/structure/prop/nest|ghost|none => |",
		"/obj/structure/prop/prism|human|none => prism_rotate|",
		"/obj/structure/prop/prism|robot|none => prism_rotate|",
		"/obj/structure/prop/prism|ai|none => |",
		"/obj/structure/prop/prism|ghost|none => |",
		"/obj/structure/prop/prismcontrol|human|none => prismcontrol_rotate|",
		"/obj/structure/prop/prismcontrol|robot|none => prismcontrol_rotate|",
		"/obj/structure/prop/prismcontrol|ai|none => |",
		"/obj/structure/prop/prismcontrol|ghost|none => |",
		"/obj/structure/prop/tyr_elevator|human|none => tyr_elevator_item|prop_hand:not possible right now",
		"/obj/structure/prop/tyr_elevator|robot|none => tyr_elevator_item|prop_hand:not possible right now",
		"/obj/structure/prop/tyr_elevator|ai|none => |",
		"/obj/structure/prop/tyr_elevator|ghost|none => |",
		"/obj/structure/railing|human|none => railing_item,gen_verb_railing_flip_effect,gen_drag_interaction_drag_buckle|",
		"/obj/structure/railing|robot|none => railing_item,gen_verb_railing_flip_effect,gen_drag_interaction_drag_buckle|",
		"/obj/structure/railing|ai|none => |",
		"/obj/structure/railing|ghost|none => |",
		"/obj/structure/reflector|human|none => reflector_item|reflector_alt:not possible right now",
		"/obj/structure/reflector|robot|none => reflector_item|reflector_alt:not possible right now",
		"/obj/structure/reflector|ai|none => |",
		"/obj/structure/reflector|ghost|none => |",
		"/obj/structure/safe|human|none => safe_open_ui,safe_item|",
		"/obj/structure/safe|robot|none => safe_open_ui,safe_item|",
		"/obj/structure/safe|ai|none => |",
		"/obj/structure/safe|ghost|none => |",
		"/obj/structure/sign/double/barsign|human|none => barsign_item|",
		"/obj/structure/sign/double/barsign|robot|none => barsign_item|",
		"/obj/structure/sign/double/barsign|ai|none => |",
		"/obj/structure/sign/double/barsign|ghost|none => |",
		"/obj/structure/sign/flag|human|none => sign_flag_rip,sign_flag_item|",
		"/obj/structure/sign/flag|robot|none => sign_flag_rip,sign_flag_item|",
		"/obj/structure/sign/flag|ai|none => |",
		"/obj/structure/sign/flag|ghost|none => |",
		"/obj/structure/sign/painting|human|none => sign_painting_item|",
		"/obj/structure/sign/painting|robot|none => sign_painting_item|",
		"/obj/structure/sign/painting|ai|none => |",
		"/obj/structure/sign/painting|ghost|none => |",
		"/obj/structure/simple_door|human|none => simple_door_hand,simple_door_item|",
		"/obj/structure/simple_door|robot|none => simple_door_hand,simple_door_item,gen_silicon_simple_door_silicon_use|",
		"/obj/structure/simple_door|ai|none => gen_silicon_simple_door_silicon_use|",
		"/obj/structure/simple_door|ghost|none => |",
		"/obj/structure/simple_door/resin|human|none => simple_door_resin_hand|simple_door_resin_tear:combat mode is off",
		"/obj/structure/simple_door/resin|robot|none => simple_door_resin_hand,gen_silicon_simple_door_silicon_use|simple_door_resin_tear:combat mode is off",
		"/obj/structure/simple_door/resin|ai|none => gen_silicon_simple_door_silicon_use|",
		"/obj/structure/simple_door/resin|ghost|none => |",
		"/obj/structure/sink|human|none => gen_item_sink_wash_gurgled_item,sink_wash,sink_item,sink_empty|",
		"/obj/structure/sink|robot|none => gen_item_sink_wash_gurgled_item,sink_wash,sink_item,sink_empty|",
		"/obj/structure/sink|ai|none => |",
		"/obj/structure/sink|ghost|none => |",
		"/obj/structure/snowman|human|none => |snowman_crush:combat mode is off",
		"/obj/structure/snowman|robot|none => |snowman_crush:combat mode is off",
		"/obj/structure/snowman|ai|none => |",
		"/obj/structure/snowman|ghost|none => |",
		"/obj/structure/stasis_cage|human|none => stasis_cage_release|",
		"/obj/structure/stasis_cage|robot|none => gen_robot_stasis_cage_robot_release,stasis_cage_release|",
		"/obj/structure/stasis_cage|ai|none => |",
		"/obj/structure/stasis_cage|ghost|none => |",
		"/obj/structure/target_stake|human|none => target_stake_item,target_stake_hand|",
		"/obj/structure/target_stake|robot|none => target_stake_item,target_stake_hand|",
		"/obj/structure/target_stake|ai|none => |",
		"/obj/structure/target_stake|ghost|none => |",
		"/obj/structure/toilet|human|none => toilet_hand,toilet_item,toilet_alt|",
		"/obj/structure/toilet|robot|none => gen_silicon_toilet_silicon_use,toilet_hand,toilet_item,toilet_alt|",
		"/obj/structure/toilet|ai|none => gen_silicon_toilet_silicon_use|",
		"/obj/structure/toilet|ghost|none => |",
		"/obj/structure/transit_tube/station|human|none => transit_tube_toggle|",
		"/obj/structure/transit_tube/station|robot|none => transit_tube_toggle|",
		"/obj/structure/transit_tube/station|ai|none => |",
		"/obj/structure/transit_tube/station|ghost|none => |",
		"/obj/structure/trash_pile|human|none => trash_pile_item,trash_pile_search,gen_drag_interaction_drag_buckle|",
		"/obj/structure/trash_pile|robot|none => trash_pile_item,trash_pile_search,gen_drag_interaction_drag_buckle|",
		"/obj/structure/trash_pile|ai|none => |",
		"/obj/structure/trash_pile|ghost|none => gen_observer_trash_pile_ghost_mouse|",
		"/obj/structure/undies_wardrobe|human|none => undies_wardrobe_open_ui,gen_drag_interaction_drag_buckle|",
		"/obj/structure/undies_wardrobe|robot|none => undies_wardrobe_open_ui,gen_drag_interaction_drag_buckle|",
		"/obj/structure/undies_wardrobe|ai|none => |",
		"/obj/structure/undies_wardrobe|ghost|none => |",
		"/obj/structure/urinal|human|none => |urinal_item:needs a grab",
		"/obj/structure/urinal|robot|none => |urinal_item:needs a grab",
		"/obj/structure/urinal|ai|none => |",
		"/obj/structure/urinal|ghost|none => |",
		"/obj/structure/vehiclecage|human|none => vehiclecage_hand,vehiclecage_load|",
		"/obj/structure/vehiclecage|robot|none => vehiclecage_hand,vehiclecage_load|",
		"/obj/structure/vehiclecage|ai|none => |",
		"/obj/structure/vehiclecage|ghost|none => |",
		"/obj/structure/windoor_assembly|human|none => gen_verb_windoor_assembly_flip_effect,windoor_assembly_item|",
		"/obj/structure/windoor_assembly|robot|none => gen_robot_windoor_robot_rename,gen_verb_windoor_assembly_flip_effect,windoor_assembly_item|",
		"/obj/structure/windoor_assembly|ai|none => |",
		"/obj/structure/windoor_assembly|ghost|none => |",
		"/obj/structure/window|human|none => window_hand,window_item|window_repair:needs a welder,window:a>u:screwdriver:needs a screwdriver,window_bang:combat mode is off",
		"/obj/structure/window|robot|none => window_hand,window_item|window_repair:needs a welder,window:a>u:screwdriver:needs a screwdriver,window_bang:combat mode is off",
		"/obj/structure/window|ai|none => |",
		"/obj/structure/window|ghost|none => |",
	)
