/**
 * I7: bulk domain snapshot for the items domain converted to interaction entries
 * (roadmap I7, doc/rewrite/interactions.md section 13). One snapshot covering every
 * converted item type, generated from the resolver's actual current output, the
 * same technique as dq_i7_bulk_capture.dm / dq_i7_structures_bulk_capture.dm for the
 * machinery and structures domains. Grows as more items subdomains are converted.
 */
/datum/unit_test/dq_interaction_domain_snapshot/i7_items_bulk
	snapshot_types = list(
		/obj/item/assembly,
		/obj/item/assembly/voice,
		/obj/item/assembly/igniter,
		/obj/item/assembly/shock_kit,
		/obj/item/assembly/mousetrap,
		/obj/item/assembly_holder,
		/obj/item/assembly/signaler,
		/obj/item/assembly/infra,
		/obj/item/nifrepairer,
		/obj/item/aicard,
		/obj/item/binoculars,
		/obj/item/bodysnatcher,
		/obj/item/chameleon,
		/obj/effect/dummy/chameleon,
		/obj/item/defib_kit,
		/obj/item/emergency_beacon,
		/obj/item/extrapolator,
		/obj/item/communicator,
	)
	expected = list(
		"/obj/item/assembly|human|none => assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly|robot|none => assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly|ai|none => |",
		"/obj/item/assembly|ghost|none => |",
		"/obj/item/assembly/voice|human|none => assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/voice|robot|none => assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/voice|ai|none => |",
		"/obj/item/assembly/voice|ghost|none => |",
		"/obj/item/assembly/igniter|human|none => assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/igniter|robot|none => assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/igniter|ai|none => |",
		"/obj/item/assembly/igniter|ghost|none => |",
		"/obj/item/assembly/shock_kit|human|none => assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/shock_kit|robot|none => assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/shock_kit|ai|none => |",
		"/obj/item/assembly/shock_kit|ghost|none => |",
		"/obj/item/assembly/mousetrap|human|none => mousetrap_hand,assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/mousetrap|robot|none => mousetrap_hand,assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/mousetrap|ai|none => |",
		"/obj/item/assembly/mousetrap|ghost|none => |",
		"/obj/item/assembly_holder|human|none => assembly_holder_hand|assembly_holder_self:must be held in hand",
		"/obj/item/assembly_holder|robot|none => assembly_holder_hand|assembly_holder_self:must be held in hand",
		"/obj/item/assembly_holder|ai|none => |",
		"/obj/item/assembly_holder|ghost|none => |",
		"/obj/item/assembly/signaler|human|none => signaler_transfer,assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/signaler|robot|none => signaler_transfer,assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/signaler|ai|none => |",
		"/obj/item/assembly/signaler|ghost|none => |",
		"/obj/item/assembly/infra|human|none => infra_hand,assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/infra|robot|none => infra_hand,assembly_item|assembly_self:must be held in hand",
		"/obj/item/assembly/infra|ai|none => |",
		"/obj/item/assembly/infra|ghost|none => |",
		"/obj/item/nifrepairer|human|none => nifrepairer_load|",
		"/obj/item/nifrepairer|robot|none => nifrepairer_load|",
		"/obj/item/nifrepairer|ai|none => |",
		"/obj/item/nifrepairer|ghost|none => |",
		"/obj/item/aicard|human|none => |aicard_self:must be held in hand",
		"/obj/item/aicard|robot|none => |aicard_self:must be held in hand",
		"/obj/item/aicard|ai|none => |",
		"/obj/item/aicard|ghost|none => |",
		"/obj/item/binoculars|human|none => |binoculars_self:must be held in hand",
		"/obj/item/binoculars|robot|none => |binoculars_self:must be held in hand",
		"/obj/item/binoculars|ai|none => |",
		"/obj/item/binoculars|ghost|none => |",
		"/obj/item/bodysnatcher|human|none => |bodysnatcher_self:must be held in hand",
		"/obj/item/bodysnatcher|robot|none => |bodysnatcher_self:must be held in hand",
		"/obj/item/bodysnatcher|ai|none => |",
		"/obj/item/bodysnatcher|ghost|none => |",
		"/obj/item/chameleon|human|none => |chameleon_self:must be held in hand",
		"/obj/item/chameleon|robot|none => |chameleon_self:must be held in hand",
		"/obj/item/chameleon|ai|none => |",
		"/obj/item/chameleon|ghost|none => |",
		"/obj/effect/dummy/chameleon|human|none => chameleon_dummy_item,chameleon_dummy_hand|",
		"/obj/effect/dummy/chameleon|robot|none => chameleon_dummy_item,chameleon_dummy_hand|",
		"/obj/effect/dummy/chameleon|ai|none => |",
		"/obj/effect/dummy/chameleon|ghost|none => |",
		"/obj/item/defib_kit|human|none => defib_kit_hand,defib_kit_load|",
		"/obj/item/defib_kit|robot|none => defib_kit_hand,defib_kit_load|",
		"/obj/item/defib_kit|ai|none => |",
		"/obj/item/defib_kit|ghost|none => |",
		"/obj/item/emergency_beacon|human|none => emergency_beacon_hand,emergency_beacon_disassemble|emergency_beacon_self:must be held in hand",
		"/obj/item/emergency_beacon|robot|none => emergency_beacon_hand,emergency_beacon_disassemble|emergency_beacon_self:must be held in hand",
		"/obj/item/emergency_beacon|ai|none => |",
		"/obj/item/emergency_beacon|ghost|none => |",
		"/obj/item/extrapolator|human|none => extrapolator_install|extrapolator_self:must be held in hand",
		"/obj/item/extrapolator|robot|none => extrapolator_install|extrapolator_self:must be held in hand",
		"/obj/item/extrapolator|ai|none => |",
		"/obj/item/extrapolator|ghost|none => |",
		"/obj/item/communicator|human|none => communicator_remove_id,communicator_scan_id|communicator_self:must be held in hand",
		"/obj/item/communicator|robot|none => communicator_remove_id,communicator_scan_id|communicator_self:must be held in hand",
		"/obj/item/communicator|ai|none => |",
		"/obj/item/communicator|ghost|none => |",
	)
