// Headless consent pins bypass only go_in's network-client admission: the real passenger-owned prompt and completion remain unchanged.
/datum/unit_test/dq_timed_pin/last_occupant
	abstract_type = /datum/unit_test/dq_timed_pin/last_occupant

/datum/unit_test/dq_timed_pin/last_occupant/proc/consent(obj/machinery/cryopod/P, mob/passenger, mob/loader)
	return open_request(P, /datum/prompt/yes_no/cryo_consent, TYPE_PROC_REF(/obj/machinery/cryopod, storage_consent_answered), answerer = passenger, title = "Cryopod", question = "Would you like to enter long-term storage?", loader = loader, ask_flags = ASK_ADJACENT | ASK_CAPABLE, timeout = 0)

/datum/unit_test/dq_timed_pin/last_occupant/cryo_yes
/datum/unit_test/dq_timed_pin/last_occupant/cryo_yes/run_pin()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/machinery/cryopod/P = allocate(/obj/machinery/cryopod, T)
	var/mob/living/carbon/human/loader = person(T)
	var/mob/living/carbon/human/passenger = person(T)
	interim_keep_awake(loader)
	interim_keep_awake(passenger)
	var/datum/prompt/yes_no/cryo_consent/R = consent(P, passenger, loader)
	TEST_ASSERT(R?.is_open(), "the real consent question opens")
	TEST_ASSERT_EQUAL(R.answerer, passenger, "the passenger is the answerer")
	TEST_ASSERT_EQUAL(R.loader, loader, "the separate loader is preserved")
	test_answer(passenger, TRUE)
	TEST_ASSERT(running(loader), "consent starts the loader's actual timed task")
	TEST_ASSERT_NULL(running(passenger), "consent does not give the passenger the loader's task")
	test_time(1 SECOND)
	TEST_ASSERT_NULL(P.slot_item(OCCUPANT_SLOT_CRYOPOD), "consent does not acquire custody before the two-second wait")
	test_time(2 SECONDS)
	TEST_ASSERT_EQUAL(P.slot_item(OCCUPANT_SLOT_CRYOPOD), passenger, "completion acquires the actual passenger")
	TEST_ASSERT_EQUAL(passenger.loc, P, "physical containment agrees with the ledger")

/datum/unit_test/dq_timed_pin/last_occupant/cryo_no
/datum/unit_test/dq_timed_pin/last_occupant/cryo_no/run_pin()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/machinery/cryopod/P = allocate(/obj/machinery/cryopod, T)
	var/mob/living/carbon/human/loader = person(T)
	var/mob/living/carbon/human/passenger = person(T)
	var/datum/prompt/yes_no/cryo_consent/R = consent(P, passenger, loader)
	TEST_ASSERT(R?.is_open(), "the real consent question opens before refusal")
	test_answer(passenger, FALSE)
	TEST_ASSERT_NULL(running(loader), "refusal starts no loader task")
	test_time(3 SECONDS)
	TEST_ASSERT_NULL(P.slot_item(OCCUPANT_SLOT_CRYOPOD), "refusal leaves the pod empty")
	TEST_ASSERT_EQUAL(passenger.loc, T, "refusal preserves passenger custody")

/datum/unit_test/dq_timed_pin/last_occupant/cryo_cancel
/datum/unit_test/dq_timed_pin/last_occupant/cryo_cancel/run_pin()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/machinery/cryopod/P = allocate(/obj/machinery/cryopod, T)
	var/mob/living/carbon/human/loader = person(T)
	var/mob/living/carbon/human/passenger = person(T)
	var/datum/prompt/yes_no/cryo_consent/R = consent(P, passenger, loader)
	TEST_ASSERT(R?.is_open(), "the real consent question opens before cancellation")
	test_answer(passenger, null, REQ_CANCELLED)
	TEST_ASSERT_NULL(running(loader), "cancellation starts no loader task")
	test_time(3 SECONDS)
	TEST_ASSERT_NULL(P.slot_item(OCCUPANT_SLOT_CRYOPOD), "cancellation leaves the pod empty")

/datum/unit_test/dq_timed_pin/last_occupant/cycler_shock
/datum/unit_test/dq_timed_pin/last_occupant/cycler_shock/run_pin()
	var/turf/T = run_loc_floor_bottom_left
	var/area/A = get_area(T)
	var/obj/machinery/power/apc/old_apc = A.get_apc()
	defer_cleanup(null, GLOBAL_PROC_REF(rel_set), A, nameof(A.apc), old_apc)
	var/obj/machinery/power/apc/APC = allocate(/obj/machinery/power/apc, T)
	if(APC.cell)
		own(APC.cell)
	if(APC.terminal)
		own(APC.terminal)
	rel_set(APC, nameof(APC.area), A)
	TEST_ASSERT_EQUAL(A.get_apc(), APC, "the paired APC-area relation supplies the actual shock source")
	var/obj/item/cell/C = allocate(/obj/item/cell/high, APC)
	rel_set(APC, nameof(APC.cell), C)
	APC.set_cell_charge(10000)
	var/obj/machinery/suit_cycler/M = allocate(/obj/machinery/suit_cycler, T)
	M.set_grid_power(TRUE)
	M.set_broken_condition(FALSE)
	M.set_locked(FALSE)
	hold(M, STAT_ELECTRIFIED, TRUE, src)
	var/mob/living/carbon/human/H = person(T)
	H.disable_godmode()
	interim_keep_awake(H)
	var/mob/living/carbon/human/V = person(T)
	var/obj/item/grab/G = allocate(/obj/item/grab, H, V)
	if(H.get_active_hand() != G)
		H.put_in_active_hand(G)
	TEST_ASSERT_EQUAL(H.get_active_hand(), G, "the shock victim actually holds the live grab")
	TEST_ASSERT(!H.has_status(STAT_STUNNED), "the actor starts unstunned")
	test_menu(H, M, "cycler_insert_grab")
	for(var/obj/effect/effect/sparks/S in T)
		own(S)
	TEST_ASSERT(H.has_status(STAT_STUNNED), "the real powered machine shock stuns the actor")
	TEST_ASSERT_NULL(running(H), "a successful shock prevents the actual timed insertion")
	TEST_ASSERT_NULL(M.slot_item(OCCUPANT_SLOT_SUIT_CYCLER), "shock leaves the real occupant slot empty")
	TEST_ASSERT_EQUAL(V.loc, T, "shock leaves the victim outside")
	rel_set(A, nameof(A.apc), old_apc)

/datum/unit_test/dq_timed_pin/last_occupant/cryo_loader_moves
/datum/unit_test/dq_timed_pin/last_occupant/cryo_loader_moves/run_pin()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/machinery/cryopod/P = allocate(/obj/machinery/cryopod, T)
	var/mob/living/carbon/human/loader = person(T)
	var/mob/living/carbon/human/passenger = person(T)
	interim_keep_awake(loader)
	interim_keep_awake(passenger)
	var/datum/prompt/yes_no/cryo_consent/R = consent(P, passenger, loader)
	TEST_ASSERT(R?.is_open(), "the real passenger question opens")
	test_answer(passenger, TRUE)
	var/datum/action = running(loader)
	TEST_ASSERT(action, "consent starts the real loader task before movement")
	loader.forceMove(get_step(T, EAST))
	test_time(3 SECONDS)
	TEST_ASSERT(was_cancelled(action, loader), "loader movement cancels the actual insertion")
	TEST_ASSERT_NULL(P.slot_item(OCCUPANT_SLOT_CRYOPOD), "a moved loader cannot acquire custody later")
	TEST_ASSERT_EQUAL(passenger.loc, T, "the uninserted passenger remains on the floor")

/datum/unit_test/dq_timed_pin/last_occupant/cryo_passenger_deleted
/datum/unit_test/dq_timed_pin/last_occupant/cryo_passenger_deleted/run_pin()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/machinery/cryopod/P = allocate(/obj/machinery/cryopod, T)
	var/mob/living/carbon/human/loader = person(T)
	var/mob/living/carbon/human/passenger = person(T)
	var/datum/prompt/yes_no/cryo_consent/R = consent(P, passenger, loader)
	TEST_ASSERT(R?.is_open(), "the actual passenger consent is open before deletion")
	qdel(passenger)
	test_time(3 SECONDS)
	TEST_ASSERT_NULL(running(loader), "deleting the answerer cannot start a loader task")
	TEST_ASSERT_NULL(P.slot_item(OCCUPANT_SLOT_CRYOPOD), "a deleted passenger never acquires custody")
	TEST_ASSERT(QDELETED(R) || !R.is_open(), "the deleted passenger's actual question closes")
