// Real machine operations answer non-harm clicks; damaging item strikes require harm.
/datum/unit_test/read_once_machinery_admission/machine_click_intent

/datum/unit_test/read_once_machinery_admission/machine_click_intent/run_gate()
	set_global(nameof(GLOB.op_menu_builds), GLOB.op_menu_builds)
	set_global(nameof(GLOB.look_effects_ran), GLOB.look_effects_ran)
	var/mob/living/carbon/human/H = person()
	var/obj/item/tool/wrench/W = allocate(/obj/item/tool/wrench, H.loc)
	TEST_ASSERT(H.put_in_active_hand(W), "The actor actually holds a force-bearing tool")
	var/list/types = list(/obj/machinery, /obj/machinery/door, /obj/machinery/light, /obj/machinery/deployable/barrier, /obj/machinery/porta_turret)
	for(var/type in types)
		var/obj/machinery/M = mach(type, tile(3, 2))
		for(var/stance in list(I_HELP, I_DISARM, I_GRAB))
			H.set_use_stance(stance)
			var/datum/op_resolution/R = op_resolve(H, M, W, ORIGIN_CLICK, actor_authority(H), GESTURE_CLICK)
			own(R)
			var/datum/op_cand/nonharm = op_resolution_winner(R)
			TEST_ASSERT(!(nonharm?.oplan.key in list("melee_hit", "strike", "hit")), "[type] does not select a damaging strike on a non-harm click")
			var/list/menu = op_menu(H, M, W)
			for(var/list/row as anything in menu)
				TEST_ASSERT(!(row["key"] in list("melee_hit", "strike", "hit")), "[type] also hides damaging strikes from its non-harm menu")
		H.set_use_stance(I_HURT)
		var/datum/op_resolution/harm = op_resolve(H, M, W, ORIGIN_CLICK, actor_authority(H), GESTURE_CLICK)
		own(harm)
		var/datum/op_cand/winner = op_resolution_winner(harm)
		TEST_ASSERT(winner?.oplan.key in list("melee_hit", "strike", "hit"), "[type] still resolves a real strike on harm")
	var/obj/machinery/ai_status_display/D = mach(/obj/machinery/ai_status_display, tile(3, 2))
	for(var/stance in list(I_HELP, I_DISARM, I_GRAB))
		H.set_use_stance(stance)
		var/before = D.get_integrity()
		var/datum/op_result/use = test_click(H, D, W)
		TEST_ASSERT_EQUAL(use?.key, "touch", "The real machine Use operation wins the non-harm click")
		TEST_ASSERT_EQUAL(use?.outcome, ACT_COMMITTED, "The machine's actual Use commits")
		TEST_ASSERT_EQUAL(D.get_integrity(), before, "Non-harm use does not damage the actual machine")
		test_time(1 SECOND)
	H.set_use_stance(I_HURT)
	var/before = D.get_integrity()
	var/datum/op_result/hit = test_click(H, D, W)
	TEST_ASSERT_EQUAL(hit?.key, "melee_hit", "Harm reaches the real inherited hit")
	TEST_ASSERT_EQUAL(hit?.outcome, ACT_COMMITTED, "The actual harm hit commits")
	TEST_ASSERT(D.get_integrity() < before, "Harm still damages the actual machine")

	// A deliberate native AI attack names its intent rather than the player's stance.
	test_time(1 SECOND)
	H.set_use_stance(I_HELP)
	var/ai_before = D.get_integrity()
	TEST_ASSERT_EQUAL(perform_intent(H, D, INTENT_ATTACK, W), "melee_hit", "An explicit AI attack remains available without harm click stance")
	TEST_ASSERT(D.get_integrity() < ai_before, "The explicit AI attack still damages the actual machine")
