// The test override observes the real console's window-opening effects without a client.
/obj/machinery/computer/med_data/dq_native_slot_probe
	var/window_opens = 0

/obj/machinery/computer/med_data/dq_native_slot_probe/tgui_interact(mob/user, datum/tgui/ui, datum/tgui/parent_ui, datum/tgui_state/custom_state)
	window_opens++

/datum/unit_test/dq_hc_computers/medical_native_slot
/datum/unit_test/dq_hc_computers/medical_native_slot/run_gate()
	var/obj/machinery/computer/med_data/dq_native_slot_probe/C = hc_console(/obj/machinery/computer/med_data/dq_native_slot_probe)
	var/mob/living/carbon/human/H = hc_actor()
	H.set_use_stance(I_HELP)
	var/datum/op_result/opened = test_click(H, C)
	TEST_ASSERT_EQUAL(opened?.key, "ui_open", "The existing generated window remains the empty-hand plain click")
	TEST_ASSERT(C.window_opens > 0, "The plain click actually opens the medical records window")
	var/obj/item/card/id/card = allocate(/obj/item/card/id, hc_side())
	TEST_ASSERT(H.put_in_active_hand(card), "The actor really carries the insertion card")
	var/datum/op_result/clicked = test_click(H, C, card)
	TEST_ASSERT_EQUAL(clicked?.key, "use_item", "Card clicks retain master's generic computer item ranking")
	TEST_ASSERT_NULL(C.scan, "The unchanged generic item click does not silently insert an ID")
	var/menu_opens_before = C.window_opens
	var/datum/op_result/menu_opened = test_menu(H, C, "open_records")
	TEST_ASSERT_EQUAL(menu_opened?.outcome, ACT_COMMITTED, "The existing named records menu action still works while carrying an ID")
	TEST_ASSERT(C.window_opens > menu_opens_before, "The held-card menu action actually opens the records window")
	TEST_ASSERT_NULL(C.scan, "Opening records from the menu does not insert the held ID")
	TEST_ASSERT(H.is_in_hands(card), "The menu's records action leaves the ID carried")
	var/opens_before = C.window_opens
	var/datum/op_result/inserted = test_menu(H, C, "insert_scan")
	TEST_ASSERT_EQUAL(inserted?.outcome, ACT_COMMITTED, "The existing named insertion commits through the real menu")
	TEST_ASSERT_EQUAL(C.scan, card, "The declared owned slot adopts the actual carried card")
	TEST_ASSERT_EQUAL(card.loc, C, "The card is physically contained by the console")
	TEST_ASSERT(!H.is_in_hands(card), "Insertion releases the player's hand")
	TEST_ASSERT(C.window_opens > opens_before, "Insertion retains its records-opening effect")
	var/obj/item/card/id/second = allocate(/obj/item/card/id, hc_side())
	TEST_ASSERT(H.put_in_active_hand(second), "The actor carries a second card")
	var/datum/op_result/full = test_click(H, C, second)
	TEST_ASSERT_EQUAL(full?.key, "use_item", "An occupied ID slot passes the plain click to the computer item fallback")
	TEST_ASSERT_EQUAL(C.scan, card, "Full-slot fallthrough preserves the first card")
	TEST_ASSERT(H.is_in_hands(second), "Full-slot fallthrough does not consume the second card")
	H.drop_from_inventory(second)
	var/datum/op_result/ejected = test_menu(H, C, "eject_scan_menu")
	TEST_ASSERT_EQUAL(ejected?.outcome, ACT_COMMITTED, "The named menu eject commits")
	TEST_ASSERT_NULL(C.scan, "Eject clears the one-occupant slot")
	TEST_ASSERT(H.is_in_hands(card), "Eject returns the physical card into a free hand")

/datum/unit_test/dq_hc_computers/medical_native_slot_unpowered
/datum/unit_test/dq_hc_computers/medical_native_slot_unpowered/run_gate()
	var/obj/machinery/computer/med_data/dq_native_slot_probe/C = hc_console(/obj/machinery/computer/med_data/dq_native_slot_probe)
	C.set_grid_power(FALSE)
	C.set_broken_condition(TRUE)
	var/mob/living/carbon/human/H = hc_actor()
	H.set_use_stance(I_HELP)
	var/obj/item/card/id/card = allocate(/obj/item/card/id, hc_side())
	TEST_ASSERT(H.put_in_active_hand(card), "The actor carries an ID beside the broken, unpowered console")
	var/datum/op_result/inserted = test_menu(H, C, "insert_scan")
	TEST_ASSERT_EQUAL(inserted?.outcome, ACT_COMMITTED, "The physical ID slot still accepts insertion without power or an intact screen")
	TEST_ASSERT_EQUAL(C.scan, card, "The unavailable window does not stop physical slot adoption")
	var/datum/op_result/ejected = test_menu(H, C, "eject_scan_menu")
	TEST_ASSERT_EQUAL(ejected?.outcome, ACT_COMMITTED, "The physical eject remains usable while broken and unpowered")
	TEST_ASSERT_NULL(C.scan, "The unavailable window does not stop physical slot release")
	TEST_ASSERT(H.is_in_hands(card), "Physical ejection returns the ID to the actor")

/datum/unit_test/dq_hc_computers/medical_native_slot_full_hands
/datum/unit_test/dq_hc_computers/medical_native_slot_full_hands/run_gate()
	var/obj/machinery/computer/med_data/dq_native_slot_probe/C = hc_console(/obj/machinery/computer/med_data/dq_native_slot_probe)
	var/mob/living/carbon/human/H = hc_actor()
	H.set_use_stance(I_HELP)
	var/obj/item/card/id/card = allocate(/obj/item/card/id, hc_side())
	TEST_ASSERT(H.put_in_active_hand(card), "The actor holds the ID before inserting it")
	var/datum/op_result/inserted = test_menu(H, C, "insert_scan")
	TEST_ASSERT_EQUAL(inserted?.outcome, ACT_COMMITTED, "The ID is inserted before the actor fills both hands")
	TEST_ASSERT_EQUAL(C.scan, card, "The physical console slot holds that ID")
	var/obj/item/first = allocate(/obj/item, hc_side())
	var/obj/item/second = allocate(/obj/item, hc_side())
	TEST_ASSERT(H.put_in_hands(first), "The actor fills one free hand")
	TEST_ASSERT(H.put_in_hands(second), "The actor fills the remaining hand")
	TEST_ASSERT(H.is_in_hands(first) && H.is_in_hands(second), "Both hands genuinely hold other objects")
	var/datum/op_result/ejected = test_menu(H, C, "eject_scan_menu")
	TEST_ASSERT_EQUAL(ejected?.outcome, ACT_COMMITTED, "The named eject still commits with full hands")
	TEST_ASSERT_NULL(C.scan, "The single-occupant owned var is cleared by ejection")
	TEST_ASSERT_EQUAL(card.loc, get_turf(H), "With no free hand the returned card lands at the actor's feet")
	TEST_ASSERT(!H.is_in_hands(card), "Eject does not replace either object already carried")
	TEST_ASSERT(H.is_in_hands(first) && H.is_in_hands(second), "Both existing hand occupants remain carried")
