// Old-code pins: custody, stack costs, real delays and claiming tool work.
/datum/unit_test/dq_machinery_timed_material_pin
	parent_type = /datum/unit_test/dq_timed_pin
	abstract_type = /datum/unit_test/dq_machinery_timed_material_pin

/datum/unit_test/dq_machinery_timed_material_pin/Run()
	dq_latency_isolate_diagnostics()
	return ..()

/datum/unit_test/dq_machinery_timed_material_pin/proc/equip(mob/living/carbon/human/H, obj/item/I)
	H.drop_item()
	TEST_ASSERT(H.put_in_active_hand(I), "the real input is held by the actual actor")

/datum/unit_test/dq_machinery_timed_material_pin/proc/begin_pin(mob/H, atom/target, obj/item/I, duration)
	test_click(H, target, I)
	var/datum/job = running(H)
	TEST_ASSERT(job, "the real input starts timed work")
	TEST_ASSERT(isnull(declared_duration(job)) || declared_duration(job) == duration, "the legacy job declares the pinned duration")
	return job

/datum/unit_test/dq_machinery_timed_material_pin/proc/lit_welder(mob/living/carbon/human/H, path = /obj/item/weldingtool)
	var/obj/item/weldingtool/W = allocate(path, H.loc)
	W.reagents.add_reagent(REAGENT_ID_FUEL, W.max_fuel)
	W.no_passive_burn = TRUE // isolate the action cost from the welder's independent idle burner
	W.setWelding(TRUE)
	equip(H, W)
	return W

/datum/unit_test/dq_machinery_timed_material_pin/bioprinter_load
/datum/unit_test/dq_machinery_timed_material_pin/bioprinter_load/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/organ_printer/flesh/M = allocate(/obj/machinery/organ_printer/flesh, H.loc)
	var/obj/item/reagent_containers/glass/beaker/B = allocate(/obj/item/reagent_containers/glass/beaker, H.loc)
	B.reagents.add_reagent(REAGENT_ID_BIOMASS, 12)
	equip(H, B)
	begin_pin(H, M, B, 1 SECOND)
	TEST_ASSERT_NULL(M.container, "loading does not move the beaker before the delay")
	TEST_ASSERT_EQUAL(B.loc, H, "the exact input remains in the real hand while waiting")
	test_time(0.5 SECONDS)
	TEST_ASSERT_NULL(M.container, "half a second is insufficient to load")
	test_time(0.6 SECONDS)
	TEST_ASSERT_EQUAL(M.container, B, "completion loads the original beaker relation")
	TEST_ASSERT_EQUAL(B.loc, M, "completion moves the original beaker inside the printer")
	TEST_ASSERT_EQUAL(B.reagents.get_reagent_amount(REAGENT_ID_BIOMASS), 12, "loading spends no biomass")
	TEST_ASSERT_NULL(running(H), "loading leaves no timed action")

/datum/unit_test/dq_machinery_timed_material_pin/bioprinter_cancel
/datum/unit_test/dq_machinery_timed_material_pin/bioprinter_cancel/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/organ_printer/flesh/M = allocate(/obj/machinery/organ_printer/flesh, H.loc)
	var/obj/item/reagent_containers/glass/beaker/B = allocate(/obj/item/reagent_containers/glass/beaker, H.loc)
	equip(H, B)
	var/datum/job = begin_pin(H, M, B, 1 SECOND)
	H.forceMove(get_step(H, EAST))
	test_time(2 SECONDS)
	TEST_ASSERT_NULL(M.container, "moving cancels actual beaker insertion")
	TEST_ASSERT_EQUAL(B.loc, H, "cancellation preserves the original held beaker")
	TEST_ASSERT(was_cancelled(job, H), "the timed insertion actually cancels")

/datum/unit_test/dq_machinery_timed_material_pin/clonepod_load
/datum/unit_test/dq_machinery_timed_material_pin/clonepod_load/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/clonepod/M = allocate(/obj/machinery/clonepod, H.loc)
	var/obj/item/reagent_containers/glass/beaker/B = allocate(/obj/item/reagent_containers/glass/beaker, H.loc)
	B.reagents.add_reagent(REAGENT_ID_BIOMASS, 9)
	equip(H, B)
	begin_pin(H, M, B, 1 SECOND)
	TEST_ASSERT(!(B in M.containers), "the pod holds no input container before completion")
	test_time(0.5 SECONDS)
	TEST_ASSERT_EQUAL(B.loc, H, "the actual beaker remains held during the loading delay")
	test_time(0.6 SECONDS)
	TEST_ASSERT(B in M.containers, "completion adds the exact beaker to the pod's relation")
	TEST_ASSERT_EQUAL(B.loc, M, "the input becomes physically contained by the pod")
	TEST_ASSERT_EQUAL(B.reagents.get_reagent_amount(REAGENT_ID_BIOMASS), 9, "loading spends no liquid biomass")

/datum/unit_test/dq_machinery_timed_material_pin/clonepod_cancel
/datum/unit_test/dq_machinery_timed_material_pin/clonepod_cancel/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/clonepod/M = allocate(/obj/machinery/clonepod, H.loc)
	var/obj/item/reagent_containers/glass/beaker/B = allocate(/obj/item/reagent_containers/glass/beaker, H.loc)
	equip(H, B)
	var/datum/job = begin_pin(H, M, B, 1 SECOND)
	H.drop_item()
	test_time(2 SECONDS)
	TEST_ASSERT(!(B in M.containers), "dropping the input cancels actual pod loading")
	TEST_ASSERT_EQUAL(B.loc, H.loc, "the dropped beaker stays on the real floor")
	TEST_ASSERT(was_cancelled(job, H), "the pod load actually cancels")

/datum/unit_test/dq_machinery_timed_material_pin/ai_core_cable
/datum/unit_test/dq_machinery_timed_material_pin/ai_core_cable/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/structure/AIcore/M = allocate(/obj/structure/AIcore, H.loc)
	M.set_state(2)
	var/obj/item/stack/cable_coil/C = allocate(/obj/item/stack/cable_coil, H.loc, 8)
	equip(H, C)
	begin_pin(H, M, C, 2 SECONDS)
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(M.state, 2, "the core is not wired before the two-second delay")
	TEST_ASSERT_EQUAL(C.get_amount(), 8, "no cable is spent before completion")
	test_time(1.1 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 3, "completion wires the real core")
	TEST_ASSERT_EQUAL(C.get_amount(), 3, "wiring spends exactly five cable units")
	TEST_ASSERT_EQUAL(M.icon_state, "3", "the core shows its actual wired state")

/datum/unit_test/dq_machinery_timed_material_pin/ai_core_cable_cancel
/datum/unit_test/dq_machinery_timed_material_pin/ai_core_cable_cancel/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/structure/AIcore/M = allocate(/obj/structure/AIcore, H.loc)
	M.set_state(2)
	var/obj/item/stack/cable_coil/C = allocate(/obj/item/stack/cable_coil, H.loc, 8)
	equip(H, C)
	var/datum/job = begin_pin(H, M, C, 2 SECONDS)
	H.forceMove(get_step(H, EAST))
	test_time(3 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 2, "walking away leaves the original core unwired")
	TEST_ASSERT_EQUAL(C.get_amount(), 8, "cancellation spends no cable")
	TEST_ASSERT(was_cancelled(job, H), "the cable action actually cancels")

/datum/unit_test/dq_machinery_timed_material_pin/ai_core_glass
/datum/unit_test/dq_machinery_timed_material_pin/ai_core_glass/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/structure/AIcore/M = allocate(/obj/structure/AIcore, H.loc)
	M.set_state(3)
	var/obj/item/stack/material/glass/reinforced/G = allocate(/obj/item/stack/material/glass/reinforced, H.loc, 4)
	equip(H, G)
	begin_pin(H, M, G, 2 SECONDS)
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(M.state, 3, "the panel is absent before completion")
	TEST_ASSERT_EQUAL(G.get_amount(), 4, "no reinforced glass is spent early")
	test_time(1.1 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 4, "completion installs the actual reinforced panel")
	TEST_ASSERT_EQUAL(G.get_amount(), 2, "the panel costs exactly two sheets")
	TEST_ASSERT_EQUAL(M.icon_state, "4", "the real core shows the installed panel")

/datum/unit_test/dq_machinery_timed_material_pin/ai_core_glass_cancel
/datum/unit_test/dq_machinery_timed_material_pin/ai_core_glass_cancel/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/structure/AIcore/M = allocate(/obj/structure/AIcore, H.loc)
	M.set_state(3)
	var/obj/item/stack/material/glass/reinforced/G = allocate(/obj/item/stack/material/glass/reinforced, H.loc, 4)
	equip(H, G)
	var/datum/job = begin_pin(H, M, G, 2 SECONDS)
	H.drop_item()
	test_time(3 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 3, "dropping the stack leaves the real core without a panel")
	TEST_ASSERT_EQUAL(G.get_amount(), 4, "cancellation spends no reinforced glass")
	TEST_ASSERT(was_cancelled(job, H), "the panel action actually cancels")

/datum/unit_test/dq_machinery_timed_material_pin/breaker_toggle
/datum/unit_test/dq_machinery_timed_material_pin/breaker_toggle/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/power/breakerbox/M = allocate(/obj/machinery/power/breakerbox, H.loc)
	begin_pin(H, M, null, 5 SECONDS)
	test_time(4 SECONDS)
	TEST_ASSERT(!M.on && !M.update_locked, "the real breaker stays off and unlocked while work is pending")
	test_time(1.1 SECONDS)
	TEST_ASSERT(M.on && M.update_locked, "completion switches the breaker and applies its update lock")
	TEST_ASSERT_EQUAL(M.icon_state, M.icon_state_on, "the actual switch presents its enabled state")
	TEST_ASSERT_NULL(running(H), "the toggle's timed action ends")

/datum/unit_test/dq_machinery_timed_material_pin/breaker_cancel_and_claim
/datum/unit_test/dq_machinery_timed_material_pin/breaker_cancel_and_claim/run_pin()
	var/mob/living/carbon/human/H = person()
	var/mob/living/carbon/human/other = person(H.loc)
	var/obj/machinery/power/breakerbox/M = allocate(/obj/machinery/power/breakerbox, H.loc)
	var/datum/job = begin_pin(H, M, null, 5 SECONDS)
	test_click(other, M, null)
	TEST_ASSERT_NULL(running(other), "a second actual actor cannot start work on the claimed breaker")
	TEST_ASSERT_EQUAL(running(H), job, "the first actor's original action retains its claim")
	H.forceMove(get_step(H, EAST))
	test_time(6 SECONDS)
	TEST_ASSERT(!M.on && !M.update_locked, "moving away leaves the real breaker off without an update lock")
	TEST_ASSERT(was_cancelled(job, H), "the claiming action actually cancels")

/datum/unit_test/dq_machinery_timed_material_pin/camera_repair
/datum/unit_test/dq_machinery_timed_material_pin/camera_repair/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/camera/M = allocate(/obj/machinery/camera, H.loc)
	M.set_broken_condition(TRUE)
	var/obj/item/camera_assembly/assembly = own(M.assembly)
	var/obj/item/weldingtool/W = lit_welder(H)
	var/fuel = W.get_fuel()
	begin_pin(H, M, W, 10 SECONDS)
	test_time(9 SECONDS)
	TEST_ASSERT(!QDELETED(M) && M.assembly == assembly, "the exact broken camera and assembly persist before completion")
	test_time(1.1 SECONDS)
	TEST_ASSERT(QDELETED(M), "completion removes the repaired camera holder")
	TEST_ASSERT_EQUAL(assembly.loc, H.loc, "the original repaired assembly is on the actual floor")
	TEST_ASSERT_EQUAL(assembly.state, 2, "repair yields the original welded assembly state")
	TEST_ASSERT(assembly.anchored, "the repaired original assembly stays anchored")
	TEST_ASSERT_EQUAL(W.get_fuel(), fuel, "legacy camera welding has zero explicit fuel cost")

/datum/unit_test/dq_machinery_timed_material_pin/camera_cancel_and_claim
/datum/unit_test/dq_machinery_timed_material_pin/camera_cancel_and_claim/run_pin()
	var/mob/living/carbon/human/H = person()
	var/mob/living/carbon/human/other = person(H.loc)
	var/obj/machinery/camera/M = allocate(/obj/machinery/camera, H.loc)
	M.set_broken_condition(TRUE)
	var/obj/item/camera_assembly/assembly = own(M.assembly)
	var/obj/item/weldingtool/W = lit_welder(H)
	var/obj/item/weldingtool/other_W = lit_welder(other)
	var/datum/job = begin_pin(H, M, W, 10 SECONDS)
	test_click(other, M, other_W)
	TEST_ASSERT_NULL(running(other), "a second actual welder cannot claim the busy camera")
	H.forceMove(get_step(H, EAST))
	test_time(11 SECONDS)
	TEST_ASSERT(!QDELETED(M) && M.assembly == assembly, "cancellation preserves the real camera and original assembly")
	TEST_ASSERT_EQUAL(assembly.loc, M, "cancellation keeps the actual assembly contained")
	TEST_ASSERT(was_cancelled(job, H), "the claiming camera action actually cancels")

/datum/unit_test/dq_machinery_timed_material_pin/proc/assembly_weld(mob/H, obj/item/camera_assembly/M, obj/item/W)
	test_click(H, M, W)

/datum/unit_test/dq_machinery_timed_material_pin/assembly_weld_claim
/datum/unit_test/dq_machinery_timed_material_pin/assembly_weld_claim/run_pin()
	var/mob/living/carbon/human/H = person()
	var/mob/living/carbon/human/other = person(H.loc)
	var/obj/item/camera_assembly/M = allocate(/obj/item/camera_assembly, H.loc)
	M.set_state(1)
	M.set_anchored(TRUE)
	var/obj/item/weldingtool/W = lit_welder(H)
	var/obj/item/weldingtool/other_W = lit_welder(other)
	var/fuel = W.get_fuel()
	assembly_weld(H, M, W)
	var/datum/job = running(H)
	TEST_ASSERT(job, "the actual assembly welding starts timed work")
	assembly_weld(other, M, other_W)
	TEST_ASSERT_NULL(running(other), "a second welder cannot start on the claimed assembly")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(M.state, 1, "the real assembly remains unwelded before completion")
	test_time(1.1 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 2, "completion welds the real assembly into place")
	TEST_ASSERT(M.anchored, "the completed assembly remains actually anchored")
	TEST_ASSERT_EQUAL(W.get_fuel(), fuel, "legacy assembly welding has zero explicit fuel cost")

/datum/unit_test/dq_machinery_timed_material_pin/assembly_weld_cancel
/datum/unit_test/dq_machinery_timed_material_pin/assembly_weld_cancel/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/item/camera_assembly/M = allocate(/obj/item/camera_assembly, H.loc)
	M.set_state(1)
	M.set_anchored(TRUE)
	var/obj/item/weldingtool/W = lit_welder(H)
	assembly_weld(H, M, W)
	var/datum/job = running(H)
	TEST_ASSERT(job, "the actual assembly starts timed welding")
	H.forceMove(get_step(H, EAST))
	test_time(3 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 1, "walking away leaves the exact assembly unwelded")
	TEST_ASSERT(was_cancelled(job, H), "the assembly welding actually cancels")

// Additional native regressions; the ordinary-tool pins above were verified on old code.
/datum/unit_test/dq_machinery_timed_material_pin/camera_fast_welder
/datum/unit_test/dq_machinery_timed_material_pin/camera_fast_welder/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/camera/M = allocate(/obj/machinery/camera, H.loc)
	M.set_broken_condition(TRUE)
	var/obj/item/camera_assembly/assembly = own(M.assembly)
	var/obj/item/weldingtool/W = lit_welder(H, /obj/item/weldingtool/experimental)
	TEST_ASSERT_EQUAL(W.toolspeed, 0.5, "the real experimental welder has its actual speed multiplier")
	begin_pin(H, M, W, 5 SECONDS)
	test_time(4 SECONDS)
	TEST_ASSERT(!QDELETED(M), "the actual fast tool does not finish before five seconds")
	test_time(1.1 SECONDS)
	TEST_ASSERT(QDELETED(M) && assembly.state == 2, "the real fast welder finishes camera repair at five seconds")

/datum/unit_test/dq_machinery_timed_material_pin/assembly_fast_welder
/datum/unit_test/dq_machinery_timed_material_pin/assembly_fast_welder/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/item/camera_assembly/M = allocate(/obj/item/camera_assembly, H.loc)
	M.set_state(1)
	M.set_anchored(TRUE)
	var/obj/item/weldingtool/W = lit_welder(H, /obj/item/weldingtool/experimental)
	TEST_ASSERT_EQUAL(W.toolspeed, 0.5, "the real experimental welder retains its actual speed multiplier")
	begin_pin(H, M, W, 1 SECOND)
	test_time(0.5 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 1, "half a second is insufficient for the actual faster tool")
	test_time(0.6 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 2, "the real fast welder finishes assembly work after one second")

// Native wire subscriptions stop work as soon as its dismantling admission disappears.
/datum/unit_test/dq_machinery_timed_material_pin/camera_mending_interrupts
/datum/unit_test/dq_machinery_timed_material_pin/camera_mending_interrupts/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/camera/M = allocate(/obj/machinery/camera, H.loc)
	M.set_broken_condition(FALSE)
	var/obj/item/camera_assembly/assembly = own(M.assembly)
	TEST_ASSERT(wires_cut_all(M) > 0 && wires_all_cut(M), "the healthy real camera has all of its actual wires cut")
	var/obj/item/weldingtool/W = lit_welder(H)
	begin_pin(H, M, W, 10 SECONDS)
	test_time(1 SECOND)
	TEST_ASSERT(running(H), "the real dismantling op is still waiting before the wire repair")
	TEST_ASSERT(wires_mend_all(M) > 0 && !wires_all_cut(M), "the actual wires are mended through their published API")
	TEST_ASSERT_NULL(running(H), "the published wire change immediately interrupts the now-ineligible op")
	TEST_ASSERT(!QDELETED(M) && M.assembly == assembly, "immediate interruption preserves the actual healthy camera and original assembly")
	test_time(10 SECONDS)
	TEST_ASSERT(!QDELETED(M) && assembly.loc == M, "the interrupted operation never dismantles the restored camera later")

// Native-only variant proof: a zero-unit fuel reservation still commits the
// electric welder's real per-use charge, exactly as its legacy remove_fuel(0).
/datum/unit_test/dq_machinery_timed_material_pin/assembly_electric_charge
/datum/unit_test/dq_machinery_timed_material_pin/assembly_electric_charge/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/item/camera_assembly/M = allocate(/obj/item/camera_assembly, H.loc)
	M.set_state(1)
	M.set_anchored(TRUE)
	var/obj/item/weldingtool/electric/W = lit_welder(H, /obj/item/weldingtool/electric)
	TEST_ASSERT(W.power_supply, "the actual electric welder has its real initial power cell")
	W.power_supply.give(W.power_supply.maxcharge)
	var/charge = W.power_supply.charge
	var/expected_charge = charge - W.charge_cost / W.power_supply.material_delivery_efficiency(W.charge_cost)
	TEST_ASSERT(charge > W.charge_cost, "the actual cell holds enough energy for the real per-use cost")
	begin_pin(H, M, W, 2 SECONDS)
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(W.power_supply.charge, charge, "the electric action spends no charge before completion")
	test_time(1.1 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 2, "the real electric welder completes assembly welding")
	TEST_ASSERT_EQUAL(W.power_supply.charge, expected_charge, "the native zero-unit fuel reservation pays exactly one electric per-use charge including the real cell's material delivery loss")

/datum/unit_test/dq_machinery_timed_material_pin/assembly_electric_cancel
/datum/unit_test/dq_machinery_timed_material_pin/assembly_electric_cancel/run_pin()
	var/mob/living/carbon/human/H = person()
	var/obj/item/camera_assembly/M = allocate(/obj/item/camera_assembly, H.loc)
	M.set_state(1)
	M.set_anchored(TRUE)
	var/obj/item/weldingtool/electric/W = lit_welder(H, /obj/item/weldingtool/electric)
	TEST_ASSERT(W.power_supply, "the actual electric welder starts with its original power cell")
	W.power_supply.give(W.power_supply.maxcharge)
	var/charge = W.power_supply.charge
	var/datum/job = begin_pin(H, M, W, 2 SECONDS)
	H.forceMove(get_step(H, EAST))
	test_time(3 SECONDS)
	TEST_ASSERT_EQUAL(M.state, 1, "cancellation leaves the real assembly unwelded")
	TEST_ASSERT_EQUAL(W.power_supply.charge, charge, "cancellation commits no electric per-use charge")
	TEST_ASSERT(was_cancelled(job, H), "the electric welding action actually cancels")
