// Generated once from the pre-conversion source (commit 62e4e63d7b) by reading
// `/type::matter` for every /obj/item subtype. Lists only the types whose value differs
// from their parent's; every other type inherits its nearest listed ancestor's value.
// Do not regenerate from the current tree: this is the reference the conversion is checked against.
/proc/dq_matter_snapshot_changes()
	var/static/list/changes = list(
		/obj/item/clothing = list("fibers" = 50),
		/obj/item/clothing/head/pin/magnetic = list("steel" = 10),
		/obj/item/clothing/head/welding = list("steel" = 3000, "glass" = 1000),
		/obj/item/clothing/glasses/welding = list("steel" = 1500, "glass" = 1000),
		/obj/item/clothing/accessory/collar/holo = list("steel" = 50),
		/obj/item/clothing/accessory/knuckledusters = list("steel" = 500),
		/obj/item/paicard/sleevecard = list("steel" = 4000, "glass" = 4000),
		/obj/item/tool/screwdriver = list("steel" = 75),
		/obj/item/tool/crowbar = list("steel" = 50),
		/obj/item/tool/wirecutters = list("steel" = 80),
		/obj/item/tool/wrench = list("steel" = 150),
		/obj/item/tool/prybar = list("steel" = 30),
		/obj/item/tool/transforming/jawsoflife = list("MAT_METAL" = 150, "silver" = 50),
		/obj/item/tool/transforming/powerdrill = list("steel" = 150, "silver" = 50),
		/obj/item/storage = list("fibers" = 50),
		/obj/item/stack/sandbags = list("cloth" = 4000),
		/obj/item/stack/sandbags/cyborg = null,
		/obj/item/stack/tile/floor = list("steel" = 500),
		/obj/item/stack/tile/floor/steel_dirty = list("plasteel" = 500),
		/obj/item/stack/tile/floor/steel = list("plasteel" = 500),
		/obj/item/stack/tile/floor/white = list("plastic" = 500),
		/obj/item/stack/tile/floor/dark = list("plasteel" = 500),
		/obj/item/stack/tile/floor/freezer = list("plastic" = 500),
		/obj/item/stack/tile/floor/cyborg = null,
		/obj/item/stack/tile/floor/gold = list("gold" = 500),
		/obj/item/stack/tile/floor/silver = list("silver" = 500),
		/obj/item/stack/tile/floor/phoron = list("phoron" = 500),
		/obj/item/stack/tile/floor/diamond = list("diamond" = 500),
		/obj/item/stack/tile/floor/uranium = list("uranium" = 500),
		/obj/item/stack/tile/floor/eris/cafe = list("plastic" = 1),
		/obj/item/stack/tile/floor/eris/bcircuit = list("steel" = 1),
		/obj/item/stack/tile/floor/eris/derelict1 = list("steel" = 1),
		/obj/item/stack/tile/floor/eris/derelict2 = list("steel" = 1),
		/obj/item/stack/tile/floor/eris/derelict3 = list("steel" = 1),
		/obj/item/stack/tile/floor/eris/derelict4 = list("steel" = 1),
		/obj/item/stack/tile/floor/eris/techmaint = list("steel" = 1),
		/obj/item/stack/tile/floor/eris/steel = list("steel" = 1),
		/obj/item/stack/tile/floor/eris/white = list("plastic" = 1),
		/obj/item/stack/tile/floor/eris/dark = list("steel" = 1),
		/obj/item/stack/tile/maintenance_panel = list("steel" = 500),
		/obj/item/stack/cable_coil = list("steel" = 50, "glass" = 20),
		/obj/item/stack/cable_coil/cyborg = null,
		/obj/item/stack/rods = list("steel" = 10),
		/obj/item/stack/rods/cyborg = null,
		/obj/item/disk/tech_disk = list("steel" = 30, "glass" = 10),
		/obj/item/disk/design_disk = list("steel" = 30, "glass" = 10),
		/obj/item/SWF_uplink = list("steel" = 100),
		/obj/item/module/power_control = list("glass" = 40),
		/obj/item/stock_parts/console_screen = list("glass" = 200),
		/obj/item/stock_parts/capacitor = list("steel" = 50, "glass" = 50),
		/obj/item/stock_parts/scanning_module = list("steel" = 50, "glass" = 20),
		/obj/item/stock_parts/manipulator = list("steel" = 30),
		/obj/item/stock_parts/micro_laser = list("steel" = 10, "glass" = 20),
		/obj/item/stock_parts/matter_bin = list("steel" = 80),
		/obj/item/stock_parts/subspace/ansible = list("steel" = 30, "glass" = 10),
		/obj/item/stock_parts/subspace/sub_filter = list("steel" = 30, "glass" = 10),
		/obj/item/stock_parts/subspace/amplifier = list("steel" = 30, "glass" = 10),
		/obj/item/stock_parts/subspace/treatment = list("steel" = 30, "glass" = 10),
		/obj/item/stock_parts/subspace/analyzer = list("steel" = 30, "glass" = 10),
		/obj/item/stock_parts/subspace/crystal = list("glass" = 50),
		/obj/item/stock_parts/subspace/transmitter = list("steel" = 50),
		/obj/item/stock_parts/gear = list("steel" = 50),
		/obj/item/stock_parts/motor = list("steel" = 60, "glass" = 10),
		/obj/item/stock_parts/spring = list("steel" = 40),
		/obj/item/flashlight = list("steel" = 50, "glass" = 20),
		/obj/item/flashlight/maglight = list("steel" = 200, "glass" = 50),
		/obj/item/material/knife = list("steel" = 12000),
		/obj/item/pinpointer = list("steel" = 500),
		/obj/item/weldingtool = list("steel" = 70, "glass" = 30),
		/obj/item/weldingtool/brass = list("steel" = 70, "glass" = 60),
		/obj/item/weldingtool/largetank = list("steel" = 70, "glass" = 60),
		/obj/item/weldingtool/hugetank = list("steel" = 70, "glass" = 120),
		/obj/item/weldingtool/mini = list("MAT_METAL" = 30, "glass" = 10),
		/obj/item/weldingtool/experimental = list("steel" = 70, "glass" = 120),
		/obj/item/weldingtool/tubefed = null,
		/obj/item/circuitboard = list("glass" = 40),
		/obj/item/circuitboard/geiger = list("steel" = 50, "glass" = 50),
		/obj/item/circuitboard/teleporter_hub = list("steel" = 50, "glass" = 50, "gold" = 100),
		/obj/item/circuitboard/teleporter_station = list("steel" = 50, "glass" = 50, "gold" = 100),
		/obj/item/circuitboard/microwave/advanced = list("steel" = 50, "glass" = 50),
		/obj/item/circuitboard/security/telescreen/entertainment = list("steel" = 50, "glass" = 50),
		/obj/item/circuitboard/security/telescreen/bodycamera = list("steel" = 50, "glass" = 50),
		/obj/item/circuitboard/pipelayer = list("steel" = 50, "glass" = 50),
		/obj/item/frame/apc = list("steel" = 100, "glass" = 30),
		/obj/item/floor_light = list("steel" = 2500, "glass" = 2750),
		/obj/item/reagent_containers/glass/beaker = list("glass" = 500),
		/obj/item/reagent_containers/glass/beaker/vial = list("glass" = 250),
		/obj/item/reagent_containers/glass/beaker/large = list("glass" = 5000),
		/obj/item/reagent_containers/glass/beaker/bluespace = list("glass" = 5000),
		/obj/item/reagent_containers/glass/paint = list("steel" = 200),
		/obj/item/reagent_containers/glass/bucket = list("steel" = 200),
		/obj/item/reagent_containers/glass/bucket/wood = list("wood" = 50),
		/obj/item/reagent_containers/glass/cooler_bottle = list("plastic" = 2000),
		/obj/item/reagent_containers/glass/pint_mug = list("wood" = 50),
		/obj/item/reagent_containers/glass/kettle = list("steel" = 50),
		/obj/item/reagent_containers/food/drinks/glass2 = list("glass" = 60),
		/obj/item/reagent_containers/food/drinks/glass2/rocks = list("glass" = 40),
		/obj/item/reagent_containers/food/drinks/glass2/shake = list("glass" = 30),
		/obj/item/reagent_containers/food/drinks/glass2/cocktail = list("glass" = 30),
		/obj/item/reagent_containers/food/drinks/glass2/shot = list("glass" = 10),
		/obj/item/reagent_containers/food/drinks/glass2/pint = list("glass" = 120),
		/obj/item/reagent_containers/food/drinks/glass2/mug = list("glass" = 80),
		/obj/item/reagent_containers/food/drinks/glass2/wine = list("glass" = 50),
		/obj/item/reagent_containers/food/drinks/glass2/carafe = list("glass" = 50),
		/obj/item/reagent_containers/food/drinks/glass2/pitcher = list("plastic" = 50),
		/obj/item/reagent_containers/food/drinks/glass2/fitnessflask = list("plastic" = 2000),
		/obj/item/reagent_containers/food/drinks/metaglass = list("glass" = 500),
		/obj/item/reagent_containers/food/drinks/drinkingglass = list("glass" = 500),
		/obj/item/reagent_containers/food/drinks/drinkingglass/shotglass = list("glass" = 175),
		/obj/item/reagent_containers/food/drinks/drinkingglass/fitnessflask = list("plastic" = 2000),
		/obj/item/reagent_containers/ecig_cartridge = list("steel" = 50, "glass" = 10),
		/obj/item/reagent_containers/spray = list("glass" = 300, "steel" = 300),
		/obj/item/reagent_containers/syringe = list("glass" = 150),
		/obj/item/camera_assembly = list("steel" = 700, "glass" = 300),
		/obj/item/airlock_electronics = list("steel" = 50, "glass" = 50),
		/obj/item/mecha_parts/mecha_equipment/weapon = list("steel" = 6000, "glass" = 3000),
		/obj/item/mecha_parts/mecha_equipment/tool = list("steel" = 5000, "glass" = 3000),
		/obj/item/healthanalyzer = list("steel" = 200),
		/obj/item/surgical/retractor = list("steel" = 10000, "glass" = 5000),
		/obj/item/surgical/hemostat = list("steel" = 5000, "glass" = 2500),
		/obj/item/surgical/cautery = list("steel" = 5000, "glass" = 2500),
		/obj/item/surgical/surgicaldrill = list("steel" = 15000, "glass" = 10000),
		/obj/item/surgical/scalpel = list("steel" = 10000, "glass" = 5000),
		/obj/item/surgical/scalpel/amaryll_claws = null,
		/obj/item/surgical/circular_saw = list("steel" = 20000, "glass" = 10000),
		/obj/item/surgical/circular_saw/manager = list("steel" = 25000, "glass" = 20000),
		/obj/item/gun = list("steel" = 2000),
		/obj/item/gun/energy/chameleon = list(),
		/obj/item/gun/energy/crossbow/largecrossbow = list("steel" = 200000),
		/obj/item/gun/energy/altevian = list("steel" = 1000),
		/obj/item/gun/energy/altevian/large = list("steel" = 2000),
		/obj/item/gun/energy/laser/old = list("steel" = 1500),
		/obj/item/gun/energy/freezegun = list("durasteel" = 1000, "morphium" = 500),
		/obj/item/gun/projectile = list("steel" = 1000),
		/obj/item/gun/projectile/shotgun/pump/toy = list("plastic" = 2000),
		/obj/item/gun/projectile/shotgun/pump/toy/moistnugget = list("plastic" = 2500),
		/obj/item/gun/projectile/revolver/toy = list("plastic" = 1000),
		/obj/item/gun/projectile/revolver/toy/sawnoff = list("plastic" = 1500),
		/obj/item/gun/projectile/pistol/toy = list("plastic" = 1000),
		/obj/item/gun/projectile/automatic/toy = list("plastic" = 1500),
		/obj/item/gun/projectile/smartgun = list("steel" = 6000, "diamond" = 2000, "uranium" = 2000),
		/obj/item/trash = list("steel" = 30),
		/obj/item/trash/material = list(),
		/obj/item/light = list("steel" = 60),
		/obj/item/light/tube = list("glass" = 100),
		/obj/item/light/bulb = list("glass" = 100),
		/obj/item/cell = list("steel" = 700, "glass" = 50),
		/obj/item/cell/device = list("steel" = 350, "glass" = 50),
		/obj/item/cell/device/crap = list("steel" = 350, "glass" = 30),
		/obj/item/cell/device/hyper = list("steel" = 400, "glass" = 60),
		/obj/item/cell/device/empproof = list("steel" = 400, "glass" = 60),
		/obj/item/cell/device/weapon/empproof = list("steel" = 400, "glass" = 60),
		/obj/item/cell/device/weapon/recharge = list("steel" = 400, "glass" = 80),
		/obj/item/cell/device/weapon/recharge/captain = list("steel" = 400, "glass" = 100),
		/obj/item/cell/spike = list("steel" = 1000, "glass" = 80, "silver" = 100),
		/obj/item/cell/crap = list("steel" = 700, "glass" = 40),
		/obj/item/cell/high = list("steel" = 700, "glass" = 60),
		/obj/item/cell/super = list("steel" = 700, "glass" = 70),
		/obj/item/cell/hyper = list("steel" = 700, "glass" = 80),
		/obj/item/cell/mech = list("steel" = 800, "glass" = 60),
		/obj/item/cell/mech/lead = list("steel" = 300, "glass" = 10),
		/obj/item/cell/mech/high = list("steel" = 800, "glass" = 80),
		/obj/item/cell/mech/super = list("steel" = 800, "glass" = 100),
		/obj/item/cell/infinite = list("steel" = 700, "glass" = 80),
		/obj/item/cell/slime = null,
		/obj/item/cell/emergency_light = list("glass" = 20),
		/obj/item/cell/void = null,
		/obj/item/cell/secborg = list("steel" = 700, "glass" = 40),
		/obj/item/cell/giga = list("steel" = 1000, "glass" = 100),
		/obj/item/cell/vepr = list("MAT_METAL" = 350, "glass" = 50),
		/obj/item/cell/clockwork = null,
		/obj/item/laser_pointer = list("glass" = 500, "steel" = 500),
		/obj/item/deskbell = list("steel" = 50),
		/obj/item/pen = list("steel" = 10),
		/obj/item/glass_jar = list("glass" = 200),
		/obj/item/glass_jar/fish/plastic = list("plastic" = 4000),
		/obj/item/rig/ch/precursor = list("plasteel" = 1200, "gold" = 500, "graphite" = 800, "osmium" = 300, "plastic" = 600, "verdantium" = 750, "morphium" = 2000),
		/obj/item/buttonofnormal = list("steel" = 1000),
		/obj/item/daredevice = list("steel" = 5000),
		/obj/item/nifrepairer = list("steel" = 4000, "glass" = 6000),
		/obj/item/multitool = list("steel" = 50, "glass" = 20),
		/obj/item/bodysnatcher = list("steel" = 200),
		/obj/item/debugger = list("steel" = 50, "glass" = 20),
		/obj/item/gps = list("steel" = 500),
		/obj/item/geiger = list(/datum/material/steel = 3000, /datum/material/glass = 3000),
		/obj/item/lightpainter = list("steel" = 5000, "glass" = 1500),
		/obj/item/radio = list("glass" = 25, "steel" = 75),
		/obj/item/radio/headset = list("steel" = 75),
		/obj/item/radio/electropack = list("steel" = 10000, "glass" = 2500),
		/obj/item/powersink = list("steel" = 750),
		/obj/item/suit_cooling_unit = list("steel" = 15000, "glass" = 3500),
		/obj/item/t_scanner = list("steel" = 150),
		/obj/item/t_scanner/upgraded = list("steel" = 500, "PHORON" = 150),
		/obj/item/t_scanner/advanced = list("steel" = 1500, "PHORON" = 200, "SILVER" = 250),
		/obj/item/taperecorder = list("steel" = 60, "glass" = 30),
		/obj/item/rectape = list("steel" = 20, "glass" = 5),
		/obj/item/communicator = list("steel" = 30, "glass" = 10),
		/obj/item/analyzer = list("steel" = 30, "glass" = 20),
		/obj/item/mass_spectrometer = list("steel" = 30, "glass" = 20),
		/obj/item/motiontracker = list("steel" = 30, "glass" = 20),
		/obj/item/reagent_scanner = list("steel" = 30, "glass" = 20),
		/obj/item/sleevemate = list("steel" = 200),
		/obj/item/slime_scanner = list("steel" = 30, "glass" = 20),
		/obj/item/ammo_magazine = list("steel" = 500),
		/obj/item/ammo_magazine/m9mm = list("steel" = 600),
		/obj/item/ammo_magazine/m9mm/large = list("steel" = 1000),
		/obj/item/ammo_magazine/m9mm/compact = list("steel" = 480),
		/obj/item/ammo_magazine/m9mm/luger = list("steel" = 480),
		/obj/item/ammo_magazine/m9mml = list("steel" = 1800),
		/obj/item/ammo_magazine/s357 = list("steel" = 1260),
		/obj/item/ammo_magazine/s38 = list("steel" = 360),
		/obj/item/ammo_magazine/ammo_box = null,
		/obj/item/ammo_magazine/ammo_box/b38 = list("steel" = 1440),
		/obj/item/ammo_magazine/ammo_box/b44 = list("steel" = 5040),
		/obj/item/ammo_magazine/ammo_box/b44/rubber = list("steel" = 1440),
		/obj/item/ammo_magazine/ammo_box/foam = list("plastic" = 1800),
		/obj/item/ammo_magazine/ammo_box/foam/riot = list("steel" = 5040, "plastic" = 1800),
		/obj/item/ammo_magazine/ammo_box/cap = list("steel" = 2040),
		/obj/item/ammo_magazine/ammo_box/b357 = list("steel" = 5040),
		/obj/item/ammo_magazine/ammo_box/b10mm = list("steel" = 3000),
		/obj/item/ammo_magazine/ammo_box/b10mm/practice = list("steel" = 2400),
		/obj/item/ammo_magazine/ammo_box/b10mm/rubber = list("steel" = 2400),
		/obj/item/ammo_magazine/ammo_box/b10mm/emp = list("steel" = 5200, "uranium" = 4000),
		/obj/item/ammo_magazine/ammo_box/b45 = list("steel" = 1800),
		/obj/item/ammo_magazine/ammo_box/b45/practice = list("steel" = 1440),
		/obj/item/ammo_magazine/ammo_box/b45/ap = list("steel" = 1200, "plasteel" = 600),
		/obj/item/ammo_magazine/ammo_box/b45/hp = list("steel" = 1440, "plastic" = 360),
		/obj/item/ammo_magazine/ammo_box/b45/rubber = list("steel" = 1440),
		/obj/item/ammo_magazine/ammo_box/b45/emp = list("steel" = 3120, "uranium" = 2400),
		/obj/item/ammo_magazine/ammo_box/b12g = list("steel" = 2880),
		/obj/item/ammo_magazine/ammo_box/b12g/beanbag = list("steel" = 1440),
		/obj/item/ammo_magazine/ammo_box/b12g/stunshell = list("steel" = 2880, "glass" = 5760),
		/obj/item/ammo_magazine/ammo_box/b12g/emp = list("steel" = 2880, "uranium" = 1920),
		/obj/item/ammo_magazine/ammo_box/b12g/flechette = list("steel" = 2880, "plasteel" = 800),
		/obj/item/ammo_magazine/ammo_box/b12g/practice = list("steel" = 480),
		/obj/item/ammo_magazine/ammo_box/b12g/blank = list("steel" = 720),
		/obj/item/ammo_magazine/ammo_box/b12g/flash = list("steel" = 720, "glass" = 720),
		/obj/item/ammo_magazine/ammo_box/b145 = list("steel" = 28000, "plasteel" = 3500),
		/obj/item/ammo_magazine/ammo_box/b145/highvel = list("steel" = 2800, "plasteel" = 7000),
		/obj/item/ammo_magazine/ammo_box/b762 = list("steel" = 6000),
		/obj/item/ammo_magazine/ammo_box/b762/hp = list("steel" = 9000),
		/obj/item/ammo_magazine/ammo_box/b762/ap = list("steel" = 9000),
		/obj/item/ammo_magazine/ammo_box/b762/practice = list("steel" = 2700),
		/obj/item/ammo_magazine/ammo_box/b762/surplus = list("steel" = 1600),
		/obj/item/ammo_magazine/ammo_box/b762/surplus/blank = list("steel" = 720),
		/obj/item/ammo_magazine/ammo_box/b545 = list("steel" = 5400),
		/obj/item/ammo_magazine/ammo_box/b545/ap = list("steel" = 8100),
		/obj/item/ammo_magazine/ammo_box/b545/practice = list("steel" = 2700),
		/obj/item/ammo_magazine/ammo_box/b545/blank = list("steel" = 2700),
		/obj/item/ammo_magazine/ammo_box/b545/large = list("steel" = 18000),
		/obj/item/ammo_magazine/ammo_box/b545/large/ap = list("steel" = 27000),
		/obj/item/ammo_magazine/ammo_box/b545/large/practice = list("steel" = 9000),
		/obj/item/ammo_magazine/ammo_box/b9mm = list("steel" = 1500),
		/obj/item/ammo_magazine/ammo_box/b9mm/practice = list("steel" = 1100),
		/obj/item/ammo_magazine/ammo_box/b9mm/ap = list("steel" = 1200, "plasteel" = 600),
		/obj/item/ammo_magazine/ammo_box/b9mm/hp = list("steel" = 1100),
		/obj/item/ammo_magazine/ammo_box/b9mm/rubber = list("steel" = 1100, "plastic" = 360),
		/obj/item/ammo_magazine/ammo_box/b9mm/flash = list("steel" = 1100),
		/obj/item/ammo_magazine/s44 = list("steel" = 1260),
		/obj/item/ammo_magazine/handful = null,
		/obj/item/ammo_magazine/mfoam_dart/pistol = list("plastic" = 250),
		/obj/item/ammo_magazine/mfoam_dart/smg = list("plastic" = 250),
		/obj/item/ammo_magazine/m38/makarov = list("steel" = 480),
		/obj/item/ammo_magazine/m38/giskard = list("steel" = 540),
		/obj/item/ammo_magazine/m45 = list("steel" = 525),
		/obj/item/ammo_magazine/m45uzi = list("steel" = 1200),
		/obj/item/ammo_magazine/m45tommy = list("steel" = 1500),
		/obj/item/ammo_magazine/m45tommydrum = list("steel" = 3750),
		/obj/item/ammo_magazine/clip/c45 = list("steel" = 675),
		/obj/item/ammo_magazine/clip/c9mm = list("steel" = 540),
		/obj/item/ammo_magazine/clip/c545 = list("steel" = 450),
		/obj/item/ammo_magazine/clip/c44 = list("steel" = 1620),
		/obj/item/ammo_magazine/clip/c762 = list("steel" = 1000),
		/obj/item/ammo_magazine/clip/c12g = list("steel" = 1070),
		/obj/item/ammo_magazine/clip/c12g/beanbag = list("steel" = 710),
		/obj/item/ammo_magazine/clip/c12g/scatter = list("steel" = 1337),
		/obj/item/ammo_magazine/clip/sks = list("steel" = 400),
		/obj/item/ammo_magazine/clip/sks/ap = list("steel" = 700),
		/obj/item/ammo_magazine/clip/mosin = list("steel" = 300),
		/obj/item/ammo_magazine/clip/mosin/ap = list("steel" = 600),
		/obj/item/ammo_magazine/s45 = list("steel" = 525),
		/obj/item/ammo_magazine/m9mmt = list("steel" = 1200),
		/obj/item/ammo_magazine/m9mmt/ap = list("steel" = 1000, "plasteel" = 2000),
		/obj/item/ammo_magazine/m9mmp90 = list("steel" = 3000),
		/obj/item/ammo_magazine/m9mmp90/rubber = list("steel" = 2000, "plastic" = 1000),
		/obj/item/ammo_magazine/m9mmAdvanced = list("steel" = 1200),
		/obj/item/ammo_magazine/m9mmAdvanced/ap = list("steel" = 2000),
		/obj/item/ammo_magazine/m10mm = list("steel" = 1500),
		/obj/item/ammo_magazine/m10mm/practice = list("steel" = 1000),
		/obj/item/ammo_magazine/m10mm/rubber = list("steel" = 1000),
		/obj/item/ammo_magazine/m10mm/emp = list("steel" = 1500, "uranium" = 2000),
		/obj/item/ammo_magazine/m10mm/pistol = list("steel" = 1000),
		/obj/item/ammo_magazine/m10mm/pistol/practice = list("steel" = 800),
		/obj/item/ammo_magazine/m10mm/pistol/rubber = list("steel" = 800),
		/obj/item/ammo_magazine/m10mm/pistol/emp = list("steel" = 1000, "uranium" = 1500),
		/obj/item/ammo_magazine/m545 = list("steel" = 1800),
		/obj/item/ammo_magazine/m545/ext = list("steel" = 2700),
		/obj/item/ammo_magazine/m545/small = list("steel" = 900),
		/obj/item/ammo_magazine/m545saw = list("steel" = 10000),
		/obj/item/ammo_magazine/m44 = list("steel" = 1260),
		/obj/item/ammo_magazine/m762 = list("steel" = 2000),
		/obj/item/ammo_magazine/m762/ext = list("steel" = 4000),
		/obj/item/ammo_magazine/m762enbloc = list("steel" = 1600),
		/obj/item/ammo_magazine/m762svd = list("steel" = 2000),
		/obj/item/ammo_magazine/m12gdrum = list("steel" = 13000),
		/obj/item/ammo_magazine/m2024 = list("steel" = 525),
		/obj/item/ammo_magazine/mglock9mm = list("steel" = 480),
		/obj/item/ammo_magazine/mg42 = list("steel" = 10000),
		/obj/item/ammo_magazine/asval = list("steel" = 1000),
		/obj/item/ammo_magazine/asval/ap = list("steel" = 1200),
		/obj/item/ammo_magazine/akm = list("steel" = 1600),
		/obj/item/ammo_magazine/akm/ap = list("steel" = 2000),
		/obj/item/ammo_magazine/akm/hp = list("steel" = 2000),
		/obj/item/ammo_magazine/akm/rubber = list("steel" = 1200),
		/obj/item/ammo_magazine/akm/drum = list("steel" = 6000),
		/obj/item/ammo_magazine/akm/drum/ap = list("steel" = 7500),
		/obj/item/ammo_magazine/ak74 = list("steel" = 1400),
		/obj/item/ammo_magazine/ak74/ap = list("steel" = 1800),
		/obj/item/ammo_magazine/ak74/hp = list("steel" = 1800),
		/obj/item/ammo_magazine/ak74/rubber = list("steel" = 1200),
		/obj/item/ammo_magazine/ak74/plum/rubber = list("steel" = 1200),
		/obj/item/ammo_magazine/m16 = list("steel" = 1400),
		/obj/item/ammo_magazine/m16/ap = list("steel" = 1700),
		/obj/item/ammo_magazine/m16/rubber = list("steel" = 1700),
		/obj/item/ammo_magazine/m16/hp = list("steel" = 1700),
		/obj/item/ammo_magazine/m16/patriot = list("steel" = 5000),
		/obj/item/ammo_magazine/m41 = list("steel" = 10000),
		/obj/item/ammo_magazine/m41/rubber = list("steel" = 7000),
		/obj/item/ammo_magazine/t12 = list("steel" = 10000),
		/obj/item/ammo_magazine/type901 = list("steel" = 2400),
		/obj/item/ammo_magazine/type901/ap = list("steel" = 3000),
		/obj/item/ammo_magazine/ar10 = list("steel" = 1800),
		/obj/item/ammo_magazine/ar10/ap = list("steel" = 2400),
		/obj/item/ammo_magazine/fal = list("steel" = 1800),
		/obj/item/ammo_magazine/fal/ap = list("steel" = 2400),
		/obj/item/ammo_magazine/awp = list("steel" = 2400),
		/obj/item/ammo_magazine/awp/ap = list("steel" = 3000),
		/obj/item/ammo_magazine/hectate = list("steel" = 4000),
		/obj/item/ammo_magazine/hectate/ap = list("steel" = 5000),
		/obj/item/ammo_magazine/ppsh = list("steel" = 1500),
		/obj/item/ammo_magazine/plamya = list("steel" = 2500),
		/obj/item/ammo_magazine/plamya/ap = list("steel" = 3000),
		/obj/item/ammo_magazine/plamya/rubber = list("steel" = 2000),
		/obj/item/ammo_magazine/strela = list("steel" = 800),
		/obj/item/ammo_magazine/molniya = list("steel" = 8000),
		/obj/item/ammo_magazine/molniya/ap = list("steel" = 10000),
		/obj/item/ammo_magazine/kord = list("steel" = 20000),
		/obj/item/ammo_magazine/pkm = list("steel" = 8000),
		/obj/item/ammo_magazine/pkm/ap = list("steel" = 10000),
		/obj/item/ammo_magazine/rpd = list("steel" = 8000),
		/obj/item/ammo_magazine/rpd/ap = list("steel" = 10000),
		/obj/item/ammo_magazine/ssp4 = list("steel" = 400),
		/obj/item/ammo_magazine/ssp4/rubber = list("steel" = 300),
		/obj/item/ammo_magazine/makarov = list("steel" = 400),
		/obj/item/ammo_magazine/tp23s = list("steel" = 800),
		/obj/item/ammo_magazine/tp23 = list("steel" = 800),
		/obj/item/ammo_magazine/mp5mag = list("steel" = 800),
		/obj/item/ammo_magazine/pitchmag = list("steel" = 800),
		/obj/item/ammo_magazine/sam48 = list("steel" = 240),
		/obj/item/ammo_magazine/m380 = list("steel" = 480),
		/obj/item/ammo_magazine/m12gdrumjack = list("steel" = 1300),
		/obj/item/ammo_magazine/m12gdrumjack/empty = list("steel" = 1625),
		/obj/item/ammo_casing/a9mm = list("steel" = 60),
		/obj/item/ammo_casing/a9mm/ap = list("steel" = 80),
		/obj/item/ammo_casing/a9mm/bb = list("plastic" = 20),
		/obj/item/ammo_casing/a357 = list("steel" = 210),
		/obj/item/ammo_casing/a357/bb = list("plastic" = 20),
		/obj/item/ammo_casing/a357/rubber = list("steel" = 60),
		/obj/item/ammo_casing/a38 = list("steel" = 60),
		/obj/item/ammo_casing/a38/emp = list("steel" = 130, "uranium" = 100),
		/obj/item/ammo_casing/a38/bb = list("plastic" = 20),
		/obj/item/ammo_casing/a44 = list("steel" = 210),
		/obj/item/ammo_casing/a44/rubber = list("steel" = 60),
		/obj/item/ammo_casing/a44/bb = list("plastic" = 20),
		/obj/item/ammo_casing/afoam_dart = list("plastic" = 60),
		/obj/item/ammo_casing/afoam_dart/riot = list("steel" = 210, "plastic" = 60),
		/obj/item/ammo_casing/a75 = list("steel" = 4000),
		/obj/item/ammo_casing/a45 = list("steel" = 75),
		/obj/item/ammo_casing/a45/ap = list("steel" = 50, "plasteel" = 25),
		/obj/item/ammo_casing/a45/practice = list("steel" = 60),
		/obj/item/ammo_casing/a45/rubber = list("steel" = 60),
		/obj/item/ammo_casing/a45/flash = list("steel" = 60),
		/obj/item/ammo_casing/a45/emp = list("steel" = 130, "uranium" = 100),
		/obj/item/ammo_casing/a45/hp = list("steel" = 60, "plastic" = 15),
		/obj/item/ammo_casing/a45/bb = list("plastic" = 20),
		/obj/item/ammo_casing/a10mm = list("steel" = 75),
		/obj/item/ammo_casing/a10mm/practice = list("steel" = 60),
		/obj/item/ammo_casing/a10mm/rubber = list("steel" = 60),
		/obj/item/ammo_casing/a10mm/emp = list("steel" = 130, "uranium" = 100),
		/obj/item/ammo_casing/a10mm/bb = list("plastic" = 20),
		/obj/item/ammo_casing/a12g = list("steel" = 360),
		/obj/item/ammo_casing/a12g/blank = list("steel" = 90),
		/obj/item/ammo_casing/a12g/practice = list("steel" = 90),
		/obj/item/ammo_casing/a12g/beanbag = list("steel" = 180),
		/obj/item/ammo_casing/a12g/stunshell = list("steel" = 360, "glass" = 720),
		/obj/item/ammo_casing/a12g/flash = list("steel" = 90, "glass" = 90),
		/obj/item/ammo_casing/a12g/emp = list("steel" = 360, "uranium" = 240),
		/obj/item/ammo_casing/a12g/flechette = list("steel" = 360, "plasteel" = 100),
		/obj/item/ammo_casing/a12g/bb = list("plastic" = 120),
		/obj/item/ammo_casing/a12g/silver = list("steel" = 360, "silver" = 240),
		/obj/item/ammo_casing/a12g/scatter = list("steel" = 450),
		/obj/item/ammo_casing/a762 = list("steel" = 200),
		/obj/item/ammo_casing/a762/ap = list("steel" = 300),
		/obj/item/ammo_casing/a762/practice = list("steel" = 90),
		/obj/item/ammo_casing/a762/blank = list("steel" = 90),
		/obj/item/ammo_casing/a762/bb = list("plastic" = 20),
		/obj/item/ammo_casing/a145 = list("steel" = 4000, "plasteel" = 500),
		/obj/item/ammo_casing/a145/highvel = list("steel" = 4000, "plasteel" = 1000),
		/obj/item/ammo_casing/a545 = list("steel" = 180),
		/obj/item/ammo_casing/a545/ap = list("steel" = 270),
		/obj/item/ammo_casing/a545/practice = list("steel" = 90),
		/obj/item/ammo_casing/a545/blank = list("steel" = 90),
		/obj/item/ammo_casing/a545/bb = list("plastic" = 20),
		/obj/item/ammo_casing/a5mmcaseless = list("steel" = 180),
		/obj/item/ammo_casing/rocket = list("steel" = 10000),
		/obj/item/ammo_casing/cap = list("steel" = 85),
		/obj/item/ammo_casing/sam48 = list("steel" = 30),
		/obj/item/handcuffs = list("steel" = 500),
		/obj/item/handcuffs/fake = list("PLASTIC" = 500),
		/obj/item/aiModule = list("steel" = 30, "glass" = 10),
		/obj/item/cane = list("steel" = 50),
		/obj/item/extinguisher = list("steel" = 90),
		/obj/item/flamethrower = list("steel" = 500),
		/obj/item/rcd = list("steel" = 50000),
		/obj/item/rcd_ammo = list("steel" = 30000, "glass" = 15000),
		/obj/item/rcd_ammo/large = list("steel" = 45000, "glass" = 22500),
		/obj/item/rms = list("steel" = 5000),
		/obj/item/rsf = list("steel" = 25000),
		/obj/item/shield/riot = list("glass" = 7500, "steel" = 1000),
		/obj/item/locator = list("steel" = 400),
		/obj/item/hand_tele = list("steel" = 10000),
		/obj/item/beartrap = list("steel" = 18750),
		/obj/item/tray = list("steel" = 3000),
		/obj/item/implanter = list("steel" = 1000, "glass" = 1000),
		/obj/item/anomaly_scanner = list("steel" = 200),
		/obj/item/assembly = list("steel" = 100),
		/obj/item/assembly/signaler = list("steel" = 1000, "glass" = 200),
		/obj/item/assembly/igniter = list("steel" = 500, "glass" = 50),
		/obj/item/assembly/infra = list("steel" = 1000, "glass" = 500),
		/obj/item/assembly/prox_sensor = list("steel" = 800, "glass" = 200),
		/obj/item/assembly/timer = list("steel" = 500, "glass" = 50),
		/obj/item/assembly/voice = list("steel" = 500, "glass" = 50),
		/obj/item/backup_implanter = list("steel" = 2000, "glass" = 2000),
		/obj/item/rig_module = list("steel" = 20000, "plastic" = 30000, "glass" = 5000),
		/obj/item/uv_light = list("steel" = 150),
		/obj/item/coin/gold = list("gold" = 250),
		/obj/item/coin/silver = list("silver" = 250),
		/obj/item/coin/copper = list("copper" = 250),
		/obj/item/coin/diamond = list("diamond" = 250),
		/obj/item/coin/graphite = list("graphite" = 250),
		/obj/item/coin/iron = list("iron" = 250),
		/obj/item/coin/steel = list("steel" = 250),
		/obj/item/coin/durasteel = list("durasteel" = 250),
		/obj/item/coin/plasteel = list("plasteel" = 250),
		/obj/item/coin/titanium = list("titanium" = 250),
		/obj/item/coin/lead = list("lead" = 250),
		/obj/item/coin/phoron = list("phoron" = 250),
		/obj/item/coin/uranium = list("uranium" = 250),
		/obj/item/coin/platinum = list("gold" = 250),
		/obj/item/coin/morphium = list("morphium" = 250),
		/obj/item/coin/aluminium = list("aluminium" = 250),
		/obj/item/coin/verdantium = list("verdantium" = 250),
		/obj/item/camera = list("steel" = 2000),
		/obj/item/pickaxe = list("steel" = 2500),
		/obj/item/pickaxe/drill = list("steel" = 3750),
		/obj/item/pickaxe/advdrill = list("steel" = 4000, "plasteel" = 2500),
		/obj/item/pickaxe/diamonddrill = list("steel" = 4500, "plasteel" = 3000, "MAT_DIAMONDS" = 1000),
		/obj/item/pickaxe/plasmacutter = list("steel" = 3000, "plasteel" = 1500, "MAT_DIAMONDS" = 500, "phoron" = 500),
		/obj/item/shovel = list("steel" = 50),
		/obj/item/shovel/wood = list("wood" = 50),
		/obj/item/ice_pick = list("steel" = 12000),
		/obj/item/mining_scanner = list("steel" = 150),
		/obj/item/robotanalyzer = list("steel" = 500, "glass" = 200),
		/obj/item/broken_device = list("steel" = 1000),
		/obj/item/stamp = list("steel" = 60),
		/obj/item/magnetic_ammo = list("steel" = 1800),
		/obj/item/syringe_cartridge = list("steel" = 125, "glass" = 375),
		/obj/item/dq_property_test = list("steel" = 1000, "cardboard" = 500),
		/obj/item/dq_property_test/blunt = list("steel" = 200),
		/obj/item/measuring_tape = list("steel" = 100),
		/obj/item/ano_scanner = list("steel" = 10000, "glass" = 5000),
		/obj/item/depth_scanner = list("steel" = 1000, "glass" = 1000),
		/obj/item/beacon_locator = list("steel" = 1000, "glass" = 500),
		/obj/item/xenoarch_multi_tool = list("steel" = 10000, "glass" = 5000),
		/obj/item/mindbinder = list("steel" = 200),
		/obj/item/pipe_dispenser = list("steel" = 50000, "glass" = 25000),
		/obj/item/fusion_coil = list("steel" = 6000, "copper" = 4000, "plastic" = 2000)
	)
	return changes
