/// Real item operations preserve the distinction between consuming and releasing.
/datum/unit_test/dq_ownership_policy_bait_consumption/Run()
	var/obj/item/material/fishing_rod/rod = allocate(/obj/item/material/fishing_rod, run_loc_floor_bottom_left)
	var/obj/item/reagent_containers/food/snacks/bait = allocate(/obj/item/reagent_containers/food/snacks, rod)
	rel_set(rod, nameof(rod.Bait), bait)
	TEST_ASSERT(rod.consume_bait(), "an attached bait is consumed")
	TEST_ASSERT_NULL(rod.Bait, "consumption empties the bait slot")
	TEST_ASSERT(QDELETED(bait), "consumption actually deletes the bait")
	TEST_ASSERT(!rod.consume_bait(), "an empty rod reports no bait consumed")
	var/obj/item/reagent_containers/food/snacks/removable = allocate(/obj/item/reagent_containers/food/snacks, rod)
	rel_set(rod, nameof(rod.Bait), removable)
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	rod.item_ctrl_click(user)
	TEST_ASSERT_NULL(rod.Bait, "manual removal empties the bait slot")
	TEST_ASSERT(!QDELETED(removable), "manual removal leaves the bait alive")
	TEST_ASSERT_EQUAL(get_turf(removable), get_turf(user), "removed bait lands beside its user")

/datum/unit_test/dq_ownership_policy_hardlight_bolt/Run()
	var/obj/item/gun/launcher/crossbow/bow/hardlight/hardlight = allocate(/obj/item/gun/launcher/crossbow/bow/hardlight, run_loc_floor_bottom_left)
	var/obj/item/arrow/energy/energy = allocate(/obj/item/arrow/energy, hardlight)
	rel_set(hardlight, nameof(hardlight.bolt), energy)
	hardlight.unload(null)
	TEST_ASSERT_NULL(hardlight.bolt, "unloading empties the hardlight slot")
	TEST_ASSERT(QDELETED(energy), "unloaded hardlight energy dissipates")
	var/obj/item/arrow/energy/loaded_energy = allocate(/obj/item/arrow/energy, hardlight)
	rel_set(hardlight, nameof(hardlight.bolt), loaded_energy)
	qdel(hardlight)
	TEST_ASSERT(QDELETED(loaded_energy), "destroying a loaded hardlight bow dissipates its energy")
	var/obj/item/gun/launcher/crossbow/bow/ordinary = allocate(/obj/item/gun/launcher/crossbow/bow, run_loc_floor_bottom_left)
	var/obj/item/arrow/standard/physical = allocate(/obj/item/arrow/standard, ordinary)
	rel_set(ordinary, nameof(ordinary.bolt), physical)
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	ordinary.unload(user)
	TEST_ASSERT_NULL(ordinary.bolt, "ordinary unloading releases the physical arrow slot")
	TEST_ASSERT(!QDELETED(physical), "ordinary unloading preserves its physical arrow")
	TEST_ASSERT_EQUAL(physical.loc, user, "the user receives the unloaded physical arrow")

/datum/unit_test/dq_ownership_policy_rig_teardown/Run()
	var/obj/item/rig/rig = allocate(/obj/item/rig, run_loc_floor_bottom_left)
	var/obj/item/cell/cell = allocate(/obj/item/cell, rig)
	var/obj/item/tank/air = allocate(/obj/item/tank, rig)
	var/obj/item/rig_module/module = allocate(/obj/item/rig_module, rig)
	rel_clear(rig, nameof(rig.cell))
	rel_clear(rig, nameof(rig.air_supply))
	rel_clear(rig, nameof(rig.installed_modules))
	rel_set(rig, nameof(rig.cell), cell)
	rel_set(rig, nameof(rig.air_supply), air)
	rel_add(rig, nameof(rig.installed_modules), module)
	qdel(rig)
	TEST_ASSERT(QDELETED(cell), "rig teardown deletes its installed cell")
	TEST_ASSERT(QDELETED(air), "rig teardown deletes its air supply")
	TEST_ASSERT(QDELETED(module), "rig teardown deletes each installed module")

/datum/unit_test/dq_ownership_policy_robot_dust/Run()
	var/mob/living/silicon/robot/robot = allocate(/mob/living/silicon/robot, run_loc_floor_bottom_left)
	var/obj/item/mmi/mmi = allocate(/obj/item/mmi, robot)
	rel_clear(robot, nameof(robot.mmi), OWN_DELETE)
	rel_set(robot, nameof(robot.mmi), mmi)
	robot.mmi_ejects = TRUE
	rel_take(robot, nameof(robot.mmi))
	var/obj/item/mmi/released = allocate(/obj/item/mmi, robot)
	rel_set(robot, nameof(robot.mmi), released)
	rel_clear(robot, nameof(robot.mmi))
	TEST_ASSERT(!QDELETED(released), "ordinary declared ejection preserves the MMI")
	TEST_ASSERT_EQUAL(get_turf(released), run_loc_floor_bottom_left, "ordinary ejection leaves the MMI on the floor")
	rel_set(robot, nameof(robot.mmi), mmi)
	var/list/old_effects = list()
	for(var/atom/movable/effect in run_loc_floor_bottom_left)
		if(istype(effect, /atom/movable/overlay) || istype(effect, /obj/effect/decal/remains/robot))
			old_effects += effect
	robot.dust()
	TEST_ASSERT(QDELETED(mmi), "dust deletes the MMI despite the ordinary eject-on-destroy policy")
	for(var/atom/movable/overlay/animation in run_loc_floor_bottom_left)
		if(!(animation in old_effects))
			qdel(animation)
	for(var/obj/effect/decal/remains/robot/remains in run_loc_floor_bottom_left)
		if(!(remains in old_effects))
			qdel(remains)

/datum/unit_test/dq_ownership_policy_soulgem_transfer/Run()
	var/mob/living/carbon/human/previous = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	var/mob/living/carbon/human/destination = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	var/obj/soulgem/moving = allocate(/obj/soulgem, previous)
	var/obj/soulgem/replaced = allocate(/obj/soulgem, destination)
	rel_clear(previous, nameof(previous.soulgem), OWN_DELETE)
	rel_clear(destination, nameof(destination.soulgem), OWN_DELETE)
	rel_set(previous, nameof(previous.soulgem), moving)
	rel_set(destination, nameof(destination.soulgem), replaced)
	rel_set(moving, nameof(moving.owner), previous)
	moving.transfer_self(destination)
	TEST_ASSERT(QDELETED(replaced), "transfer deletes the destination's old gem")
	TEST_ASSERT(!QDELETED(moving), "the transferred gem survives")
	TEST_ASSERT_NULL(previous.soulgem, "transfer releases the previous owner's slot")
	TEST_ASSERT_EQUAL(destination.soulgem, moving, "the destination owns the transferred gem")
	TEST_ASSERT_EQUAL(moving.owner(), destination, "the gem's owner view points to its destination")

/datum/unit_test/dq_ownership_policy_smasher_dump/Run()
	var/obj/machinery/particle_smasher/smasher = allocate(/obj/machinery/particle_smasher, run_loc_floor_bottom_left)
	for(var/slot in list(nameof(smasher.target), nameof(smasher.reagent_container)))
		var/list/entry = own_table_of(smasher).entries[slot]
		TEST_ASSERT(entry && entry[OWNE_KIND] == OWNK_OWN && entry[OWNE_ARG] == OWN_CONTAINED && !entry[OWNE_LIST], "Each dumped slot declares one contained item: [slot]")
	var/obj/item/stack/material/iron/target = allocate(/obj/item/stack/material/iron, smasher)
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, smasher)
	var/obj/item/tool/crowbar/stored = allocate(/obj/item/tool/crowbar, smasher)
	rel_set(smasher, nameof(smasher.target), target)
	rel_set(smasher, nameof(smasher.reagent_container), beaker)
	rel_add(smasher, nameof(smasher.storage), stored)
	smasher.successful_craft = TRUE
	TEST_ASSERT_EQUAL(smasher.target, target, "Setup fills the real target slot")
	TEST_ASSERT_EQUAL(smasher.reagent_container(), beaker, "Setup fills the real reagent bay")
	TEST_ASSERT(stored in smasher.storage, "Setup fills the real fabrication storage")
	smasher.DumpContents()
	TEST_ASSERT_NULL(smasher.target, "Dumping releases the target slot")
	TEST_ASSERT_NULL(smasher.reagent_container(), "Dumping releases the reagent bay")
	TEST_ASSERT_EQUAL(length(smasher.storage), 0, "Dumping releases the stored ingredient")
	TEST_ASSERT(!smasher.successful_craft, "Dumping clears the waiting-for-empty state")
	for(var/obj/item/item as anything in list(target, beaker, stored))
		TEST_ASSERT(!QDELETED(item), "Dumping preserves each actual item")
		TEST_ASSERT_EQUAL(item.loc, run_loc_floor_bottom_left, "Each released item lands on the machine's turf")
