/datum/unit_test/requirement_protocol_cablelayer_toggle/Run()
	var/obj/machinery/cablelayer/layer = allocate(/obj/machinery/cablelayer)
	var/datum/act/op/A = allocate(/datum/act/op)
	A.holder = layer
	TEST_ASSERT(layer.cable, "The real layer initializes its loaded reel")
	TEST_ASSERT_NULL(layer.toggle_ready(A), "The initialized reel permits toggling while off")
	rel_clear(layer, nameof(/obj/machinery/cablelayer::cable))
	layer.set_on(FALSE)
	TEST_ASSERT_EQUAL(layer.toggle_ready(A), MSG(cablelayer/toggle_no_cable), "An off layer with no reel refuses with the original reason")
	layer.set_on(TRUE)
	TEST_ASSERT_NULL(layer.toggle_ready(A), "A running empty layer still permits switching off")

/datum/unit_test/requirement_protocol_bomb_tester_slots/Run()
	var/obj/machinery/bomb_tester/tester = allocate(/obj/machinery/bomb_tester)
	var/datum/act/op/A = allocate(/datum/act/op)
	A.holder = tester
	TEST_ASSERT_NULL(tester.tank_slot_available(A), "Two empty real tank slots allow the loading selection")
	var/obj/item/tank/oxygen/first = allocate(/obj/item/tank/oxygen)
	var/obj/item/tank/oxygen/second = allocate(/obj/item/tank/oxygen)
	rel_set(tester, nameof(/obj/machinery/bomb_tester::tank1), first)
	TEST_ASSERT_NULL(tester.tank_slot_available(A), "An empty secondary slot still allows loading")
	rel_set(tester, nameof(/obj/machinery/bomb_tester::tank2), second)
	TEST_ASSERT_EQUAL(tester.tank_slot_available(A), MSG(req_wrong_state), "Both occupied slots suppress loading")
	rel_take(tester, nameof(/obj/machinery/bomb_tester::tank1))
	TEST_ASSERT_NULL(tester.tank_slot_available(A), "Removing the primary tank restores loading")
