// Real input/request regressions for the expressible lane-B conversions.
/datum/unit_test/dq_round3_requests_b
	parent_type = /datum/unit_test/dq_hc_struct
	abstract_type = /datum/unit_test/dq_round3_requests_b

/datum/unit_test/dq_round3_requests_b/sensor_name_captures_device
/datum/unit_test/dq_round3_requests_b/sensor_name_captures_device/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/computer/general_air_control/C = mach(/obj/machinery/computer/general_air_control, tile(3, 2))
	var/obj/item/multitool/T = allocate(/obj/item/multitool, H.loc)
	TEST_ASSERT(H.put_in_active_hand(T), "the operator holds the actual multitool")
	var/obj/machinery/air_sensor/first = mach(/obj/machinery/air_sensor, tile(3, 3))
	var/obj/machinery/air_sensor/second = mach(/obj/machinery/air_sensor, tile(4, 3))
	first.id_tag = "round3-first"
	second.id_tag = "round3-second"
	rel_set(T, nameof(T.connectable), first)
	var/datum/op_result/R = test_click(H, C, T)
	TEST_ASSERT_EQUAL(R?.key, "configure", "the real tool click selects configuration")
	request_answer(H, "Sensors")
	request_answer(H, "Add")
	var/datum/prompt/text/air_control_sensor_name/N = SSrequests.open_for(H)
	TEST_ASSERT(istype(N), "the native chain opens the sensor name step")
	TEST_ASSERT_EQUAL(N.device, first, "naming captures the buffer at the Add answer")
	rel_set(T, nameof(T.connectable), second)
	request_answer(H, "Captured sensor")
	TEST_ASSERT_EQUAL(C.sensors?[first.id_tag], "Captured sensor", "the named device is the original captured sensor")
	TEST_ASSERT_NULL(C.sensors?[second.id_tag], "a later buffer change cannot retarget naming")
	TEST_ASSERT(!asked(H), "successful naming closes the native chain")

/datum/unit_test/dq_round3_requests_b/sensor_remove_captures_tag
/datum/unit_test/dq_round3_requests_b/sensor_remove_captures_tag/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/computer/general_air_control/C = mach(/obj/machinery/computer/general_air_control, tile(3, 2))
	var/obj/item/multitool/T = allocate(/obj/item/multitool, H.loc)
	TEST_ASSERT(H.put_in_active_hand(T), "the operator holds the multitool")
	C.sensors = list("original-tag" = "Shared name")
	test_click(H, C, T)
	request_answer(H, "Sensors")
	request_answer(H, "Remove")
	request_answer(H, "Shared name")
	var/datum/prompt/yes_no/air_control_sensor_remove/Q = SSrequests.open_for(H)
	TEST_ASSERT(istype(Q), "removal opens the confirmation step")
	TEST_ASSERT_EQUAL(Q.sensor_names["Shared name"], "original-tag", "confirmation holds the originally selected tag")
	C.sensors = list("original-tag" = "Renamed", "replacement-tag" = "Shared name")
	request_answer(H, TRUE)
	TEST_ASSERT_NULL(C.sensors?["original-tag"], "confirmation removes the captured tag despite renaming")
	TEST_ASSERT_EQUAL(C.sensors?["replacement-tag"], "Shared name", "it preserves a replacement with the old display name")

/datum/unit_test/dq_round3_requests_b/port_reads_buffer_on_answer
/datum/unit_test/dq_round3_requests_b/port_reads_buffer_on_answer/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/computer/general_air_control/large_tank_control/C = mach(/obj/machinery/computer/general_air_control/large_tank_control, tile(3, 2))
	var/obj/item/multitool/T = allocate(/obj/item/multitool, H.loc)
	TEST_ASSERT(H.put_in_active_hand(T), "the operator holds the multitool")
	var/obj/machinery/atmospherics/unary/vent_pump/first = mach(/obj/machinery/atmospherics/unary/vent_pump, tile(3, 3))
	var/obj/machinery/atmospherics/unary/vent_pump/second = mach(/obj/machinery/atmospherics/unary/vent_pump, tile(4, 3))
	first.id_tag = "round3-old-outlet"
	second.id_tag = "round3-new-outlet"
	rel_set(T, nameof(T.connectable), first)
	test_click(H, C, T)
	request_answer(H, "Outlet")
	TEST_ASSERT(istype(SSrequests.open_for(H), /datum/prompt/choice/air_control_port), "outlet selection opens the native port step")
	rel_set(T, nameof(T.connectable), second)
	request_answer(H, "Set")
	TEST_ASSERT_EQUAL(C.output_tag, second.id_tag, "Set reads the live buffer at its answer")
	TEST_ASSERT_EQUAL(second.external_pressure_bound, 0, "setting an outlet changes the actual vent bound")
	TEST_ASSERT_EQUAL(second.external_pressure_bound_default, 0, "the vent default also becomes zero")

/datum/unit_test/dq_round3_requests_b/frequency_cancel_and_answer
/datum/unit_test/dq_round3_requests_b/frequency_cancel_and_answer/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/computer/general_air_control/C = mach(/obj/machinery/computer/general_air_control, tile(3, 2))
	var/obj/item/multitool/T = allocate(/obj/item/multitool, H.loc)
	TEST_ASSERT(H.put_in_active_hand(T), "the operator holds the multitool")
	var/original = C.frequency
	test_click(H, C, T)
	request_answer(H, "Frequency")
	TEST_ASSERT(istype(SSrequests.open_for(H), /datum/prompt/number), "Frequency opens the native numeric step")
	request_answer(H, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(C.frequency, original, "cancellation preserves the actual radio frequency")
	test_click(H, C, T)
	request_answer(H, "Frequency")
	request_answer(H, RADIO_LOW_FREQ)
	TEST_ASSERT_EQUAL(C.frequency, sanitize_frequency(RADIO_LOW_FREQ, RADIO_LOW_FREQ, RADIO_HIGH_FREQ), "the answer updates the real radio connection frequency")

/datum/unit_test/dq_round3_requests_b/board_reconfiguration
/datum/unit_test/dq_round3_requests_b/board_reconfiguration/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/item/circuitboard/airlock_cycling/B = allocate(/obj/item/circuitboard/airlock_cycling, tile(3, 2))
	var/obj/item/multitool/T = allocate(/obj/item/multitool, H.loc)
	TEST_ASSERT(H.put_in_active_hand(T), "the operator holds the multitool")
	var/datum/op_result/R = test_click(H, B, T)
	TEST_ASSERT_EQUAL(R?.key, "use_multitool", "a real multitool click selects board reconfiguration")
	TEST_ASSERT(asked(H), "reconfiguration opens its native choice")
	request_answer(H, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(B.build_path, /obj/machinery/access_button, "cancellation preserves the original board target")
	test_click(H, B, T)
	request_answer(H, "Controller - Advanced")
	TEST_ASSERT_EQUAL(B.build_path, /obj/machinery/embedded_controller/radio/airlock/advanced_airlock_controller, "answering selects the real advanced controller build path")
	TEST_ASSERT_EQUAL(B.name, T_BOARD("cycling airlock controller (advanced)"), "the native answer updates the board name")

/datum/unit_test/dq_round3_requests_b/frame_choice_stale_and_cancel
/datum/unit_test/dq_round3_requests_b/frame_choice_stale_and_cancel/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/item/frame/F = allocate(/obj/item/frame, H.loc)
	TEST_ASSERT(H.put_in_active_hand(F), "the builder holds the frame")
	var/datum/op_result/R = test_click(H, F, F, GESTURE_SELF)
	TEST_ASSERT_EQUAL(R?.key, "self", "the real self input selects frame construction")
	var/datum/prompt/choice/P = SSrequests.open_for(H)
	TEST_ASSERT(istype(P) && length(P.choices), "the native self op offers actual floor-frame types")
	request_answer(H, null, REQ_CANCELLED)
	TEST_ASSERT(!QDELETED(F) && !F.build_machine_type, "cancellation neither consumes nor types the frame")
	test_click(H, F, F, GESTURE_SELF)
	P = SSrequests.open_for(H)
	TEST_ASSERT(istype(P) && length(P.choices), "the cancelled frame can reopen its choice")
	F.build_machine_type = /obj/structure/frame
	request_answer(H, P.choices[1])
	TEST_ASSERT(!QDELETED(F), "a stale answer cannot consume an already typed frame")
	TEST_ASSERT_EQUAL(F.build_machine_type, /obj/structure/frame, "the stale answer preserves the externally selected type")

/datum/unit_test/dq_round3_requests_b/cutout_paint_timed_and_cancel
/datum/unit_test/dq_round3_requests_b/cutout_paint_timed_and_cancel/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/structure/barricade/cutout/C = allocate(/obj/structure/barricade/cutout, tile(3, 2))
	var/obj/item/floor_painter/P = allocate(/obj/item/floor_painter, H.loc)
	TEST_ASSERT(H.put_in_active_hand(P), "the painter holds the real floor painter")
	test_click(H, C, P)
	TEST_ASSERT(asked(H), "painting opens its native cutout choice")
	request_answer(H, null, REQ_CANCELLED)
	TEST_ASSERT(!QDELETED(C), "cancelling leaves the cutout intact")
	test_click(H, C, P)
	request_answer(H, "clown")
	TEST_ASSERT(!QDELETED(C), "answering begins timed work without replacing immediately")
	test_time(9 SECONDS)
	TEST_ASSERT(!QDELETED(C), "the original cutout survives before the work duration")
	test_time(1 SECOND)
	var/obj/structure/barricade/cutout/clown/replacement = locate() in tile(3, 2)
	TEST_ASSERT(QDELETED(C) && replacement, "completion actually replaces the old cutout with the selected clown")
