/datum/unit_test/dq_e2/requirement_protocol

/datum/unit_test/dq_e2/requirement_protocol/run_gate()
	var/obj/req_protocol_fixture/F = allocate(/obj/req_protocol_fixture)
	var/datum/act/op/A = allocate(/datum/act/op)
	A.holder = F
	var/datum/entry/part/req/R = req(TYPE_PROC_REF(/obj/req_protocol_fixture, check_ready))
	TEST_ASSERT(R.holds(A), "A null callback result allows")
	TEST_ASSERT(R.require(A), "The part's boolean Require view also allows")
	TEST_ASSERT(isnull(R.check(A)), "The reason view returns null for an allowed requirement")
	F.set_mode(1)
	TEST_ASSERT(!R.holds(A), "A string callback result refuses")
	TEST_ASSERT_EQUAL(R.refusal(A), "A custom reason.", "The callback supplies its refusal text")
	TEST_ASSERT_EQUAL(R.check(A), "A custom reason.", "The reason view returns the callback refusal")
	F.set_mode(2)
	TEST_ASSERT(!R.holds(A), "A message path refuses")
	TEST_ASSERT_EQUAL(R.refusal(A), MSG(req_protocol/blocked), "A message path remains a typed refusal")
	F.set_mode(3)
	TEST_ASSERT(!R.holds(A), "A message datum refuses")
	TEST_ASSERT_EQUAL(reason_text(R.refusal(A)), "The protocol fixture is blocked.", "A refusal datum contributes its actual text")
	var/datum/entry/part/req/override = req(TYPE_PROC_REF(/obj/req_protocol_fixture, check_ready), because = MSG(req_protocol/override))
	TEST_ASSERT_EQUAL(override.refusal(A), MSG(req_protocol/override), "An explicit because overrides a callback reason")
	var/datum/entry/part/req/literal = req(TYPE_PROC_REF(/obj/req_protocol_fixture, check_ready), because = "A literal override.")
	TEST_ASSERT_EQUAL(literal.refusal(A), "A literal override.", "A literal string override is not called as a proc")
	var/datum/entry/part/req/dynamic = req(TYPE_PROC_REF(/obj/req_protocol_fixture, check_ready), because = TYPE_PROC_REF(/obj/req_protocol_fixture, check_other))
	TEST_ASSERT_EQUAL(dynamic.refusal(A), "Another reason.", "Existing callback overrides retain their wording")
	var/datum/entry/part/req/silent = req(TYPE_PROC_REF(/obj/req_protocol_fixture, check_ready), because = "")
	TEST_ASSERT_EQUAL(silent.refusal(A), /datum/msg/req_silent, "Empty because overrides with a silent refusal")
	F.set_mode(4)
	TEST_ASSERT(!R.holds(A), "An empty callback string still refuses")
	TEST_ASSERT_EQUAL(R.refusal(A), /datum/msg/req_silent, "An empty reason does not become a falsey allowed result")
	// Deliberately feed a boolean callback to the reason protocol through a runtime argument.
	// The static hook checker rejects this mismatch in real declarations; the engine also fails closed.
	var/boolean_callback = TYPE_PROC_REF(/obj/req_protocol_fixture, boolean_ready)
	var/datum/entry/part/req/invalid = req(boolean_callback)
	F.set_mode(5)
	TEST_ASSERT(!invalid.holds(A), "FALSE is not the new protocol's null allowance")
	TEST_ASSERT_EQUAL(invalid.refusal(A), /datum/msg/req_failed, "An invalid FALSE result fails closed with an actual reason")
	F.set_mode(6)
	TEST_ASSERT(!invalid.holds(A), "TRUE is not the new protocol's null allowance")
	TEST_ASSERT_EQUAL(invalid.refusal(A), /datum/msg/req_failed, "An invalid TRUE result also fails closed")
	F.set_mode(1)
	var/datum/entry/part/req/B = req_bool(TYPE_PROC_REF(/obj/req_protocol_fixture, boolean_ready), because = MSG(req_protocol/blocked))
	TEST_ASSERT(!B.holds(A), "The transitional form preserves FALSE refusal")
	F.set_mode(0)
	TEST_ASSERT(B.holds(A), "The transitional form preserves TRUE allowance")
	TEST_ASSERT(R.holds(A), "Requirements are evaluated afresh after recovery")
	var/datum/requirement/req_protocol_fixture/compatibility = allocate(/datum/requirement/req_protocol_fixture)
	TEST_ASSERT(isnull(compatibility.check(A)), "An allowed compatibility requirement exposes null")
	compatibility.allowed = FALSE
	TEST_ASSERT_EQUAL(compatibility.check(A), "A compatibility reason.", "A refused compatibility requirement exposes its reason")

/datum/unit_test/dq_e2/requirement_protocol_composition

/datum/unit_test/dq_e2/requirement_protocol_composition/run_gate()
	var/obj/req_protocol_fixture/F = allocate(/obj/req_protocol_fixture)
	var/datum/act/op/A = allocate(/datum/act/op)
	A.holder = F
	var/datum/entry/part/req/first = req(TYPE_PROC_REF(/obj/req_protocol_fixture, check_ready))
	var/datum/entry/part/req/second = req(TYPE_PROC_REF(/obj/req_protocol_fixture, check_other))
	var/datum/entry/part/req/all = all_of(first, second)
	var/datum/entry/part/req/any = any_of(first, second)
	TEST_ASSERT(all.holds(A), "All null results allow all_of")
	TEST_ASSERT(any.holds(A), "A null result allows any_of")
	F.set_mode(1)
	TEST_ASSERT(!all.holds(A), "all_of refuses when its children refuse")
	TEST_ASSERT_EQUAL(all.refusal(A), "A custom reason.", "all_of reports the first refusal")
	TEST_ASSERT(!any.holds(A), "any_of refuses when every child refuses")
	TEST_ASSERT_EQUAL(any.refusal(A), "A custom reason. or Another reason.", "any_of joins the actual callback reasons")
	var/datum/entry/part/req/allow = req(TYPE_PROC_REF(/obj/req_protocol_fixture, check_always))
	var/datum/entry/part/req/mixed_any = any_of(first, allow)
	var/datum/entry/part/req/mixed_all = all_of(allow, first)
	TEST_ASSERT(mixed_any.holds(A), "One null result permits any_of even when another child refuses")
	TEST_ASSERT(!mixed_all.holds(A), "One refusing child still blocks all_of")
	TEST_ASSERT_EQUAL(mixed_all.refusal(A), "A custom reason.", "all_of skips the allowed child when finding a reason")
	F.set_mode(0)
	TEST_ASSERT(all.holds(A) && any.holds(A), "Both compositions recover without stale refusal state")

/datum/unit_test/dq_e2/requirement_protocol_menu

/datum/unit_test/dq_e2/requirement_protocol_menu/run_gate()
	var/mob/living/simple_mob/e0_fixture/M = actor()
	var/obj/req_protocol_fixture/F = allocate(/obj/req_protocol_fixture)
	F.set_mode(3)
	var/list/rows = action_options(M, F, null)
	var/found = FALSE
	var/conditional_found = FALSE
	for(var/list/row in rows)
		if(row["key"] == "boolean_when")
			conditional_found = TRUE
		if(row["key"] == "protocol")
			found = TRUE
			TEST_ASSERT_EQUAL(row["enabled"], FALSE, "The menu disables a callback-refused op")
			TEST_ASSERT_EQUAL(row["reason"], "The protocol fixture is blocked.", "The menu exposes a refusal datum's real wording")
	TEST_ASSERT(found, "A refused protocol op remains discoverable")
	TEST_ASSERT(!conditional_found, "A FALSE transitional condition hides the op even without because")
	var/datum/op_result/refused = test_menu(M, F, "protocol")
	TEST_ASSERT_EQUAL(refused?.outcome, ACT_REFUSED, "The menu execution also refuses")
	TEST_ASSERT_EQUAL(F.commits, 0, "A refused op did not run its effect")
	F.set_mode(0)
	var/datum/op_result/allowed = test_menu(M, F, "protocol")
	TEST_ASSERT_EQUAL(allowed?.outcome, ACT_COMMITTED, "The same op commits after recovery")
	TEST_ASSERT_EQUAL(F.commits, 1, "The allowed op ran its real effect exactly once")
	var/datum/op_result/conditional = test_menu(M, F, "boolean_when")
	TEST_ASSERT_EQUAL(conditional?.outcome, ACT_COMMITTED, "A TRUE transitional condition works without a refusal declaration")
	TEST_ASSERT_EQUAL(F.commits, 2, "The conditional op executed its real effect")
