/// Public native request-chain regressions for the machinery records and colour controls.
/datum/unit_test/dq_e2/round3_record_notes_chain
/datum/unit_test/dq_e2/round3_record_notes_chain/run_gate()
	var/mob/living/simple_mob/e0_fixture/user = actor()
	for(var/console_type in list(/obj/machinery/computer/med_data, /obj/machinery/computer/secure_data, /obj/machinery/computer/skills))
		var/obj/machinery/computer/console = allocate(console_type, get_turf(user))
		console.set_grid_power(TRUE)
		console.set_broken_condition(FALSE)
		var/datum/data/record/record = allocate(/datum/data/record)
		record.fields["notes"] = "Original notes"
		set_var(GLOB.data_core, "general", list(record))
		set_var(GLOB.data_core, "medical", list(record))
		set_var(GLOB.data_core, "security", list(record))
		set_var(console, "authenticated", TRUE)
		var/record_slot = console_type == /obj/machinery/computer/skills ? "active1" : "active2"
		rel_set(console, record_slot, record)
		var/datum/op_result/opened = test_ui(user, console, "edit_notes", list())
		TEST_ASSERT_NOTNULL(SSrequests.open_for(user), "[console_type] opens its actual notes editor")
		TEST_ASSERT_EQUAL(record.fields["notes"], "Original notes", "opening changes no record")
		test_answer(user, "")
		var/datum/prompt/yes_no/record_notes_delete/confirmation = SSrequests.open_for(user)
		TEST_ASSERT(istype(confirmation), "empty text opens the native conditional deletion question")
		TEST_ASSERT_EQUAL(confirmation.record, record, "confirmation captures the real selected record")
		test_answer(user, null, REQ_CANCELLED)
		TEST_ASSERT_EQUAL(record.fields["notes"], "Original notes", "cancelled deletion preserves actual notes")
		test_ui(user, console, "edit_notes", list())
		test_answer(user, "")
		test_answer(user, TRUE)
		TEST_ASSERT_EQUAL(record.fields["notes"], "", "confirmed deletion clears actual notes")
		test_ui(user, console, "edit_notes", list())
		test_answer(user, "Replacement notes")
		TEST_ASSERT_NULL(SSrequests.open_for(user), "nonempty text asks no deletion question")
		TEST_ASSERT_EQUAL(record.fields["notes"], "Replacement notes", "nonempty answer updates the actual record")
		TEST_ASSERT_NOTNULL(opened, "public UI dispatch returns the waiting operation")

/datum/unit_test/dq_e2/round3_painter_colour_chain
/datum/unit_test/dq_e2/round3_painter_colour_chain/run_gate()
	var/mob/living/simple_mob/e0_fixture/user = actor()
	var/obj/machinery/gear_painter/painter = allocate(/obj/machinery/gear_painter, get_turf(user))
	painter.set_grid_power(TRUE)
	painter.set_broken_condition(FALSE)
	test_ui(user, painter, "choose_color", list())
	TEST_ASSERT_NULL(SSrequests.open_for(user), "an empty painter never opens the colour question")
	var/obj/item/clothing/gloves/gloves = allocate(/obj/item/clothing/gloves, painter)
	rel_set(painter, "inserted", gloves)
	var/original = painter.activecolor
	test_ui(user, painter, "choose_color", list())
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/color), "loaded painter opens its native colour question")
	test_answer(user, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(painter.activecolor, original, "cancel preserves chosen colour")
	test_ui(user, painter, "choose_color", list())
	test_answer(user, "#123456")
	TEST_ASSERT_EQUAL(painter.activecolor, "#123456", "answered native colour question changes real selected colour")

/datum/unit_test/dq_e2/round3_newscaster_text_chain
/datum/unit_test/dq_e2/round3_newscaster_text_chain/run_gate()
	var/mob/living/simple_mob/e0_fixture/user = actor()
	var/obj/machinery/newscaster/caster = allocate(/obj/machinery/newscaster, get_turf(user))
	caster.set_grid_power(TRUE)
	caster.set_broken_condition(FALSE)
	var/original = caster.title
	test_ui(user, caster, "set_new_title", list())
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/text), "title action opens the production text question")
	test_answer(user, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(caster.title, original, "cancelling changes no feed title")
	test_ui(user, caster, "set_new_title", list())
	test_answer(user, "Native title")
	TEST_ASSERT_EQUAL(caster.title, "Native title", "answer changes the actual caster title")
	test_ui(user, caster, "set_new_message", list())
	test_answer(user, "Native story")
	TEST_ASSERT_EQUAL(caster.msg, "Native story", "story answer changes the actual message field")

/datum/unit_test/dq_e2/round3_message_key_chain
/datum/unit_test/dq_e2/round3_message_key_chain/run_gate()
	var/mob/living/simple_mob/e0_fixture/user = actor()
	var/obj/machinery/computer/message_monitor/monitor = allocate(/obj/machinery/computer/message_monitor, get_turf(user))
	var/obj/machinery/message_server/server = allocate(/obj/machinery/message_server, get_turf(user))
	monitor.set_grid_power(TRUE)
	monitor.set_broken_condition(FALSE)
	server.set_grid_power(TRUE)
	server.set_broken_condition(FALSE)
	rel_set(monitor, "linkedServer", server)
	monitor.auth = TRUE
	server.decryptkey = "original-key"
	test_ui(user, monitor, "pass", list())
	TEST_ASSERT_NOTNULL(SSrequests.open_for(user), "authorized key action opens current-key question")
	test_answer(user, "wrong-key")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "wrong current key never opens replacement question")
	TEST_ASSERT_EQUAL(server.decryptkey, "original-key", "wrong credential changes no actual server key")
	test_ui(user, monitor, "pass", list())
	test_answer(user, "original-key")
	TEST_ASSERT_NOTNULL(SSrequests.open_for(user), "matching key opens chained replacement question")
	test_answer(user, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(server.decryptkey, "original-key", "cancel preserves actual server key")
	test_ui(user, monitor, "pass", list())
	test_answer(user, "original-key")
	test_answer(user, "replacement-key")
	TEST_ASSERT_EQUAL(server.decryptkey, "replacement-key", "completed chain changes the real linked server key")
	test_ui(user, monitor, "addtoken", list())
	test_answer(user, "filtered-token")
	TEST_ASSERT("filtered-token" in server.spamfilter, "native token question adds actual server filtering state")
