// Real menu refusals and physical admission for restored machinery operations.
/datum/unit_test/round2_menu_refusal_restore
	parent_type = /datum/unit_test/read_once_machinery_admission
	abstract_type = /datum/unit_test/round2_menu_refusal_restore

/datum/unit_test/round2_menu_refusal_restore/status_display
/datum/unit_test/round2_menu_refusal_restore/status_display/run_gate()
	set_global(nameof(GLOB.op_menu_builds), GLOB.op_menu_builds)
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/ai_status_display/D = mach(/obj/machinery/ai_status_display, tile(3, 2))
	var/list/row = find_row(op_menu(H, D, null), "touch")
	TEST_ASSERT_NOTNULL(row, "Empty-hand Use remains visibly refused")
	TEST_ASSERT(!row["enabled"], "An empty hand cannot select the item-touch operation")
	TEST_ASSERT_EQUAL(row["reason"], "needs an item", "The original missing-item refusal remains")
	var/datum/op_result/rejected = test_menu(H, D, "touch")
	TEST_ASSERT_EQUAL(rejected?.outcome, ACT_REFUSED, "A public empty-hand menu pick is refused")
	var/obj/item/I = allocate(/obj/item, H.loc)
	TEST_ASSERT(H.put_in_active_hand(I), "A real item is in the active hand")
	H.forceMove(tile(6, 6))
	rejected = test_menu(H, D, "touch")
	TEST_ASSERT_EQUAL(rejected?.outcome, ACT_REFUSED, "Distant item-touch menu picks are refused")
	H.forceMove(tile(2, 2))
	hold(H, STAT_CAN_ACT, null, src)
	TEST_ASSERT(!H.operation_actor_capable(0), "The real stat veto disables action capability")
	rejected = test_menu(H, D, "touch")
	TEST_ASSERT_EQUAL(rejected?.outcome, ACT_REFUSED, "Capability-vetoed item-touch menu picks are refused")
	release(H, STAT_CAN_ACT, src)
	row = find_row(op_menu(H, D, I), "touch")
	TEST_ASSERT(row && row["enabled"], "The original item-touch operation remains enabled")
	var/datum/op_result/used = test_menu(H, D, "touch")
	TEST_ASSERT_EQUAL(used?.outcome, ACT_COMMITTED, "The public item-touch menu route still commits")
	TEST_ASSERT_EQUAL(H.get_active_hand(), I, "Touch does not consume the held item")

/datum/unit_test/round2_menu_refusal_restore/pandemic
	abstract_type = /datum/unit_test/round2_menu_refusal_restore/pandemic
	var/container_type = /obj/item/reagent_containers/glass/beaker

/datum/unit_test/round2_menu_refusal_restore/pandemic/run_gate()
	set_global(nameof(GLOB.op_menu_builds), GLOB.op_menu_builds)
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/computer/pandemic/P = mach(/obj/machinery/computer/pandemic, tile(3, 2))
	var/list/row = find_row(op_menu(H, P, null), "insert_beaker")
	TEST_ASSERT_NOTNULL(row, "Insert beaker remains visible with an empty hand")
	TEST_ASSERT(!row["enabled"], "Empty-hand insertion is refused")
	TEST_ASSERT_EQUAL(row["reason"], "not possible right now", "The original inappropriate-item refusal remains")
	var/datum/op_result/rejected = test_menu(H, P, "insert_beaker")
	TEST_ASSERT_EQUAL(rejected?.outcome, ACT_REFUSED, "The public empty-hand pick is refused")
	TEST_ASSERT_NULL(P.beaker, "Refusal leaves the real slot empty")
	var/obj/item/invalid = allocate(/obj/item, H.loc)
	TEST_ASSERT(H.put_in_active_hand(invalid), "The inappropriate item is really held")
	row = find_row(op_menu(H, P, invalid), "insert_beaker")
	TEST_ASSERT(row && !row["enabled"], "An inappropriate item retains the gray insertion row")
	TEST_ASSERT_EQUAL(row["reason"], "not possible right now", "Invalid items retain the exact refusal")
	var/datum/op_resolution/R = op_resolve(H, P, invalid, ORIGIN_CLICK, actor_authority(H), null, null, FALSE)
	var/datum/op_cand/winner = op_resolution_winner(R)
	TEST_ASSERT(winner?.oplan?.key != "insert_beaker", "Invalid physical item clicks still fall through instead of selecting insertion")
	rejected = test_menu(H, P, "insert_beaker")
	TEST_ASSERT_EQUAL(rejected?.outcome, ACT_REFUSED, "Invalid menu insertion is refused")
	TEST_ASSERT_EQUAL(H.get_active_hand(), invalid, "Refusal retains actual hand custody")
	TEST_ASSERT_NULL(P.beaker, "Invalid insertion does not mutate the slot")
	qdel(invalid)
	var/obj/item/container = allocate(container_type, H.loc)
	TEST_ASSERT(H.put_in_active_hand(container), "The real compatible container is held")
	H.forceMove(tile(6, 6))
	rejected = test_menu(H, P, "insert_beaker")
	TEST_ASSERT_EQUAL(rejected?.outcome, ACT_REFUSED, "Distant insertion menu picks are refused")
	TEST_ASSERT_NULL(P.beaker, "Distance refusal leaves the real slot empty")
	TEST_ASSERT_EQUAL(H.get_active_hand(), container, "Distance refusal preserves hand custody")
	H.forceMove(tile(2, 2))
	hold(H, STAT_CAN_ACT, null, src)
	TEST_ASSERT(!H.operation_actor_capable(0), "The real stat veto disables insertion capability")
	rejected = test_menu(H, P, "insert_beaker")
	TEST_ASSERT_EQUAL(rejected?.outcome, ACT_REFUSED, "Capability-vetoed insertion menu picks are refused")
	TEST_ASSERT_NULL(P.beaker, "Capability refusal leaves the slot empty")
	TEST_ASSERT_EQUAL(H.get_active_hand(), container, "Capability refusal preserves hand custody")
	release(H, STAT_CAN_ACT, src)
	row = find_row(op_menu(H, P, container), "insert_beaker")
	TEST_ASSERT(row && row["enabled"], "Compatible container insertion remains enabled")
	var/datum/op_result/inserted = test_click(H, P, container)
	TEST_ASSERT_EQUAL(inserted?.key, "insert_beaker", "The real compatible-container click selects insertion ahead of generic computer item use")
	TEST_ASSERT_EQUAL(inserted?.outcome, ACT_COMMITTED, "The public physical click inserts the compatible container")
	TEST_ASSERT_EQUAL(P.beaker, container, "The exact container occupies the actual slot")
	TEST_ASSERT_EQUAL(container.loc, P, "Insertion physically moves the container")
	TEST_ASSERT_NULL(H.get_active_hand(), "Successful insertion vacates the actor hand")
	var/obj/item/second = allocate(container_type, H.loc)
	TEST_ASSERT(H.put_in_active_hand(second), "A second compatible container is held")
	row = find_row(op_menu(H, P, second), "insert_beaker")
	TEST_ASSERT(row && !row["enabled"], "Occupied slots still refuse insertion")
	TEST_ASSERT_EQUAL(row["reason"], "a beaker is already loaded", "The existing occupied-slot refusal remains exact")
	rejected = test_menu(H, P, "insert_beaker")
	TEST_ASSERT_EQUAL(rejected?.outcome, ACT_REFUSED, "Public occupied-slot insertion is refused")
	TEST_ASSERT_EQUAL(P.beaker, container, "Refusal preserves the first inserted container")
	TEST_ASSERT_EQUAL(H.get_active_hand(), second, "Refusal preserves the second held container")

/datum/unit_test/round2_menu_refusal_restore/pandemic/beaker
/datum/unit_test/round2_menu_refusal_restore/pandemic/syringe
	container_type = /obj/item/reagent_containers/syringe
