/datum/unit_test/read_once_machinery_admission/round3_vr_logout_cancel
/datum/unit_test/read_once_machinery_admission/round3_vr_logout_cancel/run_gate()
	var/mob/living/carbon/human/H = person()
	TEST_ASSERT_NULL(SSrequests.open_for(H), "The actor starts without a request")
	grant(H, granted_verb(/mob/living/carbon/human/proc/fake_exit_vr), H)
	H.fake_exit_vr()
	TEST_ASSERT(istype(SSrequests.open_for(H), /datum/prompt/yes_no), "The genuinely granted logout verb opens its native question")
	test_answer(H, null, REQ_CANCELLED)
	TEST_ASSERT(!QDELETED(H), "Cancelling leaves the actual avatar alive")
	TEST_ASSERT_EQUAL(H.loc, tile(2, 2), "Cancelling preserves actual avatar placement")
	H.fake_exit_vr()
	test_answer(H, FALSE)
	TEST_ASSERT(!QDELETED(H), "Answering No preserves the actual avatar")
	TEST_ASSERT_NULL(SSrequests.open_for(H), "No finishes the operation without another prompt")

/datum/unit_test/read_once_machinery_admission/round3_ai_core_offer
/datum/unit_test/read_once_machinery_admission/round3_ai_core_offer/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/structure/AIcore/deactivated/core = allocate(/obj/structure/AIcore/deactivated, tile(3, 2))
	perform_op(H, core, "latejoin_offer", origin = ORIGIN_SYSTEM)
	TEST_ASSERT(istype(SSrequests.open_for(H), /datum/prompt/yes_no), "The completed core opens its actual native latejoin offer")
	test_answer(H, null, REQ_CANCELLED)
	TEST_ASSERT(!(core in REGISTRY_MEMBERS(REGISTRY_EMPTY_AI_CORES)), "Cancel leaves the core unavailable")
	perform_op(H, core, "latejoin_offer", origin = ORIGIN_SYSTEM)
	test_answer(H, TRUE)
	TEST_ASSERT(core in REGISTRY_MEMBERS(REGISTRY_EMPTY_AI_CORES), "Accepting registers the actual completed core for latejoin")
	registry_leave(REGISTRY_EMPTY_AI_CORES, core)
