// Public gameplay entries schedule these continuations; no callback is invoked directly.
/datum/unit_test/retire_after_lunge_deleted_warmup_target

/datum/unit_test/retire_after_lunge_deleted_warmup_target/Run()
	set_global("om_resolve_nulled", GLOB.om_resolve_nulled)
	test_driver_begin()
	set_global("dview_mob", GLOB.dview_mob)
	defer_cleanup(null, GLOBAL_PROC_REF(test_driver_end))
	var/turf/T = test_floor()
	var/mob/living/simple_mob/vore/cryptdrake/drake = allocate(/mob/living/simple_mob/vore/cryptdrake, T)
	var/mob/living/carbon/human/monkey/punpun/prey = allocate(/mob/living/carbon/human/monkey/punpun, T)
	TEST_ASSERT(drake.ai_brain, "Cryptdrake must initialize its real AI brain")
	TEST_ASSERT(prey.devourable && prey.allowmobvore && prey.can_be_drop_prey && prey.throw_vore && !prey.unacidable, "Actual Pun Pun must satisfy lunge preconditions")
	drake.do_special_attack(prey, 0)
	TEST_ASSERT(drake.ai_brain.is_busy(), "Public attack must claim the owner during warmup")
	TEST_ASSERT(!(drake.status_flags & LEAPING), "Warmup must precede passage-state activation")
	qdel(prey)
	test_time(drake.leap_warmup + 0.1 SECONDS)
	TEST_ASSERT(!drake.ai_brain.is_busy(), "Deleted warmup target must release the real busy hold")
	TEST_ASSERT(!(drake.status_flags & LEAPING), "Deleted warmup target must not activate passage state")

/datum/unit_test/retire_after_lunge_deleted_landing_target

/datum/unit_test/retire_after_lunge_deleted_landing_target/Run()
	set_global("om_resolve_nulled", GLOB.om_resolve_nulled)
	test_driver_begin()
	set_global("dview_mob", GLOB.dview_mob)
	defer_cleanup(null, GLOBAL_PROC_REF(test_driver_end))
	var/turf/T = test_floor()
	var/mob/living/simple_mob/vore/cryptdrake/drake = allocate(/mob/living/simple_mob/vore/cryptdrake, T)
	var/mob/living/carbon/human/monkey/punpun/prey = allocate(/mob/living/carbon/human/monkey/punpun, T)
	TEST_ASSERT(drake.ai_brain, "Cryptdrake must initialize its real AI brain")
	TEST_ASSERT(prey.devourable && prey.allowmobvore && prey.can_be_drop_prey && prey.throw_vore && !prey.unacidable, "Actual Pun Pun must satisfy lunge preconditions")
	drake.do_special_attack(prey, 0)
	TEST_ASSERT(drake.ai_brain.is_busy(), "Public attack must schedule the warmup")
	test_time(drake.leap_warmup)
	TEST_ASSERT(drake.status_flags & LEAPING, "Real warmup must reach the landing continuation")
	TEST_ASSERT(drake.ai_brain.is_busy(), "Landing continuation must still own the busy hold")
	qdel(prey)
	test_time(0.6 SECONDS)
	TEST_ASSERT(!drake.ai_brain.is_busy(), "Deleted landing target must release the busy hold")
	TEST_ASSERT(!(drake.status_flags & LEAPING), "Landing cleanup must restore passage state despite deleted target")

/datum/unit_test/retire_after_mule_deleted_load

/datum/unit_test/retire_after_mule_deleted_load/Run()
	set_global("om_resolve_nulled", GLOB.om_resolve_nulled)
	test_driver_begin()
	set_global("dview_mob", GLOB.dview_mob)
	defer_cleanup(null, GLOBAL_PROC_REF(test_driver_end))
	var/turf/T = test_floor()
	var/mob/living/bot/mulebot/bot = allocate(/mob/living/bot/mulebot, T)
	var/obj/structure/closet/crate/crate = allocate(/obj/structure/closet/crate, T)
	TEST_ASSERT(!task_busy(bot) && !bot.load, "Real mule must start available")
	bot.load(crate)
	TEST_ASSERT(task_busy(bot), "Public load must enter the actual settling delay")
	TEST_ASSERT_EQUAL(crate.loc, bot.loc, "Public load must stage the actual crate on the bot's floor")
	qdel(crate)
	test_time(0.3 SECONDS)
	TEST_ASSERT_NULL(bot.load, "Deleted staged crate must never enter the load slot")
	TEST_ASSERT(!task_busy(bot), "Independent busy hold must expire after missing-load callback")
