/// Real pipe state and timed clamp removal retain their explicit initiating actor.
/datum/unit_test/interim_clamp_detach_actor/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	actor.enable_godmode()
	bystander.enable_godmode()
	var/obj/machinery/atmospherics/pipe/simple/pipe = allocate(/obj/machinery/atmospherics/pipe/simple, T)
	var/obj/machinery/clamp/clamp = allocate(/obj/machinery/clamp, T, pipe)
	TEST_ASSERT_EQUAL(clamp.target_ref(), pipe, "the actual clamp attaches to its supplied pipe")
	TEST_ASSERT(clamp.interaction_toggle(actor, null, null), "the actual toggle closes the clamp")
	TEST_ASSERT(pipe.in_stasis, "the closed clamp places its actual pipe in stasis")
	clamp.detach_with_actor(actor, actor)
	test_time(4 SECONDS)
	TEST_ASSERT(!QDELETED(clamp), "a closed clamp cannot start timed removal")
	TEST_ASSERT(pipe.in_stasis, "refused removal preserves actual closed pipe state")
	TEST_ASSERT(clamp.interaction_toggle(actor, null, null), "the actual toggle reopens the clamp")
	TEST_ASSERT(!pipe.in_stasis, "reopening restores actual pipe flow")
	clamp.detach_with_actor(actor, bystander)
	clamp.detach_with_actor(null, actor)
	test_time(4 SECONDS)
	TEST_ASSERT(!QDELETED(clamp), "unrelated drop destinations and absent actors cannot remove the clamp")
	TEST_ASSERT_NULL(actor.get_active_hand(), "refused removal produces no item in the actor's hand")
	TEST_ASSERT_EQUAL(actor.stat, CONSCIOUS, "the real timed-task actor remains conscious after the prior refusal waits")
	clamp.detach_with_actor(actor, actor)
	test_time(1 SECOND)
	TEST_ASSERT(!QDELETED(clamp), "actual removal does not finish before its three second delay")
	test_time(3 SECONDS)
	TEST_ASSERT(QDELETED(clamp), "the actual timed callback removes the original clamp machine")
	var/obj/item/clamp/product = actor.get_active_hand()
	TEST_ASSERT(istype(product), "the actual callback places its folded clamp product in the initiating actor's hand")
	own(product)
	TEST_ASSERT_EQUAL(product.loc, actor, "the actual folded clamp is contained by its initiating actor")
	TEST_ASSERT_NULL(bystander.get_active_hand(), "the unrelated nearby mob receives no clamp product")
	TEST_ASSERT(!QDELETED(pipe), "actual clamp replacement preserves its attached pipe")
	TEST_ASSERT(!pipe.in_stasis, "actual removal preserves the reopened pipe's flow state")
