/// A pinned target's destruction must restore its real stake's blocking behavior.
/datum/unit_test/interim_target_stake_deletion/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/structure/target_stake/stake = allocate(/obj/structure/target_stake, T)
	var/obj/item/target/target = allocate(/obj/item/target, T)
	TEST_ASSERT(actor.put_in_active_hand(target), "The actor must hold the shooting target")
	TEST_ASSERT(stake.interaction_item(actor, target, null), "The stake's real insertion interaction must accept the target")
	TEST_ASSERT_EQUAL(stake.pinned_target, target, "The stake must record its actual pinned target")
	TEST_ASSERT(!stake.density && target.density, "A pinned target must replace the stake's blocking surface")
	qdel(target)
	TEST_ASSERT_NULL(stake.pinned_target, "Deleting the target must clear the stake's relation")
	TEST_ASSERT(stake.density, "Deleting the pinned target must restore the stake's blocking surface")
	TEST_ASSERT(!QDELETED(stake), "Target deletion must preserve its stake")

/// Destruction must release a real trapped ghost before declared views disappear.
/datum/unit_test/interim_ghost_trap_deletion/Run()
	var/turf/T = test_floor()
	var/obj/item/ghost_trap/trap = allocate(/obj/item/ghost_trap, T)
	var/mob/observer/dead/ghost = allocate(/mob/observer/dead, T)
	trap.catch_ghost(ghost)
	TEST_ASSERT_EQUAL(trap.captured_entity, ghost, "The real capture operation must record its ghost")
	TEST_ASSERT_EQUAL(ghost.loc, trap, "The real capture operation must physically contain the ghost")
	TEST_ASSERT(has_trait(ghost, TRAIT_NO_TRANSFORM), "Capturing the ghost must actually inhibit transformation")
	qdel(trap)
	TEST_ASSERT(!QDELETED(ghost), "Destroying a trap must preserve its captured ghost")
	TEST_ASSERT_EQUAL(ghost.loc, T, "Destroying a trap must release its ghost onto the actual floor")
	TEST_ASSERT(!has_trait(ghost, TRAIT_NO_TRANSFORM), "Destroying the trap must remove its transformation inhibition")
