/// A full real storage item must refuse before removing the candidate from its actor's hand.
/datum/unit_test/interim_storage_held_count_refusal/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/box/box = allocate(/obj/item/storage/box, T)
	box.storage_slots = 1
	var/obj/item/pen/filler = allocate(/obj/item/pen, T)
	var/obj/item/pen/candidate = allocate(/obj/item/pen, T)
	TEST_ASSERT(box.insert_item(filler), "the box's single slot can be filled")
	TEST_ASSERT(user.put_in_active_hand(candidate), "the candidate is held")
	var/held_slot = user.inventory_slot_id(candidate)
	var/used_before = box.slot_used()
	TEST_ASSERT(!box.insert_item(candidate, user), "the full box refuses the held candidate")
	TEST_ASSERT_EQUAL(candidate.loc, user, "a count refusal preserves the candidate's holder")
	TEST_ASSERT_EQUAL(user.inventory_slot_id(candidate), held_slot, "a count refusal preserves the held slot")
	TEST_ASSERT_EQUAL(box.slot_used(), used_before, "a count refusal preserves used capacity")
	TEST_ASSERT(filler in box.slot_contents(CONTAINER_SLOT_STORAGE), "a refusal preserves the existing contents")
	TEST_ASSERT(!(candidate in box.slot_contents(CONTAINER_SLOT_STORAGE)), "a refusal cannot list the candidate as stored")
	TEST_ASSERT(box.remove_from_storage(filler, T, user), "removing the filler frees the count limit")
	TEST_ASSERT(box.insert_item(candidate, user), "the same candidate fits once the slot is free")
	TEST_ASSERT_EQUAL(candidate.loc, box, "accepted insertion moves the candidate inside")
	TEST_ASSERT_NULL(user.inventory_slot_id(candidate), "accepted insertion clears the hand slot")
	TEST_ASSERT(candidate in box.slot_contents(CONTAINER_SLOT_STORAGE), "accepted insertion records the stored item")
	TEST_ASSERT(box.remove_from_storage(candidate, T, user), "the candidate can be removed again")
	TEST_ASSERT_EQUAL(candidate.loc, T, "removal returns the candidate to the floor")
	TEST_ASSERT_EQUAL(box.slot_used(), 0, "removing the last item releases all used capacity")

/// Legacy storage deletes what remains inside it, while removed items survive the container.
/datum/unit_test/interim_storage_destroy_contents/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/item/storage/backpack/pack = allocate(/obj/item/storage/backpack, T)
	var/obj/item/storage/box/box = allocate(/obj/item/storage/box, T)
	var/obj/item/pen/kept = allocate(/obj/item/pen, T)
	var/obj/item/pen/removed = allocate(/obj/item/pen, T)
	TEST_ASSERT(box.insert_item(kept), "the inner box holds an item")
	TEST_ASSERT(pack.insert_item(box), "the backpack holds the inner box")
	TEST_ASSERT(pack.insert_item(removed), "the backpack holds an item to remove")
	TEST_ASSERT(pack.remove_from_storage(removed, T), "the removed item leaves the backpack")
	TEST_ASSERT_EQUAL(removed.loc, T, "the removed item reaches the floor before deletion")
	qdel(pack)
	TEST_ASSERT(QDELETED(pack), "the backpack is deleted")
	TEST_ASSERT(QDELETED(box), "legacy storage deletes its contained box")
	TEST_ASSERT(QDELETED(kept), "nested storage deletion reaches its contained item")
	TEST_ASSERT(!QDELETED(removed), "a previously removed item survives storage deletion")
	TEST_ASSERT_EQUAL(removed.loc, T, "storage deletion leaves the removed item's placement unchanged")
