/// Actual solar tracking electronics must be consumed before the assembly gains its refundable tracker.
/datum/unit_test/interim_solar_assembly_sticky_tracker/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/solar_assembly/assembly = allocate(/obj/item/solar_assembly, T)
	var/obj/item/tracker_electronics/electronics = allocate(/obj/item/tracker_electronics, T)
	TEST_ASSERT_EQUAL(assembly.tracker, 0, "actual solar assembly starts without tracking electronics")
	TEST_ASSERT_EQUAL(assembly.loc, T, "actual assembly occupies a turf required by its construction effect")
	TEST_ASSERT(user.put_in_active_hand(electronics), "the actor holds exact original tracking electronics")
	add_trait(electronics, TRAIT_NODROP, "interim_solar_tracker")
	TEST_ASSERT(user.release_refusal(electronics, user), "actual inventory refuses sticky tracking electronics")
	test_click(user, assembly, electronics)
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(assembly.tracker, 0, "refused consumption grants no tracking assembly state")
	TEST_ASSERT(!QDELETED(electronics), "refused installation preserves exact original electronics")
	TEST_ASSERT_EQUAL(user.get_active_hand(), electronics, "refused installation preserves original source hand")
	TEST_ASSERT_EQUAL(electronics.loc, user, "refused installation preserves inventory containment")
	remove_trait(electronics, TRAIT_NODROP, "interim_solar_tracker")
	test_click(user, assembly, electronics)
	test_time(1 SECOND)
	TEST_ASSERT(QDELETED(electronics), "allowed installation consumes exact original electronics")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(assembly.tracker, 1, "one consumed original enables actual tracker construction state")
	var/obj/item/tool/crowbar/tool = allocate(/obj/item/tool/crowbar, T)
	TEST_ASSERT(user.put_in_active_hand(tool), "the actor holds a real crowbar for public removal")
	var/refunds_before = length(contents_of(T, /obj/item/tracker_electronics))
	test_click(user, assembly, tool)
	test_time(3 SECONDS)
	TEST_ASSERT_EQUAL(assembly.tracker, 0, "actual crowbar removal clears tracking electronics state")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/tracker_electronics)), refunds_before + 1, "actual crowbar removal refunds exactly one physical electronics unit")
	var/obj/item/tracker_electronics/refund = locate_within(T, /obj/item/tracker_electronics)
	TEST_ASSERT_NOTNULL(refund, "actual removal produces surviving real electronics")
	own(refund)
	TEST_ASSERT(!QDELETED(refund) && refund != electronics, "actual refund is a distinct replacement for consumed original")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "public removal preserves actual held crowbar")
	test_driver_end()
