/// Destroying a reversible gargoyle statue must restore its real petrified person.
/datum/unit_test/interim_gargoyle_deletion/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/person = allocate(/mob/living/carbon/human, T)
	TEST_ASSERT(!(person.sdisabilities & MUTE), "The fixture person must initially be able to speak")
	var/obj/structure/gargoyle/statue = allocate(/obj/structure/gargoyle, T, person)
	TEST_ASSERT_EQUAL(statue.WR_gargoyle, person, "The real statue constructor must record its petrified person")
	TEST_ASSERT_EQUAL(person.loc, statue, "The real statue constructor must physically contain its person")
	TEST_ASSERT(person.sdisabilities & MUTE, "Petrification must actually mute its person")
	TEST_ASSERT(!person.canmove, "Petrification must actually prevent movement")
	qdel(statue)
	TEST_ASSERT(!QDELETED(person), "Destroying a reversible statue must preserve its person")
	TEST_ASSERT_EQUAL(person.loc, T, "Statue destruction must release its person to the floor")
	TEST_ASSERT(!(person.sdisabilities & MUTE), "Statue destruction must restore the person's speech")
	TEST_ASSERT(person.canmove, "Statue destruction must restore the person's movement")
