/// Charging must report accepted energy and leave full cells at their capacity.
/datum/unit_test/interim_cell_charge_boundaries/Run()
	var/obj/item/cell/C = allocate(/obj/item/cell, run_loc_floor_bottom_left)
	C.charge = C.maxcharge - 10
	TEST_ASSERT_EQUAL(C.give(25, FALSE), 10, "charging reports only the space available")
	TEST_ASSERT_EQUAL(C.charge, C.maxcharge, "charging stops at capacity")
	TEST_ASSERT_EQUAL(C.give(25, FALSE), 0, "a full cell accepts nothing")
	TEST_ASSERT_EQUAL(C.give(-25, FALSE), 0, "negative charging cannot drain the cell")
	TEST_ASSERT_EQUAL(C.charge, C.maxcharge, "refused charging preserves charge")
	C.charge = 0
	TEST_ASSERT_EQUAL(C.percent(), 0, "an empty cell reports zero percent")
	TEST_ASSERT_EQUAL(C.use(10, FALSE), 0, "an empty cell cannot deliver power")
	TEST_ASSERT_EQUAL(C.charge, 0, "failed discharge leaves no negative charge")
	TEST_ASSERT_EQUAL(C.give(25, FALSE), 25, "an empty cell accepts the requested charge")
	TEST_ASSERT_EQUAL(C.charge, 25, "accepted charge is stored")
	TEST_ASSERT(!C.checked_use(C.maxcharge + 1), "an unaffordable checked discharge refuses")
	TEST_ASSERT_EQUAL(C.charge, 25, "a refused checked discharge preserves charge")

/// Moving an item between storage containers must clear the old slot as well as loc.
/datum/unit_test/interim_storage_cell_roundtrip/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/item/storage/backpack/first = allocate(/obj/item/storage/backpack, T)
	var/obj/item/storage/backpack/second = allocate(/obj/item/storage/backpack, T)
	var/obj/item/cell/C = allocate(/obj/item/cell, T)
	TEST_ASSERT(first.insert_item(C), "the first backpack accepts a cell")
	TEST_ASSERT_EQUAL(C.loc, first, "the inserted cell is inside the first backpack")
	TEST_ASSERT(C in first.slot_contents(CONTAINER_SLOT_STORAGE), "the first storage slot contains it")
	TEST_ASSERT(second.insert_item(C), "the second backpack accepts a stored cell")
	TEST_ASSERT_EQUAL(C.loc, second, "the transferred cell is inside the second backpack")
	TEST_ASSERT(!(C in first.slot_contents(CONTAINER_SLOT_STORAGE)), "the old storage slot releases it")
	TEST_ASSERT(C in second.slot_contents(CONTAINER_SLOT_STORAGE), "the new storage slot contains it")
	TEST_ASSERT(!first.remove_from_storage(C, T), "the old container cannot remove a transferred item")
	TEST_ASSERT_EQUAL(C.loc, second, "a wrong-container removal preserves location")
	TEST_ASSERT(second.remove_from_storage(C, T), "the cell can be removed to the floor")
	TEST_ASSERT_EQUAL(C.loc, T, "removal places the cell on the floor")
	TEST_ASSERT(!(C in second.slot_contents(CONTAINER_SLOT_STORAGE)), "removal clears the storage slot")

/// A capacity-limited pour preserves the proportions of the source mixture.
/datum/unit_test/interim_reagent_transfer_capacity/Run()
	var/obj/item/reagent_containers/glass/beaker/source = allocate(/obj/item/reagent_containers/glass/beaker, run_loc_floor_bottom_left)
	var/obj/item/reagent_containers/glass/beaker/target = allocate(/obj/item/reagent_containers/glass/beaker, run_loc_floor_bottom_left)
	source.reagents.add_reagent(REAGENT_ID_WATER, 30)
	source.reagents.add_reagent(REAGENT_ID_ETHANOL, 10)
	target.reagents.add_reagent(REAGENT_ID_WATER, target.reagents.maximum_volume - 8)
	var/target_before = target.reagents.total_volume
	TEST_ASSERT_EQUAL(source.reagents.trans_to(target, 20), 8, "a pour is limited to the destination's free space")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 32, "only the accepted amount leaves the source")
	TEST_ASSERT_EQUAL(source.reagents.get_reagent_amount(REAGENT_ID_WATER), 24, "the pour removes water proportionally")
	TEST_ASSERT_EQUAL(source.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 8, "the pour removes ethanol proportionally")
	TEST_ASSERT_EQUAL(target.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 2, "the target receives its ethanol share")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, target_before + 8, "the target receives exactly the debit")
	TEST_ASSERT(!source.reagents.trans_to(target, 20), "a full destination accepts no more")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 32, "a refused pour preserves the source")

/// Scaled transfers report the source debit; copies leave that source unchanged.
/datum/unit_test/interim_reagent_transfer_scaled_copy/Run()
	var/obj/item/reagent_containers/glass/beaker/source = allocate(/obj/item/reagent_containers/glass/beaker, run_loc_floor_bottom_left)
	var/obj/item/reagent_containers/glass/beaker/target = allocate(/obj/item/reagent_containers/glass/beaker, run_loc_floor_bottom_left)
	source.reagents.add_reagent(REAGENT_ID_WATER, 20)
	TEST_ASSERT_EQUAL(source.reagents.trans_to_holder(target.reagents, 10, multiplier = 2), 10, "the return value is the source debit")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 10, "scaled transfer debits the requested source amount")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 20, "the target receives the scaled amount")
	TEST_ASSERT_EQUAL(source.reagents.trans_to_holder(target.reagents, 4, multiplier = 0.5, copy = TRUE), 4, "a copy reports the amount sampled")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 10, "copying preserves source volume")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 22, "copying still adds the scaled amount to the target")
	TEST_ASSERT(!source.reagents.trans_to_holder(target.reagents, -5), "negative transfer amounts refuse")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 10, "negative transfer preserves source volume")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 22, "negative transfer preserves target volume")

/// Layers are consumed only when they fit the cake's current construction stage.
/datum/unit_test/interim_cake_layer_progression/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/thecake/cake = allocate(/obj/structure/thecake, T)
	var/obj/item/thecake_layer/first = allocate(/obj/item/thecake_layer, T)
	var/obj/item/thecake_layer/five/wrong = allocate(/obj/item/thecake_layer/five, T)
	TEST_ASSERT_EQUAL(cake.stage, 1, "a new cake starts at its first stage")
	test_op_handler(cake, "interaction_item", user, wrong)
	TEST_ASSERT_EQUAL(cake.stage, 1, "a wrong layer cannot advance the stage")
	TEST_ASSERT(!QDELETED(wrong), "a rejected layer is not consumed")
	TEST_ASSERT_EQUAL(wrong.loc, T, "a rejected layer stays where it was")
	test_op_handler(cake, "interaction_item", user, first)
	TEST_ASSERT_EQUAL(cake.stage, 2, "the matching layer advances the cake exactly once")
	TEST_ASSERT(QDELETED(first), "the matching layer is consumed")
	TEST_ASSERT_EQUAL(cake.icon_state, "thecake_stage-2", "the cake displays the next construction stage")
	TEST_ASSERT(!cake.edible, "a partial cake remains inedible")

/// Direct UI dispatch must authorize the supplied actor, including when usr is absent.
/datum/unit_test/interim_research_console_lock_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/computer/rdconsole_tg/console = allocate(/obj/machinery/computer/rdconsole_tg, T)
	TEST_ASSERT(!console.locked, "the research console starts unlocked")
	op_ui_act(user, console, "toggleLock")
	TEST_ASSERT(!console.locked, "a user without research access cannot lock it")
	var/obj/item/card/id/id = allocate(/obj/item/card/id, T)
	id.access = list(ACCESS_RESEARCH)
	TEST_ASSERT(user.put_in_active_hand(id), "the user holds the research-access ID")
	TEST_ASSERT(console.allowed(user), "the held ID grants the console's required access")
	op_ui_act(user, console, "toggleLock")
	TEST_ASSERT(console.locked, "the supplied authorized actor can lock the console")
	op_ui_act(user, console, "toggleLock")
	TEST_ASSERT(!console.locked, "the same actor can unlock it again")

/// The public insertion path must finish the newly seated patient's presentation and buckle state.
/datum/unit_test/interim_cryo_patient_roundtrip/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/atmospherics/unary/cryo_cell/cell = allocate(/obj/machinery/atmospherics/unary/cryo_cell, T)
	var/obj/machinery/atmospherics/pipe/simple/pipe = allocate(/obj/machinery/atmospherics/pipe/simple, get_step(T, NORTH))
	rel_set(cell, nameof(cell.node), pipe)
	cell.set_grid_power(TRUE)
	cell.set_broken_condition(FALSE)
	cell.set_maintenance(FALSE)
	release(cell, STAT_OPERABLE, SRC_EMP)
	TEST_ASSERT(cell.operable(), "the connected cryo cell is operable")
	TEST_ASSERT(!patient.abiotic(), "the patient has no items preventing insertion")
	var/pixel_y_before = patient.pixel_y
	TEST_ASSERT(occupant_enter(cell, patient, actor), "the public insertion path finishes successfully")
	test_time(1)
	TEST_ASSERT_EQUAL(occupant_of(cell), patient, "the patient occupies the cryo slot")
	TEST_ASSERT_EQUAL(patient.loc, cell, "the patient is inside the cell")
	TEST_ASSERT_EQUAL(patient.buckled_to(), cell, "insertion buckles the newly inserted patient")
	TEST_ASSERT(patient in cell.vis_contents, "insertion presents the patient in the tube")
	TEST_ASSERT_EQUAL(patient.pixel_y, pixel_y_before + 19, "insertion raises the patient's presentation offset")
	TEST_ASSERT(patient.cozyloop.running, "insertion starts the patient's cryo sound")
	TEST_ASSERT_EQUAL(cell.use_power, USE_POWER_ACTIVE, "an occupied cell uses active power")
	TEST_ASSERT(!occupant_enter(cell, actor, actor), "a second patient is refused")
	TEST_ASSERT_EQUAL(occupant_of(cell), patient, "refused insertion preserves the current patient")
	occupant_eject(cell)
	test_time(1)
	TEST_ASSERT_NULL(occupant_of(cell), "ejection clears the occupant slot")
	TEST_ASSERT_NULL(patient.buckled_to(), "ejection unbuckles the patient")
	TEST_ASSERT(!(patient in cell.vis_contents), "ejection removes the tube presentation")
	TEST_ASSERT_EQUAL(patient.pixel_y, patient.default_pixel_y, "ejection restores the patient's offset")
	TEST_ASSERT(!patient.cozyloop.running, "ejection stops the patient's cryo sound")
	TEST_ASSERT_EQUAL(cell.use_power, USE_POWER_IDLE, "an empty cell returns to idle power")
	test_driver_end()
