/// Actual wrench dismantling preserves the bed's material return policy.
/datum/unit_test/interim_bed_dismantle_bare/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/bed/bed = allocate(/obj/structure/bed, T)
	var/obj/item/tool/wrench/tool = allocate(/obj/item/tool/wrench, T)
	TEST_ASSERT_EQUAL(bed.material, get_material_by_name(MAT_STEEL), "the actual bed has its default steel frame")
	TEST_ASSERT(user.put_in_active_hand(tool), "the actor holds the actual dismantling wrench")
	TEST_ASSERT(test_op_committed(perform_op(user, bed, "dismantle", tool)), "actual wrench dismantling commits")
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(bed), "actual wrench dismantling immediately consumes the original floor bed")
	TEST_ASSERT_NULL(locate_within(T, /obj/structure/bed), "dismantling leaves no duplicate bed")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/steel)), 1, "actual dismantling returns exactly one steel stack")
	var/obj/item/stack/material/steel/steel = locate_within(T, /obj/item/stack/material/steel)
	TEST_ASSERT_EQUAL(steel.get_amount(), 1, "actual dismantling returns one steel sheet for the bed frame")
	TEST_ASSERT_EQUAL(steel.loc, T, "the actual returned steel remains on the original floor")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "actual dismantling preserves the actor's held wrench")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/cloth)), 0, "actual bare-bed dismantling returns no nonexistent padding")

/// Actual wrench dismantling preserves the bed's material return policy.
/datum/unit_test/interim_bed_dismantle_padded/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/bed/bed = allocate(/obj/structure/bed, T)
	var/obj/item/tool/wrench/tool = allocate(/obj/item/tool/wrench, T)
	bed.add_padding(MAT_CLOTH)
	TEST_ASSERT_EQUAL(bed.padding_material, get_material_by_name(MAT_CLOTH), "the actual padded bed contains cloth padding before dismantling")
	TEST_ASSERT_EQUAL(bed.material, get_material_by_name(MAT_STEEL), "the actual bed has its default steel frame")
	TEST_ASSERT(user.put_in_active_hand(tool), "the actor holds the actual dismantling wrench")
	TEST_ASSERT(test_op_committed(perform_op(user, bed, "dismantle", tool)), "actual wrench dismantling commits")
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(bed), "actual wrench dismantling immediately consumes the original floor bed")
	TEST_ASSERT_NULL(locate_within(T, /obj/structure/bed), "dismantling leaves no duplicate bed")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/steel)), 1, "actual dismantling returns exactly one steel stack")
	var/obj/item/stack/material/steel/steel = locate_within(T, /obj/item/stack/material/steel)
	TEST_ASSERT_EQUAL(steel.get_amount(), 1, "actual dismantling returns one steel sheet for the bed frame")
	TEST_ASSERT_EQUAL(steel.loc, T, "the actual returned steel remains on the original floor")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "actual dismantling preserves the actor's held wrench")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/cloth)), 1, "actual padded dismantling returns exactly one cloth stack")
	var/obj/item/stack/material/cloth/cloth = locate_within(T, /obj/item/stack/material/cloth)
	TEST_ASSERT_EQUAL(cloth.get_amount(), 1, "actual padded dismantling returns one cloth sheet")
	TEST_ASSERT_EQUAL(cloth.loc, T, "the actual padding return remains on the original floor")
