/// Real native gun HUD clicks affect the supplied actor's owned aiming state and actual icons.
/datum/unit_test/interim_gun_hud_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/mob/observer/dead/unsupported = allocate(/mob/observer/dead, T)
	var/atom/movable/screen/gun/move/move_button = allocate(/atom/movable/screen/gun/move, T)
	var/atom/movable/screen/gun/item/item_button = allocate(/atom/movable/screen/gun/item, T)
	var/atom/movable/screen/gun/radio/radio_button = allocate(/atom/movable/screen/gun/radio, T)
	var/atom/movable/screen/gun/mode/mode_button = allocate(/atom/movable/screen/gun/mode, T)
	own_set(actor, nameof(actor.gun_move_icon), move_button)
	own_set(actor, nameof(actor.item_use_icon), item_button)
	own_set(actor, nameof(actor.radio_use_icon), radio_button)
	own_set(actor, nameof(actor.gun_setting_icon), mode_button)
	TEST_ASSERT_NULL(actor.aiming, "the actual actor starts without an aiming overlay")
	TEST_ASSERT_NULL(bystander.aiming, "the actual bystander starts without an aiming overlay")
	km_synthetic_click(actor, move_button)
	var/obj/aiming_overlay/aim = actor.aiming
	TEST_ASSERT_NOTNULL(aim, "the actual native click creates the actor's real aiming overlay")
	TEST_ASSERT_EQUAL(aim.owner(), actor, "the actual native click retains the exact initiating actor as overlay owner")
	TEST_ASSERT_EQUAL(aim.target_permissions, TARGET_CAN_MOVE, "the actual native click grants exactly movement permission")
	TEST_ASSERT_EQUAL(move_button.icon_state, "no_walk1", "the actual permission updates the owner's movement icon")
	TEST_ASSERT_EQUAL(move_button.name, "Disallow Movement", "the actual permission updates the owner's movement label")
	TEST_ASSERT_NULL(bystander.aiming, "the actual native click does not create aiming state for the bystander")
	TEST_ASSERT_EQUAL(move_button.click_with_actor(bystander, null, null, null), 1, "the direct helper preserves the legacy consumed return")
	TEST_ASSERT_NOTNULL(bystander.aiming, "the helper creates the explicitly supplied different actor's real overlay")
	TEST_ASSERT_EQUAL(bystander.aiming.owner(), bystander, "the second actual overlay belongs to its explicit actor")
	TEST_ASSERT_EQUAL(bystander.aiming.target_permissions, TARGET_CAN_MOVE, "the second explicit actor receives its own movement permission")
	TEST_ASSERT_EQUAL(actor.aiming, aim, "the second actor preserves the first exact overlay identity")
	TEST_ASSERT_EQUAL(aim.target_permissions, TARGET_CAN_MOVE, "the second actor preserves the first actor's actual permission")
	TEST_ASSERT_EQUAL(move_button.click_with_actor(actor, null, null, null), 1, "the actual repeat click preserves the handled return")
	TEST_ASSERT_EQUAL(aim.target_permissions, 0, "the actual repeat click revokes exactly movement permission")
	TEST_ASSERT_EQUAL(move_button.icon_state, "no_walk0", "the actual repeat click restores the movement icon")
	TEST_ASSERT_EQUAL(move_button.name, "Allow Movement", "the actual repeat click restores the movement label")
	TEST_ASSERT_EQUAL(item_button.click_with_actor(actor, null, null, null), 1, "the actual item-use helper handles its actor")
	TEST_ASSERT_EQUAL(aim.target_permissions, TARGET_CAN_CLICK, "actual item-use grants precisely its permission")
	TEST_ASSERT_EQUAL(item_button.icon_state, "no_item1", "actual item-use updates its real icon")
	TEST_ASSERT_EQUAL(item_button.name, "Disallow Item Use", "actual item-use updates its real label")
	TEST_ASSERT_EQUAL(radio_button.click_with_actor(actor, null, null, null), 1, "the actual radio helper handles its actor")
	TEST_ASSERT_EQUAL(aim.target_permissions, TARGET_CAN_CLICK | TARGET_CAN_RADIO, "actual radio preserves item-use and grants its own bit")
	TEST_ASSERT_EQUAL(radio_button.icon_state, "no_radio1", "actual radio updates its real icon")
	TEST_ASSERT_EQUAL(radio_button.name, "Disallow Radio Use", "actual radio updates its real label")
	km_synthetic_click(actor, mode_button)
	TEST_ASSERT_EQUAL(aim.active, TRUE, "the actual native mode click activates the actor's existing overlay")
	TEST_ASSERT_EQUAL(actor.aiming, aim, "the actual mode click retains the same owned overlay")
	TEST_ASSERT_EQUAL(mode_button.click_with_actor(actor, null, null, null), 1, "the actual mode helper preserves its handled return")
	TEST_ASSERT_EQUAL(aim.active, FALSE, "the actual mode retry deactivates the same overlay")
	TEST_ASSERT_EQUAL(aim.target_permissions, TARGET_CAN_CLICK | TARGET_CAN_RADIO, "actual mode roundtrip preserves permission bits")
	var/list/buttons = list(move_button, item_button, radio_button, mode_button)
	for(var/atom/movable/screen/gun/button as anything in buttons)
		TEST_ASSERT_EQUAL(button.click_with_actor(null, null, null, null), 0, "each actual child preserves the null-actor refusal return")
		TEST_ASSERT_EQUAL(button.click_with_actor(unsupported, null, null, null), 1, "each actual child consumes but ignores a nonliving actor as before")
		TEST_ASSERT_EQUAL(actor.aiming, aim, "unsupported/null actors preserve the original actual overlay identity")
		TEST_ASSERT_EQUAL(aim.target_permissions, TARGET_CAN_CLICK | TARGET_CAN_RADIO, "unsupported/null actors change no real permission")
		TEST_ASSERT_EQUAL(aim.active, FALSE, "unsupported/null actors change no real mode")
	TEST_ASSERT_EQUAL(bystander.aiming.target_permissions, TARGET_CAN_MOVE, "all remaining clicks preserve the unrelated actor's permission")
