/// Actual material armor breakage and worn release preserve the original neighboring items.
/datum/unit_test/interim_material_armor_shatter_cleanup/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/item/clothing/suit/armor/material/makeshift/armor = allocate(/obj/item/clothing/suit/armor/material/makeshift, T)
	var/obj/item/clothing/suit/armor/material/makeshift/control = allocate(/obj/item/clothing/suit/armor/material/makeshift, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT_EQUAL(armor.get_material(), get_material_by_name(MAT_STEEL), "actual armor constructor resolves canonical steel")
	TEST_ASSERT_EQUAL(armor.get_integrity(), armor.max_integrity, "the actual material constructor starts with full integrity")
	var/control_integrity = control.get_integrity()
	armor.take_damage(MATERIAL_WEAR_UNIT, BRUTE, null, FALSE)
	TEST_ASSERT(!QDELETED(armor), "one real wear unit preserves the same armor")
	TEST_ASSERT_EQUAL(armor.get_integrity_damage(), MATERIAL_WEAR_UNIT, "real damage debits exactly one wear unit")
	armor.take_damage(armor.max_integrity, BRUTE, null, FALSE)
	TEST_ASSERT(QDELETED(armor), "actual terminal damage dispatches shatter and deletes the exact exhausted armor")
	TEST_ASSERT(!QDELETED(control), "terminal damage preserves the neighboring original armor")
	TEST_ASSERT_EQUAL(control.get_integrity(), control_integrity, "terminal damage leaves neighboring armor integrity unchanged")
	TEST_ASSERT_EQUAL(control.loc, T, "neighboring original armor stays on its original floor")
	TEST_ASSERT(!QDELETED(pen), "terminal damage preserves the original unrelated pen")
	TEST_ASSERT_EQUAL(pen.loc, T, "terminal damage preserves the original pen location")

/datum/unit_test/interim_material_armor_shatter_cleanup/worn/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/clothing/suit/armor/material/makeshift/armor = allocate(/obj/item/clothing/suit/armor/material/makeshift, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT_EQUAL(armor.get_material(), get_material_by_name(MAT_STEEL), "actual worn armor constructor resolves canonical steel")
	TEST_ASSERT(actor.equip_to_slot(armor, SLOT_ID_SUIT), "the real armor equips through the actual public suit-slot API")
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_SUIT), armor, "the exact armor occupies the real suit slot")
	TEST_ASSERT(actor.put_in_l_hand(pen), "the original unrelated pen occupies the actual left hand")
	var/original_material = armor.get_material()
	var/original_integrity = armor.get_integrity()
	add_trait(armor, TRAIT_NODROP, "interim_material_armor_shatter")
	TEST_ASSERT_NOTNULL(actor.release_refusal(armor), "the actual worn-source release requirement refuses sticky armor")
	TEST_ASSERT_NULL(armor.shatter(), "actual sticky shatter retains its implicit null return")
	TEST_ASSERT(!QDELETED(armor), "refused shatter preserves the exact sticky armor")
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_SUIT), armor, "refused shatter preserves the original real suit-slot occupant")
	TEST_ASSERT_EQUAL(armor.loc, actor, "refused shatter preserves actual wearer containment")
	TEST_ASSERT_EQUAL(armor.get_material(), original_material, "refused shatter preserves the exact original material")
	TEST_ASSERT_EQUAL(armor.get_integrity(), original_integrity, "refused shatter preserves the original integrity")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), pen, "refused shatter preserves the unrelated original hand item")
	remove_trait(armor, TRAIT_NODROP, "interim_material_armor_shatter")
	TEST_ASSERT_NULL(actor.release_refusal(armor), "removing the actual sticky trait clears the real release requirement")
	TEST_ASSERT_NULL(armor.shatter(), "accepted actual shatter retains its implicit null return")
	TEST_ASSERT(QDELETED(armor), "accepted actual shatter deletes the exact original worn armor")
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_SUIT), "accepted shatter clears the actual original suit slot")
	TEST_ASSERT(!QDELETED(actor), "accepted shatter preserves the actual original wearer")
	TEST_ASSERT(!QDELETED(pen), "accepted shatter preserves the original unrelated hand item")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), pen, "accepted shatter leaves the exact unrelated item in its original hand")
