/datum/unit_test/interim_contained_remains_cleanup/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/box/container = allocate(/obj/item/storage/box, T)
	var/obj/effect/decal/remains/human/remains = allocate(/obj/effect/decal/remains/human, T)
	remains.forceMove(container)
	TEST_ASSERT(!QDELETED(remains) && remains.loc == container, "The actual original remains genuinely occupy the real container")
	TEST_ASSERT_EQUAL(remains.crumble_into, /obj/effect/decal/cleanable/ash, "The actual human remains retain their canonical ash product")
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(actor.put_in_active_hand(pen), "The actual actor holds its original unrelated pen")
	var/list/before = turf_contents_of_type(T, /obj/effect/decal/cleanable/ash)
	TEST_ASSERT_EQUAL(remains.interaction_crumble_remains(actor, pen, null), TRUE, "Actual contained crumbling preserves its original handled result")
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(remains), "Actual contained crumbling consumes the exact original remains")
	var/list/products = turf_contents_of_type(T, /obj/effect/decal/cleanable/ash) - before
	TEST_ASSERT_EQUAL(length(products), 1, "Actual contained crumbling leaves exactly one canonical ash product on the original floor")
	var/obj/effect/decal/cleanable/ash/ash = products[1]
	TEST_ASSERT_EQUAL(ash.type, /obj/effect/decal/cleanable/ash, "Actual contained crumbling creates the exact canonical ash type")
	TEST_ASSERT(!QDELETED(ash) && ash.loc == T, "The actual original ash product survives on the floor rather than inside the container")
	TEST_ASSERT(!QDELETED(container) && container.loc == T, "Actual contained crumbling preserves its original real container")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), pen, "Actual contained crumbling preserves its original held unrelated pen")
	TEST_ASSERT(!QDELETED(actor) && !QDELETED(pen), "Actual cleanup preserves both original unrelated participants")
