/// Uses a real granted item action, actual HUD viewer records and flashlight state.
/datum/unit_test/interim_action_button_click_actor/Run()
	test_driver_begin()
	set_config(/datum/config_entry/flag/no_click_cooldown, FALSE)
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	var/datum/hud/other_hud = allocate(/datum/hud, bystander)
	hud.build_action_groups()
	other_hud.build_action_groups()
	var/obj/item/flashlight/light = allocate(/obj/item/flashlight, T)
	TEST_ASSERT(actor.put_in_active_hand(light), "the real action target is held by its actor")
	var/datum/action/item_action/toggle_flashlight/action = allocate(/datum/action/item_action/toggle_flashlight, light)
	action.Grant(actor)
	var/atom/movable/screen/movable/action_button/button = action.button_for(hud)
	TEST_ASSERT_NOTNULL(button, "the actual grant creates a real button for the actor HUD")
	TEST_ASSERT_EQUAL(button.linked_action(), action, "the actual HUD button links its granted action")
	TEST_ASSERT_NULL(action.button_for(other_hud), "the unrelated actual HUD has no viewer grant")
	TEST_ASSERT(!light.on, "the actual flashlight begins off")
	COOLDOWN_RESET(actor, next_click)
	COOLDOWN_RESET(bystander, next_click)
	button.click_with_actor(bystander, null, null, "left=1")
	TEST_ASSERT(!light.on, "an actor without a real viewer grant cannot trigger the item action")
	TEST_ASSERT_EQUAL(COOLDOWN_TIMELEFT(bystander, next_click), 0, "viewer refusal does not spend the unrelated actor cooldown")
	km_synthetic_click(actor, button)
	TEST_ASSERT(light.on, "the real item action turns the actual flashlight on")
	appearance_flush() // the draw runs on the presentation lane, not inside the click
	TEST_ASSERT_EQUAL(light.icon_state, "flashlight-on", "the actual action updates the target appearance")
	TEST_ASSERT(COOLDOWN_TIMELEFT(actor, next_click) > 0, "the accepted actor click starts its actual cooldown")
	button.click_with_actor(actor, null, null, "left=1")
	TEST_ASSERT(light.on, "a second click during the real cooldown cannot toggle the target off")
	COOLDOWN_RESET(actor, next_click)
	TEST_ASSERT_EQUAL(button.click_with_actor(actor, null, null, "left=1"), TRUE, "the real granted actor helper preserves its successful return")
	TEST_ASSERT(!light.on, "a later accepted real action toggles the actual target off")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), light, "the real actions preserve target item ownership")
	button.click_with_actor(null, null, null, "left=1")
	TEST_ASSERT(!light.on, "an absent actor cannot trigger the granted item action")
