/// Actual clientless storage viewers prove album actor attribution and photo retention.
/datum/unit_test/interim_photo_album_drop_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	var/atom/movable/screen/target = hud.l_hand_hud_object
	TEST_ASSERT_NOTNULL(target, "the real human HUD provides a screen target")
	var/obj/item/storage/photo_album/album = allocate(/obj/item/storage/photo_album, T)
	var/obj/item/photo/photo = allocate(/obj/item/photo, T)
	TEST_ASSERT(album.handle_item_insertion(photo, TRUE), "actual photo insertion succeeds through real storage")
	TEST_ASSERT_EQUAL(photo.loc, album, "the actual album physically contains its exact photo")
	TEST_ASSERT(photo in album.stored_items(), "the real storage ledger contains its photo")
	TEST_ASSERT(actor.put_in_r_hand(album), "the actual album is carried by the initiating actor")
	var/obj/item/storage/box/previous = allocate(/obj/item/storage/box, T)
	var/obj/item/storage/box/other_box = allocate(/obj/item/storage/box, T)
	previous.show_to(actor)
	other_box.show_to(bystander)
	TEST_ASSERT_EQUAL(actor.s_active, previous, "the real clientless actor begins viewing the actual prior box")
	TEST_ASSERT_EQUAL(bystander.s_active, other_box, "the unrelated actual actor views its own box")
	TEST_ASSERT_EQUAL(album.handle_album_drop(bystander, target), TRUE, "the original human screen branch remains consumed")
	TEST_ASSERT_EQUAL(bystander.s_active, other_box, "an actor not carrying the album retains its actual storage viewer")
	TEST_ASSERT_EQUAL(actor.s_active, previous, "unrelated actor routing cannot alter the actual owner viewer")
	TEST_ASSERT_EQUAL(album.handle_album_drop(actor, target), TRUE, "the actual carried album branch is native-consumed")
	TEST_ASSERT_EQUAL(actor.s_active, album, "the real album opens for its explicitly supplied actor")
	TEST_ASSERT_NOTNULL(album.hud, "actual storage creates its real clientless HUD")
	TEST_ASSERT(actor in album.is_seeing, "the actual album tracks its explicit viewer")
	TEST_ASSERT(!(actor in previous.is_seeing), "the previous real box closes for that exact actor")
	TEST_ASSERT_EQUAL(bystander.s_active, other_box, "actual opening leaves the unrelated actor's active storage unchanged")
	TEST_ASSERT(!(bystander in album.is_seeing), "actual opening never registers the unrelated actor")
	TEST_ASSERT_EQUAL(photo.loc, album, "opening preserves physical photo containment")
	TEST_ASSERT(photo in album.stored_items(), "opening preserves actual photo ledger identity")
	TEST_ASSERT_EQUAL(actor.get_right_hand(), album, "the non-back carried branch never transfers the real album hand")
	TEST_ASSERT_EQUAL(album.handle_album_drop(actor, previous), FALSE, "human non-screen drop selects unchanged native parent fallback")
	TEST_ASSERT_EQUAL(actor.s_active, album, "fallback selection itself does not close the actual album viewer")
	album.handle_album_drop(null, target)
	TEST_ASSERT_EQUAL(actor.s_active, album, "absent actor cannot change the actual viewer")
	album.close(actor)
	other_box.close(bystander)
	TEST_ASSERT_NULL(actor.s_active, "actual close releases the album viewer relation")
	TEST_ASSERT_NULL(bystander.s_active, "actual close releases the unrelated fixture viewer")
