/// Charge a physically inserted cell, respect loss of power, and stop after ejection.
/datum/unit_test/interim_cell_charger_roundtrip/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/cell_charger/charger = allocate(/obj/machinery/cell_charger, T)
	var/obj/item/cell/cell = allocate(/obj/item/cell, T)
	var/obj/item/cell/device/device = allocate(/obj/item/cell/device, T)
	cell.charge = 0
	charger.set_stat(0)
	TEST_ASSERT(istext(charger.can_insert_cell(actor, charger, device)), "the charger refuses an incompatible device cell")
	TEST_ASSERT_NULL(charger.charging, "checking the incompatible cell leaves the charger empty")
	TEST_ASSERT(actor.put_in_active_hand(cell), "the actor holds the cell to insert")
	TEST_ASSERT(charger.interaction_insert(actor, cell, null), "the actual insertion handler runs")
	TEST_ASSERT_EQUAL(charger.charging, cell, "the charger records the inserted cell")
	TEST_ASSERT_EQUAL(cell.loc, charger, "insertion physically places the cell inside the charger")
	TEST_ASSERT_NULL(actor.get_active_hand(), "insertion releases the actor's hand")
	TEST_ASSERT(istext(charger.can_insert_cell(actor, charger, cell)), "the occupied charger refuses a second insertion")
	om_stage_run_now(charger, /datum/om/stage/machine/power/cell_charger)
	var/first_charge = min(cell.maxcharge, charger.efficiency * CELLRATE)
	TEST_ASSERT(first_charge > 0, "the real charging rate is positive")
	TEST_ASSERT_EQUAL(cell.charge, first_charge, "the charging stage delivers its configured charge")
	TEST_ASSERT_EQUAL(charger.use_power, USE_POWER_ACTIVE, "charging selects active power draw")
	charger.set_stat(NOPOWER)
	om_stage_run_now(charger, /datum/om/stage/machine/power/cell_charger)
	TEST_ASSERT_EQUAL(cell.charge, first_charge, "loss of power prevents any additional charge")
	TEST_ASSERT_EQUAL(charger.use_power, USE_POWER_OFF, "an unpowered charger switches off")
	charger.set_stat(0)
	cell.charge = cell.maxcharge - 1
	om_stage_run_now(charger, /datum/om/stage/machine/power/cell_charger)
	TEST_ASSERT_EQUAL(cell.charge, cell.maxcharge, "charging saturates at cell capacity")
	om_stage_run_now(charger, /datum/om/stage/machine/power/cell_charger)
	TEST_ASSERT_EQUAL(charger.use_power, USE_POWER_IDLE, "a full cell leaves the charger idle")
	TEST_ASSERT(charger.interaction_take(actor, null, null), "the actual removal handler runs")
	TEST_ASSERT_NULL(charger.charging, "removal clears the charging reference")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), cell, "removal gives the real cell back to the actor")
	cell.charge = 0
	om_stage_run_now(charger, /datum/om/stage/machine/power/cell_charger)
	TEST_ASSERT_EQUAL(cell.charge, 0, "an ejected cell receives no further charge")

/// Player self-feeding delivers the configured dose to ingestion rather than the bloodstream.
/datum/unit_test/interim_standard_feed_dose/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/glass/beaker/source = allocate(/obj/item/reagent_containers/glass/beaker, T)
	var/obj/item/clothing/mask/gas/mask = allocate(/obj/item/clothing/mask/gas, T)
	source.amount_per_transfer_from_this = 7
	source.reagents.add_reagent(REAGENT_ID_WATER, 10)
	var/blood_before = actor.reagents.get_reagent_amount(REAGENT_ID_WATER)
	var/ingested_before = actor.ingested.get_reagent_amount(REAGENT_ID_WATER)
	TEST_ASSERT(mask.move_into(actor, SLOT_ID_MASK), "the actor wears a real mouth-covering mask")
	TEST_ASSERT_NOTNULL(mouth_blocked_reason(actor, actor), "the fixture actually blocks feeding")
	TEST_ASSERT(!source.standard_feed_mob(actor, actor), "feeding through the covering mask refuses")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 10, "the refusal leaves the source dose intact")
	TEST_ASSERT_EQUAL(actor.ingested.get_reagent_amount(REAGENT_ID_WATER), ingested_before, "the refusal delivers no swallowed water")
	actor.drop_from_inventory(mask)
	TEST_ASSERT_NULL(mouth_blocked_reason(actor, actor), "removing the mask opens the mouth")
	TEST_ASSERT(source.standard_feed_mob(actor, actor), "the actual self-feed helper handles a drink")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 3, "feeding debits the configured seven-unit dose")
	TEST_ASSERT_EQUAL(actor.ingested.get_reagent_amount(REAGENT_ID_WATER), ingested_before + 7, "the configured dose reaches ingestion")
	TEST_ASSERT_EQUAL(actor.reagents.get_reagent_amount(REAGENT_ID_WATER), blood_before, "feeding does not inject the dose into blood")
	TEST_ASSERT(source.standard_feed_mob(actor, actor), "a second drink handles the remaining partial dose")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 0, "the partial drink empties the source")
	TEST_ASSERT_EQUAL(actor.ingested.get_reagent_amount(REAGENT_ID_WATER), ingested_before + 10, "the full original dose is conserved across both drinks")
	TEST_ASSERT(source.standard_feed_mob(actor, actor), "an empty source is handled as a refusal")
	TEST_ASSERT_EQUAL(actor.ingested.get_reagent_amount(REAGENT_ID_WATER), ingested_before + 10, "the empty refusal delivers no additional water")
