/// Real held inventory item movement exercises existing actor ownership and slot guards.
/datum/unit_test/interim_flashlight_drop_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	hud.build_action_groups()
	TEST_ASSERT_NOTNULL(hud.listed_actions, "the real clientless HUD initializes its listed action group")
	TEST_ASSERT_NOTNULL(hud.palette_actions, "the real clientless HUD initializes its palette action group")
	var/atom/movable/screen/right = hud.r_hand_hud_object
	var/atom/movable/screen/left = hud.l_hand_hud_object
	TEST_ASSERT_NOTNULL(right, "the actual HUD provides its right hand target")
	TEST_ASSERT_NOTNULL(left, "the actual HUD provides its left hand target")
	var/obj/item/flashlight/tool = allocate(/obj/item/flashlight, T)
	var/obj/item/blocker = allocate(/obj/item, T)
	var/obj/item/cell/cell = tool.get_cell()
	TEST_ASSERT_NOTNULL(cell, "the actual flashlight contains its real power cell")
	var/initial_charge = cell.charge
	var/initial_force = tool.force
	TEST_ASSERT_EQUAL(tool.on, FALSE, "the actual flashlight begins inactive")
	TEST_ASSERT(actor.put_in_r_hand(tool), "the real tool begins held by its actual actor")
	TEST_ASSERT_EQUAL(tool.loc, actor, "actual tool location satisfies the original owner guard")
	set_var(tool, nameof(tool.canremove), FALSE)
	TEST_ASSERT_EQUAL(tool.handle_inventory_drop(actor, blocker), TRUE, "a nonremovable real tool retains the earlier consumed guard even for a non-screen target")
	TEST_ASSERT_EQUAL(actor.get_right_hand(), tool, "the actual removal lock preserves the real tool slot")
	set_var(tool, nameof(tool.canremove), TRUE)
	tool.handle_inventory_drop(bystander, left)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), tool, "an unrelated explicit actor cannot take the real held tool")
	TEST_ASSERT(!bystander.item_is_in_hands(tool), "ownership refusal never grants the bystander a held tool")
	actor.set_stat(UNCONSCIOUS)
	TEST_ASSERT_EQUAL(actor.stat, UNCONSCIOUS, "the actual source stat guard is enabled")
	tool.handle_inventory_drop(actor, left)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), tool, "the actual stat guard prevents hand movement")
	actor.set_stat(CONSCIOUS)
	TEST_ASSERT(actor.put_in_l_hand(blocker), "an actual unrelated item occupies the destination hand")
	tool.handle_inventory_drop(actor, left)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), tool, "occupied hand refusal preserves the original real tool slot")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), blocker, "occupied hand refusal never drops its unrelated held item")
	TEST_ASSERT(actor.unEquip(blocker), "actual inventory removal makes the target hand available")
	TEST_ASSERT_EQUAL(tool.handle_inventory_drop(actor, left), TRUE, "a real hand target remains native-consumed")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), tool, "the explicit actor moves the actual tool to its left slot")
	TEST_ASSERT_NULL(actor.get_right_hand(), "the successful transfer clears the real former slot")
	TEST_ASSERT_EQUAL(tool.handle_inventory_drop(actor, blocker), FALSE, "the human non-screen target retains native parent routing")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), tool, "parent branch selection does not perform a screen hand transfer")
	tool.handle_inventory_drop(null, right)
	TEST_ASSERT_EQUAL(actor.get_left_hand(), tool, "an absent actor leaves the actual held tool unchanged")
	tool.handle_inventory_drop(actor, right)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), tool, "actual roundtrip restores the original hand slot")
	TEST_ASSERT_NULL(actor.get_left_hand(), "actual roundtrip clears the temporary slot")
	TEST_ASSERT_EQUAL(tool.get_cell(), cell, "inventory routing preserves the exact flashlight power cell")
	TEST_ASSERT_EQUAL(cell.loc, tool, "the actual flashlight cell remains physically contained")
	TEST_ASSERT_EQUAL(cell.charge, initial_charge, "inventory routing never spends actual flashlight charge")
	TEST_ASSERT_EQUAL(tool.force, initial_force, "inventory routing preserves flashlight force")

	TEST_ASSERT_EQUAL(tool.on, FALSE, "hand routing does not activate the real flashlight")
