/// The real girder's reinforcing mode spends one actual sheet only after its timed material interaction finishes.
/datum/unit_test/om/interim_girder_reinforcement_dose/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/girder/girder = allocate(/obj/structure/girder, T)
	var/obj/item/stack/material/steel/sheets = allocate(/obj/item/stack/material/steel, T, 2)
	made += list(user, girder, sheets)
	var/datum/material/steel = get_material_by_name(MAT_STEEL)
	var/integrity_before = girder.max_integrity
	TEST_ASSERT(girder.anchored && !girder.reinf_material, "the real girder starts anchored without reinforcement")
	TEST_ASSERT(interim_construction_step(girder, user, "reinforcing_toggled"), "the real construction edge selects reinforcing mode")
	TEST_ASSERT(girder.reinforcing, "the real girder now selects reinforcement rather than wall plating")
	TEST_ASSERT(user.put_in_active_hand(sheets), "the actual actor holds the real steel sheets")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the fresh actual actor is capable of reinforcing")
	test_op_handler(girder, "interaction_item", user, sheets)
	TEST_ASSERT(test_actor_busy(user), "the real material interaction starts a timed reinforcing action")
	TEST_ASSERT_NULL(girder.reinf_material, "starting reinforcement does not add material early")
	TEST_ASSERT_EQUAL(girder.max_integrity, integrity_before, "starting reinforcement does not add integrity early")
	TEST_ASSERT_EQUAL(sheets.get_amount(), 2, "starting reinforcement does not consume a sheet early")
	scheduler_advance((5 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual actor remains capable after its single reinforcing action")
	TEST_ASSERT(!test_actor_busy(user), "actual reinforcement releases its pending action")
	TEST_ASSERT_EQUAL(girder.reinf_material, steel, "the completed real action installs the actual steel reinforcement")
	TEST_ASSERT_EQUAL(sheets.get_amount(), 1, "completed real reinforcement consumes exactly one steel sheet")
	TEST_ASSERT_EQUAL(girder.state, 2, "completed real reinforcement advances the girder's actual state")
	TEST_ASSERT_EQUAL(girder.max_integrity, integrity_before + round(steel.integrity / 2), "completed reinforcement adds the actual steel integrity allowance")
	TEST_ASSERT_EQUAL(girder.cover, steel.hardness, "completed reinforcement derives cover from the actual steel hardness")
	TEST_ASSERT_EQUAL(user.get_active_hand(), sheets, "completed reinforcement leaves the actual remaining sheet held")
