/// A real windoor's declared emag opens through its actual delayed animation and leaves the mechanism disabled, while unpowered/open refusals spend no card uses.
/datum/unit_test/om/interim_windoor_emag_disabled_open/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/door/window/door = allocate(/obj/machinery/door/window, T)
	var/obj/item/card/emag/card = allocate(/obj/item/card/emag, T)
	made += list(user, door, card)
	card.uses = 3
	TEST_ASSERT(user.put_in_active_hand(card), "the actual windoor actor holds a real charged emag")
	var/datum/interaction/emag_entry
	for(var/datum/interaction/candidate as anything in interaction_candidates(door))
		if(candidate.id == "emag")
			emag_entry = candidate
			break
	TEST_ASSERT_NOTNULL(emag_entry, "the actual windoor exposes its inherited declared emag interaction")
	TEST_ASSERT_NOTNULL(SSticker, "the actual windoor animation has the real round service required by open")
	door.set_stat(NOPOWER)
	var/timers_before = om_timer_count(door)
	emag_entry.perform(user, door, card)
	TEST_ASSERT_EQUAL(card.uses, 3, "the actual unpowered windoor refuses without spending a card use")
	TEST_ASSERT(door.density && !door.operating, "actual unpowered refusal preserves the closed idle windoor")
	TEST_ASSERT_EQUAL(om_timer_count(door), timers_before, "actual unpowered refusal schedules no animation")
	door.set_stat(0)
	TEST_ASSERT(emag_entry.perform(user, door, card), "the actual powered windoor runs its real declared emag")
	TEST_ASSERT_EQUAL(card.uses, 2, "actual accepted windoor emag spends exactly one card use")
	TEST_ASSERT_EQUAL(door.operating, -1, "actual accepted windoor emag immediately disables its mechanism")
	TEST_ASSERT(door.density, "the actual accepted windoor remains closed before its animation delay")
	TEST_ASSERT_EQUAL(om_timer_count(door), timers_before + 1, "actual accepted windoor schedules one delayed opening")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!door.density, "the actual delayed windoor animation opens the passage")
	TEST_ASSERT_EQUAL(door.operating, -1, "the actual opening animation preserves the disabled mechanism")
	TEST_ASSERT_EQUAL(door.explosion_resistance, 0, "the actual opened windoor removes its closed explosion barrier")
	TEST_ASSERT(!door.close(), "the actual disabled windoor cannot close through its public mechanism")
	TEST_ASSERT(!door.density, "actual refused closing preserves the open passage")
	var/open_timers = om_timer_count(door)
	emag_entry.perform(user, door, card)
	TEST_ASSERT_EQUAL(card.uses, 2, "actual repeated emag on the open windoor spends no additional card use")
	TEST_ASSERT_EQUAL(om_timer_count(door), open_timers, "actual repeated emag on the open windoor schedules no animation")
	TEST_ASSERT_EQUAL(user.get_active_hand(), card, "the actual complete interaction preserves the actor's remaining charged card")
