/// A real photocopier refill must consume its original cartridge before gaining toner.
/datum/unit_test/interim_photocopier_sticky_toner/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/photocopier/machine = allocate(/obj/machinery/photocopier, T)
	var/obj/item/toner/cartridge = allocate(/obj/item/toner, T)
	TEST_ASSERT_EQUAL(machine.toner, initial(machine.toner), "the actual machine starts with its declared toner supply")
	TEST_ASSERT(cartridge.toner_amount > 0, "the actual original cartridge has a positive declared refill")
	var/refill_amount = cartridge.toner_amount
	machine.toner = 10
	TEST_ASSERT(user.put_in_active_hand(cartridge), "the actor holds the exact original toner cartridge")
	add_trait(cartridge, TRAIT_NODROP, "interim_photocopier_sticky")
	TEST_ASSERT(user.release_refusal(cartridge, user), "actual inventory refuses cartridge consumption")
	test_op_handler(machine, "interaction_insert_toner", user, cartridge)
	TEST_ASSERT_EQUAL(machine.toner, 10, "refused consumption grants no toner")
	TEST_ASSERT(!QDELETED(cartridge), "refused refill preserves the original cartridge")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cartridge, "refused refill preserves the original hand")
	TEST_ASSERT_EQUAL(cartridge.loc, user, "refused refill preserves actual inventory containment")
	remove_trait(cartridge, TRAIT_NODROP, "interim_photocopier_sticky")
	test_op_handler(machine, "interaction_insert_toner", user, cartridge)
	TEST_ASSERT(QDELETED(cartridge), "allowed refill consumes the exact original cartridge")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears the actual source hand")
	TEST_ASSERT_EQUAL(machine.toner, 10 + refill_amount, "one consumed cartridge grants exactly its actual toner supply")
	var/obj/item/toner/replacement = allocate(/obj/item/toner, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds a real second cartridge")
	test_op_handler(machine, "interaction_insert_toner", user, replacement)
	TEST_ASSERT_EQUAL(machine.toner, 10 + refill_amount, "a machine above its refill threshold gains no extra toner")
	TEST_ASSERT(!QDELETED(replacement), "threshold refusal preserves the original replacement cartridge")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "threshold refusal preserves the original replacement hand")
