/datum/unit_test/om/interim_fulton_landing_release/run_om(list/made)
	var/turf/T = test_floor()
	var/obj/effect/extraction_holder/holder = allocate(/obj/effect/extraction_holder, T)
	var/obj/item/storage/box/cargo = allocate(/obj/item/storage/box, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	made += list(holder, cargo, pen)
	cargo.forceMove(holder)
	cargo.set_anchored(TRUE)
	cargo.set_density(FALSE)
	TEST_ASSERT_EQUAL(cargo.loc, holder, "The actual original cargo is contained in its real extraction holder")
	holder.fulton_land(cargo)
	TEST_ASSERT(!cargo.anchored, "The actual landing phase restores the original cargo's movable state")
	TEST_ASSERT_EQUAL(cargo.density, initial(cargo.density), "Actual landing restores the original cargo's declared density")
	TEST_ASSERT_EQUAL(cargo.loc, holder, "Actual landing retains original containment until the release deadline")
	scheduler_advance((0.4 SECONDS) / (1 SECOND))
	TEST_ASSERT(!QDELETED(holder) && holder.loc == T, "The actual original extraction holder survives before its half-second release deadline")
	TEST_ASSERT_EQUAL(cargo.loc, holder, "The actual original cargo remains contained before release")
	scheduler_advance((0.2 SECONDS) / (1 SECOND))
	TEST_ASSERT(QDELETED(holder), "The actual owned landing timer consumes the exact original extraction holder")
	TEST_ASSERT(!QDELETED(cargo) && cargo.loc == T, "Actual timed release recovers the exact original cargo on the original landing floor")
	TEST_ASSERT(!cargo.anchored, "Actual timed release preserves the cargo's restored movable state")
	TEST_ASSERT_EQUAL(cargo.density, initial(cargo.density), "Actual timed release preserves the cargo's restored declared density")
	TEST_ASSERT(!QDELETED(pen) && pen.loc == T, "Actual landing release preserves the unrelated original floor item")
