/// Repair and reset safety gates depend on the real cell bay, without removing its occupant on refusal.
/datum/unit_test/interim_apc_cell_safety_gates/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/power/apc/dx_test/apc = dx_apc_make(T)
	var/obj/item/cell/C = apc.cell
	TEST_ASSERT_NOTNULL(C, "the APC starts with an installed cell")
	TEST_ASSERT(!apc.cell_out(user, null), "installed cells block unfastening electronics")
	TEST_ASSERT(istext(apc.cell_out_for_reset(user, null)), "installed cells block the reset procedure")
	TEST_ASSERT(istext(apc.cover_replaceable(user, null)), "an intact cover cannot be replaced")
	apc.stat_add(BROKEN)
	TEST_ASSERT(istext(apc.cover_replaceable(user, null)), "a broken APC still requires its cell removed before cover replacement")
	TEST_ASSERT_EQUAL(apc.cell, C, "safety refusals preserve the installed cell reference")
	TEST_ASSERT_EQUAL(C.loc, apc, "safety refusals preserve the cell's physical location")
	TEST_ASSERT_EQUAL(C.charge, C.maxcharge, "safety refusals do not consume cell charge")
	own_take(apc, nameof(apc.cell))
	TEST_ASSERT(C.move_into(T), "the cell can be physically removed after releasing its owner")
	TEST_ASSERT(apc.cell_out(user, null), "empty bays permit the electronics step")
	TEST_ASSERT_EQUAL(apc.cell_out_for_reset(user, null), TRUE, "empty bays permit resetting")
	TEST_ASSERT_EQUAL(apc.cover_replaceable(user, null), TRUE, "a broken APC with an empty bay permits cover replacement")
	apc.stat_remove(BROKEN)
	TEST_ASSERT(istext(apc.cover_replaceable(user, null)), "an empty bay does not make an intact cover replaceable")
	apc.stat_add(MAINT)
	TEST_ASSERT(istext(apc.cell_bay_ready(user, C)), "unsecured electronics refuse cell insertion")
	apc.stat_remove(MAINT)
	TEST_ASSERT_EQUAL(apc.cell_bay_ready(user, C), TRUE, "secured electronics allow cell insertion")
