/// Installing the actual held kit consumes its hand item and creates one floor structure at the actor's turf.
/datum/unit_test/interim_floor_light_install/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/floor_light/kit = allocate(/obj/item/floor_light, T)
	TEST_ASSERT(user.put_in_active_hand(kit), "the actual floor light kit is held")
	test_click(user, kit, kit, GESTURE_SELF)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(kit), "installation consumes the actual kit")
	TEST_ASSERT_NULL(user.get_active_hand(), "installation correctly vacates the original kit's hand")
	var/obj/machinery/floor_light/light = locate_within(T, /obj/machinery/floor_light)
	TEST_ASSERT(light, "installation creates the actual floor light at the original actor's turf")
	TEST_ASSERT_EQUAL(light.loc, T, "installation keeps the structure on the floor")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/floor_light)), 1, "installation creates exactly one floor light")
	TEST_ASSERT_NULL(locate_within(user, /obj/machinery/floor_light), "installation puts no structure into the actor's inventory")

/// A sticky floor light kit refuses installation before either a floor structure or hand mutation occurs.
/datum/unit_test/interim_floor_light_install_refusal/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/floor_light/kit = allocate(/obj/item/floor_light, T)
	TEST_ASSERT(user.put_in_active_hand(kit), "the actual floor light kit is held")
	add_trait(kit, TRAIT_NODROP, "interim_floor_light_install")
	TEST_ASSERT(kit.loc.release_refusal(kit, user), "the actual sticky kit refuses release")
	TEST_ASSERT(kit.can_install(user, kit, kit) != TRUE, "the installation requirement rejects the actual sticky kit")
	test_click(user, kit, kit, GESTURE_SELF)
	own_turf_contents(T)
	TEST_ASSERT(!QDELETED(kit), "refusal preserves the actual kit")
	TEST_ASSERT_EQUAL(user.get_active_hand(), kit, "refusal preserves the kit's actual hand")
	TEST_ASSERT_EQUAL(kit.loc, user, "refusal preserves the kit on its original holder")
	TEST_ASSERT_NULL(locate_within(T, /obj/machinery/floor_light), "refusal creates no floor structure")
	TEST_ASSERT_NULL(locate_within(user, /obj/machinery/floor_light), "refusal creates no inventory structure")
	remove_trait(kit, TRAIT_NODROP, "interim_floor_light_install")
