/// Real slug slime registration and buckle cleanup use the public wash endpoint.
/datum/unit_test/interim_slug_glue_wash_cleanup/Run()
	var/turf/T = run_loc_floor_bottom_left
	TEST_ASSERT_NULL(locate_on(T, /obj/effect/slug_glue), "the actual source floor starts without existing slug glue")
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(actor.put_in_l_hand(pen), "the actor holds the original unrelated pen")
	var/mob/living/simple_mob/vore/slug/slug = allocate(/mob/living/simple_mob/vore/slug, T)
	slug.spread_slime()
	var/obj/effect/slug_glue/glue = locate_on(T, /obj/effect/slug_glue)
	TEST_ASSERT_NOTNULL(glue, "actual public slug spreading creates a real glue effect")
	own(glue)
	TEST_ASSERT_EQUAL(glue.owner_slug, slug, "the real created glue retains its original slug relation")
	TEST_ASSERT_EQUAL(glue.my_turf, T, "the real glue constructor records its original floor")
	TEST_ASSERT_EQUAL(slug.slime_count, 1, "the real slug registers exactly one glue effect")
	slug.spread_slime()
	TEST_ASSERT_EQUAL(locate_on(T, /obj/effect/slug_glue), glue, "actual duplicate spreading preserves the original effect identity")
	TEST_ASSERT_EQUAL(slug.slime_count, 1, "actual duplicate spreading does not add another owner registration")
	TEST_ASSERT(glue.buckle_mob(actor), "the real glue buckles the actual actor through the public restraint API")
	TEST_ASSERT_EQUAL(actor.buckled_to(), glue, "the actual actor's restraint relation references the exact original glue")
	TEST_ASSERT(glue.has_buckled_mobs(), "the real glue records its actual restrained occupant")
	glue.germ_level = 7
	TEST_ASSERT(!glue.wash(CLEAN_RAD), "real radiation-only cleaning does not satisfy the existing scrub mask")
	TEST_ASSERT(!QDELETED(glue), "unsupported cleaning preserves the exact original glue")
	TEST_ASSERT_EQUAL(glue.germ_level, 0, "unsupported cleaning still runs the original parent wash consequences")
	TEST_ASSERT_EQUAL(glue.owner_slug, slug, "unsupported cleaning preserves the original owner relation")
	TEST_ASSERT_EQUAL(slug.slime_count, 1, "unsupported cleaning preserves the exact owner registration count")
	TEST_ASSERT_EQUAL(actor.buckled_to(), glue, "unsupported cleaning preserves the original actual restraint")
	TEST_ASSERT(glue.wash(CLEAN_SCRUB), "actual successful scrub reports real glue consumption")
	TEST_ASSERT(QDELETED(glue), "successful actual scrub deletes the exact original glue")
	TEST_ASSERT_EQUAL(slug.slime_count, 0, "unchanged glue teardown removes the exact original owner registration")
	TEST_ASSERT_NULL(actor.buckled_to(), "unchanged inherited relation cleanup releases the real actor")
	TEST_ASSERT(!QDELETED(actor), "successful scrub preserves the actual original actor")
	TEST_ASSERT(!QDELETED(slug), "successful scrub preserves the actual original slug")
	TEST_ASSERT_EQUAL(actor.loc, T, "actual release preserves the original actor floor")
	TEST_ASSERT_EQUAL(slug.loc, T, "successful scrub preserves the original slug floor")
	TEST_ASSERT(!QDELETED(pen), "successful scrub preserves the original unrelated held pen")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), pen, "actual restraint cleanup preserves the exact unrelated hand item")
	TEST_ASSERT_NULL(locate_on(T, /obj/effect/slug_glue), "successful scrub leaves no residual glue on the original floor")
