/// These controls invoke the real selected mob's resistance without ownership substitution.
/datum/unit_test/interim_restrained_alert_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/mob/unsupported = allocate(/mob, T)
	var/obj/structure/bed/roller/bed = allocate(/obj/structure/bed/roller, T)
	var/obj/structure/bed/roller/other_bed = allocate(/obj/structure/bed/roller, T)
	TEST_ASSERT(bed.buckle_mob(actor, forced = TRUE), "the real bed buckles the selected actor")
	TEST_ASSERT(other_bed.buckle_mob(bystander, forced = TRUE), "the real second bed buckles the unrelated mob")
	var/atom/movable/screen/alert/restrained/buckled/alert = allocate(/atom/movable/screen/alert/restrained/buckled)
	alert.click_with_actor(null)
	alert.click_with_actor(unsupported)
	TEST_ASSERT_EQUAL(actor.buckled_to(), bed, "unsupported and absent actors do not release the selected actor")
	km_synthetic_click(actor, alert)
	TEST_ASSERT_NULL(actor.buckled_to(), "the actual native restrained alert invokes the actor's real unbuckling resistance")
	TEST_ASSERT(!bed.has_buckled_mobs(), "the actual actor bed removes its occupant")
	TEST_ASSERT_EQUAL(bystander.buckled_to(), other_bed, "the unrelated nearby mob remains buckled to its original bed")
	TEST_ASSERT(other_bed.has_buckled_mobs(), "the unrelated bed retains its actual occupant")

/datum/unit_test/interim_fire_alert_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/atom/movable/screen/alert/fire/alert = allocate(/atom/movable/screen/alert/fire)
	actor.adjust_fire_stacks(2.4)
	bystander.adjust_fire_stacks(2.4)
	TEST_ASSERT(actor.ignite_mob(TRUE), "the actual actor's fire status ignites")
	TEST_ASSERT(bystander.ignite_mob(TRUE), "the unrelated mob's actual fire status ignites")
	TEST_ASSERT(actor.on_fire && bystander.on_fire, "both real fire statuses are burning before the click")
	var/actor_stacks = actor.fire_stacks
	var/other_stacks = bystander.fire_stacks
	alert.click_with_actor(null)
	TEST_ASSERT_EQUAL(actor.fire_stacks, actor_stacks, "an absent actor cannot resist the selected mob's fire")
	km_synthetic_click(actor, alert)
	TEST_ASSERT(abs(actor.fire_stacks - (actor_stacks - 1.2)) < 0.001, "the native alert invokes the actual selected carbon's fire resistance amount")
	TEST_ASSERT(actor.has_status(STAT_WEAKENED), "the actual selected actor enters stop-drop-roll weakness")
	TEST_ASSERT_EQUAL(bystander.fire_stacks, other_stacks, "the unrelated mob's fire stacks are preserved")
	TEST_ASSERT(!bystander.has_status(STAT_WEAKENED), "the unrelated mob never enters the actor's stop-drop-roll state")
