/// The real stock console starts with its declared cargo account and logout isolates that console.
/datum/unit_test/interim_stock_account_data/Run()
	var/obj/machinery/computer/stockexchange/console = allocate(/obj/machinery/computer/stockexchange)
	var/obj/machinery/computer/stockexchange/other = allocate(/obj/machinery/computer/stockexchange)
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	TEST_ASSERT(!QDELETED(console) && !QDELETED(other), "actual stock consoles survive parent initialization")
	TEST_ASSERT_EQUAL(console.logged_in, "Cargo Department", "actual stock console starts with its declared cargo account")
	TEST_ASSERT_EQUAL(other.logged_in, "Cargo Department", "each actual stock console independently starts logged in")
	TEST_ASSERT_EQUAL(console.balance(), GLOB.supply_service.budget_balance(), "logged-in console exposes the real supply budget")
	console.ui_act_logout(user, list(), null, null, "logout")
	TEST_ASSERT(isnull(console.logged_in), "actual logout clears the account")
	TEST_ASSERT_EQUAL(console.balance(), 0, "actual logged-out console exposes no spending balance")
	TEST_ASSERT_EQUAL(other.logged_in, "Cargo Department", "logging out one console preserves the other console account")
	TEST_ASSERT_EQUAL(other.balance(), GLOB.supply_service.budget_balance(), "other console keeps its real supply budget access")
