/// A real cell mode swap must consume its original and preserve actual charge fraction.
/datum/unit_test/interim_alien_cell_sticky_mode_swap/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/cell/device/weapon/recharge/alien/cell = allocate(/obj/item/cell/device/weapon/recharge/alien, T)
	TEST_ASSERT_EQUAL(cell.swaps_to, /obj/item/cell/void, "the actual cell declares its real reciprocal replacement type")
	TEST_ASSERT(cell.maxcharge > 0, "the original actual cell has positive capacity")
	cell.charge = cell.maxcharge / 4
	cell.persist_storable = FALSE
	var/original_charge = cell.charge
	var/floor_items_before = length(contents_of(T, /obj/item))
	TEST_ASSERT(user.put_in_active_hand(cell), "the actor holds the exact original cell")
	add_trait(cell, TRAIT_NODROP, "interim_alien_cell_sticky")
	TEST_ASSERT(user.release_refusal(cell, user), "actual inventory refuses sticky original cell consumption")
	test_click(user, cell, cell, GESTURE_SELF)
	TEST_ASSERT(!QDELETED(cell), "refused mode swap preserves exact original cell")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cell, "refused mode swap preserves original source hand")
	TEST_ASSERT_EQUAL(cell.loc, user, "refused mode swap preserves inventory containment")
	TEST_ASSERT_EQUAL(cell.charge, original_charge, "refused mode swap preserves original actual charge")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item)), floor_items_before - 1, "refused mode swap creates no floor replacement")
	remove_trait(cell, TRAIT_NODROP, "interim_alien_cell_sticky")
	test_click(user, cell, cell, GESTURE_SELF)
	TEST_ASSERT(QDELETED(cell), "allowed mode swap consumes exact original cell")
	var/obj/item/cell/void/replacement = user.get_active_hand()
	TEST_ASSERT(istype(replacement, /obj/item/cell/void), "allowed mode swap returns its actual reciprocal cell type")
	own(replacement)
	TEST_ASSERT_EQUAL(replacement.loc, user, "actual replacement physically occupies actor inventory")
	TEST_ASSERT_EQUAL(replacement.charge, replacement.maxcharge / 4, "allowed mode swap conserves the exact original quarter-charge fraction")
	TEST_ASSERT_EQUAL(replacement.persist_storable, FALSE, "allowed mode swap preserves original persistence policy")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item)), floor_items_before - 1, "allowed mode swap creates no extra floor cell")
