/// Real book insertion followed by dismantling spills the books and returns three wood sheets.
/datum/unit_test/interim_bookcase_dismantle_lifecycle/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/bookcase/shelf = allocate(/obj/structure/bookcase, T)
	var/list/books = list()
	for(var/i in 1 to 2)
		var/obj/item/book/book = allocate(/obj/item/book, T)
		TEST_ASSERT(user.put_in_active_hand(book), "the actual book starts held for insertion")
		test_op_handler(shelf, "shelve_book", user, book)
		TEST_ASSERT_EQUAL(book.loc, shelf, "actual insertion puts the book inside the shelf")
		TEST_ASSERT_NULL(user.get_active_hand(), "actual insertion vacates the book's hand slot")
		books += book
	TEST_ASSERT_EQUAL(contents_count(shelf), 2, "the real shelf contains both inserted books before dismantling")
	TEST_ASSERT_EQUAL(shelf.screwdriver_act_tool_done(user), ITEM_INTERACT_SUCCESS, "actual dismantling completion reports success")
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(shelf), "actual dismantling immediately consumes the original shelf")
	for(var/obj/item/book/book as anything in books)
		TEST_ASSERT(!QDELETED(book), "each actual inserted book survives dismantling")
		TEST_ASSERT_EQUAL(book.loc, T, "each actual inserted book spills onto the original floor")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/book)), 2, "dismantling preserves exactly both original books")
	var/obj/item/stack/material/wood/wood = locate_within(T, /obj/item/stack/material/wood)
	TEST_ASSERT(wood, "actual dismantling creates a wood stack on the original floor")
	TEST_ASSERT_EQUAL(wood.get_amount(), 3, "actual dismantling returns exactly three wood sheets")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/wood)), 1, "actual dismantling creates only one returned wood stack")
	TEST_ASSERT_NULL(locate_within(T, /obj/structure/bookcase), "dismantling leaves no duplicate shelf")
