/// Actual lamp shade installation must consume its original before enabling a refundable shade.
/datum/unit_test/interim_floor_lamp_sticky_shade/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/light/flamp/noshade/lamp = allocate(/obj/machinery/light/flamp/noshade, T)
	var/obj/item/lampshade/shade = allocate(/obj/item/lampshade, T)
	TEST_ASSERT(lamp.no_shade(user, lamp, shade), "actual bare lamp initialization accepts shade installation")
	TEST_ASSERT(user.put_in_active_hand(shade), "the actor holds the exact original shade")
	add_trait(shade, TRAIT_NODROP, "interim_floor_lamp_shade")
	TEST_ASSERT(user.release_refusal(shade, user), "actual inventory refuses sticky shade consumption")
	lamp.interaction_add_shade(user, shade, null)
	TEST_ASSERT_EQUAL(lamp.lamp_shade, 0, "refused consumption grants no installed shade")
	TEST_ASSERT(!QDELETED(shade), "refused installation preserves original shade")
	TEST_ASSERT_EQUAL(user.get_active_hand(), shade, "refused installation preserves exact original hand")
	TEST_ASSERT_EQUAL(shade.loc, user, "refused installation preserves inventory containment")
	remove_trait(shade, TRAIT_NODROP, "interim_floor_lamp_shade")
	lamp.interaction_add_shade(user, shade, null)
	TEST_ASSERT(QDELETED(shade), "allowed installation consumes exact original shade")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(lamp.lamp_shade, 1, "one consumed original grants actual installed shade state")
	var/obj/item/tool/screwdriver/tool = allocate(/obj/item/tool/screwdriver, T)
	TEST_ASSERT(user.put_in_active_hand(tool), "the actor holds an actual screwdriver for shade removal")
	var/refunds_before = length(contents_of(T, /obj/item/lampshade))
	lamp.screwdriver_act(user, tool)
	TEST_ASSERT_EQUAL(lamp.lamp_shade, FALSE, "actual screwdriver removal clears installed shade state")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/lampshade)), refunds_before + 1, "actual screwdriver removal refunds exactly one physical shade")
	var/obj/item/lampshade/refund = locate_within(T, /obj/item/lampshade)
	TEST_ASSERT_NOTNULL(refund, "actual removal creates a real surviving shade refund")
	own(refund)
	TEST_ASSERT(!QDELETED(refund) && refund != shade, "the refund is a real replacement for the consumed original")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "actual removal preserves the actor's original screwdriver")
