/// Construction uses real held source slots, owned edge blankets and the actual fold-back path.
/datum/unit_test/interim_picnic_blanket_roundtrip/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/picnic_blankets_carried/carried = allocate(/obj/item/picnic_blankets_carried, T)
	carried.name = "Fixture blanket"
	carried.unfolded_desc = "Fixture unfolded blanket"
	TEST_ASSERT(user.put_in_active_hand(carried), "the folded blanket occupies a real hand slot")
	test_op_handler(carried, "picnic_blankets_carried_fold_out_effect", user)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(carried), "the actual fold-out consumes the carried blanket")
	TEST_ASSERT_NULL(user.get_active_hand(), "unfolding vacates the actual source hand")
	var/obj/structure/picnic_blanket_deployed/deployed = locate_within(T, /obj/structure/picnic_blanket_deployed)
	TEST_ASSERT(deployed, "unfolding creates the actual floor structure")
	TEST_ASSERT_EQUAL(deployed.loc, T, "the blanket structure remains on the floor")
	TEST_ASSERT_EQUAL(deployed.name, "Fixture blanket", "unfolding preserves the customized name")
	TEST_ASSERT_EQUAL(deployed.desc, "Fixture unfolded blanket", "unfolding uses the customized unfolded description")
	TEST_ASSERT(length(deployed.attached_blankets), "the actual unfold expands into available neighboring tiles")
	var/list/edges = deployed.attached_blankets.Copy()
	for(var/obj/structure/picnic_blanket_deployed/edge in edges)
		TEST_ASSERT(isturf(edge.loc), "each actual edge remains on a floor tile")
		TEST_ASSERT_EQUAL(edge.name, deployed.name, "edges inherit the configured blanket name")
	test_op_handler(deployed, "picnic_blanket_deployed_fold_up_effect", user)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(deployed), "folding back consumes the actual center structure")
	for(var/obj/structure/picnic_blanket_deployed/edge in edges)
		TEST_ASSERT(QDELETED(edge), "folding back deletes every actual edge")
	var/obj/item/picnic_blankets_carried/refolded = locate_within(T, /obj/item/picnic_blankets_carried)
	TEST_ASSERT(refolded, "the actual fold-back creates a carried blanket")
	TEST_ASSERT_EQUAL(refolded.name, "Fixture blanket", "the construction round-trip retains the customized name")
	TEST_ASSERT_EQUAL(refolded.loc, T, "the folded product stays on the floor")
	TEST_ASSERT_NULL(user.get_active_hand(), "fold-back cannot equip a structure or unrelated product")

/datum/unit_test/interim_picnic_blanket_refused_release/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/picnic_blankets_carried/carried = allocate(/obj/item/picnic_blankets_carried, T)
	TEST_ASSERT(user.put_in_active_hand(carried), "the refused blanket starts in a real hand")
	var/obj/item/pen/other = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_inactive_hand(other), "the other hand contains an independent item")
	var/datum/dq_containment_listener/refusal = allocate(/datum/dq_containment_listener)
	refusal.watch(user)
	refusal.block_remove = TRUE
	TEST_ASSERT(!test_op_handler(carried, "can_unfold", user), "the requirement rejects real source release refusal")
	test_op_handler(carried, "picnic_blankets_carried_fold_out_effect", user)
	own_turf_contents(T)
	TEST_ASSERT(!QDELETED(carried), "refusal preserves the original folded blanket")
	TEST_ASSERT_EQUAL(user.get_active_hand(), carried, "refusal retains the original source slot")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), other, "refusal does not drop the independent held item")
	TEST_ASSERT_NULL(locate_within(T, /obj/structure/picnic_blanket_deployed), "refusal allocates no center structure")
	for(var/direction in GLOB.alldirs)
		var/turf/neighbor = get_step(T, direction)
		TEST_ASSERT_NULL(locate_within(neighbor, /obj/structure/picnic_blanket_deployed), "refusal allocates no edge structure")

/// Crowding still skips that tile while expanding into the other available neighbors.
/datum/unit_test/interim_picnic_blanket_crowding/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/crowded = get_step(T, EAST)
	TEST_ASSERT(crowded && !crowded.density, "the fixture provides an available neighboring floor")
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	for(var/i in 1 to 21)
		allocate(/obj/item/pen, crowded)
	var/obj/item/picnic_blankets_carried/carried = allocate(/obj/item/picnic_blankets_carried, T)
	TEST_ASSERT(user.put_in_active_hand(carried), "the actual actor holds the folded blanket")
	test_op_handler(carried, "picnic_blankets_carried_fold_out_effect", user)
	own_turf_contents(T)
	var/obj/structure/picnic_blanket_deployed/deployed = locate_within(T, /obj/structure/picnic_blanket_deployed)
	TEST_ASSERT(deployed, "a crowded neighboring tile does not block creating the center")
	TEST_ASSERT_NULL(locate_within(crowded, /obj/structure/picnic_blanket_deployed), "the actual unfold skips the crowded neighbor")
	TEST_ASSERT(length(deployed.attached_blankets), "the actual unfold still creates edges on other neighbors")
	TEST_ASSERT_NULL(user.get_active_hand(), "crowded unfolding still vacates the source hand")
