/// Actual beaker lid interactions gate the public help-pour path without discarding liquid or unrelated flags.
/datum/unit_test/interim_beaker_lid_transfer
	parent_type = /datum/unit_test/dq_p2_reagents

/datum/unit_test/interim_beaker_lid_transfer/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = rc_actor(T)
	var/obj/item/reagent_containers/glass/beaker/source = allocate(/obj/item/reagent_containers/glass/beaker, T)
	var/obj/item/reagent_containers/glass/beaker/target = allocate(/obj/item/reagent_containers/glass/beaker, T)
	source.reagents.add_reagent(REAGENT_ID_WATER, 20)
	rc_set_amount_menu(user, source, 7)
	TEST_ASSERT_EQUAL(rc_amount(source), 7, "the actual amount-setting menu configures a seven-unit dose")
	TEST_ASSERT(source.is_open_container() && target.is_open_container(), "the actual beakers begin open")
	TEST_ASSERT(source.flags & NOCONDUCT, "the actual source begins with its nonconductive flag")
	rc_use(user, source)
	TEST_ASSERT(!source.is_open_container(), "the actual source lid is closed")
	TEST_ASSERT(source.flags & NOCONDUCT, "closing the lid preserves the unrelated nonconductive flag")
	rc_click(user, target, source)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 20, "a closed-source help pour preserves the actual source liquid")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 0, "a closed-source help pour delivers no liquid")
	rc_use(user, source)
	TEST_ASSERT(source.is_open_container(), "the actual source is open again")
	rc_use(user, target)
	TEST_ASSERT(!target.is_open_container(), "the actual target lid is closed")
	rc_click(user, target, source)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 20, "a closed-target help pour preserves the actual source liquid")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 0, "a closed-target help pour delivers no liquid")
	rc_use(user, target)
	TEST_ASSERT(target.is_open_container(), "the actual target is open again")
	var/turf/distant = run_loc_floor_top_right
	TEST_ASSERT(get_dist(T, distant) > 1, "the actual distant pour fixture is outside adjacent reach")
	target.forceMove(distant)
	rc_click(user, target, source)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 20, "a distant help pour preserves actual source liquid")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 0, "a distant help pour delivers no liquid")
	target.forceMove(T)
	rc_click(user, target, source)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 13, "the actual nearby open-container help pour spends the configured seven-unit dose")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 7, "the actual target receives the configured seven-unit dose")
	TEST_ASSERT(source.flags & NOCONDUCT, "the source's lid round trip preserves its unrelated nonconductive flag")
	TEST_ASSERT(target.flags & NOCONDUCT, "the target's lid round trip preserves its unrelated nonconductive flag")
