/// Refusals run against an existing test z; this fixture never creates an abduction map.
/datum/unit_test/om/interim_redspace_abduction_actor_refusal/run_om(list/made)
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/target = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/pen/held = allocate(/obj/item/pen, T)
	made += list(target, actor, held)
	TEST_ASSERT(target.put_in_active_hand(held), "the actual target holds an item before the refusal")
	target.set_transforming(FALSE)
	var/turf/start = get_turf(target)
	var/initial_timers = LAZYLEN(target.om_rec?.timers)
	var/initial_z_count = world.maxz
	set_global("redspace_abduction_z", T.z)
	redspace_abduction(target, null)
	TEST_ASSERT_EQUAL(target.transforming, FALSE, "a missing explicit actor does not freeze the actual target")
	TEST_ASSERT_EQUAL(LAZYLEN(target.om_rec?.timers), initial_timers, "a missing actor schedules no actual delayed abduction")
	TEST_ASSERT_EQUAL(get_turf(target), start, "a missing actor does not move the actual target")
	TEST_ASSERT_EQUAL(target.get_active_hand(), held, "a missing actor preserves the actual target inventory")
	TEST_ASSERT_EQUAL(held.loc, target, "a missing actor preserves actual item containment")
	redspace_abduction(target, FALSE)
	TEST_ASSERT_EQUAL(target.transforming, FALSE, "the actual false actor follows the same existing refusal")
	TEST_ASSERT_EQUAL(LAZYLEN(target.om_rec?.timers), initial_timers, "the actual false actor schedules no callback")
	redspace_abduction(null, actor)
	TEST_ASSERT_EQUAL(world.maxz, initial_z_count, "the refusal fixture never generates a live abduction z-level")
	TEST_ASSERT_EQUAL(GLOB.redspace_abduction_z, T.z, "all actual refusals preserve the existing configured z-level")
