/// Exercise the same public helper both real PDA entry handlers call.
/datum/unit_test/interim_pda_message_missing_sender/Run()
	test_driver_begin()
	check_missing_sender()
	test_driver_end()

/datum/unit_test/interim_pda_message_missing_sender/proc/check_missing_sender()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	var/obj/item/pda/sender = allocate(/obj/item/pda, run_loc_floor_bottom_left)
	var/obj/item/pda/recipient = allocate(/obj/item/pda, run_loc_floor_bottom_left)
	var/datum/data/pda/app/messenger/program = sender.find_program(/datum/data/pda/app/messenger)
	var/datum/data/pda/app/messenger/recipient_program = recipient.find_program(/datum/data/pda/app/messenger)
	TEST_ASSERT(istype(program) && istype(recipient_program), "real initialized PDAs contain their actual messenger programs")
	TEST_ASSERT_EQUAL(program.pda(), sender, "the actual sender association exists before the question")
	var/initial_cooldown = program.text_cooldown
	var/initial_sent = LAZYLEN(program.tnote)
	var/initial_received = LAZYLEN(recipient_program.tnote)
	program.create_message(actor, recipient)
	var/datum/prompt/text/pda_message/ask = SSrequests.open_for(actor)
	TEST_ASSERT(istype(ask), "the public helper used by UI and topic callers opens its real native request")
	TEST_ASSERT_EQUAL(ask.owner, program, "the request keeps the actual program, not a synthetic callback owner")
	TEST_ASSERT_EQUAL(ask.subject, recipient, "the request retains the real recipient PDA")
	rel_clear(program, nameof(/datum/data/pda::pda))
	TEST_ASSERT_NULL(program.pda(), "the sender relation is actually missing before answering")
	test_answer(actor, "This must not be sent")
	TEST_ASSERT_EQUAL(ask.outcome, REQ_CANCELLED, "loss of the current sender cleanly refuses the actual answer")
	TEST_ASSERT_EQUAL(ask.last_error, "no sender", "the missing sender reaches the real sender-validity requirement")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "a rejected message retires its real question")
	TEST_ASSERT_EQUAL(program.text_cooldown, initial_cooldown, "the actual send tail did not start its cooldown")
	TEST_ASSERT_EQUAL(LAZYLEN(program.tnote), initial_sent, "no sent message was appended")
	TEST_ASSERT_EQUAL(LAZYLEN(recipient_program.tnote), initial_received, "no received message was appended")
	rel_set(program, nameof(/datum/data/pda::pda), sender)
