/// The actual APC cell bay must preserve a cell's held slot when its actor cannot release it, then adopt and eject that same cell after release is allowed.
/datum/unit_test/interim_apc_cell_inventory_roundtrip/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/power/apc/apc = interim_apc_make(T)
	var/obj/item/cell/cell = apc.cell
	TEST_ASSERT_NOTNULL(cell, "the actual APC starts with its installed cell")
	cap_key_set(apc, COVER_OPEN, TRUE, null)
	TEST_ASSERT_EQUAL(interim_apc_take(apc, user, drop = TRUE), cell, "the actual public bay take op and inventory drop release the original actual cell")
	TEST_ASSERT_NULL(apc.cell, "actual ejection clears the APC cell view")
	TEST_ASSERT_EQUAL(cell.loc, T, "actual ejection releases the original cell to the floor")
	TEST_ASSERT(user.put_in_inactive_hand(cell), "the actual actor holds the ejected cell in the inactive hand")
	var/obj/item/pen/unrelated = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_active_hand(unrelated), "the actual actor holds an unrelated active pen")
	var/charge_before = cell.charge
	add_trait(cell, TRAIT_NODROP, "interim_apc_cell_inventory")
	TEST_ASSERT(user.release_refusal(cell, user), "the actual inventory refuses to release its sticky power cell")
	TEST_ASSERT(!interim_apc_insert(apc, cell, user), "the public bay insertion API refuses the sticky held cell")
	TEST_ASSERT_NULL(apc.cell, "refused insertion preserves the empty bay")
	TEST_ASSERT_EQUAL(cell.loc, user, "refused insertion leaves the original cell on its actor")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), cell, "refused insertion preserves the cell's exact held slot")
	TEST_ASSERT_EQUAL(user.get_active_hand(), unrelated, "refused insertion preserves the unrelated active item")
	TEST_ASSERT_EQUAL(cell.charge, charge_before, "refused insertion spends no stored cell charge")
	remove_trait(cell, TRAIT_NODROP, "interim_apc_cell_inventory")
	TEST_ASSERT(interim_apc_insert(apc, cell, user), "the same actual cell enters the bay when release is allowed")
	TEST_ASSERT_EQUAL(apc.cell, cell, "successful insertion restores the same original APC cell")
	TEST_ASSERT_EQUAL(cell.loc, apc, "successful insertion moves the actual cell inside the APC")
	TEST_ASSERT_NULL(user.get_inactive_hand(), "successful insertion clears the original inventory slot")
	TEST_ASSERT_EQUAL(user.get_active_hand(), unrelated, "successful insertion preserves the unrelated active item")
	TEST_ASSERT_EQUAL(interim_apc_take(apc, user), cell, "the public bay API returns the actual cell to the actor's free hand")
	TEST_ASSERT_NULL(apc.cell, "second actual ejection clears the APC cell view")
	TEST_ASSERT_EQUAL(cell.loc, user, "second actual ejection returns the cell to its actor")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), cell, "second actual ejection uses the only free hand")
	TEST_ASSERT_EQUAL(user.get_active_hand(), unrelated, "the full bay round trip preserves the unrelated active item")
	TEST_ASSERT_EQUAL(cell.charge, charge_before, "the complete bay round trip preserves actual stored charge")
