/// A real attached corporate tag must survive destruction of its synthmorph bag.
/datum/unit_test/interim_robobag_tag_spill/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/structure/closet/body_bag/cryobag/robobag/bag = allocate(/obj/structure/closet/body_bag/cryobag/robobag, T)
	var/obj/item/clothing/accessory/badge/corporate_tag/tag = allocate(/obj/item/clothing/accessory/badge/corporate_tag, T)
	TEST_ASSERT(!bag.opened, "The real bag must begin closed for tag attachment")
	TEST_ASSERT(actor.put_in_active_hand(tag), "The actor must hold the real corporate tag")
	bag.robobag_interaction_item(actor, tag, null)
	TEST_ASSERT_EQUAL(bag.corptag, tag, "Public attachment must store the exact corporate tag")
	TEST_ASSERT_NULL(tag.loc, "Current attachment must keep its tag in nullspace")
	TEST_ASSERT_NULL(actor.get_active_hand(), "Attachment must release the actor's hand")
	qdel(bag)
	TEST_ASSERT(!QDELETED(tag), "Destroying the bag must preserve its attached corporate tag")
	TEST_ASSERT_EQUAL(tag.loc, T, "The bag's prerelease must return its nullspace-owned tag to its floor")
