/// Actual crate initialization gathers cargo; crowbar opening preserves it and recovers wood.
/datum/unit_test/interim_largecrate_recovery/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/book/book = allocate(/obj/item/book, T)
	var/obj/structure/largecrate/crate = allocate(/obj/structure/largecrate, T)
	TEST_ASSERT_EQUAL(book.loc, crate, "actual crate initialization gathers the floor book")
	var/obj/item/tool/crowbar/tool = allocate(/obj/item/tool/crowbar, T)
	TEST_ASSERT(user.put_in_active_hand(tool), "the actor holds the actual crowbar")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/wood)), 0, "the floor starts without returned wood")
	TEST_ASSERT(test_op_handler(crate, "crowbar_used", user, tool), "actual crate opening reports success")
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(crate), "actual opening consumes the original crate")
	TEST_ASSERT(!QDELETED(book), "the original gathered book survives opening")
	TEST_ASSERT_EQUAL(book.loc, T, "opening returns the original book to the floor")
	TEST_ASSERT_NULL(locate_within(T, /obj/structure/largecrate), "opening leaves no duplicate crate")
	var/sheets = 0
	for(var/obj/item/stack/material/wood/wood as anything in contents_of(T, /obj/item/stack/material/wood))
		TEST_ASSERT_EQUAL(wood.loc, T, "returned wood stays on the original floor")
		sheets += wood.get_amount()
	TEST_ASSERT_EQUAL(sheets, 1, "actual opening returns exactly one wood sheet")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "opening keeps the original crowbar held")

/// Actual cage loading and tool completion release the same vehicle and recover steel.
/datum/unit_test/interim_vehiclecage_recovery/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/vehiclecage/cage = allocate(/obj/structure/vehiclecage, T)
	var/obj/vehicle/vehicle = allocate(/obj/vehicle, T)
	var/obj/item/tool/wrench/tool = allocate(/obj/item/tool/wrench, T)
	TEST_ASSERT(user.put_in_active_hand(tool), "the actor holds the actual wrench")
	cage.load_vehicle(vehicle, user)
	TEST_ASSERT_EQUAL(vehicle.loc, cage, "actual loading puts the vehicle inside the cage")
	TEST_ASSERT(vehicle in cage.slot_contents(CONTAINER_SLOT_VEHICLE_CAGE), "actual loading registers the vehicle in the declared cage slot")
	TEST_ASSERT_EQUAL(cage.paint_color, vehicle.paint_color, "actual loading copies the vehicle paint")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/steel)), 0, "the floor starts without returned steel")
	cage.tool_disassemble_tool_done(user, tool)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(cage), "actual tool completion consumes the cage")
	TEST_ASSERT(!QDELETED(vehicle), "the original loaded vehicle survives disassembly")
	TEST_ASSERT_EQUAL(vehicle.loc, T, "actual completion releases the vehicle onto the floor")
	TEST_ASSERT_NULL(locate_within(T, /obj/structure/vehiclecage), "completion leaves no duplicate cage")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/vehicle)), 1, "completion returns exactly the original vehicle")
	var/sheets = 0
	for(var/obj/item/stack/material/steel/steel as anything in contents_of(T, /obj/item/stack/material/steel))
		TEST_ASSERT_EQUAL(steel.loc, T, "returned steel stays on the original floor")
		sheets += steel.get_amount()
	TEST_ASSERT_EQUAL(sheets, 5, "actual completion returns exactly five steel sheets")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "completion keeps the original wrench held")
