/// Real nonstack ingredient loading respects release and its actual timed eject action returns the same uncooked produce.
/datum/unit_test/interim_microwave_sticky_produce/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/mob/controller = allocate(/mob/living/simple_mob/e0_fixture, run_loc_floor_top_right)
	rel_set(user, nameof(user.teleop), controller)
	var/obj/machinery/microwave/microwave = allocate(/obj/machinery/microwave, T)
	var/obj/item/reagent_containers/food/snacks/grown/produce = allocate(/obj/item/reagent_containers/food/snacks/grown, T, PLANT_APPLE)
	var/original_volume = produce.reagents.total_volume
	TEST_ASSERT(is_type_in_list(produce, GLOB.acceptable_items), "the actual original apple is an accepted microwave ingredient")
	TEST_ASSERT_EQUAL(length(microwave.cookingContents()), 0, "the actual initialized microwave starts without cooking ingredients")
	TEST_ASSERT(!microwave.operating, "the actual microwave starts outside a cooking cycle")
	TEST_ASSERT(user.put_in_active_hand(produce), "the actor holds the original real apple")
	add_trait(produce, TRAIT_NODROP, "interim_microwave_sticky")
	TEST_ASSERT(user.release_refusal(produce, user), "the actual inventory refuses the sticky apple's release")
	microwave.try_insert_item(produce, user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), produce, "refused loading preserves the exact original hand")
	TEST_ASSERT_EQUAL(produce.loc, user, "refused loading preserves actual inventory containment")
	TEST_ASSERT_EQUAL(length(microwave.cookingContents()), 0, "refused loading records no cooking ingredient")
	TEST_ASSERT_EQUAL(produce.reagents.total_volume, original_volume, "refused loading preserves the real original food amount")
	remove_trait(produce, TRAIT_NODROP, "interim_microwave_sticky")
	microwave.try_insert_item(produce, user)
	TEST_ASSERT_EQUAL(produce.loc, microwave, "allowed loading contains the same original apple")
	TEST_ASSERT(produce in microwave.cookingContents(), "the actual cooking-contents view contains the original apple")
	TEST_ASSERT_EQUAL(length(microwave.cookingContents()), 1, "allowed loading records exactly one real ingredient")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed loading clears the original hand")
	test_menu(user, microwave, "microwave_verb_eject")
	TEST_ASSERT(!isnull(op_pending_of(user)), "the actual eject interaction starts its real timed action")
	TEST_ASSERT_EQUAL(produce.loc, microwave, "starting actual ejection returns no ingredient early")
	test_time(2 SECONDS)
	TEST_ASSERT_NULL(op_pending_of(user), "actual ejection releases its pending timed action")
	TEST_ASSERT_EQUAL(produce.loc, T, "actual timed ejection returns the same original uncooked apple to the floor")
	TEST_ASSERT_EQUAL(length(microwave.cookingContents()), 0, "actual timed ejection empties the cooking-contents view")
	TEST_ASSERT_EQUAL(produce.reagents.total_volume, original_volume, "actual insertion and ejection preserve the food's original reagent amount")
	TEST_ASSERT(!microwave.operating, "actual loading and ejection never start a cooking cycle")
	qdel(microwave)
	TEST_ASSERT(!QDELETED(produce), "the returned original apple survives empty-microwave teardown")
	test_driver_end()
