/// Real owned voice connections are disposed by their list owner during public hangup.
/// This configures the supported connection state; it does not claim ghost/client dialing coverage.
/datum/unit_test/interim_communicator_owned_hangup
	parent_type = /datum/unit_test/dq_p2_reagents
	var/all_case = FALSE

/datum/unit_test/interim_communicator_owned_hangup/all
	all_case = TRUE

/datum/unit_test/interim_communicator_owned_hangup/run_gate()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = rc_actor(T)
	var/obj/item/communicator/comm = allocate(/obj/item/communicator, T)
	var/obj/item/communicator/control = allocate(/obj/item/communicator, T)
	var/mob/living/voice/first = allocate(/mob/living/voice, comm)
	var/mob/living/voice/second = allocate(/mob/living/voice, comm)
	var/mob/living/voice/unrelated = allocate(/mob/living/voice, control)
	TEST_ASSERT_EQUAL(first.comm, comm, "The actual first voice constructor must link its original communicator")
	TEST_ASSERT_EQUAL(second.comm, comm, "The actual second voice constructor must link its original communicator")
	TEST_ASSERT_EQUAL(unrelated.comm, control, "The independent actual constructor must link its own communicator")
	TEST_ASSERT_EQUAL(own_add(comm, nameof(comm.voice_mobs), first), first, "Supported adoption must own the exact first connection")
	TEST_ASSERT_EQUAL(own_add(comm, nameof(comm.voice_mobs), second), second, "Supported adoption must own the exact second connection")
	TEST_ASSERT_EQUAL(own_add(control, nameof(control.voice_mobs), unrelated), unrelated, "Independent connection adoption must retain its exact identity")
	registry_join(REGISTRY_LISTENING_OBJECTS, comm)
	registry_join(REGISTRY_LISTENING_OBJECTS, control)
	TEST_ASSERT(registry_has(REGISTRY_LISTENING_OBJECTS, comm), "The actual connected communicator must be a real listener")
	TEST_ASSERT_EQUAL(length(comm.voice_mobs), 2, "The actual owner must hold both original connections")
	TEST_ASSERT_EQUAL(owner_of(first), comm, "The original first voice must have its actual owner stamp")
	TEST_ASSERT_EQUAL(owner_of(second), comm, "The original second voice must have its actual owner stamp")
	comm.close_connection(actor, all_case ? null : first, "Connection timed out")
	TEST_ASSERT(QDELETED(first), "Real hangup must dispose of the exact selected first voice")
	TEST_ASSERT_NULL(owner_of(first), "Hangup must remove the disposed first voice's ownership")
	if(!all_case)
		TEST_ASSERT(!QDELETED(second), "Targeted hangup must preserve the exact unselected second voice")
		TEST_ASSERT_EQUAL(owner_of(second), comm, "Targeted hangup must retain the actual surviving owner")
		TEST_ASSERT_EQUAL(second.loc, comm, "Targeted hangup must retain the actual surviving containment")
		TEST_ASSERT_EQUAL(second.comm, comm, "Targeted hangup must retain the original surviving communicator relation")
		TEST_ASSERT_EQUAL(length(comm.voice_mobs), 1, "Targeted hangup must leave exactly one owned connection")
		TEST_ASSERT_EQUAL(comm.voice_mobs[1], second, "The remaining list must hold the exact original second voice")
		TEST_ASSERT(registry_has(REGISTRY_LISTENING_OBJECTS, comm), "The real listener must remain while a connection survives")
		comm.close_connection(actor, second, "Connection timed out")
	TEST_ASSERT(QDELETED(second), "Final or all hangup must dispose of the exact original second voice")
	TEST_ASSERT_NULL(owner_of(second), "Final disposal must clear the exact second voice owner stamp")
	TEST_ASSERT_EQUAL(length(comm.voice_mobs), 0, "Completed hangup must leave no original owned connections")
	TEST_ASSERT(!registry_has(REGISTRY_LISTENING_OBJECTS, comm), "Completed hangup must leave the real listening registry")
	TEST_ASSERT(!QDELETED(comm), "Hangup must preserve the exact original communicator")
	TEST_ASSERT(!QDELETED(unrelated) && !QDELETED(control), "Hangup must preserve the independent exact communicator and voice")
	TEST_ASSERT_EQUAL(owner_of(unrelated), control, "Hangup must preserve independent original voice ownership")
	TEST_ASSERT_EQUAL(unrelated.loc, control, "Hangup must preserve independent original voice containment")
	TEST_ASSERT_EQUAL(unrelated.comm, control, "Hangup must preserve independent original communicator relation")
	TEST_ASSERT_EQUAL(length(control.voice_mobs), 1, "Hangup must preserve independent actual connection membership")
	TEST_ASSERT(registry_has(REGISTRY_LISTENING_OBJECTS, control), "Hangup must preserve the independent real listening registration")
	control.close_connection(actor, unrelated, "Connection timed out")
	TEST_ASSERT(QDELETED(unrelated), "Actual independent final cleanup must dispose of its original voice")
	TEST_ASSERT(!registry_has(REGISTRY_LISTENING_OBJECTS, control), "Actual independent cleanup must remove its own listener")
