/// An empty initializer removal retains real worn shield/core/projectile behavior.
/datum/unit_test/interim_shield_armor_init/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/clothing/suit/armor/shield/shield = allocate(/obj/item/clothing/suit/armor/shield, T)
	var/atom/movable/screen/movable/ability_master/master = allocate(/atom/movable/screen/movable/ability_master, user)
	rel_set(user, nameof(user.ability_master), master)
	var/obj/item/technomancer_core/core = allocate(/obj/item/technomancer_core, T)
	var/obj/item/projectile/bullet/pistol/strong/projectile = allocate(/obj/item/projectile/bullet/pistol/strong, T)
	TEST_ASSERT(!issmall(user), "actual human shield fixture uses normal-size protection")
	TEST_ASSERT(!shield.active, "actual initialized shield starts inactive")
	TEST_ASSERT_EQUAL(shield.block_percentage, 75, "actual shield retains its original seventy-five percent block")
	TEST_ASSERT_EQUAL(shield.damage_to_energy_multiplier, 50, "actual shield retains its original energy cost scale")
	TEST_ASSERT_EQUAL(core.energy, 10000, "actual initialized core starts with its original energy")
	TEST_ASSERT_EQUAL(core.energy_cost_modifier, 1, "actual standard core uses the original unmodified energy cost")
	TEST_ASSERT(user.equip_to_slot_if_possible(core, SLOT_ID_BACK), "actual actor wears its real core on its back")
	TEST_ASSERT(user.equip_to_slot_if_possible(shield, SLOT_ID_SUIT), "actual actor wears its initialized shield armor")
	projectile.agony = 20
	projectile.sharp = TRUE
	projectile.edge = TRUE
	projectile.embed_chance = 50
	var/damage_before = projectile.damage
	TEST_ASSERT_EQUAL(shield.handle_shield(user, 20, projectile), 0, "actual inactive shield returns the original damage-handling result")
	TEST_ASSERT_EQUAL(projectile.damage, damage_before, "actual inactive shield leaves projectile damage unchanged")
	TEST_ASSERT_EQUAL(projectile.agony, 20, "actual inactive shield leaves projectile agony unchanged")
	TEST_ASSERT_EQUAL(core.energy, 10000, "actual inactive shield spends no core energy")
	test_op_handler(shield, "shield_armor_toggle_self", user, shield) // worn, not held: the handler runs as the engine would
	TEST_ASSERT(shield.active, "actual toggle activates the worn shield")
	var/result = shield.handle_shield(user, 20, projectile)
	own_turf_contents(T)
	TEST_ASSERT_EQUAL(result, 0, "actual partial shielding preserves the original damage-handling return")
	TEST_ASSERT_EQUAL(core.energy, 9250, "actual twenty-damage shielding spends exactly seven hundred fifty real core energy")
	TEST_ASSERT_EQUAL(projectile.damage, damage_before - 15, "actual shielding removes exactly fifteen projectile damage")
	TEST_ASSERT_EQUAL(projectile.agony, 5, "actual shielding removes seventy-five percent of projectile agony")
	TEST_ASSERT_EQUAL(projectile.sharp, FALSE, "actual shielding makes the real projectile blunt")
	TEST_ASSERT_EQUAL(projectile.edge, FALSE, "actual shielding clears the real projectile cutting edge")
	TEST_ASSERT_EQUAL(projectile.embed_chance, 0, "actual shielding prevents the real projectile embedding")
	TEST_ASSERT(shield.active, "actual successful shielding leaves its emitter active")
	TEST_ASSERT_EQUAL(core.pay_energy(core.energy), 1, "actual core payment drains its remaining energy")
	TEST_ASSERT_EQUAL(core.energy, 0, "actual core payment leaves no energy for another shield hit")
	var/damage_after = projectile.damage
	TEST_ASSERT_EQUAL(shield.handle_shield(user, 20, projectile), 0, "actual insufficient-energy shielding preserves its documented return")
	TEST_ASSERT(!shield.active, "actual insufficient-energy shielding disables its shield")
	TEST_ASSERT_EQUAL(core.energy, 0, "actual energy refusal creates no energy debt")
	TEST_ASSERT_EQUAL(projectile.damage, damage_after, "actual energy refusal leaves projectile damage unchanged")
	TEST_ASSERT_EQUAL(projectile.agony, 5, "actual energy refusal leaves projectile agony unchanged")
	TEST_ASSERT_EQUAL(user.get_equipped_item(SLOT_ID_BACK), core, "actual shielding preserves its original worn core")
	TEST_ASSERT_EQUAL(user.get_equipped_item(SLOT_ID_SUIT), shield, "actual shielding preserves its original worn armor")
	TEST_ASSERT(!QDELETED(user) && !QDELETED(core) && !QDELETED(shield), "actual shielding preserves actor and equipment identities")
