/// Actual wired-crate attachment respects original electropack release and preserves ledger retrieval.
/datum/unit_test/interim_crate_sticky_electropack/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/closet/crate/crate = allocate(/obj/structure/closet/crate, T)
	interim_keep_awake(user)
	TEST_ASSERT(!crate.opened && !crate.rigged, "actual initialized crate starts closed and unwired")
	TEST_ASSERT_EQUAL(length(crate.slot_contents()), 0, "actual initialized crate starts with empty physical ledger")
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, T, 1)
	TEST_ASSERT(user.put_in_active_hand(cable), "actor holds exact original cable segment")
	test_click(user, crate, cable)
	test_time(5 SECONDS)
	TEST_ASSERT(crate.rigged && QDELETED(cable), "actual cable effect wires crate and consumes its final segment")
	var/obj/item/radio/electropack/pack = allocate(/obj/item/radio/electropack, T)
	TEST_ASSERT(user.put_in_active_hand(pack), "actor holds exact original electropack")
	add_trait(pack, TRAIT_NODROP, "interim_crate_pack")
	TEST_ASSERT(user.release_refusal(pack, user), "actual inventory refuses sticky original electropack")
	test_click(user, crate, pack)
	test_time(5 SECONDS)
	TEST_ASSERT_EQUAL(user.get_active_hand(), pack, "refused attachment preserves exact original hand")
	TEST_ASSERT_EQUAL(pack.loc, user, "refused attachment preserves original inventory location")
	TEST_ASSERT_EQUAL(length(crate.slot_contents()), 0, "refused attachment admits no electropack to actual ledger")
	TEST_ASSERT(crate.rigged, "refused attachment preserves actual existing wiring")
	remove_trait(pack, TRAIT_NODROP, "interim_crate_pack")
	test_click(user, crate, pack)
	test_time(5 SECONDS)
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed attachment clears actual source hand")
	TEST_ASSERT_EQUAL(pack.loc, crate, "allowed attachment physically contains exact original electropack")
	TEST_ASSERT(pack in crate.slot_contents(), "allowed attachment records original electropack in actual crate ledger")
	TEST_ASSERT_EQUAL(length(crate.slot_contents()), 1, "allowed attachment admits exactly one original item")
	TEST_ASSERT_NULL(owner_of(pack), "crate preserves its existing unowned electropack containment policy")
	var/obj/item/tool/wirecutters/cutters = allocate(/obj/item/tool/wirecutters, T)
	TEST_ASSERT(user.put_in_active_hand(cutters), "actor holds canonical wirecutters")
	test_click(user, crate, cutters)
	test_time(5 SECONDS)
	TEST_ASSERT(!crate.rigged, "actual wirecutter effect disarms crate wiring")
	TEST_ASSERT(crate.open(user), "actual disarmed crate opens for the real actor")
	TEST_ASSERT(!QDELETED(pack), "actual opening preserves original electropack alive")
	TEST_ASSERT_EQUAL(pack.loc, T, "actual opening refunds exact original electropack to floor")
	TEST_ASSERT_EQUAL(length(crate.slot_contents()), 0, "actual opening clears original electropack from ledger")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cutters, "actual disarming and opening preserve original tool hand")
	test_driver_end()
