/// Real floor evidence is bagged and removed using the explicit initiating human.
/datum/unit_test/interim_evidence_bag_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/obj/item/evidencebag/bag = allocate(/obj/item/evidencebag, T)
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	var/obj/item/paper/other = allocate(/obj/item/paper, T)
	TEST_ASSERT(actor.put_in_r_hand(bag), "the actual initiating human holds the real bag")
	TEST_ASSERT(actor.Adjacent(paper), "real floor evidence satisfies the existing proximity guard")
	var/obj/item/storage/box/outer = allocate(/obj/item/storage/box, T)
	TEST_ASSERT(actor.put_in_l_hand(outer), "the actual actor carries the outer nested-storage fixture")
	var/obj/item/storage/box/middle = allocate(/obj/item/storage/box, outer)
	var/obj/item/storage/box/inner = allocate(/obj/item/storage/box, middle)
	var/obj/item/paper/deep = allocate(/obj/item/paper, inner)
	TEST_ASSERT_EQUAL(middle.loc, outer, "actual construction contains the middle box in the outer box")
	TEST_ASSERT_EQUAL(inner.loc, middle, "actual construction contains the inner box in the middle box")
	TEST_ASSERT_EQUAL(deep.loc, inner, "actual construction contains the exact deeply nested paper")
	TEST_ASSERT(deep.storage_depth(actor) > MAX_STORAGE_REACH, "the real physical chain exceeds the source reach limit before client access")
	TEST_ASSERT_EQUAL(bag.bag_with_actor(actor, deep), TRUE, "the actual deep-storage refusal remains native-consumed")
	TEST_ASSERT_EQUAL(deep.loc, inner, "deep refusal preserves exact nested evidence location")
	TEST_ASSERT_EQUAL(inner.loc, middle, "deep refusal preserves the exact inner box chain")
	TEST_ASSERT_EQUAL(middle.loc, outer, "deep refusal preserves the exact middle box chain")
	TEST_ASSERT_NULL(bag.stored_item(), "deep refusal leaves the actual evidence bag empty")
	TEST_ASSERT_EQUAL(contents_count(bag), 0, "deep refusal creates no physical bag contents")
	TEST_ASSERT_EQUAL(actor.get_right_hand(), bag, "deep refusal preserves the initiating held bag")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), outer, "deep refusal preserves the held outer box")
	TEST_ASSERT(actor.unEquip(outer), "actual release frees the hand for later evidence removal")
	TEST_ASSERT_EQUAL(bag.bag_with_actor(bystander, paper), TRUE, "non-holder refusal remains native-consumed")
	TEST_ASSERT_NULL(bag.stored_item(), "an unrelated human cannot fill the actor's actual held bag")
	TEST_ASSERT_EQUAL(paper.loc, T, "non-holder refusal preserves the exact floor evidence")
	TEST_ASSERT_EQUAL(bag.bag_with_actor(actor, paper), TRUE, "actual successful bagging remains native-consumed")
	TEST_ASSERT_EQUAL(bag.stored_item(), paper, "actual insertion records the exact evidence relation")
	TEST_ASSERT_EQUAL(paper.loc, bag, "actual insertion physically contains the exact paper")
	TEST_ASSERT_EQUAL(contents_count(bag), 1, "actual insertion produces exactly one physical evidence item")
	TEST_ASSERT_EQUAL(bag.w_class, paper.w_class, "actual filled bag takes its evidence's real size")
	TEST_ASSERT_EQUAL(bag.icon_state, "evidence", "actual filled bag renders its filled state")
	bag.bag_with_actor(actor, other)
	TEST_ASSERT_EQUAL(bag.stored_item(), paper, "actual occupied-bag refusal preserves its exact existing evidence")
	TEST_ASSERT_EQUAL(other.loc, T, "occupied-bag refusal leaves unrelated floor evidence untouched")
	TEST_ASSERT(test_op_committed(perform_op(actor, bag, "self", bag)), "actual self op removes evidence through its existing effect")
	TEST_ASSERT_NULL(bag.stored_item(), "actual removal clears the real evidence relation")
	TEST_ASSERT_EQUAL(contents_count(bag), 0, "actual removal empties physical bag contents")
	TEST_ASSERT(actor.item_is_in_hands(paper), "actual removal gives exact evidence to its initiating human")
	TEST_ASSERT_EQUAL(actor.get_right_hand(), bag, "actual removal retains the original held bag")
	TEST_ASSERT_EQUAL(bag.w_class, initial(bag.w_class), "actual removal restores the bag's configured size")
	TEST_ASSERT_EQUAL(bag.icon_state, "evidenceobj", "actual removal restores empty bag state")
	TEST_ASSERT(actor.unEquip(paper), "actual actor releases the paper back onto the floor")
	bag.bag_with_actor(actor, paper)
	TEST_ASSERT_EQUAL(bag.stored_item(), paper, "actual bag can reinsert the same evidence after removal")
	TEST_ASSERT_EQUAL(paper.loc, bag, "actual complete roundtrip retains exact evidence identity")
	TEST_ASSERT_EQUAL(other.loc, T, "actual roundtrip leaves unrelated evidence untouched")
