/datum/unit_test/dq_p2_engine/interim_native_mining_requests

/datum/unit_test/dq_p2_engine/interim_native_mining_requests/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/mining/drill/drill = allocate(/obj/machinery/mining/drill, T)
	own(drill.faultreporter)
	var/obj/item/multitool/tool = allocate(/obj/item/multitool, T)
	TEST_ASSERT(user.put_in_active_hand(tool), "the real multitool is held for the machine click")
	test_click(user, drill, tool)
	test_time(0.1 SECONDS)
	var/datum/prompt/text/drill_label/label_request = SSrequests.open_for(user)
	TEST_ASSERT(istype(label_request), "the actual multitool click opens the drill label request")
	TEST_ASSERT_EQUAL(label_request.captured_tool, tool, "the request captures the exact tool used")
	test_answer(user, "42")
	test_time(0.1 SECONDS)
	TEST_ASSERT_EQUAL(drill.name, "[initial(drill.name)] #42", "the actual answer labels the machine with its numeric ID")
	test_click(user, drill, tool)
	test_time(0.1 SECONDS)
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/text/drill_label), "a second actual click opens the clear-label request")
	test_answer(user, "")
	test_time(0.1 SECONDS)
	TEST_ASSERT_EQUAL(drill.name, initial(drill.name), "the accepted empty answer removes the label")
	test_click(user, drill, tool)
	test_time(0.1 SECONDS)
	label_request = SSrequests.open_for(user)
	TEST_ASSERT(istype(label_request), "the late-active case begins with a real inactive machine request")
	drill.set_active(TRUE)
	test_answer(user, "99")
	TEST_ASSERT_EQUAL(label_request.outcome, REQ_CANCELLED, "becoming active rejects the pending label answer")
	TEST_ASSERT_EQUAL(drill.name, initial(drill.name), "the rejected answer leaves the actual label unchanged")
	drill.set_active(FALSE)
	TEST_ASSERT(user.drop_from_inventory(tool), "the multitool is released through the real inventory path")
	var/obj/item/pickaxe/excavationdrill/excavator = allocate(/obj/item/pickaxe/excavationdrill, T)
	TEST_ASSERT(user.put_in_active_hand(excavator), "the actual excavation drill is held for self-use")
	test_click(user, excavator, excavator, GESTURE_SELF)
	test_time(0.1 SECONDS)
	var/datum/prompt/number/excavation_depth/depth_request = SSrequests.open_for(user)
	TEST_ASSERT(istype(depth_request), "actual self-use opens the native excavation depth request")
	TEST_ASSERT_EQUAL(depth_request.min_value, 1, "the real number request retains its lower depth bound")
	TEST_ASSERT_EQUAL(depth_request.max_value, 60, "the real number request retains its upper depth bound")
	TEST_ASSERT_EQUAL(depth_request.captured_item, excavator, "self-use captures the original drill")
	var/datum/tgui_input_number/prompt/box = depth_request.present(user)
	own(box)
	TEST_ASSERT_EQUAL(box.round_value, TRUE, "the actual number window retains the old integer-entry setting")
	test_answer(user, 6)
	test_time(0.1 SECONDS)
	TEST_ASSERT_EQUAL(excavator.excavation_amount, 6, "the real answer changes excavation depth")
	TEST_ASSERT_EQUAL(excavator.icon_state, "excavationdrill1", "the accepted depth reaches its real icon band")
	test_click(user, excavator, excavator, GESTURE_SELF)
	test_time(0.1 SECONDS)
	depth_request = SSrequests.open_for(user)
	TEST_ASSERT(istype(depth_request), "the upper-bound case opens through actual self-use")
	test_answer(user, 60)
	test_time(0.1 SECONDS)
	TEST_ASSERT_EQUAL(excavator.excavation_amount, 60, "the upper boundary is accepted")
	TEST_ASSERT_EQUAL(excavator.icon_state, "excavationdrill5", "the upper boundary uses the final real icon band")
	test_click(user, excavator, excavator, GESTURE_SELF)
	test_time(0.1 SECONDS)
	depth_request = SSrequests.open_for(user)
	TEST_ASSERT(istype(depth_request), "the disappearance case captures a real pending request")
	TEST_ASSERT(user.drop_from_inventory(excavator), "the original drill survives outside the retiring actor")
	qdel(user)
	request_submit(depth_request, 2)
	TEST_ASSERT_EQUAL(depth_request.outcome, REQ_CANCELLED, "the real request boundary rejects a disappeared captured actor")
	TEST_ASSERT_EQUAL(excavator.excavation_amount, 60, "capture loss preserves the surviving original drill depth")
	TEST_ASSERT_EQUAL(excavator.icon_state, "excavationdrill5", "capture loss preserves its surviving real appearance")
