/// Real mining weapons retain conflict identities and accelerator charge initialization.
/datum/unit_test/interim_mining_conflict_data/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/kinetic_crusher/crusher = allocate(/obj/item/kinetic_crusher, T)
	var/obj/item/kinetic_crusher/cyborg/integrated = allocate(/obj/item/kinetic_crusher/cyborg, T)
	var/obj/item/gun/energy/kinetic_accelerator/accelerator = allocate(/obj/item/gun/energy/kinetic_accelerator, T)
	var/obj/item/gun/energy/kinetic_accelerator/minebot/minebot = allocate(/obj/item/gun/energy/kinetic_accelerator/minebot, T)
	TEST_ASSERT_EQUAL(crusher.conflict_id, CONFLICT_ELEMENT_CRUSHER, "actual crusher keeps its conflict identity")
	TEST_ASSERT_EQUAL(integrated.conflict_id, CONFLICT_ELEMENT_CRUSHER, "actual integrated crusher inherits its conflict identity")
	TEST_ASSERT_EQUAL(accelerator.conflict_id, CONFLICT_ELEMENT_KA, "actual accelerator keeps its conflict identity")
	TEST_ASSERT_EQUAL(minebot.conflict_id, CONFLICT_ELEMENT_KA, "actual minebot accelerator inherits its conflict identity")
	var/obj/item/cell/device/weapon/empproof/reference_cell = allocate(/obj/item/cell/device/weapon/empproof, T)
	var/reference_before = reference_cell.charge
	TEST_ASSERT(reference_cell.use(reference_before) > 0, "the actual reference cell supplies charge through the public discharge API")
	TEST_ASSERT(reference_cell.charge > 0 && reference_cell.charge < reference_before, "actual material-limited discharge leaves a partially charged reference cell")
	TEST_ASSERT_EQUAL(accelerator.power_supply.charge, reference_cell.charge, "actual standard initialization performs the same material-limited full-charge discharge as its real cell")
	TEST_ASSERT_EQUAL(minebot.power_supply.charge, minebot.power_supply.maxcharge, "actual charge-retaining minebot keeps its real cell fully charged")
	var/accelerator_charge = accelerator.power_supply.charge
	TEST_ASSERT(accelerator_charge < accelerator.charge_cost, "actual initialization leaves less stored charge than the nominal shot cost")
	TEST_ASSERT_NULL(accelerator.consume_next_projectile(), "actual undercharged initialized accelerator cannot produce a projectile")
	TEST_ASSERT_EQUAL(accelerator.power_supply.charge, accelerator_charge, "actual shot refusal preserves the partially charged cell")
	TEST_ASSERT_EQUAL(user.ConflictElementCount(CONFLICT_ELEMENT_CRUSHER), 0, "the actual empty inventory has no crusher conflict")
	TEST_ASSERT_EQUAL(user.ConflictElementCount(CONFLICT_ELEMENT_KA), 0, "the actual empty inventory has no accelerator conflict")
	TEST_ASSERT(user.put_in_active_hand(crusher), "the real crusher occupies the actor's active hand")
	TEST_ASSERT(user.put_in_inactive_hand(accelerator), "the real accelerator occupies the actor's other hand")
	TEST_ASSERT_EQUAL(user.ConflictElementCount(CONFLICT_ELEMENT_CRUSHER), 1, "actual recursive inventory counts the exact held crusher")
	TEST_ASSERT_EQUAL(user.ConflictElementCount(CONFLICT_ELEMENT_KA), 1, "actual recursive inventory counts the exact held accelerator")
	TEST_ASSERT(user.drop_from_inventory(crusher), "the actual crusher can be released to the floor")
	TEST_ASSERT_EQUAL(crusher.loc, T, "actual release returns the exact crusher to the floor")
	TEST_ASSERT_EQUAL(user.ConflictElementCount(CONFLICT_ELEMENT_CRUSHER), 0, "actual release removes the crusher conflict")
	TEST_ASSERT_EQUAL(user.ConflictElementCount(CONFLICT_ELEMENT_KA), 1, "crusher release preserves the actual accelerator conflict")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), accelerator, "crusher release preserves the exact accelerator hand slot")
