/// Grab insertion and self-entry must use their supplied actor at the real slot boundary.
/datum/unit_test/interim_implantchair_actor_roundtrip/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/other = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/implantchair/chair = allocate(/obj/machinery/implantchair, T)
	var/datum/interim_resleever_actor_probe/probe = allocate(/datum/interim_resleever_actor_probe)
	observe(chair, /datum/act/check_insert, probe, instead(then(TYPE_PROC_REF(/datum/interim_resleever_actor_probe, on_insert))))
	var/obj/item/grab/grab = allocate(/obj/item/grab, actor, patient)
	TEST_ASSERT(!QDELETED(grab), "The real grab must remain live before insertion")
	TEST_ASSERT_EQUAL(grab.grab_target(), patient, "The real grab must hold the intended patient")
	TEST_ASSERT(test_op_handler(chair, "interaction_insert", actor, grab), "The public grab interaction must be handled")
	TEST_ASSERT_EQUAL(probe.last_actor_ref, REF(actor), "The grab initiator must reach the real containment boundary")
	TEST_ASSERT_EQUAL(probe.insert_count, 1, "Successful grab insertion must attempt exactly one slot insertion")
	TEST_ASSERT_EQUAL(chair.slot_item(OCCUPANT_SLOT_IMPLANT_CHAIR), patient, "The chair must seat the grabbed patient")
	TEST_ASSERT_EQUAL(patient.loc, chair, "The patient must actually move inside the chair")
	TEST_ASSERT_EQUAL(chair.icon_state, "implantchair_on", "Successful seating must select occupied presentation")
	TEST_ASSERT(QDELETED(grab), "Successful seating must consume the original grab")
	var/obj/item/grab/second_grab = allocate(/obj/item/grab, actor, other)
	TEST_ASSERT(!QDELETED(second_grab), "The second real grab must start live")
	test_op_handler(chair, "interaction_insert", actor, second_grab)
	TEST_ASSERT(!QDELETED(second_grab), "Occupied refusal must preserve the unused grab")
	TEST_ASSERT_EQUAL(other.loc, T, "Occupied refusal must leave the second patient outside")
	TEST_ASSERT_EQUAL(probe.insert_count, 1, "Occupied refusal must not enter the slot transaction")
	TEST_ASSERT_EQUAL(chair.slot_item(OCCUPANT_SLOT_IMPLANT_CHAIR), patient, "Occupied refusal must preserve the original patient")
	chair.go_out(patient)
	TEST_ASSERT_EQUAL(chair.slot_item(OCCUPANT_SLOT_IMPLANT_CHAIR), patient, "The occupant must remain unable to eject themselves")
	chair.go_out(actor)
	TEST_ASSERT_NULL(chair.slot_item(OCCUPANT_SLOT_IMPLANT_CHAIR), "External ejection must clear the actual occupant slot")
	TEST_ASSERT_EQUAL(patient.loc, T, "External ejection must return the patient to the floor")
	TEST_ASSERT_EQUAL(chair.icon_state, "implantchair", "Ejection must restore unoccupied presentation")
	dq_machine_clear(chair)
	TEST_ASSERT(chair.operable(), "The self-entry fixture must be operable")
	test_op_handler(chair, "interaction_move_inside", actor)
	TEST_ASSERT_EQUAL(probe.last_actor_ref, REF(actor), "Self-entry must forward its initiator to the slot boundary")
	TEST_ASSERT_EQUAL(probe.insert_count, 2, "Self-entry must perform a fresh actual insertion")
	TEST_ASSERT_EQUAL(chair.slot_item(OCCUPANT_SLOT_IMPLANT_CHAIR), actor, "Self-entry must seat the initiating actor")
	TEST_ASSERT_EQUAL(actor.loc, chair, "Self-entry must move the actor inside the machine")
	chair.go_out(patient)
