/datum/unit_test/interim_range_explicit_center/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/diagonal = get_step(T, NORTHEAST)
	var/turf/distant = get_step(get_step(T, EAST), EAST)
	TEST_ASSERT_NOTNULL(diagonal, "the fixture has a diagonal neighbor")
	TEST_ASSERT_NOTNULL(distant, "the fixture has a turf outside radius one")
	var/obj/item/binoculars/center = allocate(/obj/item/binoculars, T)
	var/obj/item/binoculars/neighbor = allocate(/obj/item/binoculars, diagonal)
	var/list/ultra = urange(1, center)
	var/list/spiral = spiral_range(1, center)
	var/list/turfs = spiral_range_turfs(1, center)
	TEST_ASSERT((T in ultra) && (center in ultra) && (diagonal in ultra) && (neighbor in ultra), "ultra range includes the supplied center turf, its object, diagonal and actual neighbor contents")
	TEST_ASSERT((T in spiral) && (center in spiral) && (diagonal in spiral) && (neighbor in spiral), "spiral range includes the same actual square geometry and contents")
	TEST_ASSERT((T in turfs) && (diagonal in turfs) && !(neighbor in turfs), "the turf-only spiral includes square diagonals without object contents")
	TEST_ASSERT(!(distant in ultra) && !(distant in spiral) && !(distant in turfs), "all three helpers exclude turfs beyond the requested radius")
	ultra = urange(1, center, TRUE)
	spiral = spiral_range(1, center, TRUE)
	turfs = spiral_range_turfs(1, center, TRUE)
	TEST_ASSERT(!(T in ultra) && !(center in ultra) && (neighbor in ultra), "orange ultra range excludes the center turf and its contents while retaining neighboring contents")
	TEST_ASSERT(!(T in spiral) && !(center in spiral) && (neighbor in spiral), "orange spiral range excludes the center turf and its contents")
	TEST_ASSERT(!(T in turfs) && (diagonal in turfs), "orange turf spiral excludes only the center turf")
	TEST_ASSERT_EQUAL(length(urange(1)), 0, "omitted ultra center never resolves an ambient actor")
	TEST_ASSERT_EQUAL(length(spiral_range(1)), 0, "omitted spiral center never resolves an ambient actor")
	TEST_ASSERT_EQUAL(length(spiral_range_turfs(1)), 0, "omitted turf spiral center never resolves an ambient actor")
	TEST_ASSERT_EQUAL(length(urange(1, null)), 0, "explicit null ultra center safely returns an empty list")
	var/list/reused = list(center)
	TEST_ASSERT(spiral_range_turfs(1, null, FALSE, reused) == reused, "the turf helper retains its caller-owned output list identity")
	TEST_ASSERT_EQUAL(length(reused), 0, "a missing center clears stale entries in the supplied output list")
	var/list/zero_ultra = urange(0, center)
	var/list/zero_turfs = spiral_range_turfs(0, center, TRUE)
	TEST_ASSERT_EQUAL(length(zero_ultra), 1, "zero-radius ultra preserves its original singleton behavior")
	TEST_ASSERT_EQUAL(zero_ultra[1], center, "zero-radius ultra returns the supplied object rather than its turf")
	TEST_ASSERT_EQUAL(length(zero_turfs), 1, "zero-radius turf spiral retains its existing singleton even with orange")
	TEST_ASSERT_EQUAL(zero_turfs[1], center, "zero-radius turf spiral preserves the supplied center object")
