/// A surviving card must still support the actual unfold and fold operations.
/datum/unit_test/interim_pai_card_folding/Run()
	var/turf/T = test_floor()
	var/obj/item/paicard/card = allocate(/obj/item/paicard, T)
	var/mob/living/silicon/pai/personality = allocate(/mob/living/silicon/pai, card)
	card.setPersonality(personality)
	personality.fold_out()
	TEST_ASSERT_EQUAL(personality.loc, T, "The real unfolding verb must place the personality on the floor")
	TEST_ASSERT_EQUAL(card.loc, personality, "The unfolded personality must carry its actual card")
	personality.close_up(TRUE)
	TEST_ASSERT_EQUAL(personality.loc, card, "Normal close_up must still fold into the surviving card")
	TEST_ASSERT_EQUAL(card.loc, T, "Normal close_up must return the card to the actual floor")
	TEST_ASSERT_EQUAL(personality.card, card, "Normal folding must preserve the actual card relation")
	TEST_ASSERT_EQUAL(card.pai, personality, "Normal folding must preserve the actual personality relation")
	TEST_ASSERT_EQUAL(personality.stat, CONSCIOUS, "Normal folding must not kill the personality")

/// Card deletion must kill its actual unfolded pAI without folding into a missing card.
/datum/unit_test/interim_pai_card_deletion/Run()
	var/turf/T = test_floor()
	var/obj/item/paicard/card = allocate(/obj/item/paicard, T)
	var/mob/living/silicon/pai/personality = allocate(/mob/living/silicon/pai, card)
	card.setPersonality(personality)
	personality.fold_out()
	TEST_ASSERT_EQUAL(personality.loc, T, "The actual unfolding verb must create the floor fixture")
	TEST_ASSERT_EQUAL(card.loc, personality, "The actual unfolded card must be carried by its personality")
	TEST_ASSERT_EQUAL(personality.stat, CONSCIOUS, "The personality must actually be alive before card deletion")
	qdel(card)
	TEST_ASSERT(QDELETED(card), "The actual card must be deleted")
	TEST_ASSERT(!QDELETED(personality), "Card deletion must preserve the personality's dead body")
	TEST_ASSERT_EQUAL(personality.stat, DEAD, "The card's declared deletion consequence must kill the actual pAI")
	TEST_ASSERT_NULL(personality.card, "Card deletion must clear the incoming card relation")
	TEST_ASSERT_EQUAL(personality.loc, T, "The dead unfolded personality must stay on the actual floor")
	personality.close_up(TRUE)
	TEST_ASSERT_EQUAL(personality.loc, T, "An explicit missing-card fold attempt must preserve the floor body")
	TEST_ASSERT_EQUAL(personality.stat, DEAD, "A missing-card fold attempt must preserve the actual death state")
