/// The actual lathe drop layout changes only for actors accepted by its existing drag guards.
/datum/unit_test/interim_autolathe_drop_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/east = get_step(T, EAST)
	var/turf/north = get_step(T, NORTH)
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(east) && isfloorturf(north) && isfloorturf(far), "actual neighboring and distant floors exist for the layout fixture")
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, far)
	var/mob/observer/dead/ghost = allocate(/mob/observer/dead, T)
	ghost.forceMove(T)
	var/obj/machinery/autolathe/lathe = allocate(/obj/machinery/autolathe, T)
	TEST_ASSERT(!om_busy(lathe), "the actual newly created lathe is not printing")
	TEST_ASSERT_EQUAL(lathe.drop_direction, 0, "the actual lathe starts without a chosen drop direction")
	TEST_ASSERT_NULL(lathe.choose_drop_with_actor(actor, east), "a successful layout choice retains the original null return")
	TEST_ASSERT_EQUAL(lathe.drop_direction, EAST, "the actual nearby actor chooses the real east landing direction")
	TEST_ASSERT(!lathe.Adjacent(bystander), "the actual unrelated mob is too distant for the source guard")
	lathe.choose_drop_with_actor(bystander, north)
	lathe.choose_drop_with_actor(ghost, north)
	TEST_ASSERT_EQUAL(lathe.drop_direction, EAST, "actual distant and observer refusals retain the previous real layout")
	lathe.choose_drop_with_actor(actor, T)
	TEST_ASSERT_EQUAL(lathe.drop_direction, EAST, "an actual zero-direction landing leaves the chosen layout unchanged")
	lathe.choose_drop_with_actor(actor, north)
	TEST_ASSERT_EQUAL(lathe.drop_direction, NORTH, "the same accepted actor can select a different real landing")
	TEST_ASSERT(lathe.can_reset_drop(actor, lathe, null), "the real reset requirement allows an idle configured lathe")
	lathe.interaction_reset_drop(actor, null, null)
	TEST_ASSERT_EQUAL(lathe.drop_direction, 0, "the actual reset interaction clears the chosen layout")
	TEST_ASSERT(!om_busy(lathe), "layout selection and reset never start real printing work")
