/// Both actual nuclear authentication insertion routes respect sticky inventory release before recording the disk.
/datum/unit_test/interim_nuclear_sticky_auth_disk/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	for(var/route in list("item", "ui"))
		var/obj/machinery/nuclearbomb/bomb = allocate(/obj/machinery/nuclearbomb, T)
		var/obj/item/disk/nuclear/disk = allocate(/obj/item/disk/nuclear, T)
		bomb.extended = TRUE
		TEST_ASSERT(!bomb.timing && bomb.safety, "the actual test bomb remains safe and unarmed")
		TEST_ASSERT(user.put_in_active_hand(disk), "the actor holds the real authentication disk")
		add_trait(disk, TRAIT_NODROP, "interim_nuclear_sticky_disk")
		TEST_ASSERT(user.release_refusal(disk, user), "the actual inventory refuses release of the held disk")
		if(route == "item")
			test_op_handler(bomb, "interaction_insert_disk", user, disk)
		else
			op_ui_act(user, bomb, "auth")
		TEST_ASSERT_NULL(bomb.auth(), "refused [route] release records no authentication relation")
		TEST_ASSERT_EQUAL(disk.loc, user, "refused [route] release preserves actual inventory containment")
		TEST_ASSERT_EQUAL(user.get_active_hand(), disk, "refused [route] release preserves the exact hand")
		remove_trait(disk, TRAIT_NODROP, "interim_nuclear_sticky_disk")
		if(route == "item")
			test_op_handler(bomb, "interaction_insert_disk", user, disk)
		else
			op_ui_act(user, bomb, "auth")
		TEST_ASSERT_EQUAL(bomb.auth(), disk, "allowed [route] insertion records the original disk")
		TEST_ASSERT_EQUAL(disk.loc, bomb, "allowed [route] insertion physically contains the original disk")
		TEST_ASSERT_NULL(user.get_active_hand(), "allowed [route] insertion clears the source hand")
		TEST_ASSERT_NULL(owner_of(disk), "the authentication relation does not invent disk ownership")
		bomb.yes_code = TRUE
		op_ui_act(user, bomb, "auth")
		TEST_ASSERT_NULL(bomb.auth(), "actual UI ejection clears the authentication relation")
		TEST_ASSERT_EQUAL(disk.loc, T, "actual UI ejection returns the original disk to the floor")
		TEST_ASSERT(!bomb.yes_code, "actual UI ejection invalidates the entered code")
		qdel(bomb)
		TEST_ASSERT(!QDELETED(disk), "safe empty bomb teardown preserves the returned original disk")
		TEST_ASSERT_EQUAL(disk.loc, T, "empty bomb teardown leaves the returned disk on the actual floor")
