// Exercises the actual stock model's offer-to-loan ownership transfer, without a budget transaction.
/datum/unit_test/interim_stock_loan_ownership

/datum/unit_test/interim_stock_loan_ownership/Run()
	var/datum/stock/company = allocate(/datum/stock)
	var/datum/stock/independent = allocate(/datum/stock)
	var/datum/borrow/first = allocate(/datum/borrow)
	var/datum/borrow/second = allocate(/datum/borrow)
	var/datum/borrow/control = allocate(/datum/borrow)
	rel_add(company, nameof(company.borrow_brokers), first)
	rel_add(company, nameof(company.borrow_brokers), second)
	rel_add(independent, nameof(independent.borrow_brokers), control)
	TEST_ASSERT_EQUAL(owner_of(first), company, "The original offer belongs to its stock")
	TEST_ASSERT_EQUAL(own_transfer(company, nameof(company.borrow_brokers), company, nameof(company.borrows), first), first, "The actual acceptance transfer retains the exact first record")
	TEST_ASSERT(islist(company.borrows), "Accepted loans are a many-slot list, including the first loan")
	TEST_ASSERT_EQUAL(length(company.borrows), 1, "The first loan occupies exactly one entry")
	TEST_ASSERT_EQUAL(company.borrows[1], first, "The accepted loan is the original offer")
	TEST_ASSERT(!(first in company.borrow_brokers), "The accepted loan leaves the offer list")
	TEST_ASSERT_EQUAL(owner_of(first), company, "Acceptance retains stock ownership")
	TEST_ASSERT_EQUAL(own_transfer(company, nameof(company.borrow_brokers), company, nameof(company.borrows), second), second, "The second exact offer transfers into the same many slot")
	TEST_ASSERT_EQUAL(length(company.borrows), 2, "Both distinct accepted loans remain in the stock")
	TEST_ASSERT((first in company.borrows) && (second in company.borrows), "Acceptance preserves both original records")
	TEST_ASSERT_EQUAL(length(company.borrow_brokers), 0, "Both offers have left the broker list")
	qdel(company)
	TEST_ASSERT(QDELETED(first) && QDELETED(second), "Stock teardown disposes both accepted owned loans")
	TEST_ASSERT(!QDELETED(control), "Another stock's exact offer survives")
	TEST_ASSERT_EQUAL(owner_of(control), independent, "Independent offer custody is unchanged")
	TEST_ASSERT(control in independent.borrow_brokers, "The independent stock still holds its original offer")
