/// Actual pAI HUD dispatch downloads and toggles the explicit actor's real translator.
/datum/unit_test/om/interim_pai_hud_actor/run_om(list/made)
	test_prompts_reset()
	var/mob/living/silicon/pai/actor = allocate(/mob/living/silicon/pai, run_loc_floor_bottom_left)
	var/mob/living/silicon/pai/bystander = allocate(/mob/living/silicon/pai, run_loc_floor_bottom_left)
	own(actor.card)
	own(bystander.card)
	var/datum/hud/actor_hud = allocate(/datum/hud, actor)
	var/datum/hud/bystander_hud = allocate(/datum/hud, bystander)
	TEST_ASSERT_EQUAL(actor.hud_used, actor_hud, "the actual HUD constructor installs the actor's owned HUD")
	TEST_ASSERT_EQUAL(bystander.hud_used, bystander_hud, "the actual other HUD belongs to its own pAI")
	var/atom/movable/screen/pai/button
	for(var/atom/movable/screen/pai/candidate as anything in actor_hud.other)
		if(candidate.name == "universal translator")
			button = candidate
	TEST_ASSERT_NOTNULL(button, "the real pAI HUD creates its actual translator button")
	var/datum/pai_software/translator/translator = GLOB.pai_software_by_key["translator"]
	TEST_ASSERT(istype(translator), "the actual global software catalog contains the translator")
	TEST_ASSERT(!actor.software[translator.id], "the actor starts without downloaded translator software")
	TEST_ASSERT(!bystander.software[translator.id], "the other pAI starts without translator software")
	var/original_ram = actor.ram
	km_synthetic_click(actor, button)
	var/datum/prompt/yes_no/pai_download/ask = SSrequests.open_for(actor)
	TEST_ASSERT_NOTNULL(ask, "the actual native pAI click opens a real download confirmation")
	TEST_ASSERT_EQUAL(ask.answerer, actor, "the real native download prompt retains its exact pAI actor")
	TEST_ASSERT_EQUAL(ask.software_key, translator.id, "the actual prompt requests precisely translator software")
	test_answer(actor, TRUE)
	TEST_ASSERT(actor.software[translator.id], "the actual answer installs the requested software")
	TEST_ASSERT_EQUAL(actor.ram, original_ram - translator.ram_cost, "the actual download charges the exact software cost once")
	TEST_ASSERT(!actor.translator_on, "downloading preserves the initial translator-off state")
	TEST_ASSERT(!bystander.software[translator.id], "the native actor's download does not install software for the other pAI")
	TEST_ASSERT(!(GLOB.all_languages[LANGUAGE_UNATHI] in actor.languages), "the actor starts without the translator's Unathi grant")
	km_synthetic_click(actor, button)
	TEST_ASSERT(actor.translator_on, "the actual native HUD toggle activates the installed translator")
	TEST_ASSERT(GLOB.all_languages[LANGUAGE_UNATHI] in actor.languages, "the actual translator grants its real language")
	TEST_ASSERT_EQUAL(button.icon_state, button.base_state, "the actual software refresh updates the real HUD button")
	TEST_ASSERT(!bystander.translator_on, "the actual native click leaves the other pAI translator off")
	TEST_ASSERT_EQUAL(button.click_with_actor(actor, null, null, null), 1, "the direct helper preserves the inherited handled return")
	TEST_ASSERT(!actor.translator_on, "the explicit actor helper actually toggles its translator off")
	TEST_ASSERT(!(GLOB.all_languages[LANGUAGE_UNATHI] in actor.languages), "the actual off toggle removes its real language grant")
	TEST_ASSERT_EQUAL(button.icon_state, "[button.base_state]_o", "the actual off toggle restores its real HUD icon")
	button.click_with_actor(bystander, null, null, null)
	var/datum/prompt/yes_no/pai_download/other_ask = SSrequests.open_for(bystander)
	TEST_ASSERT_NOTNULL(other_ask, "a different explicit pAI opens its own real download prompt")
	TEST_ASSERT_EQUAL(other_ask.answerer, bystander, "the direct helper preserves the explicit other actor")
	test_answer(bystander, null, REQ_CANCELLED)
	TEST_ASSERT(!bystander.software[translator.id], "actual cancellation installs no software for the other pAI")
	actor.set_stat(UNCONSCIOUS)
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT(!actor.translator_on, "the actual software requirement refuses an unconscious pAI")
	actor.set_stat(CONSCIOUS)
	var/mob/living/carbon/human/unsupported = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	button.click_with_actor(unsupported, null, null, null)
	button.click_with_actor(null, null, null, null)
	TEST_ASSERT_NULL(SSrequests.open_for(unsupported), "unsupported and null actors open no additional software prompt")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "the refused click opened no prompt for the pAI either")
	TEST_ASSERT(!actor.translator_on && !bystander.translator_on, "refused actors preserve both actual translator states")
	TEST_ASSERT_EQUAL(actor.ram, original_ram - translator.ram_cost, "toggles/refusals charge no additional RAM")
