/// A laser pointer's actual removable diode respects inventory release and retains its original ownership policy.
/datum/unit_test/interim_laser_pointer_sticky_diode/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/laser_pointer/pointer = allocate(/obj/item/laser_pointer, T)
	var/obj/item/tool/screwdriver/tool = allocate(/obj/item/tool/screwdriver, T)
	var/obj/item/stock_parts/micro_laser/diode = pointer.diode
	TEST_ASSERT(istype(diode) && !QDELETED(diode), "actual initialized pointer creates a live original micro laser")
	TEST_ASSERT_EQUAL(diode.loc, pointer, "original default diode is physically contained")
	TEST_ASSERT_EQUAL(owner_of(diode), pointer, "actual default diode is owned by original pointer")
	own(diode)
	TEST_ASSERT(user.put_in_active_hand(tool), "actor holds real canonical screwdriver")
	pointer.screwdriver_act(user, tool)
	TEST_ASSERT_NULL(pointer.diode, "actual screwdriver action clears loaded diode field")
	TEST_ASSERT_EQUAL(diode.loc, T, "actual removal refunds exact original diode to floor")
	TEST_ASSERT_NULL(owner_of(diode), "actual removal releases original diode ownership stamp")
	TEST_ASSERT(user.unEquip(tool, T), "actor legitimately releases screwdriver")
	TEST_ASSERT(user.put_in_active_hand(diode), "actor holds exact original refunded diode")
	add_trait(diode, TRAIT_NODROP, "interim_pointer_diode")
	TEST_ASSERT(user.release_refusal(diode, user), "actual inventory refuses sticky original diode")
	pointer.interaction_item(user, diode, null)
	TEST_ASSERT_NULL(pointer.diode, "refused insertion leaves pointer empty")
	TEST_ASSERT_EQUAL(user.get_active_hand(), diode, "refused insertion preserves exact original hand")
	TEST_ASSERT_EQUAL(diode.loc, user, "refused insertion preserves original inventory containment")
	TEST_ASSERT_NULL(owner_of(diode), "refused insertion creates no pointer ownership stamp")
	remove_trait(diode, TRAIT_NODROP, "interim_pointer_diode")
	pointer.interaction_item(user, diode, null)
	TEST_ASSERT_EQUAL(pointer.diode, diode, "allowed insertion loads exact original refunded diode")
	TEST_ASSERT_EQUAL(diode.loc, pointer, "allowed insertion physically contains exact original diode")
	TEST_ASSERT_EQUAL(owner_of(diode), pointer, "allowed insertion stamps existing pointer ownership policy")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears actual source hand")
	var/obj/item/stock_parts/micro_laser/replacement = allocate(/obj/item/stock_parts/micro_laser, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "actor holds a second actual diode")
	pointer.interaction_item(user, replacement, null)
	TEST_ASSERT_EQUAL(pointer.diode, diode, "occupied pointer preserves its exact original loaded diode")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "occupied refusal preserves exact second diode hand")
	TEST_ASSERT_EQUAL(replacement.loc, user, "occupied refusal preserves second diode inventory location")
	TEST_ASSERT_NULL(owner_of(replacement), "occupied refusal creates no second ownership stamp")
