/datum/unit_test/dq_eg2/interim_casino_collar_registry_lifetime
/datum/unit_test/dq_eg2/interim_casino_collar_registry_lifetime/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/machinery/casinosentientprize_handler/registry = allocate(/obj/machinery/casinosentientprize_handler, T)
	var/obj/item/clothing/accessory/collar/casinosentientprize/first = allocate(/obj/item/clothing/accessory/collar/casinosentientprize, T)
	TEST_ASSERT_EQUAL(LAZYLEN(registry.collar_list), 0, "the actual prize registry starts empty")
	TEST_ASSERT_EQUAL(rel_kind(registry, nameof(registry.collar_list)), OWNK_REL, "the actual field declares a borrowed native reference view before any write")
	rel_add(registry, nameof(registry.collar_list), first)
	TEST_ASSERT_EQUAL(LAZYLEN(registry.collar_list), 1, "the actual native registry accepts one borrowed collar")
	TEST_ASSERT(first in registry.collar_list, "the registered entry is the exact original collar")
	TEST_ASSERT_EQUAL(first.loc, T, "registering does not move a borrowed collar into the machinery")
	TEST_ASSERT(consume(first), "a real unheld collar can be retired through checked consumption")
	test_time(0.1 SECONDS)
	TEST_ASSERT(QDELETED(first), "the first actual collar was retired")
	TEST_ASSERT_EQUAL(LAZYLEN(registry.collar_list), 0, "retiring a registered collar prunes the actual native reference field")
	var/obj/item/clothing/accessory/collar/casinosentientprize/second = allocate(/obj/item/clothing/accessory/collar/casinosentientprize, T)
	rel_add(registry, nameof(registry.collar_list), second)
	TEST_ASSERT_EQUAL(LAZYLEN(registry.collar_list), 1, "the same production registry accepts another real collar")
	TEST_ASSERT(second in registry.collar_list, "the second registered entry retains its original identity")
	TEST_ASSERT(consume(registry), "the actual registry can be retired on its floor")
	test_time(0.1 SECONDS)
	TEST_ASSERT(QDELETED(registry), "the actual reference holder was retired")
	TEST_ASSERT(!QDELETED(second), "retiring the registry leaves its borrowed collar alive")
	TEST_ASSERT_EQUAL(second.loc, T, "the surviving original collar remains on its actual floor")
