/// The actual cartridge hypospray refuses an occupied vial bay, loads a real mixed vial after its delay, then returns the exact mixture on public ejection.
/datum/unit_test/om/interim_hypospray_vial_transfer/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/hypospray/vial/hypo = allocate(/obj/item/reagent_containers/hypospray/vial, T)
	var/obj/item/reagent_containers/glass/beaker/vial/candidate = allocate(/obj/item/reagent_containers/glass/beaker/vial, T)
	var/obj/item/reagent_containers/glass/beaker/vial/original = hypo.loaded_vial
	made += list(user, hypo, candidate, original)
	TEST_ASSERT_NOTNULL(original, "the actual cartridge hypospray starts with its empty original vial")
	TEST_ASSERT_EQUAL(hypo.reagents.total_volume, 0, "the actual hypospray initially contains no liquid")
	TEST_ASSERT_EQUAL(candidate.reagents.maximum_volume, 30, "the real candidate vial holds thirty units")
	candidate.reagents.add_reagent(REAGENT_ID_WATER, 24)
	candidate.reagents.add_reagent(REAGENT_ID_ETHANOL, 6)
	TEST_ASSERT(user.put_in_inactive_hand(hypo), "the actual actor holds the hypospray in the removal hand")
	TEST_ASSERT(user.put_in_active_hand(candidate), "the actual actor holds the real mixed replacement vial")
	hypo.interaction_item(user, candidate, null)
	TEST_ASSERT(!LAZYLEN(user.do_afters), "an occupied actual vial bay starts no replacement task")
	TEST_ASSERT_EQUAL(hypo.loaded_vial, original, "occupied-bay refusal preserves the exact original vial")
	TEST_ASSERT_EQUAL(candidate.reagents.total_volume, 30, "occupied-bay refusal transfers none of the replacement mixture")
	TEST_ASSERT_EQUAL(user.get_active_hand(), candidate, "occupied-bay refusal preserves the held candidate")
	TEST_ASSERT(hypo.interaction_hand(user, null, null), "the public removal entry ejects the actual original vial")
	TEST_ASSERT_NULL(hypo.loaded_vial, "actual original-vial ejection empties the ownership view")
	TEST_ASSERT_EQUAL(original.loc, T, "both actual occupied hands cause the original empty vial to land on the floor")
	TEST_ASSERT_EQUAL(hypo.reagents.maximum_volume, 0, "actual original-vial ejection disables the hypospray reservoir")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual vial-loading actor starts capable")
	hypo.interaction_item(user, candidate, null)
	TEST_ASSERT(LAZYLEN(user.do_afters), "the actual mixed-vial loading entry starts its timed task")
	TEST_ASSERT_NULL(hypo.loaded_vial, "starting actual vial loading does not adopt early")
	TEST_ASSERT_EQUAL(candidate.reagents.total_volume, 30, "starting actual vial loading transfers no liquid early")
	TEST_ASSERT_EQUAL(hypo.reagents.total_volume, 0, "the pending actual hypospray remains empty")
	scheduler_advance((4 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual vial-loading actor remains capable through its single task")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "completed actual vial loading releases its task")
	TEST_ASSERT_EQUAL(hypo.loaded_vial, candidate, "actual completed loading adopts the exact candidate vial")
	TEST_ASSERT_EQUAL(candidate.loc, hypo, "actual completed loading contains the candidate physically")
	TEST_ASSERT_NULL(user.get_active_hand(), "actual completed loading clears the candidate's former hand")
	TEST_ASSERT(!candidate.is_open_container(), "actual completed loading closes the candidate vial")
	TEST_ASSERT_EQUAL(candidate.reagents.total_volume, 0, "actual completed loading transfers the whole vial mixture out")
	TEST_ASSERT_EQUAL(hypo.reagents.maximum_volume, 30, "actual completed loading restores the thirty-unit reservoir")
	TEST_ASSERT_EQUAL(hypo.reagents.get_reagent_amount(REAGENT_ID_WATER), 24, "actual completed loading transfers exactly twenty-four water units")
	TEST_ASSERT_EQUAL(hypo.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 6, "actual completed loading transfers exactly six ethanol units")
	TEST_ASSERT(hypo.interaction_hand(user, null, null), "the actual public ejection returns the mixed candidate vial")
	TEST_ASSERT_NULL(hypo.loaded_vial, "actual mixed-vial ejection clears the ownership view")
	TEST_ASSERT_EQUAL(user.get_active_hand(), candidate, "actual mixed-vial ejection returns the same vial to the free hand")
	TEST_ASSERT_EQUAL(candidate.reagents.get_reagent_amount(REAGENT_ID_WATER), 24, "actual ejection returns exactly twenty-four water units")
	TEST_ASSERT_EQUAL(candidate.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 6, "actual ejection returns exactly six ethanol units")
	TEST_ASSERT_EQUAL(hypo.reagents.total_volume, 0, "actual ejection leaves no transferred liquid in the hypospray")
	TEST_ASSERT_EQUAL(hypo.reagents.maximum_volume, 0, "actual ejection again disables the uncartridged reservoir")
