/// Harvesting with the actual knife cannot mint seeds while its original sunflower refuses release.
/datum/unit_test/interim_sunflower_sticky_seed_harvest/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/food/snacks/grown/flower = allocate(/obj/item/reagent_containers/food/snacks/grown, T, PLANT_SUNFLOWERS)
	var/obj/item/material/knife/knife = allocate(/obj/item/material/knife, T)
	TEST_ASSERT(!QDELETED(flower) && flower.seed(), "actual sunflower registry initializes a live grown flower")
	TEST_ASSERT_EQUAL(flower.seed().kitchen_tag, PLANT_SUNFLOWERS, "actual seed is the sunflower ingredient")
	TEST_ASSERT(knife.sharp, "actual canonical material knife reaches sharp-tool harvest route")
	TEST_ASSERT(user.put_in_inactive_hand(flower), "actor holds exact original sunflower in inactive hand")
	TEST_ASSERT(user.put_in_active_hand(knife), "actor holds exact original knife in active hand")
	TEST_ASSERT_NULL(locate_within(T, /obj/item/reagent_containers/food/snacks/rawsunflower), "fixture floor starts without harvested seeds")
	add_trait(flower, TRAIT_NODROP, "interim_sunflower_harvest")
	TEST_ASSERT(user.release_refusal(flower, user), "actual inventory refuses sticky original sunflower")
	test_op_handler(flower, "grown_item", user, knife)
	TEST_ASSERT(!QDELETED(flower), "refused harvest preserves original flower alive")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), flower, "refused harvest preserves exact original inactive hand")
	TEST_ASSERT_EQUAL(flower.loc, user, "refused harvest preserves original inventory location")
	TEST_ASSERT_NULL(locate_within(T, /obj/item/reagent_containers/food/snacks/rawsunflower), "refused harvest emits no seed product")
	remove_trait(flower, TRAIT_NODROP, "interim_sunflower_harvest")
	test_op_handler(flower, "grown_item", user, knife)
	TEST_ASSERT(QDELETED(flower), "allowed harvest consumes exact original flower")
	TEST_ASSERT_NULL(user.get_inactive_hand(), "allowed harvest clears original source hand")
	var/products = 0
	for(var/obj/item/reagent_containers/food/snacks/rawsunflower/seeds in T)
		own(seeds)
		products++
		TEST_ASSERT_EQUAL(seeds.type, /obj/item/reagent_containers/food/snacks/rawsunflower, "actual harvest emits exact declared seed type")
		TEST_ASSERT(!QDELETED(seeds), "actual emitted seed product survives")
	TEST_ASSERT_EQUAL(products, 1, "allowed harvest emits exactly one original-ingredient seed product")
	TEST_ASSERT_EQUAL(user.get_active_hand(), knife, "harvest preserves exact original knife hand")
	TEST_ASSERT_EQUAL(knife.loc, user, "harvest preserves knife inventory location")
