/// Actual crossbow unloading preserves ordinary rods and consumes superheated rods into floor shrapnel.
/datum/unit_test/interim_crossbow_rod_unload_lifecycle/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	for(var/heated in list(FALSE, TRUE))
		var/obj/item/gun/launcher/crossbow/bow = allocate(/obj/item/gun/launcher/crossbow, T)
		var/obj/item/arrow/rod/rod = allocate(/obj/item/arrow/rod, T)
		if(heated)
			rod.throwforce = 15
		TEST_ASSERT(user.put_in_inactive_hand(bow), "the actual crossbow occupies the actor's inactive hand")
		TEST_ASSERT(user.put_in_active_hand(rod), "the actual loading rod occupies the actor's active hand")
		test_op_handler(bow, "gun_item", user, rod)
		TEST_ASSERT_EQUAL(bow.bolt, rod, "actual loading installs the supplied rod as the owned bolt")
		TEST_ASSERT_EQUAL(rod.loc, bow, "actual loading transfers the held rod into the crossbow")
		TEST_ASSERT_NULL(user.get_active_hand(), "actual loading releases the rod's original hand slot")
		user.swap_hand()
		TEST_ASSERT_EQUAL(user.get_active_hand(), bow, "the actual loaded crossbow becomes the actor's active item")
		bow.tension = 1
		test_op_handler(bow, "gun_self", user, bow)
		own_turf_contents(T)
		TEST_ASSERT_NULL(bow.bolt, "actual unloading clears the crossbow's owned bolt")
		TEST_ASSERT_EQUAL(bow.tension, 0, "actual unloading releases the crossbow's tension")
		TEST_ASSERT_EQUAL(user.get_active_hand(), bow, "unloading preserves the actor's actual held crossbow")
		if(heated)
			TEST_ASSERT(QDELETED(rod), "unloading consumes the actual superheated rod")
			var/obj/item/material/shard/shrapnel/shard = locate_within(T, /obj/item/material/shard/shrapnel)
			TEST_ASSERT(shard, "the actual superheated rod produces floor shrapnel")
			TEST_ASSERT_EQUAL(shard.material, get_material_by_name(MAT_STEEL), "the actual produced shrapnel retains its steel material")
			TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/material/shard/shrapnel)), 1, "the single spent rod produces exactly one shrapnel shard")
		else
			TEST_ASSERT(!QDELETED(rod), "ordinary unloading preserves the actual cold rod")
			TEST_ASSERT_EQUAL(rod.loc, T, "the actual cold rod is released onto the original turf")
			TEST_ASSERT_NULL(owner_of(rod), "the released cold rod is no longer owned by the crossbow")
			TEST_ASSERT_NULL(locate_within(T, /obj/item/material/shard/shrapnel), "an ordinary cold rod creates no shrapnel")
		user.drop_from_inventory(bow)
