/// Actual grass uprooting consumes the plant without touching an unrelated floor item.
/datum/unit_test/interim_grass_uproot_lifecycle/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/flora/grass/grass = allocate(/obj/structure/flora/grass, T)
	var/obj/item/book/book = allocate(/obj/item/book, T)
	var/obj/item/shovel/tool = allocate(/obj/item/shovel, T)
	TEST_ASSERT(user.put_in_active_hand(tool), "the actor holds the actual removal shovel")
	TEST_ASSERT(!QDELETED(grass), "the actual grass initializes and survives before uprooting")
	test_driver_begin()
	test_click(user, grass, tool)
	test_time(4 SECONDS)
	test_driver_end()
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(grass), "actual uprooting completion consumes the original grass")
	TEST_ASSERT_NULL(locate_within(T, /obj/structure/flora/grass), "uprooting leaves no duplicate grass")
	TEST_ASSERT(!QDELETED(book), "uprooting preserves the unrelated floor book")
	TEST_ASSERT_EQUAL(book.loc, T, "the unrelated book remains on the original floor")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "uprooting keeps the original shovel held")

/// Real pine felling leaves its stump and ten logs; digging the stump preserves those logs.
/datum/unit_test/interim_pine_stump_removal/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/flora/tree/pine/tree = allocate(/obj/structure/flora/tree/pine, T)
	var/obj/item/shovel/tool = allocate(/obj/item/shovel, T)
	TEST_ASSERT(user.put_in_active_hand(tool), "the actor holds the actual stump shovel")
	TEST_ASSERT(!tree.is_stump, "the actual pine begins as a standing tree")
	TEST_ASSERT_EQUAL(tree.product, /obj/item/stack/material/log, "the actual pine declares its wood log product")
	TEST_ASSERT_EQUAL(tree.product_amount, 10, "the actual pine declares ten returned logs")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/log)), 0, "the floor starts without tree logs")
	tree.adjust_health(-tree.max_integrity)
	own_turf_contents(T)
	TEST_ASSERT(!QDELETED(tree), "actual felling preserves the tree as a stump")
	TEST_ASSERT(tree.is_stump, "actual felling marks the same tree as a stump")
	TEST_ASSERT(!tree.density, "the actual stump no longer blocks movement")
	var/list/logs = contents_of(T, /obj/item/stack/material/log)
	var/amount = 0
	for(var/obj/item/stack/material/log/felled as anything in logs)
		amount += felled.get_amount()
	TEST_ASSERT_EQUAL(amount, 10, "actual felling returns exactly ten logs")
	test_driver_begin()
	test_click(user, tree, tool)
	test_time(6 SECONDS)
	test_driver_end()
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(tree), "actual digging completion consumes the original stump")
	TEST_ASSERT_NULL(locate_within(T, /obj/structure/flora/tree/pine), "digging leaves no duplicate pine stump")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/log)), length(logs), "digging creates no extra log stacks")
	amount = 0
	for(var/obj/item/stack/material/log/log as anything in logs)
		TEST_ASSERT(!QDELETED(log), "each original felled log stack survives stump digging")
		TEST_ASSERT_EQUAL(log.loc, T, "each original log remains on the original floor")
		amount += log.get_amount()
	TEST_ASSERT_EQUAL(amount, 10, "digging preserves exactly the ten original logs")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "digging keeps the original shovel held")
