/// Queue selection uses actual metadata and relations without firing any world event.
/datum/unit_test/interim_event_queue_actor/Run()
	test_driver_begin()
	check_queue()
	test_driver_end()

/datum/unit_test/interim_event_queue_actor/proc/check_queue()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	var/datum/event_container/container = allocate(/datum/event_container)
	container.severity = EVENT_LEVEL_MUNDANE
	var/datum/event_meta/first = allocate(/datum/event_meta, EVENT_LEVEL_MUNDANE, "First actual queue fixture", /datum/event/nothing, 1)
	var/datum/event_meta/second = allocate(/datum/event_meta, EVENT_LEVEL_MUNDANE, "Second actual queue fixture", /datum/event/nothing, 1)
	rel_add(container, nameof(container.event_pool), first)
	rel_add(container, nameof(container.event_pool), second)
	rel_add(container, nameof(container.available_events), first)
	rel_add(container, nameof(container.available_events), second)
	// The panel's select_event button (an admin's, on one of the event system's containers) asks the container to select.
	container.SelectEvent(actor)
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/choice/queue_event), "the actual container creates one native selection prompt")
	var/datum/prompt/choice/queue_event/ask = SSrequests.open_for(actor)
	TEST_ASSERT_EQUAL(ask.answerer, actor, "the actual selection prompt uses the panel's explicit actor")
	TEST_ASSERT_EQUAL(ask.owner, container, "the actual selection prompt refers to its container")
	test_answer(actor, first)
	TEST_ASSERT_EQUAL(ask.outcome, REQ_ANSWERED, "the real typed choice queues its selected metadata")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "accepted first choice ends its actual native request")
	TEST_ASSERT_EQUAL(container.next_event(), first, "the actual next-event relation resolves the selected object")
	TEST_ASSERT(!(first in container.available_events), "the queued event leaves actual random availability")
	TEST_ASSERT(second in container.available_events, "the unselected event remains available")
	container.SelectEvent(actor)
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/choice/queue_event), "a second real request creates a new native selection prompt")
	ask = SSrequests.open_for(actor)
	TEST_ASSERT_EQUAL(ask.answerer, actor, "the second real prompt keeps the explicit actor")
	test_answer(actor, second)
	TEST_ASSERT_EQUAL(ask.outcome, REQ_ANSWERED, "the actual answer replaces the queued event")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "accepted replacement ends its actual native request")
	TEST_ASSERT_EQUAL(container.next_event(), second, "the next-event relation resolves the replacement object")
	TEST_ASSERT(first in container.available_events, "replacement restores the previous event to actual availability")
	TEST_ASSERT(!(second in container.available_events), "replacement removes its newly queued event from availability")
	TEST_ASSERT_EQUAL(owner_of(first), container, "queue replacement preserves ownership of the first metadata")
	TEST_ASSERT_EQUAL(owner_of(second), container, "queue replacement preserves ownership of the second metadata")

/datum/unit_test/interim_event_queue_stale_choice/Run()
	test_driver_begin()
	check_queue()
	test_driver_end()

/datum/unit_test/interim_event_queue_stale_choice/proc/check_queue()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	var/datum/event_container/container = allocate(/datum/event_container)
	container.severity = EVENT_LEVEL_MUNDANE
	var/datum/event_meta/event = allocate(/datum/event_meta, EVENT_LEVEL_MUNDANE, "Actual stale queue fixture", /datum/event/nothing, 1)
	rel_add(container, nameof(container.event_pool), event)
	rel_add(container, nameof(container.available_events), event)
	container.SelectEvent(actor)
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/choice/queue_event), "the real container opens its initial native event choice")
	var/datum/prompt/choice/queue_event/ask = SSrequests.open_for(actor)
	rel_remove(container, nameof(container.available_events), event)
	test_answer(actor, event)
	TEST_ASSERT_EQUAL(ask.outcome, REQ_CANCELLED, "the actual validity guard refuses metadata no longer available")
	TEST_ASSERT_EQUAL(ask.last_error, "not available", "stale offered metadata reaches the current-availability requirement")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "rejected stale choice ends its actual native request")
	TEST_ASSERT_NULL(container.next_event(), "a stale answer cannot install an actual queued event")
	TEST_ASSERT_EQUAL(owner_of(event), container, "the refusal preserves actual metadata ownership")
