/// Actual N2O mine crossings add the original thirty moles to every eligible nearby floor.
/datum/unit_test/interim_n2o_mine_cleanup/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/mob/living/simple_mob/animal/passive/mouse/mouse = allocate(/mob/living/simple_mob/animal/passive/mouse, T)
	var/obj/effect/mine/n2o/mine = allocate(/obj/effect/mine/n2o, T)
	var/list/floors = list()
	for(var/turf/simulated/floor/floor in range(1, mine))
		if(!floor.blocks_air)
			var/datum/gas_mixture/air = floor.return_air()
			TEST_ASSERT(air, "real eligible mine floor has an atmosphere")
			var/n2o_before = air.get_moles(GAS_N2O)
			var/temperature_before = air.return_temperature()
			defer_cleanup(src, PROC_REF(restore_floor_atmosphere), floor, n2o_before, temperature_before)
			floors += list(list(floor, n2o_before, temperature_before))
	TEST_ASSERT(length(floors) > 0, "actual N2O fixture has eligible payload destinations")
	TEST_ASSERT(mouse.mob_size <= MOB_TINY, "actual mouse meets the tiny-victim exemption")
	mine.Bumped(mouse)
	TEST_ASSERT(!QDELETED(mine) && !mine.triggered, "actual tiny crossing preserves the untriggered gas mine")
	for(var/list/entry as anything in floors)
		var/turf/simulated/floor/floor = entry[1]
		var/datum/gas_mixture/air = floor.return_air()
		TEST_ASSERT(abs(air.get_moles(GAS_N2O) - entry[2]) < 0.01, "actual tiny crossing releases no N2O payload")
	mine.Bumped(user)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(mine), "actual full-size crossing consumes the N2O mine")
	for(var/list/entry as anything in floors)
		var/turf/simulated/floor/floor = entry[1]
		var/datum/gas_mixture/air = floor.return_air()
		TEST_ASSERT(abs(air.get_moles(GAS_N2O) - (entry[2] + 30)) < 0.01, "actual N2O detonation adds exactly thirty moles at every eligible destination")
	TEST_ASSERT(!(mine in T.dangerous_objects), "actual N2O mine teardown clears the source floor danger index")
	TEST_ASSERT(!QDELETED(user) && !QDELETED(mouse), "actual gas-mine cleanup preserves both real victims")

/// Registered before detonation; teardown restores every snapshot even after an assertion or runtime.
/datum/unit_test/interim_n2o_mine_cleanup/proc/restore_floor_atmosphere(turf/simulated/floor/floor, original_n2o, original_temperature)
	var/datum/gas_mixture/air = floor.return_air()
	air.set_moles(GAS_N2O, original_n2o)
	air.set_temperature(original_temperature)

/// Actual incendiary crossings preserve tiny victims but ignite a full-size human before cleanup.
/datum/unit_test/interim_incendiary_mine_cleanup/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/mob/living/simple_mob/animal/passive/mouse/mouse = allocate(/mob/living/simple_mob/animal/passive/mouse, T)
	var/obj/effect/mine/incendiary/mine = allocate(/obj/effect/mine/incendiary, T)
	TEST_ASSERT_NULL(user.fire_stacks, "actual human starts without combustible stacks")
	TEST_ASSERT(!user.on_fire, "actual human starts without an active fire")
	TEST_ASSERT_EQUAL(user.fire_reaction, FIRE_REACTION_BURN, "actual human uses the normal burn reaction")
	mine.Bumped(mouse)
	TEST_ASSERT(!QDELETED(mine) && !mine.triggered, "actual tiny crossing preserves the untriggered incendiary mine")
	TEST_ASSERT(!mouse.on_fire, "actual tiny crossing does not ignite the exempt mouse")
	mine.Bumped(user)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(mine), "actual full-size crossing consumes the incendiary mine")
	TEST_ASSERT(user.on_fire, "actual detonation ignites the real human victim")
	TEST_ASSERT_EQUAL(user.fire_stacks, 7, "actual detonation preserves five payload stacks plus two from the normal fire reaction")
	TEST_ASSERT(!(mine in T.dangerous_objects), "actual incendiary teardown clears the source floor danger index")
	TEST_ASSERT(!QDELETED(user) && !QDELETED(mouse), "actual incendiary cleanup preserves both real victims")
	user.extinguish_mob()
	TEST_ASSERT(!user.on_fire, "actual cleanup extinguishes the fixture's real fire")
