/// A real toolbox's size ceiling refuses a held backpack even when its remaining capacity could pay that backpack's storage cost, while a normal cell inserts and removes normally.
/datum/unit_test/interim_toolbox_size_refusal/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/toolbox/toolbox = allocate(/obj/item/storage/toolbox, T)
	var/obj/item/storage/backpack/large = allocate(/obj/item/storage/backpack, T)
	var/obj/item/cell/cell = allocate(/obj/item/cell, T)
	TEST_ASSERT_EQUAL(toolbox.slot_used(CONTAINER_SLOT_STORAGE), 0, "the actual base toolbox starts empty")
	TEST_ASSERT_EQUAL(cell.w_class, ITEMSIZE_NORMAL, "the actual cell is at the toolbox's permitted size ceiling")
	TEST_ASSERT(large.w_class > cell.w_class, "the actual backpack exceeds the normal cell's size")
	TEST_ASSERT(user.put_in_inactive_hand(large), "the actual actor holds the oversized backpack in the inactive hand")
	TEST_ASSERT(user.put_in_active_hand(cell), "the actual actor holds the normal cell in the active hand")
	var/charge_before = cell.charge
	TEST_ASSERT(toolbox.insert_item(cell, user), "the actual toolbox accepts the normal-sized held cell")
	TEST_ASSERT_EQUAL(cell.loc, toolbox, "accepted insertion places the actual cell in the toolbox")
	TEST_ASSERT_NULL(user.get_active_hand(), "accepted insertion releases the actual active inventory slot")
	var/used_before = toolbox.slot_used(CONTAINER_SLOT_STORAGE)
	TEST_ASSERT_EQUAL(used_before, cell.get_storage_cost(), "actual cell insertion charges its storage cost exactly")
	TEST_ASSERT(used_before + large.get_storage_cost() <= toolbox.max_storage_space, "the real remaining toolbox capacity could pay the backpack's cost")
	TEST_ASSERT_NOTNULL(toolbox.insert_refusal(large, user), "the actual toolbox still rejects the oversized held backpack despite spare capacity")
	TEST_ASSERT(!toolbox.insert_item(large, user), "the actual insertion path enforces the toolbox size ceiling")
	TEST_ASSERT_EQUAL(large.loc, user, "size refusal keeps the real backpack on its actor")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), large, "size refusal preserves the backpack's exact held slot")
	TEST_ASSERT_EQUAL(toolbox.slot_used(CONTAINER_SLOT_STORAGE), used_before, "size refusal preserves the actual used capacity")
	TEST_ASSERT_EQUAL(length(toolbox.slot_contents(CONTAINER_SLOT_STORAGE)), 1, "size refusal preserves the one actual accepted occupant")
	TEST_ASSERT(cell in toolbox.slot_contents(CONTAINER_SLOT_STORAGE), "size refusal preserves the actual installed cell ledger entry")
	TEST_ASSERT(!(large in toolbox.slot_contents(CONTAINER_SLOT_STORAGE)), "size refusal creates no backpack ledger entry")
	TEST_ASSERT(toolbox.remove_from_storage(cell, T, user), "the actual accepted cell can be removed to the floor")
	TEST_ASSERT_EQUAL(cell.loc, T, "actual removal puts the original cell on the floor")
	TEST_ASSERT_EQUAL(toolbox.slot_used(CONTAINER_SLOT_STORAGE), 0, "actual removal refunds all of the cell's capacity cost")
	TEST_ASSERT_EQUAL(cell.charge, charge_before, "the actual storage round trip preserves stored cell charge")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), large, "the successful cell round trip preserves the previously refused backpack")
