/// A sealed package must not roll physical contraband before its original wrapper is consumed.
/datum/unit_test/interim_contraband_sticky_unwrapping/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/contraband/package = allocate(/obj/item/contraband, T)
	TEST_ASSERT(user.put_in_active_hand(package), "the actor holds the exact original sealed package")
	var/floor_items_before = length(contents_of(T, /obj/item))
	var/held_items_before = length(contents_of(user, /obj/item))
	add_trait(package, TRAIT_NODROP, "interim_contraband_sticky")
	TEST_ASSERT(user.release_refusal(package, user), "actual inventory refuses original package consumption")
	package.interaction_unwrap(user, package, null)
	TEST_ASSERT(!QDELETED(package), "refused unwrapping preserves the exact original wrapper")
	TEST_ASSERT_EQUAL(user.get_active_hand(), package, "refused unwrapping preserves original hand")
	TEST_ASSERT_EQUAL(package.loc, user, "refused unwrapping preserves inventory containment")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item)), floor_items_before, "refused unwrapping creates no physical floor product")
	TEST_ASSERT_EQUAL(length(contents_of(user, /obj/item)), held_items_before, "refused unwrapping creates no physical inventory product")
	remove_trait(package, TRAIT_NODROP, "interim_contraband_sticky")
	package.interaction_unwrap(user, package, null)
	TEST_ASSERT(QDELETED(package), "allowed unwrapping consumes exact original wrapper")
	var/obj/item/product = user.get_active_hand()
	TEST_ASSERT_NOTNULL(product, "allowed unwrapping creates a real product in the freed original hand")
	TEST_ASSERT(product != package && !QDELETED(product), "the real product is a surviving distinct item")
	own(product)
	TEST_ASSERT_EQUAL(product.loc, user, "actual product is physically contained in actor inventory")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item)), floor_items_before, "allowed unwrapping leaves no extra floor product")
	TEST_ASSERT_EQUAL(length(contents_of(user, /obj/item)), held_items_before, "one consumed wrapper is replaced by exactly one direct inventory product")
