/// Emagging the emitter shorts its ID lock open for good: an authorized ID locks it, the card unlocks it, and the ID can no longer relock it.
/datum/unit_test/interim_emitter_emag_lock/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/power/emitter/emitter = allocate(/obj/machinery/power/emitter, T)
	var/obj/item/card/id/id = allocate(/obj/item/card/id, T)
	id.access = list(ACCESS_ENGINE_EQUIP)
	TEST_ASSERT(user.put_in_active_hand(id), "the actor holds an engineering-equipment ID")
	TEST_ASSERT(emitter.allowed(user), "the held ID grants emitter access")
	TEST_ASSERT(!is_emagged(emitter) && !lock_locked(emitter), "the emitter starts with intact unlocked controls")
	test_click(user, emitter, id)
	test_time(2 SECONDS)
	TEST_ASSERT(lock_locked(emitter), "the ID locks the controls")
	TEST_ASSERT_EQUAL(emag_target(emitter, 1, user), 1, "the emag takes")
	TEST_ASSERT(is_emagged(emitter), "the emitter records its damaged authentication lock")
	TEST_ASSERT(!lock_locked(emitter), "emagging unlocks the controls")
	test_click(user, emitter, id)
	test_time(2 SECONDS)
	TEST_ASSERT(!lock_locked(emitter), "an authorized ID cannot relock the damaged lock")
	TEST_ASSERT_EQUAL(emag_target(emitter, 1, user), EMAG_DECLINED, "a repeated emag is declined")
	TEST_ASSERT(is_emagged(emitter) && !lock_locked(emitter), "the bypassed lock stays bypassed")
	TEST_ASSERT(!emitter.active, "lock and emag operations never switch the emitter on")
	test_driver_end()
