/// Actual folding preserves the cryobag injector through refusals and a full construction roundtrip.
/datum/unit_test/interim_bodybag_fold_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	actor.enable_godmode() // five-second waits pass over this actor several times: a bare human would not stay conscious
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/obj/structure/closet/body_bag/cryobag/bag = allocate(/obj/structure/closet/body_bag/cryobag, T)
	var/obj/item/reagent_containers/syringe/injector = allocate(/obj/item/reagent_containers/syringe, T)
	TEST_ASSERT(!bag.opened, "the real stasis bag begins closed")
	TEST_ASSERT(actor.put_in_active_hand(injector), "the real injector begins held by its actual actor")
	test_click(actor, bag, injector)
	test_time(5 SECONDS)
	TEST_ASSERT_EQUAL(bag.syringe, injector, "actual injector insertion records the exact syringe")
	TEST_ASSERT_EQUAL(owner_of(injector), bag, "actual injector insertion adopts its real ownership")
	TEST_ASSERT_NULL(injector.loc, "actual installed injector retains deliberate nullspace storage")
	test_drag(actor, bag, bystander)
	test_time(5 SECONDS)
	TEST_ASSERT(!QDELETED(bag), "a distinct target refuses the fold")
	TEST_ASSERT_EQUAL(owner_of(injector), bag, "distinct-target refusal retains actual injector ownership")
	TEST_ASSERT(bag.open(), "the actual unused cryobag opens through its real closet API")
	TEST_ASSERT(bag.opened, "the actual open state activates the original folding guard")
	test_drag(actor, bag, actor)
	test_time(5 SECONDS)
	TEST_ASSERT(!QDELETED(bag), "actual open bag cannot fold")
	TEST_ASSERT_EQUAL(bag.syringe, injector, "open refusal retains exact injector identity")
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "a real floor exists outside the closet pickup turf")
	actor.forceMove(far)
	bystander.forceMove(far)
	TEST_ASSERT(bag.close(), "the real closet API closes the actual bag")
	TEST_ASSERT(!bag.used, "actual closing collected no unrelated fixture patient")
	actor.forceMove(T)
	var/obj/item/occupant = allocate(/obj/item, T)
	occupant.forceMove(bag)
	TEST_ASSERT(contents_count(bag) > 0, "a real physical item activates the original contents guard")
	test_drag(actor, bag, actor)
	test_time(5 SECONDS)
	TEST_ASSERT(!QDELETED(bag), "a genuinely occupied bag cannot fold")
	TEST_ASSERT_EQUAL(owner_of(injector), bag, "occupied refusal preserves injector ownership")
	TEST_ASSERT_EQUAL(occupant.loc, bag, "occupied refusal preserves its unrelated physical contents")
	TEST_ASSERT_NULL(locate(/obj/item/bodybag) in T, "all actual refusal paths create no folded duplicate")
	occupant.forceMove(T)
	TEST_ASSERT(!contents_count(bag) && !bag.has_latent(), "the actual empty closed bag meets both original contents preconditions")
	test_drag(actor, bag, actor)
	test_time(5 SECONDS)
	var/obj/item/bodybag/cryobag/folded = locate(/obj/item/bodybag/cryobag) in T
	TEST_ASSERT(istype(folded), "actual collapse returns its concrete cryobag product")
	own(folded)
	TEST_ASSERT_EQUAL(folded.type, bag.item_path, "actual folding uses the exact configured item type")
	TEST_ASSERT_EQUAL(folded.loc, T, "actual folding creates its product at the real bag turf")
	TEST_ASSERT_EQUAL(folded.syringe, injector, "actual cryobag helper transfers the exact injector into its product")
	TEST_ASSERT_EQUAL(owner_of(injector), folded, "actual folding transfers real injector ownership")
	TEST_ASSERT_NULL(bag.syringe, "actual ownership transfer clears the old bag's injector slot")
	test_time(1 SECOND)
	TEST_ASSERT(QDELETED(bag), "the actual source bag expires after folding")
	TEST_ASSERT(!QDELETED(injector), "the actual injector survives old bag teardown")
	TEST_ASSERT(actor.put_in_active_hand(folded), "the real folded cryobag is held for actual deployment")
	test_click(actor, folded, folded, GESTURE_SELF)
	test_time(5 SECONDS)
	var/obj/structure/closet/body_bag/cryobag/rebuilt = locate(/obj/structure/closet/body_bag/cryobag) in T
	TEST_ASSERT_NOTNULL(rebuilt, "actual deployment constructs a replacement stasis bag")
	own(rebuilt)
	TEST_ASSERT(rebuilt != bag, "construction creates a distinct replacement real bag")
	TEST_ASSERT_EQUAL(rebuilt.syringe, injector, "the full real roundtrip retains exact injector identity")
	TEST_ASSERT_EQUAL(owner_of(injector), rebuilt, "the full real roundtrip transfers actual injector ownership back to structure")
	TEST_ASSERT_NULL(injector.loc, "the full roundtrip preserves deliberate injector nullspace storage")
	TEST_ASSERT(QDELETED(folded), "actual deployment consumes its folded shell")
	TEST_ASSERT_EQUAL(occupant.loc, T, "the full roundtrip leaves the unrelated released item untouched")
