/// Both actual dye-item families obey held-item release restrictions before the washer records its relation.
/datum/unit_test/interim_washer_sticky_dye/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	for(var/dye_type in list(/obj/item/pen/crayon, /obj/item/stamp))
		var/obj/machinery/washing_machine/washer = allocate(/obj/machinery/washing_machine, T)
		var/obj/item/dye = allocate(dye_type, T)
		var/open_state = washer.state
		TEST_ASSERT_NULL(washer.crayon(), "the fresh actual washer has no dye relation")
		TEST_ASSERT(user.put_in_active_hand(dye), "the actor holds the actual dye item")
		add_trait(dye, TRAIT_NODROP, "interim_washer_sticky_dye")
		TEST_ASSERT(user.release_refusal(dye, user), "the actual inventory refuses release of the sticky dye")
		test_click(user, washer, dye)
		TEST_ASSERT_NULL(washer.crayon(), "refused release does not record a dye relation")
		TEST_ASSERT_EQUAL(dye.loc, user, "refused release keeps the exact dye in actual inventory")
		TEST_ASSERT_EQUAL(user.get_active_hand(), dye, "refused release preserves the exact hand slot")
		TEST_ASSERT_EQUAL(washer.state, open_state, "refused release preserves the washer's original open state")
		TEST_ASSERT_EQUAL(LAZYLEN(washer.washing), 0, "refused dye insertion adds no laundry")
		remove_trait(dye, TRAIT_NODROP, "interim_washer_sticky_dye")
		test_click(user, washer, dye)
		TEST_ASSERT_EQUAL(washer.crayon(), dye, "allowed release records the original dye relation")
		TEST_ASSERT_EQUAL(dye.loc, washer, "allowed release places the original dye inside the actual washer")
		TEST_ASSERT_NULL(user.get_active_hand(), "allowed release clears the original active hand")
		TEST_ASSERT_NULL(owner_of(dye), "the ordinary dye relation does not invent an owned laundry stamp")
		TEST_ASSERT_EQUAL(washer.state, open_state, "dye insertion preserves the open machine state")
		TEST_ASSERT_EQUAL(LAZYLEN(washer.washing), 0, "dye insertion preserves the separate laundry collection")
