/// The actual delayed biomass-container load must not move a bottle whose inventory refuses release.
/datum/unit_test/om/interim_clonepod_sticky_container/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/clonepod/pod = allocate(/obj/machinery/clonepod, T)
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	made += list(user, pod, beaker)
	beaker.reagents.add_reagent(REAGENT_ID_BIOMASS, 10)
	TEST_ASSERT_EQUAL(LAZYLEN(pod.containers), 0, "the real base clonepod starts without stored containers")
	TEST_ASSERT(user.put_in_active_hand(beaker), "the actor holds the actual biomass beaker")
	add_trait(beaker, TRAIT_NODROP, "interim_clonepod_sticky_container")
	TEST_ASSERT(user.release_refusal(beaker, user), "the actual inventory refuses release of the sticky beaker")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual actor can start the delayed load")
	perform_op(user, pod, "load_container", beaker, ORIGIN_CLICK, AUTH_PHYSICAL)
	TEST_ASSERT(test_actor_busy(user), "actual glass insertion starts its real pending action")
	TEST_ASSERT_EQUAL(beaker.loc, user, "starting the delay does not prematurely move the beaker")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!test_actor_busy(user), "the actual delayed load finishes its pending action")
	TEST_ASSERT_EQUAL(beaker.loc, user, "completed release refusal keeps the exact beaker in inventory")
	TEST_ASSERT_EQUAL(user.get_active_hand(), beaker, "completed refusal preserves the exact source hand")
	TEST_ASSERT_EQUAL(LAZYLEN(pod.containers), 0, "completed refusal records no biomass container")
	TEST_ASSERT_EQUAL(pod.get_biomass(), 0, "completed refusal exposes no biomass to the pod")
	TEST_ASSERT_EQUAL(beaker.reagents.get_reagent_amount(REAGENT_ID_BIOMASS), 10, "completed refusal preserves the original biomass dose")
	remove_trait(beaker, TRAIT_NODROP, "interim_clonepod_sticky_container")
	perform_op(user, pod, "load_container", beaker, ORIGIN_CLICK, AUTH_PHYSICAL)
	TEST_ASSERT(test_actor_busy(user), "the allowed second attempt starts another real delayed load")
	TEST_ASSERT_EQUAL(LAZYLEN(pod.containers), 0, "the allowed delayed attempt does not adopt early")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual actor remains capable through both short actions")
	TEST_ASSERT(!test_actor_busy(user), "the allowed delayed action completes")
	TEST_ASSERT_EQUAL(LAZYLEN(pod.containers), 1, "the completed allowed load records exactly one original container")
	TEST_ASSERT(beaker in pod.containers, "the pod records the exact original beaker")
	TEST_ASSERT_EQUAL(beaker.loc, pod, "the actual load physically contains its beaker")
	TEST_ASSERT_EQUAL(owner_of(beaker), pod, "the actual load stamps the existing declared container ownership")
	TEST_ASSERT_NULL(user.get_active_hand(), "the actual allowed load clears its source hand")
	TEST_ASSERT_EQUAL(pod.get_biomass(), 10, "the actual pod reads the exact original biomass dose")
	test_op_handler(pod, "clonepod_empty_beakers", user)
	TEST_ASSERT_EQUAL(beaker.loc, T, "the actual empty-container interaction returns the original beaker to the floor")
	TEST_ASSERT_EQUAL(LAZYLEN(pod.containers), 0, "emptying clears the actual container list")
	TEST_ASSERT_NULL(owner_of(beaker), "emptying releases the actual container ownership")
	TEST_ASSERT_EQUAL(beaker.reagents.get_reagent_amount(REAGENT_ID_BIOMASS), 10, "loading and emptying conserve the original biomass dose")
	qdel(pod)
	TEST_ASSERT(!QDELETED(beaker), "empty pod teardown preserves its returned original beaker")
