/// Uses actual forensic sample insertion, real hand placement and removal guards.
/datum/unit_test/interim_microscope_drop_actor/Run()
	var/turf/start = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, start)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, start)
	var/obj/machinery/microscope/microscope = allocate(/obj/machinery/microscope, start)
	var/obj/item/forensics/swab/swab = allocate(/obj/item/forensics/swab, start)
	TEST_ASSERT(actor.put_in_active_hand(swab), "the real sample begins in the explicit actor's hand")
	TEST_ASSERT_EQUAL(test_op_handler(microscope, "interaction_attackby", actor, swab), OP_OK, "actual insertion installs the real forensic sample")
	TEST_ASSERT_EQUAL(microscope.sample(), swab, "insertion records the exact real sample relation")
	TEST_ASSERT_EQUAL(swab.loc, microscope, "insertion physically contains the actual sample")
	TEST_ASSERT_EQUAL(microscope.handle_sample_drop(actor, bystander), FALSE, "a distinct target is unhandled for unchanged native parent routing")
	TEST_ASSERT_EQUAL(microscope.sample(), swab, "a distinct drop target leaves the actual sample installed")
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, start)
	TEST_ASSERT(actor.equip_to_slot(cuffs, SLOT_ID_HANDCUFFED), "actual cuffs equip into the real restraint slot")
	TEST_ASSERT(actor.incapacitated(), "real restraint satisfies the existing removal guard")
	TEST_ASSERT_EQUAL(microscope.handle_sample_drop(actor, actor), TRUE, "self drop remains handled even when actual removal refuses")
	TEST_ASSERT_EQUAL(microscope.sample(), swab, "the real incapacitation guard retains the exact sample")
	TEST_ASSERT(actor.unEquip(cuffs), "actual inventory removal clears the cuffs")
	TEST_ASSERT(!actor.incapacitated(), "the actual actor is no longer incapacitated")
	var/turf/far = get_step(get_step(get_step(start, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "a real distant floor exists in the isolated room")
	bystander.forceMove(far)
	TEST_ASSERT(!microscope.Adjacent(bystander), "the actual distant actor fails removal proximity")
	TEST_ASSERT_EQUAL(microscope.handle_sample_drop(bystander, bystander), TRUE, "a distant self drop remains handled")
	TEST_ASSERT_EQUAL(microscope.sample(), swab, "the real proximity guard preserves the installed sample")
	TEST_ASSERT_EQUAL(microscope.handle_sample_drop(null, actor), FALSE, "a null actor with a real target selects unchanged parent routing")
	TEST_ASSERT_EQUAL(microscope.handle_sample_drop(null, null), TRUE, "the original equal-null branch remains handled")
	TEST_ASSERT_EQUAL(swab.loc, microscope, "all refused removals preserve actual physical containment")
	TEST_ASSERT_EQUAL(microscope.handle_sample_drop(actor, actor), TRUE, "the actual explicit nearby actor handles sample removal")
	TEST_ASSERT_NULL(microscope.sample(), "actual removal clears the sample relation")
	TEST_ASSERT(actor.item_is_in_hands(swab), "actual removal puts the exact swab into the initiating actor's hands")
	TEST_ASSERT(!bystander.item_is_in_hands(swab), "removal never attributes the sample to the unrelated actor")
	TEST_ASSERT_EQUAL(test_op_handler(microscope, "interaction_attackby", actor, swab), OP_OK, "the same actual sample can be reinserted after removal")
	bystander.forceMove(start)
	TEST_ASSERT(microscope.Adjacent(bystander), "the second actor actually reaches the microscope")
	microscope.handle_sample_drop(bystander, bystander)
	TEST_ASSERT_NULL(microscope.sample(), "the second explicit actor clears the real sample relation")
	TEST_ASSERT(bystander.item_is_in_hands(swab), "the second actual removal follows its explicitly supplied actor")
	TEST_ASSERT(!actor.item_is_in_hands(swab), "the former actor retains no stale held sample")
