/datum/unit_test/interim_artifact_blade_summon_request/Run()
	test_driver_begin()
	check_summon_request()
	test_driver_end()

/datum/unit_test/interim_artifact_blade_summon_request/proc/check_summon_request()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/melee/artifact_blade/blade = allocate(/obj/item/melee/artifact_blade, T)
	var/obj/item/melee/artifact_blade/control = allocate(/obj/item/melee/artifact_blade, T)
	var/obj/item/soulstone/existing = allocate(/obj/item/soulstone, T)
	var/list/original_stones = list()
	for(var/obj/item/soulstone/stone in contents_of(T))
		original_stones += stone
	TEST_ASSERT(existing in original_stones, "Actual independent original stone is present before summoning")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Actor begins without a pending request")
	control.stored_blood = 777
	blade.stored_blood = 200

	blade.summon_item(actor, "Soulstone")
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/choice/artifact_blade_summon), "Actual public summon entry opens native confirmation")
	test_answer(actor, "NO")
	TEST_ASSERT_EQUAL(blade.stored_blood, 200, "Accepted NO does not debit lifeforce")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Accepted NO ends the native request")
	for(var/obj/item/soulstone/stone in contents_of(T))
		TEST_ASSERT(stone in original_stones, "Accepted NO creates no stone")

	blade.summon_item(actor, "Soulstone")
	TEST_ASSERT_NOTNULL(SSrequests.open_for(actor), "Late insufficiency has an actual pending question")
	blade.stored_blood = 199
	test_answer(actor, "YES")
	TEST_ASSERT_EQUAL(blade.stored_blood, 199, "Late blood check rejects YES without a debit")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Late rejected YES ends its native request")
	for(var/obj/item/soulstone/stone in contents_of(T))
		TEST_ASSERT(stone in original_stones, "Late blood insufficiency creates no stone")

	blade.stored_blood = 200
	blade.summon_item(actor, "Soulstone")
	var/datum/request/closed = SSrequests.open_for(actor)
	TEST_ASSERT_NOTNULL(closed, "Explicit close acts on a real pending request")
	test_answer(actor, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(closed.outcome, REQ_CANCELLED, "Native explicit close records cancellation")
	TEST_ASSERT_EQUAL(blade.stored_blood, 200, "Explicit close preserves lifeforce")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Explicit close does not reopen confirmation")
	for(var/obj/item/soulstone/stone in contents_of(T))
		TEST_ASSERT(stone in original_stones, "Explicit close creates no stone")

	blade.summon_item(actor, "Soulstone")
	TEST_ASSERT_NOTNULL(SSrequests.open_for(actor), "Successful summon has an actual pending confirmation")
	test_answer(actor, "YES")
	var/list/products = list()
	for(var/obj/item/soulstone/stone in contents_of(T))
		if(!(stone in original_stones))
			own(stone)
			products += stone
	TEST_ASSERT_EQUAL(length(products), 1, "Accepted YES constructs exactly one new soulstone")
	var/obj/item/soulstone/gem = products[1]
	TEST_ASSERT_EQUAL(gem.type, /obj/item/soulstone, "Summon constructs the canonical soulstone type")
	TEST_ASSERT_EQUAL(gem.name, "Redspace Gem", "Actual production summon names the new gem")
	TEST_ASSERT_EQUAL(gem.loc, actor.loc, "Actual product appears at the requesting human's location")
	TEST_ASSERT_EQUAL(blade.stored_blood, 0, "Successful summon debits exactly 200 lifeforce")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Successful YES completes its request")
	TEST_ASSERT(!QDELETED(existing) && existing.loc == T, "Independent original stone survives in its original location")
	TEST_ASSERT(!QDELETED(control) && control.loc == T, "Independent blade survives in its original location")
	TEST_ASSERT_EQUAL(control.stored_blood, 777, "Independent blade's lifeforce is unchanged")
