/// The real airlock-assembly item entry rejects ordinary glass, then installs one reinforced sheet only when its actual timed action completes.
/datum/unit_test/om/interim_airlock_assembly_glass_dose/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/door_assembly/frame = allocate(/obj/structure/door_assembly, T)
	var/obj/item/stack/material/glass/plain = allocate(/obj/item/stack/material/glass, T, 3)
	var/obj/item/stack/material/glass/reinforced/reinforced = allocate(/obj/item/stack/material/glass/reinforced, T, 2)
	made += list(user, frame, plain, reinforced)
	frame.set_anchored(TRUE)
	TEST_ASSERT(!frame.glass, "the real anchored assembly starts without a window")
	TEST_ASSERT(user.put_in_active_hand(plain), "the real actor holds the ordinary glass stack")
	frame.interaction_item(user, plain, null)
	TEST_ASSERT(!LAZYLEN(user.do_afters), "ordinary glass starts no installation action")
	TEST_ASSERT(!frame.glass, "ordinary glass cannot install a window in this assembly")
	TEST_ASSERT_EQUAL(plain.get_amount(), 3, "the refused ordinary glass stack is not spent")
	TEST_ASSERT_EQUAL(user.get_active_hand(), plain, "the refused ordinary glass remains held")
	TEST_ASSERT(user.drop_from_inventory(plain, T), "the real actor releases the ordinary glass")
	TEST_ASSERT(user.put_in_active_hand(reinforced), "the real actor holds the reinforced glass stack")
	frame.interaction_item(user, reinforced, null)
	TEST_ASSERT(LAZYLEN(user.do_afters), "reinforced glass starts the actual timed installation")
	TEST_ASSERT(!frame.glass, "starting installation does not prematurely add the window")
	TEST_ASSERT_EQUAL(reinforced.get_amount(), 2, "starting installation does not prematurely consume a sheet")
	scheduler_advance((5 SECONDS) / (1 SECOND))
	TEST_ASSERT_EQUAL(frame.glass, 1, "the completed real installation adds the glass window")
	TEST_ASSERT_EQUAL(reinforced.get_amount(), 1, "completed installation spends exactly one reinforced sheet")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "completed installation releases its pending action")
	TEST_ASSERT_EQUAL(frame.state, 0, "window installation does not wire the assembly")
	TEST_ASSERT(frame.anchored, "window installation preserves assembly anchoring")
	frame.interaction_item(user, reinforced, null)
	TEST_ASSERT(!LAZYLEN(user.do_afters), "an assembly with a window starts no second installation")
	TEST_ASSERT_EQUAL(reinforced.get_amount(), 1, "a repeated installation attempt cannot spend another sheet")
	TEST_ASSERT_EQUAL(frame.glass, 1, "a repeated attempt preserves the installed window")
	TEST_ASSERT_EQUAL(user.get_active_hand(), reinforced, "the actual installation leaves the remaining reinforced sheet held")
