/datum/unit_test/dq_eg2/interim_shapeshift_reform_initial_gate
/datum/unit_test/dq_eg2/interim_shapeshift_reform_initial_gate/run_gate()
	var/mob/living/carbon/human/human = person()
	human.set_stat(UNCONSCIOUS)
	TEST_ASSERT_EQUAL(human.stat, UNCONSCIOUS, "actual mob setter establishes the old conscious-flow refusal state")
	TEST_ASSERT_NULL(SSrequests.open_for(human), "the fixture starts without an unrelated request")
	human.shapeshifter_regenerate()
	TEST_ASSERT_NULL(SSrequests.open_for(human), "the actual Fully Reform entry opens no question while unconscious")
	human.set_stat(CONSCIOUS)
	TEST_ASSERT_EQUAL(human.stat, CONSCIOUS, "actual setter restores a permitted actor")
	human.shapeshifter_regenerate()
	var/datum/prompt/choice/shapeshift_reform/asked = SSrequests.open_for(human)
	TEST_ASSERT(istype(asked), "the same real entry opens its native reform confirmation for a conscious actor")
	TEST_ASSERT_EQUAL(asked.title, "Reformation", "the actual entry retains its original confirmation title")
	TEST_ASSERT_EQUAL(length(asked.choices), 2, "the confirmation has exactly its real two options")
	TEST_ASSERT_EQUAL(asked.choices[1], "Reform", "the accepted option preserves its actual custom label")
	TEST_ASSERT_EQUAL(asked.choices[2], "Cancel", "the decline option preserves its actual custom label")
	test_answer(human, null, REQ_CANCELLED)
	TEST_ASSERT_NULL(SSrequests.open_for(human), "closing the actual confirmation ends without opening flavor or OOC questions")
