/// Actual fossil pulverization requires successful consumption before generating its single real random seed packet.
/datum/unit_test/interim_seed_extractor_sticky_fossil/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/seed_extractor/extractor = allocate(/obj/machinery/seed_extractor, T)
	var/obj/item/fossil/plant/fossil = allocate(/obj/item/fossil/plant, T)
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/seeds)), 0, "the actual fossil-processing floor starts without output packets")
	TEST_ASSERT(user.put_in_active_hand(fossil), "the actor holds the actual supported plant fossil")
	add_trait(fossil, TRAIT_NODROP, "interim_seed_extractor_sticky_fossil")
	TEST_ASSERT(user.release_refusal(fossil, user), "the real inventory refuses release of the sticky fossil")
	test_op_handler(extractor, "interaction_pulverize_fossil", user, fossil)
	own_turf_contents(T)
	TEST_ASSERT(!QDELETED(fossil), "refused pulverization preserves the original fossil")
	TEST_ASSERT_EQUAL(fossil.loc, user, "refused pulverization preserves actual inventory containment")
	TEST_ASSERT_EQUAL(user.get_active_hand(), fossil, "refused pulverization preserves the exact hand slot")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/seeds)), 0, "refused consumption emits no seed packet")
	remove_trait(fossil, TRAIT_NODROP, "interim_seed_extractor_sticky_fossil")
	test_op_handler(extractor, "interaction_pulverize_fossil", user, fossil)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(fossil), "allowed actual pulverization consumes the original fossil")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears the original hand")
	var/list/packets = contents_of(T, /obj/item/seeds)
	TEST_ASSERT_EQUAL(length(packets), 1, "allowed actual pulverization emits exactly one packet")
	var/obj/item/seeds/packet = packets[1]
	TEST_ASSERT(istype(packet, /obj/item/seeds/random), "the actual output is the declared random seed-packet type")
	TEST_ASSERT_NOTNULL(packet.seed(), "the actual random output has real generated seed data")
	TEST_ASSERT_EQUAL(packet.seed_type, packet.seed().name, "the actual packet names its original generated seed")
	TEST_ASSERT(!QDELETED(packet), "the real generated output survives extraction")

