/// The actual delayed wiring entry spends one cable length only after completion, on a fresh actor's clock.
/datum/unit_test/om/interim_airlock_assembly_wiring_dose/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/door_assembly/frame = allocate(/obj/structure/door_assembly, T)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, T, 2)
	made += list(user, frame, cable)
	frame.set_anchored(TRUE)
	TEST_ASSERT_EQUAL(frame.state, 0, "the actual anchored assembly starts unwired")
	TEST_ASSERT(user.put_in_active_hand(cable), "the actual actor holds two wiring lengths")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the fresh actual actor is capable of wiring")
	frame.interaction_item(user, cable, null)
	TEST_ASSERT(LAZYLEN(user.do_afters), "the actual wiring entry starts a pending timed action")
	TEST_ASSERT_EQUAL(frame.state, 0, "starting wiring does not prematurely change the assembly stage")
	TEST_ASSERT_EQUAL(cable.get_amount(), 2, "starting wiring does not prematurely spend cable")
	scheduler_advance((5 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual wiring actor remains capable after its single timed action")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "completed wiring releases its pending action")
	TEST_ASSERT_EQUAL(frame.state, 1, "the actual timed wiring action advances to the wired stage")
	TEST_ASSERT_EQUAL(cable.get_amount(), 1, "completed airlock wiring spends exactly one cable length")
	TEST_ASSERT(frame.anchored, "completed wiring preserves anchoring")
	TEST_ASSERT_NULL(frame.electronics, "actual wiring does not invent an electronics board")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cable, "completed wiring leaves the actual remaining cable held")

/// A real wired assembly refunds exactly one cable length through its actual tool action; a separate clock avoids chaining unrelated human physiology through two long tasks.
/datum/unit_test/om/interim_airlock_assembly_unwiring_refund/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/door_assembly/frame = allocate(/obj/structure/door_assembly, T)
	var/obj/item/tool/wirecutters/cutters = allocate(/obj/item/tool/wirecutters, T)
	made += list(user, frame, cutters)
	frame.set_anchored(TRUE)
	frame.state = 1
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/cable_coil)), 0, "the actual wired-assembly fixture starts without refunded cable")
	TEST_ASSERT(user.put_in_active_hand(cutters), "the fresh actual actor holds the unwiring tool")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the fresh actual actor is capable of unwiring")
	var/unwiring_delay = tool_delay(user, cutters, 4 SECONDS, TOOL_WIRECUTTER)
	TEST_ASSERT(unwiring_delay > 0, "the actual tool has a positive scaled unwiring delay")
	TEST_ASSERT_EQUAL(frame.wirecutter_act(user, cutters), ITEM_INTERACT_SUCCESS, "the real tool entry starts airlock unwiring")
	TEST_ASSERT(LAZYLEN(user.do_afters), "the real tool starts a pending unwiring action")
	TEST_ASSERT_EQUAL(frame.state, 1, "starting unwiring preserves the actual wired stage")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/cable_coil)), 0, "starting unwiring does not refund cable early")
	scheduler_advance((unwiring_delay + 1 SECOND) / (1 SECOND))
	own_turf_contents(T)
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual unwiring actor remains capable after its single timed action")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "actual unwiring finishes after its scaled tool delay")
	TEST_ASSERT_EQUAL(frame.state, 0, "actual completed unwiring returns the assembly to the unwired stage")
	TEST_ASSERT(frame.anchored, "actual unwiring preserves assembly anchoring")
	TEST_ASSERT_NULL(frame.electronics, "actual unwiring does not invent an electronics board")
	var/cable_lengths = 0
	for(var/obj/item/stack/cable_coil/refund as anything in contents_of(T, /obj/item/stack/cable_coil))
		cable_lengths += refund.get_amount()
	TEST_ASSERT_EQUAL(cable_lengths, 1, "actual unwiring refunds exactly one cable length")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cutters, "actual unwiring preserves the actor's held tool")
