/// Actual extract enhancement must consume the original agent before granting uses.
/datum/unit_test/interim_slime_extract_sticky_enhancer/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/slime_extract/extract = allocate(/obj/item/slime_extract, T)
	var/obj/item/slimepotion/enhancer/agent = allocate(/obj/item/slimepotion/enhancer, T)
	TEST_ASSERT_EQUAL(extract.uses, initial(extract.uses), "actual extract starts with its declared uses")
	TEST_ASSERT_EQUAL(extract.enhanced, FALSE, "actual extract starts without enhancement")
	var/original_uses = extract.uses
	TEST_ASSERT(user.put_in_active_hand(agent), "the actor holds the exact original enhancer")
	add_trait(agent, TRAIT_NODROP, "interim_extract_enhancer")
	TEST_ASSERT(user.release_refusal(agent, user), "actual inventory refuses sticky enhancer consumption")
	test_op_handler(extract, "interaction_item", user, agent)
	TEST_ASSERT_EQUAL(extract.uses, original_uses, "refused consumption grants no extract uses")
	TEST_ASSERT_EQUAL(extract.enhanced, FALSE, "refused consumption leaves actual enhancement disabled")
	TEST_ASSERT(!QDELETED(agent), "refused enhancement preserves original agent")
	TEST_ASSERT_EQUAL(user.get_active_hand(), agent, "refused enhancement preserves exact original hand")
	TEST_ASSERT_EQUAL(agent.loc, user, "refused enhancement preserves actual inventory containment")
	remove_trait(agent, TRAIT_NODROP, "interim_extract_enhancer")
	test_op_handler(extract, "interaction_item", user, agent)
	TEST_ASSERT(QDELETED(agent), "allowed enhancement consumes exact original agent")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(extract.uses, original_uses + 2, "one consumed enhancer grants exactly two declared uses")
	TEST_ASSERT_EQUAL(extract.enhanced, TRUE, "allowed enhancement sets actual one-time enhancement state")
	var/obj/item/slimepotion/enhancer/replacement = allocate(/obj/item/slimepotion/enhancer, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds an actual second enhancer")
	test_op_handler(extract, "interaction_item", user, replacement)
	TEST_ASSERT(!QDELETED(replacement), "already enhanced extract preserves original replacement agent")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "repeat refusal preserves replacement hand")
	TEST_ASSERT_EQUAL(extract.uses, original_uses + 2, "repeat refusal grants no additional uses")
