/// Hanging a real labcoat respects inventory release and returns the same coat without consuming or owning it.
/datum/unit_test/interim_coatrack_sticky_coat/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/coatrack/rack = allocate(/obj/structure/coatrack, T)
	var/obj/item/clothing/suit/storage/toggle/labcoat/coat = allocate(/obj/item/clothing/suit/storage/toggle/labcoat, T)
	TEST_ASSERT_NULL(rack.coat(), "the actual rack begins without a hung coat")
	TEST_ASSERT(user.put_in_active_hand(coat), "the actor holds the original allowed labcoat")
	add_trait(coat, TRAIT_NODROP, "interim_coatrack_sticky")
	TEST_ASSERT(user.release_refusal(coat, user), "the actual inventory refuses release of this coat")
	test_op_handler(rack, "interaction_item", user, coat)
	TEST_ASSERT_EQUAL(user.get_active_hand(), coat, "refused hanging preserves the exact original hand")
	TEST_ASSERT_EQUAL(coat.loc, user, "refused hanging preserves actual inventory containment")
	TEST_ASSERT_NULL(rack.coat(), "refused hanging records no coat on the rack")
	remove_trait(coat, TRAIT_NODROP, "interim_coatrack_sticky")
	test_op_handler(rack, "interaction_item", user, coat)
	TEST_ASSERT_EQUAL(rack.coat(), coat, "allowed hanging records the exact original coat")
	TEST_ASSERT_EQUAL(coat.loc, rack, "allowed hanging physically contains the same coat")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed hanging clears the source hand")
	TEST_ASSERT_NULL(owner_of(coat), "the rack preserves its existing non-owning relation policy")
	test_op_handler(rack, "interaction_hand", user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), coat, "taking the hung coat returns the original to the actor's hand")
	TEST_ASSERT_EQUAL(coat.loc, user, "taking the coat restores actual inventory containment")
	TEST_ASSERT_NULL(rack.coat(), "taking the coat clears the rack's relation")
	qdel(rack)
	TEST_ASSERT(!QDELETED(coat), "the original returned coat survives empty-rack teardown")
	TEST_ASSERT_EQUAL(user.get_active_hand(), coat, "rack teardown preserves the returned original hand")
