/// Actual worn clothing uses its existing release and actor guards before hand transfer.
/datum/unit_test/interim_clothing_drop_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	var/atom/movable/screen/right = hud.r_hand_hud_object
	TEST_ASSERT_NOTNULL(right, "the actual human HUD supplies its real hand target")
	var/obj/item/clothing/under/color/black/uniform = allocate(/obj/item/clothing/under/color/black, T)
	var/obj/item/unrelated = allocate(/obj/item, T)
	TEST_ASSERT(actor.equip_to_slot(uniform, SLOT_ID_UNIFORM), "the real uniform occupies the actual clothing slot")
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_UNIFORM), uniform, "the real worn slot contains the exact uniform")
	TEST_ASSERT(actor.put_in_l_hand(unrelated), "an unrelated actual item occupies the other hand")
	uniform.drop_with_actor(bystander, right)
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_UNIFORM), uniform, "a different explicit actor cannot remove another actor's actual clothing")
	TEST_ASSERT(!bystander.item_is_in_hands(uniform), "ownership refusal never grants the unrelated actor a held uniform")
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, T)
	TEST_ASSERT(actor.equip_to_slot(cuffs, SLOT_ID_HANDCUFFED), "actual cuffs activate the source restraint guard")
	TEST_ASSERT(actor.restrained(), "the actual source restraint predicate is true")
	uniform.drop_with_actor(actor, right)
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_UNIFORM), uniform, "real restraint refuses removal of the exact worn uniform")
	TEST_ASSERT(actor.unEquip(cuffs), "actual removal clears the cuffs")
	TEST_ASSERT(!actor.restrained(), "the actual source restraint predicate is clear")
	TEST_ASSERT(actor.put_in_l_hand(unrelated), "the unrelated item is actually held after the cuff fixture dropped it")
	set_var(uniform, nameof(uniform.canremove), FALSE)
	TEST_ASSERT(!actor.canUnEquip(uniform), "the actual inventory unequip predicate refuses nonremovable clothing")
	uniform.drop_with_actor(actor, right)
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_UNIFORM), uniform, "checked actual unEquip preserves nonremovable worn clothing")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), unrelated, "nonremovable refusal preserves the unrelated actual held item")
	set_var(uniform, nameof(uniform.canremove), TRUE)
	TEST_ASSERT(actor.canUnEquip(uniform), "restoring removability clears the actual inventory unequip refusal")
	uniform.drop_with_actor(actor, null)
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_UNIFORM), uniform, "absent destination leaves actual worn clothing untouched")
	uniform.drop_with_actor(null, right)
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_UNIFORM), uniform, "absent actor leaves the actual worn slot untouched")
	TEST_ASSERT_NULL(uniform.drop_with_actor(actor, right), "actual accepted clothing drop preserves implicit null return")
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_UNIFORM), "actual accepted transfer clears the worn uniform slot")
	TEST_ASSERT_EQUAL(actor.get_right_hand(), uniform, "the actual initiating actor receives its exact uniform in the requested hand")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), unrelated, "actual transfer preserves the unrelated held item")
	TEST_ASSERT_EQUAL(uniform.loc, actor, "the real transferred clothing remains physically carried by its actor")
