/// A real computer frame rejects reinforced glass without spending it, then installs exactly two plain glass sheets through its actual timed construction edge.
/datum/unit_test/om/interim_computer_frame_glass_material/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/frame/computer/frame = allocate(/obj/structure/frame/computer, T)
	var/obj/item/circuitboard/crew/board = allocate(/obj/item/circuitboard/crew, T)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, T, 6)
	var/obj/item/stack/material/glass/reinforced/reinforced = allocate(/obj/item/stack/material/glass/reinforced, T, 3)
	var/obj/item/stack/material/glass/plain = allocate(/obj/item/stack/material/glass, T, 3)
	made += list(user, frame, board, cable, reinforced, plain)
	TEST_ASSERT(interim_construction_step(frame, user, /datum/interaction/construction/frame/insert_board, board), "the actual matching computer board enters its frame")
	TEST_ASSERT(interim_construction_step(frame, user, /datum/interaction/construction/frame/fasten_board), "the actual matching computer board can be fastened")
	TEST_ASSERT(interim_construction_step(frame, user, /datum/interaction/construction/frame/wire, cable), "the actual computer frame reaches its wired state")
	var/datum/interaction/construction/add_glass
	for(var/datum/interaction/construction/edge as anything in construction_edges_for(frame))
		if(edge.type == /datum/interaction/construction/frame/add_glass)
			add_glass = edge
			break
	TEST_ASSERT_NOTNULL(add_glass, "the actual wired computer frame exposes its glass-panel edge")
	TEST_ASSERT(reinforced.get_material_name() != MAT_GLASS, "the actual reinforced sheets have a genuinely incompatible material")
	TEST_ASSERT(user.put_in_active_hand(reinforced), "the actual actor holds real reinforced glass sheets")
	TEST_ASSERT_NOTNULL(add_glass.why_not(user, frame, reinforced), "the actual panel requirement refuses reinforced glass")
	TEST_ASSERT(!add_glass.perform(user, frame, reinforced), "the actual public panel edge refuses reinforced glass")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "actual material refusal starts no panel installation task")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "actual material refusal preserves the wired frame")
	TEST_ASSERT_EQUAL(reinforced.get_amount(), 3, "actual material refusal spends no reinforced sheet")
	TEST_ASSERT_EQUAL(user.get_active_hand(), reinforced, "actual material refusal preserves the exact reinforced stack in hand")
	TEST_ASSERT(user.drop_from_inventory(reinforced, T), "the actual actor releases the incompatible reinforced sheets")
	TEST_ASSERT(user.put_in_active_hand(plain), "the actual actor holds the real plain-glass alternative")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual panel-installation actor starts capable")
	var/install_delay = add_glass.duration_for(user, frame, plain)
	TEST_ASSERT(install_delay > 0, "the actual panel edge has a positive installation delay")
	TEST_ASSERT(add_glass.perform(user, frame, plain), "the actual public panel edge accepts plain glass")
	TEST_ASSERT(LAZYLEN(user.do_afters), "actual accepted panel installation starts its timed task")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "actual accepted installation does not advance the frame early")
	TEST_ASSERT_EQUAL(plain.get_amount(), 3, "actual accepted installation spends no plain glass early")
	scheduler_advance((install_delay + 1 SECOND) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual panel-installation actor remains capable through its single task")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "actual panel installation releases its completed task")
	TEST_ASSERT_EQUAL(frame.state, FRAME_PANELED, "actual completed installation reaches the paneled stage")
	TEST_ASSERT_EQUAL(plain.get_amount(), 1, "actual completed installation consumes exactly two plain sheets")
	TEST_ASSERT_EQUAL(reinforced.get_amount(), 3, "actual later success never consumes previously refused reinforced glass")
	TEST_ASSERT_EQUAL(frame.circuit, board, "actual completed installation preserves the exact computer board")
	TEST_ASSERT_EQUAL(board.loc, frame, "actual completed installation keeps its board physically contained")
	TEST_ASSERT(frame.anchored, "actual completed installation preserves frame anchoring")
	TEST_ASSERT_EQUAL(user.get_active_hand(), plain, "actual completed installation retains the remaining plain sheet in hand")
