/// Late choice checks use actual current limbs, retaining the original sole-limb fallback.
/datum/unit_test/interim_tourniquet_late_choice

/datum/unit_test/interim_tourniquet_late_choice/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	patient.enable_godmode()
	TEST_ASSERT(!user.incapacitated() && user.Adjacent(patient), "The actual actor can reach the patient")
	var/obj/item/organ/external/left = patient.get_organ(BP_L_ARM)
	var/obj/item/organ/external/right = patient.get_organ(BP_R_ARM)
	var/obj/item/organ/external/leg = patient.get_organ(BP_L_LEG)
	TEST_ASSERT_NOTNULL(left, "The patient has a real left arm")
	TEST_ASSERT_NOTNULL(right, "The patient has a real right arm")
	TEST_ASSERT_NOTNULL(leg, "The patient has a real left leg")
	var/obj/item/tourniquet/left_strap = allocate(/obj/item/tourniquet, T)
	var/obj/item/tourniquet/right_strap = allocate(/obj/item/tourniquet, T)
	var/obj/item/tourniquet/leg_strap = allocate(/obj/item/tourniquet, T)
	TEST_ASSERT(left.apply_tourniquet(left_strap, user), "The first real strap cinches")
	TEST_ASSERT(right.apply_tourniquet(right_strap, user), "The second real strap cinches")
	TEST_ASSERT(leg.apply_tourniquet(leg_strap, user), "The third real strap cinches")
	var/list/choices = list()
	choices[left.name] = left
	choices[right.name] = right
	choices[leg.name] = leg
	var/datum/request/stale = open_request(patient, /datum/prompt/choice/loosen_tourniquet, TYPE_PROC_REF(/mob/living/carbon/human, loosen_tourniquet_chosen), answerer = user, choices = choices)
	TEST_ASSERT(stale.is_open(), "The production native request opens for the actual actor")
	TEST_ASSERT_EQUAL(left.remove_tourniquet(user), left_strap, "The selected old strap is actually removed before answer")
	test_answer(user, left.name)
	TEST_ASSERT_EQUAL(stale.outcome, REQ_CANCELLED, "An absent label with multiple current limbs is refused before dereference")
	TEST_ASSERT_EQUAL(right.tourniquet, right_strap, "Refusal retains the exact second strap")
	TEST_ASSERT_EQUAL(leg.tourniquet, leg_strap, "Refusal retains the exact third strap")
	TEST_ASSERT_NULL(left.tourniquet, "Refusal does not recreate the removed strap")
	var/list/remaining = list()
	remaining[right.name] = right
	remaining[leg.name] = leg
	var/datum/request/sole = open_request(patient, /datum/prompt/choice/loosen_tourniquet, TYPE_PROC_REF(/mob/living/carbon/human, loosen_tourniquet_chosen), answerer = user, choices = remaining)
	TEST_ASSERT(sole.is_open(), "A second actual request opens")
	TEST_ASSERT_EQUAL(right.remove_tourniquet(user), right_strap, "Removing the selected strap leaves one actual cinched limb")
	test_answer(user, right.name)
	TEST_ASSERT_EQUAL(sole.outcome, REQ_ANSWERED, "The original sole-current-limb fallback still accepts the old key")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(leg.tourniquet, leg_strap, "The real fallback does not skip the removal delay")
	test_time(2 SECONDS)
	TEST_ASSERT_NULL(leg.tourniquet, "The unchanged timed callback releases the actual sole limb")
	TEST_ASSERT_EQUAL(leg_strap.loc, user, "The explicit actor receives that exact strap")
	TEST_ASSERT(leg_strap == user.get_equipped_item(SLOT_ID_L_HAND) || leg_strap == user.get_equipped_item(SLOT_ID_R_HAND), "The removed strap occupies a real hand")
	TEST_ASSERT_EQUAL(left_strap.loc, T, "The other previously removed strap stays on the actual floor")
	TEST_ASSERT_EQUAL(right_strap.loc, T, "The bystander strap is never collected by fallback")
	test_driver_end()
