/datum/unit_test/interim_native_reference_lifetime/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/item/gun/energy/gun = allocate(/obj/item/gun/energy, T)
	var/obj/item/cell/device/borrowed = allocate(/obj/item/cell/device, T)
	var/obj/item/cell/device/independent_cell = allocate(/obj/item/cell/device, T)
	TEST_ASSERT_NOTNULL(gun.get_cell(), "the actual energy gun initially has its constructed internal cell")
	own(gun.get_cell())
	var/datum/borrowed_owner = owner_of(borrowed)
	TEST_ASSERT_NOTEQUAL(borrowed_owner, gun, "the external floor cell is not initially owned by the gun")
	rel_set(gun, nameof(gun.power_supply), borrowed)
	TEST_ASSERT_EQUAL(gun.get_cell(), borrowed, "the production energy gun getter resolves the exact borrowed cell")
	TEST_ASSERT_EQUAL(borrowed.loc, T, "setting the reference does not move the external cell into the gun")
	TEST_ASSERT_EQUAL(owner_of(borrowed), borrowed_owner, "the gun reference preserves the external cell's original owner stamp")
	qdel(gun)
	TEST_ASSERT(QDELETED(gun), "the actual gun has completed teardown")
	TEST_ASSERT(!QDELETED(borrowed), "gun teardown preserves the referenced external cell")
	TEST_ASSERT_EQUAL(borrowed.loc, T, "gun teardown leaves the borrowed cell on its original floor")
	TEST_ASSERT_EQUAL(owner_of(borrowed), borrowed_owner, "gun teardown preserves the borrowed cell's original owner stamp")
	TEST_ASSERT(!QDELETED(independent_cell), "the independent original cell also survives gun teardown")

	var/mob/living/simple_mob/animal = allocate(/mob/living/simple_mob, T)
	var/mob/living/carbon/human/tamer = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/independent_tamer = allocate(/mob/living/carbon/human, T)
	var/datum/tamer_owner = owner_of(tamer)
	var/datum/independent_tamer_owner = owner_of(independent_tamer)
	TEST_ASSERT_NOTEQUAL(tamer_owner, animal, "the first human is not initially owned by the animal")
	TEST_ASSERT_NOTEQUAL(independent_tamer_owner, animal, "the independent human is not initially owned by the animal")
	rel_add(animal, nameof(animal.tamers), tamer)
	rel_add(animal, nameof(animal.tamers), independent_tamer)
	TEST_ASSERT_EQUAL(length(animal.tamers), 2, "the real animal reference list contains both distinct original tamers")
	TEST_ASSERT((tamer in animal.tamers) && (independent_tamer in animal.tamers), "both exact original tamer identities are linked before deletion")
	TEST_ASSERT_EQUAL(owner_of(tamer), tamer_owner, "linking the first tamer preserves its original owner stamp")
	TEST_ASSERT_EQUAL(owner_of(independent_tamer), independent_tamer_owner, "linking the independent tamer preserves its original owner stamp")
	qdel(tamer)
	TEST_ASSERT(QDELETED(tamer), "the original first tamer is actually deleted")
	TEST_ASSERT_EQUAL(length(animal.tamers), 1, "deleting one tamer removes exactly its real reference list entry")
	TEST_ASSERT(!(tamer in animal.tamers), "the deleted original no longer appears in the production tamers list")
	TEST_ASSERT(independent_tamer in animal.tamers, "the independent original remains linked")
	TEST_ASSERT(!QDELETED(independent_tamer) && !QDELETED(animal), "reference cleanup preserves the independent tamer and animal")
	qdel(animal)
	TEST_ASSERT(!QDELETED(independent_tamer), "animal teardown does not dispose of its remaining referenced tamer")
	TEST_ASSERT_EQUAL(owner_of(independent_tamer), independent_tamer_owner, "animal teardown preserves the surviving human's original owner stamp")
