/// Actual unpowered airlock motion must refuse ordinary operation and mechanical obstructions, while forced motion completes through its real animation timers.
/datum/unit_test/om/interim_airlock_unpowered_motion
	parent_type = /datum/unit_test/dq_p2_door

/datum/unit_test/om/interim_airlock_unpowered_motion/run_gate()
	var/turf/T = tile(2, 2)
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock, T)
	door.set_autoclose(FALSE)
	p2_door_set_power(door, FALSE)
	TEST_ASSERT(!door.power_systems_on(), "the actual airlock fixture has no operating power")
	TEST_ASSERT(door.density && !door.operating, "the actual airlock starts closed and idle")
	var/timers_before = time_scheduler().timer_count(door)
	TEST_ASSERT(!door.open(), "the actual ordinary open entry refuses missing power")
	TEST_ASSERT(door.density && !door.operating, "ordinary opening refusal preserves closed idle state")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), timers_before, "ordinary opening refusal schedules no new timer")
	set_bolted(door, TRUE, TRUE)
	TEST_ASSERT(!door.open(TRUE), "the actual forced open entry respects dropped bolts")
	TEST_ASSERT(door.density && !door.operating, "bolted forced refusal preserves closed idle state")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), timers_before, "bolted forced refusal schedules no motion timer")
	set_bolted(door, FALSE, TRUE)
	set_welded(door, TRUE)
	TEST_ASSERT(!door.open(TRUE), "the actual forced open entry respects a welded airlock")
	TEST_ASSERT(door.density && !door.operating, "welded forced refusal preserves closed idle state")
	set_welded(door, FALSE)
	door.open(TRUE)
	TEST_ASSERT_EQUAL(door.operating, 1, "the unrestricted actual forced open starts animation")
	TEST_ASSERT(door.density, "actual forced opening retains density before its animation deadline")
	test_time(2 SECONDS)
	TEST_ASSERT(!door.density && !door.operating, "the actual forced open timers finish with an open idle airlock")
	TEST_ASSERT(!door.opacity, "the actually opened airlock no longer blocks sight")
	TEST_ASSERT(!door.power_systems_on(), "forced opening does not restore actual airlock power")
	TEST_ASSERT(!door.close(), "the actual ordinary close entry also refuses missing power")
	TEST_ASSERT(!door.density && !door.operating, "ordinary closing refusal preserves open idle state")
	door.close(TRUE)
	TEST_ASSERT_EQUAL(door.operating, 1, "the actual forced close starts animation without power")
	TEST_ASSERT(!door.density, "actual forced closing preserves the open density until its animation deadline")
	test_time(2 SECONDS)
	TEST_ASSERT(door.density && !door.operating, "the real forced close timers finish with a closed idle airlock")
	TEST_ASSERT(door.opacity, "the actual closed opaque airlock blocks sight again")
	TEST_ASSERT(!door.power_systems_on(), "forced closing does not restore actual airlock power")
