/// The actual delayed wiring entry spends one cable length only after completion, on a fresh actor's clock.
/datum/unit_test/interim_airlock_assembly_wiring_dose/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/structure/door_assembly/frame = allocate(/obj/structure/door_assembly, T)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, T, 2)
	var/obj/item/tool/wrench/wrench = allocate(/obj/item/tool/wrench, T)
	p2_door_click(user, frame, wrench)
	test_time(5 SECONDS)
	TEST_ASSERT(frame.anchored, "The actual wrench anchors the original assembly through native construction")
	TEST_ASSERT(user.drop_from_inventory(wrench, T), "The actor releases the real anchoring wrench")
	TEST_ASSERT_EQUAL(frame.assembly_state(), 0, "the actual anchored assembly starts unwired")
	TEST_ASSERT(user.put_in_active_hand(cable), "the actual actor holds two wiring lengths")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the fresh actual actor is capable of wiring")
	p2_door_click(user, frame, cable)
	TEST_ASSERT_EQUAL(frame.assembly_state(), 0, "starting wiring does not prematurely change the assembly stage")
	TEST_ASSERT_EQUAL(cable.get_amount(), 2, "starting wiring does not prematurely spend cable")
	test_time(3 SECONDS)
	TEST_ASSERT_EQUAL(frame.assembly_state(), 0, "Actual native wiring retains its original stage before its deadline")
	TEST_ASSERT_EQUAL(cable.get_amount(), 2, "Actual native wiring spends no cable before its deadline")
	test_time(5 SECONDS)
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual wiring actor remains capable after its single timed action")
	TEST_ASSERT_EQUAL(frame.assembly_state(), 1, "the actual timed wiring action advances to the wired stage")
	TEST_ASSERT_EQUAL(cable.get_amount(), 1, "completed airlock wiring spends exactly one cable length")
	TEST_ASSERT(frame.anchored, "completed wiring preserves anchoring")
	TEST_ASSERT_NULL(frame.electronics, "actual wiring does not invent an electronics board")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cable, "completed wiring leaves the actual remaining cable held")

/// A real wired assembly refunds exactly one cable length through its actual tool action; a separate clock avoids chaining unrelated human physiology through two long tasks.
/datum/unit_test/interim_airlock_assembly_unwiring_refund/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/structure/door_assembly/frame = allocate(/obj/structure/door_assembly, T)
	var/obj/item/tool/wirecutters/cutters = allocate(/obj/item/tool/wirecutters, T)
	var/obj/item/tool/wrench/wrench = allocate(/obj/item/tool/wrench, T)
	p2_door_click(user, frame, wrench)
	test_time(5 SECONDS)
	TEST_ASSERT(frame.anchored, "The actual wrench anchors the original assembly through native construction")
	TEST_ASSERT(user.drop_from_inventory(wrench, T), "The actor releases the real anchoring wrench")
	var/obj/item/stack/cable_coil/setup_cable = allocate(/obj/item/stack/cable_coil, T, 1)
	p2_door_click(user, frame, setup_cable)
	test_time(5 SECONDS)
	TEST_ASSERT(QDELETED(setup_cable), "Actual native wiring spends the complete original one-length setup cable")
	TEST_ASSERT_EQUAL(frame.assembly_state(), 1, "The actual native construction fixture reaches its real wired stage")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/cable_coil)), 0, "the actual wired-assembly fixture starts without refunded cable")
	TEST_ASSERT(user.put_in_active_hand(cutters), "the fresh actual actor holds the unwiring tool")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the fresh actual actor is capable of unwiring")
	p2_door_click(user, frame, cutters)
	TEST_ASSERT_EQUAL(frame.assembly_state(), 1, "starting unwiring preserves the actual wired stage")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/cable_coil)), 0, "starting unwiring does not refund cable early")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(frame.assembly_state(), 1, "Actual native unwiring preserves its original stage before its deadline")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/cable_coil)), 0, "Actual native unwiring refunds no cable before its deadline")
	test_time(5 SECONDS)
	own_turf_contents(T)
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual unwiring actor remains capable after its single timed action")
	TEST_ASSERT_EQUAL(frame.assembly_state(), 0, "actual completed unwiring returns the assembly to the unwired stage")
	TEST_ASSERT(frame.anchored, "actual unwiring preserves assembly anchoring")
	TEST_ASSERT_NULL(frame.electronics, "actual unwiring does not invent an electronics board")
	var/cable_lengths = 0
	for(var/obj/item/stack/cable_coil/refund as anything in contents_of(T, /obj/item/stack/cable_coil))
		cable_lengths += refund.get_amount()
	TEST_ASSERT_EQUAL(cable_lengths, 1, "actual unwiring refunds exactly one cable length")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cutters, "actual unwiring preserves the actor's held tool")
