/// Ore-box inventory credit must be backed by consumption of the exact original ore.
/datum/unit_test/interim_ore_box_sticky_ore/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/ore_box/box = allocate(/obj/structure/ore_box, T)
	var/obj/item/ore/iron/ore = allocate(/obj/item/ore/iron, T)
	TEST_ASSERT_EQUAL(ore.material, ORE_HEMATITE, "the actual iron ore declares the hematite inventory key")
	TEST_ASSERT_EQUAL(box.stored_ore[ore.material], 0, "the actual box starts with no stored iron ore")
	TEST_ASSERT(user.put_in_active_hand(ore), "the actor holds the exact original iron ore")
	add_trait(ore, TRAIT_NODROP, "interim_box_sticky_ore")
	TEST_ASSERT(user.release_refusal(ore, user), "actual inventory refuses sticky ore consumption")
	test_op_handler(box, "interaction_item", user, ore)
	TEST_ASSERT_EQUAL(box.stored_ore[ORE_HEMATITE], 0, "refused consumption grants no stored ore")
	TEST_ASSERT(!QDELETED(ore), "refused loading preserves exact original ore")
	TEST_ASSERT_EQUAL(user.get_active_hand(), ore, "refused loading preserves original source hand")
	TEST_ASSERT_EQUAL(ore.loc, user, "refused loading preserves actual inventory containment")
	remove_trait(ore, TRAIT_NODROP, "interim_box_sticky_ore")
	test_op_handler(box, "interaction_item", user, ore)
	TEST_ASSERT(QDELETED(ore), "allowed loading consumes exact original ore")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(box.stored_ore[ORE_HEMATITE], 1, "one consumed original ore credits exactly one stored unit")
	var/obj/item/pen/non_ore = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_active_hand(non_ore), "the actor holds a real non-ore item")
	test_op_handler(box, "interaction_item", user, non_ore)
	TEST_ASSERT_EQUAL(user.get_active_hand(), non_ore, "non-ore input preserves exact original source hand")
	TEST_ASSERT_EQUAL(box.stored_ore[ORE_HEMATITE], 1, "non-ore input credits no additional stored ore")
