/// Actual empty energy nets expire at the declared deadline; occupied nets survive until release.
/datum/unit_test/interim_energy_net_empty_deadline/Run()
	test_driver_begin()
	var/obj/effect/energy_net/net = allocate(/obj/effect/energy_net, run_loc_floor_bottom_left)
	TEST_ASSERT(!net.has_buckled_mobs(), "real fresh net starts without occupants")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(net), 1, "actual net initialization registers one empty-check timer")
	test_time(1 SECOND)
	TEST_ASSERT(!QDELETED(net), "actual empty net remains until its two-second deadline")
	test_time(1 SECOND)
	TEST_ASSERT(QDELETED(net), "actual empty-check timer consumes the net at its deadline")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(net), 0, "expired real net retains no timer")

/datum/unit_test/interim_energy_net_release_deadline/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/target = allocate(/mob/living/carbon/human, T)
	var/obj/effect/energy_net/net = allocate(/obj/effect/energy_net, T)
	TEST_ASSERT(net.buckle_mob(target), "actual net restrains the real target")
	TEST_ASSERT_EQUAL(target.buckled_to(), net, "actual buckle relation references the original net")
	TEST_ASSERT_EQUAL(target.can_pull_size, 0, "actual net prevents its restrained target from pulling")
	test_time(2 SECONDS)
	TEST_ASSERT(!QDELETED(net), "real empty-check deadline preserves an occupied net")
	TEST_ASSERT_EQUAL(target.buckled_to(), net, "occupied deadline preserves the actual restraint")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(net), 0, "real occupied check completes its one-shot timer")
	TEST_ASSERT_EQUAL(net.unbuckle_mob(target), target, "actual unbuckling returns its released target")
	TEST_ASSERT(QDELETED(net), "actual post-unbuckle cleanup consumes the empty net")
	TEST_ASSERT_NULL(target.buckled_to(), "actual unbuckling clears the target relation")
	TEST_ASSERT_EQUAL(target.can_pull_size, initial(target.can_pull_size), "actual net release restores the target pull-size default")
	TEST_ASSERT(!QDELETED(target), "actual net cleanup preserves its released target")

/datum/unit_test/interim_energy_net_early_release/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/target = allocate(/mob/living/carbon/human, T)
	var/obj/effect/energy_net/net = allocate(/obj/effect/energy_net, T)
	TEST_ASSERT(net.buckle_mob(target), "actual net restrains the real target before its deadline")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(net), 1, "actual occupied net still has its initial deadline")
	net.unbuckle_mob(target)
	TEST_ASSERT(QDELETED(net), "actual early release consumes the net")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(net), 0, "real early release cancels the source deadline")
	test_time(2 SECONDS)
	TEST_ASSERT_NULL(target.buckled_to(), "passing the canceled deadline keeps the real target released")
	TEST_ASSERT_EQUAL(target.can_pull_size, initial(target.can_pull_size), "passing the canceled deadline preserves restored pull capability")
	TEST_ASSERT(!QDELETED(target), "canceled net deadline preserves the real target")
