// Native request fields are assigned after construction; prepare must register both captured references.
/datum/unit_test/dq_eg2/interim_faction_request_refs

/datum/unit_test/dq_eg2/interim_faction_request_refs/run_gate()
	var/mob/living/carbon/human/inviter = person()
	var/mob/living/carbon/human/joiner = person()
	var/datum/mind/player = allocate(/datum/mind)
	own(player.antag_holder)
	var/datum/antagonist/faction = allocate(/datum/antagonist)
	var/datum/prompt/choice/faction_join/asked = open_request(inviter, /datum/prompt/choice/faction_join, TYPE_PROC_REF(/mob/living, faction_join_answered), answerer = joiner, asker = inviter, player = player, faction = faction)
	TEST_ASSERT(SSrequests.open_for(joiner) == asked, "The real faction request is open for its actual answerer")
	TEST_ASSERT(asked.player == player && asked.faction == faction, "Prepare preserves both original captured identities")
	TEST_ASSERT_EQUAL(length(asked.choices), 2, "Faction confirmation retains exactly two buttons")
	TEST_ASSERT_EQUAL(asked.choices[1], "No!", "The refusal button stays first")
	TEST_ASSERT_EQUAL(asked.choices[2], "Yes!", "The acceptance button stays second")
	qdel(player)
	TEST_ASSERT_NULL(asked.player, "Deleting the captured mind clears the prepared request's real reference")
	TEST_ASSERT(asked.faction == faction, "Deleting the mind preserves the independent faction capture")
	test_answer(joiner, "Yes!")
	TEST_ASSERT_NULL(SSrequests.open_for(joiner), "An answer after the captured mind disappears ends the real request")

	var/datum/mind/second_player = allocate(/datum/mind)
	own(second_player.antag_holder)
	var/datum/antagonist/second_faction = allocate(/datum/antagonist)
	var/datum/prompt/choice/faction_join/second = open_request(inviter, /datum/prompt/choice/faction_join, TYPE_PROC_REF(/mob/living, faction_join_answered), answerer = joiner, asker = inviter, player = second_player, faction = second_faction)
	TEST_ASSERT(second.player == second_player && second.faction == second_faction, "The second request captures its exact original participants")
	qdel(second_faction)
	TEST_ASSERT_NULL(second.faction, "Deleting the captured faction clears the prepared request's real reference")
	TEST_ASSERT(second.player == second_player, "Deleting the faction preserves the independent mind capture")
	test_answer(joiner, "Yes!")
	TEST_ASSERT_NULL(SSrequests.open_for(joiner), "An answer after the captured faction disappears ends the real request")
