/// A body nobody plays is put to sleep by its life while the test's clock runs: a controller keeps it awake.
/datum/unit_test/proc/interim_keep_awake(mob/living/carbon/human/H)
	var/mob/controller = allocate(/mob/living/simple_mob/e0_fixture, run_loc_floor_bottom_left)
	rel_set(H, nameof(H.teleop), controller)

/// Assemble the actual wired/electropack trap through its normal item effects.
/datum/unit_test/proc/interim_rig_crate(obj/structure/closet/crate/crate, mob/living/carbon/human/installer)
	interim_keep_awake(installer)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, get_turf(crate), 1)
	TEST_ASSERT(installer.put_in_active_hand(cable), "the installer holds one real cable segment")
	test_click(installer, crate, cable)
	test_time(5 SECONDS)
	TEST_ASSERT(crate.rigged, "the actual cable interaction rigs the crate")
	TEST_ASSERT(QDELETED(cable), "rigging consumes the actual final cable segment")
	var/obj/item/radio/electropack/pack = allocate(/obj/item/radio/electropack, get_turf(crate))
	TEST_ASSERT(installer.put_in_active_hand(pack), "the installer holds the actual electropack")
	test_click(installer, crate, pack)
	test_time(5 SECONDS)
	TEST_ASSERT_EQUAL(pack.loc, crate, "the actual rigging effect places the electropack inside the crate")
	TEST_ASSERT(pack in crate.slot_contents(), "the actual container ledger includes the trap's electropack")
	TEST_ASSERT_NULL(installer.get_active_hand(), "attaching the electropack vacates its real hand slot")
	return TRUE

/datum/unit_test/interim_crate_hand_opener_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/opener = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/obj/structure/closet/crate/crate = allocate(/obj/structure/closet/crate, T)
	TEST_ASSERT(interim_rig_crate(crate, opener), "the actual trap is assembled")
	TEST_ASSERT(!opener.has_status(STAT_STUNNED), "the explicit opener starts unstunned")
	test_click(opener, crate, null)
	test_time(5 SECONDS)
	own_turf_contents(T)
	TEST_ASSERT(opener.has_status(STAT_STUNNED), "the real hand and toggle opening chain electrocutes the explicit opener")
	TEST_ASSERT(!bystander.has_status(STAT_STUNNED), "the real trap leaves the nearby bystander unstunned")
	TEST_ASSERT(!crate.opened, "the actual shock prevents the stunned opener from completing the opening")
	TEST_ASSERT_EQUAL(length(crate.slot_contents()), 1, "the prevented opening retains the actual electropack")
	test_driver_end()

/datum/unit_test/interim_crate_relay_opener_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/opener = allocate(/mob/living/carbon/human, T)
	var/obj/structure/closet/crate/crate = allocate(/obj/structure/closet/crate, T)
	TEST_ASSERT(interim_rig_crate(crate, opener), "the actual trap is assembled")
	opener.forceMove(crate)
	TEST_ASSERT_EQUAL(opener.loc, crate, "the actual relay fixture places the opener inside the crate")
	crate.relaymove(opener)
	test_time(5 SECONDS)
	own_turf_contents(T)
	TEST_ASSERT(opener.has_status(STAT_STUNNED), "the real escape relay forwards its actor into the trap")
	TEST_ASSERT(!crate.opened, "the real trap stops the escape opening")
	TEST_ASSERT_EQUAL(opener.loc, crate, "the prevented opening retains the actual occupant")
	test_driver_end()

/datum/unit_test/interim_crate_automated_open_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/installer = allocate(/mob/living/carbon/human, T)
	var/obj/structure/closet/crate/crate = allocate(/obj/structure/closet/crate, T)
	TEST_ASSERT(interim_rig_crate(crate, installer), "the actual trap is assembled")
	TEST_ASSERT_EQUAL(crate.open(), 1, "an actorless automated opening still completes")
	own_turf_contents(T)
	TEST_ASSERT(crate.opened, "the actual automated opening updates the crate state")
	TEST_ASSERT(!installer.has_status(STAT_STUNNED), "an automated opening cannot invent a player victim")
	TEST_ASSERT_EQUAL(length(crate.slot_contents()), 0, "the actual automated opening empties the container ledger")
	var/obj/item/radio/electropack/pack = locate_within(T, /obj/item/radio/electropack)
	TEST_ASSERT(pack, "the actual opening releases its electropack onto the floor")
	TEST_ASSERT_EQUAL(pack.loc, T, "the electropack retains the actual floor destination")
	test_driver_end()
