/// A real captured soul jumps its own actual eye; another soul's eye stays put.
/datum/unit_test/om/interim_soulcatcher_hud_jump_actor/run_om(list/made)
	var/turf/start = run_loc_floor_bottom_left
	var/turf/destination = get_step(start, EAST)
	TEST_ASSERT(isturf(destination) && destination != start, "the real projection destination differs from its origin")
	var/obj/soulgem/gem = allocate(/obj/soulgem, destination)
	var/mob/living/carbon/brain/caught_soul/vore/actor = allocate(/mob/living/carbon/brain/caught_soul/vore, start)
	var/mob/living/carbon/brain/caught_soul/vore/bystander = allocate(/mob/living/carbon/brain/caught_soul/vore, start)
	rel_set(actor, nameof(actor.gem), gem)
	rel_set(bystander, nameof(bystander.gem), gem)
	var/mob/observer/eye/actor_eye = allocate(/mob/observer/eye, start)
	var/mob/observer/eye/bystander_eye = allocate(/mob/observer/eye, start)
	actor_eye.forceMove(start)
	bystander_eye.forceMove(start)
	TEST_ASSERT(actor.take_eye(actor_eye), "the actor acquires its actual active-eye relation")
	TEST_ASSERT(bystander.take_eye(bystander_eye), "the bystander acquires a separate actual active-eye relation")
	TEST_ASSERT_EQUAL(get_turf(actor_eye), start, "the actual actor eye begins at the known origin")
	TEST_ASSERT_EQUAL(get_turf(bystander_eye), start, "the actual bystander eye begins at the known origin")
	var/atom/movable/screen/nifsc/jumptoowner/button = allocate(/atom/movable/screen/nifsc/jumptoowner)
	km_synthetic_click(actor, button)
	TEST_ASSERT_EQUAL(get_turf(actor_eye), destination, "the actual native HUD click moves the initiating soul's eye to its real gem")
	TEST_ASSERT_EQUAL(get_turf(bystander_eye), start, "the actual native HUD click leaves the unrelated soul's eye in place")
	actor_eye.forceMove(start)
	button.click_with_actor(bystander, null, null, null)
	TEST_ASSERT_EQUAL(get_turf(bystander_eye), destination, "the helper executes the actual jump for its explicit other soul")
	TEST_ASSERT_EQUAL(get_turf(actor_eye), start, "the explicit other soul preserves the first soul's actual eye position")
	var/mob/living/carbon/human/unsupported = allocate(/mob/living/carbon/human, start)
	button.click_with_actor(unsupported, null, null, null)
	button.click_with_actor(null, null, null, null)
	TEST_ASSERT_EQUAL(get_turf(actor_eye), start, "unsupported and null actors do not move the first actual eye")
	TEST_ASSERT_EQUAL(get_turf(bystander_eye), destination, "unsupported and null actors do not move the second actual eye")
	TEST_ASSERT_EQUAL(actor.drop_eye(), actor_eye, "normal relation cleanup releases the actor's exact actual eye")
	TEST_ASSERT_EQUAL(bystander.drop_eye(), bystander_eye, "normal relation cleanup releases the bystander's exact actual eye")

/// The real captured-soul speech/emote handlers open typed prompts for the explicit HUD actor.
/datum/unit_test/om/interim_soulcatcher_hud_prompt_actor/run_om(list/made)
	test_prompts_reset()
	var/mob/living/carbon/brain/caught_soul/actor = allocate(/mob/living/carbon/brain/caught_soul, run_loc_floor_bottom_left)
	var/mob/living/carbon/brain/caught_soul/bystander = allocate(/mob/living/carbon/brain/caught_soul, run_loc_floor_bottom_left)
	var/atom/movable/screen/nifsc/nme/emote_button = allocate(/atom/movable/screen/nifsc/nme)
	var/atom/movable/screen/nifsc/nsay/speech_button = allocate(/atom/movable/screen/nifsc/nsay)
	km_synthetic_click(actor, emote_button)
	TEST_ASSERT_EQUAL(length(GLOB.test_prompts), 1, "the actual native emote click opens one real typed prompt")
	var/datum/prompt/text/emote_ask = GLOB.test_prompts[1]
	made += emote_ask
	TEST_ASSERT_EQUAL(emote_ask.answerer, actor, "the actual emote prompt retains the exact native actor")
	TEST_ASSERT_EQUAL(test_prompt_answer(emote_ask, null, TRUE), "no answer", "the real typed emote cancellation is delivered")
	speech_button.click_with_actor(bystander, null, null, null)
	TEST_ASSERT_EQUAL(length(GLOB.test_prompts), 2, "a separate explicit soul opens its real speech prompt")
	var/datum/prompt/text/speech_ask = GLOB.test_prompts[2]
	made += speech_ask
	TEST_ASSERT_EQUAL(speech_ask.answerer, bystander, "the actual speech prompt belongs to the explicit other soul")
	TEST_ASSERT_EQUAL(test_prompt_answer(speech_ask, null, TRUE), "no answer", "the real typed speech cancellation is delivered")
	var/mob/living/carbon/human/unsupported = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	var/list/buttons = list(emote_button, speech_button)
	for(var/atom/movable/screen/nifsc/button as anything in buttons)
		button.click_with_actor(unsupported, null, null, null)
		button.click_with_actor(null, null, null, null)
	TEST_ASSERT_EQUAL(length(GLOB.test_prompts), 2, "unsupported and null actors open no captured-soul prompts")
	TEST_ASSERT_NULL(actor.active_eye(), "actual cancellation creates no projection for the first soul")
	TEST_ASSERT_NULL(bystander.active_eye(), "actual cancellation creates no projection for the other soul")
