/// The actual pneumatic tank-insertion route respects source inventory release and returns the same tank without spending any gas.
/datum/unit_test/interim_pneumatic_sticky_tank/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/gun/launcher/pneumatic/cannon = allocate(/obj/item/gun/launcher/pneumatic, T)
	var/obj/item/tank/oxygen/tank = allocate(/obj/item/tank/oxygen, T)
	TEST_ASSERT(user.put_in_inactive_hand(cannon), "the actor holds the actual cannon in its inactive hand")
	TEST_ASSERT(user.put_in_active_hand(tank), "the actor holds the original oxygen tank in its active hand")
	TEST_ASSERT_NOTNULL(tank.air_contents, "the actual oxygen tank has its real gas mixture")
	var/moles_before = tank.air_contents.total_moles()
	var/pressure_before = tank.air_contents.return_pressure()
	var/setting_before = cannon.pressure_setting
	TEST_ASSERT(moles_before > 0 && pressure_before > 0, "the actual oxygen tank starts with positive gas and pressure")
	TEST_ASSERT_NULL(cannon.tank(), "the actual cannon starts without a tank relation")
	add_trait(tank, TRAIT_NODROP, "interim_pneumatic_sticky_tank")
	TEST_ASSERT(user.release_refusal(tank, user), "the actual inventory refuses release of its sticky tank")
	test_op_handler(cannon, "gun_item", user, tank)
	TEST_ASSERT_NULL(cannon.tank(), "refused insertion records no tank relation")
	TEST_ASSERT_EQUAL(tank.loc, user, "refused insertion preserves actual tank inventory containment")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tank, "refused insertion preserves the original active tank hand")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), cannon, "refused insertion preserves the original inactive cannon hand")
	TEST_ASSERT_EQUAL(tank.air_contents.total_moles(), moles_before, "refused insertion preserves every original gas mole")
	remove_trait(tank, TRAIT_NODROP, "interim_pneumatic_sticky_tank")
	test_op_handler(cannon, "gun_item", user, tank)
	TEST_ASSERT_EQUAL(cannon.tank(), tank, "allowed insertion records the original tank relation")
	TEST_ASSERT_EQUAL(tank.loc, cannon, "allowed insertion physically contains the original tank")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears the original source hand")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), cannon, "allowed insertion preserves its actual held cannon")
	cannon.eject_tank(user)
	TEST_ASSERT_NULL(cannon.tank(), "actual tank ejection clears the relation")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tank, "actual ejection returns the original tank to the free active hand")
	TEST_ASSERT_EQUAL(tank.loc, user, "actual ejection restores original tank inventory containment")
	TEST_ASSERT_EQUAL(tank.air_contents.total_moles(), moles_before, "the actual round trip conserves all original tank gas")
	TEST_ASSERT_EQUAL(tank.air_contents.return_pressure(), pressure_before, "the actual round trip preserves original tank pressure")
	TEST_ASSERT_EQUAL(cannon.pressure_setting, setting_before, "the actual round trip preserves its original valve setting")
	qdel(cannon)
	TEST_ASSERT(!QDELETED(tank), "empty cannon teardown preserves the returned original tank")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tank, "empty cannon teardown preserves the returned tank's actual hand")
