/// Actual ashtray insertion must respect inventory release before accepting its original butt.
/datum/unit_test/interim_ashtray_sticky_butt/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/material/ashtray/tray = allocate(/obj/item/material/ashtray, T, MAT_STEEL)
	var/obj/item/trash/cigbutt/butt = allocate(/obj/item/trash/cigbutt, T)
	TEST_ASSERT(!QDELETED(tray) && tray.get_integrity() > 0, "actual steel ashtray survives material initialization with real integrity")
	TEST_ASSERT(tray.max_butts > 0, "actual material-derived ashtray capacity accepts a first butt")
	TEST_ASSERT_EQUAL(contents_count(tray), 0, "actual initialized ashtray starts empty")
	TEST_ASSERT(user.put_in_active_hand(butt), "the actor holds exact original butt")
	add_trait(butt, TRAIT_NODROP, "interim_ashtray_butt")
	TEST_ASSERT(user.release_refusal(butt, user), "actual inventory refuses sticky original butt")
	test_op_handler(tray, "butt_added", user, butt)
	TEST_ASSERT_EQUAL(user.get_active_hand(), butt, "refused insertion preserves exact original hand")
	TEST_ASSERT_EQUAL(butt.loc, user, "refused insertion preserves inventory containment")
	TEST_ASSERT_EQUAL(contents_count(tray), 0, "refused insertion physically contains no butt")
	remove_trait(butt, TRAIT_NODROP, "interim_ashtray_butt")
	test_op_handler(tray, "butt_added", user, butt)
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears actual source hand")
	TEST_ASSERT_EQUAL(butt.loc, tray, "allowed insertion physically contains exact original butt")
	TEST_ASSERT_EQUAL(contents_count(tray), 1, "allowed insertion adds exactly one original physical butt")
	TEST_ASSERT_NULL(owner_of(butt), "ashtray insertion preserves existing unowned containment policy")
	var/obj/item/trash/cigbutt/replacement = allocate(/obj/item/trash/cigbutt, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds a real second original butt")
	tray.set_max_butts(1)
	test_op_handler(tray, "butt_added", user, replacement)
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "actual full-capacity refusal preserves second original hand")
	TEST_ASSERT_EQUAL(replacement.loc, user, "actual full-capacity refusal preserves second inventory containment")
	TEST_ASSERT_EQUAL(butt.loc, tray, "actual full-capacity refusal preserves stored original butt")
	TEST_ASSERT_EQUAL(contents_count(tray), 1, "actual full-capacity refusal adds no extra physical butt")
