/// Actual nanomass credit follows successful original nanopaste consumption.
/datum/unit_test/interim_reconstitutor_sticky_paste/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/protean_reconstitutor/machine = allocate(/obj/machinery/protean_reconstitutor, T)
	var/obj/item/stack/nanopaste/paste = allocate(/obj/item/stack/nanopaste, T)
	TEST_ASSERT_EQUAL(machine.nanomass_reserve, 0, "actual initialized reconstitutor starts with no nanomass")
	TEST_ASSERT_EQUAL(machine.paste_inefficiency, 5, "actual default machine uses its fivefold paste divisor")
	TEST_ASSERT_EQUAL(paste.get_amount(), 10, "actual default original paste has ten swarms")
	TEST_ASSERT_EQUAL(paste.mech_repair, 10, "actual original paste has its declared repair strength")
	TEST_ASSERT(user.put_in_active_hand(paste), "actor holds exact original paste stack")
	add_trait(paste, TRAIT_NODROP, "interim_reconstitutor_paste")
	TEST_ASSERT(user.release_refusal(paste, user), "actual inventory refuses sticky original paste")
	test_op_handler(machine, "reconstitutor_interaction_item", user, paste)
	TEST_ASSERT_EQUAL(machine.nanomass_reserve, 0, "refused consumption credits no nanomass")
	TEST_ASSERT(!QDELETED(paste), "refused consumption preserves original stack alive")
	TEST_ASSERT_EQUAL(paste.get_amount(), 10, "refused consumption preserves all original swarms")
	TEST_ASSERT_EQUAL(user.get_active_hand(), paste, "refused consumption preserves exact original hand")
	TEST_ASSERT_EQUAL(paste.loc, user, "refused consumption preserves inventory location")
	remove_trait(paste, TRAIT_NODROP, "interim_reconstitutor_paste")
	test_op_handler(machine, "reconstitutor_interaction_item", user, paste)
	TEST_ASSERT(QDELETED(paste), "allowed filling consumes exact original paste stack")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed filling clears actual source hand")
	TEST_ASSERT_EQUAL(machine.nanomass_reserve, 20, "actual ten original swarms credit twenty nanomass at declared default efficiency")
	var/obj/item/stack/nanopaste/replacement = allocate(/obj/item/stack/nanopaste, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "actor holds second original paste stack")
	set_var(machine, nameof(machine.nanomass_reserve), machine.nanotank_max)
	test_op_handler(machine, "reconstitutor_interaction_item", user, replacement)
	TEST_ASSERT_EQUAL(machine.nanomass_reserve, machine.nanotank_max, "actual full-tank refusal preserves full reserve")
	TEST_ASSERT(!QDELETED(replacement), "actual full-tank refusal preserves original second stack alive")
	TEST_ASSERT_EQUAL(replacement.get_amount(), 10, "actual full-tank refusal preserves second stack amount")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "actual full-tank refusal preserves exact second hand")
