/// Oversized transfers of a fractional remainder must drain both mixture entries and their real holder indexes, without manufacturing the requested excess.
/datum/unit_test/interim_reagent_fractional_depletion/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/item/reagent_containers/glass/beaker/source = allocate(/obj/item/reagent_containers/glass/beaker, T)
	var/obj/item/reagent_containers/glass/beaker/target = allocate(/obj/item/reagent_containers/glass/beaker, T)
	source.reagents.add_reagent(REAGENT_ID_WATER, 1.5)
	source.reagents.add_reagent(REAGENT_ID_ETHANOL, 0.5)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 2, "the actual source starts with a two-unit mixed solution")
	TEST_ASSERT_EQUAL(length(source.reagents.reagent_list), 2, "the actual source starts with both reagent entries")
	TEST_ASSERT(abs(source.reagents.trans_to_holder(target.reagents, 0.5) - 0.5) < 0.001, "the actual first transfer debits its fractional requested dose")
	TEST_ASSERT(abs(source.reagents.get_reagent_amount(REAGENT_ID_WATER) - 1.125) < 0.001, "the actual fractional transfer leaves the proportional water remainder")
	TEST_ASSERT(abs(source.reagents.get_reagent_amount(REAGENT_ID_ETHANOL) - 0.375) < 0.001, "the actual fractional transfer leaves the proportional ethanol remainder")
	TEST_ASSERT(abs(target.reagents.get_reagent_amount(REAGENT_ID_WATER) - 0.375) < 0.001, "the actual target receives the fractional water share")
	TEST_ASSERT(abs(target.reagents.get_reagent_amount(REAGENT_ID_ETHANOL) - 0.125) < 0.001, "the actual target receives the fractional ethanol share")
	TEST_ASSERT(abs(source.reagents.trans_to_holder(target.reagents, 100) - 1.5) < 0.001, "the actual oversized request reports only the fractional remainder debited")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 0, "the actual oversized transfer completely drains the source")
	TEST_ASSERT_EQUAL(length(source.reagents.reagent_list), 0, "actual depletion removes both reagent entries rather than skipping one during removal")
	TEST_ASSERT_EQUAL(source.reagents.get_reagent_amount(REAGENT_ID_WATER), 0, "actual depletion clears the water lookup")
	TEST_ASSERT_EQUAL(source.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 0, "actual depletion clears the ethanol lookup")
	TEST_ASSERT(abs(target.reagents.total_volume - 2) < 0.001, "the actual target receives only the original source volume")
	TEST_ASSERT(abs(target.reagents.get_reagent_amount(REAGENT_ID_WATER) - 1.5) < 0.001, "actual complete transfer conserves the original water dose")
	TEST_ASSERT(abs(target.reagents.get_reagent_amount(REAGENT_ID_ETHANOL) - 0.5) < 0.001, "actual complete transfer conserves the original ethanol dose")
	TEST_ASSERT(!source.reagents.trans_to_holder(target.reagents, 100), "the actual depleted source refuses another oversized request")
	TEST_ASSERT(abs(target.reagents.total_volume - 2) < 0.001, "the actual empty-source refusal preserves the delivered solution")
