/// The actual airlock control-wire pulse respects an intact ID scanner, bypasses it only while that wire is cut, and returns to access-gated behavior after mending.
/datum/unit_test/om/interim_airlock_id_wire_pulse
	parent_type = /datum/unit_test/dq_p2_door

/datum/unit_test/om/interim_airlock_id_wire_pulse/run_gate()
	var/turf/T = tile(2, 2)
	var/mob/living/carbon/human/user = make_person(null, tile(3, 2))
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock, T)
	p2_door_set_power(door, TRUE)
	door.set_autoclose(FALSE)
	door.req_access = list(ACCESS_SECURITY)
	var/list/access_before = door.req_access
	var/datum/wires_test_adapter/wires = wires_test(door)
	TEST_ASSERT(istype(wires), "the actual airlock creates its real airlock wires datum")
	TEST_ASSERT(door.power_systems_on(), "the actual wire-pulse fixture has available actuator power")
	TEST_ASSERT(door.requiresID() && !door.check_access(null), "the actual restricted airlock starts with an intact ID scanner")
	var/timers_before = time_scheduler().timer_count(door)
	wires.pulse(WIRE_OPEN_DOOR, user)
	TEST_ASSERT(door.density && !door.operating, "actual control-wire pulse cannot open the restricted airlock with an intact scanner")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), timers_before, "actual access-refused pulse schedules no opening animation")
	wires.cut(WIRE_IDSCAN, user)
	TEST_ASSERT(wires.is_cut(WIRE_IDSCAN), "the actual interactive wire API cuts the scanner wire")
	TEST_ASSERT(wire_is_cut(door, WIRE_IDSCAN), "the actual door reads its subtype capability wire state")
	TEST_ASSERT(door.aiDisabledIdScanner && !door.requiresID(), "actual scanner-wire cutting disables scanner requirements")
	TEST_ASSERT_EQUAL(door.req_access, access_before, "actual scanner-wire cutting preserves the original access-list identity")
	wires.pulse(WIRE_OPEN_DOOR, user)
	TEST_ASSERT(door.operating && door.density, "actual control-wire pulse starts opening while density remains until animation")
	TEST_ASSERT(time_scheduler().timer_count(door) > timers_before, "actual scanner-bypassing pulse schedules a real opening animation")
	test_time(2 SECONDS)
	TEST_ASSERT(!door.density && !door.opacity && !door.operating, "the actual scanner-bypassing animation opens the passage and finishes idle")
	wires.cut(WIRE_IDSCAN, user)
	TEST_ASSERT(!wires.is_cut(WIRE_IDSCAN) && !wire_is_cut(door, WIRE_IDSCAN), "the actual interactive wire API mends the scanner wire")
	TEST_ASSERT(!door.aiDisabledIdScanner && door.requiresID(), "actual scanner-wire mending restores scanner requirements")
	TEST_ASSERT_EQUAL(door.req_access, access_before, "actual scanner-wire mending retains the exact original access-list identity")
	var/open_timers = time_scheduler().timer_count(door)
	wires.pulse(WIRE_OPEN_DOOR, user)
	TEST_ASSERT(!door.density && !door.operating, "actual control-wire pulse is access-gated again and cannot close the restricted passage after mending")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), open_timers, "actual access-restored pulse schedules no closing animation")
	TEST_ASSERT(!wire_is_cut(door, WIRE_OPEN_DOOR), "all actual scanner changes preserve the distinct control wire")
