/// Real filter transition effects only; no administrative UI or request acceptance claim.
/datum/unit_test/om/interim_filter_editor_color_actor/run_om(list/made)
	var/obj/item/pen/target = allocate(/obj/item/pen, run_loc_floor_bottom_left)
	var/datum/filter_editor/editor = allocate(/datum/filter_editor, target)
	target.add_filter("actor_color", 1, list("type" = "color", "color" = "#FFFFFF"))
	TEST_ASSERT_EQUAL(editor.apply_filter_colour("actor_color", "#123456"), TRUE, "the actual transition effect handles a nonblank answer")
	TEST_ASSERT_EQUAL(target.filter_data["actor_color"]["color"], "#123456", "the actual filter transition stores the supplied answer color")
	TEST_ASSERT_EQUAL(target.filter_data["actor_color"]["priority"], 1, "the actual color transition preserves filter priority")
	TEST_ASSERT_NULL(editor.apply_filter_colour("actor_color", ""), "blank color has the original unhandled effect result")
	TEST_ASSERT_EQUAL(target.filter_data["actor_color"]["color"], "#123456", "blank color leaves the actual filter unchanged")

/datum/unit_test/interim_filter_editor_mass_apply_refusal/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	TEST_ASSERT_NULL(actor.client, "the actual fixture has no native admin client")
	var/obj/item/pen/target = allocate(/obj/item/pen, T)
	var/obj/item/pen/other = allocate(/obj/item/pen, T)
	var/datum/filter_editor/editor = allocate(/datum/filter_editor, target)
	target.add_filter("source_color", 1, list("type" = "color", "color" = "#123456"))
	other.add_filter("other_color", 2, list("type" = "color", "color" = "#654321"))
	editor.ui_act_mass_apply(actor, list("path" = /obj/item/pen), null, null, "mass_apply")
	TEST_ASSERT_EQUAL(other.filter_data["other_color"]["color"], "#654321", "the actual rights refusal preserves the unrelated target's own filter")
	TEST_ASSERT_NULL(other.filter_data["source_color"], "a clientless actor cannot mass-copy actual source filters")
	TEST_ASSERT_EQUAL(target.filter_data["source_color"]["color"], "#123456", "the actual rights refusal preserves the source filter")
	editor.ui_act_mass_apply(null, list("path" = /obj/item/pen), null, null, "mass_apply")
	TEST_ASSERT_NULL(other.filter_data["source_color"], "an absent actor cannot mass-copy the source filters")
