/// Drive completed construction steps directly: no tool delay or scheduler timing is involved.
/datum/unit_test/proc/interim_construction_step(atom/target, mob/actor, edge_type, obj/item/held)
	var/datum/construction_graph/graph = construction_graph_of(target)
	if(!graph)
		return FALSE
	for(var/datum/interaction/construction/edge as anything in graph.edges_for(target))
		if(edge.type == edge_type)
			return edge.traverse(target, actor, held)
	return FALSE

/datum/unit_test/interim_airlock_mechanical_gates/Run()
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock)
	TEST_ASSERT(door.density, "Airlock must start closed")
	TEST_ASSERT(door.can_open(TRUE), "An unlocked closed airlock must permit forced opening")
	TEST_ASSERT(!door.can_close(TRUE), "A closed airlock cannot close again")
	door.set_bolted(TRUE, TRUE)
	TEST_ASSERT(is_bolted(door), "Dropping the bolts did not change their state")
	TEST_ASSERT(!door.can_open(TRUE), "Forced opening must respect bolts")
	door.set_bolted(FALSE, TRUE)
	TEST_ASSERT(!is_bolted(door), "Forced unbolting did not raise the bolts")
	set_welded(door, TRUE)
	TEST_ASSERT(is_welded(door), "Welding did not change the airlock state")
	TEST_ASSERT(!door.can_open(TRUE), "Forced opening must respect welding")
	set_welded(door, FALSE)
	TEST_ASSERT(door.can_open(TRUE), "Removing both mechanical restrictions must allow opening")
	door.set_density(FALSE)
	TEST_ASSERT(!door.can_open(TRUE), "An open airlock cannot open again")
	TEST_ASSERT(door.can_close(TRUE), "An open unrestricted airlock must permit forced closing")
	door.set_bolted(TRUE, TRUE)
	TEST_ASSERT(!door.can_close(TRUE), "Bolts must prevent closing an open airlock")
	door.set_bolted(FALSE, TRUE)
	set_welded(door, TRUE)
	TEST_ASSERT(!door.can_close(TRUE), "Welding must prevent closing an open airlock")

/datum/unit_test/interim_airlock_electronics_emag/Run()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	var/obj/item/airlock_electronics/electronics = allocate(/obj/item/airlock_electronics)
	TEST_ASSERT(!electronics.emagged, "Electronics must start with intact access restrictions")
	TEST_ASSERT_EQUAL(emag_target(electronics, 1, actor), 1, "First emag must consume one use")
	TEST_ASSERT(electronics.emagged, "Successful emag did not remove access restrictions")
	TEST_ASSERT_EQUAL(emag_target(electronics, 1, actor), EMAG_DECLINED, "Already emagged electronics must refuse another use")
	TEST_ASSERT(electronics.emagged, "Declined repeat emag must retain the bypass")

/datum/unit_test/interim_girder_secure_displace/Run()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	var/obj/structure/girder/girder = allocate(/obj/structure/girder)
	var/full_integrity = girder.get_integrity()
	var/full_cover = girder.cover
	TEST_ASSERT(girder.anchored && full_integrity > girder.displaced_health, "Girder must start secured at full integrity")
	TEST_ASSERT(interim_construction_step(girder, actor, /datum/interaction/construction/girder/dislodge), "Dislodging step was unavailable or failed")
	TEST_ASSERT(!girder.anchored, "Dislodging did not release the girder")
	TEST_ASSERT_EQUAL(girder.get_integrity(), girder.displaced_health, "Dislodging must reduce integrity to the displaced allowance")
	TEST_ASSERT(girder.cover < full_cover, "Dislodging must reduce projectile cover")
	TEST_ASSERT(interim_construction_step(girder, actor, /datum/interaction/construction/girder/secure), "Securing step was unavailable or failed")
	TEST_ASSERT(girder.anchored, "Securing did not anchor the girder")
	TEST_ASSERT_EQUAL(girder.get_integrity(), full_integrity, "Securing must restore full integrity")
	TEST_ASSERT_EQUAL(girder.cover, full_cover, "Securing must restore cover")
	var/datum/construction_graph/graph = construction_graph_of(girder)
	TEST_ASSERT_EQUAL(graph.state_of(girder), "anchored", "Secured girder must offer the anchored construction steps")

/datum/unit_test/interim_machine_frame_board_and_wiring/Run()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	var/obj/structure/frame/frame = allocate(/obj/structure/frame)
	var/obj/item/circuitboard/autolathe/board = allocate(/obj/item/circuitboard/autolathe)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, run_loc_floor_bottom_left, 6)
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/anchor), "Frame anchoring failed")
	TEST_ASSERT(frame.anchored && frame.state == FRAME_PLACED, "Anchoring must leave an empty placed frame")
	TEST_ASSERT_EQUAL(frame.accepts_board(actor, frame, board), TRUE, "Machine frame must accept an autolathe board")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/insert_board, board), "Board insertion failed")
	TEST_ASSERT_EQUAL(frame.state, FRAME_UNFASTENED, "Inserted board must initially be unfastened")
	TEST_ASSERT_EQUAL(frame.circuit, board, "Frame did not retain its inserted board")
	TEST_ASSERT_EQUAL(board.loc, frame, "Inserted board must reside inside the frame")
	TEST_ASSERT(frame.req_components[/obj/item/stock_parts/matter_bin] > 0, "Inserted board did not populate real component requirements")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/fasten_board), "Board fastening failed")
	TEST_ASSERT_EQUAL(frame.state, FRAME_FASTENED, "Fastening must advance the frame state")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/wire, cable), "Wiring failed")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "Wiring must advance the frame state")
	TEST_ASSERT_EQUAL(cable.get_amount(), 1, "Wiring must consume exactly five cable lengths")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/unwire), "Unwiring failed")
	own_turf_contents(get_turf(frame))
	TEST_ASSERT_EQUAL(frame.state, FRAME_FASTENED, "Unwiring must return to a fastened board")
	var/returned_cable = 0
	for(var/obj/item/stack/cable_coil/returned as anything in turf_contents_of_type(get_turf(frame), /obj/item/stack/cable_coil))
		returned_cable += returned.get_amount()
	TEST_ASSERT_EQUAL(returned_cable, 6, "Unwiring must return the five consumed lengths alongside the remaining one")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/unfasten_board), "Board unfastening failed")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/remove_board), "Board removal failed")
	TEST_ASSERT_EQUAL(frame.state, FRAME_PLACED, "Removing the board must leave a placed frame")
	TEST_ASSERT_NULL(frame.circuit, "Board removal must clear the owned circuit reference")
	TEST_ASSERT_EQUAL(board.loc, get_turf(frame), "Removed board must return to the floor")
	TEST_ASSERT_NULL(frame.req_components, "Removing the board must clear its component requirements")

/datum/unit_test/interim_wall_reversible_construction/Run()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	var/restore_floor_type = run_loc_floor_bottom_left.type
	var/turf/simulated/wall/wall = run_loc_floor_bottom_left.ChangeTurf(/turf/simulated/wall)
	defer_cleanup(wall, TYPE_PROC_REF(/turf, ChangeTurf), restore_floor_type)
	var/datum/material/steel = get_material_by_name(MAT_STEEL)
	wall.set_material(steel, steel, steel)
	TEST_ASSERT_EQUAL(wall.construction_stage, 6, "A reinforced wall must start with an intact outer grille")
	TEST_ASSERT(interim_construction_step(wall, actor, /datum/interaction/construction/wall/cut_grille), "Cutting the grille failed")
	TEST_ASSERT_EQUAL(wall.construction_stage, 5, "Cutting the grille must expose the support lines")
	TEST_ASSERT(interim_construction_step(wall, actor, /datum/interaction/construction/wall/unscrew_lines), "Unscrewing the support lines failed")
	TEST_ASSERT_EQUAL(wall.construction_stage, 4, "Unscrewing must expose the cover")
	TEST_ASSERT(interim_construction_step(wall, actor, /datum/interaction/construction/wall/screw_lines), "Reattaching the support lines failed")
	TEST_ASSERT_EQUAL(wall.construction_stage, 5, "Reattaching must restore the support lines")
	TEST_ASSERT(interim_construction_step(wall, actor, /datum/interaction/construction/wall/mend_grille), "Mending the grille failed")
	TEST_ASSERT_EQUAL(wall.construction_stage, 6, "Mending must restore the intact reinforced wall")
	TEST_ASSERT(wall.density && wall.reinf_material == steel, "Reversible construction must preserve the wall and its reinforcement")



/// Dispatching a UI action directly has no ambient usr: it must use the supplied actor.
/datum/unit_test/interim_airlock_electronics_login_actor/Run()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	actor.real_name = "Explicit Electronics Configurator"
	actor.name = actor.real_name
	var/obj/item/airlock_electronics/electronics = allocate(/obj/item/airlock_electronics)
	TEST_ASSERT(electronics.locked, "Electronics must initially be locked")
	TEST_ASSERT_EQUAL(emag_target(electronics, 1, actor), 1, "Fixture must bypass access checks")
	TEST_ASSERT(electronics.ui_act_login(actor, list()), "Login handler did not accept the explicit actor")
	TEST_ASSERT(!electronics.locked, "Emagged electronics must unlock for the supplied actor")
	TEST_ASSERT_EQUAL(electronics.last_configurator, actor.name, "Login attribution must identify the supplied actor")

/datum/unit_test/interim_airlock_wire_electrify_actor/Run()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	actor.real_name = "Explicit Wire Operator"
	actor.name = actor.real_name
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock)
	door.set_stat(0)
	TEST_ASSERT(door.arePowerSystemsOn(), "Fixture must have working airlock power")
	var/datum/wires/wires = wires_of(door)
	TEST_ASSERT_NOTNULL(wires, "Airlock did not provide wires")
	wires.pulse(WIRE_ELECTRIFY, actor)
	TEST_ASSERT(door.isElectrified(), "Pulsing the electrify wire must electrify the door")
	var/attributed = FALSE
	for(var/entry in door.shockedby)
		if(findtext(entry, actor.name))
			attributed = TRUE
	TEST_ASSERT(attributed, "Electrification history must credit the explicit wire operator")
	wires.cut(WIRE_ELECTRIFY, actor)
	TEST_ASSERT(wires.is_cut(WIRE_ELECTRIFY), "Cutting must sever the electrify wire")
	TEST_ASSERT_EQUAL(door.electrified_until, -1, "Cut wire must leave permanent electrification")
	wires.cut(WIRE_ELECTRIFY, actor)
	TEST_ASSERT(!wires.is_cut(WIRE_ELECTRIFY), "Second cut action must mend the wire")
	TEST_ASSERT(!door.isElectrified(), "Mending the electrify wire must remove electrification")

/// Exercise declared requirements as well as completion: wrong boards and short cable stacks refuse.
/datum/unit_test/interim_machine_frame_requirements/Run()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	var/obj/structure/frame/frame = allocate(/obj/structure/frame)
	var/obj/item/circuitboard/autolathe/machine_board = allocate(/obj/item/circuitboard/autolathe)
	var/obj/item/circuitboard/computer_board = allocate(/obj/item/circuitboard)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, run_loc_floor_bottom_left, 4)
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/anchor), "Fixture anchoring failed")
	var/datum/construction_graph/graph = construction_graph_of(frame)
	var/datum/interaction/construction/insert_board
	var/datum/interaction/construction/wire
	for(var/datum/interaction/construction/edge as anything in graph.edges)
		if(edge.type == /datum/interaction/construction/frame/insert_board)
			insert_board = edge
		if(edge.type == /datum/interaction/construction/frame/wire)
			wire = edge
	TEST_ASSERT_NOTNULL(insert_board, "Frame graph must have a board insertion edge")
	TEST_ASSERT_NOTNULL(wire, "Frame graph must have a wiring edge")
	TEST_ASSERT_EQUAL(insert_board.why_not(actor, frame, computer_board), "this frame does not accept circuit boards of this type", "Machine frame must refuse a computer board through its requirement")
	TEST_ASSERT_NULL(frame.circuit, "Checking a wrong board must leave the frame empty")
	TEST_ASSERT_EQUAL(computer_board.loc, get_turf(frame), "Checking a wrong board must not insert it")
	TEST_ASSERT_NULL(insert_board.why_not(actor, frame, machine_board), "Machine board must satisfy the same insertion requirement")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/insert_board, machine_board), "Fixture board insertion failed")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/fasten_board), "Fixture board fastening failed")
	TEST_ASSERT_NOTNULL(wire.why_not(actor, frame, cable), "Four cable lengths must fail the declared wiring requirement")
	TEST_ASSERT(!wire.traverse(frame, actor, cable), "Completion must recheck and refuse insufficient cable")
	TEST_ASSERT_EQUAL(frame.state, FRAME_FASTENED, "Refused wiring must not advance construction")
	TEST_ASSERT_EQUAL(cable.get_amount(), 4, "Refused wiring must not consume cable")
	cable.set_amount(6)
	TEST_ASSERT_NULL(wire.why_not(actor, frame, cable), "Sufficient cable must satisfy the wiring requirement")
	TEST_ASSERT(wire.traverse(frame, actor, cable), "Sufficient cable must allow completed wiring")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "Successful wiring must advance construction")
	TEST_ASSERT_EQUAL(cable.get_amount(), 1, "Successful wiring must consume exactly five cable lengths")

/datum/unit_test/interim_girder_resolver_refusals/Run()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	var/obj/structure/girder/girder = allocate(/obj/structure/girder)
	var/obj/item/tool/crowbar/crowbar = allocate(/obj/item/tool/crowbar)
	var/obj/item/tool/wrench/wrench = allocate(/obj/item/tool/wrench)
	var/datum/construction_graph/graph = construction_graph_of(girder)
	var/datum/interaction/construction/dislodge
	for(var/datum/interaction/construction/edge as anything in graph.edges)
		if(edge.type == /datum/interaction/construction/girder/dislodge)
			dislodge = edge
	TEST_ASSERT_NOTNULL(dislodge, "Girder graph must have a dislodging edge")
	var/datum/interaction_resolution/wrong_tool = interactions_for(actor, girder, wrench)
	TEST_ASSERT_EQUAL(wrong_tool.blocked[dislodge], "needs a crowbar", "Resolver must explain why a wrench cannot dislodge a girder")
	TEST_ASSERT(!(dislodge in wrong_tool.available), "Wrong-tool dislodging must not be available")
	TEST_ASSERT(!dislodge.perform(actor, girder, wrench), "Attempting the wrong tool must refuse before construction changes")
	TEST_ASSERT(girder.anchored, "Wrong-tool refusal must preserve anchoring")
	var/datum/interaction_resolution/right_tool = interactions_for(actor, girder, crowbar)
	TEST_ASSERT(dislodge in right_tool.available, "An adjacent actor with a crowbar must be offered dislodging")
	TEST_ASSERT_NULL(right_tool.blocked[dislodge], "Correct-tool dislodging must not remain blocked")
	actor.forceMove(get_step(get_step(get_turf(girder), EAST), EAST))
	var/datum/interaction_resolution/too_far = interactions_for(actor, girder, crowbar)
	TEST_ASSERT(too_far.blocked[dislodge], "Resolver must refuse a crowbar used beyond adjacent reach")
	TEST_ASSERT(!(dislodge in too_far.available), "A distant actor must not be offered dislodging")
	TEST_ASSERT(!dislodge.perform(actor, girder, crowbar), "Distant attempt must refuse before construction changes")
	TEST_ASSERT(girder.anchored, "Distant refusal must preserve anchoring")
	actor.forceMove(get_turf(girder))
	girder.displace()
	TEST_ASSERT_EQUAL(dislodge.why_not(actor, girder, crowbar), "it has changed", "A stale dislodging interaction must reject the changed girder state")

/// Run the real door's declared emag and animation timers on an isolated deterministic clock.
/datum/unit_test/om/interim_door_emag_reaction/run_om(list/made)
	var/obj/machinery/door/door = allocate(/obj/machinery/door)
	made += door
	door.set_stat(0)
	TEST_ASSERT(door.density && door.operable(), "Fixture door must be closed and operable")
	var/original_timers = om_timer_count(door)
	TEST_ASSERT_EQUAL(emag_target(door, 1), 1, "A closed operable door must consume one emag use")
	TEST_ASSERT_EQUAL(om_timer_count(door), original_timers + 1, "Successful emag must schedule its delayed reaction")
	TEST_ASSERT(!door.emagged, "Door declaration is repeatable and must not set the gated emag field")
	TEST_ASSERT(door.density, "Emag must retain density until its delayed opening")
	scheduler_advance(0.7)
	TEST_ASSERT_EQUAL(door.operating, -1, "The emag reaction must disable the door while opening begins")
	scheduler_advance(1.2)
	TEST_ASSERT(!door.density, "The real delayed emag reaction must finish opening the door")
	TEST_ASSERT(!door.opacity, "The opened door must no longer block sight")
	var/open_timers = om_timer_count(door)
	TEST_ASSERT_EQUAL(emag_target(door, 1), 0, "An already open door must consume no emag uses")
	TEST_ASSERT_EQUAL(om_timer_count(door), open_timers, "Open-door refusal must schedule no reaction")
	var/obj/machinery/door/unpowered = allocate(/obj/machinery/door)
	made += unpowered
	unpowered.set_stat(NOPOWER)
	var/unpowered_timers = om_timer_count(unpowered)
	TEST_ASSERT_EQUAL(emag_target(unpowered, 1), 0, "A closed unpowered door must consume no emag uses")
	TEST_ASSERT_EQUAL(om_timer_count(unpowered), unpowered_timers, "Unpowered-door refusal must schedule no reaction")
	TEST_ASSERT(unpowered.density, "Unpowered-door refusal must leave the door closed")
