/// Real cap-projectile retirement remains immediate on the floor and in a sticky inventory hand.
/datum/unit_test/interim_cap_projectile_cleanup/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/list/paths = list(/obj/item/projectile/bullet/pistol/cap, /obj/item/projectile/bullet/cap)
	for(var/path in paths)
		for(var/held in list(FALSE, TRUE))
			var/obj/item/projectile/bullet/projectile = allocate(path, T)
			TEST_ASSERT(!QDELETED(projectile), "the actual cap projectile starts alive")
			if(held)
				TEST_ASSERT(user.put_in_active_hand(projectile), "the actual cap projectile occupies a real hand slot")
				add_trait(projectile, TRAIT_NODROP, "interim_cap_projectile_cleanup")
				TEST_ASSERT(projectile.loc.release_refusal(projectile, user), "the actual sticky cap refuses ordinary removal")
			var/handle = entity_handle(projectile)
			projectile.projectile_step()
			TEST_ASSERT(QDELETED(projectile), "the existing nullspace retirement consumes this spent cap immediately")
			TEST_ASSERT_NULL(resolve_handle(handle), "the actual consumed projectile identity no longer resolves")
			TEST_ASSERT_NULL(user.get_active_hand(), "retirement leaves the actual inventory hand vacant")
			TEST_ASSERT_NULL(locate_within(user, path), "retirement leaves no spent cap inside its holder")
			TEST_ASSERT_NULL(locate_within(T, path), "retirement leaves no spent cap on its original turf")
