/// Actual patient links preserve existing attachment and unconditional living detach behavior.
/datum/unit_test/interim_iv_drip_patient_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/iv_drip/machine = allocate(/obj/machinery/iv_drip, T)
	var/mob/living/simple_mob/unsupported_target = allocate(/mob/living/simple_mob, T)
	TEST_ASSERT(!ishuman(unsupported_target), "the actual unsupported patient fails the original target guard")
	machine.drop_patient_with_actor(actor, unsupported_target)
	TEST_ASSERT_NULL(machine.attached(), "unsupported actual patient cannot acquire the real machine link")
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "a real distant floor exists in the fixture")
	bystander.forceMove(far)
	TEST_ASSERT(!in_range(machine, bystander), "the actual distant actor fails the original attachment range guard")
	machine.drop_patient_with_actor(bystander, patient)
	TEST_ASSERT_NULL(machine.attached(), "an out-of-range actual actor cannot establish a patient link")
	patient.forceMove(far)
	TEST_ASSERT(get_dist(patient, machine) > 1, "the actual distant patient fails the existing distance guard")
	machine.drop_patient_with_actor(actor, patient)
	TEST_ASSERT_NULL(machine.attached(), "an actual distant patient cannot be linked by a nearby actor")
	patient.forceMove(T)
	var/mob/observer/dead/observer = allocate(/mob/observer/dead, T)
	machine.drop_patient_with_actor(observer, patient)
	machine.drop_patient_with_actor(null, patient)
	TEST_ASSERT_NULL(machine.attached(), "nonliving and absent actors cannot establish a real patient link")
	TEST_ASSERT_NULL(machine.drop_patient_with_actor(actor, patient), "actual attachment retains its original implicit null return")
	TEST_ASSERT_EQUAL(machine.attached(), patient, "the actual link names the exact explicitly selected patient")
	machine.appearance_overlays()
	TEST_ASSERT_EQUAL(machine.icon_state, "hooked", "actual patient attachment updates the real hooked appearance")
	machine.drop_patient_with_actor(observer, patient)
	TEST_ASSERT_EQUAL(machine.attached(), patient, "the nonliving actor cannot detach the actual existing patient")
	machine.drop_patient_with_actor(bystander, unsupported_target)
	TEST_ASSERT_NULL(machine.attached(), "an actual distant living actor detaches first under the unchanged existing branch order")
	machine.appearance_overlays()
	TEST_ASSERT_EQUAL(machine.icon_state, "", "actual detach clears the machine's hooked appearance")
	bystander.forceMove(T)
	machine.drop_patient_with_actor(actor, bystander)
	TEST_ASSERT_EQUAL(machine.attached(), bystander, "actual reattachment follows the newly selected patient rather than the old one")
	machine.drop_patient_with_actor(patient, actor)
	TEST_ASSERT_NULL(machine.attached(), "the existing living detach branch clears the exact new patient link")

/// Actual patient links preserve existing attachment and unconditional living detach behavior.
/datum/unit_test/interim_feeder_patient_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/feeder/machine = allocate(/obj/machinery/feeder, T)
	var/mob/living/simple_mob/unsupported_target = allocate(/mob/living/simple_mob, T)
	TEST_ASSERT(!ishuman(unsupported_target), "the actual unsupported patient fails the original target guard")
	machine.drop_patient_with_actor(actor, unsupported_target)
	TEST_ASSERT_NULL(machine.attached(), "unsupported actual patient cannot acquire the real machine link")
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "a real distant floor exists in the fixture")
	bystander.forceMove(far)
	TEST_ASSERT(!in_range(machine, bystander), "the actual distant actor fails the original attachment range guard")
	machine.drop_patient_with_actor(bystander, patient)
	TEST_ASSERT_NULL(machine.attached(), "an out-of-range actual actor cannot establish a patient link")
	patient.forceMove(far)
	TEST_ASSERT(get_dist(patient, machine) > 1, "the actual distant patient fails the existing distance guard")
	machine.drop_patient_with_actor(actor, patient)
	TEST_ASSERT_NULL(machine.attached(), "an actual distant patient cannot be linked by a nearby actor")
	patient.forceMove(T)
	var/mob/observer/dead/observer = allocate(/mob/observer/dead, T)
	machine.drop_patient_with_actor(observer, patient)
	machine.drop_patient_with_actor(null, patient)
	TEST_ASSERT_NULL(machine.attached(), "nonliving and absent actors cannot establish a real patient link")
	TEST_ASSERT_NULL(machine.drop_patient_with_actor(actor, patient), "actual attachment retains its original implicit null return")
	TEST_ASSERT_EQUAL(machine.attached(), patient, "the actual link names the exact explicitly selected patient")
	machine.appearance_overlays()
	TEST_ASSERT_EQUAL(machine.icon_state, "feeding", "actual patient attachment updates the real hooked appearance")
	machine.drop_patient_with_actor(observer, patient)
	TEST_ASSERT_EQUAL(machine.attached(), patient, "the nonliving actor cannot detach the actual existing patient")
	machine.drop_patient_with_actor(bystander, unsupported_target)
	TEST_ASSERT_NULL(machine.attached(), "an actual distant living actor detaches first under the unchanged existing branch order")
	machine.appearance_overlays()
	TEST_ASSERT_EQUAL(machine.icon_state, "", "actual detach clears the machine's hooked appearance")
	bystander.forceMove(T)
	machine.drop_patient_with_actor(actor, bystander)
	TEST_ASSERT_EQUAL(machine.attached(), bystander, "actual reattachment follows the newly selected patient rather than the old one")
	machine.drop_patient_with_actor(patient, actor)
	TEST_ASSERT_NULL(machine.attached(), "the existing living detach branch clears the exact new patient link")
