/datum/unit_test/interim_gargoyle_terminal_cleanup/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/person = allocate(/mob/living/carbon/human, T)
	TEST_ASSERT(!(person.sdisabilities & MUTE), "The actual person starts able to speak")
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	var/obj/structure/gargoyle/statue = allocate(/obj/structure/gargoyle, T, person)
	TEST_ASSERT_EQUAL(statue.WR_gargoyle, person, "The actual constructor records its exact original person")
	TEST_ASSERT_EQUAL(person.loc, statue, "The actual constructor genuinely contains its original person")
	TEST_ASSERT(person.sdisabilities & MUTE, "The actual constructor genuinely mutes its person")
	TEST_ASSERT(!person.canmove, "The actual constructor genuinely prevents movement")
	var/integrity_before = statue.get_integrity()
	statue.gargoyle_step(null)
	TEST_ASSERT(!QDELETED(statue), "The real periodic positive control preserves a living contained person's statue")
	TEST_ASSERT_EQUAL(person.loc, statue, "The positive periodic control preserves original containment")
	TEST_ASSERT_EQUAL(statue.get_integrity(), integrity_before, "The positive periodic control preserves real integrity")
	statue.unpetrify(deal_damage = FALSE, deleting = TRUE)
	TEST_ASSERT(QDELETED(statue), "The real unpetrify terminal path consumes its exact original statue")
	TEST_ASSERT(!QDELETED(person) && person.loc == T, "Real terminal unpetrification preserves and releases its exact original person")
	TEST_ASSERT(!(person.sdisabilities & MUTE), "Real terminal unpetrification restores the person's speech")
	TEST_ASSERT(person.canmove, "Real terminal unpetrification restores the person's movement")
	TEST_ASSERT(!QDELETED(pen) && pen.loc == T, "Real terminal unpetrification preserves the unrelated original floor item")

/datum/unit_test/interim_gargoyle_orphan_cleanup/Run()
	var/turf/T = test_floor()
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	var/obj/structure/gargoyle/statue = allocate(/obj/structure/gargoyle, T)
	TEST_ASSERT(statue && !QDELETED(statue) && statue.loc == T, "The actual no-person constructor creates a real floor statue")
	TEST_ASSERT_NULL(statue.WR_gargoyle, "The actual no-person constructor leaves its real person relation empty")
	TEST_ASSERT_NULL(statue.gargoyle_step(null), "The real orphan periodic endpoint preserves its original null result")
	TEST_ASSERT(QDELETED(statue), "The real orphan periodic endpoint consumes the exact original empty statue")
	TEST_ASSERT(!QDELETED(pen) && pen.loc == T, "Real orphan cleanup preserves the unrelated original floor item")
