/// Destroying a real triggered watch must reveal its surviving owner.
/datum/unit_test/interim_deadringer_deletion/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/deadringer/watch = allocate(/obj/item/deadringer, T)
	TEST_ASSERT(actor.put_in_active_hand(watch), "The actual wearer must hold the watch")
	test_op_handler(watch, "interaction_self", actor, watch)
	TEST_ASSERT(watch.activated, "The actual self interaction must arm the watch")
	actor.injure(INJURY_BLUNT, 10, BP_TORSO, null)
	watch.deadringer_step(null)
	// The real injury reaction creates a decoy body; register it before any assertion stops the test.
	own_turf_contents(T)
	TEST_ASSERT_EQUAL(watch.watchowner(), actor, "The real injury reaction must capture the actual wearer")
	TEST_ASSERT_EQUAL(actor.alpha, 7, "The real injury reaction must actually cloak the wearer")
	TEST_ASSERT_EQUAL(watch.timer, 5, "The actual triggered watch must enter its cooldown")
	TEST_ASSERT(!watch.activated, "The actual injury reaction must disarm the watch")
	TEST_ASSERT(watch.corpse(), "The real human reaction must create a decoy corpse")
	qdel(watch)
	TEST_ASSERT(QDELETED(watch), "The actual watch must be deleted")
	TEST_ASSERT(!QDELETED(actor), "Deleting the watch must preserve its wearer")
	TEST_ASSERT_EQUAL(actor.alpha, 255, "Watch deletion must reveal the surviving wearer before its relation clears")
	TEST_ASSERT_EQUAL(actor.loc, T, "Watch deletion must preserve the wearer's actual floor")
