/// Refused donor release preserves both physical samples and their exact evidence.
/datum/unit_test/interim_forensic_sample_release/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/sample/fibers/recipient = allocate(/obj/item/sample/fibers, T)
	var/obj/item/sample/fibers/donor = allocate(/obj/item/sample/fibers, T)
	recipient.evidence = list("recipient fiber")
	donor.evidence = list("donor fiber")
	var/recipient_name = recipient.name
	var/donor_name = donor.name
	TEST_ASSERT(user.put_in_active_hand(donor), "the original donor is genuinely held")
	add_trait(donor, TRAIT_NODROP, "interim_forensic_sample_release")
	test_click(user, recipient, donor)
	test_time(1 SECOND)
	TEST_ASSERT(!QDELETED(donor), "refused release must not destroy the original donor")
	TEST_ASSERT_EQUAL(user.get_active_hand(), donor, "refusal preserves the exact held donor")
	TEST_ASSERT_EQUAL(donor.loc, user, "refusal preserves donor custody")
	TEST_ASSERT_EQUAL(recipient.loc, T, "refusal preserves the original recipient")
	TEST_ASSERT_EQUAL(recipient.name, recipient_name, "refusal preserves recipient labeling")
	TEST_ASSERT_EQUAL(donor.name, donor_name, "refusal preserves donor labeling")
	TEST_ASSERT_EQUAL(length(recipient.evidence), 1, "refusal cannot copy donor evidence")
	TEST_ASSERT_EQUAL(recipient.evidence[1], "recipient fiber", "original recipient evidence remains exact")
	TEST_ASSERT_EQUAL(length(donor.evidence), 1, "refusal retains the original donor evidence")
	TEST_ASSERT_EQUAL(donor.evidence[1], "donor fiber", "donor evidence remains exact")
	remove_trait(donor, TRAIT_NODROP, "interim_forensic_sample_release")
	test_click(user, recipient, donor)
	test_time(1 SECOND)
	TEST_ASSERT(QDELETED(donor), "successful release and merge consume the actual donor")
	TEST_ASSERT_NULL(user.get_active_hand(), "successful consumption clears the actual hand")
	TEST_ASSERT_EQUAL(recipient.loc, T, "successful merge retains the exact recipient")
	TEST_ASSERT_EQUAL(length(recipient.evidence), 2, "successful merge contains exactly both distinct records")
	TEST_ASSERT("recipient fiber" in recipient.evidence, "successful merge retains original evidence")
	TEST_ASSERT("donor fiber" in recipient.evidence, "successful merge transfers original donor evidence")
	TEST_ASSERT_EQUAL(recipient.name, "fiber bag (combined)", "successful merge retains the original combined label")
