/// The actual processor consumes a mixed conveyor chunk once and credits every member exactly once.
/datum/unit_test/interim_mining_mixed_chunk_accounting/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/input_turf = get_step(T, EAST)
	var/turf/output_turf = get_step(T, NORTH)
	var/area/A = get_area(T)
	set_var(A, nameof(A.requires_power), FALSE)
	var/obj/machinery/mineral/input/input = allocate(/obj/machinery/mineral/input, input_turf)
	var/obj/machinery/mineral/output/output = allocate(/obj/machinery/mineral/output, output_turf)
	var/obj/machinery/mineral/processing_unit/processor = allocate(/obj/machinery/mineral/processing_unit, T)
	TEST_ASSERT_EQUAL(processor.input_marker(), input, "real initialization finds the actual adjacent input plate")
	TEST_ASSERT_EQUAL(processor.output_marker(), output, "real initialization finds the actual adjacent output plate")
	TEST_ASSERT(processor.powered(), "the actual processor has power in its test area")
	TEST_ASSERT_EQUAL(processor.ores_stored[ORE_HEMATITE], 0, "the processor starts without hematite credit")
	TEST_ASSERT_EQUAL(processor.ores_stored[ORE_GOLD], 0, "the processor starts without gold credit")
	TEST_ASSERT_EQUAL(processor.points, 0, "the processor starts without point credit")
	TEST_ASSERT_EQUAL(LAZYACCESS(processor.ores_processing, ORE_HEMATITE), 0, "hematite remains in its real unprocessed mode")
	TEST_ASSERT_EQUAL(LAZYACCESS(processor.ores_processing, ORE_GOLD), 0, "gold remains in its real unprocessed mode")
	var/obj/item/ore_chunk/chunk = allocate(/obj/item/ore_chunk, input_turf)
	chunk.stored_ore = list(ORE_HEMATITE = 3, ORE_GOLD = 5)
	var/points_expected = 3 * processor.ore_values[ORE_HEMATITE] * processor.points_mult + 5 * processor.ore_values[ORE_GOLD] * processor.points_mult
	TEST_ASSERT(points_expected > 0, "the actual mixed ore has positive registered point value")
	test_step_machine(processor)
	TEST_ASSERT(QDELETED(chunk), "the actual mixed chunk is consumed by its input step")
	TEST_ASSERT_EQUAL(processor.ores_stored[ORE_HEMATITE], 3, "the complete first mixture member is credited")
	TEST_ASSERT_EQUAL(processor.ores_stored[ORE_GOLD], 5, "the complete second mixture member survives source consumption and is credited")
	TEST_ASSERT_EQUAL(processor.points, points_expected, "the processor credits the full actual mixed value once")
	test_step_machine(processor)
	TEST_ASSERT_EQUAL(processor.ores_stored[ORE_HEMATITE], 3, "another actual step cannot double-credit spent hematite")
	TEST_ASSERT_EQUAL(processor.ores_stored[ORE_GOLD], 5, "another actual step cannot double-credit spent gold")
	TEST_ASSERT_EQUAL(processor.points, points_expected, "another actual step cannot double-credit spent points")
	TEST_ASSERT_EQUAL(length(contents_of(output_turf, /obj/item/stack/material)), 0, "disabled ore modes emit no sheets")
