/// Removing the empty wrapper retains the real spell parent's constructor gate and argument forwarding.
/datum/unit_test/interim_warp_strike_init/Run()
	test_driver_begin()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	TEST_ASSERT_NULL(actor.get_technomancer_core(), "The real unworn actor starts without a core")
	var/obj/item/spell/warp_strike/coreless = allocate(/obj/item/spell/warp_strike, actor, TRUE)
	TEST_ASSERT(coreless && !QDELETED(coreless), "Explicit coreless construction must produce the actual spell")
	TEST_ASSERT_EQUAL(coreless.owner_ref(), actor, "The actual spell parent records its original living owner")
	TEST_ASSERT_EQUAL(coreless.loc, actor, "The real coreless spell stays inside its original owner")
	TEST_ASSERT_NULL(coreless.core, "Explicit coreless construction must not invent a linked core")
	TEST_ASSERT_EQUAL(coreless.cast_methods, CAST_RANGED, "The real subtype retains its ranged casting method")
	TEST_ASSERT_EQUAL(coreless.aspect, ASPECT_TELE, "The real subtype retains its teleport aspect")
	TEST_ASSERT(!coreless.pay_energy(2000), "A real coreless spell cannot pay the actual warp cost")
	var/list/before = contents_of(actor, /obj/item/spell/warp_strike)
	var/obj/item/spell/warp_strike/refused = allocate(/obj/item/spell/warp_strike, actor)
	TEST_ASSERT(QDELETED(refused), "Ordinary construction without a worn core must refuse through the actual parent")
	TEST_ASSERT_EQUAL(length(contents_of(actor, /obj/item/spell/warp_strike)), length(before), "Actual refusal leaves only the original surviving coreless spell")
	TEST_ASSERT(!QDELETED(coreless) && coreless.owner_ref() == actor, "Refusal preserves the original living spell and owner link")

/// Actual warp casting spends a real worn core's energy and moves its owner beside the real selected opponent.
/datum/unit_test/interim_warp_strike_init/cast/Run()
	test_driver_begin()
	var/turf/start = run_loc_floor_bottom_left
	var/turf/destination = get_step(get_step(start, EAST), EAST)
	TEST_ASSERT(destination && !destination.density, "The real target floor must be two tiles away and passable")
	// Native view requires world illumination: use a real lamp and drain the actual lighting service's pending work.
	var/obj/item/flashlight/lamp/lamp = allocate(/obj/item/flashlight/lamp, destination)
	TEST_ASSERT(lamp.on && lamp.light_range == 5, "The actual desk lamp starts lit with its normal five-tile illumination")
	SSlighting.light_step(0, TRUE)
	TEST_ASSERT_NOTNULL(lamp.light, "The actual lamp constructor creates its real world light source")
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, start)
	var/mob/living/carbon/human/opponent = allocate(/mob/living/carbon/human, destination)
	var/atom/movable/screen/movable/ability_master/master = allocate(/atom/movable/screen/movable/ability_master, actor)
	rel_set(actor, nameof(actor.ability_master), master)
	var/obj/item/technomancer_core/core = allocate(/obj/item/technomancer_core, start)
	TEST_ASSERT(actor.equip_to_slot_if_possible(core, SLOT_ID_BACK), "The actual actor wears its real core")
	TEST_ASSERT_EQUAL(core.energy, 10000, "The original standard core starts with ten thousand energy")
	TEST_ASSERT_EQUAL(core.energy_cost_modifier, 1, "The real standard core does not modify the warp cost")
	var/obj/item/spell/warp_strike/spell = allocate(/obj/item/spell/warp_strike, actor)
	TEST_ASSERT(spell && !QDELETED(spell), "A worn core admits actual ordinary spell construction")
	TEST_ASSERT_EQUAL(spell.core, core, "The parent constructor records the exact worn core")
	TEST_ASSERT_EQUAL(spell.owner_ref(), actor, "The parent constructor records the exact caster")
	TEST_ASSERT(actor.put_in_active_hand(spell), "The caster holds its actual initialized warp spell")
	var/obj/item/pen/pen = allocate(/obj/item/pen, start)
	TEST_ASSERT_EQUAL(pen.force, 0, "The actual ordinary pen provides the harmless off-hand attack")
	TEST_ASSERT(actor.put_in_inactive_hand(pen), "The real pen occupies the caster's inactive hand")
	TEST_ASSERT_EQUAL(opponent.stat, CONSCIOUS, "The actual target starts conscious without artificial status setup")
	TEST_ASSERT(!spell.is_ally(opponent), "The actual unrelated target is not a caster ally")
	TEST_ASSERT(opponent.invisibility <= actor.see_invisible, "The actual target is not hidden from the caster")
	TEST_ASSERT(opponent in view(destination, 5), "The actual target belongs to the real local target view")
	TEST_ASSERT(opponent in viewers(actor), "The actual nearby target belongs to the caster's real visible viewers")
	TEST_ASSERT_EQUAL(spell.targeting_assist(destination, 5), opponent, "The actual selection helper selects the sole real opponent")
	spell.on_ranged_cast(opponent, actor)
	own_turf_contents(get_turf(actor))
	TEST_ASSERT(get_turf(actor) != start, "Actual paid warp casting moves the caster away from its original floor")
	TEST_ASSERT_EQUAL(get_dist(actor, opponent), 1, "Actual casting places the caster on an adjacent nonoccupied target floor")
	TEST_ASSERT_EQUAL(core.energy, 8000, "Actual warp casting spends exactly two thousand core energy")
	TEST_ASSERT_EQUAL(opponent.loc, destination, "The actual off-hand strike preserves the opponent's original floor")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), spell, "Actual casting retains the original held warp spell")
	TEST_ASSERT_EQUAL(actor.get_inactive_hand(), pen, "Actual casting retains the original off-hand pen")
	TEST_ASSERT_EQUAL(spell.core, core, "Actual casting preserves the original core link")
	TEST_ASSERT_EQUAL(spell.owner_ref(), actor, "Actual casting preserves the original living owner link")
