/// Unwrapping the real gift cannot detach its original owned present until the wrapper's actual source releases it.
/datum/unit_test/interim_gift_sticky_unwrapping/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/gift/wrapper = allocate(/obj/item/gift, T)
	var/obj/item/pen/present = allocate(/obj/item/pen, T)
	TEST_ASSERT(move_into(wrapper, nameof(wrapper.gift), present), "the actual wrapper owns its original physical present")
	TEST_ASSERT_EQUAL(present.loc, wrapper, "the actual original present is contained in its wrapper")
	TEST_ASSERT_EQUAL(owner_of(present), wrapper, "the actual wrapper stamps its original present ownership")
	TEST_ASSERT(user.put_in_active_hand(wrapper), "the actor holds the actual wrapped gift")
	TEST_ASSERT_EQUAL(wrapper.gift, present, "picking up the real wrapper preserves its original present field")
	TEST_ASSERT_EQUAL(present.loc, wrapper, "picking up the wrapper preserves original present containment")
	TEST_ASSERT_EQUAL(owner_of(present), wrapper, "picking up the wrapper preserves original present ownership")
	add_trait(wrapper, TRAIT_NODROP, "interim_gift_sticky_wrapper")
	TEST_ASSERT(user.release_refusal(wrapper, user), "the real inventory refuses release of the sticky wrapper")
	perform_op(user, wrapper, "self", wrapper)
	TEST_ASSERT(!QDELETED(wrapper), "refused unwrapping preserves the actual original wrapper")
	TEST_ASSERT_EQUAL(user.get_active_hand(), wrapper, "refused unwrapping preserves the exact wrapper hand slot")
	TEST_ASSERT_EQUAL(wrapper.loc, user, "refused unwrapping preserves actual wrapper containment")
	TEST_ASSERT_EQUAL(wrapper.gift, present, "refused unwrapping preserves the original present field")
	TEST_ASSERT_EQUAL(present.loc, wrapper, "refused unwrapping preserves original present containment")
	TEST_ASSERT_EQUAL(owner_of(present), wrapper, "refused unwrapping preserves original present ownership")
	remove_trait(wrapper, TRAIT_NODROP, "interim_gift_sticky_wrapper")
	perform_op(user, wrapper, "self", wrapper)
	TEST_ASSERT(QDELETED(wrapper), "allowed actual unwrapping consumes the original paper wrapper")
	TEST_ASSERT(!QDELETED(present), "allowed unwrapping preserves the original physical present")
	TEST_ASSERT_EQUAL(user.get_active_hand(), present, "allowed unwrapping returns the original present into the freed hand")
	TEST_ASSERT_EQUAL(present.loc, user, "allowed unwrapping restores the original present to actual inventory")
	TEST_ASSERT_NULL(owner_of(present), "allowed unwrapping clears the original wrapper ownership stamp")
