/// Actual primary and placeholder ear drops forward the same actor through both helpers.
/datum/unit_test/interim_two_ear_drop_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	var/atom/movable/screen/right = hud.r_hand_hud_object
	TEST_ASSERT_NOTNULL(right, "the actual HUD supplies the real right hand target")
	var/obj/item/clothing/ears/earmuffs/primary = allocate(/obj/item/clothing/ears/earmuffs, T)
	TEST_ASSERT(actor.equip_to_slot(primary, SLOT_ID_EAR_L), "real earmuffs equip into their actual primary ear slot")
	var/obj/item/clothing/ears/offear/placeholder = actor.get_equipped_item(SLOT_ID_EAR_R)
	TEST_ASSERT(istype(placeholder), "actual two-ear equip creates its real offear placeholder")
	own(placeholder)
	TEST_ASSERT(HAS_TAG(primary, TAG_WEAR_TWO_EARS), "the actual primary uses the existing two-ear branch")
	TEST_ASSERT_EQUAL(primary.loc, actor, "the actual primary is physically worn by its actor")
	primary.drop_with_actor(actor, right)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), primary, "dropping primary earmuffs puts the exact primary into its actor's hand")
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_EAR_L), "actual primary removal clears the first ear slot")
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_EAR_R), "actual primary removal clears the second ear slot")
	TEST_ASSERT(QDELETED(placeholder), "actual primary removal consumes its real placeholder")
	TEST_ASSERT(actor.unEquip(primary), "actual release makes the primary available for the second equip")
	TEST_ASSERT(actor.equip_to_slot(primary, SLOT_ID_EAR_R), "actual second equip swaps the primary to the opposite ear")
	var/obj/item/clothing/ears/offear/second_placeholder = actor.get_equipped_item(SLOT_ID_EAR_L)
	TEST_ASSERT(istype(second_placeholder), "actual second equip creates a new opposite-ear placeholder")
	own(second_placeholder)
	TEST_ASSERT(second_placeholder != placeholder, "actual second equip does not reuse its consumed placeholder")
	TEST_ASSERT(HAS_TAG(second_placeholder, TAG_WEAR_TWO_EARS), "the actual offear uses the existing forwarding branch")
	second_placeholder.drop_with_actor(actor, right)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), primary, "placeholder forwarding places the exact actual primary in the explicitly supplied actor's hand")
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_EAR_L), "actual placeholder forwarding clears the first ear slot")
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_EAR_R), "actual placeholder forwarding clears the second ear slot")
	TEST_ASSERT(QDELETED(second_placeholder), "actual forwarding consumes its real placeholder")
	TEST_ASSERT_EQUAL(primary.loc, actor, "actual forwarding retains physical primary ownership")
