/// The actual airlock emag capability spends only after its mechanism accepts and opens through the real delayed door reaction without cutting wires or changing access lists.
/datum/unit_test/om/interim_airlock_emag_capability/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock, T)
	var/obj/item/card/emag/card = allocate(/obj/item/card/emag, T)
	made += list(user, door, card)
	door.autoclose = FALSE
	door.req_access = list(ACCESS_SECURITY)
	var/list/access_before = door.req_access
	card.uses = 3
	TEST_ASSERT(user.put_in_active_hand(card), "the actual airlock actor holds the real charged emag")
	var/datum/interaction/emag_entry
	for(var/datum/interaction/candidate as anything in interaction_candidates(door))
		if(candidate.id == "emag")
			emag_entry = candidate
			break
	TEST_ASSERT_NOTNULL(emag_entry, "the actual airlock exposes its capability's declared emag interaction")
	TEST_ASSERT(!door.wire_cut(WIRE_OPEN_DOOR) && !door.wire_cut(WIRE_IDSCAN), "the actual airlock starts with control and ID wires intact")
	door.set_stat(NOPOWER)
	var/timers_before = om_timer_count(door)
	emag_entry.perform(user, door, card)
	TEST_ASSERT_EQUAL(card.uses, 3, "the actual unpowered mechanism refusal spends no card use")
	TEST_ASSERT(!is_emagged(door), "the actual unpowered mechanism refusal sets no emag state")
	TEST_ASSERT_EQUAL(om_timer_count(door), timers_before, "actual unpowered refusal schedules no reaction")
	TEST_ASSERT(door.density && !door.operating, "actual unpowered refusal leaves the closed airlock idle")
	door.set_stat(0)
	TEST_ASSERT(door.arePowerSystemsOn(), "the actual powered fixture has an available power system")
	TEST_ASSERT(emag_entry.perform(user, door, card), "the actual powered airlock runs its declared capability emag")
	TEST_ASSERT_EQUAL(card.uses, 2, "the actual successful capability spends exactly one card use")
	TEST_ASSERT(is_emagged(door), "the actual successful capability records its emag state")
	TEST_ASSERT_EQUAL(om_timer_count(door), timers_before + 1, "the actual successful effect schedules its delayed door reaction")
	TEST_ASSERT(door.density, "the actual accepted emag does not open before its reaction delay")
	scheduler_advance((3 SECONDS) / (1 SECOND))
	TEST_ASSERT(!door.density && !door.opacity, "the actual delayed airlock reaction finishes opening and clears opacity")
	TEST_ASSERT(!door.operating, "the actual opening animation finishes idle")
	TEST_ASSERT_EQUAL(door.req_access, access_before, "actual airlock emag preserves the exact configured access list")
	TEST_ASSERT(ACCESS_SECURITY in door.req_access, "actual airlock emag retains the security-access requirement")
	TEST_ASSERT(!door.wire_cut(WIRE_OPEN_DOOR) && !door.wire_cut(WIRE_IDSCAN), "actual airlock emag does not cut control or ID wires")
	var/open_timers = om_timer_count(door)
	emag_entry.perform(user, door, card)
	TEST_ASSERT_EQUAL(card.uses, 2, "the actual already-open mechanism refusal spends no additional card use")
	TEST_ASSERT_EQUAL(om_timer_count(door), open_timers, "actual already-open refusal schedules no additional reaction")
	TEST_ASSERT(!door.density, "the actual already-open refusal preserves the open passage")
