/// Real item self-entry, inherited collar tag request, then craftable label request.
/datum/unit_test/interim_craftable_collar_label_request/Run()
	test_driver_begin()
	check_label_request()
	test_driver_end()

/datum/unit_test/interim_craftable_collar_label_request/proc/check_label_request()
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, surface)
	var/obj/item/clothing/accessory/collar/craftable/collar = allocate(/obj/item/clothing/accessory/collar/craftable, surface)
	TEST_ASSERT(user.put_in_active_hand(collar), "actual actor holds the exact handmade collar")
	TEST_ASSERT(!collar.writtenon, "actual new collar starts with an unengraved tag")
	TEST_ASSERT_NULL(collar.given_name, "actual new collar has no handmade label")
	test_click(user, collar, collar)
	var/datum/prompt/text/collar_tag/tag = SSrequests.open_for(user)
	TEST_ASSERT_NOTNULL(tag, "actual self entry first opens the inherited tag request")
	TEST_ASSERT_EQUAL(tag.type, /datum/prompt/text/collar_tag, "initial parent handling opens the real tag kind")
	test_answer(user, "Original tag")
	TEST_ASSERT(collar.writtenon, "actual inherited tag answer engraves the original collar")
	TEST_ASSERT_EQUAL(collar.name, "handmade collar (Original tag)", "actual tag handler updates the collar's real name")
	test_click(user, collar, collar)
	var/datum/prompt/text/collar_tag/craftable_label/label = SSrequests.open_for(user)
	TEST_ASSERT(istype(label), "actual subsequent self entry reaches the handmade label request")
	var/datum/pending_op/label_op = label.owner
	TEST_ASSERT(istype(label_op) && label_op.oplan?.key == "craftable_collar_self", "the collar's own label op owns the label request (the engine's pending op, not the collar)")
	TEST_ASSERT_EQUAL(label.answerer, user, "the label keeps the original real actor")
	TEST_ASSERT_EQUAL(label.captured_item, collar, "the inherited relation preserves the original self-entry held argument")
	test_answer(user, "Handmade label")
	TEST_ASSERT_EQUAL(collar.given_name, "Handmade label", "the real accepted continuation writes the handmade label")
	TEST_ASSERT_EQUAL(collar.name, "handmade collar (Original tag)", "parent-first replay preserves the existing engraved tag")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "accepted real label retires its question")
	test_click(user, collar, collar)
	var/datum/prompt/text/collar_tag/craftable_label/cancelled = SSrequests.open_for(user)
	TEST_ASSERT(istype(cancelled), "actual retry opens another real label request")
	test_answer(user, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(cancelled.outcome, REQ_CANCELLED, "actual cancellation records the cancellation outcome")
	TEST_ASSERT_EQUAL(collar.given_name, "Handmade label", "cancellation preserves the actual earlier handmade label")
	TEST_ASSERT_EQUAL(collar.name, "handmade collar (Original tag)", "cancellation preserves the actual parent tag state")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "cancelled real label retires its question")
