/// A refused actual sheet must not change ordered page records or current-page position.
/datum/unit_test/interim_paper_bundle_sticky_sheet/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/paper_bundle/bundle = allocate(/obj/item/paper_bundle, T)
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	TEST_ASSERT_EQUAL(length(bundle.pages), 0, "actual initialized bundle starts without physical pages")
	var/original_page = bundle.page
	TEST_ASSERT(user.put_in_active_hand(paper), "the actor holds the exact original sheet")
	add_trait(paper, TRAIT_NODROP, "interim_bundle_sheet")
	TEST_ASSERT(user.release_refusal(paper, user), "actual inventory refuses sticky sheet")
	bundle.insert_sheet_at(user, 1, paper)
	TEST_ASSERT_EQUAL(length(bundle.pages), 0, "refused insertion adds no page record")
	TEST_ASSERT_EQUAL(bundle.page, original_page, "refused insertion preserves current page position")
	TEST_ASSERT_EQUAL(user.get_active_hand(), paper, "refused insertion preserves original hand")
	TEST_ASSERT_EQUAL(paper.loc, user, "refused insertion preserves inventory containment")
	remove_trait(paper, TRAIT_NODROP, "interim_bundle_sheet")
	bundle.insert_sheet_at(user, 1, paper)
	TEST_ASSERT_EQUAL(length(bundle.pages), 1, "allowed insertion adds exactly one page")
	TEST_ASSERT_EQUAL(bundle.pages[1], paper, "allowed insertion records the exact original sheet")
	TEST_ASSERT_EQUAL(paper.loc, bundle, "allowed insertion physically contains original sheet")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears actual source hand")
	TEST_ASSERT_NULL(owner_of(paper), "ordered pages preserve existing relation-only policy")
	TEST_ASSERT_EQUAL(bundle.page, original_page + 1, "inserting before the viewed position preserves actual page-offset behavior")
