/// Actual buckle refusal and collapse preserve the roller-bed construction roundtrip.
/datum/unit_test/interim_roller_bed_collapse_actor/Run()
	test_driver_begin()
	var/turf/start = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, start)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, start)
	var/obj/structure/bed/roller/bed = allocate(/obj/structure/bed/roller, start)
	var/obj/item/unrelated = allocate(/obj/item, start)
	TEST_ASSERT_NULL(locate(/obj/item/roller) in start, "the actual fixture begins without a folded roller product")
	bed.collapse_with_actor(actor, bystander)
	TEST_ASSERT(!after_pending(bed, "lifecycle_lifetime_timer"), "a distinct target never schedules actual bed expiry")
	TEST_ASSERT_NULL(locate(/obj/item/roller) in start, "distinct-target refusal creates no folded product")
	var/turf/far = get_step(get_step(get_step(start, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "a real distant floor exists")
	bystander.forceMove(far)
	TEST_ASSERT(!in_range(bed, bystander), "the actual second actor fails the source range guard")
	bed.collapse_with_actor(bystander, bystander)
	TEST_ASSERT_NULL(locate(/obj/item/roller) in start, "distant actor refusal creates no product")
	TEST_ASSERT(bed.buckle_mob(actor, forced = TRUE), "the real roller bed restrains its actual occupant")
	TEST_ASSERT(bed.has_buckled_mobs(), "the real buckle state activates the original collapse guard")
	TEST_ASSERT_EQUAL(bed.collapse_with_actor(actor, actor), 0, "actual occupied-bed refusal retains its original return")
	TEST_ASSERT_NULL(locate(/obj/item/roller) in start, "occupied bed produces no folded duplicate")
	TEST_ASSERT(!after_pending(bed, "lifecycle_lifetime_timer"), "occupied bed never schedules expiry")
	bed.unbuckle_mob(actor)
	TEST_ASSERT(!bed.has_buckled_mobs(), "actual unbuckling permits original collapse behavior")
	TEST_ASSERT_NULL(bed.collapse_with_actor(actor, actor), "valid collapse preserves original implicit null return")
	var/obj/item/roller/folded = locate(/obj/item/roller) in start
	TEST_ASSERT_NOTNULL(folded, "actual collapse creates its concrete folded roller product")
	own(folded)
	TEST_ASSERT_EQUAL(folded.type, bed.rollertype, "the actual folded product has the exact configured type")
	TEST_ASSERT_EQUAL(folded.loc, start, "the actual folded product remains at the original bed turf")
	TEST_ASSERT(after_pending(bed, "lifecycle_lifetime_timer"), "actual collapse schedules the original zero-delay expiry")
	test_time(1 SECOND)
	TEST_ASSERT(QDELETED(bed), "the real original bed expires after collapse")
	TEST_ASSERT(actor.put_in_active_hand(folded), "the actual collapsed product can be held for deployment")
	p2_seat_use_in_hand(actor, folded)
	test_time(1 SECOND)
	var/obj/structure/bed/roller/rebuilt = locate(/obj/structure/bed/roller) in start
	TEST_ASSERT_NOTNULL(rebuilt, "actual construction creates a replacement roller bed")
	own(rebuilt)
	TEST_ASSERT(rebuilt != bed, "construction creates a new real bed rather than reviving the expired source")
	TEST_ASSERT_EQUAL(rebuilt.type, /obj/structure/bed/roller, "the actual construction roundtrip retains exact bed type")
	TEST_ASSERT(QDELETED(folded), "actual deployment consumes the concrete folded product")
	TEST_ASSERT_EQUAL(unrelated.loc, start, "the full actual roundtrip leaves unrelated items untouched")
