/// The actual airlock emag capability spends only after its mechanism accepts and opens through the real delayed door reaction without cutting wires or changing access lists.
/datum/unit_test/om/interim_airlock_emag_capability
	parent_type = /datum/unit_test/dq_p2_door

/datum/unit_test/om/interim_airlock_emag_capability/run_gate()
	var/turf/T = tile(2, 2)
	var/mob/living/carbon/human/user = make_person(null, tile(3, 2))
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock, T)
	var/obj/item/card/emag/card = allocate(/obj/item/card/emag, T)
	door.set_autoclose(FALSE)
	door.req_access = list(ACCESS_SECURITY)
	var/list/access_before = door.req_access
	card.uses = 3
	TEST_ASSERT(user.put_in_active_hand(card), "the actual airlock actor holds the real charged emag")
	TEST_ASSERT(!wire_is_cut(door, WIRE_OPEN_DOOR) && !wire_is_cut(door, WIRE_IDSCAN), "the actual airlock starts with control and ID wires intact")
	p2_door_set_power(door, FALSE)
	var/timers_before = time_scheduler().timer_count(door)
	p2_door_click(user, door, card)
	TEST_ASSERT_EQUAL(card.uses, 3, "the actual unpowered mechanism refusal spends no card use")
	TEST_ASSERT(!is_emagged(door), "the actual unpowered mechanism refusal sets no emag state")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), timers_before, "actual unpowered refusal schedules no reaction")
	TEST_ASSERT(door.density && !door.operating, "actual unpowered refusal leaves the closed airlock idle")
	p2_door_set_power(door, TRUE)
	TEST_ASSERT(door.power_systems_on(), "the actual powered fixture has an available power system")
	p2_door_click(user, door, card)
	TEST_ASSERT_EQUAL(card.uses, 2, "the actual successful capability spends exactly one card use")
	TEST_ASSERT(is_emagged(door), "the actual successful capability records its emag state")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), timers_before + 1, "the actual successful effect schedules its delayed door reaction")
	TEST_ASSERT(door.density, "the actual accepted emag does not open before its reaction delay")
	test_time(3 SECONDS)
	TEST_ASSERT(!door.density && !door.opacity, "the actual delayed airlock reaction finishes opening and clears opacity")
	TEST_ASSERT(!door.operating, "the actual opening animation finishes idle")
	TEST_ASSERT_EQUAL(door.req_access, access_before, "actual airlock emag preserves the exact configured access list")
	TEST_ASSERT(ACCESS_SECURITY in door.req_access, "actual airlock emag retains the security-access requirement")
	TEST_ASSERT(!wire_is_cut(door, WIRE_OPEN_DOOR) && !wire_is_cut(door, WIRE_IDSCAN), "actual airlock emag does not cut control or ID wires")
	var/open_timers = time_scheduler().timer_count(door)
	p2_door_click(user, door, card)
	TEST_ASSERT_EQUAL(card.uses, 2, "the actual already-open mechanism refusal spends no additional card use")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), open_timers, "actual already-open refusal schedules no additional reaction")
	TEST_ASSERT(!door.density, "the actual already-open refusal preserves the open passage")
