/datum/unit_test/interim_pet_cube_expansion_cleanup/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/box/monkeycubes/pets/box = allocate(/obj/item/storage/box/monkeycubes/pets, T)
	var/obj/item/reagent_containers/food/snacks/monkeycube/pet/wrapped/cube = locate_within(box, /obj/item/reagent_containers/food/snacks/monkeycube/pet/wrapped)
	TEST_ASSERT_NOTNULL(cube, "The actual pet box constructor creates its real original wrapped pet cube")
	own(cube)
	TEST_ASSERT_EQUAL(cube.pet_path, /mob/living/simple_mob/animal/passive/dog/corgi/Ian, "The actual standard pet box configures the canonical Ian product")
	TEST_ASSERT(cube.wrapped, "The actual constructor creates a genuinely wrapped original cube")
	TEST_ASSERT(box.release_to(cube, T, null, actor), "The actual original box releases its real cube onto the floor")
	TEST_ASSERT(actor.put_in_active_hand(cube), "The actual actor holds the exact original pet cube")
	TEST_ASSERT(cube.monkeycube_self(actor, cube, null), "The actual self-use unwraps the original pet cube")
	TEST_ASSERT(!cube.wrapped, "Actual self-use leaves the original cube genuinely unwrapped")
	var/list/before = turf_contents_of_type(T, /mob/living/simple_mob/animal/passive/dog/corgi/Ian)
	add_trait(cube, TRAIT_NODROP, "interim_pet_cube_expansion_cleanup")
	TEST_ASSERT(cube.loc.release_refusal(cube, actor), "The actual sticky held original cube genuinely refuses release")
	TEST_ASSERT_EQUAL(cube.Expand(), 0, "Actual expansion refuses a sticky held source before creating a pet")
	TEST_ASSERT(!QDELETED(cube) && cube.loc == actor, "Actual sticky refusal preserves the exact original held cube")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), cube, "Actual sticky refusal preserves the original occupied hand")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(T, /mob/living/simple_mob/animal/passive/dog/corgi/Ian) - before), 0, "Actual sticky refusal creates no free Ian pet")
	remove_trait(cube, TRAIT_NODROP, "interim_pet_cube_expansion_cleanup")
	TEST_ASSERT(actor.drop_from_inventory(cube, T), "The actual actor releases the original cube onto its original floor")
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(actor.put_in_active_hand(pen), "The actual actor holds its unrelated original pen during floor expansion")
	TEST_ASSERT_EQUAL(cube.Expand(), 1, "Actual floor expansion retains its original success result")
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(cube), "Actual expansion consumes the exact original pet cube")
	var/list/products = turf_contents_of_type(T, /mob/living/simple_mob/animal/passive/dog/corgi/Ian) - before
	TEST_ASSERT_EQUAL(length(products), 1, "Actual expansion creates exactly one canonical Ian pet")
	var/mob/living/simple_mob/animal/passive/dog/corgi/Ian/pet = products[1]
	TEST_ASSERT_EQUAL(pet.type, /mob/living/simple_mob/animal/passive/dog/corgi/Ian, "The actual created pet retains its exact canonical type")
	TEST_ASSERT(!QDELETED(pet) && pet.loc == T, "The actual original pet survives source consumption on the original floor")
	TEST_ASSERT(!QDELETED(box) && box.loc == T, "Actual expansion preserves the original source box")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), pen, "Actual expansion preserves the unrelated original held pen")
	TEST_ASSERT(!QDELETED(actor) && actor.loc == T, "Actual expansion preserves the original actor and floor")
