/// The real first equip has no prior wearer; a later actual drop still removes the real ability button.
/datum/unit_test/interim_technomancer_core_first_equip/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/atom/movable/screen/movable/ability_master/master = allocate(/atom/movable/screen/movable/ability_master, actor)
	rel_set(actor, nameof(actor.ability_master), master)
	TEST_ASSERT_EQUAL(master.my_mob(), actor, "The actual ability screen records its original owning actor")
	var/obj/item/technomancer_core/core = allocate(/obj/item/technomancer_core, T)
	TEST_ASSERT_NULL(core.wearer, "The actual floor core has no prior wearer")
	core.energy = 0
	test_time(5 SECONDS)
	TEST_ASSERT_EQUAL(core.energy, 0, "The actual unworn core runs no upkeep")
	TEST_ASSERT(actor.equip_to_slot_if_possible(core, SLOT_ID_BACK), "The actual first equip must complete through the public inventory API")
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_BACK), core, "The real first equip inserts the exact core in the back slot")
	TEST_ASSERT_EQUAL(core.wearer, actor, "The actual equipped lifecycle records the real wearer")
	test_time(5 SECONDS)
	TEST_ASSERT(core.energy > 0, "The actual equipped lifecycle starts normal core upkeep")
	var/obj/spellbutton/button = allocate(/obj/spellbutton, core, /obj/item/spell/warp_strike, "Test warp", "tech_warpstrike")
	master.add_technomancer_ability(button, button.ability_icon_state)
	var/atom/movable/screen/ability/obj_based/technomancer/ability = master.get_ability_by_instance(button)
	TEST_ASSERT(ability && !QDELETED(ability), "The actual ability master constructs a real technomancer ability")
	TEST_ASSERT_EQUAL(ability.object(), button, "The real ability points at the original spell button")
	TEST_ASSERT(actor.unEquip(core, FALSE, T), "The worn real core drops through the ordinary public inventory API")
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_BACK), "Actual dropping empties the original back slot")
	TEST_ASSERT_EQUAL(core.loc, T, "The exact surviving core drops onto the original floor")
	TEST_ASSERT_NULL(core.wearer, "Actual dropping clears the real wearer relation")
	var/energy_when_dropped = core.energy
	test_time(5 SECONDS)
	TEST_ASSERT_EQUAL(core.energy, energy_when_dropped, "Actual dropping stops the real core upkeep")
	TEST_ASSERT(QDELETED(ability), "Actual worn cleanup deletes the original technomancer ability")
	TEST_ASSERT_NULL(master.get_ability_by_instance(button), "Actual worn cleanup removes the ability from its original master")
	TEST_ASSERT(!QDELETED(button) && button.loc == core, "Dropping preserves the original spell button inside the core")
	TEST_ASSERT(core.canremove, "Actual dropping retains the original removal-unlock effect")
