/datum/unit_test/dq_eg2/interim_domination_native_cancel
/datum/unit_test/dq_eg2/interim_domination_native_cancel/run_gate()
	var/mob/living/carbon/human/pred = person()
	var/mob/living/carbon/human/prey = person()
	pred.allow_mind_transfer = TRUE
	prey.forceMove(pred)
	TEST_ASSERT_EQUAL(prey.loc, pred, "the real public entry sees its actor physically inside a living predator")
	TEST_ASSERT(!pred.prey_controlled && !prey.prey_controlled, "both real participants start without transferred control")
	TEST_ASSERT_NULL(SSrequests.open_for(prey), "the actor starts without an unrelated question")
	prey.dominate_predator()
	var/datum/prompt/choice/control_transfer_review/asked = SSrequests.open_for(prey)
	TEST_ASSERT(istype(asked), "the actual Dominate Predator entry opens the native initial consent")
	TEST_ASSERT_EQUAL(asked.title, "Take Over Predator", "the real opening retains its original title")
	TEST_ASSERT_EQUAL(length(asked.choices), 2, "the actual consent contains exactly its two original options")
	TEST_ASSERT_EQUAL(asked.choices[1], "No", "the native question preserves original no-first ordering")
	TEST_ASSERT_EQUAL(asked.choices[2], "Yes", "the native question preserves its real affirmative option")
	// framework_gaps E2: zero selects the engine default; REQUEST_NO_TIMEOUT is the explicit unbounded opt-out.
	TEST_ASSERT_EQUAL(asked.timeout, REQUEST_DEFAULT_TIMEOUT, "native consent uses the documented bounded request default")
	var/datum/control_transfer_review/dominate_predator/review = asked.owner
	TEST_ASSERT(istype(review), "the actual entry supplies its production workflow context")
	TEST_ASSERT_EQUAL(review.actor, prey, "the workflow captures the real actor")
	TEST_ASSERT_EQUAL(review.pred, pred, "the workflow captures the actual containing predator")
	test_answer(prey, "No")
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(prey), "an actual No ends the actor consent without another question")
	TEST_ASSERT_NULL(SSrequests.open_for(pred), "an actual No never asks the partner for control")
	TEST_ASSERT(QDELETED(review), "decline retires the actual waiting workflow")
	TEST_ASSERT(!pred.prey_controlled && !prey.prey_controlled, "declining leaves both actual control states unchanged")
	prey.dominate_predator()
	asked = SSrequests.open_for(prey)
	TEST_ASSERT(istype(asked), "the same real entry can open another independent consent")
	review = asked.owner
	test_answer(prey, null, REQ_CANCELLED)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(prey), "closing the actual consent ends the request")
	TEST_ASSERT_NULL(SSrequests.open_for(pred), "closing never opens partner consent")
	TEST_ASSERT(QDELETED(review), "closing retires its actual workflow context")
	TEST_ASSERT_EQUAL(prey.loc, pred, "both refusal paths preserve physical containment")
	TEST_ASSERT(!pred.prey_controlled && !prey.prey_controlled, "closing leaves both real control states unchanged")
