/// Variant tables drive real grants, and removing one source preserves other mobs.
/datum/unit_test/interim_shadekin_variant_grants/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/list/variants = list(/datum/shadekin, /datum/shadekin/phase_only, /datum/shadekin/full, /datum/shadekin/full/rakshasa)
	for(var/path in variants)
		var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human, T)
		var/mob/living/carbon/human/other = allocate(/mob/living/carbon/human, T)
		H.add_shadekin(path)
		other.add_shadekin(path)
		TEST_ASSERT(granted(H, shadekin_phase()), "each real variant grants phase shift")
		TEST_ASSERT_EQUAL(granted(H, shadekin_utility()), path != /datum/shadekin/phase_only, "only phase-only omits regeneration")
		TEST_ASSERT_EQUAL(granted(H, shadekin_dark()), istype(H.shadekin, /datum/shadekin/full), "only full variants grant respite")
		TEST_ASSERT_EQUAL(granted(H, shadekin_utility()), path != /datum/shadekin/phase_only, "only phase-only omits shade creation")
		TEST_ASSERT_EQUAL(granted(H, shadekin_dark()), istype(H.shadekin, /datum/shadekin/full), "only full variants grant tunneling")
		TEST_ASSERT_EQUAL(granted(H, shadekin_dark()), istype(H.shadekin, /datum/shadekin/full), "only full variants grant dark maw")
		TEST_ASSERT_EQUAL(granted(H, shadekin_dark()), istype(H.shadekin, /datum/shadekin/full), "full and rakshasa inherit the exact clear-maws grant")
		H.remove_shadekin()
		TEST_ASSERT_NULL(H.shadekin, "removal deletes the owned state")
		TEST_ASSERT(!granted(H, shadekin_phase()), "removal revokes actual phase shift")
		TEST_ASSERT(!granted(H, shadekin_utility()), "removal leaves no regeneration grant")
		TEST_ASSERT(!granted(H, shadekin_dark()), "removal leaves no respite grant")
		TEST_ASSERT(!granted(H, shadekin_utility()), "removal leaves no shade-creation grant")
		TEST_ASSERT(!granted(H, shadekin_dark()), "removal leaves no tunneling grant")
		TEST_ASSERT(!granted(H, shadekin_dark()), "removal leaves no dark-maw grant")
		TEST_ASSERT(!granted(H, shadekin_dark()), "removal leaves no clear-maws grant")
		TEST_ASSERT(granted(other, shadekin_phase()), "removing one source never affects the other mob")

		var/mob/living/carbon/human/later = allocate(/mob/living/carbon/human, T)
		later.add_shadekin(path)
		TEST_ASSERT(granted(later, shadekin_phase()), "later instances retain the shared variant table after source removal")
