/// Installing a real kinetic-accelerator modkit respects its actual source release and refunds the exact original mod capacity on crowbar removal.
/datum/unit_test/interim_accelerator_sticky_modkit/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/gun/energy/kinetic_accelerator/accelerator = allocate(/obj/item/gun/energy/kinetic_accelerator, T)
	var/obj/item/borg/upgrade/modkit/range/modkit = allocate(/obj/item/borg/upgrade/modkit/range, T)
	var/obj/item/tool/crowbar/crowbar = allocate(/obj/item/tool/crowbar, T)
	TEST_ASSERT(user.put_in_inactive_hand(accelerator), "the actor holds the actual accelerator in its inactive hand")
	TEST_ASSERT(user.put_in_active_hand(modkit), "the actor holds the actual supported range modkit")
	var/capacity_before = accelerator.get_remaining_mod_capacity()
	var/charge_before = accelerator.power_supply.charge
	TEST_ASSERT(capacity_before >= modkit.cost && modkit.cost > 0, "the actual accelerator has room for the positive-cost original modkit")
	TEST_ASSERT_EQUAL(length(accelerator.get_modkits()), 0, "the actual accelerator starts without installed modkits")
	add_trait(modkit, TRAIT_NODROP, "interim_accelerator_sticky_modkit")
	TEST_ASSERT(user.release_refusal(modkit, user), "the actual inventory refuses release of the sticky modkit")
	test_op_handler(accelerator, "gun_item", user, modkit)
	TEST_ASSERT_EQUAL(length(accelerator.get_modkits()), 0, "refused release records no accelerator modkit")
	TEST_ASSERT_EQUAL(accelerator.get_remaining_mod_capacity(), capacity_before, "refused release spends no mod capacity")
	TEST_ASSERT_EQUAL(modkit.loc, user, "refused release preserves actual modkit inventory containment")
	TEST_ASSERT_EQUAL(user.get_active_hand(), modkit, "refused release preserves the original modkit hand")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), accelerator, "refused release preserves the actual held accelerator")
	remove_trait(modkit, TRAIT_NODROP, "interim_accelerator_sticky_modkit")
	test_op_handler(accelerator, "gun_item", user, modkit)
	TEST_ASSERT_EQUAL(length(accelerator.get_modkits()), 1, "allowed insertion records exactly one actual modkit")
	TEST_ASSERT(modkit in accelerator.get_modkits(), "allowed insertion records the original modkit identity")
	TEST_ASSERT_EQUAL(modkit.loc, accelerator, "allowed insertion physically contains the original modkit")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears the original source hand")
	TEST_ASSERT_EQUAL(accelerator.get_remaining_mod_capacity(), capacity_before - modkit.cost, "allowed insertion spends exactly the original modkit's actual capacity cost")
	TEST_ASSERT(user.put_in_active_hand(crowbar), "the actor holds the real modification-removal tool")
	accelerator.interaction_tool_act(user, crowbar, TOOL_CROWBAR)
	TEST_ASSERT_EQUAL(length(accelerator.get_modkits()), 0, "the actual crowbar action removes the original modkit relation")
	TEST_ASSERT_EQUAL(accelerator.get_remaining_mod_capacity(), capacity_before, "actual removal refunds the full original capacity cost")
	TEST_ASSERT_EQUAL(modkit.loc, T, "actual removal returns the original modkit to the floor")
	TEST_ASSERT_EQUAL(user.get_active_hand(), crowbar, "actual removal preserves the real tool hand")
	TEST_ASSERT_EQUAL(accelerator.power_supply.charge, charge_before, "the actual install and removal round trip spends no weapon charge")
	qdel(accelerator)
	TEST_ASSERT(!QDELETED(modkit), "empty accelerator teardown preserves its returned original modkit")
