/// Clipping an original paper must respect actual inventory release and preserve its record.
/datum/unit_test/interim_clipboard_sticky_paper/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/clipboard/board = allocate(/obj/item/clipboard, T)
	user.put_in_inactive_hand(board) // the window works in the hand that holds it
	user.put_in_inactive_hand(board) // the window works in the hand that holds it
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	paper.info = "Original checked clipboard contents"
	TEST_ASSERT_NULL(board.toppaper(), "the actual clipboard initializes without a top paper")
	TEST_ASSERT(user.put_in_active_hand(paper), "the actor holds the exact original paper")
	add_trait(paper, TRAIT_NODROP, "interim_clipboard_sticky_paper")
	TEST_ASSERT(user.release_refusal(paper, user), "actual inventory refuses the sticky paper")
	test_op_handler(board, "interaction_item", user, paper)
	TEST_ASSERT_EQUAL(user.get_active_hand(), paper, "refused clipping preserves original hand")
	TEST_ASSERT_EQUAL(paper.loc, user, "refused clipping preserves inventory containment")
	TEST_ASSERT_NULL(board.toppaper(), "refused clipping records no top paper")
	TEST_ASSERT_EQUAL(contents_count(board), 0, "refused clipping physically contains no paper")
	remove_trait(paper, TRAIT_NODROP, "interim_clipboard_sticky_paper")
	test_op_handler(board, "interaction_item", user, paper)
	TEST_ASSERT_EQUAL(board.toppaper(), paper, "allowed clipping records the exact original top paper")
	TEST_ASSERT_EQUAL(paper.loc, board, "allowed clipping physically contains the original paper")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed clipping clears the actual source hand")
	TEST_ASSERT_NULL(owner_of(paper), "clipping preserves the original relation-only policy")
	op_ui_act(user, board, "remove", list("ref" = paper))
	TEST_ASSERT_EQUAL(user.get_active_hand(), paper, "public UI removal returns the exact original paper")
	TEST_ASSERT_EQUAL(paper.loc, user, "public UI removal restores inventory containment")
	TEST_ASSERT_NULL(board.toppaper(), "public UI removal clears the top-paper relation")
	TEST_ASSERT_EQUAL(paper.info, "Original checked clipboard contents", "actual insertion and removal preserve original written contents")
	qdel(board)
	TEST_ASSERT(!QDELETED(paper), "returned original paper survives empty clipboard teardown")
