/// Storage must respect actual inventory release refusal before vacating either hand or changing its declared slot.
/datum/unit_test/interim_storage_sticky_inventory_roundtrip/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/box/box = allocate(/obj/item/storage/box, T)
	var/obj/item/pen/candidate = allocate(/obj/item/pen, T)
	var/obj/item/pen/unrelated = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_active_hand(unrelated), "the unrelated real pen occupies the active hand")
	TEST_ASSERT(user.put_in_inactive_hand(candidate), "the actual storage candidate occupies the inactive hand")
	var/used_before = box.slot_used(CONTAINER_SLOT_STORAGE)
	var/count_before = length(box.slot_contents(CONTAINER_SLOT_STORAGE))
	add_trait(candidate, TRAIT_NODROP, "interim_storage_sticky_inventory")
	TEST_ASSERT(user.release_refusal(candidate, user), "the actual inventory refuses release of the sticky candidate")
	TEST_ASSERT_NOTNULL(box.insert_refusal(candidate, user), "the actual storage requirement rejects that release refusal")
	TEST_ASSERT(!box.insert_item(candidate, user), "the actual insertion path refuses the sticky candidate")
	TEST_ASSERT_EQUAL(candidate.loc, user, "refused insertion leaves the candidate on its actor")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), candidate, "refused insertion preserves the candidate's exact hand")
	TEST_ASSERT_EQUAL(user.get_active_hand(), unrelated, "refused insertion preserves the unrelated active item")
	TEST_ASSERT_EQUAL(box.slot_used(CONTAINER_SLOT_STORAGE), used_before, "refused insertion preserves storage capacity accounting")
	TEST_ASSERT_EQUAL(length(box.slot_contents(CONTAINER_SLOT_STORAGE)), count_before, "refused insertion preserves storage slot count")
	TEST_ASSERT(!(candidate in box.slot_contents(CONTAINER_SLOT_STORAGE)), "refused insertion registers no candidate in storage")
	remove_trait(candidate, TRAIT_NODROP, "interim_storage_sticky_inventory")
	TEST_ASSERT_NULL(box.insert_refusal(candidate, user), "removing the trait permits the same actual candidate")
	TEST_ASSERT(box.insert_item(candidate, user), "the actual released candidate can be inserted")
	TEST_ASSERT_EQUAL(candidate.loc, box, "successful insertion places the actual candidate in storage")
	TEST_ASSERT_NULL(user.get_inactive_hand(), "successful insertion vacates the original inactive hand")
	TEST_ASSERT_EQUAL(user.get_active_hand(), unrelated, "successful insertion preserves the unrelated active item")
	TEST_ASSERT(candidate in box.slot_contents(CONTAINER_SLOT_STORAGE), "successful insertion registers the actual storage occupant")
	TEST_ASSERT_EQUAL(box.slot_used(CONTAINER_SLOT_STORAGE), used_before + candidate.get_storage_cost(), "successful insertion charges exactly the candidate's storage cost")
	TEST_ASSERT(box.remove_from_storage(candidate, T, user), "the real stored candidate can be removed to the floor")
	TEST_ASSERT_EQUAL(candidate.loc, T, "actual removal places the candidate on the requested floor")
	TEST_ASSERT(!(candidate in box.slot_contents(CONTAINER_SLOT_STORAGE)), "actual removal clears the declared storage occupant")
	TEST_ASSERT_EQUAL(box.slot_used(CONTAINER_SLOT_STORAGE), used_before, "actual removal restores original capacity accounting")
	TEST_ASSERT_EQUAL(user.get_active_hand(), unrelated, "the complete round trip preserves the unrelated active item")
