/// Actual unpowered airlock motion must refuse ordinary operation and mechanical obstructions, while forced motion completes through its real animation timers.
/datum/unit_test/om/interim_airlock_unpowered_motion/run_om(list/made)
	var/turf/T = test_floor()
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock, T)
	made += door
	door.autoclose = FALSE
	door.set_stat(NOPOWER)
	TEST_ASSERT(!door.arePowerSystemsOn(), "the actual airlock fixture has no operating power")
	TEST_ASSERT(door.density && !door.operating, "the actual airlock starts closed and idle")
	var/timers_before = om_timer_count(door)
	TEST_ASSERT(!door.open(), "the actual ordinary open entry refuses missing power")
	TEST_ASSERT(door.density && !door.operating, "ordinary opening refusal preserves closed idle state")
	TEST_ASSERT_EQUAL(om_timer_count(door), timers_before, "ordinary opening refusal schedules no new timer")
	set_bolted(door, TRUE, TRUE)
	TEST_ASSERT(!door.open(TRUE), "the actual forced open entry respects dropped bolts")
	TEST_ASSERT(door.density && !door.operating, "bolted forced refusal preserves closed idle state")
	TEST_ASSERT_EQUAL(om_timer_count(door), timers_before, "bolted forced refusal schedules no motion timer")
	set_bolted(door, FALSE, TRUE)
	set_welded(door, TRUE)
	TEST_ASSERT(!door.open(TRUE), "the actual forced open entry respects a welded airlock")
	TEST_ASSERT(door.density && !door.operating, "welded forced refusal preserves closed idle state")
	set_welded(door, FALSE)
	door.open(TRUE)
	TEST_ASSERT_EQUAL(door.operating, 1, "the unrestricted actual forced open starts animation")
	TEST_ASSERT(door.density, "actual forced opening retains density before its animation deadline")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!door.density && !door.operating, "the actual forced open timers finish with an open idle airlock")
	TEST_ASSERT(!door.opacity, "the actually opened airlock no longer blocks sight")
	TEST_ASSERT(!door.arePowerSystemsOn(), "forced opening does not restore actual airlock power")
	TEST_ASSERT(!door.close(), "the actual ordinary close entry also refuses missing power")
	TEST_ASSERT(!door.density && !door.operating, "ordinary closing refusal preserves open idle state")
	door.close(TRUE)
	TEST_ASSERT_EQUAL(door.operating, 1, "the actual forced close starts animation without power")
	TEST_ASSERT(!door.density, "actual forced closing preserves the open density until its animation deadline")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(door.density && !door.operating, "the real forced close timers finish with a closed idle airlock")
	TEST_ASSERT(door.opacity, "the actual closed opaque airlock blocks sight again")
	TEST_ASSERT(!door.arePowerSystemsOn(), "forced closing does not restore actual airlock power")
