/// Actual shoe chaining refuses stuck cuffs and refunds the same original on removal.
/datum/unit_test/interim_orange_shoes_sticky_cuffs/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/clothing/shoes/orange/shoes = allocate(/obj/item/clothing/shoes/orange, T)
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, T)
	TEST_ASSERT_NULL(shoes.chained(), "actual shoes initialize without chained cuffs")
	var/original_slowdown = shoes.slowdown
	var/original_icon = shoes.icon_state
	TEST_ASSERT(user.put_in_active_hand(cuffs), "the actor holds the original cuffs")
	add_trait(cuffs, TRAIT_NODROP, "interim_shoe_cuffs")
	TEST_ASSERT(user.release_refusal(cuffs, user), "actual inventory refuses sticky cuffs")
	test_op_handler(shoes, "orange_shoes_cuff_item", user, cuffs)
	TEST_ASSERT_NULL(shoes.chained(), "refused chaining records no cuffs")
	TEST_ASSERT_EQUAL(shoes.slowdown, original_slowdown, "refused chaining grants no movement penalty")
	TEST_ASSERT_EQUAL(shoes.icon_state, original_icon, "refused chaining preserves original shoe appearance")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cuffs, "refused chaining preserves exact original hand")
	TEST_ASSERT_EQUAL(cuffs.loc, user, "refused chaining preserves inventory containment")
	remove_trait(cuffs, TRAIT_NODROP, "interim_shoe_cuffs")
	test_op_handler(shoes, "orange_shoes_cuff_item", user, cuffs)
	TEST_ASSERT_EQUAL(shoes.chained(), cuffs, "allowed chaining records exact original cuffs")
	TEST_ASSERT_EQUAL(cuffs.loc, shoes, "allowed chaining physically contains original cuffs")
	TEST_ASSERT_EQUAL(shoes.slowdown, 15, "allowed chaining applies the actual declared movement penalty")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed chaining clears actual source hand")
	TEST_ASSERT_NULL(owner_of(cuffs), "chaining preserves its existing relation-only policy")
	shoes.remove_cuffs(user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), cuffs, "public removal returns the exact original cuffs")
	TEST_ASSERT_NULL(shoes.chained(), "public removal clears cuff relation")
	TEST_ASSERT_EQUAL(shoes.slowdown, original_slowdown, "public removal restores original movement penalty")
	TEST_ASSERT_EQUAL(shoes.icon_state, original_icon, "public removal restores original appearance")
	qdel(shoes)
	TEST_ASSERT(!QDELETED(cuffs), "returned original cuffs survive shoe teardown")
