/// Actual bulk gathering collects every eligible item of a repeated type while preserving a rejected oversized item; bulk emptying releases every original occupant and refunds all capacity.
/datum/unit_test/interim_toolbox_bulk_gather_empty/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/toolbox/toolbox = allocate(/obj/item/storage/toolbox, T)
	var/obj/item/storage/backpack/oversized = allocate(/obj/item/storage/backpack, T)
	var/obj/item/pen/first = allocate(/obj/item/pen, T)
	var/obj/item/pen/second = allocate(/obj/item/pen, T)
	var/obj/item/pen/third = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_active_hand(toolbox), "the actual actor holds the collection toolbox")
	var/expected_cost = first.get_storage_cost() + second.get_storage_cost() + third.get_storage_cost()
	TEST_ASSERT(expected_cost + oversized.get_storage_cost() <= toolbox.max_storage_space, "the actual fixture has spare capacity even for the oversized item")
	TEST_ASSERT_EQUAL(length(toolbox.slot_contents(CONTAINER_SLOT_STORAGE)), 0, "the actual collection toolbox starts empty")
	toolbox.gather_all(T, user)
	TEST_ASSERT_EQUAL(length(toolbox.slot_contents(CONTAINER_SLOT_STORAGE)), 3, "actual bulk gathering collects all three repeated-type pens")
	TEST_ASSERT_EQUAL(first.loc, toolbox, "actual gathering puts the first original pen in the toolbox")
	TEST_ASSERT_EQUAL(second.loc, toolbox, "actual gathering puts the second original pen in the toolbox")
	TEST_ASSERT_EQUAL(third.loc, toolbox, "actual gathering puts the third original pen in the toolbox")
	TEST_ASSERT(first in toolbox.slot_contents(CONTAINER_SLOT_STORAGE), "actual gathering records the first pen in the ledger")
	TEST_ASSERT(second in toolbox.slot_contents(CONTAINER_SLOT_STORAGE), "actual gathering records the second pen in the ledger")
	TEST_ASSERT(third in toolbox.slot_contents(CONTAINER_SLOT_STORAGE), "actual gathering records the third pen in the ledger")
	TEST_ASSERT_EQUAL(toolbox.slot_used(CONTAINER_SLOT_STORAGE), expected_cost, "actual gathering charges exactly the three pens' costs")
	TEST_ASSERT_EQUAL(oversized.loc, T, "actual mixed gathering leaves the rejected oversized backpack on the floor")
	TEST_ASSERT(!(oversized in toolbox.slot_contents(CONTAINER_SLOT_STORAGE)), "actual mixed gathering records no rejected backpack")
	TEST_ASSERT_EQUAL(user.get_active_hand(), toolbox, "actual gathering preserves the actor's held toolbox")
	toolbox.drop_contents(user)
	TEST_ASSERT_EQUAL(first.loc, T, "actual bulk emptying returns the first original pen to the floor")
	TEST_ASSERT_EQUAL(second.loc, T, "actual bulk emptying returns the second original pen to the floor")
	TEST_ASSERT_EQUAL(third.loc, T, "actual bulk emptying returns the third original pen to the floor")
	TEST_ASSERT_EQUAL(length(toolbox.slot_contents(CONTAINER_SLOT_STORAGE)), 0, "actual bulk emptying clears every original ledger occupant")
	TEST_ASSERT_EQUAL(toolbox.slot_used(CONTAINER_SLOT_STORAGE), 0, "actual bulk emptying refunds all gathered capacity")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/pen)), 3, "actual gather-empty round trip neither duplicates nor loses pens")
	TEST_ASSERT_EQUAL(oversized.loc, T, "actual bulk emptying preserves the previously rejected backpack")
	TEST_ASSERT_EQUAL(user.get_active_hand(), toolbox, "actual bulk emptying preserves the actor's held toolbox")
