/// Actual independent countdowns follow their target and disappear when its real relation clears.
/datum/unit_test/interim_countdown_orphan_cleanup/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/destination = get_step(T, EAST)
	TEST_ASSERT(destination, "real countdown fixture needs a neighboring turf")
	var/obj/item/pen/parent = allocate(/obj/item/pen, T)
	var/obj/effect/countdown/display = allocate(/obj/effect/countdown, parent)
	TEST_ASSERT(!QDELETED(display), "actual independent countdown initializes alive")
	TEST_ASSERT_EQUAL(display.attached_to, parent, "actual countdown initialization links its configured parent")
	TEST_ASSERT_EQUAL(display.loc, T, "actual countdown initialization projects onto the parent turf")
	display.start()
	TEST_ASSERT(display.started, "actual public start enables countdown updates")
	parent.forceMove(destination)
	display.countdown_step(null)
	TEST_ASSERT(!QDELETED(display), "actual update preserves a countdown with its live parent")
	TEST_ASSERT_EQUAL(display.loc, destination, "actual update follows its relocated parent onto the new turf")
	TEST_ASSERT_EQUAL(display.attached_to, parent, "actual live update preserves the exact parent relation")
	TEST_ASSERT(consume(parent), "actual parent consumption succeeds")
	TEST_ASSERT(QDELETED(parent), "actual consumption removes the original parent")
	TEST_ASSERT(!QDELETED(display), "independent countdown survives until its orphan update")
	TEST_ASSERT_NULL(display.attached_to, "actual parent deletion clears its weak attachment relation")
	display.countdown_step(null)
	TEST_ASSERT(QDELETED(display), "actual orphan update consumes the original independent countdown")
