/datum/unit_test/interim_parcel_native_label/Run()
	test_driver_begin()
	exercise_label()
	test_driver_end()

/datum/unit_test/interim_parcel_native_label/proc/exercise_label()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	var/obj/item/smallDelivery/parcel = allocate(/obj/item/smallDelivery, T)
	var/original_name = parcel.name
	var/original_desc = parcel.desc
	var/original_examtext = parcel.examtext
	TEST_ASSERT_EQUAL(parcel.nameset, 0, "The actual empty parcel starts without a title")
	test_click(user, parcel, pen)
	var/datum/prompt/choice/menu = SSrequests.open_for(user)
	TEST_ASSERT(istype(menu), "The migrated pen stage opens the native alteration menu")
	test_answer(user, "Title")
	var/datum/prompt/text/title = SSrequests.open_for(user)
	TEST_ASSERT(istype(title), "The real Title selection opens native text entry")
	TEST_ASSERT_EQUAL(title.normalize("Field Samples"), "Field Samples", "The actual title kind accepts the canonical label unchanged")
	test_answer(user, "Field Samples")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Accepted title completes the request chain")
	TEST_ASSERT_EQUAL(parcel.name, "[original_name] (Field Samples)", "The actual parcel receives exactly one title suffix")
	TEST_ASSERT_EQUAL(parcel.nameset, 1, "Accepted title sets the real parcel flag")
	TEST_ASSERT_EQUAL(parcel.desc, original_desc, "Title preserves the real parcel description")
	TEST_ASSERT_EQUAL(parcel.examtext, original_examtext, "Title preserves the independent handwritten description")
	test_click(user, parcel, pen)
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/choice), "The next migrated pen stage opens a fresh alteration menu")
	test_answer(user, null, REQ_CANCELLED)
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Closing the next menu leaves no pending request")
	TEST_ASSERT_EQUAL(parcel.name, "[original_name] (Field Samples)", "Explicit close adds no duplicate title")
	TEST_ASSERT_EQUAL(parcel.nameset, 1, "Explicit close preserves the title flag")
	TEST_ASSERT_EQUAL(parcel.desc, original_desc, "Explicit close preserves description")
	TEST_ASSERT_EQUAL(parcel.examtext, original_examtext, "Explicit close preserves handwritten text")
