/// Deleting a closed clamp must restore the actual pipe it placed into stasis.
/datum/unit_test/interim_clamp_deletion/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/atmospherics/pipe/simple/pipe = allocate(/obj/machinery/atmospherics/pipe/simple, T)
	var/obj/machinery/clamp/clamp = allocate(/obj/machinery/clamp, T, pipe)
	TEST_ASSERT_EQUAL(clamp.target_ref(), pipe, "The real clamp constructor must attach to its supplied pipe")
	TEST_ASSERT(!pipe.in_stasis, "The unclamped pipe must initially allow normal flow")
	TEST_ASSERT(clamp.interaction_toggle(actor, null, null), "The real toggle interaction must close its attached clamp")
	TEST_ASSERT(!clamp.open, "Toggling must close the actual clamp")
	TEST_ASSERT(pipe.in_stasis, "The closed clamp must place its actual pipe into stasis")
	qdel(clamp)
	TEST_ASSERT(!QDELETED(pipe), "Deleting the clamp must preserve its pipe")
	TEST_ASSERT(!pipe.in_stasis, "Deleting the closed clamp must restore normal pipe flow")
