/// Ending a live beam destroys its actual segments and cancels its declared repeat.
/datum/unit_test/om/interim_beam_end_lifecycle/run_om(list/made)
	var/turf/T = run_loc_floor_bottom_left
	var/obj/item/pen/origin = allocate(/obj/item/pen, T)
	var/obj/item/pen/target = allocate(/obj/item/pen, get_step(T, EAST))
	var/datum/beam/beam = allocate(/datum/beam, origin, target, 'icons/effects/beam.dmi', "b_beam", 1 MINUTE, 10, /obj/effect/ebeam, 1 SECOND)
	made += list(origin, target, beam)
	beam.Start()
	TEST_ASSERT(length(beam.elements) > 0, "the live beam draws actual owned segments")
	var/list/segments = beam.elements.Copy()
	scheduler_advance(0.01 SECONDS)
	TEST_ASSERT(after_pending(beam, "beam_tick"), "the live beam has an actual pending repeat")
	beam.End()
	beam.beam_tick()
	TEST_ASSERT(QDELETED(beam), "ending the beam deletes its non-movable controller immediately")
	TEST_ASSERT_NULL(beam.origin(), "terminal teardown clears the origin relation")
	TEST_ASSERT_NULL(beam.target(), "terminal teardown clears the target relation")
	TEST_ASSERT_EQUAL(length(beam.elements), 0, "terminal teardown clears the owned segment list")
	for(var/obj/effect/ebeam/segment as anything in segments)
		TEST_ASSERT(QDELETED(segment), "terminal teardown deletes every drawn segment")
		TEST_ASSERT_NULL(segment.owner(), "the deleted segment no longer names its beam owner")
	TEST_ASSERT_EQUAL(om_timer_count(beam), 0, "terminal teardown cancels the pending repeat timer")

/// Draw() can terminate a beam before Start() reaches its state setter.
/datum/unit_test/om/interim_beam_invalid_start/run_om(list/made)
	var/turf/T = run_loc_floor_bottom_left
	var/obj/item/pen/origin = allocate(/obj/item/pen, T)
	var/obj/item/pen/target = allocate(/obj/item/pen, get_step(T, EAST))
	var/datum/beam/beam = allocate(/datum/beam, origin, target, 'icons/effects/beam.dmi', "b_beam", 1 MINUTE, 10, /obj/effect/ebeam, 1 SECOND)
	made += list(origin, target, beam)
	qdel(target)
	TEST_ASSERT_NULL(beam.target(), "deleting the endpoint actually clears the beam's target relation")
	beam.Start()
	TEST_ASSERT(QDELETED(beam), "Start terminates a beam whose endpoint disappeared")
	TEST_ASSERT(!after_pending(beam, "beam_tick"), "Start never rearms the controller after Draw deletes it")
	scheduler_advance(0.01 SECONDS)
	TEST_ASSERT_EQUAL(om_timer_count(beam), 0, "the invalid controller has no repeat timer after field processing")
	TEST_ASSERT_EQUAL(length(beam.elements), 0, "the invalid controller leaves no owned visual segments")
