/// Actual grown-produce extraction consumes its input only when inventory releases it, then creates packets for the original seed.
/datum/unit_test/interim_seed_extractor_sticky_produce/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/seed_extractor/extractor = allocate(/obj/machinery/seed_extractor, T)
	var/obj/item/reagent_containers/food/snacks/grown/fruit = allocate(/obj/item/reagent_containers/food/snacks/grown, T, PLANT_APPLE)
	TEST_ASSERT(!QDELETED(fruit), "the actual apple seed creates a live grown fruit")
	var/datum/seed/original_seed = fruit.seed()
	TEST_ASSERT_NOTNULL(original_seed, "the actual fruit has a real original seed")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/seeds)), 0, "the actual extraction floor starts without output packets")
	TEST_ASSERT(user.put_in_active_hand(fruit), "the actor holds the original grown fruit")
	add_trait(fruit, TRAIT_NODROP, "interim_seed_extractor_sticky")
	TEST_ASSERT(user.release_refusal(fruit, user), "the actual inventory refuses release of the sticky fruit")
	test_op_handler(extractor, "interaction_extract_grown", user, fruit)
	own_turf_contents(T)
	TEST_ASSERT(!QDELETED(fruit), "refused extraction preserves the original input fruit")
	TEST_ASSERT_EQUAL(user.get_active_hand(), fruit, "refused extraction preserves the original hand slot")
	TEST_ASSERT_EQUAL(fruit.loc, user, "refused extraction preserves actual inventory containment")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/seeds)), 0, "refused input consumption produces no seed packets")
	remove_trait(fruit, TRAIT_NODROP, "interim_seed_extractor_sticky")
	test_op_handler(extractor, "interaction_extract_grown", user, fruit)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(fruit), "allowed actual extraction consumes the original input")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed input consumption clears the source hand")
	var/list/packets = contents_of(T, /obj/item/seeds)
	TEST_ASSERT(length(packets) >= 2 && length(packets) <= 5, "actual extraction preserves the existing inclusive two-to-five packet yield")
	for(var/obj/item/seeds/packet in packets)
		TEST_ASSERT_EQUAL(packet.seed_type, original_seed.name, "every actual output packet names the original fruit's seed")
		TEST_ASSERT(!QDELETED(packet), "every actual output packet survives extraction")
