/// The actual balloon refill entry preserves both mixture components when its remaining capacity limits delivery.
/datum/unit_test/interim_balloon_mixed_capacity_refill/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/toy/balloon/balloon = allocate(/obj/item/toy/balloon, T)
	var/obj/structure/reagent_dispensers/watertank/tank = allocate(/obj/structure/reagent_dispensers/watertank, T)
	TEST_ASSERT_EQUAL(balloon.reagents.maximum_volume, 10, "actual initialized balloon holds ten units")
	TEST_ASSERT_EQUAL(balloon.reagents.total_volume, 0, "actual initialized balloon starts empty")
	TEST_ASSERT(user.put_in_active_hand(balloon), "actor holds exact original balloon adjacent to tank")
	tank.reagents.clear_reagents()
	tank.reagents.add_reagent(REAGENT_ID_WATER, 12)
	tank.reagents.add_reagent(REAGENT_ID_NICOTINE, 4)
	balloon.reagents.add_reagent(REAGENT_ID_WATER, 6)
	balloon.afterattack(tank, user, TRUE)
	TEST_ASSERT_EQUAL(balloon.reagents.total_volume, 10, "actual refill fills only four remaining units")
	TEST_ASSERT_EQUAL(balloon.reagents.get_reagent_amount(REAGENT_ID_WATER), 9, "capacity-limited refill delivers three mixture units of water")
	TEST_ASSERT_EQUAL(balloon.reagents.get_reagent_amount(REAGENT_ID_NICOTINE), 1, "capacity-limited refill delivers one mixture unit of nicotine")
	TEST_ASSERT_EQUAL(tank.reagents.get_reagent_amount(REAGENT_ID_WATER), 9, "actual source loses only the three accepted water units")
	TEST_ASSERT_EQUAL(tank.reagents.get_reagent_amount(REAGENT_ID_NICOTINE), 3, "actual source loses only the one accepted nicotine unit")
	balloon.afterattack(tank, user, TRUE)
	TEST_ASSERT_EQUAL(tank.reagents.total_volume, 12, "full balloon receives no additional source debit")
	TEST_ASSERT_EQUAL(balloon.reagents.total_volume, 10, "full balloon preserves its exact total volume")
	TEST_ASSERT_EQUAL(balloon.reagents.get_reagent_amount(REAGENT_ID_NICOTINE), 1, "full balloon preserves its mixture composition")
	TEST_ASSERT_EQUAL(tank.reagents.get_reagent_amount(REAGENT_ID_NICOTINE), 3, "full-container refusal preserves source mixture composition")
	TEST_ASSERT_EQUAL(user.get_active_hand(), balloon, "refilling preserves exact original balloon hand")
	TEST_ASSERT_EQUAL(balloon.loc, user, "refilling preserves original inventory location")
