/// Actual condiment use transfers into closed food with capacity-limited proportional mixtures, refusing full, distant, and empty-source attempts without liquid loss.
/datum/unit_test/interim_condiment_food_transfer/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/food/condiment/source = allocate(/obj/item/reagent_containers/food/condiment, T)
	var/obj/item/reagent_containers/food/snacks/food = allocate(/obj/item/reagent_containers/food/snacks, T)
	TEST_ASSERT(!food.is_open_container(), "the actual food target is closed and requires the special condiment path")
	TEST_ASSERT_EQUAL(source.amount_per_transfer_from_this, 2, "the actual condiment container has a two-unit dose")
	TEST_ASSERT_EQUAL(food.reagents.total_volume, 0, "the actual base food begins without ingredients")
	source.reagents.add_reagent(REAGENT_ID_WATER, 6)
	source.reagents.add_reagent(REAGENT_ID_ETHANOL, 2)
	food.reagents.add_reagent(REAGENT_ID_WATER, food.reagents.maximum_volume - 1)
	var/target_water_before = food.reagents.get_reagent_amount(REAGENT_ID_WATER)
	source.afterattack(food, user, TRUE)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 7, "actual condiment application debits only the food's one free unit")
	TEST_ASSERT(abs(source.reagents.get_reagent_amount(REAGENT_ID_WATER) - 5.25) < 0.001, "actual limited transfer debits exactly three-quarter unit of source water")
	TEST_ASSERT(abs(source.reagents.get_reagent_amount(REAGENT_ID_ETHANOL) - 1.75) < 0.001, "actual limited transfer debits exactly one-quarter unit of source ethanol")
	TEST_ASSERT(abs(food.reagents.get_reagent_amount(REAGENT_ID_WATER) - (target_water_before + 0.75)) < 0.001, "the actual food receives the matching three-quarter water unit")
	TEST_ASSERT(abs(food.reagents.get_reagent_amount(REAGENT_ID_ETHANOL) - 0.25) < 0.001, "the actual food receives the matching one-quarter ethanol unit")
	TEST_ASSERT_EQUAL(food.reagents.total_volume, food.reagents.maximum_volume, "actual limited condiment use fills the food exactly to capacity")
	source.afterattack(food, user, TRUE)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 7, "actual full-food refusal preserves the entire remaining source mixture")
	TEST_ASSERT(abs(food.reagents.get_reagent_amount(REAGENT_ID_ETHANOL) - 0.25) < 0.001, "actual full-food refusal preserves the target mixture")
	food.reagents.clear_reagents()
	source.afterattack(food, user, TRUE)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 5, "actual application to empty food debits the configured two-unit dose")
	TEST_ASSERT(abs(food.reagents.get_reagent_amount(REAGENT_ID_WATER) - 1.5) < 0.001, "actual full-dose application delivers exactly one-and-a-half water units")
	TEST_ASSERT(abs(food.reagents.get_reagent_amount(REAGENT_ID_ETHANOL) - 0.5) < 0.001, "actual full-dose application delivers exactly one-half ethanol unit")
	var/turf/distant = get_step(get_step(T, EAST), EAST)
	TEST_ASSERT_NOTNULL(distant, "the actual target has a genuinely distant turf")
	food.forceMove(distant)
	TEST_ASSERT(!user.Adjacent(food), "the actual food really lies beyond the actor's adjacent reach")
	source.afterattack(food, user, TRUE)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 5, "actual distant-target refusal preserves the remaining source dose")
	TEST_ASSERT_EQUAL(food.reagents.total_volume, 2, "actual distant-target refusal preserves the food's received dose")
	food.forceMove(T)
	source.reagents.clear_reagents()
	source.afterattack(food, user, TRUE)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 0, "actual empty-source refusal cannot invent condiment")
	TEST_ASSERT(abs(food.reagents.get_reagent_amount(REAGENT_ID_WATER) - 1.5) < 0.001, "actual empty-source refusal preserves food water")
	TEST_ASSERT(abs(food.reagents.get_reagent_amount(REAGENT_ID_ETHANOL) - 0.5) < 0.001, "actual empty-source refusal preserves food ethanol")
