/// Actual lethal nanoform dormancy enables the cluster's existing inventory transfer.
/datum/unit_test/interim_protean_cluster_drop_actor/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/core = make_protean_with_rig()
	var/datum/forms/protean/forms = core.get_protean_forms()
	var/obj/item/rig/protean/cluster = forms.rig
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	hud.build_action_groups()
	var/atom/movable/screen/right = hud.r_hand_hud_object
	var/atom/movable/screen/left = hud.l_hand_hud_object
	TEST_ASSERT_NOTNULL(cluster, "actual protean construction creates its real control cluster")
	TEST_ASSERT_NOTNULL(right, "the real actor HUD provides its right hand target")
	TEST_ASSERT_NOTNULL(left, "the real actor HUD provides its left hand target")
	TEST_ASSERT_NULL(cluster.get_dormancy(), "the real living protean starts without dormancy")
	TEST_ASSERT_EQUAL(cluster.handle_inventory_drop(actor, left), TRUE, "a nondormant cluster retains its earlier consumed refusal")
	TEST_ASSERT(cluster.unremovable, "actual nondormant refusal enforces its original unremovable state")
	core.injure(INJURY_BLUNT, 1000, BP_TORSO, flags = INJURE_IGNORE_RESISTANCE | INJURE_SILENT)
	TEST_ASSERT_NOTNULL(cluster.get_dormancy(), "actual lethal nanoform injury creates real core dormancy")
	TEST_ASSERT_EQUAL(core.loc, cluster, "actual dormancy folds the real protean core inside its cluster")
	TEST_ASSERT(cluster.inert && cluster.canremove, "actual dormancy makes the real cluster inert and removable")
	TEST_ASSERT(actor.put_in_r_hand(cluster), "the actual initiating human picks up the dormant cluster")
	cluster.handle_inventory_drop(bystander, left)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), cluster, "an unrelated actor cannot take the actual held cluster")
	TEST_ASSERT(!bystander.item_is_in_hands(cluster), "unrelated actor obtains no held cluster")
	actor.set_stat(UNCONSCIOUS)
	TEST_ASSERT_EQUAL(actor.stat, UNCONSCIOUS, "the original actor stat guard is actually enabled")
	cluster.handle_inventory_drop(actor, left)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), cluster, "actual stat refusal preserves the original cluster hand")
	actor.set_stat(CONSCIOUS)
	var/obj/item/blocker = allocate(/obj/item, T)
	TEST_ASSERT(actor.put_in_l_hand(blocker), "a real unrelated item occupies the dormant cluster destination hand")
	cluster.handle_inventory_drop(actor, left)
	TEST_ASSERT_NULL(actor.get_right_hand(), "legacy occupied-hand transfer first clears the real cluster's former hand")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), blocker, "failed cluster hand insertion preserves the unrelated held item")
	TEST_ASSERT_EQUAL(cluster.loc, T, "actual occupied-hand branch drops the dormant cluster onto its real floor")
	TEST_ASSERT_EQUAL(core.loc, cluster, "actual floor drop preserves the exact dormant core inside")
	TEST_ASSERT_EQUAL(cluster.myprotean, core, "actual floor drop retains the real protean relation")
	TEST_ASSERT(actor.unEquip(blocker), "actual removal frees the destination hand")
	TEST_ASSERT(actor.put_in_r_hand(cluster), "actual pickup recovers the same dormant cluster from its floor")
	TEST_ASSERT_EQUAL(core.loc, cluster, "actual pickup preserves the exact folded core")
	TEST_ASSERT_EQUAL(cluster.handle_inventory_drop(actor, left), TRUE, "actual dormant cluster transfer consumes native drag")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), cluster, "actual explicit actor receives exact dormant cluster in requested hand")
	TEST_ASSERT_NULL(actor.get_right_hand(), "actual accepted transfer clears the real former hand")
	cluster.handle_inventory_drop(actor, right)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), cluster, "actual roundtrip restores the exact dormant cluster")
	TEST_ASSERT_NULL(actor.get_left_hand(), "actual roundtrip clears its temporary hand")
	TEST_ASSERT_EQUAL(core.loc, cluster, "actual inventory roundtrip retains its exact dormant protean inside")
	TEST_ASSERT_EQUAL(cluster.myprotean, core, "actual roundtrip retains the exact protean relation")
	TEST_ASSERT_EQUAL(forms.rig, cluster, "actual roundtrip retains the original real forms cluster")
	TEST_ASSERT_NOTNULL(cluster.get_dormancy(), "inventory transfer does not revive the genuinely dormant core")
	TEST_ASSERT(!cluster.unremovable, "actual dormant inventory transfer retains the original removable state")
