/// Actual caseless chamber processing consumes the exact chamber record and preserves independent magazine stock.
/datum/unit_test/interim2_caseless_chamber_disposal/Run()
	var/turf/T = test_floor()
	var/obj/item/gun/projectile/caseless/prototype/loaded/gun = allocate(/obj/item/gun/projectile/caseless/prototype/loaded, T)
	var/obj/item/gun/projectile/caseless/prototype/loaded/control = allocate(/obj/item/gun/projectile/caseless/prototype/loaded, T)
	var/obj/item/ammo_magazine/magazine = gun.ammo_magazine
	var/obj/item/ammo_magazine/control_magazine = control.ammo_magazine
	TEST_ASSERT(istype(magazine) && istype(control_magazine) && magazine != control_magazine, "The actual loaded rifle constructors must supply distinct real magazines")
	TEST_ASSERT_EQUAL(magazine.type, /obj/item/ammo_magazine/m5mmcaseless, "The actual canonical rifle must construct its 5mm caseless magazine")
	TEST_ASSERT_EQUAL(owner_of(magazine), gun, "The actual rifle must own its original magazine")
	TEST_ASSERT_EQUAL(length(magazine.stored_ammo), 30, "The installed canonical magazine must construct its thirty real rounds")
	TEST_ASSERT_EQUAL(length(control_magazine.stored_ammo), 30, "The independent installed magazine must construct thirty distinct rounds")
	var/list/original_stock = magazine.stored_ammo.Copy()
	var/list/control_stock = control_magazine.stored_ammo.Copy()
	TEST_ASSERT_EQUAL(gun.handle_casings, EJECT_CASINGS, "The canonical rifle must select the actual eject-casing path")
	for(var/i in 1 to 2)
		var/obj/item/ammo_casing/original = original_stock[31 - i]
		TEST_ASSERT_EQUAL(original.type, /obj/item/ammo_casing/a5mmcaseless, "The actual original round must be canonical caseless ammunition")
		TEST_ASSERT(original.caseless, "The canonical original casing must select real caseless disposal")
		TEST_ASSERT_EQUAL(owner_of(original), magazine, "The actual magazine must own the original round before chambering")
		var/obj/item/projectile/projectile = original.BB
		TEST_ASSERT(istype(projectile), "The real original casing must contain an actual projectile")
		own(original)
		own(projectile)
		TEST_ASSERT(gun.chamber_bullet(), "The real public chamber operation must load the next original magazine round")
		TEST_ASSERT_EQUAL(gun.chambered, original, "Actual chambering must reference the exact original final magazine round")
		TEST_ASSERT_NULL(owner_of(original), "The relation-only chamber must release the original magazine ownership")
		TEST_ASSERT_EQUAL(length(magazine.stored_ammo), 30 - i, "Actual chambering must debit exactly one magazine record")
		TEST_ASSERT_EQUAL(gun.consume_next_projectile(), projectile, "The actual chamber must return its exact original projectile")
		gun.process_chambered()
		TEST_ASSERT(QDELETED(original), "Actual caseless processing must destroy the exact original chamber record")
		TEST_ASSERT(QDELETED(projectile), "Actual un-fired chamber disposal must destroy its exact original contained projectile")
		TEST_ASSERT_NULL(gun.chambered, "Actual destruction must clear the real reciprocal chamber relation")
		TEST_ASSERT(!QDELETED(magazine), "Chamber processing must preserve the original installed magazine")
		TEST_ASSERT_EQUAL(owner_of(magazine), gun, "Chamber processing must preserve actual magazine ownership")
	for(var/i in 1 to 28)
		var/obj/item/ammo_casing/remaining = original_stock[i]
		TEST_ASSERT_EQUAL(magazine.stored_ammo[i], remaining, "Processing must preserve exact remaining original stock order")
		TEST_ASSERT(!QDELETED(remaining), "Processing must preserve every unchambered original round")
		TEST_ASSERT_EQUAL(owner_of(remaining), magazine, "Every remaining original round must retain its magazine owner")
	TEST_ASSERT_EQUAL(control.ammo_magazine, control_magazine, "Processing must preserve the independent original magazine")
	TEST_ASSERT_EQUAL(length(control_magazine.stored_ammo), 30, "Processing must preserve the entire independent magazine quantity")
	for(var/i in 1 to 30)
		var/obj/item/ammo_casing/remaining = control_stock[i]
		TEST_ASSERT_EQUAL(control_magazine.stored_ammo[i], remaining, "Processing must preserve each independent exact original round identity")
		TEST_ASSERT(!QDELETED(remaining), "Independent original stock must stay alive")
		TEST_ASSERT_EQUAL(owner_of(remaining), control_magazine, "Independent original stock must retain its owner")
