/// Real nested storage insertion and removal APIs reject containment cycles while preserving both actual ledgers and the nested item.
/datum/unit_test/interim_storage_nested_cycle_refusals/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/backpack/outer = allocate(/obj/item/storage/backpack, T)
	var/obj/item/storage/box/inner = allocate(/obj/item/storage/box, T)
	var/obj/item/pen/item = allocate(/obj/item/pen, T)
	TEST_ASSERT(inner.insert_item(item), "the actual inner box accepts its real pen")
	TEST_ASSERT(outer.insert_item(inner), "the actual backpack accepts the real filled inner box")
	var/outer_used = outer.slot_used()
	var/inner_used = inner.slot_used()
	TEST_ASSERT(outer_used > 0 && inner_used > 0, "both actual nested containers account for their contents")
	TEST_ASSERT_EQUAL(inner.insert_refusal(outer, user), "it can't go inside itself", "the actual ancestor insertion is refused specifically as a containment cycle")
	TEST_ASSERT(!inner.insert_item(outer, user), "the actual public insertion API rejects placing the ancestor inside its child")
	TEST_ASSERT(!outer.insert_item(outer, user), "the actual public insertion API rejects direct self-containment")
	TEST_ASSERT(!outer.remove_from_storage(inner, inner, user), "the actual removal API rejects moving the contained box inside itself")
	TEST_ASSERT_EQUAL(outer.loc, T, "all actual cycle refusals preserve the outer backpack on the original floor")
	TEST_ASSERT_EQUAL(inner.loc, outer, "all actual cycle refusals preserve the inner box's exact parent")
	TEST_ASSERT_EQUAL(item.loc, inner, "all actual cycle refusals preserve the original pen's inner box")
	TEST_ASSERT(inner in outer.slot_contents(CONTAINER_SLOT_STORAGE), "all actual cycle refusals preserve the outer ledger entry")
	TEST_ASSERT(item in inner.slot_contents(CONTAINER_SLOT_STORAGE), "all actual cycle refusals preserve the inner ledger entry")
	TEST_ASSERT(!(outer in inner.slot_contents(CONTAINER_SLOT_STORAGE)), "actual cycle refusals cannot add the ancestor to its child's ledger")
	TEST_ASSERT(!(inner in inner.slot_contents(CONTAINER_SLOT_STORAGE)), "actual cycle refusals cannot add the child to its own ledger")
	TEST_ASSERT_EQUAL(outer.slot_used(), outer_used, "all actual cycle refusals preserve outer capacity accounting")
	TEST_ASSERT_EQUAL(inner.slot_used(), inner_used, "all actual cycle refusals preserve inner capacity accounting")
	TEST_ASSERT(inner.remove_from_storage(item, T, user), "the actual preserved inner container remains usable for ordinary removal")
	TEST_ASSERT_EQUAL(item.loc, T, "actual subsequent ordinary removal reaches the original floor")
	TEST_ASSERT_EQUAL(inner.slot_used(), 0, "actual subsequent ordinary removal releases only the inner pen's capacity")
	TEST_ASSERT_EQUAL(outer.slot_used(), outer_used, "actual subsequent inner-item removal preserves the outer box's capacity cost")
	TEST_ASSERT_EQUAL(inner.loc, outer, "actual subsequent inner-item removal preserves the nested box relationship")
