/// The patient choice is answered by its own answerer, whoever else is acting at that moment.
/datum/unit_test/interim_medical_stand_prompt_actor/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	actor.enable_godmode()
	patient.enable_godmode()
	bystander.enable_godmode()
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, T)
	TEST_ASSERT(bystander.equip_to_slot(cuffs, SLOT_ID_HANDCUFFED), "actual cuffs equip into the unrelated actor restraint slot")
	TEST_ASSERT(bystander.incapacitated(), "the unrelated native answer delivery actor really fails the drag requirement")
	var/obj/structure/medical_stand/stand = allocate(/obj/structure/medical_stand, T)
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	TEST_ASSERT(test_op_handler(stand, "medical_stand_interaction_item", actor, beaker), "actual item interaction installs the reagent vessel")
	TEST_ASSERT_EQUAL(stand.beaker, beaker, "the stand owns the exact installed vessel")
	TEST_ASSERT(stand.CanMouseDrop(patient, actor), "the explicit initiating actor satisfies the real patient drag requirement")
	TEST_ASSERT(!stand.CanMouseDrop(patient, bystander), "the unrelated native actor cannot satisfy that same requirement")
	stand.attach_action(null, "Drip needle", patient)
	TEST_ASSERT_NULL(stand.attached(), "an absent actor cannot begin patient attachment")
	var/datum/request/open = open_request(stand, /datum/prompt/choice/medical_stand_attach, TYPE_PROC_REF(/obj/structure/medical_stand, attach_choice_made), answerer = actor, title = "Attach/Detach Choice", question = "What do you want to attach/detach?", choices = list("Gas mask", "Drip needle"), patient = patient, ask_flags = ASK_NEAR_SUBJECT | ASK_CAPABLE, timeout = 0)
	TEST_ASSERT_NOTNULL(open, "one actual typed patient choice is opened")
	TEST_ASSERT_EQUAL(open.answerer, actor, "the actual choice retains its explicit initiating actor")
	test_answer(actor, "Drip needle")
	TEST_ASSERT_NULL(stand.attached(), "the actual answer starts timed insertion without immediately attaching")
	test_time(4 SECONDS)
	TEST_ASSERT_NULL(stand.attached(), "needle insertion remains incomplete before its five second deadline")
	test_time(2 SECONDS)
	TEST_ASSERT_EQUAL(stand.attached(), patient, "the actual choice callback completes insertion into the exact selected patient despite unrelated ambient actor")
	TEST_ASSERT_NOTEQUAL(stand.attached(), bystander, "the unrelated native actor is never attached")
	TEST_ASSERT_EQUAL(stand.beaker, beaker, "timed attachment preserves the exact installed vessel")
	stand.attach_action(actor, "Drip needle", patient)
	test_time(3 SECONDS)
	TEST_ASSERT_NULL(stand.attached(), "the same explicit actor can complete actual timed needle removal")
	TEST_ASSERT_EQUAL(stand.beaker, beaker, "actual removal preserves the installed vessel")
