/// Actual timed hive construction consumes its original assembly only at completion.
/datum/unit_test/interim_beehive_assembly_consumption/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/beehive_assembly/assembly = allocate(/obj/item/beehive_assembly, T)
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/beehive)), 0, "actual fixture starts without constructed hives")
	TEST_ASSERT(user.put_in_active_hand(assembly), "the actor holds exact original assembly")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "actual construction actor starts capable")
	test_click(user, assembly, assembly)
	TEST_ASSERT(!isnull(op_pending_of(user)), "public construction entry starts actual timed work")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/beehive)), 0, "starting construction creates no early hive")
	test_time(2 SECONDS)
	TEST_ASSERT(!QDELETED(assembly), "actual construction consumes no assembly before deadline")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/beehive)), 0, "actual construction creates no hive before deadline")
	test_time(2 SECONDS)
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "actual construction actor remains capable at completion")
	TEST_ASSERT_NULL(op_pending_of(user), "actual construction completes pending work")
	TEST_ASSERT(QDELETED(assembly), "allowed construction consumes exact original assembly")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/beehive)), 1, "one consumed original produces exactly one real hive")
	var/obj/machinery/beehive/hive = locate_within(T, /obj/machinery/beehive)
	TEST_ASSERT_NOTNULL(hive, "actual construction creates a real surviving hive")
	own(hive)
	TEST_ASSERT_EQUAL(hive.type, /obj/machinery/beehive, "actual construction produces exact declared hive type")
	TEST_ASSERT(!QDELETED(hive), "actual product survives initialization")
	TEST_ASSERT_EQUAL(hive.loc, T, "actual product occupies original construction turf")
	TEST_ASSERT(hive.anchored && hive.density, "actual initialized hive is a secured physical machine")
	test_driver_end()
