/// Actual timed species upload must consume its original disk before enabling a new fabrication option.
/datum/unit_test/om/interim_prosthetics_species_upload_consumption/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/mob/controller = allocate(/mob/living/simple_mob/e0_fixture, get_step(T, NORTH))
	rel_set(user, nameof(user.teleop), controller)
	var/obj/machinery/mecha_part_fabricator_tg/prosthetics/machine = allocate(/obj/machinery/mecha_part_fabricator_tg/prosthetics, T)
	var/obj/item/disk/species/disk = allocate(/obj/item/disk/species, T)
	made += list(user, controller, machine, disk)
	disk.species = SPECIES_TAJARAN
	TEST_ASSERT((disk.species in GLOB.all_species), "actual disk names a real registered fabrication species")
	TEST_ASSERT(!(disk.species in machine.species_types), "actual initialized fabricator does not already support the disk species")
	var/original_count = length(machine.species_types)
	TEST_ASSERT(user.put_in_active_hand(disk), "the actor holds exact original species disk")
	machine.interaction_species_disk(user, disk, null)
	TEST_ASSERT(LAZYLEN(user.do_afters), "public upload entry starts actual timed work")
	scheduler_advance((4 SECONDS) / (1 SECOND))
	TEST_ASSERT(!QDELETED(disk), "actual upload consumes no original disk before deadline")
	TEST_ASSERT_EQUAL(length(machine.species_types), original_count, "actual upload grants no early fabrication option")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "actual controlled upload actor remains capable at completion")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "actual upload finishes pending work")
	TEST_ASSERT(QDELETED(disk), "allowed upload consumes exact original species disk")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT((SPECIES_TAJARAN in machine.species_types), "allowed original consumption enables exact disk species")
	TEST_ASSERT_EQUAL(length(machine.species_types), original_count + 1, "one consumed disk grants exactly one new fabrication option")
