/// Removing real machine-frame stock parts refunds the exact items while preserving wiring and restoring the board's requirements.
/datum/unit_test/interim_machine_frame_component_removal/Run()
	test_driver_begin()
	defer_cleanup(src, PROC_REF(interim_native_frame_driver_end))
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/structure/frame/frame = allocate(/obj/structure/frame, T)
	var/obj/item/circuitboard/autolathe/board = allocate(/obj/item/circuitboard/autolathe, T)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, T, 6)
	var/obj/item/stock_parts/matter_bin/part = allocate(/obj/item/stock_parts/matter_bin, T)
	TEST_ASSERT(interim_native_frame_step(frame, user, "construction.build:machine_frame_placed.anchor"), "the actual frame can be anchored")
	TEST_ASSERT(interim_native_frame_step(frame, user, "construction.build:machine_frame_board_in.insert_board", board), "the actual autolathe board enters the frame")
	TEST_ASSERT(interim_native_frame_step(frame, user, "construction.build:machine_frame_fastened.fasten_board"), "the actual board can be fastened")
	TEST_ASSERT(interim_native_frame_step(frame, user, "construction.build:machine_frame_wired.wire", cable), "the actual machine frame can be wired")
	var/bin_requirement = board.req_components[/obj/item/stock_parts/matter_bin]
	TEST_ASSERT(bin_requirement > 0, "the actual autolathe board requires matter bins")
	TEST_ASSERT_EQUAL(cable.get_amount(), 1, "actual wiring spends exactly five cable lengths")
	user.drop_item()
	TEST_ASSERT(user.put_in_active_hand(part), "the actual actor holds the exact stock part")
	TEST_ASSERT(test_op_committed(test_click(user, frame, part)), "the stock part enters through actual native item dispatch")
	TEST_ASSERT_EQUAL(part.loc, frame, "actual insertion contains the exact stock part")
	TEST_ASSERT(part in frame.components, "actual insertion registers the exact component")
	TEST_ASSERT_NULL(user.get_active_hand(), "actual insertion releases the original held slot")
	TEST_ASSERT_EQUAL(frame.req_components[/obj/item/stock_parts/matter_bin], bin_requirement - 1, "actual insertion satisfies exactly one bin requirement")
	TEST_ASSERT(interim_native_frame_step(frame, user, "construction.build:machine_frame_wired.remove_components"), "the real component-removal edge completes")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "component removal preserves the actual wired construction state")
	TEST_ASSERT_EQUAL(frame.circuit, board, "component removal preserves the exact circuit board")
	TEST_ASSERT_EQUAL(board.loc, frame, "component removal preserves actual board containment")
	TEST_ASSERT(!QDELETED(part), "component removal preserves the same original stock part")
	TEST_ASSERT_EQUAL(part.loc, T, "component removal refunds that exact stock part to the floor")
	TEST_ASSERT_EQUAL(length(frame.components), 0, "component removal clears the actual installed-components list")
	TEST_ASSERT_EQUAL(frame.req_components[/obj/item/stock_parts/matter_bin], bin_requirement, "component removal restores the full bin requirement")
	TEST_ASSERT_EQUAL(cable.get_amount(), 1, "component removal does not refund or spend wiring")
	TEST_ASSERT(!frame.has_all_components(user, frame, null), "the emptied wired frame cannot finish its machine")
	user.drop_item()
	TEST_ASSERT(user.put_in_active_hand(part), "the same refunded stock part can be held again")
	TEST_ASSERT(test_op_committed(test_click(user, frame, part)), "the stock part enters through actual native item dispatch")
	TEST_ASSERT_EQUAL(part.loc, frame, "the same refunded stock part can be reinstalled")
	TEST_ASSERT_EQUAL(length(frame.components), 1, "reinstalling registers exactly one actual component")
	TEST_ASSERT(part in frame.components, "reinstalling registers the same original stock part")
	TEST_ASSERT_EQUAL(frame.req_components[/obj/item/stock_parts/matter_bin], bin_requirement - 1, "reinstalling satisfies exactly one restored bin requirement")
