/// Tucking an actual breath mask into a gaiter respects its inventory release and restores the original item and material flags on removal.
/datum/unit_test/interim_gaiter_sticky_mask/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/clothing/accessory/gaiter/gaiter = allocate(/obj/item/clothing/accessory/gaiter, T)
	var/obj/item/clothing/mask/breath/mask = allocate(/obj/item/clothing/mask/breath, T)
	var/original_flags = gaiter.item_flags
	TEST_ASSERT(original_flags & FLEXIBLEMATERIAL, "the actual base gaiter starts flexible")
	TEST_ASSERT_NULL(gaiter.breathmask(), "the actual base gaiter starts without a tucked breath mask")
	TEST_ASSERT(!gaiter.breath_masked, "the actual base gaiter starts without the mask-presence flag")
	TEST_ASSERT(user.put_in_active_hand(mask), "the actor holds the actual supported breath mask")
	add_trait(mask, TRAIT_NODROP, "interim_gaiter_sticky_mask")
	TEST_ASSERT(user.release_refusal(mask, user), "the actual inventory refuses release of the sticky mask")
	test_op_handler(gaiter, "gaiter_tuck_mask_item", user, mask)
	TEST_ASSERT_EQUAL(mask.loc, user, "refused tucking preserves actual inventory containment")
	TEST_ASSERT_EQUAL(user.get_active_hand(), mask, "refused tucking preserves the exact source hand")
	TEST_ASSERT_NULL(gaiter.breathmask(), "refused release records no tucked mask relation")
	TEST_ASSERT(!gaiter.breath_masked, "refused release leaves the mask-presence flag clear")
	TEST_ASSERT_EQUAL(gaiter.item_flags, original_flags, "refused release preserves every original gaiter material flag")
	remove_trait(mask, TRAIT_NODROP, "interim_gaiter_sticky_mask")
	test_op_handler(gaiter, "gaiter_tuck_mask_item", user, mask)
	TEST_ASSERT_EQUAL(gaiter.breathmask(), mask, "allowed tucking records the exact original breath mask")
	TEST_ASSERT_EQUAL(mask.loc, gaiter, "allowed tucking physically contains the original mask")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed tucking clears the actual source hand")
	TEST_ASSERT(gaiter.breath_masked, "allowed tucking sets the actual mask-presence flag")
	TEST_ASSERT(!(gaiter.item_flags & FLEXIBLEMATERIAL), "the actual tucked mask removes gaiter flexibility")
	test_op_handler(gaiter, "gaiter_adjust_self", user, null)
	TEST_ASSERT(gaiter.item_flags & AIRTIGHT, "the actual adjustment secures the tucked mask into an airtight gaiter")
	test_op_handler(gaiter, "gaiter_remove_mask_alt", user, null)
	TEST_ASSERT_EQUAL(mask.loc, T, "the actual removal action returns the original mask to the floor")
	TEST_ASSERT_NULL(gaiter.breathmask(), "actual removal clears the tucked mask relation")
	TEST_ASSERT(!gaiter.breath_masked, "actual removal clears the mask-presence flag")
	TEST_ASSERT(gaiter.item_flags & FLEXIBLEMATERIAL, "actual removal restores gaiter flexibility")
	TEST_ASSERT(!(gaiter.item_flags & AIRTIGHT), "actual removal clears mask-provided airtightness")
	qdel(gaiter)
	TEST_ASSERT(!QDELETED(mask), "empty gaiter teardown preserves the returned original mask")
	TEST_ASSERT_EQUAL(mask.loc, T, "empty gaiter teardown preserves the returned mask's actual floor location")
