/// Actual granted action viewers drive real hover relations and owned landing generation.
/datum/unit_test/interim_action_button_drag_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/other = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	var/datum/hud/other_hud = allocate(/datum/hud, other)
	hud.build_action_groups()
	other_hud.build_action_groups()
	var/obj/item/flashlight/light = allocate(/obj/item/flashlight, T)
	var/datum/action/item_action/toggle_flashlight/action = allocate(/datum/action/item_action/toggle_flashlight, light)
	action.Grant(actor)
	var/atom/movable/screen/movable/action_button/button = action.button_for(hud)
	TEST_ASSERT_NOTNULL(button, "actual action grant creates its real viewer button")
	TEST_ASSERT(button.can_use(actor), "the actual granted viewer passes the existing authorization predicate")
	TEST_ASSERT(!button.can_use(other), "an unrelated real HUD fails existing viewer authorization")
	TEST_ASSERT_NULL(hud.listed_actions.landing, "actual listed group begins without a drag landing")
	TEST_ASSERT_NULL(hud.palette_actions.landing, "actual palette group begins without a drag landing")
	button.drag_with_actor(other, hud.toggle_palette, null, null, null)
	TEST_ASSERT_NULL(button.last_hovored, "unrelated viewer cannot change the actual hover relation")
	TEST_ASSERT_NULL(hud.listed_actions.landing, "unrelated viewer creates no actual owner landing")
	button.drag_with_actor(actor, hud.toggle_palette, null, null, null)
	TEST_ASSERT_EQUAL(button.last_hovored, hud.toggle_palette, "actual drag records its exact hovered palette")
	var/atom/movable/screen/action_landing/listed = hud.listed_actions.landing
	var/atom/movable/screen/action_landing/palette = hud.palette_actions.landing
	TEST_ASSERT_NOTNULL(listed, "actual first drag generates the real listed landing")
	TEST_ASSERT_NOTNULL(palette, "actual first drag generates the real palette landing")
	TEST_ASSERT_EQUAL(owner_of(listed), hud.listed_actions, "listed group really owns its generated landing")
	TEST_ASSERT_EQUAL(owner_of(palette), hud.palette_actions, "palette group really owns its generated landing")
	button.drag_with_actor(actor, hud.toggle_palette, null, null, null)
	TEST_ASSERT_EQUAL(hud.listed_actions.landing, listed, "same-target early return preserves exact landing identity")
	button.drag_with_actor(other, hud.palette_down, null, null, null)
	TEST_ASSERT_EQUAL(button.last_hovored, hud.toggle_palette, "unrelated viewer cannot replace an existing hover target")
	button.drag_with_actor(actor, hud.palette_down, null, null, null)
	TEST_ASSERT_EQUAL(button.last_hovored, hud.palette_down, "actual authorized drag changes to the exact new hovered control")
	button.drag_with_actor(actor, null, null, null, null)
	TEST_ASSERT_NULL(button.last_hovored, "actual drag out clears the real hover relation")
	TEST_ASSERT_NULL(other_hud.listed_actions.landing, "actor drag never generates landings for an unrelated HUD")
	TEST_ASSERT_EQUAL(button.linked_action(), action, "drag preserves the actual granted action link")
	TEST_ASSERT(!light.on, "layout drag does not activate the actual flashlight")
	hud.hide_landings()
	TEST_ASSERT(QDELETED(listed) && QDELETED(palette), "actual HUD cleanup deletes both owned landing objects")
