/// Real organ records are copied into scanner-owned snapshots, replaced on rescan and disposed with the scanner.
/datum/unit_test/interim_autopsy_snapshot_ownership/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/obj/item/autopsy_scanner/scanner = allocate(/obj/item/autopsy_scanner, T)
	var/obj/item/tool/crowbar/tool = allocate(/obj/item/tool/crowbar, T)
	var/obj/item/organ/external/left = patient.get_organ(BP_L_ARM)
	var/obj/item/organ/external/right = patient.get_organ(BP_R_ARM)
	TEST_ASSERT(istype(left) && istype(right) && left != right, "The actual human constructor must supply two distinct real arm organs")
	TEST_ASSERT(left.name != right.name, "The real anatomical names must distinguish the scanner's organ keys")
	var/weapon_name = tool.name
	left.add_autopsy_data(weapon_name, 5)
	var/datum/autopsy_data/original = LAZYACCESS(left.autopsy_data, weapon_name)
	TEST_ASSERT(istype(original), "Actual organ recording must construct a real source record")
	TEST_ASSERT_EQUAL(original.damage, 5, "Actual recording must store the exact supplied damage")
	TEST_ASSERT_EQUAL(original.hits, 1, "Actual recording must store one source hit")
	TEST_ASSERT_EQUAL(owner_of(original), left, "The real organ must own its original record")
	scanner.add_data(left)
	var/datum/autopsy_data_scanner/row = LAZYACCESS(scanner.wdata, weapon_name)
	TEST_ASSERT(istype(row), "Actual scanning must create a real weapon row")
	TEST_ASSERT_EQUAL(owner_of(row), scanner, "The actual scanner must own its weapon row")
	var/datum/autopsy_data/first = LAZYACCESS(row.organs_scanned, left.name)
	TEST_ASSERT(istype(first) && first != original, "Actual scanning must create a distinct snapshot of the source record")
	own(first)
	TEST_ASSERT_EQUAL(owner_of(first), row, "The actual scanner row must own its copied record")
	TEST_ASSERT_EQUAL(first.damage, 5, "The first actual snapshot must preserve exact recorded damage")
	TEST_ASSERT_EQUAL(first.hits, 1, "The first actual snapshot must preserve the source hit count")
	TEST_ASSERT_EQUAL(first.weapon, weapon_name, "The first actual snapshot must preserve its real weapon key")
	TEST_ASSERT_EQUAL(row.organ_names, left.name, "The actual report row must name its original anatomy")
	left.add_autopsy_data(weapon_name, 7)
	TEST_ASSERT_EQUAL(original.damage, 12, "The real source record must accumulate seven additional damage")
	TEST_ASSERT_EQUAL(original.hits, 2, "The real source record must accumulate its second hit")
	TEST_ASSERT_EQUAL(first.damage, 5, "An existing actual snapshot must remain isolated from source recording")
	scanner.add_data(left)
	TEST_ASSERT(QDELETED(first), "Rescanning must dispose of the exact previous owned snapshot")
	var/datum/autopsy_data/latest = LAZYACCESS(row.organs_scanned, left.name)
	TEST_ASSERT(istype(latest) && latest != first && latest != original, "Rescan must create a distinct actual copied identity")
	own(latest)
	TEST_ASSERT_EQUAL(owner_of(latest), row, "Rescan must adopt its replacement snapshot into the same row")
	TEST_ASSERT_EQUAL(latest.damage, 12, "Rescan must copy the exact accumulated source damage")
	TEST_ASSERT_EQUAL(latest.hits, 2, "Rescan must copy the exact accumulated source hit count")
	TEST_ASSERT_EQUAL(row.organ_names, left.name, "Rescan must not duplicate the anatomical report name")
	right.add_autopsy_data(weapon_name, 3)
	var/datum/autopsy_data/right_original = LAZYACCESS(right.autopsy_data, weapon_name)
	scanner.add_data(right)
	var/datum/autopsy_data/right_copy = LAZYACCESS(row.organs_scanned, right.name)
	TEST_ASSERT(istype(right_copy) && right_copy != right_original, "The second real organ must produce its own distinct snapshot")
	own(right_copy)
	TEST_ASSERT_EQUAL(owner_of(right_copy), row, "The same report row must own the second actual snapshot")
	TEST_ASSERT_EQUAL(right_copy.damage, 3, "The second actual snapshot must preserve its independent damage")
	TEST_ASSERT_EQUAL(right_copy.hits, 1, "The second actual snapshot must preserve its independent hit count")
	TEST_ASSERT_EQUAL(length(row.organs_scanned), 2, "The actual report row must contain both original anatomical keys")
	TEST_ASSERT_EQUAL(LAZYACCESS(row.organs_scanned, left.name), latest, "Adding another organ must preserve the exact latest first-organ snapshot")
	TEST_ASSERT(consume(scanner), "Actual public scanner disposal must succeed on the floor")
	TEST_ASSERT(QDELETED(scanner) && QDELETED(row), "Disposal must destroy the exact scanner and its owned report row")
	TEST_ASSERT(QDELETED(latest) && QDELETED(right_copy), "Scanner teardown must dispose of both exact owned snapshots")
	TEST_ASSERT(!QDELETED(original) && !QDELETED(right_original), "Scanner disposal must preserve both original anatomical records")
	TEST_ASSERT_EQUAL(owner_of(original), left, "Disposal must preserve the original first-organ owner")
	TEST_ASSERT_EQUAL(owner_of(right_original), right, "Disposal must preserve the original second-organ owner")
	TEST_ASSERT_EQUAL(original.damage, 12, "Disposal must preserve the accumulated real source damage")
	TEST_ASSERT_EQUAL(right_original.damage, 3, "Disposal must preserve the independent real source damage")
	TEST_ASSERT(!QDELETED(patient) && !QDELETED(tool), "Scanner disposal must preserve the original patient and recording tool")
