/// Observe the supplied actor at the real containment boundary without changing insertion.
/datum/interim_resleever_actor_probe
	var/last_actor_ref
	var/insert_count = 0

/datum/interim_resleever_actor_probe/proc/on_insert(datum/act/check_insert/check)
	SHOULD_NOT_SLEEP(TRUE)
	last_actor_ref = check.actor ? REF(check.actor) : null
	insert_count++
	return HOOK_DECLINE

/datum/unit_test/interim_resleever_actor_roundtrip/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/transhuman/resleever/pod = allocate(/obj/machinery/transhuman/resleever, T)
	var/datum/interim_resleever_actor_probe/probe = allocate(/datum/interim_resleever_actor_probe)
	observe(pod, /datum/act/check_insert, probe, instead(then(TYPE_PROC_REF(/datum/interim_resleever_actor_probe, on_insert))))
	TEST_ASSERT_EQUAL(test_op_handler(pod, "resleever_interaction_drag", actor, patient), OP_OK, "Dragging the patient through the public interaction must succeed")
	TEST_ASSERT_EQUAL(probe.last_actor_ref, REF(actor), "The drag initiator must reach the real insertion boundary")
	TEST_ASSERT_EQUAL(probe.insert_count, 1, "The successful drag must attempt exactly one insertion")
	TEST_ASSERT_EQUAL(pod.get_occupant(), patient, "The machine must record the inserted patient")
	TEST_ASSERT_EQUAL(pod.slot_item(OCCUPANT_SLOT_RESLEEVER), patient, "The real slot must contain the patient")
	TEST_ASSERT_EQUAL(patient.loc, pod, "The patient must be inside the machine")
	TEST_ASSERT_EQUAL(pod.icon_state, "implantchair_on", "Successful insertion must select occupied presentation")
	TEST_ASSERT(!pod.put_mob(actor, actor), "An occupied machine must refuse a second patient")
	TEST_ASSERT_EQUAL(probe.insert_count, 1, "Occupied refusal must never enter the containment transaction")
	TEST_ASSERT_EQUAL(pod.get_occupant(), patient, "Refused insertion must preserve the original occupant")
	pod.go_out()
	TEST_ASSERT_NULL(pod.get_occupant(), "Ejection must clear the recorded occupant")
	TEST_ASSERT_NULL(pod.slot_item(OCCUPANT_SLOT_RESLEEVER), "Ejection must clear the actual occupant slot")
	TEST_ASSERT_EQUAL(patient.loc, T, "Ejection must return the patient to the floor")
	dq_machine_clear(pod)
	TEST_ASSERT(pod.operable(), "The self-entry fixture must be operable")
	test_op_handler(pod, "resleever_verb_move_inside", actor)
	TEST_ASSERT_EQUAL(probe.last_actor_ref, REF(actor), "Self-entry must forward its actor to the insertion boundary")
	TEST_ASSERT_EQUAL(probe.insert_count, 2, "Self-entry must run a fresh actual insertion")
	TEST_ASSERT_EQUAL(pod.get_occupant(), actor, "Self-entry must seat the initiating actor")
	TEST_ASSERT_EQUAL(actor.loc, pod, "Self-entry must actually move the actor into the machine")
	pod.go_out()

/// The real drag refuses a carrier with a rider before attempting any containment transaction.
/datum/unit_test/interim_resleever_attached_passenger_refusal/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/rider = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/transhuman/resleever/pod = allocate(/obj/machinery/transhuman/resleever, T)
	var/datum/interim_resleever_actor_probe/probe = allocate(/datum/interim_resleever_actor_probe)
	observe(pod, /datum/act/check_insert, probe, instead(then(TYPE_PROC_REF(/datum/interim_resleever_actor_probe, on_insert))))
	dq_machine_clear(pod)
	TEST_ASSERT(patient.buckle_link(rider), "setup: the patient carries a real linked rider")
	TEST_ASSERT(patient.has_buckled_mobs(), "setup: the riding relation is present")
	var/datum/op_result/refused = test_drag(actor, patient, pod)
	TEST_ASSERT_EQUAL(refused?.outcome, ACT_REFUSED, "Dragging a patient with a rider must be refused by the actual op")
	TEST_ASSERT_EQUAL(reason_text(refused?.reason), "[patient] has other entities attached to it; remove them first", "The refusal must preserve the attached-entities explanation")
	TEST_ASSERT_EQUAL(probe.insert_count, 0, "The refusal must happen before the real containment transaction")
	TEST_ASSERT_NULL(pod.get_occupant(), "The refused drag must leave the pod empty")
	TEST_ASSERT_NULL(pod.slot_item(OCCUPANT_SLOT_RESLEEVER), "The refused drag must not claim the physical slot")
	TEST_ASSERT_EQUAL(patient.loc, T, "The patient must stay outside the pod")
	TEST_ASSERT_EQUAL(rider.buckled_to(), patient, "The refused drag must preserve the actual rider relation")
	TEST_ASSERT_EQUAL(patient.unbuckle_mob(rider, force = TRUE), rider, "Removing the rider must release the real relation")
	var/datum/op_result/allowed = test_drag(actor, patient, pod)
	TEST_ASSERT_EQUAL(allowed?.outcome, ACT_COMMITTED, "The same real drag must succeed once the rider is removed")
	TEST_ASSERT_EQUAL(probe.insert_count, 1, "The allowed drag must run one real containment transaction")
	TEST_ASSERT_EQUAL(probe.last_actor_ref, REF(actor), "The allowed drag must forward its initiating actor")
	TEST_ASSERT_EQUAL(pod.slot_item(OCCUPANT_SLOT_RESLEEVER), patient, "The allowed drag must actually fill the pod slot")
	TEST_ASSERT_EQUAL(patient.loc, pod, "The allowed drag must move the patient into the pod")
	pod.go_out()
	TEST_ASSERT_NULL(pod.get_occupant(), "Ejection must clear the pod after recovery")
	TEST_ASSERT_EQUAL(patient.loc, T, "Ejection must return the patient to the floor")
