/// Player loading must respect release before the actual floorlayer sorts distinct tile materials.
/datum/unit_test/interim_floorlayer_sticky_distinct_tile/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/floorlayer/device = allocate(/obj/machinery/floorlayer, T)
	device.latent_materialize_all()
	var/obj/item/stack/tile/floor/original_tiles = locate_within(device, /obj/item/stack/tile/floor)
	TEST_ASSERT_NOTNULL(original_tiles, "the real device materializes its actual default floor tiles")
	var/original_amount = original_tiles.get_amount()
	var/obj/item/stack/tile/wood/tiles = allocate(/obj/item/stack/tile/wood, T, 3)
	TEST_ASSERT_EQUAL(tiles.get_amount(), 3, "the actual held wood tile stack has three units")
	TEST_ASSERT(tiles.get_amount() <= tiles.get_max_amount() - tiles.get_amount(), "the actual partial stack exposes destructive self-transfer without the exclusion")
	TEST_ASSERT(tiles.stacktype != original_tiles.stacktype, "actual floor and wood stacks have distinct merge types")
	TEST_ASSERT(user.put_in_active_hand(tiles), "the actor holds the exact original distinct tile stack")
	add_trait(tiles, TRAIT_NODROP, "interim_floorlayer_sticky")
	TEST_ASSERT(user.release_refusal(tiles, user), "actual inventory refuses sticky tile release")
	test_op_handler(device, "interaction_load_tile", user, tiles)
	TEST_ASSERT_EQUAL(user.get_active_hand(), tiles, "refused loading preserves exact original source hand")
	TEST_ASSERT_EQUAL(tiles.loc, user, "refused loading preserves inventory containment")
	TEST_ASSERT_EQUAL(tiles.get_amount(), 3, "refused loading consumes no held tile material")
	TEST_ASSERT_EQUAL(original_tiles.get_amount(), original_amount, "refused loading preserves existing floor tile material")
	TEST_ASSERT_NULL(locate_within(device, /obj/item/stack/tile/wood), "refused loading records no wood tile stack inside")
	remove_trait(tiles, TRAIT_NODROP, "interim_floorlayer_sticky")
	test_op_handler(device, "interaction_load_tile", user, tiles)
	TEST_ASSERT_EQUAL(locate_within(device, /obj/item/stack/tile/wood), tiles, "actual sorting retains the exact original distinct-material stack")
	TEST_ASSERT_EQUAL(tiles.loc, device, "allowed loading physically contains original wood tiles")
	TEST_ASSERT_EQUAL(tiles.get_amount(), 3, "allowed sorting conserves all three distinct-material tile units")
	TEST_ASSERT(!QDELETED(tiles), "actual sorting must not consume the original wood stack by merging it into itself")
	TEST_ASSERT(!QDELETED(original_tiles), "actual sorting preserves the original default floor stack")
	TEST_ASSERT_EQUAL(original_tiles.get_amount(), original_amount, "allowed sorting preserves all original floor tile units")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed loading clears actual source hand")
	TEST_ASSERT_NULL(owner_of(tiles), "loading a second distinct stack preserves the original unowned extra-stack policy")
