/// The real open-panel laser upgrade must consume its original component before increasing blast power.
/datum/unit_test/interim_seismic_charge_sticky_laser/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/plastique/seismic/charge = allocate(/obj/item/plastique/seismic, T)
	var/obj/item/tool/screwdriver/tool = allocate(/obj/item/tool/screwdriver, T)
	var/obj/item/stock_parts/micro_laser/laser = allocate(/obj/item/stock_parts/micro_laser, T)
	TEST_ASSERT(!charge.open_panel, "actual seismic charge starts with a closed panel")
	TEST_ASSERT_EQUAL(charge.blast_heavy, 2, "actual seismic charge starts at heavy blast power two")
	TEST_ASSERT_EQUAL(laser.rating, 1, "actual unimbued laser starts at the original component rating")
	TEST_ASSERT(user.put_in_active_hand(tool), "actor holds the canonical screwdriver")
	test_op_handler(charge, "screwdriver_used", user, tool)
	TEST_ASSERT(charge.open_panel, "actual screwdriver action opens the charge panel")
	TEST_ASSERT(user.unEquip(tool, T), "actor legitimately releases original screwdriver")
	TEST_ASSERT(user.put_in_active_hand(laser), "actor holds exact original laser")
	var/base_heavy = charge.blast_heavy
	var/base_light = charge.blast_light
	var/base_flash = charge.blast_flash
	add_trait(laser, TRAIT_NODROP, "interim_seismic_laser")
	TEST_ASSERT(user.release_refusal(laser, user), "actual inventory refuses sticky original laser")
	test_op_handler(charge, "interaction_item", user, laser)
	TEST_ASSERT_EQUAL(charge.blast_heavy, base_heavy, "refused consumption grants no heavy blast upgrade")
	TEST_ASSERT_EQUAL(charge.blast_light, base_light, "refused consumption grants no light blast upgrade")
	TEST_ASSERT_EQUAL(charge.blast_flash, base_flash, "refused consumption grants no flash upgrade")
	TEST_ASSERT(!QDELETED(laser), "refused consumption preserves original laser alive")
	TEST_ASSERT_EQUAL(user.get_active_hand(), laser, "refused consumption preserves exact original hand")
	TEST_ASSERT_EQUAL(laser.loc, user, "refused consumption preserves inventory location")
	remove_trait(laser, TRAIT_NODROP, "interim_seismic_laser")
	test_op_handler(charge, "interaction_item", user, laser)
	TEST_ASSERT(QDELETED(laser), "allowed upgrade consumes exact original laser")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed upgrade clears actual source hand")
	TEST_ASSERT_EQUAL(charge.blast_heavy, 3, "actual original rating-one laser raises heavy power to three")
	TEST_ASSERT_EQUAL(charge.blast_light, 4, "actual upgraded light blast power follows existing formula")
	TEST_ASSERT_EQUAL(charge.blast_flash, 6, "actual upgraded flash power follows existing formula")
	var/obj/item/stock_parts/micro_laser/replacement = allocate(/obj/item/stock_parts/micro_laser, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "actor holds a second original rating-one laser")
	test_op_handler(charge, "interaction_item", user, replacement)
	TEST_ASSERT(!QDELETED(replacement), "non-improving component remains alive")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "non-improving refusal preserves exact second original hand")
	TEST_ASSERT_EQUAL(charge.blast_heavy, 3, "non-improving refusal preserves installed heavy blast power")
