/// A real debug printer receives paper only after its original sheet is consumed.
/datum/unit_test/interim_drone_circuit_sticky_printer_paper/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/poi/broken_drone_circuit/circuit = allocate(/obj/item/poi/broken_drone_circuit, T)
	var/obj/item/tool/screwdriver/tool = allocate(/obj/item/tool/screwdriver, T)
	TEST_ASSERT(!circuit.unscrewed && !circuit.has_paper && !circuit.fried, "actual initialized circuit starts closed, empty and workable")
	TEST_ASSERT(user.put_in_active_hand(tool), "actor holds the actual screwdriver")
	test_op_handler(circuit, "interaction_item", user, tool)
	TEST_ASSERT(circuit.unscrewed, "actual screwdriver interaction opens the debug printer panel")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "opening preserves original screwdriver")
	TEST_ASSERT(user.unEquip(tool, T), "actor legitimately releases screwdriver before loading paper")
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	TEST_ASSERT(user.put_in_active_hand(paper), "actor holds exact original printer sheet")
	add_trait(paper, TRAIT_NODROP, "interim_drone_printer")
	TEST_ASSERT(user.release_refusal(paper, user), "real inventory refuses sticky original sheet")
	test_op_handler(circuit, "interaction_item", user, paper)
	TEST_ASSERT(!circuit.has_paper, "refused consumption grants no printer sheet")
	TEST_ASSERT(!QDELETED(paper), "refused consumption preserves original sheet alive")
	TEST_ASSERT_EQUAL(user.get_active_hand(), paper, "refused consumption preserves exact original hand")
	TEST_ASSERT_EQUAL(paper.loc, user, "refused consumption preserves original inventory location")
	remove_trait(paper, TRAIT_NODROP, "interim_drone_printer")
	test_op_handler(circuit, "interaction_item", user, paper)
	TEST_ASSERT(QDELETED(paper), "allowed loading consumes exact original sheet")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed loading clears original source hand")
	TEST_ASSERT(circuit.has_paper && circuit.unscrewed && !circuit.fried, "allowed loading supplies exactly the printer while preserving open workable circuit")
	var/obj/item/paper/replacement = allocate(/obj/item/paper, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "actor holds a second actual original sheet")
	test_op_handler(circuit, "interaction_item", user, replacement)
	TEST_ASSERT(!QDELETED(replacement), "occupied printer refuses consumption of another sheet")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "occupied printer preserves exact second original hand")
	TEST_ASSERT_EQUAL(replacement.loc, user, "occupied printer preserves second inventory location")
	TEST_ASSERT(circuit.has_paper, "occupied refusal preserves existing printer supply")
