/// Player self-feeding delivers the configured dose to ingestion rather than the bloodstream.
/datum/unit_test/interim_standard_feed_dose/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/glass/beaker/source = allocate(/obj/item/reagent_containers/glass/beaker, T)
	var/obj/item/clothing/mask/gas/mask = allocate(/obj/item/clothing/mask/gas, T)
	source.amount_per_transfer_from_this = 7
	source.reagents.add_reagent(REAGENT_ID_WATER, 10)
	var/blood_before = actor.reagents.get_reagent_amount(REAGENT_ID_WATER)
	var/ingested_before = actor.ingested.get_reagent_amount(REAGENT_ID_WATER)
	TEST_ASSERT(mask.move_into(actor, SLOT_ID_MASK), "the actor wears a real mouth-covering mask")
	TEST_ASSERT_NOTNULL(mouth_blocked_reason(actor, actor), "the fixture actually blocks feeding")
	TEST_ASSERT(!source.standard_feed_mob(actor, actor), "feeding through the covering mask refuses")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 10, "the refusal leaves the source dose intact")
	TEST_ASSERT_EQUAL(actor.ingested.get_reagent_amount(REAGENT_ID_WATER), ingested_before, "the refusal delivers no swallowed water")
	actor.drop_from_inventory(mask)
	TEST_ASSERT_NULL(mouth_blocked_reason(actor, actor), "removing the mask opens the mouth")
	TEST_ASSERT(source.standard_feed_mob(actor, actor), "the actual self-feed helper handles a drink")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 3, "feeding debits the configured seven-unit dose")
	TEST_ASSERT_EQUAL(actor.ingested.get_reagent_amount(REAGENT_ID_WATER), ingested_before + 7, "the configured dose reaches ingestion")
	TEST_ASSERT_EQUAL(actor.reagents.get_reagent_amount(REAGENT_ID_WATER), blood_before, "feeding does not inject the dose into blood")
	TEST_ASSERT(source.standard_feed_mob(actor, actor), "a second drink handles the remaining partial dose")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 0, "the partial drink empties the source")
	TEST_ASSERT_EQUAL(actor.ingested.get_reagent_amount(REAGENT_ID_WATER), ingested_before + 10, "the full original dose is conserved across both drinks")
	TEST_ASSERT(source.standard_feed_mob(actor, actor), "an empty source is handled as a refusal")
	TEST_ASSERT_EQUAL(actor.ingested.get_reagent_amount(REAGENT_ID_WATER), ingested_before + 10, "the empty refusal delivers no additional water")
