/datum/unit_test/interim_holobadge_credentials/Run()
	test_driver_begin()
	run_credentials()
	test_driver_end()

/datum/unit_test/interim_holobadge_credentials/proc/run_credentials()
	var/turf/floor = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, floor)
	var/obj/item/clothing/accessory/badge/holo/badge = allocate(/obj/item/clothing/accessory/badge/holo, floor)
	var/obj/item/pda/pda = allocate(/obj/item/pda, floor)
	TEST_ASSERT_NULL(pda.id, "Actual new PDA starts without credentials")
	TEST_ASSERT(actor.put_in_active_hand(pda), "Actor holds the real empty PDA")
	test_click(actor, badge, pda)
	TEST_ASSERT_NULL(badge.stored_name, "Empty PDA refuses imprinting without a runtime or state change")
	TEST_ASSERT_EQUAL(badge.name, initial(badge.name), "Missing credentials preserve actual badge name")
	TEST_ASSERT(actor.drop_from_inventory(pda, floor), "Actor releases the real PDA")
	var/obj/item/card/id/card = allocate(/obj/item/card/id, floor)
	TEST_ASSERT(actor.put_in_active_hand(card), "Actor holds a real ID card")
	test_click(actor, badge, card)
	TEST_ASSERT_NULL(badge.stored_name, "Actual ID without security access is refused")
	LAZYADD(card.access, ACCESS_SECURITY)
	TEST_ASSERT(ACCESS_SECURITY in card.GetAccess(), "Real card supplies security access through its public getter")
	test_click(actor, badge, card)
	TEST_ASSERT_EQUAL(badge.stored_name, actor.real_name, "Real security ID imprints the actual actor's name")
	TEST_ASSERT_EQUAL(badge.name, "[initial(badge.name)] ([actor.real_name])", "Accepted imprint changes the actual visible badge name")
	TEST_ASSERT(actor.drop_from_inventory(card, floor), "Actor releases the real ID")
	var/obj/item/clothing/accessory/badge/holo/cracked = allocate(/obj/item/clothing/accessory/badge/holo, floor)
	var/obj/item/card/emag/emag = allocate(/obj/item/card/emag, floor)
	TEST_ASSERT(actor.put_in_active_hand(emag), "Actor holds the real emag")
	var/old_uses = emag.uses
	test_click(actor, cracked, emag)
	TEST_ASSERT(cracked.emagged, "Actual emag click cracks the badge's access check")
	TEST_ASSERT_EQUAL(emag.uses, old_uses - 1, "Successful real emag pays its charge")
	TEST_ASSERT(actor.drop_from_inventory(emag, floor), "Actor releases the emag")
	TEST_ASSERT(actor.put_in_active_hand(pda), "Actor holds the empty PDA again")
	test_click(actor, cracked, pda)
	TEST_ASSERT_NULL(cracked.stored_name, "Emagged badge still needs an actual ID rather than accepting an empty PDA")
	TEST_ASSERT(actor.drop_from_inventory(pda, floor), "Actor releases the PDA")
	LAZYREMOVE(card.access, ACCESS_SECURITY)
	TEST_ASSERT(actor.put_in_active_hand(card), "Actor holds the now-unprivileged real ID")
	test_click(actor, cracked, card)
	TEST_ASSERT_EQUAL(cracked.stored_name, actor.real_name, "Emagged badge accepts an actual ID with insufficient security access")
