/datum/unit_test/interim_hailer_mask_recovery/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/tool/crowbar/crowbar = allocate(/obj/item/tool/crowbar, T)
	TEST_ASSERT(actor.put_in_active_hand(crowbar), "The real actor holds its original mask recovery tool")
	var/obj/item/clothing/mask/gas/sechailer/integrated = allocate(/obj/item/clothing/mask/gas/sechailer, T)
	TEST_ASSERT_NULL(integrated.hailer(), "The actual integrated mask starts without a removable hailer")
	TEST_ASSERT_EQUAL(integrated.crowbar_act(actor, crowbar), ITEM_INTERACT_BLOCKING, "The actual integrated mask refuses hailer removal")
	TEST_ASSERT(!QDELETED(integrated) && integrated.loc == T, "Actual integrated refusal preserves its exact original source")
	var/obj/item/clothing/mask/gas/half/shell = allocate(/obj/item/clothing/mask/gas/half, T)
	var/obj/item/hailer/hailer = allocate(/obj/item/hailer, T)
	var/datum/forensics_crime/evidence = shell.init_forensic_data()
	TEST_ASSERT(evidence.add_prints(actor), "The actual original shell receives real fingerprint evidence")
	var/list/prints = evidence.get_prints().Copy()
	TEST_ASSERT(length(prints), "The actual source fingerprint evidence is nonempty")
	test_op_handler(shell, "half_mask_add_hailer_item", actor, hailer)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(shell), "Actual hailer installation consumes the original shell")
	var/obj/item/clothing/mask/gas/sechailer/source
	for(var/obj/item/clothing/mask/gas/sechailer/candidate in contents_of(T))
		if(candidate.hailer() == hailer)
			source = candidate
	TEST_ASSERT_NOTNULL(source, "Actual installation creates the real mask containing the exact original hailer")
	TEST_ASSERT_EQUAL(hailer.loc, source, "The exact original hailer is physically installed in the real source")
	var/list/before = turf_contents_of_type(T, /obj/item/clothing/mask/gas/half)
	TEST_ASSERT(actor.put_in_hands(source), "The actor actually holds the original upgraded source beside its recovery tool")
	var/source_hand = actor.inventory_slot_id(source)
	TEST_ASSERT(source_hand, "The actual upgraded source occupies a real inventory slot")
	add_trait(source, TRAIT_NODROP, "interim_hailer_mask_recovery")
	TEST_ASSERT(source.loc.release_refusal(source, actor), "The actual sticky upgraded source refuses removal")
	TEST_ASSERT_EQUAL(source.crowbar_act(actor, crowbar), ITEM_INTERACT_BLOCKING, "Actual crowbar recovery refuses the sticky source before creating replacement products")
	TEST_ASSERT(!QDELETED(source) && source.loc == actor, "Actual sticky refusal preserves the exact original held mask")
	TEST_ASSERT_EQUAL(actor.get_equipped_item(source_hand), source, "Actual sticky refusal preserves the original occupied source slot")
	TEST_ASSERT_EQUAL(source.hailer(), hailer, "Actual sticky refusal preserves the exact installed hailer link")
	TEST_ASSERT(!QDELETED(hailer) && hailer.loc == source, "Actual sticky refusal preserves original hailer containment")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(T, /obj/item/clothing/mask/gas/half) - before), 0, "Actual sticky refusal produces no free replacement mask on the floor")
	TEST_ASSERT_NULL(locate_within(actor, /obj/item/clothing/mask/gas/half), "Actual sticky refusal produces no free replacement mask in the actor")
	remove_trait(source, TRAIT_NODROP, "interim_hailer_mask_recovery")
	TEST_ASSERT(actor.drop_from_inventory(source, T), "The real unblocked source returns to its original floor for recovery")
	TEST_ASSERT_EQUAL(source.crowbar_act(actor, crowbar), ITEM_INTERACT_SUCCESS, "The actual crowbar removes the original installed hailer")
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(source), "Actual recovery consumes the exact original upgraded mask")
	TEST_ASSERT(!QDELETED(hailer) && hailer.loc == T, "Actual recovery returns the exact original hailer alive on the source floor")
	var/list/products = turf_contents_of_type(T, /obj/item/clothing/mask/gas/half) - before
	TEST_ASSERT_EQUAL(length(products), 1, "Actual removal creates exactly one real replacement half mask")
	var/obj/item/clothing/mask/gas/half/product = products[1]
	TEST_ASSERT_EQUAL(product.type, /obj/item/clothing/mask/gas/half, "The actual recovery retains the canonical half-mask type")
	TEST_ASSERT(!QDELETED(product) && product.loc == T, "The actual replacement mask remains alive on the original floor")
	var/list/transferred = product.forensic_data?.get_prints()
	TEST_ASSERT_EQUAL(length(transferred), length(prints), "Actual removal retains the original nonempty fingerprint count")
	for(var/print in prints)
		TEST_ASSERT_EQUAL(transferred?[print], prints[print], "Actual removal retains each exact original fingerprint")
	TEST_ASSERT(!QDELETED(integrated) && integrated.loc == T, "Actual removal preserves the unrelated original integrated mask")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), crowbar, "Actual mask removal preserves the exact original held crowbar")
