/// The actual one-use transmitter must consume its original before deploying its beacon.
/datum/unit_test/interim_singularity_beacon_sticky_deployment/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/radio/beacon/syndicate/transmitter = allocate(/obj/item/radio/beacon/syndicate, T)
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/power/singularity_beacon/syndicate)), 0, "actual fixture starts without deployed beacons")
	TEST_ASSERT(user.put_in_active_hand(transmitter), "the actor holds exact original transmitter")
	add_trait(transmitter, TRAIT_NODROP, "interim_singularity_transmitter")
	TEST_ASSERT(user.release_refusal(transmitter, user), "actual inventory refuses sticky transmitter consumption")
	transmitter.interaction_self(user, transmitter, null)
	TEST_ASSERT(!QDELETED(transmitter), "refused deployment preserves exact original transmitter")
	TEST_ASSERT_EQUAL(user.get_active_hand(), transmitter, "refused deployment preserves original source hand")
	TEST_ASSERT_EQUAL(transmitter.loc, user, "refused deployment preserves inventory containment")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/power/singularity_beacon/syndicate)), 0, "refused consumption creates no deployed beacon")
	remove_trait(transmitter, TRAIT_NODROP, "interim_singularity_transmitter")
	transmitter.interaction_self(user, transmitter, null)
	TEST_ASSERT(QDELETED(transmitter), "allowed deployment consumes exact original transmitter")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/power/singularity_beacon/syndicate)), 1, "one consumed original produces exactly one physical beacon")
	var/obj/machinery/power/singularity_beacon/syndicate/beacon = locate_within(T, /obj/machinery/power/singularity_beacon/syndicate)
	TEST_ASSERT_NOTNULL(beacon, "allowed deployment creates a real surviving beacon")
	own(beacon)
	TEST_ASSERT_EQUAL(beacon.type, /obj/machinery/power/singularity_beacon/syndicate, "actual product has exact declared beacon type")
	TEST_ASSERT_EQUAL(beacon.loc, T, "actual product occupies original actor turf")
	TEST_ASSERT(!QDELETED(beacon), "actual product survives initialization")
