/// A real native refill click preserves the tap mixture when only fractional constituent amounts fit, and closed/full receivers debit nothing.
/datum/unit_test/interim_native_tap_mixed_capacity_dose
	parent_type = /datum/unit_test/dq_p2_reagents

/datum/unit_test/interim_native_tap_mixed_capacity_dose/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = rc_actor(T)
	var/obj/structure/reagent_dispensers/watertank/tank = allocate(/obj/structure/reagent_dispensers/watertank, T)
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	tank.reagents.clear_reagents()
	tank.reagents.add_reagent(REAGENT_ID_NUTRIMENT, 10)
	tank.reagents.add_reagent(REAGENT_ID_SUGAR, 10)
	TEST_ASSERT_EQUAL(tank.reagents.total_volume, 20, "the actual tap fixture contains the configured twenty-unit mixture")
	TEST_ASSERT_EQUAL(tank.amount_per_transfer_from_this, 10, "the actual tap's declared refill dose is ten units")
	TEST_ASSERT(beaker.reagents.maximum_volume > 3, "the actual beaker can have a three-unit capacity remainder")
	var/existing_water = beaker.reagents.maximum_volume - 3
	beaker.reagents.add_reagent(REAGENT_ID_WATER, existing_water)
	rc_set_amount_menu(user, beaker, 7)
	TEST_ASSERT_EQUAL(rc_amount(beaker), 7, "the actual beaker's amount menu sets a distinct seven-unit pour dose")
	var/original_total = tank.reagents.total_volume + beaker.reagents.total_volume
	rc_click(user, tank, beaker)
	TEST_ASSERT(abs(beaker.reagents.total_volume - beaker.reagents.maximum_volume) < 0.001, "actual native refill fills only the three-unit remaining capacity")
	TEST_ASSERT(abs(beaker.reagents.get_reagent_amount(REAGENT_ID_NUTRIMENT) - 1.5) < 0.001, "actual capacity-limited refill delivers the mixture's nutriment fraction")
	TEST_ASSERT(abs(beaker.reagents.get_reagent_amount(REAGENT_ID_SUGAR) - 1.5) < 0.001, "actual capacity-limited refill delivers the mixture's sugar fraction")
	TEST_ASSERT(abs(beaker.reagents.get_reagent_amount(REAGENT_ID_WATER) - existing_water) < 0.001, "actual refill preserves the receiver's independent existing water")
	TEST_ASSERT(abs(tank.reagents.get_reagent_amount(REAGENT_ID_NUTRIMENT) - 8.5) < 0.001, "the actual tap retains its undelivered nutriment")
	TEST_ASSERT(abs(tank.reagents.get_reagent_amount(REAGENT_ID_SUGAR) - 8.5) < 0.001, "the actual tap retains its undelivered sugar")
	TEST_ASSERT(abs(tank.reagents.total_volume + beaker.reagents.total_volume - original_total) < 0.001, "actual capacity-limited native transfer conserves both original holders' total liquid")
	rc_click(user, tank, beaker)
	TEST_ASSERT(abs(tank.reagents.total_volume - 17) < 0.001, "actual full-beaker refusal debits no tap mixture")
	TEST_ASSERT(abs(beaker.reagents.get_reagent_amount(REAGENT_ID_NUTRIMENT) - 1.5) < 0.001, "actual full-beaker refusal changes no delivered fraction")
	beaker.reagents.clear_reagents()
	rc_use(user, beaker)
	TEST_ASSERT(!rc_open(beaker), "actual use-in-hand closes the emptied receiver's lid")
	rc_click(user, tank, beaker)
	TEST_ASSERT(abs(tank.reagents.total_volume - 17) < 0.001, "actual closed-receiver refusal debits no source mixture despite free capacity")
	TEST_ASSERT_EQUAL(beaker.reagents.total_volume, 0, "actual closed-receiver refusal delivers no liquid")
	rc_use(user, beaker)
	TEST_ASSERT(rc_open(beaker), "actual use-in-hand reopens the same original receiver")
	rc_click(user, tank, beaker)
	TEST_ASSERT(abs(beaker.reagents.total_volume - 10) < 0.001, "actual native refill uses the original tap's ten-unit dose rather than the receiver's seven")
	TEST_ASSERT(abs(beaker.reagents.get_reagent_amount(REAGENT_ID_NUTRIMENT) - 5) < 0.001, "actual full refill preserves the original nutriment fraction")
	TEST_ASSERT(abs(beaker.reagents.get_reagent_amount(REAGENT_ID_SUGAR) - 5) < 0.001, "actual full refill preserves the original sugar fraction")
	TEST_ASSERT(abs(tank.reagents.total_volume - 7) < 0.001, "actual full refill retains the exact remaining source mixture")
	TEST_ASSERT(abs(tank.reagents.get_reagent_amount(REAGENT_ID_NUTRIMENT) - 3.5) < 0.001, "the original tap retains its exact remaining nutriment fraction")
	TEST_ASSERT(abs(tank.reagents.get_reagent_amount(REAGENT_ID_SUGAR) - 3.5) < 0.001, "the original tap retains its exact remaining sugar fraction")
	TEST_ASSERT_EQUAL(user.get_active_hand(), beaker, "all real refill and lid clicks preserve the original receiver's held identity")
