/// Actual money-jar insertion respects release and returns the same original physical cash.
/datum/unit_test/interim_glass_jar_sticky_money/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/glass_jar/jar = allocate(/obj/item/glass_jar, T)
	var/obj/item/spacecash/c5/cash = allocate(/obj/item/spacecash/c5, T)
	TEST_ASSERT_EQUAL(contents_count(jar), 0, "actual initialized money jar starts empty")
	var/empty_state = jar.contains
	TEST_ASSERT_EQUAL(cash.worth, 5, "actual original banknote has its declared five-thaler value")
	TEST_ASSERT(user.put_in_active_hand(cash), "actor holds exact original banknote")
	add_trait(cash, TRAIT_NODROP, "interim_glass_jar_cash")
	TEST_ASSERT(user.release_refusal(cash, user), "actual inventory refuses sticky original cash")
	test_op_handler(jar, "interaction_item", user, cash)
	TEST_ASSERT_EQUAL(jar.contains, empty_state, "refused insertion preserves actual empty jar mode")
	TEST_ASSERT_EQUAL(contents_count(jar), 0, "refused insertion transfers no physical cash")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cash, "refused insertion preserves exact original hand")
	TEST_ASSERT_EQUAL(cash.loc, user, "refused insertion preserves inventory containment")
	remove_trait(cash, TRAIT_NODROP, "interim_glass_jar_cash")
	test_op_handler(jar, "interaction_item", user, cash)
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears actual source hand")
	TEST_ASSERT_EQUAL(cash.loc, jar, "allowed insertion contains exact original banknote")
	TEST_ASSERT_EQUAL(contents_count(jar), 1, "allowed insertion contains exactly one banknote")
	TEST_ASSERT_NOTEQUAL(jar.contains, empty_state, "allowed insertion activates actual money contents mode")
	TEST_ASSERT_NULL(owner_of(cash), "money jar preserves its existing unowned physical containment policy")
	test_op_handler(jar, "interaction_self", user)
	TEST_ASSERT(!QDELETED(cash), "actual emptying returns original cash alive")
	TEST_ASSERT_EQUAL(cash.loc, T, "actual emptying returns original cash to actor floor")
	TEST_ASSERT_EQUAL(cash.worth, 5, "actual round trip preserves banknote value")
	TEST_ASSERT_EQUAL(jar.contains, empty_state, "actual emptying restores exact original empty mode")
	TEST_ASSERT_EQUAL(contents_count(jar), 0, "actual emptying leaves no physical cash in jar")
