/// Intentional shattering retains compulsory hand release, exact prepared destination, fingerprints, and rag spill.
/datum/unit_test/interim_bottle_smash_lifecycle/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/destination = run_loc_floor_top_right
	TEST_ASSERT(T != destination, "the prepared successor destination is distinct from the original holder's turf")
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	for(var/sticky in list(FALSE, TRUE))
		var/obj/item/reagent_containers/food/drinks/bottle/small/beer/bottle = allocate(/obj/item/reagent_containers/food/drinks/bottle/small/beer, T)
		var/obj/item/reagent_containers/glass/rag/rag = allocate(/obj/item/reagent_containers/glass/rag, T)
		TEST_ASSERT(own_set(bottle, nameof(bottle.rag), rag, user = user), "the actual bottle owns its physically contained rag")
		TEST_ASSERT_EQUAL(rag.loc, bottle, "the real rag starts inside the original bottle")
		TEST_ASSERT(user.put_in_active_hand(bottle), "the real bottle occupies the actor's hand")
		var/datum/forensics_crime/evidence = bottle.init_forensic_data()
		TEST_ASSERT(evidence.add_prints(user), "the original bottle has real fingerprint evidence")
		var/list/prints = evidence.get_prints().Copy()
		TEST_ASSERT(length(prints), "the fixture contains actual prints to transfer")
		if(sticky)
			add_trait(bottle, TRAIT_NODROP, "interim_bottle_smash")
			TEST_ASSERT(bottle.loc.release_refusal(bottle, user), "the actual sticky bottle refuses ordinary removal")
		var/obj/item/broken_bottle/broken = bottle.smash(destination)
		own_turf_contents(T)
		own_turf_contents(destination)
		TEST_ASSERT(QDELETED(bottle), "intentional shattering destroys the actual original bottle even when sticky")
		TEST_ASSERT(istype(broken), "shattering returns the actual prepared broken bottle")
		TEST_ASSERT_EQUAL(broken.loc, destination, "replacement retains the exact requested destination instead of equipping the broken bottle")
		TEST_ASSERT_NULL(user.get_active_hand(), "the original compulsory drop vacates the actual hand")
		TEST_ASSERT_EQUAL(broken.icon_state, "beer", "the prepared broken bottle keeps its original bottle appearance state")
		var/list/transferred = broken.forensic_data?.get_prints()
		TEST_ASSERT_EQUAL(length(transferred), length(prints), "shattering retains all original print evidence")
		for(var/print in prints)
			TEST_ASSERT_EQUAL(transferred?[print], prints[print], "shattering preserves each actual fingerprint")
		TEST_ASSERT(!QDELETED(rag), "the owned rag survives original bottle teardown")
		TEST_ASSERT_EQUAL(rag.loc, T, "the rag spills at the original bottle's drop turf")
		TEST_ASSERT_NULL(owner_of(rag), "the spilled rag no longer belongs to the destroyed bottle")
