/// Real lit-welder destruction reaches the ordinary spider web death endpoint.
/datum/unit_test/interim_spider_death_cleanup/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/weldingtool/welder = allocate(/obj/item/weldingtool, T)
	var/obj/effect/spider/stickyweb/web = allocate(/obj/effect/spider/stickyweb, T)
	TEST_ASSERT(!QDELETED(web), "actual sticky web initializes alive")
	TEST_ASSERT_EQUAL(web.get_integrity(), web.max_integrity, "actual sticky web starts with full integrity")
	TEST_ASSERT(user.put_in_active_hand(welder), "actual actor holds its real welder")
	TEST_ASSERT(!welder.isOn(), "actual welder starts unlit")
	var/fuel_before = welder.get_fuel()
	TEST_ASSERT_EQUAL(web.welder_act(user, welder), ITEM_INTERACT_BLOCKING, "actual unlit welder refuses web burning")
	TEST_ASSERT(!QDELETED(web), "actual rejected burning preserves the web")
	TEST_ASSERT_EQUAL(web.get_integrity(), web.max_integrity, "actual rejected burning preserves exact integrity")
	welder.interaction_self(user, welder, null)
	TEST_ASSERT(welder.isOn(), "actual self interaction lights the welder")
	TEST_ASSERT_EQUAL(web.welder_act(user, welder), ITEM_INTERACT_SUCCESS, "actual lit welder burns through the web")
	TEST_ASSERT(QDELETED(web), "actual burning consumes the original web")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/effect/spider/stickyweb)), 0, "actual burning leaves no sticky web")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/effect/decal/cleanable/spiderling_remains)), 0, "burning ordinary web produces no spiderling corpse")
	TEST_ASSERT_EQUAL(welder.get_fuel(), fuel_before, "actual zero-cost web welding preserves exact fuel")
	TEST_ASSERT(!QDELETED(user) && !QDELETED(welder), "actual web cleanup preserves actor and welder")
	TEST_ASSERT_EQUAL(user.get_active_hand(), welder, "actual web cleanup preserves the held welder")

/// Actual spiderling integrity destruction preserves its distinct remains side effect.
/datum/unit_test/interim_spider_death_cleanup/spiderling/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/effect/spider/spiderling/spiderling = allocate(/obj/effect/spider/spiderling, T)
	TEST_ASSERT(!QDELETED(spiderling), "actual spiderling initializes alive")
	TEST_ASSERT_EQUAL(spiderling.get_integrity(), spiderling.max_integrity, "actual spiderling starts at full integrity")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/effect/decal/cleanable/spiderling_remains)), 0, "actual fixture begins without spiderling remains")
	spiderling.take_damage(0, BRUTE, MELEE, sound_effect = FALSE)
	TEST_ASSERT(!QDELETED(spiderling), "actual zero damage preserves the spiderling")
	TEST_ASSERT_EQUAL(spiderling.get_integrity(), spiderling.max_integrity, "actual zero damage preserves exact integrity")
	spiderling.take_damage(spiderling.max_integrity * 3, BRUTE, MELEE, sound_effect = FALSE)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(spiderling), "actual lethal damage consumes the original spiderling")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/effect/spider/spiderling)), 0, "actual death leaves no living spiderling effect")
	var/list/products = contents_of(T, /obj/effect/decal/cleanable/spiderling_remains)
	TEST_ASSERT_EQUAL(length(products), 1, "actual spiderling death creates exactly one distinct remains product")
	var/obj/effect/decal/cleanable/spiderling_remains/product = products[1]
	TEST_ASSERT_EQUAL(product.type, /obj/effect/decal/cleanable/spiderling_remains, "actual remains retain their concrete product type")
	TEST_ASSERT_EQUAL(product.loc, T, "actual remains occupy the original spiderling floor")

/// The same death endpoint preserves the cocoon's real OWN_SPILL contents.
/datum/unit_test/interim_spider_death_cleanup/cocoon/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/effect/spider/cocoon/cocoon = allocate(/obj/effect/spider/cocoon, T)
	var/obj/item/pen/content = allocate(/obj/item/pen, cocoon)
	TEST_ASSERT_EQUAL(content.loc, cocoon, "actual cocoon initially contains the original item")
	TEST_ASSERT_EQUAL(cocoon.get_integrity(), cocoon.max_integrity, "actual cocoon begins at full integrity")
	cocoon.take_damage(0, BRUTE, MELEE, sound_effect = FALSE)
	TEST_ASSERT(!QDELETED(cocoon), "actual zero damage preserves its cocoon")
	TEST_ASSERT_EQUAL(content.loc, cocoon, "actual zero damage preserves the contained original item")
	cocoon.take_damage(cocoon.max_integrity * 3, BRUTE, MELEE, sound_effect = FALSE)
	TEST_ASSERT(QDELETED(cocoon), "actual lethal damage consumes its cocoon")
	TEST_ASSERT(!QDELETED(content), "actual cocoon death preserves its original spill item")
	TEST_ASSERT_EQUAL(content.loc, T, "actual cocoon death spills the same original item onto its floor")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/pen)), 1, "actual cocoon death spills exactly the original pen")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/effect/decal/cleanable/spiderling_remains)), 0, "actual cocoon death makes no spiderling corpse")
