/datum/unit_test/om/interim_boulder_excavation_cleanup/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	actor.enable_godmode()
	var/obj/structure/boulder/boulder = allocate(/obj/structure/boulder, T)
	TEST_ASSERT(boulder.excavation_level >= 5 && boulder.excavation_level <= 50, "The real boulder constructor retains its original random excavation range")
	TEST_ASSERT_NULL(boulder.artifact_find(), "The actual unseeded boulder has no artifact find")
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(actor.put_in_active_hand(pen), "The actual actor holds the original unsupported pen")
	var/depth_before = boulder.excavation_level
	TEST_ASSERT_EQUAL(test_op_handler(boulder, "interaction_item", actor, pen), OP_PASS, "The real unsupported item preserves the original interaction result")
	TEST_ASSERT(!QDELETED(boulder) && boulder.loc == T, "The real unsupported item preserves the original boulder")
	TEST_ASSERT_EQUAL(boulder.excavation_level, depth_before, "The real unsupported item does not excavate the boulder")
	TEST_ASSERT(actor.drop_from_inventory(pen), "The actual actor releases its original pen")
	var/obj/item/pickaxe/brush/tool = allocate(/obj/item/pickaxe/brush, T)
	TEST_ASSERT(actor.put_in_active_hand(tool), "The actual actor holds its original archaeological brush")
	TEST_ASSERT_EQUAL(tool.excavation_amount, 1, "The actual archaeological brush retains its canonical excavation amount")
	TEST_ASSERT_EQUAL(tool.digspeed, 2 SECONDS, "The actual archaeological brush retains its canonical two-second wait")
	// Set the public accumulated depth to a real late-excavation state; the actual completion still does its increment and probability check.
	boulder.excavation_level = 100
	TEST_ASSERT_NOTNULL(perform_op(actor, boulder, "dig", tool, ORIGIN_CLICK, AUTH_PHYSICAL), "The real brush dig op starts actual timed excavation")
	scheduler_advance((1.9 SECONDS) / (1 SECOND))
	TEST_ASSERT(!QDELETED(boulder) && boulder.loc == T, "The actual boulder survives before its original excavation deadline")
	TEST_ASSERT_EQUAL(boulder.excavation_level, 100, "The actual brush spends no excavation amount before its original deadline")
	scheduler_advance((0.2 SECONDS) / (1 SECOND))
	TEST_ASSERT(QDELETED(boulder), "The actual successful late-excavation callback consumes the exact original boulder")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), tool, "The actual completion preserves its exact original held archaeological brush")
	TEST_ASSERT(!QDELETED(tool) && !QDELETED(actor), "The actual completion preserves both original participants")
	TEST_ASSERT(!QDELETED(pen) && pen.loc == T, "The actual completion preserves the unrelated original floor pen")
