/datum/unit_test/interim_synth_native_recipe/Run()
	test_driver_begin()
	exercise_import()
	test_driver_end()

/datum/unit_test/interim_synth_native_recipe/proc/exercise_import()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/chemical_synthesizer/synth = allocate(/obj/machinery/chemical_synthesizer, T)
	own_turf_contents(T)
	var/original_count = length(synth.recipes)
	synth.synth_import_recipe_stage(user, list())
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/text/synth_recipe_review), "Actual import opens native recipe naming")
	test_answer(user, "Native import")
	var/datum/prompt/text/synth_recipe_review/body = SSrequests.open_for(user)
	TEST_ASSERT(istype(body), "Accepted naming opens actual recipe text entry")
	TEST_ASSERT_EQUAL(body.synth_key, "a3", "Native continuation advances to the recipe body")
	test_answer(user, "[REAGENT_ID_WATER],2.5,[REAGENT_ID_ETHANOL],7")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Accepted recipe completes the actual request chain")
	TEST_ASSERT_EQUAL(length(synth.recipes), original_count + 1, "Import stores exactly one new real recipe")
	var/list/recipe = synth.recipes["Native import"]
	TEST_ASSERT_EQUAL(length(recipe), 4, "Stored recipe contains both reagent and volume pairs")
	TEST_ASSERT_EQUAL(recipe[1], REAGENT_ID_WATER, "First reagent retains its actual identifier")
	TEST_ASSERT_EQUAL(recipe[2], 2.5, "Imported fractional volume remains numeric and unrounded")
	TEST_ASSERT_EQUAL(recipe[3], REAGENT_ID_ETHANOL, "Second reagent retains its actual identifier")
	TEST_ASSERT_EQUAL(recipe[4], 7, "Second volume is parsed into its actual numeric value")
	synth.synth_import_recipe_stage(user, list())
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/text/synth_recipe_review), "Next import opens a fresh native request")
	test_answer(user, null, REQ_CANCELLED)
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Closing the next import clears its request")
	TEST_ASSERT_EQUAL(length(synth.recipes), original_count + 1, "Explicit close adds no recipe")
	TEST_ASSERT_EQUAL(synth.recipes["Native import"], recipe, "Explicit close preserves the original stored recipe")
