/// Native release of the last actual round must leave an installed magazine safe for actual gun appearance computation.
/datum/unit_test/interim2_weapon_lazy_ammo_appearance/Run()
	var/turf/T = test_floor()
	var/obj/item/gun/projectile/automatic/wt550/gun = allocate(/obj/item/gun/projectile/automatic/wt550, T)
	var/obj/item/gun/projectile/automatic/wt550/control = allocate(/obj/item/gun/projectile/automatic/wt550, T)
	var/obj/item/ammo_magazine/magazine = gun.ammo_magazine
	var/obj/item/ammo_magazine/control_magazine = control.ammo_magazine
	TEST_ASSERT_NOTNULL(magazine, "The actual WT550 must construct its original magazine")
	TEST_ASSERT_NOTNULL(control_magazine, "The independent WT550 must construct its own magazine")
	TEST_ASSERT_EQUAL(magazine.type, /obj/item/ammo_magazine/m9mmt/rubber, "The canonical constructor must supply its real rubber magazine")
	TEST_ASSERT(magazine != control_magazine, "The original magazines must be independent")
	TEST_ASSERT_EQUAL(length(magazine.stored_ammo), 20, "The original magazine must contain twenty real rounds")
	TEST_ASSERT_EQUAL(length(control_magazine.stored_ammo), 20, "The control magazine must contain twenty real rounds")
	TEST_ASSERT_EQUAL(gun.appearance_mag_state(), "-20", "Actual appearance must initially expose the full magazine")
	var/list/original_stock = magazine.stored_ammo.Copy()
	var/list/control_stock = control_magazine.stored_ammo.Copy()
	for(var/obj/item/ammo_casing/original as anything in original_stock)
		TEST_ASSERT_EQUAL(owner_of(original), magazine, "Each exact original starts with its real ammunition owner")
		TEST_ASSERT_EQUAL(own_take_member(magazine, nameof(magazine.stored_ammo), original), original, "The current native release must return the exact original")
		own(original)
		original.forceMove(T)
		TEST_ASSERT_NULL(owner_of(original), "Actual release must clear the original ammunition ownership")
	TEST_ASSERT(!length(magazine.stored_ammo), "The final actual release empties the list (a list declared = list() stays an empty list, own_list_emptied())")
	TEST_ASSERT_EQUAL(gun.ammo_magazine, magazine, "The exact empty magazine must remain installed")
	TEST_ASSERT_EQUAL(owner_of(magazine), gun, "The original empty magazine must retain its gun owner")
	TEST_ASSERT_EQUAL(gun.appearance_mag_state(), "-0", "The real appearance helper must handle the emptied native list")
	gun.update_icon()
	// The drawn state is the look's (draw sweep): appearance_mag_state() above is what it declares; icon_state stays the mapped sprite.
	TEST_ASSERT_EQUAL(control.appearance_mag_state(), "-20", "The independent gun must remain visibly full")
	for(var/i in 1 to 20)
		var/obj/item/ammo_casing/remaining = control_stock[i]
		TEST_ASSERT_EQUAL(control_magazine.stored_ammo[i], remaining, "The control must retain every exact original in order")
		TEST_ASSERT_EQUAL(owner_of(remaining), control_magazine, "The independent originals must retain their real owner")
		TEST_ASSERT(!QDELETED(remaining), "The independent originals must remain alive")
