/// Pinning and unpinning a real target preserve inventory release and the original target identity.
/datum/unit_test/interim_target_stake_sticky_target/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/target_stake/stake = allocate(/obj/structure/target_stake, T)
	var/obj/item/target/target = allocate(/obj/item/target, T)
	var/original_layer = target.layer
	TEST_ASSERT(stake.density && !target.density, "the actual empty stake and unpinned target have opposite density")
	TEST_ASSERT_NULL(stake.pinned_target, "the stake starts without a target relation")
	TEST_ASSERT(user.put_in_active_hand(target), "the actor holds the original shooting target")
	add_trait(target, TRAIT_NODROP, "interim_target_stake_sticky")
	TEST_ASSERT(user.release_refusal(target, user), "the actual inventory refuses release of the sticky target")
	stake.interaction_item(user, target, null)
	TEST_ASSERT_EQUAL(user.get_active_hand(), target, "refused pinning preserves the exact original hand")
	TEST_ASSERT_EQUAL(target.loc, user, "refused pinning preserves actual inventory containment")
	TEST_ASSERT_NULL(stake.pinned_target, "refused pinning records no target relation")
	TEST_ASSERT(stake.density && !target.density, "refused pinning preserves both actual densities")
	TEST_ASSERT_EQUAL(target.layer, original_layer, "refused pinning does not raise the target's layer")
	remove_trait(target, TRAIT_NODROP, "interim_target_stake_sticky")
	stake.interaction_item(user, target, null)
	TEST_ASSERT_EQUAL(stake.pinned_target, target, "allowed pinning records the exact original target")
	TEST_ASSERT_EQUAL(target.loc, T, "a pinned target sits on the stake's turf, preserving the existing policy")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed pinning clears the source hand")
	TEST_ASSERT(!stake.density && target.density, "allowed pinning transfers the actual blocking density to the target")
	TEST_ASSERT_EQUAL(target.layer, ABOVE_JUNK_LAYER, "the pinned target has its actual presentation layer")
	stake.interaction_hand(user, null, null)
	TEST_ASSERT_EQUAL(user.get_active_hand(), target, "unpinning returns the same original target to the actor")
	TEST_ASSERT_EQUAL(target.loc, user, "unpinning restores actual inventory containment")
	TEST_ASSERT_NULL(stake.pinned_target, "unpinning clears the stake's relation")
	TEST_ASSERT(stake.density && !target.density, "unpinning restores both actual densities")
	TEST_ASSERT_EQUAL(target.layer, OBJ_LAYER, "unpinning restores the actual loose-target layer")
	qdel(stake)
	TEST_ASSERT(!QDELETED(target), "the returned original target survives empty-stake teardown")
