/datum/unit_test/interim_xenochimera_branch_replay/Run()
	test_driver_begin()
	exercise_branch_replay()
	test_driver_end()

/datum/unit_test/interim_xenochimera_branch_replay/proc/exercise_branch_replay()
	var/mob/living/carbon/human/H = allocate(/mob/living/carbon/human, test_floor())
	H.set_species(SPECIES_XENOCHIMERA)
	var/datum/xenochimera/xc = H.get_xenochimera_state()
	TEST_ASSERT_NOTNULL(xc, "The real species constructor installs xenochimera state")
	TEST_ASSERT(H.quickcheckuninjured(), "The actual newly constructed body is uninjured")
	var/ready_before = xc.revive_ready
	TEST_ASSERT(H.death(), "The real death pipeline produces the corpse branch")
	H.reconstitute_form()
	var/datum/prompt/choice/xenochimera_review/first = SSrequests.open_for(H)
	TEST_ASSERT(istype(first), "The public ability opens its real native choice")
	TEST_ASSERT_EQUAL(first.answer_key, "a1", "The initial dead body uses the corpse branch")
	TEST_ASSERT_EQUAL(H.return_from_death("unit test", src, REVIVE_IGNORE_WINDOW), TRUE, "The actual revival API restores the healthy body before answering")
	TEST_ASSERT_EQUAL(H.stat, CONSCIOUS, "The revived actor is conscious")
	TEST_ASSERT(H.quickcheckuninjured(), "The revived body still selects the uninjured branch")
	test_answer(H, "No")
	var/datum/prompt/choice/xenochimera_review/second = SSrequests.open_for(H)
	TEST_ASSERT(istype(second) && second != first, "Answer replay opens a distinct current-state request")
	TEST_ASSERT_EQUAL(second.answer_key, "a2", "Replay selects the now-uninjured branch instead of reusing corpse permission")
	TEST_ASSERT_EQUAL(second.answers["a1"], "No", "The original branch answer remains cached under its own key")
	TEST_ASSERT(!("a2" in second.answers), "The new branch requires its own answer")
	TEST_ASSERT_EQUAL(xc.revive_ready, ready_before, "Changing branches starts no reconstruction")
	test_answer(H, null, REQ_CANCELLED)
	TEST_ASSERT_NULL(SSrequests.open_for(H), "Explicit close ends the new branch without replay")
	TEST_ASSERT_EQUAL(xc.revive_ready, ready_before, "Explicit close preserves actual reconstruction state")
	H.reconstitute_form()
	test_answer(H, "No")
	TEST_ASSERT_NULL(SSrequests.open_for(H), "A current-branch No ends the real request")
	TEST_ASSERT_EQUAL(xc.revive_ready, ready_before, "No leaves regeneration inert")
