/datum/unit_test/interim_diagonal_inventory_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	actor.throw_mode_off()
	bystander.throw_mode_off()
	actor.diagonal_inventory_action(SOUTHWEST)
	TEST_ASSERT_EQUAL(actor.in_throw_mode, 1, "the selected carbon enters throw mode")
	TEST_ASSERT_EQUAL(bystander.in_throw_mode, 0, "an unrelated carbon remains outside throw mode")
	actor.diagonal_inventory_action(SOUTHWEST)
	TEST_ASSERT_EQUAL(actor.in_throw_mode, 0, "a second throw action disables throw mode")
	var/obj/item/pen/held = allocate(/obj/item/pen, T)
	TEST_ASSERT(actor.put_in_active_hand(held), "the actor really holds the item before dropping")
	actor.set_stat(UNCONSCIOUS)
	actor.diagonal_inventory_action(NORTHWEST)
	TEST_ASSERT_EQUAL(actor.get_active_hand(), held, "the native drop guard refuses an unconscious holder")
	actor.set_stat(CONSCIOUS)
	actor.diagonal_inventory_action(NORTHWEST)
	TEST_ASSERT_EQUAL(held.loc, T, "the conscious holder drops the real item onto the turf")
	TEST_ASSERT_NULL(actor.get_active_hand(), "the active hand empties after dropping")
	var/mob/living/carbon/human/pulled = allocate(/mob/living/carbon/human, T)
	actor.start_pulling(pulled)
	TEST_ASSERT_EQUAL(actor.pulling_target(), pulled, "the actor actually establishes a pull relation")
	actor.diagonal_inventory_action(NORTHWEST)
	TEST_ASSERT_NULL(actor.pulling_target(), "the empty-handed action releases the pull relation")
	var/mob/observer/dead/unsupported = allocate(/mob/observer/dead, T)
	unsupported.diagonal_inventory_action(SOUTHWEST)
	unsupported.diagonal_inventory_action(NORTHWEST)
	TEST_ASSERT_EQUAL(unsupported.in_throw_mode, 0, "unsupported actions do not enable throwing")
	var/mob/living/silicon/ai/silicon = allocate(/mob/living/silicon/ai, T, null, null, null, TRUE)
	TEST_ASSERT(isliving(silicon) && !iscarbon(silicon), "the actual safety AI exercises the original noncarbon living branch")
	silicon.throw_mode_off()
	silicon.diagonal_inventory_action(SOUTHWEST)
	TEST_ASSERT_EQUAL(silicon.in_throw_mode, 1, "the existing living-silicon throw behavior is preserved")
	silicon.diagonal_inventory_action(SOUTHWEST)
	TEST_ASSERT_EQUAL(silicon.in_throw_mode, 0, "a second silicon action restores throw state")
	TEST_ASSERT_NULL(silicon.get_active_hand(), "the actual safety AI starts without a held item")
	silicon.diagonal_inventory_action(NORTHWEST)
	TEST_ASSERT_NULL(silicon.pulling_target(), "an empty-handed AI remains without a pull target")
	TEST_ASSERT_EQUAL(actor.in_throw_mode, 0, "silicon actions leave the earlier human's throw state unchanged")
