/// Real slime-food consumption uses its initialized five-unit bite and real ingest holder.
/datum/unit_test/interim_slime_food_bite_data/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/eater = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/food/snacks/slime/food = allocate(/obj/item/reagent_containers/food/snacks/slime, T)
	TEST_ASSERT_EQUAL(food.bitesize, 5, "the real slime food retains its initialized bite size")
	TEST_ASSERT_EQUAL(food.reagents.get_reagent_amount(REAGENT_ID_NUTRIMENT), 50, "the real slime food retains its declared fifty units of nutrition")
	TEST_ASSERT_EQUAL(eater.species.bite_mod, 1, "the real human fixture has the standard bite multiplier")
	TEST_ASSERT(eater.put_in_active_hand(food), "the real slime food starts in the eater's active hand")
	var/original_ingested = eater.ingested.get_reagent_amount(REAGENT_ID_NUTRIMENT)
	TEST_ASSERT_EQUAL(interim_bite(eater, food), TRUE, "actual feeding performs a real slime-food bite")
	TEST_ASSERT_EQUAL(food.reagents.total_volume, 45, "the actual first bite removes exactly five units from the food")
	TEST_ASSERT_EQUAL(eater.ingested.get_reagent_amount(REAGENT_ID_NUTRIMENT), original_ingested + 5, "the actual first bite delivers exactly five units to the real ingest holder")
	TEST_ASSERT_EQUAL(food.bitecount, 1, "actual feeding counts its first real bite")
	TEST_ASSERT(!QDELETED(food), "a partial actual bite preserves the exact slime food")
	TEST_ASSERT_EQUAL(eater.get_active_hand(), food, "a partial actual bite preserves the exact held food")
	for(var/i in 1 to 8)
		interim_bite(eater, food)
	TEST_ASSERT(!QDELETED(food), "nine real bites preserve the final remaining portion")
	TEST_ASSERT_EQUAL(food.reagents.total_volume, 5, "nine actual bites leave exactly one five-unit portion")
	TEST_ASSERT_EQUAL(food.bitecount, 9, "the real food records nine completed bites")
	TEST_ASSERT_EQUAL(interim_bite(eater, food), TRUE, "the actual final bite completes consumption")
	TEST_ASSERT(QDELETED(food), "the actual final bite consumes the original slime food")
	TEST_ASSERT_NULL(eater.get_active_hand(), "actual completed consumption clears the original food hand slot")
	TEST_ASSERT_EQUAL(eater.ingested.get_reagent_amount(REAGENT_ID_NUTRIMENT), original_ingested + 50, "ten actual bites deliver the original full nutritional quantity")
	test_driver_end()
