/// The actual creation model progresses once per accepted unique trait, without UI/admin fabrication.
/datum/unit_test/interim_admin_virus_creation_progress

/datum/unit_test/interim_admin_virus_creation_progress/proc/clear_fixture_archive(list/archive)
	for(var/key in archive)
		var/datum/affliction/contagion/engineered/D = archive[key]
		if(!QDELETED(D))
			qdel(D)
	archive.Cut()

/datum/unit_test/interim_admin_virus_creation_progress/Run()
	test_driver_begin()
	var/list/archive = list()
	set_global(nameof(GLOB.archive_diseases), archive)
	defer_cleanup(src, PROC_REF(clear_fixture_archive), archive)
	var/datum/admin_virus_creation/creation = allocate(/datum/admin_virus_creation)
	var/datum/affliction/contagion/engineered/D = creation.prepare_strain()
	TEST_ASSERT_NOTNULL(D, "A real draft is created")
	TEST_ASSERT_EQUAL(owner_of(D), creation, "The workflow owns the draft")
	TEST_ASSERT_EQUAL(creation.prepare_strain(), D, "Repeated preparation retains the exact draft")
	TEST_ASSERT_EQUAL(length(D.symptoms), 0, "The draft starts empty")
	TEST_ASSERT_EQUAL(creation.remaining, VIRUS_SYMPTOM_LIMIT, "The initial budget is the actual limit")
	TEST_ASSERT(creation.select_symptom(/datum/viral_trait/sneeze), "A real first trait is added")
	TEST_ASSERT_EQUAL(length(D.symptoms), 1, "The first answer produces one trait")
	TEST_ASSERT_EQUAL(creation.remaining, VIRUS_SYMPTOM_LIMIT - 1, "A unique trait consumes one slot")
	var/datum/viral_trait/first = D.symptoms[1]
	TEST_ASSERT_EQUAL(owner_of(first), D, "The draft owns its actual trait")
	for(var/i in 1 to 8)
		TEST_ASSERT(!creation.select_symptom(/datum/viral_trait/sneeze), "Duplicate selection returns without adding a trait")
	TEST_ASSERT_EQUAL(length(D.symptoms), 1, "Repeated duplicates retain one exact trait")
	TEST_ASSERT_EQUAL(D.symptoms[1], first, "Duplicate selection preserves the original trait identity")
	TEST_ASSERT_EQUAL(creation.remaining, VIRUS_SYMPTOM_LIMIT - 1, "Duplicates do not spend the remaining budget")
	TEST_ASSERT_NULL(creation.candidate, "Rejected temporary traits are disposed")
	for(var/symptom_type in GLOB.viral_trait_types)
		if(creation.remaining <= 0)
			break
		creation.select_symptom(symptom_type)
	TEST_ASSERT_EQUAL(creation.remaining, 0, "Distinct real traits eventually fill the budget")
	TEST_ASSERT_EQUAL(length(D.symptoms), VIRUS_SYMPTOM_LIMIT, "The exact limit of traits is retained")
	TEST_ASSERT(!creation.select_symptom(/datum/viral_trait/cough), "A full draft rejects further additions")
	TEST_ASSERT_EQUAL(length(D.symptoms), VIRUS_SYMPTOM_LIMIT, "Full-draft refusal retains its contents")
	TEST_ASSERT_EQUAL(creation.strain, D, "Every selection retains the original draft")
	creation.retire()
	test_drain()
	TEST_ASSERT(QDELETED(creation), "Actual retirement deletes the nonspatial workflow")
	TEST_ASSERT(QDELETED(D), "Retirement deletes its owned draft")
	TEST_ASSERT(QDELETED(first), "Retirement deletes the draft's owned traits")
	test_driver_end()
