/datum/unit_test/interim_shield_telecom_reference_pairs/Run()
	var/turf/T = test_floor()
	var/obj/machinery/shield_gen/generator = allocate(/obj/machinery/shield_gen, T)
	var/obj/machinery/shield_capacitor/first = allocate(/obj/machinery/shield_capacitor, T)
	var/obj/machinery/shield_capacitor/second = allocate(/obj/machinery/shield_capacitor, T)
	TEST_ASSERT_NULL(first.owned_gen(), "The first real capacitor starts without a generator")
	TEST_ASSERT_NULL(second.owned_gen(), "The second real capacitor starts without a generator")
	rel_set(first, nameof(first.owned_gen), generator)
	rel_set(second, nameof(second.owned_gen), generator)
	TEST_ASSERT(first.owned_gen() == generator && second.owned_gen() == generator, "Both exact capacitors resolve their real generator")
	TEST_ASSERT(length(generator.capacitors) == 2 && (first in generator.capacitors) && (second in generator.capacitors), "The generator holds both reciprocal original memberships")
	qdel(first)
	TEST_ASSERT(QDELETED(first), "The first original capacitor is actually retired")
	TEST_ASSERT(length(generator.capacitors) == 1 && (second in generator.capacitors), "Deleting one capacitor prunes only its own reverse membership")
	TEST_ASSERT(second.owned_gen() == generator, "The surviving capacitor retains its exact backlink")
	qdel(generator)
	TEST_ASSERT(QDELETED(generator), "The original generator is actually retired")
	TEST_ASSERT_NULL(second.owned_gen(), "Generator deletion clears the surviving capacitor backlink")
	TEST_ASSERT(!QDELETED(second) && second.loc == T, "Reference cleanup preserves the independent capacitor and its original location")

	var/obj/machinery/telecomms/center = allocate(/obj/machinery/telecomms, T)
	var/obj/machinery/telecomms/left = allocate(/obj/machinery/telecomms, T)
	var/obj/machinery/telecomms/right = allocate(/obj/machinery/telecomms, T)
	TEST_ASSERT(!length(center.links) && !length(left.links) && !length(right.links), "The real base telecom machines have no automatic links")
	rel_add(center, nameof(center.links), left)
	rel_add(center, nameof(center.links), right)
	TEST_ASSERT(length(center.links) == 2 && (left in center.links) && (right in center.links), "The real center stores both exact peers")
	TEST_ASSERT(length(left.links) == 1 && (center in left.links), "The first peer receives reciprocal membership")
	TEST_ASSERT(length(right.links) == 1 && (center in right.links), "The second peer receives reciprocal membership")
	qdel(left)
	TEST_ASSERT(QDELETED(left), "The first original telecom peer is actually retired")
	TEST_ASSERT(length(center.links) == 1 && (right in center.links), "Deleting one peer preserves the other exact link")
	TEST_ASSERT(length(right.links) == 1 && (center in right.links), "The remaining reciprocal link survives unrelated peer deletion")
	qdel(center)
	TEST_ASSERT(QDELETED(center), "The original telecom center is actually retired")
	TEST_ASSERT(!length(right.links), "Center deletion prunes the final reciprocal membership")
	TEST_ASSERT(!QDELETED(right) && right.loc == T, "The referenced telecom peer survives with its original location")
