/// Actual core-backed spell creation retains the initiating actor and real inventory gates.
/datum/unit_test/interim_technomancer_spellbutton_actor/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/mob/observer/dead/observer = allocate(/mob/observer/dead, T)
	observer.forceMove(T)
	var/atom/movable/screen/movable/ability_master/master = allocate(/atom/movable/screen/movable/ability_master, actor)
	rel_set(actor, nameof(actor.ability_master), master)
	var/obj/item/technomancer_core/universal/core = allocate(/obj/item/technomancer_core/universal, T)
	core.add_spell(/obj/item/spell/warp_strike, "Test warp", "tech_warpstrike")
	TEST_ASSERT_EQUAL(length(core.spells), 1, "the actual core adds one owned spell button")
	var/obj/spellbutton/button = core.spells[1]
	TEST_ASSERT_EQUAL(button.core, core, "the actual button constructor retains the original core")
	TEST_ASSERT_EQUAL(button.loc, core, "the actual owned button is physically inside its core")
	TEST_ASSERT(actor.equip_to_slot_if_possible(core, SLOT_ID_BACK), "real inventory equips the original universal core")
	TEST_ASSERT_EQUAL(core.wearer, actor, "the actual equipped lifecycle records its wearer")
	var/atom/movable/screen/ability/obj_based/technomancer/ability = master.get_ability_by_instance(button)
	TEST_ASSERT(ability && ability.object() == button, "real core equip exposes the exact owned button through its ability")
	var/energy = core.energy
	button.create_spell_with_actor(null)
	km_synthetic_click(observer, button)
	TEST_ASSERT_EQUAL(length(contents_of(actor, /obj/item/spell)), 0, "absent and unsupported actors never create a spell for the actual wearer")
	TEST_ASSERT_EQUAL(length(contents_of(observer, /obj/item/spell)), 0, "an actual observer native click cannot create a human spell")
	km_synthetic_click(actor, button)
	var/obj/item/spell/warp_strike/first = actor.get_active_hand()
	TEST_ASSERT(istype(first), "the actual native button places a real warp spell in the initiating human's active hand")
	own(first)
	TEST_ASSERT_EQUAL(first.owner_ref(), actor, "the real spell constructor records the initiating actor")
	TEST_ASSERT_EQUAL(first.core, core, "the real spell links the actually worn core")
	TEST_ASSERT(first.run_checks(), "the actual universal core authorizes its real spell without an antagonist fixture")
	TEST_ASSERT_EQUAL(length(contents_of(bystander, /obj/item/spell)), 0, "native creation leaves an unrelated human unchanged")
	TEST_ASSERT(actor.unEquip(first), "real inventory drops the original disposable spell")
	TEST_ASSERT(QDELETED(first), "actual DROPDEL release removes the original spell")
	TEST_ASSERT_NULL(actor.get_active_hand(), "real disposable spell release frees the original active hand")
	button.create_spell_with_actor(actor)
	var/obj/item/spell/warp_strike/second = actor.get_active_hand()
	TEST_ASSERT(istype(second) && second != first, "explicit actor creation with no native usr makes a distinct real held spell")
	own(second)
	TEST_ASSERT_EQUAL(second.owner_ref(), actor, "the direct helper preserves the supplied actor through actual spell construction")
	TEST_ASSERT_EQUAL(second.core, core, "the direct helper retains the exact worn core")
	TEST_ASSERT_EQUAL(core.energy, energy, "actual button creation alone never spends warp-casting energy")
	TEST_ASSERT_EQUAL(length(core.spells), 1, "all creation and refusal paths preserve the original core button ledger")
	TEST_ASSERT_EQUAL(core.spells[1], button, "the actual button identity survives repeated real spell creation")
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_BACK), core, "actual spell creation preserves the original worn core slot")
