/// Successful assembly consumes only the mask shell, preserves its slot, and installs the real hailer.
/datum/unit_test/interim_hailer_mask_install/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/clothing/mask/gas/half/mask = allocate(/obj/item/clothing/mask/gas/half, T)
	var/obj/item/hailer/hailer = allocate(/obj/item/hailer, T)
	TEST_ASSERT(user.put_in_l_hand(mask), "the original mask occupies the left hand")
	TEST_ASSERT(user.put_in_r_hand(hailer), "the hailer occupies the right hand")
	var/datum/forensics_crime/evidence = mask.init_forensic_data()
	TEST_ASSERT(evidence.add_prints(user), "the original mask has real fingerprint evidence")
	var/list/prints = evidence.get_prints().Copy()
	TEST_ASSERT(length(prints), "the original mask has nonempty fingerprint evidence")
	test_op_handler(mask, "half_mask_add_hailer_item", user, hailer)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(mask), "installation consumes the original mask")
	var/obj/item/clothing/mask/gas/sechailer/product = user.get_equipped_item(SLOT_ID_HAND_L)
	TEST_ASSERT(istype(product), "the upgraded mask occupies the original mask's hand")
	TEST_ASSERT(!QDELETED(hailer), "the installed hailer survives assembly")
	TEST_ASSERT_EQUAL(product.hailer(), hailer, "the upgraded mask refers to the actual ingredient")
	TEST_ASSERT_EQUAL(hailer.loc, product, "the hailer is physically inside the upgraded mask")
	TEST_ASSERT_NULL(user.get_equipped_item(SLOT_ID_HAND_R), "the ingredient's hand is correctly vacated")
	var/list/transferred = product.forensic_data?.get_prints()
	TEST_ASSERT_EQUAL(length(transferred), length(prints), "installation preserves the actual fingerprint count")
	for(var/print in prints)
		TEST_ASSERT_EQUAL(transferred?[print], prints[print], "installation preserves each original fingerprint")

/// Refusal of either real ingredient preserves both ingredients and produces no upgraded mask.
/datum/unit_test/interim_hailer_mask_refusal/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/datum/dq_containment_listener/refusal = allocate(/datum/dq_containment_listener)
	refusal.watch(user)
	refusal.block_remove = TRUE
	for(var/source_refuses in list(TRUE, FALSE))
		var/obj/item/clothing/mask/gas/half/mask = allocate(/obj/item/clothing/mask/gas/half, T)
		var/obj/item/hailer/hailer = allocate(/obj/item/hailer, T)
		var/obj/item/held = source_refuses ? mask : hailer
		TEST_ASSERT(user.put_in_active_hand(held), "the refusing ingredient is actually held")
		TEST_ASSERT(held.loc.release_refusal(held, user), "the actual held ingredient refuses release")
		TEST_ASSERT(mask.can_fit_hailer(user, mask, hailer) != TRUE, "assembly requirements reject the refusing ingredient")
		test_op_handler(mask, "half_mask_add_hailer_item", user, hailer)
		own_turf_contents(T)
		TEST_ASSERT(!QDELETED(mask), "refusal preserves the original mask")
		TEST_ASSERT(!QDELETED(hailer), "refusal preserves the actual hailer")
		TEST_ASSERT_EQUAL(user.get_active_hand(), held, "refusal preserves the ingredient's original hand")
		TEST_ASSERT_EQUAL(source_refuses ? hailer.loc : mask.loc, T, "refusal preserves the other ingredient's floor location")
		TEST_ASSERT_NULL(locate_within(T, /obj/item/clothing/mask/gas/sechailer), "refusal creates no floor product")
		TEST_ASSERT_NULL(locate_within(user, /obj/item/clothing/mask/gas/sechailer), "refusal creates no inventory product")
		user.drop_from_inventory(held)
