/// Generator deletion must perform the same real moving-anomaly release as explicit deactivation.
/datum/unit_test/interim_suspension_generator_deletion/Run()
	var/turf/T = test_floor()
	var/turf/field_turf = get_step(T, EAST)
	TEST_ASSERT(field_turf, "The actual directional field fixture needs a neighboring turf")
	var/obj/machinery/suspension_gen/generator = allocate(/obj/machinery/suspension_gen, T)
	generator.set_dir(EAST)
	var/obj/effect/anomaly/anomaly = allocate(/obj/effect/anomaly, field_turf)
	anomaly.stabilize(TRUE, TRUE, TRUE)
	var/datum/anomaly_modifiers/move/modifier = allocate(/datum/anomaly_modifiers/move)
	own_set(anomaly.stats, nameof(anomaly.stats.modifier), modifier)
	modifier.on_add(anomaly)
	TEST_ASSERT_EQUAL(anomaly.move_chance, ANOMALY_MOVECHANCE, "The actual movement modifier must make the stabilized anomaly mobile")
	generator.activate()
	own_turf_contents(T)
	own_turf_contents(field_turf)
	TEST_ASSERT_EQUAL(anomaly.move_chance, 0, "The actual generator activation must stop anomaly movement")
	TEST_ASSERT(generator.suspension_field, "Actual activation must create the owned field")
	TEST_ASSERT_EQUAL(generator.suspension_field.loc, field_turf, "The actual field must project onto the directional turf")
	generator.deactivate()
	TEST_ASSERT_EQUAL(anomaly.move_chance, ANOMALY_MOVECHANCE, "Explicit deactivation must restore the actual movement modifier's anomaly")
	generator.activate()
	own_turf_contents(T)
	own_turf_contents(field_turf)
	var/obj/effect/suspension_field/field = generator.suspension_field
	TEST_ASSERT(field, "Reactivation must create an actual replacement field")
	TEST_ASSERT_EQUAL(anomaly.move_chance, 0, "Reactivation must actually suppress movement before deletion")
	qdel(generator)
	own_turf_contents(T)
	own_turf_contents(field_turf)
	TEST_ASSERT(QDELETED(generator), "The actual generator must be deleted")
	TEST_ASSERT(QDELETED(field), "The generator's actual owned field must be removed")
	TEST_ASSERT(!QDELETED(anomaly), "Generator deletion must preserve the actual independent anomaly")
	TEST_ASSERT_EQUAL(anomaly.loc, field_turf, "Generator deletion must preserve the anomaly's real turf")
	TEST_ASSERT_EQUAL(anomaly.move_chance, ANOMALY_MOVECHANCE, "Deletion must restore movement before the field reference clears")
