/// Actual timed hive construction refuses a stuck original assembly.
/datum/unit_test/om/interim_beehive_assembly_refusal/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/beehive_assembly/assembly = allocate(/obj/item/beehive_assembly, T)
	made += list(user, assembly)
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/beehive)), 0, "actual fixture starts without constructed hives")
	TEST_ASSERT(user.put_in_active_hand(assembly), "the actor holds exact original assembly")
	add_trait(assembly, TRAIT_NODROP, "interim_beehive_assembly")
	TEST_ASSERT(user.release_refusal(assembly, user), "actual inventory refuses sticky assembly consumption")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "actual construction actor starts capable")
	test_op_handler(assembly, "interaction_self", user, assembly)
	TEST_ASSERT(LAZYLEN(user.do_afters), "public construction entry starts actual timed work")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/beehive)), 0, "starting construction creates no early hive")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!QDELETED(assembly), "actual construction consumes no assembly before deadline")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/beehive)), 0, "actual construction creates no hive before deadline")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "actual construction actor remains capable at completion")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "actual construction completes pending work")
	TEST_ASSERT(!QDELETED(assembly), "refused construction preserves exact original assembly")
	TEST_ASSERT_EQUAL(user.get_active_hand(), assembly, "refused construction preserves original source hand")
	TEST_ASSERT_EQUAL(assembly.loc, user, "refused construction preserves inventory containment")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/machinery/beehive)), 0, "refused original consumption creates no free hive")
