/// Actual pose verb and native answers; no client-window delivery claim.
/datum/unit_test/interim_human_native_pose_chain

/datum/unit_test/interim_human_native_pose_chain/Run()
	test_driver_begin()
	defer_cleanup(null, GLOBAL_PROC_REF(test_driver_end))
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	actor.enable_godmode()
	TEST_ASSERT_NULL(actor.pose, "the real human starts without a pose")
	TEST_ASSERT_NULL(actor.pose_indicator, "the real human starts without a pose indicator")
	actor.pose()
	test_drain()
	var/datum/request/request = SSrequests.open_for(actor)
	TEST_ASSERT(istype(request, /datum/prompt/text/pose), "the production pose verb opens the real native text request")
	TEST_ASSERT_EQUAL(request.timeout, REQUEST_DEFAULT_TIMEOUT, "the pose question gets the engine default timeout (it declares none)")
	test_answer(actor, "stands at attention.")
	request = SSrequests.open_for(actor)
	TEST_ASSERT(istype(request, /datum/prompt/checklist/pose_options), "an accepted pose opens the actual checklist")
	TEST_ASSERT_NULL(actor.pose, "the pose is not committed before the real checklist answer")
	test_answer(actor, list("Cancel Pose on Movement", "Quiet Pose"))
	TEST_ASSERT_EQUAL(actor.pose, "stands at attention.", "the native checklist commits the exact entered pose")
	TEST_ASSERT(actor.pose_move, "the actual selected movement option is applied")
	TEST_ASSERT_NOTNULL(actor.pose_indicator, "the default icon option creates the real pose indicator")
	var/image/original_indicator = actor.pose_indicator
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "the accepted checklist ends the workflow")

	actor.pose()
	test_drain()
	test_answer(actor, "leans on the wall.")
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/checklist/pose_options), "the second actual text answer reaches its checklist")
	test_answer(actor, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(actor.pose, "stands at attention.", "checklist cancellation preserves the actual previously committed pose")
	TEST_ASSERT_EQUAL(actor.pose_indicator, original_indicator, "checklist cancellation preserves the exact original indicator")
	TEST_ASSERT(actor.pose_move, "checklist cancellation preserves the original movement option")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "checklist cancellation ends without another prompt")

	actor.pose()
	test_drain()
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/text/pose), "the first-question cancellation control really opens")
	test_answer(actor, null, REQ_CANCELLED)
	TEST_ASSERT_NULL(actor.pose, "first-question cancellation clears the real existing pose")
	TEST_ASSERT_NULL(actor.pose_indicator, "first-question cancellation removes its real existing indicator")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "first-question cancellation does not open the checklist")

	actor.pose()
	test_drain()
	test_answer(actor, "waits patiently.")
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/checklist/pose_options), "the empty-choice control reaches the actual checklist")
	test_answer(actor, list())
	TEST_ASSERT_EQUAL(actor.pose, "waits patiently.", "an accepted empty checklist still commits the real pose")
	TEST_ASSERT(!actor.pose_move, "the empty checklist resets movement cancellation to its actual default")
	TEST_ASSERT_NOTNULL(actor.pose_indicator, "the empty checklist retains the actual default indicator")

	actor.pose()
	test_drain()
	test_answer(actor, "looks around.")
	test_answer(actor, list("Disable Pose Icon", "Quiet Pose"))
	TEST_ASSERT_EQUAL(actor.pose, "looks around.", "the actual disabled-icon checklist commits the new pose")
	TEST_ASSERT_NULL(actor.pose_indicator, "the actual selected Disable Pose Icon removes the indicator")
	actor.pose()
	test_drain()
	test_answer(actor, "")
	TEST_ASSERT_NULL(actor.pose, "an accepted empty text clears the actual pose")
	TEST_ASSERT_NULL(actor.pose_indicator, "an accepted empty text leaves no indicator")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "an accepted empty text ends without a checklist")
