/// A real portable turret's declared emag spends one card use, disables it for its actual grace period, and locks out remote control both before and after reactivation.
/datum/unit_test/om/interim_portable_turret_emag_grace/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/porta_turret/turret = allocate(/obj/machinery/porta_turret, T)
	var/obj/item/card/emag/card = allocate(/obj/item/card/emag, T)
	var/datum/turret_checks/remote = allocate(/datum/turret_checks)
	made += list(user, turret, card)
	card.uses = 3
	turret.enabled = TRUE
	TEST_ASSERT(!turret.emagged && !turret.controllock, "the actual portable turret starts unsubverted and remotely controllable")
	TEST_ASSERT(user.put_in_active_hand(card), "the actual actor holds the charged emag")
	TEST_ASSERT(op_known_anywhere(user, turret, card, "emag.use"), "the actual portable turret exposes its declared emag op")
	var/timers_before = om_timer_count(turret)
	TEST_ASSERT(test_op_committed(perform_op(user, turret, "emag.use", card)), "the actual declared emag op subverts the portable turret")
	TEST_ASSERT_EQUAL(card.uses, 2, "the actual accepted turret emag spends one card use")
	TEST_ASSERT(turret.emagged && turret.controllock && !turret.enabled, "actual subversion locks out controllers and immediately disables the turret")
	TEST_ASSERT(om_timer_count(turret) > timers_before, "actual subversion schedules the grace-period reactivation")
	remote.enabled = TRUE
	turret.setState(remote)
	TEST_ASSERT(!turret.enabled, "actual remote control cannot prematurely reactivate the subverted turret")
	var/pending_timers = om_timer_count(turret)
	TEST_ASSERT(!test_op_committed(perform_op(user, turret, "emag.use", card)), "a subverted turret refuses a repeat emag")
	TEST_ASSERT_EQUAL(card.uses, 2, "actual repeat refusal spends no extra card use")
	TEST_ASSERT_EQUAL(om_timer_count(turret), pending_timers, "actual repeat refusal schedules no second reactivation")
	scheduler_advance((5 SECONDS) / (1 SECOND))
	TEST_ASSERT(!turret.enabled, "the actual turret remains disabled before its six-second grace period expires")
	scheduler_advance((1 SECOND + 1 TICK) / (1 SECOND))
	TEST_ASSERT(turret.enabled, "the real delayed effect reactivates the original turret after its grace period")
	TEST_ASSERT(turret.emagged && turret.controllock, "actual delayed reactivation preserves subversion and remote-control lockout")
	remote.enabled = FALSE
	turret.setState(remote)
	TEST_ASSERT(turret.enabled, "actual remote control cannot switch the reactivated subverted turret off")
	TEST_ASSERT_EQUAL(card.uses, 2, "actual delayed reactivation and remote refusals consume no additional card use")
	own_turf_contents(T)
