/// The read-only target-family table is shared while real hacking state and random capacity remain per instance.
/datum/unit_test/om/interim_hacktool_supported_table
	var/tool_type = /obj/item/multitool/hacktool

/datum/unit_test/om/interim_hacktool_supported_table/override_tool
	tool_type = /obj/item/multitool/hacktool/override

/datum/unit_test/om/interim_hacktool_supported_table/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	actor.enable_godmode()
	var/obj/structure/closet/crate/secure/crate = allocate(/obj/structure/closet/crate/secure, T)
	var/obj/item/multitool/hacktool/tool = allocate(tool_type, T)
	var/obj/item/multitool/hacktool/other = allocate(/obj/item/multitool/hacktool, T)
	var/obj/item/tool/screwdriver/screwdriver = allocate(/obj/item/tool/screwdriver, T)
	var/obj/item/pen/unsupported = allocate(/obj/item/pen, T)
	made += list(actor, tool, other, screwdriver, unsupported, crate)
	TEST_ASSERT_EQUAL(length(tool.supported_types), 3, "The actual tool supports exactly its original three target families")
	TEST_ASSERT_EQUAL(tool.supported_types[1], /obj/machinery/door/airlock, "The first actual supported family remains airlocks")
	TEST_ASSERT_EQUAL(tool.supported_types[2], /obj/structure/closet/crate/secure, "The second actual supported family remains secure crates")
	TEST_ASSERT_EQUAL(tool.supported_types[3], /obj/structure/closet/secure_closet, "The third actual supported family remains secure closets")
	TEST_ASSERT_EQUAL(tool.supported_types, other.supported_types, "Real base and inherited tools share the original immutable target table")
	TEST_ASSERT(tool.max_known_targets >= 6 && tool.max_known_targets <= 8, "The real constructor retains its per-instance random capacity range")
	TEST_ASSERT(other.max_known_targets >= 6 && other.max_known_targets <= 8, "The second real constructor independently retains its random capacity range")
	if(tool_type == /obj/item/multitool/hacktool/override)
		TEST_ASSERT(tool.full_override && tool.max_level == 5 && tool.hackspeed == 0.75, "The actual override subtype retains its original hacking configuration")
	else
		TEST_ASSERT(!tool.full_override && tool.max_level == 4 && tool.hackspeed == 1, "The actual base tool retains its original hacking configuration")
	TEST_ASSERT(actor.put_in_active_hand(tool), "The real actor holds the actual hacktool")
	TEST_ASSERT(actor.put_in_inactive_hand(screwdriver), "The real actor holds the actual mode-switching screwdriver")
	test_op_handler(tool, "screwdriver_used", actor, screwdriver)
	TEST_ASSERT(tool.in_hack_mode, "The actual public tool interaction enables hacking mode")
	TEST_ASSERT_EQUAL(unsupported.loc, T, "The actual unsupported pen starts on its original floor after crate construction")
	TEST_ASSERT_EQUAL(tool.attempt_hack(actor, unsupported), 0, "The real unsupported pen is refused by target-family membership")
	TEST_ASSERT(!task_busy(tool), "Actual unsupported refusal schedules no hacking task")
	TEST_ASSERT_EQUAL(unsupported.loc, T, "Actual unsupported refusal preserves the original pen floor")
	TEST_ASSERT(lock_locked(crate), "The actual secure crate starts locked")
	TEST_ASSERT(!actor.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "The actual actor is capable before starting the real hack")
	tool.attempt_hack(actor, crate)
	var/list/actions = timed_tasks_of(actor, tool)
	TEST_ASSERT_EQUAL(length(actions), 1, "The actual supported hack creates exactly one real timed action")
	var/datum/task/timed/action = actions[1]
	TEST_ASSERT(action.duration >= (5 SECONDS) * tool.hackspeed && action.duration <= (15 SECONDS) * tool.hackspeed, "The actual hack duration preserves the original bounded random delay: [action.duration]")
	var/actual_deadline = action.ends_at
	TEST_ASSERT_NULL(action.why_not_running(), "The actual task initially satisfies all captured actor/target/held-item conditions")
	TEST_ASSERT(task_busy(tool) && lock_locked(crate), "The actual supported crate starts a real claimed timed hack without unlocking early")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(task_busy(tool) && lock_locked(crate), "The actual minimum-duration hack remains busy and locked after two seconds")
	TEST_ASSERT(!actor.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "The real actor remains capable at two seconds: stat=[actor.stat], physical=[actor.injury_load(INJURY_CATEGORY_PHYSICAL)]")
	TEST_ASSERT_NULL(action.why_not_running(), "The actual task still satisfies its captured conditions at two seconds")
	scheduler_advance((20 SECONDS) / (1 SECOND))
	TEST_ASSERT(sched.now() >= actual_deadline, "The actual test scheduler has passed the real task deadline")
	TEST_ASSERT(!actor.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "The real actor remains capable after advancing: stat=[actor.stat], physical=[actor.injury_load(INJURY_CATEGORY_PHYSICAL)]")
	TEST_ASSERT(!lock_locked(crate), "The real timed callback unlocks the original supported crate; task deleted=[QDELETED(action)], state=[action?.state], reason=[action?.reason], deadline=[actual_deadline], now=[sched.now()]")
	TEST_ASSERT(!task_busy(tool), "The actual completed hacking task releases its claim")
	TEST_ASSERT_EQUAL(crate.loc, T, "Actual hacking preserves the exact crate and original floor")
	TEST_ASSERT(!QDELETED(crate) && !QDELETED(unsupported), "Actual hacking preserves both original target identities")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), tool, "Actual hacking preserves the actor's original held tool")
	TEST_ASSERT_EQUAL(actor.get_inactive_hand(), screwdriver, "Actual hacking preserves the actor's original held screwdriver")
	TEST_ASSERT(!task_busy(other) && !other.in_hack_mode, "The second instance's actual mutable hacking state remains independent")
