/// Actual unwiring refuses the wrong held tool, then refunds five cable lengths and the exact installed stock part while restoring board requirements.
/datum/unit_test/interim_frame_unwire_component_refund/Run()
	test_driver_begin()
	defer_cleanup(src, PROC_REF(interim_native_frame_driver_end))
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/structure/frame/frame = allocate(/obj/structure/frame, T)
	var/obj/item/circuitboard/autolathe/board = allocate(/obj/item/circuitboard/autolathe, T)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, T, 6)
	var/obj/item/stock_parts/matter_bin/bin = allocate(/obj/item/stock_parts/matter_bin, T)
	var/obj/item/tool/wrench/wrench = allocate(/obj/item/tool/wrench, T)
	var/obj/item/tool/wirecutters/cutters = allocate(/obj/item/tool/wirecutters, T)
	TEST_ASSERT(interim_native_frame_step(frame, user, "construction.build:machine_frame_placed.anchor"), "the real unwiring fixture can be anchored")
	TEST_ASSERT(interim_native_frame_step(frame, user, "construction.build:machine_frame_board_in.insert_board", board), "the real matching board enters the unwiring fixture")
	TEST_ASSERT(interim_native_frame_step(frame, user, "construction.build:machine_frame_fastened.fasten_board"), "the real board can be fastened")
	TEST_ASSERT(interim_native_frame_step(frame, user, "construction.build:machine_frame_wired.wire", cable), "the real frame fixture can be wired")
	user.drop_item()
	TEST_ASSERT(user.put_in_active_hand(bin), "the actual actor holds the stock part to install")
	test_op_handler(frame, "interaction_item", user, bin)
	TEST_ASSERT_EQUAL(bin.loc, frame, "the actual stock part physically enters the wired frame")
	TEST_ASSERT(bin in frame.components, "the wired frame records the exact installed stock part")
	var/full_bin_requirement = board.req_components[/obj/item/stock_parts/matter_bin]
	TEST_ASSERT_EQUAL(frame.req_components[/obj/item/stock_parts/matter_bin], full_bin_requirement - 1, "actual installed stock part reduces its real requirement once")
	var/unwire = "construction.build:machine_frame_fastened.unwire"
	TEST_ASSERT_NOTNULL(op_plan_for(frame, unwire), "the actual wired frame exposes its unwiring edge")
	user.drop_item()
	TEST_ASSERT(user.put_in_active_hand(wrench), "the actual actor holds the wrong unwiring tool")
	TEST_ASSERT_NOTNULL(interim_native_frame_reason(frame, user, unwire, wrench), "the actual unwiring requirement refuses a wrench")
	TEST_ASSERT(!interim_native_frame_started(frame, user, unwire, wrench), "the actual public edge refuses the wrong held tool")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "wrong-tool refusal preserves actual wiring")
	TEST_ASSERT_EQUAL(bin.loc, frame, "wrong-tool refusal preserves the actual installed stock part")
	TEST_ASSERT_EQUAL(cable.get_amount(), 1, "wrong-tool refusal creates no cable refund")
	TEST_ASSERT(user.drop_from_inventory(wrench, T), "the actor really releases the wrong tool")
	user.drop_item()
	TEST_ASSERT(user.put_in_active_hand(cutters), "the actor really holds the proper unwiring tool")
	TEST_ASSERT(interim_native_frame_started(frame, user, unwire, cutters), "the actual public construction edge removes wiring and components")
	own_turf_contents(T)
	TEST_ASSERT_EQUAL(frame.state, FRAME_FASTENED, "actual unwiring returns to the board-fastened stage")
	TEST_ASSERT(frame.anchored, "actual unwiring preserves frame anchoring")
	TEST_ASSERT_EQUAL(frame.circuit, board, "actual unwiring preserves the exact installed board")
	TEST_ASSERT_EQUAL(board.loc, frame, "actual unwiring keeps the board physically inside")
	TEST_ASSERT_EQUAL(bin.loc, T, "actual unwiring refunds the exact original stock part to the floor")
	TEST_ASSERT(!(bin in frame.components), "actual unwiring clears the refunded stock part's ownership view")
	TEST_ASSERT_EQUAL(frame.req_components[/obj/item/stock_parts/matter_bin], full_bin_requirement, "actual unwiring restores the original full stock-part requirement")
	var/cable_lengths = 0
	for(var/obj/item/stack/cable_coil/returned as anything in contents_of(T, /obj/item/stack/cable_coil))
		cable_lengths += returned.get_amount()
	TEST_ASSERT_EQUAL(cable_lengths, 6, "actual unwiring refunds exactly five cable lengths alongside the original one-length remainder")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cutters, "actual unwiring preserves the proper held tool")
