/// Actual shredding must consume the original document before crediting recoverable shredded paper.
/datum/unit_test/interim_paper_shredder_sticky_paper/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/papershredder/machine = allocate(/obj/machinery/papershredder, T)
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	dq_machine_clear(machine)
	TEST_ASSERT(machine.operable(), "actual initialized shredder is genuinely operable")
	TEST_ASSERT_EQUAL(machine.paperamount, 0, "actual shredder starts without recoverable shredded paper")
	TEST_ASSERT(user.put_in_active_hand(paper), "the actor holds exact original document")
	add_trait(paper, TRAIT_NODROP, "interim_shredder_paper")
	TEST_ASSERT(user.release_refusal(paper, user), "actual inventory refuses sticky document consumption")
	test_op_handler(machine, "interaction_shred", user, paper)
	TEST_ASSERT(!QDELETED(paper), "refused shredding preserves exact original document")
	TEST_ASSERT_EQUAL(user.get_active_hand(), paper, "refused shredding preserves original source hand")
	TEST_ASSERT_EQUAL(paper.loc, user, "refused shredding preserves inventory containment")
	TEST_ASSERT_EQUAL(machine.paperamount, 0, "refused consumption grants no recoverable paper")
	remove_trait(paper, TRAIT_NODROP, "interim_shredder_paper")
	test_op_handler(machine, "interaction_shred", user, paper)
	TEST_ASSERT(QDELETED(paper), "allowed shredding consumes exact original document")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(machine.paperamount, 1, "one consumed document grants exactly one recoverable paper unit")
	var/products_before = length(contents_of(T, /obj/item/shreddedp))
	test_op_handler(machine, "interaction_empty", user)
	TEST_ASSERT_EQUAL(machine.paperamount, 0, "actual public emptying consumes recoverable paper credit")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/shreddedp)), products_before + 1, "actual public emptying creates exactly one physical shredded-paper product")
	var/obj/item/shreddedp/product = locate_within(T, /obj/item/shreddedp)
	TEST_ASSERT_NOTNULL(product, "actual emptying creates real surviving shredded paper")
	own(product)
	TEST_ASSERT(!QDELETED(product), "actual physical product survives initialization")
