/// Actual native self-use must refuse before sparks and teleport when the held crystal cannot leave its slot.
/datum/unit_test/interim_bluespace_crystal_sticky_self
	parent_type = /datum/unit_test/dq_p2_reagents

/datum/unit_test/interim_bluespace_crystal_sticky_self/run_gate()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = rc_actor(T)
	var/obj/item/bluespace_crystal/crystal = allocate(/obj/item/bluespace_crystal, T)
	var/obj/item/bluespace_crystal/control = allocate(/obj/item/bluespace_crystal, T)
	TEST_ASSERT(actor.put_in_active_hand(crystal), "the actor actually holds the original crystal")
	var/datum/original_owner = owner_of(crystal)
	add_trait(crystal, TRAIT_NODROP, "interim_bluespace_crystal_sticky_self")
	TEST_ASSERT(actor.release_refusal(crystal, actor), "actual inventory refuses to release the sticky crystal")
	var/list/before = turf_contents_of_type(T, /obj/effect/effect/sparks)
	var/datum/op_result/refused = test_click(actor, crystal, crystal, GESTURE_SELF)
	TEST_ASSERT_NOTNULL(refused, "the real held self-use input resolves its native op")
	TEST_ASSERT_EQUAL(refused.outcome, ACT_REFUSED, "the actual crystal op refuses before its effect runs")
	TEST_ASSERT_EQUAL(actor.loc, T, "refused crushing does not teleport the original actor")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), crystal, "refusal preserves the exact active-hand crystal")
	TEST_ASSERT_EQUAL(crystal.loc, actor, "refusal preserves real held containment")
	TEST_ASSERT_EQUAL(owner_of(crystal), original_owner, "refusal preserves the original custody stamp")
	TEST_ASSERT(!QDELETED(crystal), "refusal preserves the original crystal")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(T, /obj/effect/effect/sparks) - before), 0, "refusal creates no real spark effects")
	TEST_ASSERT(!QDELETED(control), "an independent original crystal is untouched")
	remove_trait(crystal, TRAIT_NODROP, "interim_bluespace_crystal_sticky_self")
	TEST_ASSERT_NULL(actor.release_refusal(crystal, actor), "the same real crystal is now releasable")
	var/datum/op_result/allowed = test_click(actor, crystal, crystal, GESTURE_SELF)
	TEST_ASSERT_NOTNULL(allowed, "allowed actual self-use resolves")
	TEST_ASSERT_EQUAL(allowed.outcome, ACT_COMMITTED, "the same native self-use commits after release is allowed")
	TEST_ASSERT(QDELETED(crystal), "allowed crushing consumes the exact original crystal")
	TEST_ASSERT_NULL(actor.get_active_hand(), "allowed consumption clears the actual original hand")
	TEST_ASSERT(!QDELETED(control), "allowed crushing preserves the independent control crystal")
