/// Cracking a real modified collar must consume its original before producing a malfunctioning replacement.
/datum/unit_test/interim_bluespace_collar_sticky_cracking/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/clothing/accessory/collar/shock/bluespace/modified/collar = allocate(/obj/item/clothing/accessory/collar/shock/bluespace/modified, T)
	var/obj/item/tool/wrench/tool = allocate(/obj/item/tool/wrench, T)
	TEST_ASSERT(user.put_in_inactive_hand(collar), "the actor holds exact original collar in its other hand")
	TEST_ASSERT(user.put_in_active_hand(tool), "the actor holds real wrench for public tool interaction")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/clothing/accessory/collar/shock/bluespace/malfunctioning)), 0, "actual fixture starts without cracked collar products")
	add_trait(collar, TRAIT_NODROP, "interim_collar_cracking")
	TEST_ASSERT(user.release_refusal(collar, user), "actual inventory refuses sticky original collar consumption")
	collar.interaction_tool_act(user, tool, TOOL_WRENCH)
	TEST_ASSERT(!QDELETED(collar), "refused cracking preserves exact original collar")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), collar, "refused cracking preserves original collar hand")
	TEST_ASSERT_EQUAL(collar.loc, user, "refused cracking preserves inventory containment")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "refused cracking preserves original wrench hand")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/clothing/accessory/collar/shock/bluespace/malfunctioning)), 0, "refused original consumption creates no cracked collar")
	remove_trait(collar, TRAIT_NODROP, "interim_collar_cracking")
	collar.interaction_tool_act(user, tool, TOOL_WRENCH)
	TEST_ASSERT(QDELETED(collar), "allowed cracking consumes exact original collar")
	TEST_ASSERT_NULL(user.get_inactive_hand(), "allowed consumption clears original collar hand")
	TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "allowed cracking preserves original wrench hand")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/clothing/accessory/collar/shock/bluespace/malfunctioning)), 1, "one consumed original creates exactly one actual cracked collar")
	var/obj/item/clothing/accessory/collar/shock/bluespace/malfunctioning/product = locate_within(T, /obj/item/clothing/accessory/collar/shock/bluespace/malfunctioning)
	TEST_ASSERT_NOTNULL(product, "actual cracking creates a real surviving replacement")
	own(product)
	TEST_ASSERT_EQUAL(product.type, /obj/item/clothing/accessory/collar/shock/bluespace/malfunctioning, "actual replacement has exact declared cracked type")
	TEST_ASSERT_EQUAL(product.loc, T, "actual replacement occupies original collar turf")
	TEST_ASSERT(!QDELETED(product), "actual replacement survives initialization")
