/// A real filing cabinet respects document release and returns the original written sheet.
/datum/unit_test/interim_filing_cabinet_sticky_document/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/filingcabinet/cabinet = allocate(/obj/structure/filingcabinet, T)
	TEST_ASSERT_EQUAL(contents_count(cabinet), 0, "the actual cabinet is initialized before document creation and has no collected files")
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	paper.info = "Original filing cabinet document"
	TEST_ASSERT(user.put_in_active_hand(paper), "the actor holds the exact original written sheet")
	add_trait(paper, TRAIT_NODROP, "interim_cabinet_sticky")
	TEST_ASSERT(user.release_refusal(paper, user), "actual inventory refuses sticky sheet release")
	test_op_handler(cabinet, "interaction_item", user, paper)
	TEST_ASSERT_EQUAL(user.get_active_hand(), paper, "refused filing preserves original hand")
	TEST_ASSERT_EQUAL(paper.loc, user, "refused filing preserves actual inventory containment")
	TEST_ASSERT_EQUAL(contents_count(cabinet), 0, "refused filing contains no original sheet")
	remove_trait(paper, TRAIT_NODROP, "interim_cabinet_sticky")
	test_op_handler(cabinet, "interaction_item", user, paper)
	TEST_ASSERT_EQUAL(paper.loc, cabinet, "allowed filing physically contains original sheet")
	TEST_ASSERT_EQUAL(contents_count(cabinet), 1, "allowed filing contains exactly one original file")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed filing clears actual source hand")
	TEST_ASSERT_NULL(owner_of(paper), "filing preserves its existing unowned containment policy")
	cabinet.ui_act_remove_object(user, list("ref" = paper), null, null, "remove_object")
	TEST_ASSERT_EQUAL(user.get_active_hand(), paper, "public retrieval returns exact original file")
	TEST_ASSERT_EQUAL(paper.loc, user, "public retrieval restores original inventory containment")
	TEST_ASSERT_EQUAL(contents_count(cabinet), 0, "public retrieval removes original file from cabinet contents")
	TEST_ASSERT_EQUAL(paper.info, "Original filing cabinet document", "filing and retrieval preserve exact original written information")
	qdel(cabinet)
	TEST_ASSERT(!QDELETED(paper), "returned original document survives empty cabinet teardown")
