/// The actual floor item's wrench action refunds one wood sheet only after its real scaled tool task consumes the original marker.
/datum/unit_test/om/interim_gravemarker_item_timed_dismantle/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/material/gravemarker/marker = allocate(/obj/item/material/gravemarker, T, MAT_WOOD)
	var/obj/item/tool/wrench/wrench = allocate(/obj/item/tool/wrench, T)
	made += list(user, marker, wrench)
	TEST_ASSERT_EQUAL(marker.material, get_material_by_name(MAT_WOOD), "the actual item marker has its configured wood material")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/wood)), 0, "the actual fixture begins without refunded wood")
	TEST_ASSERT(user.put_in_active_hand(wrench), "the actual dismantling actor holds the real wrench")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual dismantling actor starts capable")
	var/dismantle_delay = tool_delay(user, wrench, marker.material.hardness, TOOL_WRENCH)
	TEST_ASSERT(dismantle_delay > 0, "the actual wooden marker has a positive scaled wrench delay")
	marker.wrench_act(user, wrench)
	TEST_ASSERT(LAZYLEN(user.do_afters), "the real wrench entry starts its actual timed dismantling task")
	TEST_ASSERT(!QDELETED(marker), "starting actual dismantling preserves the marker until completion")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/wood)), 0, "starting actual dismantling refunds no wood early")
	scheduler_advance((dismantle_delay + 1 SECOND) / (1 SECOND))
	own_turf_contents(T)
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual dismantling actor remains capable through its single short task")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "actual dismantling releases its completed task")
	TEST_ASSERT(QDELETED(marker), "actual timed dismantling consumes the original item marker")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/wood)), 1, "actual timed dismantling produces exactly one wood stack")
	var/obj/item/stack/material/wood/refund = locate_within(T, /obj/item/stack/material/wood)
	TEST_ASSERT_EQUAL(refund.get_amount(), 1, "actual timed dismantling refunds exactly one wood sheet")
	TEST_ASSERT_EQUAL(refund.loc, T, "actual timed dismantling refunds wood on the original marker floor")
	TEST_ASSERT_EQUAL(user.get_active_hand(), wrench, "actual timed dismantling preserves the exact held wrench")

/// A real sticky item marker in the actor's other hand cannot be consumed or refunded when its actual wrench task completes.
/datum/unit_test/om/interim_gravemarker_item_sticky_refusal/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/material/gravemarker/marker = allocate(/obj/item/material/gravemarker, T, MAT_WOOD)
	var/obj/item/tool/wrench/wrench = allocate(/obj/item/tool/wrench, T)
	made += list(user, marker, wrench)
	marker.grave_name = "Remembered"
	marker.epitaph = "Preserved through refusal"
	TEST_ASSERT(user.put_in_active_hand(wrench), "the actual refusal actor holds the real wrench")
	TEST_ASSERT(user.put_in_inactive_hand(marker), "the actual refusal actor holds the marker in the other hand")
	add_trait(marker, TRAIT_NODROP, "interim_gravemarker_item_sticky_refusal")
	TEST_ASSERT(user.release_refusal(marker, user), "the actual inventory genuinely refuses release of the sticky marker")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual refusal actor starts capable")
	var/dismantle_delay = tool_delay(user, wrench, marker.material.hardness, TOOL_WRENCH)
	TEST_ASSERT(dismantle_delay > 0, "the actual sticky wooden marker has a positive scaled tool delay")
	marker.wrench_act(user, wrench)
	TEST_ASSERT(LAZYLEN(user.do_afters), "the real held-marker wrench entry starts its timed task")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/wood)), 0, "pending sticky-marker dismantling refunds no material early")
	scheduler_advance((dismantle_delay + 1 SECOND) / (1 SECOND))
	own_turf_contents(T)
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual refusal actor remains capable so release refusal is exercised")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "the actual completed sticky-marker task releases its pending action")
	TEST_ASSERT(!QDELETED(marker), "actual checked consumption refuses to delete the sticky item marker")
	TEST_ASSERT_EQUAL(marker.loc, user, "actual refusal preserves the original item's actor")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), marker, "actual refusal preserves the marker's exact inactive hand")
	TEST_ASSERT_EQUAL(user.get_active_hand(), wrench, "actual refusal preserves the actor's exact wrench")
	TEST_ASSERT_EQUAL(marker.grave_name, "Remembered", "actual refusal preserves the original carved name")
	TEST_ASSERT_EQUAL(marker.epitaph, "Preserved through refusal", "actual refusal preserves the original carved epitaph")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/wood)), 0, "actual refused consumption cannot create a material refund")
	remove_trait(marker, TRAIT_NODROP, "interim_gravemarker_item_sticky_refusal")
