/// Actual last-item removal leaves one wrapper only after the empty package can be consumed.
/datum/unit_test/interim_mre_wrapper_consumption/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/box/tgmc_mre/package = allocate(/obj/item/storage/box/tgmc_mre, T)
	TEST_ASSERT(user.put_in_active_hand(package), "the actual actor holds the original meal package")
	var/list/items = package.slot_contents(CONTAINER_SLOT_STORAGE)
	items = items.Copy()
	TEST_ASSERT_EQUAL(length(items), 5, "the actual meal initializes with its five real items")
	var/removed = 0
	for(var/obj/item/item as anything in items)
		TEST_ASSERT(package.remove_from_storage(item, T, user), "each actual meal item leaves through the public storage boundary")
		removed++
		TEST_ASSERT_EQUAL(item.loc, T, "the exact actual meal item is returned to the floor")
		if(removed < length(items))
			TEST_ASSERT(!QDELETED(package), "partial actual removal preserves the package")
			TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/trash/tgmc_mre)), 0, "partial actual removal creates no wrapper")
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(package), "actual last-item removal consumes the empty package")
	TEST_ASSERT_NULL(user.get_active_hand(), "actual package consumption clears its original hand slot")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/trash/tgmc_mre)), 1, "actual successful consumption creates exactly one wrapper")

/datum/unit_test/interim_mre_wrapper_release_refusal/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/box/tgmc_mre/package = allocate(/obj/item/storage/box/tgmc_mre, T)
	TEST_ASSERT(user.put_in_active_hand(package), "the actual actor holds the sticky meal package")
	add_trait(package, TRAIT_NODROP, "interim_mre_wrapper_release_refusal")
	TEST_ASSERT(user.release_refusal(package, user), "the actual package genuinely cannot be released")
	var/list/items = package.slot_contents(CONTAINER_SLOT_STORAGE)
	items = items.Copy()
	TEST_ASSERT_EQUAL(length(items), 5, "the actual sticky package contains its five real items")
	for(var/obj/item/item as anything in items)
		TEST_ASSERT(package.remove_from_storage(item, T, user), "actual contained items remain removable from the sticky package")
		TEST_ASSERT_EQUAL(item.loc, T, "actual contained-item removal returns the exact item")
	own_turf_contents(T)
	TEST_ASSERT(!QDELETED(package), "actual release refusal preserves the empty sticky package")
	TEST_ASSERT_EQUAL(length(package.slot_contents(CONTAINER_SLOT_STORAGE)), 0, "the preserved actual package is genuinely empty")
	TEST_ASSERT_EQUAL(user.get_active_hand(), package, "actual release refusal preserves the exact package hand slot")
	TEST_ASSERT_EQUAL(package.loc, user, "actual release refusal preserves the original package holder")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/trash/tgmc_mre)), 0, "refused package consumption cannot create a wrapper")
	remove_trait(package, TRAIT_NODROP, "interim_mre_wrapper_release_refusal")
