/// Completed construction transfers only the player's installed board and parts.
/datum/unit_test/interim_machine_frame_finalization/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/structure/frame/frame = allocate(/obj/structure/frame, T)
	var/obj/item/circuitboard/autolathe/board = allocate(/obj/item/circuitboard/autolathe, T)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, T, 6)
	var/obj/item/tool/screwdriver/tool = allocate(/obj/item/tool/screwdriver, T)
	frame.set_bulk_material(MAT_STEEL, 123)
	frame.pixel_x = 3
	frame.pixel_y = -4
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/anchor), "Fixture anchoring must succeed")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/insert_board, board), "Fixture board insertion must succeed")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/fasten_board), "Fixture board fastening must succeed")
	TEST_ASSERT(interim_construction_step(frame, actor, /datum/interaction/construction/frame/wire, cable), "Fixture wiring must succeed")
	var/datum/construction_graph/graph = construction_graph_of(frame)
	var/datum/interaction/construction/finish
	for(var/datum/interaction/construction/edge as anything in graph.edges)
		if(edge.type == /datum/interaction/construction/frame/finish_machine)
			finish = edge
	TEST_ASSERT(finish, "The real frame graph must contain machine finalization")
	TEST_ASSERT_NOTNULL(finish.why_not(actor, frame, tool), "Missing parts must refuse finalization through its requirement")
	TEST_ASSERT(!finish.traverse(frame, actor, tool), "Completion must independently reject missing parts")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "Refused completion must preserve the wired frame")
	TEST_ASSERT_EQUAL(frame.circuit, board, "Refused completion must preserve board ownership")
	TEST_ASSERT_EQUAL(board.loc, frame, "Refused completion must preserve physical board containment")
	TEST_ASSERT_NULL(locate_within(T, /obj/machinery/autolathe), "Refused completion must create no machine")
	var/list/installed = list()
	for(var/part_type in board.req_components)
		for(var/part_number in 1 to board.req_components[part_type])
			var/obj/item/part = allocate(part_type, T)
			TEST_ASSERT(actor.put_in_active_hand(part), "The actor must hold each real construction part")
			var/remaining_before = frame.req_components[part_type]
			frame.interaction_item(actor, part, null)
			TEST_ASSERT_EQUAL(part.loc, frame, "Part insertion must physically place the part in the frame")
			TEST_ASSERT(part in frame.components, "The frame must own each installed part")
			TEST_ASSERT_NULL(actor.get_active_hand(), "Insertion must release the actor's hand")
			TEST_ASSERT_EQUAL(frame.req_components[part_type], remaining_before - 1, "Insertion must decrement the corresponding requirement exactly once")
			installed += part
	TEST_ASSERT_EQUAL(length(installed), 5, "The real autolathe board must require five stock parts")
	TEST_ASSERT_NULL(finish.why_not(actor, frame, tool), "Installed parts must satisfy finalization")
	var/frame_handle = om_handle(frame)
	var/completed = finish.traverse(frame, actor, tool)
	// Register generated successors before any assertion can terminate the test.
	own_turf_contents(T)
	TEST_ASSERT(completed, "The complete frame must finish through the real construction edge")
	TEST_ASSERT(QDELETED(frame), "Successful completion must delete the old frame")
	TEST_ASSERT_NULL(om_resolve(frame_handle), "A frame handle must end when its successor belongs to the machinery family")
	var/obj/machinery/autolathe/machine = locate_within(T, /obj/machinery/autolathe)
	TEST_ASSERT(machine, "Successful completion must create the board's real machine type")
	TEST_ASSERT_EQUAL(machine.circuit, board, "The successor must own the exact installed board")
	TEST_ASSERT_EQUAL(board.loc, machine, "The installed board must physically reside in the successor")
	var/list/internals = machine.slot_contents(CONTAINER_SLOT_INTERNALS)
	TEST_ASSERT(board in internals, "The installed board must enter the real internal slot")
	TEST_ASSERT_EQUAL(length(machine.component_parts), 5, "Default stock parts must not duplicate the player's installed parts")
	for(var/obj/item/part as anything in installed)
		TEST_ASSERT(!QDELETED(part), "Frame deletion must preserve every installed part")
		TEST_ASSERT_EQUAL(part.loc, machine, "Every installed part must physically reside in the successor")
		TEST_ASSERT(part in machine.component_parts, "The successor must own each exact installed part")
		TEST_ASSERT(part in internals, "Every installed part must enter the real internal slot")
	TEST_ASSERT_EQUAL(machine.material_bulk_material, MAT_STEEL, "Completion must preserve the frame's bulk material")
	TEST_ASSERT_EQUAL(machine.material_total, 123, "Completion must preserve the frame's material quantity")
	TEST_ASSERT_EQUAL(machine.pixel_x, 3, "Completion must preserve the frame's horizontal offset")
	TEST_ASSERT_EQUAL(machine.pixel_y, -4, "Completion must preserve the frame's vertical offset")
