/// The real harvester battery bay respects held release, refuses replacing an occupied bay and ejects the exact original charge.
/datum/unit_test/interim_artifact_harvester_sticky_battery/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/artifact_harvester/harvester = allocate(/obj/machinery/artifact_harvester, T)
	var/obj/item/anobattery/battery = allocate(/obj/item/anobattery, T)
	var/obj/item/anobattery/other = allocate(/obj/item/anobattery, T)
	TEST_ASSERT(battery.capacity > 0, "the actual battery has positive declared capacity")
	battery.stored_charge = battery.capacity / 2
	var/original_charge = battery.stored_charge
	TEST_ASSERT_NULL(harvester.inserted_battery(), "the actual harvester starts with an empty battery bay")
	TEST_ASSERT_EQUAL(harvester.harvesting, 0, "the actual harvester starts outside harvesting or emission")
	TEST_ASSERT(user.put_in_active_hand(battery), "the actor holds the original charged battery")
	add_trait(battery, TRAIT_NODROP, "interim_harvester_sticky")
	TEST_ASSERT(user.release_refusal(battery, user), "the actual inventory refuses the sticky battery's release")
	test_op_handler(harvester, "interaction_artifact_harvester_use_item", user, battery)
	TEST_ASSERT_EQUAL(user.get_active_hand(), battery, "refused insertion preserves the exact original hand")
	TEST_ASSERT_EQUAL(battery.loc, user, "refused insertion preserves actual inventory containment")
	TEST_ASSERT_NULL(harvester.inserted_battery(), "refused insertion leaves the actual harvester bay empty")
	TEST_ASSERT_EQUAL(battery.stored_charge, original_charge, "refused insertion preserves the actual stored charge")
	remove_trait(battery, TRAIT_NODROP, "interim_harvester_sticky")
	test_op_handler(harvester, "interaction_artifact_harvester_use_item", user, battery)
	TEST_ASSERT_EQUAL(harvester.inserted_battery(), battery, "allowed insertion records the exact original battery")
	TEST_ASSERT_EQUAL(battery.loc, harvester, "allowed insertion contains the original battery")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears the original source hand")
	TEST_ASSERT_NULL(owner_of(battery), "the actual harvester preserves its existing non-owning relation policy")
	TEST_ASSERT(user.put_in_active_hand(other), "the actor holds a different real replacement battery")
	test_op_handler(harvester, "interaction_artifact_harvester_use_item", user, other)
	TEST_ASSERT_EQUAL(harvester.inserted_battery(), battery, "occupied-bay refusal preserves the original installed battery")
	TEST_ASSERT_EQUAL(battery.loc, harvester, "occupied-bay refusal preserves actual original containment")
	TEST_ASSERT_EQUAL(user.get_active_hand(), other, "occupied-bay refusal preserves the exact replacement hand")
	TEST_ASSERT_EQUAL(other.loc, user, "occupied-bay refusal preserves the replacement's actual inventory containment")
	op_ui_act(user, harvester, "ejectbattery")
	TEST_ASSERT_NULL(harvester.inserted_battery(), "actual UI ejection clears the original battery relation")
	TEST_ASSERT_EQUAL(battery.loc, T, "actual UI ejection returns the original charged battery to the floor")
	TEST_ASSERT_EQUAL(battery.stored_charge, original_charge, "insertion replacement refusal and ejection spend no original charge")
	TEST_ASSERT_EQUAL(harvester.harvesting, 0, "actual ejection leaves harvesting and emission inactive")
	qdel(harvester)
	TEST_ASSERT(!QDELETED(battery) && !QDELETED(other), "empty-harvester teardown preserves both original batteries")
