/// Service-fabricator matter must be backed by consumption of its original cartridge.
/datum/unit_test/interim_rsf_sticky_matter_refill/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/rsf/device = allocate(/obj/item/rsf, T)
	var/obj/item/rcd_ammo/cartridge = allocate(/obj/item/rcd_ammo, T)
	TEST_ASSERT_EQUAL(device.stored_matter, initial(device.stored_matter), "the real device starts with its declared matter supply")
	device.stored_matter = 20
	TEST_ASSERT(user.put_in_active_hand(cartridge), "the actor holds the original refill cartridge")
	add_trait(cartridge, TRAIT_NODROP, "interim_rsf_sticky")
	TEST_ASSERT(user.release_refusal(cartridge, user), "actual inventory refuses sticky cartridge consumption")
	test_op_handler(device, "interaction_item", user, cartridge)
	TEST_ASSERT_EQUAL(device.stored_matter, 20, "refused consumption grants no fabrication matter")
	TEST_ASSERT(!QDELETED(cartridge), "refused refill preserves original cartridge")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cartridge, "refused refill preserves exact source hand")
	TEST_ASSERT_EQUAL(cartridge.loc, user, "refused refill preserves inventory containment")
	remove_trait(cartridge, TRAIT_NODROP, "interim_rsf_sticky")
	test_op_handler(device, "interaction_item", user, cartridge)
	TEST_ASSERT(QDELETED(cartridge), "allowed refill consumes exact original cartridge")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed refill clears actual source hand")
	TEST_ASSERT_EQUAL(device.stored_matter, 30, "one consumed cartridge grants exactly ten matter units")
	var/obj/item/rcd_ammo/replacement = allocate(/obj/item/rcd_ammo, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds an actual replacement cartridge")
	test_op_handler(device, "interaction_item", user, replacement)
	TEST_ASSERT(!QDELETED(replacement), "full device refuses original replacement intact")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "full-device refusal preserves replacement hand")
	TEST_ASSERT_EQUAL(device.stored_matter, 30, "full-device refusal grants no extra fabrication matter")
