/// The real detached-organ tick disposes healed owned wounds and preserves original live wounds.
/datum/unit_test/interim2_detached_wound_owned_expiry/Run()
	var/turf/T = test_floor()
	var/obj/item/organ/external/arm/arm = allocate(/obj/item/organ/external/arm, T)
	TEST_ASSERT_NULL(arm.owner, "The real floor-born arm must remain detached from a body")
	TEST_ASSERT_EQUAL(arm.receive_injury(INJURY_CUT, 5, null, INJURE_CONTINUOUS), 5, "Actual continuous injury must create five cut damage")
	TEST_ASSERT_EQUAL(arm.receive_injury(INJURY_BURN, 5, null, INJURE_CONTINUOUS), 5, "Actual continuous injury must create five burn damage")
	TEST_ASSERT_EQUAL(arm.receive_injury(INJURY_BLUNT, 7, null, INJURE_CONTINUOUS), 7, "Actual continuous injury must create seven independent bruise damage")
	var/list/wounds = arm.get_wounds()
	TEST_ASSERT_EQUAL(length(wounds), 3, "The actual damage paths must construct three distinct wounds")
	var/datum/affliction/wound/cut/cut
	var/datum/affliction/wound/burn/burn
	var/datum/affliction/wound/bruise/bruise
	for(var/datum/affliction/wound/W in wounds)
		own(W)
		TEST_ASSERT_EQUAL(owner_of(W), arm, "The detached arm must own every real injury record")
		TEST_ASSERT_EQUAL(W.location, arm, "Each original wound must locate the actual detached arm")
		if(istype(W, /datum/affliction/wound/cut))
			cut = W
		else if(istype(W, /datum/affliction/wound/burn))
			burn = W
		else if(istype(W, /datum/affliction/wound/bruise))
			bruise = W
	TEST_ASSERT(istype(cut) && istype(burn) && istype(bruise), "Actual injury selection must provide all three canonical wound families")
	TEST_ASSERT_EQUAL(cut.heal_damage(5), 0, "Real wound healing must spend its exact five-unit cut budget")
	TEST_ASSERT_EQUAL(burn.heal_damage(5), 0, "Real wound healing must spend its exact five-unit burn budget")
	TEST_ASSERT_EQUAL(cut.severity, 0, "Actual healing must synchronize cut severity to zero")
	TEST_ASSERT_EQUAL(burn.severity, 0, "Actual healing must synchronize burn severity to zero")
	TEST_ASSERT(!QDELETED(cut) && !QDELETED(burn), "Healing must leave disposal to the real detached tick")
	arm.tick_detached_afflictions()
	TEST_ASSERT(QDELETED(cut) && QDELETED(burn), "One actual detached tick must dispose of both exact healed original wounds")
	TEST_ASSERT_NULL(owner_of(cut), "The expired cut must lose its ownership stamp")
	TEST_ASSERT_NULL(owner_of(burn), "The expired burn must lose its ownership stamp")
	TEST_ASSERT_EQUAL(length(arm.detached_afflictions), 1, "The actual owned index must retain only the live wound")
	TEST_ASSERT_EQUAL(arm.detached_afflictions[1], bruise, "The exact independent live bruise must survive cleanup")
	TEST_ASSERT(!QDELETED(bruise), "The original live wound must remain alive")
	TEST_ASSERT_EQUAL(owner_of(bruise), arm, "Cleanup must preserve the original live wound's owner")
	TEST_ASSERT_EQUAL(bruise.location, arm, "Cleanup must preserve the original live wound's location")
	TEST_ASSERT_EQUAL(bruise.damage, 7, "The no-progression wound tick must preserve exact live damage")
	TEST_ASSERT_EQUAL(arm.get_trauma(), 7, "Real integrity recomputation must reflect only the surviving bruise")
	TEST_ASSERT_EQUAL(arm.get_burn(), 0, "Real integrity recomputation must omit the expired burn")
	arm.tick_detached_afflictions()
	TEST_ASSERT_EQUAL(arm.detached_afflictions[1], bruise, "A repeated real tick must preserve the same live identity")
	TEST_ASSERT(consume(arm), "Actual detached floor arm disposal must succeed")
	TEST_ASSERT(QDELETED(bruise), "Actual organ teardown must dispose of its exact remaining owned wound")
