/datum/unit_test/interim_strangerock_mining_release/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/strangerock/rock = allocate(/obj/item/strangerock, T, ARCHAEO_BOWL)
	var/list/products = contents_of(rock, /obj/item)
	for(var/obj/item/I as anything in products)
		own(I)
	TEST_ASSERT_EQUAL(length(products), 1, "The actual configured rock constructor creates one real concealed product")
	var/obj/item/product = products[1]
	TEST_ASSERT(product && !QDELETED(product) && product.loc == rock, "The actual original concealed product is alive inside its real source")
	var/obj/item/pickaxe/brush/tool = allocate(/obj/item/pickaxe/brush, T)
	TEST_ASSERT(actor.put_in_active_hand(tool), "The actual actor holds its original archaeological brush")
	TEST_ASSERT(actor.put_in_inactive_hand(rock), "The actual rock occupies its original real source slot")
	add_trait(rock, TRAIT_NODROP, "interim_strangerock_mining_release")
	TEST_ASSERT(rock.loc.release_refusal(rock, actor), "The actual sticky held source genuinely refuses release")
	TEST_ASSERT_EQUAL(rock.strangerock_use(actor, tool), OP_PASS, "The actual refused mining action retains its original handled result")
	TEST_ASSERT(!QDELETED(rock) && rock.loc == actor, "Actual refusal preserves the exact original held rock")
	TEST_ASSERT_EQUAL(actor.get_inactive_hand(), rock, "Actual refusal preserves the exact original source slot")
	TEST_ASSERT(!QDELETED(product) && product.loc == rock, "Actual refusal preserves the exact original concealed product inside its original source")
	TEST_ASSERT_EQUAL(length(contents_of(rock, /obj/item)), 1, "Actual refusal leaves the original concealed contents unchanged")
	remove_trait(rock, TRAIT_NODROP, "interim_strangerock_mining_release")
	TEST_ASSERT(actor.drop_from_inventory(rock, T), "The actual unblocked rock returns to its original floor")
	TEST_ASSERT_EQUAL(rock.strangerock_use(actor, tool), OP_PASS, "Actual floor mining retains its original handled result")
	TEST_ASSERT(QDELETED(rock), "Actual floor mining consumes its exact original source")
	TEST_ASSERT(!QDELETED(product) && product.loc == T, "Actual floor mining releases its exact original concealed product alive onto its original floor")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), tool, "Actual mining preserves the exact original held brush")
	TEST_ASSERT(!QDELETED(actor) && !QDELETED(tool), "Actual mining preserves both original participants")
