/// Replacing an actual tucked mask preserves the secured original on refusal and returns it through the real removal path on success.
/datum/unit_test/interim_gaiter_mask_replacement_refund/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/clothing/accessory/gaiter/gaiter = allocate(/obj/item/clothing/accessory/gaiter, T)
	var/obj/item/clothing/mask/breath/original = allocate(/obj/item/clothing/mask/breath, T)
	var/obj/item/clothing/mask/breath/replacement = allocate(/obj/item/clothing/mask/breath, T)
	TEST_ASSERT(user.put_in_active_hand(original), "the actor holds its original real mask")
	test_op_handler(gaiter, "gaiter_tuck_mask_item", user, original)
	TEST_ASSERT_EQUAL(gaiter.breathmask(), original, "the real first insertion records the original mask")
	test_op_handler(gaiter, "gaiter_adjust_self", user, null)
	TEST_ASSERT(gaiter.item_flags & AIRTIGHT, "actual adjustment secures the original mask")
	var/secured_flags = gaiter.item_flags
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds the actual incoming replacement mask")
	add_trait(replacement, TRAIT_NODROP, "interim_gaiter_sticky_replacement")
	TEST_ASSERT(user.release_refusal(replacement, user), "actual inventory refuses the sticky incoming replacement")
	test_op_handler(gaiter, "gaiter_tuck_mask_item", user, replacement)
	TEST_ASSERT_EQUAL(gaiter.breathmask(), original, "refused replacement preserves the exact original mask relation")
	TEST_ASSERT_EQUAL(original.loc, gaiter, "refused replacement keeps the original secured mask inside")
	TEST_ASSERT_EQUAL(replacement.loc, user, "refused replacement keeps the incoming mask in actual inventory")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "refused replacement preserves the exact incoming hand")
	TEST_ASSERT_EQUAL(gaiter.item_flags, secured_flags, "refused replacement preserves every original secured material flag")
	TEST_ASSERT(gaiter.breath_masked, "refused replacement preserves original mask presence")
	remove_trait(replacement, TRAIT_NODROP, "interim_gaiter_sticky_replacement")
	test_op_handler(gaiter, "gaiter_tuck_mask_item", user, replacement)
	TEST_ASSERT_EQUAL(gaiter.breathmask(), replacement, "allowed replacement records the original incoming mask")
	TEST_ASSERT_EQUAL(replacement.loc, gaiter, "allowed replacement contains the original incoming mask")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed replacement clears its original incoming hand")
	TEST_ASSERT_EQUAL(original.loc, T, "allowed replacement refunds the former mask through the actual removal route")
	TEST_ASSERT(!QDELETED(original), "allowed replacement does not consume the refunded original mask")
	TEST_ASSERT(gaiter.breath_masked, "allowed replacement records its actual new mask presence")
	TEST_ASSERT(!(gaiter.item_flags & FLEXIBLEMATERIAL), "the newly tucked replacement keeps the gaiter inflexible")
	TEST_ASSERT(!(gaiter.item_flags & AIRTIGHT), "removing the secured original clears its old airtightness before a new adjustment")
	test_op_handler(gaiter, "gaiter_remove_mask_alt", user, null)
	TEST_ASSERT_EQUAL(replacement.loc, T, "actual final removal returns the original replacement mask")
	TEST_ASSERT_NULL(gaiter.breathmask(), "actual final removal clears the relation")
	TEST_ASSERT(!gaiter.breath_masked, "actual final removal clears mask presence")
	TEST_ASSERT(gaiter.item_flags & FLEXIBLEMATERIAL, "actual final removal restores flexibility")
	qdel(gaiter)
	TEST_ASSERT(!QDELETED(original) && !QDELETED(replacement), "empty gaiter teardown preserves both returned original masks")
