/// Actual teshari species and real holder construction exercise both supported scoop actors.
/datum/unit_test/interim_teshari_scoop_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/micro = allocate(/mob/living/carbon/human, T, SPECIES_TESHARI)
	var/mob/living/carbon/human/grabber = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/other = allocate(/mob/living/carbon/human, T)
	micro.set_combat_mode(FALSE)
	grabber.set_combat_mode(FALSE)
	TEST_ASSERT(micro.species.is_micro_carry(micro) && micro.holder_type, "the actual teshari species supplies real micro-carry and holder support")
	TEST_ASSERT(micro.pickup_pref && grabber.pickup_active, "actual default preferences enable both supported pickup actors")
	TEST_ASSERT(micro.Adjacent(grabber), "actual scoop participants begin adjacent")
	TEST_ASSERT_EQUAL(micro.micro_scoop_with_actor(other, grabber), FALSE, "unrelated actor selects original native parent fallback")
	TEST_ASSERT_EQUAL(micro.loc, T, "unrelated actor cannot scoop the actual micro")
	grabber.toggle_pickups()
	TEST_ASSERT(!grabber.pickup_active, "the actual pickup toggle disables grabber-initiated scooping")
	micro.micro_scoop_with_actor(grabber, grabber)
	TEST_ASSERT_EQUAL(micro.loc, T, "actual disabled grabber pickup leaves the micro on its floor")
	grabber.toggle_pickups()
	TEST_ASSERT(grabber.pickup_active, "the actual pickup toggle enables the original grabber guard")
	TEST_ASSERT_EQUAL(micro.micro_scoop_with_actor(grabber, grabber), TRUE, "actual grabber scoop consumes native drag")
	var/obj/item/holder/holder = micro.loc
	TEST_ASSERT(istype(holder), "actual successful scoop constructs a real holder")
	own(holder)
	TEST_ASSERT_EQUAL(holder.held_mob, micro, "the actual holder contains the exact scooped micro")
	TEST_ASSERT(grabber.item_is_in_hands(holder), "actual grabber scoop places its concrete holder into the initiating grabber's hands")
	TEST_ASSERT_EQUAL(holder.loc, grabber, "actual holder remains physically carried by its grabber")
	TEST_ASSERT(!other.item_is_in_hands(holder), "unrelated actor receives no actual holder")
	TEST_ASSERT(grabber.unEquip(holder), "actual release drops the holder through the inventory API")
	test_time(1 SECOND)
	TEST_ASSERT(QDELETED(holder), "the actual floor holder cleanup expires its wrapper")
	TEST_ASSERT_EQUAL(micro.loc, T, "actual holder teardown releases the exact micro onto its floor")
	grabber.toggle_pickups()
	TEST_ASSERT(!grabber.pickup_active, "self-requested scoop tests the real disabled grabber pickup preference")
	TEST_ASSERT_EQUAL(micro.micro_scoop_with_actor(micro, grabber), TRUE, "actual micro-requested scoop bypasses only the original grabber pickup toggle")
	var/obj/item/holder/self_holder = micro.loc
	TEST_ASSERT(istype(self_holder), "actual self-request constructs a distinct real holder")
	own(self_holder)
	TEST_ASSERT(self_holder != holder, "the second actual scoop creates a distinct wrapper")
	TEST_ASSERT_EQUAL(self_holder.held_mob, micro, "actual self-request retains the exact carried micro")
	TEST_ASSERT_EQUAL(self_holder.loc, grabber, "actual self-request chooses the explicitly selected grabber")
	TEST_ASSERT(!other.item_is_in_hands(self_holder), "self-request never transfers its holder to the unrelated actor")
