/// Destroying a real dark node unlinks its original tile and lets the actual delayed withering finish.
/datum/unit_test/interim_dark_node_withering/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/structure/prop/dark_node/node = allocate(/obj/structure/prop/dark_node, T)
	var/obj/effect/dark/floor/tile = allocate(/obj/effect/dark/floor, T, null, node)
	TEST_ASSERT(!QDELETED(tile), "actual darkness tile initializes on a real floor")
	TEST_ASSERT_EQUAL(tile.linked_node, node, "actual floor initialization links its configured dark node")
	TEST_ASSERT((tile in node.children_effects), "actual paired relation registers the original child")
	TEST_ASSERT_EQUAL(tile.health, 10, "actual dark tile starts at its declared health")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(tile), 0, "linked real tile starts without a withering timer")
	TEST_ASSERT(consume(node), "actual public node consumption succeeds")
	TEST_ASSERT(QDELETED(node), "actual node teardown removes the original node")
	TEST_ASSERT(!QDELETED(tile), "actual node teardown initially preserves the independent child")
	TEST_ASSERT_NULL(tile.linked_node, "actual node teardown unlinks the paired child relation")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(tile), 1, "actual node teardown schedules one real withering timer")
	test_time(1 SECOND)
	TEST_ASSERT(!QDELETED(tile), "real child survives before the minimum withering delay")
	TEST_ASSERT_EQUAL(tile.loc, T, "unlinked child remains on its original floor while withering")
	test_time(6 SECONDS)
	TEST_ASSERT(QDELETED(tile), "actual child withers by the maximum configured seven-second delay")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(tile), 0, "actual withering completion leaves no child timer")

/datum/unit_test/interim_dark_lost_turf/Run()
	var/obj/effect/dark/darkness = allocate(/obj/effect/dark, run_loc_floor_bottom_left)
	TEST_ASSERT_EQUAL(darkness.health, 10, "actual darkness starts with nonzero health")
	darkness.moveToNullspace()
	TEST_ASSERT_NULL(get_turf(darkness), "actual relocation removes the darkness's world turf")
	darkness.light_check()
	TEST_ASSERT_EQUAL(darkness.health, 0, "actual lost-turf check depletes the darkness health")
	TEST_ASSERT(QDELETED(darkness), "actual zero-health lost-turf check consumes the darkness")
