/// Copying a real potion must consume its original mimic agent before creating a second potion.
/datum/unit_test/interim_slime_potion_sticky_mimic/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/slimepotion/enhancer/original = allocate(/obj/item/slimepotion/enhancer, T)
	var/obj/item/slimepotion/mimic/agent = allocate(/obj/item/slimepotion/mimic, T)
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/slimepotion/enhancer)), 1, "the actual floor initially contains exactly the original potion")
	TEST_ASSERT(user.put_in_active_hand(agent), "the actor holds the exact original mimic agent")
	add_trait(agent, TRAIT_NODROP, "interim_mimic_agent")
	TEST_ASSERT(user.release_refusal(agent, user), "actual inventory refuses sticky mimic agent consumption")
	test_op_handler(original, "interaction_item", user, agent)
	TEST_ASSERT(!QDELETED(agent), "refused copying preserves exact original mimic agent")
	TEST_ASSERT_EQUAL(user.get_active_hand(), agent, "refused copying preserves original source hand")
	TEST_ASSERT_EQUAL(agent.loc, user, "refused copying preserves actual inventory containment")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/slimepotion/enhancer)), 1, "refused consumption creates no duplicate potion")
	TEST_ASSERT(!QDELETED(original), "refused copying preserves exact original target potion")
	remove_trait(agent, TRAIT_NODROP, "interim_mimic_agent")
	test_op_handler(original, "interaction_item", user, agent)
	TEST_ASSERT(QDELETED(agent), "allowed copying consumes exact original mimic agent")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/slimepotion/enhancer)), 2, "one consumed mimic creates exactly one actual same-type duplicate")
	TEST_ASSERT_EQUAL(original.loc, T, "allowed copying preserves original target potion location")
	TEST_ASSERT(!QDELETED(original), "allowed copying preserves exact original target identity")
	var/distinct_copies = 0
	for(var/obj/item/slimepotion/enhancer/copy in contents_of(T, /obj/item/slimepotion/enhancer))
		if(copy != original)
			distinct_copies++
			TEST_ASSERT_EQUAL(copy.type, original.type, "the actual duplicate has the exact original potion type")
			TEST_ASSERT(!QDELETED(copy), "the actual distinct duplicate survives initialization")
			TEST_ASSERT_EQUAL(copy.loc, T, "the actual distinct duplicate remains on original target turf")
			own(copy)
	TEST_ASSERT_EQUAL(distinct_copies, 1, "allowed copying creates exactly one distinct surviving duplicate")
