/// Actual detachment releases the clamped item only for a valid explicit nearby actor.
/datum/unit_test/interim_hoist_detach_actor/Run()
	var/turf/start = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, start)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, start)
	var/obj/structure/hoist/hoist = allocate(/obj/structure/hoist, start, EAST)
	var/obj/effect/hoist_hook/hook = hoist.source_hook
	TEST_ASSERT_NOTNULL(hook, "the actual hoist constructor creates its owned clamp")
	TEST_ASSERT_EQUAL(hook.source_hoist(), hoist, "the actual clamp retains its source relation")
	TEST_ASSERT_EQUAL(get_turf(hook), get_step(start, EAST), "the actual clamp is deployed in the specified direction")
	var/obj/item/load = allocate(/obj/item, start)
	var/obj/item/unrelated = allocate(/obj/item, start)
	hoist.attach_hoistee(load)
	TEST_ASSERT_EQUAL(hoist.hoistee(), load, "the actual attach operation records the exact clamped item")
	TEST_ASSERT_EQUAL(get_turf(load), get_turf(hook), "the actual attach operation moves the item to its clamp")
	TEST_ASSERT(load.anchored, "the actual clamped item is anchored")
	TEST_ASSERT(isfloorturf(start), "the real nearby destination is a floor")
	TEST_ASSERT(hook.Adjacent(actor) && start.Adjacent(actor), "the valid actor passes both real proximity preconditions")
	var/turf/far = get_step(get_step(get_step(start, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "the actual test room contains the distant floor three steps east")
	bystander.forceMove(far)
	TEST_ASSERT(!hook.Adjacent(bystander), "the distant actual actor cannot reach the clamp")
	hook.detach_with_actor(bystander, start)
	TEST_ASSERT_EQUAL(hoist.hoistee(), load, "a distant explicit actor cannot release the actual load")
	TEST_ASSERT_EQUAL(get_turf(load), get_turf(hook), "a distant explicit actor cannot move the actual load")
	TEST_ASSERT(load.anchored, "distant refusal preserves real anchoring")
	var/mob/living/simple_mob/unsupported = allocate(/mob/living/simple_mob, start)
	TEST_ASSERT(hook.Adjacent(unsupported) && start.Adjacent(unsupported), "the actual unsupported mob passes both proximity preconditions")
	TEST_ASSERT(!ishuman(unsupported) && !issilicon(unsupported), "the actual unsupported mob fails the existing type guard")
	hook.detach_with_actor(unsupported, start)
	TEST_ASSERT_EQUAL(hoist.hoistee(), load, "an actual unsupported nearby mob cannot release the clamp")
	TEST_ASSERT(load.anchored, "the actual type refusal preserves anchoring")
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, start)
	TEST_ASSERT(actor.equip_to_slot(cuffs, SLOT_ID_HANDCUFFED), "actual cuffs equip into the real restraint slot")
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_HANDCUFFED), cuffs, "the actual restraint slot contains the exact cuffs")
	TEST_ASSERT(actor.incapacitated(), "real restraint satisfies the existing default incapacitation guard")
	hook.detach_with_actor(actor, start)
	TEST_ASSERT_EQUAL(hoist.hoistee(), load, "the actual incapacitated actor cannot release the clamp relation")
	TEST_ASSERT(load.anchored, "incapacitation refusal preserves actual anchoring")
	TEST_ASSERT(actor.unEquip(cuffs), "actual inventory removal clears the cuffs")
	TEST_ASSERT(!actor.incapacitated(), "removing real restraints restores the valid actor precondition")
	hook.detach_with_actor(actor, unrelated)
	TEST_ASSERT_EQUAL(hoist.hoistee(), load, "a real non-turf destination cannot release the load")
	hook.detach_with_actor(null, start)
	TEST_ASSERT_EQUAL(hoist.hoistee(), load, "a null initiating actor cannot release the actual load")
	TEST_ASSERT_EQUAL(get_turf(load), get_turf(hook), "refused actors preserve the exact clamped position")
	TEST_ASSERT(load.anchored, "all refused detachments leave the actual load anchored")
	TEST_ASSERT_NULL(hook.detach_with_actor(actor, start), "actual success preserves the original implicit null return")
	TEST_ASSERT_NULL(hoist.hoistee(), "the actual successful detachment clears its clamp relation")
	TEST_ASSERT_EQUAL(get_turf(load), start, "the actual successful detachment moves the load to the requested turf")
	TEST_ASSERT(!load.anchored, "the actual successful detachment releases the item's anchoring")
	TEST_ASSERT_EQUAL(get_turf(unrelated), start, "actual detachment never moves the unrelated item")
	TEST_ASSERT_EQUAL(hook.source_hoist(), hoist, "actual detachment retains the source hoist relation")
	hoist.attach_hoistee(load)
	bystander.forceMove(start)
	hook.detach_with_actor(bystander, start)
	TEST_ASSERT_NULL(hoist.hoistee(), "the helper accepts a separate explicitly supplied valid nearby actor")
	TEST_ASSERT_EQUAL(get_turf(load), start, "the second actual actor performs the same real detach effect")
	TEST_ASSERT(!load.anchored, "the second actual detach also releases anchoring")
