/// Actual storage viewer and physical contents survive explicit actor hand routing.
/datum/unit_test/interim_storage_drop_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	hud.build_action_groups()
	var/atom/movable/screen/right = hud.r_hand_hud_object
	var/atom/movable/screen/left = hud.l_hand_hud_object
	TEST_ASSERT_NOTNULL(right, "the actual HUD supplies its right hand target")
	TEST_ASSERT_NOTNULL(left, "the actual HUD supplies its left hand target")
	var/obj/item/storage/box/box = allocate(/obj/item/storage/box, T)
	var/obj/item/storage/box/previous = allocate(/obj/item/storage/box, T)
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	var/obj/item/blocker = allocate(/obj/item, T)
	TEST_ASSERT(box.handle_item_insertion(paper, TRUE), "actual storage accepts its real contained paper")
	TEST_ASSERT_EQUAL(paper.loc, box, "the actual paper is physically contained")
	TEST_ASSERT((paper in box.stored_items()), "actual storage ledger records the exact paper")
	TEST_ASSERT(actor.put_in_r_hand(box), "the actual storage begins in its owner's hand")
	previous.show_to(actor)
	TEST_ASSERT_EQUAL(actor.s_active, previous, "the actor has a real previous storage viewer")
	box.handle_inventory_drop(bystander, left)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), box, "unrelated actor cannot move another actor's carried storage")
	TEST_ASSERT(!bystander.item_is_in_hands(box), "unrelated actor gains no held storage")
	TEST_ASSERT_EQUAL(box.handle_inventory_drop(actor, actor), TRUE, "actual self target consumes native drag")
	TEST_ASSERT_EQUAL(actor.s_active, box, "actual opening selects the explicit actor's storage viewer")
	TEST_ASSERT((actor in box.is_seeing), "actual storage records the explicit viewer")
	TEST_ASSERT(!(actor in previous.is_seeing), "actual opening closes the previous storage viewer")
	box.close(actor)
	actor.set_stat(UNCONSCIOUS)
	TEST_ASSERT_EQUAL(actor.stat, UNCONSCIOUS, "the original explicit stat guard is genuinely enabled")
	box.handle_inventory_drop(actor, left)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), box, "actual stat refusal preserves the real storage hand")
	actor.set_stat(CONSCIOUS)
	TEST_ASSERT(actor.put_in_l_hand(blocker), "actual destination hand contains an unrelated item")
	box.handle_inventory_drop(actor, left)
	TEST_ASSERT_NULL(actor.get_right_hand(), "legacy storage drop first unequips even when its destination is occupied")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), blocker, "failed legacy hand insertion preserves the unrelated held item")
	TEST_ASSERT_EQUAL(box.loc, T, "legacy occupied hand branch leaves the actual storage on its floor")
	TEST_ASSERT_EQUAL(paper.loc, box, "occupied hand branch preserves the actual contained paper")
	TEST_ASSERT(actor.unEquip(blocker), "actual inventory removal makes the destination available")
	TEST_ASSERT(actor.put_in_r_hand(box), "the actor genuinely picks the same storage back up")
	box.handle_inventory_drop(actor, left)
	TEST_ASSERT_EQUAL(actor.get_left_hand(), box, "actual accepted drag moves exact storage into requested hand")
	TEST_ASSERT_NULL(actor.get_right_hand(), "actual transfer clears the former hand")
	box.handle_inventory_drop(actor, right)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), box, "actual roundtrip returns exact storage to original hand")
	TEST_ASSERT_EQUAL(box.handle_inventory_drop(actor, blocker), FALSE, "actual non-screen target selects original conditional native parent")
	TEST_ASSERT_EQUAL(actor.get_right_hand(), box, "helper parent selection leaves existing hand unchanged")
	TEST_ASSERT_EQUAL(paper.loc, box, "all real routing paths retain exact paper containment")
	TEST_ASSERT((paper in box.stored_items()), "all real routing paths retain the exact storage ledger member")
	TEST_ASSERT_NULL(actor.s_active, "actual viewer close remains clear after hand routing")
