/// The legacy item screen calls the real item effect with its authoritative actor.
/datum/unit_test/interim_legacy_item_screen_actor/Run()
	test_driver_begin()
	set_config(/datum/config_entry/flag/no_click_cooldown, FALSE)
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/obj/item/flashlight/light = allocate(/obj/item/flashlight, T)
	TEST_ASSERT(actor.put_in_active_hand(light), "the real actor holds the legacy screen action target")
	var/atom/movable/screen/item_action/button = allocate(/atom/movable/screen/item_action)
	rel_set(button, nameof(button.owner), light)
	TEST_ASSERT_EQUAL(button.owner(), light, "the actual screen action links the exact held item")
	COOLDOWN_RESET(actor, next_click)
	COOLDOWN_RESET(bystander, next_click)
	button.click_with_actor(bystander, null, null, null)
	TEST_ASSERT(!light.on, "another mob cannot activate an item it does not contain")
	km_synthetic_click(actor, button)
	TEST_ASSERT(light.on, "the native legacy screen supplies its actor to the real flashlight action")
	appearance_flush() // the draw runs on the presentation lane, not inside the click
	TEST_ASSERT_EQUAL(light.icon_state, "flashlight-on", "the real legacy screen action updates actual item appearance")
	TEST_ASSERT_EQUAL(button.click_with_actor(actor, null, null, null), 1, "the actor helper preserves the successful legacy screen return")
	TEST_ASSERT(!light.on, "a second real item action turns the actual held flashlight off")
	actor.setClickCooldown(1 SECOND)
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT(!light.on, "the real actor cooldown refuses another legacy item action")
	COOLDOWN_RESET(actor, next_click)
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, T)
	TEST_ASSERT(move_into(actor, SLOT_ID_HANDCUFFED, cuffs), "the actual actor wears real restraints")
	TEST_ASSERT(actor.restrained(), "the actual actor is restrained before the item-action refusal")
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT(!light.on, "the actual restraint guard refuses the legacy item action")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), light, "all actions and refusals preserve the exact held target")
	TEST_ASSERT_NULL(bystander.get_active_hand(), "the unrelated mob never acquires the target")
	button.click_with_actor(null, null, null, null)
	TEST_ASSERT(!light.on, "an absent actor cannot activate the actual target")
	rel_clear(button, nameof(button.owner))
	TEST_ASSERT_EQUAL(button.click_with_actor(actor, null, null, null), 1, "a screen without an item preserves its early return")
	TEST_ASSERT(!light.on, "clearing the actual target link leaves the real item unchanged")
