/datum/unit_test/interim_handlabeler_native_configuration/Run()
	test_driver_begin()
	exercise_configuration()
	test_driver_end()

/datum/unit_test/interim_handlabeler_native_configuration/proc/exercise_configuration()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/hand_labeler/labeler = allocate(/obj/item/hand_labeler, T)
	TEST_ASSERT_EQUAL(labeler.mode, 0, "Real labeler starts disabled")
	labeler.label_configuration_begin(user, null)
	TEST_ASSERT_EQUAL(labeler.mode, 1, "Starting real configuration enables the labeler once")
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/text/hand_labeler_label), "The native configuration opens real text entry")
	test_answer(user, "Field Samples")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Accepted label closes the real request")
	TEST_ASSERT_EQUAL(labeler.label, "Field Samples", "Accepted native text reaches the real label field")
	TEST_ASSERT_EQUAL(labeler.mode, 1, "Acceptance does not toggle the enabled device off")
	TEST_ASSERT_EQUAL(labeler.icon_state, "labeler1", "Enabled presentation matches actual mode")
	labeler.label_configuration_begin(user, null)
	TEST_ASSERT_EQUAL(labeler.mode, 0, "The actual control switches the configured labeler off")
	labeler.label_configuration_begin(user, null)
	test_answer(user, null, REQ_CANCELLED)
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Explicit close leaves no request")
	TEST_ASSERT_EQUAL(labeler.mode, 1, "Explicit close preserves the enabled mode")
	TEST_ASSERT_EQUAL(labeler.label, "Field Samples", "Explicit close preserves the previous label")
	labeler.label_configuration_begin(user, null)
	labeler.label_configuration_begin(user, null)
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/text/hand_labeler_label), "Reenabling opens the next real request")
	labeler.label_configuration_begin(user, null)
	test_answer(user, "Late Replacement")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Answering after disabling settles the rejected request")
	TEST_ASSERT_EQUAL(labeler.mode, 0, "Late answer cannot enable a switched-off labeler")
	TEST_ASSERT_EQUAL(labeler.label, "Field Samples", "Late disabled answer cannot replace the actual label")
