/// Actual linen-bin sheet and hidden-item routes respect held release and return both original occupants with an exact stock-count refund.
/datum/unit_test/interim_linen_bin_sticky_items/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/bedsheetbin/bin = allocate(/obj/structure/bedsheetbin, T)
	var/obj/item/bedsheet/sheet = allocate(/obj/item/bedsheet, T)
	var/obj/item/pen/hidden_item = allocate(/obj/item/pen, T)
	var/original_stock = bin.amount
	TEST_ASSERT(original_stock > 0, "the real linen bin has stock among which an item can be hidden")
	TEST_ASSERT_EQUAL(length(bin.sheets), 0, "the real linen bin initially has no physically returned sheet records")
	TEST_ASSERT_NULL(bin.hidden(), "the actual linen bin starts without a hidden item")
	TEST_ASSERT(user.put_in_active_hand(sheet), "the actor holds the original sheet to return")
	add_trait(sheet, TRAIT_NODROP, "interim_linen_sticky_sheet")
	TEST_ASSERT(user.release_refusal(sheet, user), "the actual inventory refuses release of the sticky sheet")
	test_op_handler(bin, "interaction_item", user, sheet)
	TEST_ASSERT_EQUAL(user.get_active_hand(), sheet, "refused sheet insertion preserves the exact original hand")
	TEST_ASSERT_EQUAL(sheet.loc, user, "refused sheet insertion preserves actual inventory containment")
	TEST_ASSERT_EQUAL(bin.amount, original_stock, "refused sheet insertion grants no additional linen stock")
	TEST_ASSERT_EQUAL(length(bin.sheets), 0, "refused sheet insertion records no physical sheet")
	remove_trait(sheet, TRAIT_NODROP, "interim_linen_sticky_sheet")
	test_op_handler(bin, "interaction_item", user, sheet)
	TEST_ASSERT_EQUAL(sheet.loc, bin, "allowed return contains the exact original sheet")
	TEST_ASSERT(sheet in bin.sheets, "allowed return records the exact original sheet relation")
	TEST_ASSERT_EQUAL(bin.amount, original_stock + 1, "allowed return credits exactly one real sheet")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed sheet return clears its source hand")
	TEST_ASSERT(user.put_in_active_hand(hidden_item), "the actor holds the real item to hide among the sheets")
	add_trait(hidden_item, TRAIT_NODROP, "interim_linen_sticky_hidden")
	TEST_ASSERT(user.release_refusal(hidden_item, user), "the actual inventory refuses release of the sticky hidden item")
	test_op_handler(bin, "interaction_item", user, hidden_item)
	TEST_ASSERT_NULL(bin.hidden(), "refused hidden-item insertion records no relation")
	TEST_ASSERT_EQUAL(user.get_active_hand(), hidden_item, "refused hiding preserves the exact source hand")
	TEST_ASSERT_EQUAL(hidden_item.loc, user, "refused hiding preserves actual inventory containment")
	TEST_ASSERT_EQUAL(bin.amount, original_stock + 1, "refused hiding preserves actual linen stock")
	remove_trait(hidden_item, TRAIT_NODROP, "interim_linen_sticky_hidden")
	test_op_handler(bin, "interaction_item", user, hidden_item)
	TEST_ASSERT_EQUAL(bin.hidden(), hidden_item, "allowed hiding records the exact original small item")
	TEST_ASSERT_EQUAL(hidden_item.loc, bin, "allowed hiding physically contains the original item")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed hiding clears its actual source hand")
	test_op_handler(bin, "interaction_hand", user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), sheet, "actual retrieval returns the same physically recorded original sheet")
	TEST_ASSERT_EQUAL(sheet.loc, user, "actual retrieval restores the original sheet to inventory")
	TEST_ASSERT_EQUAL(hidden_item.loc, T, "actual retrieval drops the original hidden item onto the actual floor")
	TEST_ASSERT_NULL(bin.hidden(), "actual retrieval clears the hidden-item relation")
	TEST_ASSERT_EQUAL(length(bin.sheets), 0, "actual retrieval clears the original physical sheet relation")
	TEST_ASSERT_EQUAL(bin.amount, original_stock, "actual retrieval refunds exactly the one returned sheet from stock")
	qdel(bin)
	TEST_ASSERT(!QDELETED(sheet) && !QDELETED(hidden_item), "linen-bin teardown preserves both returned original occupants")
