/// Inventory controls use real hand state and actual inventory slot transfers.
/datum/unit_test/interim_inventory_screen_hand_actor/Run()
	test_driver_begin()
	set_config(/datum/config_entry/flag/no_click_cooldown, FALSE)
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/atom/movable/screen/inventory/hand/button = allocate(/atom/movable/screen/inventory/hand)
	actor.activate_hand("l")
	bystander.activate_hand("l")
	COOLDOWN_RESET(actor, next_click)
	button.name = "r_hand"
	km_synthetic_click(actor, button)
	TEST_ASSERT_EQUAL(actor.hand, 0, "the real native inventory click activates the actor's right hand")
	TEST_ASSERT_EQUAL(bystander.hand, 1, "the actual native click does not alter a separate mob's hand")
	button.name = "l_hand"
	TEST_ASSERT_EQUAL(button.click_with_actor(actor, null, null, null), 1, "the real inventory helper preserves its return value")
	TEST_ASSERT_EQUAL(actor.hand, 1, "the real left-hand control activates the actor's left hand")
	button.name = "swap"
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT_EQUAL(actor.hand, 0, "the real swap control changes the actor's active hand")
	button.name = "hand"
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT_EQUAL(actor.hand, 1, "the alternate real hand control swaps back")
	actor.setClickCooldown(1 SECOND)
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT_EQUAL(actor.hand, 1, "the actual cooldown guard prevents another hand swap")
	COOLDOWN_RESET(actor, next_click)
	actor.set_stat(UNCONSCIOUS)
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT_EQUAL(actor.hand, 1, "the actual unconscious-state guard prevents another hand swap")
	actor.set_stat(CONSCIOUS)
	button.click_with_actor(null, null, null, null)
	TEST_ASSERT_EQUAL(actor.hand, 1, "an absent actor cannot alter the real hand state")

/datum/unit_test/interim_inventory_screen_slot_transfer/Run()
	test_driver_begin()
	set_config(/datum/config_entry/flag/no_click_cooldown, FALSE)
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/atom/movable/screen/inventory/button = allocate(/atom/movable/screen/inventory)
	button.name = "mask"
	button.slot_id = SLOT_ID_MASK
	var/obj/item/clothing/mask/breath/mask = allocate(/obj/item/clothing/mask/breath, T)
	TEST_ASSERT(actor.put_in_active_hand(mask), "the real inventory actor initially holds the transfer item")
	actor.setClickCooldown(1 SECOND)
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_MASK), "the actual cooldown guard refuses slot insertion")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), mask, "cooldown refusal preserves the exact held item")
	COOLDOWN_RESET(actor, next_click)
	actor.set_stat(UNCONSCIOUS)
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_MASK), "the actual unconscious-state guard refuses slot insertion")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), mask, "state refusal preserves the exact held item")
	actor.set_stat(CONSCIOUS)
	km_synthetic_click(actor, button)
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_MASK), mask, "the real native inventory control equips the actual held mask")
	TEST_ASSERT_NULL(actor.get_active_hand(), "actual slot insertion releases the original hand")
	TEST_ASSERT_EQUAL(mask.loc, actor, "actual slot insertion preserves the actor's item containment")
	TEST_ASSERT_NULL(bystander.get_equipped_item(SLOT_ID_MASK), "the native inventory click leaves another mob's mask slot empty")
	COOLDOWN_RESET(actor, next_click)
	button.click_with_actor(actor, null, null, null)
	TEST_ASSERT_NULL(actor.get_equipped_item(SLOT_ID_MASK), "the actual inventory control removes the equipped mask")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), mask, "actual removal returns the exact mask to the actor's active hand")
	TEST_ASSERT_EQUAL(mask.loc, actor, "actual removal retains the same actor's item containment")
