/// The real bulk plant-bag route releases each stored fruit through its actual storage bookkeeping, including HUD appearance cleanup.
/datum/unit_test/interim_biogenerator_bulk_storage_release/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/biogenerator/generator = allocate(/obj/machinery/biogenerator, T)
	var/obj/item/storage/bag/plants/bag = allocate(/obj/item/storage/bag/plants, T)
	var/obj/item/reagent_containers/food/snacks/grown/first = allocate(/obj/item/reagent_containers/food/snacks/grown, T, PLANT_APPLE)
	var/obj/item/reagent_containers/food/snacks/grown/second = allocate(/obj/item/reagent_containers/food/snacks/grown, T, PLANT_APPLE)
	TEST_ASSERT(!QDELETED(first) && !QDELETED(second), "actual apple seed data creates both original grown fruits")
	TEST_ASSERT(user.put_in_active_hand(bag), "the actor holds the original plant bag")
	TEST_ASSERT(bag.handle_item_insertion(first, user, TRUE), "the actual storage route inserts the first original fruit")
	TEST_ASSERT(bag.handle_item_insertion(second, user, TRUE), "the actual storage route inserts the second original fruit")
	var/first_volume = first.reagents.total_volume
	var/second_volume = second.reagents.total_volume
	TEST_ASSERT_EQUAL(length(bag.slot_contents(CONTAINER_SLOT_STORAGE)), 2, "the actual bag ledger records both original fruits")
	TEST_ASSERT_EQUAL(bag.slot_used(CONTAINER_SLOT_STORAGE), first.get_storage_cost() + second.get_storage_cost(), "the real bag charges both original storage costs")
	bag.show_to(user)
	TEST_ASSERT_NOTNULL(bag.hud, "the actual storage display creates its real HUD without a fabricated client")
	TEST_ASSERT(first.plane != initial(first.plane) || first.layer != initial(first.layer), "the actual displayed fruit has storage HUD appearance")
	test_op_handler(generator, "interaction_insert", user, bag)
	TEST_ASSERT_EQUAL(first.loc, generator, "actual bulk insertion moves the first original fruit into the generator")
	TEST_ASSERT_EQUAL(second.loc, generator, "actual bulk insertion moves the second original fruit into the generator")
	TEST_ASSERT_EQUAL(length(bag.slot_contents(CONTAINER_SLOT_STORAGE)), 0, "actual bulk insertion empties the real source ledger")
	TEST_ASSERT_EQUAL(bag.slot_used(CONTAINER_SLOT_STORAGE), 0, "actual bulk insertion refunds all source capacity")
	TEST_ASSERT_EQUAL(first.plane, initial(first.plane), "actual bulk release resets the first fruit's HUD plane")
	TEST_ASSERT_EQUAL(first.layer, initial(first.layer), "actual bulk release resets the first fruit's HUD layer")
	TEST_ASSERT_EQUAL(second.plane, initial(second.plane), "actual bulk release resets the second fruit's HUD plane")
	TEST_ASSERT_EQUAL(second.layer, initial(second.layer), "actual bulk release resets the second fruit's HUD layer")
	TEST_ASSERT_EQUAL(first.reagents.total_volume, first_volume, "bulk release preserves the first original mixture")
	TEST_ASSERT_EQUAL(second.reagents.total_volume, second_volume, "bulk release preserves the second original mixture")
	TEST_ASSERT_EQUAL(user.get_active_hand(), bag, "actual bulk insertion preserves the source bag's held slot")
	TEST_ASSERT(!generator.processing, "bulk insertion alone does not process or consume either fruit")
	bag.hide_from(user)
