/// Actual empty macrobattery expenditure disposes its unused owned projectile, preserving handed-off shots.
/datum/unit_test/interim2_macrobattery_empty_projectile_disposal/Run()
	var/obj/item/ammo_casing/macrobattery/casing = allocate(/obj/item/ammo_casing/macrobattery, test_floor())
	TEST_ASSERT_EQUAL(casing.charge, 10, "The actual canonical constructor must begin with ten charges")
	var/list/handed_off = list()
	for(var/i in 1 to 10)
		var/obj/item/projectile/original = casing.BB
		TEST_ASSERT(istype(original), "Every real charged expenditure must begin with an actual owned projectile")
		TEST_ASSERT_EQUAL(original.type, /obj/item/projectile/beam/chain_lightning, "The canonical macrobattery must construct lightning projectiles")
		TEST_ASSERT_EQUAL(owner_of(original), casing, "The actual casing must own the original chamber projectile")
		own(original)
		TEST_ASSERT_EQUAL(casing.expend(), original, "Actual charged expenditure must return the exact original projectile")
		TEST_ASSERT(!QDELETED(original), "Handing off a charged projectile must preserve it for its caller")
		TEST_ASSERT_NULL(owner_of(original), "Actual handoff must release the original projectile's ownership")
		handed_off += original
		TEST_ASSERT_EQUAL(casing.charge, 10 - i, "Every actual expenditure must debit exactly one charge")
		TEST_ASSERT(istype(casing.BB) && casing.BB != original, "Actual expenditure must build a distinct replacement projectile")
		TEST_ASSERT_EQUAL(owner_of(casing.BB), casing, "The actual casing must adopt its replacement projectile")
	var/obj/item/projectile/unused = casing.BB
	own(unused)
	TEST_ASSERT_NULL(casing.expend(), "Actual zero-charge expenditure must return no projectile")
	TEST_ASSERT(QDELETED(unused), "Failed empty expenditure must dispose of the exact unused original replacement")
	TEST_ASSERT_NULL(owner_of(unused), "Disposal must clear the unused projectile's owner")
	TEST_ASSERT_NULL(casing.BB, "Failed expenditure must clear the actual owned chamber")
	TEST_ASSERT_EQUAL(casing.charge, 0, "Failed expenditure must leave the actual charge at zero")
	for(var/obj/item/projectile/shot in handed_off)
		TEST_ASSERT(!QDELETED(shot), "Disposing an unused replacement must preserve every original handed-off shot")
		TEST_ASSERT_NULL(owner_of(shot), "Empty expenditure must not reclaim any original handed-off shot")
	TEST_ASSERT_NULL(casing.expend(), "A repeated empty expenditure must remain a real no-shot result")
	casing.recharge()
	TEST_ASSERT_EQUAL(casing.charge, 1, "Actual recharge must supply exactly one charge")
	var/obj/item/projectile/recharged = casing.BB
	TEST_ASSERT(istype(recharged) && recharged != unused, "Actual recharge must construct a distinct canonical replacement")
	own(recharged)
	TEST_ASSERT_EQUAL(recharged.type, /obj/item/projectile/beam/chain_lightning, "Recharge must preserve the real projectile family")
	TEST_ASSERT_EQUAL(owner_of(recharged), casing, "Recharge must adopt its newly constructed projectile")
	TEST_ASSERT_EQUAL(casing.expend(), recharged, "Actual restored charge must hand off its exact original replacement")
	var/obj/item/projectile/last_unused = casing.BB
	own(last_unused)
	TEST_ASSERT_NULL(casing.expend(), "The next actual empty expenditure must refuse a shot again")
	TEST_ASSERT(QDELETED(last_unused), "The second empty cycle must dispose of its exact unused replacement")
	TEST_ASSERT(!QDELETED(recharged), "Second-cycle disposal must preserve the exact restored shot")
