/// Real patient attachment consumes the supplied actor's drag guards and preserves existing detach behavior.
/datum/unit_test/interim_vitals_monitor_drag_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "a real distant floor exists for the original drag guard")
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/vitals_monitor/monitor = allocate(/obj/machinery/vitals_monitor, T)
	TEST_ASSERT_NULL(monitor.victim(), "the actual constructed monitor has no patient")
	TEST_ASSERT_EQUAL(monitor.use_power, USE_POWER_IDLE, "the actual unoccupied monitor starts idle")
	TEST_ASSERT(!monitor.CanMouseDrop(patient), "an omitted actor never reads ambient state to pass the actual drag guard")
	monitor.drop_patient_with_actor(null, patient)
	monitor.drop_patient_with_actor(actor, null)
	TEST_ASSERT_NULL(monitor.victim(), "absent actor or target cannot attach an actual patient")
	bystander.forceMove(far)
	TEST_ASSERT(!monitor.CanMouseDrop(patient, bystander), "the actual distant actor fails source adjacency")
	monitor.drop_patient_with_actor(bystander, patient)
	TEST_ASSERT_NULL(monitor.victim(), "a distant supplied actor cannot attach the nearby actual patient")
	patient.forceMove(far)
	TEST_ASSERT(!monitor.CanMouseDrop(patient, actor), "the actual distant target fails target adjacency")
	monitor.drop_patient_with_actor(actor, patient)
	TEST_ASSERT_NULL(monitor.victim(), "the nearby actor cannot attach a distant patient")
	patient.forceMove(T)
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, T)
	TEST_ASSERT(actor.equip_to_slot(cuffs, SLOT_ID_HANDCUFFED), "real cuffs establish the existing incapacity guard")
	TEST_ASSERT(actor.incapacitated(), "the actual restrained actor satisfies the original incapacity predicate")
	monitor.drop_patient_with_actor(actor, patient)
	TEST_ASSERT_NULL(monitor.victim(), "actual restraints prevent real patient attachment")
	TEST_ASSERT(actor.unEquip(cuffs), "real cuff removal restores the actual drag guard")
	TEST_ASSERT(monitor.CanMouseDrop(patient, actor), "the actual supplied actor and patient satisfy the real drag guard")
	TEST_ASSERT_NULL(monitor.drop_patient_with_actor(actor, patient), "actual attachment preserves the original implicit-null return")
	TEST_ASSERT_EQUAL(monitor.victim(), patient, "the real monitor records the exact explicitly selected patient")
	TEST_ASSERT_EQUAL(monitor.use_power, USE_POWER_ACTIVE, "real attachment selects active power use")
	TEST_ASSERT_EQUAL(patient.loc, T, "real monitor attachment leaves the original patient on its actual floor")
	TEST_ASSERT_EQUAL(bystander.loc, far, "real attachment leaves the unrelated distant human unchanged")
	monitor.drop_patient_with_actor(bystander, patient)
	TEST_ASSERT_EQUAL(monitor.victim(), patient, "a distant actor cannot detach the actual connected patient")
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	TEST_ASSERT(monitor.CanMouseDrop(paper, actor), "the existing drag guard admits a nearby actual nonhuman target")
	monitor.drop_patient_with_actor(actor, paper)
	TEST_ASSERT_NULL(monitor.victim(), "the existing occupied branch detaches before considering target type")
	TEST_ASSERT_EQUAL(monitor.use_power, USE_POWER_IDLE, "actual detach restores idle power")
	monitor.drop_patient_with_actor(actor, paper)
	TEST_ASSERT_NULL(monitor.victim(), "an empty monitor never attaches the actual nonhuman target")
	monitor.drop_patient_with_actor(actor, patient)
	TEST_ASSERT_EQUAL(monitor.victim(), patient, "actual attachment can reconnect the same original patient")
	patient.forceMove(far)
	test_step_machine(monitor)
	TEST_ASSERT_NULL(monitor.victim(), "the actual machine step clears a patient who moved beyond its existing range")
	TEST_ASSERT_EQUAL(monitor.use_power, USE_POWER_IDLE, "actual range cleanup restores idle power")
