/// The actual card bay refuses sticky release and returns the same original ID.
/datum/unit_test/interim_atm_sticky_id/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/atm/machine = allocate(/obj/machinery/atm, T)
	var/obj/item/card/id/card = allocate(/obj/item/card/id, T)
	var/obj/item/card/id/replacement = allocate(/obj/item/card/id, T)
	TEST_ASSERT_NULL(machine.held_card(), "the actual ATM initializes without an inserted ID")
	TEST_ASSERT_NULL(machine.authenticated_account(), "the unopened ATM has no authenticated account")
	var/obj/item/card/generic_card = allocate(/obj/item/card, T)
	TEST_ASSERT(user.put_in_active_hand(generic_card), "the actor holds an actual non-ID card")
	machine.atm_take_card(user, generic_card)
	TEST_ASSERT_EQUAL(user.get_active_hand(), generic_card, "non-ID refusal preserves the actual source hand")
	TEST_ASSERT_EQUAL(generic_card.loc, user, "non-ID refusal preserves actual inventory containment")
	TEST_ASSERT_NULL(machine.held_card(), "non-ID refusal records no card in the ID bay")
	TEST_ASSERT(user.unEquip(generic_card), "the actor releases the rejected generic card")
	TEST_ASSERT(user.put_in_active_hand(card), "the actor holds the original ID")
	add_trait(card, TRAIT_NODROP, "interim_atm_sticky")
	TEST_ASSERT(user.release_refusal(card, user), "actual inventory refuses the sticky ID")
	machine.atm_take_card(user, card)
	TEST_ASSERT_EQUAL(user.get_active_hand(), card, "refused insertion preserves the original hand")
	TEST_ASSERT_EQUAL(card.loc, user, "refused insertion preserves original inventory containment")
	TEST_ASSERT_NULL(machine.held_card(), "refused insertion records no ID")
	remove_trait(card, TRAIT_NODROP, "interim_atm_sticky")
	machine.atm_take_card(user, card)
	TEST_ASSERT_EQUAL(machine.held_card(), card, "allowed insertion records the exact original ID")
	TEST_ASSERT_EQUAL(card.loc, machine, "allowed insertion physically contains the original ID")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears the source hand")
	TEST_ASSERT_NULL(owner_of(card), "the existing relation policy does not adopt ownership")
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds a real replacement ID")
	machine.atm_take_card(user, replacement)
	TEST_ASSERT_EQUAL(machine.held_card(), card, "an occupied bay retains the original ID")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "occupied-bay refusal preserves the replacement hand")
	TEST_ASSERT(user.unEquip(replacement), "the actor releases the replacement to make room")
	machine.release_held_id(user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), card, "public ejection returns the exact original ID")
	TEST_ASSERT_EQUAL(card.loc, user, "public ejection restores original inventory containment")
	TEST_ASSERT_NULL(machine.held_card(), "public ejection clears the bay relation")
	TEST_ASSERT_NULL(machine.authenticated_account(), "ejection leaves no authenticated account")
	qdel(machine)
	TEST_ASSERT(!QDELETED(card), "returned original ID survives empty ATM teardown")
