/// The actual syringe interaction draws configured doses, switches at capacity and conserves liquid on injection refusals.
/datum/unit_test/interim_syringe_container_doses/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/syringe/needle = allocate(/obj/item/reagent_containers/syringe, T)
	var/obj/item/reagent_containers/glass/beaker/source = allocate(/obj/item/reagent_containers/glass/beaker, T)
	var/obj/item/reagent_containers/glass/beaker/target = allocate(/obj/item/reagent_containers/glass/beaker, T)
	source.reagents.add_reagent(REAGENT_ID_WATER, 30)
	TEST_ASSERT_EQUAL(needle.amount_per_transfer_from_this, 5, "the actual syringe starts with a five-unit dose")
	TEST_ASSERT_EQUAL(needle.reagents.maximum_volume, 15, "the actual syringe holds fifteen units")
	needle.afterattack(source, user, TRUE)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 30, "a capped syringe leaves the real source unchanged")
	TEST_ASSERT_EQUAL(needle.reagents.total_volume, 0, "a capped syringe draws nothing")
	needle.interaction_self(user, null, null)
	var/draw_mode = needle.mode
	needle.afterattack(source, user, TRUE)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 25, "the first actual draw debits five units")
	TEST_ASSERT_EQUAL(needle.reagents.total_volume, 5, "the first draw stores five units")
	TEST_ASSERT_EQUAL(needle.mode, draw_mode, "a partially filled syringe stays in drawing mode")
	needle.afterattack(source, user, TRUE)
	needle.afterattack(source, user, TRUE)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 15, "three actual draws debit fifteen units")
	TEST_ASSERT_EQUAL(needle.reagents.total_volume, 15, "three draws exactly fill the syringe")
	TEST_ASSERT_NOTEQUAL(needle.mode, draw_mode, "a full syringe automatically switches to injection")
	var/inject_mode = needle.mode
	target.reagents.add_reagent(REAGENT_ID_WATER, target.reagents.maximum_volume - 1)
	needle.afterattack(target, user, TRUE)
	TEST_ASSERT_EQUAL(needle.reagents.total_volume, 14, "injection debits only the target's remaining one-unit capacity")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, target.reagents.maximum_volume, "the capacity-limited injection fills the target")
	needle.afterattack(target, user, TRUE)
	TEST_ASSERT_EQUAL(needle.reagents.total_volume, 14, "a full target cannot debit another dose")
	TEST_ASSERT_EQUAL(needle.mode, inject_mode, "a refused injection preserves injection mode")
	target.reagents.clear_reagents()
	needle.afterattack(target, user, TRUE)
	TEST_ASSERT_EQUAL(needle.reagents.total_volume, 9, "the next actual injection debits the configured five units")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 5, "the next actual injection delivers five units")
	needle.afterattack(target, user, TRUE)
	needle.afterattack(target, user, TRUE)
	TEST_ASSERT_EQUAL(needle.reagents.total_volume, 0, "the final partial dose empties the syringe")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 14, "the target receives all fourteen remaining units")
	TEST_ASSERT_EQUAL(needle.mode, draw_mode, "an emptied syringe automatically returns to drawing mode")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 15, "injections preserve the independent source beaker")
