/// Actual entertainment alternate-click effects and fallback guards retain the supplied actor.
/datum/unit_test/interim_entertainment_monitor_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "the actual distant actor fixture has a real floor")
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, far)
	var/mob/unsupported = allocate(/mob, T)
	var/obj/machinery/computer/security/telescreen/entertainment/monitor = allocate(/obj/machinery/computer/security/telescreen/entertainment, T)
	var/obj/item/radio/original_radio = monitor.radio
	TEST_ASSERT_NOTNULL(original_radio, "the actual monitor creates its radio child")
	TEST_ASSERT(monitor.enabled, "the actual monitor begins enabled")
	TEST_ASSERT(GLOB.input_router.click_is(params2list("alt=1"), TYPE_TABLE_GET(GLOB.input_router, alternate_table), INPUT_ACTION_ALTERNATE), "the real router table recognizes the actual alternate-click parameters")
	TEST_ASSERT(monitor.handle_click_with_actor(actor, "alt=1"), "the actual nearby actor's alternate click consumes the existing branch")
	TEST_ASSERT(!monitor.enabled, "the actual alternate-click effect disables the real monitor")
	TEST_ASSERT(!original_radio.on, "disabling the actual monitor switches its own radio off")
	TEST_ASSERT_EQUAL(monitor.radio, original_radio, "the actual toggle preserves the exact radio child")
	TEST_ASSERT(!monitor.Adjacent(bystander), "the actual unrelated actor fails the existing range guard")
	TEST_ASSERT(!monitor.handle_click_with_actor(bystander, "alt=1"), "the distant actor retains the original native fallback")
	TEST_ASSERT(!monitor.handle_click_with_actor(unsupported, "alt=1"), "an actual unsupported mob retains the native fallback")
	TEST_ASSERT(!monitor.handle_click_with_actor(null, "alt=1"), "an absent actor retains the native fallback")
	TEST_ASSERT(!monitor.enabled, "all actual refused toggles preserve the disabled monitor")
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, T)
	TEST_ASSERT(actor.equip_to_slot(cuffs, SLOT_ID_HANDCUFFED), "real cuffs equip into the actor's actual restraint slot")
	TEST_ASSERT(actor.incapacitated(), "real cuffs satisfy the exact existing default incapacitation guard")
	TEST_ASSERT(!monitor.handle_click_with_actor(actor, "alt=1"), "actual restraint retains the original native fallback")
	TEST_ASSERT(!monitor.enabled, "the restrained actor cannot change the actual monitor state")
	TEST_ASSERT(actor.unEquip(cuffs), "actual cuff removal restores the actor's valid state")
	TEST_ASSERT(!actor.incapacitated(), "the real actor is capable again after cuff removal")
	TEST_ASSERT(monitor.handle_click_with_actor(actor, "alt=1"), "the same valid actor can consume the next alternate-click branch")
	TEST_ASSERT(monitor.enabled, "the actual second toggle reenables the original monitor")
	TEST_ASSERT_EQUAL(monitor.radio, original_radio, "reenabling retains the exact original radio child")
	TEST_ASSERT(!monitor.handle_click_with_actor(actor, ""), "a plain click retains the original native parent fallback")
	TEST_ASSERT(monitor.enabled, "plain-click fallback itself does not run the alternate-toggle effect")

/// Actual bodycamera alternate-click effects and fallback guards retain the supplied actor.
/datum/unit_test/interim_bodycamera_monitor_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "the actual distant actor fixture has a real floor")
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, far)
	var/mob/unsupported = allocate(/mob, T)
	var/obj/machinery/computer/security/telescreen/bodycamera/monitor = allocate(/obj/machinery/computer/security/telescreen/bodycamera, T)
	var/obj/item/radio/original_radio = monitor.bradio
	TEST_ASSERT_NOTNULL(original_radio, "the actual monitor creates its radio child")
	TEST_ASSERT(monitor.enabled, "the actual monitor begins enabled")
	TEST_ASSERT(GLOB.input_router.click_is(params2list("alt=1"), TYPE_TABLE_GET(GLOB.input_router, alternate_table), INPUT_ACTION_ALTERNATE), "the real router table recognizes the actual alternate-click parameters")
	TEST_ASSERT(monitor.handle_click_with_actor(actor, "alt=1"), "the actual nearby actor's alternate click consumes the existing branch")
	TEST_ASSERT(!monitor.enabled, "the actual alternate-click effect disables the real monitor")
	TEST_ASSERT(!original_radio.on, "disabling the actual monitor switches its own radio off")
	TEST_ASSERT_EQUAL(monitor.bradio, original_radio, "the actual toggle preserves the exact radio child")
	TEST_ASSERT(!monitor.Adjacent(bystander), "the actual unrelated actor fails the existing range guard")
	TEST_ASSERT(!monitor.handle_click_with_actor(bystander, "alt=1"), "the distant actor retains the original native fallback")
	TEST_ASSERT(!monitor.handle_click_with_actor(unsupported, "alt=1"), "an actual unsupported mob retains the native fallback")
	TEST_ASSERT(!monitor.handle_click_with_actor(null, "alt=1"), "an absent actor retains the native fallback")
	TEST_ASSERT(!monitor.enabled, "all actual refused toggles preserve the disabled monitor")
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, T)
	TEST_ASSERT(actor.equip_to_slot(cuffs, SLOT_ID_HANDCUFFED), "real cuffs equip into the actor's actual restraint slot")
	TEST_ASSERT(actor.incapacitated(), "real cuffs satisfy the exact existing default incapacitation guard")
	TEST_ASSERT(!monitor.handle_click_with_actor(actor, "alt=1"), "actual restraint retains the original native fallback")
	TEST_ASSERT(!monitor.enabled, "the restrained actor cannot change the actual monitor state")
	TEST_ASSERT(actor.unEquip(cuffs), "actual cuff removal restores the actor's valid state")
	TEST_ASSERT(!actor.incapacitated(), "the real actor is capable again after cuff removal")
	TEST_ASSERT(monitor.handle_click_with_actor(actor, "alt=1"), "the same valid actor can consume the next alternate-click branch")
	TEST_ASSERT(monitor.enabled, "the actual second toggle reenables the original monitor")
	TEST_ASSERT_EQUAL(monitor.bradio, original_radio, "reenabling retains the exact original radio child")
	TEST_ASSERT(!monitor.handle_click_with_actor(actor, ""), "a plain click retains the original native parent fallback")
	TEST_ASSERT(monitor.enabled, "plain-click fallback itself does not run the alternate-toggle effect")
