/// Actual HUD hand buttons move the real clipboard between actual inventory slots.
/datum/unit_test/interim_clipboard_drop_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	var/atom/movable/screen/right = hud.r_hand_hud_object
	var/atom/movable/screen/left = hud.l_hand_hud_object
	TEST_ASSERT_NOTNULL(right, "actual human HUD creates its right hand button")
	TEST_ASSERT_NOTNULL(left, "actual human HUD creates its left hand button")
	TEST_ASSERT_EQUAL(right.name, "r_hand", "actual right button selects the existing branch")
	TEST_ASSERT_EQUAL(left.name, "l_hand", "actual left button selects the existing branch")
	var/obj/item/clipboard/board = allocate(/obj/item/clipboard, T)
	var/obj/item/unrelated = allocate(/obj/item, T)
	TEST_ASSERT(actor.put_in_r_hand(board), "actual clipboard begins in the initiating actor's right hand")
	TEST_ASSERT_EQUAL(board.handle_hand_drop(actor, left), TRUE, "real hand target is handled without parent dispatch")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), board, "explicit actor receives the exact clipboard in its left hand")
	TEST_ASSERT_NULL(actor.get_right_hand(), "actual transfer clears the original right hand")
	TEST_ASSERT(!bystander.item_is_in_hands(board), "transfer never hands the clipboard to the unrelated actor")
	actor.set_stat(UNCONSCIOUS)
	TEST_ASSERT_EQUAL(actor.stat, UNCONSCIOUS, "the actual source stat guard is active")
	board.handle_hand_drop(actor, right)
	TEST_ASSERT_EQUAL(actor.get_left_hand(), board, "the explicit source stat guard refuses actual hand movement")
	actor.set_stat(CONSCIOUS)
	TEST_ASSERT_EQUAL(board.handle_hand_drop(actor, unrelated), FALSE, "human non-screen drop retains native parent fallback selection")
	TEST_ASSERT_EQUAL(actor.get_left_hand(), board, "parent fallback selection does not execute hand transfer")
	var/mob/living/simple_mob/unsupported = allocate(/mob/living/simple_mob, T)
	TEST_ASSERT(!ishuman(unsupported), "actual unsupported actor fails the original type guard")
	TEST_ASSERT_EQUAL(board.handle_hand_drop(unsupported, right), TRUE, "unsupported actor preserves consumed no-parent branch")
	board.handle_hand_drop(null, right)
	TEST_ASSERT_EQUAL(actor.get_left_hand(), board, "null and unsupported actors leave the actual clipboard unchanged")
	board.handle_hand_drop(actor, right)
	TEST_ASSERT_EQUAL(actor.get_right_hand(), board, "the valid explicit actor moves its clipboard back to the real right slot")
	TEST_ASSERT_NULL(actor.get_left_hand(), "roundtrip clears the temporary real left slot")
	TEST_ASSERT_EQUAL(unrelated.loc, T, "hand movement leaves the unrelated physical item untouched")
