/// Actual item and projectile hits distinguish harmless contact from real silk destruction.
/datum/unit_test/interim_weaversilk_item_hit/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/obj/effect/weaversilk/wall/web = allocate(/obj/effect/weaversilk/wall)
	var/obj/item/pen/pen = allocate(/obj/item/pen)
	var/obj/item/tool/wrench/wrench = allocate(/obj/item/tool/wrench)
	TEST_ASSERT_EQUAL(pen.force, 0, "actual pen provides harmless contact")
	TEST_ASSERT(wrench.force > 0, "actual wrench provides a real damaging hit")
	TEST_ASSERT_EQUAL(test_op_handler(web, "interaction_hit_weaversilk", user, pen), OP_PASS, "actual harmless contact preserves afterattack forwarding")
	TEST_ASSERT(!QDELETED(web), "actual zero-force contact preserves the web")
	TEST_ASSERT_EQUAL(test_op_handler(web, "interaction_hit_weaversilk", user, wrench), OP_PASS, "actual damaging contact preserves afterattack forwarding")
	TEST_ASSERT(QDELETED(web), "actual wrench hit consumes the original silk wall")
	TEST_ASSERT(!QDELETED(wrench) && !QDELETED(user), "actual silk consumption preserves tool and actor")

/datum/unit_test/interim_weaversilk_projectile_hit/Run()
	var/obj/effect/weaversilk/floor/web = allocate(/obj/effect/weaversilk/floor)
	var/obj/item/projectile/beam/practice/practice = allocate(/obj/item/projectile/beam/practice)
	var/obj/item/projectile/beam/laser = allocate(/obj/item/projectile/beam)
	TEST_ASSERT_EQUAL(practice.get_structure_damage(), 0, "actual practice beam cannot damage structures")
	TEST_ASSERT(laser.get_structure_damage() > 0, "actual live laser damages structures")
	web.bullet_act(practice)
	TEST_ASSERT(!QDELETED(web), "actual practice beam preserves the original silk floor")
	web.bullet_act(laser)
	TEST_ASSERT(QDELETED(web), "actual live laser consumes the original silk floor")

/datum/unit_test/interim_weaversilk_generic_hit/Run()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	var/obj/effect/weaversilk/web = allocate(/obj/effect/weaversilk)
	generic_hit(web, user, 0)
	TEST_ASSERT(!QDELETED(web), "actual zero-damage generic hit preserves the web")
	generic_hit(web, user, 1)
	TEST_ASSERT(QDELETED(web), "actual nonzero generic hit consumes the web")
	TEST_ASSERT(!QDELETED(user), "actual generic cleanup preserves its actor")

/datum/unit_test/interim_weaversilk_nest_teardown/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/bed/double/weaversilk_nest/nest = allocate(/obj/structure/bed/double/weaversilk_nest, T)
	TEST_ASSERT(nest.buckle_mob(user, forced = TRUE), "actual silk nest restrains its occupant")
	TEST_ASSERT_EQUAL(test_op_handler(nest, "interaction_tear_down", user, null), OP_DECLINE, "actual occupied silk nest refuses teardown")
	TEST_ASSERT(!QDELETED(nest), "actual occupied teardown refusal preserves the original nest")
	TEST_ASSERT_EQUAL(user.buckled_to(), nest, "occupied refusal preserves the actual restraint")
	nest.unbuckle_mob(user)
	TEST_ASSERT_NULL(user.buckled_to(), "actual public release clears the occupied nest")
	TEST_ASSERT_EQUAL(test_op_handler(nest, "interaction_tear_down", user, null), TRUE, "actual empty nest reports teardown")
	TEST_ASSERT(QDELETED(nest), "actual empty teardown consumes the original nest")
	TEST_ASSERT(!QDELETED(user), "actual nest cleanup preserves its former occupant")

/datum/unit_test/interim_weaversilk_trap_teardown/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/effect/weaversilk/trap/trap = allocate(/obj/effect/weaversilk/trap, T)
	user.m_intent = I_RUN
	trap.Crossed(user)
	TEST_ASSERT_EQUAL(user.buckled_to(), trap, "actual running crossing ensnares the real target")
	TEST_ASSERT(!trap.trap_active, "actual crossing spends the trap")
	TEST_ASSERT_EQUAL(test_op_handler(trap, "interaction_tear_weaversilk", user, null), TRUE, "actual public hand tearing reports completion")
	TEST_ASSERT(QDELETED(trap), "actual tearing consumes the original occupied trap")
	TEST_ASSERT_NULL(user.buckled_to(), "actual trap cleanup releases its original restraint")
	TEST_ASSERT(!QDELETED(user), "actual trap cleanup preserves its restrained target")
