/// Mining shield software upgrades must consume the original disk before enabling stronger projection.
/datum/unit_test/interim_mining_shield_sticky_upgrade/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/personal_shield_generator/belt/mining/device = allocate(/obj/item/personal_shield_generator/belt/mining, T)
	var/obj/item/borg/upgrade/shield_upgrade/disk = allocate(/obj/item/borg/upgrade/shield_upgrade, T)
	TEST_ASSERT_EQUAL(device.upgraded, FALSE, "actual mining shield initializes without its software upgrade")
	var/original_modifier = device.modifier_type
	TEST_ASSERT(original_modifier != /datum/body_effect/shield_projection/mining/strong, "actual initialized device does not already use strong projection")
	TEST_ASSERT(user.put_in_active_hand(disk), "the actor holds the exact original upgrade disk")
	add_trait(disk, TRAIT_NODROP, "interim_shield_upgrade")
	TEST_ASSERT(user.release_refusal(disk, user), "actual inventory refuses sticky disk consumption")
	test_op_handler(device, "interaction_upgrade", user, disk)
	TEST_ASSERT_EQUAL(device.modifier_type, original_modifier, "refused consumption preserves original projection type")
	TEST_ASSERT_EQUAL(device.upgraded, FALSE, "refused consumption grants no software upgrade")
	TEST_ASSERT(!QDELETED(disk), "refused upgrade preserves exact original disk")
	TEST_ASSERT_EQUAL(user.get_active_hand(), disk, "refused upgrade preserves original source hand")
	TEST_ASSERT_EQUAL(disk.loc, user, "refused upgrade preserves inventory containment")
	remove_trait(disk, TRAIT_NODROP, "interim_shield_upgrade")
	test_op_handler(device, "interaction_upgrade", user, disk)
	TEST_ASSERT(QDELETED(disk), "allowed upgrade consumes exact original disk")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(device.upgraded, TRUE, "one consumed original grants actual software-upgrade state")
	TEST_ASSERT_EQUAL(device.modifier_type, /datum/body_effect/shield_projection/mining/strong, "one consumed original enables actual strong projection type")
	var/obj/item/borg/upgrade/shield_upgrade/replacement = allocate(/obj/item/borg/upgrade/shield_upgrade, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds a real second upgrade disk")
	test_op_handler(device, "interaction_upgrade", user, replacement)
	TEST_ASSERT(!QDELETED(replacement), "already upgraded device preserves original replacement disk")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "repeat refusal preserves replacement hand")
	TEST_ASSERT_EQUAL(device.modifier_type, /datum/body_effect/shield_projection/mining/strong, "repeat refusal preserves exact actual projection type")
