/// Camera film capacity must be backed by consumption of the original cartridge.
/datum/unit_test/interim_camera_sticky_film/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/camera/camera = allocate(/obj/item/camera, T)
	var/obj/item/camera_film/film = allocate(/obj/item/camera_film, T)
	TEST_ASSERT(camera.pictures_max > 0, "the actual camera has positive declared exposure capacity")
	camera.pictures_left = 0
	TEST_ASSERT(user.put_in_active_hand(film), "the actor holds the exact original film")
	add_trait(film, TRAIT_NODROP, "interim_camera_sticky")
	TEST_ASSERT(user.release_refusal(film, user), "actual inventory refuses sticky film consumption")
	test_op_handler(camera, "interaction_item", user, film)
	TEST_ASSERT_EQUAL(camera.pictures_left, 0, "refused consumption grants no exposures")
	TEST_ASSERT(!QDELETED(film), "refused refill preserves original film")
	TEST_ASSERT_EQUAL(user.get_active_hand(), film, "refused refill preserves exact original hand")
	TEST_ASSERT_EQUAL(film.loc, user, "refused refill preserves actual inventory containment")
	remove_trait(film, TRAIT_NODROP, "interim_camera_sticky")
	test_op_handler(camera, "interaction_item", user, film)
	TEST_ASSERT(QDELETED(film), "allowed refill consumes the exact original film")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed refill clears actual source hand")
	TEST_ASSERT_EQUAL(camera.pictures_left, camera.pictures_max, "one consumed film restores exactly declared exposure capacity")
	var/obj/item/camera_film/replacement = allocate(/obj/item/camera_film, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds a real replacement film")
	test_op_handler(camera, "interaction_item", user, replacement)
	TEST_ASSERT(!QDELETED(replacement), "a loaded camera preserves original replacement film")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "loaded-camera refusal preserves replacement hand")
	TEST_ASSERT_EQUAL(camera.pictures_left, camera.pictures_max, "loaded-camera refusal grants no extra exposures")
