/// A real anomaly utilizer respects battery release and ejects the same charged original without consuming its charge.
/datum/unit_test/interim_anodevice_sticky_battery/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/anodevice/device = allocate(/obj/item/anodevice, T)
	var/obj/item/anobattery/battery = allocate(/obj/item/anobattery, T)
	TEST_ASSERT(battery.capacity > 0, "the actual anomaly battery has positive declared capacity")
	battery.stored_charge = battery.capacity / 2
	battery.UpdateSprite()
	var/original_charge = battery.stored_charge
	var/original_capacity = battery.capacity
	TEST_ASSERT_NULL(device.inserted_battery(), "the actual utilizer starts with an empty battery bay")
	TEST_ASSERT(!device.activated, "the actual utilizer starts inactive")
	TEST_ASSERT(user.put_in_inactive_hand(device), "the actor holds the real utilizer in the other hand")
	TEST_ASSERT(user.put_in_active_hand(battery), "the actor holds the original charged battery to insert")
	add_trait(battery, TRAIT_NODROP, "interim_anodevice_sticky")
	TEST_ASSERT(user.release_refusal(battery, user), "the actual inventory refuses the sticky battery's release")
	test_op_handler(device, "interaction_item", user, battery)
	TEST_ASSERT_EQUAL(user.get_active_hand(), battery, "refused insertion preserves the exact original active hand")
	TEST_ASSERT_EQUAL(battery.loc, user, "refused insertion preserves actual inventory containment")
	TEST_ASSERT_NULL(device.inserted_battery(), "refused insertion leaves the actual battery bay empty")
	TEST_ASSERT_EQUAL(battery.stored_charge, original_charge, "refused insertion preserves the actual charge")
	TEST_ASSERT(!device.activated, "refused insertion activates no emission")
	remove_trait(battery, TRAIT_NODROP, "interim_anodevice_sticky")
	test_op_handler(device, "interaction_item", user, battery)
	TEST_ASSERT_EQUAL(device.inserted_battery(), battery, "allowed insertion records the exact original battery")
	TEST_ASSERT_EQUAL(battery.loc, device, "allowed insertion contains the original battery in the held device")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears the actual source hand")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), device, "allowed insertion preserves the device's original hand")
	TEST_ASSERT_NULL(owner_of(battery), "the bay preserves its existing non-owning relation policy")
	op_ui_act(user, device, "ejectbattery")
	TEST_ASSERT_NULL(device.inserted_battery(), "actual UI ejection clears the battery relation")
	TEST_ASSERT_EQUAL(battery.loc, T, "actual UI ejection returns the exact original battery to the floor")
	TEST_ASSERT_EQUAL(battery.stored_charge, original_charge, "the actual insertion and ejection round trip spends no charge")
	TEST_ASSERT_EQUAL(battery.capacity, original_capacity, "the actual round trip preserves the original capacity")
	TEST_ASSERT(!device.activated, "actual ejection leaves emission inactive")
	qdel(device)
	TEST_ASSERT(!QDELETED(battery), "the returned original battery survives empty-device teardown")
