/// Installing a stuck proximity sensor must not advance construction without consuming the part.
/datum/unit_test/interim_turret_sensor_consumption/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/porta_turret_construct/frame = allocate(/obj/machinery/porta_turret_construct, T)
	frame.set_anchored(TRUE)
	frame.build_step = 4
	var/obj/item/assembly/prox_sensor/sensor = allocate(/obj/item/assembly/prox_sensor, T)
	TEST_ASSERT(actor.put_in_active_hand(sensor), "The actor must hold the actual proximity sensor")
	add_trait(sensor, TRAIT_NODROP, "interim_turret_sensor_consumption")
	frame.interaction_install_prox(actor, sensor, null)
	TEST_ASSERT_EQUAL(frame.build_step, 4, "A refused sensor insertion must not advance construction")
	TEST_ASSERT(!QDELETED(sensor), "A refused insertion must preserve the actual sensor")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), sensor, "A refused insertion must preserve the occupied hand")
	remove_trait(sensor, TRAIT_NODROP, "interim_turret_sensor_consumption")
	frame.interaction_install_prox(actor, sensor, null)
	TEST_ASSERT_EQUAL(frame.build_step, 5, "A successful insertion must advance to the installed-sensor step")
	TEST_ASSERT(QDELETED(sensor), "A successful insertion must consume the exact sensor")
	TEST_ASSERT_NULL(actor.get_active_hand(), "A successful insertion must release the actor's actual hand")
	TEST_ASSERT(!QDELETED(frame), "Installing the sensor must preserve the unfinished frame")
