/// Real rig teardown disposes every original installed module through its owned list, preserving another rig.
/datum/unit_test/interim2_rig_owned_module_teardown/Run()
	var/turf/T = test_floor()
	var/obj/item/rig/internalaffairs/equipped/rig = allocate(/obj/item/rig/internalaffairs/equipped, T)
	var/obj/item/rig/internalaffairs/equipped/control = allocate(/obj/item/rig/internalaffairs/equipped, T)
	var/list/module_types = list(/obj/item/rig_module/ai_container, /obj/item/rig_module/device/flash, /obj/item/rig_module/device/paperdispenser, /obj/item/rig_module/device/pen, /obj/item/rig_module/device/stamp)
	TEST_ASSERT_EQUAL(length(rig.installed_modules), 5, "The real augmented-tie constructor must install its five canonical modules")
	TEST_ASSERT_EQUAL(length(control.installed_modules), 5, "The independent constructor must install its own five modules")
	var/list/originals = rig.installed_modules.Copy()
	var/list/controls = control.installed_modules.Copy()
	var/list/devices = list()
	for(var/i in 1 to 5)
		var/obj/item/rig_module/M = originals[i]
		var/obj/item/rig_module/C = controls[i]
		own(M)
		TEST_ASSERT_EQUAL(M.type, module_types[i], "The original constructor must preserve canonical ordered module types")
		TEST_ASSERT_EQUAL(C.type, module_types[i], "The independent constructor must preserve canonical ordered module types")
		TEST_ASSERT(M != C, "Independent rigs must construct distinct original module identities")
		TEST_ASSERT_EQUAL(owner_of(M), rig, "The actual rig must own every original installed module")
		TEST_ASSERT_EQUAL(M.vars[nameof(M.holder)], rig, "Each original module must retain its real installation backlink")
		TEST_ASSERT_EQUAL(M.loc, rig, "Each original module must remain physically inside its rig")
		TEST_ASSERT_EQUAL(owner_of(C), control, "The independent rig must own its original module")
		if(istype(M, /obj/item/rig_module/device))
			var/obj/item/rig_module/device/D = M
			TEST_ASSERT(istype(D.device), "A real mounted device module must construct its actual device")
			TEST_ASSERT_EQUAL(owner_of(D.device), D, "The original module must own its actual mounted device")
			TEST_ASSERT_EQUAL(D.device.loc, D, "The original mounted device must reside in its actual module")
			devices += D.device
			own(D.device)
	TEST_ASSERT(consume(rig), "Actual floor rig disposal must succeed")
	TEST_ASSERT(QDELETED(rig), "Actual disposal must destroy the original rig")
	for(var/obj/item/rig_module/M in originals)
		TEST_ASSERT(QDELETED(M), "Rig teardown must dispose of each exact original installed module")
		TEST_ASSERT_NULL(owner_of(M), "Teardown must clear every original module's ownership stamp")
	for(var/obj/item/D in devices)
		TEST_ASSERT(QDELETED(D), "Module teardown must dispose of each exact original mounted device")
	TEST_ASSERT(!QDELETED(control), "Teardown must preserve the exact independent rig")
	TEST_ASSERT_EQUAL(length(control.installed_modules), 5, "Teardown must preserve the independent actual module list")
	for(var/i in 1 to 5)
		var/obj/item/rig_module/C = controls[i]
		TEST_ASSERT_EQUAL(control.installed_modules[i], C, "Teardown must preserve each exact original independent module")
		TEST_ASSERT(!QDELETED(C), "Each independent original module must remain alive")
		TEST_ASSERT_EQUAL(owner_of(C), control, "Independent original module ownership must remain unchanged")
		TEST_ASSERT_EQUAL(C.vars[nameof(C.holder)], control, "Independent module installation backlinks must remain unchanged")
		TEST_ASSERT_EQUAL(C.loc, control, "Independent original module containment must remain unchanged")
