/datum/unit_test/interim_anomaly_battery_effect_custody/Run()
	var/turf/T = test_floor()
	var/obj/item/anobattery/battery = allocate(/obj/item/anobattery, T)
	var/obj/item/anobattery/control = allocate(/obj/item/anobattery, T)
	TEST_ASSERT_NULL(battery.battery_effect, "Real empty anomaly battery begins without an effect")
	TEST_ASSERT_NULL(control.battery_effect, "Independent actual battery begins without an effect")
	var/datum/artifact_effect/dnaswitch/original = allocate(/datum/artifact_effect/dnaswitch, battery)
	var/datum/artifact_effect/dnaswitch/independent = allocate(/datum/artifact_effect/dnaswitch, control)
	TEST_ASSERT(!QDELETED(original) && !QDELETED(independent), "Actual artifact-effect constructors produce live distinct records")
	TEST_ASSERT(original != independent, "Independent battery uses a distinct actual effect identity")
	TEST_ASSERT_EQUAL(original.get_master_holder(), battery, "Actual producer constructor binds the original effect to its battery")
	TEST_ASSERT_EQUAL(independent.get_master_holder(), control, "Independent actual effect binds to its own battery")
	rel_set(battery, nameof(battery.battery_effect), original)
	rel_set(control, nameof(control.battery_effect), independent)
	TEST_ASSERT_EQUAL(battery.battery_effect, original, "Supported production adoption retains exact original effect")
	TEST_ASSERT_EQUAL(owner_of(original), battery, "Original artifact effect belongs to its battery")
	TEST_ASSERT_EQUAL(owner_of(independent), control, "Independent effect has independent custody")
	own_clear(battery, nameof(battery.battery_effect), OWN_DELETE)
	TEST_ASSERT_NULL(battery.battery_effect, "Actual empty-battery reset clears the owned slot")
	TEST_ASSERT(QDELETED(original), "Actual empty-battery reset retires its exact original effect")
	TEST_ASSERT(!QDELETED(independent) && control.battery_effect == independent, "Reset preserves independent original effect and slot")
	var/datum/artifact_effect/dnaswitch/replacement = allocate(/datum/artifact_effect/dnaswitch, battery)
	rel_set(battery, nameof(battery.battery_effect), replacement)
	TEST_ASSERT_EQUAL(battery.battery_effect, replacement, "Refill owns the exact newly constructed replacement")
	TEST_ASSERT_EQUAL(owner_of(replacement), battery, "Replacement custody is the real battery")
	qdel(battery)
	TEST_ASSERT(QDELETED(battery), "Real battery teardown completes")
	TEST_ASSERT(QDELETED(replacement), "Battery teardown retires its exact currently owned artifact effect")
	TEST_ASSERT(!QDELETED(independent), "Other battery's original effect survives teardown")
	TEST_ASSERT_EQUAL(control.battery_effect, independent, "Other battery retains exact original effect")
	TEST_ASSERT_EQUAL(owner_of(independent), control, "Independent effect custody remains unchanged")
