/// A proximity sensor stuck to the hand does not go into the frame (the build does not advance and the sensor stays); a free one goes in and is used up.
/datum/unit_test/interim_turret_sensor_consumption/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/porta_turret_construct/frame = allocate(/obj/machinery/porta_turret_construct, T)
	frame.set_anchored(FALSE)
	var/obj/item/tool/wrench/wrench = dq_fast_tool(/obj/item/tool/wrench, T)
	var/obj/item/stack/material/steel/metal = allocate(/obj/item/stack/material/steel, T)
	metal.set_amount(2)
	var/obj/item/gun/energy/gun/gun = allocate(/obj/item/gun/energy/gun, T)
	for(var/obj/item/I as anything in list(wrench, metal, wrench, gun))
		actor.drop_item()
		actor.put_in_active_hand(I)
		hci_click(actor, frame, I)
		test_time(1 SECOND)
	TEST_ASSERT(built(frame, STAGE_TURRET_FRAME_ARMED), "(the frame has its gun)")
	actor.drop_item()
	var/obj/item/assembly/prox_sensor/sensor = allocate(/obj/item/assembly/prox_sensor, T)
	TEST_ASSERT(actor.put_in_active_hand(sensor), "The actor must hold the actual proximity sensor")
	add_trait(sensor, TRAIT_NODROP, "interim_turret_sensor_consumption")
	hci_click(actor, frame, sensor)
	test_time(1 SECOND)
	TEST_ASSERT(!built(frame, STAGE_TURRET_FRAME_SENSING), "A refused sensor insertion must not advance construction")
	TEST_ASSERT(!QDELETED(sensor), "A refused insertion must preserve the actual sensor")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), sensor, "A refused insertion must preserve the occupied hand")
	remove_trait(sensor, TRAIT_NODROP, "interim_turret_sensor_consumption")
	hci_click(actor, frame, sensor)
	test_time(1 SECOND)
	TEST_ASSERT(built(frame, STAGE_TURRET_FRAME_SENSING), "A successful insertion must advance to the installed-sensor step")
	TEST_ASSERT_NOTEQUAL(sensor.loc, actor, "A successful insertion takes the sensor from the hand")
	TEST_ASSERT_NULL(actor.get_active_hand(), "A successful insertion must release the actor's actual hand")
	TEST_ASSERT(!QDELETED(frame), "Installing the sensor must preserve the unfinished frame")
