/// Actual custom-paper storage respects release and returns the original sheet before stock paper.
/datum/unit_test/interim_paper_bin_sticky_paper/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/paper_bin/bin = allocate(/obj/item/paper_bin, T)
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	paper.info = "Original paper-bin record"
	var/stock_before = bin.amount
	TEST_ASSERT_EQUAL(stock_before, initial(bin.amount), "the actual bin starts with its declared stock")
	TEST_ASSERT_EQUAL(LAZYLEN(bin.papers), 0, "the actual bin starts without custom original papers")
	TEST_ASSERT(user.put_in_active_hand(paper), "the actor holds the original written sheet")
	add_trait(paper, TRAIT_NODROP, "interim_bin_sticky")
	TEST_ASSERT(user.release_refusal(paper, user), "actual inventory refuses sticky paper release")
	test_op_handler(bin, "interaction_item", user, paper)
	TEST_ASSERT_EQUAL(bin.amount, stock_before, "refused insertion adds no stock")
	TEST_ASSERT_EQUAL(LAZYLEN(bin.papers), 0, "refused insertion records no custom paper")
	TEST_ASSERT_EQUAL(user.get_active_hand(), paper, "refused insertion preserves exact original hand")
	TEST_ASSERT_EQUAL(paper.loc, user, "refused insertion preserves actual inventory containment")
	remove_trait(paper, TRAIT_NODROP, "interim_bin_sticky")
	test_op_handler(bin, "interaction_item", user, paper)
	TEST_ASSERT_EQUAL(bin.amount, stock_before + 1, "allowed insertion credits exactly one stored sheet")
	TEST_ASSERT_EQUAL(LAZYLEN(bin.papers), 1, "allowed insertion records exactly one custom sheet")
	TEST_ASSERT_EQUAL(bin.papers[1], paper, "the actual stored record preserves original identity")
	TEST_ASSERT_EQUAL(paper.loc, bin, "allowed insertion physically contains original sheet")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears actual source hand")
	TEST_ASSERT_NULL(owner_of(paper), "custom-paper storage preserves its existing relation policy")
	test_op_handler(bin, "interaction_hand", user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), paper, "public taking prioritizes the exact original custom sheet")
	TEST_ASSERT_EQUAL(paper.info, "Original paper-bin record", "actual storage and retrieval preserve original written information")
	TEST_ASSERT_EQUAL(bin.amount, stock_before, "one original retrieval refunds exactly one stock unit")
	TEST_ASSERT_EQUAL(LAZYLEN(bin.papers), 0, "actual retrieval clears its custom-paper relation")
	qdel(bin)
	TEST_ASSERT(!QDELETED(paper), "returned original sheet survives bin teardown")
