/// Dismantling the actual loaded drip must release its beaker and prepare six rods.
/datum/unit_test/interim_iv_drip_dismantle/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/iv_drip/drip = allocate(/obj/machinery/iv_drip, T)
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	beaker.reagents.add_reagent(REAGENT_ID_WATER, 10)
	TEST_ASSERT(actor.put_in_active_hand(beaker), "The actor must hold the actual reagent container")
	TEST_ASSERT_EQUAL(test_op_handler(drip, "iv_drip_interaction_item", actor, beaker), OP_OK, "The real insertion effect must accept the container")
	TEST_ASSERT_EQUAL(drip.beaker, beaker, "The actual drip must own the inserted container")
	TEST_ASSERT_NULL(actor.get_active_hand(), "Insertion must release the actor's hand")
	var/drip_handle = entity_handle(drip)
	var/list/before = turf_contents_of_type(T, /obj/item/stack/rods)
	drip.screwdriver_act_timed_done(actor)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(drip), "The actual completed action must remove the drip")
	var/list/created = turf_contents_of_type(T, /obj/item/stack/rods) - before
	TEST_ASSERT_EQUAL(length(created), 1, "Dismantling must prepare exactly one rods stack")
	var/obj/item/stack/rods/rods = created[1]
	TEST_ASSERT_EQUAL(rods.get_amount(), 6, "Dismantling must preserve the six-rod material yield")
	TEST_ASSERT_EQUAL(rods.loc, T, "The replacement rods must remain on the actual drip floor")
	TEST_ASSERT(!QDELETED(beaker), "The drip's deletion must preserve its released container")
	TEST_ASSERT_EQUAL(beaker.loc, T, "The separately released container must remain on the actual floor")
	TEST_ASSERT_EQUAL(beaker.reagents.total_volume, 10, "Dismantling must preserve the container contents")
	TEST_ASSERT(!QDELETED(actor), "Dismantling must preserve the actor")
	TEST_ASSERT_EQUAL(actor.loc, T, "Dismantling must preserve the actor's actual floor")
	TEST_ASSERT_NULL(actor.get_active_hand(), "Dismantling must not put either independent output in the actor's hand")
	TEST_ASSERT_NULL(resolve_handle(drip_handle), "A machinery drip handle must terminate for its cross-family item successor")
	qdel(rods)
	TEST_ASSERT(!QDELETED(beaker), "The released container must not become owned by the rods successor")
	TEST_ASSERT_EQUAL(beaker.loc, T, "Deleting the rods must preserve the independent floor container")
