/datum/unit_test/interim_reagent_implant_transfer_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/host = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/implant/reagent_generator/implant = allocate(/obj/item/implant/reagent_generator, T)
	implant.random_emote = list("looks relieved")
	TEST_ASSERT(implant.handle_implant(host), "the real implant API embeds the generator in its host")
	TEST_ASSERT_EQUAL(implant.imp_in(), host, "the actual implanted generator resolves its host")
	var/obj/item/organ/external/chest = host.get_organ(BP_TORSO)
	TEST_ASSERT(implant in chest.implants, "the real organ implant list contains the generator")
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	var/obj/item/reagent_containers/glass/beaker/host_beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	TEST_ASSERT(actor.put_in_active_hand(beaker), "the explicit actor holds the actual destination container")
	TEST_ASSERT(host.put_in_active_hand(host_beaker), "the implant host holds a separate container")
	TEST_ASSERT_EQUAL(implant.transfer_amount, 30, "the real generator's configured transfer is thirty units")
	TEST_ASSERT(implant.reagents.add_reagent(REAGENT_ID_WATER, 80), "the real generator stores eighty units of water")
	host.do_reagent_implant(actor)
	TEST_ASSERT_EQUAL(beaker.reagents.get_reagent_amount(REAGENT_ID_WATER), 30, "the real transfer delivers exactly the configured dose to the actor's container")
	TEST_ASSERT_EQUAL(implant.reagents.get_reagent_amount(REAGENT_ID_WATER), 50, "the real source loses exactly thirty units")
	TEST_ASSERT_EQUAL(host_beaker.reagents.total_volume, 0, "the separate host's held container receives no reagents")
	var/top_up = beaker.volume - beaker.reagents.total_volume - 5
	TEST_ASSERT(top_up >= 0, "the real destination has capacity to leave exactly five units free")
	beaker.reagents.add_reagent(REAGENT_ID_WATER, top_up)
	host.do_reagent_implant(actor)
	TEST_ASSERT_EQUAL(beaker.reagents.total_volume, beaker.volume, "the real transfer fills the last five units without overflowing")
	TEST_ASSERT_EQUAL(implant.reagents.get_reagent_amount(REAGENT_ID_WATER), 45, "capacity clamping removes exactly the five units delivered")
	host.do_reagent_implant(actor)
	TEST_ASSERT_EQUAL(implant.reagents.get_reagent_amount(REAGENT_ID_WATER), 45, "a full actual container refuses to consume source reagents")
	TEST_ASSERT_EQUAL(beaker.reagents.total_volume, beaker.volume, "full-container refusal leaves the destination unchanged")

/datum/unit_test/interim_reagent_implant_source_limit/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/host = allocate(/mob/living/carbon/human, T)
	var/obj/item/implant/reagent_generator/implant = allocate(/obj/item/implant/reagent_generator, T)
	implant.random_emote = list("looks relieved")
	TEST_ASSERT(implant.handle_implant(host), "the actual generator is implanted before use")
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	TEST_ASSERT(host.put_in_active_hand(beaker), "the actual host holds its destination container")
	TEST_ASSERT(implant.reagents.add_reagent(REAGENT_ID_WATER, 7), "the actual generator contains only seven units")
	host.do_reagent_implant(host)
	TEST_ASSERT_EQUAL(beaker.reagents.get_reagent_amount(REAGENT_ID_WATER), 7, "source clamping delivers exactly the seven available units")
	TEST_ASSERT_EQUAL(implant.reagents.total_volume, 0, "the real transfer exhausts the limited source")
	host.do_reagent_implant(host)
	TEST_ASSERT_EQUAL(beaker.reagents.get_reagent_amount(REAGENT_ID_WATER), 7, "an empty source cannot fabricate another configured dose")
	TEST_ASSERT_EQUAL(implant.reagents.total_volume, 0, "the empty source stays empty")
