/// Removing empty initialization wrappers retains actual declared contents and public behavior.
/datum/unit_test/interim_empty_content_init/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/food/drinks/bluespace_coffee/coffee = allocate(/obj/item/reagent_containers/food/drinks/bluespace_coffee, T)
	TEST_ASSERT_EQUAL(coffee.reagents.total_volume, 50, "actual declared infinite coffee starts with fifty units")
	TEST_ASSERT_EQUAL(coffee.reagents.get_reagent_amount(REAGENT_ID_COFFEE), 50, "actual infinite coffee starts with exactly coffee")
	TEST_ASSERT_EQUAL(coffee.amount_per_transfer_from_this, 5, "actual coffee retains its inherited sip amount")
	TEST_ASSERT(user.put_in_active_hand(coffee), "actual actor holds its real infinite coffee")
	var/ingested_before = user.ingested.get_reagent_amount(REAGENT_ID_COFFEE)
	user.next_click = 0
	test_click(user, user, coffee)
	test_time(3)
	TEST_ASSERT(abs(user.ingested.get_reagent_amount(REAGENT_ID_COFFEE) - ingested_before - 5) < 0.001, "actual self-drinking transfers the exact inherited five-unit sip")
	TEST_ASSERT_EQUAL(coffee.reagents.get_reagent_amount(REAGENT_ID_COFFEE), 50, "actual infinite coffee refills its source after drinking")
	TEST_ASSERT_EQUAL(coffee.reagents.total_volume, 50, "actual refill respects the original fifty-unit capacity")
	TEST_ASSERT(!QDELETED(coffee), "actual drinking preserves the same infinite coffee item")
	TEST_ASSERT_EQUAL(user.get_active_hand(), coffee, "actual drinking retains its original hand identity")
	test_driver_end()

/datum/unit_test/interim_empty_content_init/churro/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/food/snacks/churro/churro = allocate(/obj/item/reagent_containers/food/snacks/churro, T)
	TEST_ASSERT_EQUAL(churro.reagents.get_reagent_amount(REAGENT_ID_NUTRIMENT), 4, "actual parent adds four nutriment units from declared food data")
	TEST_ASSERT_EQUAL(churro.reagents.get_reagent_amount(REAGENT_ID_COOKINGOIL), 1, "actual lifecycle declaration retains one oil unit")
	TEST_ASSERT_EQUAL(churro.reagents.total_volume, 5, "actual churro starts with exactly five reagent units")
	TEST_ASSERT_EQUAL(churro.bitesize, 2, "actual churro retains its two-unit bite")
	TEST_ASSERT(user.put_in_active_hand(churro), "actual actor holds its initialized churro")
	var/ingested_before = user.ingested.total_volume
	TEST_ASSERT_EQUAL(interim_bite(user, churro), TRUE, "actual first churro bite executes")
	TEST_ASSERT_EQUAL(churro.reagents.total_volume, 3, "actual first bite debits two units")
	TEST_ASSERT_EQUAL(churro.bitecount, 1, "actual first bite records one bite")
	TEST_ASSERT(!QDELETED(churro), "actual partial bite preserves its churro")
	TEST_ASSERT_EQUAL(interim_bite(user, churro), TRUE, "actual second churro bite executes")
	TEST_ASSERT(abs(churro.reagents.total_volume - 1) < 0.001, "actual second bite leaves one unit within native reagent precision")
	TEST_ASSERT_EQUAL(interim_bite(user, churro), TRUE, "actual final churro bite executes")
	var/obj/item/trash = user.get_active_hand()
	own(trash)
	TEST_ASSERT(QDELETED(churro), "actual final bite consumes the original churro")
	TEST_ASSERT(abs(user.ingested.total_volume - ingested_before - 5) < 0.001, "actual bites transfer all five original units to the real ingest holder")
	TEST_ASSERT(trash && trash.type == /obj/item/paper/crumpled, "actual finished churro yields its exact declared paper trash")
	TEST_ASSERT_EQUAL(trash.loc, user, "actual churro trash is held by its original eater")
	test_driver_end()

/datum/unit_test/interim_empty_content_init/ecig/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/clothing/mask/smokable/ecig/simple/ecig = allocate(/obj/item/clothing/mask/smokable/ecig/simple, T)
	var/obj/item/reagent_containers/ecig_cartridge/cartridge = ecig.ec_cartridge
	TEST_ASSERT(cartridge, "actual lifecycle initialization constructs its cartridge")
	TEST_ASSERT_EQUAL(cartridge.type, /obj/item/reagent_containers/ecig_cartridge/med_nicotine, "actual ecig constructs its exact declared cartridge type")
	TEST_ASSERT_EQUAL(cartridge.loc, ecig, "actual initialized cartridge is contained by its ecig")
	TEST_ASSERT_EQUAL(cartridge.reagents.get_reagent_amount(REAGENT_ID_NICOTINE), 5, "actual cartridge starts with five nicotine units")
	TEST_ASSERT_EQUAL(cartridge.reagents.get_reagent_amount(REAGENT_ID_WATER), 15, "actual cartridge starts with fifteen water units")
	TEST_ASSERT(!ecig.active, "actual ecig starts off")
	TEST_ASSERT(user.equip_to_slot_if_possible(ecig, SLOT_ID_MASK), "actual actor wears its initialized ecig")
	TEST_ASSERT_EQUAL(test_op_handler(ecig, "toggled", user, ecig), OP_OK, "actual self-use ends the click")
	TEST_ASSERT(ecig.active, "actual self-use activates its ecig")
	var/ingested_before = user.ingested.total_volume
	test_time(3 SECONDS)
	TEST_ASSERT(abs(cartridge.reagents.total_volume - (20 - REM)) < 0.001, "actual worn vaping debits its exact original reagent effect amount")
	TEST_ASSERT(abs(user.ingested.total_volume - ingested_before - REM * 0.4) < 0.001, "actual worn vaping transfers the original retained fraction into its real ingest holder")
	TEST_ASSERT_EQUAL(user.get_equipped_item(SLOT_ID_MASK), ecig, "actual vaping preserves its original worn ecig")
	TEST_ASSERT(consume(ecig, user), "actual worn ecig can be consumed through checked removal")
	TEST_ASSERT(QDELETED(ecig) && QDELETED(cartridge), "actual ecig cleanup deletes its exact owned cartridge")
	TEST_ASSERT_NULL(user.get_equipped_item(SLOT_ID_MASK), "actual ecig cleanup clears its wearer slot")
	test_driver_end()

/datum/unit_test/interim_empty_content_init/rpd/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/item/pipe_dispenser/rpd = allocate(/obj/item/pipe_dispenser, T)
	var/obj/item/tool/wrench/tool = rpd.tool
	TEST_ASSERT(tool, "actual RPD lifecycle constructs its internal wrench")
	TEST_ASSERT_EQUAL(tool.type, /obj/item/tool/wrench/cyborg, "actual RPD constructs the exact declared wrench type")
	TEST_ASSERT_EQUAL(tool.loc, rpd, "actual initialized wrench remains in its original RPD")
	TEST_ASSERT_NULL(rpd.recipe(), "actual RPD starts without a selected recipe")
	rpd.SetupPipes()
	TEST_ASSERT(rpd.recipe(), "actual pipe setup resolves its live registered default recipe")
	TEST_ASSERT_EQUAL(rpd.recipe(), GLOB.atmos_pipe_recipes[GLOB.atmos_pipe_recipes[1]][1], "actual RPD selects the original first atmospheric recipe")
	var/datum/pipe_recipe/recipe = rpd.recipe()
	TEST_ASSERT(consume(rpd), "actual RPD can be consumed through its removal endpoint")
	TEST_ASSERT(QDELETED(rpd) && QDELETED(tool), "actual RPD cleanup deletes its original owned wrench")
	TEST_ASSERT(!QDELETED(recipe), "actual RPD cleanup preserves its shared registered recipe")
