/// Real inventory-panel construction uses the supplied viewer and preserves native fallback decisions.
/datum/unit_test/interim_living_inventory_drag_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "the real fixture has a distant floor for the existing adjacency guard")
	var/mob/living/carbon/human/source = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/viewer = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/obj/item/paper/paper = allocate(/obj/item/paper, T)
	TEST_ASSERT_NULL(source.inventory_panel, "the actual source starts with no inventory panel")
	TEST_ASSERT(!source.inventory_drop_with_actor(viewer, null), "a null actual drop target safely retains the original parent fallback")
	TEST_ASSERT(!source.inventory_drop_with_actor(viewer, paper), "an ordinary nonliving target retains the existing parent fallback")
	TEST_ASSERT(!source.inventory_drop_with_actor(null, viewer), "an absent supplied actor cannot satisfy the original viewer identity guard")
	TEST_ASSERT(!source.inventory_drop_with_actor(bystander, viewer), "a different supplied actor retains parent fallback without selecting the viewer")
	TEST_ASSERT(!source.inventory_drop_with_actor(source, source), "the existing source-self guard retains parent fallback")
	TEST_ASSERT_NULL(source.inventory_panel, "all actual identity refusals leave the source panel absent")
	viewer.forceMove(far)
	TEST_ASSERT(!source.Adjacent(viewer), "the actual distant viewer fails the existing adjacency predicate")
	TEST_ASSERT(!source.inventory_drop_with_actor(viewer, viewer), "distant viewer drag retains parent fallback")
	TEST_ASSERT_NULL(source.inventory_panel, "actual distant viewer cannot construct the source inventory panel")
	viewer.forceMove(T)
	TEST_ASSERT(source.Adjacent(viewer), "the actual supplied viewer is adjacent before the successful effect")
	TEST_ASSERT(!viewer.is_incorporeal(), "the real human viewer passes the existing corporeal target guard")
	TEST_ASSERT(!source.inventory_drop_with_actor(viewer, viewer), "successful panel construction still retains the original parent fallback")
	var/datum/inventory_panel/human/panel = source.inventory_panel
	TEST_ASSERT(istype(panel) && !QDELETED(panel), "the actual effect constructs the real human inventory panel without claiming client delivery")
	TEST_ASSERT_EQUAL(panel.host, source, "the real panel constructor retains its exact original living source")
	TEST_ASSERT_EQUAL(owner_of(panel), source, "the actual source owns its constructed inventory panel")
	TEST_ASSERT_NULL(viewer.inventory_panel, "actual viewer selection never constructs a panel on the viewer")
	TEST_ASSERT_NULL(bystander.inventory_panel, "actual viewer selection never constructs a panel on the unrelated actor")
	TEST_ASSERT(!source.inventory_drop_with_actor(viewer, viewer), "repeated real viewer selection retains parent fallback")
	TEST_ASSERT_EQUAL(source.inventory_panel, panel, "the actual effect reuses its original source-owned panel")
	TEST_ASSERT_EQUAL(source.loc, T, "inventory-panel construction preserves the original source location")
	TEST_ASSERT_EQUAL(viewer.loc, T, "inventory-panel construction preserves the real viewer location")
