/// The real camera upgrade route respects inventory release and records removable list members from its first insertion.
/datum/unit_test/interim_camera_sticky_upgrade/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/camera_assembly/assembly = allocate(/obj/item/camera_assembly, T)
	var/obj/item/assembly/prox_sensor/upgrade = allocate(/obj/item/assembly/prox_sensor, T)
	var/obj/item/tool/crowbar/crowbar = allocate(/obj/item/tool/crowbar, T)
	var/original_state = assembly.state
	TEST_ASSERT_NULL(assembly.upgrades, "the actual fresh camera has no allocated upgrade list")
	TEST_ASSERT(user.put_in_active_hand(upgrade), "the actor holds the actual supported camera upgrade")
	add_trait(upgrade, TRAIT_NODROP, "interim_camera_sticky_upgrade")
	TEST_ASSERT(user.release_refusal(upgrade, user), "the real inventory refuses the sticky upgrade")
	test_click(user, assembly, upgrade)
	TEST_ASSERT_NULL(assembly.upgrades, "refused release records no upgrade member")
	TEST_ASSERT_EQUAL(user.get_active_hand(), upgrade, "refused release preserves the exact held slot")
	TEST_ASSERT_EQUAL(upgrade.loc, user, "refused release preserves actual inventory containment")
	remove_trait(upgrade, TRAIT_NODROP, "interim_camera_sticky_upgrade")
	test_click(user, assembly, upgrade)
	TEST_ASSERT(islist(assembly.upgrades), "the first actual upgrade creates a real upgrade list")
	TEST_ASSERT_EQUAL(LAZYLEN(assembly.upgrades), 1, "the first actual upgrade records exactly one member")
	TEST_ASSERT(upgrade in assembly.upgrades, "the actual upgrade list contains the original sensor")
	TEST_ASSERT_EQUAL(owner_of(upgrade), assembly, "the existing implicit upgrade ownership stamps the original sensor")
	TEST_ASSERT_EQUAL(upgrade.loc, assembly, "the checked upgrade physically enters its actual assembly")
	TEST_ASSERT_NULL(user.get_active_hand(), "the checked upgrade clears the original source hand")
	TEST_ASSERT_EQUAL(assembly.state, original_state, "upgrade insertion preserves the construction stage")
	TEST_ASSERT(user.put_in_active_hand(crowbar), "the actor holds the real upgrade-removal tool")
	TEST_ASSERT(assembly.crowbar_act(user, crowbar), "the public crowbar action removes the original upgrade")
	TEST_ASSERT_EQUAL(upgrade.loc, T, "actual crowbar removal returns the original sensor to the floor")
	TEST_ASSERT_EQUAL(LAZYLEN(assembly.upgrades), 0, "actual crowbar removal empties the recorded upgrade list")
	TEST_ASSERT_NULL(owner_of(upgrade), "actual crowbar removal clears the upgrade ownership stamp")
	TEST_ASSERT_EQUAL(user.get_active_hand(), crowbar, "actual crowbar removal preserves its real tool")
	qdel(assembly)
	TEST_ASSERT(!QDELETED(upgrade), "empty camera-assembly teardown preserves its removed original upgrade")
	TEST_ASSERT_EQUAL(upgrade.loc, T, "empty assembly teardown preserves the returned upgrade floor location")
