/// Actual infrared beam endpoints preserve their original emitter, clear owned beam identities, and leave no blocked-step orphan.
/datum/unit_test/interim_infrared_beam_endpoints/Run()
	var/turf/T = test_floor()
	var/turf/beam_floor = get_step(T, EAST)
	TEST_ASSERT(beam_floor && !beam_floor.density, "The actual beam fixture has an adjacent passable floor")
	var/obj/item/assembly/infra/emitter = allocate(/obj/item/assembly/infra, T)
	emitter.set_dir(EAST)
	emitter.set_secured(TRUE)
	emitter.toggle_state(TRUE)
	TEST_ASSERT(emitter.secured && emitter.on, "The original actual emitter is secured and switched on")
	var/list/before = turf_contents_of_type(beam_floor, /obj/effect/beam/i_beam)
	emitter.create_beams(1)
	own_turf_contents(beam_floor)
	TEST_ASSERT_EQUAL(length(emitter.i_beams), 1, "The real emitter owns exactly one actually constructed beam")
	var/obj/effect/beam/i_beam/beam = emitter.i_beams[1]
	TEST_ASSERT(beam && !QDELETED(beam), "The original actual beam survives successful construction")
	TEST_ASSERT_EQUAL(beam.master(), emitter, "The actual beam retains its exact original emitter relation")
	TEST_ASSERT_EQUAL(beam.loc, beam_floor, "The actual beam constructor steps onto its original adjacent floor")
	var/obj/item/pen/crossing = allocate(/obj/item/pen, T)
	TEST_ASSERT(step(crossing, EAST), "The real original pen actually crosses the constructed beam")
	TEST_ASSERT(QDELETED(beam), "Actual crossing triggers and removes the original emitter-owned beam")
	TEST_ASSERT(!LAZYLEN(emitter.i_beams), "Actual crossing clears the original emitter's owned beam list")
	TEST_ASSERT(!QDELETED(emitter) && emitter.loc == T && emitter.on, "Actual beam triggering preserves the original switched-on emitter")
	TEST_ASSERT(!QDELETED(crossing) && crossing.loc == beam_floor, "Actual beam triggering preserves the exact crossing pen on its destination floor")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(beam_floor, /obj/effect/beam/i_beam)), length(before), "Actual crossing leaves no additional beam product on the original floor")

/datum/unit_test/interim_infrared_beam_endpoints/blocked/Run()
	var/turf/T = test_floor()
	var/turf/beam_floor = get_step(T, EAST)
	TEST_ASSERT(beam_floor && !beam_floor.density, "The actual blocked-beam fixture has an adjacent passable floor")
	var/obj/structure/largecrate/blocker = allocate(/obj/structure/largecrate, beam_floor)
	TEST_ASSERT(blocker.density, "The actual ordinary crate is a real dense beam obstacle")
	var/obj/item/assembly/infra/emitter = allocate(/obj/item/assembly/infra, T)
	emitter.set_dir(EAST)
	emitter.set_secured(TRUE)
	emitter.toggle_state(TRUE)
	var/list/original_floor = turf_contents_of_type(T, /obj/effect/beam/i_beam)
	var/list/blocked_floor = turf_contents_of_type(beam_floor, /obj/effect/beam/i_beam)
	emitter.create_beams(1)
	TEST_ASSERT(!LAZYLEN(emitter.i_beams), "The actual failed movement retains no emitter-owned beam")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(T, /obj/effect/beam/i_beam)), length(original_floor), "The real collision endpoint removes its unowned beam from the source floor")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(beam_floor, /obj/effect/beam/i_beam)), length(blocked_floor), "The real blocked step creates no beam product on its destination floor")
	TEST_ASSERT(!QDELETED(emitter) && emitter.loc == T && emitter.on, "Actual collision cleanup preserves the exact active emitter")
	TEST_ASSERT(!QDELETED(blocker) && blocker.loc == beam_floor, "Actual collision cleanup preserves the exact real obstacle")

/datum/unit_test/interim_infrared_beam_endpoints/orphan/Run()
	var/turf/T = test_floor()
	var/obj/effect/beam/i_beam/beam = allocate(/obj/effect/beam/i_beam, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(beam && !QDELETED(beam), "The actual orphan starts alive before its real periodic endpoint")
	TEST_ASSERT_NULL(beam.master(), "The actual orphan has no surviving emitter relation")
	beam.i_beam_step(null)
	TEST_ASSERT(QDELETED(beam), "The actual periodic endpoint consumes the exact orphan beam")
	TEST_ASSERT(!QDELETED(pen) && pen.loc == T, "Actual orphan cleanup preserves the exact unrelated floor pen")
