/// Actual cube loading respects release and returns the same undeployed original through its public use-in-hand removal.
/datum/unit_test/interim_monkey_rehydrator_sticky_cube/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/xenobio/monkey_gun/device = allocate(/obj/item/xenobio/monkey_gun, T)
	var/obj/item/reagent_containers/food/snacks/monkeycube/cube = allocate(/obj/item/reagent_containers/food/snacks/monkeycube, T)
	TEST_ASSERT_NULL(device.loaded_item, "the actual rehydrator starts without a loaded cube")
	TEST_ASSERT(istype(cube, device.loadable_item), "the actual original cube matches the device's declared loadable type")
	TEST_ASSERT(user.put_in_inactive_hand(device), "the actor holds the real rehydrator in the other hand")
	TEST_ASSERT(user.put_in_active_hand(cube), "the actor holds the original actual cube")
	add_trait(cube, TRAIT_NODROP, "interim_rehydrator_sticky")
	TEST_ASSERT(user.release_refusal(cube, user), "the actual inventory refuses release of the sticky cube")
	test_op_handler(device, "interaction_item", user, cube)
	TEST_ASSERT_EQUAL(user.get_active_hand(), cube, "refused loading preserves the exact original hand")
	TEST_ASSERT_EQUAL(cube.loc, user, "refused loading preserves actual inventory containment")
	TEST_ASSERT_NULL(device.loaded_item, "refused loading records no cube")
	remove_trait(cube, TRAIT_NODROP, "interim_rehydrator_sticky")
	test_op_handler(device, "interaction_item", user, cube)
	TEST_ASSERT_EQUAL(device.loaded_item, cube, "allowed loading records the exact original cube")
	TEST_ASSERT_EQUAL(cube.loc, device, "allowed loading physically contains the original cube")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed loading clears the actual source hand")
	TEST_ASSERT_NULL(owner_of(cube), "loading preserves the device's existing unowned containment policy")
	test_op_handler(device, "interaction_self", user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), cube, "actual removal returns the exact original undeployed cube")
	TEST_ASSERT_EQUAL(cube.loc, user, "actual removal restores original inventory containment")
	TEST_ASSERT_NULL(device.loaded_item, "actual removal clears the device's recorded original")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), device, "actual loading and removal preserve the device's original hand")
	qdel(device)
	TEST_ASSERT(!QDELETED(cube), "the original returned cube survives empty-device teardown")
