/// The actual clipboard pen slot must respect source inventory release before recording its original pen.
/datum/unit_test/interim_clipboard_sticky_pen_slot/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/clipboard/board = allocate(/obj/item/clipboard, T)
	user.put_in_inactive_hand(board) // the window works in the hand that holds it
	user.put_in_inactive_hand(board) // the window works in the hand that holds it
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT_NULL(board.haspen(), "actual initialized clipboard starts without a slotted pen")
	TEST_ASSERT(user.put_in_active_hand(pen), "the actor holds exact original pen")
	add_trait(pen, TRAIT_NODROP, "interim_clipboard_pen_slot")
	TEST_ASSERT(user.release_refusal(pen, user), "actual inventory refuses sticky pen release")
	op_ui_act(user, board, "add_pen")
	TEST_ASSERT_EQUAL(user.get_active_hand(), pen, "refused slotting preserves original source hand")
	TEST_ASSERT_EQUAL(pen.loc, user, "refused slotting preserves inventory containment")
	TEST_ASSERT_NULL(board.haspen(), "refused slotting records no clipboard pen")
	remove_trait(pen, TRAIT_NODROP, "interim_clipboard_pen_slot")
	op_ui_act(user, board, "add_pen")
	TEST_ASSERT_EQUAL(board.haspen(), pen, "allowed slotting records exact original pen")
	TEST_ASSERT_EQUAL(pen.loc, board, "allowed slotting physically contains original pen")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed slotting clears actual source hand")
	TEST_ASSERT_NULL(owner_of(pen), "pen slotting preserves existing relation-only policy")
	var/obj/item/pen/replacement = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds actual replacement pen")
	op_ui_act(user, board, "add_pen")
	TEST_ASSERT_EQUAL(board.haspen(), pen, "occupied slot retains exact original pen")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "occupied-slot refusal preserves replacement hand")
	TEST_ASSERT(user.unEquip(replacement), "actor releases replacement before retrieving original")
	op_ui_act(user, board, "remove_pen")
	TEST_ASSERT_EQUAL(user.get_active_hand(), pen, "public removal returns exact original pen")
	TEST_ASSERT_EQUAL(pen.loc, user, "public removal restores actual inventory containment")
	TEST_ASSERT_NULL(board.haspen(), "public removal clears original pen relation")
	qdel(board)
	TEST_ASSERT(!QDELETED(pen), "returned original pen survives empty clipboard teardown")
