/// Reclaiming an actual linked original beacon must consume it before returning deployment capacity.
/datum/unit_test/interim_translocator_sticky_beacon_reclaim/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/perfect_tele/device = allocate(/obj/item/perfect_tele, T)
	var/obj/item/perfect_tele_beacon/beacon = allocate(/obj/item/perfect_tele_beacon, T)
	TEST_ASSERT_EQUAL(device.beacons_left, initial(device.beacons_left), "actual device starts with declared deployment capacity")
	TEST_ASSERT_EQUAL(LAZYLEN(device.beacons), 0, "actual initialized device starts without linked beacons")
	rel_set(beacon, nameof(beacon.tele_hand), device)
	rel_add(device, nameof(device.beacons), beacon)
	device.beacons_left--
	var/deployed_capacity = device.beacons_left
	TEST_ASSERT((beacon in device.beacons), "actual deployed fixture records exact original beacon through its relation")
	TEST_ASSERT(user.put_in_active_hand(beacon), "the actor holds exact original linked beacon")
	add_trait(beacon, TRAIT_NODROP, "interim_translocator_beacon")
	TEST_ASSERT(user.release_refusal(beacon, user), "actual inventory refuses sticky beacon consumption")
	test_op_handler(device, "interaction_item", user, beacon)
	TEST_ASSERT(!QDELETED(beacon), "refused reclaim preserves exact original beacon")
	TEST_ASSERT_EQUAL(user.get_active_hand(), beacon, "refused reclaim preserves original source hand")
	TEST_ASSERT_EQUAL(beacon.loc, user, "refused reclaim preserves inventory containment")
	TEST_ASSERT((beacon in device.beacons), "refused reclaim preserves exact original deployed relation")
	TEST_ASSERT_EQUAL(device.beacons_left, deployed_capacity, "refused consumption refunds no deployment capacity")
	remove_trait(beacon, TRAIT_NODROP, "interim_translocator_beacon")
	test_op_handler(device, "interaction_item", user, beacon)
	TEST_ASSERT(QDELETED(beacon), "allowed reclaim consumes exact original linked beacon")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed consumption clears actual source hand")
	TEST_ASSERT_EQUAL(LAZYLEN(device.beacons), 0, "allowed reclaim removes original deployed relation")
	TEST_ASSERT_EQUAL(device.beacons_left, deployed_capacity + 1, "one consumed original refunds exactly one deployment slot")
	var/obj/item/perfect_tele_beacon/unrelated = allocate(/obj/item/perfect_tele_beacon, T)
	TEST_ASSERT(user.put_in_active_hand(unrelated), "the actor holds an actual unrelated beacon")
	test_op_handler(device, "interaction_item", user, unrelated)
	TEST_ASSERT(!QDELETED(unrelated), "unrelated beacon refusal preserves exact original item")
	TEST_ASSERT_EQUAL(user.get_active_hand(), unrelated, "unrelated beacon refusal preserves source hand")
	TEST_ASSERT_EQUAL(device.beacons_left, deployed_capacity + 1, "unrelated beacon grants no capacity refund")
