/// Actual PDA pen insertion respects source release and returns the same original pen.
/datum/unit_test/interim_pda_sticky_pen/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/pda/device = allocate(/obj/item/pda, T)
	var/obj/item/pen/pen = locate_within(device, /obj/item/pen)
	TEST_ASSERT_NOTNULL(pen, "the actual PDA initializes with a real original pen")
	own(pen)
	TEST_ASSERT(user.put_in_inactive_hand(device), "the actor holds the actual PDA in the other hand")
	device.remove_pen(user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), pen, "actual removal first returns the initialized original pen")
	TEST_ASSERT_NULL(locate_within(device, /obj/item/pen), "actual removal empties the pen slot")
	add_trait(pen, TRAIT_NODROP, "interim_pda_sticky_pen")
	TEST_ASSERT(user.release_refusal(pen, user), "actual inventory refuses the sticky pen")
	test_op_handler(device, "interaction_item", user, pen)
	TEST_ASSERT_EQUAL(user.get_active_hand(), pen, "refused insertion preserves the exact original hand")
	TEST_ASSERT_EQUAL(pen.loc, user, "refused insertion preserves actual inventory containment")
	TEST_ASSERT_NULL(locate_within(device, /obj/item/pen), "refused insertion leaves no pen inside")
	remove_trait(pen, TRAIT_NODROP, "interim_pda_sticky_pen")
	test_op_handler(device, "interaction_item", user, pen)
	TEST_ASSERT_EQUAL(locate_within(device, /obj/item/pen), pen, "allowed insertion contains the exact initialized original pen")
	TEST_ASSERT_EQUAL(pen.loc, device, "allowed insertion physically contains the original pen")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears the actual source hand")
	TEST_ASSERT_NULL(owner_of(pen), "insertion preserves original unowned PDA pen containment")
	device.remove_pen(user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), pen, "public removal again returns the exact original pen")
	TEST_ASSERT_EQUAL(pen.loc, user, "public removal restores original inventory containment")
	qdel(device)
	TEST_ASSERT(!QDELETED(pen), "the returned original pen survives empty PDA teardown")
