/// A real deployable barrier's two emag stages bypass authentication then disable lock toggling; real wrench repair restores authentication without moving the anchored barrier.
/datum/unit_test/interim_barrier_emag_stages/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/deployable/barrier/barrier = allocate(/obj/machinery/deployable/barrier, T)
	var/obj/item/card/id/id = allocate(/obj/item/card/id, T)
	var/obj/item/tool/wrench/wrench = allocate(/obj/item/tool/wrench, T)
	TEST_ASSERT(user.put_in_active_hand(id), "the actual actor holds an ID with no security access")
	TEST_ASSERT(user.put_in_inactive_hand(wrench), "the actual actor also holds the real repair wrench")
	TEST_ASSERT(!barrier.allowed(user), "the actual barrier's security restriction refuses the actor")
	TEST_ASSERT(!barrier.locked && !barrier.anchored, "the actual barrier starts unlocked and movable")
	test_op_handler(barrier, "interaction_swipe_id", user, id)
	TEST_ASSERT(!barrier.locked && !barrier.anchored, "the real unauthorized ID swipe preserves lock and anchoring")
	var/first_uses = emag_target(barrier, 1, user)
	own_turf_contents(T)
	TEST_ASSERT_EQUAL(first_uses, 1, "the first actual emag consumes one use")
	TEST_ASSERT_EQUAL(barrier.emagged, 1, "the first actual emag records the authentication-bypass stage")
	TEST_ASSERT_NULL(barrier.req_access, "the first actual emag removes the security-access restriction")
	TEST_ASSERT(barrier.allowed(user), "the same actual actor is allowed after authentication bypass")
	test_op_handler(barrier, "interaction_swipe_id", user, id)
	TEST_ASSERT(barrier.locked && barrier.anchored, "the real now-authorized ID swipe locks and anchors the barrier")
	var/second_uses = emag_target(barrier, 1, user)
	own_turf_contents(T)
	TEST_ASSERT_EQUAL(second_uses, 1, "the second actual emag consumes one additional use")
	TEST_ASSERT_EQUAL(barrier.emagged, 2, "the second actual emag records the disabled-anchoring-mechanism stage")
	test_op_handler(barrier, "interaction_swipe_id", user, id)
	own_turf_contents(T)
	TEST_ASSERT(barrier.locked && barrier.anchored, "the real ID swipe cannot toggle a second-stage damaged mechanism")
	TEST_ASSERT(emag_target(barrier, 1, user) <= 0, "a fully damaged mechanism consumes no third emag use (declined)")
	TEST_ASSERT_EQUAL(barrier.emagged, 2, "a repeated actual emag preserves the second-stage damage")
	user.next_click = 0
	test_click(user, barrier, wrench)
	TEST_ASSERT_EQUAL(barrier.emagged, 0, "actual wrench repair clears both emag stages")
	TEST_ASSERT(!barrier.allowed(user), "actual wrench repair restores the security-access refusal for the same ID")
	TEST_ASSERT(ACCESS_SECURITY in barrier.req_access, "actual wrench repair restores the security-access requirement")
	TEST_ASSERT(barrier.locked && barrier.anchored, "actual repair preserves existing lock and anchoring")
	test_op_handler(barrier, "interaction_swipe_id", user, id)
	TEST_ASSERT(barrier.locked && barrier.anchored, "the real unauthorized swipe after repair cannot release the barrier")
