/// Actual pressure entry and native answers retain a live borrowed tool and cancel when that same tool disappears.
/datum/unit_test/interim_pneumatic_pressure_borrowed_capture/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/item/gun/launcher/pneumatic/gun = allocate(/obj/item/gun/launcher/pneumatic, T)
	var/obj/item/tool/wrench/tool = allocate(/obj/item/tool/wrench, T)
	TEST_ASSERT_EQUAL(gun.pressure_setting, 10, "the actual gun starts at its canonical pressure setting")
	TEST_ASSERT((50 in gun.possible_pressure_amounts) && (25 in gun.possible_pressure_amounts), "both actual selected pressures belong to the production choices")
	gun.pneumatic_verb_set_pressure(user, tool, null)
	var/datum/prompt/choice/pneumatic_pressure/first = SSrequests.open_for(user)
	TEST_ASSERT_NOTNULL(first, "the actual pressure entry opens a request")
	TEST_ASSERT(first.captured_item == tool && first.item_expected, "the request weakly captures the exact borrowed tool")
	TEST_ASSERT(!first.interaction_expected, "a null original interaction is a valid capture")
	test_answer(user, 50)
	TEST_ASSERT_EQUAL(first.outcome, REQ_ANSWERED, "a live borrowed tool permits the real answer")
	TEST_ASSERT_EQUAL(gun.pressure_setting, 50, "the real accepted choice changes pressure")
	TEST_ASSERT(!QDELETED(tool), "answering does not dispose the borrowed tool")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "the first actual request completes")
	gun.pneumatic_verb_set_pressure(user, tool, null)
	var/datum/prompt/choice/pneumatic_pressure/second = SSrequests.open_for(user)
	TEST_ASSERT_NOTNULL(second, "the second actual entry opens a request")
	TEST_ASSERT(second != first && second.captured_item == tool, "the second request captures the same exact live tool")
	qdel(tool)
	TEST_ASSERT(QDELETED(tool), "the original borrowed tool is actually deleted")
	test_answer(user, 25)
	TEST_ASSERT_EQUAL(second.outcome, REQ_CANCELLED, "the actual answer cancels after the originally captured tool is gone")
	TEST_ASSERT_EQUAL(gun.pressure_setting, 50, "canceled continuation preserves the exact prior pressure")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "the canceled request unregisters")
	test_driver_end()
