/// A real large pouch delays removal and preserves its ledger until the actual task completes.
/datum/unit_test/om/interim_pouch_delayed_removal/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/pouch/large/pouch = allocate(/obj/item/storage/pouch/large, T)
	var/obj/item/pen/item = allocate(/obj/item/pen, T)
	made += list(user, pouch, item)
	TEST_ASSERT(pouch.insert_item(item), "the real large pouch accepts the actual pen")
	var/used_before = pouch.slot_used()
	TEST_ASSERT(used_before > 0, "the actual stored pen occupies capacity")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual removal actor starts capable")
	TEST_ASSERT(!pouch.remove_from_storage(item, T, user), "the real large pouch defers removal while resting on the floor")
	TEST_ASSERT(test_actor_busy(user), "the actual removal entry starts its timed task")
	TEST_ASSERT_EQUAL(item.loc, pouch, "pending removal leaves the actual pen inside")
	TEST_ASSERT(item in pouch.slot_contents(CONTAINER_SLOT_STORAGE), "pending removal retains the actual storage ledger entry")
	TEST_ASSERT_EQUAL(pouch.slot_used(), used_before, "pending removal retains occupied capacity")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual actor remains capable through the single short removal")
	TEST_ASSERT(!test_actor_busy(user), "completed actual removal releases its pending task")
	TEST_ASSERT_EQUAL(item.loc, T, "actual delayed removal reaches the requested floor")
	TEST_ASSERT(!(item in pouch.slot_contents(CONTAINER_SLOT_STORAGE)), "actual delayed removal clears the pen's ledger entry")
	TEST_ASSERT_EQUAL(pouch.slot_used(), 0, "actual delayed removal releases all occupied capacity")
	TEST_ASSERT(!pouch.stall_passed, "the actual completion restores the pouch's delay gate")

/// Moving the real actor cancels delayed removal without losing the stored item or its capacity accounting.
/datum/unit_test/om/interim_pouch_removal_movement_cancel/run_om(list/made)
	var/turf/T = test_floor()
	var/turf/other = get_step(T, EAST)
	TEST_ASSERT_NOTNULL(other, "the actual actor has a neighboring turf for movement cancellation")
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/storage/pouch/large/pouch = allocate(/obj/item/storage/pouch/large, T)
	var/obj/item/pen/item = allocate(/obj/item/pen, T)
	made += list(user, pouch, item)
	TEST_ASSERT(pouch.insert_item(item), "the real large pouch accepts the cancellation fixture's pen")
	var/used_before = pouch.slot_used()
	TEST_ASSERT(used_before > 0, "the actual stored cancellation pen occupies capacity")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual cancellation actor starts capable")
	TEST_ASSERT(!pouch.remove_from_storage(item, T, user), "the actual removal entry starts with a deferred move")
	TEST_ASSERT(test_actor_busy(user), "the actual removal task is pending before actor movement")
	user.forceMove(other)
	TEST_ASSERT_EQUAL(user.loc, other, "the actual actor really moves off the captured task turf")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the moved actor remains capable so movement is the refusal cause")
	TEST_ASSERT(!test_actor_busy(user), "movement-cancelled removal releases its actual task")
	TEST_ASSERT_EQUAL(item.loc, pouch, "movement cancellation preserves the actual stored pen")
	TEST_ASSERT(item in pouch.slot_contents(CONTAINER_SLOT_STORAGE), "movement cancellation preserves the pen's ledger entry")
	TEST_ASSERT_EQUAL(pouch.slot_used(), used_before, "movement cancellation preserves occupied capacity")
	TEST_ASSERT(!pouch.stall_passed, "movement cancellation never bypasses the pouch delay gate")
