/// Electrification history keeps actor and ambient entries in order, including repeated actions.
/datum/unit_test/interim_airlock_electrification_history/Run()
	test_driver_begin()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human)
	actor.name = "Interim Electrification Operator"
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock)
	p2_door_set_power(door, TRUE)
	TEST_ASSERT(door.power_systems_on(), "the real door has working internal power")
	var/before = length(door.shockedby)
	door.electrify((2 SECONDS) / (1 SECOND), SRC_LOCKDOWN, actor)
	TEST_ASSERT(door.electrified, "the actor actually electrifies the real door")
	TEST_ASSERT_EQUAL(length(door.shockedby), before + 1, "actor electrification appends exactly one history entry")
	var/actor_entry = door.shockedby[before + 1]
	TEST_ASSERT(findtext(actor_entry, "[actor](ckey:[actor.ckey])"), "the actor entry preserves the operator and ckey text")
	door.electrify(0)
	TEST_ASSERT(!door.electrified, "disabling electrification clears the real shock state")
	TEST_ASSERT_EQUAL(length(door.shockedby), before + 1, "disabling electrification adds no fabricated shock entry")
	door.electrify((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(door.electrified, "ambient electrification still activates the real door")
	TEST_ASSERT_EQUAL(length(door.shockedby), before + 2, "ambient electrification appends exactly one entry")
	TEST_ASSERT(findtext(door.shockedby[before + 2], " - EMP)"), "ambient history preserves its existing EMP label")
	door.electrify((2 SECONDS) / (1 SECOND), SRC_LOCKDOWN, actor)
	TEST_ASSERT_EQUAL(length(door.shockedby), before + 3, "repeated electrification appends instead of replacing history")
	TEST_ASSERT_EQUAL(door.shockedby[before + 1], actor_entry, "later actions preserve the original history entry")
	TEST_ASSERT(findtext(door.shockedby[before + 3], "[actor](ckey:[actor.ckey])"), "the final repeated entry credits the actual actor")
