/// Deliver the actual native drop under the established synthetic native actor boundary.
/obj/interim_cup_return_actor_click
	var/obj/item/reagent_containers/food/drinks/sillycup/cup
	var/obj/destination

/obj/interim_cup_return_actor_click/Click(location, control, params)
	cup.MouseDrop(destination)

/datum/unit_test/interim_cup_return_actor/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "a real distant floor exists for the original range predicate")
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	var/obj/structure/reagent_dispensers/water_cooler/full/cooler = allocate(/obj/structure/reagent_dispensers/water_cooler/full, T)
	TEST_ASSERT(cooler.cupholder, "actual full cooler initializes its real cup dispenser")
	TEST_ASSERT_EQUAL(cooler.cups, 10, "actual full cooler initializes ten available cups")
	var/obj/item/reagent_containers/food/drinks/sillycup/extra = allocate(/obj/item/reagent_containers/food/drinks/sillycup, T)
	TEST_ASSERT_EQUAL(extra.reagents.total_volume, 0, "actual paper cup initializes empty")
	TEST_ASSERT_EQUAL(extra.cup_return_with_actor(actor, cooler), TRUE, "full-capacity empty-cup branch remains consumed")
	TEST_ASSERT_EQUAL(cooler.cups, 10, "full dispenser refuses an eleventh cup")
	TEST_ASSERT(!QDELETED(extra), "capacity refusal preserves the exact empty paper cup")
	var/list/before = turf_contents_of_type(T, /obj/item/reagent_containers/food/drinks/sillycup)
	test_op_handler(cooler, "interaction_hand", actor)
	var/list/products = turf_contents_of_type(T, /obj/item/reagent_containers/food/drinks/sillycup) - before
	TEST_ASSERT_EQUAL(length(products), 1, "real dispensing creates exactly one actual paper cup")
	var/obj/item/reagent_containers/food/drinks/sillycup/cup = own(products[1])
	TEST_ASSERT_EQUAL(cooler.cups, 9, "actual dispensing removes exactly one stored cup")
	TEST_ASSERT_EQUAL(cup.loc, T, "real dispensed cup rests on the actual cooler floor")
	TEST_ASSERT_EQUAL(cup.reagents.total_volume, 0, "real dispensed paper cup begins empty")
	actor.forceMove(far)
	TEST_ASSERT(!cooler.Adjacent(actor), "actual distant actor fails the existing range guard")
	TEST_ASSERT(cooler.Adjacent(bystander), "unrelated actual nearby human satisfies range independently")
	TEST_ASSERT_EQUAL(cup.cup_return_with_actor(actor, cooler), TRUE, "distant empty-cup branch retains native consumption")
	TEST_ASSERT(!QDELETED(cup), "explicit distant actor preserves the exact cup despite the nearby bystander")
	TEST_ASSERT_EQUAL(cooler.cups, 9, "distant refusal cannot credit the nearby bystander with a return")
	actor.forceMove(T)
	var/obj/structure/reagent_dispensers/water_cooler/no_holder = allocate(/obj/structure/reagent_dispensers/water_cooler, T)
	TEST_ASSERT(!no_holder.cupholder, "actual ordinary cooler has no installed cup dispenser")
	TEST_ASSERT_EQUAL(cup.cup_return_with_actor(actor, no_holder), TRUE, "missing dispenser retains the original consumed branch")
	TEST_ASSERT_EQUAL(no_holder.cups, 0, "missing dispenser cannot gain a stored cup")
	TEST_ASSERT(!QDELETED(cup), "missing dispenser preserves the exact real cup")
	cup.reagents.add_reagent(REAGENT_ID_WATER, 1)
	TEST_ASSERT_EQUAL(cup.reagents.total_volume, 1, "actual water addition establishes a nonempty cup")
	TEST_ASSERT_EQUAL(cup.cup_return_with_actor(actor, cooler), FALSE, "nonempty real cup selects the original native parent fallback")
	TEST_ASSERT_EQUAL(cup.reagents.total_volume, 1, "parent selection preserves the exact drink volume")
	TEST_ASSERT_EQUAL(cooler.cups, 9, "nonempty cup cannot replenish the dispenser")
	cup.reagents.clear_reagents()
	TEST_ASSERT_EQUAL(cup.reagents.total_volume, 0, "actual reagent removal restores an empty returnable cup")
	var/obj/item/unrelated = allocate(/obj/item, T)
	TEST_ASSERT_EQUAL(cup.cup_return_with_actor(actor, unrelated), FALSE, "non-cooler target selects the original native parent fallback")
	TEST_ASSERT(!QDELETED(cup), "fallback branch selection retains the exact real cup")
	var/obj/interim_cup_return_actor_click/native = allocate(/obj/interim_cup_return_actor_click, T)
	native.cup = cup
	native.destination = cooler
	TEST_ASSERT(actor.put_in_active_hand(cup), "the actual actor holds the exact dispensed empty cup")
	add_trait(cup, TRAIT_NODROP, "interim_cup_return_actor")
	TEST_ASSERT(actor.release_refusal(cup, actor), "actual sticky held cup refuses the real consumption release")
	km_synthetic_click(actor, native)
	TEST_ASSERT(!QDELETED(cup), "actual native sticky return preserves the exact original cup")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), cup, "actual native sticky refusal preserves the exact occupied hand")
	TEST_ASSERT_EQUAL(cup.loc, actor, "actual sticky refusal preserves the real held source")
	TEST_ASSERT_EQUAL(cooler.cups, 9, "actual refused consumption cannot grant dispenser stock")
	TEST_ASSERT_EQUAL(cup.reagents.total_volume, 0, "actual refused consumption preserves the empty cup state")
	remove_trait(cup, TRAIT_NODROP, "interim_cup_return_actor")
	TEST_ASSERT_NULL(actor.release_refusal(cup, actor), "actual trait removal allows the original source release")
	km_synthetic_click(actor, native)
	TEST_ASSERT(QDELETED(cup), "actual native drop consumes the exact dispensed cup")
	TEST_ASSERT_NULL(actor.get_active_hand(), "successful consumption clears the actual actor hand before stock credit")
	TEST_ASSERT_EQUAL(cooler.cups, 10, "actual native return restores exactly one stored cup")
	TEST_ASSERT(!QDELETED(extra), "returning the dispensed cup preserves the unrelated extra cup")
	TEST_ASSERT_EQUAL(extra.loc, T, "return preserves the unrelated real cup location")
