/// Real aiming relationships survive retargeting and cancellation.
/datum/unit_test/interim_aiming_relationships/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/first = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/second = allocate(/mob/living/carbon/human, T)
	var/obj/item/binoculars/tool = allocate(/obj/item/binoculars, T)
	TEST_ASSERT(actor.put_in_active_hand(tool), "the actor holds the actual aiming tool")
	own_set(actor, nameof(actor.aiming), new /obj/aiming_overlay(actor))
	var/obj/aiming_overlay/aim = actor.aiming
	TEST_ASSERT_NOTNULL(aim, "the actor owns a real aiming overlay")
	TEST_ASSERT_EQUAL(aim.owner(), actor, "the overlay retains its actual owner")
	aim.aim_at(first, tool)
	TEST_ASSERT_EQUAL(aim.aiming_at, first, "aiming selects the first target")
	TEST_ASSERT(aim in first.aimed, "the first target tracks the real aiming relationship")
	aim.aim_at(second, tool)
	TEST_ASSERT_EQUAL(aim.aiming_at, second, "retargeting selects the second target")
	TEST_ASSERT_EQUAL(length(first.aimed), 0, "retargeting removes the prior target relationship")
	TEST_ASSERT(aim in second.aimed, "the second target tracks the same overlay")
	actor.stop_aiming(tool, TRUE)
	TEST_ASSERT_NULL(aim.aiming_at, "cancellation clears the targeted mob")
	TEST_ASSERT_NULL(aim.aiming_with(), "cancellation clears the held-tool relationship")
	TEST_ASSERT_EQUAL(length(second.aimed), 0, "cancellation clears the target's incoming aim")
	second.forceMove(T)
	second.trigger_aiming(TARGET_CAN_MOVE)
	TEST_ASSERT_EQUAL(length(second.aimed), 0, "movement and trigger checks preserve an empty incoming relationship")
