/// Actual granted actions and HUD groups exercise reset attribution and layout.
/datum/unit_test/interim_action_palette_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/other = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	var/datum/hud/other_hud = allocate(/datum/hud, other)
	hud.build_action_groups()
	other_hud.build_action_groups()
	var/obj/item/flashlight/light = allocate(/obj/item/flashlight, T)
	var/obj/item/flashlight/other_light = allocate(/obj/item/flashlight, T)
	var/datum/action/item_action/toggle_flashlight/action = allocate(/datum/action/item_action/toggle_flashlight, light)
	var/datum/action/item_action/toggle_flashlight/other_action = allocate(/datum/action/item_action/toggle_flashlight, other_light)
	action.Grant(actor)
	other_action.Grant(other)
	var/atom/movable/screen/movable/action_button/button = action.button_for(hud)
	var/atom/movable/screen/movable/action_button/other_button = other_action.button_for(other_hud)
	TEST_ASSERT_NOTNULL(button, "actual actor grant creates its HUD viewer")
	TEST_ASSERT_NOTNULL(other_button, "actual unrelated grant creates its HUD viewer")
	var/atom/movable/screen/button_palette/palette = hud.toggle_palette
	TEST_ASSERT_EQUAL(palette.our_hud(), hud, "the actual HUD owns the palette")
	hud.position_action(button, SCRN_OBJ_IN_PALETTE)
	TEST_ASSERT(button in hud.palette_actions.actions, "the actual button occupies the palette")
	TEST_ASSERT(!palette.expanded, "the real palette begins collapsed")
	km_synthetic_click(actor, palette)
	TEST_ASSERT(palette.expanded, "the native click expands the populated palette")
	palette.click_with_actor(actor, null, null, "left=1")
	TEST_ASSERT(!palette.expanded, "the explicit helper collapses the populated palette")
	hud.position_action(button, "2,2")
	other_hud.position_action(other_button, "3,3")
	TEST_ASSERT_EQUAL(button.location, SCRN_OBJ_FLOATING, "actor button has an actual custom position")
	TEST_ASSERT_EQUAL(other_button.location, SCRN_OBJ_FLOATING, "unrelated button has an actual custom position")
	TEST_ASSERT_EQUAL(palette.click_with_actor(actor, null, null, "alt=1"), TRUE, "alternate reset preserves the successful return")
	TEST_ASSERT_EQUAL(button.location, action.default_button_position, "explicit actor reset restores the actual default location")
	TEST_ASSERT(button in hud.listed_actions.actions, "the reset inserts the actual actor button in its default group")
	TEST_ASSERT(!(button in hud.floating_actions), "reset removes the actual floating membership")
	TEST_ASSERT_EQUAL(other_button.location, SCRN_OBJ_FLOATING, "reset leaves unrelated actor placement unchanged")
	TEST_ASSERT_EQUAL(other_button.screen_loc, "3,3", "reset preserves unrelated exact coordinates")
	palette.click_with_actor(other, null, null, "alt=1")
	TEST_ASSERT_EQUAL(other_button.location, other_action.default_button_position, "the permissive existing palette resets the explicitly supplied second actor")
	TEST_ASSERT(other_button in other_hud.listed_actions.actions, "the second reset updates the second actor's actual HUD group")
	TEST_ASSERT_EQUAL(button.linked_action(), action, "layout changes preserve the granted action relation")
	TEST_ASSERT(!light.on && !other_light.on, "layout clicks never activate either actual flashlight")
