/datum/unit_test/interim_directional_shield_edge_cleanup/Run()
	var/turf/T = test_floor()
	var/turf/east = get_step(T, EAST)
	var/turf/east_twice = get_step(east, EAST)
	TEST_ASSERT(T && east && east_twice, "The real fixture has two existing eastern destinations")
	var/obj/item/shield_projector/projector = allocate(/obj/item/shield_projector, T)
	projector.create_shield(east, EAST)
	own_turf_contents(east)
	TEST_ASSERT_EQUAL(length(projector.active_shields), 1, "The actual creation helper registers one original shield")
	var/obj/effect/directional_shield/offset = projector.active_shields[1]
	TEST_ASSERT(offset && !QDELETED(offset) && offset.loc == east, "The actual constructor creates its exact offset shield")
	TEST_ASSERT_EQUAL(offset.projector, projector, "The actual shield records its original real projector")
	TEST_ASSERT_EQUAL(offset.x_offset, 1, "The actual constructor computes the original one-tile east offset")
	TEST_ASSERT_EQUAL(offset.y_offset, 0, "The actual constructor computes no north-south offset")
	projector.create_shield(T, NORTH)
	own_turf_contents(T)
	TEST_ASSERT_EQUAL(length(projector.active_shields), 2, "The actual helper registers a distinct center shield")
	var/obj/effect/directional_shield/center
	for(var/obj/effect/directional_shield/S as anything in projector.active_shields)
		if(S != offset)
			center = S
	TEST_ASSERT(center && !QDELETED(center) && center.loc == T, "The actual helper creates a real original center shield")
	var/integrity_before = projector.get_integrity()
	projector.forceMove(east)
	offset.relocate()
	center.relocate()
	TEST_ASSERT(!QDELETED(offset) && offset.loc == east_twice, "Real relocation follows the actual projector while its offset destination exists")
	TEST_ASSERT(!QDELETED(center) && center.loc == east, "Real center relocation follows the actual projector exactly")
	var/turf/edge = locate(world.maxx, T.y, T.z)
	TEST_ASSERT(edge, "The real world contains its actual eastern edge turf")
	TEST_ASSERT_NULL(locate(edge.x + 1, edge.y, edge.z), "The actual computed east-offset destination is genuinely outside the world")
	projector.forceMove(edge)
	if(!QDELETED(offset))
		offset.relocate()
	center.relocate()
	TEST_ASSERT(QDELETED(offset), "Real relocation consumes the exact shield whose original offset leaves the world")
	TEST_ASSERT(!QDELETED(center) && center.loc == edge, "Real edge cleanup preserves and relocates the exact original center shield")
	TEST_ASSERT_EQUAL(center.projector, projector, "The surviving center shield retains its original projector link")
	TEST_ASSERT(!QDELETED(projector) && projector.loc == edge, "Real edge cleanup preserves the exact original projector")
	TEST_ASSERT_EQUAL(projector.get_integrity(), integrity_before, "Real edge cleanup preserves the projector's actual integrity")
