/// Real spore construction and reassignment maintain both reciprocal relations.
/datum/unit_test/interim_blob_native_pairs/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/obj/structure/blob/factory/first_factory = allocate(/obj/structure/blob/factory, T)
	var/obj/structure/blob/factory/second_factory = allocate(/obj/structure/blob/factory, T)
	var/mob/living/simple_mob/blob/spore/spore = allocate(/mob/living/simple_mob/blob/spore, T, first_factory)
	TEST_ASSERT_EQUAL(spore.factory, first_factory, "Actual spore initialization retains its factory")
	TEST_ASSERT((spore in first_factory.spores), "Actual spore initialization registers the reverse factory relation")
	rel_set(spore, nameof(spore.factory), second_factory)
	TEST_ASSERT_EQUAL(spore.factory, second_factory, "Factory reassignment changes the scalar endpoint")
	TEST_ASSERT(!(spore in first_factory.spores), "Factory reassignment removes the old reverse endpoint")
	TEST_ASSERT((spore in second_factory.spores), "Factory reassignment registers the new reverse endpoint")
	var/mob/observer/blob/first_overmind = allocate(/mob/observer/blob, T)
	var/mob/observer/blob/second_overmind = allocate(/mob/observer/blob, T)
	rel_set(spore, nameof(spore.overmind), first_overmind)
	TEST_ASSERT_EQUAL(spore.overmind, first_overmind, "Overmind adoption changes the scalar endpoint")
	TEST_ASSERT((spore in first_overmind.blob_mobs), "Overmind adoption registers the reverse relation")
	rel_set(spore, nameof(spore.overmind), second_overmind)
	TEST_ASSERT(!(spore in first_overmind.blob_mobs), "Overmind reassignment removes the old reverse endpoint")
	TEST_ASSERT((spore in second_overmind.blob_mobs), "Overmind reassignment registers the new reverse endpoint")
	rel_clear(spore, nameof(spore.overmind))
	TEST_ASSERT_NULL(spore.overmind, "Clearing overmind drops the scalar endpoint")
	TEST_ASSERT(!(spore in second_overmind.blob_mobs), "Clearing overmind drops the reverse endpoint")
	TEST_ASSERT_EQUAL(spore.factory, second_factory, "Clearing overmind preserves the independent factory relation")
	rel_clear(spore, nameof(spore.factory))
	TEST_ASSERT_NULL(spore.factory, "Clearing factory drops the scalar endpoint")
	TEST_ASSERT(!(spore in second_factory.spores), "Clearing factory drops the reverse endpoint")
