/// The actual dropper item draws its configured mixture and preserves undelivered liquid across a full-target refusal.
/datum/unit_test/interim_dropper_container_dose
	parent_type = /datum/unit_test/dq_p2_reagents

/datum/unit_test/interim_dropper_container_dose/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = rc_actor(T)
	var/obj/item/reagent_containers/dropper/dropper = allocate(/obj/item/reagent_containers/dropper, T)
	var/obj/item/reagent_containers/glass/beaker/source = allocate(/obj/item/reagent_containers/glass/beaker, T)
	var/obj/item/reagent_containers/glass/beaker/target = allocate(/obj/item/reagent_containers/glass/beaker, T)
	source.reagents.add_reagent(REAGENT_ID_WATER, 30)
	source.reagents.add_reagent(REAGENT_ID_ETHANOL, 10)
	TEST_ASSERT_EQUAL(dropper.amount_per_transfer_from_this, 5, "the actual dropper starts with a five-unit dose")
	TEST_ASSERT_EQUAL(dropper.reagents.maximum_volume, 5, "the actual dropper has five units of capacity")
	var/turf/far = get_step(get_step(get_step(T, EAST), EAST), EAST)
	TEST_ASSERT(isfloorturf(far), "the actual out-of-reach source has a real distant floor")
	source.forceMove(far)
	TEST_ASSERT(!user.Adjacent(source), "the actual remote source fails native reach")
	rc_click(user, source, dropper)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 40, "an out-of-reach actual draw cannot debit source liquid")
	TEST_ASSERT_EQUAL(dropper.reagents.total_volume, 0, "an out-of-reach draw cannot fill the dropper")
	source.forceMove(T)
	TEST_ASSERT(user.Adjacent(source), "the actual source is returned within native reach")
	rc_click(user, source, dropper)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 35, "the actual draw debits its configured five units")
	TEST_ASSERT_EQUAL(dropper.reagents.total_volume, 5, "the actual draw fills the dropper")
	TEST_ASSERT_EQUAL(dropper.reagents.get_reagent_amount(REAGENT_ID_WATER), 3.75, "the actual draw preserves the water mixture fraction")
	TEST_ASSERT_EQUAL(dropper.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 1.25, "the actual draw preserves the ethanol mixture fraction")
	var/target_water_before = target.reagents.maximum_volume - 1
	target.reagents.add_reagent(REAGENT_ID_WATER, target_water_before)
	rc_click(user, target, dropper)
	TEST_ASSERT_EQUAL(target.reagents.total_volume, target.reagents.maximum_volume, "the actual dropper fills the target's final one-unit capacity")
	TEST_ASSERT_EQUAL(target.reagents.get_reagent_amount(REAGENT_ID_WATER), target_water_before + 0.75, "the actual capacity-limited dose delivers its water fraction")
	TEST_ASSERT_EQUAL(target.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 0.25, "the actual capacity-limited dose delivers its ethanol fraction")
	TEST_ASSERT_EQUAL(dropper.reagents.total_volume, 4, "the actual capacity-limited dose retains four undelivered units")
	rc_click(user, target, dropper)
	TEST_ASSERT_EQUAL(dropper.reagents.total_volume, 4, "a full-target refusal preserves actual remaining dropper liquid")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, target.reagents.maximum_volume, "a full-target refusal preserves target capacity")
	target.reagents.clear_reagents()
	rc_click(user, target, dropper)
	TEST_ASSERT_EQUAL(dropper.reagents.total_volume, 0, "the actual next dose empties the four remaining units")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 4, "the actual target receives all four remaining units")
	TEST_ASSERT_EQUAL(target.reagents.get_reagent_amount(REAGENT_ID_WATER), 3, "the remaining real dose preserves its water fraction")
	TEST_ASSERT_EQUAL(target.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 1, "the remaining real dose preserves its ethanol fraction")
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 35, "delivering and refusing doses do not debit the independent source again")
