/datum/unit_test/interim_cleanable_wash_cleanup/Run()
	var/turf/T = test_floor()
	var/obj/effect/decal/cleanable/ash/source = allocate(/obj/effect/decal/cleanable/ash, T)
	var/obj/effect/decal/cleanable/other = allocate(/obj/effect/decal/cleanable, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(source && !QDELETED(source) && source.loc == T, "The actual ash completes its real original floor constructor")
	TEST_ASSERT_EQUAL(source.clean_type, CLEAN_TYPE_LIGHT_DECAL, "The actual ash retains its canonical light-decal cleaning requirement")
	source.germ_level = 7
	TEST_ASSERT_EQUAL(source.germ_level, 7, "The actual dirty source has nonzero germs before washing")
	TEST_ASSERT(!source.wash(CLEAN_TYPE_HARD_DECAL), "The actual mismatched cleaning method retains its original refusal result")
	TEST_ASSERT(!QDELETED(source) && source.loc == T, "Actual mismatched washing preserves the exact original ash")
	TEST_ASSERT_EQUAL(source.germ_level, 0, "Actual mismatched washing still preserves the original parent germ-cleaning effect")
	TEST_ASSERT(source.wash(CLEAN_TYPE_LIGHT_DECAL), "Actual matching washing retains its original success result")
	TEST_ASSERT(QDELETED(source), "Actual matching washing consumes the exact original ash")
	TEST_ASSERT(!QDELETED(other) && other.loc == T, "Actual washing preserves the exact unrelated neighboring decal")
	TEST_ASSERT(!QDELETED(pen) && pen.loc == T, "Actual washing preserves the unrelated original floor item")
