/// Real granted action buttons move among actual HUD groups through explicit drop actors.
/datum/unit_test/interim_action_button_drop_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/other = allocate(/mob/living/carbon/human, T)
	var/datum/hud/hud = allocate(/datum/hud, actor)
	var/datum/hud/other_hud = allocate(/datum/hud, other)
	hud.build_action_groups()
	other_hud.build_action_groups()
	var/obj/item/flashlight/light = allocate(/obj/item/flashlight, T)
	var/datum/action/item_action/toggle_flashlight/action = allocate(/datum/action/item_action/toggle_flashlight, light)
	action.Grant(actor)
	var/atom/movable/screen/movable/action_button/button = action.button_for(hud)
	TEST_ASSERT_NOTNULL(button, "real grant creates the actual actor viewer")
	TEST_ASSERT(button.can_use(actor) && !button.can_use(other), "actual viewer authorization distinguishes the two real HUDs")
	TEST_ASSERT((button in hud.listed_actions.actions), "the real action starts in its actual listed group")
	hud.generate_landings(button)
	var/atom/movable/screen/action_landing/listed = hud.listed_actions.landing
	var/atom/movable/screen/action_landing/palette = hud.palette_actions.landing
	rel_set(button, nameof(button.last_hovored), hud.toggle_palette)
	TEST_ASSERT_EQUAL(button.drop_with_actor(other, hud.toggle_palette), TRUE, "unauthorized drop retains native-consumed return")
	TEST_ASSERT_NULL(button.last_hovored, "original drop ordering clears hover even for an unauthorized viewer")
	TEST_ASSERT_EQUAL(hud.listed_actions.landing, listed, "unauthorized drop preserves actual owner landing")
	TEST_ASSERT((button in hud.listed_actions.actions), "unauthorized drop preserves exact group membership")
	TEST_ASSERT_EQUAL(button.drop_with_actor(actor, hud.toggle_palette), TRUE, "actual palette drop is native-consumed")
	TEST_ASSERT_EQUAL(button.location, SCRN_OBJ_IN_PALETTE, "actual authorized drop moves to the palette location")
	TEST_ASSERT((button in hud.palette_actions.actions), "actual authorized drop inserts exact button into palette")
	TEST_ASSERT(!(button in hud.listed_actions.actions), "actual movement removes the old listed membership")
	TEST_ASSERT(QDELETED(listed) && QDELETED(palette), "actual drop hides and disposes both generated landings")
	hud.generate_landings(button)
	listed = hud.listed_actions.landing
	TEST_ASSERT_EQUAL(button.drop_with_actor(actor, listed), TRUE, "actual landing drop is native-consumed")
	TEST_ASSERT_EQUAL(button.location, SCRN_OBJ_IN_LIST, "actual landing hit restores listed location")
	TEST_ASSERT((button in hud.listed_actions.actions), "actual landing hit restores exact listed membership")
	TEST_ASSERT(!(button in hud.palette_actions.actions), "actual landing movement clears the palette membership")
	TEST_ASSERT(QDELETED(listed), "actual landing hit disposes its consumed landing")
	hud.generate_landings(button)
	listed = hud.listed_actions.landing
	TEST_ASSERT_EQUAL(button.drop_with_actor(actor, button), TRUE, "actual self drop retains consumed branch")
	TEST_ASSERT(QDELETED(listed), "actual self drop clears visible landings")
	TEST_ASSERT((button in hud.listed_actions.actions), "actual self drop preserves real listed placement")
	TEST_ASSERT_EQUAL(button.drop_with_actor(actor, light), FALSE, "unrecognized target selects original native parent fallback")
	TEST_ASSERT((button in hud.listed_actions.actions), "helper fallback performs no premature floating move")
	TEST_ASSERT_NULL(other_hud.listed_actions.landing, "all actual drops leave unrelated HUD untouched")
	TEST_ASSERT_EQUAL(button.linked_action(), action, "all layout moves preserve real granted action link")
	TEST_ASSERT(!light.on, "actual layout drops never activate the flashlight")
