/// Actual spray setup consumes a nullspace spray before chemical exposure or travel.
/datum/unit_test/interim_effect_location_cleanup/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/effect/effect/water/spray = allocate(/obj/effect/effect/water, T)
	TEST_ASSERT(!QDELETED(spray), "actual water effect initializes alive")
	TEST_ASSERT(time_scheduler().timer_count(spray) > 0, "actual water effect initializes its expiration deadline")
	TEST_ASSERT_EQUAL(spray.steps_left, 0, "actual water effect begins without travel steps")
	spray.step_process()
	TEST_ASSERT(!spray.spraying, "actual unconfigured spray is not travelling")
	TEST_ASSERT(!QDELETED(spray), "actual unconfigured spray preserves its effect until expiry")
	spray.moveToNullspace()
	TEST_ASSERT_NULL(spray.loc, "actual public nullspace helper removes the spray from the world")
	spray.set_up(T, 5, 0.5 SECONDS, user)
	TEST_ASSERT(QDELETED(spray), "actual target setup consumes a spray with no location on its first step")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(spray), 0, "actual nullspace spray cleanup cancels its owned deadlines")
	TEST_ASSERT(!QDELETED(user), "actual invalid-location spray cleanup preserves its linked actor")
	TEST_ASSERT_EQUAL(user.loc, T, "actual early spray cleanup preserves its actor floor")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/effect/effect/water)), 0, "actual early cleanup produces no replacement spray")

/// Actual weeds moved into space die on their next processing call without harming the node.
/datum/unit_test/interim_effect_location_cleanup/weeds/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/turf/other_floor = get_step(T, EAST)
	TEST_ASSERT(istype(other_floor, /turf/simulated/floor), "actual linked weed fixture has a separate simulated floor")
	var/turf/space/space = locate(/turf/space) in world
	TEST_ASSERT(space, "actual map supplies an existing space turf without replacing test floors")
	var/obj/effect/alien/weeds/node/node = allocate(/obj/effect/alien/weeds/node, T)
	var/obj/effect/alien/weeds/weed = allocate(/obj/effect/alien/weeds, other_floor, node)
	TEST_ASSERT(!QDELETED(node) && !QDELETED(weed), "actual node and linked weeds initialize on valid floors")
	TEST_ASSERT_EQUAL(weed.linked_node(), node, "actual weed initialization links its original node")
	var/node_integrity = node.get_integrity()
	weed.forceMove(space)
	TEST_ASSERT(!QDELETED(weed), "actual movement into space preserves weeds until processing")
	TEST_ASSERT_EQUAL(weed.loc, space, "actual weed moves onto the existing space turf")
	weed.weed_spread()
	TEST_ASSERT(QDELETED(weed), "actual space processing consumes the original weed")
	TEST_ASSERT(!QDELETED(node), "actual weed cleanup preserves its original node")
	TEST_ASSERT_EQUAL(node.loc, T, "actual weed cleanup preserves its node floor")
	TEST_ASSERT_EQUAL(node.get_integrity(), node_integrity, "actual weed cleanup preserves exact original node integrity")
	var/obj/effect/alien/weeds/unlinked = allocate(/obj/effect/alien/weeds, other_floor)
	TEST_ASSERT_NULL(unlinked.linked_node(), "actual independent floor weed starts without a node")
	var/integrity_before = unlinked.get_integrity()
	unlinked.weed_spread()
	TEST_ASSERT(!QDELETED(unlinked), "actual simulated-floor processing preserves an unlinked weed")
	TEST_ASSERT_EQUAL(unlinked.loc, other_floor, "actual unlinked weed processing preserves its original floor")
	TEST_ASSERT_EQUAL(unlinked.get_integrity(), integrity_before, "actual unlinked weed processing preserves exact integrity")
