/// The production limb application API must release its original held tourniquet before cutting blood flow.
/datum/unit_test/interim_tourniquet_sticky_limb_insertion/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/organ/external/arm = user.get_organ(BP_L_ARM)
	var/obj/item/tourniquet/strap = allocate(/obj/item/tourniquet, T)
	TEST_ASSERT(arm && arm.owner == user, "actual human initializes its own original left arm")
	TEST_ASSERT_NULL(arm.tourniquet, "actual initialized limb starts without a tourniquet")
	TEST_ASSERT(!arm.flow_occluded(), "actual original limb starts with blood flow open")
	TEST_ASSERT(user.put_in_active_hand(strap), "actor holds exact original tourniquet")
	add_trait(strap, TRAIT_NODROP, "interim_tourniquet_release")
	TEST_ASSERT(user.release_refusal(strap, user), "actual inventory refuses sticky original strap")
	TEST_ASSERT_EQUAL(arm.apply_tourniquet(strap, user), FALSE, "production application refuses unreleasable original strap")
	TEST_ASSERT_NULL(arm.tourniquet, "refused application leaves actual limb slot empty")
	TEST_ASSERT(!arm.flow_occluded(), "refused application grants no blood-flow occlusion")
	TEST_ASSERT_EQUAL(user.get_active_hand(), strap, "refused application preserves exact original hand")
	TEST_ASSERT_EQUAL(strap.loc, user, "refused application preserves original inventory location")
	TEST_ASSERT_NULL(owner_of(strap), "refused application establishes no limb ownership")
	remove_trait(strap, TRAIT_NODROP, "interim_tourniquet_release")
	TEST_ASSERT(arm.apply_tourniquet(strap, user), "same original strap applies once release is permitted")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed application clears actual source hand")
	TEST_ASSERT_EQUAL(arm.tourniquet, strap, "allowed application records exact original strap")
	TEST_ASSERT_EQUAL(strap.loc, arm, "allowed application physically contains original strap in limb")
	TEST_ASSERT_EQUAL(owner_of(strap), arm, "allowed application preserves existing limb ownership policy")
	TEST_ASSERT(arm.flow_occluded(), "allowed application really cuts blood flow")
	TEST_ASSERT_EQUAL(arm.remove_tourniquet(user), strap, "production loosening returns exact original strap")
	TEST_ASSERT_NULL(arm.tourniquet, "actual loosening clears limb slot")
	TEST_ASSERT(!arm.flow_occluded(), "actual loosening restores original blood flow")
	TEST_ASSERT(!QDELETED(strap), "actual loosening preserves original strap alive")
	TEST_ASSERT_EQUAL(strap.loc, T, "actual loosening refunds original strap to floor")
	TEST_ASSERT_NULL(owner_of(strap), "actual loosening clears limb ownership stamp")
