/datum/unit_test/interim_strangerock_welder_cleanup/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/strangerock/rock = allocate(/obj/item/strangerock, T, ARCHAEO_BOWL)
	var/list/inside_items = contents_of(rock, /obj/item)
	for(var/obj/item/I as anything in inside_items)
		own(I)
	TEST_ASSERT_EQUAL(length(inside_items), 1, "The actual configured rock constructor produces exactly one real concealed find or sample")
	var/obj/item/product = inside_items[1]
	TEST_ASSERT(product && !QDELETED(product) && product.loc == rock, "The actual concealed original product is alive inside its original rock")
	var/obj/item/weldingtool/welder = allocate(/obj/item/weldingtool, T)
	TEST_ASSERT(actor.put_in_active_hand(welder), "The actual actor holds its original real welder")
	TEST_ASSERT(actor.put_in_inactive_hand(rock), "The actual rock occupies the actor's original other hand")
	TEST_ASSERT_EQUAL(rock.interaction_tool_act(actor, welder, TOOL_WELDER), ITEM_INTERACT_BLOCKING, "The actual unlit welder preserves its original refusal")
	TEST_ASSERT(!QDELETED(rock) && product.loc == rock, "The actual unlit control preserves the original source and concealed product")
	TEST_ASSERT(test_op_handler(welder, "interaction_self", actor, welder), "The actual welder self-use genuinely lights it")
	TEST_ASSERT(welder.isOn(), "The actual original welder is genuinely lit")
	var/fuel_before = welder.get_fuel()
	TEST_ASSERT(fuel_before >= 2, "The actual original welder has enough real fuel for recovery")
	add_trait(rock, TRAIT_NODROP, "interim_strangerock_welder_cleanup")
	TEST_ASSERT(rock.loc.release_refusal(rock, actor), "The actual sticky held rock genuinely refuses release")
	TEST_ASSERT_EQUAL(rock.interaction_tool_act(actor, welder, TOOL_WELDER), ITEM_INTERACT_BLOCKING, "Actual sticky recovery refuses before releasing its original product")
	TEST_ASSERT(!QDELETED(rock) && rock.loc == actor, "Actual sticky refusal preserves its exact original held source")
	TEST_ASSERT_EQUAL(actor.get_inactive_hand(), rock, "Actual sticky refusal preserves the exact original source hand slot")
	TEST_ASSERT(!QDELETED(product) && product.loc == rock, "Actual sticky refusal preserves exact original product containment")
	TEST_ASSERT_EQUAL(welder.get_fuel(), fuel_before, "Actual sticky refusal spends no original recovery fuel")
	remove_trait(rock, TRAIT_NODROP, "interim_strangerock_welder_cleanup")
	TEST_ASSERT(actor.drop_from_inventory(rock, T), "The actual unblocked rock returns to its original floor")
	TEST_ASSERT_EQUAL(rock.interaction_tool_act(actor, welder, TOOL_WELDER), ITEM_INTERACT_SUCCESS, "Actual floor recovery preserves its original success result")
	TEST_ASSERT(QDELETED(rock), "Actual floor recovery consumes the exact original strange rock")
	TEST_ASSERT(!QDELETED(product) && product.loc == T, "Actual recovery releases the exact original concealed product alive to the original floor")
	TEST_ASSERT(abs(welder.get_fuel() - (fuel_before - 2)) < 0.001, "Actual successful recovery spends exactly two original fuel units")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), welder, "Actual recovery preserves its original held welding tool")
	test_op_handler(welder, "interaction_self", actor, welder)
