/// The actual combat interaction crushes a floor snowman into exactly one snow sheet.
/datum/unit_test/interim_snowman_crush_lifecycle/Run()
	var/turf/T = run_loc_floor_bottom_left
	TEST_ASSERT(istype(T, /turf/simulated/floor), "the real snowman fixture occupies a simulated floor")
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/snowman/snowman = allocate(/obj/structure/snowman, T)
	user.set_combat_mode(FALSE)
	test_click(user, snowman, null)
	test_time(1 SECOND)
	TEST_ASSERT(!QDELETED(snowman), "resolving the refused interaction preserves the real snowman")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/snow)), 0, "peaceful resolution creates no snow product")
	user.set_combat_mode(TRUE)
	TEST_ASSERT(test_op_committed(test_click(user, snowman, null)), "a combat-mode touch crushes the snowman")
	test_time(1 SECOND)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(snowman), "actual combat crushing immediately consumes the original snowman")
	TEST_ASSERT_NULL(locate_within(T, /obj/structure/snowman), "actual crushing leaves no source snowman")
	TEST_ASSERT_EQUAL(length(contents_of(T, /obj/item/stack/material/snow)), 1, "actual crushing creates exactly one snow stack")
	var/obj/item/stack/material/snow/snow = locate_within(T, /obj/item/stack/material/snow)
	TEST_ASSERT_EQUAL(snow.get_amount(), 1, "actual crushing returns exactly one snow sheet")
	TEST_ASSERT_EQUAL(snow.loc, T, "actual crushing keeps the snow on the original floor")
	TEST_ASSERT_NULL(user.get_active_hand(), "crushing the floor snowman does not equip its returned snow")
