/// Real limb teardown consumes contained splints while preserving externally referenced splints.
/datum/unit_test/interim2_organ_splint_containment_teardown/Run()
	var/turf/T = test_floor()
	var/obj/item/organ/external/arm/arm = allocate(/obj/item/organ/external/arm, T)
	var/obj/item/organ/external/arm/control = allocate(/obj/item/organ/external/arm, T)
	var/obj/item/stack/medical/splint/contained = allocate(/obj/item/stack/medical/splint, arm)
	var/obj/item/stack/medical/splint/external = allocate(/obj/item/stack/medical/splint, T)
	var/original_external_amount = external.get_amount()
	TEST_ASSERT(original_external_amount > 0, "The real external splint constructor must supply usable material")
	TEST_ASSERT_EQUAL(contained.loc, arm, "The real contained splint must begin inside its original limb")
	TEST_ASSERT_EQUAL(external.loc, T, "The independent actual splint must begin on the floor")
	TEST_ASSERT_EQUAL(arm.apply_splint(contained), 1, "The actual public support API must accept the contained splint")
	TEST_ASSERT_EQUAL(control.apply_splint(external), 1, "The actual public support API must accept an externally located support")
	TEST_ASSERT_EQUAL(arm.splinted, contained, "The first real limb must reference its exact original contained support")
	TEST_ASSERT_EQUAL(control.splinted, external, "The independent limb must reference its exact external support")
	TEST_ASSERT_EQUAL(arm.apply_splint(external), 0, "An already supported real limb must refuse a second support")
	TEST_ASSERT_EQUAL(arm.splinted, contained, "The actual refusal must preserve the first original support")
	TEST_ASSERT(consume(arm), "Actual floor limb disposal must succeed")
	TEST_ASSERT(QDELETED(arm) && QDELETED(contained), "Actual teardown must dispose of the exact limb and its physically contained splint")
	TEST_ASSERT(!QDELETED(control) && !QDELETED(external), "Contained teardown must preserve the independent original limb and floor support")
	TEST_ASSERT_EQUAL(control.splinted, external, "Independent support relation must retain its exact original identity")
	TEST_ASSERT_EQUAL(external.loc, T, "Contained teardown must preserve external support location")
	TEST_ASSERT_EQUAL(external.get_amount(), original_external_amount, "Contained teardown must preserve exact independent support quantity")
	TEST_ASSERT(consume(control), "Actual externally supported floor limb disposal must succeed")
	TEST_ASSERT(QDELETED(control), "Actual disposal must destroy the externally supported limb")
	TEST_ASSERT(!QDELETED(external), "A relation to an external support must not destroy that original item")
	TEST_ASSERT_EQUAL(external.loc, T, "External support must stay on its original floor after linked limb teardown")
	TEST_ASSERT_EQUAL(external.get_amount(), original_external_amount, "External support must retain its exact original material quantity")
