/// Actual mutant parents pass the mutation flag to offspring; baby setup consumes that flag.
/datum/unit_test/interim_teppi_mutation_data/Run()
	var/mob/living/simple_mob/vore/alienanimals/teppi/mutant/mother = allocate(/mob/living/simple_mob/vore/alienanimals/teppi/mutant)
	var/mob/living/simple_mob/vore/alienanimals/teppi/father = allocate(/mob/living/simple_mob/vore/alienanimals/teppi)
	var/mob/living/simple_mob/vore/alienanimals/teppi/baby/child = allocate(/mob/living/simple_mob/vore/alienanimals/teppi/baby)
	TEST_ASSERT(!QDELETED(mother) && !QDELETED(father) && !QDELETED(child), "actual teppi initialize alive")
	TEST_ASSERT(mother.teppi_mutate, "actual adult mutant retains its inheritable mutation flag through parent setup")
	TEST_ASSERT(!father.teppi_mutate, "ordinary adult teppi starts without the mutant inheritance flag")
	TEST_ASSERT(!child.teppi_adult, "actual baby uses the juvenile mutation branch")
	mother.set_nutrition(1000)
	father.set_nutrition(1000)
	child.inherit_from_parents(mother, father)
	TEST_ASSERT(child.teppi_mutate, "actual parent inheritance passes the mutant flag to the baby")
	TEST_ASSERT(child.inherit_colors, "actual parent inheritance selects inherited colors before mutation")
	TEST_ASSERT_EQUAL(mother.nutrition, 500, "actual inheritance debits the mother's nutrition")
	TEST_ASSERT_EQUAL(father.nutrition, 750, "actual inheritance debits the father's nutrition")
	child.teppi_setup()
	TEST_ASSERT(!child.teppi_mutate, "actual juvenile setup consumes the pending mutation")
	TEST_ASSERT(mother.teppi_mutate, "juvenile setup preserves the adult's future offspring mutation flag")
