/datum/unit_test/interim_shock_kit_recovery/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/clothing/head/helmet/helmet = allocate(/obj/item/clothing/head/helmet, T)
	var/obj/item/radio/electropack/pack = allocate(/obj/item/radio/electropack, T)
	var/obj/item/tool/screwdriver/screwdriver = allocate(/obj/item/tool/screwdriver, T)
	var/obj/item/tool/wrench/wrench = allocate(/obj/item/tool/wrench, T)
	TEST_ASSERT(!pack.b_stat, "The actual original electropack starts closed to modification")
	TEST_ASSERT_EQUAL(test_op_handler(pack, "screwdriver_used", actor, screwdriver), OP_OK, "The actual screwdriver opens the original pack for assembly")
	TEST_ASSERT(pack.b_stat, "The actual opened pack permits real assembly")
	test_op_handler(pack, "interaction_item", actor, helmet)
	var/obj/item/assembly/shock_kit/kit = locate_within(actor, /obj/item/assembly/shock_kit)
	TEST_ASSERT_NOTNULL(kit, "Actual public pack assembly creates its original electrohelmet")
	own(kit)
	TEST_ASSERT_EQUAL(kit.part1, helmet, "The real assembly owns the exact original helmet")
	TEST_ASSERT_EQUAL(kit.part2, pack, "The real assembly owns the exact original pack")
	TEST_ASSERT_EQUAL(helmet.master, kit, "The original helmet links to the actual assembly")
	TEST_ASSERT_EQUAL(pack.master, kit, "The original pack links to the actual assembly")
	TEST_ASSERT_EQUAL(kit.loc, actor, "The actual newly assembled source is genuinely held before refusal")
	var/source_hand = actor.inventory_slot_id(kit)
	TEST_ASSERT(source_hand, "The actual assembled source occupies a real inventory slot")
	add_trait(kit, TRAIT_NODROP, "interim_shock_kit_recovery")
	TEST_ASSERT(kit.loc.release_refusal(kit, actor), "The actual sticky source genuinely refuses removal")
	TEST_ASSERT_EQUAL(kit.wrench_act(actor, wrench), ITEM_INTERACT_BLOCKING, "Actual disassembly refuses the sticky held source before releasing its parts")
	TEST_ASSERT(!QDELETED(kit) && kit.loc == actor, "Actual sticky refusal preserves the exact original held source")
	TEST_ASSERT_EQUAL(actor.get_equipped_item(source_hand), kit, "Actual sticky refusal preserves the original occupied slot")
	TEST_ASSERT_EQUAL(kit.part1, helmet, "Actual sticky refusal preserves exact original helmet ownership")
	TEST_ASSERT_EQUAL(kit.part2, pack, "Actual sticky refusal preserves exact original pack ownership")
	TEST_ASSERT_EQUAL(helmet.loc, kit, "Actual sticky refusal preserves original helmet containment")
	TEST_ASSERT_EQUAL(pack.loc, kit, "Actual sticky refusal preserves original pack containment")
	TEST_ASSERT_EQUAL(helmet.master, kit, "Actual sticky refusal preserves the original helmet link")
	TEST_ASSERT_EQUAL(pack.master, kit, "Actual sticky refusal preserves the original pack link")
	remove_trait(kit, TRAIT_NODROP, "interim_shock_kit_recovery")
	TEST_ASSERT(actor.drop_from_inventory(kit, T), "The actor places the real original assembly on its floor")
	TEST_ASSERT(actor.put_in_active_hand(wrench), "The actual actor holds its original recovery wrench")
	TEST_ASSERT_EQUAL(kit.screwdriver_act(actor, screwdriver), ITEM_INTERACT_SUCCESS, "The actual screwdriver secures the original assembly")
	TEST_ASSERT(kit.status, "The original assembly is genuinely secured")
	TEST_ASSERT_EQUAL(kit.wrench_act(actor, wrench), ITEM_INTERACT_BLOCKING, "A secured real assembly refuses wrench disassembly")
	TEST_ASSERT(!QDELETED(kit) && kit.loc == T, "The actual secured refusal preserves the original assembly")
	TEST_ASSERT_EQUAL(kit.part1, helmet, "The actual refusal preserves original helmet ownership")
	TEST_ASSERT_EQUAL(kit.part2, pack, "The actual refusal preserves original pack ownership")
	TEST_ASSERT_EQUAL(kit.screwdriver_act(actor, screwdriver), ITEM_INTERACT_SUCCESS, "The actual screwdriver releases the original assembly")
	TEST_ASSERT(!kit.status, "The actual original assembly becomes unsecured")
	TEST_ASSERT_EQUAL(kit.wrench_act(actor, wrench), ITEM_INTERACT_SUCCESS, "The actual wrench disassembles the original unsecured kit")
	TEST_ASSERT(QDELETED(kit), "Actual disassembly consumes the exact original assembly")
	TEST_ASSERT(!QDELETED(helmet) && helmet.loc == T, "Actual disassembly recovers the exact original helmet on the same floor")
	TEST_ASSERT(!QDELETED(pack) && pack.loc == T, "Actual disassembly recovers the exact original electropack on the same floor")
	TEST_ASSERT_NULL(helmet.master, "Actual disassembly clears the original helmet assembly link")
	TEST_ASSERT_NULL(pack.master, "Actual disassembly clears the original electropack assembly link")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), wrench, "Actual disassembly preserves the exact original held recovery wrench")
