/// Missing refinery equipment refuses at the actual constructor boundary; a real adjacent processor still connects and responds.
/datum/unit_test/interim_processing_console_constructor/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	TEST_ASSERT_NULL(locate_in_list(range(5, T), /obj/machinery/mineral/processing_unit), "The actual missing-machine fixture has no processor in the real constructor search radius")
	var/list/before = turf_contents_of_type(T, /obj/machinery/mineral/processing_unit_console)
	var/obj/machinery/mineral/processing_unit_console/refused = allocate(/obj/machinery/mineral/processing_unit_console, T)
	TEST_ASSERT(QDELETED(refused), "The real missing-machine constructor refuses its incomplete console")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(T, /obj/machinery/mineral/processing_unit_console)), length(before), "The actual refused constructor leaves no console on its original floor")
	var/turf/machine_floor = get_step(T, EAST)
	TEST_ASSERT(machine_floor && !machine_floor.density, "The real processor has an adjacent passable floor")
	var/obj/machinery/mineral/processing_unit/machine = allocate(/obj/machinery/mineral/processing_unit, machine_floor)
	var/obj/machinery/mineral/processing_unit_console/console = allocate(/obj/machinery/mineral/processing_unit_console, T)
	TEST_ASSERT(console && !QDELETED(console), "The real adjacent processor admits ordinary console construction")
	TEST_ASSERT(console.flags & ATOM_INITIALIZED, "The actual successful constructor preserves the complete initialized parent chain")
	TEST_ASSERT_EQUAL(console.machine(), machine, "The actual constructor links the exact adjacent processor")
	TEST_ASSERT_EQUAL(machine.console, console, "The actual constructor records the exact console on the original processor")
	TEST_ASSERT_EQUAL(console.loc, T, "The actual connected console stays on its original floor")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(T, /obj/machinery/mineral/processing_unit_console)), length(before) + 1, "Successful construction adds only the original connected console")
	TEST_ASSERT(!machine.active, "The actual initialized processor starts inactive")
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/datum/op_result/first_power = test_ui(actor, console, "power", list())
	test_drain()
	TEST_ASSERT_EQUAL(first_power?.outcome, ACT_COMMITTED, "The actual connected console handles its public power action")
	TEST_ASSERT(machine.active, "The actual console power action activates the original processor")
	var/datum/op_result/second_power = test_ui(actor, console, "power", list())
	test_drain()
	TEST_ASSERT_EQUAL(second_power?.outcome, ACT_COMMITTED, "The actual connected console handles the second public power action")
	TEST_ASSERT(!machine.active, "The second actual console action restores its original inactive processor state")
	TEST_ASSERT_EQUAL(console.machine(), machine, "Actual console actions preserve the original processor relationship")
	TEST_ASSERT_EQUAL(machine.console, console, "Actual console actions preserve the original reciprocal console relationship")
	test_driver_end()
