/// Actual hand and item clearing consume only the dead plant; the item path refreshes a real adjacent live plant's spreading state.
/datum/unit_test/interim_deadplant_hand_cleanup/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	var/obj/effect/dead_plant/dead = allocate(/obj/effect/dead_plant, T)
	TEST_ASSERT(dead && !QDELETED(dead) && dead.loc == T, "The actual dead plant starts alive on its original floor")
	TEST_ASSERT(actor.put_in_active_hand(pen), "The actual actor holds its original unrelated pen")
	TEST_ASSERT(test_op_handler(dead, "interaction_clear_dead_plant", actor, null), "The actual public hand clearing preserves its original handled result")
	TEST_ASSERT(QDELETED(dead), "The actual hand clearing consumes its exact original dead plant")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), pen, "Actual hand clearing preserves the exact unrelated original held pen")
	TEST_ASSERT(!QDELETED(actor) && actor.loc == T, "Actual hand clearing preserves the original actor and floor")

/datum/unit_test/interim_deadplant_item_neighbor_cleanup/Run()
	// test_floor() is the room's bottom-left floor; its western neighbor is the wall.
	var/turf/T = get_step(test_floor(), EAST)
	var/turf/neighbor_floor = get_step(T, EAST)
	var/turf/actor_floor = get_step(T, WEST)
	TEST_ASSERT(isfloorturf(T) && isfloorturf(neighbor_floor) && isfloorturf(actor_floor), "The actual neighbor fixture uses three real room floors")
	TEST_ASSERT(!T.density && !neighbor_floor.density && !actor_floor.density, "The real neighbor fixture has three passable floors")
	TEST_ASSERT(SSplants && SSplants.initialized, "The actual live-plant service is initialized")
	var/datum/seed/seed = SSplants.seeds[PLANT_GLOWSHROOM]
	TEST_ASSERT_NOTNULL(seed, "The real plant service contains its canonical registered glowshroom seed")
	seed.update_growth_stages()
	TEST_ASSERT(seed.growth_stages > 0 && seed.get_trait(TRAIT_ENDURANCE) > 0, "The canonical real seed resolves positive construction growth stages and endurance")
	var/obj/effect/plant/live = allocate(/obj/effect/plant, neighbor_floor, seed)
	TEST_ASSERT(live && !QDELETED(live), "The actual adjacent live plant completes its real seeded constructor")
	TEST_ASSERT_EQUAL(live.seed(), seed, "The actual live plant retains the exact original registered shared seed")
	TEST_ASSERT(!LAZYLEN(live.neighbors), "The actual new live plant has not yet computed its spreading neighbors")
	var/original_health = live.health
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, actor_floor)
	var/obj/item/pen/pen = allocate(/obj/item/pen, actor_floor)
	TEST_ASSERT(actor.put_in_active_hand(pen), "The actual adjacent actor holds the real clearing item")
	var/obj/effect/dead_plant/dead = allocate(/obj/effect/dead_plant, T)
	TEST_ASSERT_EQUAL(test_op_handler(dead, "interaction_clear_dead_plant_item", actor, pen), OP_PASS, "The actual public item clearing preserves the original parent-pass return")
	TEST_ASSERT(QDELETED(dead), "The actual item clearing consumes the exact original dead plant")
	TEST_ASSERT(!QDELETED(live) && live.loc == neighbor_floor, "Actual item clearing preserves the exact original adjacent live plant and floor")
	TEST_ASSERT(T in live.neighbors, "The actual neighboring plant refresh discovers the original cleared floor as a real spreading target")
	TEST_ASSERT(live in REGISTRY_MEMBERS(REGISTRY_GROWING_PLANTS), "The actual refreshed live neighbor is registered for resumed growth")
	TEST_ASSERT(live.growing, "The actual refreshed neighbor resumes growing")
	TEST_ASSERT_EQUAL(live.health, original_health, "Actual neighbor refreshing preserves the original live plant health")
	TEST_ASSERT_EQUAL(live.seed(), seed, "Actual neighbor refreshing preserves the exact original shared seed")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), pen, "Actual item clearing preserves the original held clearing item")
	TEST_ASSERT(!QDELETED(actor) && actor.loc == actor_floor, "Actual item clearing preserves the original actor outside the spreading target")
