/// Actual bolt-wire cutting drops bolts; mending repairs the conductor without raising bolts, and only a subsequent intact powered pulse raises them.
/datum/unit_test/om/interim_airlock_bolt_wire_recovery/run_om(list/made)
	var/turf/T = test_floor()
	var/obj/machinery/door/airlock/door = allocate(/obj/machinery/door/airlock, T)
	made += door
	door.set_stat(0)
	door.autoclose = FALSE
	var/datum/wires/airlock/wires = wires_of(door)
	TEST_ASSERT(istype(wires), "the actual airlock creates its real wires datum")
	TEST_ASSERT(door.arePowerSystemsOn() && door.density && !door.operating, "the actual airlock starts powered, closed and idle")
	TEST_ASSERT(!is_bolted(door) && !wires.is_cut(WIRE_DOOR_BOLTS), "the actual bolt mechanism starts raised with an intact conductor")
	var/timers_before = om_timer_count(door)
	wires.cut(WIRE_DOOR_BOLTS, null)
	TEST_ASSERT(wires.is_cut(WIRE_DOOR_BOLTS) && door.wire_cut(WIRE_DOOR_BOLTS), "the actual interactive wire API cuts the bolt conductor")
	TEST_ASSERT(is_bolted(door), "actual cutting drops the airlock bolts")
	TEST_ASSERT(!door.unlock(), "actual ordinary bolt raising refuses the cut conductor despite available power")
	wires.pulse(WIRE_DOOR_BOLTS, null)
	TEST_ASSERT(is_bolted(door), "the actual wire API refuses to pulse a cut bolt conductor")
	TEST_ASSERT(!door.open(TRUE), "actual forced opening cannot bypass the dropped bolts")
	TEST_ASSERT(door.density && !door.operating, "actual cut-wire refusals leave the passage closed and idle")
	TEST_ASSERT_EQUAL(om_timer_count(door), timers_before, "actual cut-wire refusals schedule no motion")
	wires.cut(WIRE_DOOR_BOLTS, null)
	TEST_ASSERT(!wires.is_cut(WIRE_DOOR_BOLTS) && !door.wire_cut(WIRE_DOOR_BOLTS), "the actual interactive wire API mends the bolt conductor")
	TEST_ASSERT(is_bolted(door), "actual mending leaves the previously dropped bolts in place")
	TEST_ASSERT(!door.open(TRUE), "actual forced opening still refuses the bolts after conductor repair")
	TEST_ASSERT(door.density && !door.operating, "actual mending alone leaves the passage closed and idle")
	wires.pulse(WIRE_DOOR_BOLTS, null)
	TEST_ASSERT(!is_bolted(door), "actual intact powered pulse raises the repaired bolt mechanism")
	TEST_ASSERT(!door.wire_cut(WIRE_DOOR_BOLTS) && door.arePowerSystemsOn(), "actual bolt recovery preserves the repaired conductor and available power")
	door.open()
	TEST_ASSERT(door.density && door.operating, "actual ordinary opening begins only after the bolt recovery")
	scheduler_advance((2 SECONDS) / (1 SECOND))
	TEST_ASSERT(!door.density && !door.opacity && !door.operating, "actual opening timers finish with a passable idle airlock after bolt recovery")
