/// Installing an actual filled beaker uses checked ownership transfer and preserves both its contents and unrelated active item.
/datum/unit_test/interim_chem_grenade_beaker_insert/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/grenade/chem_grenade/grenade = allocate(/obj/item/grenade/chem_grenade, T)
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	beaker.reagents.add_reagent(REAGENT_ID_WATER, 10)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_active_hand(pen), "the unrelated pen occupies the active hand")
	TEST_ASSERT(user.put_in_inactive_hand(beaker), "the actual filled beaker occupies the inactive hand")
	test_op_handler(grenade, "interaction_item", user, beaker)
	TEST_ASSERT_EQUAL(beaker.loc, grenade, "the actual beaker is physically inside the grenade")
	TEST_ASSERT_EQUAL(owner_of(beaker), grenade, "the grenade owns the actual installed beaker")
	TEST_ASSERT_EQUAL(length(grenade.beakers), 1, "assembly records exactly one installed container")
	TEST_ASSERT_EQUAL(grenade.beakers[1], beaker, "assembly records the actual supplied beaker")
	TEST_ASSERT_EQUAL(grenade.stage, 1, "successful insertion advances the real assembly stage")
	TEST_ASSERT_EQUAL(beaker.reagents.get_reagent_amount(REAGENT_ID_WATER), 10, "insertion preserves the actual reagent amount")
	TEST_ASSERT_NULL(user.get_inactive_hand(), "insertion correctly vacates the ingredient hand")
	TEST_ASSERT_EQUAL(user.get_active_hand(), pen, "insertion preserves the unrelated active item")

/// A sticky filled beaker cannot alter grenade assembly or be forcibly transferred from its hand.
/datum/unit_test/interim_chem_grenade_beaker_sticky_refusal/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/grenade/chem_grenade/grenade = allocate(/obj/item/grenade/chem_grenade, T)
	var/initial_name = grenade.name
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	beaker.reagents.add_reagent(REAGENT_ID_WATER, 10)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_active_hand(pen), "the unrelated pen occupies the active hand")
	TEST_ASSERT(user.put_in_inactive_hand(beaker), "the actual filled beaker occupies the inactive hand")
	add_trait(beaker, TRAIT_NODROP, "interim_chem_grenade_beaker")
	TEST_ASSERT(beaker.loc.release_refusal(beaker, user), "the actual sticky beaker refuses release")
	TEST_ASSERT(grenade.container_refusal(user, beaker), "the assembly refuses the actual sticky beaker")
	test_op_handler(grenade, "interaction_item", user, beaker)
	TEST_ASSERT_EQUAL(length(grenade.beakers), 0, "refusal leaves the actual container list empty")
	TEST_ASSERT_EQUAL(grenade.stage, 0, "refusal preserves the original assembly stage")
	TEST_ASSERT_EQUAL(grenade.path, 0, "refusal preserves the original construction path")
	TEST_ASSERT_EQUAL(grenade.name, initial_name, "refusal preserves the grenade's name")
	TEST_ASSERT_EQUAL(beaker.loc, user, "refusal preserves the actual beaker on its holder")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), beaker, "refusal preserves the ingredient hand")
	TEST_ASSERT_EQUAL(user.get_active_hand(), pen, "refusal preserves the unrelated active item")
	TEST_ASSERT_EQUAL(beaker.reagents.get_reagent_amount(REAGENT_ID_WATER), 10, "refusal preserves the actual reagent amount")
	remove_trait(beaker, TRAIT_NODROP, "interim_chem_grenade_beaker")
