/// Actual coin bagging respects release and its public removal action returns the same coin without duplicating its count.
/datum/unit_test/interim_moneybag_sticky_coin/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/moneybag/bag = allocate(/obj/item/moneybag, T)
	var/obj/item/coin/gold/coin = allocate(/obj/item/coin/gold, T)
	var/list/counts = bag.count_coins()
	TEST_ASSERT_EQUAL(contents_count(bag), 0, "the actual ordinary money bag starts empty")
	TEST_ASSERT_EQUAL(counts[MAT_GOLD], 0, "the actual gold-coin count begins at zero")
	TEST_ASSERT(user.put_in_active_hand(coin), "the actor holds the original real gold coin")
	add_trait(coin, TRAIT_NODROP, "interim_moneybag_sticky")
	TEST_ASSERT(user.release_refusal(coin, user), "the actual inventory refuses release of the sticky coin")
	test_op_handler(bag, "interaction_item", user, coin)
	TEST_ASSERT_EQUAL(user.get_active_hand(), coin, "refused insertion preserves the exact original hand")
	TEST_ASSERT_EQUAL(coin.loc, user, "refused insertion preserves actual inventory containment")
	TEST_ASSERT_EQUAL(contents_count(bag), 0, "refused insertion adds no coin to actual contents")
	counts = bag.count_coins()
	TEST_ASSERT_EQUAL(counts[MAT_GOLD], 0, "refused insertion grants no counted gold coin")
	remove_trait(coin, TRAIT_NODROP, "interim_moneybag_sticky")
	test_op_handler(bag, "interaction_item", user, coin)
	TEST_ASSERT_EQUAL(coin.loc, bag, "allowed insertion contains the same original coin")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears its actual source hand")
	TEST_ASSERT_EQUAL(contents_count(bag), 1, "allowed insertion contains exactly one actual item")
	counts = bag.count_coins()
	TEST_ASSERT_EQUAL(counts[MAT_GOLD], 1, "allowed insertion counts exactly one original gold coin")
	TEST_ASSERT_NULL(owner_of(coin), "the bag preserves its existing unowned contents policy")
	TEST_ASSERT(user.stat == CONSCIOUS && !user.restrained() && user.Adjacent(bag), "the actual actor satisfies the public coin-removal gate")
	op_ui_act(user, bag, "remove", list("coin" = MAT_GOLD))
	TEST_ASSERT_EQUAL(coin.loc, T, "actual removal returns the exact original coin to the bag's floor")
	TEST_ASSERT_EQUAL(contents_count(bag), 0, "actual removal empties the physical bag contents")
	counts = bag.count_coins()
	TEST_ASSERT_EQUAL(counts[MAT_GOLD], 0, "actual removal clears the counted original gold coin")
	qdel(bag)
	TEST_ASSERT(!QDELETED(coin), "the returned original coin survives empty-bag teardown")
