/// A shade that cannot leave the hand is not installed (the allowed install and the screwdriver removal are dq_p2_lights/screwdriver_takes_the_shade_off_and_a_shade_goes_back_on).
/datum/unit_test/interim_floor_lamp_sticky_shade/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/light/flamp/noshade/lamp = allocate(/obj/machinery/light/flamp/noshade, T)
	var/obj/item/lampshade/shade = allocate(/obj/item/lampshade, T)
	TEST_ASSERT_EQUAL(lamp.lamp_shade, 0, "actual bare lamp initialization accepts shade installation")
	TEST_ASSERT(user.put_in_active_hand(shade), "the actor holds the exact original shade")
	add_trait(shade, TRAIT_NODROP, "interim_floor_lamp_shade")
	TEST_ASSERT(user.release_refusal(shade, user), "actual inventory refuses sticky shade consumption")
	test_click(user, lamp, shade)
	test_time(10 SECONDS)
	TEST_ASSERT_EQUAL(lamp.lamp_shade, 0, "refused consumption grants no installed shade")
	TEST_ASSERT(!QDELETED(shade), "refused installation preserves original shade")
	TEST_ASSERT_EQUAL(user.get_active_hand(), shade, "refused installation preserves exact original hand")
	TEST_ASSERT_EQUAL(shade.loc, user, "refused installation preserves inventory containment")
	remove_trait(shade, TRAIT_NODROP, "interim_floor_lamp_shade")
	test_driver_end()
