/// Magic ammunition uses the actual shooter for anti-magic, preserving charge on refusal.
/datum/unit_test/interim_magic_staff_actor/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/protected = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/other = allocate(/mob/living/carbon/human, T)
	var/obj/item/gun/magic/firestaff/staff = allocate(/obj/item/gun/magic/firestaff, T)
	var/obj/item/nullrod/rod = allocate(/obj/item/nullrod, T)
	TEST_ASSERT(protected.put_in_active_hand(staff), "the actual shooter holds the real staff")
	TEST_ASSERT(protected.put_in_inactive_hand(rod), "the shooter physically carries an actual null rod")
	TEST_ASSERT_EQUAL(staff.charges, staff.max_charges, "the real staff initializes charged")
	var/before = staff.charges
	TEST_ASSERT_NULL(staff.consume_next_projectile(protected), "the shooter's actual null rod prevents magic ammunition")
	TEST_ASSERT_EQUAL(staff.charges, before, "anti-magic refusal preserves every charge")
	TEST_ASSERT(protected.drop_from_inventory(staff), "the protected shooter releases the actual staff")
	TEST_ASSERT(other.put_in_active_hand(staff), "the other shooter physically receives the staff")
	var/obj/item/projectile/energy/fireball/projectile = staff.consume_next_projectile(other)
	own(projectile)
	TEST_ASSERT(istype(projectile), "the unprotected actor produces a real fireball projectile")
	TEST_ASSERT_EQUAL(projectile.loc, staff, "the actual projectile starts inside the staff")
	TEST_ASSERT_EQUAL(staff.charges, before - 1, "one real projectile spends exactly one charge")
	TEST_ASSERT_EQUAL(protected.get_inactive_hand(), rod, "the original actor still carries its null rod")
	projectile = staff.consume_next_projectile()
	own(projectile)
	TEST_ASSERT(istype(projectile), "an explicitly actorless consumer retains ambient magic ammunition behavior")
	TEST_ASSERT_EQUAL(staff.charges, before - 2, "actorless ammunition spends exactly one further charge")
