/// The native load/unload inputs preserve the exact mixed vial and its complete mixture.
/datum/unit_test/om/interim_hypospray_vial_transfer
	parent_type = /datum/unit_test/dq_p2_reagents

/datum/unit_test/om/interim_hypospray_vial_transfer/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = rc_actor(T)
	var/obj/item/reagent_containers/hypospray/vial/hypo = allocate(/obj/item/reagent_containers/hypospray/vial, T)
	var/obj/item/reagent_containers/glass/beaker/vial/candidate = allocate(/obj/item/reagent_containers/glass/beaker/vial, T)
	var/obj/item/reagent_containers/glass/beaker/vial/original = hypo.loaded_vial
	TEST_ASSERT_NOTNULL(original, "the actual cartridge hypospray starts with its empty original vial")
	own(original)
	TEST_ASSERT_EQUAL(owner_of(original), hypo, "the actual cartridge owns its original vial")
	TEST_ASSERT_EQUAL(hypo.reagents.total_volume, 0, "the actual hypospray initially contains no liquid")
	TEST_ASSERT_EQUAL(candidate.reagents.maximum_volume, 30, "the real candidate vial holds thirty units")
	candidate.reagents.add_reagent(REAGENT_ID_WATER, 24)
	candidate.reagents.add_reagent(REAGENT_ID_ETHANOL, 6)
	TEST_ASSERT(user.put_in_inactive_hand(hypo), "the actual actor holds the hypospray in the removal hand")
	rc_click(user, hypo, candidate, I_HELP, FALSE)
	test_time(4 SECONDS)
	TEST_ASSERT_EQUAL(hypo.loaded_vial, original, "occupied-bay refusal preserves the exact original vial beyond the loading deadline")
	TEST_ASSERT_EQUAL(owner_of(original), hypo, "occupied-bay refusal preserves original vial ownership")
	TEST_ASSERT_EQUAL(candidate.reagents.get_reagent_amount(REAGENT_ID_WATER), 24, "occupied-bay refusal preserves all twenty-four water units")
	TEST_ASSERT_EQUAL(candidate.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 6, "occupied-bay refusal preserves all six ethanol units")
	TEST_ASSERT_EQUAL(user.get_active_hand(), candidate, "occupied-bay refusal preserves the held candidate")
	rc_click(user, hypo, null, I_HELP, FALSE)
	TEST_ASSERT_NULL(hypo.loaded_vial, "actual empty-hand unload empties the ownership view")
	TEST_ASSERT_NULL(owner_of(original), "actual original-vial unload releases ownership")
	TEST_ASSERT_EQUAL(user.get_active_hand(), original, "the actual empty-hand gesture returns the exact original vial to that hand")
	TEST_ASSERT_EQUAL(original.loc, user, "actual original-vial unload preserves physical hand containment")
	TEST_ASSERT_EQUAL(hypo.reagents.maximum_volume, 0, "actual original-vial unload disables the hypospray reservoir")
	user.drop_item()
	TEST_ASSERT_EQUAL(original.loc, T, "actual public dropping parks the original empty vial on the floor")
	rc_click(user, hypo, candidate, I_HELP, FALSE)
	TEST_ASSERT_NULL(hypo.loaded_vial, "starting actual native loading does not adopt early")
	TEST_ASSERT_EQUAL(candidate.reagents.total_volume, 30, "starting actual native loading transfers no liquid early")
	TEST_ASSERT_EQUAL(hypo.reagents.total_volume, 0, "the pending actual hypospray remains empty")
	test_time(2 SECONDS)
	TEST_ASSERT_NULL(hypo.loaded_vial, "the exact candidate is not adopted before the three-second loading deadline")
	TEST_ASSERT_EQUAL(user.get_active_hand(), candidate, "the real predeadline task preserves the exact held candidate")
	TEST_ASSERT_EQUAL(candidate.reagents.total_volume, 30, "the real predeadline task preserves the complete original mixture")
	test_time(2 SECONDS)
	TEST_ASSERT_EQUAL(hypo.loaded_vial, candidate, "actual completed native loading adopts the exact candidate vial")
	TEST_ASSERT_EQUAL(owner_of(candidate), hypo, "actual completed loading owns the exact candidate")
	TEST_ASSERT_EQUAL(candidate.loc, hypo, "actual completed loading contains the candidate physically")
	TEST_ASSERT_NULL(user.get_active_hand(), "actual completed loading clears the candidate's former hand")
	TEST_ASSERT(!candidate.is_open_container(), "actual completed loading closes the candidate vial")
	TEST_ASSERT_EQUAL(candidate.reagents.total_volume, 0, "actual completed loading transfers the whole vial mixture out")
	TEST_ASSERT_EQUAL(hypo.reagents.maximum_volume, 30, "actual completed loading restores the thirty-unit reservoir")
	TEST_ASSERT_EQUAL(hypo.reagents.get_reagent_amount(REAGENT_ID_WATER), 24, "actual completed loading transfers exactly twenty-four water units")
	TEST_ASSERT_EQUAL(hypo.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 6, "actual completed loading transfers exactly six ethanol units")
	rc_click(user, hypo, null, I_HELP, FALSE)
	TEST_ASSERT_NULL(hypo.loaded_vial, "actual public native unload clears the candidate ownership view")
	TEST_ASSERT_NULL(owner_of(candidate), "actual public native unload releases the exact candidate's ownership")
	TEST_ASSERT_EQUAL(user.get_active_hand(), candidate, "actual native unload returns the same vial to the free hand")
	TEST_ASSERT_EQUAL(candidate.reagents.get_reagent_amount(REAGENT_ID_WATER), 24, "actual unload returns exactly twenty-four water units")
	TEST_ASSERT_EQUAL(candidate.reagents.get_reagent_amount(REAGENT_ID_ETHANOL), 6, "actual unload returns exactly six ethanol units")
	TEST_ASSERT_EQUAL(hypo.reagents.total_volume, 0, "actual unload leaves no transferred liquid in the hypospray")
	TEST_ASSERT_EQUAL(hypo.reagents.maximum_volume, 0, "actual unload again disables the uncartridged reservoir")
	TEST_ASSERT(!QDELETED(candidate), "the exact original mixed candidate survives the ownership roundtrip")
	TEST_ASSERT(!QDELETED(original), "the original empty vial survives the ownership roundtrip")
	TEST_ASSERT_EQUAL(original.loc, T, "the exact original empty vial remains on its parked floor")
