/// Unpacking a real pistol kit creates exactly its gun and two magazines at the original delivery turf.
/datum/unit_test/interim_gunbox_unpack/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/item/gunbox/box = allocate(/obj/item/gunbox, T)
	box.w_class = ITEMSIZE_SMALL
	TEST_ASSERT(user.put_in_active_hand(box), "the actual gun box is carried")
	hci_click(user, box, box)
	test_time(10 SECONDS)
	hci_answer(user, "M1911 (.45)")
	test_time(10 SECONDS)
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(box), "unpacking consumes the original box")
	TEST_ASSERT_NULL(user.get_active_hand(), "unpacking correctly vacates the box's hand")
	var/guns = length(contents_of(T, /obj/item/gun/projectile/colt/detective))
	var/magazines = length(contents_of(T, /obj/item/ammo_magazine/m45/rubber))
	TEST_ASSERT_EQUAL(guns, 1, "unpacking creates exactly one actual selected pistol")
	TEST_ASSERT_EQUAL(magazines, 2, "unpacking creates exactly two actual selected magazines")
	test_driver_end()

/// A real carried box's release refusal prevents every kit product from being created.
/datum/unit_test/interim_gunbox_unpack_refusal/Run()
	test_driver_begin()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/item/gunbox/box = allocate(/obj/item/gunbox, T)
	box.w_class = ITEMSIZE_SMALL
	TEST_ASSERT(user.put_in_active_hand(box), "the actual box is carried")
	var/datum/dq_containment_listener/refusal = allocate(/datum/dq_containment_listener)
	refusal.watch(user)
	refusal.block_remove = TRUE
	TEST_ASSERT(box.loc.release_refusal(box, user), "the real box refuses release")
	hci_click(user, box, box)
	test_time(10 SECONDS)
	hci_answer(user, "M1911 (.45)")
	test_time(10 SECONDS)
	own_turf_contents(T)
	TEST_ASSERT(!QDELETED(box), "refusal preserves the actual box")
	TEST_ASSERT_EQUAL(user.get_active_hand(), box, "refusal preserves the original inventory slot")
	TEST_ASSERT_NULL(locate_within(T, /obj/item/gun/projectile/colt/detective), "refusal creates no selected gun")
	TEST_ASSERT_NULL(locate_within(T, /obj/item/ammo_magazine/m45/rubber), "refusal creates no selected magazines")
	test_driver_end()
