/// A real windoor's declared emag opens through its actual delayed animation and leaves the mechanism disabled, while unpowered/open refusals spend no card uses.
/datum/unit_test/om/interim_windoor_emag_disabled_open
	parent_type = /datum/unit_test/dq_p2_reagents

/datum/unit_test/om/interim_windoor_emag_disabled_open/run_gate()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = rc_actor(T)
	var/obj/machinery/door/window/door = allocate(/obj/machinery/door/window, T)
	var/obj/item/card/emag/card = allocate(/obj/item/card/emag, T)
	card.uses = 3
	TEST_ASSERT(user.put_in_active_hand(card), "the actual windoor actor holds a real charged emag")
	TEST_ASSERT_NOTNULL(SSticker, "the actual windoor animation has the real round service required by open")
	dq_machine_clear(door)
	door.set_grid_power(FALSE)
	var/timers_before = time_scheduler().timer_count(door)
	rc_click(user, door, card, I_HELP, FALSE)
	TEST_ASSERT_EQUAL(card.uses, 3, "the actual unpowered windoor refuses without spending a card use")
	TEST_ASSERT(door.density && !door.operating, "actual unpowered refusal preserves the closed idle windoor")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), timers_before, "actual unpowered refusal schedules no animation")
	dq_machine_clear(door)
	rc_click(user, door, card, I_HELP, FALSE)
	TEST_ASSERT_EQUAL(card.uses, 2, "actual accepted windoor emag spends exactly one card use")
	TEST_ASSERT_EQUAL(door.operating, 0, "actual accepted native emag waits before disabling its mechanism")
	TEST_ASSERT(door.density, "the actual accepted windoor remains closed before its animation delay")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), timers_before + 1, "actual accepted windoor schedules one delayed opening")
	test_time(0.6 SECONDS)
	TEST_ASSERT_EQUAL(door.operating, -1, "actual delayed emag disables the mechanism before its swing completes")
	TEST_ASSERT(after_pending(door, "swing"), "the actual disabled windoor has its world-clock opening animation pending")
	TEST_ASSERT(door.density, "the actual windoor stays closed until its opening animation finishes")
	test_time(1 SECOND)
	TEST_ASSERT(!after_pending(door, "swing"), "the actual opening animation timer drains")
	TEST_ASSERT(!door.density, "the actual delayed windoor animation opens the passage")
	TEST_ASSERT_EQUAL(door.operating, -1, "the actual opening animation preserves the disabled mechanism")
	TEST_ASSERT_EQUAL(door.explosion_resistance, 0, "the actual opened windoor removes its closed explosion barrier")
	TEST_ASSERT(!door.close(), "the actual disabled windoor cannot close through its public mechanism")
	TEST_ASSERT(!door.density, "actual refused closing preserves the open passage")
	var/open_timers = time_scheduler().timer_count(door)
	rc_click(user, door, card, I_HELP, FALSE)
	TEST_ASSERT_EQUAL(card.uses, 2, "actual repeated emag on the open windoor spends no additional card use")
	TEST_ASSERT_EQUAL(time_scheduler().timer_count(door), open_timers, "actual repeated emag on the open windoor schedules no animation")
	TEST_ASSERT_EQUAL(user.get_active_hand(), card, "the actual complete interaction preserves the actor's remaining charged card")
