/// An actual unsecured holder cannot refund its owned parts while its original inventory release is refused.
/datum/unit_test/interim_assembly_holder_sticky_disassembly/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/assembly_holder/holder = allocate(/obj/item/assembly_holder, T)
	var/obj/item/assembly/timer/left = allocate(/obj/item/assembly/timer, T)
	var/obj/item/assembly/timer/right = allocate(/obj/item/assembly/timer, T)
	TEST_ASSERT(!left.secured && !right.secured, "actual timer ingredients start unsecured for construction")
	TEST_ASSERT(holder.attach(left, right, user), "actual attachment constructs holder from both original timer ingredients")
	TEST_ASSERT_EQUAL(user.get_active_hand(), holder, "actual construction puts original assembly in active hand")
	TEST_ASSERT_EQUAL(holder.a_left, left, "actual construction retains exact left ingredient")
	TEST_ASSERT_EQUAL(holder.a_right, right, "actual construction retains exact right ingredient")
	TEST_ASSERT_EQUAL(owner_of(left), holder, "actual original left part is owned by holder")
	TEST_ASSERT_EQUAL(owner_of(right), holder, "actual original right part is owned by holder")
	add_trait(holder, TRAIT_NODROP, "interim_holder_disassembly")
	TEST_ASSERT(user.release_refusal(holder, user), "actual inventory refuses sticky original assembly")
	test_op_handler(holder, "interaction_self", user, holder)
	TEST_ASSERT(!QDELETED(holder), "refused disassembly preserves original holder alive")
	TEST_ASSERT_EQUAL(user.get_active_hand(), holder, "refused disassembly preserves exact original hand")
	TEST_ASSERT_EQUAL(holder.a_left, left, "refused disassembly preserves exact left slot")
	TEST_ASSERT_EQUAL(holder.a_right, right, "refused disassembly preserves exact right slot")
	TEST_ASSERT_EQUAL(left.loc, holder, "refused disassembly preserves original left containment")
	TEST_ASSERT_EQUAL(right.loc, holder, "refused disassembly preserves original right containment")
	TEST_ASSERT_EQUAL(owner_of(left), holder, "refused disassembly preserves original left owner")
	TEST_ASSERT_EQUAL(owner_of(right), holder, "refused disassembly preserves original right owner")
	remove_trait(holder, TRAIT_NODROP, "interim_holder_disassembly")
	test_op_handler(holder, "interaction_self", user, holder)
	TEST_ASSERT(QDELETED(holder), "allowed disassembly consumes exact original holder")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed disassembly clears original source hand")
	TEST_ASSERT(!QDELETED(left) && !QDELETED(right), "allowed disassembly preserves both original ingredients alive")
	TEST_ASSERT_EQUAL(left.loc, T, "allowed disassembly refunds exact original left part to floor")
	TEST_ASSERT_EQUAL(right.loc, T, "allowed disassembly refunds exact original right part to floor")
	TEST_ASSERT_NULL(owner_of(left), "allowed disassembly releases left ownership stamp")
	TEST_ASSERT_NULL(owner_of(right), "allowed disassembly releases right ownership stamp")
	TEST_ASSERT_NULL(left.holder(), "allowed disassembly clears original left holder relation")
	TEST_ASSERT_NULL(right.holder(), "allowed disassembly clears original right holder relation")
