/// A real safe refuses stuck originals without charging capacity and refunds the exact capacity on actual retrieval.
/datum/unit_test/interim_safe_sticky_insertion_capacity_refund/Run()
	var/turf/T = run_loc_floor_bottom_left
	// The safe collects loose turf items after init (take_loose_items()), so establish it before creating the originals.
	var/obj/structure/safe/safe = allocate(/obj/structure/safe, T)
	safe.take_loose_items()
	TEST_ASSERT_EQUAL(contents_count(safe), 0, "the actual initialized fixture safe starts without collected items")
	TEST_ASSERT_EQUAL(safe.space, 0, "the actual empty safe begins with zero occupied capacity")
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/pen/item = allocate(/obj/item/pen, T)
	var/obj/item/pen/blocker = allocate(/obj/item/pen, T)
	var/obj/item/pen/other_blocker = allocate(/obj/item/pen, T)
	safe.open = TRUE
	TEST_ASSERT(item.w_class > 0 && item.w_class <= safe.maxspace, "the original real item occupies positive capacity and fits the safe")
	TEST_ASSERT(user.put_in_active_hand(item), "the actor holds the original item to store")
	add_trait(item, TRAIT_NODROP, "interim_safe_sticky")
	TEST_ASSERT(user.release_refusal(item, user), "the actual inventory refuses the sticky item's release")
	test_op_handler(safe, "interaction_item", user, item)
	TEST_ASSERT_EQUAL(user.get_active_hand(), item, "refused insertion preserves the exact original hand")
	TEST_ASSERT_EQUAL(item.loc, user, "refused insertion preserves actual inventory containment")
	TEST_ASSERT_EQUAL(safe.space, 0, "refused insertion charges no occupied capacity")
	TEST_ASSERT_EQUAL(contents_count(safe), 0, "refused insertion contains no item")
	remove_trait(item, TRAIT_NODROP, "interim_safe_sticky")
	test_op_handler(safe, "interaction_item", user, item)
	TEST_ASSERT_EQUAL(item.loc, safe, "allowed insertion contains the original actual item")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears the source hand")
	TEST_ASSERT_EQUAL(safe.space, item.w_class, "allowed insertion charges exactly the real item's size")
	TEST_ASSERT(user.put_in_active_hand(blocker), "the actor fills the active hand before retrieval")
	TEST_ASSERT(user.put_in_inactive_hand(other_blocker), "the actor fills the other hand before retrieval")
	op_ui_act(user, safe, "retrieve", list("ref" = REF(item)))
	TEST_ASSERT_EQUAL(item.loc, T, "actual full-hands retrieval drops the same original onto the floor")
	TEST_ASSERT_EQUAL(safe.space, 0, "actual full-hands floor retrieval refunds its occupied capacity")
	TEST_ASSERT_EQUAL(contents_count(safe), 0, "actual full-hands floor retrieval empties the safe")
	TEST_ASSERT_EQUAL(user.get_active_hand(), blocker, "floor retrieval preserves the original active-hand blocker")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), other_blocker, "floor retrieval preserves the original other-hand blocker")
	TEST_ASSERT(user.unEquip(blocker), "the actor actually clears one hand for retrieval")
	TEST_ASSERT(user.put_in_active_hand(item), "the actor picks up the same original floor refund")
	test_op_handler(safe, "interaction_item", user, item)
	TEST_ASSERT_EQUAL(item.loc, safe, "a real second insertion restores the same original to the safe")
	TEST_ASSERT_EQUAL(safe.space, item.w_class, "a real second insertion charges its actual capacity once")
	op_ui_act(user, safe, "retrieve", list("ref" = REF(item)))
	TEST_ASSERT_EQUAL(user.get_active_hand(), item, "actual successful retrieval returns the same original item")
	TEST_ASSERT_EQUAL(item.loc, user, "actual retrieval restores inventory containment")
	TEST_ASSERT_EQUAL(contents_count(safe), 0, "actual retrieval empties the safe")
	TEST_ASSERT_EQUAL(safe.space, 0, "actual successful retrieval refunds exactly the original occupied capacity")
	qdel(safe)
	TEST_ASSERT(!QDELETED(item), "the returned original survives empty-safe teardown")
