/// Actual beaker lid interactions gate the public help-pour path without discarding liquid or unrelated flags.
/datum/unit_test/interim_beaker_lid_transfer/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/reagent_containers/glass/beaker/source = allocate(/obj/item/reagent_containers/glass/beaker, T)
	var/obj/item/reagent_containers/glass/beaker/target = allocate(/obj/item/reagent_containers/glass/beaker, T)
	source.reagents.add_reagent(REAGENT_ID_WATER, 20)
	source.amount_per_transfer_from_this = 7
	TEST_ASSERT(source.is_open_container() && target.is_open_container(), "the actual beakers begin open")
	TEST_ASSERT(source.flags & NOCONDUCT, "the actual source begins with its nonconductive flag")
	TEST_ASSERT(source.glass_self(user, null, null), "the actual lid interaction closes the source")
	TEST_ASSERT(!source.is_open_container(), "the actual source lid is closed")
	TEST_ASSERT(source.flags & NOCONDUCT, "closing the lid preserves the unrelated nonconductive flag")
	source.afterattack(target, user, TRUE, null, I_HELP)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 20, "a closed-source help pour preserves the actual source liquid")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 0, "a closed-source help pour delivers no liquid")
	TEST_ASSERT(source.glass_self(user, null, null), "the actual lid interaction reopens the source")
	TEST_ASSERT(source.is_open_container(), "the actual source is open again")
	TEST_ASSERT(target.glass_self(user, null, null), "the actual lid interaction closes the target")
	TEST_ASSERT(!target.is_open_container(), "the actual target lid is closed")
	source.afterattack(target, user, TRUE, null, I_HELP)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 20, "a closed-target help pour preserves the actual source liquid")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 0, "a closed-target help pour delivers no liquid")
	TEST_ASSERT(target.glass_self(user, null, null), "the actual target lid reopens")
	TEST_ASSERT(target.is_open_container(), "the actual target is open again")
	source.afterattack(target, user, FALSE, null, I_HELP)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 20, "a distant help pour preserves actual source liquid")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 0, "a distant help pour delivers no liquid")
	source.afterattack(target, user, TRUE, null, I_HELP)
	TEST_ASSERT_EQUAL(source.reagents.total_volume, 13, "the actual nearby open-container help pour spends the configured seven-unit dose")
	TEST_ASSERT_EQUAL(target.reagents.total_volume, 7, "the actual target receives the configured seven-unit dose")
	TEST_ASSERT(source.flags & NOCONDUCT, "the source's lid round trip preserves its unrelated nonconductive flag")
	TEST_ASSERT(target.flags & NOCONDUCT, "the target's lid round trip preserves its unrelated nonconductive flag")
