/// A carried selection kit consumes itself without dropping the actor's unrelated active item.
/datum/unit_test/interim_selection_kit_inactive/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/selectable_item/kit = allocate(/obj/item/selectable_item, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_active_hand(pen), "the unrelated pen occupies the active hand")
	TEST_ASSERT(user.put_in_inactive_hand(kit), "the selection kit occupies the inactive hand")
	var/datum/prompt/choice/ask = open_request(kit, /datum/prompt/choice, TYPE_PROC_REF(/obj/item/selectable_item, item_selected), answerer = user, subject = kit, choices = TYPE_TABLE_GET(kit, selectable_item_options), ask_flags = ASK_CARRIED | ASK_CAPABLE, timeout = 0)
	TEST_ASSERT_NULL(test_prompt_answer(ask, "Health Analyzer"), "the actual typed choice answer reaches the callback")
	own_turf_contents(T)
	TEST_ASSERT(QDELETED(kit), "selection consumes the original kit")
	TEST_ASSERT_EQUAL(user.get_active_hand(), pen, "selection preserves the unrelated active item")
	TEST_ASSERT_NULL(user.get_inactive_hand(), "selection vacates the consumed kit's hand")
	var/obj/item/healthanalyzer/result = locate_within(T, /obj/item/healthanalyzer)
	TEST_ASSERT(result, "the actual selected analyzer lands on the turf when the active hand is occupied")

/// A refused selection consumes nothing and creates no product.
/datum/unit_test/interim_selection_kit_refusal/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/selectable_item/kit = allocate(/obj/item/selectable_item, T)
	var/obj/item/pen/pen = allocate(/obj/item/pen, T)
	TEST_ASSERT(user.put_in_active_hand(pen), "the unrelated pen occupies the active hand")
	TEST_ASSERT(user.put_in_inactive_hand(kit), "the selection kit occupies the inactive hand")
	var/datum/dq_containment_listener/refusal = allocate(/datum/dq_containment_listener)
	refusal.watch(user)
	refusal.block_remove = TRUE
	TEST_ASSERT(kit.loc.release_refusal(kit, user), "the actual kit refuses consumption")
	var/datum/prompt/choice/ask = open_request(kit, /datum/prompt/choice, TYPE_PROC_REF(/obj/item/selectable_item, item_selected), answerer = user, subject = kit, choices = TYPE_TABLE_GET(kit, selectable_item_options), ask_flags = ASK_CARRIED | ASK_CAPABLE, timeout = 0)
	TEST_ASSERT_NULL(test_prompt_answer(ask, "Health Analyzer"), "the actual typed choice answer reaches the callback")
	own_turf_contents(T)
	TEST_ASSERT(!QDELETED(kit), "refusal preserves the original kit")
	TEST_ASSERT_EQUAL(user.get_active_hand(), pen, "refusal preserves the unrelated active item")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), kit, "refusal preserves the kit's original hand")
	TEST_ASSERT_NULL(locate_within(T, /obj/item/healthanalyzer), "refusal creates no floor product")
	TEST_ASSERT_NULL(locate_within(user, /obj/item/healthanalyzer), "refusal creates no inventory product")
