/// The actual repeatable remote-button emag removes both access modes, making its previously refused public toggle usable without changing wiring or toggling on emag itself.
/datum/unit_test/interim_remote_button_emag_access/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/button/remote/button = allocate(/obj/machinery/button/remote, T)
	button.set_stat(0)
	button.req_access = list(ACCESS_ENGINE_EQUIP)
	button.req_one_access = list(ACCESS_SECURITY, ACCESS_RESEARCH)
	var/wiring_before = button.wires_num
	TEST_ASSERT(button.operable(), "the actual fixture button is operable")
	TEST_ASSERT(!button.allowed(user), "the actual actor lacks both configured access modes")
	TEST_ASSERT_EQUAL(button.desiredstate, 0, "the actual button begins with its default requested state")
	button.interaction_toggle(user, null, null)
	TEST_ASSERT_EQUAL(button.desiredstate, 0, "the real unauthorized toggle preserves the requested state")
	TEST_ASSERT_EQUAL(emag_target(button, 1, user), 1, "the actual declared emag consumes one use to remove authentication")
	TEST_ASSERT_NULL(button.req_access, "the actual emag clears the required-all access list")
	TEST_ASSERT_NULL(button.req_one_access, "the actual emag clears the required-any access list")
	TEST_ASSERT(button.allowed(user), "the same actual actor is allowed after authentication is removed")
	TEST_ASSERT_EQUAL(button.wires_num, wiring_before, "emagging preserves the actual button's wiring flags")
	TEST_ASSERT_EQUAL(button.desiredstate, 0, "emagging does not itself toggle the requested state")
	button.interaction_toggle(user, null, null)
	TEST_ASSERT_EQUAL(button.desiredstate, 1, "the real now-authorized toggle changes the actual requested state")
	TEST_ASSERT_EQUAL(emag_target(button, 1, user), 0, "a repeat without access lists consumes no additional emag use")
	TEST_ASSERT_EQUAL(button.desiredstate, 1, "the repeat emag does not toggle the requested state")
	TEST_ASSERT_NULL(button.req_access, "repeat refusal preserves the cleared required-all list")
	TEST_ASSERT_NULL(button.req_one_access, "repeat refusal preserves the cleared required-any list")
	TEST_ASSERT_EQUAL(button.wires_num, wiring_before, "the full emag interaction sequence preserves actual wiring flags")
