/// The real cistern opening and insertion routes respect held-item release and refund their original occupancy on removal.
/datum/unit_test/om/interim_toilet_cistern_sticky_item/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/toilet/toilet = allocate(/obj/structure/toilet, T)
	var/obj/item/tool/crowbar/crowbar = allocate(/obj/item/tool/crowbar, T)
	var/obj/item/pen/item = allocate(/obj/item/pen, T)
	made += list(user, toilet, crowbar, item)
	TEST_ASSERT(!toilet.cistern, "the actual fresh toilet starts with a covered cistern")
	TEST_ASSERT_EQUAL(toilet.w_items, 0, "the actual fresh cistern starts empty")
	if(toilet.open)
		test_op_handler(toilet, "interaction_hand", user)
	TEST_ASSERT(!toilet.open, "the actual hand interaction leaves the seat closed for cistern retrieval")
	TEST_ASSERT(user.put_in_active_hand(crowbar), "the actor holds the actual cistern opening tool")
	TEST_ASSERT_NOTNULL(perform_op(user, toilet, "use_crowbar", crowbar, ORIGIN_CLICK, AUTH_PHYSICAL), "the actual crowbar action starts opening the cistern")
	TEST_ASSERT(test_actor_busy(user), "opening the actual cistern creates a pending timed action")
	TEST_ASSERT(!toilet.cistern, "starting the actual delay does not open the cistern early")
	scheduler_advance((4 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual actor remains capable through the opening delay")
	TEST_ASSERT(!test_actor_busy(user), "the real cistern-opening action completes")
	TEST_ASSERT(toilet.cistern, "the actual completed crowbar action exposes the cistern")
	TEST_ASSERT(user.unEquip(crowbar, target = T), "the actor actually releases its opening tool")
	TEST_ASSERT(user.put_in_active_hand(item), "the actor holds the original item to store")
	add_trait(item, TRAIT_NODROP, "interim_toilet_sticky_item")
	TEST_ASSERT(user.release_refusal(item, user), "the actual inventory refuses release of the sticky item")
	test_op_handler(toilet, "interaction_item", user, item)
	TEST_ASSERT_EQUAL(item.loc, user, "refused cistern insertion preserves actual inventory containment")
	TEST_ASSERT_EQUAL(user.get_active_hand(), item, "refused cistern insertion preserves the exact hand slot")
	TEST_ASSERT_EQUAL(toilet.w_items, 0, "refused cistern insertion adds no occupancy")
	remove_trait(item, TRAIT_NODROP, "interim_toilet_sticky_item")
	test_op_handler(toilet, "interaction_item", user, item)
	TEST_ASSERT_EQUAL(item.loc, toilet, "allowed actual insertion places the original item inside the cistern")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears the source hand")
	TEST_ASSERT_EQUAL(toilet.w_items, item.w_class, "allowed insertion charges exactly the real item size")
	test_op_handler(toilet, "interaction_hand", user)
	TEST_ASSERT_EQUAL(user.get_active_hand(), item, "actual cistern retrieval returns the original item to the free hand")
	TEST_ASSERT_EQUAL(item.loc, user, "actual retrieval restores inventory containment")
	TEST_ASSERT_EQUAL(toilet.w_items, 0, "actual retrieval refunds the exact original cistern occupancy")
	qdel(toilet)
	TEST_ASSERT(!QDELETED(item), "empty toilet teardown preserves the returned original item")
