/// The actual fluid-pump battery-panel route respects held-cell release and returns the same cell without losing the pump mixture.
/datum/unit_test/interim_fluid_pump_sticky_cell/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/pump/pump = allocate(/obj/machinery/pump, T)
	var/obj/item/tool/screwdriver/screwdriver = allocate(/obj/item/tool/screwdriver, T)
	var/obj/item/tool/crowbar/crowbar = allocate(/obj/item/tool/crowbar, T)
	var/obj/item/cell/cell = pump.cell
	TEST_ASSERT_NOTNULL(cell, "the actual fluid pump starts with its installed real power cell")
	own(cell)
	TEST_ASSERT(user.put_in_active_hand(screwdriver), "the actor holds the actual panel screw tool")
	test_op_handler(pump, "screwdriver_used", user, screwdriver)
	TEST_ASSERT(pump.unlocked, "the actual battery panel is unlocked")
	TEST_ASSERT(user.unEquip(screwdriver, target = T), "the actor actually releases the first tool")
	TEST_ASSERT(user.put_in_active_hand(crowbar), "the actor holds the actual panel-opening tool")
	test_op_handler(pump, "crowbar_used", user, crowbar)
	TEST_ASSERT(pump.open, "the actual battery panel is open")
	TEST_ASSERT(user.unEquip(crowbar, target = T), "the actor actually releases its panel-opening tool")
	perform_op(user, pump, "use", origin = ORIGIN_SYSTEM)
	TEST_ASSERT_NULL(pump.cell, "the actual open-panel hand action ejects the original installed cell")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cell, "actual ejection returns the original installed cell to the free hand")
	TEST_ASSERT_EQUAL(isnull(pump.battery_panel_open(null)) && isnull(pump.no_cell(null)), TRUE, "the actual open empty panel permits a real cell insertion")
	pump.reagents.add_reagent(REAGENT_ID_WATER, 10)
	var/charge_before = cell.charge
	var/capacity_before = pump.reagents.maximum_volume
	add_trait(cell, TRAIT_NODROP, "interim_fluid_pump_sticky_cell")
	TEST_ASSERT(user.release_refusal(cell, user), "the actual inventory refuses release of its sticky cell")
	perform_op(user, pump, "insert_cell", cell, origin = ORIGIN_SYSTEM)
	TEST_ASSERT_NULL(pump.cell, "refused insertion preserves the actual empty cell view")
	TEST_ASSERT_EQUAL(cell.loc, user, "refused insertion preserves actual cell inventory containment")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cell, "refused insertion preserves the exact original cell hand")
	TEST_ASSERT(!(cell in pump.component_parts), "refused insertion records no battery component")
	TEST_ASSERT_EQUAL(cell.charge, charge_before, "refused insertion conserves original cell charge")
	TEST_ASSERT_EQUAL(pump.reagents.maximum_volume, capacity_before, "refused insertion does not rebuild or enlarge the pump's reagent holder")
	TEST_ASSERT_EQUAL(pump.reagents.get_reagent_amount(REAGENT_ID_WATER), 10, "refused insertion preserves the pump's original stored mixture")
	remove_trait(cell, TRAIT_NODROP, "interim_fluid_pump_sticky_cell")
	perform_op(user, pump, "insert_cell", cell, origin = ORIGIN_SYSTEM)
	TEST_ASSERT_EQUAL(pump.cell, cell, "allowed insertion restores the exact original pump cell view")
	TEST_ASSERT(cell in pump.component_parts, "allowed insertion records the original battery as an actual component")
	TEST_ASSERT_EQUAL(owner_of(cell), pump, "allowed insertion stamps actual component ownership")
	TEST_ASSERT_EQUAL(cell.loc, pump, "allowed insertion physically contains the original cell")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed insertion clears the original cell hand")
	TEST_ASSERT_EQUAL(pump.reagents.get_reagent_amount(REAGENT_ID_WATER), 10, "successful part refresh preserves the actual original pump mixture")
	perform_op(user, pump, "use", origin = ORIGIN_SYSTEM)
	TEST_ASSERT_NULL(pump.cell, "actual second ejection clears the cell view")
	TEST_ASSERT(!(cell in pump.component_parts), "actual second ejection removes its battery component")
	TEST_ASSERT_EQUAL(user.get_active_hand(), cell, "actual second ejection returns the exact original cell")
	TEST_ASSERT_NULL(owner_of(cell), "actual second ejection clears component ownership")
	TEST_ASSERT_EQUAL(cell.charge, charge_before, "the actual complete cell round trip preserves stored charge")
	qdel(pump)
	TEST_ASSERT(!QDELETED(cell), "empty pump teardown preserves its returned original cell")
