/// Replacing a real attached news photo must respect the incoming photograph's release rules before ejecting the existing attachment.
/datum/unit_test/interim_newscaster_sticky_photo_replacement/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/machinery/newscaster/caster = allocate(/obj/machinery/newscaster, T)
	var/obj/item/photo/original = allocate(/obj/item/photo, T)
	var/obj/item/photo/replacement = allocate(/obj/item/photo, T)
	TEST_ASSERT(user.put_in_active_hand(original), "the actor holds the original physical photo")
	caster.AttachPhoto(user)
	TEST_ASSERT_NOTNULL(caster.photo_data, "the actual attachment route records its news photo datum")
	var/datum/news_photo/original_data = caster.photo_data
	TEST_ASSERT_EQUAL(original_data.photo(), original, "the actual attachment references the original physical photo")
	TEST_ASSERT_EQUAL(original.loc, caster, "the actual attachment physically contains the original photo")
	TEST_ASSERT_NULL(user.get_active_hand(), "the first attachment clears its actual source hand")
	TEST_ASSERT(user.put_in_active_hand(replacement), "the actor holds the actual replacement photo")
	add_trait(replacement, TRAIT_NODROP, "interim_newscaster_sticky_photo")
	TEST_ASSERT(user.release_refusal(replacement, user), "actual inventory refuses release of the sticky replacement")
	caster.AttachPhoto(user)
	TEST_ASSERT_EQUAL(caster.photo_data, original_data, "refused replacement preserves the original attachment datum")
	TEST_ASSERT_EQUAL(caster.photo_data.photo(), original, "refused replacement preserves the original photo relation")
	TEST_ASSERT_EQUAL(original.loc, caster, "refused replacement does not eject the existing photo")
	TEST_ASSERT_EQUAL(replacement.loc, user, "refused replacement preserves incoming actual inventory containment")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "refused replacement preserves the exact incoming hand slot")
	remove_trait(replacement, TRAIT_NODROP, "interim_newscaster_sticky_photo")
	caster.AttachPhoto(user)
	TEST_ASSERT_EQUAL(caster.photo_data.photo(), replacement, "allowed replacement records the exact incoming photo")
	TEST_ASSERT_EQUAL(replacement.loc, caster, "allowed replacement physically contains the incoming photo")
	TEST_ASSERT_NULL(user.get_active_hand(), "allowed replacement clears its original source hand")
	TEST_ASSERT_EQUAL(user.get_inactive_hand(), original, "allowed replacement returns the original attachment to the free inactive hand")
	TEST_ASSERT_EQUAL(original.loc, user, "the ejected original photo returns to actual actor containment")
	TEST_ASSERT(!QDELETED(original), "replacement does not consume the original physical photograph")
	caster.AttachPhoto(user)
	TEST_ASSERT_NULL(caster.photo_data, "the actual empty-hand attachment action detaches the current news photo")
	TEST_ASSERT_EQUAL(replacement.loc, T, "with its inactive hand occupied, actual detachment leaves the replacement on the floor")
	qdel(caster)
	TEST_ASSERT(!QDELETED(original) && !QDELETED(replacement), "empty caster teardown preserves both returned physical photographs")
