/datum/unit_test/interim_rcd_native_choices/Run()
	test_driver_begin()
	exercise_choices()
	test_driver_end()

/datum/unit_test/interim_rcd_native_choices/proc/exercise_choices()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/rcd/tool = allocate(/obj/item/rcd, T)
	tool.mode_index = tool.rcd_mode_index(RCD_DECONSTRUCT)
	open_request(tool, /datum/prompt/choice/rcd_option_review, TYPE_PROC_REF(/obj/item/rcd, rcd_girder_chosen), answerer = user, choices = list("DEFAULT", "BAY", "ERIS"), anchor = tool, require_near = TRUE, optional_pick = TRUE)
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/choice/rcd_option_review), "RCD selection uses its actual native request kind")
	test_answer(user, "ERIS")
	TEST_ASSERT_EQUAL(tool.girder_type, /obj/structure/girder/eris, "Accepted choice changes the actual constructed girder type")
	TEST_ASSERT_EQUAL(tool.mode_index, tool.rcd_mode_index(RCD_FLOORWALL), "Accepted girder choice selects construction mode")
	tool.mode_index = tool.rcd_mode_index(RCD_DECONSTRUCT)
	open_request(tool, /datum/prompt/choice/rcd_option_review, TYPE_PROC_REF(/obj/item/rcd, rcd_girder_chosen), answerer = user, choices = list("DEFAULT", "BAY", "ERIS"), anchor = tool, require_near = TRUE, optional_pick = TRUE)
	test_answer(user, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(tool.girder_type, /obj/structure/girder/eris, "Explicit cancellation keeps the selected girder type")
	TEST_ASSERT_EQUAL(tool.mode_index, tool.rcd_mode_index(RCD_FLOORWALL), "Optional cancellation retains the existing mode-switch behavior")
	tool.mode_index = tool.rcd_mode_index(RCD_DECONSTRUCT)
	open_request(tool, /datum/prompt/choice/rcd_option_review, TYPE_PROC_REF(/obj/item/rcd, rcd_girder_chosen), answerer = user, choices = list("DEFAULT", "BAY", "ERIS"), anchor = tool, require_near = TRUE, optional_pick = TRUE)
	user.forceMove(locate(T.x + 3, T.y, T.z))
	test_answer(user, "DEFAULT")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "A late out-of-range answer ends the request")
	TEST_ASSERT_EQUAL(tool.girder_type, /obj/structure/girder/eris, "A late refused answer preserves the actual construction type")
	TEST_ASSERT_EQUAL(tool.mode_index, tool.rcd_mode_index(RCD_DECONSTRUCT), "A late refused answer does not invoke the optional cancellation fallback")
