/// Opening the real washer returns its separate dye as well as its laundry, including a dye-only load.
/datum/unit_test/interim_washer_dye_ejection/Run()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	for(var/dye_type in list(/obj/item/pen/crayon, /obj/item/stamp))
		for(var/with_laundry in list(FALSE, TRUE))
			var/obj/machinery/washing_machine/washer = allocate(/obj/machinery/washing_machine, T)
			var/obj/item/dye = allocate(dye_type, T)
			var/open_state = washer.state
			TEST_ASSERT(user.put_in_active_hand(dye), "the actor holds the original dye")
			test_click(user, washer, dye)
			TEST_ASSERT_EQUAL(washer.crayon(), dye, "actual insertion records the dye before the opening test")
			TEST_ASSERT_EQUAL(dye.loc, washer, "actual insertion physically contains the dye")
			var/obj/item/clothing/gloves/white/laundry
			if(with_laundry)
				laundry = allocate(/obj/item/clothing/gloves/white, T)
				TEST_ASSERT(user.put_in_active_hand(laundry), "the actor holds the actual laundry")
				test_click(user, washer, laundry)
				TEST_ASSERT(laundry in washer.washing, "the actual washer records its separate laundry")
			test_click(user, washer, null)
			TEST_ASSERT_NOTEQUAL(washer.state, open_state, "the actual public hand interaction closes the washer")
			TEST_ASSERT_EQUAL(dye.loc, washer, "closing the washer keeps the original dye inside")
			test_click(user, washer, null)
			TEST_ASSERT_EQUAL(washer.state, open_state, "the second public hand interaction opens the washer")
			TEST_ASSERT_NULL(washer.crayon(), "opening clears the original dye relation")
			TEST_ASSERT_EQUAL(dye.loc, T, "opening physically returns the original dye to the floor")
			TEST_ASSERT(!QDELETED(dye), "opening does not consume or delete the original dye")
			TEST_ASSERT_NULL(owner_of(dye), "dye ejection creates no ownership stamp")
			TEST_ASSERT_EQUAL(LAZYLEN(washer.washing), 0, "opening leaves no recorded laundry")
			if(with_laundry)
				TEST_ASSERT_EQUAL(laundry.loc, T, "opening also returns the exact original laundry")
				TEST_ASSERT_NULL(owner_of(laundry), "opening detaches the declared laundry ownership")
			qdel(washer)
			TEST_ASSERT(!QDELETED(dye), "empty washer teardown preserves its returned dye")
			TEST_ASSERT_EQUAL(dye.loc, T, "empty washer teardown leaves the returned dye on the actual floor")
