/// The actual refill entry uses the dispenser's dose, honors receiving capacity and never debits a full-container or empty-dispenser refusal.
/datum/unit_test/interim_water_tank_refill_amounts
	parent_type = /datum/unit_test/dq_p2_reagents

/datum/unit_test/interim_water_tank_refill_amounts/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = rc_actor(T)
	var/obj/structure/reagent_dispensers/watertank/tank = allocate(/obj/structure/reagent_dispensers/watertank, T)
	var/obj/item/reagent_containers/glass/beaker/beaker = allocate(/obj/item/reagent_containers/glass/beaker, T)
	rc_set_amount_menu(user, beaker, 7)
	TEST_ASSERT_EQUAL(rc_amount(beaker), 7, "the actual amount menu configures a seven-unit pour dose")
	TEST_ASSERT_EQUAL(tank.amount_per_transfer_from_this, 10, "the actual water tank dispenses ten units")
	TEST_ASSERT_EQUAL(tank.reagents.get_reagent_amount(REAGENT_ID_WATER), 1000, "the actual water tank begins with its declared thousand units of water")
	rc_click(user, tank, beaker)
	TEST_ASSERT_EQUAL(beaker.reagents.total_volume, 10, "the actual refill uses the tank's ten-unit dose rather than the beaker's seven-unit pour dose")
	TEST_ASSERT_EQUAL(tank.reagents.total_volume, 990, "the actual refill debits exactly ten units from the tank")
	beaker.reagents.clear_reagents()
	beaker.reagents.add_reagent(REAGENT_ID_WATER, beaker.reagents.maximum_volume - 4)
	rc_click(user, tank, beaker)
	TEST_ASSERT_EQUAL(beaker.reagents.total_volume, beaker.reagents.maximum_volume, "the actual capacity-limited refill fills the last four units")
	TEST_ASSERT_EQUAL(tank.reagents.total_volume, 986, "the capacity-limited refill debits only the four accepted units")
	rc_click(user, tank, beaker)
	TEST_ASSERT_EQUAL(tank.reagents.total_volume, 986, "the actual full-container refusal debits no tank water")
	TEST_ASSERT_EQUAL(beaker.reagents.total_volume, beaker.reagents.maximum_volume, "the actual full-container refusal preserves its water volume")
	beaker.reagents.clear_reagents()
	tank.reagents.clear_reagents()
	tank.reagents.add_reagent(REAGENT_ID_WATER, 3)
	rc_click(user, tank, beaker)
	TEST_ASSERT_EQUAL(tank.reagents.total_volume, 0, "the actual refill can exhaust a tank with only three units remaining")
	TEST_ASSERT_EQUAL(beaker.reagents.total_volume, 3, "the actual refill delivers only the tank's three remaining units")
	rc_click(user, tank, beaker)
	TEST_ASSERT_EQUAL(tank.reagents.total_volume, 0, "the actual empty-tank refusal preserves the empty source")
	TEST_ASSERT_EQUAL(beaker.reagents.total_volume, 3, "the actual empty-tank refusal preserves the receiver's existing water")
