/// The real holder/owner check refuses theft; consumption releases the owner's hand.
/datum/unit_test/interim_crystal_consumption/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/owner = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/holder = allocate(/mob/living/carbon/human, T)
	var/obj/item/capture_crystal/crystal = allocate(/obj/item/capture_crystal, T)
	rel_set(crystal, nameof(crystal.owner), owner)
	TEST_ASSERT(holder.put_in_active_hand(crystal), "The non-owner must hold the real crystal")
	crystal.destroy_crystal_effect(holder)
	TEST_ASSERT(!QDELETED(crystal), "A non-owner must not destroy the crystal")
	TEST_ASSERT_EQUAL(holder.get_active_hand(), crystal, "Refused destruction must preserve the holder's hand")
	TEST_ASSERT(holder.drop_from_inventory(crystal, T), "The holder must return the crystal")
	TEST_ASSERT(owner.put_in_active_hand(crystal), "The actual owner must hold the crystal")
	add_trait(crystal, TRAIT_NODROP, "interim_crystal_consumption")
	crystal.destroy_crystal_effect(owner)
	TEST_ASSERT(!QDELETED(crystal), "Consumption must honor the actual inventory removal refusal")
	TEST_ASSERT_EQUAL(owner.get_active_hand(), crystal, "Refused consumption must retain the stuck crystal")
	remove_trait(crystal, TRAIT_NODROP, "interim_crystal_consumption")
	crystal.destroy_crystal_effect(owner)
	TEST_ASSERT(QDELETED(crystal), "The owner must consume an ordinary removable crystal")
	TEST_ASSERT_NULL(owner.get_active_hand(), "Consumption must release the owner's hand")

/// Destroying an occupied crystal must free its actual captured creature.
/datum/unit_test/interim_crystal_occupied_consumption/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/owner = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/patient = allocate(/mob/living/carbon/human, T)
	var/obj/item/capture_crystal/crystal = allocate(/obj/item/capture_crystal, T)
	rel_set(crystal, nameof(crystal.owner), owner)
	rel_set(crystal, nameof(crystal.bound_mob), patient)
	patient.capture_caught = TRUE
	patient.forceMove(crystal)
	TEST_ASSERT(owner.put_in_active_hand(crystal), "The owner must hold the occupied crystal")
	TEST_ASSERT_EQUAL(patient.loc, crystal, "The captured patient must physically reside inside the crystal")
	crystal.destroy_crystal_effect(owner)
	TEST_ASSERT(QDELETED(crystal), "The owner must consume the occupied crystal")
	TEST_ASSERT(!QDELETED(patient), "Consumption must preserve the captured creature")
	TEST_ASSERT_EQUAL(patient.loc, T, "Consumption must release the creature onto the actual floor")
	TEST_ASSERT(!patient.capture_caught, "Released creatures must no longer be under capture control")
	TEST_ASSERT_NULL(owner.get_active_hand(), "Occupied consumption must also release the owner's hand")
