/// Real pylon variants shatter on the first hit, survive ineffective hits, then pulverize.
/datum/unit_test/interim_pylon_pulverize/Run()
	var/static/list/pylon_types = list(/obj/structure/cult/pylon, /obj/structure/cult/pylon/swarm, /obj/structure/cult/pylon/swarm/zp_well, /obj/structure/cult/pylon/swarm/defender)
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	for(var/pylon_type in pylon_types)
		var/obj/structure/cult/pylon/pylon = allocate(pylon_type, run_loc_floor_bottom_left)
		TEST_ASSERT(!QDELETED(pylon), "actual pylon variant survives its full parent initialization")
		TEST_ASSERT(!pylon.isbroken, "actual pylon variant starts intact")
		TEST_ASSERT(pylon.density, "actual intact pylon blocks passage")
		TEST_ASSERT_EQUAL(pylon.light_range, 5, "actual intact pylon preserves its inherited light range")
		var/original_state = pylon.icon_state
		generic_hit(pylon, user, 50)
		TEST_ASSERT(!QDELETED(pylon), "first actual guaranteed hit leaves a broken structure")
		TEST_ASSERT(pylon.isbroken, "first actual hit sets the tracked broken state")
		TEST_ASSERT(!pylon.density, "actual broken pylon permits passage")
		TEST_ASSERT_EQUAL(pylon.icon_state, "[original_state]-broken", "actual break preserves the variant's broken appearance")
		TEST_ASSERT_EQUAL(pylon.light_range, 0, "actual break extinguishes the pylon")
		generic_hit(pylon, user, 0)
		TEST_ASSERT(!QDELETED(pylon), "actual zero-damage hit cannot pulverize a broken pylon")
		TEST_ASSERT(pylon.isbroken && !pylon.density, "ineffective actual hit preserves the broken passage state")
		generic_hit(pylon, user, 50)
		TEST_ASSERT(QDELETED(pylon), "second actual guaranteed hit consumes the pulverized structure")
		TEST_ASSERT(!QDELETED(user), "actual structure cleanup preserves its attacking actor")
