/// ID removal releases ownership while preserving actual handoff and full-hand fallback.
/datum/unit_test/interim_pda_id_removal/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/pda/pda = allocate(/obj/item/pda, T)
	var/obj/item/card/id/card = allocate(/obj/item/card/id, T)
	TEST_ASSERT(actor.put_in_active_hand(pda), "The actor must hold the PDA")
	TEST_ASSERT(own_set(pda, nameof(pda.id), card), "The fixture PDA must own its inserted ID")
	TEST_ASSERT_EQUAL(card.loc, pda, "The inserted ID must reside inside the PDA")
	TEST_ASSERT_EQUAL(pda.id_check(actor, 1), 1, "The existing ID-check removal entry must succeed")
	TEST_ASSERT_NULL(pda.id, "ID removal must release the PDA's declared ownership")
	TEST_ASSERT(actor.is_in_hands(card), "An available hand must receive the removed ID")
	TEST_ASSERT(!QDELETED(card), "Removing an ID must preserve it")
	TEST_ASSERT(own_set(pda, nameof(pda.id), card), "The same ID must be reinsertable")
	var/obj/item/pen/blocker = allocate(/obj/item/pen, T)
	TEST_ASSERT(actor.put_in_inactive_hand(blocker), "The other hand must be occupied for fallback")
	pda.remove_id(actor)
	TEST_ASSERT_NULL(pda.id, "Full-hand ID removal must still release PDA ownership")
	TEST_ASSERT_EQUAL(card.loc, T, "Full hands must leave the removed ID on the floor")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), pda, "ID removal must preserve the held PDA")
	TEST_ASSERT(actor.is_in_hands(blocker), "ID removal must preserve the other held item")
	TEST_ASSERT(!QDELETED(card), "Floor fallback must preserve the removed ID")

/// Pen removal retains its active-hand rule and floor fallback.
/datum/unit_test/interim_pda_pen_removal/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/obj/item/pda/pda = allocate(/obj/item/pda, T)
	var/obj/item/pen/pen = locate_within(pda, /obj/item/pen)
	TEST_ASSERT(pen, "A real PDA must initialize with its pen")
	own(pen)
	TEST_ASSERT(actor.put_in_active_hand(pda), "The actor must hold the PDA")
	actor.swap_hand()
	TEST_ASSERT_NULL(actor.get_active_hand(), "The actor's active hand must be available")
	pda.remove_pen(actor)
	TEST_ASSERT_EQUAL(actor.get_active_hand(), pen, "An empty active hand must receive the pen")
	TEST_ASSERT_NULL(locate_within(pda, /obj/item/pen), "Handoff must remove the pen from PDA contents")
	TEST_ASSERT(!QDELETED(pen), "Pen removal must preserve the pen")
	pen.forceMove(pda)
	var/obj/item/pen/blocker = allocate(/obj/item/pen, T)
	TEST_ASSERT(actor.put_in_active_hand(blocker), "The active hand must be occupied before fallback")
	pda.remove_pen(actor)
	TEST_ASSERT_EQUAL(pen.loc, T, "Full hands must leave the removed pen on the floor")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), blocker, "Fallback must preserve the active hand item")
	TEST_ASSERT(actor.is_in_hands(pda), "Fallback must preserve the PDA in the other hand")
	TEST_ASSERT_NULL(locate_within(pda, /obj/item/pen), "Floor fallback must remove the pen from PDA contents")
	TEST_ASSERT(!QDELETED(pen), "Floor fallback must preserve the pen")
	var/obj/item/pda/floor_pda = allocate(/obj/item/pda, T)
	var/obj/item/pen/floor_pen = locate_within(floor_pda, /obj/item/pen)
	TEST_ASSERT(floor_pen, "The floor PDA must initialize with its own pen")
	own(floor_pen)
	floor_pda.remove_pen(actor)
	TEST_ASSERT_EQUAL(floor_pen.loc, T, "Removing from a floor PDA must leave its pen on that floor")
