/// The real delayed glass-panel construction rechecks a shrinking held stack before paying its two-sheet cost.
/datum/unit_test/om/interim_frame_glass_cost_recheck/run_om(list/made)
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/structure/frame/computer/frame = allocate(/obj/structure/frame/computer, T)
	var/obj/item/circuitboard/crew/board = allocate(/obj/item/circuitboard/crew, T)
	var/obj/item/stack/cable_coil/cable = allocate(/obj/item/stack/cable_coil, T, 6)
	var/obj/item/stack/material/glass/glass = allocate(/obj/item/stack/material/glass, T, 3)
	made += list(user, frame, board, cable, glass)
	TEST_ASSERT(frame.anchored, "the actual computer-frame subtype starts anchored")
	TEST_ASSERT(interim_construction_step(frame, user, /datum/interaction/construction/frame/insert_board, board), "the actual computer board enters its matching frame")
	TEST_ASSERT(interim_construction_step(frame, user, /datum/interaction/construction/frame/fasten_board), "the actual board can be fastened")
	TEST_ASSERT(interim_construction_step(frame, user, /datum/interaction/construction/frame/wire, cable), "the actual computer frame can be wired")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "the actual fixture reaches the wired state")
	var/datum/interaction/construction/add_glass
	for(var/datum/interaction/construction/edge as anything in construction_edges_for(frame))
		if(edge.type == /datum/interaction/construction/frame/add_glass)
			add_glass = edge
	TEST_ASSERT_NOTNULL(add_glass, "the actual wired computer frame offers its glass-panel edge")
	TEST_ASSERT(user.put_in_active_hand(glass), "the actual actor holds three glass sheets")
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual actor is capable of adding a panel")
	TEST_ASSERT(add_glass.perform(user, frame, glass), "the actual declared edge starts its timed panel action")
	TEST_ASSERT(LAZYLEN(user.do_afters), "the actual panel action is pending")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "starting the real action does not install the panel early")
	TEST_ASSERT_EQUAL(glass.get_amount(), 3, "starting the real action does not spend sheets early")
	TEST_ASSERT(glass.use(2), "another actual stack use consumes two sheets while the panel action waits")
	TEST_ASSERT_EQUAL(glass.get_amount(), 1, "the real held stack now has insufficient panel material")
	TEST_ASSERT_EQUAL(user.get_active_hand(), glass, "the stack mutation preserves the same actual held item")
	scheduler_advance((3 SECONDS) / (1 SECOND))
	TEST_ASSERT(!user.incapacitated(INCAPACITATION_STUNNED | INCAPACITATION_KNOCKOUT), "the actual actor remains capable after this single short action")
	TEST_ASSERT(!LAZYLEN(user.do_afters), "the actual panel attempt finishes its pending action")
	TEST_ASSERT_EQUAL(frame.state, FRAME_WIRED, "completion refuses an insufficient stack rather than installing the panel")
	TEST_ASSERT_EQUAL(glass.get_amount(), 1, "the refused completion cannot spend the remaining insufficient sheet")
	TEST_ASSERT_EQUAL(user.get_active_hand(), glass, "the refused completion preserves the exact held stack")
	TEST_ASSERT_EQUAL(frame.circuit, board, "the refused completion preserves the exact installed computer board")
	TEST_ASSERT_EQUAL(board.loc, frame, "the refused completion preserves actual board containment")
	TEST_ASSERT_EQUAL(cable.get_amount(), 1, "the refused panel completion preserves prior wiring consumption")
