/// Actual alternate clicks preserve confirmation cancellation and both original prompt defaults.
/datum/unit_test/round2_shield_recolor_request
	parent_type = /datum/unit_test/dq_p2_engine

/datum/unit_test/round2_shield_recolor_request/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/item/shield/energy/shield = allocate(/obj/item/shield/energy, T)
	TEST_ASSERT(user.put_in_active_hand(shield), "actual actor holds the original energy shield")
	var/original_color = shield.lcolor
	test_click(user, shield, shield, GESTURE_ALT)
	test_time(1 SECOND)
	var/datum/prompt/yes_no/confirmation = SSrequests.open_for(user)
	TEST_ASSERT(istype(confirmation), "actual alternate click opens confirmation")
	TEST_ASSERT_EQUAL(confirmation.title, "Confirm Recolor", "actual confirmation retains its original title")
	TEST_ASSERT_EQUAL(confirmation.timeout, REQUEST_DEFAULT_TIMEOUT, "actual confirmation has no expiry deadline (a request given no timeout gets the default, framework_gaps.md E2)")
	test_answer(user, FALSE)
	test_time(1 SECOND)
	TEST_ASSERT_NULL(SSrequests.open_for(user), "a real No answer opens no color request")
	TEST_ASSERT_EQUAL(shield.lcolor, original_color, "a real No answer preserves original shield color")
	test_click(user, shield, shield, GESTURE_ALT)
	test_time(1 SECOND)
	confirmation = SSrequests.open_for(user)
	TEST_ASSERT(istype(confirmation), "actual alternate click opens a new confirmation")
	shield.set_lcolor("#abcdef")
	TEST_ASSERT_EQUAL(shield.lcolor, "#abcdef", "public setter changes the real shield while confirmation is open")
	test_answer(user, TRUE)
	test_time(1 SECOND)
	var/datum/prompt/color/color_request = SSrequests.open_for(user)
	TEST_ASSERT(istype(color_request), "a real Yes answer opens the color request")
	TEST_ASSERT_EQUAL(color_request.title, "Choose Energy Color", "actual color request retains its original title")
	TEST_ASSERT_EQUAL(color_request.timeout, REQUEST_DEFAULT_TIMEOUT, "actual color request has no expiry deadline (a request given no timeout gets the default, framework_gaps.md E2)")
	TEST_ASSERT_EQUAL(color_request.default, "#abcdef", "second request reads the current shield color after confirmation")
	test_answer(user, "#123456")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(shield.lcolor, "#123456", "actual answer recolors the original shield")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "actual color answer completes the workflow")
	TEST_ASSERT_EQUAL(user.get_active_hand(), shield, "both workflows preserve the original shield hand")
