/// Actual native translator choices refuse unsupported output without changing the selected definition.
/datum/unit_test/round2_translator_native_choice
	parent_type = /datum/unit_test/dq_p2_engine

/datum/unit_test/round2_translator_native_choice/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	user.add_language(LANGUAGE_GALCOM)
	user.add_language(LANGUAGE_ROOTGLOBAL)
	var/datum/language/supported = GLOB.all_languages[LANGUAGE_GALCOM]
	var/datum/language/unsupported = GLOB.all_languages[LANGUAGE_ROOTGLOBAL]
	TEST_ASSERT(istype(supported) && istype(unsupported), "canonical Galcom and Dionaea global language definitions exist")
	TEST_ASSERT(supported in user.languages, "supported actual choice is one of the actor's languages")
	TEST_ASSERT(unsupported in user.languages, "unsupported actual choice is one of the actor's languages")
	TEST_ASSERT(supported.machine_understands && !(supported.flags & (NONVERBAL | HIVEMIND)), "canonical supported language has actual machine output")
	TEST_ASSERT(!unsupported.machine_understands || (unsupported.flags & (NONVERBAL | HIVEMIND)), "canonical unsupported language really cannot be output")
	var/obj/item/universal_translator/device = allocate(/obj/item/universal_translator, T)
	TEST_ASSERT(user.put_in_active_hand(device), "actual actor holds the original translator")
	TEST_ASSERT(!device.translation_enabled, "actual translator starts disabled")
	TEST_ASSERT_NULL(device.langset(), "actual translator starts without a selected language")
	var/initial_membership = (device in REGISTRY_MEMBERS(REGISTRY_LISTENING_OBJECTS))
	test_click(user, device, device)
	test_time(1 SECOND)
	var/datum/prompt/choice/question = SSrequests.open_for(user)
	TEST_ASSERT(istype(question), "actual native self activation opens its real language choice")
	TEST_ASSERT(supported in question.choices, "real request offers actor's supported language")
	TEST_ASSERT(unsupported in question.choices, "real request offers actor's unsupported language")
	test_answer(user, unsupported)
	test_time(1 SECOND)
	TEST_ASSERT(!device.translation_enabled, "unsupported actual answer cannot enable translator")
	TEST_ASSERT_NULL(device.langset(), "unsupported actual answer preserves original null selected definition")
	TEST_ASSERT_EQUAL((device in REGISTRY_MEMBERS(REGISTRY_LISTENING_OBJECTS)), initial_membership, "unsupported answer preserves original registry membership")
	TEST_ASSERT_EQUAL(user.get_active_hand(), device, "unsupported answer preserves exact original held device")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "refused operation closes its answered request")
	test_click(user, device, device)
	test_time(1 SECOND)
	question = SSrequests.open_for(user)
	TEST_ASSERT(istype(question), "a fresh real activation offers the language request after refusal")
	test_answer(user, supported)
	test_time(1 SECOND)
	TEST_ASSERT(device.translation_enabled, "supported actual answer enables original translator")
	TEST_ASSERT_EQUAL(device.langset(), supported, "supported actual answer stores exact registered language identity")
	TEST_ASSERT(device in REGISTRY_MEMBERS(REGISTRY_LISTENING_OBJECTS), "enabled original translator joins actual listening registry")
	test_click(user, device, device)
	test_time(1 SECOND)
	TEST_ASSERT(!device.translation_enabled, "next actual self activation disables original translator")
	TEST_ASSERT_NULL(device.langset(), "disable clears actual selected definition")
	TEST_ASSERT(!(device in REGISTRY_MEMBERS(REGISTRY_LISTENING_OBJECTS)), "disable leaves actual listening registry")
	TEST_ASSERT_EQUAL(user.get_active_hand(), device, "native enable and disable preserve exact original held device")
