/// Real native ability clicks retain their actor through actual core-backed spell creation.
/datum/unit_test/round2_technomancer_ability_actor/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/dummy/actor = allocate(/mob/living/carbon/human/dummy, T)
	var/mob/living/carbon/human/dummy/bystander = allocate(/mob/living/carbon/human/dummy, T)
	var/mob/observer/dead/observer = allocate(/mob/observer/dead, T)
	observer.forceMove(T)
	var/atom/movable/screen/movable/ability_master/master = allocate(/atom/movable/screen/movable/ability_master, actor)
	own_set(actor, nameof(actor.ability_master), master)
	var/obj/item/technomancer_core/universal/core = allocate(/obj/item/technomancer_core/universal, T)
	core.add_spell(/obj/item/spell/warp_strike, "Actor warp", "tech_warpstrike")
	TEST_ASSERT_EQUAL(length(core.spells), 1, "the real core creates one actually owned spell button")
	var/obj/spellbutton/button = core.spells[1]
	TEST_ASSERT_EQUAL(button.core, core, "the actual constructor retains its original core")
	TEST_ASSERT(actor.equip_to_slot_if_possible(core, SLOT_ID_BACK), "real inventory equips the actual universal core")
	TEST_ASSERT_EQUAL(core.wearer, actor, "the real equipped lifecycle records the actual wearer")
	var/atom/movable/screen/ability/obj_based/technomancer/ability = master.get_ability_by_instance(button)
	TEST_ASSERT(ability && ability.object() == button, "actual equip constructs an ability pointing at its original spell button")
	var/atom/movable/screen/movable/ability_master/bystander_master = allocate(/atom/movable/screen/movable/ability_master, bystander)
	own_set(bystander, nameof(bystander.ability_master), bystander_master)
	var/obj/item/technomancer_core/universal/bystander_core = allocate(/obj/item/technomancer_core/universal, T)
	TEST_ASSERT(bystander.equip_to_slot_if_possible(bystander_core, SLOT_ID_BACK), "real inventory equips the independent human's actual universal core")
	var/energy = core.energy
	var/bystander_energy = bystander_core.energy
	km_synthetic_click(observer, ability)
	TEST_ASSERT_NULL(actor.get_active_hand(), "an actual unsupported observer cannot create a spell for the core wearer")
	TEST_ASSERT_EQUAL(length(contents_of(observer, /obj/item/spell)), 0, "unsupported native clicking creates no observer spell")
	km_synthetic_click(bystander, ability)
	var/obj/item/spell/warp_strike/bystander_spell = bystander.get_active_hand()
	TEST_ASSERT(istype(bystander_spell), "another genuinely equipped human can use the existing unowned ability-click semantics")
	own(bystander_spell)
	TEST_ASSERT_EQUAL(bystander_spell.owner_ref(), bystander, "another native click retains the actual clicking human instead of substituting the ability's owner")
	TEST_ASSERT_EQUAL(bystander_spell.core, bystander_core, "the other native actor's real spell uses its own actually worn core")
	TEST_ASSERT_NULL(actor.get_active_hand(), "another human's native click cannot fill the original core wearer's hand")
	TEST_ASSERT(bystander.unEquip(bystander_spell), "real inventory releases the independent actual disposable spell")
	TEST_ASSERT(QDELETED(bystander_spell), "actual DROPDEL release cleans the independent spell")
	TEST_ASSERT_NULL(bystander.get_active_hand(), "actual independent spell release frees the other human's hand")
	km_synthetic_click(actor, ability)
	var/obj/item/spell/warp_strike/first = actor.get_active_hand()
	TEST_ASSERT(istype(first), "the actual native ability places a real warp spell in the initiating human's active hand")
	own(first)
	TEST_ASSERT_EQUAL(first.owner_ref(), actor, "actual spell construction preserves the initiating ability actor")
	TEST_ASSERT_EQUAL(first.core, core, "actual spell construction retains the exact worn core")
	TEST_ASSERT(first.run_checks(), "the actual universal core authorizes its real held spell without a fabricated antagonist")
	TEST_ASSERT(actor.unEquip(first), "real inventory releases the actual disposable spell")
	TEST_ASSERT(QDELETED(first), "actual DROPDEL release removes the original spell")
	TEST_ASSERT_NULL(actor.get_active_hand(), "real disposable release frees the initiating hand")
	km_synthetic_click(actor, ability)
	var/obj/item/spell/warp_strike/second = actor.get_active_hand()
	TEST_ASSERT(istype(second) && second != first, "repeated native activation creates a distinct real held warp spell")
	own(second)
	TEST_ASSERT_EQUAL(second.owner_ref(), actor, "repeated native activation retains the initiating actor")
	TEST_ASSERT_EQUAL(second.core, core, "repeated native activation retains the original worn core")
	TEST_ASSERT_EQUAL(core.energy, energy, "actual spell-button creation alone does not spend casting energy")
	TEST_ASSERT_EQUAL(bystander_core.energy, bystander_energy, "independent actual button creation alone does not spend casting energy")
	TEST_ASSERT_EQUAL(actor.get_equipped_item(SLOT_ID_BACK), core, "native activation preserves the original actual back slot")
	TEST_ASSERT_EQUAL(core.spells[1], button, "all native success/refusal paths preserve the original owned spell button")
	TEST_ASSERT_EQUAL(master.get_ability_by_instance(button), ability, "all native paths preserve the actual ability identity")
	TEST_ASSERT_NULL(bystander.get_active_hand(), "repeated owner activation leaves the unrelated human's hand unchanged")
	test_driver_end()
