/// Actual public spellbook choices upgrade the real spell immediately, then refund at its limit.
/datum/unit_test/round2_spellbook_immediate_speed_upgrade/Run()
	test_driver_begin()
	exercise_upgrade()
	own_turf_contents(test_floor())
	test_driver_end()

/datum/unit_test/round2_spellbook_immediate_speed_upgrade/proc/exercise_upgrade()
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, surface)
	var/obj/item/spellbook/book = allocate(/obj/item/spellbook, surface)
	var/datum/spell/targeted/projectile/magic_missile/spell = allocate(/datum/spell/targeted/projectile/magic_missile)
	TEST_ASSERT(user.put_in_active_hand(book), "Actual inventory insertion places the real book in the user's hand")
	TEST_ASSERT_EQUAL(book.loc, user, "Real inventory custody satisfies the spellbook's production proximity guard")
	TEST_ASSERT(user.add_spell(spell), "Public learning API installs the actual magic missile and its real HUD")
	TEST_ASSERT(spell in user.spell_list, "Actual spell list contains the learned spell used by public choose")
	TEST_ASSERT(spell.can_improve(Sp_SPEED), "Actual initial spell can improve speed")
	TEST_ASSERT(!spell.can_improve(Sp_POWER), "Actual concrete spell has no power upgrades, without changing its limits")
	TEST_ASSERT_EQUAL(spell.spell_levels[Sp_SPEED], 0, "Real constructor begins with no speed upgrades")
	var/datum/tgui/editor = allocate(/datum/tgui, user, book, "Spellbook")
	TEST_ASSERT_EQUAL(editor.src_object(), book, "Real UI constructor binds the actual book")
	TEST_ASSERT_EQUAL(editor.status, STATUS_INTERACTIVE, "Real window starts with its normal status")
	var/original_uses = book.uses
	var/original_charge = spell.charge_max
	TEST_ASSERT(original_uses > spell.level_max[Sp_SPEED], "Actual book budget permits all real speed levels and a final refund attempt")
	for(var/rank in 1 to spell.level_max[Sp_SPEED])
		input_submit(new /datum/input_event/ui_act(user, editor, "choose", list("id" = "magicmissile"), editor.state()))
		TEST_ASSERT_EQUAL(spell.spell_levels[Sp_SPEED], rank, "Actual public choice increases the learned spell's real speed level exactly once")
		TEST_ASSERT_EQUAL(spell.spell_levels[Sp_POWER], 0, "Speed-only choice leaves actual power level unchanged")
		TEST_ASSERT_EQUAL(book.uses, original_uses - rank, "Each actual upgrade spends exactly one book use")
		TEST_ASSERT_NULL(SSrequests.open_for(user), "Actual speed-only choice completes without opening a legacy or native prompt")
		TEST_ASSERT(spell.charge_max < original_charge && spell.charge_max >= spell.cooldown_min, "Real upgrade lowers recharge time while respecting the concrete minimum")
		TEST_ASSERT_EQUAL(spell.charge_counter, spell.charge_max, "Real upgrade clamps the already charged spell to its new recharge maximum")
		if(rank == 1)
			TEST_ASSERT_EQUAL(spell.name, "Efficient Magic Missile", "Actual first speed upgrade renames the real spell")
	TEST_ASSERT_EQUAL(spell.name, "Instant Magic Missile", "Actual fourth speed upgrade reaches the concrete final name")
	TEST_ASSERT(!spell.can_improve(), "The real spell reaches its total upgrade limit")
	var/final_uses = book.uses
	var/final_charge = spell.charge_max
	input_submit(new /datum/input_event/ui_act(user, editor, "choose", list("id" = "magicmissile"), editor.state()))
	TEST_ASSERT_EQUAL(book.uses, final_uses, "Public maxed-spell attempt refunds its temporary budget debit")
	TEST_ASSERT_EQUAL(spell.spell_levels[Sp_SPEED], spell.level_max[Sp_SPEED], "Refused extra upgrade leaves real level at its limit")
	TEST_ASSERT_EQUAL(spell.charge_max, final_charge, "Refused extra upgrade preserves real cooldown")
	TEST_ASSERT_EQUAL(spell.name, "Instant Magic Missile", "Refused extra upgrade preserves real final name")
	TEST_ASSERT_EQUAL(book.temp, "This spell cannot be improved further.", "Public maxed-spell path supplies its actual refusal feedback")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Maxed-spell refund never opens an upgrade prompt")
