/// Real outlet controls and request answers preserve range changes and late refusals.
/datum/unit_test/round2_disposal_outlet_range_request/Run()
	test_driver_begin()
	check_outlet()
	test_driver_end()

/datum/unit_test/round2_disposal_outlet_range_request/proc/check_outlet()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, run_loc_floor_bottom_left)
	var/obj/structure/disposaloutlet/outlet = allocate(/obj/structure/disposaloutlet, run_loc_floor_bottom_left)
	var/obj/item/tool/screwdriver/screwdriver = allocate(/obj/item/tool/screwdriver, run_loc_floor_bottom_left)
	var/obj/item/multitool/tool = allocate(/obj/item/multitool, run_loc_floor_bottom_left)
	var/original_range = outlet.eject_range
	TEST_ASSERT_EQUAL(outlet.interaction_tool_act(actor, tool, TOOL_MULTITOOL), ITEM_INTERACT_BLOCKING, "The actual initially closed outlet blocks configuration")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Closed initial configuration creates no native request")
	TEST_ASSERT_EQUAL(outlet.interaction_tool_act(actor, screwdriver, TOOL_SCREWDRIVER), ITEM_INTERACT_SUCCESS, "The real screwdriver control opens the outlet")
	outlet.interaction_tool_act(actor, tool, TOOL_MULTITOOL)
	var/datum/prompt/number/disposal_outlet_range/ask = SSrequests.open_for(actor)
	TEST_ASSERT(istype(ask), "The public multitool control opens the actual native range request")
	TEST_ASSERT_EQUAL(ask.owner, outlet, "The request holds the actual outlet owner")
	TEST_ASSERT_EQUAL(ask.answerer, actor, "The request uses the original explicit actor")
	TEST_ASSERT_EQUAL(ask.subject, tool, "The request retains the actual optional tool")
	TEST_ASSERT_EQUAL(ask.default, original_range, "The range request retains its actual default")
	test_answer(actor, 2.5)
	TEST_ASSERT_EQUAL(ask.outcome, REQ_ANSWERED, "A numeric reply completes the actual request")
	TEST_ASSERT_EQUAL(outlet.eject_range, 2.5, "The actual old numeric answer semantics retain a fractional range")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Accepted range closes its native request")

	outlet.interaction_tool_act(actor, tool, TOOL_MULTITOOL)
	ask = SSrequests.open_for(actor)
	TEST_ASSERT(istype(ask), "A second public action opens a new range request")
	outlet.interaction_tool_act(actor, screwdriver, TOOL_SCREWDRIVER)
	test_answer(actor, 4)
	TEST_ASSERT_EQUAL(ask.outcome, REQ_CANCELLED, "Actually closing the outlet refuses the pending numeric reply")
	TEST_ASSERT_EQUAL(ask.last_error, "closed", "The exact pure late mode requirement caused refusal")
	TEST_ASSERT_EQUAL(outlet.eject_range, 2.5, "Late mode refusal preserves the real prior ejection range")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "The refused pending request ends")

	outlet.interaction_tool_act(actor, screwdriver, TOOL_SCREWDRIVER)
	outlet.interaction_tool_act(actor, tool, TOOL_MULTITOOL)
	ask = SSrequests.open_for(actor)
	TEST_ASSERT(istype(ask), "Reopening through the real screwdriver permits another request")
	qdel(tool)
	test_answer(actor, 5)
	TEST_ASSERT_EQUAL(ask.outcome, REQ_CANCELLED, "Deleting the captured actual tool refuses its pending reply")
	TEST_ASSERT_EQUAL(outlet.eject_range, 2.5, "A deleted captured tool cannot alter the range")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "The deleted-tool request ends")

	outlet.ask_outlet_range(actor, null)
	ask = SSrequests.open_for(actor)
	TEST_ASSERT(istype(ask), "The original optional null-tool public argument remains usable")
	TEST_ASSERT_NULL(ask.subject, "A null original tool has no captured subject")
	test_answer(actor, 0)
	TEST_ASSERT_EQUAL(ask.outcome, REQ_ANSWERED, "Raw numeric zero still completes the actual optional-tool request")
	TEST_ASSERT_EQUAL(outlet.eject_range, 0, "The actual callback preserves raw numeric semantics beyond modal-only bounds")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "The optional-tool answer closes its request")
	outlet.ask_outlet_range(actor, null)
	ask = SSrequests.open_for(actor)
	TEST_ASSERT(istype(ask), "An additional optional-tool request opens before explicit cancellation")
	test_answer(actor, null, REQ_CANCELLED)
	TEST_ASSERT_EQUAL(outlet.eject_range, 0, "Closing the actual prompt preserves the range")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Explicit cancellation removes the request")
