/// Actual console UI answers refuse a current body's transfer without replacing any mind.
/datum/unit_test/round2_resleeving_console_consent_no
/datum/unit_test/round2_resleeving_console_consent_no/Run()
	test_driver_begin()
	exercise_consent()
	own_turf_contents(test_floor())
	test_driver_end()

/datum/unit_test/round2_resleeving_console_consent_no/proc/exercise_consent()
	var/mob/living/carbon/human/operator = allocate(/mob/living/carbon/human, test_floor())
	var/mob/living/carbon/human/source_body = allocate(/mob/living/carbon/human, test_floor())
	var/mob/living/carbon/human/sleeve = allocate(/mob/living/carbon/human, test_floor())
	var/datum/mind/source_mind = allocate(/datum/mind, "round2-disconnected-resleeving")
	TEST_ASSERT(transfer_mind(source_mind, source_body, "actual resleeving consent fixture"), "the real mind API links the disconnected character to its actual body")
	var/datum/transhuman/mind_record/record = allocate(/datum/transhuman/mind_record, source_mind, source_body, FALSE)
	var/obj/machinery/transhuman/resleever/pod = allocate(/obj/machinery/transhuman/resleever, test_floor())
	TEST_ASSERT(pod.put_mob(sleeve, operator), "the real resleever accepts the actual target body through its insertion API")
	var/obj/machinery/computer/transhuman/resleeving/console = allocate(/obj/machinery/computer/transhuman/resleeving, test_floor())
	TEST_ASSERT(pod in console.sleevers, "normal console initialization discovers the actual nearby unconnected resleever")
	var/datum/tgui/ui = allocate(/datum/tgui, operator, console, "ResleevingConsole")
	input_submit(new /datum/input_event/ui_act(operator, ui, "selectsleever", list("ref" = REF(pod)), ui.state()))
	input_submit(new /datum/input_event/ui_act(operator, ui, "view_m_rec", list("ref" = REF(record)), ui.state()))
	TEST_ASSERT_EQUAL(console.selected_sleever(), pod, "the public UI selects the real linked pod")
	TEST_ASSERT_EQUAL(console.current_mr, record, "the public UI loads the genuine constructed backup record")
	input_submit(new /datum/input_event/ui_act(operator, ui, "sleeve", list("mode" = 1), ui.state()))
	var/datum/prompt/choice/resleeving_consent/asked = SSrequests.open_for(source_body)
	TEST_ASSERT(istype(asked), "the actual public sleeve action asks the real living source body for consent")
	TEST_ASSERT_EQUAL(asked.owner, ui, "the original console window owns this question")
	TEST_ASSERT_EQUAL(asked.answerer, source_body, "the current mind body answers rather than the console operator")
	TEST_ASSERT_NULL(SSrequests.open_for(operator), "the operator cannot supply the other body's consent")
	TEST_ASSERT_EQUAL(asked.choices[1], "No", "the actual question retains original no-first ordering")
	test_answer(source_body, "No")
	TEST_ASSERT_NULL(SSrequests.open_for(source_body), "a real No retires the transfer question")
	TEST_ASSERT_NULL(console.current_mr, "the unchanged production refusal tail clears its selected record")
	TEST_ASSERT_EQUAL(source_mind.current, source_body, "declining leaves the backed-up mind in its actual current body")
	TEST_ASSERT_EQUAL(source_body.mind, source_mind, "the actual original body retains its mind")
	TEST_ASSERT_NULL(sleeve.mind, "the target body receives no mind on No")
	TEST_ASSERT_EQUAL(pod.get_occupant(), sleeve, "declining preserves the real occupied pod")
