// Real public-click upload routing, law state, and unrelated-item fallback.
/datum/unit_test/dq_hc_computers/round2_borg_module_click
/datum/unit_test/dq_hc_computers/round2_borg_module_click/run_gate()
	var/obj/machinery/computer/borgupload/C = hc_console(/obj/machinery/computer/borgupload)
	var/mob/living/carbon/human/H = hc_actor()
	var/mob/living/silicon/robot/robot = allocate(/mob/living/silicon/robot, hc_side())
	TEST_ASSERT(!robot.connected_ai && !robot.emagged && robot.stat != DEAD, "the real isolated cyborg accepts independent law uploads")
	rel_set(C, nameof(C.current), robot)
	verify_module_click(C, H, robot)

/datum/unit_test/dq_hc_computers/round2_ai_module_click
/datum/unit_test/dq_hc_computers/round2_ai_module_click/run_gate()
	var/obj/machinery/computer/aiupload/C = hc_console(/obj/machinery/computer/aiupload)
	var/mob/living/carbon/human/H = hc_actor()
	var/mob/living/silicon/ai/AI = allocate(/mob/living/silicon/ai, hc_side(), null, null, null, TRUE)
	TEST_ASSERT(!AI.control_disabled && AI.see_in_dark && AI.stat != DEAD, "the actual safe-spawned AI has a usable upload signal")
	rel_set(C, nameof(C.current), AI)
	verify_module_click(C, H, AI)

/datum/unit_test/dq_hc_computers/proc/verify_module_click(obj/machinery/computer/C, mob/living/carbon/human/H, mob/living/silicon/recipient)
	set_global(nameof(GLOB.lawchanges), GLOB.lawchanges.Copy())
	var/obj/item/aiModule/safeguard/module = allocate(/obj/item/aiModule/safeguard, hc_side())
	module.set_targetName("Round2 public upload recipient")
	TEST_ASSERT(H.put_in_active_hand(module), "the actual actor holds the original configured law module")
	TEST_ASSERT(recipient.laws, "the actual recipient has its production law set")
	var/datum/ai_law/previous = recipient.laws.supplied_laws.len >= 9 ? recipient.laws.supplied_laws[9] : null
	TEST_ASSERT(!previous || !findtext(previous.law, "Round2 public upload recipient"), "the production law state does not already contain this upload")
	var/datum/op_result/result = test_click(H, C, module)
	TEST_ASSERT_EQUAL(result?.key, "install_module", "the real held-module click chooses installation ahead of the inherited generic item touch")
	TEST_ASSERT_EQUAL(result?.outcome, ACT_COMMITTED, "the real public upload commits")
	TEST_ASSERT(recipient.laws.supplied_laws.len >= 9, "the actual supplied-law slot is created")
	var/datum/ai_law/installed = recipient.laws.supplied_laws[9]
	TEST_ASSERT(installed, "the upload created a real supplied-law datum")
	TEST_ASSERT_EQUAL(installed.law, "Safeguard Round2 public upload recipient. Anyone threatening or attempting to harm Round2 public upload recipient is no longer to be considered a crew member, and is a threat which must be neutralized.", "the public click changes the real recipient's exact production law")
	TEST_ASSERT_EQUAL(H.get_active_hand(), module, "the public upload preserves its reusable original source module")
	TEST_ASSERT_NULL(SSrequests.open_for(H), "installation did not route into an unrelated selection prompt")
	TEST_ASSERT(H.unEquip(module), "the actor releases its reusable module before the unrelated-item probe")
	var/obj/item/pen/pen = allocate(/obj/item/pen, hc_side())
	TEST_ASSERT(H.put_in_active_hand(pen), "the actor holds an actual unrelated non-module item")
	var/datum/op_result/fallback = test_click(H, C, pen)
	TEST_ASSERT_EQUAL(fallback?.key, "use_item", "a real unrelated item retains the inherited computer fallback")
	TEST_ASSERT_EQUAL(fallback?.outcome, ACT_COMMITTED, "the inherited unrelated-item fallback remains handled")
	TEST_ASSERT_EQUAL(recipient.laws.supplied_laws[9], installed, "the unrelated item preserves the exact original uploaded law datum")
	TEST_ASSERT_EQUAL(H.get_active_hand(), pen, "the inherited fallback does not consume the unrelated original item")
