/// Actual drug question and answer delivery; no reagent metabolism, timer or connected UI claim.
/datum/unit_test/round2_gender_change_drug_request/Run()
	test_driver_begin()
	exercise_question()
	test_driver_end()

/datum/unit_test/round2_gender_change_drug_request/proc/exercise_question()
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, surface)
	var/mob/living/carbon/human/control = allocate(/mob/living/carbon/human, surface)
	actor.enable_godmode()
	control.enable_godmode()
	actor.change_gender(MALE)
	actor.change_gender_identity(MALE)
	control.change_gender(MALE)
	control.change_gender_identity(MALE)
	actor.gender_change_cooldown = 1
	change_drug_ask(actor, FEMALE)
	var/datum/prompt/yes_no/gender_change_drug/request = SSrequests.open_for(actor)
	TEST_ASSERT(istype(request), "Actual drug helper opens its native confirmation")
	TEST_ASSERT_EQUAL(request.owner, actor, "The original human owns the question")
	TEST_ASSERT_EQUAL(request.answerer, actor, "The original human answers the question")
	TEST_ASSERT_EQUAL(request.timeout, REQUEST_DEFAULT_TIMEOUT, "Drug confirmation retains no expiry (a request given no timeout gets the default, framework_gaps.md E2)")
	TEST_ASSERT_EQUAL(actor.gender_change_cooldown, 0, "Public helper resets the real cooldown before asking")
	test_answer(actor, FALSE)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "No closes the actual question")
	TEST_ASSERT_EQUAL(actor.gender, MALE, "No preserves body gender")
	TEST_ASSERT_EQUAL(actor.identifying_gender, MALE, "No preserves identity gender")
	change_drug_ask(actor, FEMALE)
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/yes_no/gender_change_drug), "A new public call opens another question")
	test_answer(actor, null, REQ_CANCELLED)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Closing ends the actual question")
	TEST_ASSERT_EQUAL(actor.gender, MALE, "Closing preserves body gender")
	TEST_ASSERT_EQUAL(actor.identifying_gender, MALE, "Closing preserves identity gender")
	change_drug_ask(actor, FEMALE)
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/yes_no/gender_change_drug), "Final public call opens a real question")
	test_answer(actor, TRUE)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Yes completes the actual question")
	TEST_ASSERT_EQUAL(actor.gender, FEMALE, "Yes changes real body gender through the production callback")
	TEST_ASSERT_EQUAL(actor.identifying_gender, FEMALE, "Yes changes real identity gender through the production callback")
	TEST_ASSERT_EQUAL(control.gender, MALE, "The control human's body gender is unchanged")
	TEST_ASSERT_EQUAL(control.identifying_gender, MALE, "The control human's identity gender is unchanged")
