/// Real player inputs and requests exercise the construction workflows.
/datum/unit_test/round3_construction_asks
	parent_type = /datum/unit_test/dq_hc_struct
	abstract_type = /datum/unit_test/round3_construction_asks

/datum/unit_test/round3_construction_asks/board
/datum/unit_test/round3_construction_asks/board/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/item/circuitboard/airlock_cycling/B = allocate(/obj/item/circuitboard/airlock_cycling, H.loc)
	var/obj/item/multitool/tool = allocate(/obj/item/multitool, H.loc)
	TEST_ASSERT(H.put_in_active_hand(tool), "The actor holds the actual multitool")
	test_click(H, B, tool)
	TEST_ASSERT(SSrequests.open_for(H), "The real tool input asks for a board type")
	H.status_set(STAT_SLEEPING, 2)
	test_answer(H, "Sensor")
	TEST_ASSERT_EQUAL(B.build_path, /obj/machinery/access_button, "Sleeping before answering preserves the board")
	H.status_end(STAT_SLEEPING)
	test_time(1 SECOND)
	test_click(H, B, tool)
	test_answer(H, "Controller - Advanced")
	TEST_ASSERT_EQUAL(B.build_path, /obj/machinery/embedded_controller/radio/airlock/advanced_airlock_controller, "A real fresh answer reconfigures the board")

/datum/unit_test/round3_construction_asks/air_control
/datum/unit_test/round3_construction_asks/air_control/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/machinery/computer/general_air_control/C = mach(/obj/machinery/computer/general_air_control, tile(3, 2))
	var/obj/item/multitool/tool = allocate(/obj/item/multitool, H.loc)
	TEST_ASSERT(H.put_in_active_hand(tool), "The actor holds the configuration tool")
	test_click(H, C, tool)
	test_answer(H, "Frequency")
	var/datum/prompt/number/R = SSrequests.open_for(H)
	TEST_ASSERT(istype(R), "The frequency branch asks a numeric question")
	test_answer(H, 1437)
	TEST_ASSERT_EQUAL(C.frequency, sanitize_frequency(1437, RADIO_LOW_FREQ, RADIO_HIGH_FREQ), "The answer applies the original frequency sanitizer")
	TEST_ASSERT_NULL(SSrequests.open_for(H), "Frequency skips every unrelated sensor and port question")
	LAZYSET(C.sensors, "round3-tag", "Round3 sensor")
	test_time(1 SECOND)
	test_click(H, C, tool)
	test_answer(H, "Sensors")
	test_answer(H, "Remove")
	test_answer(H, "Round3 sensor")
	TEST_ASSERT(SSrequests.open_for(H), "Sensor removal asks for confirmation")
	TEST_ASSERT(LAZYACCESS(C.sensors, "round3-tag"), "Selecting a sensor does not remove it before consent")
	test_answer(H, FALSE)
	TEST_ASSERT(LAZYACCESS(C.sensors, "round3-tag"), "A no answer preserves the real sensor")
	test_time(1 SECOND)
	test_click(H, C, tool)
	test_answer(H, "Sensors")
	test_answer(H, "Remove")
	test_answer(H, "Round3 sensor")
	test_answer(H, TRUE)
	TEST_ASSERT_NULL(LAZYACCESS(C.sensors, "round3-tag"), "A confirmed real workflow removes exactly the chosen tag")

/datum/unit_test/round3_construction_asks/frame
/datum/unit_test/round3_construction_asks/frame/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/item/frame/F = allocate(/obj/item/frame, H.loc)
	TEST_ASSERT(H.put_in_active_hand(F), "The actor carries the actual frame")
	test_click(H, F, F)
	var/datum/prompt/choice/R = SSrequests.open_for(H)
	TEST_ASSERT(istype(R) && length(R.choices), "The floor workflow asks for an actual registered frame type")
	var/selected = R.choices[1]
	F.build_machine_type = /obj/structure/frame
	test_answer(H, selected)
	TEST_ASSERT(!QDELETED(F), "An intervening type assignment invalidates the pending construction")
	TEST_ASSERT_EQUAL(H.get_active_hand(), F, "A refused build leaves its frame carried")

/datum/unit_test/round3_construction_asks/cutout
/datum/unit_test/round3_construction_asks/cutout/run_gate()
	var/mob/living/carbon/human/H = person()
	var/obj/structure/barricade/cutout/C = allocate(/obj/structure/barricade/cutout, tile(3, 2))
	var/obj/item/floor_painter/tool = allocate(/obj/item/floor_painter, H.loc)
	TEST_ASSERT(H.put_in_active_hand(tool), "The actor holds the actual painter")
	test_click(H, C, tool)
	test_answer(H, "clown")
	TEST_ASSERT(!QDELETED(C), "Answering begins the timed workflow without replacing the cutout")
	test_time(11 SECONDS)
	TEST_ASSERT(QDELETED(C), "Finishing the real timed workflow replaces its cutout")
	var/obj/structure/barricade/cutout/clown/repainted = locate() in tile(3, 2)
	TEST_ASSERT(istype(repainted), "The chosen original cutout type is constructed")
