/// Actual hotspot constructor replacement of an existing owned fire.
/datum/unit_test/round2_hotspot_replacement_retirement/Run()
	test_driver_begin()
	exercise_replacement()
	test_driver_end()

/datum/unit_test/round2_hotspot_replacement_retirement/proc/exercise_replacement()
	var/turf/open/T = test_floor()
	var/turf/open/control_turf = get_step(T, EAST)
	TEST_ASSERT(T && control_turf && T != control_turf && T.air && control_turf.air, "real distinct test-block floor turfs provide actual native air")
	TEST_ASSERT(!T.active_hotspot && !control_turf.active_hotspot, "both real test turfs begin without a fire")
	for(var/turf/open/floor in list(T, control_turf))
		floor.air.adjust_gas(/datum/gas/plasma, 20)
		floor.air.adjust_gas(/datum/gas/oxygen, 50)
		floor.air.set_temperature(PLASMA_MINIMUM_BURN_TEMPERATURE + 300)
	var/obj/effect/hotspot/original = allocate(/obj/effect/hotspot, T, CELL_VOLUME, PLASMA_MINIMUM_BURN_TEMPERATURE + 300)
	var/obj/effect/hotspot/control = allocate(/obj/effect/hotspot, control_turf, CELL_VOLUME, PLASMA_MINIMUM_BURN_TEMPERATURE + 300)
	TEST_ASSERT(!QDELETED(original) && !QDELETED(control), "actual constructors create two live original fires")
	TEST_ASSERT_EQUAL(T.active_hotspot, original, "first constructor adopts its exact original turf fire")
	TEST_ASSERT_EQUAL(owner_of(original), T, "original fire is actually owned by its turf")
	TEST_ASSERT_EQUAL(control_turf.active_hotspot, control, "independent turf adopts its exact original fire")
	TEST_ASSERT_EQUAL(owner_of(control), control_turf, "independent fire belongs to its own actual turf")
	set_var(original, nameof(original.just_spawned), FALSE)
	TEST_ASSERT(!original.just_spawned, "existing fire has the actual replacement-eligible non-new state")
	var/obj/effect/hotspot/replacement = allocate(/obj/effect/hotspot, T, CELL_VOLUME, PLASMA_MINIMUM_BURN_TEMPERATURE + 300)
	TEST_ASSERT(replacement != original && !QDELETED(replacement), "actual replacement constructor produces a distinct live fire")
	TEST_ASSERT(QDELETED(original), "constructor exposure retires the exact old owned fire")
	TEST_ASSERT_EQUAL(T.active_hotspot, replacement, "actual exposure adopts the exact replacement into the turf slot")
	TEST_ASSERT_EQUAL(owner_of(replacement), T, "the exact replacement retains real turf ownership")
	TEST_ASSERT(!QDELETED(control), "replacement preserves the independent original fire")
	TEST_ASSERT_EQUAL(control_turf.active_hotspot, control, "independent exact active-fire identity remains unchanged")
	TEST_ASSERT_EQUAL(owner_of(control), control_turf, "independent exact fire custody remains unchanged")
