/// The actual construct spell API cleans up its fresh item when both manipulators are occupied.
/datum/unit_test/round2_construct_blocked_spell_cleanup/Run()
	test_driver_begin()
	exercise_construct()
	test_driver_end()

/datum/unit_test/round2_construct_blocked_spell_cleanup/proc/exercise_construct()
	var/turf/T = test_floor()
	var/mob/living/simple_mob/construct/blocked = allocate(/mob/living/simple_mob/construct, T)
	var/mob/living/simple_mob/construct/control = allocate(/mob/living/simple_mob/construct, T)
	var/obj/item/paper/left = allocate(/obj/item/paper, T)
	var/obj/item/paper/right = allocate(/obj/item/paper, T)
	TEST_ASSERT(blocked.put_in_active_hand(left), "first real paper occupies a construct manipulator")
	TEST_ASSERT(blocked.put_in_inactive_hand(right), "second real paper occupies the other manipulator")
	TEST_ASSERT(blocked.get_equipped_item(SLOT_ID_HAND_L) && blocked.get_equipped_item(SLOT_ID_HAND_R), "both actual hand slots are occupied")
	TEST_ASSERT_EQUAL(blocked.place_spell_in_hand(/obj/item/spell/construct/projectile/inverted_beam), 0, "actual full-hands path refuses with its original return value")
	for(var/obj/item/spell/construct/S in blocked.contents)
		TEST_ASSERT(QDELETED(S), "refusal leaves no live newly allocated construct spell in the original mob")
	TEST_ASSERT(!QDELETED(left) && left.loc == blocked, "refusal retains the exact first hand item")
	TEST_ASSERT(!QDELETED(right) && right.loc == blocked, "refusal retains the exact second hand item")
	TEST_ASSERT_EQUAL(control.place_spell_in_hand(/obj/item/spell/construct/projectile/inverted_beam), 1, "independent real free-hand control succeeds")
	var/obj/item/spell/construct/product = control.get_equipped_item(SLOT_ID_HAND_L)
	if(!product)
		product = control.get_equipped_item(SLOT_ID_HAND_R)
	TEST_ASSERT(istype(product, /obj/item/spell/construct/projectile/inverted_beam), "actual successful API produces the concrete original projectile spell")
	TEST_ASSERT(!QDELETED(product) && product.loc == control, "successful original product remains alive in its real hand")
	TEST_ASSERT_EQUAL(product.owner_ref(), control, "successful spell retains its actual construct owner")
	own(product)
	TEST_ASSERT(!QDELETED(left) && !QDELETED(right), "successful independent control leaves the blocked original items alive")
