/// Real public selector, explicit cancellation and late state refusal; no timed detachment claim.
/datum/unit_test/round2_modular_limb_native_refusal/Run()
	test_driver_begin()
	exercise_refusal()
	test_driver_end()

/datum/unit_test/round2_modular_limb_native_refusal/proc/exercise_refusal()
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, surface)
	var/mob/living/carbon/human/control = allocate(/mob/living/carbon/human, surface)
	user.enable_godmode()
	control.enable_godmode()
	var/obj/item/organ/external/arm = user.get_organ(BP_L_ARM)
	var/obj/item/organ/external/control_arm = control.get_organ(BP_L_ARM)
	TEST_ASSERT(istype(arm) && istype(control_arm), "Actual human constructors supply both arms")
	TEST_ASSERT(GLOB.basic_robolimb && GLOB.all_robolimbs[GLOB.basic_robolimb.company], "Real startup robolimb registry supplies its basic manufacturer")
	arm.robotize(GLOB.basic_robolimb.company)
	var/atom/original_location = arm.loc
	COOLDOWN_START(user, last_special, -1 SECONDS)
	TEST_ASSERT(arm.is_robotic(), "Public robotize makes the actual attached arm robotic")
	TEST_ASSERT(original_location && !QDELETED(original_location), "The real body tree supplies the attached limb's location")
	TEST_ASSERT(arm in user.get_modular_limbs(return_first_found = FALSE, validate_proc = TYPE_PROC_REF(/obj/item/organ/external, can_remove_modular_limb)), "Real manufacturer/body rules offer this exact arm")
	TEST_ASSERT(COOLDOWN_FINISHED(user, last_special), "The real actor's configured cooldown is already expired")
	TEST_ASSERT(!user.incapacitated() && !user.restrained(), "The actual actor is capable before the question opens")
	user.detach_limb_verb()
	var/datum/prompt/choice/detach_limb/first = SSrequests.open_for(user)
	TEST_ASSERT(istype(first), "Actual public removal entry opens the native selector")
	TEST_ASSERT(arm in first.choices, "Actual native options retain the exact attached arm")
	test_answer(user, null, REQ_CANCELLED)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Explicit close retires the real request")
	TEST_ASSERT_EQUAL(user.get_organ(BP_L_ARM), arm, "Cancellation retains the exact attached arm")
	TEST_ASSERT_EQUAL(arm.owner, user, "Cancellation preserves actual body ownership")
	TEST_ASSERT_EQUAL(arm.loc, original_location, "Cancellation preserves the actual body-tree location")
	user.detach_limb_verb()
	var/datum/prompt/choice/detach_limb/late = SSrequests.open_for(user)
	TEST_ASSERT(istype(late), "Public entry can open another real native selector")
	var/obj/item/handcuffs/cuffs = allocate(/obj/item/handcuffs, surface)
	TEST_ASSERT(user.equip_to_slot(cuffs, SLOT_ID_HANDCUFFED), "Real equipment entry attaches actual handcuffs while the choice waits")
	TEST_ASSERT(user.restrained(), "Actual equipped handcuffs make the actor restrained")
	test_answer(user, arm)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Late refusal closes the real request")
	TEST_ASSERT_EQUAL(late.last_error, "detach_limb_state", "Native pure state requirement rejects the accepted exact limb")
	TEST_ASSERT_EQUAL(user.get_organ(BP_L_ARM), arm, "Late refused answer retains the exact attached arm")
	TEST_ASSERT_EQUAL(arm.owner, user, "Late refusal preserves real body ownership")
	TEST_ASSERT_EQUAL(arm.loc, original_location, "Late refusal preserves the actual body-tree location")
	TEST_ASSERT_EQUAL(control.get_organ(BP_L_ARM), control_arm, "Independent human keeps its exact arm")
	TEST_ASSERT(!control_arm.is_robotic(), "Independent arm remains biological")
