/// Actual account effects only; no UI delivery or permission coverage.
/datum/unit_test/round2_account_funds_effect/Run()
	set_global(nameof(GLOB.num_financial_terminals), GLOB.num_financial_terminals)
	if(SSsupply)
		set_var(SSsupply, nameof(SSsupply.currency_created), SSsupply.currency_created)
		set_var(SSsupply, nameof(SSsupply.currency_destroyed), SSsupply.currency_destroyed)
		set_var(SSsupply, nameof(SSsupply.currency_sources), SSsupply.currency_sources.Copy())
		set_var(SSsupply, nameof(SSsupply.currency_sinks), SSsupply.currency_sinks.Copy())
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, surface)
	user.enable_godmode()
	var/obj/machinery/account_database/terminal = allocate(/obj/machinery/account_database, surface)
	var/datum/money_account/account = allocate(/datum/money_account)
	rel_set(terminal, nameof(terminal.detailed_account_view), account)
	TEST_ASSERT_EQUAL(terminal.detailed_account_view(), account, "terminal selects the exact real borrowed account")
	account.money = terminal.fund_cap - 2.5
	TEST_ASSERT(terminal.apply_ui_add_funds(user, 20), "real positive add effect has its original truthy result")
	TEST_ASSERT_EQUAL(account.money, terminal.fund_cap, "positive add is capped at the actual terminal fund limit")
	TEST_ASSERT_EQUAL(length(account.transaction_log), 1, "capped add records exactly one real transaction")
	var/datum/transaction/credit = account.transaction_log[1]
	TEST_ASSERT_EQUAL(credit.amount, "2.5", "transaction records only the exact fractional credited remainder")
	TEST_ASSERT_EQUAL(credit.target_name, user.real_name, "transaction records the actual supplied user name")
	TEST_ASSERT_EQUAL(credit.source_terminal, terminal.machine_id, "transaction records the actual initialized machine id")
	terminal.apply_ui_add_funds(user, 0)
	terminal.apply_ui_add_funds(user, -5)
	terminal.apply_ui_add_funds(user, 20)
	terminal.apply_ui_remove_funds(user, -5)
	TEST_ASSERT_EQUAL(account.money, terminal.fund_cap, "zero, negative and over-cap additions do not change the balance")
	TEST_ASSERT_EQUAL(length(account.transaction_log), 1, "no-op amounts create no transactions")
	terminal.apply_ui_remove_funds(user, 2.5)
	TEST_ASSERT_EQUAL(account.money, terminal.fund_cap - 2.5, "real remove preserves fractional amounts")
	TEST_ASSERT_EQUAL(length(account.transaction_log), 2, "fractional debit records one transaction")
	var/datum/transaction/debit = account.transaction_log[2]
	TEST_ASSERT_EQUAL(debit.amount, "(2.5)", "debit transaction records the exact fractional amount")
	terminal.apply_ui_remove_funds(user, terminal.fund_cap + 10)
	TEST_ASSERT_EQUAL(account.money, 0, "overdraw is capped at the actual available account money")
	TEST_ASSERT_EQUAL(length(account.transaction_log), 3, "overdraw records exactly one capped debit")
