/// Real native sprayer requests configure its original state without painting unrelated surfaces.
/datum/unit_test/round2_floor_painter_config_native
	parent_type = /datum/unit_test/dq_p2_engine

/datum/unit_test/round2_floor_painter_config_native/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/item/floor_painter/painter = allocate(/obj/item/floor_painter, T)
	TEST_ASSERT(user.put_in_active_hand(painter), "actual actor holds original sprayer")
	test_click(user, painter, painter)
	test_time(1 SECOND)
	var/datum/prompt/choice/R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "actual self-input opens configuration choice")
	TEST_ASSERT_EQUAL(R.title, "Modify What?", "native initial choice preserves title")
	test_answer(user, "Decal")
	test_time(1 SECOND)
	R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "actual Decal choice opens decal request")
	TEST_ASSERT_EQUAL(R.title, "Decal Choice", "actual choice skips direction/color requests")
	test_answer(user, "quarter-turf")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(painter.decal, "quarter-turf", "actual second answer updates original decal setting")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "decal workflow has no unrelated follow-up")
	test_menu(user, painter, "direction")
	test_time(1 SECOND)
	R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "actual native direction menu opens request")
	test_answer(user, "precise")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(painter.paint_dir, "precise", "actual zero-valued precise direction remains a valid choice")
	test_menu(user, painter, "colour")
	test_time(1 SECOND)
	var/datum/prompt/color/C = SSrequests.open_for(user)
	TEST_ASSERT(istype(C), "actual native color menu opens color request")
	TEST_ASSERT_EQUAL(C.title, painter.name, "real color prompt retains current sprayer name")
	TEST_ASSERT_EQUAL(C.default, painter.paint_colour, "real color prompt starts with current source color")
	test_answer(user, "#123456")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(painter.paint_colour, "#123456", "actual native color answer updates exact original sprayer")
	test_click(user, painter, painter)
	test_time(1 SECOND)
	R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "actual configured sprayer opens initial choice before cancel")
	test_answer(user, "Cancel")
	test_time(1 SECOND)
	TEST_ASSERT_NULL(SSrequests.open_for(user), "real Cancel choice opens no follow-up")
	TEST_ASSERT_EQUAL(painter.decal, "quarter-turf", "cancel preserves actual decal setting")
	TEST_ASSERT_EQUAL(painter.paint_dir, "precise", "cancel preserves actual direction setting")
	TEST_ASSERT_EQUAL(painter.paint_colour, "#123456", "cancel preserves actual color setting")
	TEST_ASSERT_EQUAL(user.get_active_hand(), painter, "all actual requests retain original sprayer hand")
