/// Production pen/body entry and native request delivery, not connected UI presentation.
/datum/unit_test/round2_body_writing_native/Run()
	test_driver_begin()
	set_global("timed_actions_instant", FALSE)
	exercise_body_writing()
	test_driver_end()

/datum/unit_test/round2_body_writing_native/proc/exercise_body_writing()
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, surface)
	var/mob/living/carbon/human/canvas = allocate(/mob/living/carbon/human, surface)
	var/mob/living/carbon/human/control = allocate(/mob/living/carbon/human, surface)
	actor.enable_godmode()
	canvas.enable_godmode()
	control.enable_godmode()
	dq_give_zone_sel(actor)
	own(actor.zone_sel)
	TEST_ASSERT(istype(actor.zone_sel, /atom/movable/screen/zone_sel), "Actual HUD constructs the targeting selector")
	TEST_ASSERT_EQUAL(actor.zone_sel.selecting, BP_TORSO, "Actual selector starts on the torso")
	var/obj/item/organ/external/limb = canvas.get_organ(BP_TORSO)
	TEST_ASSERT(limb && limb.owner == canvas && !limb.is_stump(), "Actual canvas has its original writable torso")
	var/obj/item/pen/pen = allocate(/obj/item/pen, surface)
	TEST_ASSERT(actor.put_in_active_hand(pen), "Actual author holds the original pen")
	TEST_ASSERT(canvas.vore_attackby(pen, actor, I_HELP), "Production pen/body entry handles helpful writing")
	var/datum/prompt/text/body_writing/request = SSrequests.open_for(actor)
	TEST_ASSERT(istype(request), "Production entry opens the actual native body-writing request")
	TEST_ASSERT_EQUAL(request.owner, canvas, "Request retains the original canvas")
	TEST_ASSERT_EQUAL(request.subject, limb, "Request retains the actual selected torso")
	test_answer(actor, "native body note")
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Accepted native answer closes the request")
	TEST_ASSERT_NULL(LAZYACCESS(canvas.body_writing, limb.organ_tag), "Existing timed task does not write before its duration")
	test_time(3.1 SECONDS)
	TEST_ASSERT_EQUAL(LAZYACCESS(canvas.body_writing, limb.organ_tag), "native body note", "Real timed completion records writing under the original organ tag")
	TEST_ASSERT_NULL(LAZYACCESS(control.body_writing, limb.organ_tag), "Independent actual human remains unwritten")
	TEST_ASSERT_EQUAL(actor.get_active_hand(), pen, "Actual writing keeps the original held pen")
	TEST_ASSERT(canvas.vore_attackby(pen, actor, I_HELP), "A second production entry opens replacement writing")
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/text/body_writing), "Replacement request is genuinely open")
	test_answer(actor, null, REQ_CANCELLED)
	test_time(3.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Explicit cancel leaves no native request")
	TEST_ASSERT_EQUAL(LAZYACCESS(canvas.body_writing, limb.organ_tag), "native body note", "Cancelled replacement leaves actual completed writing unchanged")
	TEST_ASSERT_NULL(LAZYACCESS(control.body_writing, limb.organ_tag), "Cancellation leaves independent human unchanged")
