/// Ordinary settings effects only; no administrative UI or request acceptance coverage.
/datum/unit_test/round2_mob_spawner_settings_effect/Run()
	var/datum/eventkit/mob_spawner/spawner = allocate(/datum/eventkit/mob_spawner)
	var/datum/eventkit/mob_spawner/control = allocate(/datum/eventkit/mob_spawner)
	TEST_ASSERT_NULL(spawner.path, "actual constructor has no selected mob path")
	spawner.new_path = FALSE // Existing plain UI-data flag: exercise its real rearm effect.
	spawner.apply_spawner_setting("select_path", /mob/living/carbon/human)
	TEST_ASSERT_EQUAL(spawner.path, /mob/living/carbon/human, "accepted type selects the exact existing concrete mob path")
	TEST_ASSERT(spawner.new_path, "selecting a path rearms actual UI-data initialization")
	spawner.apply_spawner_setting("set_faction", "unit faction")
	TEST_ASSERT_EQUAL(spawner.faction, "unit faction", "accepted faction updates the real model")
	spawner.apply_spawner_setting("set_faction", "")
	TEST_ASSERT_EQUAL(spawner.faction, "", "accepted blank overwrites the existing faction")
	spawner.apply_spawner_setting("set_intent", I_HURT)
	TEST_ASSERT_EQUAL(spawner.intent, I_HURT, "accepted harmful intent updates the real model")
	spawner.apply_spawner_setting("set_intent", I_HELP)
	TEST_ASSERT_EQUAL(spawner.intent, I_HELP, "accepted helpful intent updates the same model")
	TEST_ASSERT_EQUAL(spawner.path, /mob/living/carbon/human, "other settings preserve the exact selected path")
	TEST_ASSERT_NULL(control.path, "independent real constructor retains its original path")
	TEST_ASSERT_EQUAL(control.faction, "", "independent constructor retains its original faction")
	TEST_ASSERT_EQUAL(control.intent, "", "independent constructor retains its original intent")
