// The notes workflow commits only after its last answer, and keeps the record
// selected when the editor opened. These inputs use the actual declared UI op.
/datum/unit_test/dq_hc_computers/round3_notes_confirmation
/datum/unit_test/dq_hc_computers/round3_notes_confirmation/run_gate()
	var/obj/machinery/computer/med_data/C = hc_console(/obj/machinery/computer/med_data)
	var/mob/living/carbon/human/doctor = hc_records_user(list(ACCESS_MEDICAL))
	var/datum/data/record/general = hc_general_record("Notes Patient", "N0TES")
	hc_records_login(doctor, C)
	press(doctor, C, "d_rec", list("d_rec" = "[REF(general)]"))
	press(doctor, C, "new")
	var/datum/data/record/record = C.active2()
	TEST_ASSERT_NOTNULL(record, "the editor has a medical record")
	LAZYADD(hc_records, record)
	record.fields["notes"] = "Keep this note."
	press(doctor, C, "edit_notes")
	p2cl_answer(doctor, "")
	test_time(1)
	TEST_ASSERT(p2cl_has_question(doctor), "clearing notes opens a second confirmation")
	TEST_ASSERT_EQUAL(record.fields["notes"], "Keep this note.", "nothing changes before confirmation")
	p2cl_answer(doctor, FALSE)
	test_time(1)
	TEST_ASSERT_EQUAL(record.fields["notes"], "Keep this note.", "declining keeps the note")
	press(doctor, C, "edit_notes")
	p2cl_answer(doctor, "")
	test_time(1)
	p2cl_answer(doctor, TRUE)
	test_time(1)
	TEST_ASSERT_EQUAL(record.fields["notes"], "", "confirming clears the selected record")
	press(doctor, C, "edit_notes")
	p2cl_answer(doctor, "Replacement note.")
	test_time(1)
	TEST_ASSERT_EQUAL(record.fields["notes"], "Replacement note.", "nonempty text commits without a second question")
	TEST_ASSERT(!p2cl_has_question(doctor), "the nonempty edit has no extra confirmation")
	press(doctor, C, "edit_notes")
	press(doctor, C, "logout")
	p2cl_answer(doctor, "Must not commit.")
	test_time(1)
	TEST_ASSERT_EQUAL(record.fields["notes"], "Replacement note.", "losing authentication while waiting cannot change notes")

/datum/unit_test/dq_hc_struct/round3_newscaster_draft_questions
/datum/unit_test/dq_hc_struct/round3_newscaster_draft_questions/run_gate()
	var/mob/living/carbon/human/actor = person()
	var/obj/machinery/newscaster/caster = mach(/obj/machinery/newscaster, tile(3, 2))
	var/old_body = caster.msg
	press(actor, caster, "set_new_message")
	TEST_ASSERT(asked(actor), "the story op opens its question")
	TEST_ASSERT_EQUAL(caster.msg, old_body, "opening the question does not edit the draft")
	hci_answer(actor, "A fresh draft.")
	settle()
	TEST_ASSERT_EQUAL(caster.msg, "A fresh draft.", "the accepted story becomes the draft")
	press(actor, caster, "set_new_title")
	hci_answer(actor, "Fresh headline")
	settle()
	TEST_ASSERT_EQUAL(caster.title, "Fresh headline", "the separate title workflow commits its own answer")
