/// Exercise only accepted search-setting effects, without claiming UI/request authorization.
/datum/unit_test/round2_library_search_effects/Run()
	var/turf/T = test_floor()
	var/obj/machinery/librarypubliccomp/computer = allocate(/obj/machinery/librarypubliccomp, T)
	var/obj/machinery/librarypubliccomp/control = allocate(/obj/machinery/librarypubliccomp, T)
	var/control_title = control.title
	var/control_author = control.author
	var/control_category = control.category
	computer.apply_search_answer("settitle", "Prior title")
	computer.apply_search_answer("setauthor", "Prior author")
	computer.apply_search_answer("setcategory", "Fiction")
	TEST_ASSERT_EQUAL(computer.title, "Prior title", "actual effect sets the accepted title")
	TEST_ASSERT_EQUAL(computer.author, "Prior author", "actual effect sets the accepted author")
	TEST_ASSERT_EQUAL(computer.category, "Fiction", "actual effect sets the accepted category")
	computer.apply_search_answer("settitle", "")
	computer.apply_search_answer("setauthor", "")
	TEST_ASSERT_EQUAL(computer.title, "Prior title", "accepted blank title preserves the original title")
	TEST_ASSERT_EQUAL(computer.author, "Prior author", "accepted blank author preserves the original author")
	computer.apply_search_answer("settitle", "Replacement title")
	computer.apply_search_answer("setauthor", "Replacement author")
	computer.apply_search_answer("setcategory", "Reference")
	TEST_ASSERT_EQUAL(computer.title, "Replacement title", "later accepted title replaces the exact original value")
	TEST_ASSERT_EQUAL(computer.author, "Replacement author", "later accepted author replaces the exact original value")
	TEST_ASSERT_EQUAL(computer.category, "Reference", "later accepted category replaces the original category")
	computer.apply_search_answer("setcategory", "")
	TEST_ASSERT_EQUAL(computer.category, "Any", "empty category retains the original Any fallback effect")
	TEST_ASSERT_EQUAL(control.title, control_title, "independent constructor title remains unchanged")
	TEST_ASSERT_EQUAL(control.author, control_author, "independent constructor author remains unchanged")
	TEST_ASSERT_EQUAL(control.category, control_category, "independent constructor category remains unchanged")
	TEST_ASSERT(!QDELETED(computer) && computer.loc == T, "setting effects preserve the exact original real computer")
