/// Ejection must preserve each crystal while releasing its console ownership.
/datum/unit_test/round2_telescience_crystal_ejection/Run()
	var/turf/T = test_floor()
	var/obj/machinery/computer/telescience/console = allocate(/obj/machinery/computer/telescience, T)
	TEST_ASSERT_NULL(console.crystals, "An unseeded console starts without a crystal list")
	TEST_ASSERT_EQUAL(console.distance, 5, "The fixture starts with a nonzero target distance")
	console.eject()
	TEST_ASSERT_EQUAL(console.distance, 0, "Ejecting an empty console resets its target distance")
	TEST_ASSERT_NULL(console.crystals, "Empty ejection preserves the lazy crystal list")
	var/obj/item/bluespace_crystal/artificial/first = allocate(/obj/item/bluespace_crystal/artificial, console)
	var/obj/item/bluespace_crystal/artificial/second = allocate(/obj/item/bluespace_crystal/artificial, console)
	TEST_ASSERT_EQUAL(rel_add(console, nameof(console.crystals), first), first, "The first crystal must be adopted")
	TEST_ASSERT_EQUAL(rel_add(console, nameof(console.crystals), second), second, "The second crystal must be adopted")
	TEST_ASSERT_EQUAL(length(console.crystals), 2, "Both real crystals must be installed")
	TEST_ASSERT_EQUAL(owner_of(first), console, "The console owns the first installed crystal")
	TEST_ASSERT_EQUAL(owner_of(second), console, "The console owns the second installed crystal")
	console.eject()
	TEST_ASSERT_EQUAL(length(console.crystals), 0, "Ejection removes every installed crystal")
	TEST_ASSERT(!QDELETED(first) && !QDELETED(second), "Ejection preserves both crystals")
	TEST_ASSERT_EQUAL(first.loc, T, "The first crystal is ejected onto the console's turf")
	TEST_ASSERT_EQUAL(second.loc, T, "The second crystal is ejected onto the console's turf")
	TEST_ASSERT_NULL(owner_of(first), "The ejected first crystal is unowned")
	TEST_ASSERT_NULL(owner_of(second), "The ejected second crystal is unowned")
