/// Shared selection definitions never become mutable generated symptoms.
/datum/unit_test/round2_viral_trait_generation/Run()
	test_driver_begin()
	exercise_generation()
	test_driver_end()

/datum/unit_test/round2_viral_trait_generation/proc/clear_archive(list/archive)
	for(var/key in archive)
		var/datum/affliction/contagion/engineered/D = archive[key]
		if(!QDELETED(D))
			qdel(D)
	archive.Cut()

/datum/unit_test/round2_viral_trait_generation/proc/adopt_generated(list/generated)
	for(var/datum/viral_trait/trait as anything in generated)
		if(istype(trait) && (!(trait.type in GLOB.viral_trait_types) || trait != dq_proto(trait.type)))
			own(trait)

/datum/unit_test/round2_viral_trait_generation/proc/exercise_generation()
	var/list/archive = list()
	set_global(nameof(GLOB.archive_diseases), archive)
	defer_cleanup(src, PROC_REF(clear_archive), archive)
	var/datum/affliction/contagion/engineered/strain = allocate(/datum/affliction/contagion/engineered, FALSE)
	var/datum/viral_trait/existing = allocate(/datum/viral_trait/sneeze)
	rel_add(strain, nameof(strain.symptoms), existing)
	for(var/severity in list(FALSE, TRUE))
		var/list/eligible = list()
		for(var/path in GLOB.viral_trait_types)
			var/datum/viral_trait/prototype = dq_proto(path)
			var/rating = severity ? prototype.threat : prototype.level
			if(rating >= 0 && rating <= 9 && !strain.HasSymptom(prototype))
				eligible += prototype
		TEST_ASSERT(length(eligible) >= 2, "actual registry supplies distinct eligible nonexisting traits")
		var/available_count = length(eligible)
		test_rng(73)
		var/datum/viral_trait/expected = pick_n_take(eligible)
		var/expected_next = rand(1, 100000)
		test_rng(73)
		var/list/generated = severity ? strain.GenerateSymptomsBySeverity(0, 9, 1) : strain.GenerateSymptoms(0, 9, 1)
		adopt_generated(generated)
		var/actual_next = rand(1, 100000)
		TEST_ASSERT_EQUAL(length(generated), 1, "actual generation returns the requested single trait")
		var/datum/viral_trait/result = generated[1]
		TEST_ASSERT(istype(result), "actual generation returns a real viral trait")
		TEST_ASSERT_EQUAL(result.type, expected.type, "registry order and seeded selection pick the exact expected type")
		TEST_ASSERT_EQUAL(actual_next, expected_next, "definition queries and fresh construction do not consume additional random draws")
		TEST_ASSERT(result != expected && result != existing, "generated state is a fresh real trait rather than a shared definition or existing symptom")
		TEST_ASSERT_EQUAL(result.id, expected.id, "fresh constructor retains the actual registry identity")
		TEST_ASSERT(!strain.HasSymptom(result), "generation excludes the original existing symptom")
		var/original_power = expected.power
		result.power = original_power + 17
		result.neutered = TRUE
		TEST_ASSERT_EQUAL(expected.power, original_power, "mutating generated state leaves the shared definition unchanged")
		TEST_ASSERT(!expected.neutered, "neutering output leaves the shared definition active")
		TEST_ASSERT_EQUAL(strain.symptoms[1], existing, "selection preserves the independent original strain symptom")
		TEST_ASSERT(!existing.neutered, "generated mutations leave the existing trait unchanged")
		if(severity)
			var/list/overrequested = strain.GenerateSymptomsBySeverity(0, 9, available_count + 2)
			adopt_generated(overrequested)
			var/list/seen = list()
			for(var/datum/viral_trait/trait as anything in overrequested)
				if(isnull(trait))
					continue
				TEST_ASSERT(istype(trait), "over-request yields only real traits or no selection")
				TEST_ASSERT(!(trait.type in seen), "over-request cannot select a trait type twice")
				TEST_ASSERT(!strain.HasSymptom(trait), "over-request excludes the original symptom")
				seen += trait.type
			TEST_ASSERT(length(seen) > 0 && length(seen) <= available_count, "over-request remains bounded by the available distinct registry types")
	var/list/no_level_match = strain.GenerateSymptoms(1, 0, 1)
	adopt_generated(no_level_match)
	TEST_ASSERT_EQUAL(length(no_level_match), 0, "impossible level range has no generated traits")
	var/list/no_severity_match = strain.GenerateSymptomsBySeverity(1, 0, 1)
	adopt_generated(no_severity_match)
	TEST_ASSERT_EQUAL(length(no_severity_match), 0, "impossible threat range has no generated traits")
