/// Native fabricated-ID clicks initialize actual identity and preserve the first registration.
/datum/unit_test/round2_changeling_id_click_actor/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/bystander = allocate(/mob/living/carbon/human, T)
	set_var(actor, nameof(actor.real_name), "Explicit Fabricated Owner")
	set_var(bystander, nameof(bystander.real_name), "Unrelated Fabricated Viewer")
	TEST_ASSERT(actor.dna && bystander.dna, "real human constructors create the identity data used by identification")
	var/obj/item/card/id/syndicate/changeling/card = allocate(/obj/item/card/id/syndicate/changeling, T)
	TEST_ASSERT_NULL(card.registered_user(), "a real floor-created fabricated ID starts unregistered")
	TEST_ASSERT_EQUAL(card.registered_name, "Unknown", "the real card constructor preserves its unregistered identity")
	TEST_ASSERT_NULL(card.front, "the unregistered fabricated ID has no photo")
	km_synthetic_click(actor, card)
	test_time(1 SECONDS)
	TEST_ASSERT_EQUAL(card.registered_user(), actor, "actual native Click registers its initiating human")
	TEST_ASSERT_EQUAL(card.registered_name, actor.real_name, "real set_id_info copies the initiating human's identity")
	TEST_ASSERT_EQUAL(card.age, actor.age, "real human identification supplies the owner's age")
	TEST_ASSERT_EQUAL(card.dna_hash, actor.dna.unique_enzymes, "real identification copies the owner's DNA hash")
	TEST_ASSERT_EQUAL(card.fingerprint_hash, md5(actor.dna.GetUniIdentity()), "real identification records the owner's fingerprint hash")
	TEST_ASSERT(card.front && findtext(card.front, "data:image/png;base64,"), "real identification generates a nonempty PNG photo")
	var/photo = card.front
	var/card_name = card.name
	km_synthetic_click(bystander, card)
	test_time(1 SECONDS)
	TEST_ASSERT_EQUAL(card.registered_user(), actor, "a subsequent native viewer cannot replace the original registration")
	TEST_ASSERT_EQUAL(card.registered_name, actor.real_name, "another viewer cannot overwrite the real owner identity")
	TEST_ASSERT_EQUAL(card.front, photo, "another viewer preserves the original actual generated photo")
	TEST_ASSERT_EQUAL(card.name, card_name, "another viewer preserves the real derived card name")
	var/obj/item/card/id/syndicate/changeling/other_card = allocate(/obj/item/card/id/syndicate/changeling, T)
	km_synthetic_click(bystander, other_card)
	test_time(1 SECONDS)
	TEST_ASSERT_EQUAL(other_card.registered_user(), bystander, "an independent real native click registers its own initiating human")
	TEST_ASSERT_EQUAL(other_card.registered_name, bystander.real_name, "independent native registration copies the actual clicker's identity")
	TEST_ASSERT(other_card.front && findtext(other_card.front, "data:image/png;base64,"), "independent native registration generates the actual owner photo")
	TEST_ASSERT_EQUAL(card.registered_user(), actor, "the independent card preserves the original card registration")
	TEST_ASSERT_EQUAL(card.front, photo, "the independent card preserves the original card photo")
	test_driver_end()
