/// Actual native explosive timer inputs never plant, arm or detonate any charge.
/datum/unit_test/round2_plastique_timer_native
	parent_type = /datum/unit_test/dq_p2_engine

/datum/unit_test/round2_plastique_timer_native/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/item/clothing/under/color/grey/uniform = allocate(/obj/item/clothing/under/color/grey, T)
	TEST_ASSERT(user.equip_to_slot_if_possible(uniform, SLOT_ID_UNIFORM, disable_warning = TRUE), "actual uniform supplies a real pocket")
	var/completed = 0
	for(var/charge_type in list(/obj/item/plastique, /obj/item/plastique/seismic, /obj/item/plastique/seismic/locked))
		var/obj/item/plastique/charge = allocate(charge_type, T)
		TEST_ASSERT(user.put_in_active_hand(charge), "actual actor holds original charge")
		test_click(user, charge, charge)
		test_time(1 SECOND)
		var/datum/prompt/number/R = SSrequests.open_for(user)
		TEST_ASSERT(istype(R), "actual native self-input opens timer request")
		TEST_ASSERT_EQUAL(R.default, 10, "actual timer request retains fixed original default")
		TEST_ASSERT_EQUAL(R.min_value, 10, "actual timer request retains original minimum seconds")
		TEST_ASSERT_EQUAL(R.max_value, 60000, "actual timer request retains original maximum seconds")
		test_answer(user, 0)
		test_time(1 SECOND)
		TEST_ASSERT_EQUAL(charge.timer, 10, "actual low native answer clamps to original minimum")
		test_click(user, charge, charge)
		test_time(1 SECOND)
		R = SSrequests.open_for(user)
		TEST_ASSERT(istype(R), "actual original charge opens another timer request")
		test_answer(user, 70000)
		test_time(1 SECOND)
		TEST_ASSERT_EQUAL(charge.timer, 60000, "actual high native answer clamps to original maximum")
		test_click(user, charge, charge)
		test_time(1 SECOND)
		TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/number), "actual held charge opens request before switching hands")
		user.swap_hand()
		TEST_ASSERT_EQUAL(user.get_inactive_hand(), charge, "original source remains in the actual inactive hand")
		test_answer(user, 37)
		test_time(1 SECOND)
		TEST_ASSERT_EQUAL(charge.timer, 37, "late answer accepts the source in either actual hand")
		user.swap_hand()
		test_click(user, charge, charge)
		test_time(1 SECOND)
		TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/number), "actual charge opens request before same-container reslot")
		TEST_ASSERT(charge.move_into(user, SLOT_ID_POCKET_L, user), "actual charge moves from hand into the actor's pocket")
		TEST_ASSERT_EQUAL(charge.loc, user, "same-container reslot preserves the original actor containment")
		test_answer(user, 42)
		test_time(1 SECOND)
		TEST_ASSERT_EQUAL(charge.timer, 37, "pocketed original source refuses a late timer answer")
		TEST_ASSERT(user.put_in_active_hand(charge), "actor retrieves the original charge from the pocket")
		test_click(user, charge, charge)
		test_time(1 SECOND)
		R = SSrequests.open_for(user)
		TEST_ASSERT(istype(R), "actual configured charge opens request before release")
		TEST_ASSERT(user.unEquip(charge), "actual actor releases source before timer answer")
		test_answer(user, 42)
		test_time(1 SECOND)
		TEST_ASSERT_EQUAL(charge.timer, 37, "released source refuses actual late timer change")
		TEST_ASSERT_NULL(charge.target_ref(), "real timer configuration never plants original charge")
		TEST_ASSERT(!QDELETED(charge), "real timer configuration never consumes original charge")
		TEST_ASSERT_EQUAL(charge.loc, T, "released original charge remains on exact fixture floor")
		completed++
	TEST_ASSERT_EQUAL(completed, 3, "all three actual explosive constructor types were configured")
