/datum/unit_test/round2_mecha_native_tank_pressure/Run()
	test_driver_begin()
	exercise_pressure()
	test_driver_end()

/datum/unit_test/round2_mecha_native_tank_pressure/proc/exercise_pressure()
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, surface)
	actor.enable_godmode()
	var/obj/mecha/working/ripley/mech = allocate(/obj/mecha/working/ripley, surface)
	mech.state = MECHA_BOLTS_SECURED
	perform_op(actor, mech, "set_internal_tank_valve", null, ORIGIN_SYSTEM)
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/number/mecha_tank_valve), "Production pressure handler opens the actual native numeric request")
	test_answer(actor, 152.75)
	test_time(0.1 SECONDS)
	TEST_ASSERT_EQUAL(mech.internal_tank_valve, 152.75, "Production callback preserves fractional pressure values")
	perform_op(actor, mech, "set_internal_tank_valve", null, ORIGIN_SYSTEM)
	test_answer(actor, 0)
	test_time(0.1 SECONDS)
	TEST_ASSERT_EQUAL(mech.internal_tank_valve, 152.75, "Zero retains the existing pressure as before")
	perform_op(actor, mech, "set_internal_tank_valve", null, ORIGIN_SYSTEM)
	test_answer(actor, null, REQ_CANCELLED)
	test_time(0.1 SECONDS)
	TEST_ASSERT_EQUAL(mech.internal_tank_valve, 152.75, "Explicit cancellation cannot alter the real valve")
	var/turf/far = locate(surface.x + 3, surface.y, surface.z)
	TEST_ASSERT(far && get_dist(surface, far) > 1, "Fixture has an actual distant turf")
	perform_op(actor, mech, "set_internal_tank_valve", null, ORIGIN_SYSTEM)
	TEST_ASSERT_NOTNULL(SSrequests.open_for(actor), "Late-distance case begins with a pending pressure request")
	actor.forceMove(far)
	test_answer(actor, 200)
	test_time(0.1 SECONDS)
	own_turf_contents(surface)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Late-distance refusal closes the request")
	TEST_ASSERT_EQUAL(mech.internal_tank_valve, 152.75, "Distant answer leaves the real pressure unchanged")
