#define FIRST_PULL_INPUT "input"
#define FIRST_PULL_OUTPUT "output"

/datum/unit_test/round2_circuit_arithmetic_first_input_pull/Run()
	test_driver_begin()
	run_case(/obj/item/integrated_circuit/arithmetic/subtraction, 10, 18)
	run_case(/obj/item/integrated_circuit/arithmetic/multiplication, 24, 40)
	run_case(/obj/item/integrated_circuit/arithmetic/division, 6, 10)
	test_driver_end()

/datum/unit_test/round2_circuit_arithmetic_first_input_pull/proc/run_case(circuit_type, expected_first, expected_second)
	var/turf/floor = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, floor)
	var/obj/item/electronic_assembly/assembly = allocate(/obj/item/electronic_assembly, floor)
	var/obj/item/tool/crowbar/crowbar = allocate(/obj/item/tool/crowbar, floor)
	TEST_ASSERT(user.put_in_active_hand(crowbar), "Real actor holds assembly opening tool")
	assembly.crowbar_act(user, crowbar)
	TEST_ASSERT(assembly.opened, "Actual crowbar handler opens the assembly for the wiring fixture")
	var/obj/item/integrated_circuit/source = allocate(/obj/item/integrated_circuit/arithmetic/addition, floor)
	var/obj/item/integrated_circuit/circuit = allocate(circuit_type, floor)
	TEST_ASSERT(assembly.add_circuit(source, user), "Actual source circuit inserts through public assembly API")
	TEST_ASSERT(assembly.add_circuit(circuit, user), "Actual arithmetic circuit inserts through public assembly API")
	var/datum/integrated_io/output_pin = source.get_pin_ref(FIRST_PULL_OUTPUT, 1)
	var/datum/integrated_io/input_pin = circuit.get_pin_ref(FIRST_PULL_INPUT, 1)
	var/obj/item/integrated_electronics/wirer/wirer = allocate(/obj/item/integrated_electronics/wirer, floor)
	wirer.wire(output_pin, user)
	wirer.wire(input_pin, user)
	TEST_ASSERT(output_pin in input_pin.linked, "Actual public wiring API establishes first operand connection")
	TEST_ASSERT(input_pin in output_pin.linked, "Actual wiring connection is symmetric")
	circuit.set_pin_data(FIRST_PULL_INPUT, 2, 2)
	source.set_pin_data(FIRST_PULL_OUTPUT, 1, 12)
	circuit.do_work()
	TEST_ASSERT_EQUAL(circuit.get_pin_data(FIRST_PULL_OUTPUT, 1), expected_first, "First computation pulls genuine source value despite initially null operand")
	source.set_pin_data(FIRST_PULL_OUTPUT, 1, 20)
	TEST_ASSERT_EQUAL(circuit.get_pin_data(FIRST_PULL_INPUT, 1), 12, "Source write alone leaves stored operand stale before the real computation pull")
	circuit.do_work()
	TEST_ASSERT_EQUAL(circuit.get_pin_data(FIRST_PULL_OUTPUT, 1), expected_second, "Repeated computation pulls changed source instead of reusing old first operand")
	if(circuit_type == /obj/item/integrated_circuit/arithmetic/division)
		circuit.set_pin_data(FIRST_PULL_INPUT, 2, 0)
		circuit.do_work()
		TEST_ASSERT_EQUAL(circuit.get_pin_data(FIRST_PULL_OUTPUT, 1), 20, "Existing zero divisor skip policy remains unchanged")

#undef FIRST_PULL_INPUT
#undef FIRST_PULL_OUTPUT
