/datum/unit_test/round2_crayon_native_drawing/Run()
	test_driver_begin()
	exercise_drawing()
	test_driver_end()

/datum/unit_test/round2_crayon_native_drawing/proc/exercise_drawing()
	var/turf/simulated/floor/surface = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, surface)
	actor.enable_godmode()
	var/obj/item/pen/crayon/crayon = allocate(/obj/item/pen/crayon, surface)
	TEST_ASSERT(actor.put_in_hands(crayon), "Actual drawer holds the original crayon")
	crayon.instant = TRUE
	var/initial_uses = crayon.uses
	var/list/original_decals = list()
	for(var/obj/effect/decal/cleanable/crayon/existing in surface)
		original_decals += existing
	crayon.afterattack(surface, actor, TRUE, "icon-x=16;icon-y=16")
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/choice/crayon_kind), "Production afterattack opens kind request")
	test_answer(actor, "letter")
	test_time(0.1 SECONDS)
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/choice/crayon_drawing), "Accepted letter opens actual drawing request")
	test_answer(actor, "a")
	test_time(0.1 SECONDS)
	own_turf_contents(surface)
	var/list/new_decals = list()
	for(var/obj/effect/decal/cleanable/crayon/drawn in surface)
		if(!(drawn in original_decals))
			new_decals += drawn
	TEST_ASSERT_EQUAL(length(new_decals), 1, "Actual completion creates exactly one new decal")
	var/obj/effect/decal/cleanable/crayon/letter = new_decals[1]
	TEST_ASSERT_EQUAL(letter.art_type, "a", "Actual decal records the selected letter")
	TEST_ASSERT_EQUAL(crayon.uses, initial_uses - 1, "Actual completion consumes exactly one use")
	TEST_ASSERT_EQUAL(crayon.loc, actor, "Original crayon remains with drawer")
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Completed chain leaves no request")
	crayon.afterattack(surface, actor, TRUE, null)
	test_answer(actor, null, REQ_CANCELLED)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Explicit close does not open second choice")
	TEST_ASSERT_EQUAL(crayon.uses, initial_uses - 1, "Closing kind request consumes no use")
	crayon.afterattack(surface, actor, TRUE, null)
	test_answer(actor, "letter")
	test_time(0.1 SECONDS)
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/choice/crayon_drawing), "Late distance case reaches second request")
	var/turf/far = locate(surface.x + 3, surface.y, surface.z)
	TEST_ASSERT(far && get_dist(surface, far) > 1, "Fixture has a genuinely distant turf")
	actor.forceMove(far)
	test_answer(actor, "b")
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Distant accepted answer is rejected without continuation")
	TEST_ASSERT_EQUAL(crayon.uses, initial_uses - 1, "Late rejection consumes no use")
	var/decal_count = 0
	for(var/obj/effect/decal/cleanable/crayon/remaining in surface)
		decal_count++
	TEST_ASSERT_EQUAL(decal_count, length(original_decals) + 1, "Cancel and distant rejection create no extra decals")
