/// Real native multitool answers change only the original circuitboard's receiver spectrum.
/datum/unit_test/round2_supply_board_native
	parent_type = /datum/unit_test/dq_p2_engine

/datum/unit_test/round2_supply_board_native/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/item/multitool/tool = allocate(/obj/item/multitool, T)
	TEST_ASSERT(user.put_in_active_hand(tool), "actual actor holds actual multitool")
	var/completed = 0
	for(var/board_type in list(/obj/item/circuitboard/supplycomp, /obj/item/circuitboard/supplycomp/control))
		var/obj/item/circuitboard/supplycomp/board = allocate(board_type, T)
		TEST_ASSERT_EQUAL(board.contraband_enabled, 0, "real ordering circuit starts standard")
		test_click(user, board, tool)
		test_time(1 SECOND)
		var/datum/prompt/choice/R = SSrequests.open_for(user)
		TEST_ASSERT(istype(R), "actual multitool input opens native spectrum request")
		TEST_ASSERT_EQUAL(R.question, "Current receiver spectrum is set to: STANDARD", "actual request reads standard source state")
		TEST_ASSERT_EQUAL(R.choices[1], "Switch to BROAD", "actual request offers original opposite spectrum")
		test_answer(user, R.choices[1])
		test_time(1 SECOND)
		TEST_ASSERT_EQUAL(board.contraband_enabled, 1, "actual native answer enables exact original board")
		test_click(user, board, tool)
		test_time(1 SECOND)
		R = SSrequests.open_for(user)
		TEST_ASSERT(istype(R), "actual configured board opens fresh request")
		TEST_ASSERT_EQUAL(R.question, "Current receiver spectrum is set to: BROAD", "fresh prompt reads actual broad source")
		TEST_ASSERT_EQUAL(R.choices[1], "Switch to STANDARD", "fresh prompt offers reverse spectrum")
		test_answer(user, "Cancel")
		test_time(1 SECOND)
		TEST_ASSERT_EQUAL(board.contraband_enabled, 1, "actual cancel button preserves enabled spectrum")
		TEST_ASSERT_NULL(SSrequests.open_for(user), "actual cancel button closes request")
		test_click(user, board, tool)
		test_time(1 SECOND)
		R = SSrequests.open_for(user)
		TEST_ASSERT(istype(R), "actual board opens next reverse request")
		test_answer(user, R.choices[1])
		test_time(1 SECOND)
		TEST_ASSERT_EQUAL(board.contraband_enabled, 0, "actual reverse answer restores standard spectrum")
		TEST_ASSERT_EQUAL(user.get_active_hand(), tool, "native configuration preserves exact original multitool hand")
		TEST_ASSERT_EQUAL(board.loc, T, "native configuration preserves exact original floor circuit")
		completed++
	TEST_ASSERT_EQUAL(completed, 2, "both real board constructors completed roundtrip")
