/datum/unit_test/round2_tele_beacon_native_warning/Run()
	test_driver_begin()
	exercise_warning()
	test_driver_end()

/datum/unit_test/round2_tele_beacon_native_warning/proc/exercise_warning()
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/actor = allocate(/mob/living/carbon/human, surface)
	actor.enable_godmode()
	var/obj/item/perfect_tele_beacon/beacon = allocate(/obj/item/perfect_tele_beacon, surface)
	TEST_ASSERT_NULL(beacon.creator, "Actual beacon has its default null creator")
	TEST_ASSERT_NULL(actor.client, "Fixture uses an actual clientless human")
	open_request(beacon, /datum/prompt/choice/tele_beacon_warning, TYPE_PROC_REF(/obj/item/perfect_tele_beacon, warning_answered), answerer = actor)
	TEST_ASSERT(istype(SSrequests.open_for(actor), /datum/prompt/choice/tele_beacon_warning), "Actual warning kind opens nearby")
	test_answer(actor, "Leave It")
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Leave It closes warning")
	TEST_ASSERT_EQUAL(beacon.loc, surface, "Leave It retains original beacon on floor")
	open_request(beacon, /datum/prompt/choice/tele_beacon_warning, TYPE_PROC_REF(/obj/item/perfect_tele_beacon, warning_answered), answerer = actor)
	test_answer(actor, null, REQ_CANCELLED)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Explicit close leaves no request")
	TEST_ASSERT_EQUAL(beacon.loc, surface, "Explicit close retains original floor beacon")
	var/turf/far = locate(surface.x + 3, surface.y, surface.z)
	TEST_ASSERT(far && get_dist(surface, far) > 1, "Fixture has genuinely distant turf")
	open_request(beacon, /datum/prompt/choice/tele_beacon_warning, TYPE_PROC_REF(/obj/item/perfect_tele_beacon, warning_answered), answerer = actor)
	TEST_ASSERT_NOTNULL(SSrequests.open_for(actor), "Late distance case starts with actual pending warning")
	actor.forceMove(far)
	test_answer(actor, "Take It")
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Distant answer closes rejected request")
	TEST_ASSERT_EQUAL(beacon.loc, surface, "Distant answer cannot pick up original beacon")
	open_request(beacon, /datum/prompt/choice/tele_beacon_warning, TYPE_PROC_REF(/obj/item/perfect_tele_beacon, warning_answered), answerer = actor)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Opening recheck prevents initial far warning")
	TEST_ASSERT_EQUAL(beacon.loc, surface, "Initial far refusal leaves original beacon")
	actor.forceMove(surface)
	open_request(beacon, /datum/prompt/choice/tele_beacon_warning, TYPE_PROC_REF(/obj/item/perfect_tele_beacon, warning_answered), answerer = actor)
	TEST_ASSERT_NOTNULL(SSrequests.open_for(actor), "Nearby accepted pickup has actual warning")
	test_answer(actor, "Take It")
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(actor), "Take It completes warning")
	TEST_ASSERT(actor.item_is_in_hands(beacon), "Production callback actually picks original beacon into a real hand")
	TEST_ASSERT_EQUAL(beacon.loc, actor, "Original beacon physically belongs to drawer after pickup")
