/// Real temperature-projectile hook and body state, without mocked protection.
/datum/unit_test/round2_temperature_projectile_bounded_delta/Run()
	var/turf/surface = test_floor()
	var/fractional_temperature = BODYTEMP_NORMAL + 0.1
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, surface)
	var/obj/item/projectile/temp/cold = allocate(/obj/item/projectile/temp, surface)
	var/obj/item/projectile/temp/hot/heat = allocate(/obj/item/projectile/temp/hot, surface)
	TEST_ASSERT_EQUAL(user.get_cold_protection(cold.target_temperature), 0, "Actual naked human has no cold protection")
	TEST_ASSERT_EQUAL(user.get_heat_protection(heat.target_temperature), 0, "Actual naked human has no heat protection")
	user.set_bodytemperature(fractional_temperature)
	cold.on_hit(user)
	TEST_ASSERT_EQUAL(user.body_temperature(), fractional_temperature - 75, "Actual freezing beam cools by its declared75K step instead of instantly setting50K")
	user.set_bodytemperature(fractional_temperature)
	heat.on_hit(user)
	TEST_ASSERT_EQUAL(user.body_temperature(), fractional_temperature + 200, "Actual heating beam heats by its declared200K step instead of instantly setting1000K")
	user.set_bodytemperature(cold.target_temperature + 20)
	cold.on_hit(user)
	TEST_ASSERT_EQUAL(user.body_temperature(), cold.target_temperature, "Real cold beam stops at its target without overshooting")
	user.set_bodytemperature(heat.target_temperature - 20)
	heat.on_hit(user)
	TEST_ASSERT_EQUAL(user.body_temperature(), heat.target_temperature, "Real hot beam stops at its target without overshooting")
	user.set_bodytemperature(1500)
	heat.on_hit(user)
	TEST_ASSERT_EQUAL(user.body_temperature(), 1425, "Actual hot beam cools an even hotter body toward its target by at most75K")
	user.set_bodytemperature(10)
	cold.on_hit(user)
	TEST_ASSERT_EQUAL(user.body_temperature(), cold.target_temperature, "Actual cold beam warms an even colder body without passing its target")
	user.set_bodytemperature(cold.target_temperature)
	cold.on_hit(user)
	TEST_ASSERT_EQUAL(user.body_temperature(), cold.target_temperature, "Matching actual target temperature remains unchanged")
	var/obj/item/clothing/suit/space/suit = allocate(/obj/item/clothing/suit/space, surface)
	TEST_ASSERT(user.equip_to_slot(suit, SLOT_ID_SUIT), "Real space suit equips through actual public inventory API")
	var/protection = user.get_cold_protection(cold.target_temperature)
	TEST_ASSERT(protection > 0 && protection < 1, "Actual suit supplies genuine partial thermal protection with uncovered head")
	user.set_bodytemperature(BODYTEMP_NORMAL)
	cold.on_hit(user)
	TEST_ASSERT(user.body_temperature() > BODYTEMP_NORMAL - 75 && user.body_temperature() <= BODYTEMP_NORMAL, "Actual clothing reduces cooling instead of multiplying absolute Kelvin and making cooling worse")
	user.add_mutation(COLD_RESISTANCE)
	TEST_ASSERT_EQUAL(user.get_cold_protection(cold.target_temperature), 1, "Real cold resistance mutation grants actual full protection")
	user.set_bodytemperature(fractional_temperature)
	cold.on_hit(user)
	TEST_ASSERT_EQUAL(user.body_temperature(), fractional_temperature, "Genuine full cold protection preserves fractional temperature rather than setting zero Kelvin or rounding")

	// Real supported admin-grantable vulnerability; no synthetic factor writes.
	var/mob/living/carbon/human/vulnerable = allocate(/mob/living/carbon/human, surface)
	TEST_ASSERT(vulnerable.apply_body_effect(/datum/body_effect/elemental_vulnerability), "Actual elemental vulnerability applies through its public API")
	TEST_ASSERT_EQUAL(vulnerable.factor(BF_COLD_EXPOSURE), 1.5, "Actual vulnerability amplifies cold exposure")
	TEST_ASSERT_EQUAL(vulnerable.factor(BF_HEAT_EXPOSURE), 1.5, "Actual vulnerability amplifies heat exposure")
	TEST_ASSERT_EQUAL(vulnerable.get_cold_protection(cold.target_temperature), -0.5, "Naked vulnerability produces genuine negative cold protection")
	TEST_ASSERT_EQUAL(vulnerable.get_heat_protection(heat.target_temperature), -0.5, "Naked vulnerability produces genuine negative heat protection")
	vulnerable.set_bodytemperature(fractional_temperature)
	cold.on_hit(vulnerable)
	TEST_ASSERT_EQUAL(vulnerable.body_temperature(), fractional_temperature - 75 * 1.5, "Vulnerability retains amplified75K cooling while far from target")
	vulnerable.set_bodytemperature(fractional_temperature)
	heat.on_hit(vulnerable)
	TEST_ASSERT_EQUAL(vulnerable.body_temperature(), fractional_temperature + 200 * 1.5, "Vulnerability retains amplified200K heating while far from target")
	vulnerable.set_bodytemperature(70)
	cold.on_hit(vulnerable)
	TEST_ASSERT_EQUAL(vulnerable.body_temperature(), 50, "Amplified cooling stops at its actual target")
	vulnerable.set_bodytemperature(980)
	heat.on_hit(vulnerable)
	TEST_ASSERT_EQUAL(vulnerable.body_temperature(), 1000, "Amplified heating stops at its actual target")
