/// Catalogue data effects only: no request, UI, permission, or SQL coverage.
/datum/unit_test/round2_library_catalogue_effect/Run()
	var/turf/surface = test_floor()
	var/obj/machinery/librarycomp/computer = allocate(/obj/machinery/librarycomp, surface)
	var/obj/machinery/libraryscanner/scanner = allocate(/obj/machinery/libraryscanner, surface)
	var/obj/item/book/first = allocate(/obj/item/book, surface)
	var/obj/item/book/second = allocate(/obj/item/book, surface)
	rel_set(computer, nameof(computer.scanner), scanner)
	rel_set(scanner, nameof(scanner.cache), first)
	TEST_ASSERT_EQUAL(computer.scanner(), scanner, "the actual computer selects the exact real scanner")
	TEST_ASSERT_EQUAL(scanner.cache(), first, "the scanner selects the exact original real book")
	computer.apply_catalogue_answer("editbook", "Unit title")
	computer.apply_catalogue_answer("editmob", "Unit recipient")
	TEST_ASSERT_EQUAL(computer.buffer_book, "Unit title", "accepted title updates the actual checkout buffer")
	TEST_ASSERT_EQUAL(computer.buffer_mob, "Unit recipient", "accepted recipient updates the actual checkout buffer")
	computer.apply_catalogue_answer("editbook", "")
	computer.apply_catalogue_answer("editmob", "")
	TEST_ASSERT_EQUAL(computer.buffer_book, "", "accepted blank overwrites the book buffer")
	TEST_ASSERT_EQUAL(computer.buffer_mob, "", "accepted blank overwrites the recipient buffer")
	computer.apply_catalogue_answer("setauthor", "First author")
	TEST_ASSERT_EQUAL(first.author, "First author", "author edit uses the actual current scanned book")
	rel_set(scanner, nameof(scanner.cache), second)
	computer.apply_catalogue_answer("setauthor", "Second author")
	TEST_ASSERT_EQUAL(second.author, "Second author", "author edit re-reads the replacement scanned book")
	TEST_ASSERT_EQUAL(first.author, "First author", "replacement edit leaves the original scanned book unchanged")
	computer.apply_catalogue_answer("setauthor", "")
	TEST_ASSERT_EQUAL(second.author, "Second author", "accepted blank author retains the current book author")
	computer.apply_catalogue_answer("setcategory", "Reference")
	TEST_ASSERT_EQUAL(computer.upload_category, "Reference", "accepted category updates the actual upload setting")
	computer.apply_catalogue_answer("setcategory", "")
	TEST_ASSERT_EQUAL(computer.upload_category, "Reference", "blank category retains the actual upload setting")
