/// Real default-radius production field retirement through the generator idle path.
/datum/unit_test/round2_shield_idle_disposal/Run()
	var/turf/T = test_floor()
	var/obj/machinery/power/shield_generator/generator = allocate(/obj/machinery/power/shield_generator, T)
	var/obj/item/paper/bystander = allocate(/obj/item/paper, T)
	TEST_ASSERT_EQUAL(generator.field_radius, 1, "real constructor keeps the bounded one-tile field radius")
	TEST_ASSERT(!generator.check_flag(MODEFLAG_HULL) && !generator.check_flag(MODEFLAG_MULTIZ), "real constructor uses the single-z square producer")
	generator.regenerate_field()
	TEST_ASSERT(length(generator.field_segments), "the actual producer supplies a field before snapshot")
	var/list/original = generator.field_segments.Copy()
	TEST_ASSERT(length(original) > 0 && length(original) <= 8, "the real producer creates a bounded nonempty square field")
	for(var/obj/effect/shield/segment as anything in original)
		TEST_ASSERT(!QDELETED(segment), "every original real segment is alive before idle")
		TEST_ASSERT(segment in generator.field_segments, "the producer retains each exact original owned segment")
		TEST_ASSERT_EQUAL(segment.gen(), generator, "each original real segment refers to its actual generator")
	generator.set_idle(TRUE)
	TEST_ASSERT_EQUAL(generator.running, SHIELD_IDLE, "the actual idle path sets the canonical idle state")
	TEST_ASSERT(!length(generator.field_segments), "idle drains the real owned field")
	for(var/obj/effect/shield/segment as anything in original)
		TEST_ASSERT(QDELETED(segment), "idle disposes each exact production field segment")
	TEST_ASSERT(!QDELETED(bystander) && bystander.loc == T, "idle preserves the independent original floor item")
	generator.set_idle(TRUE)
	TEST_ASSERT_EQUAL(generator.running, SHIELD_IDLE, "repeated idle keeps the canonical state")
	TEST_ASSERT(!length(generator.field_segments), "repeated idle creates no replacement segments")
	TEST_ASSERT(!QDELETED(bystander) && bystander.loc == T, "repeated idle preserves the same floor item")
