/// Existing constructor-bypass preference fixture; actual request/flag behavior, not real-client login or persistence.
/datum/unit_test/round2_preference_slot_dialog_busy/Run()
	test_driver_begin()
	exercise_slot_dialogs()
	test_driver_end()

/datum/unit_test/round2_preference_slot_dialog_busy/proc/exercise_slot_dialogs()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human)
	user.enable_godmode()
	var/datum/preferences/dq_test_stub/preferences = allocate(/datum/preferences/dq_test_stub)
	var/datum/json_savefile/memory = allocate(/datum/json_savefile, null)
	rel_set(preferences, nameof(preferences.savefile), memory)
	TEST_ASSERT_NULL(memory.path, "Genuine JSON savefile is memory-only")
	preferences.open_load_dialog(user)
	var/datum/prompt/choice/preferences_slot_dialog/load_request = SSrequests.open_for(user)
	TEST_ASSERT(istype(load_request), "Actual load helper opens native slot choice")
	TEST_ASSERT(preferences.selecting_slots, "Open load request sets actual busy flag")
	preferences.open_copy_dialog(user)
	TEST_ASSERT_EQUAL(SSrequests.open_for(user), load_request, "Duplicate helper opening retains original request")
	test_answer(user, null, REQ_CANCELLED)
	test_time(0.1 SECONDS)
	TEST_ASSERT(!preferences.selecting_slots, "Cancelling load clears the stranded busy flag")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Cancelled load leaves no request")
	preferences.open_copy_dialog(user)
	var/datum/prompt/choice/preferences_slot_dialog/copy_request = SSrequests.open_for(user)
	TEST_ASSERT(istype(copy_request), "Actual copy helper opens after cancelled load")
	TEST_ASSERT(preferences.selecting_slots && copy_request.copying, "Copy opening records actual busy state and copy kind")
	TEST_ASSERT(length(copy_request.choices) > 0, "Configured real character slots provide a label")
	var/selected_label = copy_request.choices[1]
	test_answer(user, selected_label)
	test_time(0.1 SECONDS)
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/choice/preferences_slot_confirmation), "Accepted actual slot label reaches override confirmation instead of rejecting its own busy flag")
	TEST_ASSERT(preferences.selecting_slots, "Copy sequence stays busy during confirmation")
	test_answer(user, null, REQ_CANCELLED)
	test_time(0.1 SECONDS)
	TEST_ASSERT(!preferences.selecting_slots, "Cancelling override confirmation clears actual busy state")
	preferences.open_copy_dialog(user)
	copy_request = SSrequests.open_for(user)
	TEST_ASSERT(istype(copy_request), "Copy can retry after confirmation cancellation")
	test_answer(user, copy_request.choices[1])
	test_time(0.1 SECONDS)
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/choice/preferences_slot_confirmation), "Retry reaches real confirmation")
	test_answer(user, "No")
	test_time(0.1 SECONDS)
	TEST_ASSERT(!preferences.selecting_slots, "Accepted No releases busy state without persistence")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Accepted No leaves no remaining request")
	TEST_ASSERT_EQUAL(length(memory.get_entry()), 0, "Cancel and No routes leave genuine memory savefile untouched")
	preferences.open_load_dialog(user)
	TEST_ASSERT(preferences.selecting_slots, "Transport failure starts with a real open busy dialog")
	test_answer(user, null, REQ_TRANSPORT_FAILED)
	test_time(0.1 SECONDS)
	TEST_ASSERT(!preferences.selecting_slots, "Actual transport-failed outcome clears busy state")
	preferences.open_load_dialog(user)
	TEST_ASSERT(preferences.selecting_slots, "Answerer deletion starts with an actual open dialog")
	qdel(user)
	test_time(1.1 SECONDS)
	TEST_ASSERT(!preferences.selecting_slots, "Real request-registry sweep clears busy state when original answerer is deleted")
