/// Actual human/grenade and dragon paths; no client, behavior stub or callback invocation.
/datum/unit_test/round2_combat_grenade_source_replacement/Run()
	test_driver_begin()
	exercise_source_replacement()
	own_turf_contents(test_floor())
	test_driver_end()

/datum/unit_test/round2_combat_grenade_source_replacement/proc/exercise_source_replacement()
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, surface)
	rel_set(user, nameof(user.ai_brain), new /datum/ai_brain(user))
	var/obj/item/grenade/original = allocate(/obj/item/grenade, surface)
	var/obj/item/grenade/replacement = allocate(/obj/item/grenade, surface)
	TEST_ASSERT(user.put_in_active_hand(original), "Real inventory equips the original behavior source")
	user.dq_use_combat_move()
	var/datum/prompt/choice/player_combat_move/question = SSrequests.open_for(user)
	TEST_ASSERT(istype(question), "Public combat verb opens its actual native move request")
	TEST_ASSERT("Throw Grenade (smart)" in question.choices, "Actual held grenade contributes the smart-throw option")
	TEST_ASSERT(user.unEquip(original, target = surface), "Actual inventory unequips the original grenade onto the floor")
	TEST_ASSERT_EQUAL(original.loc, surface, "Public drop relinquishes original grenade custody")
	TEST_ASSERT(user.put_in_active_hand(replacement), "Real inventory equips the replacement source while the request is pending")
	test_answer(user, "Throw Grenade (smart)")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Real answer retires the move request after no-target resolution")
	TEST_ASSERT_EQUAL(user.ai_brain.behavior_source(/datum/ai_behavior/throw_grenade), replacement, "Replay rebuild selects the currently held grenade, not the original")
	TEST_ASSERT_EQUAL(question.captured["late_refusal"], "No valid target turf nearby.", "Real empty perception resolves the late no-target refusal")
	TEST_ASSERT(!original.active && !replacement.active, "Neither actual grenade is primed without a real target cluster")
	TEST_ASSERT_EQUAL(user.get_active_hand(), replacement, "Refusal retains actual replacement grenade custody")
	TEST_ASSERT_NULL(user.ai_brain.active_behavior_type, "No-target refusal never starts a brain behavior")

/datum/unit_test/round2_combat_dragon_manual_target/Run()
	test_driver_begin()
	exercise_manual_target()
	own_turf_contents(test_floor())
	test_driver_end()

/datum/unit_test/round2_combat_dragon_manual_target/proc/exercise_manual_target()
	var/turf/surface = test_floor()
	var/turf/nearby = get_step(surface, EAST)
	TEST_ASSERT(istype(nearby, /turf/simulated/floor), "Manual victim has an actual adjacent floor")
	var/mob/living/simple_mob/vore/bigdragon/dragon = allocate(/mob/living/simple_mob/vore/bigdragon, surface)
	var/mob/living/carbon/human/victim = allocate(/mob/living/carbon/human, nearby)
	TEST_ASSERT(dragon.ai_brain && !dragon.nospecial && dragon.specialtoggle, "Actual dragon supplies its ready special-move brain")
	TEST_ASSERT_NULL(dragon.ai_brain.primary_threat, "Actual new dragon starts without an automatic target")
	dragon.ai_brain.add_personal(victim, DQ_DISPOSITION_HOSTILE, 0, "focused public combat selection")
	dragon.dq_use_combat_move()
	TEST_ASSERT(istype(SSrequests.open_for(dragon), /datum/prompt/choice/player_combat_move), "Actual public dragon verb opens the move selector")
	test_answer(dragon, "Tail Sweep")
	var/datum/prompt/choice/player_combat_move/question = SSrequests.open_for(dragon)
	TEST_ASSERT(istype(question) && question.step_name == "target", "No primary threat produces the actual manual target request")
	var/target_label = "[victim] ([get_dist(dragon, victim)] tiles)"
	TEST_ASSERT(target_label in question.choices, "Actual visible hostile is offered by manual targeting")
	TEST_ASSERT_EQUAL(victim.status_units(STAT_WEAKENED), 0, "Actual victim starts without tail-sweep knockdown")
	test_answer(dragon, target_label)
	TEST_ASSERT_NULL(SSrequests.open_for(dragon), "Actual target answer retires the request")
	var/datum/ai_behavior/sweep = dq_get_behavior(/datum/ai_behavior/dragon_tail_sweep)
	TEST_ASSERT(!sweep.is_off_cooldown(dragon.ai_brain, null), "Real brain lifecycle records the tail-sweep cooldown")
	test_time(0.1 SECONDS)
	TEST_ASSERT(victim.status_units(STAT_WEAKENED) > 0, "Actual delayed dragon yeet weakens the real victim")

/datum/unit_test/round2_combat_dragon_expired_disposition/Run()
	test_driver_begin()
	exercise_expired_disposition()
	own_turf_contents(test_floor())
	test_driver_end()

/datum/unit_test/round2_combat_dragon_expired_disposition/proc/exercise_expired_disposition()
	var/turf/surface = test_floor()
	var/mob/living/simple_mob/vore/bigdragon/dragon = allocate(/mob/living/simple_mob/vore/bigdragon/friendly, surface)
	var/mob/living/simple_mob/vore/bigdragon/target = allocate(/mob/living/simple_mob/vore/bigdragon/friendly, get_step(surface, EAST))
	TEST_ASSERT_EQUAL(dragon.faction, target.faction, "Actual two dragons naturally share a faction")
	TEST_ASSERT_NULL(dragon.ai_brain.primary_threat, "New dragon has no automatic primary threat")
	dragon.ai_brain.add_personal(target, DQ_DISPOSITION_HOSTILE, 0, "initial public selection")
	dragon.dq_use_combat_move()
	TEST_ASSERT(istype(SSrequests.open_for(dragon), /datum/prompt/choice/player_combat_move), "Actual dragon opens the move request")
	test_answer(dragon, "Tail Sweep")
	var/datum/prompt/choice/player_combat_move/question = SSrequests.open_for(dragon)
	var/target_label = "[target] ([get_dist(dragon, target)] tiles)"
	TEST_ASSERT(istype(question) && (target_label in question.choices), "Actual personal hostility offers the other dragon")
	dragon.ai_brain.add_personal(target, DQ_DISPOSITION_FRIENDLY, 1 SECOND, "short-lived public disposition")
	TEST_ASSERT_NOTNULL(dragon.ai_brain.grudge_value(target), "Real personal standing exists before it runs out")
	test_time(2 SECONDS)
	TEST_ASSERT_NULL(dragon.ai_brain.grudge_value(target), "The standing expired on its own when its time ran out")
	test_answer(dragon, target_label)
	TEST_ASSERT_NULL(SSrequests.open_for(dragon), "Expired personal disposition retires the original target request")
	TEST_ASSERT(dragon.ai_brain.disposition_to(target) >= DQ_DISPOSITION_FRIENDLY, "Actual faction disposition excludes the former hostile after personal expiry")
	var/datum/ai_behavior/sweep = dq_get_behavior(/datum/ai_behavior/dragon_tail_sweep)
	TEST_ASSERT(sweep.is_off_cooldown(dragon.ai_brain, null), "Refused target never starts a tail sweep")

/datum/unit_test/round2_combat_dragon_auto_supersedes_manual/Run()
	test_driver_begin()
	exercise_auto_target()
	own_turf_contents(test_floor())
	test_driver_end()

/datum/unit_test/round2_combat_dragon_auto_supersedes_manual/proc/exercise_auto_target()
	var/turf/surface = test_floor()
	var/mob/living/simple_mob/vore/bigdragon/dragon = allocate(/mob/living/simple_mob/vore/bigdragon, surface)
	var/mob/living/carbon/human/original = allocate(/mob/living/carbon/human, get_step(surface, EAST))
	dragon.ai_brain.add_personal(original, DQ_DISPOSITION_HOSTILE, 0, "initial manual candidate")
	dragon.dq_use_combat_move()
	TEST_ASSERT(istype(SSrequests.open_for(dragon), /datum/prompt/choice/player_combat_move), "Actual dragon opens its move request")
	test_answer(dragon, "Tail Sweep")
	var/datum/prompt/choice/player_combat_move/question = SSrequests.open_for(dragon)
	var/old_label = "[original] ([get_dist(dragon, original)] tiles)"
	TEST_ASSERT(istype(question) && (old_label in question.choices), "Original actual victim is offered before automatic targeting exists")
	qdel(original)
	TEST_ASSERT(QDELETED(original), "Original manual target actually disappears")
	var/mob/living/carbon/human/first = allocate(/mob/living/carbon/human, get_step(surface, EAST))
	var/mob/living/carbon/human/second = allocate(/mob/living/carbon/human, get_step(surface, NORTH))
	dragon.ai_brain.add_personal(first, DQ_DISPOSITION_HOSTILE, 0, "actual first auto candidate")
	dragon.ai_brain.add_personal(second, DQ_DISPOSITION_HOSTILE, 0, "actual second auto candidate")
	dragon.ai_brain.model.update_perception(dragon.ai_brain)
	dragon.ai_brain.give_target(first, TRUE)
	TEST_ASSERT((first in dragon.ai_brain.model.visible_hostiles) && (second in dragon.ai_brain.model.visible_hostiles), "Actual perception sees the two current hostiles")
	TEST_ASSERT_EQUAL(dragon.ai_brain.primary_threat, first, "Actual brain public target API establishes current primary threat")
	test_answer(dragon, old_label)
	TEST_ASSERT_NULL(SSrequests.open_for(dragon), "Automatic reevaluation retires the stale manual request")
	var/datum/ai_behavior/sweep = dq_get_behavior(/datum/ai_behavior/dragon_tail_sweep)
	TEST_ASSERT(!sweep.is_off_cooldown(dragon.ai_brain, null), "Actual automatic result starts tail sweep despite vanished manual target")
	test_time(0.1 SECONDS)
	TEST_ASSERT(first.status_units(STAT_WEAKENED) > 0 && second.status_units(STAT_WEAKENED) > 0, "Actual tail sweep yeets both current automatic hostiles")
