/// Native spell buttons invoke the actual spell and retain its caster through timed casting.
/datum/unit_test/round2_spell_button_actor/Run()
	test_driver_begin()
	var/turf/T = test_floor()
	var/turf/other = get_step(get_step(T, EAST), EAST)
	TEST_ASSERT(istype(other, /turf/simulated/floor) && other != T, "the fixture has two real distinct floor locations")
	var/mob/living/carbon/human/dummy/actor = allocate(/mob/living/carbon/human/dummy, T)
	var/mob/living/carbon/human/dummy/bystander = allocate(/mob/living/carbon/human/dummy, other)
	var/datum/spell/aoe_turf/conjure/forcewall/spell = allocate(/datum/spell/aoe_turf/conjure/forcewall)
	TEST_ASSERT(actor.add_spell(spell), "the real public spell-learning API creates the actual spell button")
	var/atom/movable/screen/spell/button = spell.connected_button
	TEST_ASSERT(button && button.spell() == spell, "actual spell learning links the original spell to its owned button")
	TEST_ASSERT(spell in actor.spell_list, "actual spell learning records the original spell in the caster ledger")
	TEST_ASSERT_EQUAL(spell.charge_counter, spell.charge_max, "the actual spell constructor starts ready")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(T, /obj/effect/forcefield)), 0, "the actual caster floor starts without a forcewall")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(other, /obj/effect/forcefield)), 0, "the actual bystander floor starts without a forcewall")
	km_synthetic_click(actor, button)
	test_time(1 SECONDS)
	own_turf_contents(T)
	var/list/walls = turf_contents_of_type(T, /obj/effect/forcefield)
	TEST_ASSERT_EQUAL(length(walls), 1, "native casting creates exactly one actual forcewall at the initiating caster")
	var/obj/effect/forcefield/wall = walls[1]
	TEST_ASSERT(wall.density && wall.anchored, "the actual spell creates the canonical anchored dense forcefield")
	TEST_ASSERT_EQUAL(spell.holder(), actor, "actual perform and its timed cast preserve the initiating caster")
	TEST_ASSERT(spell.charge_counter < spell.charge_max, "real native casting spends charge and starts actual recharge")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(other, /obj/effect/forcefield)), 0, "casting leaves the unrelated human's floor unchanged")
	TEST_ASSERT_EQUAL(spell.connected_button, button, "real casting preserves the actual owned button identity")
	km_synthetic_click(actor, button)
	test_time(1 SECONDS)
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(T, /obj/effect/forcefield)), 1, "a real cooldown refusal cannot duplicate the existing forcewall")
	walls = turf_contents_of_type(T, /obj/effect/forcefield)
	TEST_ASSERT_EQUAL(walls[1], wall, "cooldown refusal preserves the original real forcefield")
	TEST_ASSERT_EQUAL(button.icon_state, "wiz_spell_base", "actual refused click redraws the recharging spell button")
	var/datum/spell/aoe_turf/conjure/forcewall/other_spell = allocate(/datum/spell/aoe_turf/conjure/forcewall)
	TEST_ASSERT(bystander.add_spell(other_spell), "the independent real human learns its own spell")
	var/atom/movable/screen/spell/other_button = other_spell.connected_button
	TEST_ASSERT(other_button && other_button != button, "independent real learning creates a distinct actual button")
	km_synthetic_click(bystander, other_button)
	test_time(1 SECONDS)
	own_turf_contents(other)
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(other, /obj/effect/forcefield)), 1, "the independent native click casts its real forcewall on its own floor")
	TEST_ASSERT_EQUAL(other_spell.holder(), bystander, "the independent timed cast retains its own actual initiating human")
	TEST_ASSERT_EQUAL(spell.holder(), actor, "independent casting preserves the original actual caster relation")
	TEST_ASSERT_EQUAL(length(turf_contents_of_type(T, /obj/effect/forcefield)), 1, "independent casting leaves the original forcewall unchanged")
	test_driver_end()
