/// The real holder refusal must not allocate a discarded disguise inside its projector.
/datum/unit_test/round2_chameleon_holder_allocation/Run()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/obj/item/chameleon/projector = allocate(/obj/item/chameleon, T)
	var/obj/item/chameleon/control = allocate(/obj/item/chameleon, T)
	TEST_ASSERT(user.put_in_active_hand(projector), "actual projector occupies the initiating human's hand")
	var/obj/item/holder/holder = allocate(/obj/item/holder, T, user)
	TEST_ASSERT_EQUAL(user.loc, holder, "real holder constructor contains the original human")
	TEST_ASSERT_EQUAL(holder.held_mob, user, "real holder tracks that exact human")
	TEST_ASSERT_EQUAL(projector.saved_item, /obj/item/trash/cigbutt, "actual default disguise is a concrete item constructor")
	TEST_ASSERT(!length(projector.contents), "projector starts without copied disguise objects")
	projector.toggle(user)
	TEST_ASSERT(!length(projector.contents), "holder refusal allocates no leaked disguise inside the actual projector")
	TEST_ASSERT(!projector.active_dummy, "holder refusal creates no active disguise")
	TEST_ASSERT_EQUAL(user.loc, holder, "refusal preserves the original holder custody")
	TEST_ASSERT_EQUAL(projector.loc, user, "refusal preserves the original held projector")
	projector.toggle(user)
	TEST_ASSERT(!length(projector.contents), "repeated refusal accumulates no copied items")
	TEST_ASSERT(!control.active_dummy && !length(control.contents), "independent original projector remains untouched")
