/// Public cracker attack and real held-item/prize state; no connected-UI claim.
/datum/unit_test/round2_cracker_pull_request/Run()
	test_driver_begin()
	exercise_pull()
	own_turf_contents(test_floor())
	test_driver_end()

/datum/unit_test/round2_cracker_pull_request/proc/exercise_pull()
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/giver = allocate(/mob/living/carbon/human, surface)
	var/mob/living/carbon/human/recipient = allocate(/mob/living/carbon/human, surface)
	giver.enable_godmode()
	recipient.enable_godmode()
	var/giver_size = giver.size_multiplier
	var/recipient_size = recipient.size_multiplier
	TEST_ASSERT_EQUAL(giver_size, 1, "Actual giver starts at ordinary size")
	TEST_ASSERT_EQUAL(recipient_size, 1, "Actual recipient starts at ordinary size")
	TEST_ASSERT(giver.resizable, "Actual giver allows the growing prize's normal resize")
	TEST_ASSERT(!has_trait(giver, TRAIT_UNLUCKY) && !has_trait(recipient, TRAIT_UNLUCKY), "Actual participants have no random unlucky winner reversal")
	var/obj/item/cracker/growing/offered = allocate(/obj/item/cracker/growing, surface)
	offered.rigged = 1
	TEST_ASSERT(giver.put_in_active_hand(offered), "Actual inventory entry equips the cracker")
	TEST_ASSERT_EQUAL(giver.get_active_hand(), offered, "Actual active-hand slot contains the exact cracker")
	TEST_ASSERT_EQUAL(offered.attack(recipient, giver, BP_TORSO, 1), ITEM_INTERACT_SUCCESS, "Public attack opens the initial offer")
	var/datum/prompt/choice/cracker_pull/question = SSrequests.open_for(recipient)
	TEST_ASSERT(istype(question), "Public attack opens a native cracker question")
	TEST_ASSERT_EQUAL(question.owner, offered, "The exact cracker owns the offer")
	TEST_ASSERT_EQUAL(question.answerer, recipient, "The original recipient answers")
	TEST_ASSERT_EQUAL(question.subject, giver, "The original giver is preserved")
	test_answer(recipient, "No")
	TEST_ASSERT_NULL(SSrequests.open_for(recipient), "No retires the actual request")
	TEST_ASSERT(!QDELETED(offered), "No retains the exact cracker")
	TEST_ASSERT_EQUAL(giver.get_active_hand(), offered, "No retains actual held custody")
	TEST_ASSERT_EQUAL(giver.size_multiplier, giver_size, "No applies no giver prize")
	TEST_ASSERT_EQUAL(recipient.size_multiplier, recipient_size, "No applies no recipient prize")
	offered.attack(recipient, giver, BP_TORSO, 1)
	TEST_ASSERT(istype(SSrequests.open_for(recipient), /datum/prompt/choice/cracker_pull), "A second public attack opens another real offer")
	test_answer(recipient, null, REQ_CANCELLED)
	TEST_ASSERT_NULL(SSrequests.open_for(recipient), "Explicit close retires the actual request")
	TEST_ASSERT(!QDELETED(offered), "Explicit close retains the cracker")
	TEST_ASSERT_EQUAL(giver.get_active_hand(), offered, "Closing preserves actual held custody")
	offered.attack(recipient, giver, BP_TORSO, 1)
	question = SSrequests.open_for(recipient)
	TEST_ASSERT(istype(question), "A third public attack opens the late-held-check offer")
	TEST_ASSERT(giver.unEquip(offered, target = surface), "Public unequip removes the exact held cracker")
	TEST_ASSERT_EQUAL(offered.loc, surface, "Public drop moves the cracker onto the actual floor")
	TEST_ASSERT(giver.get_active_hand() != offered, "The exact cracker has left the active-hand slot")
	test_answer(recipient, "Yes")
	TEST_ASSERT_NULL(SSrequests.open_for(recipient), "Late held refusal closes the actual offer")
	TEST_ASSERT_EQUAL(question.last_error, "cracker not held", "The real native held requirement refuses the dropped cracker")
	TEST_ASSERT(!QDELETED(offered), "Late refusal preserves the exact dropped cracker")
	TEST_ASSERT_EQUAL(offered.loc, surface, "Late refusal leaves actual floor custody unchanged")
	TEST_ASSERT_EQUAL(giver.size_multiplier, giver_size, "Late refusal applies no giver prize")
	TEST_ASSERT_EQUAL(recipient.size_multiplier, recipient_size, "Late refusal applies no recipient prize")
	TEST_ASSERT(giver.put_in_active_hand(offered), "Public inventory entry reequips the same cracker")
	TEST_ASSERT_EQUAL(giver.get_active_hand(), offered, "Accepted case begins with the real held precondition")
	offered.attack(recipient, giver, BP_TORSO, 1)
	TEST_ASSERT(istype(SSrequests.open_for(recipient), /datum/prompt/choice/cracker_pull), "Final public attack opens a real accepted offer")
	test_answer(recipient, "Yes")
	TEST_ASSERT_NULL(SSrequests.open_for(recipient), "Yes retires the actual accepted request")
	TEST_ASSERT_EQUAL(giver.size_multiplier, 2, "The rigged actual growing prize changes the giver size")
	TEST_ASSERT_EQUAL(recipient.size_multiplier, recipient_size, "The losing recipient retains actual original size")
	TEST_ASSERT(QDELETED(offered), "The successful actual prize consumes the exact cracker")
	TEST_ASSERT(giver.get_active_hand() != offered, "Consumed cracker leaves the real active-hand slot")
