/// Real native card/tool/emag inputs configure only the original eligible board.
/datum/unit_test/round2_camera_board_native
	parent_type = /datum/unit_test/dq_p2_engine

/datum/unit_test/round2_camera_board_native/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/locker = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	locker.enable_godmode()
	var/obj/item/circuitboard/security/board = allocate(/obj/item/circuitboard/security, T)
	var/list/original = board.network.Copy()
	var/obj/item/card/id/blank = allocate(/obj/item/card/id, T)
	var/obj/item/card/id/gold/captain/spare/card = allocate(/obj/item/card/id/gold/captain/spare, T)
	TEST_ASSERT(!board.check_access(blank), "actual blank ID lacks the board's required access")
	TEST_ASSERT(board.check_access(card), "actual canonical spare ID grants board access")
	TEST_ASSERT(board.locked && !board.emagged, "actual board starts locked and unsubverted")
	TEST_ASSERT(user.put_in_active_hand(blank), "actor holds actual blank ID")
	test_click(user, board, blank)
	TEST_ASSERT(board.locked, "actual denied card cannot unlock board")
	TEST_ASSERT(user.unEquip(blank), "actor releases actual denied card")
	TEST_ASSERT(locker.put_in_active_hand(card), "other actor holds actual authorized ID")
	test_click(locker, board, card)
	TEST_ASSERT(!board.locked, "actual authorized card unlocks board")
	var/obj/item/multitool/tool = allocate(/obj/item/multitool, T)
	TEST_ASSERT(user.put_in_active_hand(tool), "configuring actor holds actual multitool")
	test_time(1 SECOND)
	test_click(user, board, tool)
	test_time(1 SECOND)
	var/datum/prompt/text/question = SSrequests.open_for(user)
	TEST_ASSERT(istype(question), "actual native multitool input opens text request")
	test_click(locker, board, card)
	TEST_ASSERT(board.locked, "other actual card input relocks board during request")
	test_answer(user, "Round2Ignored")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(jointext(board.network, ","), jointext(original, ","), "answered request rechecks lock and preserves exact original networks")
	test_click(locker, board, card)
	TEST_ASSERT(!board.locked, "actual authorized card unlocks again")
	test_time(1 SECOND)
	test_click(user, board, tool)
	test_time(1 SECOND)
	question = SSrequests.open_for(user)
	TEST_ASSERT(istype(question), "unlocked board offers real fresh configuration")
	test_answer(user, "Round2Camera,Secret")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(length(board.network), 1, "actual answer removes restricted network")
	TEST_ASSERT_EQUAL(board.network[1], "Round2Camera", "actual answer stores exact permitted network")
	TEST_ASSERT(user.unEquip(tool), "actor releases real multitool")
	var/obj/item/card/emag/emag = allocate(/obj/item/card/emag, T)
	TEST_ASSERT(user.put_in_active_hand(emag), "actor holds actual charged emag")
	var/uses_before = emag.uses
	test_time(1 SECOND)
	test_click(user, board, emag)
	TEST_ASSERT(board.emagged && !board.locked, "native emag leaves actual circuit lock removed and controls open")
	TEST_ASSERT_EQUAL(emag.uses, uses_before - 1, "successful native subversion consumes exactly one real charge")
	test_time(1 SECOND)
	test_click(locker, board, card)
	TEST_ASSERT(!board.locked, "actual ID cannot relock an emagged board")
	test_time(1 SECOND)
	test_click(user, board, emag)
	TEST_ASSERT_EQUAL(emag.uses, uses_before - 1, "repeat native subversion refusal preserves charge")
	TEST_ASSERT_EQUAL(board.network[1], "Round2Camera", "lock and emag inputs preserve configured network")
