/// Toy suicide consumes charge but must retire the real unused laser-tag beam.
/datum/unit_test/round2_lasertag_suicide_projectile_cleanup/Run()
	test_driver_begin()
	exercise_toy()
	test_driver_end()

/datum/unit_test/round2_lasertag_suicide_projectile_cleanup/proc/exercise_toy()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode() // the test block has no air: without it the user passes out mid-wait and the op's ALIVE keep stops the second attempt
	var/obj/item/gun/energy/lasertag/toy = allocate(/obj/item/gun/energy/lasertag, T)
	var/obj/item/gun/energy/lasertag/control = allocate(/obj/item/gun/energy/lasertag, T)
	TEST_ASSERT(user.put_in_active_hand(toy), "actual laser-tag gun occupies the initiating human hand")
	var/obj/item/cell/toy_cell = toy.get_cell()
	var/obj/item/cell/control_cell = control.get_cell()
	TEST_ASSERT(toy_cell && control_cell, "actual constructors provide distinct charged cells")
	TEST_ASSERT(toy_cell != control_cell, "independent real guns have distinct original cells")
	own(toy_cell)
	own(control_cell)
	var/initial_charge = toy_cell.charge
	TEST_ASSERT_EQUAL(initial_charge, control_cell.charge, "both real guns begin with equal charge")
	for(var/i in 1 to 2)
		var/obj/item/projectile/expected = control.consume_next_projectile(user)
		if(expected)
			own(expected)
		TEST_ASSERT(istype(expected, /obj/item/projectile/beam/lasertag/omni), "actual independent production consumer constructs the original concrete beam")
		TEST_ASSERT(!QDELETED(expected) && expected.loc == control, "independent real projectile remains alive inside its original gun")
		toy.handle_suicide(user)
		test_time(5 SECONDS)
		for(var/obj/item/projectile/leaked in toy.contents)
			TEST_ASSERT(QDELETED(leaked), "toy refusal leaves no live consumed projectile inside its actual gun")
		TEST_ASSERT_EQUAL(toy_cell.charge, control_cell.charge, "toy path retains the exact original production charge use")
		TEST_ASSERT(!QDELETED(expected) && expected.loc == control, "toy cleanup preserves the independent original beam")
		TEST_ASSERT_EQUAL(toy.mouthshoot, 0, "toy path clears its original suicide state")
		TEST_ASSERT_EQUAL(user.stat, CONSCIOUS, "toy path never enters the harmful projectile branch")
		TEST_ASSERT_EQUAL(toy.loc, user, "toy cleanup preserves the original held gun")
	TEST_ASSERT(toy_cell.charge < initial_charge, "two actual toy attempts consume real cell charge")
