/datum/unit_test/round2_flashlight_flicker_timing/Run()
	test_driver_begin()
	exercise_flicker()
	test_driver_end()

/datum/unit_test/round2_flashlight_flicker_timing/proc/exercise_flicker()
	var/turf/surface = test_floor()
	var/obj/item/flashlight/light = allocate(/obj/item/flashlight, surface)
	TEST_ASSERT_NOTNULL(light.overlay_light, "Real flashlight initializes its directional lighting")
	TEST_ASSERT(!light.on, "Real flashlight starts off")
	light.set_power_use(FALSE)
	light.flicker(amount = 2, forced = TRUE)
	TEST_ASSERT(light.on && light.flickering, "Production flicker turns actual flashlight on and starts its cycle")
	test_time(0.4 SECONDS)
	TEST_ASSERT(light.on && light.flickering, "Randomized continuation cannot run before its half-second minimum")
	test_time(1.2 SECONDS)
	own_turf_contents(surface)
	TEST_ASSERT(!light.on, "Continuation restores the original off state within its one-and-a-half-second maximum")
	TEST_ASSERT(!light.flickering, "Production continuation finishes the actual flicker cycle")
