/// Actual owned base soul-link teardown and independent borrowed-view isolation.
/datum/unit_test/round2_owned_soul_link_retirement/Run()
	test_driver_begin()
	exercise_links()
	test_driver_end()

/datum/unit_test/round2_owned_soul_link_retirement/proc/exercise_links()
	var/turf/T = test_floor()
	var/mob/living/carbon/human/owner = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/sharer = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/control_owner = allocate(/mob/living/carbon/human, T)
	var/mob/living/carbon/human/control_sharer = allocate(/mob/living/carbon/human, T)
	var/datum/soul_link/link = allocate(/datum/soul_link)
	var/datum/soul_link/control = allocate(/datum/soul_link)
	TEST_ASSERT(link.parse_args(owner, sharer), "actual producer accepts the first real owner/sharer pair")
	TEST_ASSERT(control.parse_args(control_owner, control_sharer), "actual producer accepts the independent real pair")
	TEST_ASSERT(link != control, "the actual pairs have distinct original link identities")
	TEST_ASSERT_EQUAL(owner_of(link), owner, "actual producer adopts the exact first link into its real owner")
	TEST_ASSERT(link in owner.owned_soul_links, "the exact first link is in its declared owned collection")
	TEST_ASSERT(link in sharer.shared_soul_links, "actual producer registers the exact first borrowed sharer view")
	TEST_ASSERT_EQUAL(owner_of(control), control_owner, "independent link has its own actual owner")
	TEST_ASSERT(control in control_owner.owned_soul_links && control in control_sharer.shared_soul_links, "independent producer establishes both exact memberships")
	qdel(owner)
	TEST_ASSERT(QDELETED(owner) && QDELETED(link), "real owner deletion retires the exact original owned link")
	TEST_ASSERT(!QDELETED(sharer), "base link teardown preserves the actual borrowed sharer")
	TEST_ASSERT(!(link in sharer.shared_soul_links), "deleted link is pruned from the surviving sharer borrowed view")
	TEST_ASSERT(!QDELETED(control_owner) && !QDELETED(control_sharer) && !QDELETED(control), "owner teardown preserves all independent original identities")
	TEST_ASSERT_EQUAL(owner_of(control), control_owner, "independent exact ownership survives unrelated teardown")
	TEST_ASSERT(control in control_owner.owned_soul_links && control in control_sharer.shared_soul_links, "independent owned and borrowed memberships remain intact")
