/// Real ghosttrap naming entry and native answer delivery; no transfer/login/UI presentation coverage.
/datum/unit_test/round2_ghosttrap_native_name/Run()
	test_driver_begin()
	exercise_naming()
	test_driver_end()

/datum/unit_test/round2_ghosttrap_native_name/proc/exercise_naming()
	var/datum/ghosttrap/trap = allocate(/datum/ghosttrap)
	var/turf/surface = test_floor()
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, surface)
	var/mob/living/carbon/human/control = allocate(/mob/living/carbon/human, surface)
	user.enable_godmode()
	control.enable_godmode()
	var/control_name = control.name
	var/control_real_name = control.real_name
	trap.set_new_name(user)
	var/datum/prompt/text/ghosttrap_name/request = SSrequests.open_for(user)
	TEST_ASSERT(istype(request), "Actual public ghosttrap naming opens its native request")
	TEST_ASSERT_EQUAL(request.owner, trap, "Naming retains the original ordinary trap")
	TEST_ASSERT_EQUAL(request.answerer, user, "Naming retains the original target mob")
	test_answer(user, "Native Ghost")
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Accepted name closes the actual request")
	TEST_ASSERT_EQUAL(user.real_name, "Native Ghost", "Production sanitizer and callback set the target's real name")
	TEST_ASSERT_EQUAL(user.name, "Native Ghost", "Production callback copies the actual new real name")
	TEST_ASSERT_EQUAL(control.name, control_name, "Independent human display name remains untouched")
	TEST_ASSERT_EQUAL(control.real_name, control_real_name, "Independent human real name remains untouched")
	trap.set_new_name(user)
	TEST_ASSERT(istype(SSrequests.open_for(user), /datum/prompt/text/ghosttrap_name), "A second public naming entry genuinely opens")
	test_answer(user, null, REQ_CANCELLED)
	test_time(0.1 SECONDS)
	TEST_ASSERT_NULL(SSrequests.open_for(user), "Explicit cancellation closes the actual naming request")
	TEST_ASSERT_EQUAL(user.real_name, "Native Ghost", "Cancellation retains the accepted real name")
	TEST_ASSERT_EQUAL(user.name, "Native Ghost", "Cancellation retains the accepted display name")
	TEST_ASSERT_EQUAL(control.name, control_name, "Cancellation leaves the independent human untouched")
	TEST_ASSERT_EQUAL(control.real_name, control_real_name, "Cancellation leaves the independent real name untouched")
