/// Real multi-step customization changes only the original carried decorative card.
/datum/unit_test/round2_decorative_card_native
	parent_type = /datum/unit_test/dq_p2_engine

/datum/unit_test/round2_decorative_card_native/run_gate()
	var/turf/T = run_loc_floor_bottom_left
	var/mob/living/carbon/human/user = allocate(/mob/living/carbon/human, T)
	user.enable_godmode()
	var/obj/item/card_fluff/card = allocate(/obj/item/card_fluff, T)
	TEST_ASSERT(user.put_in_active_hand(card), "actual actor holds exact original decorative card")
	TEST_ASSERT_EQUAL(length(card.sprite_stack), 1, "original card begins with its one empty base layer")
	TEST_ASSERT_EQUAL(card.sprite_stack[1], "", "original card base layer is empty")
	test_click(user, card, card)
	test_time(1 SECOND)
	var/datum/prompt/choice/R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "native self-input opens actual customization request")
	TEST_ASSERT_EQUAL(R.title, "Customize Card", "native request retains original customization title")
	test_answer(user, "Band")
	test_time(1 SECOND)
	R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "actual Band answer opens the color request")
	TEST_ASSERT_EQUAL(R.title, "Band colour", "actual Band answer selects only the color branch")
	TEST_ASSERT_EQUAL(length(card.sprite_stack), 1, "first-stage answer does not add a layer")
	test_answer(user, "dark green")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(length(card.sprite_stack), 2, "actual color answer appends one layer")
	TEST_ASSERT_EQUAL(card.sprite_stack[2], "bar-darkgreen", "actual color answer maps to original dark-green icon state")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "completed Band workflow skips Stamp request")
	test_click(user, card, card)
	test_time(1 SECOND)
	R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "original configured card opens fresh customization request")
	test_answer(user, "Stamp")
	test_time(1 SECOND)
	R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "actual Stamp answer opens image request")
	TEST_ASSERT_EQUAL(R.title, "Stamp image", "actual Stamp answer skips Band request")
	test_answer(user, "big ears")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(length(card.sprite_stack), 3, "actual image answer appends exactly one stamp")
	TEST_ASSERT_EQUAL(card.sprite_stack[2], "bar-darkgreen", "actual stamp retains prior band")
	TEST_ASSERT_EQUAL(card.sprite_stack[3], "stamp-bigears", "actual stamp maps to original big-ears icon state")
	test_click(user, card, card)
	test_time(1 SECOND)
	R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "actual card opens customization before cancellation")
	test_answer(user, "Band")
	test_time(1 SECOND)
	R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "actual second-stage Band request exists before cancellation")
	test_answer(user, null, REQ_CANCELLED)
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(length(card.sprite_stack), 3, "second-stage cancellation preserves all actual layers")
	TEST_ASSERT_EQUAL(card.sprite_stack[3], "stamp-bigears", "cancellation preserves exact last actual stamp")
	test_click(user, card, card)
	test_time(1 SECOND)
	R = SSrequests.open_for(user)
	TEST_ASSERT(istype(R), "actual card opens reset selection")
	test_answer(user, "Reset")
	test_time(1 SECOND)
	TEST_ASSERT_EQUAL(length(card.sprite_stack), 1, "real reset removes both added layers")
	TEST_ASSERT_EQUAL(card.sprite_stack[1], "", "real reset restores exact empty base layer")
	TEST_ASSERT_NULL(SSrequests.open_for(user), "reset opens no follow-up request")
	TEST_ASSERT_EQUAL(user.get_active_hand(), card, "all workflows retain the original actor's exact card")
	TEST_ASSERT_EQUAL(card.loc, user, "all workflows retain the real card carrier")
