#define FLIGHT_CAP_STRATEGIC (1<<0)
#define FLIGHT_CAP_DOCK (1<<1)
#define FLIGHT_CAP_LAND (1<<2)
#define FLIGHT_CAP_EXPEDITION (1<<3)

#define FLIGHT_DEST_SYSTEM "system"
#define FLIGHT_DEST_ORBIT "orbit"
#define FLIGHT_DEST_STATION "station"
#define FLIGHT_DEST_VESSEL "vessel"
#define FLIGHT_DEST_SURFACE "surface"
#define FLIGHT_DEST_EXPEDITION "expedition"

#define FLIGHT_PLAN_DRAFT 1
#define FLIGHT_PLAN_PREPARING 2
#define FLIGHT_PLAN_UNDOCKING 3
#define FLIGHT_PLAN_TRANSIT 4
#define FLIGHT_PLAN_HOLDING 5
#define FLIGHT_PLAN_APPROACH 6
#define FLIGHT_PLAN_ARRIVING 7
#define FLIGHT_PLAN_ARRIVED 8
#define FLIGHT_PLAN_ABORTING 9
#define FLIGHT_PLAN_FAILED 10

#define FLIGHT_GENERATION_NONE 0
#define FLIGHT_GENERATION_QUEUED 1
#define FLIGHT_GENERATION_RUNNING 2
#define FLIGHT_GENERATION_READY 3
#define FLIGHT_GENERATION_FAILED 4

#define FLIGHT_DEFAULT_TRANSIT_TIME (30 SECONDS)
